import { PrismaClient as PrismaClientHostinger } from '@prisma/client';

const prisma = new PrismaClientHostinger({
  datasources: { db: { url: process.env.DATABASE_URL } }
});

const descriptions = [
  {
    minifigure_no: 'sw1251',
    description_en: "The Imperial TIE Bomber Pilot with light nougat head operates the Empire's heavy assault starfighters. These specialized pilots deliver ordnance against capital ships and ground targets. The distinctive helmet design identifies bomber crews within Imperial naval aviation. Essential for collectors building TIE Bomber vehicle crews and Imperial starfighter pilot rosters.",
    description_de: "Der imperiale TIE-Bomber-Pilot mit hellbraunem Kopf bedient die schweren Angriffssternenjäger des Imperiums. Diese spezialisierten Piloten liefern Munition gegen Hauptschiffe und Bodenziele. Das markante Helmdesign identifiziert Bomber-Besatzungen innerhalb der imperialen Marinefliegerei. Unverzichtbar für Sammler, die TIE-Bomber-Fahrzeugbesatzungen und imperiale Sternenjägerpiloten-Rosters bauen.",
    description_fr: "Le pilote de bombardier TIE impérial avec tête nougat clair opère les chasseurs stellaires d'assaut lourds de l'Empire. Ces pilotes spécialisés délivrent des munitions contre les vaisseaux capitaux et les cibles terrestres. Le design de casque distinctif identifie les équipages de bombardiers au sein de l'aviation navale impériale. Essentiel pour les collectionneurs construisant des équipages de véhicules bombardiers TIE et des listes de pilotes de chasseurs stellaires impériaux.",
    description_es: "El Piloto de Bombardero TIE Imperial con cabeza tono claro opera los cazas estelares de asalto pesado del Imperio. Estos pilotos especializados entregan municiones contra naves capitales y objetivos terrestres. El diseño de casco distintivo identifica tripulaciones de bombarderos dentro de la aviación naval imperial. Esencial para coleccionistas construyendo tripulaciones de vehículos Bombardero TIE y listas de pilotos de cazas estelares imperiales."
  },
  {
    minifigure_no: 'sw1252',
    description_en: "This Gonk Droid in light bluish gray with Imperial logo serves the Empire's logistics operations. The Imperial branding distinguishes it from civilian power droids. These utilitarian droids provide essential power for military installations. Perfect for collectors building Imperial base displays and showing the Empire's requisitioned civilian technology.",
    description_de: "Dieser Gonk-Droide in hellblaugrau mit Imperial-Logo dient den Logistikoperationen des Imperiums. Das imperiale Branding unterscheidet ihn von zivilen Energiedroiden. Diese utilitaristische Droiden bieten wesentliche Energie für militärische Installationen. Perfekt für Sammler, die imperiale Basis-Ausstellungen bauen und die requisitionierte zivile Technologie des Imperiums zeigen.",
    description_fr: "Ce droïde Gonk en gris bleuâtre clair avec logo impérial sert les opérations logistiques de l'Empire. La marque impériale le distingue des droïdes d'alimentation civils. Ces droïdes utilitaires fournissent une alimentation essentielle pour les installations militaires. Parfait pour les collectionneurs construisant des présentoirs de base impériale et montrant la technologie civile réquisitionnée de l'Empire.",
    description_es: "Este Droide Gonk en gris azulado claro con logo imperial sirve las operaciones logísticas del Imperio. La marca imperial lo distingue de droides de energía civiles. Estos droides utilitarios proporcionan energía esencial para instalaciones militares. Perfecto para coleccionistas construyendo exhibiciones de base imperial y mostrando la tecnología civil requisada del Imperio."
  },
  {
    minifigure_no: 'sw1253',
    description_en: "Chewbacca in dark brown with medium nougat face fur and dark tan leg fur captures the Wookiee's distinctive two-tone appearance. The detailed fur printing creates visual depth and realism. This color variation represents one of LEGO's most accurate Chewbacca designs. Highly valued by collectors seeking screen-accurate Original Trilogy character representations.",
    description_de: "Chewbacca in Dunkelbraun mit mittelbraunem Gesichtsfell und dunkelbraunem Beinfell fängt das markante zweifarbige Aussehen des Wookiees ein. Die detaillierte Fellbedruckung schafft visuelle Tiefe und Realismus. Diese Farbvariation repräsentiert eines von LEGOs genauesten Chewbacca-Designs. Sehr geschätzt von Sammlern, die bildschirmgenaue Original-Trilogie-Charakterdarstellungen suchen.",
    description_fr: "Chewbacca en brun foncé avec fourrure de visage nougat moyen et fourrure de jambe brun foncé capture l'apparence bicolore distinctive du Wookiee. L'impression de fourrure détaillée crée une profondeur visuelle et un réalisme. Cette variation de couleur représente l'un des designs Chewbacca les plus précis de LEGO. Très valorisé par les collectionneurs recherchant des représentations de personnages de la trilogie originale fidèles à l'écran.",
    description_es: "Chewbacca en marrón oscuro con pelaje facial tono medio y pelaje de piernas marrón oscuro captura la distintiva apariencia de dos tonos del Wookiee. La impresión detallada de pelaje crea profundidad visual y realismo. Esta variación de color representa uno de los diseños de Chewbacca más precisos de LEGO. Muy valorado por coleccionistas buscando representaciones de personajes de Trilogía Original fieles a pantalla."
  },
  {
    minifigure_no: 'sw1254',
    description_en: "Old Obi-Wan Kenobi with tattered cape from the LEGO Watch set captures the weathered Jedi hermit on Tatooine. The worn cape reflects years of desert exile watching over Luke. This exclusive variant from the watch promotion adds collectibility. Essential for collectors of rare Obi-Wan variants and promotional LEGO releases.",
    description_de: "Der alte Obi-Wan Kenobi mit zerrissenem Umhang aus dem LEGO-Uhren-Set fängt den verwitterten Jedi-Einsiedler auf Tatooine ein. Der abgenutzte Umhang spiegelt Jahre des Wüstenexils beim Wachen über Luke wider. Diese exklusive Variante aus der Uhren-Promotion fügt Sammelwürdigkeit hinzu. Unverzichtbar für Sammler seltener Obi-Wan-Varianten und LEGO-Werbeaktionen.",
    description_fr: "Le vieux Obi-Wan Kenobi avec cape en lambeaux de l'ensemble de montre LEGO capture l'ermite Jedi altéré sur Tatooine. La cape usée reflète des années d'exil dans le désert veillant sur Luke. Cette variante exclusive de la promotion de montre ajoute de la collectibilité. Essentielle pour les collectionneurs de variantes Obi-Wan rares et de versions LEGO promotionnelles.",
    description_es: "El viejo Obi-Wan Kenobi con capa andrajosa del set de Reloj LEGO captura al ermitaño Jedi desgastado en Tatooine. La capa desgastada refleja años de exilio en el desierto vigilando a Luke. Esta variante exclusiva de la promoción de reloj añade coleccionabilidad. Esencial para coleccionistas de variantes raras de Obi-Wan y lanzamientos promocionales LEGO."
  },
  {
    minifigure_no: 'sw1255',
    description_en: "Obi-Wan Kenobi in reddish brown robe and hood represents the Jedi Master during Clone Wars or exile periods. The hooded design adds mystery and versatility for different display scenarios. The reddish brown color provides visual distinction from lighter Jedi robes. Essential for collectors building comprehensive Obi-Wan displays across multiple eras.",
    description_de: "Obi-Wan Kenobi in rotbrauner Robe und Kapuze repräsentiert den Jedi-Meister während der Klonkriege oder Exilperioden. Das Kapuzen-Design fügt Mysterium und Vielseitigkeit für verschiedene Display-Szenarien hinzu. Die rotbraune Farbe bietet visuelle Unterscheidung von helleren Jedi-Roben. Unverzichtbar für Sammler, die umfassende Obi-Wan-Ausstellungen über mehrere Epochen bauen.",
    description_fr: "Obi-Wan Kenobi en robe et capuche brun rougeâtre représente le Maître Jedi pendant les périodes des guerres des clones ou d'exil. Le design à capuche ajoute du mystère et de la polyvalence pour différents scénarios d'affichage. La couleur brun rougeâtre offre une distinction visuelle des robes Jedi plus claires. Essentiel pour les collectionneurs construisant des présentoirs Obi-Wan complets à travers plusieurs époques.",
    description_es: "Obi-Wan Kenobi en túnica y capucha marrón rojizo representa al Maestro Jedi durante períodos de Guerras Clon o exilio. El diseño con capucha añade misterio y versatilidad para diferentes escenarios de exhibición. El color marrón rojizo proporciona distinción visual de túnicas Jedi más claras. Esencial para coleccionistas construyendo exhibiciones completas de Obi-Wan a través de múltiples eras."
  },
  {
    minifigure_no: 'sw1256',
    description_en: "The Snub Fighter Pilot represents the Rebel Alliance's starfighter crews flying various short-range craft. These versatile pilots operate X-wings, A-wings, and other snub fighters against Imperial forces. The pilot uniform creates consistency across Rebel aviation units. Perfect for collectors building diverse Rebel starfighter squadrons and hangar displays.",
    description_de: "Der Snub-Jägerpilot repräsentiert die Sternenjäger-Besatzungen der Rebellenallianz, die verschiedene Kurzstrecken-Raumschiffe fliegen. Diese vielseitigen Piloten bedienen X-Wings, A-Wings und andere Snub-Jäger gegen imperiale Streitkräfte. Die Pilotenuniform schafft Konsistenz über Rebellen-Luftfahrteinheiten hinweg. Perfekt für Sammler, die vielfältige Rebellen-Sternenjäger-Staffeln und Hangar-Ausstellungen bauen.",
    description_fr: "Le pilote de chasseur Snub représente les équipages de chasseurs stellaires de l'Alliance Rebelle pilotant divers engins à courte portée. Ces pilotes polyvalents opèrent des X-wings, A-wings et autres chasseurs snub contre les forces impériales. L'uniforme de pilote crée une cohérence à travers les unités d'aviation rebelles. Parfait pour les collectionneurs construisant des escadrons de chasseurs stellaires rebelles diversifiés et des présentoirs de hangar.",
    description_es: "El Piloto de Caza Snub representa las tripulaciones de cazas estelares de la Alianza Rebelde piloteando diversas naves de corto alcance. Estos pilotos versátiles operan X-wings, A-wings y otros cazas snub contra fuerzas imperiales. El uniforme de piloto crea consistencia a través de unidades de aviación rebelde. Perfecto para coleccionistas construyendo escuadrones diversos de cazas estelares rebeldes y exhibiciones de hangar."
  },
  {
    minifigure_no: 'sw1257',
    description_en: "Vane serves as a pirate crew member in The Mandalorian series, representing the lawless elements plaguing the Outer Rim. His distinctive appearance and aggressive personality make him memorable among pirate antagonists. Vane's recurring role creates ongoing tension throughout the series. Essential for collectors building Mandalorian pirate gang displays and antagonist rosters.",
    description_de: "Vane dient als Piraten-Crewmitglied in der Mandalorian-Serie und repräsentiert die gesetzlosen Elemente, die den Outer Rim plagen. Sein markantes Aussehen und aggressive Persönlichkeit machen ihn unter Piraten-Antagonisten unvergesslich. Vanes wiederkehrende Rolle schafft anhaltende Spannung während der Serie. Unverzichtbar für Sammler, die Mandalorian-Piraten-Gang-Ausstellungen und Antagonisten-Rosters bauen.",
    description_fr: "Vane sert de membre d'équipage pirate dans la série The Mandalorian, représentant les éléments hors-la-loi ravageant la Bordure Extérieure. Son apparence distinctive et sa personnalité aggressive le rendent mémorable parmi les antagonistes pirates. Le rôle récurrent de Vane crée une tension continue tout au long de la série. Essentiel pour les collectionneurs construisant des présentoirs de gang de pirates Mandalorian et des listes d'antagonistes.",
    description_es: "Vane sirve como miembro de tripulación pirata en la serie The Mandalorian, representando los elementos sin ley que plagan el Borde Exterior. Su apariencia distintiva y personalidad agresiva lo hacen memorable entre antagonistas piratas. El papel recurrente de Vane crea tensión continua a lo largo de la serie. Esencial para coleccionistas construyendo exhibiciones de pandilla pirata Mandalorian y listas de antagonistas."
  },
  {
    minifigure_no: 'sw1258',
    description_en: "The Mandalorian Din Djarin with silver beskar armor, jet pack, and helmet with top lines represents the fully armored warrior at peak capability. The helmet detail distinguishes this variant from earlier versions. The complete package of armor and jet pack creates the definitive Mandalorian display piece. Highly sought after by collectors seeking the ultimate Din Djarin representation.",
    description_de: "Der Mandalorianer Din Djarin mit silberner Beskar-Rüstung, Jet Pack und Helm mit oberen Linien repräsentiert den vollständig gepanzerten Krieger auf Höchstleistung. Das Helm-Detail unterscheidet diese Variante von früheren Versionen. Das komplette Paket aus Rüstung und Jet Pack schafft das definitive Mandalorian-Ausstellungsstück. Sehr begehrt bei Sammlern, die die ultimative Din Djarin-Darstellung suchen.",
    description_fr: "Le Mandalorien Din Djarin avec armure beskar argentée, réacteur dorsal et casque avec lignes supérieures représente le guerrier entièrement blindé à capacité maximale. Le détail du casque distingue cette variante des versions antérieures. L'ensemble complet d'armure et de réacteur dorsal crée la pièce d'exposition Mandalorian définitive. Très recherché par les collectionneurs recherchant la représentation ultime de Din Djarin.",
    description_es: "El Mandaloriano Din Djarin con armadura beskar plateada, jet pack y casco con líneas superiores representa al guerrero completamente blindado en capacidad máxima. El detalle del casco distingue esta variante de versiones anteriores. El paquete completo de armadura y jet pack crea la pieza de exhibición Mandalorian definitiva. Muy buscado por coleccionistas buscando la representación definitiva de Din Djarin."
  },
  {
    minifigure_no: 'sw1259',
    description_en: "The Mandalorian Fleet Commander with hair represents leadership within the scattered Mandalorian forces. Her command position demonstrates the diverse leadership structure in Mandalorian culture. The hair detail allows for helmet-off display options. Important for collectors building Mandalorian command hierarchies and fleet operations displays.",
    description_de: "Die mandalorianische Flottenkommandantin mit Haar repräsentiert Führung innerhalb der verstreuten mandalorianischen Streitkräfte. Ihre Befehlsposition demonstriert die vielfältige Führungsstruktur in der mandalorianischen Kultur. Das Haar-Detail ermöglicht Helm-ab-Anzeigeoptionen. Wichtig für Sammler, die mandalorianische Befehlshierarchien und Flottenoperations-Ausstellungen bauen.",
    description_fr: "Le commandant de flotte mandalorien avec cheveux représente le leadership au sein des forces mandaloriennes dispersées. Sa position de commandement démontre la structure de leadership diversifiée dans la culture mandalorienne. Le détail des cheveux permet des options d'affichage sans casque. Important pour les collectionneurs construisant des hiérarchies de commandement mandaloriennes et des présentoirs d'opérations de flotte.",
    description_es: "La Comandante de Flota Mandaloriana con cabello representa liderazgo dentro de las dispersas fuerzas mandalorianas. Su posición de comando demuestra la diversa estructura de liderazgo en la cultura mandaloriana. El detalle de cabello permite opciones de exhibición sin casco. Importante para coleccionistas construyendo jerarquías de comando mandalorianas y exhibiciones de operaciones de flota."
  },
  {
    minifigure_no: 'sw1260',
    description_en: "This female Imperial TIE Fighter/Interceptor Pilot with nougat head represents the diverse pilots serving in elite Imperial starfighter squadrons. TIE Interceptor pilots were the Empire's best aviators. The gender diversity adds realism to Imperial military displays. Essential for collectors building inclusive Imperial naval aviation rosters and TIE Interceptor crews.",
    description_de: "Diese weibliche imperiale TIE-Jäger/Interceptor-Pilotin mit hellbraunem Kopf repräsentiert die vielfältigen Piloten, die in elitären imperialen Sternenjäger-Staffeln dienen. TIE-Interceptor-Piloten waren die besten Flieger des Imperiums. Die Geschlechtervielfalt fügt imperialen Militärausstellungen Realismus hinzu. Unverzichtbar für Sammler, die inklusive imperiale Marine-Fliegerei-Rosters und TIE-Interceptor-Besatzungen bauen.",
    description_fr: "Ce pilote de chasseur/intercepteur TIE impérial féminin avec tête nougat représente les pilotes divers servant dans des escadrons de chasseurs stellaires impériaux d'élite. Les pilotes d'intercepteur TIE étaient les meilleurs aviateurs de l'Empire. La diversité de genre ajoute du réalisme aux présentoirs militaires impériaux. Essentiel pour les collectionneurs construisant des listes d'aviation navale impériale inclusives et des équipages d'intercepteur TIE.",
    description_es: "Esta piloto femenina de Caza/Interceptor TIE Imperial con cabeza tono claro representa a los diversos pilotos sirviendo en escuadrones de cazas estelares imperiales de élite. Los pilotos de Interceptor TIE eran los mejores aviadores del Imperio. La diversidad de género añade realismo a exhibiciones militares imperiales. Esencial para coleccionistas construyendo listas inclusivas de aviación naval imperial y tripulaciones de Interceptor TIE."
  },
  {
    minifigure_no: 'sw1261',
    description_en: "R2-E6 is an astromech droid variant with distinctive color scheme and markings. These utility droids serve across the galaxy in starfighter and technical support roles. The unique designation and appearance make each astromech individually collectible. Perfect for collectors building diverse droid populations and expanding astromech varieties.",
    description_de: "R2-E6 ist eine Astromech-Droiden-Variante mit markanter Farbgestaltung und Kennzeichnungen. Diese Nutz-Droiden dienen in der gesamten Galaxie in Sternenjäger- und technischen Unterstützungsrollen. Die einzigartige Bezeichnung und Erscheinung machen jeden Astromech individuell sammelwürdig. Perfekt für Sammler, die vielfältige Droiden-Populationen bauen und Astromech-Varianten erweitern.",
    description_fr: "R2-E6 est une variante de droïde astromech avec schéma de couleurs et marquages distinctifs. Ces droïdes utilitaires servent à travers la galaxie dans des rôles de chasseurs stellaires et de support technique. La désignation et l'apparence uniques rendent chaque astromech individuellement collectionnable. Parfait pour les collectionneurs construisant des populations de droïdes diverses et élargissant les variétés d'astromech.",
    description_es: "R2-E6 es una variante de droide astromecánico con esquema de colores y marcas distintivos. Estos droides utilitarios sirven por toda la galaxia en roles de cazas estelares y soporte técnico. La designación y apariencia únicas hacen cada astromecánico individualmente coleccionable. Perfecto para coleccionistas construyendo poblaciones diversas de droides y expandiendo variedades de astromecánicos."
  },
  {
    minifigure_no: 'sw1262',
    description_en: "Luke Skywalker as Jedi with hair side part and dual-sided head (smile/stern) captures the hero during Return of the Jedi. The side part hairstyle reflects Luke's mature appearance. The dual expressions allow for different emotional display moments. Essential for collectors recreating Luke's final confrontation with Vader and the Emperor.",
    description_de: "Luke Skywalker als Jedi mit Seitenscheitel-Haar und doppelseitigem Kopf (Lächeln/Ernst) fängt den Helden während Die Rückkehr der Jedi-Ritter ein. Die Seitenscheitel-Frisur spiegelt Lukes reifes Aussehen wider. Die doppelten Ausdrücke ermöglichen verschiedene emotionale Display-Momente. Unverzichtbar für Sammler, die Lukes finale Konfrontation mit Vader und dem Imperator nachstellen.",
    description_fr: "Luke Skywalker en tant que Jedi avec cheveux séparés sur le côté et tête double face (sourire/sévère) capture le héros pendant Le Retour du Jedi. La coiffure séparée sur le côté reflète l'apparence mature de Luke. Les expressions doubles permettent différents moments d'affichage émotionnel. Essentiel pour les collectionneurs recréant la confrontation finale de Luke avec Vador et l'Empereur.",
    description_es: "Luke Skywalker como Jedi con cabello con raya al lado y cabeza de doble cara (sonrisa/severo) captura al héroe durante El Retorno del Jedi. El peinado con raya al lado refleja la apariencia madura de Luke. Las expresiones duales permiten diferentes momentos de exhibición emocional. Esencial para coleccionistas recreando la confrontación final de Luke con Vader y el Emperador."
  },
  {
    minifigure_no: 'sw1263',
    description_en: "Emperor Palpatine with spongy cape, basic hood, and yellow eyes embodies the Sith Lord's terrifying presence. The textured cape adds dramatic flair while the yellow eyes capture his corruption by the dark side. This definitive villain remains central to the entire Star Wars saga. Essential for collectors of Original and Prequel Trilogy villains and Death Star throne room displays.",
    description_de: "Imperator Palpatine mit schwammigem Umhang, einfacher Kapuze und gelben Augen verkörpert die erschreckende Präsenz des Sith-Lords. Der texturierte Umhang fügt dramatisches Flair hinzu, während die gelben Augen seine Korruption durch die dunkle Seite einfangen. Dieser definitive Bösewicht bleibt zentral für die gesamte Star Wars-Saga. Unverzichtbar für Sammler von Original- und Prequel-Trilogie-Bösewichten und Todesstern-Thronsaal-Ausstellungen.",
    description_fr: "L'Empereur Palpatine avec cape spongieuse, capuche basique et yeux jaunes incarne la présence terrifiante du Seigneur Sith. La cape texturée ajoute du panache dramatique tandis que les yeux jaunes capturent sa corruption par le côté obscur. Ce méchant définitif reste central à toute la saga Star Wars. Essentiel pour les collectionneurs de méchants des trilogies originale et préquelle et des présentoirs de salle du trône de l'Étoile de la Mort.",
    description_es: "El Emperador Palpatine con capa esponjosa, capucha básica y ojos amarillos encarna la presencia aterradora del Señor Sith. La capa texturizada añade dramatismo mientras los ojos amarillos capturan su corrupción por el lado oscuro. Este villano definitivo permanece central para toda la saga Star Wars. Esencial para coleccionistas de villanos de Trilogías Original y Precuela y exhibiciones de sala del trono de la Estrella de la Muerte."
  },
  {
    minifigure_no: 'sw1264',
    description_en: "Princess Leia in Endor outfit with olive green camouflage and helmet leads the Rebel strike team against the shield generator. The military fatigues show Leia's evolution from royalty to military commander. The helmet adds tactical authenticity. Essential for collectors recreating the Battle of Endor and Leia's complete character progression.",
    description_de: "Prinzessin Leia im Endor-Outfit mit olivgrüner Tarnung und Helm führt das Rebellen-Einsatzteam gegen den Schildgenerator. Die Militäruniform zeigt Leias Entwicklung von Royalty zur Militärkommandantin. Der Helm fügt taktische Authentizität hinzu. Unverzichtbar für Sammler, die die Schlacht von Endor und Leias vollständige Charakterentwicklung nachstellen.",
    description_fr: "La Princesse Leia en tenue Endor avec camouflage vert olive et casque dirige l'équipe de frappe rebelle contre le générateur de bouclier. Le treillis militaire montre l'évolution de Leia de la royauté à commandante militaire. Le casque ajoute une authenticité tactique. Essentielle pour les collectionneurs recréant la bataille d'Endor et la progression complète du personnage de Leia.",
    description_es: "La Princesa Leia en atuendo Endor con camuflaje verde oliva y casco lidera el equipo de ataque rebelde contra el generador de escudos. El uniforme militar muestra la evolución de Leia de realeza a comandante militar. El casco añade autenticidad táctica. Esencial para coleccionistas recreando la Batalla de Endor y la progresión completa del personaje de Leia."
  },
  {
    minifigure_no: 'sw1265',
    description_en: "This male Imperial Scout Trooper with dual-molded helmet and detailed belt features light nougat head with dark brown eyebrows and frown. The expressive face beneath the helmet adds personality to the elite reconnaissance forces. Scout troopers on speeder bikes provide fast Imperial reconnaissance. Perfect for creating diverse Scout Trooper displays with individual character.",
    description_de: "Dieser männliche imperiale Scout-Trooper mit dual-gegossenem Helm und detailliertem Gürtel zeigt hellbraunen Kopf mit dunkelbraunen Augenbrauen und Stirnrunzeln. Das ausdrucksstarke Gesicht unter dem Helm fügt den Elite-Aufklärungsstreitkräften Persönlichkeit hinzu. Scout-Trooper auf Speeder-Bikes bieten schnelle imperiale Aufklärung. Perfekt zum Erstellen vielfältiger Scout-Trooper-Ausstellungen mit individuellem Charakter.",
    description_fr: "Ce Scout Trooper impérial masculin avec casque bi-moulé et ceinture détaillée présente une tête nougat clair avec sourcils brun foncé et froncement de sourcils. Le visage expressif sous le casque ajoute de la personnalité aux forces de reconnaissance d'élite. Les Scout troopers sur motos à répulsion fournissent une reconnaissance impériale rapide. Parfait pour créer des présentoirs de Scout Trooper diversifiés avec caractère individuel.",
    description_es: "Este Scout Trooper imperial masculino con casco bi-moldeado y cinturón detallado presenta cabeza tono claro con cejas marrón oscuro y ceño fruncido. El rostro expresivo bajo el casco añade personalidad a las fuerzas de reconocimiento de élite. Los Scout troopers en motos deslizadoras proporcionan reconocimiento imperial rápido. Perfecto para crear exhibiciones diversas de Scout Trooper con carácter individual."
  },
  {
    minifigure_no: 'sw1266',
    description_en: "Luke Skywalker in dark tan Endor outfit with helmet infiltrates the Imperial installation on the forest moon. This commando appearance shows Luke as a tactical operative rather than mystical Jedi. The practical military gear reflects the Rebellion's guerrilla warfare tactics. Essential for collectors recreating the Battle of Endor strike team mission.",
    description_de: "Luke Skywalker im dunkelbraunen Endor-Outfit mit Helm infiltriert die imperiale Installation auf dem Waldmond. Dieses Kommando-Aussehen zeigt Luke als taktischen Agenten statt mystischen Jedi. Die praktische Militärausrüstung spiegelt die Guerilla-Kriegstaktiken der Rebellion wider. Unverzichtbar für Sammler, die die Schlacht-von-Endor-Einsatzteam-Mission nachstellen.",
    description_fr: "Luke Skywalker en tenue Endor brun foncé avec casque infiltre l'installation impériale sur la lune forestière. Cette apparence de commando montre Luke comme un opératif tactique plutôt qu'un Jedi mystique. L'équipement militaire pratique reflète les tactiques de guérilla de la Rébellion. Essentiel pour les collectionneurs recréant la mission d'équipe de frappe de la bataille d'Endor.",
    description_es: "Luke Skywalker en atuendo Endor marrón oscuro con casco infiltra la instalación imperial en la luna forestal. Esta apariencia de comando muestra a Luke como operativo táctico en lugar de Jedi místico. El equipo militar práctico refleja las tácticas de guerra de guerrillas de la Rebelión. Esencial para coleccionistas recreando la misión del equipo de ataque de la Batalla de Endor."
  },
  {
    minifigure_no: 'sw1267',
    description_en: "Luke Skywalker in pilot suit with printed arms and black boots represents the hero during starfighter missions. The detailed printing eliminates sticker needs while capturing Luke's X-wing pilot appearance. The black boots add a distinctive detail. Essential for collectors building Luke's Rebel pilot displays and X-wing vehicle crews.",
    description_de: "Luke Skywalker im Pilotenanzug mit bedruckten Armen und schwarzen Stiefeln repräsentiert den Helden während Sternenjäger-Missionen. Die detaillierte Bedruckung eliminiert Aufkleber-Bedarf und fängt Lukes X-Wing-Pilot-Aussehen ein. Die schwarzen Stiefel fügen ein markantes Detail hinzu. Unverzichtbar für Sammler, die Lukes Rebellenpiloten-Ausstellungen und X-Wing-Fahrzeugbesatzungen bauen.",
    description_fr: "Luke Skywalker en combinaison de pilote avec bras imprimés et bottes noires représente le héros pendant les missions de chasseurs stellaires. L'impression détaillée élimine le besoin d'autocollants tout en capturant l'apparence de pilote X-wing de Luke. Les bottes noires ajoutent un détail distinctif. Essentiel pour les collectionneurs construisant des présentoirs de pilotes rebelles de Luke et des équipages de véhicules X-wing.",
    description_es: "Luke Skywalker en traje de piloto con brazos impresos y botas negras representa al héroe durante misiones de cazas estelares. La impresión detallada elimina necesidad de calcomanías mientras captura la apariencia de piloto X-wing de Luke. Las botas negras añaden un detalle distintivo. Esencial para coleccionistas construyendo exhibiciones de piloto rebelde de Luke y tripulaciones de vehículos X-wing."
  },
  {
    minifigure_no: 'sw1268',
    description_en: "Kai Brightstar represents a new generation of Jedi younglings from Star Wars: Young Jedi Adventures. This character introduces young audiences to Force-sensitive heroes. The youthful design appeals to both children and collectors of complete Star Wars character rosters. Perfect for collectors of animated series characters and next-generation Jedi.",
    description_de: "Kai Brightstar repräsentiert eine neue Generation von Jedi-Jünglingen aus Star Wars: Young Jedi Adventures. Dieser Charakter führt junge Zuschauer in machtsensitive Helden ein. Das jugendliche Design spricht sowohl Kinder als auch Sammler vollständiger Star Wars-Charakterrosters an. Perfekt für Sammler von Animationsserien-Charakteren und Jedi der nächsten Generation.",
    description_fr: "Kai Brightstar représente une nouvelle génération de jeunes Jedi de Star Wars: Young Jedi Adventures. Ce personnage présente aux jeunes publics des héros sensibles à la Force. Le design jeune séduit à la fois les enfants et les collectionneurs de listes de personnages Star Wars complètes. Parfait pour les collectionneurs de personnages de séries animées et de Jedi de nouvelle génération.",
    description_es: "Kai Brightstar representa una nueva generación de jóvenes Jedi de Star Wars: Young Jedi Adventures. Este personaje introduce a audiencias jóvenes a héroes sensibles a la Fuerza. El diseño juvenil atrae tanto a niños como a coleccionistas de listas completas de personajes Star Wars. Perfecto para coleccionistas de personajes de series animadas y Jedi de nueva generación."
  },
  {
    minifigure_no: 'sw1269',
    description_en: "Lys Solay joins Kai Brightstar as a young Jedi in Star Wars: Young Jedi Adventures. This character helps introduce the Jedi Order to younger audiences. The companion design works alongside other young Jedi characters. Essential for collectors of animated series content and building young Jedi training temple displays.",
    description_de: "Lys Solay schließt sich Kai Brightstar als junger Jedi in Star Wars: Young Jedi Adventures an. Dieser Charakter hilft, den Jedi-Orden jüngeren Zuschauern vorzustellen. Das Begleiter-Design funktioniert neben anderen jungen Jedi-Charakteren. Unverzichtbar für Sammler von Animationsserien-Inhalten und zum Aufbau junger Jedi-Trainingstempel-Ausstellungen.",
    description_fr: "Lys Solay rejoint Kai Brightstar en tant que jeune Jedi dans Star Wars: Young Jedi Adventures. Ce personnage aide à présenter l'Ordre Jedi aux jeunes publics. Le design de compagnon fonctionne aux côtés d'autres personnages jeunes Jedi. Essentiel pour les collectionneurs de contenu de séries animées et la construction de présentoirs de temple d'entraînement de jeunes Jedi.",
    description_es: "Lys Solay se une a Kai Brightstar como joven Jedi en Star Wars: Young Jedi Adventures. Este personaje ayuda a introducir la Orden Jedi a audiencias más jóvenes. El diseño de compañero funciona junto a otros personajes jóvenes Jedi. Esencial para coleccionistas de contenido de series animadas y construir exhibiciones de templo de entrenamiento de jóvenes Jedi."
  },
  {
    minifigure_no: 'sw1270',
    description_en: "Yoda in lime color represents an unusual variant of the legendary Jedi Grand Master. This bright color scheme creates a distinctive collectible piece. The lime variation may represent promotional or special edition releases. Valued by collectors of rare Yoda variants and unique LEGO color variations.",
    description_de: "Yoda in Limonenfarbe repräsentiert eine ungewöhnliche Variante des legendären Jedi-Großmeisters. Dieses helle Farbschema schafft ein markantes Sammlerstück. Die Limonen-Variation kann Werbe- oder Sonderauflagen repräsentieren. Geschätzt von Sammlern seltener Yoda-Varianten und einzigartiger LEGO-Farbvariationen.",
    description_fr: "Yoda en couleur citron vert représente une variante inhabituelle du légendaire Grand Maître Jedi. Ce schéma de couleurs vives crée une pièce de collection distinctive. La variation citron vert peut représenter des versions promotionnelles ou spéciales. Valorisé par les collectionneurs de variantes Yoda rares et de variations de couleurs LEGO uniques.",
    description_es: "Yoda en color lima representa una variante inusual del legendario Gran Maestro Jedi. Este esquema de colores brillantes crea una pieza coleccionable distintiva. La variación lima puede representar lanzamientos promocionales o de edición especial. Valorado por coleccionistas de variantes raras de Yoda y variaciones únicas de colores LEGO."
  },
  {
    minifigure_no: 'sw1271',
    description_en: "The Training Droid serves as practice targets and sparring partners for Jedi younglings. These droids help Force-sensitive students develop their combat skills and reflexes. The functional design reflects the utilitarian nature of training equipment. Perfect for collectors building Jedi Temple training room displays and youngling class scenes.",
    description_de: "Der Trainingsdroide dient als Übungsziele und Sparringspartner für Jedi-Jünglinge. Diese Droiden helfen machtsensitiven Schülern, ihre Kampffähigkeiten und Reflexe zu entwickeln. Das funktionale Design spiegelt die utilitaristische Natur von Trainingsausrüstung wider. Perfekt für Sammler, die Jedi-Tempel-Trainingsraum-Ausstellungen und Jünglingsklassen-Szenen bauen.",
    description_fr: "Le droïde d'entraînement sert de cibles d'exercice et de partenaires d'entraînement pour les jeunes Jedi. Ces droïdes aident les étudiants sensibles à la Force à développer leurs compétences de combat et leurs réflexes. Le design fonctionnel reflète la nature utilitaire de l'équipement d'entraînement. Parfait pour les collectionneurs construisant des présentoirs de salle d'entraînement du Temple Jedi et des scènes de classe de jeunes.",
    description_es: "El Droide de Entrenamiento sirve como objetivos de práctica y compañeros de combate para jóvenes Jedi. Estos droides ayudan a estudiantes sensibles a la Fuerza a desarrollar sus habilidades de combate y reflejos. El diseño funcional refleja la naturaleza utilitaria del equipo de entrenamiento. Perfecto para coleccionistas construyendo exhibiciones de sala de entrenamiento del Templo Jedi y escenas de clase de jóvenes."
  },
  {
    minifigure_no: 'sw1272',
    description_en: "Yoda in olive green with belt and light nougat feet represents the Jedi Grand Master during various missions. The belt accessory suggests preparedness for field operations. The light feet add a distinctive detail to this variant. Essential for collectors building comprehensive Yoda collections across different appearances and eras.",
    description_de: "Yoda in Olivgrün mit Gürtel und hellbraunen Füßen repräsentiert den Jedi-Großmeister während verschiedener Missionen. Das Gürtel-Zubehör suggeriert Bereitschaft für Feldeinsätze. Die hellen Füße fügen dieser Variante ein markantes Detail hinzu. Unverzichtbar für Sammler, die umfassende Yoda-Sammlungen über verschiedene Erscheinungsbilder und Epochen bauen.",
    description_fr: "Yoda en vert olive avec ceinture et pieds nougat clair représente le Grand Maître Jedi pendant diverses missions. L'accessoire de ceinture suggère la préparation pour les opérations sur le terrain. Les pieds clairs ajoutent un détail distinctif à cette variante. Essentiel pour les collectionneurs construisant des collections Yoda complètes à travers différentes apparences et époques.",
    description_es: "Yoda en verde oliva con cinturón y pies tono claro representa al Gran Maestro Jedi durante varias misiones. El accesorio de cinturón sugiere preparación para operaciones de campo. Los pies claros añaden un detalle distintivo a esta variante. Esencial para coleccionistas construyendo colecciones completas de Yoda a través de diferentes apariencias y eras."
  },
  {
    minifigure_no: 'sw1273',
    description_en: "Darth Vader with printed arms, traditional starched fabric cape, and white head with frown reveals the scarred Sith Lord. The premium fabric cape drapes naturally for dramatic displays. The exposed head shows Anakin's tragic transformation. Highly collectible for fans seeking Vader's most detailed and emotionally resonant representation.",
    description_de: "Darth Vader mit bedruckten Armen, traditionellem gestärktem Stoffumhang und weißem Kopf mit Stirnrunzeln enthüllt den vernarbten Sith-Lord. Der Premium-Stoffumhang fällt natürlich für dramatische Ausstellungen. Der freiliegende Kopf zeigt Anakins tragische Transformation. Sehr sammelwürdig für Fans, die Vaders detaillierteste und emotional resonanteste Darstellung suchen.",
    description_fr: "Dark Vador avec bras imprimés, cape en tissu amidonné traditionnel et tête blanche avec froncement de sourcils révèle le Seigneur Sith scarifié. La cape en tissu premium drape naturellement pour des présentoirs dramatiques. La tête exposée montre la transformation tragique d'Anakin. Très collectionnable pour les fans recherchant la représentation la plus détaillée et émotionnellement résonnante de Vador.",
    description_es: "Darth Vader con brazos impresos, capa de tela almidonada tradicional y cabeza blanca con ceño fruncido revela al Señor Sith con cicatrices. La capa de tela premium cae naturalmente para exhibiciones dramáticas. La cabeza expuesta muestra la trágica transformación de Anakin. Altamente coleccionable para fans buscando la representación más detallada y emocionalmente resonante de Vader."
  },
  {
    minifigure_no: 'sw1274',
    description_en: "Boba Fett with helmet, jet pack, printed arms and legs, and rangefinder represents the ultimate bounty hunter configuration. The comprehensive printing on all limbs eliminates sticker needs. The complete accessories package creates the definitive Boba Fett display piece. Highly sought after by collectors seeking the most detailed and authentic Fett representation.",
    description_de: "Boba Fett mit Helm, Jet Pack, bedruckten Armen und Beinen und Entfernungsmesser repräsentiert die ultimative Kopfgeldjäger-Konfiguration. Die umfassende Bedruckung aller Gliedmaßen eliminiert Aufkleber-Bedarf. Das komplette Zubehör-Paket schafft das definitive Boba Fett-Ausstellungsstück. Sehr begehrt bei Sammlern, die die detaillierteste und authentischste Fett-Darstellung suchen.",
    description_fr: "Boba Fett avec casque, réacteur dorsal, bras et jambes imprimés et télémètre représente la configuration ultime du chasseur de primes. L'impression complète sur tous les membres élimine le besoin d'autocollants. L'ensemble d'accessoires complet crée la pièce d'exposition Boba Fett définitive. Très recherché par les collectionneurs recherchant la représentation Fett la plus détaillée et authentique.",
    description_es: "Boba Fett con casco, jet pack, brazos y piernas impresos y telémetro representa la configuración definitiva de cazarrecompensas. La impresión integral en todas las extremidades elimina necesidad de calcomanías. El paquete completo de accesorios crea la pieza de exhibición definitiva de Boba Fett. Muy buscado por coleccionistas buscando la representación más detallada y auténtica de Fett."
  },
  {
    minifigure_no: 'sw1275',
    description_en: "This female Imperial Stormtrooper with shoulder belts adds important diversity to Imperial ground forces. The dual-molded helmet and nougat head show LEGO's commitment to inclusive representation. The shoulder belts suggest equipment-carrying roles. Essential for collectors building realistic and diverse Imperial army displays that reflect canon military diversity.",
    description_de: "Diese weibliche imperiale Sturmtrupplerin mit Schultergurten fügt den imperialen Bodentruppen wichtige Vielfalt hinzu. Der dual-gegossene Helm und hellbraune Kopf zeigen LEGOs Engagement für inklusive Repräsentation. Die Schultergurte suggerieren Ausrüstungstragende Rollen. Unverzichtbar für Sammler, die realistische und vielfältige imperiale Armeeausstellungen bauen, die kanonische militärische Vielfalt widerspiegeln.",
    description_fr: "Ce Stormtrooper impérial féminin avec bandoulières ajoute une diversité importante aux forces terrestres impériales. Le casque bi-moulé et la tête nougat montrent l'engagement de LEGO envers une représentation inclusive. Les bandoulières suggèrent des rôles de port d'équipement. Essentiel pour les collectionneurs construisant des présentoirs d'armée impériale réalistes et diversifiés qui reflètent la diversité militaire canonique.",
    description_es: "Esta Stormtrooper imperial femenina con correas de hombro añade importante diversidad a las fuerzas terrestres imperiales. El casco bi-moldeado y cabeza tono claro muestran el compromiso de LEGO con representación inclusiva. Las correas de hombro sugieren roles de transporte de equipo. Esencial para coleccionistas construyendo exhibiciones de ejército imperial realistas y diversas que reflejan diversidad militar canónica."
  }
];

async function main() {
  console.log('Starting batch save for sw1251-sw1275...');

  for (const desc of descriptions) {
    await prisma.minifigCatalog.update({
      where: { minifigure_no: desc.minifigure_no },
      data: {
        description_en: desc.description_en,
        description_de: desc.description_de,
        description_fr: desc.description_fr,
        description_es: desc.description_es,
        description_generated_at: new Date(),
        description_status: 'completed'
      }
    });
    console.log(`✓ Saved ${desc.minifigure_no}: ${desc.minifigure_no}`);
  }

  await prisma.$disconnect();
  console.log(`Batch complete! ${descriptions.length} minifigs saved (sw1251-sw1275).`);
}

main().catch(console.error);
