import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    minifigure_no: 'sw0655',
    name: 'Unkar\'s Thug',
    description_en: 'Unkar\'s Thugs worked as enforcers for Unkar Plutt, the junk dealer who controlled Jakku\'s scavenging economy and exploited desperate scavengers like Rey. These brutish criminals maintained order in Niima Outpost, ensuring scavengers received minimal compensation for salvaged parts. The thugs intimidated anyone who challenged Unkar\'s monopoly on scavenged goods from the Graveyard of Ships. Their presence represented the lawless frontier conditions on forgotten worlds like Jakku where the New Republic\'s authority didn\'t reach. Unkar\'s organization controlled food rations, forcing scavengers into exploitative relationships. These thugs embodied the petty tyranny of local crime bosses filling power vacuums in the galaxy\'s margins. Collectors value Unkar\'s Thugs for building Jakku marketplace scenes, representing The Force Awakens\' gritty scavenger culture, and displaying the everyday criminals Rey faced before her hero\'s journey began.',
    description_de: 'Unkars Schläger arbeiteten als Vollstrecker für Unkar Plutt, den Schrotthändler, der Jakkus Plünderungswirtschaft kontrollierte und verzweifelte Plünderer wie Rey ausbeutete. Diese brutalen Kriminellen hielten Ordnung im Niima-Außenposten und stellten sicher, dass Plünderer minimale Entschädigung für geborgene Teile erhielten. Die Schläger schüchterten jeden ein, der Unkars Monopol auf geplünderte Waren vom Friedhof der Schiffe herausforderte. Ihre Präsenz repräsentierte die gesetzlosen Grenzbedingungen auf vergessenen Welten wie Jakku, wo die Autorität der Neuen Republik nicht reichte. Unkars Organisation kontrollierte Essensrationen und zwang Plünderer in ausbeuterische Beziehungen. Diese Schläger verkörperten die kleinliche Tyrannei lokaler Krimineller Bosse, die Machtvakua in den Randgebieten der Galaxis füllten. Sammler schätzen Unkars Schläger für den Aufbau von Jakku-Marktplatz-Szenen, die Darstellung der rauen Plünderer-Kultur von Das Erwachen der Macht und die Darstellung der alltäglichen Kriminellen, denen Rey vor Beginn ihrer Heldenreise begegnete.',
    description_fr: 'Les Voyous d\'Unkar travaillaient comme exécuteurs pour Unkar Plutt, le ferrailleur qui contrôlait l\'économie de récupération de Jakku et exploitait les récupérateurs désespérés comme Rey. Ces criminels brutaux maintenaient l\'ordre dans l\'Avant-poste de Niima, s\'assurant que les récupérateurs recevaient une compensation minimale pour les pièces récupérées. Les voyous intimidaient quiconque défiait le monopole d\'Unkar sur les marchandises récupérées du Cimetière des Vaisseaux. Leur présence représentait les conditions de frontière sans loi sur les mondes oubliés comme Jakku où l\'autorité de la Nouvelle République n\'atteignait pas. L\'organisation d\'Unkar contrôlait les rations alimentaires, forçant les récupérateurs dans des relations d\'exploitation. Ces voyous incarnaient la tyrannie mesquine des patrons du crime local remplissant les vides de pouvoir dans les marges de la galaxie. Les collectionneurs apprécient les Voyous d\'Unkar pour construire des scènes de marché de Jakku, représenter la culture de récupérateurs crue du Réveil de la Force et afficher les criminels quotidiens que Rey a affrontés avant que son voyage héroïque ne commence.',
    description_es: 'Los Matones de Unkar trabajaban como ejecutores para Unkar Plutt, el chatarrero que controlaba la economía de recuperación de Jakku y explotaba a recuperadores desesperados como Rey. Estos criminales brutales mantenían el orden en el Puesto Avanzado de Niima, asegurando que los recuperadores recibieran compensación mínima por partes recuperadas. Los matones intimidaban a cualquiera que desafiara el monopolio de Unkar sobre bienes recuperados del Cementerio de Naves. Su presencia representaba las condiciones fronterizas sin ley en mundos olvidados como Jakku donde la autoridad de la Nueva República no alcanzaba. La organización de Unkar controlaba las raciones de comida, forzando a recuperadores en relaciones de explotación. Estos matones encarnaban la tiranía mezquina de jefes criminales locales llenando vacíos de poder en los márgenes de la galaxia. Los coleccionistas valoran a los Matones de Unkar para construir escenas del mercado de Jakku, representar la cultura cruda de recuperadores de El Despertar de la Fuerza y mostrar a los criminales cotidianos que Rey enfrentó antes de que comenzara su viaje heroico.'
  },
  {
    minifigure_no: 'sw0656',
    name: 'First Order Snowtrooper Officer',
    description_en: 'First Order Snowtrooper Officers commanded specialized cold weather assault units during operations on frozen worlds like Starkiller Base. This minifigure features distinctive officer markings on the white and gray snowtrooper armor designed for sub-zero combat. Snowtroopers wore insulated suits with heating systems, breathing apparatus for extreme conditions, and enhanced vision equipment for blizzard operations. Officers led squads during the attack on Maz Kanata\'s castle and other cold environment missions. The First Order inherited snowtrooper technology from the Galactic Empire, updating designs with improved thermal protection and communications. Officer insignia distinguished command personnel from standard snowtrooper ranks. These specialists represented the First Order\'s capability to operate across all planetary environments. Collectors value snowtrooper officers for building Starkiller Base scenes, army building specialized units, and displaying First Order military hierarchy in extreme conditions.',
    description_de: 'Erste-Ordnung-Schneetruppen-Offiziere befehligten spezialisierte Kälte-Wetter-Angriffseinheiten während Operationen auf gefrorenen Welten wie Starkiller Base. Diese Minifigur zeigt markante Offiziersmarkierungen auf der weißen und grauen Schneetruppen-Rüstung, die für Kampf unter null Grad entwickelt wurde. Schneetruppen trugen isolierte Anzüge mit Heizsystemen, Atemapparaten für extreme Bedingungen und verbesserter Sichtausrüstung für Schneesturm-Operationen. Offiziere führten Trupps während des Angriffs auf Maz Kanatas Schloss und andere Kälteumgebungs-Missionen an. Die Erste Ordnung erbte Schneetruppen-Technologie vom Galaktischen Imperium und aktualisierte Designs mit verbessertem thermischen Schutz und Kommunikation. Offiziers-Insignien unterschieden Befehlspersonal von Standard-Schneetruppen-Rängen. Diese Spezialisten repräsentierten die Fähigkeit der Ersten Ordnung, über alle planetarischen Umgebungen hinweg zu operieren. Sammler schätzen Schneetruppen-Offiziere für den Aufbau von Starkiller-Base-Szenen, Army-Building spezialisierter Einheiten und die Darstellung der militärischen Hierarchie der Ersten Ordnung unter extremen Bedingungen.',
    description_fr: 'Les Officiers Snowtroopers du Premier Ordre commandaient des unités d\'assaut spécialisées par temps froid pendant les opérations sur des mondes gelés comme la Base Starkiller. Cette minifigurine présente des marques d\'officier distinctives sur l\'armure de snowtrooper blanche et grise conçue pour le combat sous zéro. Les Snowtroopers portaient des combinaisons isolées avec des systèmes de chauffage, un appareil respiratoire pour conditions extrêmes et un équipement de vision amélioré pour les opérations de blizzard. Les officiers dirigeaient des escouades lors de l\'attaque du château de Maz Kanata et d\'autres missions en environnement froid. Le Premier Ordre a hérité de la technologie snowtrooper de l\'Empire Galactique, mettant à jour les designs avec une protection thermique et des communications améliorées. Les insignes d\'officier distinguaient le personnel de commandement des rangs standard de snowtrooper. Ces spécialistes représentaient la capacité du Premier Ordre à opérer dans tous les environnements planétaires. Les collectionneurs apprécient les officiers snowtroopers pour construire des scènes de Base Starkiller, construire des unités spécialisées et afficher la hiérarchie militaire du Premier Ordre dans des conditions extrêmes.',
    description_es: 'Los Oficiales Snowtrooper de la Primera Orden comandaban unidades de asalto especializadas en clima frío durante operaciones en mundos congelados como la Base Starkiller. Esta minifigura presenta marcas distintivas de oficial en la armadura de snowtrooper blanca y gris diseñada para combate bajo cero. Los Snowtroopers usaban trajes aislados con sistemas de calefacción, aparato respiratorio para condiciones extremas y equipo de visión mejorado para operaciones de ventisca. Los oficiales lideraban escuadrones durante el ataque al castillo de Maz Kanata y otras misiones en ambiente frío. La Primera Orden heredó tecnología de snowtrooper del Imperio Galáctico, actualizando diseños con protección térmica y comunicaciones mejoradas. Las insignias de oficial distinguían al personal de comando de rangos estándar de snowtrooper. Estos especialistas representaban la capacidad de la Primera Orden para operar en todos los ambientes planetarios. Los coleccionistas valoran a los oficiales snowtrooper para construir escenas de Base Starkiller, construcción de ejércitos de unidades especializadas y mostrar la jerarquía militar de la Primera Orden en condiciones extremas.'
  },
  {
    minifigure_no: 'sw0657',
    name: 'First Order Snowtrooper with Kama',
    description_en: 'This First Order Snowtrooper features a kama - a protective waist cape worn over armor providing additional protection and status indication. The kama distinguished specialized or veteran snowtroopers from standard cold weather troops. First Order snowtroopers operated in extreme sub-zero environments wearing advanced insulated armor with integrated heating and life support. The kama addition suggests enhanced combat experience or specialized role within snowtrooper units. These cold weather specialists participated in operations on Starkiller Base and other frozen installations. The white and gray camouflage pattern provided concealment in snowy terrain while advanced helmet systems allowed operation during blizzards. Snowtroopers with kama represented elite or veteran status within specialized environmental units. Collectors value this kama variant for its visual distinctiveness, indication of specialist status, and for building diverse snowtrooper squads with rank variation for Starkiller Base and cold weather displays.',
    description_de: 'Dieser Erste-Ordnung-Schneetruppe zeigt eine Kama - einen schützenden Hüftumhang, der über der Rüstung getragen wird und zusätzlichen Schutz und Statusanzeige bietet. Die Kama unterschied spezialisierte oder Veteranen-Schneetruppen von Standard-Kältewetter-Truppen. Erste-Ordnung-Schneetruppen operierten in extremen Minusgraden mit fortschrittlicher isolierter Rüstung mit integrierter Heizung und Lebenserhaltung. Die Kama-Hinzufügung deutet auf erweiterte Kampferfahrung oder spezialisierte Rolle innerhalb von Schneetruppen-Einheiten hin. Diese Kältewetter-Spezialisten nahmen an Operationen auf Starkiller Base und anderen gefrorenen Anlagen teil. Das weiß-graue Tarnmuster bot Tarnung in verschneitem Gelände, während fortschrittliche Helmsysteme den Betrieb während Schneestürmen ermöglichten. Schneetruppen mit Kama repräsentierten Elite- oder Veteranenstatus innerhalb spezialisierter Umgebungseinheiten. Sammler schätzen diese Kama-Variante für ihre visuelle Unterscheidbarkeit, Anzeige von Spezialistenstatus und für den Aufbau vielfältiger Schneetruppen-Trupps mit Rangvariation für Starkiller-Base- und Kältewetter-Displays.',
    description_fr: 'Ce Snowtrooper du Premier Ordre présente un kama - une cape de taille protectrice portée sur l\'armure fournissant une protection supplémentaire et une indication de statut. Le kama distinguait les snowtroopers spécialisés ou vétérans des troupes standard par temps froid. Les snowtroopers du Premier Ordre opéraient dans des environnements extrêmes sous zéro portant une armure isolée avancée avec chauffage et support vital intégrés. L\'ajout du kama suggère une expérience de combat améliorée ou un rôle spécialisé au sein des unités de snowtrooper. Ces spécialistes du temps froid ont participé à des opérations sur la Base Starkiller et d\'autres installations gelées. Le motif de camouflage blanc et gris fournissait une dissimulation dans un terrain enneigé tandis que les systèmes de casque avancés permettaient l\'opération pendant les blizzards. Les Snowtroopers avec kama représentaient un statut d\'élite ou de vétéran au sein d\'unités environnementales spécialisées. Les collectionneurs apprécient cette variante kama pour sa distinction visuelle, son indication de statut de spécialiste et pour construire des escouades de snowtroopers diverses avec variation de rang pour les displays de Base Starkiller et par temps froid.',
    description_es: 'Este Snowtrooper de la Primera Orden presenta un kama - una capa protectora de cintura usada sobre la armadura proporcionando protección adicional e indicación de estatus. El kama distinguía a snowtroopers especializados o veteranos de tropas estándar de clima frío. Los snowtroopers de la Primera Orden operaban en ambientes extremos bajo cero usando armadura aislada avanzada con calefacción y soporte vital integrados. La adición del kama sugiere experiencia de combate mejorada o papel especializado dentro de unidades de snowtrooper. Estos especialistas de clima frío participaron en operaciones en Base Starkiller y otras instalaciones congeladas. El patrón de camuflaje blanco y gris proporcionaba ocultación en terreno nevado mientras sistemas de casco avanzados permitían operación durante ventiscas. Los Snowtroopers con kama representaban estatus de élite o veterano dentro de unidades ambientales especializadas. Los coleccionistas valoran esta variante kama por su distintividad visual, indicación de estatus especialista y para construir escuadrones diversos de snowtroopers con variación de rango para exhibiciones de Base Starkiller y clima frío.'
  },
  {
    minifigure_no: 'sw0658',
    name: 'Poe Dameron (Pilot Jumpsuit, Helmet)',
    description_en: 'Poe Dameron was the Resistance\'s best starfighter pilot, flying his customized black and orange X-wing on critical missions against the First Order. This minifigure shows Poe in his distinctive pilot jumpsuit with helmet, ready for combat operations. His natural piloting talent and fearless attitude made him a legendary squadron leader. Poe\'s missions included stealing First Order data, rescuing Finn from execution, and leading the attack on Starkiller Base. The orange and gray flight suit reflected Resistance pilot colors distinct from Rebel Alliance traditions. Poe\'s partnership with BB-8 and friendship with Finn and Rey formed the sequel trilogy\'s core relationships. His character embodied the new generation of heroes fighting tyranny. Collectors value this helmeted pilot variant for displaying Poe in action configuration, building X-wing cockpit scenes, and representing the Resistance\'s elite starfighter corps.',
    description_de: 'Poe Dameron war der beste Sternenjägerpilot des Widerstands und flog seinen angepassten schwarz-orangen X-Wing auf kritischen Missionen gegen die Erste Ordnung. Diese Minifigur zeigt Poe in seinem markanten Piloten-Jumpsuit mit Helm, bereit für Kampfeinsätze. Sein natürliches Pilottalent und furchtlose Haltung machten ihn zu einem legendären Staffelführer. Poes Missionen umfassten das Stehlen von Erste-Ordnung-Daten, die Rettung von Finn vor der Hinrichtung und die Führung des Angriffs auf Starkiller Base. Der orange-graue Fluganzug spiegelte Widerstands-Pilotenfarben wider, die sich von Rebellenallianz-Traditionen unterschieden. Poes Partnerschaft mit BB-8 und Freundschaft mit Finn und Rey bildeten die Kernbeziehungen der Sequel-Trilogie. Sein Charakter verkörperte die neue Generation von Helden, die Tyrannei bekämpften. Sammler schätzen diese behelmte Pilotenvariante für die Darstellung von Poe in Aktionskonfiguration, den Aufbau von X-Wing-Cockpit-Szenen und die Darstellung des Elite-Sternenjägerkorps des Widerstands.',
    description_fr: 'Poe Dameron était le meilleur pilote de chasseur stellaire de la Résistance, pilotant son X-wing noir et orange personnalisé lors de missions critiques contre le Premier Ordre. Cette minifigurine montre Poe dans sa combinaison de pilote distinctive avec casque, prêt pour les opérations de combat. Son talent de pilotage naturel et son attitude intrépide en faisaient un chef d\'escadron légendaire. Les missions de Poe incluaient le vol de données du Premier Ordre, le sauvetage de Finn de l\'exécution et la direction de l\'attaque sur la Base Starkiller. La combinaison de vol orange et grise reflétait les couleurs de pilote de la Résistance distinctes des traditions de l\'Alliance Rebelle. Le partenariat de Poe avec BB-8 et l\'amitié avec Finn et Rey formaient les relations centrales de la trilogie des suites. Son personnage incarnait la nouvelle génération de héros combattant la tyrannie. Les collectionneurs apprécient cette variante de pilote casqué pour afficher Poe en configuration d\'action, construire des scènes de cockpit de X-wing et représenter le corps de chasseurs stellaires d\'élite de la Résistance.',
    description_es: 'Poe Dameron era el mejor piloto de cazas estelares de la Resistencia, volando su X-wing negro y naranja personalizado en misiones críticas contra la Primera Orden. Esta minifigura muestra a Poe en su distintivo traje de piloto con casco, listo para operaciones de combate. Su talento natural de pilotaje y actitud intrépida lo convirtieron en un legendario líder de escuadrón. Las misiones de Poe incluyeron robar datos de la Primera Orden, rescatar a Finn de la ejecución y liderar el ataque a la Base Starkiller. El traje de vuelo naranja y gris reflejaba colores de piloto de la Resistencia distintos de las tradiciones de la Alianza Rebelde. La asociación de Poe con BB-8 y amistad con Finn y Rey formaron las relaciones centrales de la trilogía de secuelas. Su personaje encarnaba la nueva generación de héroes luchando contra la tiranía. Los coleccionistas valoran esta variante de piloto con casco para mostrar a Poe en configuración de acción, construir escenas de cabina de X-wing y representar el cuerpo de cazas estelares de élite de la Resistencia.'
  },
  {
    minifigure_no: 'sw0659',
    name: 'Resistance Pilot X-wing',
    description_en: 'Resistance X-wing pilots flew the latest generation of Incom T-70 starfighters defending the New Republic from First Order aggression. This generic pilot minifigure allows collectors to build diverse squadron rosters with different species and appearances. Resistance pilots wore orange and gray flight suits updated from Rebel Alliance designs with modern flight gear and life support systems. These starfighter pilots formed Black Squadron under Poe Dameron\'s command and participated in crucial battles including Starkiller Base assault. X-wing pilots underwent rigorous training in dogfighting, bombing runs, and coordinated squadron tactics. The orange color scheme maintained visual continuity with original trilogy Rebel pilots while updated helmets reflected technological advancement. Generic pilot figures enabled collectors to crew multiple X-wings and build realistic squadron displays. Collectors value Resistance pilots for army building, creating diverse flight rosters, and representing the new generation defending freedom across the galaxy.',
    description_de: 'Widerstands-X-Wing-Piloten flogen die neueste Generation von Incom-T-70-Sternenjägern zur Verteidigung der Neuen Republik gegen Erste-Ordnung-Aggression. Diese generische Piloten-Minifigur ermöglicht es Sammlern, vielfältige Staffellisten mit verschiedenen Spezies und Erscheinungen aufzubauen. Widerstands-Piloten trugen orange-graue Fluganzüge, die von Rebellenallianz-Designs mit moderner Flugausrüstung und Lebenserhaltungssystemen aktualisiert wurden. Diese Sternenjägerpiloten bildeten Black Squadron unter Poe Damerons Kommando und nahmen an entscheidenden Schlachten einschließlich des Starkiller-Base-Angriffs teil. X-Wing-Piloten durchliefen rigoroses Training in Luftkampf, Bombenläufen und koordinierten Staffeltaktiken. Das orange Farbschema erhielt visuelle Kontinuität mit Original-Trilogie-Rebellenpiloten, während aktualisierte Helme technologischen Fortschritt widerspiegelten. Generische Pilotenfiguren ermöglichten es Sammlern, mehrere X-Wings zu bemannen und realistische Staffel-Displays aufzubauen. Sammler schätzen Widerstands-Piloten für Army-Building, die Erstellung vielfältiger Fluglisten und die Darstellung der neuen Generation, die Freiheit in der Galaxis verteidigt.',
    description_fr: 'Les pilotes X-wing de la Résistance pilotaient la dernière génération de chasseurs stellaires Incom T-70 défendant la Nouvelle République contre l\'agression du Premier Ordre. Cette minifigurine de pilote générique permet aux collectionneurs de construire des listes d\'escadrons diverses avec différentes espèces et apparences. Les pilotes de la Résistance portaient des combinaisons de vol orange et grises mises à jour des designs de l\'Alliance Rebelle avec équipement de vol moderne et systèmes de support vital. Ces pilotes de chasseurs stellaires formaient l\'Escadron Noir sous le commandement de Poe Dameron et ont participé à des batailles cruciales incluant l\'assaut de la Base Starkiller. Les pilotes X-wing suivaient un entraînement rigoureux en combat aérien, bombardements et tactiques d\'escadron coordonnées. Le schéma de couleurs orange maintenait une continuité visuelle avec les pilotes rebelles de la trilogie originale tandis que les casques mis à jour reflétaient l\'avancement technologique. Les figurines de pilote génériques permettaient aux collectionneurs d\'équiper plusieurs X-wings et de construire des displays d\'escadron réalistes. Les collectionneurs apprécient les pilotes de la Résistance pour la construction d\'armée, la création de listes de vol diverses et la représentation de la nouvelle génération défendant la liberté à travers la galaxie.',
    description_es: 'Los pilotos X-wing de la Resistencia volaban la última generación de cazas estelares Incom T-70 defendiendo a la Nueva República de la agresión de la Primera Orden. Esta minifigura de piloto genérica permite a coleccionistas construir listas de escuadrón diversas con diferentes especies y apariencias. Los pilotos de la Resistencia usaban trajes de vuelo naranja y gris actualizados de diseños de la Alianza Rebelde con equipo de vuelo moderno y sistemas de soporte vital. Estos pilotos de cazas estelares formaron el Escuadrón Negro bajo el comando de Poe Dameron y participaron en batallas cruciales incluyendo el asalto a la Base Starkiller. Los pilotos X-wing se sometían a entrenamiento riguroso en combate aéreo, bombardeos y tácticas de escuadrón coordinadas. El esquema de colores naranja mantenía continuidad visual con pilotos rebeldes de la trilogía original mientras cascos actualizados reflejaban avance tecnológico. Las figuras de piloto genéricas permitían a coleccionistas tripular múltiples X-wings y construir exhibiciones de escuadrón realistas. Los coleccionistas valoran a los pilotos de la Resistencia para construcción de ejércitos, crear listas de vuelo diversas y representar la nueva generación defendiendo la libertad a través de la galaxia.'
  },
  {
    minifigure_no: 'sw0660',
    name: 'Resistance Ground Crew (Goss Toowers)',
    description_en: 'Goss Toowers was a member of the Resistance ground crew responsible for maintaining, repairing, and preparing starfighters between missions. Ground crew personnel performed the essential but unglamorous work keeping X-wings, A-wings, and transports operational. These technicians conducted pre-flight checks, repaired battle damage, refueled spacecraft, and loaded munitions. The Resistance\'s small size meant ground crews worked with limited resources and minimal downtime between sorties. Toowers and other mechanics enabled pilots like Poe Dameron to fly successful missions through their expert maintenance. Ground crew wore practical work clothes rather than military uniforms, emphasizing their technical rather than combat roles. The named character detail shows LEGO\'s attention to background characters from sequel trilogy scenes. Collectors value ground crew figures for building Resistance base hangar displays, showing the full support infrastructure behind starfighter operations, and representing the unsung heroes keeping the fleet flying.',
    description_de: 'Goss Toowers war Mitglied der Widerstands-Bodencrew, verantwortlich für Wartung, Reparatur und Vorbereitung von Sternenjägern zwischen Missionen. Bodencrew-Personal führte die wesentliche, aber unspektakuläre Arbeit durch, X-Wings, A-Wings und Transporter betriebsbereit zu halten. Diese Techniker führten Vorflugchecks durch, reparierten Kampfschäden, tankten Raumschiffe auf und luden Munition. Die kleine Größe des Widerstands bedeutete, dass Bodencrews mit begrenzten Ressourcen und minimaler Ausfallzeit zwischen Einsätzen arbeiteten. Toowers und andere Mechaniker ermöglichten es Piloten wie Poe Dameron, erfolgreiche Missionen durch ihre Expertenwartung zu fliegen. Bodencrew trug praktische Arbeitskleidung statt Militäruniformen und betonte ihre technische statt Kampfrolle. Das benannte Charakterdetail zeigt LEGOs Aufmerksamkeit für Hintergrundcharaktere aus Sequel-Trilogie-Szenen. Sammler schätzen Bodencrew-Figuren für den Aufbau von Widerstands-Basis-Hangar-Displays, die Darstellung der vollständigen Unterstützungsinfrastruktur hinter Sternenjäger-Operationen und die Darstellung der unbesungenen Helden, die die Flotte fliegen halten.',
    description_fr: 'Goss Toowers était membre de l\'équipe au sol de la Résistance responsable de l\'entretien, de la réparation et de la préparation des chasseurs stellaires entre les missions. Le personnel de l\'équipe au sol effectuait le travail essentiel mais peu glorieux pour maintenir les X-wings, A-wings et transports opérationnels. Ces techniciens effectuaient des vérifications avant vol, réparaient les dommages de combat, ravitaillaient en carburant les vaisseaux spatiaux et chargeaient les munitions. La petite taille de la Résistance signifiait que les équipes au sol travaillaient avec des ressources limitées et un temps d\'arrêt minimal entre les sorties. Toowers et d\'autres mécaniciens permettaient aux pilotes comme Poe Dameron de voler des missions réussies grâce à leur entretien expert. L\'équipe au sol portait des vêtements de travail pratiques plutôt que des uniformes militaires, soulignant leurs rôles techniques plutôt que de combat. Le détail du personnage nommé montre l\'attention de LEGO aux personnages de fond des scènes de la trilogie des suites. Les collectionneurs apprécient les figurines d\'équipe au sol pour construire des displays de hangar de base de la Résistance, montrer l\'infrastructure de soutien complète derrière les opérations de chasseurs stellaires et représenter les héros méconnus qui maintiennent la flotte en vol.',
    description_es: 'Goss Toowers era miembro de la tripulación de tierra de la Resistencia responsable del mantenimiento, reparación y preparación de cazas estelares entre misiones. El personal de tripulación de tierra realizaba el trabajo esencial pero poco glamoroso manteniendo operativos X-wings, alas-A y transportes. Estos técnicos realizaban verificaciones prevuelo, reparaban daños de batalla, reabastecían naves espaciales y cargaban municiones. El pequeño tamaño de la Resistencia significaba que las tripulaciones de tierra trabajaban con recursos limitados y tiempo de inactividad mínimo entre salidas. Toowers y otros mecánicos permitían a pilotos como Poe Dameron volar misiones exitosas mediante su mantenimiento experto. La tripulación de tierra usaba ropa de trabajo práctica en lugar de uniformes militares, enfatizando sus roles técnicos en lugar de combate. El detalle del personaje nombrado muestra la atención de LEGO a personajes de fondo de escenas de la trilogía de secuelas. Los coleccionistas valoran figuras de tripulación de tierra para construir exhibiciones de hangar de base de la Resistencia, mostrar la infraestructura de soporte completa detrás de operaciones de cazas estelares y representar a los héroes no reconocidos que mantienen la flota volando.'
  },
  {
    minifigure_no: 'sw0661',
    name: 'BB-8 (Small Photoreceptor and Small Black Circle)',
    description_en: 'BB-8 was Poe Dameron\'s loyal astromech droid whose spherical design and orange and white coloring made him instantly iconic in the sequel trilogy. This variant features small photoreceptor and small black circle details distinguishing it from other BB-8 versions. BB-8\'s rolling ball locomotion represented cutting-edge droid technology. His brave personality and expressive beeps endeared him to audiences worldwide. BB-8 carried the map to Luke Skywalker, making him crucial to The Force Awakens plot. His friendship with Rey and partnership with Poe showcased droids as true companions rather than tools. The spherical build represents LEGO\'s creative approach to non-standard droid designs. BB-8\'s thumbs-up lighter moment and combat-ready modifications showed his versatility. Collectors highly value BB-8 figures for their unique construction, sequel trilogy significance, and adorable character design that made BB-8 as beloved as R2-D2.',
    description_de: 'BB-8 war Poe Damerons treuer Astromech-Droide, dessen kugelförmiges Design und orange-weiße Färbung ihn in der Sequel-Trilogie sofort ikonisch machten. Diese Variante zeigt kleine Photozellen- und kleine schwarze Kreisdetails, die sie von anderen BB-8-Versionen unterscheiden. BB-8s rollende Kugel-Fortbewegung repräsentierte modernste Droiden-Technologie. Seine mutige Persönlichkeit und ausdrucksstarke Pieptöne machten ihn beim Publikum weltweit beliebt. BB-8 trug die Karte zu Luke Skywalker und machte ihn entscheidend für die Handlung von Das Erwachen der Macht. Seine Freundschaft mit Rey und Partnerschaft mit Poe zeigten Droiden als wahre Gefährten statt Werkzeuge. Der kugelförmige Bau repräsentiert LEGOs kreativen Ansatz für nicht-standardmäßige Droiden-Designs. BB-8s Daumen-hoch-heiterer Moment und kampfbereite Modifikationen zeigten seine Vielseitigkeit. Sammler schätzen BB-8-Figuren sehr für ihre einzigartige Konstruktion, Sequel-Trilogie-Bedeutung und entzückendes Charakterdesign, das BB-8 genauso beliebt wie R2-D2 machte.',
    description_fr: 'BB-8 était le droïde astromech loyal de Poe Dameron dont le design sphérique et la coloration orange et blanche l\'ont rendu instantanément iconique dans la trilogie des suites. Cette variante présente des détails de petit photorécepteur et de petit cercle noir la distinguant des autres versions de BB-8. La locomotion à balle roulante de BB-8 représentait la technologie de droïde de pointe. Sa personnalité courageuse et ses bips expressifs l\'ont rendu attachant au public mondial. BB-8 transportait la carte vers Luke Skywalker, le rendant crucial pour l\'intrigue du Réveil de la Force. Son amitié avec Rey et son partenariat avec Poe montraient les droïdes comme de vrais compagnons plutôt que des outils. La construction sphérique représente l\'approche créative de LEGO pour les designs de droïdes non standard. Le moment léger de pouce levé de BB-8 et les modifications prêtes au combat montraient sa polyvalence. Les collectionneurs apprécient hautement les figurines BB-8 pour leur construction unique, leur signification de trilogie des suites et leur design de personnage adorable qui a rendu BB-8 aussi aimé que R2-D2.',
    description_es: 'BB-8 era el leal droide astromech de Poe Dameron cuyo diseño esférico y coloración naranja y blanca lo convirtieron instantáneamente icónico en la trilogía de secuelas. Esta variante presenta detalles de fotorreceptor pequeño y círculo negro pequeño distinguiéndola de otras versiones de BB-8. La locomoción de bola rodante de BB-8 representaba tecnología droide de vanguardia. Su personalidad valiente y pitidos expresivos lo hicieron querido para audiencias mundiales. BB-8 llevaba el mapa a Luke Skywalker, haciéndolo crucial para la trama de El Despertar de la Fuerza. Su amistad con Rey y asociación con Poe mostraba droides como verdaderos compañeros en lugar de herramientas. La construcción esférica representa el enfoque creativo de LEGO para diseños de droides no estándar. El momento alegre de pulgar arriba de BB-8 y modificaciones listas para combate mostraban su versatilidad. Los coleccionistas valoran altamente las figuras de BB-8 por su construcción única, significado de trilogía de secuelas y diseño de personaje adorable que hizo a BB-8 tan amado como R2-D2.'
  }
];

async function saveBatch() {
  console.log('Starting batch save for sw0655-sw0661...');

  for (const minifig of batch) {
    try {
      await prisma.minifigCatalog.update({
        where: { minifigure_no: minifig.minifigure_no },
        data: {
          description_en: minifig.description_en,
          description_de: minifig.description_de,
          description_fr: minifig.description_fr,
          description_es: minifig.description_es,
          description_generated_at: new Date(),
          description_status: 'generated'
        },
      });
      console.log(`✓ Saved ${minifig.minifigure_no}: ${minifig.name}`);
    } catch (error) {
      console.error(`✗ Error saving ${minifig.minifigure_no}:`, error);
    }
  }

  console.log('Batch complete! 7 minifigs saved.');
  await prisma.$disconnect();
}

saveBatch();
