// Friends sets
module.exports = {
  '10292-1': {
    en: "The Friends Apartments features 2,048 pieces recreating Monica's and Rachel's apartments from the TV show. Includes 7 minifigures: Ross, Rachel, Chandler, Monica, Phoebe, Joey, and Janice. Features Monica's purple apartment with kitchen, living room, and balcony. Includes Joey's apartment with foosball table and Ugly Naked Guy's apartment. Measures over 14 inches high with authentic details from the series.",
    de: "Die Friends Apartments enthält 2.048 Teile und stellt Monicas und Rachels Apartments aus der TV-Serie nach. Mit 7 Minifiguren: Ross, Rachel, Chandler, Monica, Phoebe, Joey und Janice. Mit Monicas lila Apartment mit Küche, Wohnzimmer und Balkon. Enthält Joeys Apartment mit Tischfußball und Ugly Naked Guys Apartment. Über 37 cm hoch mit authentischen Details aus der Serie.",
    fr: "Les Appartements Friends comprend 2 048 pièces recréant les appartements de Monica et Rachel de la série TV. Comprend 7 minifigurines : Ross, Rachel, Chandler, Monica, Phoebe, Joey et Janice. Appartement violet de Monica avec cuisine, salon et balcon. Comprend l'appartement de Joey avec baby-foot et l'appartement d'Ugly Naked Guy. Mesure plus de 37 cm de haut avec détails authentiques de la série.",
    es: "Los Apartamentos Friends contiene 2.048 piezas recreando los apartamentos de Monica y Rachel del programa de TV. Incluye 7 minifiguras: Ross, Rachel, Chandler, Monica, Phoebe, Joey y Janice. Con apartamento morado de Monica con cocina, sala de estar y balcón. Incluye apartamento de Joey con futbolín y apartamento de Ugly Naked Guy. Mide más de 37 cm de alto con detalles auténticos de la serie."
  },
  '21319-1': {
    en: "Central Perk features 1,070 pieces recreating the iconic coffee shop from Friends. Includes 7 minifigures: Ross, Rachel, Chandler, Monica, Phoebe, Joey, and Gunther. Features detailed café interior with counter, coffee machine, menu board, couch, armchairs, and Phoebe's stage area. Includes brick-built accessories and authentic details. Measures over 4 inches high and 11 inches wide.",
    de: "Central Perk enthält 1.070 Teile und stellt das ikonische Café aus Friends nach. Mit 7 Minifiguren: Ross, Rachel, Chandler, Monica, Phoebe, Joey und Gunther. Mit detailliertem Café-Innenraum mit Theke, Kaffeemaschine, Menütafel, Couch, Sesseln und Phoebes Bühnenbereich. Mit gebauten Accessoires und authentischen Details. Über 11 cm hoch und 29 cm breit.",
    fr: "Central Perk comprend 1 070 pièces recréant le café emblématique de Friends. Comprend 7 minifigurines : Ross, Rachel, Chandler, Monica, Phoebe, Joey et Gunther. Intérieur de café détaillé avec comptoir, machine à café, tableau de menu, canapé, fauteuils et zone de scène de Phoebe. Comprend accessoires construits en briques et détails authentiques. Mesure plus de 11 cm de haut et 29 cm de large.",
    es: "Central Perk contiene 1.070 piezas recreando el icónico café de Friends. Incluye 7 minifiguras: Ross, Rachel, Chandler, Monica, Phoebe, Joey y Gunther. Con interior detallado del café con mostrador, máquina de café, pizarra de menú, sofá, sillones y área de escenario de Phoebe. Incluye accesorios construidos y detalles auténticos. Mide más de 11 cm de alto y 29 cm de ancho."
  },
  '41704-1': {
    en: "Main Street Building features 1,682 pieces recreating Heartlake City's downtown. Includes 7 minifigures: Emma, Stephanie, Olivia, Andrea, Mia, River, and Niko. Features 3-story building with hair salon, sushi restaurant, dance studio, recording studio, and apartments. Includes working elevator, rooftop garden, and detailed interiors. Measures over 12 inches high with modular design.",
    de: "Hauptstraßengebäude enthält 1.682 Teile und stellt Heartlake Citys Innenstadt nach. Mit 7 Minifiguren: Emma, Stephanie, Olivia, Andrea, Mia, River und Niko. Mit 3-stöckigem Gebäude mit Friseursalon, Sushi-Restaurant, Tanzstudio, Aufnahmestudio und Apartments. Mit funktionierendem Aufzug, Dachgarten und detaillierten Innenräumen. Über 31 cm hoch mit modularem Design.",
    fr: "Bâtiment de la Rue Principale comprend 1 682 pièces recréant le centre-ville d'Heartlake City. Comprend 7 minifigurines : Emma, Stephanie, Olivia, Andrea, Mia, River et Niko. Bâtiment de 3 étages avec salon de coiffure, restaurant de sushi, studio de danse, studio d'enregistrement et appartements. Comprend ascenseur fonctionnel, jardin sur le toit et intérieurs détaillés. Mesure plus de 31 cm de haut avec conception modulaire.",
    es: "Edificio de la Calle Principal contiene 1.682 piezas recreando el centro de Heartlake City. Incluye 7 minifiguras: Emma, Stephanie, Olivia, Andrea, Mia, River y Niko. Con edificio de 3 pisos con salón de belleza, restaurante de sushi, estudio de baile, estudio de grabación y apartamentos. Incluye ascensor funcional, jardín en azotea e interiores detallados. Mide más de 31 cm de alto con diseño modular."
  },
  '41450-1': {
    en: "Heartlake City Shopping Mall features 1,032 pieces recreating a modern shopping center. Includes 6 minifigures: Andrea, Emma, Stephanie, Olivia, and shoppers. Features fashion boutique, technology store, juice bar, photo booth, and ATM. Includes escalator, elevator, and detailed storefronts. Measures over 9 inches high and 15 inches wide with vibrant colors.",
    de: "Heartlake City Einkaufszentrum enthält 1.032 Teile und stellt ein modernes Einkaufszentrum nach. Mit 6 Minifiguren: Andrea, Emma, Stephanie, Olivia und Einkäufer. Mit Mode-Boutique, Technikladen, Saftbar, Fotoautomat und Geldautomat. Mit Rolltreppe, Aufzug und detaillierten Schaufenstern. Über 24 cm hoch und 39 cm breit mit lebendigen Farben.",
    fr: "Centre Commercial d'Heartlake City comprend 1 032 pièces recréant un centre commercial moderne. Comprend 6 minifigurines : Andrea, Emma, Stephanie, Olivia et acheteurs. Boutique de mode, magasin de technologie, bar à jus, photomaton et distributeur automatique. Comprend escalier roulant, ascenseur et vitrines détaillées. Mesure plus de 24 cm de haut et 39 cm de large avec couleurs vibrantes.",
    es: "Centro Comercial de Heartlake City contiene 1.032 piezas recreando un centro comercial moderno. Incluye 6 minifiguras: Andrea, Emma, Stephanie, Olivia y compradores. Con boutique de moda, tienda de tecnología, bar de jugos, cabina de fotos y cajero automático. Incluye escalera mecánica, ascensor y escaparates detallados. Mide más de 24 cm de alto y 39 cm de ancho con colores vibrantes."
  },
  '41685-1': {
    en: "Magical Funfair Roller Coaster features 974 pieces building a working roller coaster. Includes 4 minifigures: Mia, Stephanie, Ethan, and Nandi. Features hand-crank powered coaster track, ticket booth, balloon stand, and funfair games. Includes 3-car train that travels around the track. Measures over 13 inches high and 16 inches wide with fantasy design.",
    de: "Magische Jahrmarkt-Achterbahn enthält 974 Teile zum Bau einer funktionierenden Achterbahn. Mit 4 Minifiguren: Mia, Stephanie, Ethan und Nandi. Mit handkurbelbetriebener Achterbahnstrecke, Ticketschalter, Ballonstand und Jahrmarkt-Spielen. Mit 3-Wagen-Zug, der auf der Strecke fährt. Über 34 cm hoch und 42 cm breit mit Fantasy-Design.",
    fr: "Montagnes Russes de la Fête Foraine Magique comprend 974 pièces construisant des montagnes russes fonctionnelles. Comprend 4 minifigurines : Mia, Stephanie, Ethan et Nandi. Circuit de montagnes russes alimenté par manivelle, guichet, stand de ballons et jeux de fête foraine. Comprend train de 3 wagons qui circule sur le circuit. Mesure plus de 34 cm de haut et 42 cm de large avec design fantastique.",
    es: "Montaña Rusa de la Feria Mágica contiene 974 piezas construyendo una montaña rusa funcional. Incluye 4 minifiguras: Mia, Stephanie, Ethan y Nandi. Con pista de montaña rusa impulsada por manivela, taquilla, puesto de globos y juegos de feria. Incluye tren de 3 vagones que viaja por la pista. Mide más de 34 cm de alto y 42 cm de ancho con diseño de fantasía."
  }
};
