import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0264',
    name: 'Neimoidian Warrior',
    en: 'The Neimoidian Warrior LEGO minifigure portrays the cowardly yet opportunistic species that led the Trade Federation and Separatist Alliance, featuring distinctive gray-green skin, elaborate robes, and the characteristic tall head crest. This minifigure captures the Neimoidian appearance with detailed printing showing their ornate clothing and facial features, representing the greedy merchants who transformed from corrupt businessmen into military leaders during the Clone Wars. Known for their risk-averse nature despite commanding vast droid armies, Neimoidians like Nute Gunray orchestrated the blockade of Naboo and became key figures in the Separatist movement. Released in sets from 2007 onwards, this minifigure appeals to collectors building Trade Federation and Separatist command scenes, sought after due to the Neimoidians\' pivotal role in starting the galactic conflict, their distinctive alien design, and their representation of the corporate greed and political manipulation that undermined the Republic from within.',
    de: 'Die LEGO-Minifigur des Neimoidianischen Kriegers porträtiert die feige, aber opportunistische Spezies, die die Handelsföderation und Separatisten-Allianz anführte, mit markanter graugrüner Haut, aufwendigen Roben und dem charakteristischen hohen Kopfkamm. Diese Minifigur fängt das Aussehen der Neimoidianer mit detaillierter Bedruckung ein, die ihre aufwendige Kleidung und Gesichtszüge zeigt, die die gierigen Händler repräsentiert, die sich während der Klonkriege von korrupten Geschäftsleuten in militärische Anführer verwandelten. Bekannt für ihre risikoaverse Natur trotz der Befehle über riesige Droiden-Armeen, orchestrierten Neimoidianer wie Nute Gunray die Blockade von Naboo und wurden zu Schlüsselfiguren in der Separatisten-Bewegung. In Sets ab 2007 veröffentlicht, spricht diese Minifigur Sammler an, die Handelsföderation- und Separatisten-Kommando-Szenen aufbauen, begehrt aufgrund der entscheidenden Rolle der Neimoidianer beim Auslösen des galaktischen Konflikts, ihres markanten außerirdischen Designs und ihrer Darstellung der Unternehmensgier und politischen Manipulation, die die Republik von innen heraus untergrub.',
    fr: 'La minifigurine LEGO du Guerrier Neimoidien dépeint l\'espèce lâche mais opportuniste qui dirigeait la Fédération du Commerce et l\'Alliance Séparatiste, avec une peau gris-vert distinctive, des robes élaborées, et la crête de tête haute caractéristique. Cette minifigurine capture l\'apparence Neimoidienne avec une impression détaillée montrant leurs vêtements ornés et traits faciaux, représentant les marchands avides qui se sont transformés de businessmen corrompus en leaders militaires pendant les Guerres des Clones. Connus pour leur nature réticente au risque malgré le commandement de vastes armées de droïdes, les Neimoidiens comme Nute Gunray ont orchestré le blocus de Naboo et sont devenus des figures clés dans le mouvement Séparatiste. Sortie dans des sets à partir de 2007, cette minifigurine plaît aux collectionneurs construisant des scènes de commandement de la Fédération du Commerce et Séparatiste, recherchée en raison du rôle pivot des Neimoidiens dans le déclenchement du conflit galactique, leur design alien distinctif, et leur représentation de la cupidité corporative et de la manipulation politique qui ont miné la République de l\'intérieur.',
    es: 'La minifigura LEGO del Guerrero Neimoidiano retrata a la especie cobarde pero oportunista que lideró la Federación de Comercio y Alianza Separatista, presentando distintiva piel gris-verde, túnicas elaboradas, y la característica cresta alta de cabeza. Esta minifigura captura la apariencia Neimoidiana con impresión detallada mostrando su vestimenta ornamentada y rasgos faciales, representando a los mercaderes codiciosos que se transformaron de empresarios corruptos en líderes militares durante las Guerras Clon. Conocidos por su naturaleza reacia al riesgo a pesar de comandar vastos ejércitos de droides, los Neimoidianos como Nute Gunray orquestaron el bloqueo de Naboo y se convirtieron en figuras clave del movimiento Separatista. Lanzada en sets desde 2007, esta minifigura atrae a coleccionistas construyendo escenas de comando de la Federación de Comercio y Separatista, buscada debido al papel fundamental de los Neimoidianos en iniciar el conflicto galáctico, su distintivo diseño alienígena, y su representación de la codicia corporativa y manipulación política que socavó la República desde dentro.'
  },
  {
    no: 'sw0265',
    name: 'Senate Commando Captain',
    en: 'The Senate Commando Captain LEGO minifigure represents the elite security forces protecting the Galactic Senate on Coruscant, featuring distinctive blue armor with specialized helmet design and captain rank markings. This minifigure showcases detailed printing showing the ceremonial yet functional armor worn by the Republic\'s most prestigious guard unit, responsible for defending senators and maintaining order in the heart of galactic government. Armed with advanced weaponry and trained in both crowd control and anti-terrorism tactics, Senate Commandos stood as the final line of defense during the Clone Wars\' darkest moments when Separatist threats reached the capital itself. Released in sets from 2009 onwards, this minifigure appeals to collectors building Coruscant scenes and Republic military displays, sought after due to its unique blue color scheme that distinguished Senate Guards from standard clone troopers, its representation of the Republic\'s internal security apparatus, and its rarity compared to more common clone variants.',
    de: 'Die LEGO-Minifigur des Senat-Kommando-Kapitäns repräsentiert die Elite-Sicherheitskräfte, die den Galaktischen Senat auf Coruscant schützen, mit markanter blauer Rüstung mit spezialisiertem Helmdesign und Kapitänsrang-Markierungen. Diese Minifigur zeigt detaillierte Bedruckung, die die zeremonielle, aber funktionale Rüstung zeigt, die von der prestigeträchtigsten Wacheinheit der Republik getragen wird, verantwortlich für den Schutz von Senatoren und die Aufrechterhaltung der Ordnung im Herzen der galaktischen Regierung. Bewaffnet mit fortschrittlichen Waffen und ausgebildet sowohl in Menschenmengenkontrolle als auch in Anti-Terror-Taktiken, standen Senat-Kommandos als letzte Verteidigungslinie während der dunkelsten Momente der Klonkriege, als Separatisten-Bedrohungen die Hauptstadt selbst erreichten. In Sets ab 2009 veröffentlicht, spricht diese Minifigur Sammler an, die Coruscant-Szenen und Republik-Militär-Displays aufbauen, begehrt aufgrund ihres einzigartigen blauen Farbschemas, das Senat-Wachen von Standard-Klontruppen unterschied, ihrer Darstellung des internen Sicherheitsapparats der Republik und ihrer Seltenheit im Vergleich zu häufigeren Klon-Varianten.',
    fr: 'La minifigurine LEGO du Capitaine Commando du Sénat représente les forces de sécurité d\'élite protégeant le Sénat Galactique sur Coruscant, avec une armure bleue distinctive avec design de casque spécialisé et marques de rang de capitaine. Cette minifigurine présente une impression détaillée montrant l\'armure cérémonielle mais fonctionnelle portée par l\'unité de garde la plus prestigieuse de la République, responsable de défendre les sénateurs et de maintenir l\'ordre au cœur du gouvernement galactique. Armés d\'armes avancées et formés aux tactiques de contrôle de foule et anti-terrorisme, les Commandos du Sénat se tenaient comme ligne de défense finale pendant les moments les plus sombres des Guerres des Clones lorsque les menaces Séparatistes atteignaient la capitale elle-même. Sortie dans des sets à partir de 2009, cette minifigurine plaît aux collectionneurs construisant des scènes de Coruscant et des présentations militaires de la République, recherchée en raison de son schéma de couleur bleu unique qui distinguait les Gardes du Sénat des soldats clones standards, sa représentation de l\'appareil de sécurité interne de la République, et sa rareté par rapport aux variantes de clones plus communes.',
    es: 'La minifigura LEGO del Capitán Comando del Senado representa a las fuerzas de seguridad de élite protegiendo el Senado Galáctico en Coruscant, presentando distintiva armadura azul con diseño de casco especializado y marcas de rango de capitán. Esta minifigura muestra impresión detallada mostrando la armadura ceremonial pero funcional usada por la unidad de guardia más prestigiosa de la República, responsable de defender senadores y mantener el orden en el corazón del gobierno galáctico. Armados con armamento avanzado y entrenados tanto en control de multitudes como en tácticas antiterroristas, los Comandos del Senado se erigieron como línea de defensa final durante los momentos más oscuros de las Guerras Clon cuando las amenazas Separatistas alcanzaron la capital misma. Lanzada en sets desde 2009, esta minifigura atrae a coleccionistas construyendo escenas de Coruscant y exhibiciones militares de la República, buscada debido a su único esquema de color azul que distinguió a los Guardias del Senado de los soldados clon estándar, su representación del aparato de seguridad interna de la República, y su rareza comparada con variantes de clon más comunes.'
  },
  {
    no: 'sw0266',
    name: 'Gonk Droid',
    en: 'The Gonk Droid LEGO minifigure brings the galaxy\'s most beloved walking power generator to life, featuring its distinctive rectangular box shape, stubby legs, and the charming "gonk gonk" personality that made it a fan favorite despite minimal screen time. This minifigure captures the GNK power droid\'s utilitarian design with simple yet effective brick-built construction, representing the countless background droids that kept the Star Wars universe running by providing portable power to remote settlements, military bases, and starships. Despite serving purely functional roles as mobile battery units, Gonk droids achieved cult status among fans for their endearing waddle and their ubiquitous presence across all Star Wars eras. Released in sets from 2012 onwards appearing in everything from Tatooine scenes to Rebel bases, this minifigure has become surprisingly collectible, with fans appreciating its quirky charm, its representation of Star Wars\' lived-in universe filled with mundane yet essential technology, and the humor of giving a walking battery box such devoted following in the fandom.',
    de: 'Die LEGO-Minifigur des Gonk-Droiden erweckt den beliebtesten gehenden Stromgenerator der Galaxie zum Leben, mit seiner markanten rechteckigen Kastenform, stämmigen Beinen und der charmanten "Gonk Gonk"-Persönlichkeit, die ihn trotz minimaler Bildschirmzeit zu einem Fanliebling machte. Diese Minifigur fängt das utilitaristische Design des GNK-Stromdroiden mit einfacher, aber effektiver Stein-gebauter Konstruktion ein, die die zahllosen Hintergrunddroiden repräsentiert, die das Star Wars-Universum am Laufen hielten, indem sie tragbare Energie für abgelegene Siedlungen, Militärbasen und Raumschiffe bereitstellten. Obwohl sie rein funktionale Rollen als mobile Batterieeinheiten erfüllten, erlangten Gonk-Droiden Kultstatus unter Fans für ihr liebenswertes Watscheln und ihre allgegenwärtige Präsenz über alle Star Wars-Epochen hinweg. In Sets ab 2012 veröffentlicht und in allem von Tatooine-Szenen bis zu Rebellenbasen erscheinend, ist diese Minifigur überraschend sammelwürdig geworden, wobei Fans ihren skurrilen Charme, ihre Darstellung von Star Wars\' bewohntem Universum voller alltäglicher, aber wesentlicher Technologie und den Humor schätzen, einer gehenden Batteriekiste solch hingebungsvolle Gefolgschaft im Fandom zu geben.',
    fr: 'La minifigurine LEGO du Droïde Gonk donne vie au générateur d\'énergie ambulant le plus aimé de la galaxie, avec sa forme de boîte rectangulaire distinctive, ses jambes trapues, et la personnalité charmante "gonk gonk" qui en a fait un favori des fans malgré un temps d\'écran minimal. Cette minifigurine capture le design utilitaire du droïde d\'énergie GNK avec une construction en briques simple mais efficace, représentant les innombrables droïdes d\'arrière-plan qui maintenaient l\'univers Star Wars en fonctionnement en fournissant de l\'énergie portable aux colonies éloignées, bases militaires et vaisseaux spatiaux. Malgré le fait de servir des rôles purement fonctionnels en tant qu\'unités de batterie mobiles, les droïdes Gonk ont atteint un statut culte parmi les fans pour leur démarche attachante et leur présence omniprésente à travers toutes les ères Star Wars. Sortie dans des sets à partir de 2012 apparaissant dans tout, des scènes de Tatooine aux bases Rebelles, cette minifigurine est devenue étonnamment collectionnable, les fans appréciant son charme décalé, sa représentation de l\'univers vécu de Star Wars rempli de technologie banale mais essentielle, et l\'humour de donner à une boîte de batterie ambulante un tel suivi dévoué dans le fandom.',
    es: 'La minifigura LEGO del Droide Gonk da vida al generador de energía caminante más querido de la galaxia, presentando su distintiva forma de caja rectangular, piernas rechonchas, y la encantadora personalidad "gonk gonk" que lo hizo un favorito de los fans a pesar del mínimo tiempo en pantalla. Esta minifigura captura el diseño utilitario del droide de energía GNK con construcción simple pero efectiva construida con ladrillos, representando a los incontables droides de fondo que mantuvieron funcionando el universo Star Wars al proporcionar energía portátil a asentamientos remotos, bases militares y naves espaciales. A pesar de servir roles puramente funcionales como unidades de batería móviles, los droides Gonk alcanzaron estatus de culto entre los fans por su adorable contoneo y su presencia ubicua a través de todas las eras Star Wars. Lanzada en sets desde 2012 apareciendo en todo desde escenas de Tatooine hasta bases Rebeldes, esta minifigura se ha vuelto sorprendentemente coleccionable, con fans apreciando su encanto peculiar, su representación del universo vivido de Star Wars lleno de tecnología mundana pero esencial, y el humor de dar a una caja de batería caminante tal seguimiento devoto en el fandom.'
  },
  {
    no: 'sw0267',
    name: 'Medical Droid',
    en: 'The Medical Droid LEGO minifigure represents the compassionate yet clinical droids that tended to wounded warriors across the galaxy, featuring distinctive white and gray coloring with specialized medical equipment attachments. This minifigure captures the appearance of droids like those that attempted to save Padmé Amidala and rebuilt Darth Vader, showcasing the advanced medical technology that kept heroes and villains alive through devastating injuries. With detailed printing showing medical diagnostic displays and surgical implements, these droids represented the Star Wars universe\'s sophisticated healthcare systems that could treat everything from blaster wounds to catastrophic burns. Released in various medical bay sets from 2005 onwards, this minifigure appeals to collectors building hospital scenes and recovery stations, sought after for its representation of the quieter side of galactic conflict where droids worked tirelessly to repair the damage wrought by war, its connection to pivotal moments like Vader\'s transformation, and its embodiment of technology serving life rather than destruction.',
    de: 'Die LEGO-Minifigur des Medizinischen Droiden repräsentiert die mitfühlenden, aber klinischen Droiden, die sich um verwundete Krieger in der gesamten Galaxie kümmerten, mit markanter weißer und grauer Färbung mit spezialisierten medizinischen Ausrüstungsanbringungen. Diese Minifigur fängt das Aussehen von Droiden wie denen ein, die versuchten, Padmé Amidala zu retten und Darth Vader wiederaufbauten, die die fortschrittliche medizinische Technologie zeigen, die Helden und Schurken durch verheerende Verletzungen am Leben hielt. Mit detaillierter Bedruckung, die medizinische Diagnosedisplays und chirurgische Instrumente zeigt, repräsentierten diese Droiden die ausgefeilten Gesundheitssysteme des Star Wars-Universums, die alles von Blasterwunden bis zu katastrophalen Verbrennungen behandeln konnten. In verschiedenen Medizinbucht-Sets ab 2005 veröffentlicht, spricht diese Minifigur Sammler an, die Krankenhaus-Szenen und Erholungsstationen aufbauen, begehrt für ihre Darstellung der ruhigeren Seite des galaktischen Konflikts, wo Droiden unermüdlich arbeiteten, um den durch Krieg verursachten Schaden zu reparieren, ihre Verbindung zu entscheidenden Momenten wie Vaders Transformation und ihre Verkörperung von Technologie, die dem Leben dient statt der Zerstörung.',
    fr: 'La minifigurine LEGO du Droïde Médical représente les droïdes compatissants mais cliniques qui soignaient les guerriers blessés à travers la galaxie, avec une coloration blanche et grise distinctive avec des attachements d\'équipement médical spécialisé. Cette minifigurine capture l\'apparence de droïdes comme ceux qui ont tenté de sauver Padmé Amidala et reconstruit Dark Vador, présentant la technologie médicale avancée qui maintenait héros et méchants en vie à travers des blessures dévastatrices. Avec une impression détaillée montrant des écrans de diagnostic médical et des instruments chirurgicaux, ces droïdes représentaient les systèmes de santé sophistiqués de l\'univers Star Wars qui pouvaient traiter tout, des blessures par blaster aux brûlures catastrophiques. Sortie dans divers sets de baie médicale à partir de 2005, cette minifigurine plaît aux collectionneurs construisant des scènes d\'hôpital et des stations de récupération, recherchée pour sa représentation du côté plus calme du conflit galactique où les droïdes travaillaient inlassablement pour réparer les dégâts causés par la guerre, sa connexion à des moments pivots comme la transformation de Vador, et son incarnation de la technologie au service de la vie plutôt que de la destruction.',
    es: 'La minifigura LEGO del Droide Médico representa a los droides compasivos pero clínicos que atendían a guerreros heridos a través de la galaxia, presentando distintiva coloración blanca y gris con accesorios de equipo médico especializado. Esta minifigura captura la apariencia de droides como aquellos que intentaron salvar a Padmé Amidala y reconstruyeron a Darth Vader, mostrando la tecnología médica avanzada que mantuvo vivos a héroes y villanos a través de heridas devastadoras. Con impresión detallada mostrando pantallas de diagnóstico médico e implementos quirúrgicos, estos droides representaron los sofisticados sistemas de salud del universo Star Wars que podían tratar todo desde heridas de bláster hasta quemaduras catastróficas. Lanzada en varios sets de bahía médica desde 2005, esta minifigura atrae a coleccionistas construyendo escenas de hospital y estaciones de recuperación, buscada por su representación del lado más tranquilo del conflicto galáctico donde droides trabajaban incansablemente para reparar el daño causado por la guerra, su conexión con momentos fundamentales como la transformación de Vader, y su encarnación de tecnología sirviendo a la vida en lugar de la destrucción.'
  },
  {
    no: 'sw0268',
    name: 'R2-Q5',
    en: 'R2-Q5\'s LEGO minifigure captures the rare Imperial astromech droid with its distinctive black and gray color scheme that set it apart from the common blue and white Republic droids. This minifigure features detailed printing showing Imperial markings and the characteristic dome design, representing one of the few astromech units serving the Empire rather than Rebel forces. As an Imperial droid variant, R2-Q5 showcased how the Empire adapted Republic technology for its own purposes, with astromechs serving aboard Star Destroyers and TIE fighters rather than X-wings and Y-wings. Released in sets from 2002 onwards appearing in Death Star and Imperial facility builds, this minifigure became highly collectible among droid enthusiasts, sought after due to its striking black appearance contrasting with more common astromech colors, its rarity compared to countless R2-D2 variants, and its representation of Imperial technical superiority that maintained the Empire\'s massive fleet of warships and starfighters across the galaxy.',
    de: 'Die LEGO-Minifigur von R2-Q5 fängt den seltenen imperialen Astromech-Droiden mit seinem markanten schwarz-grauen Farbschema ein, das ihn von den üblichen blau-weißen Republik-Droiden unterschied. Diese Minifigur verfügt über detaillierte Bedruckung, die imperiale Markierungen und das charakteristische Kuppeldesign zeigt, die eine der wenigen Astromech-Einheiten repräsentiert, die dem Imperium statt den Rebellenstreitkräften dienten. Als imperiale Droiden-Variante zeigte R2-Q5, wie das Imperium Republik-Technologie für seine eigenen Zwecke anpasste, wobei Astromechs an Bord von Sternenzerstörern und TIE-Jägern statt X-Flüglern und Y-Flüglern dienten. In Sets ab 2002 veröffentlicht und in Todesstern- und imperialen Anlagen-Builds erscheinend, wurde diese Minifigur unter Droiden-Enthusiasten hochgradig sammelwürdig, begehrt aufgrund ihres markanten schwarzen Aussehens im Kontrast zu häufigeren Astromech-Farben, ihrer Seltenheit im Vergleich zu zahllosen R2-D2-Varianten und ihrer Darstellung imperialer technischer Überlegenheit, die die massive Flotte des Imperiums von Kriegsschiffen und Sternenjägern in der gesamten Galaxie aufrechterhielt.',
    fr: 'La minifigurine LEGO de R2-Q5 capture le rare droïde astromech Impérial avec son schéma de couleur noir et gris distinctif qui le distinguait des droïdes de la République bleus et blancs communs. Cette minifigurine présente une impression détaillée montrant des marques Impériales et le design de dôme caractéristique, représentant l\'une des rares unités astromech servant l\'Empire plutôt que les forces Rebelles. En tant que variante de droïde Impérial, R2-Q5 a montré comment l\'Empire a adapté la technologie de la République à ses propres fins, avec des astromechs servant à bord de Star Destroyers et de chasseurs TIE plutôt que des X-wings et Y-wings. Sortie dans des sets à partir de 2002 apparaissant dans les constructions de l\'Étoile de la Mort et des installations Impériales, cette minifigurine est devenue hautement collectionnable parmi les enthousiastes de droïdes, recherchée en raison de son apparence noire frappante contrastant avec les couleurs d\'astromech plus communes, sa rareté par rapport aux innombrables variantes R2-D2, et sa représentation de la supériorité technique Impériale qui maintenait la flotte massive de vaisseaux de guerre et de chasseurs stellaires de l\'Empire à travers la galaxie.',
    es: 'La minifigura LEGO de R2-Q5 captura al raro droide astromecánico Imperial con su distintivo esquema de color negro y gris que lo diferenciaba de los comunes droides de la República azules y blancos. Esta minifigura presenta impresión detallada mostrando marcas Imperiales y el característico diseño de cúpula, representando a una de las pocas unidades astromecánicas sirviendo al Imperio en lugar de las fuerzas Rebeldes. Como variante de droide Imperial, R2-Q5 mostró cómo el Imperio adaptó la tecnología de la República para sus propios propósitos, con astromecánicos sirviendo a bordo de Destructores Estelares y cazas TIE en lugar de X-wings e Y-wings. Lanzada en sets desde 2002 apareciendo en construcciones de la Estrella de la Muerte e instalaciones Imperiales, esta minifigura se volvió altamente coleccionable entre entusiastas de droides, buscada debido a su llamativa apariencia negra contrastando con colores astromecánicos más comunes, su rareza comparada con incontables variantes R2-D2, y su representación de superioridad técnica Imperial que mantuvo la masiva flota de naves de guerra y cazas estelares del Imperio a través de la galaxia.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 156-160 (sw0264-sw0268)...\n');

  for (const m of batch) {
    await prisma.minifigCatalog.upsert({
      where: { minifigure_no: m.no },
      update: {
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      },
      create: {
        minifigure_no: m.no,
        name: m.name,
        category_id: 1,
        category_name: 'Star Wars',
        search_name: m.name.toLowerCase(),
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`  ✅ ${m.no}: ${m.name}`);
  }

  console.log('\n✨ Batch 156-160 complete: 5 minifigs (20 descriptions)');
  await prisma.$disconnect();
}

saveBatch().catch(console.error);