import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch046 = [
  {
    no: 'sw0384',
    name: 'Clone Trooper (Episode 3, 212th Attack Battalion)',
    en: 'The 212th Attack Battalion served as one of the Republic\'s most distinguished military units during the Clone Wars, led by Jedi General Obi-Wan Kenobi and Clone Commander Cody, fighting in major campaigns from Utapau to Christophsis. This 2009 minifigure features Phase II armor with distinctive orange markings identifying the 212th, representing the elite troops who formed Obi-Wan\'s personal legion and participated in some of the war\'s most critical battles. Released in set 7676 (Republic Attack Gunship), this orange-marked trooper became highly valued by army builders for recreating Kenobi\'s forces. The 212th\'s prominent role in Revenge of the Sith, particularly the tragic execution of Order 66 on Utapau, gives this figure historical significance beyond its military aesthetics, and collectors often pair multiple 212th troopers with Commander Cody figures to build accurate battalion displays from the final days of the Clone Wars.',
    de: 'Das 212. Angriffsbataillon diente während der Klonkriege als eine der angesehensten Militäreinheiten der Republik, angeführt von Jedi-General Obi-Wan Kenobi und Klonkommandant Cody, und kämpfte in großen Kampagnen von Utapau bis Christophsis. Diese Minifigur von 2009 zeigt Phase-II-Rüstung mit markanten orangefarbenen Markierungen, die die 212. identifizieren, und repräsentiert die Elite-Truppen, die Obi-Wans persönliche Legion bildeten und an einigen der kritischsten Schlachten des Krieges teilnahmen. Veröffentlicht in Set 7676 (Republic Attack Gunship), wurde dieser orange markierte Truppen bei Armeebauern für die Nachstellung von Kenobis Streitkräften hoch geschätzt. Die prominente Rolle der 212. in Die Rache der Sith, insbesondere die tragische Ausführung von Order 66 auf Utapau, verleiht dieser Figur historische Bedeutung über ihre militärische Ästhetik hinaus, und Sammler paaren oft mehrere 212.-Truppen mit Commander-Cody-Figuren, um präzise Bataillonsdisplays aus den letzten Tagen der Klonkriege aufzubauen.',
    fr: 'Le 212e Bataillon d\'Attaque servait comme l\'une des unités militaires les plus distinguées de la République pendant la Guerre des Clones, dirigée par le Général Jedi Obi-Wan Kenobi et le Commandant Clone Cody, combattant dans des campagnes majeures d\'Utapau à Christophsis. Cette minifigurine de 2009 présente une armure Phase II avec des marques orange distinctives identifiant la 212e, représentant les troupes d\'élite qui formaient la légion personnelle d\'Obi-Wan et participaient à certaines des batailles les plus critiques de la guerre. Sortie dans le set 7676 (Canonnière d\'Attaque de la République), ce soldat marqué orange est devenu très apprécié par les constructeurs d\'armées pour recréer les forces de Kenobi. Le rôle proéminent de la 212e dans La Revanche des Sith, en particulier l\'exécution tragique de l\'Ordre 66 sur Utapau, donne à cette figurine une signification historique au-delà de son esthétique militaire, et les collectionneurs associent souvent plusieurs soldats de la 212e avec des figurines du Commandant Cody pour construire des présentations de bataillon précises des derniers jours de la Guerre des Clones.',
    es: 'El Batallón de Ataque 212 sirvió como una de las unidades militares más distinguidas de la República durante las Guerras Clon, liderada por el General Jedi Obi-Wan Kenobi y el Comandante Clon Cody, luchando en campañas importantes desde Utapau hasta Christophsis. Esta minifigura de 2009 presenta armadura Fase II con distintivas marcas naranjas identificando al 212, representando las tropas de élite que formaron la legión personal de Obi-Wan y participaron en algunas de las batallas más críticas de la guerra. Lanzado en el set 7676 (Cañonera de Ataque de la República), este soldado marcado en naranja se volvió altamente valorado por constructores de ejércitos para recrear las fuerzas de Kenobi. El papel prominente del 212 en La Venganza de los Sith, particularmente la trágica ejecución de la Orden 66 en Utapau, le da a esta figura significancia histórica más allá de su estética militar, y los coleccionistas a menudo emparejan múltiples soldados del 212 con figuras del Comandante Cody para construir exhibiciones precisas de batallón de los últimos días de las Guerras Clon.'
  },
  {
    no: 'sw0385',
    name: 'Clone Commander (501st Legion)',
    en: 'Clone Commanders in the 501st Legion served as Anakin Skywalker\'s trusted officers, leading "Vader\'s Fist" through some of the Clone Wars\' most intense campaigns and later participating in the assault on the Jedi Temple during Order 66. This 2009 minifigure features Phase II armor with blue 501st markings enhanced by specialized command-level detailing, including pauldron, rangefinder-equipped helmet, and kama waist skirt distinguishing officers from rank-and-file troopers. Released in set 7676 (Republic Attack Gunship), this commander variant represents the elite leadership tier of the Republic\'s most famous legion. The combination of 501st blue coloring and specialized officer equipment makes this figure particularly valuable for collectors building command squads, and it serves as an excellent stand-in for Captain Rex or other named 501st officers in large-scale Republic military displays showing Anakin\'s personal forces at their peak.',
    de: 'Klonkommandanten in der 501. Legion dienten als Anakin Skywalkers vertrauenswürdige Offiziere und führten "Vaders Faust" durch einige der intensivsten Kampagnen der Klonkriege und nahmen später am Angriff auf den Jedi-Tempel während Order 66 teil. Diese Minifigur von 2009 zeigt Phase-II-Rüstung mit blauen 501.-Markierungen, die durch spezialisierte Kommandodetails verstärkt werden, einschließlich Pauldron, mit Entfernungsmesser ausgestattetem Helm und Kama-Taillenrock, die Offiziere von einfachen Truppen unterscheiden. Veröffentlicht in Set 7676 (Republic Attack Gunship), repräsentiert diese Kommandantenvariante die Elite-Führungsebene der berühmtesten Legion der Republik. Die Kombination aus 501.-Blaufärbung und spezialisierter Offiziersausrüstung macht diese Figur besonders wertvoll für Sammler, die Kommandotrupps aufbauen, und sie dient als ausgezeichneter Ersatz für Captain Rex oder andere benannte 501.-Offiziere in groß angelegten republikanischen Militärdisplays, die Anakins persönliche Streitkräfte auf ihrem Höhepunkt zeigen.',
    fr: 'Les Commandants Clones de la 501e Légion servaient d\'officiers de confiance d\'Anakin Skywalker, dirigeant le "Poing de Vader" à travers certaines des campagnes les plus intenses de la Guerre des Clones et participant plus tard à l\'assaut sur le Temple Jedi pendant l\'Ordre 66. Cette minifigurine de 2009 présente une armure Phase II avec des marques bleues de la 501e améliorées par des détails spécialisés au niveau du commandement, y compris pauldron, casque équipé de télémètre et jupe de taille kama distinguant les officiers des soldats de base. Sortie dans le set 7676 (Canonnière d\'Attaque de la République), cette variante de commandant représente le niveau de leadership d\'élite de la légion la plus célèbre de la République. La combinaison de la coloration bleue de la 501e et de l\'équipement d\'officier spécialisé rend cette figurine particulièrement précieuse pour les collectionneurs construisant des escouades de commandement, et elle sert d\'excellent remplaçant pour le Capitaine Rex ou d\'autres officiers nommés de la 501e dans des présentations militaires de la République à grande échelle montrant les forces personnelles d\'Anakin à leur apogée.',
    es: 'Los Comandantes Clon en la Legión 501 sirvieron como oficiales de confianza de Anakin Skywalker, liderando "El Puño de Vader" a través de algunas de las campañas más intensas de las Guerras Clon y participando más tarde en el asalto al Templo Jedi durante la Orden 66. Esta minifigura de 2009 presenta armadura Fase II con marcas azules del 501 mejoradas por detalles especializados a nivel de comando, incluyendo pauldron, casco equipado con telémetro y falda de cintura kama distinguiendo oficiales de soldados rasos. Lanzado en el set 7676 (Cañonera de Ataque de la República), esta variante de comandante representa el nivel de liderazgo de élite de la legión más famosa de la República. La combinación de coloración azul del 501 y equipo de oficial especializado hace esta figura particularmente valiosa para coleccionistas construyendo escuadrones de comando, y sirve como un excelente sustituto para el Capitán Rex u otros oficiales nombrados del 501 en exhibiciones militares de la República a gran escala mostrando las fuerzas personales de Anakin en su apogeo.'
  },
  {
    no: 'sw0386',
    name: 'Mace Windu (75th Anniversary)',
    en: 'Mace Windu, the legendary Jedi Master and member of the High Council, appears in this special 75th Anniversary edition commemorating 75 years of The LEGO Group, representing one of the most powerful Jedi in the Order and Samuel L. Jackson\'s iconic character. This 2009 minifigure features detailed torso printing of Windu\'s Jedi robes with layered brown garments, his distinctive bald head piece with stern expression, and hands ready to wield his unique purple lightsaber blade. Released in set 7868 (Mace Windu\'s Jedi Starfighter), this anniversary variant includes the special chrome-finished purple lightsaber exclusive to 75th anniversary figures. The commemorative chrome lightsaber and Mace Windu\'s status as one of the most powerful Jedi make this figure highly collectible, and his pivotal role confronting Chancellor Palpatine in Revenge of the Sith ensures this minifigure remains essential for collectors building prequel-era Jedi Council displays.',
    de: 'Mace Windu, der legendäre Jedi-Meister und Mitglied des Hohen Rats, erscheint in dieser speziellen 75. Jubiläumsausgabe zum 75-jährigen Bestehen der LEGO Group und repräsentiert einen der mächtigsten Jedi im Orden und Samuel L. Jacksons ikonischen Charakter. Diese Minifigur von 2009 zeigt detaillierten Torso-Druck von Windus Jedi-Roben mit mehrschichtigen braunen Gewändern, sein markantes kahles Kopfteil mit strengem Ausdruck und Hände, die bereit sind, seine einzigartige violette Lichtschwertklinge zu schwingen. Veröffentlicht in Set 7868 (Mace Windus Jedi Starfighter), enthält diese Jubiläumsvariante das spezielle verchromte violette Lichtschwert, das exklusiv für 75-Jahr-Jubiläumsfiguren ist. Das Gedenk-Chrom-Lichtschwert und Mace Windus Status als einer der mächtigsten Jedi machen diese Figur sehr sammelwürdig, und seine entscheidende Rolle bei der Konfrontation mit Kanzler Palpatine in Die Rache der Sith stellt sicher, dass diese Minifigur für Sammler, die Jedi-Rats-Displays aus der Prequel-Ära aufbauen, unerlässlich bleibt.',
    fr: 'Mace Windu, le légendaire Maître Jedi et membre du Haut Conseil, apparaît dans cette édition spéciale du 75e anniversaire commémorant 75 ans du Groupe LEGO, représentant l\'un des Jedi les plus puissants de l\'Ordre et le personnage iconique de Samuel L. Jackson. Cette minifigurine de 2009 présente des impressions de torse détaillées des robes Jedi de Windu avec des vêtements bruns superposés, sa pièce de tête chauve distinctive avec une expression sévère, et des mains prêtes à manier sa lame de sabre laser violette unique. Sortie dans le set 7868 (Le Chasseur Stellaire Jedi de Mace Windu), cette variante d\'anniversaire inclut le sabre laser violet à finition chromée spécial exclusif aux figurines du 75e anniversaire. Le sabre laser chromé commémoratif et le statut de Mace Windu comme l\'un des Jedi les plus puissants rendent cette figurine très collectionnable, et son rôle pivot confrontant le Chancelier Palpatine dans La Revanche des Sith garantit que cette minifigurine reste essentielle pour les collectionneurs construisant des présentations du Conseil Jedi de l\'ère des préquelles.',
    es: 'Mace Windu, el legendario Maestro Jedi y miembro del Alto Consejo, aparece en esta edición especial del 75° Aniversario conmemorando 75 años del Grupo LEGO, representando a uno de los Jedi más poderosos de la Orden y el icónico personaje de Samuel L. Jackson. Esta minifigura de 2009 presenta impresiones de torso detalladas de las túnicas Jedi de Windu con prendas marrones en capas, su distintiva pieza de cabeza calva con expresión severa, y manos listas para blandir su única hoja de sable de luz púrpura. Lanzado en el set 7868 (Caza Estelar Jedi de Mace Windu), esta variante de aniversario incluye el sable de luz púrpura con acabado cromado especial exclusivo de figuras del 75° aniversario. El sable de luz cromado conmemorativo y el estatus de Mace Windu como uno de los Jedi más poderosos hacen esta figura altamente coleccionable, y su papel crucial confrontando al Canciller Palpatine en La Venganza de los Sith asegura que esta minifigura permanezca esencial para coleccionistas construyendo exhibiciones del Consejo Jedi de la era de precuelas.'
  },
  {
    no: 'sw0387',
    name: 'Astromech Droid (R2-D5)',
    en: 'R2-D5 is a red and white astromech droid briefly seen in A New Hope aboard the Jawa sandcrawler, nearly purchased by Uncle Owen before its motivator malfunctioned, leading to the fateful selection of R2-D2 instead. This 2009 minifigure features distinctive red dome and body panels with white accents and mechanical detailing, representing one of the background droids whose small moment changed galactic history. Released in set 7868 (Mace Windu\'s Jedi Starfighter), R2-D5\'s inclusion in a prequel-era set is anachronistic but provides collectors with this rarely-produced astromech variant. The red color scheme makes R2-D5 visually striking among astromech collections, and its connection to one of the saga\'s most pivotal "what if" moments gives this humble background droid surprising significance for completionist collectors seeking every named astromech from the films.',
    de: 'R2-D5 ist ein rot-weißer Astromech-Droide, der kurz in Eine neue Hoffnung an Bord des Jawa-Sandkriechers zu sehen ist und von Onkel Owen fast gekauft wurde, bevor sein Motivator ausfiel, was zur schicksalhaften Auswahl von R2-D2 führte. Diese Minifigur von 2009 zeigt eine markante rote Kuppel und Körperplatten mit weißen Akzenten und mechanischen Details und repräsentiert einen der Hintergrunddroiden, dessen kleiner Moment die galaktische Geschichte veränderte. Veröffentlicht in Set 7868 (Mace Windus Jedi Starfighter), ist R2-D5s Aufnahme in ein Prequel-Ära-Set anachronistisch, bietet Sammlern jedoch diese selten produzierte Astromech-Variante. Das rote Farbschema macht R2-D5 visuell auffällig unter Astromech-Sammlungen, und seine Verbindung zu einem der entscheidendsten "Was-wäre-wenn"-Momente der Saga verleiht diesem bescheidenen Hintergrunddroiden überraschende Bedeutung für Vervollständigungs-Sammler, die jeden benannten Astromech aus den Filmen suchen.',
    fr: 'R2-D5 est un droïde astromech rouge et blanc brièvement vu dans Un Nouvel Espoir à bord du véhicule des sables Jawa, presque acheté par l\'Oncle Owen avant que son motivateur ne tombe en panne, conduisant à la sélection fatidique de R2-D2 à la place. Cette minifigurine de 2009 présente un dôme et des panneaux de corps rouges distinctifs avec des accents blancs et des détails mécaniques, représentant l\'un des droïdes d\'arrière-plan dont le petit moment a changé l\'histoire galactique. Sortie dans le set 7868 (Le Chasseur Stellaire Jedi de Mace Windu), l\'inclusion de R2-D5 dans un set de l\'ère des préquelles est anachronique mais fournit aux collectionneurs cette variante d\'astromech rarement produite. Le schéma de couleurs rouges rend R2-D5 visuellement frappant parmi les collections d\'astromech, et sa connexion à l\'un des moments "et si" les plus cruciaux de la saga donne à ce humble droïde d\'arrière-plan une importance surprenante pour les collectionneurs complétistes recherchant chaque astromech nommé des films.',
    es: 'R2-D5 es un droide astromecánico rojo y blanco visto brevemente en Una Nueva Esperanza a bordo del vehiculo de arena Jawa, casi comprado por el Tío Owen antes de que su motivador funcionara mal, llevando a la fatídica selección de R2-D2 en su lugar. Esta minifigura de 2009 presenta distintiva cúpula roja y paneles de cuerpo con acentos blancos y detalles mecánicos, representando uno de los droides de fondo cuyo pequeño momento cambió la historia galáctica. Lanzado en el set 7868 (Caza Estelar Jedi de Mace Windu), la inclusión de R2-D5 en un set de la era de precuelas es anacrónica pero proporciona a los coleccionistas esta variante de astromecánico raramente producida. El esquema de color rojo hace a R2-D5 visualmente llamativo entre colecciones de astromecánicos, y su conexión a uno de los momentos "qué hubiera pasado si" más cruciales de la saga le da a este humilde droide de fondo significancia sorprendente para coleccionistas completistas buscando cada astromecánico nombrado de las películas.'
  },
  {
    no: 'sw0388',
    name: 'Clone Trooper (Episode 3, Clone Wars)',
    en: 'Clone Troopers in standard Phase II armor formed the backbone of the Grand Army of the Republic during the final years of the Clone Wars, representing the millions of identical soldiers who fought across thousands of worlds in the galaxy-spanning conflict. This 2009 minifigure features clean white Phase II armor with minimal markings, black body glove printing, and the streamlined helmet design introduced in Revenge of the Sith that replaced the earlier Phase I equipment. Released in set 8014 (Clone Walker Battle Pack), this standard white clone trooper variant became essential for army builders creating large-scale Republic forces without specialized unit markings. The plain white armor and affordable battle pack availability made this figure perfect for massing troops, and it represents the anonymous clone soldiers whose sacrifice and ultimate betrayal during Order 66 defined the tragic end of the Republic era.',
    de: 'Klontruppen in Standard-Phase-II-Rüstung bildeten das Rückgrat der Großen Armee der Republik während der letzten Jahre der Klonkriege und repräsentierten die Millionen identischer Soldaten, die auf Tausenden von Welten im galaxisweiten Konflikt kämpften. Diese Minifigur von 2009 zeigt saubere weiße Phase-II-Rüstung mit minimalen Markierungen, schwarzem Körperanzug-Druck und dem stromlinienförmigen Helmdesign, das in Die Rache der Sith eingeführt wurde und die frühere Phase-I-Ausrüstung ersetzte. Veröffentlicht in Set 8014 (Clone Walker Battle Pack), wurde diese Standard-Weiß-Klontruppen-Variante für Armeebauer unerlässlich, die groß angelegte republikanische Streitkräfte ohne spezialisierte Einheitsmarkierungen erschaffen. Die einfache weiße Rüstung und die erschwingliche Battle-Pack-Verfügbarkeit machten diese Figur perfekt für Massierung von Truppen, und sie repräsentiert die anonymen Klonsoldaten, deren Opfer und ultimativer Verrat während Order 66 das tragische Ende der Republik-Ära definierten.',
    fr: 'Les Clone Troopers en armure Phase II standard formaient l\'épine dorsale de la Grande Armée de la République pendant les dernières années de la Guerre des Clones, représentant les millions de soldats identiques qui ont combattu à travers des milliers de mondes dans le conflit à l\'échelle galactique. Cette minifigurine de 2009 présente une armure Phase II blanche propre avec un minimum de marques, des impressions de combinaison corporelle noire et le design de casque épuré introduit dans La Revanche des Sith qui a remplacé l\'équipement Phase I antérieur. Sortie dans le set 8014 (Battle Pack Clone Walker), cette variante standard de clone trooper blanc est devenue essentielle pour les constructeurs d\'armées créant des forces de la République à grande échelle sans marques d\'unité spécialisées. L\'armure blanche simple et la disponibilité en battle pack abordable ont rendu cette figurine parfaite pour masser les troupes, et elle représente les soldats clones anonymes dont le sacrifice et la trahison ultime pendant l\'Ordre 66 ont défini la fin tragique de l\'ère de la République.',
    es: 'Los Clone Troopers en armadura Fase II estándar formaron la columna vertebral del Gran Ejército de la República durante los últimos años de las Guerras Clon, representando los millones de soldados idénticos que lucharon a través de miles de mundos en el conflicto que abarcó la galaxia. Esta minifigura de 2009 presenta armadura blanca Fase II limpia con marcas mínimas, impresiones de traje de cuerpo negro y el diseño de casco aerodinámico introducido en La Venganza de los Sith que reemplazó el equipo Fase I anterior. Lanzado en el set 8014 (Battle Pack Clone Walker), esta variante de clone trooper blanco estándar se volvió esencial para constructores de ejércitos creando fuerzas de la República a gran escala sin marcas de unidades especializadas. La armadura blanca simple y disponibilidad asequible en battle pack hicieron esta figura perfecta para amasar tropas, y representa los soldados clon anónimos cuyo sacrificio y traición final durante la Orden 66 definió el trágico final de la era de la República.'
  },
  {
    no: 'sw0389',
    name: 'Luminara Unduli',
    en: 'Luminara Unduli, a wise Mirialan Jedi Master on the High Council, served as one of the Republic\'s most skilled generals during the Clone Wars, known for her calm demeanor and tactical brilliance leading campaigns alongside her Padawan Barriss Offee. This 2009 minifigure captures Luminara\'s distinctive appearance with green Mirialan skin tone, black diamond facial tattoos marking her species, detailed printing of her dark robes with ornate collar and headpiece, and her characteristic lightsaber. Released in set 8091 (Republic Swamp Speeder), this figure represents one of the few female Jedi Masters from the prequel era to receive minifigure form. Luminara\'s unique appearance and tragic fate during Order 66 make this figure significant for collectors building comprehensive Jedi Council displays, and her role in The Clone Wars animated series cemented her status as a fan-favorite character worthy of inclusion in any prequel-era collection.',
    de: 'Luminara Unduli, eine weise Mirialan-Jedi-Meisterin im Hohen Rat, diente während der Klonkriege als eine der geschicktesten Generäle der Republik, bekannt für ihre ruhige Haltung und taktische Brillanz bei der Leitung von Kampagnen neben ihrer Padawan Barriss Offee. Diese Minifigur von 2009 fängt Luminaras markantes Aussehen mit grünem Mirialan-Hautton, schwarzen Diamanten-Gesichtstattoos, die ihre Spezies markieren, detailliertem Druck ihrer dunklen Roben mit verziertem Kragen und Kopfschmuck sowie ihrem charakteristischen Lichtschwert ein. Veröffentlicht in Set 8091 (Republic Swamp Speeder), repräsentiert diese Figur eine der wenigen weiblichen Jedi-Meisterinnen aus der Prequel-Ära, die Minifigur-Form erhielten. Luminaras einzigartiges Aussehen und tragisches Schicksal während Order 66 machen diese Figur bedeutsam für Sammler, die umfassende Jedi-Rats-Displays aufbauen, und ihre Rolle in der animierten Serie The Clone Wars zementierte ihren Status als Fan-Lieblingscharakter, der es wert ist, in jede Sammlung aus der Prequel-Ära aufgenommen zu werden.',
    fr: 'Luminara Unduli, une sage Maître Jedi Mirialan du Haut Conseil, a servi comme l\'un des généraux les plus qualifiés de la République pendant la Guerre des Clones, connue pour son comportement calme et sa brillance tactique dirigeant des campagnes aux côtés de sa Padawan Barriss Offee. Cette minifigurine de 2009 capture l\'apparence distinctive de Luminara avec un teint de peau Mirialan vert, des tatouages faciaux en diamants noirs marquant son espèce, des impressions détaillées de ses robes sombres avec un col orné et une coiffe, et son sabre laser caractéristique. Sortie dans le set 8091 (Speeder des Marais de la République), cette figurine représente l\'une des rares Maîtres Jedi féminines de l\'ère des préquelles à recevoir une forme de minifigurine. L\'apparence unique de Luminara et son destin tragique pendant l\'Ordre 66 rendent cette figurine significative pour les collectionneurs construisant des présentations complètes du Conseil Jedi, et son rôle dans la série animée The Clone Wars a cimenté son statut de personnage favori des fans digne d\'être inclus dans toute collection de l\'ère des préquelles.',
    es: 'Luminara Unduli, una sabia Maestra Jedi Mirialan del Alto Consejo, sirvió como una de las generales más hábiles de la República durante las Guerras Clon, conocida por su comportamiento calmado y brillantez táctica liderando campañas junto a su Padawan Barriss Offee. Esta minifigura de 2009 captura la apariencia distintiva de Luminara con tono de piel Mirialan verde, tatuajes faciales de diamante negro marcando su especie, impresiones detalladas de sus túnicas oscuras con cuello ornamentado y tocado, y su característico sable de luz. Lanzada en el set 8091 (Speeder del Pantano de la República), esta figura representa una de las pocas Maestras Jedi femeninas de la era de precuelas en recibir forma de minifigura. La apariencia única de Luminara y su trágico destino durante la Orden 66 hacen esta figura significativa para coleccionistas construyendo exhibiciones completas del Consejo Jedi, y su papel en la serie animada The Clone Wars cementó su estatus como personaje favorito de los fanáticos digno de inclusión en cualquier colección de la era de precuelas.'
  },
  {
    no: 'sw0390',
    name: 'Battle Droid (with Binoculars)',
    en: 'Battle Droids equipped with electrobinoculars served as reconnaissance and forward observation units in the Separatist droid armies, scanning battlefields and coordinating artillery strikes during the Clone Wars. This 2009 minifigure features the standard tan battle droid body construction with specialized printing showing equipment harness, and importantly includes black electrobinocular accessories for surveillance duties. Released in set 8091 (Republic Swamp Speeder), this variant adds functional variety to Separatist forces beyond standard infantry droids. The binocular accessory and scout designation make this battle droid useful for dioramas depicting Separatist reconnaissance operations, and collectors building large droid armies appreciate having specialized variants like scouts and observers to create more realistic and tactically diverse Separatist military displays beyond endless ranks of identical gun-wielding droids.',
    de: 'Kampfdroiden, die mit Elektroferngläsern ausgestattet sind, dienten in den Separatistendroideenarmeen als Aufklärungs- und Vorwärtsbeobachtungseinheiten, scannten Schlachtfelder und koordinierten Artillerieschläge während der Klonkriege. Diese Minifigur von 2009 zeigt die standardmäßige beige Kampfdroiden-Körperkonstruktion mit spezialisiertem Druck, der Ausrüstungsgeschirr zeigt, und enthält wichtigerweise schwarze Elektrofernglas-Zubehörteile für Überwachungsaufgaben. Veröffentlicht in Set 8091 (Republic Swamp Speeder), fügt diese Variante den Separatistenstreitkräften funktionale Vielfalt über Standard-Infanteriedroiden hinaus hinzu. Das Fernglas-Zubehör und die Späher-Bezeichnung machen diesen Kampfdroiden nützlich für Dioramen, die Separatisten-Aufklärungsoperationen darstellen, und Sammler, die große Droideenarmeen aufbauen, schätzen es, spezialisierte Varianten wie Späher und Beobachter zu haben, um realistischere und taktisch vielfältigere Separatisten-Militärdisplays über endlose Reihen identischer waffenschwingender Droiden hinaus zu erschaffen.',
    fr: 'Les Droïdes de Combat équipés de jumelles électroniques servaient d\'unités de reconnaissance et d\'observation avancée dans les armées de droïdes Séparatistes, scannant les champs de bataille et coordonnant les frappes d\'artillerie pendant la Guerre des Clones. Cette minifigurine de 2009 présente la construction de corps de droïde de combat beige standard avec une impression spécialisée montrant un harnais d\'équipement, et comprend surtout des accessoires de jumelles électroniques noires pour les tâches de surveillance. Sortie dans le set 8091 (Speeder des Marais de la République), cette variante ajoute une variété fonctionnelle aux forces Séparatistes au-delà des droïdes d\'infanterie standard. L\'accessoire de jumelles et la désignation d\'éclaireur rendent ce droïde de combat utile pour les dioramas représentant des opérations de reconnaissance Séparatistes, et les collectionneurs construisant de grandes armées de droïdes apprécient d\'avoir des variantes spécialisées comme des éclaireurs et des observateurs pour créer des présentations militaires Séparatistes plus réalistes et tactiquement diverses au-delà de rangs sans fin de droïdes identiques brandissant des armes.',
    es: 'Los Droides de Batalla equipados con electrobinoculares sirvieron como unidades de reconocimiento y observación avanzada en los ejércitos de droides Separatistas, escaneando campos de batalla y coordinando ataques de artillería durante las Guerras Clon. Esta minifigura de 2009 presenta la construcción estándar de cuerpo de droide de batalla beige con impresiones especializadas mostrando arnés de equipo, e importantemente incluye accesorios de electrobinoculares negros para deberes de vigilancia. Lanzado en el set 8091 (Speeder del Pantano de la República), esta variante agrega variedad funcional a las fuerzas Separatistas más allá de droides de infantería estándar. El accesorio de binoculares y la designación de explorador hacen este droide de batalla útil para dioramas representando operaciones de reconocimiento Separatistas, y coleccionistas construyendo grandes ejércitos de droides aprecian tener variantes especializadas como exploradores y observadores para crear exhibiciones militares Separatistas más realistas y tácticamente diversas más allá de filas interminables de droides idénticos empuñando armas.'
  },
  {
    no: 'sw0391',
    name: 'Clone Trooper (Episode 3, Swamp Camo)',
    en: 'Clone Troopers in swamp camouflage armor served in specialized wetland and jungle environment operations during the Clone Wars, deployed to planets with dense vegetation and aquatic terrain like Kashyyyk, Felucia, and other humid battlefields. This 2009 minifigure features Phase II armor with distinctive green and brown camouflage printing designed to blend into forested environments, representing the Republic\'s environmental adaptation doctrine that equipped troops for specific planetary conditions. Released in set 8091 (Republic Swamp Speeder), this swamp camo variant provides collectors with another specialized clone color scheme for diversifying their armies. The green camouflage pattern and its association with battles on lush forest worlds make this trooper essential for recreating specific campaign settings, and army builders value having environmental variants to accurately represent the Republic\'s tactical flexibility across the galaxy\'s diverse biomes.',
    de: 'Klontruppen in Sumpftarnrüstung dienten in spezialisierten Feuchtgebiets- und Dschungelumgebungsoperationen während der Klonkriege und wurden auf Planeten mit dichter Vegetation und aquatischem Terrain wie Kashyyyk, Felucia und anderen feuchten Schlachtfeldern eingesetzt. Diese Minifigur von 2009 zeigt Phase-II-Rüstung mit markanter grün-brauner Tarnbedruckung, die entwickelt wurde, um sich in bewaldete Umgebungen einzufügen, und repräsentiert die Umweltanpassungsdoktrin der Republik, die Truppen für spezifische planetare Bedingungen ausrüstete. Veröffentlicht in Set 8091 (Republic Swamp Speeder), bietet diese Sumpftarn-Variante Sammlern ein weiteres spezialisiertes Klon-Farbschema zur Diversifizierung ihrer Armeen. Das grüne Tarnmuster und seine Verbindung mit Schlachten auf üppigen Waldwelten machen diesen Truppen unerlässlich für die Nachstellung spezifischer Kampagneneinstellungen, und Armeebauer schätzen Umweltvarianten, um die taktische Flexibilität der Republik über die vielfältigen Biome der Galaxis hinweg genau darzustellen.',
    fr: 'Les Clone Troopers en armure de camouflage des marais servaient dans des opérations spécialisées en zones humides et en jungle pendant la Guerre des Clones, déployés sur des planètes avec une végétation dense et un terrain aquatique comme Kashyyyk, Felucia et d\'autres champs de bataille humides. Cette minifigurine de 2009 présente une armure Phase II avec une impression de camouflage vert et brun distinctive conçue pour se fondre dans les environnements forestiers, représentant la doctrine d\'adaptation environnementale de la République qui équipait les troupes pour des conditions planétaires spécifiques. Sortie dans le set 8091 (Speeder des Marais de la République), cette variante de camouflage des marais fournit aux collectionneurs un autre schéma de couleurs de clone spécialisé pour diversifier leurs armées. Le motif de camouflage vert et son association avec les batailles sur des mondes forestiers luxuriants rendent ce soldat essentiel pour recréer des décors de campagne spécifiques, et les constructeurs d\'armées apprécient d\'avoir des variantes environnementales pour représenter avec précision la flexibilité tactique de la République à travers les biomes diversifiés de la galaxie.',
    es: 'Los Clone Troopers en armadura de camuflaje de pantano sirvieron en operaciones especializadas de humedales y selva durante las Guerras Clon, desplegados en planetas con vegetación densa y terreno acuático como Kashyyyk, Felucia y otros campos de batalla húmedos. Esta minifigura de 2009 presenta armadura Fase II con distintivas impresiones de camuflaje verde y marrón diseñadas para mezclarse con ambientes forestales, representando la doctrina de adaptación ambiental de la República que equipó tropas para condiciones planetarias específicas. Lanzado en el set 8091 (Speeder del Pantano de la República), esta variante de camuflaje de pantano proporciona a los coleccionistas otro esquema de color de clon especializado para diversificar sus ejércitos. El patrón de camuflaje verde y su asociación con batallas en mundos forestales exuberantes hacen este soldado esencial para recrear configuraciones de campaña específicas, y constructores de ejércitos valoran tener variantes ambientales para representar con precisión la flexibilidad táctica de la República a través de los diversos biomas de la galaxia.'
  },
  {
    no: 'sw0392',
    name: 'Clone Trooper (Episode 3, Clone Wars, Light Bluish Gray)',
    en: 'This Clone Trooper variant features Phase II armor molded in light bluish gray plastic rather than standard white, representing either weathered and battle-worn armor or specialized stealth operations equipment used during the Clone Wars. The 2009 minifigure maintains standard Phase II design elements with black body glove printing and helmet details, but the gray coloring creates a distinctly different aesthetic from standard white clone troopers. Released in set 8091 (Republic Swamp Speeder), this gray armor variant is somewhat unusual and debated among collectors regarding its canonical intent—whether representing dirty/worn armor or a deliberate tactical color choice. The unique gray coloring makes this clone trooper stand out in collections, and some builders use these figures to represent veterans with battle-damaged equipment or specialized units operating in low-visibility conditions, adding visual variety to Republic military displays.',
    de: 'Diese Klontruppen-Variante zeigt Phase-II-Rüstung, die in hellblaugrauem Kunststoff statt in Standardweiß geformt ist, und repräsentiert entweder verwitterte und kampfabgenutzte Rüstung oder spezialisierte Tarnoperationsausrüstung, die während der Klonkriege verwendet wurde. Die Minifigur von 2009 behält standardmäßige Phase-II-Designelemente mit schwarzem Körperanzug-Druck und Helmdetails bei, aber die graue Färbung schafft eine deutlich andere Ästhetik als standardmäßige weiße Klontruppen. Veröffentlicht in Set 8091 (Republic Swamp Speeder), ist diese graue Rüstungsvariante etwas ungewöhnlich und unter Sammlern bezüglich ihrer kanonischen Absicht diskutiert – ob sie schmutzige/abgenutzte Rüstung oder eine bewusste taktische Farbwahl repräsentiert. Die einzigartige graue Färbung lässt diesen Klontruppler in Sammlungen hervorstechen, und einige Bauer verwenden diese Figuren, um Veteranen mit kampfbeschädigter Ausrüstung oder spezialisierte Einheiten darzustellen, die unter Bedingungen geringer Sichtbarkeit operieren, was republikanischen Militärdisplays visuelle Vielfalt hinzufügt.',
    fr: 'Cette variante de Clone Trooper présente une armure Phase II moulée en plastique gris bleuâtre clair plutôt qu\'en blanc standard, représentant soit une armure usée et marquée par les combats, soit un équipement d\'opérations furtives spécialisées utilisé pendant la Guerre des Clones. La minifigurine de 2009 conserve les éléments de design Phase II standard avec des impressions de combinaison corporelle noire et des détails de casque, mais la coloration grise crée une esthétique distinctement différente des clone troopers blancs standard. Sortie dans le set 8091 (Speeder des Marais de la République), cette variante d\'armure grise est quelque peu inhabituelle et débattue parmi les collectionneurs concernant son intention canonique—qu\'elle représente une armure sale/usée ou un choix de couleur tactique délibéré. La coloration grise unique fait ressortir ce clone trooper dans les collections, et certains constructeurs utilisent ces figurines pour représenter des vétérans avec un équipement endommagé au combat ou des unités spécialisées opérant dans des conditions de faible visibilité, ajoutant une variété visuelle aux présentations militaires de la République.',
    es: 'Esta variante de Clone Trooper presenta armadura Fase II moldeada en plástico gris azulado claro en lugar de blanco estándar, representando armadura desgastada y gastada por batalla o equipo de operaciones sigilosas especializadas usado durante las Guerras Clon. La minifigura de 2009 mantiene elementos de diseño Fase II estándar con impresiones de traje de cuerpo negro y detalles de casco, pero la coloración gris crea una estética distintamente diferente de los clone troopers blancos estándar. Lanzado en el set 8091 (Speeder del Pantano de la República), esta variante de armadura gris es algo inusual y debatida entre coleccionistas respecto a su intención canónica—si representa armadura sucia/gastada o una elección de color táctica deliberada. La coloración gris única hace destacar este clone trooper en colecciones, y algunos constructores usan estas figuras para representar veteranos con equipo dañado en batalla o unidades especializadas operando en condiciones de baja visibilidad, agregando variedad visual a exhibiciones militares de la República.'
  },
  {
    no: 'sw0393',
    name: 'Clone Trooper (Episode 3, 41st Elite Corps)',
    en: 'The 41st Elite Corps served as a prestigious Republic military unit during the Clone Wars, led by Jedi General Luminara Unduli and known for their operations in challenging environments including jungle and swamp terrain. This 2009 minifigure features Phase II armor with distinctive green markings and camouflage patterns identifying the 41st Elite Corps, representing the specialized troopers who fought alongside Luminara on planets like Kashyyyk during the final days of the war. Released in set 8091 (Republic Swamp Speeder), this green-marked variant became highly sought after by army builders for its unique color scheme and elite unit designation. The 41st\'s prominence in Revenge of the Sith during the tragic Order 66 sequence on Kashyyyk gives this figure historical significance, and collectors often build squads of 41st troopers to pair with Luminara Unduli figures, creating complete Elite Corps displays from the prequel trilogy\'s climactic battles.',
    de: 'Das 41. Elite-Korps diente während der Klonkriege als prestigeträchtige republikanische Militäreinheit, angeführt von Jedi-General Luminara Unduli und bekannt für ihre Operationen in herausfordernden Umgebungen einschließlich Dschungel- und Sumpfgelände. Diese Minifigur von 2009 zeigt Phase-II-Rüstung mit markanten grünen Markierungen und Tarnmustern, die das 41. Elite-Korps identifizieren, und repräsentiert die spezialisierten Truppen, die während der letzten Tage des Krieges neben Luminara auf Planeten wie Kashyyyk kämpften. Veröffentlicht in Set 8091 (Republic Swamp Speeder), wurde diese grün markierte Variante von Armeebauern für ihr einzigartiges Farbschema und ihre Elite-Einheitsbezeichnung sehr begehrt. Die Prominenz des 41. in Die Rache der Sith während der tragischen Order-66-Sequenz auf Kashyyyk verleiht dieser Figur historische Bedeutung, und Sammler bauen oft Trupps von 41.-Truppen, um sie mit Luminara-Unduli-Figuren zu paaren und vollständige Elite-Korps-Displays aus den klimaktischen Schlachten der Prequel-Trilogie zu erstellen.',
    fr: 'Le 41e Corps d\'Élite servait comme une unité militaire prestigieuse de la République pendant la Guerre des Clones, dirigée par le Général Jedi Luminara Unduli et connue pour ses opérations dans des environnements difficiles, y compris les terrains de jungle et de marais. Cette minifigurine de 2009 présente une armure Phase II avec des marques vertes distinctives et des motifs de camouflage identifiant le 41e Corps d\'Élite, représentant les soldats spécialisés qui ont combattu aux côtés de Luminara sur des planètes comme Kashyyyk pendant les derniers jours de la guerre. Sortie dans le set 8091 (Speeder des Marais de la République), cette variante marquée de vert est devenue très recherchée par les constructeurs d\'armées pour son schéma de couleurs unique et sa désignation d\'unité d\'élite. La proéminence du 41e dans La Revanche des Sith pendant la séquence tragique de l\'Ordre 66 sur Kashyyyk donne à cette figurine une importance historique, et les collectionneurs construisent souvent des escouades de soldats du 41e pour les associer avec des figurines de Luminara Unduli, créant des présentations complètes du Corps d\'Élite des batailles culminantes de la trilogie des préquelles.',
    es: 'El Cuerpo de Élite 41 sirvió como una prestigiosa unidad militar de la República durante las Guerras Clon, liderada por la General Jedi Luminara Unduli y conocida por sus operaciones en ambientes desafiantes incluyendo terreno de selva y pantano. Esta minifigura de 2009 presenta armadura Fase II con distintivas marcas verdes y patrones de camuflaje identificando al Cuerpo de Élite 41, representando a los soldados especializados que lucharon junto a Luminara en planetas como Kashyyyk durante los días finales de la guerra. Lanzado en el set 8091 (Speeder del Pantano de la República), esta variante marcada en verde se volvió altamente codiciada por constructores de ejércitos por su esquema de color único y designación de unidad de élite. La prominencia del 41 en La Venganza de los Sith durante la trágica secuencia de la Orden 66 en Kashyyyk le da a esta figura significancia histórica, y los coleccionistas a menudo construyen escuadrones de soldados del 41 para emparejar con figuras de Luminara Unduli, creando exhibiciones completas del Cuerpo de Élite de las batallas climáticas de la trilogía de precuelas.'
  }
];

async function saveBatch046() {
  console.log('💾 Saving batch 046 (sw0384-sw0393) - 10 minifigs...\n');

  let saved = 0;
  let skipped = 0;

  for (const m of batch046) {
    try {
      await prisma.minifigCatalog.update({
        where: { minifigure_no: m.no },
        data: {
          description_en: m.en,
          description_de: m.de,
          description_fr: m.fr,
          description_es: m.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        }
      });
      console.log(`  ✅ ${m.no}: ${m.name}`);
      saved++;
    } catch (error: any) {
      console.log(`  ⚠️  ${m.no}: NOT IN DATABASE (skipped)`);
      skipped++;
    }
  }

  console.log(`\n✨ Batch 046 complete: ${saved} saved, ${skipped} skipped (${saved * 4} descriptions)\n`);

  await prisma.$disconnect();
}

saveBatch046().catch(console.error);
