import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0409',
    name: 'Sebulba',
    en: 'Sebulba is the aggressive Dug podracer pilot and Anakin Skywalker\'s main rival in the Boonta Eve Classic podrace on Tatooine in The Phantom Menace. This minifigure captures Sebulba\'s distinctive alien appearance with his elongated snout, arms used as legs, orange flight suit, and racing goggles. Known for his dirty racing tactics and violent temperament, Sebulba represents the dangerous competition Anakin faces. Released in podracer sets, this unique minifigure is essential for recreating the iconic racing sequence and represents one of the Prequel trilogy\'s most memorable alien characters.',
    de: 'Sebulba ist der aggressive Dug-Podracer-Pilot und Anakin Skywalkers Hauptrivale im Boonta-Eve-Classic-Podrennen auf Tatooine in Die dunkle Bedrohung. Diese Minifigur erfasst Sebulbas charakteristisches außerirdisches Aussehen mit seiner verlängerten Schnauze, als Beine verwendeten Armen, orangenem Fluganzug und Rennbrille. Bekannt für seine schmutzigen Renntaktiken und gewalttätiges Temperament, repräsentiert Sebulba die gefährliche Konkurrenz, der Anakin gegenübersteht. Veröffentlicht in Podracer-Sets, ist diese einzigartige Minifigur unerlässlich für die Nachstellung der ikonischen Rennsequenz und repräsentiert eine der einprägsamsten außerirdischen Charaktere der Prequel-Trilogie.',
    fr: 'Sebulba est le pilote de podracer Dug agressif et principal rival d\'Anakin Skywalker dans la course Boonta Eve Classic sur Tatooine dans La Menace Fantôme. Cette minifigurine capture l\'apparence extraterrestre distinctive de Sebulba avec son museau allongé, bras utilisés comme jambes, combinaison de vol orange, et lunettes de course. Connu pour ses tactiques de course sales et son tempérament violent, Sebulba représente la compétition dangereuse à laquelle Anakin fait face. Sortie dans des sets de podracer, cette minifigurine unique est essentielle pour recréer la séquence de course iconique et représente l\'un des personnages extraterrestres les plus mémorables de la Trilogie Prequel.',
    es: 'Sebulba es el agresivo piloto de carreras de pods Dug y principal rival de Anakin Skywalker en la carrera Clásico Boonta Eve en Tatooine en La Amenaza Fantasma. Esta minifigura captura la distintiva apariencia alienígena de Sebulba con su hocico alargado, brazos usados como piernas, traje de vuelo naranja y gafas de carreras. Conocido por sus tácticas de carreras sucias y temperamento violento, Sebulba representa la competencia peligrosa que Anakin enfrenta. Lanzada en sets de carreras de pods, esta minifigura única es esencial para recrear la icónica secuencia de carreras y representa uno de los personajes alienígenas más memorables de la Trilogía Precuela.'
  },
  {
    no: 'sw0410',
    name: 'Watto',
    en: 'Watto is the Toydarian junk dealer and slave owner who owned Anakin and Shmi Skywalker on Tatooine in The Phantom Menace. This minifigure depicts the flying alien merchant with his distinctive trunk-like snout, small wings, blue skin, and shabby clothing. Despite his greed and ownership of slaves, Watto is portrayed as a shrewd businessman rather than cruel. Released in Tatooine marketplace and podracer sets, this unique minifigure adds authenticity to Tatooine scenes and represents an important character in Anakin\'s backstory.',
    de: 'Watto ist der Toydarianische Trödelhändler und Sklavenbesitzer, der Anakin und Shmi Skywalker auf Tatooine in Die dunkle Bedrohung besaß. Diese Minifigur zeigt den fliegenden außerirdischen Händler mit seiner charakteristischen rüsselartigen Schnauze, kleinen Flügeln, blauer Haut und schäbiger Kleidung. Trotz seiner Gier und seines Besitzes von Sklaven wird Watto eher als gerissener Geschäftsmann denn als grausam dargestellt. Veröffentlicht in Tatooine-Marktplatz- und Podracer-Sets, fügt diese einzigartige Minifigur Authentizität zu Tatooine-Szenen hinzu und repräsentiert einen wichtigen Charakter in Anakins Hintergrundgeschichte.',
    fr: 'Watto est le marchand de ferraille Toydarien et propriétaire d\'esclaves qui possédait Anakin et Shmi Skywalker sur Tatooine dans La Menace Fantôme. Cette minifigurine dépeint le marchand extraterrestre volant avec son museau distinctif en forme de trompe, petites ailes, peau bleue, et vêtements miteux. Malgré son avidité et sa propriété d\'esclaves, Watto est dépeint comme un homme d\'affaires rusé plutôt que cruel. Sortie dans des sets de marché Tatooine et podracer, cette minifigurine unique ajoute de l\'authenticité aux scènes de Tatooine et représente un personnage important dans l\'histoire de fond d\'Anakin.',
    es: 'Watto es el comerciante de chatarra Toydarian y dueño de esclavos que poseía a Anakin y Shmi Skywalker en Tatooine en La Amenaza Fantasma. Esta minifigura representa al comerciante alienígena volador con su distintivo hocico similar a trompa, pequeñas alas, piel azul y ropa andrajosa. A pesar de su codicia y propiedad de esclavos, Watto es retratado como un hombre de negocios astuto en lugar de cruel. Lanzada en sets de mercado de Tatooine y carreras de pods, esta minifigura única añade autenticidad a las escenas de Tatooine y representa un personaje importante en la historia de fondo de Anakin.'
  },
  {
    no: 'sw0411',
    name: 'Jar Jar Binks',
    en: 'Jar Jar Binks is the clumsy Gungan outcast who befriends Qui-Gon Jinn and plays a pivotal role in forging the alliance between Naboo and the Gungans in The Phantom Menace. This minifigure depicts Jar Jar with his distinctive long ears, eye stalks, orange and yellow coloring, and awkward posture. Despite being one of the most controversial characters in Star Wars history, Jar Jar represents comic relief and ultimately helps save Naboo. Released in various Phantom Menace sets, this minifigure is essential for complete Naboo collections and represents an undeniably significant character in the Prequel trilogy.',
    de: 'Jar Jar Binks ist der tollpatschige Gungan-Ausgestoßene, der sich mit Qui-Gon Jinn anfreundet und eine entscheidende Rolle beim Schmieden der Allianz zwischen Naboo und den Gungans in Die dunkle Bedrohung spielt. Diese Minifigur zeigt Jar Jar mit seinen charakteristischen langen Ohren, Augenstielen, oranger und gelber Färbung und unbeholfener Haltung. Trotz der Tatsache, dass er eine der umstrittensten Figuren in der Star Wars-Geschichte ist, repräsentiert Jar Jar komische Erleichterung und hilft letztendlich, Naboo zu retten. Veröffentlicht in verschiedenen Die dunkle Bedrohung-Sets, ist diese Minifigur unerlässlich für vollständige Naboo-Sammlungen und repräsentiert eine unbestreitbar bedeutende Figur in der Prequel-Trilogie.',
    fr: 'Jar Jar Binks est le Gungan maladroit paria qui se lie d\'amitié avec Qui-Gon Jinn et joue un rôle pivot dans la forge de l\'alliance entre Naboo et les Gungans dans La Menace Fantôme. Cette minifigurine dépeint Jar Jar avec ses longues oreilles distinctives, tiges oculaires, coloration orange et jaune, et posture maladroite. Malgré le fait d\'être l\'un des personnages les plus controversés de l\'histoire de Star Wars, Jar Jar représente le soulagement comique et aide finalement à sauver Naboo. Sortie dans divers sets La Menace Fantôme, cette minifigurine est essentielle pour les collections Naboo complètes et représente un personnage indéniablement significatif dans la Trilogie Prequel.',
    es: 'Jar Jar Binks es el torpe Gungan proscrito que se hace amigo de Qui-Gon Jinn y juega un papel fundamental en forjar la alianza entre Naboo y los Gungans en La Amenaza Fantasma. Esta minifigura representa a Jar Jar con sus distintivas orejas largas, tallos oculares, coloración naranja y amarilla, y postura torpe. A pesar de ser uno de los personajes más controvertidos en la historia de Star Wars, Jar Jar representa alivio cómico y finalmente ayuda a salvar Naboo. Lanzada en varios sets de La Amenaza Fantasma, esta minifigura es esencial para colecciones completas de Naboo y representa un personaje innegablemente significativo en la Trilogía Precuela.'
  },
  {
    no: 'sw0412',
    name: 'Boss Nass',
    en: 'Boss Nass is the booming-voiced leader of the Gungan people who rules Otoh Gunga and commands the Grand Army during the Battle of Naboo in The Phantom Menace. This minifigure depicts the imposing Gungan leader with his distinctive large build, elaborate headdress, ceremonial robes, and authority staff. Initially reluctant to help the Naboo surface dwellers, Boss Nass ultimately agrees to the alliance that saves the planet. Released in limited Gungan and battle sets, this minifigure represents Gungan leadership and is valued by collectors seeking complete Naboo battle scenes.',
    de: 'Boss Nass ist der dröhnend-stimmige Anführer des Gungan-Volkes, der Otoh Gunga regiert und die Große Armee während der Schlacht um Naboo in Die dunkle Bedrohung kommandiert. Diese Minifigur zeigt den eindrucksvollen Gungan-Anführer mit seinem charakteristischen großen Körperbau, aufwendigem Kopfschmuck, zeremoniellen Roben und Autoritätsstab. Anfänglich widerwillig, den Naboo-Oberflächenbewohnern zu helfen, stimmt Boss Nass letztendlich der Allianz zu, die den Planeten rettet. Veröffentlicht in begrenzten Gungan- und Schlacht-Sets, repräsentiert diese Minifigur die Gungan-Führung und wird von Sammlern geschätzt, die vollständige Naboo-Schlacht-Szenen suchen.',
    fr: 'Boss Nass est le leader à voix tonitruante du peuple Gungan qui gouverne Otoh Gunga et commande la Grande Armée pendant la Bataille de Naboo dans La Menace Fantôme. Cette minifigurine dépeint le leader Gungan imposant avec sa grande stature distinctive, coiffe élaborée, robes cérémonielles, et bâton d\'autorité. Initialement réticent à aider les habitants de surface de Naboo, Boss Nass accepte finalement l\'alliance qui sauve la planète. Sortie dans des sets Gungan et bataille limités, cette minifigurine représente le leadership Gungan et est appréciée par les collectionneurs cherchant des scènes complètes de bataille de Naboo.',
    es: 'Boss Nass es el líder de voz retumbante del pueblo Gungan que gobierna Otoh Gunga y comanda el Gran Ejército durante la Batalla de Naboo en La Amenaza Fantasma. Esta minifigura representa al imponente líder Gungan con su distintiva gran complexión, tocado elaborado, túnicas ceremoniales y bastón de autoridad. Inicialmente reacio a ayudar a los habitantes de superficie de Naboo, Boss Nass finalmente acepta la alianza que salva el planeta. Lanzada en sets limitados de Gungan y batalla, esta minifigura representa el liderazgo Gungan y es valorada por coleccionistas que buscan escenas completas de batalla de Naboo.'
  },
  {
    no: 'sw0413',
    name: 'Gungan Warrior',
    en: 'Gungan Warriors are the amphibious soldiers who form the Grand Army of the Gungans and fight alongside Naboo forces against the Trade Federation in The Phantom Menace. This minifigure depicts the typical Gungan soldier with orange and yellow skin tones, distinctive ear stalks, primitive armor, and energy ball weapons or shields. Despite their technologically primitive weapons, the Gungans demonstrate bravery in the Battle of Naboo. Released in battle pack and army builder sets, these warriors are essential for recreating the climactic ground battle and represent the native defenders of Naboo.',
    de: 'Gungan-Krieger sind die amphibischen Soldaten, die die Große Armee der Gungans bilden und an der Seite der Naboo-Streitkräfte gegen die Handelsföderation in Die dunkle Bedrohung kämpfen. Diese Minifigur zeigt den typischen Gungan-Soldaten mit orangen und gelben Hauttönen, charakteristischen Ohrstielen, primitiver Rüstung und Energiekugel-Waffen oder Schilden. Trotz ihrer technologisch primitiven Waffen demonstrieren die Gungans Tapferkeit in der Schlacht um Naboo. Veröffentlicht in Kampfpack- und Armee-Bauer-Sets, sind diese Krieger unerlässlich für die Nachstellung der klimatischen Bodenschlacht und repräsentieren die einheimischen Verteidiger von Naboo.',
    fr: 'Les Guerriers Gungans sont les soldats amphibies qui forment la Grande Armée des Gungans et combattent aux côtés des forces de Naboo contre la Fédération du Commerce dans La Menace Fantôme. Cette minifigurine dépeint le soldat Gungan typique avec des tons de peau orange et jaune, tiges d\'oreilles distinctives, armure primitive, et armes ou boucliers à boules d\'énergie. Malgré leurs armes technologiquement primitives, les Gungans démontrent du courage dans la Bataille de Naboo. Sortie dans des packs de bataille et sets de constructeurs d\'armée, ces guerriers sont essentiels pour recréer la bataille terrestre climatique et représentent les défenseurs natifs de Naboo.',
    es: 'Los Guerreros Gungan son los soldados anfibios que forman el Gran Ejército de los Gungans y luchan junto a las fuerzas de Naboo contra la Federación de Comercio en La Amenaza Fantasma. Esta minifigura representa al soldado Gungan típico con tonos de piel naranja y amarilla, tallos de orejas distintivos, armadura primitiva y armas o escudos de bolas de energía. A pesar de sus armas tecnológicamente primitivas, los Gungans demuestran valentía en la Batalla de Naboo. Lanzada en paquetes de batalla y sets de constructores de ejércitos, estos guerreros son esenciales para recrear la batalla terrestre climática y representan a los defensores nativos de Naboo.'
  },
  {
    no: 'sw0414',
    name: 'Naboo Security Officer',
    en: 'Naboo Security Officers are the royal guards and security forces who protect Queen Amidala and defend Theed Palace from the Trade Federation invasion in The Phantom Menace. This minifigure features the distinctive ceremonial uniform with burgundy and black colors, plumed helmet, and blaster weaponry. These professional soldiers fight to liberate their planet from occupation. Released in various Naboo palace and battle sets, these guards add authenticity to Theed Palace scenes and represent the military forces of the peaceful Naboo civilization.',
    de: 'Naboo-Sicherheitsoffiziere sind die königlichen Wachen und Sicherheitskräfte, die Königin Amidala schützen und den Theed-Palast vor der Invasion der Handelsföderation in Die dunkle Bedrohung verteidigen. Diese Minifigur zeigt die charakteristische zeremonielle Uniform mit burgunderroten und schwarzen Farben, gefedertem Helm und Blaster-Bewaffnung. Diese professionellen Soldaten kämpfen, um ihren Planeten von der Besatzung zu befreien. Veröffentlicht in verschiedenen Naboo-Palast- und Schlacht-Sets, fügen diese Wachen Authentizität zu Theed-Palast-Szenen hinzu und repräsentieren die Streitkräfte der friedlichen Naboo-Zivilisation.',
    fr: 'Les Officiers de Sécurité de Naboo sont les gardes royaux et forces de sécurité qui protègent la Reine Amidala et défendent le Palais de Theed contre l\'invasion de la Fédération du Commerce dans La Menace Fantôme. Cette minifigurine présente l\'uniforme cérémoniel distinctif avec couleurs bordeaux et noir, casque à plumes, et armement blaster. Ces soldats professionnels combattent pour libérer leur planète de l\'occupation. Sortie dans divers sets de palais et bataille de Naboo, ces gardes ajoutent de l\'authenticité aux scènes du Palais de Theed et représentent les forces militaires de la civilisation paisible de Naboo.',
    es: 'Los Oficiales de Seguridad de Naboo son los guardias reales y fuerzas de seguridad que protegen a la Reina Amidala y defienden el Palacio de Theed de la invasión de la Federación de Comercio en La Amenaza Fantasma. Esta minifigura presenta el distintivo uniforme ceremonial con colores borgoña y negro, casco con plumas y armamento bláster. Estos soldados profesionales luchan para liberar su planeta de la ocupación. Lanzada en varios sets de palacio y batalla de Naboo, estos guardias añaden autenticidad a las escenas del Palacio de Theed y representan las fuerzas militares de la civilización pacífica de Naboo.'
  },
  {
    no: 'sw0415',
    name: 'Naboo Fighter Pilot',
    en: 'Naboo Fighter Pilots operate the sleek N-1 starfighters that defend the peaceful planet from space threats in The Phantom Menace. This minifigure features the distinctive yellow flight suit with black accents, helmet with communications equipment, and flight gear. Young Anakin Skywalker flies in an N-1 during the Battle of Naboo and accidentally destroys the droid control ship. Released in N-1 starfighter sets, these pilot minifigures represent the small but skilled Naboo Space Fighter Corps and are essential for recreating the space battle sequences.',
    de: 'Naboo-Kampfpiloten bedienen die schlanken N-1-Sternenjäger, die den friedlichen Planeten vor Weltraumbedrohungen in Die dunkle Bedrohung verteidigen. Diese Minifigur zeigt den charakteristischen gelben Fluganzug mit schwarzen Akzenten, Helm mit Kommunikationsausrüstung und Flugausrüstung. Der junge Anakin Skywalker fliegt einen N-1 während der Schlacht um Naboo und zerstört versehentlich das Droiden-Kontrollschiff. Veröffentlicht in N-1-Sternenjäger-Sets, repräsentieren diese Piloten-Minifiguren das kleine, aber geschickte Naboo-Weltraum-Kampfkorps und sind unerlässlich für die Nachstellung der Weltraumschlacht-Sequenzen.',
    fr: 'Les Pilotes de Chasseur Naboo opèrent les chasseurs stellaires N-1 élégants qui défendent la planète paisible contre les menaces spatiales dans La Menace Fantôme. Cette minifigurine présente la combinaison de vol jaune distinctive avec accents noirs, casque avec équipement de communication, et équipement de vol. Le jeune Anakin Skywalker pilote un N-1 pendant la Bataille de Naboo et détruit accidentellement le vaisseau de contrôle droïde. Sortie dans des sets de chasseur stellaire N-1, ces minifigurines de pilote représentent le petit mais qualifié Corps de Chasseurs Spatiaux de Naboo et sont essentielles pour recréer les séquences de bataille spatiale.',
    es: 'Los Pilotos de Caza de Naboo operan los elegantes cazas estelares N-1 que defienden el planeta pacífico de amenazas espaciales en La Amenaza Fantasma. Esta minifigura presenta el distintivo traje de vuelo amarillo con acentos negros, casco con equipo de comunicaciones y equipo de vuelo. El joven Anakin Skywalker vuela un N-1 durante la Batalla de Naboo y accidentalmente destruye la nave de control de droides. Lanzada en sets de caza estelar N-1, estas minifiguras de piloto representan el pequeño pero hábil Cuerpo de Cazas Espaciales de Naboo y son esenciales para recrear las secuencias de batalla espacial.'
  },
  {
    no: 'sw0416',
    name: 'R2-D2 - Naboo',
    en: 'R2-D2 serves aboard Queen Amidala\'s Royal Starship and proves his worth by repairing the ship\'s shields during the Trade Federation blockade escape in The Phantom Menace. This variant depicts R2 in his standard blue and white astromech colors, representing the droid before he becomes Luke\'s companion. His heroic repair work earns him recognition and begins his long service to the Skywalker family. Released in Naboo starship and palace sets, this variant represents R2-D2\'s introduction to the saga and his first of many crucial moments saving his allies.',
    de: 'R2-D2 dient an Bord von Königin Amidalas königlichem Raumschiff und beweist seinen Wert, indem er die Schilde des Schiffes während der Flucht aus der Blockade der Handelsföderation in Die dunkle Bedrohung repariert. Diese Variante zeigt R2 in seinen standardmäßigen blauen und weißen Astromech-Farben und repräsentiert den Droiden, bevor er Lukes Begleiter wird. Seine heldenhafte Reparaturarbeit bringt ihm Anerkennung ein und beginnt seinen langen Dienst für die Skywalker-Familie. Veröffentlicht in Naboo-Raumschiff- und Palast-Sets, repräsentiert diese Variante R2-D2s Einführung in die Saga und seinen ersten von vielen entscheidenden Momenten, in denen er seine Verbündeten rettet.',
    fr: 'R2-D2 sert à bord du Vaisseau Royal de la Reine Amidala et prouve sa valeur en réparant les boucliers du vaisseau pendant l\'évasion du blocus de la Fédération du Commerce dans La Menace Fantôme. Cette variante dépeint R2 dans ses couleurs astromech bleues et blanches standard, représentant le droïde avant qu\'il ne devienne le compagnon de Luke. Son travail de réparation héroïque lui vaut la reconnaissance et commence son long service à la famille Skywalker. Sortie dans des sets de vaisseau spatial et palais Naboo, cette variante représente l\'introduction de R2-D2 dans la saga et son premier de nombreux moments cruciaux sauvant ses alliés.',
    es: 'R2-D2 sirve a bordo de la Nave Real de la Reina Amidala y demuestra su valor reparando los escudos de la nave durante el escape del bloqueo de la Federación de Comercio en La Amenaza Fantasma. Esta variante representa a R2 en sus colores estándar de astromecánico azul y blanco, representando al droide antes de convertirse en compañero de Luke. Su heroico trabajo de reparación le gana reconocimiento y comienza su largo servicio a la familia Skywalker. Lanzada en sets de nave espacial y palacio de Naboo, esta variante representa la introducción de R2-D2 a la saga y su primer momento crucial de muchos salvando a sus aliados.'
  },
  {
    no: 'sw0417',
    name: 'TC-14',
    en: 'TC-14 is the silver protocol droid serving aboard the Trade Federation flagship who greets Qui-Gon Jinn and Obi-Wan Kenobi at the beginning of The Phantom Menace. This minifigure depicts the feminine-programmed protocol droid with chrome silver finish and elegant design. Unknowingly serving the Neimoidians\' treacherous plans, TC-14 represents the diplomatic droids used in high-level negotiations. Released in limited Trade Federation ship sets, this unique droid adds authenticity to the opening sequence and represents the protocol droid class in the Prequel era.',
    de: 'TC-14 ist der silberne Protokoll-Droide, der an Bord des Flaggschiffs der Handelsföderation dient und Qui-Gon Jinn und Obi-Wan Kenobi zu Beginn von Die dunkle Bedrohung begrüßt. Diese Minifigur zeigt den weiblich programmierten Protokoll-Droiden mit verchromtem Silberfinish und elegantem Design. Unwissentlich den verräterischen Plänen der Neimoidier dienend, repräsentiert TC-14 die diplomatischen Droiden, die bei hochrangigen Verhandlungen verwendet werden. Veröffentlicht in begrenzten Handelsföderation-Schiff-Sets, fügt dieser einzigartige Droide Authentizität zur Eröffnungssequenz hinzu und repräsentiert die Protokoll-Droiden-Klasse in der Prequel-Ära.',
    fr: 'TC-14 est le droïde de protocole argenté servant à bord du vaisseau amiral de la Fédération du Commerce qui accueille Qui-Gon Jinn et Obi-Wan Kenobi au début de La Menace Fantôme. Cette minifigurine dépeint le droïde de protocole programmé féminin avec finition chrome argenté et design élégant. Servant sans le savoir les plans traîtres des Neimoidiens, TC-14 représente les droïdes diplomatiques utilisés dans les négociations de haut niveau. Sortie dans des sets de vaisseau de Fédération du Commerce limités, ce droïde unique ajoute de l\'authenticité à la séquence d\'ouverture et représente la classe de droïdes de protocole dans l\'ère Prequel.',
    es: 'TC-14 es el droide de protocolo plateado que sirve a bordo de la nave insignia de la Federación de Comercio que saluda a Qui-Gon Jinn y Obi-Wan Kenobi al comienzo de La Amenaza Fantasma. Esta minifigura representa al droide de protocolo programado femenino con acabado plateado cromado y diseño elegante. Sirviendo sin saberlo los planes traicioneros de los Neimoidians, TC-14 representa a los droides diplomáticos utilizados en negociaciones de alto nivel. Lanzada en sets limitados de nave de la Federación de Comercio, este droide único añade autenticidad a la secuencia de apertura y representa la clase de droides de protocolo en la era Precuela.'
  },
  {
    no: 'sw0418',
    name: 'Nute Gunray',
    en: 'Nute Gunray is the cowardly Viceroy of the Trade Federation who orchestrates the blockade and invasion of Naboo under Darth Sidious\'s orders in The Phantom Menace. This minifigure depicts the Neimoidian leader with distinctive green-gray skin, elaborate ceremonial robes, and miter-like headdress. As the primary antagonist representing corporate greed and corruption, Nute Gunray becomes a recurring villain throughout the Prequel trilogy. Released in Trade Federation ship and throne room sets, this minifigure is essential for Phantom Menace collections and represents the political corruption that enables the rise of the Empire.',
    de: 'Nute Gunray ist der feige Vizekönig der Handelsföderation, der die Blockade und Invasion von Naboo unter Darth Sidious\' Befehlen in Die dunkle Bedrohung orchestriert. Diese Minifigur zeigt den Neimoidianischen Anführer mit charakteristischer grüngrauer Haut, aufwendigen zeremoniellen Roben und mitra-ähnlichem Kopfschmuck. Als Hauptantagonist, der Unternehmensgier und Korruption repräsentiert, wird Nute Gunray zu einem wiederkehrenden Schurken während der gesamten Prequel-Trilogie. Veröffentlicht in Handelsföderation-Schiff- und Thronsaal-Sets, ist diese Minifigur unerlässlich für Die dunkle Bedrohung-Sammlungen und repräsentiert die politische Korruption, die den Aufstieg des Imperiums ermöglicht.',
    fr: 'Nute Gunray est le Vice-Roi lâche de la Fédération du Commerce qui orchestre le blocus et l\'invasion de Naboo sous les ordres de Darth Sidious dans La Menace Fantôme. Cette minifigurine dépeint le leader Neimoidien avec peau vert-gris distinctive, robes cérémonielles élaborées, et coiffe en forme de mitre. En tant qu\'antagoniste principal représentant l\'avidité corporative et la corruption, Nute Gunray devient un méchant récurrent tout au long de la Trilogie Prequel. Sortie dans des sets de vaisseau et salle du trône de Fédération du Commerce, cette minifigurine est essentielle pour les collections La Menace Fantôme et représente la corruption politique qui permet la montée de l\'Empire.',
    es: 'Nute Gunray es el cobarde Virrey de la Federación de Comercio que orquesta el bloqueo e invasión de Naboo bajo las órdenes de Darth Sidious en La Amenaza Fantasma. Esta minifigura representa al líder Neimoidiano con distintiva piel verde-gris, elaboradas túnicas ceremoniales y tocado similar a mitra. Como el antagonista principal representando codicia corporativa y corrupción, Nute Gunray se convierte en un villano recurrente a lo largo de la Trilogía Precuela. Lanzada en sets de nave y sala del trono de la Federación de Comercio, esta minifigura es esencial para colecciones de La Amenaza Fantasma y representa la corrupción política que permite el ascenso del Imperio.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 301-310 (sw0409-sw0418) - 10 minifigs...\n');

  for (const m of batch) {
    try {
      await prisma.minifigCatalog.upsert({
        where: { minifigure_no: m.no },
        update: {
          description_en: m.en,
          description_de: m.de,
          description_fr: m.fr,
          description_es: m.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        },
        create: {
          minifigure_no: m.no,
          name: m.name,
          category_id: 1,
          category_name: 'Star Wars',
          search_name: m.name.toLowerCase(),
          description_en: m.en,
          description_de: m.de,
          description_fr: m.fr,
          description_es: m.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        }
      });
      console.log(`  ✅ ${m.no}: ${m.name}`);
    } catch (error: any) {
      console.error(`  ❌ ${m.no}: ${error.message}`);
    }
  }

  console.log('\n✨ Batch 301-310 complete: 10 minifigs (40 descriptions)');
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
