import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0589',
    name: 'First Order Snowtrooper',
    en: 'First Order Snowtroopers are specialized cold-weather assault troops deployed on ice planets like Starkiller Base, combining the Empire\'s classic snowtrooper design with First Order technological upgrades. This LEGO minifigure features white and gray armor with distinctive ribbed fabric kama skirt, insulated helmet with black visor, and blaster rifle accessory. Released in 2015-2016 as part of sets including 75100 and 75103, these troopers represent First Order adaptation of Imperial military doctrine. The winter warfare specialization and role in The Force Awakens\' Starkiller Base assault make this minifigure valuable for collectors building First Order arctic operations scenes.',
    de: 'First Order Snowtroopers sind spezialisierte Kaltwetter-Sturmtruppen, die auf Eisplaneten wie Starkiller-Basis eingesetzt werden und das klassische Snowtrooper-Design des Imperiums mit technologischen Upgrades der Ersten Ordnung kombinieren. Diese LEGO Minifigur zeigt weiß-graue Rüstung mit charakteristischem geripptem Stoff-Kama-Rock, isoliertem Helm mit schwarzem Visier und Blastergewehr-Zubehör. Veröffentlicht 2015-2016 als Teil von Sets einschließlich 75100 und 75103, repräsentieren diese Soldaten die Anpassung imperialer Militärdoktrin durch die Erste Ordnung. Die Winterkriegsführungs-Spezialisierung und Rolle im Starkiller-Basis-Angriff von Das Erwachen der Macht machen diese Minifigur wertvoll für Sammler, die First Order-Arktis-Operationsszenen aufbauen.',
    fr: 'Les Snowtroopers du Premier Ordre sont des troupes d\'assaut spécialisées par temps froid déployées sur des planètes glacées comme la Base Starkiller, combinant le design classique du snowtrooper de l\'Empire avec des améliorations technologiques du Premier Ordre. Cette minifigurine LEGO présente une armure blanche et grise avec jupe kama en tissu nervuré distinctive, casque isolé avec visière noire et accessoire fusil blaster. Sortie en 2015-2016 dans le cadre de sets dont 75100 et 75103, ces soldats représentent l\'adaptation de la doctrine militaire impériale par le Premier Ordre. La spécialisation en guerre hivernale et le rôle dans l\'assaut de la Base Starkiller du Réveil de la Force rendent cette minifigurine précieuse pour les collectionneurs construisant des scènes d\'opérations arctiques du Premier Ordre.',
    es: 'Los Snowtroopers de la Primera Orden son tropas de asalto especializadas en clima frío desplegadas en planetas helados como la Base Starkiller, combinando el diseño clásico del snowtrooper del Imperio con mejoras tecnológicas de la Primera Orden. Esta minifigura LEGO presenta armadura blanca y gris con distintiva falda kama de tela acanalada, casco aislado con visor negro y accesorio de rifle bláster. Lanzada en 2015-2016 como parte de sets incluyendo 75100 y 75103, estos soldados representan la adaptación de la doctrina militar imperial por la Primera Orden. La especialización en guerra de invierno y papel en el asalto de la Base Starkiller de El Despertar de la Fuerza hacen de esta minifigura valiosa para coleccionistas construyendo escenas de operaciones árticas de la Primera Orden.'
  },
  {
    no: 'sw0590',
    name: 'First Order Officer',
    en: 'First Order Officers command military operations and crew aboard Star Destroyers, wearing distinctive uniforms that denote rank within the sequel trilogy\'s authoritarian regime. This LEGO minifigure features gray or black uniform with officer\'s cap, rank insignia plaques, and command posture representing the leadership hierarchy. Released in 2015-2018 across multiple sets, First Order Officers add essential command structure to military displays. Their administrative role and presence on Star Destroyer bridges make this minifigure crucial for collectors building complete First Order command staff and realistic military chain-of-command scenarios.',
    de: 'First Order Offiziere befehligen militärische Operationen und Besatzungen an Bord von Sternenzerstörern und tragen charakteristische Uniformen, die den Rang innerhalb des autoritären Regimes der Sequel-Trilogie kennzeichnen. Diese LEGO Minifigur zeigt graue oder schwarze Uniform mit Offizierskappe, Rangabzeichen-Plaketten und Kommando-Haltung, die die Führungshierarchie repräsentiert. Veröffentlicht 2015-2018 in mehreren Sets, fügen First Order Offiziere wesentliche Kommandostruktur zu Militär-Displays hinzu. Ihre administrative Rolle und Präsenz auf Sternenzerstörer-Brücken machen diese Minifigur entscheidend für Sammler, die vollständigen First Order-Kommandostab und realistische militärische Befehlsketten-Szenarien aufbauen.',
    fr: 'Les Officiers du Premier Ordre commandent les opérations militaires et l\'équipage à bord des Destroyers Stellaires, portant des uniformes distinctifs qui dénotent le rang au sein du régime autoritaire de la trilogie suite. Cette minifigurine LEGO présente un uniforme gris ou noir avec casquette d\'officier, plaques d\'insignes de rang et posture de commandement représentant la hiérarchie de leadership. Sortie en 2015-2018 dans plusieurs sets, les Officiers du Premier Ordre ajoutent une structure de commandement essentielle aux affichages militaires. Leur rôle administratif et présence sur les passerelles de Destroyer Stellaire rendent cette minifigurine cruciale pour les collectionneurs construisant un état-major complet du Premier Ordre et des scénarios réalistes de chaîne de commandement militaire.',
    es: 'Los Oficiales de la Primera Orden comandan operaciones militares y tripulación a bordo de Destructores Estelares, vistiendo uniformes distintivos que denotan rango dentro del régimen autoritario de la trilogía secuela. Esta minifigura LEGO presenta uniforme gris o negro con gorra de oficial, placas de insignias de rango y postura de mando representando la jerarquía de liderazgo. Lanzada en 2015-2018 en múltiples sets, los Oficiales de la Primera Orden añaden estructura de mando esencial a exhibiciones militares. Su papel administrativo y presencia en puentes de Destructores Estelares hacen de esta minifigura crucial para coleccionistas construyendo personal de mando completo de la Primera Orden y escenarios realistas de cadena de mando militar.'
  },
  {
    no: 'sw0591',
    name: 'First Order TIE Pilot',
    en: 'First Order TIE Fighter Pilots represent the next generation of Imperial starfighter corps, flying advanced TIE/fo fighters with improved shields and life support systems in the sequel trilogy. This LEGO minifigure features all-black flight suit with red First Order insignia on helmet, detailed life support chest box, and flight gear representing elite pilot training. Released in 2015-2018 across multiple TIE Fighter sets, these pilots show the First Order\'s commitment to learning from Imperial mistakes. The sleek black armor and role as starfighter elite make this minifigure essential for collectors building First Order aerospace forces and TIE Fighter cockpit scenes.',
    de: 'First Order TIE Fighter-Piloten repräsentieren die nächste Generation des imperialen Sternenjäger-Korps und fliegen fortschrittliche TIE/fo-Jäger mit verbesserten Schilden und Lebenserhaltungssystemen in der Sequel-Trilogie. Diese LEGO Minifigur zeigt einen komplett schwarzen Fluganzug mit rotem First Order-Abzeichen auf dem Helm, detaillierter Lebenserhaltungs-Brustbox und Flugausrüstung, die Elite-Pilotentraining repräsentiert. Veröffentlicht 2015-2018 in mehreren TIE Fighter-Sets, zeigen diese Piloten das Engagement der Ersten Ordnung, aus imperialen Fehlern zu lernen. Die schlanke schwarze Rüstung und Rolle als Sternenjäger-Elite machen diese Minifigur unverzichtbar für Sammler, die First Order-Luftwaffen-Streitkräfte und TIE Fighter-Cockpitszenen aufbauen.',
    fr: 'Les Pilotes de Chasseur TIE du Premier Ordre représentent la prochaine génération du corps de chasseurs stellaires impériaux, pilotant des chasseurs TIE/fo avancés avec boucliers améliorés et systèmes de survie dans la trilogie suite. Cette minifigurine LEGO présente une combinaison de vol entièrement noire avec insigne rouge du Premier Ordre sur le casque, boîte de poitrine de survie détaillée et équipement de vol représentant un entraînement de pilote d\'élite. Sortie en 2015-2018 dans plusieurs sets de Chasseur TIE, ces pilotes montrent l\'engagement du Premier Ordre à apprendre des erreurs impériales. L\'armure noire élégante et le rôle d\'élite des chasseurs stellaires rendent cette minifigurine essentielle pour les collectionneurs construisant des forces aérospatiales du Premier Ordre et des scènes de cockpit de Chasseur TIE.',
    es: 'Los Pilotos de Caza TIE de la Primera Orden representan la siguiente generación del cuerpo de cazas estelares imperiales, volando cazas TIE/fo avanzados con escudos mejorados y sistemas de soporte vital en la trilogía secuela. Esta minifigura LEGO presenta traje de vuelo completamente negro con insignia roja de la Primera Orden en el casco, caja de pecho de soporte vital detallada y equipo de vuelo representando entrenamiento de piloto de élite. Lanzada en 2015-2018 en múltiples sets de Caza TIE, estos pilotos muestran el compromiso de la Primera Orden de aprender de los errores imperiales. La elegante armadura negra y papel como élite de cazas estelares hacen de esta minifigura esencial para coleccionistas construyendo fuerzas aeroespaciales de la Primera Orden y escenas de cabina de Caza TIE.'
  },
  {
    no: 'sw0592',
    name: 'First Order Flametrooper',
    en: 'First Order Flametroopers are specialized assault infantry equipped with D-93 incinerators for crowd control and destroying fortifications, seen clearing resistance on Takodana in The Force Awakens. This LEGO minifigure features distinctive white armor with red and black markings, reinforced helmet with blast shield, fuel tank backpack, and flamethrower weapon accessory. Released in 2015-2016 as part of set 75103, Flametroopers represent the First Order\'s brutal pacification tactics. The unique red markings and specialized role in terror weapons make this minifigure highly sought after for collectors building diverse First Order trooper variants and Takodana battle scenes.',
    de: 'First Order Flametroopers sind spezialisierte Sturminfanterie, ausgerüstet mit D-93-Brandwaffen zur Massenkontrolle und Zerstörung von Befestigungen, gesehen beim Beseitigen von Widerstand auf Takodana in Das Erwachen der Macht. Diese LEGO Minifigur zeigt charakteristische weiße Rüstung mit rot-schwarzen Markierungen, verstärktem Helm mit Sprengschild, Treibstofftank-Rucksack und Flammenwerfer-Waffen-Zubehör. Veröffentlicht 2015-2016 als Teil des Sets 75103, repräsentieren Flametroopers die brutalen Befriedungstaktiken der Ersten Ordnung. Die einzigartigen roten Markierungen und spezialisierte Rolle bei Terrorwaffen machen diese Minifigur sehr begehrt für Sammler, die vielfältige First Order-Soldaten-Varianten und Takodana-Kampfszenen aufbauen.',
    fr: 'Les Flametroopers du Premier Ordre sont une infanterie d\'assaut spécialisée équipée d\'incinérateurs D-93 pour le contrôle des foules et la destruction de fortifications, vus éliminant la résistance sur Takodana dans Le Réveil de la Force. Cette minifigurine LEGO présente une armure blanche distinctive avec marquages rouges et noirs, casque renforcé avec bouclier anti-souffle, sac à dos de réservoir de carburant et accessoire d\'arme lance-flammes. Sortie en 2015-2016 dans le cadre du set 75103, les Flametroopers représentent les tactiques de pacification brutales du Premier Ordre. Les marquages rouges uniques et le rôle spécialisé dans les armes de terreur rendent cette minifigurine très recherchée pour les collectionneurs construisant diverses variantes de soldats du Premier Ordre et des scènes de bataille de Takodana.',
    es: 'Los Flametroopers de la Primera Orden son infantería de asalto especializada equipada con incineradores D-93 para control de multitudes y destrucción de fortificaciones, vistos eliminando resistencia en Takodana en El Despertar de la Fuerza. Esta minifigura LEGO presenta distintiva armadura blanca con marcas rojas y negras, casco reforzado con escudo contra explosiones, mochila de tanque de combustible y accesorio de arma lanzallamas. Lanzada en 2015-2016 como parte del set 75103, los Flametroopers representan las tácticas brutales de pacificación de la Primera Orden. Las marcas rojas únicas y papel especializado en armas de terror hacen de esta minifigura muy buscada para coleccionistas construyendo variantes diversas de soldados de la Primera Orden y escenas de batalla de Takodana.'
  },
  {
    no: 'sw0593',
    name: 'BB-8',
    en: 'BB-8 is the spherical astromech droid who carries the map to Luke Skywalker and becomes Poe Dameron\'s loyal companion throughout the sequel trilogy. This LEGO minifigure captures BB-8\'s distinctive orange and white paneled sphere body with separate domed head piece, representing one of the most beloved new droids in Star Wars. Released in 2015-2018 across numerous sets including 75105, 75149, and 75192, BB-8\'s frequent appearances reflect the character\'s popularity and importance to sequel trilogy storylines. The adorable design, pivotal role carrying critical data, and expressive personality make this minifigure essential for collectors building Resistance bases, Millennium Falcon interiors, and sequel trilogy droid collections.',
    de: 'BB-8 ist der kugelförmige Astromech-Droide, der die Karte zu Luke Skywalker trägt und Poe Damerons treuer Begleiter durch die gesamte Sequel-Trilogie wird. Diese LEGO Minifigur fängt BB-8s charakteristischen orange-weiß gepanelten Kugelkörper mit separatem Kuppelkopf-Teil ein und repräsentiert einen der beliebtesten neuen Droiden in Star Wars. Veröffentlicht 2015-2018 in zahlreichen Sets einschließlich 75105, 75149 und 75192, spiegeln BB-8s häufige Erscheinungen die Popularität und Bedeutung der Figur für Sequel-Trilogie-Storylines wider. Das bezaubernde Design, die entscheidende Rolle beim Tragen kritischer Daten und ausdrucksstarke Persönlichkeit machen diese Minifigur unverzichtbar für Sammler, die Resistance-Basen, Millennium-Falcon-Innenräume und Sequel-Trilogie-Droiden-Sammlungen aufbauen.',
    fr: 'BB-8 est le droïde astromech sphérique qui transporte la carte vers Luke Skywalker et devient le compagnon loyal de Poe Dameron tout au long de la trilogie suite. Cette minifigurine LEGO capture le corps sphérique distinctif de BB-8 à panneaux orange et blanc avec pièce de tête en dôme séparée, représentant l\'un des nouveaux droïdes les plus aimés de Star Wars. Sortie en 2015-2018 dans de nombreux sets dont 75105, 75149 et 75192, les apparitions fréquentes de BB-8 reflètent la popularité du personnage et son importance pour les histoires de la trilogie suite. Le design adorable, le rôle central transportant des données critiques et la personnalité expressive rendent cette minifigurine essentielle pour les collectionneurs construisant des bases de la Résistance, des intérieurs du Faucon Millenium et des collections de droïdes de la trilogie suite.',
    es: 'BB-8 es el droide astromecánico esférico que lleva el mapa a Luke Skywalker y se convierte en el compañero leal de Poe Dameron a lo largo de la trilogía secuela. Esta minifigura LEGO captura el distintivo cuerpo esférico de paneles naranja y blanco de BB-8 con pieza de cabeza en cúpula separada, representando uno de los nuevos droides más queridos de Star Wars. Lanzada en 2015-2018 en numerosos sets incluyendo 75105, 75149 y 75192, las frecuentes apariciones de BB-8 reflejan la popularidad del personaje y su importancia para las historias de la trilogía secuela. El adorable diseño, papel crucial llevando datos críticos y personalidad expresiva hacen de esta minifigura esencial para coleccionistas construyendo bases de la Resistencia, interiores del Halcón Milenario y colecciones de droides de la trilogía secuela.'
  },
  {
    no: 'sw0594',
    name: 'Captain Phasma',
    en: 'Captain Phasma commands First Order stormtrooper legions with ruthless efficiency, distinguished by her unique chromium-plated armor that reflects her elite status in The Force Awakens and The Last Jedi. This LEGO minifigure features striking silver armor with black accents, flowing cape, and blaster rifle, representing one of the sequel trilogy\'s most visually distinctive characters. Released in 2015-2017 across multiple sets including 75103 and 75118, Phasma\'s chrome armor makes her instantly recognizable on any display. Her mysterious background, imposing presence, and unique armor design make this minifigure highly desirable for collectors seeking First Order leadership figures and visually striking display pieces.',
    de: 'Captain Phasma befehligt First Order Sturmtruppler-Legionen mit rücksichtsloser Effizienz und zeichnet sich durch ihre einzigartige verchromte Rüstung aus, die ihren Elite-Status in Das Erwachen der Macht und Die letzten Jedi widerspiegelt. Diese LEGO Minifigur zeigt auffällige silberne Rüstung mit schwarzen Akzenten, fließendem Umhang und Blastergewehr und repräsentiert eine der visuell markantesten Figuren der Sequel-Trilogie. Veröffentlicht 2015-2017 in mehreren Sets einschließlich 75103 und 75118, macht Phasmas Chrom-Rüstung sie auf jedem Display sofort erkennbar. Ihr mysteriöser Hintergrund, imposante Präsenz und einzigartiges Rüstungsdesign machen diese Minifigur sehr begehrenswert für Sammler, die First Order-Führungsfiguren und visuell beeindruckende Display-Stücke suchen.',
    fr: 'Le Capitaine Phasma commande les légions de stormtroopers du Premier Ordre avec une efficacité impitoyable, distinguée par son armure chromée unique qui reflète son statut d\'élite dans Le Réveil de la Force et Les Derniers Jedi. Cette minifigurine LEGO présente une armure argentée frappante avec accents noirs, cape fluide et fusil blaster, représentant l\'un des personnages les plus visuellement distinctifs de la trilogie suite. Sortie en 2015-2017 dans plusieurs sets dont 75103 et 75118, l\'armure chromée de Phasma la rend instantanément reconnaissable sur n\'importe quel affichage. Son passé mystérieux, sa présence imposante et son design d\'armure unique rendent cette minifigurine hautement désirable pour les collectionneurs recherchant des figures de leadership du Premier Ordre et des pièces d\'affichage visuellement frappantes.',
    es: 'La Capitana Phasma comanda legiones de stormtroopers de la Primera Orden con eficiencia despiadada, distinguida por su armadura cromada única que refleja su estatus de élite en El Despertar de la Fuerza y Los Últimos Jedi. Esta minifigura LEGO presenta llamativa armadura plateada con acentos negros, capa fluida y rifle bláster, representando uno de los personajes más visualmente distintivos de la trilogía secuela. Lanzada en 2015-2017 en múltiples sets incluyendo 75103 y 75118, la armadura cromada de Phasma la hace instantáneamente reconocible en cualquier exhibición. Su trasfondo misterioso, presencia imponente y diseño único de armadura hacen de esta minifigura altamente deseable para coleccionistas buscando figuras de liderazgo de la Primera Orden y piezas de exhibición visualmente llamativas.'
  },
  {
    no: 'sw0595',
    name: 'General Hux',
    en: 'General Armitage Hux is the ambitious and fanatical First Order military commander who oversees Starkiller Base operations and commands the Star Destroyer fleet in the sequel trilogy. This LEGO minifigure features Hux\'s black First Order officer uniform with rank insignia, peaked cap, and stern expression representing his zealous commitment to the First Order cause. Released in 2015-2017 in sets including 75103 and 75190, Hux represents the ideological heart of the First Order\'s military leadership. His role in Starkiller Base\'s destruction of the Hosnian system and rivalry with Kylo Ren make this minifigure essential for collectors building First Order command hierarchies and sequel trilogy villain collections.',
    de: 'General Armitage Hux ist der ehrgeizige und fanatische First Order Militärkommandant, der Starkiller-Basis-Operationen überwacht und die Sternenzerstörer-Flotte in der Sequel-Trilogie befehligt. Diese LEGO Minifigur zeigt Hux\' schwarze First Order-Offiziersuniform mit Rangabzeichen, Schirmmütze und strengem Ausdruck, der sein leidenschaftliches Engagement für die Sache der Ersten Ordnung repräsentiert. Veröffentlicht 2015-2017 in Sets einschließlich 75103 und 75190, repräsentiert Hux das ideologische Herz der militärischen Führung der Ersten Ordnung. Seine Rolle bei der Zerstörung des Hosnian-Systems durch die Starkiller-Basis und Rivalität mit Kylo Ren machen diese Minifigur unverzichtbar für Sammler, die First Order-Befehlshierarchien und Sequel-Trilogie-Schurken-Sammlungen aufbauen.',
    fr: 'Le Général Armitage Hux est le commandant militaire ambitieux et fanatique du Premier Ordre qui supervise les opérations de la Base Starkiller et commande la flotte de Destroyers Stellaires dans la trilogie suite. Cette minifigurine LEGO présente l\'uniforme d\'officier noir du Premier Ordre de Hux avec insignes de rang, casquette à visière et expression sévère représentant son engagement zélé pour la cause du Premier Ordre. Sortie en 2015-2017 dans des sets dont 75103 et 75190, Hux représente le cœur idéologique du leadership militaire du Premier Ordre. Son rôle dans la destruction du système Hosnian par la Base Starkiller et sa rivalité avec Kylo Ren rendent cette minifigurine essentielle pour les collectionneurs construisant des hiérarchies de commandement du Premier Ordre et des collections de méchants de la trilogie suite.',
    es: 'El General Armitage Hux es el ambicioso y fanático comandante militar de la Primera Orden que supervisa las operaciones de la Base Starkiller y comanda la flota de Destructores Estelares en la trilogía secuela. Esta minifigura LEGO presenta el uniforme negro de oficial de la Primera Orden de Hux con insignias de rango, gorra de plato y expresión severa representando su compromiso fanático con la causa de la Primera Orden. Lanzada en 2015-2017 en sets incluyendo 75103 y 75190, Hux representa el corazón ideológico del liderazgo militar de la Primera Orden. Su papel en la destrucción del sistema Hosnian por la Base Starkiller y rivalidad con Kylo Ren hacen de esta minifigura esencial para coleccionistas construyendo jerarquías de mando de la Primera Orden y colecciones de villanos de la trilogía secuela.'
  },
  {
    no: 'sw0596',
    name: 'Kylo Ren (Battle Damaged)',
    en: 'This battle-damaged Kylo Ren variant shows the conflicted dark sider after his lightsaber duel with Rey on Starkiller Base in The Force Awakens, bearing a prominent facial scar from her blade. This LEGO minifigure features Kylo\'s black outfit with detailed torso printing, unmasked head with diagonal scar across the face, and crossguard lightsaber accessory. Released in 2016-2017 in sets including 75139, this version captures a pivotal moment showing Kylo\'s vulnerability and the consequences of underestimating Rey\'s power. The visible scar and unmasked appearance make this minifigure significant for collectors building The Force Awakens finale scenes and tracking Kylo Ren\'s character evolution through physical injury.',
    de: 'Diese kampfbeschädigte Kylo Ren-Variante zeigt den konfliktreichen Dunkelseiten-Nutzer nach seinem Lichtschwert-Duell mit Rey auf Starkiller-Basis in Das Erwachen der Macht mit einer prominenten Gesichtsnarbe von ihrer Klinge. Diese LEGO Minifigur zeigt Kylos schwarzes Outfit mit detailliertem Torso-Druck, unmaskiertem Kopf mit diagonaler Narbe über dem Gesicht und Kreuzparierstangen-Lichtschwert-Zubehör. Veröffentlicht 2016-2017 in Sets einschließlich 75139, fängt diese Version einen entscheidenden Moment ein, der Kylos Verwundbarkeit und die Konsequenzen des Unterschätzens von Reys Macht zeigt. Die sichtbare Narbe und unmaskierte Erscheinung machen diese Minifigur bedeutsam für Sammler, die Das-Erwachen-der-Macht-Finalszenen aufbauen und Kylo Rens Charakterentwicklung durch physische Verletzung verfolgen.',
    fr: 'Cette variante de Kylo Ren endommagée au combat montre le partisan du côté obscur en conflit après son duel au sabre laser avec Rey sur la Base Starkiller dans Le Réveil de la Force, portant une cicatrice faciale proéminente de sa lame. Cette minifigurine LEGO présente la tenue noire de Kylo avec impression de torse détaillée, tête démasquée avec cicatrice diagonale sur le visage et accessoire sabre laser à garde croisée. Sortie en 2016-2017 dans des sets dont 75139, cette version capture un moment décisif montrant la vulnérabilité de Kylo et les conséquences de sous-estimer le pouvoir de Rey. La cicatrice visible et l\'apparence démasquée rendent cette minifigurine significative pour les collectionneurs construisant des scènes finales du Réveil de la Force et suivant l\'évolution du personnage de Kylo Ren à travers la blessure physique.',
    es: 'Esta variante de Kylo Ren dañado en batalla muestra al usuario del lado oscuro en conflicto después de su duelo de sables de luz con Rey en la Base Starkiller en El Despertar de la Fuerza, portando una prominente cicatriz facial de su hoja. Esta minifigura LEGO presenta el atuendo negro de Kylo con impresión de torso detallada, cabeza desenmascarada con cicatriz diagonal en el rostro y accesorio de sable de luz con guardamano cruzado. Lanzada en 2016-2017 en sets incluyendo 75139, esta versión captura un momento crucial mostrando la vulnerabilidad de Kylo y las consecuencias de subestimar el poder de Rey. La cicatriz visible y apariencia desenmascarada hacen de esta minifigura significativa para coleccionistas construyendo escenas finales de El Despertar de la Fuerza y siguiendo la evolución del personaje de Kylo Ren a través de la lesión física.'
  },
  {
    no: 'sw0597',
    name: 'Rey (Scavenger)',
    en: 'Rey\'s scavenger outfit represents her years surviving alone on Jakku, salvaging parts from Imperial wreckage before discovering her Force sensitivity in The Force Awakens. This LEGO minifigure captures Rey\'s practical desert attire with tan and gray wrappings, goggles accessory, utility belt, and staff weapon representing her self-reliant lifestyle. Released in 2015-2016 across multiple sets including 75099 and 75105, this version shows Rey before her hero\'s journey begins. The humble origins costume and transformation from scavenger to Jedi make this minifigure essential for collectors tracking Rey\'s character arc from Jakku orphan to the sequel trilogy\'s protagonist.',
    de: 'Reys Schrottsammler-Outfit repräsentiert ihre Jahre des Allein-Überlebens auf Jakku, bei denen sie Teile aus imperialen Wracks birgt, bevor sie in Das Erwachen der Macht ihre Macht-Sensibilität entdeckt. Diese LEGO Minifigur fängt Reys praktische Wüstenkleidung mit beige-grauen Umwicklungen, Schutzbrille-Zubehör, Gürtel und Stab-Waffe ein, die ihren selbstständigen Lebensstil repräsentieren. Veröffentlicht 2015-2016 in mehreren Sets einschließlich 75099 und 75105, zeigt diese Version Rey, bevor ihre Heldenreise beginnt. Das bescheidene Ursprungs-Kostüm und die Transformation von Schrottsammlerin zu Jedi machen diese Minifigur unverzichtbar für Sammler, die Reys Charakterbogen von Jakku-Waise zur Protagonistin der Sequel-Trilogie verfolgen.',
    fr: 'La tenue de récupératrice de Rey représente ses années de survie seule sur Jakku, récupérant des pièces d\'épaves impériales avant de découvrir sa sensibilité à la Force dans Le Réveil de la Force. Cette minifigurine LEGO capture la tenue désertique pratique de Rey avec enroulements beiges et gris, accessoire de lunettes, ceinture utilitaire et arme bâton représentant son style de vie autonome. Sortie en 2015-2016 dans plusieurs sets dont 75099 et 75105, cette version montre Rey avant que son voyage héroïque ne commence. Le costume d\'origines humbles et la transformation de récupératrice à Jedi rendent cette minifigurine essentielle pour les collectionneurs suivant l\'arc narratif de Rey d\'orpheline de Jakku à protagoniste de la trilogie suite.',
    es: 'El atuendo de chatarrera de Rey representa sus años sobreviviendo sola en Jakku, rescatando partes de restos imperiales antes de descubrir su sensibilidad a la Fuerza en El Despertar de la Fuerza. Esta minifigura LEGO captura el práctico atuendo desértico de Rey con envolturas beige y grises, accesorio de gafas, cinturón de utilidad y arma de bastón representando su estilo de vida autosuficiente. Lanzada en 2015-2016 en múltiples sets incluyendo 75099 y 75105, esta versión muestra a Rey antes de que comience su viaje de héroe. El traje de orígenes humildes y transformación de chatarrera a Jedi hacen de esta minifigura esencial para coleccionistas siguiendo el arco de personaje de Rey de huérfana de Jakku a protagonista de la trilogía secuela.'
  },
  {
    no: 'sw0598',
    name: 'Finn (FN-2187)',
    en: 'Finn begins as FN-2187, a First Order stormtrooper who defects after refusing to massacre civilians on Jakku in The Force Awakens, becoming a key Resistance hero. This LEGO minifigure features standard First Order stormtrooper armor with specific printing details, representing Finn during his time serving the First Order before his moral awakening. Released in 2015-2016, this version captures Finn\'s origins as a brainwashed soldier and his transformative moment of conscience. The stormtrooper armor and Finn\'s journey from First Order conscript to Resistance fighter make this minifigure significant for collectors depicting his character\'s redemption arc and the sequel trilogy\'s themes of choice versus indoctrination.',
    de: 'Finn beginnt als FN-2187, ein First Order Sturmtruppler, der desertiert, nachdem er sich weigert, Zivilisten auf Jakku in Das Erwachen der Macht zu massakrieren, und wird zu einem wichtigen Resistance-Helden. Diese LEGO Minifigur zeigt Standard-First Order Sturmtruppler-Rüstung mit spezifischen Druckdetails, die Finn während seiner Zeit im Dienst der Ersten Ordnung vor seinem moralischen Erwachen repräsentiert. Veröffentlicht 2015-2016, fängt diese Version Finns Ursprünge als gehirngewaschener Soldat und seinen transformativen Moment des Gewissens ein. Die Sturmtruppler-Rüstung und Finns Reise vom First Order-Zwangsrekruten zum Resistance-Kämpfer machen diese Minifigur bedeutsam für Sammler, die seinen Erlösungsbogen und die Themen der Sequel-Trilogie von Wahl versus Indoktrination darstellen.',
    fr: 'Finn commence comme FN-2187, un stormtrooper du Premier Ordre qui fait défection après avoir refusé de massacrer des civils sur Jakku dans Le Réveil de la Force, devenant un héros clé de la Résistance. Cette minifigurine LEGO présente une armure de stormtrooper standard du Premier Ordre avec des détails d\'impression spécifiques, représentant Finn pendant son temps au service du Premier Ordre avant son éveil moral. Sortie en 2015-2016, cette version capture les origines de Finn en tant que soldat endoctriné et son moment transformateur de conscience. L\'armure de stormtrooper et le parcours de Finn de conscrit du Premier Ordre à combattant de la Résistance rendent cette minifigurine significative pour les collectionneurs représentant l\'arc de rédemption de son personnage et les thèmes de la trilogie suite de choix versus endoctrinement.',
    es: 'Finn comienza como FN-2187, un stormtrooper de la Primera Orden que deserta después de negarse a masacrar civiles en Jakku en El Despertar de la Fuerza, convirtiéndose en un héroe clave de la Resistencia. Esta minifigura LEGO presenta armadura de stormtrooper estándar de la Primera Orden con detalles de impresión específicos, representando a Finn durante su tiempo sirviendo a la Primera Orden antes de su despertar moral. Lanzada en 2015-2016, esta versión captura los orígenes de Finn como soldado lavado de cerebro y su momento transformador de conciencia. La armadura de stormtrooper y el viaje de Finn de conscripto de la Primera Orden a luchador de la Resistencia hacen de esta minifigura significativa para coleccionistas representando el arco de redención de su personaje y los temas de la trilogía secuela de elección versus adoctrinamiento.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 481-490 (sw0589-sw0598) - 10 minifigs...\n');

  for (const m of batch) {
    await prisma.minifigCatalog.upsert({
      where: { minifigure_no: m.no },
      update: {
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      },
      create: {
        minifigure_no: m.no,
        name: m.name,
        category_id: 1,
        category_name: 'Star Wars',
        search_name: m.name.toLowerCase(),
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`  ✅ ${m.no}: ${m.name}`);
  }

  console.log('\n✨ Batch 481-490 complete: 10 minifigs (40 descriptions)');
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
