import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0169',
    name: 'Rebel Technician',
    en: "Rebel Technicians maintain and repair the Alliance's starfighter fleet, working tirelessly in Echo Base hangars and Yavin IV facilities to keep X-Wings and Y-Wings combat-ready. This LEGO minifigure captures the practical work attire of these essential support personnel with coveralls and tool vests. First released in 1999, the Rebel Technician represents the unsung heroes who enabled the Rebellion's aerial victories. The figure features detailed printing showing grease-stained work clothes and equipment pouches that reflect their mechanical expertise. Collectors value Rebel Technicians for adding realism to hangar bay displays and for representing the logistical backbone of Rebel military operations. Multiple technicians are often desired to properly populate base scenes, showing the extensive support crew needed to maintain operational readiness across the Original Trilogy.",
    de: "Rebellentechniker warten und reparieren die Sternenjägerflotte der Allianz und arbeiten unermüdlich in Echo-Basis-Hangars und Yavin IV-Einrichtungen, um X-Flügler und Y-Flügler kampfbereit zu halten. Diese LEGO-Minifigur fängt die praktische Arbeitskleidung dieses essentiellen Hilfspersonals mit Overalls und Werkzeugwesten ein. Erstmals 1999 veröffentlicht, repräsentiert der Rebellentechniker die unbesungenen Helden, die die Luftsiege der Rebellion ermöglichten. Die Figur zeigt detaillierte Bedruckung mit ölverschmierter Arbeitskleidung und Ausrüstungstaschen, die ihre mechanische Expertise widerspiegeln. Sammler schätzen Rebellentechniker für das Hinzufügen von Realismus zu Hangar-Ausstellungen und für die Darstellung des logistischen Rückgrats der militärischen Operationen der Rebellion. Mehrere Techniker werden oft gewünscht, um Basis-Szenen ordnungsgemäß zu bevölkern und die umfangreiche Unterstützungscrew zu zeigen, die benötigt wird, um operative Bereitschaft über die Original-Trilogie hinweg aufrechtzuerhalten.",
    fr: "Les Techniciens Rebelles entretiennent et réparent la flotte de chasseurs stellaires de l'Alliance, travaillant sans relâche dans les hangars de la Base Echo et les installations de Yavin IV pour maintenir les X-Wing et Y-Wing prêts au combat. Cette minifigurine LEGO capture la tenue de travail pratique de ce personnel de soutien essentiel avec des combinaisons et des gilets à outils. Sortie pour la première fois en 1999, le Technicien Rebelle représente les héros méconnus qui ont permis les victoires aériennes de la Rébellion. La figurine présente une impression détaillée montrant des vêtements de travail tachés de graisse et des pochettes d'équipement qui reflètent leur expertise mécanique. Les collectionneurs apprécient les Techniciens Rebelles pour ajouter du réalisme aux expositions de baie de hangar et pour représenter l'épine dorsale logistique des opérations militaires Rebelles. Plusieurs techniciens sont souvent désirés pour peupler correctement les scènes de base, montrant l'équipage de soutien étendu nécessaire pour maintenir la disponibilité opérationnelle à travers la trilogie originale.",
    es: "Los Técnicos Rebeldes mantienen y reparan la flota de cazas estelares de la Alianza, trabajando incansablemente en hangares de Base Eco e instalaciones de Yavin IV para mantener Alas-X y Alas-Y listos para combate. Esta minifigura LEGO captura la vestimenta de trabajo práctica de este personal de apoyo esencial con overoles y chalecos de herramientas. Lanzada por primera vez en 1999, el Técnico Rebelde representa a los héroes no reconocidos que permitieron las victorias aéreas de la Rebelión. La figura presenta impresión detallada mostrando ropa de trabajo manchada de grasa y bolsas de equipo que reflejan su experiencia mecánica. Los coleccionistas valoran a los Técnicos Rebeldes por agregar realismo a exhibiciones de bahías de hangar y por representar la columna vertebral logística de las operaciones militares Rebeldes. Múltiples técnicos son frecuentemente deseados para poblar apropiadamente escenas de base, mostrando el extenso equipo de apoyo necesario para mantener preparación operacional a través de la trilogía original."
  },
  {
    no: 'sw0170',
    name: 'Hoth Rebel Trooper',
    en: "Hoth Rebel Troopers defended Echo Base against the Imperial invasion, manning trenches and anti-vehicle emplacements in the frozen wastes of the ice planet. This LEGO minifigure features the distinctive white and tan cold-weather gear with insulated helmet and survival equipment. First released in 2003, the Hoth Rebel Trooper has become essential for recreating The Empire Strikes Back's opening battle. The figure's detailed printing shows thermal layers, goggles, and equipment pouches designed for sub-zero combat operations. Collectors value Hoth Rebel Troopers for building comprehensive trench defense displays and for representing the Alliance's desperate ground forces during their evacuation. Multiple troopers are crucial for authentically recreating the scale of Echo Base's defensive perimeter against AT-AT walkers and snowtroopers.",
    de: "Hoth-Rebellensoldaten verteidigten Echo-Basis gegen die imperiale Invasion, bemannten Gräben und Panzerabwehr-Stellungen in der gefrorenen Wildnis des Eisplaneten. Diese LEGO-Minifigur zeigt die charakteristische weiß-beige Kälteschutzausrüstung mit isoliertem Helm und Überlebensausrüstung. Erstmals 2003 veröffentlicht, ist der Hoth-Rebellensoldat unverzichtbar geworden für die Nachbildung der Eröffnungsschlacht von Das Imperium schlägt zurück. Die detaillierte Bedruckung der Figur zeigt thermische Schichten, Schutzbrille und Ausrüstungstaschen, die für Kampfoperationen unter null Grad konzipiert sind. Sammler schätzen Hoth-Rebellensoldaten für den Aufbau umfassender Grabenverteidigungs-Ausstellungen und für die Darstellung der verzweifelten Bodentruppen der Allianz während ihrer Evakuierung. Mehrere Soldaten sind entscheidend für die authentische Nachbildung der Größenordnung des Verteidigungsperimeters der Echo-Basis gegen AT-AT-Walker und Schneetruppen.",
    fr: "Les Soldats Rebelles de Hoth ont défendu la Base Echo contre l'invasion Impériale, tenant des tranchées et des emplacements anti-véhicules dans les étendues gelées de la planète de glace. Cette minifigurine LEGO présente l'équipement distinctif blanc et beige pour temps froid avec casque isolé et équipement de survie. Sortie pour la première fois en 2003, le Soldat Rebelle de Hoth est devenu essentiel pour recréer la bataille d'ouverture de L'Empire contre-attaque. L'impression détaillée de la figurine montre des couches thermiques, des lunettes et des pochettes d'équipement conçues pour les opérations de combat sous zéro. Les collectionneurs apprécient les Soldats Rebelles de Hoth pour construire des expositions complètes de défense de tranchées et pour représenter les forces terrestres désespérées de l'Alliance pendant leur évacuation. Plusieurs soldats sont cruciaux pour recréer authentiquement l'échelle du périmètre défensif de la Base Echo contre les marcheurs AT-AT et les snowtroopers.",
    es: "Los Soldados Rebeldes de Hoth defendieron la Base Eco contra la invasión Imperial, equipando trincheras y emplazamientos anti-vehículo en los páramos congelados del planeta de hielo. Esta minifigura LEGO presenta el distintivo equipo para clima frío blanco y beige con casco aislado y equipo de supervivencia. Lanzada por primera vez en 2003, el Soldado Rebelde de Hoth se ha vuelto esencial para recrear la batalla de apertura de El Imperio Contraataca. La impresión detallada de la figura muestra capas térmicas, gafas y bolsas de equipo diseñadas para operaciones de combate bajo cero. Los coleccionistas valoran a los Soldados Rebeldes de Hoth por construir exhibiciones integrales de defensa de trincheras y por representar las fuerzas terrestres desesperadas de la Alianza durante su evacuación. Múltiples soldados son cruciales para recrear auténticamente la escala del perímetro defensivo de la Base Eco contra caminantes AT-AT y soldados de nieve."
  },
  {
    no: 'sw0171',
    name: 'Endor Rebel Trooper',
    en: "Endor Rebel Troopers fought alongside Han Solo's strike team in the forest moon mission, wearing camouflage gear adapted for jungle warfare against Imperial forces. This LEGO minifigure features the distinctive tan and green combat uniform with webbing and tactical equipment. Released in 2009, the Endor Rebel Trooper represents the ground forces who partnered with Ewok warriors during the Battle of Endor. The figure's detailed printing shows camouflage patterns, utility pouches, and field gear designed for covert operations. Collectors value Endor Rebel Troopers for building comprehensive ground assault displays and for representing the Alliance's elite commando units during Return of the Jedi. Multiple troopers are essential for recreating the full strike team that infiltrated the shield generator bunker alongside the main heroes.",
    de: "Endor-Rebellensoldaten kämpften an der Seite von Han Solos Schlagteam in der Waldmond-Mission und trugen Tarnausrüstung, die für Dschungelkriegsführung gegen imperiale Streitkräfte angepasst war. Diese LEGO-Minifigur zeigt die charakteristische beige-grüne Kampfuniform mit Gurten und taktischer Ausrüstung. 2009 veröffentlicht, repräsentiert der Endor-Rebellensoldat die Bodentruppen, die während der Schlacht von Endor mit Ewok-Kriegern zusammenarbeiteten. Die detaillierte Bedruckung der Figur zeigt Tarnmuster, Nutztaschen und Feldausrüstung, die für verdeckte Operationen konzipiert sind. Sammler schätzen Endor-Rebellensoldaten für den Aufbau umfassender Bodenangriffs-Ausstellungen und für die Darstellung der Elite-Kommandoeinheiten der Allianz während Die Rückkehr der Jedi-Ritter. Mehrere Soldaten sind unverzichtbar für die Nachbildung des vollständigen Schlagteams, das den Schildgenerator-Bunker zusammen mit den Haupthelden infiltrierte.",
    fr: "Les Soldats Rebelles d'Endor ont combattu aux côtés de l'équipe de frappe de Han Solo dans la mission de la lune forestière, portant un équipement de camouflage adapté à la guerre de jungle contre les forces Impériales. Cette minifigurine LEGO présente l'uniforme de combat beige et vert distinctif avec sangles et équipement tactique. Sortie en 2009, le Soldat Rebelle d'Endor représente les forces terrestres qui se sont associées aux guerriers Ewok pendant la Bataille d'Endor. L'impression détaillée de la figurine montre des motifs de camouflage, des pochettes utilitaires et un équipement de terrain conçu pour les opérations secrètes. Les collectionneurs apprécient les Soldats Rebelles d'Endor pour construire des expositions complètes d'assaut terrestre et pour représenter les unités commando d'élite de l'Alliance pendant Le Retour du Jedi. Plusieurs soldats sont essentiels pour recréer l'équipe de frappe complète qui a infiltré le bunker du générateur de bouclier aux côtés des héros principaux.",
    es: "Los Soldados Rebeldes de Endor lucharon junto al equipo de ataque de Han Solo en la misión de la luna boscosa, usando equipo de camuflaje adaptado para guerra de jungla contra fuerzas Imperiales. Esta minifigura LEGO presenta el distintivo uniforme de combate beige y verde con correas y equipo táctico. Lanzada en 2009, el Soldado Rebelde de Endor representa las fuerzas terrestres que se asociaron con guerreros Ewok durante la Batalla de Endor. La impresión detallada de la figura muestra patrones de camuflaje, bolsas de utilidad y equipo de campo diseñado para operaciones encubiertas. Los coleccionistas valoran a los Soldados Rebeldes de Endor por construir exhibiciones integrales de asalto terrestre y por representar las unidades comando de élite de la Alianza durante El Retorno del Jedi. Múltiples soldados son esenciales para recrear el equipo de ataque completo que infiltró el búnker del generador de escudo junto a los héroes principales."
  },
  {
    no: 'sw0172',
    name: 'Death Star Trooper',
    en: "Death Star Troopers serve as the Imperial Navy's security and gunnery personnel aboard the battle station, manning turbolaser batteries and maintaining internal security. This LEGO minifigure features the distinctive black uniform and Imperial cap that identifies these specialized naval troops. First released in 2005, the Death Star Trooper represents the Empire's garrison forces aboard their ultimate weapon. The figure's unique black attire distinguishes these personnel from standard stormtroopers, reflecting their technical and security roles. Collectors value Death Star Troopers for populating Death Star interior displays and for representing the diverse Imperial military hierarchy. Multiple troopers are often desired to properly staff corridor, control room, and hangar bay scenes across both Death Star battle stations from the Original Trilogy.",
    de: "Todesstern-Soldaten dienen als Sicherheits- und Geschützpersonal der imperialen Marine an Bord der Kampfstation, bemannen Turbolaser-Batterien und halten die innere Sicherheit aufrecht. Diese LEGO-Minifigur zeigt die charakteristische schwarze Uniform und imperiale Mütze, die diese spezialisierten Marinetruppen kennzeichnet. Erstmals 2005 veröffentlicht, repräsentiert der Todesstern-Soldat die Garnisonstruppen des Imperiums an Bord ihrer ultimativen Waffe. Die einzigartige schwarze Kleidung der Figur unterscheidet dieses Personal von Standard-Sturmtruppen und spiegelt ihre technischen und Sicherheitsrollen wider. Sammler schätzen Todesstern-Soldaten für die Bevölkerung von Todesstern-Innenraum-Ausstellungen und für die Darstellung der vielfältigen imperialen Militärhierarchie. Mehrere Soldaten werden oft gewünscht, um Korridore, Kontrollräume und Hangar-Szenen über beide Todesstern-Kampfstationen aus der Original-Trilogie ordnungsgemäß zu besetzen.",
    fr: "Les Soldats de l'Étoile de la Mort servent comme personnel de sécurité et d'artillerie de la Marine Impériale à bord de la station de combat, tenant des batteries de turbolaser et maintenant la sécurité intérieure. Cette minifigurine LEGO présente l'uniforme noir distinctif et la casquette Impériale qui identifie ces troupes navales spécialisées. Sortie pour la première fois en 2005, le Soldat de l'Étoile de la Mort représente les forces de garnison de l'Empire à bord de leur arme ultime. La tenue noire unique de la figurine distingue ce personnel des stormtroopers standard, reflétant leurs rôles techniques et de sécurité. Les collectionneurs apprécient les Soldats de l'Étoile de la Mort pour peupler les expositions d'intérieur de l'Étoile de la Mort et pour représenter la hiérarchie militaire Impériale diversifiée. Plusieurs soldats sont souvent désirés pour équiper correctement des scènes de couloir, de salle de contrôle et de baie de hangar à travers les deux stations de combat Étoile de la Mort de la trilogie originale.",
    es: "Los Soldados de la Estrella de la Muerte sirven como personal de seguridad y artillería de la Armada Imperial a bordo de la estación de batalla, equipando baterías de turboláser y manteniendo seguridad interna. Esta minifigura LEGO presenta el distintivo uniforme negro y gorra Imperial que identifica a estas tropas navales especializadas. Lanzada por primera vez en 2005, el Soldado de la Estrella de la Muerte representa las fuerzas de guarnición del Imperio a bordo de su arma definitiva. La vestimenta negra única de la figura distingue a este personal de soldados de asalto estándar, reflejando sus roles técnicos y de seguridad. Los coleccionistas valoran a los Soldados de la Estrella de la Muerte por poblar exhibiciones de interior de la Estrella de la Muerte y por representar la diversa jerarquía militar Imperial. Múltiples soldados son frecuentemente deseados para equipar apropiadamente escenas de corredor, sala de control y bahía de hangar a través de ambas estaciones de batalla Estrella de la Muerte de la trilogía original."
  },
  {
    no: 'sw0173',
    name: 'Imperial Shuttle Pilot',
    en: "Imperial Shuttle Pilots command the Empire's Lambda-class transports, ferrying high-ranking officers and valuable cargo between Star Destroyers and planetary installations. This LEGO minifigure features the distinctive all-black flight suit and specialized helmet that identifies these elite transport pilots. Released in 2005, the Imperial Shuttle Pilot represents the Empire's precision navigation specialists. The figure's sleek black uniform and unique helmet design distinguish these pilots from standard TIE fighter operators, reflecting their role in transporting Imperial leadership. Collectors value Imperial Shuttle Pilots for completing Lambda-class shuttle displays and for representing the logistical complexity of Imperial military operations. Their responsibility for safely transporting figures like Darth Vader and Emperor Palpatine makes this minifigure essential for recreating key scenes from the Original Trilogy.",
    de: "Imperiale Shuttle-Piloten kommandieren die Lambda-Klasse-Transporter des Imperiums und befördern hochrangige Offiziere und wertvolle Fracht zwischen Sternzerstörern und planetaren Installationen. Diese LEGO-Minifigur zeigt den charakteristischen ganz schwarzen Fluganzug und spezialisierten Helm, der diese Elite-Transportpiloten kennzeichnet. 2005 veröffentlicht, repräsentiert der Imperiale Shuttle-Pilot die Präzisionsnavigationsspezialisten des Imperiums. Die schlanke schwarze Uniform und das einzigartige Helmdesign der Figur unterscheiden diese Piloten von Standard-TIE-Jäger-Operatoren und spiegeln ihre Rolle beim Transport der imperialen Führung wider. Sammler schätzen Imperiale Shuttle-Piloten für die Vervollständigung von Lambda-Klasse-Shuttle-Ausstellungen und für die Darstellung der logistischen Komplexität imperialer Militäroperationen. Ihre Verantwortung für den sicheren Transport von Figuren wie Darth Vader und Imperator Palpatine macht diese Minifigur unverzichtbar für die Nachbildung wichtiger Szenen aus der Original-Trilogie.",
    fr: "Les Pilotes de Navette Impériale commandent les transports de classe Lambda de l'Empire, transportant des officiers de haut rang et du fret précieux entre les Destroyers Stellaires et les installations planétaires. Cette minifigurine LEGO présente la combinaison de vol toute noire distinctive et le casque spécialisé qui identifie ces pilotes de transport d'élite. Sortie en 2005, le Pilote de Navette Impériale représente les spécialistes de navigation de précision de l'Empire. L'uniforme noir élégant et le design de casque unique de la figurine distinguent ces pilotes des opérateurs de chasseurs TIE standard, reflétant leur rôle dans le transport du leadership Impérial. Les collectionneurs apprécient les Pilotes de Navette Impériale pour compléter les expositions de navettes de classe Lambda et pour représenter la complexité logistique des opérations militaires Impériales. Leur responsabilité de transporter en toute sécurité des personnages comme Dark Vador et l'Empereur Palpatine fait de cette minifigurine un élément essentiel pour recréer des scènes clés de la trilogie originale.",
    es: "Los Pilotos de Lanzadera Imperial comandan los transportes clase Lambda del Imperio, transportando oficiales de alto rango y carga valiosa entre Destructores Estelares e instalaciones planetarias. Esta minifigura LEGO presenta el distintivo traje de vuelo completamente negro y casco especializado que identifica a estos pilotos de transporte de élite. Lanzada en 2005, el Piloto de Lanzadera Imperial representa a los especialistas en navegación de precisión del Imperio. El elegante uniforme negro y diseño de casco único de la figura distinguen a estos pilotos de operadores de cazas TIE estándar, reflejando su papel en transportar al liderazgo Imperial. Los coleccionistas valoran a los Pilotos de Lanzadera Imperial por completar exhibiciones de lanzaderas clase Lambda y por representar la complejidad logística de las operaciones militares Imperiales. Su responsabilidad de transportar con seguridad figuras como Darth Vader y el Emperador Palpatine hace que esta minifigura sea esencial para recrear escenas clave de la trilogía original."
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 61-65 (sw0169-sw0173)...\n');

  for (const m of batch) {
    await prisma.minifigCatalog.upsert({
      where: { minifigure_no: m.no },
      update: {
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      },
      create: {
        minifigure_no: m.no,
        name: m.name,
        category_id: 1,
        category_name: 'Star Wars',
        search_name: m.name.toLowerCase(),
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`  ✅ ${m.no}: ${m.name}`);
  }

  console.log(`\n✨ Batch 61-65 complete: 5 minifigs (20 descriptions)`);
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
