import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0284',
    name: 'Imperial Probe Droid',
    en: 'The Imperial Probe Droid LEGO minifigure captures the sinister reconnaissance units that scoured the galaxy hunting Rebel bases, featuring its distinctive black spherical body, multiple sensor arms, and the menacing appearance that made it instantly recognizable. This specialized build showcases the probe droid\'s unique mechanical design with detailed construction representing the advanced sensor packages and communication arrays, embodying the Empire\'s far-reaching surveillance network. Deployed in thousands across remote star systems, these droids discovered the Rebel base on Hoth, triggering the Empire\'s devastating assault. Released in sets from 2010 onwards including Hoth scenes and Imperial deployment scenarios, this minifigure became highly sought after by collectors despite its non-humanoid design, prized for its accurate representation of one of The Empire Strikes Back\'s most memorable opening sequences, its connection to the film\'s inciting incident, and its embodiment of the Empire\'s oppressive omnipresence that forced the Rebellion to hide in the galaxy\'s most inhospitable locations.',
    de: 'Die LEGO-Minifigur der imperialen Sondendroide fängt die finsteren Aufklärungseinheiten ein, die die Galaxie nach Rebellenbasen absuchten, mit ihrem markanten schwarzen kugelförmigen Körper, mehreren Sensorarmen und dem bedrohlichen Aussehen, das sie sofort erkennbar machte. Dieser spezialisierte Build zeigt das einzigartige mechanische Design der Sondendroide mit detaillierter Konstruktion, die die fortschrittlichen Sensorpakete und Kommunikations-Arrays repräsentiert, die das weitreichende Überwachungsnetzwerk des Imperiums verkörpern. In Tausenden über abgelegene Sternensysteme verteilt, entdeckten diese Droiden die Rebellenbasis auf Hoth und lösten den verheerenden Angriff des Imperiums aus. In Sets ab 2010 veröffentlicht, einschließlich Hoth-Szenen und imperialen Einsatzszenarien, wurde diese Minifigur trotz ihres nicht-humanoiden Designs von Sammlern hochgradig begehrt, geschätzt für ihre genaue Darstellung einer der unvergesslichsten Eröffnungssequenzen von Das Imperium schlägt zurück, ihre Verbindung zum auslösenden Vorfall des Films und ihre Verkörperung der unterdrückerischen Allgegenwart des Imperiums, die die Rebellion zwang, sich in den unwirtlichsten Orten der Galaxie zu verstecken.',
    fr: 'La minifigurine LEGO du Droïde de Reconnaissance Impérial capture les unités de reconnaissance sinistres qui parcouraient la galaxie à la recherche de bases Rebelles, avec son corps sphérique noir distinctif, ses multiples bras de capteurs, et son apparence menaçante qui le rendait instantanément reconnaissable. Cette construction spécialisée présente le design mécanique unique du droïde de reconnaissance avec une construction détaillée représentant les packages de capteurs avancés et les réseaux de communication, incarnant le réseau de surveillance étendu de l\'Empire. Déployés par milliers à travers des systèmes stellaires éloignés, ces droïdes ont découvert la base Rebelle sur Hoth, déclenchant l\'assaut dévastateur de l\'Empire. Sortie dans des sets à partir de 2010 incluant des scènes de Hoth et des scénarios de déploiement Impérial, cette minifigurine est devenue très recherchée par les collectionneurs malgré son design non-humanoïde, prisée pour sa représentation précise de l\'une des séquences d\'ouverture les plus mémorables de L\'Empire Contre-Attaque, sa connexion à l\'incident déclencheur du film, et son incarnation de l\'omniprésence oppressive de l\'Empire qui a forcé la Rébellion à se cacher dans les endroits les plus inhospitaliers de la galaxie.',
    es: 'La minifigura LEGO del Droide de Sonda Imperial captura a las unidades de reconocimiento siniestras que recorrieron la galaxia cazando bases Rebeldes, presentando su distintivo cuerpo esférico negro, múltiples brazos de sensores, y la apariencia amenazante que lo hizo instantáneamente reconocible. Esta construcción especializada muestra el diseño mecánico único del droide de sonda con construcción detallada representando los paquetes de sensores avanzados y matrices de comunicación, encarnando la red de vigilancia de largo alcance del Imperio. Desplegados por miles a través de sistemas estelares remotos, estos droides descubrieron la base Rebelde en Hoth, desencadenando el devastador asalto del Imperio. Lanzada en sets desde 2010 incluyendo escenas de Hoth y escenarios de despliegue Imperial, esta minifigura se volvió muy buscada por coleccionistas a pesar de su diseño no-humanoide, apreciada por su representación precisa de una de las secuencias de apertura más memorables de El Imperio Contraataca, su conexión con el incidente desencadenante de la película, y su encarnación de la omnipresencia opresiva del Imperio que forzó a la Rebelión a esconderse en las ubicaciones más inhóspitas de la galaxia.'
  },
  {
    no: 'sw0285',
    name: 'Bossk',
    en: 'Bossk\'s LEGO minifigure portrays the fearsome Trandoshan bounty hunter with his distinctive reptilian features, yellow-orange skin tone, and the flight suit that marked him as one of the galaxy\'s most dangerous mercenaries. This minifigure captures the lizard-like alien with detailed printing showing his scaly texture and predatory appearance, representing the ruthless hunter hired by Darth Vader to track the Millennium Falcon after the Battle of Hoth. Known for his species\' regenerative abilities and violent nature, Bossk built a reputation through decades of successful hunts targeting Wookiees and other high-value prey across the Outer Rim. Released in sets from 2010 onwards including Slave I and bounty hunter collections, this minifigure became highly collectible among fans of The Empire Strikes Back\'s infamous bounty hunter lineup, sought after due to Bossk\'s intimidating design, his prominent appearance in extended Star Wars media, and his representation of the galaxy\'s criminal underworld that served the Empire when credits aligned with Imperial interests.',
    de: 'Die LEGO-Minifigur von Bossk porträtiert den furchterregenden Trandoshan-Kopfgeldjäger mit seinen markanten reptilienartigen Zügen, gelb-orangefarbenem Hautton und dem Fluganzug, der ihn als einen der gefährlichsten Söldner der Galaxie kennzeichnete. Diese Minifigur fängt den echsenartigen Außerirdischen mit detaillierter Bedruckung ein, die seine schuppige Textur und räuberisches Aussehen zeigt, die den rücksichtslosen Jäger repräsentiert, der von Darth Vader angeheuert wurde, um den Millennium Falken nach der Schlacht von Hoth aufzuspüren. Bekannt für die regenerativen Fähigkeiten und gewalttätige Natur seiner Spezies, baute Bossk sich über Jahrzehnte erfolgreicher Jagden einen Ruf auf, die auf Wookiees und andere hochwertige Beute im Äußeren Rand abzielten. In Sets ab 2010 veröffentlicht, einschließlich Slave I und Kopfgeldjäger-Sammlungen, wurde diese Minifigur unter Fans der berüchtigten Kopfgeldjäger-Aufstellung von Das Imperium schlägt zurück hochgradig sammelwürdig, begehrt aufgrund von Bossks einschüchterndem Design, seinem prominenten Auftreten in erweiterten Star Wars-Medien und seiner Darstellung der kriminellen Unterwelt der Galaxie, die dem Imperium diente, wenn Credits mit imperialen Interessen übereinstimmten.',
    fr: 'La minifigurine LEGO de Bossk dépeint le redoutable chasseur de primes Trandoshan avec ses traits reptiliens distinctifs, son teint de peau jaune-orange, et la combinaison de vol qui le marquait comme l\'un des mercenaires les plus dangereux de la galaxie. Cette minifigurine capture l\'alien semblable à un lézard avec une impression détaillée montrant sa texture écailleuse et son apparence prédatrice, représentant le chasseur impitoyable engagé par Dark Vador pour traquer le Faucon Millenium après la Bataille de Hoth. Connu pour les capacités régénératives et la nature violente de son espèce, Bossk s\'est bâti une réputation à travers des décennies de chasses réussies ciblant les Wookiees et autres proies de grande valeur à travers la Bordure Extérieure. Sortie dans des sets à partir de 2010 incluant Slave I et des collections de chasseurs de primes, cette minifigurine est devenue hautement collectionnable parmi les fans de la tristement célèbre formation de chasseurs de primes de L\'Empire Contre-Attaque, recherchée en raison du design intimidant de Bossk, son apparition proéminente dans les médias Star Wars étendus, et sa représentation du monde souterrain criminel de la galaxie qui servait l\'Empire lorsque les crédits s\'alignaient avec les intérêts Impériaux.',
    es: 'La minifigura LEGO de Bossk retrata al temible cazarrecompensas Trandoshano con sus distintivos rasgos reptilianos, tono de piel amarillo-naranja, y el traje de vuelo que lo marcaba como uno de los mercenarios más peligrosos de la galaxia. Esta minifigura captura al alienígena similar a un lagarto con impresión detallada mostrando su textura escamosa y apariencia depredadora, representando al cazador despiadado contratado por Darth Vader para rastrear al Halcón Milenario después de la Batalla de Hoth. Conocido por las habilidades regenerativas y naturaleza violenta de su especie, Bossk construyó una reputación a través de décadas de cazas exitosas apuntando a Wookiees y otras presas de alto valor a través del Borde Exterior. Lanzada en sets desde 2010 incluyendo Slave I y colecciones de cazarrecompensas, esta minifigura se volvió altamente coleccionable entre fans de la infame alineación de cazarrecompensas de El Imperio Contraataca, buscada debido al diseño intimidante de Bossk, su prominente aparición en medios extendidos de Star Wars, y su representación del inframundo criminal de la galaxia que servía al Imperio cuando los créditos se alineaban con intereses Imperiales.'
  },
  {
    no: 'sw0286',
    name: 'IG-88',
    en: 'IG-88\'s LEGO minifigure captures the deadly assassin droid with its distinctive skeletal appearance, bandolier of weapons, and the menacing design that made it one of the galaxy\'s most feared bounty hunters. This minifigure features specialized construction showing the droid\'s unique mechanical frame and sensor arrays, representing the rogue IG-series droid that escaped its manufacturers and became an independent killer. Armed with multiple weapons and possessing superior combat programming, IG-88 operated without the moral constraints of organic hunters, making it particularly dangerous to targets who valued their lives. Released in sets from 2011 onwards appearing in bounty hunter collections and cantina scenes, this minifigure became a favorite among collectors of The Empire Strikes Back\'s bounty hunter lineup, highly sought after due to IG-88\'s striking mechanical design, its brief but memorable appearance aboard the Executor, and its representation of the Star Wars universe\'s sophisticated yet dangerous droid technology that blurred the line between tool and autonomous killer.',
    de: 'Die LEGO-Minifigur von IG-88 fängt den tödlichen Attentäterdroiden mit seinem markanten skelettartigen Aussehen, Bandolier mit Waffen und dem bedrohlichen Design ein, das ihn zu einem der gefürchtetsten Kopfgeldjäger der Galaxie machte. Diese Minifigur verfügt über spezialisierte Konstruktion, die den einzigartigen mechanischen Rahmen und Sensor-Arrays des Droiden zeigt, die den abtrünnigen IG-Serien-Droiden repräsentiert, der seinen Herstellern entkam und zu einem unabhängigen Killer wurde. Bewaffnet mit mehreren Waffen und überlegener Kampfprogrammierung operierte IG-88 ohne die moralischen Einschränkungen organischer Jäger, was ihn besonders gefährlich für Ziele machte, die ihr Leben schätzten. In Sets ab 2011 veröffentlicht und in Kopfgeldjäger-Sammlungen und Cantina-Szenen erscheinend, wurde diese Minifigur zu einem Favoriten unter Sammlern der Kopfgeldjäger-Aufstellung von Das Imperium schlägt zurück, hochgradig begehrt aufgrund von IG-88s auffälligem mechanischen Design, seinem kurzen, aber unvergesslichen Auftritt an Bord der Executor und seiner Darstellung der ausgefeilten, aber gefährlichen Droidentechnologie des Star Wars-Universums, die die Grenze zwischen Werkzeug und autonomem Killer verwischte.',
    fr: 'La minifigurine LEGO d\'IG-88 capture le droïde assassin mortel avec son apparence squelettique distinctive, sa bandoulière d\'armes, et le design menaçant qui en a fait l\'un des chasseurs de primes les plus redoutés de la galaxie. Cette minifigurine présente une construction spécialisée montrant le cadre mécanique unique et les réseaux de capteurs du droïde, représentant le droïde série IG voyou qui a échappé à ses fabricants et est devenu un tueur indépendant. Armé de multiples armes et possédant une programmation de combat supérieure, IG-88 opérait sans les contraintes morales des chasseurs organiques, le rendant particulièrement dangereux pour les cibles qui valorisaient leurs vies. Sortie dans des sets à partir de 2011 apparaissant dans les collections de chasseurs de primes et les scènes de cantina, cette minifigurine est devenue une favorite parmi les collectionneurs de la formation de chasseurs de primes de L\'Empire Contre-Attaque, très recherchée en raison du design mécanique frappant d\'IG-88, son apparition brève mais mémorable à bord de l\'Executor, et sa représentation de la technologie de droïdes sophistiquée mais dangereuse de l\'univers Star Wars qui brouillait la ligne entre outil et tueur autonome.',
    es: 'La minifigura LEGO de IG-88 captura al mortífero droide asesino con su distintiva apariencia esquelética, bandolera de armas, y el diseño amenazante que lo hizo uno de los cazarrecompensas más temidos de la galaxia. Esta minifigura presenta construcción especializada mostrando el único marco mecánico y matrices de sensores del droide, representando al droide serie IG rebelde que escapó de sus fabricantes y se convirtió en un asesino independiente. Armado con múltiples armas y poseyendo programación de combate superior, IG-88 operaba sin las restricciones morales de cazadores orgánicos, haciéndolo particularmente peligroso para objetivos que valoraban sus vidas. Lanzada en sets desde 2011 apareciendo en colecciones de cazarrecompensas y escenas de cantina, esta minifigura se convirtió en favorita entre coleccionistas de la alineación de cazarrecompensas de El Imperio Contraataca, muy buscada debido al llamativo diseño mecánico de IG-88, su breve pero memorable aparición a bordo del Executor, y su representación de la tecnología de droides sofisticada pero peligrosa del universo Star Wars que difuminó la línea entre herramienta y asesino autónomo.'
  },
  {
    no: 'sw0287',
    name: '4-LOM',
    en: '4-LOM\'s LEGO minifigure depicts the protocol droid turned bounty hunter with its distinctive insectoid head design, worn plating, and the unique appearance marking its transformation from diplomatic service to criminal enterprises. This minifigure captures the droid\'s unusual combination of protocol programming and combat modifications with detailed printing showing its altered systems, representing one of the galaxy\'s most unusual career transitions from luxury liner attendant to ruthless hunter. Partnered with Zuckuss and reprogrammed to override its core diplomatic functions, 4-LOM brought analytical precision to bounty hunting that organic hunters lacked. Released in sets from 2012 onwards appearing in bounty hunter collections and Imperial recruitment scenes, this minifigure appeals to collectors seeking complete Empire Strikes Back bounty hunter rosters, highly sought after due to 4-LOM\'s unique insect-like design distinguishing it from humanoid characters, its representation of droid autonomy and self-modification, and its status as one of the more obscure bounty hunters that dedicated fans appreciate for deep Star Wars lore collection completion.',
    de: 'Die LEGO-Minifigur von 4-LOM zeigt den Protokolldroiden, der zum Kopfgeldjäger wurde, mit seinem markanten insektoiden Kopfdesign, abgenutzter Panzerung und dem einzigartigen Aussehen, das seine Verwandlung vom diplomatischen Dienst zu kriminellen Unternehmungen kennzeichnet. Diese Minifigur fängt die ungewöhnliche Kombination des Droiden aus Protokoll-Programmierung und Kampfmodifikationen mit detaillierter Bedruckung ein, die seine veränderten Systeme zeigt, die einen der ungewöhnlichsten Karriereübergänge der Galaxie vom Luxusliner-Begleiter zum rücksichtslosen Jäger repräsentiert. Mit Zuckuss gepaart und umprogrammiert, um seine diplomatischen Kernfunktionen zu überschreiben, brachte 4-LOM analytische Präzision zur Kopfgeldjagd, die organischen Jägern fehlte. In Sets ab 2012 veröffentlicht und in Kopfgeldjäger-Sammlungen und imperialen Rekrutierungsszenen erscheinend, spricht diese Minifigur Sammler an, die vollständige Empire Strikes Back-Kopfgeldjäger-Listen suchen, hochgradig begehrt aufgrund von 4-LOMs einzigartigem insektenartigen Design, das ihn von humanoiden Charakteren unterscheidet, seiner Darstellung von Droiden-Autonomie und Selbstmodifikation und seinem Status als einer der obskureren Kopfgeldjäger, den engagierte Fans für die Vervollständigung tiefgehender Star Wars-Überlieferungs-Sammlungen schätzen.',
    fr: 'La minifigurine LEGO de 4-LOM dépeint le droïde de protocole devenu chasseur de primes avec son design de tête insectoïde distinctif, son blindage usé, et l\'apparence unique marquant sa transformation du service diplomatique aux entreprises criminelles. Cette minifigurine capture la combinaison inhabituelle du droïde de programmation de protocole et de modifications de combat avec une impression détaillée montrant ses systèmes altérés, représentant l\'une des transitions de carrière les plus inhabituelles de la galaxie d\'accompagnateur de paquebot de luxe à chasseur impitoyable. Associé à Zuckuss et reprogrammé pour outrepasser ses fonctions diplomatiques de base, 4-LOM apportait une précision analytique à la chasse aux primes que les chasseurs organiques n\'avaient pas. Sortie dans des sets à partir de 2012 apparaissant dans les collections de chasseurs de primes et les scènes de recrutement Impérial, cette minifigurine plaît aux collectionneurs cherchant des listes complètes de chasseurs de primes de L\'Empire Contre-Attaque, très recherchée en raison du design unique semblable à un insecte de 4-LOM le distinguant des personnages humanoïdes, sa représentation de l\'autonomie et de l\'auto-modification des droïdes, et son statut comme l\'un des chasseurs de primes les plus obscurs que les fans dédiés apprécient pour compléter leur collection de tradition Star Wars profonde.',
    es: 'La minifigura LEGO de 4-LOM representa al droide de protocolo convertido en cazarrecompensas con su distintivo diseño de cabeza insectoide, blindaje desgastado, y la única apariencia marcando su transformación del servicio diplomático a empresas criminales. Esta minifigura captura la inusual combinación del droide de programación de protocolo y modificaciones de combate con impresión detallada mostrando sus sistemas alterados, representando una de las transiciones de carrera más inusuales de la galaxia desde asistente de transatlántico de lujo hasta cazador despiadado. Asociado con Zuckuss y reprogramado para anular sus funciones diplomáticas básicas, 4-LOM aportó precisión analítica a la caza de recompensas que los cazadores orgánicos carecían. Lanzada en sets desde 2012 apareciendo en colecciones de cazarrecompensas y escenas de reclutamiento Imperial, esta minifigura atrae a coleccionistas buscando listas completas de cazarrecompensas de El Imperio Contraataca, muy buscada debido al único diseño similar a insecto de 4-LOM distinguiéndolo de personajes humanoides, su representación de autonomía y automodificación de droides, y su estatus como uno de los cazarrecompensas más oscuros que fans dedicados aprecian para completar colecciones de tradición profunda de Star Wars.'
  },
  {
    no: 'sw0288',
    name: 'Dengar',
    en: 'Dengar\'s LEGO minifigure portrays the battle-scarred human bounty hunter with his distinctive wrapped head bandages, worn armor plating, and the weathered appearance reflecting decades of dangerous work across the galaxy\'s criminal underworld. This minifigure features detailed printing showing his makeshift armor and medical wrappings, representing the veteran hunter whose near-fatal encounter with Han Solo during swoop racing left him physically and mentally scarred, driving his obsessive pursuit of the Corellian smuggler. Armed with modified weaponry and possessing intimate knowledge of the Core Worlds\' criminal networks, Dengar combined human intuition with ruthless efficiency. Released in sets from 2010 onwards including bounty hunter collections and Cloud City scenes, this minifigure appeals to collectors completing The Empire Strikes Back\'s iconic bounty hunter lineup, sought after due to Dengar\'s gritty design conveying his dangerous profession, his backstory of personal vendetta adding depth to his character, and his representation of the galaxy\'s human criminals who chose bounty hunting over legitimate work in the Empire\'s oppressive regime.',
    de: 'Die LEGO-Minifigur von Dengar porträtiert den kampfvernarbten menschlichen Kopfgeldjäger mit seinen markanten gewickelten Kopfbandagen, abgenutzter Rüstungspanzerung und dem verwitterten Aussehen, das Jahrzehnte gefährlicher Arbeit in der kriminellen Unterwelt der Galaxie widerspiegelt. Diese Minifigur verfügt über detaillierte Bedruckung, die seine provisorische Rüstung und medizinischen Verbände zeigt, die den Veteranen-Jäger repräsentiert, dessen beinahe tödliche Begegnung mit Han Solo während eines Swoop-Rennens ihn körperlich und geistig vernarbt zurückließ und seine obsessive Verfolgung des corellianischen Schmuggler antrieb. Bewaffnet mit modifizierten Waffen und mit intimer Kenntnis der kriminellen Netzwerke der Kernwelten kombinierte Dengar menschliche Intuition mit rücksichtsloser Effizienz. In Sets ab 2010 veröffentlicht, einschließlich Kopfgeldjäger-Sammlungen und Cloud City-Szenen, spricht diese Minifigur Sammler an, die die ikonische Kopfgeldjäger-Aufstellung von Das Imperium schlägt zurück vervollständigen, begehrt aufgrund von Dengars grobkörnigem Design, das seinen gefährlichen Beruf vermittelt, seiner Hintergrundgeschichte persönlicher Vendetta, die seinem Charakter Tiefe verleiht, und seiner Darstellung der menschlichen Kriminellen der Galaxie, die Kopfgeldjagd statt legitimer Arbeit im unterdrückerischen Regime des Imperiums wählten.',
    fr: 'La minifigurine LEGO de Dengar dépeint le chasseur de primes humain marqué par les batailles avec ses bandages de tête enveloppés distinctifs, son blindage usé, et l\'apparence marquée reflétant des décennies de travail dangereux à travers le monde souterrain criminel de la galaxie. Cette minifigurine présente une impression détaillée montrant son armure de fortune et ses pansements médicaux, représentant le chasseur vétéran dont la rencontre presque fatale avec Han Solo pendant une course de swoop l\'a laissé physiquement et mentalement marqué, alimentant sa poursuite obsessionnelle du contrebandier Corellien. Armé d\'armes modifiées et possédant une connaissance intime des réseaux criminels des Mondes du Noyau, Dengar combinait l\'intuition humaine avec une efficacité impitoyable. Sortie dans des sets à partir de 2010 incluant des collections de chasseurs de primes et des scènes de Cloud City, cette minifigurine plaît aux collectionneurs complétant la formation emblématique de chasseurs de primes de L\'Empire Contre-Attaque, recherchée en raison du design brut de Dengar transmettant sa profession dangereuse, son histoire personnelle de vendetta ajoutant de la profondeur à son personnage, et sa représentation des criminels humains de la galaxie qui ont choisi la chasse aux primes plutôt que le travail légitime dans le régime oppressif de l\'Empire.',
    es: 'La minifigura LEGO de Dengar retrata al cazarrecompensas humano marcado por batallas con sus distintivos vendajes de cabeza envueltos, blindaje desgastado, y la apariencia curtida reflejando décadas de trabajo peligroso a través del inframundo criminal de la galaxia. Esta minifigura presenta impresión detallada mostrando su armadura improvisada y vendajes médicos, representando al cazador veterano cuyo encuentro casi fatal con Han Solo durante carreras de swoop lo dejó física y mentalmente marcado, impulsando su persecución obsesiva del contrabandista Corelliano. Armado con armamento modificado y poseyendo conocimiento íntimo de las redes criminales de los Mundos del Núcleo, Dengar combinó intuición humana con eficiencia despiadada. Lanzada en sets desde 2010 incluyendo colecciones de cazarrecompensas y escenas de Cloud City, esta minifigura atrae a coleccionistas completando la icónica alineación de cazarrecompensas de El Imperio Contraataca, buscada debido al diseño áspero de Dengar transmitiendo su profesión peligrosa, su trasfondo de venganza personal añadiendo profundidad a su personaje, y su representación de los criminales humanos de la galaxia que eligieron la caza de recompensas sobre trabajo legítimo en el régimen opresivo del Imperio.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 176-180 (sw0284-sw0288)...\n');

  for (const m of batch) {
    await prisma.minifigCatalog.upsert({
      where: { minifigure_no: m.no },
      update: {
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      },
      create: {
        minifigure_no: m.no,
        name: m.name,
        category_id: 1,
        category_name: 'Star Wars',
        search_name: m.name.toLowerCase(),
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`  ✅ ${m.no}: ${m.name}`);
  }

  console.log('\n✨ Batch 176-180 complete: 5 minifigs (20 descriptions)');
  await prisma.$disconnect();
}

saveBatch().catch(console.error);