import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0349',
    name: 'Rebel Trooper - Hoth',
    en: 'Rebel Troopers on Hoth defended Echo Base against the Imperial invasion in The Empire Strikes Back, wearing specialized cold weather gear for survival on the ice planet. This minifigure features distinctive white and tan winter uniform with insulated vest printing, survival backpack, and typically includes a blaster rifle. These brave soldiers manned the trenches and anti-vehicle cannons during the desperate defense of the Rebel base. Released in numerous Hoth battle sets including defense trenches and Echo Base playsets, these troopers are essential for recreating the iconic opening battle and represent the Rebellion\'s resourcefulness in hostile environments.',
    de: 'Rebellentruppen auf Hoth verteidigten die Echo-Basis gegen die imperiale Invasion in Das Imperium schlägt zurück und trugen spezialisierte Kaltwetterausrüstung zum Überleben auf dem Eisplaneten. Diese Minifigur zeigt eine charakteristische weiße und hellbraune Winteruniform mit isoliertem Westendruck, Überlebensrucksack und enthält typischerweise ein Blastergewehr. Diese tapferen Soldaten besetzten die Schützengräben und Panzerabwehrkanonen während der verzweifelten Verteidigung der Rebellenbasis. Veröffentlicht in zahlreichen Hoth-Schlacht-Sets, darunter Verteidigungsschützengräben und Echo-Basis-Spielsets, sind diese Truppen unerlässlich für die Nachstellung der ikonischen Eröffnungsschlacht und repräsentieren die Einfallsreichtum der Rebellion in feindlichen Umgebungen.',
    fr: 'Les Soldats Rebelles sur Hoth ont défendu la Base Echo contre l\'invasion impériale dans L\'Empire Contre-Attaque, portant un équipement spécialisé par temps froid pour survivre sur la planète de glace. Cette minifigurine présente un uniforme d\'hiver blanc et beige distinctif avec impression de gilet isolé, sac à dos de survie, et inclut généralement un fusil blaster. Ces braves soldats ont occupé les tranchées et les canons anti-véhicules pendant la défense désespérée de la base rebelle. Sortie dans de nombreux sets de bataille de Hoth, y compris des tranchées de défense et des playsets de Base Echo, ces soldats sont essentiels pour recréer la bataille d\'ouverture iconique et représentent l\'ingéniosité de la Rébellion dans des environnements hostiles.',
    es: 'Los Soldados Rebeldes en Hoth defendieron la Base Echo contra la invasión Imperial en El Imperio Contraataca, vistiendo equipo especializado de clima frío para sobrevivir en el planeta de hielo. Esta minifigura presenta distintivo uniforme de invierno blanco y beige con impresión de chaleco aislado, mochila de supervivencia, y normalmente incluye un rifle bláster. Estos valientes soldados ocuparon las trincheras y cañones anti-vehículo durante la desesperada defensa de la base rebelde. Lanzada en numerosos sets de batalla de Hoth incluyendo trincheras de defensa y playsets de Base Echo, estos soldados son esenciales para recrear la icónica batalla de apertura y representan el ingenio de la Rebelión en ambientes hostiles.'
  },
  {
    no: 'sw0350',
    name: 'Luke Skywalker - Hoth',
    en: 'Luke Skywalker in his Hoth outfit represents the young Jedi-in-training during the pivotal events of The Empire Strikes Back\'s opening battle. This minifigure captures Luke wearing his insulated tan and brown winter gear with detailed printing, survival backpack, and typically includes his lightsaber and blaster. From surviving a Wampa attack to destroying an AT-AT with a thermal detonator, Luke\'s heroics on Hoth showcase his growing abilities. Released in countless Hoth-themed sets including Snowspeeder and Wampa Cave, this is one of the most frequently produced Luke variants and essential for any Empire Strikes Back collection.',
    de: 'Luke Skywalker in seiner Hoth-Kleidung repräsentiert den jungen Jedi-in-Ausbildung während der entscheidenden Ereignisse der Eröffnungsschlacht von Das Imperium schlägt zurück. Diese Minifigur zeigt Luke in seiner isolierten hellbraunen und braunen Winterausrüstung mit detailliertem Druck, Überlebensrucksack und enthält typischerweise sein Lichtschwert und einen Blaster. Vom Überleben eines Wampa-Angriffs bis zur Zerstörung eines AT-AT mit einem Thermaldetonator zeigen Lukes Heldentaten auf Hoth seine wachsenden Fähigkeiten. Veröffentlicht in zahllosen Hoth-themenbezogenen Sets, darunter Snowspeeder und Wampa-Höhle, ist dies eine der am häufigsten produzierten Luke-Varianten und unerlässlich für jede Das Imperium schlägt zurück-Sammlung.',
    fr: 'Luke Skywalker dans sa tenue de Hoth représente le jeune Jedi en formation pendant les événements cruciaux de la bataille d\'ouverture de L\'Empire Contre-Attaque. Cette minifigurine capture Luke portant son équipement d\'hiver isolé beige et brun avec impression détaillée, sac à dos de survie, et inclut généralement son sabre laser et blaster. De la survie d\'une attaque de Wampa à la destruction d\'un AT-AT avec un détonateur thermique, les exploits héroïques de Luke sur Hoth montrent ses capacités croissantes. Sortie dans d\'innombrables sets à thème Hoth, y compris Snowspeeder et Grotte Wampa, c\'est l\'une des variantes Luke les plus fréquemment produites et essentielle pour toute collection L\'Empire Contre-Attaque.',
    es: 'Luke Skywalker en su atuendo de Hoth representa al joven Jedi en entrenamiento durante los eventos cruciales de la batalla de apertura de El Imperio Contraataca. Esta minifigura captura a Luke vistiendo su equipo de invierno aislado beige y marrón con impresión detallada, mochila de supervivencia, y normalmente incluye su sable de luz y bláster. Desde sobrevivir un ataque Wampa hasta destruir un AT-AT con un detonador térmico, las hazañas heroicas de Luke en Hoth muestran sus habilidades crecientes. Lanzada en innumerables sets con tema de Hoth incluyendo Snowspeeder y Cueva Wampa, esta es una de las variantes de Luke más frecuentemente producidas y esencial para cualquier colección de El Imperio Contraataca.'
  },
  {
    no: 'sw0351',
    name: 'Han Solo - Hoth',
    en: 'Han Solo in his Hoth gear represents the smuggler-turned-hero during the evacuation of Echo Base in The Empire Strikes Back. This minifigure depicts Han wearing his distinctive blue parka jacket with fur-lined hood, tan pants, and survival equipment. From rescuing Luke from the frozen wasteland to commanding the evacuation, Han\'s leadership shines during the Hoth crisis. Released in numerous sets including the Millennium Falcon Hoth versions and Echo Base playsets, this is one of the most iconic Han Solo variants and captures his transition from selfish smuggler to committed Rebel leader.',
    de: 'Han Solo in seiner Hoth-Ausrüstung repräsentiert den Schmuggler-wird-Held während der Evakuierung der Echo-Basis in Das Imperium schlägt zurück. Diese Minifigur zeigt Han in seiner charakteristischen blauen Parka-Jacke mit pelzgefütterter Kapuze, hellbraunen Hosen und Überlebensausrüstung. Von der Rettung von Luke aus der gefrorenen Einöde bis zum Kommandieren der Evakuierung glänzt Hans Führung während der Hoth-Krise. Veröffentlicht in zahlreichen Sets, darunter die Millennium Falcon Hoth-Versionen und Echo-Basis-Spielsets, ist dies eine der ikonischsten Han Solo-Varianten und erfasst seinen Übergang vom egoistischen Schmuggler zum engagierten Rebellenführer.',
    fr: 'Han Solo dans son équipement de Hoth représente le contrebandier devenu héros pendant l\'évacuation de la Base Echo dans L\'Empire Contre-Attaque. Cette minifigurine dépeint Han portant sa veste parka bleue distinctive avec capuche doublée de fourrure, pantalon beige, et équipement de survie. Du sauvetage de Luke des terres gelées au commandement de l\'évacuation, le leadership d\'Han brille pendant la crise de Hoth. Sortie dans de nombreux sets, y compris les versions Faucon Millenium Hoth et playsets de Base Echo, c\'est l\'une des variantes Han Solo les plus iconiques et capture sa transition de contrebandier égoïste à leader rebelle engagé.',
    es: 'Han Solo en su equipo de Hoth representa al contrabandista convertido en héroe durante la evacuación de la Base Echo en El Imperio Contraataca. Esta minifigura representa a Han vistiendo su distintiva chaqueta parka azul con capucha forrada de piel, pantalones beige y equipo de supervivencia. Desde rescatar a Luke del páramo congelado hasta comandar la evacuación, el liderazgo de Han brilla durante la crisis de Hoth. Lanzada en numerosos sets incluyendo las versiones del Halcón Milenario de Hoth y playsets de Base Echo, esta es una de las variantes de Han Solo más icónicas y captura su transición de contrabandista egoísta a líder rebelde comprometido.'
  },
  {
    no: 'sw0352',
    name: 'Princess Leia - Hoth',
    en: 'Princess Leia in her Hoth uniform commanded the evacuation of Echo Base during the Imperial assault in The Empire Strikes Back. This minifigure depicts Leia wearing her practical white and gray winter vest over turtleneck, with her distinctive braided hairstyle wrapped around her head. As the base commander coordinating the desperate escape, Leia demonstrates her military leadership and cool composure under pressure. Released in various Hoth battle sets and Echo Base playsets, this variant captures one of Leia\'s most commanding moments and showcases her evolution from princess to general.',
    de: 'Prinzessin Leia in ihrer Hoth-Uniform befehligte die Evakuierung der Echo-Basis während des imperialen Angriffs in Das Imperium schlägt zurück. Diese Minifigur zeigt Leia in ihrer praktischen weißen und grauen Winterweste über Rollkragenpullover, mit ihrer charakteristischen geflochtenen Frisur um ihren Kopf gewickelt. Als Basiskommandantin, die die verzweifelte Flucht koordiniert, demonstriert Leia ihre militärische Führung und kühle Fassung unter Druck. Veröffentlicht in verschiedenen Hoth-Schlacht-Sets und Echo-Basis-Spielsets, erfasst diese Variante einen von Leias kommandierendsten Momenten und zeigt ihre Evolution von Prinzessin zu General.',
    fr: 'La Princesse Leia dans son uniforme de Hoth a commandé l\'évacuation de la Base Echo pendant l\'assaut impérial dans L\'Empire Contre-Attaque. Cette minifigurine dépeint Leia portant son gilet d\'hiver blanc et gris pratique sur col roulé, avec sa coiffure tressée distinctive enroulée autour de sa tête. En tant que commandante de base coordonnant l\'évasion désespérée, Leia démontre son leadership militaire et son sang-froid sous pression. Sortie dans divers sets de bataille de Hoth et playsets de Base Echo, cette variante capture l\'un des moments les plus commandants de Leia et montre son évolution de princesse à général.',
    es: 'La Princesa Leia en su uniforme de Hoth comandó la evacuación de la Base Echo durante el asalto Imperial en El Imperio Contraataca. Esta minifigura representa a Leia vistiendo su práctico chaleco de invierno blanco y gris sobre cuello alto, con su distintivo peinado trenzado envuelto alrededor de su cabeza. Como comandante de base coordinando el escape desesperado, Leia demuestra su liderazgo militar y compostura bajo presión. Lanzada en varios sets de batalla de Hoth y playsets de Base Echo, esta variante captura uno de los momentos más al mando de Leia y muestra su evolución de princesa a general.'
  },
  {
    no: 'sw0353',
    name: 'Dack Ralter',
    en: 'Dack Ralter was Luke Skywalker\'s enthusiastic snowspeeder gunner during the Battle of Hoth, tragically killed during their assault on the AT-AT walkers. This minifigure depicts Dack in his Rebel pilot uniform with orange flight suit details, helmet with visor, and represents one of the few named Rebel pilots with dialogue in The Empire Strikes Back. His memorable line "That armor\'s too strong for blasters" and tragic death make him a poignant character. Released in premium Snowspeeder sets, this minifigure is valued by collectors for completing authentic Hoth battle scenes and honoring fallen Rebel heroes.',
    de: 'Dack Ralter war Luke Skywalkers enthusiastischer Snowspeeder-Schütze während der Schlacht um Hoth, tragisch getötet während ihres Angriffs auf die AT-AT-Läufer. Diese Minifigur zeigt Dack in seiner Rebellenpiloten-Uniform mit orangen Fluganzug-Details, Helm mit Visier und repräsentiert einen der wenigen benannten Rebellenpiloten mit Dialog in Das Imperium schlägt zurück. Seine einprägsame Zeile "Diese Panzerung ist zu stark für Blaster" und sein tragischer Tod machen ihn zu einem ergreifenden Charakter. Veröffentlicht in Premium-Snowspeeder-Sets, wird diese Minifigur von Sammlern geschätzt, um authentische Hoth-Schlacht-Szenen zu vervollständigen und gefallene Rebellenhelden zu ehren.',
    fr: 'Dack Ralter était le mitrailleur enthousiaste de snowspeeder de Luke Skywalker pendant la Bataille de Hoth, tragiquement tué pendant leur assaut sur les marcheurs AT-AT. Cette minifigurine dépeint Dack dans son uniforme de pilote rebelle avec des détails de combinaison de vol orange, casque avec visière, et représente l\'un des rares pilotes rebelles nommés avec dialogue dans L\'Empire Contre-Attaque. Sa ligne mémorable "Cette armure est trop forte pour les blasters" et sa mort tragique en font un personnage poignant. Sortie dans des sets Snowspeeder premium, cette minifigurine est appréciée par les collectionneurs pour compléter des scènes de bataille de Hoth authentiques et honorer les héros rebelles tombés.',
    es: 'Dack Ralter fue el entusiasta artillero de snowspeeder de Luke Skywalker durante la Batalla de Hoth, trágicamente asesinado durante su asalto en los caminantes AT-AT. Esta minifigura representa a Dack en su uniforme de piloto rebelde con detalles de traje de vuelo naranja, casco con visor, y representa uno de los pocos pilotos rebeldes nombrados con diálogo en El Imperio Contraataca. Su línea memorable "Esa armadura es demasiado fuerte para blásteres" y su muerte trágica lo hacen un personaje conmovedor. Lanzada en sets premium de Snowspeeder, esta minifigura es valorada por coleccionistas para completar escenas auténticas de batalla de Hoth y honrar héroes rebeldes caídos.'
  },
  {
    no: 'sw0354',
    name: 'Wes Janson',
    en: 'Wes Janson was a skilled Rebel pilot and gunner who flew as part of Rogue Squadron during the Battle of Hoth in The Empire Strikes Back. This minifigure depicts Janson in his orange Rebel flight suit with helmet, representing one of the veteran pilots who helped cover the evacuation. Famous for successfully using the harpoon and tow cable to bring down an AT-AT walker, Janson showcases Rebel ingenuity and piloting skill. Released in various Snowspeeder sets, this minifigure adds authenticity to Hoth battle displays and represents the brave pilots who turned the tide of the ground battle.',
    de: 'Wes Janson war ein geschickter Rebellenpilot und Schütze, der als Teil der Rogue Squadron während der Schlacht um Hoth in Das Imperium schlägt zurück flog. Diese Minifigur zeigt Janson in seinem orangen Rebellenfluganzug mit Helm und repräsentiert einen der Veteranenpiloten, die halfen, die Evakuierung zu decken. Berühmt dafür, erfolgreich die Harpune und das Abschleppseil verwendet zu haben, um einen AT-AT-Läufer zu Fall zu bringen, zeigt Janson den Einfallsreichtum und die Pilotenfähigkeiten der Rebellen. Veröffentlicht in verschiedenen Snowspeeder-Sets, fügt diese Minifigur Authentizität zu Hoth-Schlacht-Displays hinzu und repräsentiert die tapferen Piloten, die das Blatt der Bodenschlacht wendeten.',
    fr: 'Wes Janson était un pilote rebelle qualifié et mitrailleur qui a volé dans le cadre de l\'Escadron Rogue pendant la Bataille de Hoth dans L\'Empire Contre-Attaque. Cette minifigurine dépeint Janson dans sa combinaison de vol rebelle orange avec casque, représentant l\'un des pilotes vétérans qui ont aidé à couvrir l\'évacuation. Célèbre pour avoir utilisé avec succès le harpon et le câble de remorquage pour faire tomber un marcheur AT-AT, Janson met en valeur l\'ingéniosité rebelle et les compétences de pilotage. Sortie dans divers sets Snowspeeder, cette minifigurine ajoute de l\'authenticité aux displays de bataille de Hoth et représente les pilotes courageux qui ont renversé le cours de la bataille terrestre.',
    es: 'Wes Janson fue un piloto rebelde hábil y artillero que voló como parte del Escuadrón Rogue durante la Batalla de Hoth en El Imperio Contraataca. Esta minifigura representa a Janson en su traje de vuelo rebelde naranja con casco, representando uno de los pilotos veteranos que ayudaron a cubrir la evacuación. Famoso por usar exitosamente el arpón y cable de remolque para derribar un caminante AT-AT, Janson muestra el ingenio rebelde y habilidad de pilotaje. Lanzada en varios sets de Snowspeeder, esta minifigura añade autenticidad a las exhibiciones de batalla de Hoth y representa a los valientes pilotos que cambiaron el curso de la batalla terrestre.'
  },
  {
    no: 'sw0355',
    name: 'Zev Senesca',
    en: 'Zev Senesca, callsign "Rogue Two," was the Rebel pilot who located and rescued Luke Skywalker and Han Solo from the Hoth wasteland in The Empire Strikes Back. This minifigure depicts Zev in his orange and white Rebel pilot uniform with helmet, representing the scout who saved Luke\'s life. His famous line "Echo Base, I\'ve got something! Not much, but it could be a life form" marks one of the film\'s most crucial rescue moments. Released in various Hoth-themed sets, this minifigure commemorates an unsung hero whose quick action prevented Luke\'s death on the frozen planet.',
    de: 'Zev Senesca, Rufzeichen "Rogue Two," war der Rebellenpilot, der Luke Skywalker und Han Solo aus der Hoth-Einöde in Das Imperium schlägt zurück lokalisierte und rettete. Diese Minifigur zeigt Zev in seiner orangen und weißen Rebellenpiloten-Uniform mit Helm und repräsentiert den Kundschafter, der Lukes Leben rettete. Seine berühmte Zeile "Echo-Basis, ich habe etwas! Nicht viel, aber es könnte eine Lebensform sein" markiert einen der entscheidendsten Rettungsmomente des Films. Veröffentlicht in verschiedenen Hoth-themenbezogenen Sets, gedenkt diese Minifigur eines unbesungenen Helden, dessen schnelles Handeln Lukes Tod auf dem gefrorenen Planeten verhinderte.',
    fr: 'Zev Senesca, indicatif d\'appel "Rogue Two," était le pilote rebelle qui a localisé et secouru Luke Skywalker et Han Solo des terres désolées de Hoth dans L\'Empire Contre-Attaque. Cette minifigurine dépeint Zev dans son uniforme de pilote rebelle orange et blanc avec casque, représentant l\'éclaireur qui a sauvé la vie de Luke. Sa ligne célèbre "Base Echo, j\'ai quelque chose ! Pas grand-chose, mais ça pourrait être une forme de vie" marque l\'un des moments de sauvetage les plus cruciaux du film. Sortie dans divers sets à thème Hoth, cette minifigurine commémore un héros méconnu dont l\'action rapide a empêché la mort de Luke sur la planète gelée.',
    es: 'Zev Senesca, indicativo "Rogue Two," fue el piloto rebelde que localizó y rescató a Luke Skywalker y Han Solo del páramo de Hoth en El Imperio Contraataca. Esta minifigura representa a Zev en su uniforme de piloto rebelde naranja y blanco con casco, representando al explorador que salvó la vida de Luke. Su famosa línea "Base Echo, ¡tengo algo! No mucho, pero podría ser una forma de vida" marca uno de los momentos de rescate más cruciales de la película. Lanzada en varios sets con tema de Hoth, esta minifigura conmemora un héroe anónimo cuya acción rápida previno la muerte de Luke en el planeta congelado.'
  },
  {
    no: 'sw0356',
    name: 'Wampa',
    en: 'The Wampa is the fearsome ice creature native to Hoth that attacked and captured Luke Skywalker in the opening scenes of The Empire Strikes Back. This minifigure captures the Wampa\'s terrifying appearance with white fur, massive clawed hands, horned head, and snarling expression. Luke\'s escape from the Wampa cave by using his lightsaber to sever the creature\'s arm is an iconic moment showcasing his developing Force abilities. Released in specialized Wampa Cave sets, this creature minifigure is essential for recreating one of the most memorable opening sequences in Star Wars and remains a fan-favorite for its unique monster design.',
    de: 'Der Wampa ist die furchteinflößende Eiskreatur, die auf Hoth heimisch ist und Luke Skywalker in den Eröffnungsszenen von Das Imperium schlägt zurück angriff und gefangen nahm. Diese Minifigur erfasst das erschreckende Aussehen des Wampa mit weißem Fell, massiven bekrallten Händen, gehörntem Kopf und knurrendem Ausdruck. Lukes Flucht aus der Wampa-Höhle, indem er sein Lichtschwert benutzt, um den Arm der Kreatur abzutrennen, ist ein ikonischer Moment, der seine sich entwickelnden Macht-Fähigkeiten zeigt. Veröffentlicht in spezialisierten Wampa-Höhlen-Sets, ist diese Kreaturen-Minifigur unerlässlich für die Nachstellung einer der einprägsamsten Eröffnungssequenzen in Star Wars und bleibt ein Fanfavorit wegen ihres einzigartigen Monsterdesigns.',
    fr: 'Le Wampa est la créature de glace redoutable native de Hoth qui a attaqué et capturé Luke Skywalker dans les scènes d\'ouverture de L\'Empire Contre-Attaque. Cette minifigurine capture l\'apparence terrifiante du Wampa avec fourrure blanche, mains massives griffues, tête cornue, et expression grondante. L\'évasion de Luke de la grotte Wampa en utilisant son sabre laser pour sectionner le bras de la créature est un moment iconique montrant ses capacités de Force en développement. Sortie dans des sets spécialisés de Grotte Wampa, cette minifigurine de créature est essentielle pour recréer l\'une des séquences d\'ouverture les plus mémorables de Star Wars et reste une favorite des fans pour son design de monstre unique.',
    es: 'El Wampa es la temible criatura de hielo nativa de Hoth que atacó y capturó a Luke Skywalker en las escenas de apertura de El Imperio Contraataca. Esta minifigura captura la aterradora apariencia del Wampa con pelaje blanco, manos masivas con garras, cabeza con cuernos y expresión gruñona. El escape de Luke de la cueva Wampa usando su sable de luz para cortar el brazo de la criatura es un momento icónico que muestra sus habilidades de Fuerza en desarrollo. Lanzada en sets especializados de Cueva Wampa, esta minifigura de criatura es esencial para recrear una de las secuencias de apertura más memorables en Star Wars y sigue siendo una favorita de los fans por su diseño único de monstruo.'
  },
  {
    no: 'sw0357',
    name: 'Luke Skywalker - Dagobah',
    en: 'Luke Skywalker on Dagobah represents his intensive Jedi training under Master Yoda in The Empire Strikes Back. This minifigure depicts Luke in his simple training outfit with tan shirt, brown vest, and utility belt, without the elaborate gear of other environments. During his time in the swamp planet\'s misty forests, Luke learns to trust the Force and confronts his inner darkness in the cave. Released in various Dagobah training sets including Yoda\'s Hut, this variant captures one of Luke\'s most transformative journeys and his evolution from impatient student to potential Jedi Knight.',
    de: 'Luke Skywalker auf Dagobah repräsentiert sein intensives Jedi-Training unter Meister Yoda in Das Imperium schlägt zurück. Diese Minifigur zeigt Luke in seinem einfachen Trainingsoutfit mit hellbraunem Hemd, brauner Weste und Werkzeuggürtel, ohne die aufwendige Ausrüstung anderer Umgebungen. Während seiner Zeit in den nebligen Wäldern des Sumpfplaneten lernt Luke, der Macht zu vertrauen und konfrontiert seine innere Dunkelheit in der Höhle. Veröffentlicht in verschiedenen Dagobah-Trainings-Sets, darunter Yodas Hütte, erfasst diese Variante eine von Lukes transformativsten Reisen und seine Evolution vom ungeduldigen Schüler zum potenziellen Jedi-Ritter.',
    fr: 'Luke Skywalker sur Dagobah représente son entraînement Jedi intensif sous Maître Yoda dans L\'Empire Contre-Attaque. Cette minifigurine dépeint Luke dans sa tenue d\'entraînement simple avec chemise beige, gilet brun, et ceinture utilitaire, sans l\'équipement élaboré d\'autres environnements. Pendant son temps dans les forêts brumeuses de la planète marécageuse, Luke apprend à faire confiance à la Force et confronte ses ténèbres intérieures dans la grotte. Sortie dans divers sets d\'entraînement Dagobah, y compris la Hutte de Yoda, cette variante capture l\'un des voyages les plus transformateurs de Luke et son évolution d\'étudiant impatient à potentiel Chevalier Jedi.',
    es: 'Luke Skywalker en Dagobah representa su intensivo entrenamiento Jedi bajo el Maestro Yoda en El Imperio Contraataca. Esta minifigura representa a Luke en su simple atuendo de entrenamiento con camisa beige, chaleco marrón y cinturón utilitario, sin el equipo elaborado de otros ambientes. Durante su tiempo en los bosques neblinosos del planeta pantanoso, Luke aprende a confiar en la Fuerza y confronta su oscuridad interior en la cueva. Lanzada en varios sets de entrenamiento de Dagobah incluyendo la Cabaña de Yoda, esta variante captura uno de los viajes más transformadores de Luke y su evolución de estudiante impaciente a potencial Caballero Jedi.'
  },
  {
    no: 'sw0358',
    name: 'Yoda',
    en: 'Yoda, the legendary Jedi Master, trained Luke Skywalker in the ways of the Force on the swamp planet Dagobah in The Empire Strikes Back. This minifigure captures Yoda\'s distinctive appearance with his short green body, large pointed ears, wrinkled face, and simple brown robe. At 900 years old, Yoda represents the wisdom and power of the Jedi Order, teaching Luke patience, concentration, and the true nature of the Force. Released in numerous Dagobah and Jedi-themed sets, this is one of the most iconic Star Wars minifigures and essential for any collection, representing one of cinema\'s most beloved characters.',
    de: 'Yoda, der legendäre Jedi-Meister, trainierte Luke Skywalker in den Wegen der Macht auf dem Sumpfplaneten Dagobah in Das Imperium schlägt zurück. Diese Minifigur erfasst Yodas charakteristisches Aussehen mit seinem kurzen grünen Körper, großen spitzen Ohren, faltigen Gesicht und einfacher brauner Robe. Mit 900 Jahren repräsentiert Yoda die Weisheit und Macht des Jedi-Ordens und lehrt Luke Geduld, Konzentration und die wahre Natur der Macht. Veröffentlicht in zahlreichen Dagobah- und Jedi-themenbezogenen Sets, ist dies eine der ikonischsten Star Wars-Minifiguren und unerlässlich für jede Sammlung, repräsentierend eine der beliebtesten Figuren des Kinos.',
    fr: 'Yoda, le légendaire Maître Jedi, a entraîné Luke Skywalker dans les voies de la Force sur la planète marécageuse Dagobah dans L\'Empire Contre-Attaque. Cette minifigurine capture l\'apparence distinctive de Yoda avec son petit corps vert, grandes oreilles pointues, visage ridé, et simple robe brune. À 900 ans, Yoda représente la sagesse et le pouvoir de l\'Ordre Jedi, enseignant à Luke la patience, la concentration, et la vraie nature de la Force. Sortie dans de nombreux sets Dagobah et à thème Jedi, c\'est l\'une des minifigurines Star Wars les plus iconiques et essentielle pour toute collection, représentant l\'un des personnages les plus aimés du cinéma.',
    es: 'Yoda, el legendario Maestro Jedi, entrenó a Luke Skywalker en los caminos de la Fuerza en el planeta pantanoso Dagobah en El Imperio Contraataca. Esta minifigura captura la apariencia distintiva de Yoda con su pequeño cuerpo verde, grandes orejas puntiagudas, cara arrugada y simple túnica marrón. A los 900 años, Yoda representa la sabiduría y poder de la Orden Jedi, enseñando a Luke paciencia, concentración y la verdadera naturaleza de la Fuerza. Lanzada en numerosos sets de Dagobah y con tema Jedi, esta es una de las minifiguras de Star Wars más icónicas y esencial para cualquier colección, representando uno de los personajes más queridos del cine.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 241-250 (sw0349-sw0358) - 10 minifigs...\n');

  for (const m of batch) {
    try {
      await prisma.minifigCatalog.upsert({
        where: { minifigure_no: m.no },
        update: {
          description_en: m.en,
          description_de: m.de,
          description_fr: m.fr,
          description_es: m.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        },
        create: {
          minifigure_no: m.no,
          name: m.name,
          category_id: 1,
          category_name: 'Star Wars',
          search_name: m.name.toLowerCase(),
          description_en: m.en,
          description_de: m.de,
          description_fr: m.fr,
          description_es: m.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        }
      });
      console.log(`  ✅ ${m.no}: ${m.name}`);
    } catch (error: any) {
      console.error(`  ❌ ${m.no}: ${error.message}`);
    }
  }

  console.log('\n✨ Batch 241-250 complete: 10 minifigs (40 descriptions)');
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
