import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0199',
    name: 'Chewbacca (Hoth)',
    en: "Chewbacca assists in defending Echo Base on Hoth while repairing the Millennium Falcon for the desperate evacuation, wearing cold-weather gear over his fur. This LEGO minifigure captures Chewie's appearance during The Empire Strikes Back's opening with additional equipment straps and tools for mechanical work. First released in 2011, Hoth Chewbacca represents his crucial role maintaining the Falcon under extreme conditions. The figure features detailed printing showing tool belts and equipment pouches over his natural fur coat. Collectors value Hoth Chewie for his mechanical expertise during the siege and his loyalty to Han during the evacuation. His constant work keeping the Falcon operational while under Imperial attack makes this version essential for recreating Echo Base hangar scenes and the frantic escape from Hoth.",
    de: "Chewbacca hilft bei der Verteidigung der Echo-Basis auf Hoth, während er den Millennium Falken für die verzweifelte Evakuierung repariert und trägt Kälteschutzausrüstung über seinem Fell. Diese LEGO-Minifigur fängt Chewies Aussehen während der Eröffnung von Das Imperium schlägt zurück mit zusätzlichen Ausrüstungsriemen und Werkzeugen für mechanische Arbeit ein. Erstmals 2011 veröffentlicht, repräsentiert Hoth-Chewbacca seine entscheidende Rolle bei der Wartung des Falken unter extremen Bedingungen. Die Figur zeigt detaillierte Bedruckung mit Werkzeuggürteln und Ausrüstungstaschen über seinem natürlichen Fellmantel. Sammler schätzen Hoth-Chewie für seine mechanische Expertise während der Belagerung und seine Loyalität zu Han während der Evakuierung. Seine ständige Arbeit, den Falken betriebsbereit zu halten, während er unter imperialem Angriff steht, macht diese Version unverzichtbar für die Nachbildung von Echo-Basis-Hangarszenen und der hektischen Flucht von Hoth.",
    fr: "Chewbacca aide à défendre la Base Echo sur Hoth tout en réparant le Faucon Millenium pour l'évacuation désespérée, portant un équipement pour temps froid par-dessus sa fourrure. Cette minifigurine LEGO capture l'apparence de Chewie pendant l'ouverture de L'Empire contre-attaque avec des sangles d'équipement supplémentaires et des outils pour le travail mécanique. Sortie pour la première fois en 2011, Chewbacca de Hoth représente son rôle crucial dans le maintien du Faucon dans des conditions extrêmes. La figurine présente une impression détaillée montrant des ceintures à outils et des pochettes d'équipement par-dessus son manteau de fourrure naturelle. Les collectionneurs apprécient Chewie de Hoth pour son expertise mécanique pendant le siège et sa loyauté envers Han pendant l'évacuation. Son travail constant pour maintenir le Faucon opérationnel sous l'attaque Impériale fait de cette version un élément essentiel pour recréer les scènes de hangar de la Base Echo et l'évasion frénétique de Hoth.",
    es: "Chewbacca asiste en defender la Base Eco en Hoth mientras repara al Halcón Milenario para la evacuación desesperada, usando equipo para clima frío sobre su pelaje. Esta minifigura LEGO captura la apariencia de Chewie durante la apertura de El Imperio Contraataca con correas de equipo adicionales y herramientas para trabajo mecánico. Lanzada por primera vez en 2011, Chewbacca de Hoth representa su papel crucial manteniendo al Halcón bajo condiciones extremas. La figura presenta impresión detallada mostrando cinturones de herramientas y bolsas de equipo sobre su abrigo de pelaje natural. Los coleccionistas valoran a Chewie de Hoth por su experiencia mecánica durante el asedio y su lealtad a Han durante la evacuación. Su trabajo constante manteniendo al Halcón operacional mientras está bajo ataque Imperial hace que esta versión sea esencial para recrear escenas de hangar de Base Eco y el escape frenético de Hoth."
  },
  {
    no: 'sw0200',
    name: 'R2-D2 (with Dagobah Swamp)',
    en: "R2-D2 accompanies Luke Skywalker to the swamp planet Dagobah, getting submerged in murky water before Yoda's introduction. This LEGO minifigure features R2-D2 with swamp accessories or special printing showing mud and vegetation from the hostile environment. Released in various sets, Dagobah R2-D2 represents the droid's loyalty through harsh conditions while Luke trains. The figure captures R2's comedic struggles with the swamp creatures and environment. Collectors value Dagobah R2 for completing training camp displays and for representing R2's constant presence throughout Luke's Jedi lessons. His interaction with Yoda and role as Luke's only companion during the intense training period make this version essential for authentic Dagobah scenes from The Empire Strikes Back.",
    de: "R2-D2 begleitet Luke Skywalker zum Sumpfplaneten Dagobah und wird in trübem Wasser untergetaucht, bevor Yoda eingeführt wird. Diese LEGO-Minifigur zeigt R2-D2 mit Sumpf-Zubehör oder spezieller Bedruckung, die Schlamm und Vegetation aus der feindlichen Umgebung zeigt. In verschiedenen Sets veröffentlicht, repräsentiert Dagobah-R2-D2 die Loyalität der Droide durch harte Bedingungen, während Luke trainiert. Die Figur fängt R2s komische Kämpfe mit den Sumpfkreaturen und der Umgebung ein. Sammler schätzen Dagobah-R2 für die Vervollständigung von Trainingslager-Ausstellungen und für die Darstellung von R2s konstanter Präsenz während Lukes Jedi-Lektionen. Seine Interaktion mit Yoda und Rolle als Lukes einziger Begleiter während der intensiven Trainingsperiode machen diese Version unverzichtbar für authentische Dagobah-Szenen aus Das Imperium schlägt zurück.",
    fr: "R2-D2 accompagne Luke Skywalker sur la planète marécageuse Dagobah, se retrouvant submergé dans l'eau trouble avant l'introduction de Yoda. Cette minifigurine LEGO présente R2-D2 avec des accessoires de marécage ou une impression spéciale montrant la boue et la végétation de l'environnement hostile. Sortie dans divers sets, R2-D2 de Dagobah représente la loyauté du droïde à travers des conditions difficiles pendant que Luke s'entraîne. La figurine capture les luttes comiques de R2 avec les créatures et l'environnement du marécage. Les collectionneurs apprécient R2 de Dagobah pour compléter les expositions de camp d'entraînement et pour représenter la présence constante de R2 tout au long des leçons Jedi de Luke. Son interaction avec Yoda et son rôle en tant que seul compagnon de Luke pendant la période d'entraînement intense font de cette version un élément essentiel pour les scènes authentiques de Dagobah de L'Empire contre-attaque.",
    es: "R2-D2 acompaña a Luke Skywalker al planeta pantanoso Dagobah, quedando sumergido en agua turbia antes de la introducción de Yoda. Esta minifigura LEGO presenta a R2-D2 con accesorios de pantano o impresión especial mostrando lodo y vegetación del ambiente hostil. Lanzado en varios sets, R2-D2 de Dagobah representa la lealtad del droide a través de condiciones duras mientras Luke entrena. La figura captura las luchas cómicas de R2 con las criaturas del pantano y el ambiente. Los coleccionistas valoran a R2 de Dagobah por completar exhibiciones de campamento de entrenamiento y por representar la presencia constante de R2 durante las lecciones Jedi de Luke. Su interacción con Yoda y papel como único compañero de Luke durante el período de entrenamiento intenso hacen que esta versión sea esencial para escenas auténticas de Dagobah de El Imperio Contraataca."
  },
  {
    no: 'sw0201',
    name: 'C-3PO (with Ewok Throne)',
    en: "C-3PO is mistaken for a deity by the Ewoks on Endor, receiving worship and a makeshift throne before helping translate for the Rebel alliance with the tribal warriors. This LEGO minifigure captures 3PO during his brief godhood with special Ewok-themed accessories or throne pieces. Released in Endor-themed sets, this version represents one of C-3PO's most important moments being useful beyond translation. The figure shows the protocol droid's unexpected role in securing Ewok military support. Collectors value Ewok Throne C-3PO for the humorous worship scenes and for representing the droid's crucial diplomatic role in the Battle of Endor. His storytelling that convinces the Ewoks to join the Rebellion makes this version essential for authentic Return of the Jedi village displays.",
    de: "C-3PO wird von den Ewoks auf Endor für eine Gottheit gehalten, erhält Anbetung und einen provisorischen Thron, bevor er hilft, für die Rebellenallianz mit den Stammeskämpfern zu übersetzen. Diese LEGO-Minifigur fängt 3PO während seiner kurzen Göttlichkeit mit speziellen Ewok-thematisierten Accessoires oder Thronstücken ein. In Endor-thematisierten Sets veröffentlicht, repräsentiert diese Version einen von C-3POs wichtigsten Momenten, in denen er über die Übersetzung hinaus nützlich ist. Die Figur zeigt die unerwartete Rolle der Protokolldroide bei der Sicherung der militärischen Unterstützung der Ewoks. Sammler schätzen Ewok-Thron-C-3PO für die humorvollen Anbetungsszenen und für die Darstellung der entscheidenden diplomatischen Rolle der Droide in der Schlacht von Endor. Sein Geschichtenerzählen, das die Ewoks überzeugt, sich der Rebellion anzuschließen, macht diese Version unverzichtbar für authentische Die Rückkehr der Jedi-Ritter Dorf-Ausstellungen.",
    fr: "C-3PO est pris pour une divinité par les Ewoks sur Endor, recevant l'adoration et un trône de fortune avant d'aider à traduire pour l'alliance Rebelle avec les guerriers tribaux. Cette minifigurine LEGO capture 3PO pendant sa brève divinité avec des accessoires spéciaux à thème Ewok ou des pièces de trône. Sortie dans des sets à thème Endor, cette version représente l'un des moments les plus importants de C-3PO étant utile au-delà de la traduction. La figurine montre le rôle inattendu du droïde de protocole dans l'obtention du soutien militaire Ewok. Les collectionneurs apprécient C-3PO du Trône Ewok pour les scènes d'adoration humoristiques et pour représenter le rôle diplomatique crucial du droïde dans la Bataille d'Endor. Son récit qui convainc les Ewoks de rejoindre la Rébellion fait de cette version un élément essentiel pour les expositions authentiques de village du Retour du Jedi.",
    es: "C-3PO es confundido con una deidad por los Ewoks en Endor, recibiendo adoración y un trono improvisado antes de ayudar a traducir para la alianza Rebelde con los guerreros tribales. Esta minifigura LEGO captura a 3PO durante su breve divinidad con accesorios especiales temáticos de Ewok o piezas de trono. Lanzada en sets temáticos de Endor, esta versión representa uno de los momentos más importantes de C-3PO siendo útil más allá de la traducción. La figura muestra el papel inesperado del droide de protocolo en asegurar apoyo militar Ewok. Los coleccionistas valoran a C-3PO del Trono Ewok por las escenas de adoración humorísticas y por representar el papel diplomático crucial del droide en la Batalla de Endor. Su narración de historias que convence a los Ewoks de unirse a la Rebelión hace que esta versión sea esencial para exhibiciones auténticas de aldea de El Retorno del Jedi."
  },
  {
    no: 'sw0202',
    name: 'TIE Fighter Pilot',
    en: "TIE Fighter Pilots form the backbone of the Imperial Navy's starfighter corps, flying the Empire's most numerous combat spacecraft throughout the galaxy. This LEGO minifigure features the distinctive all-black flight suit with life support chest box and specialized helmet for TIE cockpit operations. First released in 1999, the TIE Pilot has become one of the most iconic Imperial minifigures. The figure's unique helmet design and uniform markings reflect the standardized training of Imperial naval aviators. Collectors value TIE Pilots for their essential role in space battles across all three Original Trilogy films and for building comprehensive Imperial fighter squadrons. Multiple TIE Pilots are crucial for recreating the overwhelming numerical superiority that characterized Imperial space combat tactics.",
    de: "TIE-Jägerpiloten bilden das Rückgrat des Sternenjägerkorps der imperialen Marine und fliegen das zahlreichste Kampfraumschiff des Imperiums in der gesamten Galaxie. Diese LEGO-Minifigur zeigt den charakteristischen ganz schwarzen Fluganzug mit Lebenserhaltungs-Brustbox und spezialisiertem Helm für TIE-Cockpit-Operationen. Erstmals 1999 veröffentlicht, ist der TIE-Pilot zu einer der ikonischsten imperialen Minifiguren geworden. Das einzigartige Helmdesign und die Uniformmarkierungen der Figur spiegeln die standardisierte Ausbildung imperialer Marine-Flieger wider. Sammler schätzen TIE-Piloten für ihre essentielle Rolle in Weltraumschlachten über alle drei Original-Trilogie-Filme hinweg und für den Aufbau umfassender imperialer Jägerstaffeln. Mehrere TIE-Piloten sind entscheidend für die Nachbildung der überwältigenden zahlenmäßigen Überlegenheit, die imperiale Weltraumkampftaktiken charakterisierte.",
    fr: "Les Pilotes de Chasseur TIE forment l'épine dorsale du corps de chasseurs stellaires de la Marine Impériale, pilotant le vaisseau spatial de combat le plus nombreux de l'Empire à travers la galaxie. Cette minifigurine LEGO présente la combinaison de vol toute noire distinctive avec boîtier de support vital sur la poitrine et casque spécialisé pour les opérations de cockpit TIE. Sortie pour la première fois en 1999, le Pilote TIE est devenu l'une des minifigurines Impériales les plus iconiques. Le design de casque unique et les marquages d'uniforme de la figurine reflètent la formation standardisée des aviateurs navals Impériaux. Les collectionneurs apprécient les Pilotes TIE pour leur rôle essentiel dans les batailles spatiales à travers les trois films de la trilogie originale et pour construire des escadrons de chasseurs Impériaux complets. Plusieurs Pilotes TIE sont cruciaux pour recréer la supériorité numérique écrasante qui caractérisait les tactiques de combat spatial Impérial.",
    es: "Los Pilotos de Caza TIE forman la columna vertebral del cuerpo de cazas estelares de la Armada Imperial, volando la nave espacial de combate más numerosa del Imperio a través de la galaxia. Esta minifigura LEGO presenta el distintivo traje de vuelo completamente negro con caja de soporte vital en el pecho y casco especializado para operaciones de cabina TIE. Lanzada por primera vez en 1999, el Piloto TIE se ha convertido en una de las minifiguras Imperiales más icónicas. El diseño de casco único y las marcas de uniforme de la figura reflejan el entrenamiento estandarizado de los aviadores navales Imperiales. Los coleccionistas valoran a los Pilotos TIE por su papel esencial en batallas espaciales a través de las tres películas de la trilogía original y por construir escuadrones de cazas Imperiales integrales. Múltiples Pilotos TIE son cruciales para recrear la superioridad numérica abrumadora que caracterizaba las tácticas de combate espacial Imperial."
  },
  {
    no: 'sw0203',
    name: 'X-Wing Pilot (Red Squadron)',
    en: "Red Squadron X-Wing Pilots flew in the historic Battle of Yavin, with most sacrificing their lives during the trench run that destroyed the first Death Star. This LEGO minifigure features the iconic orange flight suit with white accents and distinctive pilot helmet worn during A New Hope. First released in 1999, the Red Squadron pilot represents the brave Rebel aviators who gave everything to destroy the Empire's ultimate weapon. The figure's detailed printing shows the squadron markings and life support systems essential for starfighter operations. Collectors value Red Squadron pilots for their heroic sacrifice at Yavin and for building comprehensive Rebel fighter wing displays. Multiple pilots are essential for recreating the full attack squadron that launched from Yavin IV's jungle moon base.",
    de: "Piloten der Roten Staffel flogen in der historischen Schlacht von Yavin, wobei die meisten ihr Leben während des Grabenangriffs opferten, der den ersten Todesstern zerstörte. Diese LEGO-Minifigur zeigt den ikonischen orangen Fluganzug mit weißen Akzenten und charakteristischem Pilotenhelm, der während Eine neue Hoffnung getragen wurde. Erstmals 1999 veröffentlicht, repräsentiert der Pilot der Roten Staffel die mutigen Rebellenflieger, die alles gaben, um die ultimative Waffe des Imperiums zu zerstören. Die detaillierte Bedruckung der Figur zeigt die Staffelmarkierungen und Lebenserhaltungssysteme, die für Sternenjäger-Operationen essentiell sind. Sammler schätzen Piloten der Roten Staffel für ihr heroisches Opfer bei Yavin und für den Aufbau umfassender Rebellenjäger-Flügel-Ausstellungen. Mehrere Piloten sind unverzichtbar für die Nachbildung der vollständigen Angriffsstaffel, die von Yavin IVs Dschungelmond-Basis startete.",
    fr: "Les Pilotes X-Wing de l'Escadron Rouge ont volé dans la Bataille historique de Yavin, la plupart sacrifiant leur vie pendant la course dans la tranchée qui a détruit la première Étoile de la Mort. Cette minifigurine LEGO présente la combinaison de vol orange iconique avec des accents blancs et le casque de pilote distinctif porté pendant Un Nouvel Espoir. Sortie pour la première fois en 1999, le pilote de l'Escadron Rouge représente les aviateurs Rebelles courageux qui ont tout donné pour détruire l'arme ultime de l'Empire. L'impression détaillée de la figurine montre les marquages d'escadron et les systèmes de support vital essentiels pour les opérations de chasseurs stellaires. Les collectionneurs apprécient les pilotes de l'Escadron Rouge pour leur sacrifice héroïque à Yavin et pour construire des expositions complètes d'aile de chasseurs Rebelles. Plusieurs pilotes sont essentiels pour recréer l'escadron d'attaque complet lancé depuis la base de lune de jungle de Yavin IV.",
    es: "Los Pilotos de Ala-X del Escuadrón Rojo volaron en la histórica Batalla de Yavin, con la mayoría sacrificando sus vidas durante la carrera de trinchera que destruyó la primera Estrella de la Muerte. Esta minifigura LEGO presenta el icónico traje de vuelo naranja con acentos blancos y distintivo casco de piloto usado durante Una Nueva Esperanza. Lanzada por primera vez en 1999, el piloto del Escuadrón Rojo representa a los aviadores Rebeldes valientes que dieron todo para destruir el arma definitiva del Imperio. La impresión detallada de la figura muestra las marcas de escuadrón y sistemas de soporte vital esenciales para operaciones de cazas estelares. Los coleccionistas valoran a los pilotos del Escuadrón Rojo por su sacrificio heroico en Yavin y por construir exhibiciones integrales de ala de cazas Rebeldes. Múltiples pilotos son esenciales para recrear el escuadrón de ataque completo que se lanzó desde la base de luna de jungla de Yavin IV."
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 91-95 (sw0199-sw0203)...\n');

  for (const m of batch) {
    await prisma.minifigCatalog.upsert({
      where: { minifigure_no: m.no },
      update: {
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      },
      create: {
        minifigure_no: m.no,
        name: m.name,
        category_id: 1,
        category_name: 'Star Wars',
        search_name: m.name.toLowerCase(),
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`  ✅ ${m.no}: ${m.name}`);
  }

  console.log(`\n✨ Batch 91-95 complete: 5 minifigs (20 descriptions)`);
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
