import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0254',
    name: 'Jango Fett',
    en: 'Jango Fett\'s LEGO minifigure captures the legendary Mandalorian bounty hunter whose genetic template created the entire Grand Army of the Republic, featuring his distinctive blue and silver armor with detailed printing. This minifigure showcases Jango\'s iconic appearance with dual blaster pistols, jet pack accessories, and the characteristic T-visor helmet that defined Mandalorian warrior culture. As the father of Boba Fett and the most dangerous bounty hunter in the galaxy during the prequel era, Jango\'s role in the Clone Wars\' origins made him pivotal to Star Wars history despite his brief screen time. Released in sets from 2002 onwards with various iterations through the years, this minifigure remains highly collectible due to Jango\'s connection to both the clone army and Boba Fett\'s origin story, his impressive combat prowess demonstrated against Obi-Wan Kenobi, and his status as one of the few characters to engage Jedi Masters in direct combat and survive until his final confrontation with Mace Windu.',
    de: 'Die LEGO-Minifigur von Jango Fett fängt den legendären mandalorianischen Kopfgeldjäger ein, dessen genetische Vorlage die gesamte Große Armee der Republik erschuf, mit seiner markanten blauen und silbernen Rüstung mit detaillierter Bedruckung. Diese Minifigur zeigt Jangos ikonisches Aussehen mit doppelten Blasterpistolen, Jetpack-Zubehör und dem charakteristischen T-Visier-Helm, der die mandalorianische Kriegerkultur definierte. Als Vater von Boba Fett und der gefährlichste Kopfgeldjäger in der Galaxie während der Prequel-Ära machte Jangos Rolle in den Ursprüngen der Klonkriege ihn trotz seiner kurzen Bildschirmzeit entscheidend für die Star Wars-Geschichte. In Sets ab 2002 mit verschiedenen Iterationen über die Jahre veröffentlicht, bleibt diese Minifigur hochgradig sammelwürdig aufgrund von Jangos Verbindung sowohl zur Klon-Armee als auch zu Boba Fetts Ursprungsgeschichte, seiner beeindruckenden Kampffähigkeit, die er gegen Obi-Wan Kenobi demonstrierte, und seinem Status als einer der wenigen Charaktere, die Jedi-Meister im direkten Kampf angriffen und bis zu seiner finalen Konfrontation mit Mace Windu überlebten.',
    fr: 'La minifigurine LEGO de Jango Fett capture le légendaire chasseur de primes Mandalorien dont le modèle génétique a créé toute la Grande Armée de la République, avec son armure bleue et argentée distinctive avec impression détaillée. Cette minifigurine présente l\'apparence emblématique de Jango avec des pistolets blaster doubles, des accessoires de jetpack, et le casque à visière en T caractéristique qui définissait la culture guerrière Mandalorienne. En tant que père de Boba Fett et le chasseur de primes le plus dangereux de la galaxie pendant l\'ère préquelle, le rôle de Jango dans les origines des Guerres des Clones l\'a rendu crucial pour l\'histoire de Star Wars malgré son temps d\'écran bref. Sortie dans des sets à partir de 2002 avec diverses itérations au fil des ans, cette minifigurine reste hautement collectionnable en raison de la connexion de Jango à la fois à l\'armée clone et à l\'histoire d\'origine de Boba Fett, sa prouesse de combat impressionnante démontrée contre Obi-Wan Kenobi, et son statut comme l\'un des rares personnages à affronter les Maîtres Jedi en combat direct et survivre jusqu\'à sa confrontation finale avec Mace Windu.',
    es: 'La minifigura LEGO de Jango Fett captura al legendario cazarrecompensas Mandaloriano cuya plantilla genética creó todo el Gran Ejército de la República, presentando su distintiva armadura azul y plateada con impresión detallada. Esta minifigura muestra la apariencia icónica de Jango con pistolas bláster duales, accesorios de jetpack, y el característico casco con visor en T que definió la cultura guerrera Mandaloriana. Como padre de Boba Fett y el cazarrecompensas más peligroso de la galaxia durante la era precuela, el papel de Jango en los orígenes de las Guerras Clon lo hizo fundamental para la historia de Star Wars a pesar de su breve tiempo en pantalla. Lanzada en sets desde 2002 con varias iteraciones a través de los años, esta minifigura permanece altamente coleccionable debido a la conexión de Jango tanto con el ejército clon como con la historia de origen de Boba Fett, su impresionante destreza en combate demostrada contra Obi-Wan Kenobi, y su estatus como uno de los pocos personajes en enfrentar Maestros Jedi en combate directo y sobrevivir hasta su confrontación final con Mace Windu.'
  },
  {
    no: 'sw0255',
    name: 'Zam Wesell',
    en: 'Zam Wesell\'s LEGO minifigure portrays the Clawdite shapeshifter bounty hunter with her distinctive purple and gray outfit, face veil, and the unique alien features that made her one of Attack of the Clones\' most memorable villains. This minifigure features detailed printing showing her armored costume and weapons, representing Jango Fett\'s partner in the attempted assassination of Senator Padmé Amidala that opened the film\'s action sequences. As a rare female bounty hunter and shapeshifter with the ability to assume any humanoid form, Zam\'s brief but impactful appearance introduced audiences to the darker criminal underworld of Coruscant. Released in sets from 2002 onwards, this minifigure appeals to collectors who appreciate rare female villains in Star Wars, with Zam\'s unique design, her partnership with Jango Fett, and her dramatic death scene involving a toxic saberdart making her a distinctive addition to bounty hunter and prequel trilogy collections despite her limited screen time.',
    de: 'Die LEGO-Minifigur von Zam Wesell porträtiert die Clawdite-Gestaltwandler-Kopfgeldjägerin mit ihrem markanten violetten und grauen Outfit, Gesichtsschleier und den einzigartigen außerirdischen Merkmalen, die sie zu einer der unvergesslichsten Schurkinnen von Angriff der Klonkrieger machten. Diese Minifigur verfügt über detaillierte Bedruckung, die ihr gepanzertes Kostüm und ihre Waffen zeigt, die Jango Fetts Partnerin beim versuchten Attentat auf Senatorin Padmé Amidala repräsentiert, das die Action-Sequenzen des Films eröffnete. Als seltene weibliche Kopfgeldjägerin und Gestaltwandlerin mit der Fähigkeit, jede humanoide Form anzunehmen, führte Zams kurzer, aber eindrucksvoller Auftritt das Publikum in die dunklere kriminelle Unterwelt von Coruscant ein. In Sets ab 2002 veröffentlicht, spricht diese Minifigur Sammler an, die seltene weibliche Schurkinnen in Star Wars schätzen, wobei Zams einzigartiges Design, ihre Partnerschaft mit Jango Fett und ihre dramatische Todesszene mit einem giftigen Saberdart sie zu einer markanten Ergänzung zu Kopfgeldjäger- und Prequel-Trilogie-Sammlungen machen trotz ihrer begrenzten Bildschirmzeit.',
    fr: 'La minifigurine LEGO de Zam Wesell dépeint la chasseuse de primes Clawdite métamorphe avec sa tenue violette et grise distinctive, son voile facial, et les traits aliens uniques qui ont fait d\'elle l\'une des méchantes les plus mémorables de L\'Attaque des Clones. Cette minifigurine présente une impression détaillée montrant son costume blindé et ses armes, représentant la partenaire de Jango Fett dans la tentative d\'assassinat de la Sénatrice Padmé Amidala qui a ouvert les séquences d\'action du film. En tant que rare chasseuse de primes féminine et métamorphe avec la capacité d\'assumer toute forme humanoïde, l\'apparition brève mais percutante de Zam a présenté au public le monde souterrain criminel plus sombre de Coruscant. Sortie dans des sets à partir de 2002, cette minifigurine plaît aux collectionneurs qui apprécient les rares méchantes féminines dans Star Wars, le design unique de Zam, son partenariat avec Jango Fett, et sa scène de mort dramatique impliquant une fléchette empoisonnée en faisant un ajout distinctif aux collections de chasseurs de primes et de la trilogie préquelle malgré son temps d\'écran limité.',
    es: 'La minifigura LEGO de Zam Wesell retrata a la cazarrecompensas metamorfa Clawdite con su distintivo atuendo morado y gris, velo facial, y las características alienígenas únicas que la hicieron una de las villanas más memorables de El Ataque de los Clones. Esta minifigura presenta impresión detallada mostrando su traje blindado y armas, representando a la compañera de Jango Fett en el intento de asesinato de la Senadora Padmé Amidala que abrió las secuencias de acción de la película. Como una rara cazarrecompensas femenina y metamorfa con la habilidad de asumir cualquier forma humanoide, la breve pero impactante aparición de Zam presentó a las audiencias al más oscuro submundo criminal de Coruscant. Lanzada en sets desde 2002, esta minifigura atrae a coleccionistas que aprecian las raras villanas femeninas en Star Wars, con el diseño único de Zam, su asociación con Jango Fett, y su dramática escena de muerte involucrando un dardo sable tóxico haciéndola una adición distintiva a colecciones de cazarrecompensas y trilogía precuela a pesar de su limitado tiempo en pantalla.'
  },
  {
    no: 'sw0256',
    name: 'Geonosian Warrior',
    en: 'The Geonosian Warrior LEGO minifigure captures the insectoid species that served as the Separatist Alliance\'s droid manufacturers and arena combatants, featuring distinctive brown coloring, translucent wings, and the elongated head design. This minifigure showcases the Geonosian\'s unique physiology with detailed printing showing their exoskeleton armor and tribal markings, representing the workers and soldiers of the hive-based society that constructed the first Death Star plans. Armed with sonic blasters and known for their aggressive flying tactics during the Battle of Geonosis, these warriors formed a crucial part of the Separatist forces during the Clone Wars\' opening battles. Released in sets from 2003 onwards with various iterations, this minifigure appeals to collectors building Clone Wars battle scenes, with the Geonosians\' unique alien design, their role in initiating the galactic conflict, and their connection to both the droid army and Death Star creation making them essential for comprehensive prequel era collections and arena battle displays.',
    de: 'Die LEGO-Minifigur des geonosianischen Kriegers fängt die insektoide Spezies ein, die als Droiden-Hersteller und Arena-Kämpfer der Separatisten-Allianz diente, mit markanter brauner Färbung, durchscheinenden Flügeln und dem länglichen Kopfdesign. Diese Minifigur zeigt die einzigartige Physiologie der Geonosianer mit detaillierter Bedruckung, die ihre Exoskelett-Rüstung und Stammesmarkierungen zeigt, die die Arbeiter und Soldaten der bienenstockbasierten Gesellschaft repräsentiert, die die ersten Todesstern-Pläne konstruierte. Bewaffnet mit Schallblastern und bekannt für ihre aggressiven Flugtaktiken während der Schlacht von Geonosis, bildeten diese Krieger einen entscheidenden Teil der Separatisten-Streitkräfte während der Eröffnungsschlachten der Klonkriege. In Sets ab 2003 mit verschiedenen Iterationen veröffentlicht, spricht diese Minifigur Sammler an, die Clone Wars-Kampfszenen aufbauen, wobei das einzigartige außerirdische Design der Geonosianer, ihre Rolle beim Einleiten des galaktischen Konflikts und ihre Verbindung sowohl zur Droiden-Armee als auch zur Todesstern-Erschaffung sie für umfassende Prequel-Ära-Sammlungen und Arena-Kampf-Displays unverzichtbar machen.',
    fr: 'La minifigurine LEGO du Guerrier Géonosien capture l\'espèce insectoïde qui servait de fabricants de droïdes et de combattants d\'arène de l\'Alliance Séparatiste, avec une coloration brune distinctive, des ailes translucides, et le design de tête allongée. Cette minifigurine présente la physiologie unique des Géonosiens avec une impression détaillée montrant leur armure d\'exosquelette et leurs marques tribales, représentant les travailleurs et soldats de la société basée sur la ruche qui a construit les premiers plans de l\'Étoile de la Mort. Armés de blasters soniques et connus pour leurs tactiques de vol agressives pendant la Bataille de Geonosis, ces guerriers formaient une partie cruciale des forces Séparatistes pendant les batailles d\'ouverture des Guerres des Clones. Sortie dans des sets à partir de 2003 avec diverses itérations, cette minifigurine plaît aux collectionneurs construisant des scènes de bataille Clone Wars, le design alien unique des Géonosiens, leur rôle dans l\'initiation du conflit galactique, et leur connexion à la fois à l\'armée droïde et à la création de l\'Étoile de la Mort les rendant essentiels pour les collections complètes de l\'ère préquelle et les présentations de batailles d\'arène.',
    es: 'La minifigura LEGO del Guerrero Geonosiano captura a la especie insectoide que sirvió como fabricantes de droides y combatientes de arena de la Alianza Separatista, presentando coloración marrón distintiva, alas translúcidas, y el diseño de cabeza alargada. Esta minifigura muestra la fisiología única de los Geonosianos con impresión detallada mostrando su armadura de exoesqueleto y marcas tribales, representando a los trabajadores y soldados de la sociedad basada en colmena que construyó los primeros planos de la Estrella de la Muerte. Armados con blásters sónicos y conocidos por sus tácticas de vuelo agresivas durante la Batalla de Geonosis, estos guerreros formaron una parte crucial de las fuerzas Separatistas durante las batallas de apertura de las Guerras Clon. Lanzada en sets desde 2003 con varias iteraciones, esta minifigura atrae a coleccionistas construyendo escenas de batalla de Clone Wars, con el diseño alienígena único de los Geonosianos, su papel en iniciar el conflicto galáctico, y su conexión tanto con el ejército droide como con la creación de la Estrella de la Muerte haciéndolos esenciales para colecciones completas de la era precuela y exhibiciones de batallas de arena.'
  },
  {
    no: 'sw0257',
    name: 'Super Battle Droid',
    en: 'The Super Battle Droid LEGO minifigure represents the Trade Federation\'s upgraded combat droid with its bulkier blue-gray armor, built-in wrist blasters, and more menacing silhouette compared to standard battle droids. This minifigure features specialized construction with detailed printing showing the droid\'s reinforced chassis and integrated weapons systems, embodying the Separatist military\'s response to battle droid vulnerabilities exposed during the Battle of Naboo. Lacking the standard droid\'s dependency on a central control ship and equipped with heavier armor and firepower, Super Battle Droids became frontline shock troops throughout the Clone Wars, presenting genuine threats to clone troopers in sustained firefights. Released in sets from 2002 onwards appearing in countless Clone Wars battle scenarios, this minifigure remains essential for army builders creating Separatist forces, with its distinctive blue coloring, imposing design, and frequent appearance across prequel trilogy battles making it one of the most produced and collected droid variants in LEGO Star Wars history.',
    de: 'Die LEGO-Minifigur des Super-Kampfdroiden repräsentiert den verbesserten Kampfdroiden der Handelsföderation mit seiner sperrigeren blaugrauen Rüstung, eingebauten Handgelenk-Blastern und bedrohlicherer Silhouette im Vergleich zu Standard-Kampfdroiden. Diese Minifigur verfügt über spezialisierte Konstruktion mit detaillierter Bedruckung, die das verstärkte Chassis und integrierte Waffensysteme des Droiden zeigt, die die Antwort des separatistischen Militärs auf die während der Schlacht von Naboo aufgedeckten Schwachstellen der Kampfdroiden verkörpert. Ohne die Abhängigkeit des Standard-Droiden von einem zentralen Kontrollschiff und ausgestattet mit schwererer Rüstung und Feuerkraft wurden Super-Kampfdroiden zu Frontlinien-Stoßtruppen während der gesamten Klonkriege und stellten echte Bedrohungen für Klontruppen in anhaltenden Feuergefechten dar. In Sets ab 2002 veröffentlicht und in unzähligen Clone Wars-Kampfszenarien erscheinend, bleibt diese Minifigur für Armee-Bauer, die Separatisten-Streitkräfte erstellen, unverzichtbar, wobei ihre markante blaue Färbung, imposante Gestaltung und häufiges Auftreten in Prequel-Trilogie-Schlachten sie zu einer der meistproduzierten und gesammelten Droiden-Varianten in der LEGO Star Wars-Geschichte machen.',
    fr: 'La minifigurine LEGO du Super Droïde de Combat représente le droïde de combat amélioré de la Fédération du Commerce avec son armure gris-bleu plus volumineuse, ses blasters de poignet intégrés, et sa silhouette plus menaçante par rapport aux droïdes de combat standards. Cette minifigurine présente une construction spécialisée avec une impression détaillée montrant le châssis renforcé du droïde et les systèmes d\'armes intégrés, incarnant la réponse militaire Séparatiste aux vulnérabilités des droïdes de combat exposées pendant la Bataille de Naboo. N\'ayant pas la dépendance du droïde standard à un vaisseau de contrôle central et équipés d\'une armure et d\'une puissance de feu plus lourdes, les Super Droïdes de Combat sont devenus des troupes de choc de première ligne tout au long des Guerres des Clones, présentant de véritables menaces aux soldats clones dans des échanges de tirs soutenus. Sortie dans des sets à partir de 2002 apparaissant dans d\'innombrables scénarios de bataille Clone Wars, cette minifigurine reste essentielle pour les constructeurs d\'armées créant des forces Séparatistes, sa coloration bleue distinctive, son design imposant, et son apparition fréquente à travers les batailles de la trilogie préquelle en faisant l\'une des variantes de droïdes les plus produites et collectionnées dans l\'histoire LEGO Star Wars.',
    es: 'La minifigura LEGO del Super Droide de Batalla representa al droide de combate mejorado de la Federación de Comercio con su armadura gris-azul más voluminosa, blásters de muñeca incorporados, y silueta más amenazante comparada con los droides de batalla estándar. Esta minifigura presenta construcción especializada con impresión detallada mostrando el chasis reforzado del droide y sistemas de armas integrados, encarnando la respuesta militar Separatista a las vulnerabilidades de los droides de batalla expuestas durante la Batalla de Naboo. Careciendo de la dependencia del droide estándar en una nave de control central y equipados con armadura y potencia de fuego más pesadas, los Super Droides de Batalla se convirtieron en tropas de choque de primera línea durante todas las Guerras Clon, presentando amenazas genuinas a los soldados clon en tiroteos sostenidos. Lanzada en sets desde 2002 apareciendo en innumerables escenarios de batalla de Clone Wars, esta minifigura permanece esencial para constructores de ejércitos creando fuerzas Separatistas, con su distintiva coloración azul, diseño imponente, y frecuente aparición a través de batallas de la trilogía precuela haciéndola una de las variantes de droide más producidas y coleccionadas en la historia LEGO Star Wars.'
  },
  {
    no: 'sw0258',
    name: 'Droideka (Destroyer Droid)',
    en: 'The Droideka LEGO minifigure captures the Trade Federation\'s most feared combat unit with its distinctive rolling wheel form, twin blaster cannons, and personal deflector shield technology that made it nearly invincible in combat. This specialized minifigure features unique construction allowing transformation between rolled ball mode and deployed battle stance, representing the technological superiority that made these destroyer droids devastating against both Jedi and clone forces. Capable of withstanding lightsaber strikes and sustained blaster fire through their shield generators, Droidekas forced enemies to employ creative tactics or overwhelming firepower to overcome their defenses. Released in various forms from 1999 onwards with increasingly sophisticated designs, this minifigure has become one of the most technically impressive LEGO Star Wars creations, highly collectible due to its transforming mechanism, its memorable introduction during the Battle of Naboo when even Qui-Gon and Obi-Wan retreated, and its continued threat throughout the Clone Wars making it essential for both Separatist army builders and collectors appreciating LEGO\'s engineering in minifigure form.',
    de: 'Die LEGO-Minifigur des Droidekas fängt die gefürchtetste Kampfeinheit der Handelsföderation mit ihrer markanten rollenden Radform, doppelten Blasterkanonen und persönlicher Deflektorschild-Technologie ein, die sie im Kampf nahezu unbesiegbar machte. Diese spezialisierte Minifigur verfügt über einzigartige Konstruktion, die Transformation zwischen gerolltem Kugelform und entfalteter Kampfhaltung ermöglicht, die die technologische Überlegenheit repräsentiert, die diese Zerstörerdroiden verheerend gegen sowohl Jedi als auch Klonstreitkräfte machte. Fähig, Lichtschwertschlägen und anhaltendem Blasterfeuer durch ihre Schildgeneratoren standzuhalten, zwangen Droidekas Feinde, kreative Taktiken oder überwältigende Feuerkraft einzusetzen, um ihre Verteidigung zu überwinden. In verschiedenen Formen ab 1999 mit zunehmend ausgefeilten Designs veröffentlicht, ist diese Minifigur zu einer der technisch beeindruckendsten LEGO Star Wars-Kreationen geworden, hochgradig sammelwürdig aufgrund ihres Transformationsmechanismus, ihrer unvergesslichen Einführung während der Schlacht von Naboo, als selbst Qui-Gon und Obi-Wan zurückwichen, und ihrer anhaltenden Bedrohung während der gesamten Klonkriege, was sie sowohl für Separatisten-Armee-Bauer als auch für Sammler, die LEGOs Engineering in Minifigur-Form schätzen, unverzichtbar macht.',
    fr: 'La minifigurine LEGO du Droideka capture l\'unité de combat la plus redoutée de la Fédération du Commerce avec sa forme de roue roulante distinctive, ses canons blaster jumeaux, et sa technologie de bouclier déflecteur personnel qui la rendait presque invincible au combat. Cette minifigurine spécialisée présente une construction unique permettant la transformation entre le mode boule roulée et la position de bataille déployée, représentant la supériorité technologique qui rendait ces droïdes destructeurs dévastateurs contre les forces Jedi et clones. Capables de résister aux coups de sabre laser et aux tirs de blaster soutenus grâce à leurs générateurs de bouclier, les Droidekas forçaient les ennemis à employer des tactiques créatives ou une puissance de feu écrasante pour surmonter leurs défenses. Sortie sous diverses formes à partir de 1999 avec des designs de plus en plus sophistiqués, cette minifigurine est devenue l\'une des créations LEGO Star Wars les plus techniquement impressionnantes, hautement collectionnable en raison de son mécanisme de transformation, son introduction mémorable pendant la Bataille de Naboo quand même Qui-Gon et Obi-Wan ont battu en retraite, et sa menace continue tout au long des Guerres des Clones la rendant essentielle pour les constructeurs d\'armées Séparatistes et les collectionneurs appréciant l\'ingénierie LEGO sous forme de minifigurine.',
    es: 'La minifigura LEGO del Droideka captura a la unidad de combate más temida de la Federación de Comercio con su distintiva forma de rueda rodante, cañones bláster gemelos, y tecnología de escudo deflector personal que la hizo casi invencible en combate. Esta minifigura especializada presenta construcción única permitiendo transformación entre modo de bola rodada y postura de batalla desplegada, representando la superioridad tecnológica que hizo a estos droides destructores devastadores contra fuerzas tanto Jedi como clon. Capaces de resistir golpes de sable de luz y fuego de bláster sostenido a través de sus generadores de escudo, los Droidekas forzaron a enemigos a emplear tácticas creativas o potencia de fuego abrumadora para superar sus defensas. Lanzada en varias formas desde 1999 con diseños cada vez más sofisticados, esta minifigura se ha convertido en una de las creaciones LEGO Star Wars técnicamente más impresionantes, altamente coleccionable debido a su mecanismo de transformación, su memorable introducción durante la Batalla de Naboo cuando incluso Qui-Gon y Obi-Wan se retiraron, y su amenaza continua durante todas las Guerras Clon haciéndola esencial tanto para constructores de ejércitos Separatistas como para coleccionistas apreciando la ingeniería de LEGO en forma de minifigura.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 146-150 (sw0254-sw0258)...\n');

  for (const m of batch) {
    await prisma.minifigCatalog.upsert({
      where: { minifigure_no: m.no },
      update: {
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      },
      create: {
        minifigure_no: m.no,
        name: m.name,
        category_id: 1,
        category_name: 'Star Wars',
        search_name: m.name.toLowerCase(),
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`  ✅ ${m.no}: ${m.name}`);
  }

  console.log('\n✨ Batch 146-150 complete: 5 minifigs (20 descriptions)');
  await prisma.$disconnect();
}

saveBatch().catch(console.error);