import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasources: {
    db: {
      url: process.env.DATABASE_URL,
    },
  },
});

interface MinifigDescription {
  minifigure_no: string;
  description_en: string;
  description_de: string;
  description_fr: string;
  description_es: string;
}

const descriptions: MinifigDescription[] = [
  {
    minifigure_no: 'sw1111',
    description_en: 'The Gonk Droid in sand green represents another color variant of the ubiquitous GNK power droids that provided portable power throughout the galaxy. This distinctive coloring may indicate different power specifications or service locations. These humble droids remain beloved background characters. A charming variant for collectors building diverse droid populations and adding authentic details to Star Wars environments.',
    description_de: 'Die Gonk-Droide in Sandgrün repräsentiert eine weitere Farbvariante der allgegenwärtigen GNK-Energiedroiden, die in der gesamten Galaxis tragbare Energie bereitstellten. Diese markante Färbung kann verschiedene Energiespezifikationen oder Dienstorte anzeigen. Diese bescheidenen Droiden bleiben beliebte Hintergrundcharaktere. Eine charmante Variante für Sammler, die vielfältige Droidenpopulationen aufbauen und authentische Details zu Star Wars-Umgebungen hinzufügen.',
    description_fr: 'Le droïde Gonk en vert sable représente une autre variante de couleur des droïdes d\'énergie GNK omniprésents qui fournissaient de l\'énergie portable dans toute la galaxie. Cette coloration distinctive peut indiquer différentes spécifications d\'énergie ou emplacements de service. Ces droïdes humbles restent des personnages de fond bien-aimés. Une variante charmante pour les collectionneurs construisant des populations de droïdes diversifiées et ajoutant des détails authentiques aux environnements Star Wars.',
    description_es: 'El Droide Gonk en verde arena representa otra variante de color de los ubicuos droides de energía GNK que proporcionaron energía portátil en toda la galaxia. Esta coloración distintiva puede indicar diferentes especificaciones de energía o ubicaciones de servicio. Estos humildes droides siguen siendo personajes de fondo queridos. Una variante encantadora para coleccionistas que construyen poblaciones de droides diversas y añaden detalles auténticos a entornos de Star Wars.'
  },
  {
    minifigure_no: 'sw1112',
    description_en: 'This premium Darth Vader variant with printed arms and traditional starched fabric cape represents the highest quality version of the iconic villain. The authentic fabric cape and detailed arm printing provide superior screen accuracy. This deluxe variant showcases LEGO\'s commitment to capturing Vader\'s menacing presence. An essential piece for collectors seeking the most authentic and premium Darth Vader minifigure.',
    description_de: 'Diese Premium-Darth Vader-Variante mit bedruckten Armen und traditionellem gestärktem Stoffumhang repräsentiert die hochwertigste Version des ikonischen Schurken. Der authentische Stoffumhang und detaillierte Armdruck bieten überlegene Bildschirmgenauigkeit. Diese Deluxe-Variante zeigt LEGOs Engagement, Vaders bedrohliche Präsenz einzufangen. Ein unverzichtbares Stück für Sammler, die die authentischste und Premium-Darth Vader-Minifigur suchen.',
    description_fr: 'Cette variante premium de Dark Vador avec bras imprimés et cape en tissu amidonné traditionnelle représente la version de la plus haute qualité du méchant iconique. La cape en tissu authentique et l\'impression détaillée des bras offrent une précision d\'écran supérieure. Cette variante de luxe met en valeur l\'engagement de LEGO à capturer la présence menaçante de Vador. Une pièce essentielle pour les collectionneurs recherchant la figurine Dark Vador la plus authentique et premium.',
    description_es: 'Esta variante premium de Darth Vader con brazos impresos y capa de tela almidonada tradicional representa la versión de más alta calidad del icónico villano. La auténtica capa de tela e impresión detallada de brazos proporcionan precisión de pantalla superior. Esta variante de lujo muestra el compromiso de LEGO de capturar la presencia amenazante de Vader. Una pieza esencial para coleccionistas que buscan la minifigura de Darth Vader más auténtica y premium.'
  },
  {
    minifigure_no: 'sw1113',
    description_en: 'Din Grogu, affectionately known as The Child or Baby Yoda, is the mysterious Force-sensitive infant who became the Mandalorian\'s foundling. This adorable character captured hearts worldwide and became a cultural phenomenon. Grogu\'s journey from asset to adopted son defines the emotional core of The Mandalorian series. An essential character for collectors of the Mandalorian series and one of Star Wars\' most beloved new characters.',
    description_de: 'Din Grogu, liebevoll als Das Kind oder Baby Yoda bekannt, ist das mysteriöse machtsensitive Kleinkind, das zum Findelkind des Mandalorianers wurde. Dieser bezaubernde Charakter eroberte weltweit Herzen und wurde zu einem kulturellen Phänomen. Grogus Reise vom Vermögenswert zum adoptierten Sohn definiert den emotionalen Kern der Mandalorianer-Serie. Ein unverzichtbarer Charakter für Sammler der Mandalorianer-Serie und einer der beliebtesten neuen Charaktere von Star Wars.',
    description_fr: 'Din Grogu, affectueusement connu comme L\'Enfant ou Bébé Yoda, est le mystérieux nourrisson sensible à la Force qui est devenu l\'enfant trouvé du Mandalorien. Ce personnage adorable a conquis les cœurs du monde entier et est devenu un phénomène culturel. Le voyage de Grogu d\'atout à fils adoptif définit le cœur émotionnel de la série Le Mandalorien. Un personnage essentiel pour les collectionneurs de la série Le Mandalorien et l\'un des nouveaux personnages les plus aimés de Star Wars.',
    description_es: 'Din Grogu, cariñosamente conocido como El Niño o Bebé Yoda, es el misterioso infante sensible a la Fuerza que se convirtió en el pupilo del Mandaloriano. Este adorable personaje capturó corazones en todo el mundo y se convirtió en un fenómeno cultural. El viaje de Grogu de activo a hijo adoptado define el núcleo emocional de la serie El Mandaloriano. Un personaje esencial para coleccionistas de la serie del Mandaloriano y uno de los nuevos personajes más queridos de Star Wars.'
  },
  {
    minifigure_no: 'sw1114',
    description_en: 'Greef Karga is the charismatic leader of the Bounty Hunters\' Guild on Nevarro who became the Mandalorian\'s ally. This shrewd magistrate evolved from opportunistic guild agent to trusted friend. His distinctive appearance and personality made him a fan favorite supporting character. An important minifigure for collectors of The Mandalorian series and the colorful characters of the Outer Rim.',
    description_de: 'Greef Karga ist der charismatische Anführer der Kopfgeldjägergilde auf Nevarro, der zum Verbündeten des Mandalorianers wurde. Dieser schlaue Magistrat entwickelte sich vom opportunistischen Gildenagenten zum vertrauenswürdigen Freund. Sein markantes Erscheinungsbild und seine Persönlichkeit machten ihn zu einem Fan-Lieblings-Nebendarsteller. Eine wichtige Minifigur für Sammler der Mandalorianer-Serie und der farbenfrohen Charaktere des Äußeren Rands.',
    description_fr: 'Greef Karga est le leader charismatique de la Guilde des Chasseurs de Primes sur Nevarro qui est devenu l\'allié du Mandalorien. Ce magistrat rusé a évolué d\'agent de guilde opportuniste à ami de confiance. Son apparence distinctive et sa personnalité en ont fait un personnage de soutien favori des fans. Une figurine importante pour les collectionneurs de la série Le Mandalorien et des personnages colorés de la Bordure Extérieure.',
    description_es: 'Greef Karga es el carismático líder del Gremio de Cazarrecompensas en Nevarro que se convirtió en aliado del Mandaloriano. Este astuto magistrado evolucionó de agente oportunista del gremio a amigo confiable. Su distintiva apariencia y personalidad lo convirtieron en un personaje secundario favorito de los fanáticos. Una minifigura importante para coleccionistas de la serie El Mandaloriano y los coloridos personajes del Borde Exterior.'
  },
  {
    minifigure_no: 'sw1115',
    description_en: 'IG-11 is the assassin droid reprogrammed as a nurse droid who sacrificed himself to save Grogu and the Mandalorian. This character\'s transformation from killer to protector provided emotional depth to The Mandalorian\'s first season. The distinctive droid design and heroic sacrifice made IG-11 memorable. A significant character for collectors honoring the heroes of The Mandalorian series and redemption stories.',
    description_de: 'IG-11 ist die Attentäter-Droide, die als Krankenschwester-Droide umprogrammiert wurde und sich opferte, um Grogu und den Mandalorianer zu retten. Die Transformation dieses Charakters vom Killer zum Beschützer bot emotionale Tiefe für die erste Staffel von Der Mandalorianer. Das markante Droidendesign und heldenhafte Opfer machten IG-11 unvergesslich. Ein bedeutender Charakter für Sammler, die die Helden der Mandalorianer-Serie und Erlösungsgeschichten ehren.',
    description_fr: 'IG-11 est le droïde assassin reprogrammé en droïde infirmier qui s\'est sacrifié pour sauver Grogu et le Mandalorien. La transformation de ce personnage de tueur à protecteur a fourni une profondeur émotionnelle à la première saison du Mandalorien. Le design de droïde distinctif et le sacrifice héroïque ont rendu IG-11 mémorable. Un personnage important pour les collectionneurs honorant les héros de la série Le Mandalorien et les histoires de rédemption.',
    description_es: 'IG-11 es el droide asesino reprogramado como droide enfermero que se sacrificó para salvar a Grogu y al Mandaloriano. La transformación de este personaje de asesino a protector proporcionó profundidad emocional a la primera temporada de El Mandaloriano. El distintivo diseño de droide y sacrificio heroico hicieron a IG-11 memorable. Un personaje significativo para coleccionistas que honran a los héroes de la serie El Mandaloriano e historias de redención.'
  },
  {
    minifigure_no: 'sw1116',
    description_en: 'This Imperial Scout Trooper variant with dual molded helmet and cheek lines adds facial diversity to the elite reconnaissance specialists. The advanced helmet molding provides superior detail for these speeder bike operators. These agile troopers specialized in rapid reconnaissance on forest worlds like Endor. A premium variant for collectors building scout trooper displays with enhanced detail and realism.',
    description_de: 'Diese imperiale Späher-Trooper-Variante mit zweifarbig geformtem Helm und Wangenlinien fügt den Elite-Aufklärungsspezialisten Gesichtsvielfalt hinzu. Die fortschrittliche Helmformung bietet überlegenes Detail für diese Speederbike-Bediener. Diese agilen Truppen spezialisierten sich auf schnelle Aufklärung auf Waldwelten wie Endor. Eine Premium-Variante für Sammler, die Späher-Trooper-Displays mit verbessertem Detail und Realismus aufbauen.',
    description_fr: 'Cette variante de Scout Trooper impérial avec casque moulé en double et lignes de joue ajoute de la diversité faciale aux spécialistes de reconnaissance d\'élite. Le moulage de casque avancé offre des détails supérieurs pour ces opérateurs de speeder bike. Ces soldats agiles se spécialisaient dans la reconnaissance rapide sur les mondes forestiers comme Endor. Une variante premium pour les collectionneurs construisant des présentations de scout troopers avec des détails et un réalisme améliorés.',
    description_es: 'Esta variante de Soldado Explorador Imperial con casco moldeado dual y líneas de mejilla añade diversidad facial a los especialistas de reconocimiento de élite. El moldeado avanzado de casco proporciona detalle superior para estos operadores de moto deslizadora. Estos soldados ágiles se especializaron en reconocimiento rápido en mundos forestales como Endor. Una variante premium para coleccionistas que construyen exhibiciones de soldados exploradores con detalle y realismo mejorados.'
  },
  {
    minifigure_no: 'sw1117',
    description_en: 'Poe Dameron in holiday sweater represents a festive seasonal variant of the Resistance\'s ace pilot. This cheerful design brings Star Wars holiday spirit to collections. The whimsical sweater combines Poe\'s heroic character with holiday celebration traditions. A fun and limited collectible for fans who appreciate holiday-themed Star Wars variants and seasonal releases.',
    description_de: 'Poe Dameron im Feiertagspullover repräsentiert eine festliche saisonale Variante des Ass-Piloten des Widerstands. Dieses fröhliche Design bringt Star Wars-Feiertagsgeist in Sammlungen. Der verspielte Pullover kombiniert Poes heroischen Charakter mit Feiertagsfeiertraditionen. Ein unterhaltsames und limitiertes Sammlerstück für Fans, die feiertagsthematische Star Wars-Varianten und saisonale Veröffentlichungen schätzen.',
    description_fr: 'Poe Dameron en pull de fête représente une variante saisonnière festive du pilote as de la Résistance. Ce design joyeux apporte l\'esprit des fêtes de Star Wars aux collections. Le pull fantaisiste combine le personnage héroïque de Poe avec les traditions de célébration des fêtes. Un objet de collection amusant et limité pour les fans qui apprécient les variantes Star Wars sur le thème des fêtes et les sorties saisonnières.',
    description_es: 'Poe Dameron en suéter navideño representa una variante festiva de temporada del piloto as de la Resistencia. Este diseño alegre trae espíritu navideño de Star Wars a las colecciones. El caprichoso suéter combina el personaje heroico de Poe con tradiciones de celebración navideña. Un coleccionable divertido y limitado para fanáticos que aprecian variantes de Star Wars temáticas navideñas y lanzamientos de temporada.'
  },
  {
    minifigure_no: 'sw1118',
    description_en: 'D-O with Santa hat represents a holiday-themed variant of the anxious cone-shaped droid from The Rise of Skywalker. This festive version brings seasonal cheer to the lovable droid. The combination of D-O\'s endearing personality with holiday spirit creates a charming collectible. A fun seasonal piece for fans of sequel trilogy droids and holiday Star Wars variants.',
    description_de: 'D-O mit Weihnachtsmannmütze repräsentiert eine feiertagsthematische Variante der ängstlichen kegelförmigen Droide aus Der Aufstieg Skywalkers. Diese festliche Version bringt saisonale Freude zur liebenswerten Droide. Die Kombination von D-Os liebenswerter Persönlichkeit mit Feiertagsgeist schafft ein charmantes Sammlerstück. Ein unterhaltsames saisonales Stück für Fans von Sequel-Trilogie-Droiden und Feiertags-Star Wars-Varianten.',
    description_fr: 'D-O avec bonnet de Père Noël représente une variante sur le thème des fêtes du droïde anxieux en forme de cône de L\'Ascension de Skywalker. Cette version festive apporte la joie saisonnière au droïde adorable. La combinaison de la personnalité attachante de D-O avec l\'esprit de fête crée un objet de collection charmant. Une pièce saisonnière amusante pour les fans de droïdes de la trilogie suite et de variantes Star Wars de fêtes.',
    description_es: 'D-O con gorro de Santa representa una variante temática navideña del ansioso droide en forma de cono de El Ascenso de Skywalker. Esta versión festiva trae alegría de temporada al adorable droide. La combinación de la entrañable personalidad de D-O con espíritu navideño crea un encantador coleccionable. Una pieza de temporada divertida para fanáticos de droides de la trilogía secuela y variantes navideñas de Star Wars.'
  },
  {
    minifigure_no: 'sw1119',
    description_en: 'The Pit Droid with dark bluish gray skeleton arms represents the maintenance droids used during podracing events on Tatooine. These skittish droids performed rapid repairs and maintenance on racing pods between heats. Their distinctive collapsible design and nervous behavior made them comedic characters. A fun droid for collectors building podrace scenes and the colorful world of Tatooine racing.',
    description_de: 'Die Pit-Droide mit dunkel-bläulich-grauen Skelettarmen repräsentiert die Wartungsdroiden, die während Podrace-Veranstaltungen auf Tatooine verwendet wurden. Diese schreckhaften Droiden führten schnelle Reparaturen und Wartungen an Rennpods zwischen den Läufen durch. Ihr markantes zusammenklappbares Design und nervöses Verhalten machten sie zu komischen Charakteren. Eine unterhaltsame Droide für Sammler, die Podrace-Szenen und die farbenfrohe Welt des Tatooine-Rennens aufbauen.',
    description_fr: 'Le Pit Droid avec bras squelette gris bleu foncé représente les droïdes de maintenance utilisés lors d\'événements de course de pods sur Tatooine. Ces droïdes nerveux effectuaient des réparations et des entretiens rapides sur les pods de course entre les manches. Leur design pliable distinctif et leur comportement nerveux en ont fait des personnages comiques. Un droïde amusant pour les collectionneurs construisant des scènes de course de pods et le monde coloré de la course sur Tatooine.',
    description_es: 'El Droide de Foso con brazos de esqueleto gris azulado oscuro representa los droides de mantenimiento usados durante eventos de carreras de vainas en Tatooine. Estos droides asustadizos realizaban reparaciones rápidas y mantenimiento en vainas de carreras entre carreras. Su distintivo diseño plegable y comportamiento nervioso los convirtieron en personajes cómicos. Un droide divertido para coleccionistas que construyen escenas de carreras de vainas y el colorido mundo de las carreras de Tatooine.'
  },
  {
    minifigure_no: 'sw1120',
    description_en: 'The Snowman Gonk Droid represents a festive holiday transformation of the humble power droid into a cheerful snowman. This whimsical design combines the iconic Gonk shape with winter holiday theming. The playful variant celebrates the intersection of Star Wars and seasonal traditions. A charming holiday collectible for fans who enjoy festive Star Wars variants and quirky seasonal releases.',
    description_de: 'Die Schneemann-Gonk-Droide repräsentiert eine festliche Feiertagstransformation der bescheidenen Energiedroide in einen fröhlichen Schneemann. Dieses verspielte Design kombiniert die ikonische Gonk-Form mit Winter-Feiertagsthematik. Die spielerische Variante feiert die Schnittstelle von Star Wars und saisonalen Traditionen. Ein charmantes Feiertagssammlerstück für Fans, die festliche Star Wars-Varianten und skurrile saisonale Veröffentlichungen genießen.',
    description_fr: 'Le droïde Gonk bonhomme de neige représente une transformation festive de fêtes de l\'humble droïde d\'énergie en bonhomme de neige joyeux. Ce design fantaisiste combine la forme iconique Gonk avec un thème de fêtes d\'hiver. La variante ludique célèbre l\'intersection de Star Wars et des traditions saisonnières. Un objet de collection de fêtes charmant pour les fans qui apprécient les variantes Star Wars festives et les sorties saisonnières excentriques.',
    description_es: 'El Droide Gonk Muñeco de Nieve representa una transformación festiva navideña del humilde droide de energía en un alegre muñeco de nieve. Este diseño caprichoso combina la icónica forma Gonk con tematización de vacaciones de invierno. La variante juguetona celebra la intersección de Star Wars y tradiciones de temporada. Un encantador coleccionable navideño para fanáticos que disfrutan variantes festivas de Star Wars y lanzamientos de temporada peculiares.'
  },
  {
    minifigure_no: 'sw1121',
    description_en: 'Darth Vader in holiday sweater represents a humorous festive variant of the galaxy\'s most feared villain. This whimsical design juxtaposes Vader\'s menacing presence with cozy holiday cheer. The playful sweater brings unexpected warmth to the Dark Lord. A fun and ironic collectible for fans who appreciate holiday-themed Star Wars variants and lighthearted takes on iconic characters.',
    description_de: 'Darth Vader im Feiertagspullover repräsentiert eine humorvolle festliche Variante des gefürchtetsten Schurken der Galaxis. Dieses verspielte Design stellt Vaders bedrohliche Präsenz mit gemütlicher Feiertagsfreude gegenüber. Der spielerische Pullover bringt unerwartete Wärme zum Dunklen Lord. Ein unterhaltsames und ironisches Sammlerstück für Fans, die feiertagsthematische Star Wars-Varianten und unbeschwerte Interpretationen ikonischer Charaktere schätzen.',
    description_fr: 'Dark Vador en pull de fête représente une variante festive humoristique du méchant le plus redouté de la galaxie. Ce design fantaisiste juxtapose la présence menaçante de Vador avec la joie festive douillette. Le pull ludique apporte une chaleur inattendue au Seigneur Noir. Un objet de collection amusant et ironique pour les fans qui apprécient les variantes Star Wars sur le thème des fêtes et les interprétations légères de personnages iconiques.',
    description_es: 'Darth Vader en suéter navideño representa una variante festiva humorística del villano más temido de la galaxia. Este diseño caprichoso yuxtapone la presencia amenazante de Vader con alegría navideña acogedora. El suéter juguetón trae calidez inesperada al Señor Oscuro. Un coleccionable divertido e irónico para fanáticos que aprecian variantes temáticas navideñas de Star Wars e interpretaciones alegres de personajes icónicos.'
  },
  {
    minifigure_no: 'sw1124',
    description_en: 'Ponda Baba is the aggressive Aqualish criminal who threatened Luke Skywalker in the Mos Eisley Cantina before Obi-Wan intervened. This belligerent patron\'s encounter with the old Jedi demonstrated lightsaber lethality. His distinctive walrus-like appearance made him one of the cantina\'s most memorable patrons. An essential character for collectors building the complete Mos Eisley Cantina scene and iconic A New Hope moments.',
    description_de: 'Ponda Baba ist der aggressive Aqualish-Kriminelle, der Luke Skywalker in der Mos Eisley-Cantina bedrohte, bevor Obi-Wan eingriff. Die Begegnung dieses kriegslustigen Gastes mit dem alten Jedi demonstrierte Lichtschwert-Tödlichkeit. Sein markantes walross-ähnliches Erscheinungsbild machte ihn zu einem der unvergesslichsten Gäste der Cantina. Ein unverzichtbarer Charakter für Sammler, die die vollständige Mos Eisley-Cantina-Szene und ikonische Eine neue Hoffnung-Momente aufbauen.',
    description_fr: 'Ponda Baba est le criminel Aqualish agressif qui a menacé Luke Skywalker dans la Cantina de Mos Eisley avant qu\'Obi-Wan n\'intervienne. La rencontre de ce client belliqueux avec le vieux Jedi a démontré la létalité du sabre laser. Son apparence distinctive ressemblant à un morse en a fait l\'un des clients les plus mémorables de la cantina. Un personnage essentiel pour les collectionneurs construisant la scène complète de la Cantina de Mos Eisley et les moments iconiques d\'Un nouvel espoir.',
    description_es: 'Ponda Baba es el criminal Aqualish agresivo que amenazó a Luke Skywalker en la Cantina de Mos Eisley antes de que Obi-Wan interviniera. El encuentro de este cliente beligerante con el viejo Jedi demostró la letalidad del sable de luz. Su distintiva apariencia similar a morsa lo convirtió en uno de los clientes más memorables de la cantina. Un personaje esencial para coleccionistas que construyen la escena completa de la Cantina de Mos Eisley y momentos icónicos de Una nueva esperanza.'
  },
  {
    minifigure_no: 'sw1125',
    description_en: 'Dr. Cornelius Evazan is the disfigured criminal doctor wanted in twelve systems who partnered with Ponda Baba. This violent surgeon\'s threats against Luke precipitated the cantina\'s first lightsaber demonstration. His scarred appearance and death sentence reputation made him memorable. An important cantina patron for collectors building the complete Mos Eisley scene and criminal underworld characters.',
    description_de: 'Dr. Cornelius Evazan ist der entstellte kriminelle Arzt, der in zwölf Systemen gesucht wird und mit Ponda Baba zusammenarbeitete. Die Drohungen dieses gewalttätigen Chirurgen gegen Luke führten zur ersten Lichtschwert-Demonstration der Cantina. Sein vernarbtes Erscheinungsbild und Todesurteil-Ruf machten ihn unvergesslich. Ein wichtiger Cantina-Gast für Sammler, die die vollständige Mos Eisley-Szene und kriminelle Unterweltcharaktere aufbauen.',
    description_fr: 'Le Dr Cornelius Evazan est le médecin criminel défiguré recherché dans douze systèmes qui s\'est associé à Ponda Baba. Les menaces de ce chirurgien violent contre Luke ont précipité la première démonstration de sabre laser de la cantina. Son apparence cicatrisée et sa réputation de condamné à mort l\'ont rendu mémorable. Un client important de la cantina pour les collectionneurs construisant la scène complète de Mos Eisley et les personnages du monde criminel.',
    description_es: 'El Dr. Cornelius Evazan es el médico criminal desfigurado buscado en doce sistemas que se asoció con Ponda Baba. Las amenazas de este cirujano violento contra Luke precipitaron la primera demostración de sable de luz de la cantina. Su apariencia cicatrizada y reputación de sentencia de muerte lo hicieron memorable. Un cliente importante de la cantina para coleccionistas que construyen la escena completa de Mos Eisley y personajes del submundo criminal.'
  },
  {
    minifigure_no: 'sw1126',
    description_en: 'Labria, also known as Kardue\'sai\'Malloc, is the Devaronian patron sitting in the Mos Eisley Cantina\'s shadows. This horned alien represents the diverse criminal element hiding throughout the spaceport. The distinctive devil-like appearance made Devaronians instantly recognizable. A character piece for collectors building the complete cantina population and diverse alien species displays.',
    description_de: 'Labria, auch bekannt als Kardue\'sai\'Malloc, ist der Devaronianer-Gast, der in den Schatten der Mos Eisley-Cantina sitzt. Dieser gehörnte Außerirdische repräsentiert das vielfältige kriminelle Element, das sich im gesamten Raumhafen versteckt. Das markante teufelähnliche Erscheinungsbild machte Devaronianer sofort erkennbar. Ein Charakterstück für Sammler, die die vollständige Cantina-Bevölkerung und vielfältige außerirdische Spezies-Displays aufbauen.',
    description_fr: 'Labria, également connu sous le nom de Kardue\'sai\'Malloc, est le client Dévaronien assis dans les ombres de la Cantina de Mos Eisley. Cet alien cornu représente l\'élément criminel divers se cachant dans tout le spatioport. L\'apparence distinctive ressemblant à un diable a rendu les Dévaroniens instantanément reconnaissables. Une pièce de personnage pour les collectionneurs construisant la population complète de la cantina et diverses présentations d\'espèces aliens.',
    description_es: 'Labria, también conocido como Kardue\'sai\'Malloc, es el cliente Devaroniano sentado en las sombras de la Cantina de Mos Eisley. Este alienígena con cuernos representa el diverso elemento criminal escondiéndose por todo el puerto espacial. La distintiva apariencia similar a demonio hizo a los Devaronianos instantáneamente reconocibles. Una pieza de personaje para coleccionistas que construyen la población completa de la cantina y diversas exhibiciones de especies alienígenas.'
  },
  {
    minifigure_no: 'sw1127',
    description_en: 'Garindan, also known as Long Snoot, is the Kubaz spy who informed Imperial forces of the droids\' location in Mos Eisley. This insectivorous alien\'s distinctive long snout and dark goggles made him visually striking. His betrayal led stormtroopers to discover the Millennium Falcon. An important supporting character for collectors building Mos Eisley street scenes and the network of Imperial informants.',
    description_de: 'Garindan, auch bekannt als Long Snoot, ist der Kubaz-Spion, der imperiale Kräfte über den Standort der Droiden in Mos Eisley informierte. Die markante lange Schnauze und dunkle Schutzbrille dieses insektenfressenden Außerirdischen machten ihn visuell auffällig. Sein Verrat führte Stormtrooper dazu, den Millennium Falken zu entdecken. Ein wichtiger Nebendarsteller für Sammler, die Mos Eisley-Straßenszenen und das Netzwerk imperialer Informanten aufbauen.',
    description_fr: 'Garindan, également connu sous le nom de Long Snoot, est l\'espion Kubaz qui a informé les forces impériales de l\'emplacement des droïdes à Mos Eisley. Le long museau distinctif et les lunettes sombres de cet alien insectivore le rendaient visuellement frappant. Sa trahison a conduit les stormtroopers à découvrir le Faucon Millenium. Un personnage de soutien important pour les collectionneurs construisant des scènes de rue de Mos Eisley et le réseau d\'informateurs impériaux.',
    description_es: 'Garindan, también conocido como Long Snoot, es el espía Kubaz que informó a las fuerzas Imperiales de la ubicación de los droides en Mos Eisley. El distintivo hocico largo y gafas oscuras de este alienígena insectívoro lo hicieron visualmente llamativo. Su traición llevó a stormtroopers a descubrir el Halcón Milenario. Un personaje secundario importante para coleccionistas que construyen escenas callejeras de Mos Eisley y la red de informantes Imperiales.'
  },
  {
    minifigure_no: 'sw1128',
    description_en: 'Momaw Nadon, the Ithorian known as Hammerhead, is the gentle herbivore sitting in the Mos Eisley Cantina. This exiled ecologist represented the peaceful species forced into hiding by the Empire. The distinctive hammer-shaped head made Ithorians one of Star Wars\' most recognizable aliens. An iconic cantina patron for collectors building the diverse alien population and memorable background characters.',
    description_de: 'Momaw Nadon, der Ithorianer bekannt als Hammerhead, ist der sanfte Pflanzenfresser, der in der Mos Eisley-Cantina sitzt. Dieser exilierte Ökologe repräsentierte die friedliche Spezies, die vom Imperium ins Versteck gezwungen wurde. Der markante hammerförmige Kopf machte Ithorianer zu einem der erkennbarsten Außerirdischen von Star Wars. Ein ikonischer Cantina-Gast für Sammler, die die vielfältige außerirdische Bevölkerung und unvergessliche Hintergrundcharaktere aufbauen.',
    description_fr: 'Momaw Nadon, l\'Ithorien connu sous le nom de Hammerhead, est l\'herbivore doux assis dans la Cantina de Mos Eisley. Cet écologiste exilé représentait l\'espèce pacifique forcée à se cacher par l\'Empire. La tête distinctive en forme de marteau a fait des Ithoriens l\'un des aliens les plus reconnaissables de Star Wars. Un client iconique de la cantina pour les collectionneurs construisant la population alien diversifiée et les personnages de fond mémorables.',
    description_es: 'Momaw Nadon, el Ithoriano conocido como Hammerhead, es el gentil herbívoro sentado en la Cantina de Mos Eisley. Este ecologista exiliado representó la especie pacífica forzada a ocultarse por el Imperio. La distintiva cabeza en forma de martillo hizo a los Ithorianos uno de los alienígenas más reconocibles de Star Wars. Un cliente icónico de la cantina para coleccionistas que construyen la población alienígena diversa y personajes de fondo memorables.'
  },
  {
    minifigure_no: 'sw1129',
    description_en: 'Kabe is the small Chadra-Fan thief who operated in the Mos Eisley underworld. This diminutive criminal represents the lowest tier of spaceport society surviving through cunning and theft. The bat-like features made Chadra-Fan distinctive among cantina patrons. A character piece for collectors building the complete social hierarchy and diverse species of the Mos Eisley Cantina.',
    description_de: 'Kabe ist die kleine Chadra-Fan-Diebin, die in der Mos Eisley-Unterwelt operierte. Diese winzige Kriminelle repräsentiert die unterste Stufe der Raumhafen-Gesellschaft, die durch List und Diebstahl überlebt. Die fledermausähnlichen Züge machten Chadra-Fan unter Cantina-Gästen markant. Ein Charakterstück für Sammler, die die vollständige soziale Hierarchie und vielfältige Spezies der Mos Eisley-Cantina aufbauen.',
    description_fr: 'Kabe est la petite voleuse Chadra-Fan qui opérait dans le monde criminel de Mos Eisley. Cette criminelle minuscule représente le niveau le plus bas de la société spatioport survivant par la ruse et le vol. Les traits ressemblant à une chauve-souris ont rendu les Chadra-Fan distinctifs parmi les clients de la cantina. Une pièce de personnage pour les collectionneurs construisant la hiérarchie sociale complète et les espèces diverses de la Cantina de Mos Eisley.',
    description_es: 'Kabe es la pequeña ladrona Chadra-Fan que operó en el submundo de Mos Eisley. Esta diminuta criminal representa el nivel más bajo de la sociedad del puerto espacial sobreviviendo mediante astucia y robo. Los rasgos similares a murciélago hicieron a los Chadra-Fan distintivos entre clientes de la cantina. Una pieza de personaje para coleccionistas que construyen la jerarquía social completa y especies diversas de la Cantina de Mos Eisley.'
  },
  {
    minifigure_no: 'sw1130',
    description_en: 'Hrchek Kal Fas is the Saurin patron in the Mos Eisley Cantina representing another of the diverse alien species populating Tatooine\'s spaceport. This reptilian character adds to the rich tapestry of cantina life. The variety of species shown in the cantina established Star Wars as a truly diverse galaxy. A collectible character for completing the cantina\'s alien population and celebrating the iconic scene\'s diversity.',
    description_de: 'Hrchek Kal Fas ist der Saurin-Gast in der Mos Eisley-Cantina, der eine weitere der vielfältigen außerirdischen Spezies repräsentiert, die Tatooines Raumhafen bevölkern. Dieser reptilienartige Charakter fügt dem reichen Geflecht des Cantina-Lebens hinzu. Die Vielfalt der in der Cantina gezeigten Spezies etablierte Star Wars als wahrhaft vielfältige Galaxis. Ein sammelbarer Charakter für die Vervollständigung der außerirdischen Bevölkerung der Cantina und das Feiern der Vielfalt der ikonischen Szene.',
    description_fr: 'Hrchek Kal Fas est le client Saurin dans la Cantina de Mos Eisley représentant une autre des diverses espèces aliens peuplant le spatioport de Tatooine. Ce personnage reptilien ajoute à la riche tapisserie de la vie de la cantina. La variété d\'espèces montrée dans la cantina a établi Star Wars comme une galaxie vraiment diversifiée. Un personnage collectionnable pour compléter la population alien de la cantina et célébrer la diversité de la scène iconique.',
    description_es: 'Hrchek Kal Fas es el cliente Saurin en la Cantina de Mos Eisley que representa otra de las diversas especies alienígenas que pueblan el puerto espacial de Tatooine. Este personaje reptiliano añade al rico tapiz de la vida de la cantina. La variedad de especies mostradas en la cantina estableció a Star Wars como una galaxia verdaderamente diversa. Un personaje coleccionable para completar la población alienígena de la cantina y celebrar la diversidad de la escena icónica.'
  }
];

async function main() {
  console.log('Starting batch save for sw1111-sw1130...');

  for (const desc of descriptions) {
    await prisma.minifigCatalog.update({
      where: { minifigure_no: desc.minifigure_no },
      data: {
        description_en: desc.description_en,
        description_de: desc.description_de,
        description_fr: desc.description_fr,
        description_es: desc.description_es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`✓ Saved ${desc.minifigure_no}: ${descriptions.find(d => d.minifigure_no === desc.minifigure_no)?.minifigure_no}`);
  }

  console.log(`Batch complete! ${descriptions.length} minifigs saved (sw1111-sw1130).`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
