import { PrismaClient as PrismaClientHostinger } from '@prisma/client';

const prisma = new PrismaClientHostinger({
  datasources: {
    db: {
      url: process.env.DATABASE_URL
    }
  }
});

const descriptions = [
  {
    minifigure_no: 'sw1351',
    description_en: "Fern is a young character from the Disney+ series Skeleton Crew, representing the new generation of Star Wars adventurers. This minifigure captures her distinctive appearance from the show with authentic costume details and youthful design. As part of the Skeleton Crew wave, Fern represents LEGO's commitment to bringing the latest Star Wars stories to life. Collectors appreciate this figure for its connection to the expanding Star Wars universe and limited availability.",
    description_de: "Fern ist eine junge Figur aus der Disney+-Serie Skeleton Crew und repräsentiert die neue Generation von Star Wars-Abenteurern. Diese Minifigur fängt ihr markantes Aussehen aus der Serie mit authentischen Kostümdetails und jugendlichem Design ein. Als Teil der Skeleton Crew-Welle zeigt Fern LEGOs Engagement, die neuesten Star Wars-Geschichten zum Leben zu erwecken. Sammler schätzen diese Figur für ihre Verbindung zum expandierenden Star Wars-Universum und begrenzte Verfügbarkeit.",
    description_fr: "Fern est un jeune personnage de la série Disney+ Skeleton Crew, représentant la nouvelle génération d'aventuriers Star Wars. Cette minifigurine capture son apparence distinctive de la série avec des détails de costume authentiques et un design juvénile. Faisant partie de la vague Skeleton Crew, Fern représente l'engagement de LEGO à donner vie aux dernières histoires Star Wars. Les collectionneurs apprécient cette figurine pour sa connexion à l'univers Star Wars en expansion et sa disponibilité limitée.",
    description_es: "Fern es un personaje joven de la serie de Disney+ Skeleton Crew, representando la nueva generación de aventureros de Star Wars. Esta minifigura captura su apariencia distintiva del programa con detalles de vestuario auténticos y diseño juvenil. Como parte de la ola de Skeleton Crew, Fern representa el compromiso de LEGO de dar vida a las últimas historias de Star Wars. Los coleccionistas aprecian esta figura por su conexión con el universo Star Wars en expansión y disponibilidad limitada."
  },
  {
    minifigure_no: 'sw1352',
    description_en: "KB is a droid character from the Disney+ series Skeleton Crew, adding to LEGO's diverse collection of Star Wars droids. This minifigure features unique droid construction and design elements specific to the Skeleton Crew series. The figure represents the latest chapter in Star Wars storytelling with authentic details from the show. Collectors value KB for its distinctive appearance and role in expanding the Star Wars droid family in LEGO form.",
    description_de: "KB ist eine Droidfigur aus der Disney+-Serie Skeleton Crew und erweitert LEGOs vielfältige Sammlung von Star Wars-Droiden. Diese Minifigur verfügt über einzigartige Droid-Konstruktion und Designelemente, die spezifisch für die Skeleton Crew-Serie sind. Die Figur repräsentiert das neueste Kapitel im Star Wars-Storytelling mit authentischen Details aus der Serie. Sammler schätzen KB für sein markantes Aussehen und seine Rolle bei der Erweiterung der Star Wars-Droidfamilie in LEGO-Form.",
    description_fr: "KB est un personnage droïde de la série Disney+ Skeleton Crew, ajoutant à la collection diversifiée de droïdes Star Wars de LEGO. Cette minifigurine présente une construction de droïde unique et des éléments de design spécifiques à la série Skeleton Crew. La figurine représente le dernier chapitre de la narration Star Wars avec des détails authentiques de la série. Les collectionneurs apprécient KB pour son apparence distinctive et son rôle dans l'expansion de la famille de droïdes Star Wars sous forme LEGO.",
    description_es: "KB es un personaje droide de la serie de Disney+ Skeleton Crew, añadiendo a la diversa colección de droides de Star Wars de LEGO. Esta minifigura presenta construcción de droide única y elementos de diseño específicos de la serie Skeleton Crew. La figura representa el último capítulo en la narrativa de Star Wars con detalles auténticos del programa. Los coleccionistas valoran KB por su apariencia distintiva y papel en expandir la familia de droides de Star Wars en forma LEGO."
  },
  {
    minifigure_no: 'sw1353',
    description_en: "Jod is a character from the Disney+ series Skeleton Crew, representing the mysterious figures in this new Star Wars adventure. This minifigure captures his distinctive appearance with authentic costume details and character-specific elements. As part of the Skeleton Crew collection, Jod helps tell the story of this unique Star Wars series. Collectors appreciate this figure for its connection to the latest Star Wars content and limited production run.",
    description_de: "Jod ist eine Figur aus der Disney+-Serie Skeleton Crew und repräsentiert die mysteriösen Gestalten in diesem neuen Star Wars-Abenteuer. Diese Minifigur fängt sein markantes Aussehen mit authentischen Kostümdetails und charakterspezifischen Elementen ein. Als Teil der Skeleton Crew-Sammlung hilft Jod dabei, die Geschichte dieser einzigartigen Star Wars-Serie zu erzählen. Sammler schätzen diese Figur für ihre Verbindung zu den neuesten Star Wars-Inhalten und begrenzte Produktionsauflage.",
    description_fr: "Jod est un personnage de la série Disney+ Skeleton Crew, représentant les figures mystérieuses dans cette nouvelle aventure Star Wars. Cette minifigurine capture son apparence distinctive avec des détails de costume authentiques et des éléments spécifiques au personnage. Faisant partie de la collection Skeleton Crew, Jod aide à raconter l'histoire de cette série Star Wars unique. Les collectionneurs apprécient cette figurine pour sa connexion au contenu Star Wars le plus récent et sa production limitée.",
    description_es: "Jod es un personaje de la serie de Disney+ Skeleton Crew, representando las figuras misteriosas en esta nueva aventura de Star Wars. Esta minifigura captura su apariencia distintiva con detalles de vestuario auténticos y elementos específicos del personaje. Como parte de la colección Skeleton Crew, Jod ayuda a contar la historia de esta serie única de Star Wars. Los coleccionistas aprecian esta figura por su conexión con el contenido más reciente de Star Wars y tirada de producción limitada."
  },
  {
    minifigure_no: 'sw1354',
    description_en: "Adult Ahsoka Tano appears in this version with a dark bluish gray vest and tan tunic, reflecting her appearance in the Ahsoka series. The figure features printed arms and light bluish gray legs, capturing her evolved Jedi aesthetic. This variant shows Ahsoka's matured character design with detailed costume printing. Collectors seek this version for its unique color combination and representation of Ahsoka's journey from Padawan to experienced Jedi.",
    description_de: "Die erwachsene Ahsoka Tano erscheint in dieser Version mit einer dunkelblaugrauen Weste und beigefarbener Tunika, die ihr Aussehen in der Ahsoka-Serie widerspiegelt. Die Figur verfügt über bedruckte Arme und hellblaugraue Beine und fängt ihre weiterentwickelte Jedi-Ästhetik ein. Diese Variante zeigt Ahsokas gereiftes Charakterdesign mit detailliertem Kostümdruck. Sammler suchen diese Version wegen ihrer einzigartigen Farbkombination und Darstellung von Ahsokas Reise von der Padawan zur erfahrenen Jedi.",
    description_fr: "Ahsoka Tano adulte apparaît dans cette version avec un gilet gris bleuâtre foncé et une tunique beige, reflétant son apparence dans la série Ahsoka. La figurine présente des bras imprimés et des jambes gris bleuâtre clair, capturant son esthétique Jedi évoluée. Cette variante montre le design de personnage mature d'Ahsoka avec une impression de costume détaillée. Les collectionneurs recherchent cette version pour sa combinaison de couleurs unique et sa représentation du voyage d'Ahsoka de Padawan à Jedi expérimentée.",
    description_es: "Ahsoka Tano adulta aparece en esta versión con un chaleco gris azulado oscuro y túnica beige, reflejando su apariencia en la serie Ahsoka. La figura presenta brazos impresos y piernas gris azulado claro, capturando su estética Jedi evolucionada. Esta variante muestra el diseño de personaje maduro de Ahsoka con impresión de vestuario detallada. Los coleccionistas buscan esta versión por su combinación de colores única y representación del viaje de Ahsoka de Padawan a Jedi experimentada."
  },
  {
    minifigure_no: 'sw1355',
    description_en: "Ezra Bridger appears in this version wearing a dark red robe, reflecting his appearance in the Ahsoka series after years in exile. This mature version of Ezra shows his evolution from the young Rebel to a seasoned Force user. The dark red robe distinguishes this variant from earlier Ezra minifigures and captures his changed circumstances. Collectors appreciate this figure for representing Ezra's return to the main Star Wars timeline and his reunion with Ahsoka.",
    description_de: "Ezra Bridger erscheint in dieser Version in einer dunkelroten Robe, die sein Aussehen in der Ahsoka-Serie nach Jahren im Exil widerspiegelt. Diese reife Version von Ezra zeigt seine Entwicklung vom jungen Rebellen zu einem erfahrenen Machtanwender. Die dunkelrote Robe unterscheidet diese Variante von früheren Ezra-Minifiguren und fängt seine veränderten Umstände ein. Sammler schätzen diese Figur für die Darstellung von Ezras Rückkehr zur Haupt-Star Wars-Zeitlinie und seiner Wiedervereinigung mit Ahsoka.",
    description_fr: "Ezra Bridger apparaît dans cette version portant une robe rouge foncé, reflétant son apparence dans la série Ahsoka après des années en exil. Cette version mature d'Ezra montre son évolution du jeune Rebelle à un utilisateur de la Force aguerri. La robe rouge foncé distingue cette variante des minifigurines Ezra antérieures et capture ses circonstances changées. Les collectionneurs apprécient cette figurine pour représenter le retour d'Ezra dans la chronologie principale de Star Wars et ses retrouvailles avec Ahsoka.",
    description_es: "Ezra Bridger aparece en esta versión vistiendo una túnica rojo oscuro, reflejando su apariencia en la serie Ahsoka después de años en exilio. Esta versión madura de Ezra muestra su evolución del joven Rebelde a un usuario de la Fuerza experimentado. La túnica rojo oscuro distingue esta variante de minifiguras anteriores de Ezra y captura sus circunstancias cambiadas. Los coleccionistas aprecian esta figura por representar el regreso de Ezra a la línea temporal principal de Star Wars y su reunión con Ahsoka."
  },
  {
    minifigure_no: 'sw1356',
    description_en: "Grand Admiral Thrawn appears in this version with medium blue skin, capturing the iconic Imperial strategist's distinctive Chiss features. This figure represents Thrawn's appearance in the Ahsoka series, marking his live-action debut. The medium blue skin tone accurately depicts the legendary villain from both Rebels and the Thrawn novel trilogy. Collectors highly value this figure for representing one of Star Wars' most intelligent and calculating adversaries in minifigure form.",
    description_de: "Großadmiral Thrawn erscheint in dieser Version mit mittelblauer Haut und fängt die markanten Chiss-Merkmale des ikonischen imperialen Strategen ein. Diese Figur repräsentiert Thrawns Aussehen in der Ahsoka-Serie und markiert sein Live-Action-Debüt. Der mittelblaue Hautton stellt den legendären Bösewicht aus sowohl Rebels als auch der Thrawn-Romantrilogie genau dar. Sammler schätzen diese Figur sehr hoch für die Darstellung eines der intelligentesten und berechnendsten Widersacher von Star Wars in Minifigurform.",
    description_fr: "Le Grand Amiral Thrawn apparaît dans cette version avec une peau bleu moyen, capturant les traits Chiss distinctifs du stratège Impérial iconique. Cette figurine représente l'apparence de Thrawn dans la série Ahsoka, marquant ses débuts en prise de vue réelle. Le ton de peau bleu moyen dépeint avec précision le vilain légendaire de Rebels et de la trilogie de romans Thrawn. Les collectionneurs apprécient beaucoup cette figurine pour représenter l'un des adversaires les plus intelligents et calculateurs de Star Wars sous forme de minifigurine.",
    description_es: "El Gran Almirante Thrawn aparece en esta versión con piel azul medio, capturando los rasgos Chiss distintivos del estratega Imperial icónico. Esta figura representa la apariencia de Thrawn en la serie Ahsoka, marcando su debut en acción real. El tono de piel azul medio representa con precisión al villano legendario tanto de Rebels como de la trilogía de novelas de Thrawn. Los coleccionistas valoran altamente esta figura por representar a uno de los adversarios más inteligentes y calculadores de Star Wars en forma de minifigura."
  },
  {
    minifigure_no: 'sw1357',
    description_en: "Morgan Elsbeth appears with black legs, representing the dark witch and ally of Thrawn from the Ahsoka series. This minifigure captures her distinctive appearance with detailed costume printing and character-specific elements. Morgan's role as a key antagonist in the Ahsoka series makes this figure narratively significant. Collectors appreciate this figure for its connection to the live-action Ahsoka series and representation of Imperial remnant forces.",
    description_de: "Morgan Elsbeth erscheint mit schwarzen Beinen und repräsentiert die dunkle Hexe und Verbündete von Thrawn aus der Ahsoka-Serie. Diese Minifigur fängt ihr markantes Aussehen mit detailliertem Kostümdruck und charakterspezifischen Elementen ein. Morgans Rolle als Hauptantagonistin in der Ahsoka-Serie macht diese Figur erzählerisch bedeutsam. Sammler schätzen diese Figur für ihre Verbindung zur Live-Action-Ahsoka-Serie und Darstellung der imperialen Überreste.",
    description_fr: "Morgan Elsbeth apparaît avec des jambes noires, représentant la sorcière sombre et alliée de Thrawn de la série Ahsoka. Cette minifigurine capture son apparence distinctive avec une impression de costume détaillée et des éléments spécifiques au personnage. Le rôle de Morgan en tant qu'antagoniste clé dans la série Ahsoka rend cette figurine narrativement significative. Les collectionneurs apprécient cette figurine pour sa connexion à la série Ahsoka en prise de vue réelle et sa représentation des forces impériales résiduelles.",
    description_es: "Morgan Elsbeth aparece con piernas negras, representando a la bruja oscura y aliada de Thrawn de la serie Ahsoka. Esta minifigura captura su apariencia distintiva con impresión de vestuario detallada y elementos específicos del personaje. El papel de Morgan como antagonista clave en la serie Ahsoka hace que esta figura sea narrativamente significativa. Los coleccionistas aprecian esta figura por su conexión con la serie de acción real de Ahsoka y representación de fuerzas imperiales remanentes."
  },
  {
    minifigure_no: 'sw1358',
    description_en: "The Night Trooper with white helmet represents the reanimated Imperial forces serving Thrawn in the Ahsoka series. This figure features distinctive armor details showing battle damage and dark magic influence. The Night Troopers represent a unique evolution of standard Stormtroopers with their eerie, undead aesthetic. Collectors value this figure for its unique design combining Imperial military elements with supernatural horror themes.",
    description_de: "Der Nachttruppler mit weißem Helm repräsentiert die wiedererweckten imperialen Streitkräfte, die Thrawn in der Ahsoka-Serie dienen. Diese Figur zeigt markante Rüstungsdetails mit Kampfschäden und Einfluss dunkler Magie. Die Nachttruppler repräsentieren eine einzigartige Entwicklung der Standard-Stormtrooper mit ihrer unheimlichen, untoten Ästhetik. Sammler schätzen diese Figur für ihr einzigartiges Design, das imperiale Militärelemente mit übernatürlichen Horrorthe men kombiniert.",
    description_fr: "Le Night Trooper avec casque blanc représente les forces Impériales réanimées servant Thrawn dans la série Ahsoka. Cette figurine présente des détails d'armure distinctifs montrant des dommages de combat et une influence de magie noire. Les Night Troopers représentent une évolution unique des Stormtroopers standards avec leur esthétique de mort-vivant inquiétante. Les collectionneurs apprécient cette figurine pour son design unique combinant des éléments militaires Impériaux avec des thèmes d'horreur surnaturelle.",
    description_es: "El Night Trooper con casco blanco representa las fuerzas Imperiales reanimadas sirviendo a Thrawn en la serie Ahsoka. Esta figura presenta detalles de armadura distintivos mostrando daño de batalla e influencia de magia oscura. Los Night Troopers representan una evolución única de los Stormtroopers estándar con su estética espeluznante de no-muerto. Los coleccionistas valoran esta figura por su diseño único que combina elementos militares Imperiales con temas de horror sobrenatural."
  },
  {
    minifigure_no: 'sw1359',
    description_en: "The Rebel Pilot with helmet featuring black Rebel Alliance symbols represents the brave starfighter pilots fighting for freedom. This figure features distinctive helmet printing with prominent Alliance symbols and authentic pilot gear details. The design captures the heroic aesthetic of Rebel forces with military precision. Collectors appreciate this pilot variant for its clean helmet design and representation of the Rebellion's ace pilots.",
    description_de: "Der Rebellenpilot mit Helm mit schwarzen Rebellenallianz-Symbolen repräsentiert die mutigen Sternenjägerpiloten, die für die Freiheit kämpfen. Diese Figur zeigt markanten Helmdruck mit prominenten Allianz-Symbolen und authentischen Pilotenausrüstungsdetails. Das Design fängt die heroische Ästhetik der Rebellenstreitkräfte mit militärischer Präzision ein. Sammler schätzen diese Pilotenvariante für ihr sauberes Helmdesign und die Darstellung der Ass-Piloten der Rebellion.",
    description_fr: "Le Pilote Rebelle avec casque arborant des symboles noirs de l'Alliance Rebelle représente les courageux pilotes de chasseurs stellaires combattant pour la liberté. Cette figurine présente une impression de casque distinctive avec des symboles d'Alliance proéminents et des détails d'équipement de pilote authentiques. Le design capture l'esthétique héroïque des forces Rebelles avec une précision militaire. Les collectionneurs apprécient cette variante de pilote pour son design de casque épuré et sa représentation des pilotes as de la Rébellion.",
    description_es: "El Piloto Rebelde con casco que presenta símbolos negros de la Alianza Rebelde representa a los valientes pilotos de cazas estelares luchando por la libertad. Esta figura presenta impresión de casco distintiva con símbolos de Alianza prominentes y detalles auténticos de equipo de piloto. El diseño captura la estética heroica de las fuerzas Rebeldes con precisión militar. Los coleccionistas aprecian esta variante de piloto por su diseño de casco limpio y representación de los pilotos as de la Rebelión."
  },
  {
    minifigure_no: 'sw1360',
    description_en: "Yesi Scala is a character from Star Wars: Young Jedi Adventures, representing the new generation of Jedi learners. This minifigure captures her youthful appearance with distinctive costume details from the animated series. As part of the Young Jedi Adventures collection, Yesi helps introduce younger fans to Star Wars storytelling. Collectors appreciate this figure for its connection to the expanding High Republic era content.",
    description_de: "Yesi Scala ist eine Figur aus Star Wars: Young Jedi Adventures und repräsentiert die neue Generation von Jedi-Schülern. Diese Minifigur fängt ihr jugendliches Aussehen mit markanten Kostümdetails aus der Animationsserie ein. Als Teil der Young Jedi Adventures-Sammlung hilft Yesi dabei, jüngere Fans an Star Wars-Storytelling heranzuführen. Sammler schätzen diese Figur für ihre Verbindung zu den expandierenden Inhalten der Ära der Hohen Republik.",
    description_fr: "Yesi Scala est un personnage de Star Wars: Young Jedi Adventures, représentant la nouvelle génération d'apprentis Jedi. Cette minifigurine capture son apparence juvénile avec des détails de costume distinctifs de la série animée. Faisant partie de la collection Young Jedi Adventures, Yesi aide à introduire les jeunes fans à la narration Star Wars. Les collectionneurs apprécient cette figurine pour sa connexion au contenu de l'ère de la Haute République en expansion.",
    description_es: "Yesi Scala es un personaje de Star Wars: Young Jedi Adventures, representando la nueva generación de aprendices Jedi. Esta minifigura captura su apariencia juvenil con detalles de vestuario distintivos de la serie animada. Como parte de la colección Young Jedi Adventures, Yesi ayuda a introducir a fans más jóvenes a la narrativa de Star Wars. Los coleccionistas aprecian esta figura por su conexión con el contenido en expansión de la era de la Alta República."
  },
  {
    minifigure_no: 'sw1361',
    description_en: "Sig Greebling appears in a dark tan jacket, representing a character from the Skeleton Crew series. This minifigure features detailed costume printing that captures his distinctive appearance from the show. The figure adds to the expanding roster of original characters in the Disney+ Star Wars series. Collectors value this minifigure for its connection to the latest Star Wars storytelling and unique character design.",
    description_de: "Sig Greebling erscheint in einer dunkelbeigen Jacke und repräsentiert eine Figur aus der Skeleton Crew-Serie. Diese Minifigur zeigt detaillierten Kostümdruck, der sein markantes Aussehen aus der Serie einfängt. Die Figur erweitert die wachsende Liste originaler Charaktere in den Disney+ Star Wars-Serien. Sammler schätzen diese Minifigur für ihre Verbindung zum neuesten Star Wars-Storytelling und einzigartigen Charakterdesign.",
    description_fr: "Sig Greebling apparaît dans une veste beige foncé, représentant un personnage de la série Skeleton Crew. Cette minifigurine présente une impression de costume détaillée qui capture son apparence distinctive de la série. La figurine s'ajoute à la liste croissante de personnages originaux dans les séries Star Wars Disney+. Les collectionneurs apprécient cette minifigurine pour sa connexion à la narration Star Wars la plus récente et son design de personnage unique.",
    description_es: "Sig Greebling aparece en una chaqueta beige oscuro, representando un personaje de la serie Skeleton Crew. Esta minifigura presenta impresión de vestuario detallada que captura su apariencia distintiva del programa. La figura añade al creciente elenco de personajes originales en las series de Star Wars de Disney+. Los coleccionistas valoran esta minifigura por su conexión con la narrativa más reciente de Star Wars y diseño de personaje único."
  },
  {
    minifigure_no: 'sw1362',
    description_en: "L3-GO is an astromech droid from the Skeleton Crew series, adding to LEGO's extensive collection of Star Wars droids. This figure features unique droid construction elements and color scheme specific to this new series. The astromech design follows LEGO's established pattern while introducing fresh details from Skeleton Crew. Collectors appreciate this droid for expanding the astromech family with a character from the latest Star Wars content.",
    description_de: "L3-GO ist ein Astromechdroid aus der Skeleton Crew-Serie und erweitert LEGOs umfangreiche Sammlung von Star Wars-Droiden. Diese Figur verfügt über einzigartige Droid-Konstruktionselemente und ein Farbschema, das spezifisch für diese neue Serie ist. Das Astromech-Design folgt LEGOs etabliertem Muster und führt gleichzeitig frische Details aus Skeleton Crew ein. Sammler schätzen diesen Droiden für die Erweiterung der Astromech-Familie mit einem Charakter aus den neuesten Star Wars-Inhalten.",
    description_fr: "L3-GO est un droïde astromech de la série Skeleton Crew, ajoutant à l'extensive collection de droïdes Star Wars de LEGO. Cette figurine présente des éléments de construction de droïde uniques et un schéma de couleurs spécifique à cette nouvelle série. Le design astromech suit le modèle établi de LEGO tout en introduisant des détails frais de Skeleton Crew. Les collectionneurs apprécient ce droïde pour élargir la famille astromech avec un personnage du contenu Star Wars le plus récent.",
    description_es: "L3-GO es un droide astromecánico de la serie Skeleton Crew, añadiendo a la extensa colección de droides de Star Wars de LEGO. Esta figura presenta elementos de construcción de droide únicos y esquema de color específico de esta nueva serie. El diseño astromecánico sigue el patrón establecido de LEGO mientras introduce detalles frescos de Skeleton Crew. Los coleccionistas aprecian este droide por expandir la familia astromecánica con un personaje del contenido más reciente de Star Wars."
  },
  {
    minifigure_no: 'sw1363',
    description_en: "Jedi Vader is a unique what-if concept figure exploring an alternate timeline where Anakin never fell to the dark side. This minifigure combines Vader's iconic armor design with Jedi aesthetic elements, creating a fascinating alternate universe variant. The figure represents creative storytelling possibilities within the Star Wars multiverse. Collectors highly prize this figure for its imaginative concept and limited availability as a speculative character design.",
    description_de: "Jedi Vader ist eine einzigartige Was-wäre-wenn-Konzeptfigur, die eine alternative Zeitlinie erforscht, in der Anakin nie zur dunklen Seite fiel. Diese Minifigur kombiniert Vaders ikonisches Rüstungsdesign mit Jedi-Ästhetikelementen und schafft eine faszinierende Variante aus einem alternativen Universum. Die Figur repräsentiert kreative Storytelling-Möglichkeiten innerhalb des Star Wars-Multiversums. Sammler schätzen diese Figur sehr hoch für ihr fantasievolles Konzept und begrenzte Verfügbarkeit als spekulatives Charakterdesign.",
    description_fr: "Jedi Vader est une figurine conceptuelle unique de type 'et si' explorant une chronologie alternative où Anakin ne serait jamais tombé du côté obscur. Cette minifigurine combine le design d'armure iconique de Vader avec des éléments esthétiques Jedi, créant une variante d'univers alternatif fascinante. La figurine représente des possibilités narratives créatives au sein du multivers Star Wars. Les collectionneurs apprécient beaucoup cette figurine pour son concept imaginatif et sa disponibilité limitée en tant que design de personnage spéculatif.",
    description_es: "Jedi Vader es una figura de concepto único de qué-pasaría-si explorando una línea temporal alternativa donde Anakin nunca cayó al lado oscuro. Esta minifigura combina el diseño de armadura icónico de Vader con elementos estéticos Jedi, creando una variante fascinante de universo alternativo. La figura representa posibilidades de narrativa creativa dentro del multiverso de Star Wars. Los coleccionistas valoran altamente esta figura por su concepto imaginativo y disponibilidad limitada como diseño de personaje especulativo."
  },
  {
    minifigure_no: 'sw1364',
    description_en: "Darth Rey features Rey in a black dress with hood and cape, representing the dark side vision from The Rise of Skywalker. This figure captures the striking alternate reality where Rey succumbs to the dark side with menacing costume details. The design includes distinctive elements that differentiate this version from standard Rey figures. Collectors value this figure for its representation of a pivotal moment and striking visual contrast to heroic Rey variants.",
    description_de: "Darth Rey zeigt Rey in einem schwarzen Kleid mit Kapuze und Umhang und repräsentiert die Vision der dunklen Seite aus Der Aufstieg Skywalkers. Diese Figur fängt die beeindruckende alternative Realität ein, in der Rey der dunklen Seite verfällt, mit bedrohlichen Kostümdetails. Das Design umfasst markante Elemente, die diese Version von Standard-Rey-Figuren unterscheiden. Sammler schätzen diese Figur für ihre Darstellung eines entscheidenden Moments und den auffälligen visuellen Kontrast zu heroischen Rey-Varianten.",
    description_fr: "Darth Rey présente Rey dans une robe noire avec capuche et cape, représentant la vision du côté obscur de L'Ascension de Skywalker. Cette figurine capture la réalité alternative frappante où Rey succombe au côté obscur avec des détails de costume menaçants. Le design inclut des éléments distinctifs qui différencient cette version des figurines Rey standards. Les collectionneurs apprécient cette figurine pour sa représentation d'un moment pivot et son contraste visuel frappant avec les variantes héroïques de Rey.",
    description_es: "Darth Rey presenta a Rey en un vestido negro con capucha y capa, representando la visión del lado oscuro de El Ascenso de Skywalker. Esta figura captura la realidad alternativa impactante donde Rey sucumbe al lado oscuro con detalles de vestuario amenazantes. El diseño incluye elementos distintivos que diferencian esta versión de figuras estándar de Rey. Los coleccionistas valoran esta figura por su representación de un momento crucial y contraste visual impactante con variantes heroicas de Rey."
  },
  {
    minifigure_no: 'sw1365',
    description_en: "Beach Luke is a humorous variant showing Luke Skywalker in casual beach attire, representing a lighthearted take on the legendary Jedi. This figure features vacation-themed costume elements that contrast dramatically with Luke's usual heroic outfits. The design showcases LEGO's playful approach to alternate universe variants. Collectors appreciate this figure for its novelty value and comedic departure from traditional character portrayals.",
    description_de: "Strand-Luke ist eine humorvolle Variante, die Luke Skywalker in lässiger Strandkleidung zeigt und eine unbeschwerte Interpretation des legendären Jedi repräsentiert. Diese Figur zeigt urlaubsthematische Kostümelemente, die dramatisch mit Lukes üblichen heroischen Outfits kontrastieren. Das Design präsentiert LEGOs spielerischen Ansatz für alternative Universumsvarianten. Sammler schätzen diese Figur für ihren Neuheitswert und komödiantische Abweichung von traditionellen Charakterdarstellungen.",
    description_fr: "Beach Luke est une variante humoristique montrant Luke Skywalker en tenue de plage décontractée, représentant une interprétation légère du Jedi légendaire. Cette figurine présente des éléments de costume sur le thème des vacances qui contrastent dramatiquement avec les tenues héroïques habituelles de Luke. Le design met en valeur l'approche ludique de LEGO pour les variantes d'univers alternatifs. Les collectionneurs apprécient cette figurine pour sa valeur de nouveauté et son écart comique par rapport aux représentations traditionnelles de personnages.",
    description_es: "Beach Luke es una variante humorística mostrando a Luke Skywalker en atuendo casual de playa, representando una interpretación alegre del legendario Jedi. Esta figura presenta elementos de vestuario con temática de vacaciones que contrastan dramáticamente con los atuendos heroicos habituales de Luke. El diseño muestra el enfoque juguetón de LEGO hacia variantes de universo alternativo. Los coleccionistas aprecian esta figura por su valor de novedad y desviación cómica de representaciones tradicionales de personajes."
  },
  {
    minifigure_no: 'sw1366',
    description_en: "Darth Dev (Darth Devastator) appears with a cape, representing an original dark side character design. This figure features menacing armor details and the iconic Sith cape that signifies dark side power. The design combines classic Sith aesthetic with unique character elements. Collectors value this figure for its original character concept and imposing dark side presence in LEGO form.",
    description_de: "Darth Dev (Darth Devastator) erscheint mit einem Umhang und repräsentiert ein originales Charakterdesign der dunklen Seite. Diese Figur zeigt bedrohliche Rüstungsdetails und den ikonischen Sith-Umhang, der die Macht der dunklen Seite symbolisiert. Das Design kombiniert klassische Sith-Ästhetik mit einzigartigen Charakterelementen. Sammler schätzen diese Figur für ihr originales Charakterkonzept und imposante Präsenz der dunklen Seite in LEGO-Form.",
    description_fr: "Darth Dev (Darth Devastator) apparaît avec une cape, représentant un design de personnage original du côté obscur. Cette figurine présente des détails d'armure menaçants et la cape Sith iconique qui signifie le pouvoir du côté obscur. Le design combine l'esthétique Sith classique avec des éléments de personnage uniques. Les collectionneurs apprécient cette figurine pour son concept de personnage original et sa présence imposante du côté obscur sous forme LEGO.",
    description_es: "Darth Dev (Darth Devastator) aparece con una capa, representando un diseño de personaje original del lado oscuro. Esta figura presenta detalles de armadura amenazantes y la capa Sith icónica que significa el poder del lado oscuro. El diseño combina estética Sith clásica con elementos de personaje únicos. Los coleccionistas valoran esta figura por su concepto de personaje original y presencia imponente del lado oscuro en forma LEGO."
  },
  {
    minifigure_no: 'sw1367',
    description_en: "Darth Jar Jar presents Jar Jar Binks in a black outfit with printed head featuring dark orange top, exploring the infamous fan theory. This humorous figure reimagines the clumsy Gungan as a secret Sith Lord with menacing costume details. The design plays on one of Star Wars' most enduring fan theories with LEGO creativity. Collectors highly prize this figure for its comedic concept and clever subversion of a beloved character.",
    description_de: "Darth Jar Jar präsentiert Jar Jar Binks in schwarzer Kleidung mit bedrucktem Kopf mit dunkelorangem Oberteil und erkundet die berüchtigte Fan-Theorie. Diese humorvolle Figur stellt den tollpatschigen Gungan als geheimen Sith-Lord mit bedrohlichen Kostümdetails neu vor. Das Design spielt auf eine der beständigsten Fan-Theorien von Star Wars mit LEGO-Kreativität an. Sammler schätzen diese Figur sehr hoch für ihr komödiantisches Konzept und clevere Subversion eines beliebten Charakters.",
    description_fr: "Darth Jar Jar présente Jar Jar Binks dans une tenue noire avec tête imprimée arborant un haut orange foncé, explorant la théorie de fan infâme. Cette figurine humoristique réinvente le Gungan maladroit en Seigneur Sith secret avec des détails de costume menaçants. Le design joue sur l'une des théories de fans les plus durables de Star Wars avec la créativité LEGO. Les collectionneurs apprécient beaucoup cette figurine pour son concept comique et sa subversion intelligente d'un personnage bien-aimé.",
    description_es: "Darth Jar Jar presenta a Jar Jar Binks en atuendo negro con cabeza impresa que presenta parte superior naranja oscuro, explorando la infame teoría de fans. Esta figura humorística reimagina al torpe Gungan como un Señor Sith secreto con detalles de vestuario amenazantes. El diseño juega con una de las teorías de fans más duraderas de Star Wars con creatividad LEGO. Los coleccionistas valoran altamente esta figura por su concepto cómico y subversión ingeniosa de un personaje querido."
  },
  {
    minifigure_no: 'sw1368',
    description_en: "Bounty Hunter C-3PO reimagines the protocol droid as a mercenary, creating an amusing alternate universe variant. This figure features modified droid design elements suggesting combat readiness rather than diplomatic functions. The concept playfully subverts C-3PO's traditionally peaceful nature with bounty hunter aesthetic. Collectors value this figure for its creative what-if scenario and humorous departure from canonical character traits.",
    description_de: "Kopfgeldjäger-C-3PO stellt den Protokolldroiden als Söldner neu vor und schafft eine amüsante Variante aus einem alternativen Universum. Diese Figur zeigt modifizierte Droid-Designelemente, die Kampfbereitschaft statt diplomatischer Funktionen suggerieren. Das Konzept untergräbt spielerisch C-3POs traditionell friedliche Natur mit Kopfgeldjäger-Ästhetik. Sammler schätzen diese Figur für ihr kreatives Was-wäre-wenn-Szenario und humorvolle Abweichung von kanonischen Charaktermerkmalen.",
    description_fr: "Bounty Hunter C-3PO réinvente le droïde de protocole en mercenaire, créant une variante d'univers alternatif amusante. Cette figurine présente des éléments de design de droïde modifiés suggérant une préparation au combat plutôt que des fonctions diplomatiques. Le concept subvertit de manière ludique la nature traditionnellement pacifique de C-3PO avec une esthétique de chasseur de primes. Les collectionneurs apprécient cette figurine pour son scénario créatif de type 'et si' et son écart humoristique par rapport aux traits de personnage canoniques.",
    description_es: "Cazarrecompensas C-3PO reimagina al droide de protocolo como un mercenario, creando una variante divertida de universo alternativo. Esta figura presenta elementos de diseño de droide modificados que sugieren preparación para combate en lugar de funciones diplomáticas. El concepto subvierte juguetonamente la naturaleza tradicionalmente pacífica de C-3PO con estética de cazarrecompensas. Los coleccionistas valoran esta figura por su escenario creativo de qué-pasaría-si y desviación humorística de rasgos de personaje canónicos."
  },
  {
    minifigure_no: 'sw1369',
    description_en: "Lando Calrissian appears in Skiff Guard disguise with dark brown printed legs, recreating his undercover mission to rescue Han Solo from Jabba's Palace. This figure captures Lando's tactical versatility with detailed costume printing showing his disguise. The design represents one of Return of the Jedi's memorable infiltration scenes. Collectors appreciate this variant for depicting Lando's heroic rescue mission and distinctive disguise outfit.",
    description_de: "Lando Calrissian erscheint in Skiff-Wächter-Verkleidung mit dunkelbraunen bedruckten Beinen und stellt seine verdeckte Mission zur Rettung von Han Solo aus Jabbas Palast nach. Diese Figur fängt Landos taktische Vielseitigkeit mit detailliertem Kostümdruck ein, der seine Verkleidung zeigt. Das Design repräsentiert eine der einprägsamen Infiltrationsszenen aus Die Rückkehr der Jedi-Ritter. Sammler schätzen diese Variante für die Darstellung von Landos heroischer Rettungsmission und markanter Verkleidung.",
    description_fr: "Lando Calrissian apparaît déguisé en Garde de Skiff avec des jambes imprimées marron foncé, recréant sa mission d'infiltration pour sauver Han Solo du Palais de Jabba. Cette figurine capture la polyvalence tactique de Lando avec une impression de costume détaillée montrant son déguisement. Le design représente l'une des scènes d'infiltration mémorables du Retour du Jedi. Les collectionneurs apprécient cette variante pour dépeindre la mission de sauvetage héroïque de Lando et sa tenue de déguisement distinctive.",
    description_es: "Lando Calrissian aparece en disfraz de Guardia de Skiff con piernas impresas marrón oscuro, recreando su misión encubierta para rescatar a Han Solo del Palacio de Jabba. Esta figura captura la versatilidad táctica de Lando con impresión de vestuario detallada mostrando su disfraz. El diseño representa una de las escenas de infiltración memorables de El Regreso del Jedi. Los coleccionistas aprecian esta variante por representar la misión de rescate heroica de Lando y atuendo de disfraz distintivo."
  },
  {
    minifigure_no: 'sw1370',
    description_en: "Luke Skywalker appears in a dark bluish gray Jedi robe with printed legs and hair with side part, representing his appearance as a Jedi Knight. This figure features detailed costume printing showing Luke's mature Jedi aesthetic. The dark gray robes signify Luke's progression from farm boy to legendary Jedi Master. Collectors value this variant for its refined character design and representation of Luke at the height of his Jedi powers.",
    description_de: "Luke Skywalker erscheint in einer dunkelblaugrauen Jedi-Robe mit bedruckten Beinen und Seitenscheitel-Frisur und repräsentiert sein Aussehen als Jedi-Ritter. Diese Figur zeigt detaillierten Kostümdruck, der Lukes reife Jedi-Ästhetik darstellt. Die dunkelgrauen Roben symbolisieren Lukes Entwicklung vom Farmjungen zum legendären Jedi-Meister. Sammler schätzen diese Variante für ihr raffiniertes Charakterdesign und die Darstellung von Luke auf dem Höhepunkt seiner Jedi-Kräfte.",
    description_fr: "Luke Skywalker apparaît dans une robe Jedi gris bleuâtre foncé avec des jambes imprimées et des cheveux avec raie latérale, représentant son apparence en tant que Chevalier Jedi. Cette figurine présente une impression de costume détaillée montrant l'esthétique Jedi mature de Luke. Les robes gris foncé signifient la progression de Luke de garçon de ferme à Maître Jedi légendaire. Les collectionneurs apprécient cette variante pour son design de personnage raffiné et sa représentation de Luke au sommet de ses pouvoirs Jedi.",
    description_es: "Luke Skywalker aparece en una túnica Jedi gris azulado oscuro con piernas impresas y cabello con raya al lado, representando su apariencia como Caballero Jedi. Esta figura presenta impresión de vestuario detallada mostrando la estética Jedi madura de Luke. Las túnicas gris oscuro significan la progresión de Luke de granjero a Maestro Jedi legendario. Los coleccionistas valoran esta variante por su diseño de personaje refinado y representación de Luke en el apogeo de sus poderes Jedi."
  },
  {
    minifigure_no: 'sw1371',
    description_en: "Han Solo appears in a white shirt with wrinkles printed on front and back, dark brown legs, and wavy hair, capturing his classic scoundrel appearance. This figure features enhanced printing detail showing fabric texture and wear. The wavy hair element gives Han his signature roguish look. Collectors appreciate this variant for its refined costume printing and authentic representation of the galaxy's favorite smuggler.",
    description_de: "Han Solo erscheint in einem weißen Hemd mit vorne und hinten aufgedruckten Falten, dunkelbraunen Beinen und welligem Haar und fängt sein klassisches Schurken-Aussehen ein. Diese Figur zeigt verbesserte Druckdetails, die Stofftextur und Abnutzung darstellen. Das wellige Haarelement verleiht Han seinen charakteristischen verwegenen Look. Sammler schätzen diese Variante für ihren raffinierten Kostümdruck und authentische Darstellung des Lieblingsschmuggler der Galaxie.",
    description_fr: "Han Solo apparaît dans une chemise blanche avec des plis imprimés à l'avant et à l'arrière, des jambes marron foncé et des cheveux ondulés, capturant son apparence classique de vaurien. Cette figurine présente des détails d'impression améliorés montrant la texture et l'usure du tissu. L'élément de cheveux ondulés donne à Han son look roublard signature. Les collectionneurs apprécient cette variante pour son impression de costume raffinée et sa représentation authentique du contrebandier préféré de la galaxie.",
    description_es: "Han Solo aparece en una camisa blanca con arrugas impresas en frente y atrás, piernas marrón oscuro y cabello ondulado, capturando su apariencia clásica de bribón. Esta figura presenta detalle de impresión mejorado mostrando textura de tela y desgaste. El elemento de cabello ondulado le da a Han su look pícaro característico. Los coleccionistas aprecian esta variante por su impresión de vestuario refinada y representación auténtica del contrabandista favorito de la galaxia."
  },
  {
    minifigure_no: 'sw1372',
    description_en: "Nien Nunb represents the brave Sullustan pilot and co-pilot of the Millennium Falcon during the Battle of Endor. This figure captures his distinctive alien features with detailed head mold showing characteristic Sullustan facial structure. Nien's role in destroying the second Death Star makes him a significant Rebel hero. Collectors value this figure for representing one of the Alliance's ace pilots and his crucial contribution to galactic freedom.",
    description_de: "Nien Nunb repräsentiert den mutigen Sullustaner-Piloten und Co-Piloten des Millennium Falken während der Schlacht von Endor. Diese Figur fängt seine markanten außerirdischen Merkmale mit detaillierter Kopfform ein, die die charakteristische Gesichtsstruktur der Sullustaner zeigt. Niens Rolle bei der Zerstörung des zweiten Todessterns macht ihn zu einem bedeutenden Rebellen-Helden. Sammler schätzen diese Figur für die Darstellung eines der Ass-Piloten der Allianz und seinen entscheidenden Beitrag zur galaktischen Freiheit.",
    description_fr: "Nien Nunb représente le courageux pilote Sullustan et copilote du Faucon Millenium pendant la Bataille d'Endor. Cette figurine capture ses traits aliens distinctifs avec un moule de tête détaillé montrant la structure faciale Sullustan caractéristique. Le rôle de Nien dans la destruction de la seconde Étoile de la Mort fait de lui un héros Rebelle significatif. Les collectionneurs apprécient cette figurine pour représenter l'un des pilotes as de l'Alliance et sa contribution cruciale à la liberté galactique.",
    description_es: "Nien Nunb representa al valiente piloto Sullustano y copiloto del Halcón Milenario durante la Batalla de Endor. Esta figura captura sus rasgos alienígenas distintivos con molde de cabeza detallado mostrando estructura facial Sullustana característica. El papel de Nien en destruir la segunda Estrella de la Muerte lo hace un héroe Rebelde significativo. Los coleccionistas valoran esta figura por representar a uno de los pilotos as de la Alianza y su contribución crucial a la libertad galáctica."
  },
  {
    minifigure_no: 'sw1373',
    description_en: "Imperial Crew with black cap and open mouth represents the technicians operating Death Star systems and Imperial installations. This figure features distinctive Imperial uniform details and expressive face printing. The black cap distinguishes this crew member variant from other Imperial personnel. Collectors appreciate this figure for adding variety to Imperial forces and representing the Death Star's operational crew.",
    description_de: "Imperiale Besatzung mit schwarzer Mütze und offenem Mund repräsentiert die Techniker, die Todesstern-Systeme und imperiale Anlagen betreiben. Diese Figur zeigt markante Details der imperialen Uniform und ausdrucksstarken Gesichtsdruck. Die schwarze Mütze unterscheidet diese Besatzungsmitglied-Variante von anderem imperialen Personal. Sammler schätzen diese Figur für die Erweiterung der imperialen Streitkräfte um Vielfalt und die Darstellung der Betriebsbesatzung des Todessterns.",
    description_fr: "L'Équipage Impérial avec casquette noire et bouche ouverte représente les techniciens opérant les systèmes de l'Étoile de la Mort et les installations Impériales. Cette figurine présente des détails d'uniforme Impérial distinctifs et une impression de visage expressive. La casquette noire distingue cette variante de membre d'équipage des autres personnels Impériaux. Les collectionneurs apprécient cette figurine pour ajouter de la variété aux forces Impériales et représenter l'équipage opérationnel de l'Étoile de la Mort.",
    description_es: "Tripulación Imperial con gorra negra y boca abierta representa a los técnicos operando sistemas de la Estrella de la Muerte e instalaciones Imperiales. Esta figura presenta detalles distintivos de uniforme Imperial e impresión facial expresiva. La gorra negra distingue esta variante de miembro de tripulación de otro personal Imperial. Los coleccionistas aprecian esta figura por añadir variedad a las fuerzas Imperiales y representar la tripulación operacional de la Estrella de la Muerte."
  },
  {
    minifigure_no: 'sw1374',
    description_en: "Commander Praji represents the Imperial officer who confronted the Rebels on the Tantive IV in A New Hope's opening scene. This figure captures his distinctive officer uniform with accurate rank insignia and costume details. Praji's brief but memorable appearance at the saga's beginning makes him recognizable to fans. Collectors value this figure for representing a specific character from the franchise's iconic opening sequence.",
    description_de: "Kommandant Praji repräsentiert den imperialen Offizier, der die Rebellen auf der Tantive IV in der Eröffnungsszene von Eine neue Hoffnung konfrontierte. Diese Figur fängt seine markante Offiziersuniform mit korrekten Rangabzeichen und Kostümdetails ein. Prajis kurzer, aber unvergesslicher Auftritt zu Beginn der Saga macht ihn für Fans erkennbar. Sammler schätzen diese Figur für die Darstellung eines spezifischen Charakters aus der ikonischen Eröffnungssequenz des Franchise.",
    description_fr: "Le Commandant Praji représente l'officier Impérial qui a confronté les Rebelles sur le Tantive IV dans la scène d'ouverture d'Un Nouvel Espoir. Cette figurine capture son uniforme d'officier distinctif avec des insignes de rang précis et des détails de costume. L'apparition brève mais mémorable de Praji au début de la saga le rend reconnaissable pour les fans. Les collectionneurs apprécient cette figurine pour représenter un personnage spécifique de la séquence d'ouverture iconique de la franchise.",
    description_es: "El Comandante Praji representa al oficial Imperial que confrontó a los Rebeldes en el Tantive IV en la escena de apertura de Una Nueva Esperanza. Esta figura captura su uniforme de oficial distintivo con insignias de rango precisas y detalles de vestuario. La aparición breve pero memorable de Praji al comienzo de la saga lo hace reconocible para los fans. Los coleccionistas valoran esta figura por representar un personaje específico de la secuencia de apertura icónica de la franquicia."
  },
  {
    minifigure_no: 'sw1375',
    description_en: "Imperial Navy Trooper with medium tan head represents the security forces aboard Imperial Star Destroyers and military installations. This figure features distinctive black Imperial uniform and helmet unique to Navy personnel. The medium tan skin tone adds diversity to Imperial forces representation. Collectors appreciate this trooper variant for expanding the range of Imperial military personnel and adding authenticity to Death Star and Star Destroyer displays.",
    description_de: "Imperialer Marine-Truppler mit mittelbeigem Kopf repräsentiert die Sicherheitskräfte an Bord imperialer Sternenzerstörer und militärischer Anlagen. Diese Figur zeigt markante schwarze imperiale Uniform und Helm, die einzigartig für Marinepersonal sind. Der mittelbeige Hautton fügt Vielfalt zur Darstellung imperialer Streitkräfte hinzu. Sammler schätzen diese Truppler-Variante für die Erweiterung des Spektrums imperialen Militärpersonals und das Hinzufügen von Authentizität zu Todesstern- und Sternenzerstörer-Ausstellungen.",
    description_fr: "Le Imperial Navy Trooper avec tête beige moyen représente les forces de sécurité à bord des Star Destroyers Impériaux et des installations militaires. Cette figurine présente un uniforme Impérial noir distinctif et un casque unique au personnel de la Marine. Le ton de peau beige moyen ajoute de la diversité à la représentation des forces Impériales. Les collectionneurs apprécient cette variante de trooper pour élargir la gamme du personnel militaire Impérial et ajouter de l'authenticité aux présentations d'Étoile de la Mort et de Star Destroyer.",
    description_es: "Soldado de la Marina Imperial con cabeza beige medio representa las fuerzas de seguridad a bordo de Destructores Estelares Imperiales e instalaciones militares. Esta figura presenta uniforme Imperial negro distintivo y casco único del personal de Marina. El tono de piel beige medio añade diversidad a la representación de fuerzas Imperiales. Los coleccionistas aprecian esta variante de soldado por expandir el rango de personal militar Imperial y añadir autenticidad a exhibiciones de Estrella de la Muerte y Destructor Estelar."
  }
];

async function main() {
  console.log('Starting batch save for sw1351-sw1375...');

  for (const desc of descriptions) {
    await prisma.minifigCatalog.update({
      where: { minifigure_no: desc.minifigure_no },
      data: {
        description_en: desc.description_en,
        description_de: desc.description_de,
        description_fr: desc.description_fr,
        description_es: desc.description_es,
        description_generated_at: new Date(),
        description_status: 'completed'
      }
    });
    console.log(`✓ Saved ${desc.minifigure_no}: ${desc.minifigure_no}`);
  }

  await prisma.$disconnect();
  console.log(`Batch complete! 25 minifigs saved (sw1351-sw1375).`);
}

main().catch(async (e) => {
  console.error('Error:', e);
  await prisma.$disconnect();
  process.exit(1);
});
