import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0397',
    name: 'Kithaba (Klatooinian Skiff Guard) - Dark Tan Vest',
    en: 'Kithaba is a Klatooinian skiff guard serving in Jabba the Hutt\'s criminal organization, identifiable by his distinctive canine-like alien features and dark tan vest. This 2012 minifigure captures the character\'s appearance from Return of the Jedi during the execution attempt at the Sarlacc pit on Tatooine. The figure features detailed printing showing Kithaba\'s rough mercenary attire with weapon holsters and tactical gear, along with the species\' characteristic snout-like face mold. Released in set 9496 Desert Skiff, Kithaba represents one of Jabba\'s many diverse alien henchmen that populate his desert palace. While a minor character with no dialogue, Kithaba is memorable as part of the colorful rogues gallery in Jabba\'s court. Essential for collectors building complete Jabba\'s Palace or Tatooine crime syndicate displays, this figure adds authentic alien diversity to any Star Wars villain collection.',
    de: 'Kithaba ist ein Klatooinianer-Skiff-Wächter im Dienst von Jabba dem Hutten\'s krimineller Organisation, erkennbar an seinen charakteristischen hundeähnlichen außerirdischen Merkmalen und seiner dunkelbraunen Weste. Diese 2012er-Minifigur erfasst das Erscheinungsbild der Figur aus Die Rückkehr der Jedi-Ritter während des Hinrichtungsversuchs an der Sarlacc-Grube auf Tatooine. Die Figur zeigt detaillierten Druck, der Kithaba\'s raue Söldnerkleidung mit Waffenholstern und taktischer Ausrüstung zeigt, zusammen mit der charakteristischen schnauzenähnlichen Gesichtsform der Spezies. Veröffentlicht im Set 9496 Wüstenskiff, repräsentiert Kithaba einen von Jabba\'s vielen vielfältigen außerirdischen Handlangern, die seinen Wüstenpalast bevölkern. Obwohl eine Nebenfigur ohne Dialog, ist Kithaba als Teil der bunten Schurkengalerie in Jabba\'s Hof einprägsam. Unverzichtbar für Sammler, die vollständige Jabba\'s Palast- oder Tatooine-Verbrechersyndikats-Darstellungen aufbauen, fügt diese Figur jeder Star Wars-Schurken-Sammlung authentische außerirdische Vielfalt hinzu.',
    fr: 'Kithaba est un garde de skiff Klatooinian servant dans l\'organisation criminelle de Jabba le Hutt, identifiable par ses traits extraterrestres distinctifs ressemblant à un canidé et son gilet brun foncé. Cette minifigurine de 2012 capture l\'apparence du personnage du Retour du Jedi lors de la tentative d\'exécution au puits du Sarlacc sur Tatooine. La figurine présente une impression détaillée montrant la tenue de mercenaire rugueuse de Kithaba avec des étuis d\'armes et un équipement tactique, ainsi que le moule de visage en forme de museau caractéristique de l\'espèce. Sortie dans le set 9496 Skiff du Désert, Kithaba représente l\'un des nombreux hommes de main extraterrestres divers de Jabba qui peuplent son palais du désert. Bien qu\'un personnage mineur sans dialogue, Kithaba est mémorable comme faisant partie de la galerie colorée de voyous dans la cour de Jabba. Essentielle pour les collectionneurs construisant des affichages complets du Palais de Jabba ou du syndicat du crime de Tatooine, cette figurine ajoute une diversité extraterrestre authentique à toute collection de méchants Star Wars.',
    es: 'Kithaba es un guardia de barcaza Klatooinian que sirve en la organización criminal de Jabba el Hutt, identificable por sus distintivos rasgos alienígenas caninos y chaleco marrón oscuro. Esta minifigura de 2012 captura la apariencia del personaje de El Retorno del Jedi durante el intento de ejecución en el pozo del Sarlacc en Tatooine. La figura presenta impresión detallada mostrando el atuendo de mercenario áspero de Kithaba con fundas de armas y equipo táctico, junto con el molde de cara con hocico característico de la especie. Lanzado en el set 9496 Barcaza del Desierto, Kithaba representa a uno de los muchos secuaces alienígenas diversos de Jabba que pueblan su palacio del desierto. Aunque un personaje menor sin diálogo, Kithaba es memorable como parte de la colorida galería de villanos en la corte de Jabba. Esencial para coleccionistas construyendo exhibiciones completas del Palacio de Jabba o del sindicato del crimen de Tatooine, esta figura añade diversidad alienígena auténtica a cualquier colección de villanos de Star Wars.'
  },
  {
    no: 'sw0398',
    name: 'Lando Calrissian - Skiff Guard, Tan Hips',
    en: 'Lando Calrissian, the smooth-talking gambler and former administrator of Cloud City, appears in this 2012 minifigure disguised as a skiff guard to infiltrate Jabba\'s Palace and rescue Han Solo. This version captures Lando\'s undercover appearance from Return of the Jedi wearing Tamtel Skreej\'s armor, featuring tan and brown protective gear with detailed torso printing showing armor plating and a distinctive helmet with wrap-around visor. The tan hips distinguish this variant from other releases. Lando\'s crucial role in the rescue mission showcases his loyalty to his friends and his skills as a con artist able to deceive Jabba\'s organization. Released in set 9496 Desert Skiff alongside the Sarlacc pit scene, this figure is essential for recreating one of the original trilogy\'s most action-packed sequences. A must-have for collectors of main saga heroes and fans of Lando\'s character evolution from scoundrel to hero.',
    de: 'Lando Calrissian, der wortgewandte Glücksspieler und ehemalige Administrator von Cloud City, erscheint in dieser 2012er-Minifigur als Skiff-Wächter verkleidet, um Jabba\'s Palast zu infiltrieren und Han Solo zu retten. Diese Version erfasst Lando\'s Undercover-Erscheinungsbild aus Die Rückkehr der Jedi-Ritter in Tamtel Skreej\'s Rüstung, mit sandfarbener und brauner Schutzausrüstung mit detailliertem Torso-Druck, der Rüstungsplatten zeigt, und einem charakteristischen Helm mit umlaufendem Visier. Die sandfarbenen Hüften unterscheiden diese Variante von anderen Veröffentlichungen. Lando\'s entscheidende Rolle in der Rettungsmission zeigt seine Loyalität gegenüber seinen Freunden und seine Fähigkeiten als Betrüger, der Jabba\'s Organisation täuschen kann. Veröffentlicht im Set 9496 Wüstenskiff neben der Sarlacc-Gruben-Szene, ist diese Figur unverzichtbar für die Nachstellung einer der actionreichsten Sequenzen der ursprünglichen Trilogie. Ein Muss für Sammler der Hauptsaga-Helden und Fans von Lando\'s Charakterentwicklung vom Schurken zum Helden.',
    fr: 'Lando Calrissian, le joueur charmeur et ancien administrateur de la Cité des Nuages, apparaît dans cette minifigurine de 2012 déguisé en garde de skiff pour infiltrer le Palais de Jabba et sauver Han Solo. Cette version capture l\'apparence sous couverture de Lando du Retour du Jedi portant l\'armure de Tamtel Skreej, avec un équipement de protection beige et brun avec une impression de torse détaillée montrant des plaques d\'armure et un casque distinctif avec visière enveloppante. Les hanches beiges distinguent cette variante des autres sorties. Le rôle crucial de Lando dans la mission de sauvetage démontre sa loyauté envers ses amis et ses compétences d\'arnaqueur capable de tromper l\'organisation de Jabba. Sortie dans le set 9496 Skiff du Désert aux côtés de la scène du puits du Sarlacc, cette figurine est essentielle pour recréer l\'une des séquences les plus pleines d\'action de la trilogie originale. Un incontournable pour les collectionneurs de héros de la saga principale et les fans de l\'évolution du personnage de Lando de voyou à héros.',
    es: 'Lando Calrissian, el jugador de labia suave y ex administrador de Ciudad Nube, aparece en esta minifigura de 2012 disfrazado como guardia de barcaza para infiltrarse en el Palacio de Jabba y rescatar a Han Solo. Esta versión captura la apariencia encubierta de Lando de El Retorno del Jedi vistiendo la armadura de Tamtel Skreej, con equipo protector beige y marrón con impresión de torso detallada mostrando placas de armadura y un casco distintivo con visor envolvente. Las caderas beige distinguen esta variante de otros lanzamientos. El papel crucial de Lando en la misión de rescate muestra su lealtad a sus amigos y sus habilidades como estafador capaz de engañar a la organización de Jabba. Lanzado en el set 9496 Barcaza del Desierto junto a la escena del pozo del Sarlacc, esta figura es esencial para recrear una de las secuencias más llenas de acción de la trilogía original. Imprescindible para coleccionistas de héroes de la saga principal y fans de la evolución del personaje de Lando de bribón a héroe.'
  },
  {
    no: 'sw0399',
    name: 'Rebel Pilot X-wing',
    en: 'This generic Rebel Alliance X-wing pilot represents the brave starfighter pilots who served in countless battles against the Galactic Empire throughout the original trilogy. The 2012 minifigure features the iconic orange flight suit with detailed torso printing showing life support systems, flight harness, and rank insignia typical of Rebel pilots. The white helmet with orange markings and transparent visor completes the classic Rebel pilot look. While not representing a specific named character, this pilot figure is essential for crewing the numerous X-wing starfighters in collectors\' fleets and recreating squadron formations from pivotal battles like Yavin, Hoth, and Endor. The universal pilot design makes it perfect for army building and populating Rebel base displays. Released in set 9493 X-wing Starfighter, this figure captures the heroic everyday soldiers of the Rebellion who risked everything to defeat tyranny.',
    de: 'Dieser generische Rebellen-Allianz-X-Wing-Pilot repräsentiert die mutigen Sternenjäger-Piloten, die in unzähligen Schlachten gegen das Galaktische Imperium während der ursprünglichen Trilogie dienten. Die 2012er-Minifigur zeigt den ikonischen orangefarbenen Fluganzug mit detailliertem Torso-Druck, der Lebenserhaltungssysteme, Fluggeschirr und Rangabzeichen zeigt, die typisch für Rebellenpiloten sind. Der weiße Helm mit orangefarbenen Markierungen und transparentem Visier vervollständigt den klassischen Rebellenpiloten-Look. Obwohl sie keine bestimmte benannte Figur repräsentiert, ist diese Pilotenfigur unverzichtbar für die Besatzung der zahlreichen X-Wing-Sternenjäger in Sammlerflotten und die Nachstellung von Staffelformationen aus entscheidenden Schlachten wie Yavin, Hoth und Endor. Das universelle Pilotendesign macht sie perfekt für Armeeaufbau und die Bevölkerung von Rebellenbasen-Darstellungen. Veröffentlicht im Set 9493 X-Wing Starfighter, erfasst diese Figur die heroischen Alltagssoldaten der Rebellion, die alles riskierten, um Tyrannei zu besiegen.',
    fr: 'Ce pilote générique de X-wing de l\'Alliance Rebelle représente les courageux pilotes de chasseurs stellaires qui ont servi dans d\'innombrables batailles contre l\'Empire Galactique tout au long de la trilogie originale. La minifigurine de 2012 présente la combinaison de vol orange iconique avec une impression de torse détaillée montrant les systèmes de maintien de vie, le harnais de vol et les insignes de rang typiques des pilotes Rebelles. Le casque blanc avec des marquages orange et une visière transparente complète le look classique du pilote Rebelle. Bien qu\'elle ne représente pas un personnage nommé spécifique, cette figurine de pilote est essentielle pour équiper les nombreux chasseurs stellaires X-wing dans les flottes des collectionneurs et recréer des formations d\'escadrons de batailles cruciales comme Yavin, Hoth et Endor. Le design de pilote universel la rend parfaite pour la construction d\'armées et le peuplement d\'affichages de bases Rebelles. Sortie dans le set 9493 Chasseur stellaire X-wing, cette figurine capture les soldats héroïques du quotidien de la Rébellion qui ont tout risqué pour vaincre la tyrannie.',
    es: 'Este piloto genérico de Ala-X de la Alianza Rebelde representa a los valientes pilotos de cazas estelares que sirvieron en innumerables batallas contra el Imperio Galáctico a lo largo de la trilogía original. La minifigura de 2012 presenta el icónico traje de vuelo naranja con impresión de torso detallada mostrando sistemas de soporte vital, arnés de vuelo e insignias de rango típicas de los pilotos Rebeldes. El casco blanco con marcas naranjas y visera transparente completa el look clásico del piloto Rebelde. Aunque no representa a un personaje nombrado específico, esta figura de piloto es esencial para tripular los numerosos cazas estelares Ala-X en las flotas de coleccionistas y recrear formaciones de escuadrones de batallas cruciales como Yavin, Hoth y Endor. El diseño de piloto universal la hace perfecta para construcción de ejércitos y poblar exhibiciones de bases Rebeldes. Lanzada en el set 9493 Caza Estelar Ala-X, esta figura captura a los heroicos soldados cotidianos de la Rebelión que arriesgaron todo para derrotar la tiranía.'
  },
  {
    no: 'sw0400',
    name: 'Lobot - Light Bluish Gray Uniform, Light Nougat Head, Black Eyebrows',
    en: 'Lobot, the cyborg chief administrative aide to Lando Calrissian at Cloud City, appears in this 2012 minifigure with his distinctive cybernetic headband implant that interfaces directly with the city\'s central computer. This version features light bluish gray uniform representing his administrative role at Bespin\'s mining facility, with detailed torso printing showing utilitarian work attire. The light nougat head piece includes black eyebrows and printing depicting the wraparound communication device that augments his cognitive abilities while limiting his emotional expression. Released in set 10123 Cloud City (2013 re-release), Lobot is a relatively rare character despite his memorable appearance in The Empire Strikes Back helping the heroes escape. His unique cyborg status and loyal friendship to Lando make him an essential figure for Cloud City displays and collectors of supporting Original Trilogy characters.',
    de: 'Lobot, der kybernetische Chef-Verwaltungsassistent von Lando Calrissian in Cloud City, erscheint in dieser 2012er-Minifigur mit seinem charakteristischen kybernetischen Stirnband-Implantat, das direkt mit dem Zentralcomputer der Stadt verbunden ist. Diese Version zeigt eine hellblaugraue Uniform, die seine Verwaltungsrolle in Bespin\'s Bergbauanlage repräsentiert, mit detailliertem Torso-Druck, der zweckmäßige Arbeitskleidung zeigt. Das hellbeige Kopfteil enthält schwarze Augenbrauen und Druck, der das umlaufende Kommunikationsgerät darstellt, das seine kognitiven Fähigkeiten verstärkt, während es seinen emotionalen Ausdruck begrenzt. Veröffentlicht im Set 10123 Cloud City (2013-Neuauflage), ist Lobot trotz seines einprägsamen Auftritts in Das Imperium schlägt zurück, als er den Helden bei der Flucht hilft, eine relativ seltene Figur. Sein einzigartiger Cyborg-Status und loyale Freundschaft zu Lando machen ihn zu einer unverzichtbaren Figur für Cloud City-Darstellungen und Sammler unterstützender Original-Trilogie-Charaktere.',
    fr: 'Lobot, l\'aide administratif en chef cyborg de Lando Calrissian à la Cité des Nuages, apparaît dans cette minifigurine de 2012 avec son bandeau frontal cybernétique distinctif qui s\'interface directement avec l\'ordinateur central de la ville. Cette version présente un uniforme gris bleuté clair représentant son rôle administratif dans l\'installation minière de Bespin, avec une impression de torse détaillée montrant une tenue de travail utilitaire. La pièce de tête noisette claire comprend des sourcils noirs et une impression représentant le dispositif de communication enveloppant qui augmente ses capacités cognitives tout en limitant son expression émotionnelle. Sortie dans le set 10123 Cité des Nuages (réédition 2013), Lobot est un personnage relativement rare malgré son apparition mémorable dans L\'Empire Contre-Attaque aidant les héros à s\'échapper. Son statut de cyborg unique et son amitié loyale envers Lando en font une figurine essentielle pour les affichages de la Cité des Nuages et les collectionneurs de personnages secondaires de la Trilogie Originale.',
    es: 'Lobot, el asistente administrativo jefe cyborg de Lando Calrissian en Ciudad Nube, aparece en esta minifigura de 2012 con su distintivo implante de banda frontal cibernética que se conecta directamente con la computadora central de la ciudad. Esta versión presenta uniforme gris azulado claro representando su papel administrativo en la instalación minera de Bespin, con impresión de torso detallada mostrando atuendo de trabajo utilitario. La pieza de cabeza color crema claro incluye cejas negras e impresión representando el dispositivo de comunicación envolvente que aumenta sus capacidades cognitivas mientras limita su expresión emocional. Lanzado en el set 10123 Ciudad Nube (relanzamiento 2013), Lobot es un personaje relativamente raro a pesar de su memorable aparición en El Imperio Contraataca ayudando a los héroes a escapar. Su estatus único de cyborg y amistad leal con Lando lo convierten en una figura esencial para exhibiciones de Ciudad Nube y coleccionistas de personajes secundarios de la Trilogía Original.'
  },
  {
    no: 'sw0401',
    name: 'Imperial AT-ST Pilot / Driver (Plain Helmet, Dual Sided Head)',
    en: 'The Imperial AT-ST pilot operates the Empire\'s two-legged scout walker, providing ground support and reconnaissance during battles on Endor and other contested worlds. This 2012 minifigure features the distinctive gray uniform with black chest armor and detailed torso printing showing Imperial rank insignia and communication equipment. The plain gray helmet without markings represents standard scout walker crew, while the dual-sided head piece offers display versatility with different facial expressions. AT-ST pilots require specialized training to operate the agile but vulnerable walkers that supplement the massive AT-AT forces. Released in set 9679 AT-ST and Endor, this pilot is essential for crewing the iconic two-legged walker that plays a memorable role in the Battle of Endor. Perfect for Imperial army building and collectors recreating ground assault formations from Return of the Jedi.',
    de: 'Der imperiale AT-ST-Pilot bedient den zweibeinigen Aufklärungs-Walker des Imperiums und bietet Bodenunterstützung und Aufklärung während Schlachten auf Endor und anderen umkämpften Welten. Diese 2012er-Minifigur zeigt die charakteristische graue Uniform mit schwarzer Brustrüstung und detailliertem Torso-Druck, der imperiale Rangabzeichen und Kommunikationsausrüstung zeigt. Der schlichte graue Helm ohne Markierungen repräsentiert Standard-Scout-Walker-Besatzung, während das doppelseitige Kopfteil Darstellungsvielseitigkeit mit verschiedenen Gesichtsausdrücken bietet. AT-ST-Piloten benötigen spezialisierte Ausbildung, um die wendigen, aber verwundbaren Walker zu bedienen, die die massiven AT-AT-Streitkräfte ergänzen. Veröffentlicht im Set 9679 AT-ST und Endor, ist dieser Pilot unverzichtbar für die Besatzung des ikonischen zweibeinigen Walkers, der eine einprägsame Rolle in der Schlacht von Endor spielt. Perfekt für imperialen Armeeaufbau und Sammler, die Bodenangriffs-Formationen aus Die Rückkehr der Jedi-Ritter nachstellen.',
    fr: 'Le pilote impérial d\'AT-ST opère le marcheur éclaireur bipède de l\'Empire, fournissant un soutien au sol et de la reconnaissance pendant les batailles sur Endor et d\'autres mondes contestés. Cette minifigurine de 2012 présente l\'uniforme gris distinctif avec une armure de poitrine noire et une impression de torse détaillée montrant des insignes de rang impériaux et de l\'équipement de communication. Le casque gris uni sans marquages représente l\'équipage standard de marcheur éclaireur, tandis que la pièce de tête à double face offre une polyvalence d\'affichage avec différentes expressions faciales. Les pilotes d\'AT-ST nécessitent une formation spécialisée pour opérer les marcheurs agiles mais vulnérables qui complètent les forces massives d\'AT-AT. Sortie dans le set 9679 AT-ST et Endor, ce pilote est essentiel pour équiper le marcheur bipède iconique qui joue un rôle mémorable dans la Bataille d\'Endor. Parfait pour la construction d\'armée impériale et les collectionneurs recréant des formations d\'assaut au sol du Retour du Jedi.',
    es: 'El piloto imperial de AT-ST opera el caminante explorador bípedo del Imperio, proporcionando apoyo terrestre y reconocimiento durante batallas en Endor y otros mundos disputados. Esta minifigura de 2012 presenta el distintivo uniforme gris con armadura de pecho negra e impresión de torso detallada mostrando insignias de rango imperiales y equipo de comunicación. El casco gris liso sin marcas representa a la tripulación estándar de caminante explorador, mientras que la pieza de cabeza de doble cara ofrece versatilidad de exhibición con diferentes expresiones faciales. Los pilotos de AT-ST requieren entrenamiento especializado para operar los ágiles pero vulnerables caminantes que complementan las fuerzas masivas de AT-AT. Lanzado en el set 9679 AT-ST y Endor, este piloto es esencial para tripular el icónico caminante bípedo que juega un papel memorable en la Batalla de Endor. Perfecto para construcción de ejército Imperial y coleccionistas recreando formaciones de asalto terrestre de El Retorno del Jedi.'
  },
  {
    no: 'sw0402',
    name: 'Jabba the Hutt - Olive Green, Tan Face, Dark Tan Wrinkles',
    en: 'Jabba the Hutt, the notorious Hutt crime lord who controls the Tatooine underworld, appears in this 2012 large-scale figure representing one of the Star Wars saga\'s most iconic villains. This substantial 46-gram piece captures Jabba\'s slug-like alien form in olive green with tan face and dark tan wrinkle details, featuring his distinctive bulbous eyes, wide mouth, and corpulent body. The detailed molding and printing recreate Jabba\'s repulsive yet memorable appearance from Return of the Jedi where he holds Han Solo frozen in carbonite and attempts to execute Luke Skywalker. Released in set 9516 Jabba\'s Palace, this figure serves as the centerpiece for the elaborate palace diorama. As one of Star Wars\' most recognizable villains despite being a giant slug, Jabba is essential for any serious collection, particularly for fans of the Original Trilogy\'s Tatooine storyline and crime syndicate themes.',
    de: 'Jabba der Hutte, der berüchtigte Hutten-Verbrecherlord, der die Unterwelt von Tatooine kontrolliert, erscheint in dieser großformatigen 2012er-Figur und repräsentiert einen der ikonischsten Schurken der Star Wars-Saga. Dieses substantielle 46-Gramm-Stück erfasst Jabba\'s schneckenähnliche außerirdische Form in olivgrün mit sandfarbenem Gesicht und dunkelbraunen Faltendetails, mit seinen charakteristischen knolligen Augen, breitem Mund und korpulentem Körper. Die detaillierte Formgebung und der Druck bilden Jabba\'s abstoßendes, aber einprägsames Erscheinungsbild aus Die Rückkehr der Jedi-Ritter nach, wo er Han Solo in Karbonit eingefroren hält und versucht, Luke Skywalker hinzurichten. Veröffentlicht im Set 9516 Jabba\'s Palast, dient diese Figur als Herzstück für das aufwendige Palast-Diorama. Als einer der bekanntesten Star Wars-Schurken, obwohl er eine riesige Schnecke ist, ist Jabba für jede ernsthafte Sammlung unverzichtbar, besonders für Fans der Tatooine-Handlung der Original-Trilogie und Verbrechersyndikats-Themen.',
    fr: 'Jabba le Hutt, le notoire seigneur du crime Hutt qui contrôle la pègre de Tatooine, apparaît dans cette figurine à grande échelle de 2012 représentant l\'un des méchants les plus iconiques de la saga Star Wars. Cette pièce substantielle de 46 grammes capture la forme extraterrestre en limace de Jabba en vert olive avec un visage beige et des détails de rides beiges foncées, avec ses yeux bulbeux distinctifs, sa large bouche et son corps corpulent. Le moulage et l\'impression détaillés recréent l\'apparence répugnante mais mémorable de Jabba du Retour du Jedi où il retient Han Solo congelé dans la carbonite et tente d\'exécuter Luke Skywalker. Sortie dans le set 9516 Palais de Jabba, cette figurine sert de pièce maîtresse pour le diorama élaboré du palais. En tant que l\'un des méchants Star Wars les plus reconnaissables malgré le fait d\'être une limace géante, Jabba est essentiel pour toute collection sérieuse, particulièrement pour les fans de l\'intrigue Tatooine de la Trilogie Originale et des thèmes de syndicat du crime.',
    es: 'Jabba el Hutt, el notorio señor del crimen Hutt que controla el submundo de Tatooine, aparece en esta figura a gran escala de 2012 representando a uno de los villanos más icónicos de la saga Star Wars. Esta pieza sustancial de 46 gramos captura la forma alienígena de babosa de Jabba en verde oliva con rostro beige y detalles de arrugas beige oscuro, con sus distintivos ojos bulbosos, boca ancha y cuerpo corpulento. El moldeado e impresión detallados recrean la apariencia repulsiva pero memorable de Jabba de El Retorno del Jedi donde mantiene a Han Solo congelado en carbonita e intenta ejecutar a Luke Skywalker. Lanzada en el set 9516 Palacio de Jabba, esta figura sirve como pieza central para el elaborado diorama del palacio. Como uno de los villanos de Star Wars más reconocibles a pesar de ser una babosa gigante, Jabba es esencial para cualquier colección seria, particularmente para fans de la trama de Tatooine de la Trilogía Original y temas de sindicato del crimen.'
  }
];

async function saveBatch() {
  console.log(`Processing ${batch.length} minifigs...\n`);

  for (const minifig of batch) {
    try {
      await prisma.minifigCatalog.update({
        where: { minifigure_no: minifig.no },
        data: {
          description_en: minifig.en,
          description_de: minifig.de,
          description_fr: minifig.fr,
          description_es: minifig.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        }
      });
      console.log(`✅ Saved ${minifig.no}: ${minifig.name}`);
    } catch (error: any) {
      console.error(`❌ Error saving ${minifig.no}: ${error.message}`);
    }
  }

  console.log(`\n✨ Batch complete!\n`);
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
