import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasources: {
    db: {
      url: process.env.DATABASE_URL,
    },
  },
});

interface MinifigDescription {
  minifigure_no: string;
  description_en: string;
  description_de: string;
  description_fr: string;
  description_es: string;
}

const descriptions: MinifigDescription[] = [
  {
    minifigure_no: 'sw0932',
    description_en: 'Jon "Dutch" Vander, Gold Leader of the Y-wing squadron, was a veteran Rebel pilot who led the crucial attack run on the first Death Star at the Battle of Yavin. This minifigure authentically recreates his distinctive orange flight suit with printed leg details and specialized headset equipment used for coordinating squadron tactics. As one of the few named pilots from A New Hope, Dutch represents an important piece of classic Star Wars history. A valuable addition for collectors building the complete Yavin briefing room scene.',
    description_de: 'Jon „Dutch" Vander, Gold Leader des Y-Flügler-Geschwaders, war ein erfahrener Rebellenpilot, der den entscheidenden Angriffsflug auf den ersten Todesstern in der Schlacht von Yavin anführte. Diese Minifigur stellt authentisch seinen markanten orangefarbenen Fluganzug mit bedruckten Beindetails und spezieller Headset-Ausrüstung nach, die zur Koordinierung der Geschwadertaktiken verwendet wurde. Als einer der wenigen namentlich bekannten Piloten aus Eine neue Hoffnung repräsentiert Dutch ein wichtiges Stück klassischer Star Wars-Geschichte. Eine wertvolle Ergänzung für Sammler, die die vollständige Yavin-Briefingszene aufbauen.',
    description_fr: 'Jon « Dutch » Vander, Gold Leader de l\'escadron Y-wing, était un pilote rebelle vétéran qui a mené l\'attaque cruciale contre la première Étoile de la Mort lors de la bataille de Yavin. Cette figurine recrée authentiquement sa combinaison de vol orange distinctive avec des détails imprimés sur les jambes et un équipement d\'écouteurs spécialisé utilisé pour coordonner les tactiques d\'escadron. En tant que l\'un des rares pilotes nommés de Un nouvel espoir, Dutch représente une pièce importante de l\'histoire classique de Star Wars. Un ajout précieux pour les collectionneurs construisant la scène complète de la salle de briefing de Yavin.',
    description_es: 'Jon "Dutch" Vander, Líder Dorado del escuadrón Y-wing, fue un veterano piloto rebelde que lideró el crucial ataque contra la primera Estrella de la Muerte en la Batalla de Yavin. Esta minifigura recrea auténticamente su distintivo traje de vuelo naranja con detalles impresos en las piernas y equipo de auriculares especializado usado para coordinar tácticas de escuadrón. Como uno de los pocos pilotos nombrados de Una nueva esperanza, Dutch representa una pieza importante de la historia clásica de Star Wars. Una valiosa adición para coleccionistas que construyen la escena completa de la sala de briefing de Yavin.'
  },
  {
    minifigure_no: 'sw0933',
    description_en: 'R2-BHD is a unique astromech droid serving aboard Rebel Y-wing starfighters during the Battle of Yavin, distinguished by its rare dark bluish gray body color scheme. This droid variant represents the diverse astromech units that supported the Rebel Alliance\'s starfighter operations. Its distinctive coloring makes it stand out among the more common R2 and R5 units in collectors\' displays. An essential piece for completing authentic Y-wing fighter builds and squadron collections.',
    description_de: 'R2-BHD ist ein einzigartiger Astromech-Droide, der während der Schlacht von Yavin an Bord von Y-Flügler-Raumjägern der Rebellen diente und sich durch sein seltenes dunkel-bläulich-graues Farbschema auszeichnet. Diese Droiden-Variante repräsentiert die vielfältigen Astromech-Einheiten, die die Raumjägeroperationen der Rebellenallianz unterstützten. Seine markante Färbung lässt ihn unter den häufigeren R2- und R5-Einheiten in Sammlerausstellungen hervorstechen. Ein unverzichtbares Stück für den Bau authentischer Y-Flügler und Geschwadersammlungen.',
    description_fr: 'R2-BHD est un droïde astromech unique servant à bord des chasseurs Y-wing rebelles lors de la bataille de Yavin, distingué par son rare schéma de couleurs gris bleu foncé. Cette variante de droïde représente les diverses unités astromech qui soutenaient les opérations de chasseurs stellaires de l\'Alliance rebelle. Sa coloration distinctive le fait ressortir parmi les unités R2 et R5 plus courantes dans les collections. Une pièce essentielle pour compléter les constructions authentiques de chasseurs Y-wing et les collections d\'escadrons.',
    description_es: 'R2-BHD es un droide astromecánico único que sirve a bordo de cazas estelares Y-wing rebeldes durante la Batalla de Yavin, distinguido por su raro esquema de color gris azulado oscuro. Esta variante de droide representa las diversas unidades astromecánicas que apoyaron las operaciones de cazas estelares de la Alianza Rebelde. Su coloración distintiva lo hace destacar entre las unidades R2 y R5 más comunes en las colecciones. Una pieza esencial para completar construcciones auténticas de cazas Y-wing y colecciones de escuadrones.'
  },
  {
    minifigure_no: 'sw0934',
    description_en: 'This Han Solo variant depicts the legendary smuggler in Imperial Mudtrooper armor during his mission to Mimban in Solo: A Star Wars Story. The detailed printing captures the battle-worn appearance of combat in the muddy trenches, representing a pivotal moment when Han was still serving in the Imperial military. This disguise helped Han and his companions infiltrate Imperial ranks during the Kessel heist operation. A must-have for collectors of the Solo movie storyline and Han\'s character evolution.',
    description_de: 'Diese Han Solo-Variante zeigt den legendären Schmuggler in imperialer Mudtrooper-Rüstung während seiner Mission nach Mimban in Solo: A Star Wars Story. Der detaillierte Druck erfasst das kampferprobte Erscheinungsbild des Gefechts in den schlammigen Schützengräben und repräsentiert einen entscheidenden Moment, als Han noch im imperialen Militär diente. Diese Verkleidung half Han und seinen Gefährten, imperiale Ränge während der Kessel-Heist-Operation zu infiltrieren. Ein Muss für Sammler der Solo-Filmhandlung und Hans Charakterentwicklung.',
    description_fr: 'Cette variante de Han Solo dépeint le légendaire contrebandier en armure de Mudtrooper impérial lors de sa mission sur Mimban dans Solo: A Star Wars Story. L\'impression détaillée capture l\'apparence usée par le combat dans les tranchées boueuses, représentant un moment pivot lorsque Han servait encore dans l\'armée impériale. Ce déguisement a aidé Han et ses compagnons à infiltrer les rangs impériaux pendant l\'opération de braquage de Kessel. Un incontournable pour les collectionneurs de l\'histoire du film Solo et de l\'évolution du personnage de Han.',
    description_es: 'Esta variante de Han Solo representa al legendario contrabandista con armadura de Mudtrooper Imperial durante su misión a Mimban en Han Solo: Una Historia de Star Wars. La impresión detallada captura la apariencia desgastada por el combate en las trincheras fangosas, representando un momento crucial cuando Han aún servía en el ejército Imperial. Este disfraz ayudó a Han y sus compañeros a infiltrarse en las filas imperiales durante la operación del atraco de Kessel. Imprescindible para coleccionistas de la historia de la película Solo y la evolución del personaje de Han.'
  },
  {
    minifigure_no: 'sw0935',
    description_en: 'The Kessel Mine Worker represents the enslaved laborers forced to extract valuable coaxium in the brutal spice mines of Kessel, as seen in Solo: A Star Wars Story. This figure\'s worn and weathered appearance reflects the harsh conditions and dangerous work in one of the galaxy\'s most notorious mining operations. The character design highlights the darker side of the Empire\'s industrial machine and the exploitation of workers. An important piece for building the complete Kessel mining facility and understanding the criminal underworld of the Star Wars universe.',
    description_de: 'Der Kessel-Minenarbeiter repräsentiert die versklavten Arbeiter, die gezwungen wurden, wertvolles Coaxium in den brutalen Gewürzminen von Kessel zu fördern, wie in Solo: A Star Wars Story zu sehen. Das abgenutzte und verwitterte Erscheinungsbild dieser Figur spiegelt die harten Bedingungen und gefährlichen Arbeiten in einer der berüchtigtsten Bergbauoperationen der Galaxis wider. Das Charakterdesign hebt die dunklere Seite der industriellen Maschinerie des Imperiums und die Ausbeutung der Arbeiter hervor. Ein wichtiges Stück für den Bau der vollständigen Kessel-Bergbauanlage und das Verständnis der kriminellen Unterwelt des Star Wars-Universums.',
    description_fr: 'Le travailleur de mine de Kessel représente les ouvriers esclaves forcés d\'extraire le précieux coaxium dans les mines d\'épices brutales de Kessel, comme on le voit dans Solo: A Star Wars Story. L\'apparence usée et altérée de cette figurine reflète les conditions difficiles et le travail dangereux dans l\'une des opérations minières les plus notoires de la galaxie. Le design du personnage met en évidence le côté sombre de la machine industrielle de l\'Empire et l\'exploitation des travailleurs. Une pièce importante pour construire l\'installation minière complète de Kessel et comprendre le monde criminel de l\'univers Star Wars.',
    description_es: 'El trabajador de minas de Kessel representa a los trabajadores esclavizados forzados a extraer valioso coaxium en las brutales minas de especias de Kessel, como se ve en Han Solo: Una Historia de Star Wars. La apariencia desgastada y deteriorada de esta figura refleja las duras condiciones y el trabajo peligroso en una de las operaciones mineras más notorias de la galaxia. El diseño del personaje resalta el lado oscuro de la maquinaria industrial del Imperio y la explotación de trabajadores. Una pieza importante para construir la instalación minera completa de Kessel y comprender el submundo criminal del universo Star Wars.'
  },
  {
    minifigure_no: 'sw0936',
    description_en: '2-1B is the dedicated medical droid who treated Luke Skywalker\'s injuries on Hoth and performed his cybernetic hand replacement after Cloud City. This version features authentic dotted badge printing and weathered peeling paint details in tan, reflecting years of service in Rebel medical facilities. As one of the most skilled surgical droids in the galaxy, 2-1B\'s advanced programming and gentle bedside manner made it invaluable to the Rebellion. Essential for collectors building the Hoth medical bay scene and Rebel base environments.',
    description_de: '2-1B ist der engagierte Medizindroide, der Luke Skywalkers Verletzungen auf Hoth behandelte und seine kybernetische Handersetzung nach Cloud City durchführte. Diese Version zeigt authentische gepunktete Abzeichendrucke und verwitterte abblätternde Farbdetails in Hellbraun, die Jahre des Dienstes in Rebellen-Medizineinrichtungen widerspiegeln. Als einer der qualifiziertesten chirurgischen Droiden der Galaxis machten 2-1Bs fortschrittliche Programmierung und sanfte Art am Krankenbett ihn für die Rebellion unverzichtbar. Unverzichtbar für Sammler, die die Hoth-Krankenstation und Rebellenstützpunktumgebungen aufbauen.',
    description_fr: '2-1B est le droïde médical dévoué qui a soigné les blessures de Luke Skywalker sur Hoth et a effectué le remplacement de sa main cybernétique après Cloud City. Cette version présente une impression authentique de badge à pois et des détails de peinture écaillée vieillie en beige, reflétant des années de service dans les installations médicales rebelles. En tant que l\'un des droïdes chirurgicaux les plus qualifiés de la galaxie, la programmation avancée et les manières douces au chevet des patients de 2-1B l\'ont rendu inestimable pour la Rébellion. Essentiel pour les collectionneurs construisant la scène de l\'infirmerie de Hoth et les environnements de base rebelle.',
    description_es: '2-1B es el dedicado droide médico que trató las heridas de Luke Skywalker en Hoth y realizó el reemplazo de su mano cibernética después de Ciudad Nube. Esta versión presenta impresión auténtica de insignia con puntos y detalles de pintura descascarada y desgastada en color bronceado, reflejando años de servicio en instalaciones médicas rebeldes. Como uno de los droides quirúrgicos más hábiles de la galaxia, la programación avanzada y los modales gentiles de 2-1B lo hicieron invaluable para la Rebelión. Esencial para coleccionistas que construyen la escena de la bahía médica de Hoth y entornos de bases rebeldes.'
  },
  {
    minifigure_no: 'sw0937',
    description_en: 'R5-A2 is an astromech droid serving aboard Rebel starfighters, representing the variety of R5 units deployed throughout the Alliance fleet. These shorter, more compact astromech droids were designed for specialized repair and navigation tasks in confined cockpit spaces. The distinctive red and white color scheme makes this droid instantly recognizable among astromech collections. A great addition for collectors building diverse Rebel hangar displays and starfighter support crews.',
    description_de: 'R5-A2 ist ein Astromech-Droide, der an Bord von Rebellen-Raumjägern dient und die Vielfalt der in der gesamten Allianzflotte eingesetzten R5-Einheiten repräsentiert. Diese kürzeren, kompakteren Astromech-Droiden wurden für spezialisierte Reparatur- und Navigationsaufgaben in beengten Cockpitbereichen entwickelt. Das markante rot-weiße Farbschema macht diesen Droiden unter Astromech-Sammlungen sofort erkennbar. Eine großartige Ergänzung für Sammler, die vielfältige Rebellen-Hangar-Displays und Raumjäger-Supportcrews aufbauen.',
    description_fr: 'R5-A2 est un droïde astromech servant à bord des chasseurs stellaires rebelles, représentant la variété des unités R5 déployées dans toute la flotte de l\'Alliance. Ces droïdes astromech plus courts et plus compacts ont été conçus pour des tâches de réparation et de navigation spécialisées dans des espaces de cockpit confinés. Le schéma de couleurs rouge et blanc distinctif rend ce droïde instantanément reconnaissable parmi les collections d\'astromech. Un excellent ajout pour les collectionneurs construisant diverses présentations de hangars rebelles et d\'équipes de soutien de chasseurs stellaires.',
    description_es: 'R5-A2 es un droide astromecánico que sirve a bordo de cazas estelares rebeldes, representando la variedad de unidades R5 desplegadas en toda la flota de la Alianza. Estos droides astromecánicos más cortos y compactos fueron diseñados para tareas especializadas de reparación y navegación en espacios de cabina confinados. El distintivo esquema de colores rojo y blanco hace que este droide sea instantáneamente reconocible entre colecciones de astromecánicos. Una gran adición para coleccionistas que construyen diversas exhibiciones de hangares rebeldes y equipos de soporte de cazas estelares.'
  },
  {
    minifigure_no: 'sw0938',
    description_en: 'The RA-7 protocol droid, known ominously as the "Death Star Droid," served aboard the Empire\'s ultimate weapon performing menial tasks and surveillance. This pearl dark gray variant captures the sinister appearance of these droids, whose insect-like photoreceptors gave them an unsettling presence. Despite being protocol droids, RA-7 units were often modified for espionage and security functions within Imperial facilities. A valuable piece for collectors building Death Star interior scenes and Imperial administrative areas.',
    description_de: 'Der RA-7-Protokolldroide, unheilvoll als „Todesstern-Droide" bekannt, diente an Bord der ultimativen Waffe des Imperiums und führte niedere Aufgaben und Überwachung durch. Diese perlmuttfarbene dunkelgraue Variante erfasst das düstere Erscheinungsbild dieser Droiden, deren insektenähnliche Photorezeptoren ihnen eine beunruhigende Präsenz verliehen. Obwohl sie Protokolldroiden waren, wurden RA-7-Einheiten oft für Spionage- und Sicherheitsfunktionen innerhalb imperialer Einrichtungen modifiziert. Ein wertvolles Stück für Sammler, die Todesstern-Innenszenen und imperiale Verwaltungsbereiche aufbauen.',
    description_fr: 'Le droïde de protocole RA-7, connu de manière inquiétante comme le « Droïde de l\'Étoile de la Mort », servait à bord de l\'arme ultime de l\'Empire en effectuant des tâches subalternes et de surveillance. Cette variante gris foncé nacré capture l\'apparence sinistre de ces droïdes, dont les photorécepteurs en forme d\'insectes leur donnaient une présence troublante. Bien qu\'étant des droïdes de protocole, les unités RA-7 étaient souvent modifiées pour des fonctions d\'espionnage et de sécurité dans les installations impériales. Une pièce précieuse pour les collectionneurs construisant des scènes intérieures de l\'Étoile de la Mort et des zones administratives impériales.',
    description_es: 'El droide de protocolo RA-7, conocido ominosamente como el "Droide de la Estrella de la Muerte", sirvió a bordo del arma definitiva del Imperio realizando tareas serviles y de vigilancia. Esta variante gris oscuro perlado captura la apariencia siniestra de estos droides, cuyos fotorreceptores similares a insectos les daban una presencia inquietante. A pesar de ser droides de protocolo, las unidades RA-7 fueron a menudo modificadas para funciones de espionaje y seguridad dentro de instalaciones imperiales. Una pieza valiosa para coleccionistas que construyen escenas interiores de la Estrella de la Muerte y áreas administrativas imperiales.'
  },
  {
    minifigure_no: 'sw0939',
    description_en: 'This Anakin Skywalker variant depicts the young Jedi Knight in his practical combat attire with black legs and communication headset during the Clone Wars. The headset represents the constant coordination required during large-scale Republic military operations across the galaxy. This version captures Anakin during his time as a General, leading clone troops into battle and performing daring tactical maneuvers. Essential for collectors building Clone Wars battle scenes and Republic military command displays.',
    description_de: 'Diese Anakin Skywalker-Variante zeigt den jungen Jedi-Ritter in seiner praktischen Kampfkleidung mit schwarzen Beinen und Kommunikations-Headset während der Klonkriege. Das Headset repräsentiert die ständige Koordination, die während großangelegter Militäroperationen der Republik in der gesamten Galaxis erforderlich war. Diese Version erfasst Anakin während seiner Zeit als General, als er Klontruppen in die Schlacht führte und gewagte taktische Manöver durchführte. Unverzichtbar für Sammler, die Klonkrieg-Kampfszenen und militärische Kommandodisplays der Republik aufbauen.',
    description_fr: 'Cette variante d\'Anakin Skywalker dépeint le jeune Chevalier Jedi dans sa tenue de combat pratique avec des jambes noires et un casque de communication pendant la Guerre des Clones. Le casque représente la coordination constante requise lors des opérations militaires à grande échelle de la République à travers la galaxie. Cette version capture Anakin pendant son temps en tant que Général, menant des troupes clones au combat et effectuant des manœuvres tactiques audacieuses. Essentiel pour les collectionneurs construisant des scènes de bataille de la Guerre des Clones et des présentations de commandement militaire de la République.',
    description_es: 'Esta variante de Anakin Skywalker representa al joven Caballero Jedi en su atuendo de combate práctico con piernas negras y auriculares de comunicación durante las Guerras Clon. Los auriculares representan la coordinación constante requerida durante las operaciones militares a gran escala de la República a través de la galaxia. Esta versión captura a Anakin durante su tiempo como General, liderando tropas clon a la batalla y realizando maniobras tácticas audaces. Esencial para coleccionistas que construyen escenas de batalla de las Guerras Clon y exhibiciones de comando militar de la República.'
  },
  {
    minifigure_no: 'sw0940',
    description_en: 'Enfys Nest is the mysterious leader of the Cloud-Riders marauder gang, revealed to be a young freedom fighter opposing the Crimson Dawn crime syndicate in Solo: A Star Wars Story. Her distinctive masked helmet and armor conceal her true identity while projecting an intimidating presence during raids. The character\'s surprising reveal as a freedom fighter rather than a villain adds depth to the Solo storyline. A highly sought-after minifigure for collectors of the Solo movie and the criminal underworld of Star Wars.',
    description_de: 'Enfys Nest ist die mysteriöse Anführerin der Cloud-Riders-Plündererbande, die sich als junge Freiheitskämpferin offenbart, die sich dem Verbrechersyndikatt Crimson Dawn in Solo: A Star Wars Story entgegenstellt. Ihr markanter maskierter Helm und ihre Rüstung verbergen ihre wahre Identität, während sie bei Überfällen eine einschüchternde Präsenz projiziert. Die überraschende Enthüllung des Charakters als Freiheitskämpferin statt als Schurkin verleiht der Solo-Handlung Tiefe. Eine sehr begehrte Minifigur für Sammler des Solo-Films und der kriminellen Unterwelt von Star Wars.',
    description_fr: 'Enfys Nest est la mystérieuse leader du gang de maraudeurs Cloud-Riders, révélée être une jeune combattante de la liberté s\'opposant au syndicat du crime Crimson Dawn dans Solo: A Star Wars Story. Son casque masqué distinctif et son armure cachent sa véritable identité tout en projetant une présence intimidante lors des raids. La révélation surprenante du personnage en tant que combattante de la liberté plutôt qu\'une méchante ajoute de la profondeur à l\'histoire de Solo. Une figurine très recherchée pour les collectionneurs du film Solo et du monde criminel de Star Wars.',
    description_es: 'Enfys Nest es la misteriosa líder de la banda de merodeadores Cloud-Riders, revelada como una joven luchadora por la libertad que se opone al sindicato criminal Amanecer Carmesí en Han Solo: Una Historia de Star Wars. Su distintivo casco enmascarado y armadura ocultan su verdadera identidad mientras proyecta una presencia intimidante durante las incursiones. La sorprendente revelación del personaje como luchadora por la libertad en lugar de villana agrega profundidad a la historia de Solo. Una minifigura muy buscada por coleccionistas de la película Solo y el submundo criminal de Star Wars.'
  },
  {
    minifigure_no: 'sw0941',
    description_en: 'Tobias Beckett is the grizzled outlaw and mentor figure who recruited Han Solo into a life of crime in Solo: A Star Wars Story. This version features his dark tan coat and tan hair, representing his weathered appearance as a veteran thief and smuggler. Beckett\'s complex relationship with Han, teaching him survival skills while ultimately betraying him, shapes Han\'s cynical worldview. A key figure for collectors building the complete cast of the Solo movie and understanding Han\'s origin story.',
    description_de: 'Tobias Beckett ist der abgehärtete Gesetzlose und Mentorfigur, der Han Solo in ein Leben der Kriminalität rekrutierte in Solo: A Star Wars Story. Diese Version zeigt seinen dunkel-hellbraunen Mantel und hellbraunes Haar und repräsentiert sein verwittertes Erscheinungsbild als erfahrener Dieb und Schmuggler. Becketts komplexe Beziehung zu Han, ihm Überlebensfähigkeiten beizubringen, während er ihn letztendlich verrät, prägt Hans zynische Weltanschauung. Eine Schlüsselfigur für Sammler, die die vollständige Besetzung des Solo-Films aufbauen und Hans Ursprungsgeschichte verstehen.',
    description_fr: 'Tobias Beckett est le hors-la-loi endurci et figure de mentor qui a recruté Han Solo dans une vie de crime dans Solo: A Star Wars Story. Cette version présente son manteau beige foncé et ses cheveux beiges, représentant son apparence altérée en tant que voleur et contrebandier vétéran. La relation complexe de Beckett avec Han, lui enseignant des compétences de survie tout en le trahissant finalement, façonne la vision cynique du monde de Han. Une figure clé pour les collectionneurs construisant la distribution complète du film Solo et comprenant l\'histoire d\'origine de Han.',
    description_es: 'Tobias Beckett es el curtido forajido y figura mentora que reclutó a Han Solo para una vida de crimen en Han Solo: Una Historia de Star Wars. Esta versión presenta su abrigo bronceado oscuro y cabello bronceado, representando su apariencia curtida como veterano ladrón y contrabandista. La compleja relación de Beckett con Han, enseñándole habilidades de supervivencia mientras finalmente lo traiciona, moldea la visión cínica del mundo de Han. Una figura clave para coleccionistas que construyen el elenco completo de la película Solo y comprenden la historia de origen de Han.'
  },
  {
    minifigure_no: 'sw0942',
    description_en: 'Weazel is a rough-and-tumble member of Tobias Beckett\'s criminal crew, specializing in heavy weapons and demolitions during their heist operations. This alien character from the Solo movie represents the diverse criminal underworld that operates in the shadows of the Empire. His distinctive alien features and rugged appearance reflect the dangerous lifestyle of outlaws in the Star Wars galaxy. A colorful addition to collections featuring the Solo movie characters and criminal gang assemblies.',
    description_de: 'Weazel ist ein raubeiniges Mitglied von Tobias Becketts krimineller Crew, spezialisiert auf schwere Waffen und Sprengungen während ihrer Raubüberfälle. Dieser außerirdische Charakter aus dem Solo-Film repräsentiert die vielfältige kriminelle Unterwelt, die in den Schatten des Imperiums operiert. Seine markanten außerirdischen Züge und sein robustes Erscheinungsbild spiegeln den gefährlichen Lebensstil von Gesetzlosen in der Star Wars-Galaxis wider. Eine farbenfrohe Ergänzung für Sammlungen mit Solo-Filmcharakteren und kriminellen Bandenzusammenstellungen.',
    description_fr: 'Weazel est un membre rude de l\'équipe criminelle de Tobias Beckett, spécialisé dans les armes lourdes et les démolitions lors de leurs opérations de braquage. Ce personnage alien du film Solo représente le monde criminel diversifié qui opère dans l\'ombre de l\'Empire. Ses traits aliens distinctifs et son apparence robuste reflètent le mode de vie dangereux des hors-la-loi dans la galaxie Star Wars. Un ajout coloré aux collections présentant les personnages du film Solo et les assemblées de gangs criminels.',
    description_es: 'Weazel es un miembro rudo de la banda criminal de Tobias Beckett, especializado en armas pesadas y demoliciones durante sus operaciones de atraco. Este personaje alienígena de la película Solo representa el diverso submundo criminal que opera en las sombras del Imperio. Sus distintivos rasgos alienígenas y apariencia robusta reflejan el peligroso estilo de vida de los forajidos en la galaxia de Star Wars. Una adición colorida a colecciones que presentan personajes de la película Solo y ensamblajes de bandas criminales.'
  },
  {
    minifigure_no: 'sw0943',
    description_en: 'R2-Q2 is an astromech droid serving with the Rebel Alliance, distinguished by its unique pattern of large red dots on its white dome. This droid variant showcases the wide variety of astromech paint schemes used to identify different units and their assignments within the Rebel fleet. Astromech droids like R2-Q2 performed essential navigation, repair, and systems management aboard X-wing and Y-wing starfighters. A distinctive addition for collectors building diverse Rebel droid collections and hangar bay scenes.',
    description_de: 'R2-Q2 ist ein Astromech-Droide im Dienst der Rebellenallianz, ausgezeichnet durch sein einzigartiges Muster aus großen roten Punkten auf seiner weißen Kuppel. Diese Droiden-Variante zeigt die große Vielfalt an Astromech-Farbschemata, die verwendet wurden, um verschiedene Einheiten und ihre Aufgaben innerhalb der Rebellenflotte zu identifizieren. Astromech-Droiden wie R2-Q2 führten wesentliche Navigations-, Reparatur- und Systemverwaltungsaufgaben an Bord von X-Flügler- und Y-Flügler-Raumjägern durch. Eine markante Ergänzung für Sammler, die vielfältige Rebellen-Druidensammlungen und Hangarszenen aufbauen.',
    description_fr: 'R2-Q2 est un droïde astromech servant avec l\'Alliance rebelle, distingué par son motif unique de grands points rouges sur son dôme blanc. Cette variante de droïde présente la grande variété de schémas de peinture astromech utilisés pour identifier différentes unités et leurs affectations au sein de la flotte rebelle. Les droïdes astromech comme R2-Q2 effectuaient des tâches essentielles de navigation, de réparation et de gestion de systèmes à bord des chasseurs X-wing et Y-wing. Un ajout distinctif pour les collectionneurs construisant diverses collections de droïdes rebelles et des scènes de baie de hangar.',
    description_es: 'R2-Q2 es un droide astromecánico que sirve con la Alianza Rebelde, distinguido por su patrón único de grandes puntos rojos en su cúpula blanca. Esta variante de droide muestra la amplia variedad de esquemas de pintura astromecánica usados para identificar diferentes unidades y sus asignaciones dentro de la flota rebelde. Droides astromecánicos como R2-Q2 realizaban navegación esencial, reparaciones y gestión de sistemas a bordo de cazas estelares X-wing y Y-wing. Una adición distintiva para coleccionistas que construyen diversas colecciones de droides rebeldes y escenas de bahía de hangar.'
  },
  {
    minifigure_no: 'sw0944',
    description_en: 'Biggs Darklighter was Luke Skywalker\'s childhood friend from Tatooine who became a Rebel pilot and flew as Red Three during the Battle of Yavin. This version features light nougat head printing and dual molded helmet details, capturing his appearance as an experienced pilot. Biggs\'s emotional reunion with Luke in the Death Star briefing room and his sacrifice during the trench run make him one of the most memorable supporting characters from A New Hope. Essential for collectors building the complete Red Squadron and honoring the heroes of the Battle of Yavin.',
    description_de: 'Biggs Darklighter war Luke Skywalkers Jugendfreund aus Tatooine, der Rebellenpilot wurde und als Rot Drei während der Schlacht von Yavin flog. Diese Version zeigt hellbraune Kopfdrucke und zweifarbig geformte Helmdetails, die sein Erscheinungsbild als erfahrener Pilot erfassen. Biggs emotionales Wiedersehen mit Luke im Todesstern-Briefingraum und sein Opfer während des Grabenlaufs machen ihn zu einem der unvergesslichsten Nebendarsteller aus Eine neue Hoffnung. Unverzichtbar für Sammler, die das vollständige Rote Geschwader aufbauen und die Helden der Schlacht von Yavin ehren.',
    description_fr: 'Biggs Darklighter était l\'ami d\'enfance de Luke Skywalker de Tatooine qui est devenu pilote rebelle et a volé en tant que Red Three lors de la bataille de Yavin. Cette version présente une impression de tête beige clair et des détails de casque moulé en double, capturant son apparence en tant que pilote expérimenté. Les retrouvailles émotionnelles de Biggs avec Luke dans la salle de briefing de l\'Étoile de la Mort et son sacrifice pendant la course dans la tranchée en font l\'un des personnages secondaires les plus mémorables d\'Un nouvel espoir. Essentiel pour les collectionneurs construisant l\'Escadron Rouge complet et honorant les héros de la bataille de Yavin.',
    description_es: 'Biggs Darklighter fue el amigo de infancia de Luke Skywalker de Tatooine que se convirtió en piloto rebelde y voló como Rojo Tres durante la Batalla de Yavin. Esta versión presenta impresión de cabeza de color beige claro y detalles de casco moldeado dual, capturando su apariencia como piloto experimentado. El emotivo reencuentro de Biggs con Luke en la sala de briefing de la Estrella de la Muerte y su sacrificio durante la carrera de trinchera lo convierten en uno de los personajes secundarios más memorables de Una nueva esperanza. Esencial para coleccionistas que construyen el Escuadrón Rojo completo y honran a los héroes de la Batalla de Yavin.'
  },
  {
    minifigure_no: 'sw0945',
    description_en: 'Dryden\'s Guard serves as a Hylobon Enforcer protecting the ruthless crime lord Dryden Vos aboard his luxury yacht in Solo: A Star Wars Story. This alien warrior\'s distinctive open-mouthed expression conveys the intimidating presence these guards maintained while securing Crimson Dawn\'s operations. The unique alien design represents the diverse species employed by criminal syndicates throughout the galaxy. A valuable piece for collectors building Dryden Vos\'s yacht interior and Crimson Dawn criminal organization displays.',
    description_de: 'Dreydens Wache dient als Hylobon-Vollstrecker, der den skrupellosen Verbrecher-Lord Dryden Vos an Bord seiner Luxusyacht in Solo: A Star Wars Story beschützt. Der markante offene Mundausdruck dieses außerirdischen Kriegers vermittelt die einschüchternde Präsenz, die diese Wachen aufrechterhielten, während sie die Operationen von Crimson Dawn sicherten. Das einzigartige außerirdische Design repräsentiert die vielfältigen Spezies, die von kriminellen Syndikaten in der gesamten Galaxis beschäftigt werden. Ein wertvolles Stück für Sammler, die das Yachtinnere von Dryden Vos und Displays der kriminellen Organisation Crimson Dawn aufbauen.',
    description_fr: 'Le garde de Dryden sert d\'exécuteur Hylobon protégeant le seigneur du crime impitoyable Dryden Vos à bord de son yacht de luxe dans Solo: A Star Wars Story. L\'expression distinctive à bouche ouverte de ce guerrier alien transmet la présence intimidante que ces gardes maintenaient tout en sécurisant les opérations de Crimson Dawn. Le design alien unique représente les diverses espèces employées par les syndicats criminels à travers la galaxie. Une pièce précieuse pour les collectionneurs construisant l\'intérieur du yacht de Dryden Vos et des présentations de l\'organisation criminelle Crimson Dawn.',
    description_es: 'El guardia de Dryden sirve como Ejecutor Hylobon protegiendo al despiadado señor del crimen Dryden Vos a bordo de su yate de lujo en Han Solo: Una Historia de Star Wars. La distintiva expresión de boca abierta de este guerrero alienígena transmite la presencia intimidante que estos guardias mantenían mientras aseguraban las operaciones de Amanecer Carmesí. El diseño alienígena único representa las diversas especies empleadas por sindicatos criminales a través de la galaxia. Una pieza valiosa para coleccionistas que construyen el interior del yate de Dryden Vos y exhibiciones de la organización criminal Amanecer Carmesí.'
  },
  {
    minifigure_no: 'sw0946',
    description_en: 'This Qi\'ra variant depicts Han Solo\'s childhood friend and love interest in her elegant fur coat, representing her rise to power within the Crimson Dawn criminal organization. The luxurious costume reflects her transformation from street urchin to Dryden Vos\'s lieutenant, showcasing her survival instincts and ambition. Her complex character arc, choosing power over love at the story\'s end, adds depth to the Solo narrative. A sought-after minifigure for collectors of the Solo movie and Star Wars underworld characters.',
    description_de: 'Diese Qi\'ra-Variante zeigt Han Solos Jugendfreundin und Liebhaberin in ihrem eleganten Pelzmantel, der ihren Aufstieg zur Macht innerhalb der kriminellen Organisation Crimson Dawn repräsentiert. Das luxuriöse Kostüm spiegelt ihre Verwandlung von der Straßengöre zur Leutnant von Dryden Vos wider und zeigt ihre Überlebensinstinkte und ihren Ehrgeiz. Ihr komplexer Charakterbogen, am Ende der Geschichte Macht über Liebe zu wählen, verleiht der Solo-Erzählung Tiefe. Eine begehrte Minifigur für Sammler des Solo-Films und Star Wars-Unterweltcharaktere.',
    description_fr: 'Cette variante de Qi\'ra dépeint l\'amie d\'enfance et intérêt amoureux de Han Solo dans son élégant manteau de fourrure, représentant son ascension au pouvoir au sein de l\'organisation criminelle Crimson Dawn. Le costume luxueux reflète sa transformation de gamine des rues en lieutenant de Dryden Vos, mettant en valeur ses instincts de survie et son ambition. Son arc de personnage complexe, choisissant le pouvoir plutôt que l\'amour à la fin de l\'histoire, ajoute de la profondeur au récit de Solo. Une figurine recherchée pour les collectionneurs du film Solo et des personnages du monde criminel de Star Wars.',
    description_es: 'Esta variante de Qi\'ra representa a la amiga de infancia e interés amoroso de Han Solo en su elegante abrigo de piel, representando su ascenso al poder dentro de la organización criminal Amanecer Carmesí. El lujoso vestuario refleja su transformación de huérfana callejera a teniente de Dryden Vos, mostrando sus instintos de supervivencia y ambición. Su complejo arco de personaje, eligiendo el poder sobre el amor al final de la historia, agrega profundidad a la narrativa de Solo. Una minifigura buscada por coleccionistas de la película Solo y personajes del submundo de Star Wars.'
  },
  {
    minifigure_no: 'sw0947',
    description_en: 'The Elite Praetorian Guard protects Supreme Leader Snoke in his throne room aboard the Supremacy in The Last Jedi. This variant features the distinctive pointed helmet design and flowing skirt piece, representing one of eight uniquely armed warriors. These elite fighters demonstrated their deadly skills in the memorable throne room battle against Rey and Kylo Ren. A highly collectible minifigure for building Snoke\'s throne room and representing the First Order\'s most skilled combatants.',
    description_de: 'Die Elite-Prätorianergarde beschützt Obersten Führer Snoke in seinem Thronsaal an Bord der Supremacy in Die letzten Jedi. Diese Variante zeigt das markante spitze Helmdesign und fließende Rockteil und repräsentiert einen von acht einzigartig bewaffneten Kriegern. Diese Elitekämpfer demonstrierten ihre tödlichen Fähigkeiten in der unvergesslichen Thronsaalschlacht gegen Rey und Kylo Ren. Eine sehr sammelwerte Minifigur für den Bau von Snokes Thronsaal und zur Repräsentation der geschicktesten Kämpfer der Ersten Ordnung.',
    description_fr: 'La Garde prétorienne d\'élite protège le Suprême Leader Snoke dans sa salle du trône à bord du Supremacy dans Les Derniers Jedi. Cette variante présente le design distinctif de casque pointu et une pièce de jupe fluide, représentant l\'un des huit guerriers armés de manière unique. Ces combattants d\'élite ont démontré leurs compétences mortelles dans la mémorable bataille de la salle du trône contre Rey et Kylo Ren. Une figurine très collectionnable pour construire la salle du trône de Snoke et représenter les combattants les plus qualifiés du Premier Ordre.',
    description_es: 'La Guardia Pretoriana de Élite protege al Líder Supremo Snoke en su sala del trono a bordo del Supremacy en Los Últimos Jedi. Esta variante presenta el distintivo diseño de casco puntiagudo y pieza de falda fluida, representando a uno de ocho guerreros armados únicamente. Estos luchadores de élite demostraron sus habilidades mortales en la memorable batalla de la sala del trono contra Rey y Kylo Ren. Una minifigura altamente coleccionable para construir la sala del trono de Snoke y representar a los combatientes más hábiles de la Primera Orden.'
  },
  {
    minifigure_no: 'sw0948',
    description_en: 'This Chewbacca variant depicts the legendary Wookiee warrior during the Kessel Run mission wearing protective goggles for the dangerous flight conditions. The dark brown and medium nougat fur coloring with crossed bandoliers captures Chewie\'s appearance during one of the most famous moments in the Solo movie. The goggles represent the practical equipment needed for navigating the hazardous Kessel mining routes and Maelstrom. An essential piece for collectors building the Millennium Falcon\'s Kessel Run configuration and iconic moments from Solo.',
    description_de: 'Diese Chewbacca-Variante zeigt den legendären Wookiee-Krieger während der Kessel-Run-Mission mit Schutzbrille für die gefährlichen Flugbedingungen. Die dunkelbraune und mittelhellbraune Fellfarbe mit gekreuzten Bandolieren erfasst Chewies Erscheinungsbild während eines der berühmtesten Momente im Solo-Film. Die Schutzbrille repräsentiert die praktische Ausrüstung, die für die Navigation der gefährlichen Kessel-Bergbaurouten und des Mahlstroms benötigt wird. Ein unverzichtbares Stück für Sammler, die die Kessel-Run-Konfiguration des Millennium Falken und ikonische Momente aus Solo aufbauen.',
    description_fr: 'Cette variante de Chewbacca dépeint le légendaire guerrier Wookiee lors de la mission du Run de Kessel portant des lunettes de protection pour les conditions de vol dangereuses. La coloration de fourrure brun foncé et beige moyen avec des bandoulières croisées capture l\'apparence de Chewie lors de l\'un des moments les plus célèbres du film Solo. Les lunettes représentent l\'équipement pratique nécessaire pour naviguer dans les routes minières dangereuses de Kessel et le Maelström. Une pièce essentielle pour les collectionneurs construisant la configuration du Faucon Millenium pour le Run de Kessel et les moments iconiques de Solo.',
    description_es: 'Esta variante de Chewbacca representa al legendario guerrero Wookiee durante la misión de la Carrera de Kessel usando gafas protectoras para las peligrosas condiciones de vuelo. La coloración de pelaje marrón oscuro y beige medio con bandoleras cruzadas captura la apariencia de Chewie durante uno de los momentos más famosos de la película Solo. Las gafas representan el equipo práctico necesario para navegar las peligrosas rutas mineras de Kessel y el Maelstrom. Una pieza esencial para coleccionistas que construyen la configuración de la Carrera de Kessel del Halcón Milenario y momentos icónicos de Solo.'
  },
  {
    minifigure_no: 'sw0949',
    description_en: 'Han Solo in his fur coat and goggles represents the smuggler\'s practical attire for surviving Kessel\'s harsh environment during the legendary Kessel Run. This outfit protected Han during the dangerous coaxium heist in the freezing mining facility and subsequent escape through the Maelstrom. The distinctive cold-weather gear showcases Han\'s resourcefulness and adaptability in extreme conditions. A must-have variant for collectors building Kessel mission scenes and tracking Han\'s journey through the Solo movie.',
    description_de: 'Han Solo in seinem Pelzmantel und seiner Schutzbrille repräsentiert die praktische Kleidung des Schmugglers zum Überleben in Kessels harscher Umgebung während des legendären Kessel-Runs. Dieses Outfit schützte Han während des gefährlichen Coaxium-Raubes in der eiskalten Bergbaueinrichtung und der anschließenden Flucht durch den Mahlstrom. Die markante Kälteschutzkleidung zeigt Hans Einfallsreichtum und Anpassungsfähigkeit unter extremen Bedingungen. Eine Must-have-Variante für Sammler, die Kessel-Missionsszenen aufbauen und Hans Reise durch den Solo-Film verfolgen.',
    description_fr: 'Han Solo dans son manteau de fourrure et ses lunettes représente la tenue pratique du contrebandier pour survivre à l\'environnement rude de Kessel pendant le légendaire Run de Kessel. Cette tenue a protégé Han pendant le dangereux braquage de coaxium dans l\'installation minière glaciale et la fuite subséquente à travers le Maelström. L\'équipement distinctif pour temps froid met en valeur l\'ingéniosité et l\'adaptabilité de Han dans des conditions extrêmes. Une variante incontournable pour les collectionneurs construisant des scènes de mission de Kessel et suivant le parcours de Han à travers le film Solo.',
    description_es: 'Han Solo en su abrigo de piel y gafas representa el atuendo práctico del contrabandista para sobrevivir al duro ambiente de Kessel durante la legendaria Carrera de Kessel. Este atuendo protegió a Han durante el peligroso atraco de coaxium en la gélida instalación minera y la subsiguiente escape a través del Maelstrom. El distintivo equipo para clima frío muestra el ingenio y adaptabilidad de Han en condiciones extremas. Una variante imprescindible para coleccionistas que construyen escenas de misión de Kessel y siguen el viaje de Han a través de la película Solo.'
  },
  {
    minifigure_no: 'sw0950',
    description_en: 'The Range Trooper is an elite Imperial soldier specialized for operations in extreme environments like the frozen mountains of Vandor. This trooper\'s distinctive armor features magnetic boots for boarding moving trains and heavy insulation for surviving brutal cold conditions. Range Troopers demonstrated their tactical prowess during the Conveyex train heist that opened the Solo movie. A unique Imperial trooper variant highly valued by collectors for its distinctive design and connection to memorable action sequences.',
    description_de: 'Der Range Trooper ist ein Elite-imperialer Soldat, spezialisiert auf Einsätze in extremen Umgebungen wie den gefrorenen Bergen von Vandor. Die markante Rüstung dieses Troopers verfügt über magnetische Stiefel für das Entern bewegender Züge und schwere Isolierung zum Überleben brutaler Kältebedingungen. Range Troopers demonstrierten ihre taktische Meisterschaft während des Conveyex-Zugraubes, der den Solo-Film eröffnete. Eine einzigartige imperiale Trooper-Variante, die von Sammlern für ihr markantes Design und ihre Verbindung zu unvergesslichen Actionsequenzen hochgeschätzt wird.',
    description_fr: 'Le Range Trooper est un soldat impérial d\'élite spécialisé pour les opérations dans des environnements extrêmes comme les montagnes gelées de Vandor. L\'armure distinctive de ce soldat comporte des bottes magnétiques pour monter à bord des trains en mouvement et une isolation lourde pour survivre à des conditions de froid brutal. Les Range Troopers ont démontré leur prouesse tactique lors du braquage du train Conveyex qui a ouvert le film Solo. Une variante unique de soldat impérial très appréciée des collectionneurs pour son design distinctif et sa connexion à des séquences d\'action mémorables.',
    description_es: 'El Range Trooper es un soldado Imperial de élite especializado en operaciones en entornos extremos como las montañas congeladas de Vandor. La distintiva armadura de este soldado cuenta con botas magnéticas para abordar trenes en movimiento y aislamiento pesado para sobrevivir condiciones de frío brutal. Los Range Troopers demostraron su destreza táctica durante el atraco del tren Conveyex que abrió la película Solo. Una variante única de soldado Imperial altamente valorada por coleccionistas por su diseño distintivo y conexión con secuencias de acción memorables.'
  }
];

async function main() {
  console.log('Starting batch save for sw0932-sw0950...');

  for (const desc of descriptions) {
    await prisma.minifigCatalog.update({
      where: { minifigure_no: desc.minifigure_no },
      data: {
        description_en: desc.description_en,
        description_de: desc.description_de,
        description_fr: desc.description_fr,
        description_es: desc.description_es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`✓ Saved ${desc.minifigure_no}: ${descriptions.find(d => d.minifigure_no === desc.minifigure_no)?.minifigure_no}`);
  }

  console.log(`Batch complete! ${descriptions.length} minifigs saved (sw0932-sw0950).`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
