import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0583',
    name: 'Imperial Navy Trooper - Nougat Head',
    en: 'Imperial Navy Troopers serve as the security forces and ship crew aboard Star Destroyers and other Imperial capital ships, wearing distinctive black uniforms that set them apart from standard Stormtroopers. This LEGO minifigure features the all-black Imperial Navy uniform with printed torso details showing armor plating and belt equipment, a black cap, and a nougat flesh-tone head representing one of the many human crew members serving the Imperial fleet. These troopers handle security duties, boarding actions, and ship defense operations throughout the Imperial Navy. Released in Star Destroyer sets and Imperial capital ship builds from the mid-2010s, Navy Troopers add essential crew presence to Imperial vessels. Collectors value these troopers for populating Star Destroyer hangar bays, detention blocks, and corridors, making them crucial for creating authentic Imperial ship interiors beyond just Stormtroopers and officers.',
    de: 'Imperiale Marine-Soldaten dienen als Sicherheitskräfte und Schiffsbesatzung an Bord von Sternenzerstörern und anderen imperialen Großkampfschiffen und tragen charakteristische schwarze Uniformen, die sie von Standard-Stormtroopern unterscheiden. Diese LEGO-Minifigur verfügt über die vollschwarze imperiale Marine-Uniform mit gedruckten Torso-Details, die Rüstungsplatten und Gürtelausrüstung zeigen, eine schwarze Mütze und einen nougatfarbenen Fleischton-Kopf, der eines der vielen menschlichen Besatzungsmitglieder repräsentiert, die der imperialen Flotte dienen. Diese Soldaten übernehmen Sicherheitsaufgaben, Enteraktionen und Schiffsverteidigungsoperationen in der gesamten imperialen Marine. Marine-Soldaten wurden in Sternenzerstörer-Sets und imperialen Großkampfschiff-Builds aus der Mitte der 2010er Jahre veröffentlicht und fügen imperiale Schiffen wesentliche Besatzungspräsenz hinzu. Sammler schätzen diese Soldaten für die Bevölkerung von Sternenzerstörer-Hangarbuchten, Haftzellen und Korridoren, was sie entscheidend für die Schaffung authentischer imperialer Schiffsinnenräume jenseits von nur Stormtroopern und Offizieren macht.',
    fr: 'Les Soldats de la Marine Impériale servent de forces de sécurité et d\'équipage de navire à bord des Destroyers Stellaires et autres vaisseaux capitaux impériaux, portant des uniformes noirs distinctifs qui les distinguent des Stormtroopers standard. Cette minifigurine LEGO présente l\'uniforme noir de la Marine Impériale avec des détails de torse imprimés montrant des plaques d\'armure et un équipement de ceinture, une casquette noire et une tête couleur chair nougat représentant l\'un des nombreux membres d\'équipage humains servant la flotte impériale. Ces soldats gèrent les tâches de sécurité, les actions d\'abordage et les opérations de défense du navire dans toute la Marine Impériale. Sortis dans des sets de Destroyers Stellaires et des constructions de vaisseaux capitaux impériaux du milieu des années 2010, les Soldats de la Marine ajoutent une présence d\'équipage essentielle aux vaisseaux impériaux. Les collectionneurs apprécient ces soldats pour peupler les baies de hangar, les blocs de détention et les couloirs des Destroyers Stellaires, ce qui les rend cruciaux pour créer des intérieurs de vaisseaux impériaux authentiques au-delà des Stormtroopers et des officiers.',
    es: 'Los Soldados de la Marina Imperial sirven como fuerzas de seguridad y tripulación de naves a bordo de Destructores Estelares y otras naves capitales imperiales, vistiendo uniformes negros distintivos que los distinguen de los Stormtroopers estándar. Esta minifigura LEGO presenta el uniforme negro de la Marina Imperial con detalles de torso impresos que muestran placas de armadura y equipo de cinturón, una gorra negra y una cabeza de tono carne nougat que representa a uno de los muchos miembros de tripulación humanos que sirven a la flota imperial. Estos soldados manejan deberes de seguridad, acciones de abordaje y operaciones de defensa de naves en toda la Marina Imperial. Lanzados en sets de Destructores Estelares y construcciones de naves capitales imperiales de mediados de la década de 2010, los Soldados de la Marina añaden presencia esencial de tripulación a las naves imperiales. Los coleccionistas valoran a estos soldados por poblar bahías de hangar, bloques de detención y corredores de Destructores Estelares, haciéndolos cruciales para crear interiores de naves imperiales auténticos más allá de solo Stormtroopers y oficiales.',
  },
  {
    no: 'sw0584',
    name: 'Imperial Crew - Dark Bluish Gray Cap, Plain Arms',
    en: 'Imperial Crew members are the technical specialists and support personnel who keep Star Destroyers, Death Stars, and Imperial facilities operational throughout the galaxy. This LEGO minifigure features a dark bluish gray cap, black jumpsuit with minimal printed details, and plain arms representing the utilitarian work uniforms worn by maintenance crews, technicians, and support staff. Unlike the military-focused Navy Troopers, crew members handle the day-to-day technical operations that keep the Imperial war machine functioning. Released in various Imperial facility sets and capital ship builds from the mid-2010s, these crew figures add background realism to Imperial installations. Collectors value generic crew members for populating engineering sections, control panels, hangar maintenance areas, and technical stations, making them essential for creating lived-in Imperial environments that show the vast support infrastructure beyond combat personnel.',
    de: 'Imperiale Besatzungsmitglieder sind die technischen Spezialisten und Unterstützungspersonal, die Sternenzerstörer, Todessterne und imperiale Einrichtungen in der gesamten Galaxis betriebsbereit halten. Diese LEGO-Minifigur verfügt über eine dunkelblaugraue Mütze, einen schwarzen Overall mit minimalen gedruckten Details und einfache Arme, die die nüchternen Arbeitsuniformen repräsentieren, die von Wartungscrews, Technikern und Unterstützungspersonal getragen werden. Im Gegensatz zu den militärisch ausgerichteten Marine-Soldaten übernehmen Besatzungsmitglieder die täglichen technischen Operationen, die die imperiale Kriegsmaschine funktionsfähig halten. Diese Besatzungsfiguren wurden in verschiedenen imperialen Einrichtungs-Sets und Großkampfschiff-Builds aus der Mitte der 2010er Jahre veröffentlicht und fügen imperialen Installationen Hintergrund-Realismus hinzu. Sammler schätzen generische Besatzungsmitglieder für die Bevölkerung von Technikbereichen, Kontrollpanelen, Hangar-Wartungsbereichen und technischen Stationen, was sie unverzichtbar für die Schaffung bewohnter imperialer Umgebungen macht, die die riesige Unterstützungsinfrastruktur jenseits des Kampfpersonals zeigen.',
    fr: 'Les Membres d\'équipage impériaux sont les spécialistes techniques et le personnel de soutien qui maintiennent les Destroyers Stellaires, les Étoiles de la Mort et les installations impériales opérationnels dans toute la galaxie. Cette minifigurine LEGO présente une casquette gris bleuté foncé, une combinaison noire avec des détails imprimés minimaux et des bras simples représentant les uniformes de travail utilitaires portés par les équipes de maintenance, les techniciens et le personnel de soutien. Contrairement aux Soldats de la Marine axés sur le militaire, les membres d\'équipage gèrent les opérations techniques quotidiennes qui maintiennent la machine de guerre impériale en fonctionnement. Sortis dans divers sets d\'installations impériales et de constructions de vaisseaux capitaux du milieu des années 2010, ces figurines d\'équipage ajoutent un réalisme d\'arrière-plan aux installations impériales. Les collectionneurs apprécient les membres d\'équipage génériques pour peupler les sections d\'ingénierie, les panneaux de contrôle, les zones de maintenance des hangars et les stations techniques, ce qui les rend essentiels pour créer des environnements impériaux habités qui montrent la vaste infrastructure de soutien au-delà du personnel de combat.',
    es: 'Los Miembros de tripulación imperiales son los especialistas técnicos y personal de apoyo que mantienen operativos los Destructores Estelares, Estrellas de la Muerte e instalaciones imperiales en toda la galaxia. Esta minifigura LEGO presenta una gorra gris azulado oscuro, mono negro con detalles impresos mínimos y brazos simples que representan los uniformes de trabajo utilitarios usados por equipos de mantenimiento, técnicos y personal de apoyo. A diferencia de los Soldados de la Marina enfocados militarmente, los miembros de tripulación manejan las operaciones técnicas del día a día que mantienen funcionando la máquina de guerra imperial. Lanzadas en varios sets de instalaciones imperiales y construcciones de naves capitales de mediados de la década de 2010, estas figuras de tripulación añaden realismo de fondo a las instalaciones imperiales. Los coleccionistas valoran a los miembros de tripulación genéricos por poblar secciones de ingeniería, paneles de control, áreas de mantenimiento de hangares y estaciones técnicas, haciéndolos esenciales para crear ambientes imperiales habitados que muestran la vasta infraestructura de apoyo más allá del personal de combate.',
  },
  {
    no: 'sw0585',
    name: 'Imperial Stormtrooper - Printed Legs, Dark Blue Helmet Vents',
    en: 'Imperial Stormtroopers with dark blue helmet vents represent another color variant of the Empire\'s iconic shock troops, adding subtle visual diversity to Stormtrooper legions. This LEGO minifigure features the classic white armor with printed leg details showing armor plating and joints, dark blue coloring on the helmet vents rather than the standard black, and the intimidating faceless mask that defines Imperial ground forces. The printed legs and colored vent details reflect LEGO\'s evolving minifigure design standards that add realism and collectibility. Released across various Star Wars sets from the mid-2010s, these Stormtroopers serve the same garrison and assault roles as their standard counterparts. Collectors particularly value Stormtroopers with unique vent colors for army-building diverse Imperial squads, with the dark blue vents making this variant slightly rarer and more desirable for creating varied trooper formations in displays ranging from Death Star corridors to planetary assaults.',
    de: 'Imperiale Stormtroopers mit dunkelblauen Helmbelüftungen repräsentieren eine weitere Farbvariante der ikonischen Schocktruppen des Imperiums und fügen Stormtrooper-Legionen subtile visuelle Vielfalt hinzu. Diese LEGO-Minifigur verfügt über die klassische weiße Rüstung mit gedruckten Beindetails, die Rüstungsplatten und Gelenke zeigen, dunkelblaue Färbung an den Helmbelüftungen statt des standardmäßigen Schwarz und die einschüchternde gesichtslose Maske, die imperiale Bodentruppen definiert. Die gedruckten Beine und farbigen Belüftungsdetails spiegeln LEGOs sich entwickelnde Minifigur-Designstandards wider, die Realismus und Sammelbarkeit hinzufügen. Diese Stormtroopers wurden in verschiedenen Star-Wars-Sets aus der Mitte der 2010er Jahre veröffentlicht und dienen denselben Garnisons- und Angriffsfunktionen wie ihre Standardgegenstücke. Sammler schätzen Stormtroopers mit einzigartigen Belüftungsfarben besonders für den Aufbau vielfältiger imperialer Trupps, wobei die dunkelblauen Belüftungen diese Variante etwas seltener und begehrenswerter für die Schaffung variierter Truppen-Formationen in Displays machen, die von Todesstern-Korridoren bis zu planetaren Angriffen reichen.',
    fr: 'Les Stormtroopers impériaux avec des évents de casque bleu foncé représentent une autre variante de couleur des troupes de choc emblématiques de l\'Empire, ajoutant une diversité visuelle subtile aux légions de Stormtroopers. Cette minifigurine LEGO présente l\'armure blanche classique avec des détails de jambes imprimées montrant des plaques d\'armure et des articulations, une coloration bleu foncé sur les évents du casque plutôt que le noir standard, et le masque intimidant sans visage qui définit les forces terrestres impériales. Les jambes imprimées et les détails d\'évents colorés reflètent l\'évolution des normes de conception de minifigurines LEGO qui ajoutent du réalisme et de la collection. Sortis dans divers sets Star Wars du milieu des années 2010, ces Stormtroopers servent les mêmes rôles de garnison et d\'assaut que leurs homologues standard. Les collectionneurs apprécient particulièrement les Stormtroopers avec des couleurs d\'évents uniques pour construire des escouades impériales diverses, les évents bleu foncé rendant cette variante légèrement plus rare et plus désirable pour créer des formations de troupes variées dans des affichages allant des couloirs de l\'Étoile de la Mort aux assauts planétaires.',
    es: 'Los Stormtroopers imperiales con rejillas de ventilación de casco azul oscuro representan otra variante de color de las icónicas tropas de choque del Imperio, añadiendo diversidad visual sutil a las legiones de Stormtrooper. Esta minifigura LEGO presenta la clásica armadura blanca con detalles de piernas impresos que muestran placas de armadura y articulaciones, coloración azul oscuro en las rejillas de ventilación del casco en lugar del negro estándar, y la intimidante máscara sin rostro que define a las fuerzas terrestres imperiales. Las piernas impresas y los detalles de ventilación coloreados reflejan los estándares de diseño de minifiguras en evolución de LEGO que añaden realismo y coleccionabilidad. Lanzados en varios sets de Star Wars de mediados de la década de 2010, estos Stormtroopers sirven los mismos roles de guarnición y asalto que sus contrapartes estándar. Los coleccionistas valoran particularmente a los Stormtroopers con colores de ventilación únicos para construir escuadrones imperiales diversos, con las rejillas de ventilación azul oscuro haciendo esta variante ligeramente más rara y deseable para crear formaciones de tropas variadas en exhibiciones que van desde corredores de la Estrella de la Muerte hasta asaltos planetarios.',
  },
  {
    no: 'sw0586',
    name: 'Darth Vader (Tan Head)',
    en: 'Darth Vader, the Dark Lord of the Sith and supreme commander of the Imperial forces, stands as one of the most iconic villains in cinematic history. This LEGO minifigure features Vader\'s instantly recognizable black armor and cape, his distinctive helmet with respiratory mask, and importantly, a tan flesh-tone head piece representing Anakin Skywalker\'s scarred face beneath the mask. The inclusion of the tan head allows for dramatic unmasking scenes from Return of the Jedi when Luke removes Vader\'s helmet in his final moments. Released in numerous high-profile sets throughout the 2010s including Death Stars, Imperial facilities, and Vader\'s TIE Advanced, this version represents Vader during the Original Trilogy era. Collectors highly prize Darth Vader minifigures as centerpieces of any Star Wars collection, with the tan head variant being especially valued for recreating the emotional redemption scene and displaying both Vader\'s imposing masked appearance and his vulnerable unmasked humanity.',
    de: 'Darth Vader, der Dunkle Lord der Sith und oberste Kommandant der imperialen Streitkräfte, steht als einer der ikonischsten Schurken der Kinogeschichte. Diese LEGO-Minifigur verfügt über Vaders sofort erkennbare schwarze Rüstung und Umhang, seinen charakteristischen Helm mit Atemmaske und wichtig, ein beige-farbenes Kopfteil, das Anakin Skywalkers vernarbtes Gesicht unter der Maske darstellt. Die Einbeziehung des beigen Kopfes ermöglicht dramatische Demaskierungsszenen aus Die Rückkehr der Jedi-Ritter, wenn Luke Vaders Helm in seinen letzten Momenten abnimmt. Diese Version wurde in zahlreichen hochkarätigen Sets während der 2010er Jahre veröffentlicht, darunter Todessterne, imperiale Einrichtungen und Vaders TIE Advanced, und repräsentiert Vader während der Original-Trilogie-Ära. Sammler schätzen Darth-Vader-Minifiguren sehr als Herzstücke jeder Star-Wars-Sammlung, wobei die beige Kopf-Variante besonders geschätzt wird für die Nachbildung der emotionalen Erlösungsszene und die Anzeige sowohl von Vaders imposantem maskiertem Erscheinungsbild als auch seiner verletzlichen unmaskierten Menschlichkeit.',
    fr: 'Dark Vador, le Seigneur Noir des Sith et commandant suprême des forces impériales, se dresse comme l\'un des méchants les plus emblématiques de l\'histoire du cinéma. Cette minifigurine LEGO présente l\'armure et la cape noires instantanément reconnaissables de Vador, son casque distinctif avec masque respiratoire, et surtout, une pièce de tête couleur chair beige représentant le visage cicatrisé d\'Anakin Skywalker sous le masque. L\'inclusion de la tête beige permet des scènes de démasquage dramatiques du Retour du Jedi lorsque Luke retire le casque de Vador dans ses derniers moments. Sortie dans de nombreux sets de haut profil tout au long des années 2010, y compris les Étoiles de la Mort, les installations impériales et le TIE Advanced de Vador, cette version représente Vador pendant l\'ère de la trilogie originale. Les collectionneurs apprécient grandement les minifigurines de Dark Vador comme pièces maîtresses de toute collection Star Wars, la variante de tête beige étant particulièrement appréciée pour recréer la scène de rédemption émotionnelle et afficher à la fois l\'apparence masquée imposante de Vador et son humanité vulnérable démasquée.',
    es: 'Darth Vader, el Señor Oscuro de los Sith y comandante supremo de las fuerzas imperiales, se erige como uno de los villanos más icónicos de la historia del cine. Esta minifigura LEGO presenta la armadura y capa negras instantáneamente reconocibles de Vader, su distintivo casco con máscara respiratoria, e importantemente, una pieza de cabeza de tono carne beige que representa el rostro cicatrizado de Anakin Skywalker debajo de la máscara. La inclusión de la cabeza beige permite escenas dramáticas de desenmascaramiento de El Retorno del Jedi cuando Luke retira el casco de Vader en sus momentos finales. Lanzada en numerosos sets de alto perfil a lo largo de la década de 2010, incluyendo Estrellas de la Muerte, instalaciones imperiales y el TIE Advanced de Vader, esta versión representa a Vader durante la era de la Trilogía Original. Los coleccionistas aprecian altamente las minifiguras de Darth Vader como piezas centrales de cualquier colección de Star Wars, con la variante de cabeza beige siendo especialmente valorada por recrear la escena de redención emocional y mostrar tanto la apariencia enmascarada imponente de Vader como su humanidad vulnerable desenmascarada.',
  },
  {
    no: 'sw0587',
    name: 'Treadwell Droid - Mini',
    en: 'The mini Treadwell Droid represents a smaller-scale version of the WED-15 service droid seen maintaining equipment on moisture farms and throughout the Star Wars galaxy. This LEGO mini build features a compact design with the characteristic white and red coloring, basic printed details suggesting the droid\'s sensors and tools, and a miniaturized form factor that fits alongside standard minifigures. Unlike full minifigure-scale droids, mini builds like this Treadwell provide background atmosphere and technical detail without consuming as much display space. Released in various Tatooine-themed sets and as accessory pieces in larger builds from the 2010s, mini droids add environmental storytelling. Collectors value mini droid builds for populating workshop scenes, adding maintenance details to hangar bays, and creating realistic technical environments where these utility droids would perform their unglamorous but essential repair work across Star Wars locations.',
    de: 'Der Mini-Treadwell-Droide repräsentiert eine kleinere Version des WED-15-Service-Droiden, der auf Feuchtigkeitsfarmen und in der gesamten Star-Wars-Galaxis Ausrüstung wartet. Dieser LEGO-Mini-Build verfügt über ein kompaktes Design mit der charakteristischen weißen und roten Färbung, grundlegenden gedruckten Details, die die Sensoren und Werkzeuge des Droiden andeuten, und einem miniaturisierten Formfaktor, der neben Standard-Minifiguren passt. Im Gegensatz zu Droiden im vollen Minifigur-Maßstab bieten Mini-Builds wie dieser Treadwell Hintergrundatmosphäre und technische Details, ohne so viel Display-Platz zu verbrauchen. Mini-Droiden wurden in verschiedenen Tatooine-Sets und als Zubehörteile in größeren Builds aus den 2010er Jahren veröffentlicht und fügen Umwelt-Storytelling hinzu. Sammler schätzen Mini-Droiden-Builds für die Bevölkerung von Werkstattszenen, das Hinzufügen von Wartungsdetails zu Hangarbuchten und die Schaffung realistischer technischer Umgebungen, in denen diese Versorgungsdroiden ihre unscheinbare, aber unverzichtbare Reparaturarbeit an Star-Wars-Orten ausführen würden.',
    fr: 'Le mini droïde Treadwell représente une version à plus petite échelle du droïde de service WED-15 vu en train d\'entretenir l\'équipement dans les fermes d\'humidité et dans toute la galaxie Star Wars. Cette mini-construction LEGO présente un design compact avec la coloration blanche et rouge caractéristique, des détails imprimés de base suggérant les capteurs et outils du droïde, et un facteur de forme miniaturisé qui s\'adapte aux côtés des minifigurines standard. Contrairement aux droïdes à l\'échelle complète des minifigurines, les mini-constructions comme ce Treadwell fournissent une atmosphère d\'arrière-plan et des détails techniques sans consommer autant d\'espace d\'affichage. Sortis dans divers sets sur le thème de Tatooine et comme pièces d\'accessoires dans des constructions plus grandes des années 2010, les mini-droïdes ajoutent une narration environnementale. Les collectionneurs apprécient les mini-constructions de droïdes pour peupler les scènes d\'atelier, ajouter des détails de maintenance aux baies de hangar et créer des environnements techniques réalistes où ces droïdes utilitaires effectueraient leur travail de réparation ingrat mais essentiel dans les lieux Star Wars.',
    es: 'El mini droide Treadwell representa una versión a menor escala del droide de servicio WED-15 visto manteniendo equipo en granjas de humedad y en toda la galaxia de Star Wars. Esta mini construcción LEGO presenta un diseño compacto con la coloración blanca y roja característica, detalles impresos básicos que sugieren los sensores y herramientas del droide, y un factor de forma miniaturizado que encaja junto a minifiguras estándar. A diferencia de los droides a escala completa de minifigura, las mini construcciones como este Treadwell proporcionan atmósfera de fondo y detalle técnico sin consumir tanto espacio de exhibición. Lanzados en varios sets temáticos de Tatooine y como piezas accesorias en construcciones más grandes de la década de 2010, los mini droides añaden narración ambiental. Los coleccionistas valoran las mini construcciones de droides por poblar escenas de taller, añadir detalles de mantenimiento a bahías de hangar y crear ambientes técnicos realistas donde estos droides de utilidad realizarían su trabajo de reparación poco glamuroso pero esencial en ubicaciones de Star Wars.',
  },
  {
    no: 'sw0588',
    name: 'Spy Droid',
    en: 'The Spy Droid represents the various surveillance and reconnaissance droids used across the Star Wars galaxy for espionage, tracking, and intelligence gathering operations. This LEGO minifigure or build features a design suggesting stealth capabilities, sensor arrays for surveillance work, and the compact form factor characteristic of probe droids. While not specifically identified with a particular faction, spy droids appear in service of both the Empire and various criminal organizations throughout Star Wars media. Released in sets from Star Wars extended universe content and various themed builds, these surveillance units add intrigue and espionage elements to displays. Collectors value spy droids for creating covert operations scenes, adding background detail to criminal underworld displays, and representing the intelligence-gathering operations that operate in the shadows throughout the galaxy, complementing the more visible military forces with subtle surveillance presence.',
    de: 'Der Spionagedroide repräsentiert die verschiedenen Überwachungs- und Aufklärungsdroiden, die in der gesamten Star-Wars-Galaxis für Spionage, Verfolgung und Geheimdienstoperationen eingesetzt werden. Diese LEGO-Minifigur oder Build verfügt über ein Design, das Tarnfähigkeiten andeutet, Sensorfelder für Überwachungsarbeiten und den kompakten Formfaktor, der für Sondendroiden charakteristisch ist. Obwohl nicht speziell mit einer bestimmten Fraktion identifiziert, erscheinen Spionagedroiden im Dienst sowohl des Imperiums als auch verschiedener krimineller Organisationen in den Star-Wars-Medien. Diese Überwachungseinheiten wurden in Sets aus Star-Wars-Extended-Universe-Inhalten und verschiedenen thematischen Builds veröffentlicht und fügen Displays Intrigen- und Spionageelemente hinzu. Sammler schätzen Spionagedroiden für die Schaffung verdeckter Operationsszenen, das Hinzufügen von Hintergrunddetails zu kriminellen Unterwelt-Displays und die Darstellung der Geheimdienstoperationen, die im Schatten der gesamten Galaxis operieren und die sichtbareren Militärkräfte mit subtiler Überwachungspräsenz ergänzen.',
    fr: 'Le Droïde espion représente les divers droïdes de surveillance et de reconnaissance utilisés dans toute la galaxie Star Wars pour l\'espionnage, le suivi et les opérations de collecte de renseignements. Cette minifigurine ou construction LEGO présente un design suggérant des capacités de furtivité, des réseaux de capteurs pour le travail de surveillance et le facteur de forme compact caractéristique des droïdes sondes. Bien que non spécifiquement identifié avec une faction particulière, les droïdes espions apparaissent au service de l\'Empire et de diverses organisations criminelles dans les médias Star Wars. Sortis dans des sets de contenu de l\'univers étendu Star Wars et diverses constructions thématiques, ces unités de surveillance ajoutent des éléments d\'intrigue et d\'espionnage aux affichages. Les collectionneurs apprécient les droïdes espions pour créer des scènes d\'opérations secrètes, ajouter des détails d\'arrière-plan aux affichages du monde criminel et représenter les opérations de collecte de renseignements qui opèrent dans l\'ombre à travers la galaxie, complétant les forces militaires plus visibles avec une présence de surveillance subtile.',
    es: 'El Droide Espía representa los diversos droides de vigilancia y reconocimiento utilizados en toda la galaxia de Star Wars para operaciones de espionaje, rastreo y recopilación de inteligencia. Esta minifigura o construcción LEGO presenta un diseño que sugiere capacidades de sigilo, matrices de sensores para trabajo de vigilancia y el factor de forma compacto característico de los droides de sonda. Aunque no está específicamente identificado con una facción particular, los droides espías aparecen al servicio tanto del Imperio como de varias organizaciones criminales en los medios de Star Wars. Lanzados en sets de contenido del universo extendido de Star Wars y varias construcciones temáticas, estas unidades de vigilancia añaden elementos de intriga y espionaje a las exhibiciones. Los coleccionistas valoran los droides espías por crear escenas de operaciones encubiertas, añadir detalles de fondo a exhibiciones del hampa criminal y representar las operaciones de recopilación de inteligencia que operan en las sombras en toda la galaxia, complementando las fuerzas militares más visibles con presencia de vigilancia sutil.',
  },
];

async function saveBatch() {
  console.log('Starting batch save for sw0583-sw0588...');

  for (const minifig of batch) {
    try {
      await prisma.minifigCatalog.update({
        where: { minifigure_no: minifig.no },
        data: {
          description_en: minifig.en,
          description_de: minifig.de,
          description_fr: minifig.fr,
          description_es: minifig.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        }
      });
      console.log(`✓ Saved ${minifig.no}: ${minifig.name}`);
    } catch (error: any) {
      console.error(`✗ Error saving ${minifig.no}:`, error.message);
    }
  }

  console.log('Batch complete! 6 minifigs saved.');
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
