import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasources: {
    db: {
      url: process.env.DATABASE_URL,
    },
  },
});

interface MinifigDescription {
  minifigure_no: string;
  description_en: string;
  description_de: string;
  description_fr: string;
  description_es: string;
}

const descriptions: MinifigDescription[] = [
  {
    minifigure_no: 'sw1011',
    description_en: 'General Leia in her dark tan turtleneck with detailed vest represents the seasoned Resistance leader in the sequel trilogy era. This mature costume reflects decades of military leadership and her elevated rank coordinating Resistance operations. The detailed vest printing shows her practical command attire worn while directing fleet movements. An essential minifigure for collectors building Resistance command centers and honoring Leia\'s lifelong dedication to fighting tyranny.',
    description_de: 'General Leia in ihrem dunkelbraunen Rollkragenpullover mit detaillierter Weste repräsentiert die erfahrene Widerstandsführerin in der Ära der Sequel-Trilogie. Dieses reife Kostüm spiegelt Jahrzehnte militärischer Führung und ihren erhöhten Rang bei der Koordinierung von Widerstandsoperationen wider. Der detaillierte Westendruck zeigt ihre praktische Kommandokleidung, die sie beim Leiten von Flottenbewegungen trug. Eine unverzichtbare Minifigur für Sammler, die Widerstands-Kommandozentren aufbauen und Leias lebenslange Hingabe im Kampf gegen Tyrannei ehren.',
    description_fr: 'La Générale Leia dans son col roulé beige foncé avec gilet détaillé représente la leader de la Résistance chevronnée dans l\'ère de la trilogie suite. Ce costume mature reflète des décennies de leadership militaire et son rang élevé coordonnant les opérations de la Résistance. L\'impression détaillée du gilet montre sa tenue de commandement pratique portée lors de la direction des mouvements de flotte. Une figurine essentielle pour les collectionneurs construisant des centres de commandement de la Résistance et honorant le dévouement de toute une vie de Leia à combattre la tyrannie.',
    description_es: 'La General Leia en su cuello de tortuga color bronceado oscuro con chaleco detallado representa a la experimentada líder de la Resistencia en la era de la trilogía secuela. Este vestuario maduro refleja décadas de liderazgo militar y su rango elevado coordinando operaciones de la Resistencia. La impresión detallada del chaleco muestra su atuendo de comando práctico usado mientras dirigía movimientos de flota. Una minifigura esencial para coleccionistas que construyen centros de comando de la Resistencia y honran la dedicación de toda la vida de Leia a luchar contra la tiranía.'
  },
  {
    minifigure_no: 'sw1012',
    description_en: 'Kaz Xiono is the young Resistance spy and skilled pilot from the Star Wars Resistance animated series who infiltrated the Colossus platform. This enthusiastic character evolved from privileged racer to committed freedom fighter under Poe Dameron\'s mentorship. His journey provides insight into how the Resistance recruited and trained new operatives before the sequel trilogy events. A key character for collectors of the Resistance animated series and the next generation of Resistance heroes.',
    description_de: 'Kaz Xiono ist der junge Widerstandsspion und geschickte Pilot aus der Star Wars Resistance-Animationsserie, der die Colossus-Plattform infiltrierte. Dieser enthusiastische Charakter entwickelte sich von privilegiertem Rennfahrer zu engagiertem Freiheitskämpfer unter Poe Damerons Mentorschaft. Seine Reise bietet Einblick, wie der Widerstand neue Agenten rekrutierte und trainierte vor den Ereignissen der Sequel-Trilogie. Ein Schlüsselcharakter für Sammler der Resistance-Animationsserie und der nächsten Generation von Widerstandshelden.',
    description_fr: 'Kaz Xiono est le jeune espion de la Résistance et pilote qualifié de la série animée Star Wars Resistance qui a infiltré la plateforme Colossus. Ce personnage enthousiaste a évolué de coureur privilégié à combattant de la liberté engagé sous le mentorat de Poe Dameron. Son parcours donne un aperçu de la façon dont la Résistance recrutait et formait de nouveaux agents avant les événements de la trilogie suite. Un personnage clé pour les collectionneurs de la série animée Resistance et de la prochaine génération de héros de la Résistance.',
    description_es: 'Kaz Xiono es el joven espía de la Resistencia y hábil piloto de la serie animada Star Wars Resistance que se infiltró en la plataforma Colossus. Este entusiasta personaje evolucionó de corredor privilegiado a luchador por la libertad comprometido bajo la tutoría de Poe Dameron. Su viaje proporciona información sobre cómo la Resistencia reclutó y entrenó nuevos operativos antes de los eventos de la trilogía secuela. Un personaje clave para coleccionistas de la serie animada Resistance y la próxima generación de héroes de la Resistencia.'
  },
  {
    minifigure_no: 'sw1013',
    description_en: 'R1-J5, nicknamed "Bucket," is Kaz Xiono\'s loyal astromech droid companion from Star Wars Resistance. This droid\'s distinctive appearance and personality made it a beloved character in the animated series. Bucket provided technical support and comic relief throughout Kaz\'s adventures on the Colossus platform. A charming droid character for collectors of the Resistance series and memorable astromech variants.',
    description_de: 'R1-J5, genannt „Bucket", ist Kaz Xionos loyaler Astromech-Droiden-Begleiter aus Star Wars Resistance. Das markante Erscheinungsbild und die Persönlichkeit dieses Droiden machten ihn zu einem beliebten Charakter in der Animationsserie. Bucket bot technische Unterstützung und komische Erleichterung während Kaz\' Abenteuern auf der Colossus-Plattform. Ein charmanter Droidencharakter für Sammler der Resistance-Serie und unvergesslicher Astromech-Varianten.',
    description_fr: 'R1-J5, surnommé « Bucket », est le compagnon droïde astromech fidèle de Kaz Xiono de Star Wars Resistance. L\'apparence et la personnalité distinctives de ce droïde en ont fait un personnage bien-aimé de la série animée. Bucket a fourni un soutien technique et un soulagement comique tout au long des aventures de Kaz sur la plateforme Colossus. Un personnage droïde charmant pour les collectionneurs de la série Resistance et des variantes astromech mémorables.',
    description_es: 'R1-J5, apodado "Bucket", es el leal droide astromecánico compañero de Kaz Xiono de Star Wars Resistance. La distintiva apariencia y personalidad de este droide lo convirtieron en un personaje querido en la serie animada. Bucket proporcionó soporte técnico y alivio cómico a lo largo de las aventuras de Kaz en la plataforma Colossus. Un encantador personaje droide para coleccionistas de la serie Resistance y variantes astromecánicas memorables.'
  },
  {
    minifigure_no: 'sw1014',
    description_en: 'This Hoth Rebel Trooper with white beard represents the diverse ages and backgrounds of soldiers who defended Echo Base. The facial features add personality and realism to the Rebel defensive forces. These seasoned veterans brought valuable combat experience to the desperate defense of the frozen base. An important variant for collectors building realistic Rebel military displays with varied trooper appearances and ages.',
    description_de: 'Dieser Hoth-Rebellentrooper mit weißem Bart repräsentiert die vielfältigen Altersgruppen und Hintergründe der Soldaten, die Echo-Basis verteidigten. Die Gesichtszüge verleihen den Rebellen-Verteidigungskräften Persönlichkeit und Realismus. Diese erfahrenen Veteranen brachten wertvolle Kampferfahrung in die verzweifelte Verteidigung der gefrorenen Basis. Eine wichtige Variante für Sammler, die realistische Rebellen-Militärdisplays mit variierten Trooper-Erscheinungen und Altersgruppen aufbauen.',
    description_fr: 'Ce soldat rebelle de Hoth avec barbe blanche représente les âges et origines divers des soldats qui ont défendu la Base Echo. Les traits faciaux ajoutent de la personnalité et du réalisme aux forces défensives rebelles. Ces vétérans chevronnés ont apporté une expérience de combat précieuse à la défense désespérée de la base gelée. Une variante importante pour les collectionneurs construisant des présentations militaires rebelles réalistes avec des apparences et âges de soldats variés.',
    description_es: 'Este Soldado Rebelde de Hoth con barba blanca representa las diversas edades y orígenes de soldados que defendieron la Base Echo. Los rasgos faciales añaden personalidad y realismo a las fuerzas defensivas rebeldes. Estos veteranos experimentados aportaron valiosa experiencia de combate a la desesperada defensa de la base congelada. Una variante importante para coleccionistas que construyen exhibiciones militares rebeldes realistas con apariencias y edades variadas de soldados.'
  },
  {
    minifigure_no: 'sw1015',
    description_en: 'This Hoth Rebel Trooper with frown expression captures the grim determination of defenders facing overwhelming Imperial forces. The facial expression reflects the desperate circumstances during the Battle of Hoth. These troops maintained discipline and courage despite knowing the base evacuation was their only hope. A character piece that adds emotional depth to Hoth battle displays and represents the Rebellion\'s fighting spirit under pressure.',
    description_de: 'Dieser Hoth-Rebellentrooper mit Stirnrunzeln erfasst die grimmige Entschlossenheit der Verteidiger, die überwältigenden imperialen Kräften gegenüberstehen. Der Gesichtsausdruck spiegelt die verzweifelten Umstände während der Schlacht von Hoth wider. Diese Truppen behielten Disziplin und Mut bei, obwohl sie wussten, dass die Basen-Evakuierung ihre einzige Hoffnung war. Ein Charakterstück, das Hoth-Schlachtdisplays emotionale Tiefe verleiht und den Kampfgeist der Rebellion unter Druck repräsentiert.',
    description_fr: 'Ce soldat rebelle de Hoth avec expression de froncement capture la détermination sinistre des défenseurs face aux forces impériales écrasantes. L\'expression faciale reflète les circonstances désespérées lors de la bataille de Hoth. Ces troupes ont maintenu la discipline et le courage malgré le fait qu\'elles savaient que l\'évacuation de la base était leur seul espoir. Une pièce de personnage qui ajoute de la profondeur émotionnelle aux présentations de bataille de Hoth et représente l\'esprit combatif de la Rébellion sous pression.',
    description_es: 'Este Soldado Rebelde de Hoth con expresión de ceño fruncido captura la sombría determinación de defensores enfrentando abrumadoras fuerzas imperiales. La expresión facial refleja las circunstancias desesperadas durante la Batalla de Hoth. Estas tropas mantuvieron disciplina y coraje a pesar de saber que la evacuación de la base era su única esperanza. Una pieza de personaje que añade profundidad emocional a exhibiciones de batalla de Hoth y representa el espíritu de lucha de la Rebelión bajo presión.'
  },
  {
    minifigure_no: 'sw1016',
    description_en: 'This Hoth Rebel Trooper with open mouth smile represents the camaraderie and optimism maintained by Rebel forces even in dire circumstances. The cheerful expression captures moments of levity between the defenders during the tense evacuation. This variant reminds collectors that the Rebellion\'s strength came from hope and fellowship as much as military might. A uplifting character piece for balanced Rebel military displays showing varied emotional states.',
    description_de: 'Dieser Hoth-Rebellentrooper mit offenem Mundlächeln repräsentiert die Kameradschaft und den Optimismus, den die Rebellenkräfte selbst unter schlimmen Umständen aufrechterhielten. Der fröhliche Ausdruck erfasst Momente der Leichtigkeit zwischen den Verteidigern während der angespannten Evakuierung. Diese Variante erinnert Sammler daran, dass die Stärke der Rebellion ebenso von Hoffnung und Kameradschaft kam wie von militärischer Macht. Ein aufheiterndes Charakterstück für ausgewogene Rebellen-Militärdisplays, die verschiedene emotionale Zustände zeigen.',
    description_fr: 'Ce soldat rebelle de Hoth avec sourire bouche ouverte représente la camaraderie et l\'optimisme maintenus par les forces rebelles même dans des circonstances désastreuses. L\'expression joyeuse capture des moments de légèreté entre les défenseurs pendant l\'évacuation tendue. Cette variante rappelle aux collectionneurs que la force de la Rébellion venait autant de l\'espoir et de la fraternité que de la puissance militaire. Une pièce de personnage édifiante pour des présentations militaires rebelles équilibrées montrant des états émotionnels variés.',
    description_es: 'Este Soldado Rebelde de Hoth con sonrisa de boca abierta representa la camaradería y optimismo mantenidos por las fuerzas rebeldes incluso en circunstancias terribles. La expresión alegre captura momentos de ligereza entre los defensores durante la tensa evacuación. Esta variante recuerda a los coleccionistas que la fuerza de la Rebelión venía tanto de la esperanza y compañerismo como del poderío militar. Una pieza de personaje edificante para exhibiciones militares rebeldes equilibradas mostrando estados emocionales variados.'
  },
  {
    minifigure_no: 'sw1017',
    description_en: 'The Imperial Probe Droid with black sensors and octagonal frame represents the Empire\'s sophisticated reconnaissance technology that discovered Echo Base\'s location. This updated design with single bar frame provides enhanced stability and screen accuracy. These automated scouts transmitted vital intelligence before self-destructing to prevent capture. An iconic piece for collectors building Hoth scenes and representing the technological superiority that made the Empire so formidable.',
    description_de: 'Die imperiale Sondendroide mit schwarzen Sensoren und achteckigem Rahmen repräsentiert die ausgeklügelte Aufklärungstechnologie des Imperiums, die den Standort der Echo-Basis entdeckte. Dieses aktualisierte Design mit Einzelstangen-Rahmen bietet verbesserte Stabilität und Bildschirmgenauigkeit. Diese automatisierten Späher übermittelten wichtige Informationen, bevor sie sich selbst zerstörten, um eine Gefangennahme zu verhindern. Ein ikonisches Stück für Sammler, die Hoth-Szenen aufbauen und die technologische Überlegenheit repräsentieren, die das Imperium so beeindruckend machte.',
    description_fr: 'Le droïde sonde impérial avec capteurs noirs et cadre octogonal représente la technologie de reconnaissance sophistiquée de l\'Empire qui a découvert l\'emplacement de la Base Echo. Cette conception mise à jour avec cadre à barre unique offre une stabilité et une précision d\'écran améliorées. Ces éclaireurs automatisés transmettaient des renseignements vitaux avant de s\'autodétruire pour empêcher la capture. Une pièce iconique pour les collectionneurs construisant des scènes de Hoth et représentant la supériorité technologique qui rendait l\'Empire si formidable.',
    description_es: 'El Droide Sonda Imperial con sensores negros y marco octagonal representa la sofisticada tecnología de reconocimiento del Imperio que descubrió la ubicación de la Base Echo. Este diseño actualizado con marco de barra única proporciona estabilidad y precisión de pantalla mejoradas. Estos exploradores automatizados transmitieron inteligencia vital antes de autodestruirse para evitar captura. Una pieza icónica para coleccionistas que construyen escenas de Hoth y representan la superioridad tecnológica que hizo al Imperio tan formidable.'
  },
  {
    minifigure_no: 'sw1018',
    description_en: 'Griff Halloran is the skilled First Order TIE fighter pilot from Star Wars Resistance who operated undercover on the Colossus platform. This antagonist represented the First Order\'s infiltration tactics and espionage operations before their open military campaign. His character added tension to the Resistance series as a hidden threat among the racing community. A valuable character for collectors of the Resistance animated series and First Order operatives.',
    description_de: 'Griff Halloran ist der geschickte Erste Ordnung-TIE-Jägerpilot aus Star Wars Resistance, der verdeckt auf der Colossus-Plattform operierte. Dieser Antagonist repräsentierte die Infiltrationstaktiken und Spionageoperationen der Ersten Ordnung vor ihrer offenen Militärkampagne. Sein Charakter fügte der Resistance-Serie Spannung hinzu als versteckte Bedrohung innerhalb der Renngemeinschaft. Ein wertvoller Charakter für Sammler der Resistance-Animationsserie und Erste Ordnung-Agenten.',
    description_fr: 'Griff Halloran est le pilote de chasseur TIE qualifié du Premier Ordre de Star Wars Resistance qui opérait en couverture sur la plateforme Colossus. Cet antagoniste représentait les tactiques d\'infiltration et les opérations d\'espionnage du Premier Ordre avant leur campagne militaire ouverte. Son personnage a ajouté de la tension à la série Resistance en tant que menace cachée parmi la communauté de course. Un personnage précieux pour les collectionneurs de la série animée Resistance et des agents du Premier Ordre.',
    description_es: 'Griff Halloran es el hábil piloto de caza TIE de la Primera Orden de Star Wars Resistance que operó encubierto en la plataforma Colossus. Este antagonista representó las tácticas de infiltración y operaciones de espionaje de la Primera Orden antes de su campaña militar abierta. Su personaje añadió tensión a la serie Resistance como una amenaza oculta entre la comunidad de carreras. Un personaje valioso para coleccionistas de la serie animada Resistance y operativos de la Primera Orden.'
  },
  {
    minifigure_no: 'sw1019',
    description_en: 'This Poe Dameron variant in pilot jumpsuit without belts and pipe shows a simplified version of the Resistance\'s best pilot. The cleaner design maintains Poe\'s recognizable appearance while offering a streamlined minifigure construction. This variant represents Poe during various flight operations throughout the sequel trilogy. A practical variant for collectors building multiple X-wing cockpits and Resistance pilot displays.',
    description_de: 'Diese Poe Dameron-Variante im Pilotenoverall ohne Gürtel und Rohr zeigt eine vereinfachte Version des besten Piloten des Widerstands. Das sauberere Design behält Poes erkennbares Erscheinungsbild bei, während es eine stromlinienförmige Minifigurkonstruktion bietet. Diese Variante repräsentiert Poe während verschiedener Flugoperationen in der gesamten Sequel-Trilogie. Eine praktische Variante für Sammler, die mehrere X-Flügler-Cockpits und Widerstandspiloten-Displays aufbauen.',
    description_fr: 'Cette variante de Poe Dameron en combinaison de pilote sans ceintures ni tuyau montre une version simplifiée du meilleur pilote de la Résistance. Le design plus épuré maintient l\'apparence reconnaissable de Poe tout en offrant une construction de figurine rationalisée. Cette variante représente Poe lors de diverses opérations de vol tout au long de la trilogie suite. Une variante pratique pour les collectionneurs construisant plusieurs cockpits X-wing et des présentations de pilotes de la Résistance.',
    description_es: 'Esta variante de Poe Dameron en mono de piloto sin cinturones ni tubería muestra una versión simplificada del mejor piloto de la Resistencia. El diseño más limpio mantiene la apariencia reconocible de Poe mientras ofrece una construcción de minifigura simplificada. Esta variante representa a Poe durante varias operaciones de vuelo a lo largo de la trilogía secuela. Una variante práctica para coleccionistas que construyen múltiples cabinas de X-wing y exhibiciones de pilotos de la Resistencia.'
  },
  {
    minifigure_no: 'sw1020',
    description_en: 'Zuckuss is the Gand bounty hunter who partnered with 4-LOM, known for his mystical findsman traditions and breathing apparatus. This distinctive alien bounty hunter was one of the specialists hired by Darth Vader to track the Millennium Falcon. His unique appearance with insect-like features and specialized equipment makes him instantly recognizable. A highly collectible character for completing the Empire Strikes Back bounty hunter lineup and representing diverse alien species.',
    description_de: 'Zuckuss ist der Gand-Kopfgeldjäger, der mit 4-LOM zusammenarbeitete, bekannt für seine mystischen Findsman-Traditionen und sein Atemgerät. Dieser markante außerirdische Kopfgeldjäger war einer der Spezialisten, die von Darth Vader angeheuert wurden, um den Millennium Falken zu verfolgen. Sein einzigartiges Erscheinungsbild mit insektenähnlichen Zügen und spezialisierter Ausrüstung macht ihn sofort erkennbar. Ein sehr sammelwerter Charakter für die Vervollständigung der Das Imperium schlägt zurück-Kopfgeldjäger-Aufstellung und zur Repräsentation vielfältiger außerirdischer Spezies.',
    description_fr: 'Zuckuss est le chasseur de primes Gand qui s\'est associé à 4-LOM, connu pour ses traditions mystiques de findsman et son appareil respiratoire. Ce chasseur de primes alien distinctif était l\'un des spécialistes embauchés par Dark Vador pour traquer le Faucon Millenium. Son apparence unique avec des traits d\'insecte et un équipement spécialisé le rend instantanément reconnaissable. Un personnage très collectionnable pour compléter la gamme de chasseurs de primes de L\'Empire contre-attaque et représenter diverses espèces aliens.',
    description_es: 'Zuckuss es el cazarrecompensas Gand que se asoció con 4-LOM, conocido por sus tradiciones místicas de rastreador y aparato respiratorio. Este distintivo cazarrecompensas alienígena fue uno de los especialistas contratados por Darth Vader para rastrear al Halcón Milenario. Su apariencia única con características similares a insectos y equipo especializado lo hace instantáneamente reconocible. Un personaje altamente coleccionable para completar la alineación de cazarrecompensas de El Imperio Contraataca y representar diversas especies alienígenas.'
  },
  {
    minifigure_no: 'sw1021',
    description_en: 'This Han Solo variant with wavy hair and dual-sided face printing captures the smuggler\'s characteristic charisma with both smile and frown expressions. The dark blue jacket over brown legs with holster pattern represents Han\'s iconic costume throughout the original trilogy. The expressive face printing allows collectors to display Han\'s emotional range from confident swagger to serious determination. A versatile and essential Han Solo variant for multiple display scenarios.',
    description_de: 'Diese Han Solo-Variante mit welligem Haar und zweiseitigem Gesichtsdruck erfasst das charakteristische Charisma des Schmugglers mit Lächel- und Stirnrunzel-Ausdrücken. Die dunkelblaue Jacke über braunen Beinen mit Holster-Muster repräsentiert Hans ikonisches Kostüm in der gesamten Originaltrilogie. Der ausdrucksstarke Gesichtsdruck ermöglicht es Sammlern, Hans emotionale Bandbreite von selbstbewusster Prahlerei bis ernster Entschlossenheit anzuzeigen. Eine vielseitige und unverzichtbare Han Solo-Variante für mehrere Display-Szenarien.',
    description_fr: 'Cette variante de Han Solo avec cheveux ondulés et impression de visage double face capture le charisme caractéristique du contrebandier avec des expressions de sourire et de froncement. La veste bleu foncé sur des jambes brunes avec motif d\'étui représente le costume iconique de Han tout au long de la trilogie originale. L\'impression de visage expressive permet aux collectionneurs d\'afficher la gamme émotionnelle de Han de la fanfaronnade confiante à la détermination sérieuse. Une variante de Han Solo polyvalente et essentielle pour plusieurs scénarios d\'affichage.',
    description_es: 'Esta variante de Han Solo con cabello ondulado e impresión de cara de doble cara captura el carisma característico del contrabandista con expresiones de sonrisa y ceño fruncido. La chaqueta azul oscuro sobre piernas marrones con patrón de funda representa el vestuario icónico de Han a lo largo de la trilogía original. La impresión de cara expresiva permite a los coleccionistas mostrar el rango emocional de Han desde confianza fanfarrona hasta determinación seria. Una variante versátil y esencial de Han Solo para múltiples escenarios de exhibición.'
  },
  {
    minifigure_no: 'sw1022',
    description_en: 'This 20th Anniversary Princess Leia in white ceremonial dress features classic yellow head and hands with special anniversary torso printing. This commemorative variant celebrates two decades of LEGO Star Wars with gold "20" printing. The simplified belt design and yellow coloring reference early LEGO minifigure aesthetics. A special collectible marking a milestone in LEGO Star Wars history and honoring the line\'s origins.',
    description_de: 'Diese 20-jähriges Jubiläum-Prinzessin Leia im weißen Zeremonienkleid zeigt klassischen gelben Kopf und Hände mit speziellem Jubiläums-Torsodruck. Diese Gedächtnisvariante feiert zwei Jahrzehnte LEGO Star Wars mit goldenem „20"-Druck. Das vereinfachte Gürteldesign und die gelbe Färbung verweisen auf frühe LEGO-Minifigur-Ästhetik. Ein besonderes Sammlerstück, das einen Meilenstein in der LEGO Star Wars-Geschichte markiert und die Ursprünge der Linie ehrt.',
    description_fr: 'Cette Princesse Leia du 20e anniversaire en robe de cérémonie blanche présente une tête et des mains jaunes classiques avec une impression de torse d\'anniversaire spéciale. Cette variante commémorative célèbre deux décennies de LEGO Star Wars avec une impression dorée « 20 ». Le design de ceinture simplifié et la coloration jaune font référence à l\'esthétique des premières figurines LEGO. Un objet de collection spécial marquant une étape importante dans l\'histoire LEGO Star Wars et honorant les origines de la gamme.',
    description_es: 'Esta Princesa Leia del 20° Aniversario en vestido ceremonial blanco presenta cabeza y manos amarillas clásicas con impresión especial de torso de aniversario. Esta variante conmemorativa celebra dos décadas de LEGO Star Wars con impresión dorada "20". El diseño de cinturón simplificado y coloración amarilla hace referencia a la estética temprana de minifiguras LEGO. Un coleccionable especial que marca un hito en la historia de LEGO Star Wars y honra los orígenes de la línea.'
  },
  {
    minifigure_no: 'sw1023',
    description_en: 'Young Padmé Naberrie with medium legs represents the future Queen and Senator as a child on Naboo before her political career. This innocent version captures Padmé before the tumultuous events that would define her life. The child-sized minifigure format makes this a distinctive addition to Padmé\'s character evolution. A charming piece for collectors tracking Padmé\'s journey from child to galactic leader.',
    description_de: 'Die junge Padmé Naberrie mit mittleren Beinen repräsentiert die zukünftige Königin und Senatorin als Kind auf Naboo vor ihrer politischen Karriere. Diese unschuldige Version erfasst Padmé vor den turbulenten Ereignissen, die ihr Leben definieren würden. Das Minifigurformat in Kindergröße macht dies zu einer markanten Ergänzung zu Padmés Charakterentwicklung. Ein charmantes Stück für Sammler, die Padmés Reise vom Kind zur galaktischen Führerin verfolgen.',
    description_fr: 'La jeune Padmé Naberrie avec jambes moyennes représente la future Reine et Sénatrice en tant qu\'enfant sur Naboo avant sa carrière politique. Cette version innocente capture Padmé avant les événements tumultueux qui définiraient sa vie. Le format de figurine de taille enfant en fait un ajout distinctif à l\'évolution du personnage de Padmé. Une pièce charmante pour les collectionneurs suivant le parcours de Padmé d\'enfant à leader galactique.',
    description_es: 'La joven Padmé Naberrie con piernas medianas representa a la futura Reina y Senadora como niña en Naboo antes de su carrera política. Esta versión inocente captura a Padmé antes de los tumultuosos eventos que definirían su vida. El formato de minifigura de tamaño infantil hace de esta una adición distintiva a la evolución del personaje de Padmé. Una pieza encantadora para coleccionistas que siguen el viaje de Padmé de niña a líder galáctica.'
  },
  {
    minifigure_no: 'sw1024',
    description_en: 'This 20th Anniversary Luke Skywalker pilot variant features commemorative torso printing celebrating two decades of LEGO Star Wars. The special gold "20" marking makes this a distinctive collectible honoring the line\'s milestone. This variant combines Luke\'s classic pilot appearance with anniversary edition exclusivity. An essential piece for collectors of LEGO Star Wars anniversary sets and commemorative editions.',
    description_de: 'Diese 20-jähriges Jubiläum-Luke Skywalker-Pilotenvariante zeigt Gedenk-Torsodruck, der zwei Jahrzehnte LEGO Star Wars feiert. Die spezielle goldene „20"-Markierung macht dies zu einem markanten Sammlerstück, das den Meilenstein der Linie ehrt. Diese Variante kombiniert Lukes klassisches Pilotenerscheinungsbild mit Jubiläumsausgaben-Exklusivität. Ein unverzichtbares Stück für Sammler von LEGO Star Wars-Jubiläumssets und Gedenkausgaben.',
    description_fr: 'Cette variante de pilote Luke Skywalker du 20e anniversaire présente une impression de torse commémorative célébrant deux décennies de LEGO Star Wars. Le marquage doré spécial « 20 » en fait un objet de collection distinctif honorant l\'étape importante de la gamme. Cette variante combine l\'apparence de pilote classique de Luke avec l\'exclusivité de l\'édition anniversaire. Une pièce essentielle pour les collectionneurs d\'ensembles d\'anniversaire LEGO Star Wars et d\'éditions commémoratives.',
    description_es: 'Esta variante de piloto de Luke Skywalker del 20° Aniversario presenta impresión de torso conmemorativa celebrando dos décadas de LEGO Star Wars. La marca dorada especial "20" hace de esta un coleccionable distintivo que honra el hito de la línea. Esta variante combina la apariencia clásica de piloto de Luke con exclusividad de edición de aniversario. Una pieza esencial para coleccionistas de sets de aniversario de LEGO Star Wars y ediciones conmemorativas.'
  },
  {
    minifigure_no: 'sw1025',
    description_en: 'Dak Ralter was Luke Skywalker\'s gunner aboard his snowspeeder during the Battle of Hoth. This variant features detailed jumpsuit printing with pockets and three bullets on the right leg. Dak\'s tragic death during the AT-AT attack made him a memorable character despite limited screen time. An important minifigure for collectors building Luke\'s snowspeeder crew and honoring fallen Rebel heroes.',
    description_de: 'Dak Ralter war Luke Skywalkers Schütze an Bord seines Snowspeeders während der Schlacht von Hoth. Diese Variante zeigt detaillierten Overall-Druck mit Taschen und drei Kugeln am rechten Bein. Daks tragischer Tod während des AT-AT-Angriffs machte ihn trotz begrenzter Bildschirmzeit zu einem unvergesslichen Charakter. Eine wichtige Minifigur für Sammler, die Lukes Snowspeeder-Crew aufbauen und gefallene Rebellenhelden ehren.',
    description_fr: 'Dak Ralter était le mitrailleur de Luke Skywalker à bord de son snowspeeder lors de la bataille de Hoth. Cette variante présente une impression de combinaison détaillée avec des poches et trois balles sur la jambe droite. La mort tragique de Dak lors de l\'attaque AT-AT en a fait un personnage mémorable malgré un temps d\'écran limité. Une figurine importante pour les collectionneurs construisant l\'équipage de snowspeeder de Luke et honorant les héros rebelles tombés.',
    description_es: 'Dak Ralter fue el artillero de Luke Skywalker a bordo de su deslizador de nieve durante la Batalla de Hoth. Esta variante presenta impresión detallada de mono con bolsillos y tres balas en la pierna derecha. La trágica muerte de Dak durante el ataque AT-AT lo convirtió en un personaje memorable a pesar del tiempo limitado en pantalla. Una minifigura importante para coleccionistas que construyen la tripulación del deslizador de nieve de Luke y honran a héroes rebeldes caídos.'
  },
  {
    minifigure_no: 'sw1026',
    description_en: 'This Hoth Rebel Trooper with backpack and cheek lines represents the field-equipped defenders manning defensive positions during the Imperial assault. The distinctive facial features and equipment loadout add realism to Rebel military displays. The backpack signifies troops preparing for the base evacuation. A detailed variant for collectors building comprehensive Hoth defensive positions with properly equipped soldiers.',
    description_de: 'Dieser Hoth-Rebellentrooper mit Rucksack und Wangenlinien repräsentiert die feldausgerüsteten Verteidiger, die während des imperialen Angriffs Verteidigungspositionen besetzen. Die markanten Gesichtszüge und Ausrüstungsausstattung verleihen Rebellen-Militärdisplays Realismus. Der Rucksack signalisiert Truppen, die sich auf die Basen-Evakuierung vorbereiten. Eine detaillierte Variante für Sammler, die umfassende Hoth-Verteidigungspositionen mit ordnungsgemäß ausgerüsteten Soldaten aufbauen.',
    description_fr: 'Ce soldat rebelle de Hoth avec sac à dos et lignes de joue représente les défenseurs équipés sur le terrain occupant des positions défensives lors de l\'assaut impérial. Les traits faciaux distinctifs et la charge d\'équipement ajoutent du réalisme aux présentations militaires rebelles. Le sac à dos signifie les troupes se préparant à l\'évacuation de la base. Une variante détaillée pour les collectionneurs construisant des positions défensives complètes de Hoth avec des soldats correctement équipés.',
    description_es: 'Este Soldado Rebelde de Hoth con mochila y líneas de mejilla representa a los defensores equipados de campo que ocupan posiciones defensivas durante el asalto Imperial. Los rasgos faciales distintivos y carga de equipo añaden realismo a exhibiciones militares rebeldes. La mochila significa tropas preparándose para la evacuación de la base. Una variante detallada para coleccionistas que construyen posiciones defensivas completas de Hoth con soldados debidamente equipados.'
  },
  {
    minifigure_no: 'sw1027',
    description_en: 'This 20th Anniversary Lando Calrissian variant in Cloud City outfit features commemorative torso printing celebrating LEGO Star Wars\' milestone. The special anniversary marking makes this Baron Administrator version a distinctive collectible. This variant honors Lando\'s pivotal role in The Empire Strikes Back while marking two decades of LEGO Star Wars. An important piece for collectors of anniversary editions and Lando variants.',
    description_de: 'Diese 20-jähriges Jubiläum-Lando Calrissian-Variante im Cloud City-Outfit zeigt Gedenk-Torsodruck, der LEGOs Star Wars-Meilenstein feiert. Die spezielle Jubiläumsmarkierung macht diese Baron-Administrator-Version zu einem markanten Sammlerstück. Diese Variante ehrt Landos entscheidende Rolle in Das Imperium schlägt zurück, während sie zwei Jahrzehnte LEGO Star Wars markiert. Ein wichtiges Stück für Sammler von Jubiläumsausgaben und Lando-Varianten.',
    description_fr: 'Cette variante de Lando Calrissian du 20e anniversaire en tenue de Cloud City présente une impression de torse commémorative célébrant l\'étape importante de LEGO Star Wars. Le marquage d\'anniversaire spécial fait de cette version Baron Administrateur un objet de collection distinctif. Cette variante honore le rôle crucial de Lando dans L\'Empire contre-attaque tout en marquant deux décennies de LEGO Star Wars. Une pièce importante pour les collectionneurs d\'éditions anniversaire et de variantes de Lando.',
    description_es: 'Esta variante de Lando Calrissian del 20° Aniversario en atuendo de Cloud City presenta impresión de torso conmemorativa celebrando el hito de LEGO Star Wars. La marca especial de aniversario hace de esta versión de Barón Administrador un coleccionable distintivo. Esta variante honra el papel crucial de Lando en El Imperio Contraataca mientras marca dos décadas de LEGO Star Wars. Una pieza importante para coleccionistas de ediciones de aniversario y variantes de Lando.'
  },
  {
    minifigure_no: 'sw1028',
    description_en: 'This Wookiee Warrior with dark brown and dark tan fur features printed legs showing traditional Wookiee attire and bandoliers. The detailed leg printing represents the combat-ready warriors who defended Kashyyyk during the Clone Wars. These fierce fighters combined primitive weapons with sophisticated tactics to protect their homeworld. An enhanced Wookiee variant for collectors building the Battle of Kashyyyk and diverse Wookiee warrior displays.',
    description_de: 'Dieser Wookiee-Krieger mit dunkelbraunem und dunkelbraunem Fell zeigt bedruckte Beine, die traditionelle Wookiee-Kleidung und Bandolieren zeigen. Der detaillierte Beindruck repräsentiert die kampfbereiten Krieger, die Kashyyyk während der Klonkriege verteidigten. Diese wilden Kämpfer kombinierten primitive Waffen mit ausgeklügelten Taktiken, um ihre Heimatwelt zu schützen. Eine verbesserte Wookiee-Variante für Sammler, die die Schlacht von Kashyyyk und vielfältige Wookiee-Krieger-Displays aufbauen.',
    description_fr: 'Ce guerrier Wookiee avec fourrure brun foncé et beige foncé présente des jambes imprimées montrant la tenue traditionnelle Wookiee et les bandoulières. L\'impression détaillée des jambes représente les guerriers prêts au combat qui ont défendu Kashyyyk pendant la Guerre des Clones. Ces combattants féroces combinaient des armes primitives avec des tactiques sophistiquées pour protéger leur monde natal. Une variante Wookiee améliorée pour les collectionneurs construisant la bataille de Kashyyyk et diverses présentations de guerriers Wookiees.',
    description_es: 'Este Guerrero Wookiee con pelaje marrón oscuro y bronceado oscuro presenta piernas impresas mostrando atuendo tradicional Wookiee y bandoleras. La impresión detallada de piernas representa a los guerreros listos para el combate que defendieron Kashyyyk durante las Guerras Clon. Estos feroces luchadores combinaron armas primitivas con tácticas sofisticadas para proteger su mundo natal. Una variante Wookiee mejorada para coleccionistas que construyen la Batalla de Kashyyyk y diversas exhibiciones de guerreros Wookiees.'
  },
  {
    minifigure_no: 'sw1029',
    description_en: 'This 20th Anniversary Darth Vader features commemorative torso printing with gold "20" marking celebrating two decades of LEGO Star Wars. This special edition of the franchise\'s most iconic villain honors the line\'s legacy. The anniversary variant combines Vader\'s menacing presence with collectible exclusivity. An essential piece for LEGO Star Wars anniversary collectors and a centerpiece for commemorative displays.',
    description_de: 'Dieser 20-jähriges Jubiläum-Darth Vader zeigt Gedenk-Torsodruck mit goldener „20"-Markierung, der zwei Jahrzehnte LEGO Star Wars feiert. Diese Sonderausgabe des ikonischsten Schurken des Franchise ehrt das Erbe der Linie. Die Jubiläumsvariante kombiniert Vaders bedrohliche Präsenz mit sammlbarer Exklusivität. Ein unverzichtbares Stück für LEGO Star Wars-Jubiläumssammler und ein Herzstück für Gedenkdisplays.',
    description_fr: 'Ce Dark Vador du 20e anniversaire présente une impression de torse commémorative avec marquage doré « 20 » célébrant deux décennies de LEGO Star Wars. Cette édition spéciale du méchant le plus iconique de la franchise honore l\'héritage de la gamme. La variante anniversaire combine la présence menaçante de Vador avec une exclusivité de collection. Une pièce essentielle pour les collectionneurs d\'anniversaire LEGO Star Wars et une pièce maîtresse pour les présentations commémoratives.',
    description_es: 'Este Darth Vader del 20° Aniversario presenta impresión de torso conmemorativa con marca dorada "20" celebrando dos décadas de LEGO Star Wars. Esta edición especial del villano más icónico de la franquicia honra el legado de la línea. La variante de aniversario combina la presencia amenazante de Vader con exclusividad coleccionable. Una pieza esencial para coleccionistas de aniversario de LEGO Star Wars y una pieza central para exhibiciones conmemorativas.'
  },
  {
    minifigure_no: 'sw1030',
    description_en: 'This Dwarf Spider Droid with light bluish gray dome and mini blaster/shooter represents a functional variant optimized for playability. The lighter color scheme and integrated shooter add action features to Clone Wars battle displays. These tactical droids provided mobile firepower for Separatist forces across countless battlefields. A fun and functional variant for collectors who appreciate interactive building elements alongside display pieces.',
    description_de: 'Diese Zwerg-Spinnen-Droide mit hellbläulich-grauer Kuppel und Mini-Blaster/Shooter repräsentiert eine funktionale Variante, die für Spielbarkeit optimiert ist. Das hellere Farbschema und der integrierte Shooter fügen Klonkrieg-Schlachtdisplays Aktionselemente hinzu. Diese taktischen Droiden boten mobile Feuerkraft für Separatistenkräfte auf zahllosen Schlachtfeldern. Eine unterhaltsame und funktionale Variante für Sammler, die interaktive Bauelemente neben Displaystücken schätzen.',
    description_fr: 'Ce Droïde Araignée Naine avec dôme gris bleu clair et mini-blaster/tireur représente une variante fonctionnelle optimisée pour la jouabilité. Le schéma de couleurs plus clair et le tireur intégré ajoutent des fonctionnalités d\'action aux présentations de bataille de la Guerre des Clones. Ces droïdes tactiques fournissaient une puissance de feu mobile aux forces séparatistes sur d\'innombrables champs de bataille. Une variante amusante et fonctionnelle pour les collectionneurs qui apprécient les éléments de construction interactifs aux côtés des pièces d\'affichage.',
    description_es: 'Este Droide Araña Enano con cúpula gris azulado claro y mini blaster/disparador representa una variante funcional optimizada para jugabilidad. El esquema de color más claro y disparador integrado añaden características de acción a exhibiciones de batalla de las Guerras Clon. Estos droides tácticos proporcionaron poder de fuego móvil para fuerzas Separatistas en innumerables campos de batalla. Una variante divertida y funcional para coleccionistas que aprecian elementos de construcción interactivos junto a piezas de exhibición.'
  }
];

async function main() {
  console.log('Starting batch save for sw1011-sw1030...');

  for (const desc of descriptions) {
    await prisma.minifigCatalog.update({
      where: { minifigure_no: desc.minifigure_no },
      data: {
        description_en: desc.description_en,
        description_de: desc.description_de,
        description_fr: desc.description_fr,
        description_es: desc.description_es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`✓ Saved ${desc.minifigure_no}: ${descriptions.find(d => d.minifigure_no === desc.minifigure_no)?.minifigure_no}`);
  }

  console.log(`Batch complete! ${descriptions.length} minifigs saved (sw1011-sw1030).`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
