import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0457',
    name: 'Imperial TIE Fighter / Bomber Pilot',
    en: 'The Imperial TIE Fighter and TIE Bomber pilot represents the elite aviators who fly the Empire\'s signature starfighters throughout the Original Trilogy. This 2013 minifigure features the distinctive all-black flight suit with integrated life support systems and the iconic black helmet necessary for operating TIE craft which lack shields and hyperdrives. These pilots undergo rigorous Imperial Academy training, representing the best of Imperial military aviation despite flying expendable fighters. TIE pilots accept the Empire\'s doctrine that overwhelming numbers and pilot skill compensate for lack of defensive systems. The black uniform creates psychological intimidation while the sealed suit allows survival in space during cockpit breaches. These aviators fly both standard TIE Fighters and the heavier TIE Bombers carrying devastating ordnance. Released in set 75055 Imperial Star Destroyer, this figure is essential for Imperial fleet operations. Perfect for army building Imperial fighter squadrons and collectors of the Empire\'s faceless military might.',
    de: 'Der imperiale TIE-Jäger- und TIE-Bomber-Pilot repräsentiert die Elite-Flieger, die die charakteristischen Sternenjäger des Imperiums während der gesamten Original-Trilogie fliegen. Diese 2013er-Minifigur zeigt den charakteristischen komplett schwarzen Fluganzug mit integrierten Lebenserhaltungssystemen und dem ikonischen schwarzen Helm, der für den Betrieb von TIE-Fahrzeugen notwendig ist, denen Schilde und Hyperantriebe fehlen. Diese Piloten durchlaufen rigoroses Training an der Imperialen Akademie und repräsentieren das Beste der imperialen Militärluftfahrt, obwohl sie Wegwerf-Jäger fliegen. TIE-Piloten akzeptieren die Doktrin des Imperiums, dass überwältigende Zahlen und Pilotenfähigkeit den Mangel an Verteidigungssystemen kompensieren. Die schwarze Uniform schafft psychologische Einschüchterung, während der versiegelte Anzug das Überleben im Weltraum während Cockpit-Durchbrüchen ermöglicht. Diese Flieger fliegen sowohl Standard-TIE-Jäger als auch die schwereren TIE-Bomber mit verheerender Munition. Veröffentlicht im Set 75055 Imperialer Sternenzerstörer, ist diese Figur unverzichtbar für imperiale Flottenoperationen. Perfekt für den Aufbau imperialer Jäger-Staffeln und Sammler der gesichtslosen militärischen Macht des Imperiums.',
    fr: 'Le pilote de Chasseur TIE et Bombardier TIE Impérial représente les aviateurs d\'élite qui pilotent les chasseurs stellaires emblématiques de l\'Empire tout au long de la Trilogie Originale. Cette minifigurine de 2013 présente la combinaison de vol entièrement noire distinctive avec systèmes de maintien de vie intégrés et le casque noir iconique nécessaire pour opérer les appareils TIE qui manquent de boucliers et d\'hyperdrives. Ces pilotes suivent une formation rigoureuse à l\'Académie Impériale, représentant le meilleur de l\'aviation militaire Impériale malgré le pilotage de chasseurs jetables. Les pilotes TIE acceptent la doctrine de l\'Empire selon laquelle des nombres écrasants et la compétence du pilote compensent le manque de systèmes défensifs. L\'uniforme noir crée une intimidation psychologique tandis que la combinaison scellée permet la survie dans l\'espace lors de brèches du cockpit. Ces aviateurs pilotent à la fois des Chasseurs TIE standard et les Bombardiers TIE plus lourds transportant des munitions dévastatrices. Sortie dans le set 75055 Destroyer Stellaire Impérial, cette figurine est essentielle pour les opérations de flotte Impériale. Parfaite pour construire des escadrons de chasseurs Impériaux et les collectionneurs de la puissance militaire sans visage de l\'Empire.',
    es: 'El piloto de Caza TIE y Bombardero TIE Imperial representa a los aviadores de élite que vuelan los cazas estelares característicos del Imperio a lo largo de la Trilogía Original. Esta minifigura de 2013 presenta el distintivo traje de vuelo completamente negro con sistemas de soporte vital integrados y el icónico casco negro necesario para operar naves TIE que carecen de escudos e hiperimpulsores. Estos pilotos se someten a riguroso entrenamiento de la Academia Imperial, representando lo mejor de la aviación militar Imperial a pesar de volar cazas desechables. Los pilotos TIE aceptan la doctrina del Imperio de que números abrumadores y habilidad del piloto compensan la falta de sistemas defensivos. El uniforme negro crea intimidación psicológica mientras el traje sellado permite supervivencia en el espacio durante brechas de cabina. Estos aviadores vuelan tanto Cazas TIE estándar como los Bombarderos TIE más pesados portando munición devastadora. Lanzada en el set 75055 Destructor Estelar Imperial, esta figura es esencial para operaciones de flota Imperial. Perfecta para construir escuadrones de cazas Imperiales y coleccionistas del poderío militar sin rostro del Imperio.'
  },
  {
    no: 'sw0458',
    name: 'Snowspeeder Pilot - White Helmet',
    en: 'The Rebel Snowspeeder pilot with white helmet represents the brave aviators who defended Echo Base during the Battle of Hoth in The Empire Strikes Back. This 2013 minifigure features the distinctive orange flight suit with white cold-weather helmet necessary for operating the modified T-47 airspeeders in Hoth\'s sub-zero environment. These pilots improvised tactics against the seemingly invincible AT-AT walkers, using tow cables to trip the massive war machines in one of Star Wars\' most iconic battle sequences. Snowspeeder crews operated in two-person teams with pilot and gunner working in coordination. Despite being outmatched by Imperial ground forces, these pilots bought precious time for the Rebel evacuation, demonstrating courage and ingenuity. The white helmet variant adds diversity to Rebel pilot collections. Released in set 75049 Snowspeeder, this figure is essential for recreating the Battle of Hoth. Perfect for army building Rebel air support and fans of the desperate defense that defined the Empire\'s greatest tactical victory.',
    de: 'Der Rebellenspeeder-Pilot mit weißem Helm repräsentiert die mutigen Flieger, die Echo Base während der Schlacht von Hoth in Das Imperium schlägt zurück verteidigten. Diese 2013er-Minifigur zeigt den charakteristischen orangefarbenen Fluganzug mit weißem Kaltwetter-Helm, der für den Betrieb der modifizierten T-47-Luftgleiter in Hoth\'s Umgebung unter null Grad notwendig ist. Diese Piloten improvisierten Taktiken gegen die scheinbar unbesiegbaren AT-AT-Läufer und verwendeten Abschleppseile, um die massiven Kriegsmaschinen in einer von Star Wars\' ikonischsten Kampfsequenzen zu Fall zu bringen. Snowspeeder-Besatzungen operierten in Zwei-Personen-Teams mit Pilot und Schütze in Koordination. Obwohl sie von imperialen Bodentruppen übertroffen wurden, gewannen diese Piloten wertvolle Zeit für die Rebellenevakuierung und demonstrierten Mut und Einfallsreichtum. Die weiße Helm-Variante fügt Vielfalt zu Rebellenpiloten-Sammlungen hinzu. Veröffentlicht im Set 75049 Snowspeeder, ist diese Figur unverzichtbar für die Nachstellung der Schlacht von Hoth. Perfekt für den Aufbau rebellischer Luftunterstützung und Fans der verzweifelten Verteidigung, die den größten taktischen Sieg des Imperiums definierte.',
    fr: 'Le pilote de Snowspeeder Rebelle avec casque blanc représente les courageux aviateurs qui ont défendu la Base Echo pendant la Bataille de Hoth dans L\'Empire Contre-Attaque. Cette minifigurine de 2013 présente la combinaison de vol orange distinctive avec casque blanc pour temps froid nécessaire pour opérer les speeders aériens T-47 modifiés dans l\'environnement sous zéro de Hoth. Ces pilotes ont improvisé des tactiques contre les marcheurs AT-AT apparemment invincibles, utilisant des câbles de remorquage pour faire trébucher les machines de guerre massives dans l\'une des séquences de bataille les plus iconiques de Star Wars. Les équipages de Snowspeeder opéraient en équipes de deux personnes avec pilote et artilleur travaillant en coordination. Malgré être surpassés par les forces terrestres Impériales, ces pilotes ont gagné un temps précieux pour l\'évacuation Rebelle, démontrant courage et ingéniosité. La variante de casque blanc ajoute de la diversité aux collections de pilotes Rebelles. Sortie dans le set 75049 Snowspeeder, cette figurine est essentielle pour recréer la Bataille de Hoth. Parfaite pour construire un soutien aérien Rebelle et les fans de la défense désespérée qui a défini la plus grande victoire tactique de l\'Empire.',
    es: 'El piloto de Deslizador de Nieve Rebelde con casco blanco representa a los valientes aviadores que defendieron la Base Eco durante la Batalla de Hoth en El Imperio Contraataca. Esta minifigura de 2013 presenta el distintivo traje de vuelo naranja con casco blanco para clima frío necesario para operar los aerodeslizadores T-47 modificados en el ambiente bajo cero de Hoth. Estos pilotos improvisaron tácticas contra los aparentemente invencibles caminantes AT-AT, usando cables de remolque para tropezar las masivas máquinas de guerra en una de las secuencias de batalla más icónicas de Star Wars. Las tripulaciones de Deslizadores de Nieve operaban en equipos de dos personas con piloto y artillero trabajando en coordinación. A pesar de estar superados por fuerzas terrestres Imperiales, estos pilotos ganaron tiempo precioso para la evacuación Rebelde, demostrando valentía e ingenio. La variante de casco blanco añade diversidad a colecciones de pilotos Rebeldes. Lanzada en el set 75049 Deslizador de Nieve, esta figura es esencial para recrear la Batalla de Hoth. Perfecta para construir apoyo aéreo Rebelde y fans de la desesperada defensa que definió la mayor victoria táctica del Imperio.'
  },
  {
    no: 'sw0459',
    name: 'Imperial Probe Droid - Trans-Clear Dish Stand, Lever on Top',
    en: 'The Imperial Probe Droid, officially designated Viper probe droid, represents the Empire\'s far-reaching surveillance network deployed across the galaxy to locate Rebel bases. This 2013 minifigure captures the distinctive hovering design with multiple sensor arrays, manipulator arms, and the trans-clear dish stand simulating its repulsorlift capability. These droids proved instrumental in discovering Echo Base on Hoth, transmitting crucial intelligence before being destroyed by Han Solo. Probe droids combine advanced AI with self-destruct mechanisms to prevent enemy analysis, making them expendable but highly effective reconnaissance tools. Their ability to survive in hostile environments from ice planets to volcanic worlds made them indispensable for Imperial intelligence operations. The lever on top adds functional play features. Released in set 75098 Assault on Hoth, this figure recreates one of The Empire Strikes Back\'s most memorable opening scenes. Essential for Hoth battle displays and collectors of Imperial technology.',
    de: 'Der imperiale Sondendroide, offiziell als Viper-Sondendroide bezeichnet, repräsentiert das weitreichende Überwachungsnetzwerk des Imperiums, das in der gesamten Galaxie eingesetzt wird, um Rebellenbasen zu lokalisieren. Diese 2013er-Minifigur erfasst das charakteristische schwebende Design mit mehreren Sensorarrays, Manipulator-Armen und dem transparenten Teller-Ständer, der seine Repulsorlift-Fähigkeit simuliert. Diese Droiden erwiesen sich als instrumental bei der Entdeckung von Echo Base auf Hoth und übermittelten entscheidende Informationen, bevor sie von Han Solo zerstört wurden. Sondendroiden kombinieren fortgeschrittene KI mit Selbstzerstörungsmechanismen, um feindliche Analyse zu verhindern, was sie zu Wegwerf-, aber hochwirksamen Aufklärungswerkzeugen macht. Ihre Fähigkeit, in feindlichen Umgebungen von Eisplaneten bis zu vulkanischen Welten zu überleben, machte sie für imperiale Geheimdienst-Operationen unverzichtbar. Der Hebel oben fügt funktionale Spielfunktionen hinzu. Veröffentlicht im Set 75098 Angriff auf Hoth, stellt diese Figur eine der einprägsamsten Eröffnungsszenen von Das Imperium schlägt zurück nach. Unverzichtbar für Hoth-Schlacht-Darstellungen und Sammler imperialer Technologie.',
    fr: 'Le Droïde Sonde Impérial, officiellement désigné droïde sonde Viper, représente le réseau de surveillance étendu de l\'Empire déployé à travers la galaxie pour localiser les bases Rebelles. Cette minifigurine de 2013 capture le design flottant distinctif avec plusieurs réseaux de capteurs, bras manipulateurs et le support de plat transparent simulant sa capacité de répulseur. Ces droïdes se sont révélés instrumentaux dans la découverte de la Base Echo sur Hoth, transmettant des renseignements cruciaux avant d\'être détruits par Han Solo. Les droïdes sondes combinent une IA avancée avec des mécanismes d\'autodestruction pour empêcher l\'analyse ennemie, les rendant jetables mais très efficaces comme outils de reconnaissance. Leur capacité à survivre dans des environnements hostiles des planètes de glace aux mondes volcaniques les rendait indispensables pour les opérations de renseignement Impérial. Le levier sur le dessus ajoute des fonctionnalités de jeu. Sortie dans le set 75098 Assaut sur Hoth, cette figurine recrée l\'une des scènes d\'ouverture les plus mémorables de L\'Empire Contre-Attaque. Essentielle pour les affichages de bataille de Hoth et les collectionneurs de technologie Impériale.',
    es: 'El Droide Sonda Imperial, oficialmente designado droide sonda Viper, representa la red de vigilancia de largo alcance del Imperio desplegada a través de la galaxia para localizar bases Rebeldes. Esta minifigura de 2013 captura el distintivo diseño flotante con múltiples matrices de sensores, brazos manipuladores y el soporte de plato transparente simulando su capacidad de repulsor. Estos droides resultaron instrumentales en descubrir la Base Eco en Hoth, transmitiendo inteligencia crucial antes de ser destruidos por Han Solo. Los droides sonda combinan IA avanzada con mecanismos de autodestrucción para prevenir análisis enemigo, haciéndolos desechables pero altamente efectivos como herramientas de reconocimiento. Su capacidad de sobrevivir en ambientes hostiles desde planetas de hielo hasta mundos volcánicos los hizo indispensables para operaciones de inteligencia Imperial. La palanca arriba añade características de juego funcionales. Lanzada en el set 75098 Asalto en Hoth, esta figura recrea una de las escenas de apertura más memorables de El Imperio Contraataca. Esencial para exhibiciones de batalla de Hoth y coleccionistas de tecnología Imperial.'
  },
  {
    no: 'sw0460',
    name: 'General Rieekan',
    en: 'General Carlist Rieekan, the tactical mastermind behind the Rebel defense of Echo Base, appears in this 2013 minifigure from The Empire Strikes Back. This figure captures Rieekan\'s military bearing with his gray Rebel officer uniform and distinguished appearance befitting his role as base commander. A veteran of the Clone Wars who later joined the Rebellion, Rieekan brought decades of military experience to the Alliance\'s strategic planning. His leadership during the Battle of Hoth balanced offensive defense with orderly evacuation, saving countless Rebel lives despite overwhelming Imperial assault. Rieekan\'s tactical decisions, including the ion cannon covering fire for transports, demonstrated the professionalism that made him one of the Rebellion\'s most respected commanders. Released in set 75098 Assault on Hoth, this rare command figure is essential for Echo Base dioramas. Highly collectible as one of the few senior Rebel officer minifigures, perfect for fans who appreciate military leadership in the Original Trilogy.',
    de: 'General Carlist Rieekan, der taktische Mastermind hinter der Rebellenverteidigung von Echo Base, erscheint in dieser 2013er-Minifigur aus Das Imperium schlägt zurück. Diese Figur erfasst Rieekan\'s militärisches Auftreten mit seiner grauen Rebellenoffiziers-Uniform und distinguiertem Erscheinungsbild, das seiner Rolle als Basiskommandant entspricht. Ein Veteran der Klonkriege, der sich später der Rebellion anschloss, brachte Rieekan jahrzehntelange militärische Erfahrung in die strategische Planung der Allianz ein. Seine Führung während der Schlacht von Hoth balancierte offensive Verteidigung mit ordentlicher Evakuierung und rettete unzählige Rebellenleben trotz überwältigendem imperialen Angriff. Rieekan\'s taktische Entscheidungen, einschließlich des Ionenkanonen-Deckungsfeuers für Transporter, demonstrierten die Professionalität, die ihn zu einem der respektiertesten Kommandanten der Rebellion machte. Veröffentlicht im Set 75098 Angriff auf Hoth, ist diese seltene Kommando-Figur unverzichtbar für Echo Base-Dioramen. Sehr sammelbar als eine der wenigen hochrangigen Rebellenoffiziers-Minifiguren, perfekt für Fans, die militärische Führung in der Original-Trilogie schätzen.',
    fr: 'Le Général Carlist Rieekan, le cerveau tactique derrière la défense Rebelle de la Base Echo, apparaît dans cette minifigurine de 2013 de L\'Empire Contre-Attaque. Cette figurine capture l\'allure militaire de Rieekan avec son uniforme d\'officier Rebelle gris et son apparence distinguée correspondant à son rôle de commandant de base. Un vétéran des Guerres des Clones qui a ensuite rejoint la Rébellion, Rieekan a apporté des décennies d\'expérience militaire à la planification stratégique de l\'Alliance. Son leadership pendant la Bataille de Hoth a équilibré la défense offensive avec une évacuation ordonnée, sauvant d\'innombrables vies Rebelles malgré l\'assaut Impérial écrasant. Les décisions tactiques de Rieekan, y compris le tir de couverture du canon ionique pour les transports, ont démontré le professionnalisme qui a fait de lui l\'un des commandants les plus respectés de la Rébellion. Sortie dans le set 75098 Assaut sur Hoth, cette figurine de commandement rare est essentielle pour les dioramas de la Base Echo. Hautement collectionnable comme l\'une des rares minifigurines d\'officiers supérieurs Rebelles, parfaite pour les fans qui apprécient le leadership militaire dans la Trilogie Originale.',
    es: 'El General Carlist Rieekan, la mente maestra táctica detrás de la defensa Rebelde de la Base Eco, aparece en esta minifigura de 2013 de El Imperio Contraataca. Esta figura captura el porte militar de Rieekan con su uniforme gris de oficial Rebelde y apariencia distinguida apropiada para su papel como comandante de base. Un veterano de las Guerras Clon que posteriormente se unió a la Rebelión, Rieekan aportó décadas de experiencia militar a la planificación estratégica de la Alianza. Su liderazgo durante la Batalla de Hoth equilibró defensa ofensiva con evacuación ordenada, salvando incontables vidas Rebeldes a pesar del abrumador asalto Imperial. Las decisiones tácticas de Rieekan, incluyendo el fuego de cobertura del cañón iónico para transportes, demostraron el profesionalismo que lo convirtió en uno de los comandantes más respetados de la Rebelión. Lanzada en el set 75098 Asalto en Hoth, esta rara figura de comando es esencial para dioramas de Base Eco. Altamente coleccionable como una de las pocas minifiguras de oficiales superiores Rebeldes, perfecta para fans que aprecian liderazgo militar en la Trilogía Original.'
  },
  {
    no: 'sw0461',
    name: 'Luke Skywalker (Pilot, Printed Legs)',
    en: 'Luke Skywalker appears in this 2013 minifigure wearing his iconic orange X-wing pilot flight suit with printed legs adding detail to the full uniform. This version represents Luke during his most heroic piloting moments from A New Hope and The Empire Strikes Back, including the trench run that destroyed the Death Star and the Battle of Hoth. The detailed printing shows his flight suit\'s life support systems, equipment pouches, and rank insignia. Luke\'s natural piloting ability, honed racing T-16 skyhoppers through Beggar\'s Canyon, translated to exceptional starfighter skills. His callsign "Red Five" became legendary after using the Force to make the impossible shot that saved the Rebellion. The printed legs variant represents peak LEGO detailing for this costume. Released in set 75098 Assault on Hoth, this figure is essential for Rebel pilot collections. Perfect for fans of Luke\'s transformation from farm boy to ace pilot and the hero of Yavin.',
    de: 'Luke Skywalker erscheint in dieser 2013er-Minifigur in seinem ikonischen orangefarbenen X-Wing-Piloten-Fluganzug mit bedruckten Beinen, die Details zur vollständigen Uniform hinzufügen. Diese Version repräsentiert Luke während seiner heroischsten Piloten-Momente aus Eine neue Hoffnung und Das Imperium schlägt zurück, einschließlich des Grabenlaufs, der den Todesstern zerstörte, und der Schlacht von Hoth. Der detaillierte Druck zeigt die Lebenserhaltungssysteme seines Fluganzugs, Ausrüstungstaschen und Rangabzeichen. Luke\'s natürliche Pilotenfähigkeit, geschärft durch Rennen mit T-16-Skyhoppern durch Beggar\'s Canyon, übertrug sich auf außergewöhnliche Sternenjäger-Fähigkeiten. Sein Rufzeichen "Red Five" wurde legendär, nachdem er die Macht benutzte, um den unmöglichen Schuss zu machen, der die Rebellion rettete. Die bedruckte Bein-Variante repräsentiert Spitzen-LEGO-Detaillierung für dieses Kostüm. Veröffentlicht im Set 75098 Angriff auf Hoth, ist diese Figur unverzichtbar für Rebellenpiloten-Sammlungen. Perfekt für Fans von Luke\'s Verwandlung vom Farmjungen zum Ass-Piloten und dem Helden von Yavin.',
    fr: 'Luke Skywalker apparaît dans cette minifigurine de 2013 portant sa combinaison de vol de pilote X-wing orange iconique avec jambes imprimées ajoutant des détails à l\'uniforme complet. Cette version représente Luke pendant ses moments de pilotage les plus héroïques d\'Un Nouvel Espoir et L\'Empire Contre-Attaque, y compris la course dans la tranchée qui a détruit l\'Étoile de la Mort et la Bataille de Hoth. L\'impression détaillée montre les systèmes de maintien de vie de sa combinaison de vol, les poches d\'équipement et les insignes de rang. La capacité de pilotage naturelle de Luke, perfectionnée en faisant la course dans des skyhoppers T-16 à travers Beggar\'s Canyon, s\'est traduite par des compétences exceptionnelles de chasseur stellaire. Son indicatif "Red Five" est devenu légendaire après avoir utilisé la Force pour faire le tir impossible qui a sauvé la Rébellion. La variante de jambes imprimées représente le détail LEGO de pointe pour ce costume. Sortie dans le set 75098 Assaut sur Hoth, cette figurine est essentielle pour les collections de pilotes Rebelles. Parfaite pour les fans de la transformation de Luke de garçon de ferme à pilote as et héros de Yavin.',
    es: 'Luke Skywalker aparece en esta minifigura de 2013 vistiendo su icónico traje de vuelo de piloto de Ala-X naranja con piernas impresas añadiendo detalle al uniforme completo. Esta versión representa a Luke durante sus momentos de pilotaje más heroicos de Una Nueva Esperanza y El Imperio Contraataca, incluyendo la carrera por la trinchera que destruyó la Estrella de la Muerte y la Batalla de Hoth. La impresión detallada muestra los sistemas de soporte vital de su traje de vuelo, bolsas de equipo e insignias de rango. La habilidad natural de pilotaje de Luke, perfeccionada corriendo T-16 skyhoppers a través del Cañón del Mendigo, se tradujo en habilidades excepcionales de caza estelar. Su indicativo "Red Five" se volvió legendario después de usar la Fuerza para hacer el tiro imposible que salvó la Rebelión. La variante de piernas impresas representa el máximo detalle de LEGO para este vestuario. Lanzada en el set 75098 Asalto en Hoth, esta figura es esencial para colecciones de pilotos Rebeldes. Perfecta para fans de la transformación de Luke de granjero a piloto as y el héroe de Yavin.'
  },
  {
    no: 'sw0462',
    name: 'Hoth Rebel Trooper Tan Uniform (Stubble)',
    en: 'The Hoth Rebel Trooper with stubble represents another brave soldier defending Echo Base during the desperate Battle of Hoth. This 2013 minifigure features the tan cold-weather uniform with facial stubble print, suggesting a veteran trooper who has endured Hoth\'s brutal conditions. These soldiers manned defensive positions, operated anti-vehicle cannons, and covered the evacuation of Rebel personnel while facing overwhelming Imperial assault forces. The harsh environment required constant vigilance against both enemy forces and the deadly climate. Stubble details suggest the exhaustion and harsh living conditions at the remote base, adding realism to the military aesthetic. These troopers demonstrated exceptional courage holding the line against AT-AT walkers and snowtroopers despite being outgunned and outnumbered. Released in set 75098 Assault on Hoth, this variant adds facial diversity to army building. Essential for Battle of Hoth dioramas and collectors creating realistic Rebel defensive formations from one of the Original Trilogy\'s most iconic battles.',
    de: 'Der Hoth-Rebellensoldat mit Stoppeln repräsentiert einen weiteren mutigen Soldaten, der Echo Base während der verzweifelten Schlacht von Hoth verteidigt. Diese 2013er-Minifigur zeigt die sandfarbene Kaltwetter-Uniform mit Gesichtsstoppel-Druck, was auf einen Veteranen-Soldaten hindeutet, der Hoth\'s brutale Bedingungen durchgestanden hat. Diese Soldaten besetzten Verteidigungspositionen, bedienten Antifahrzeug-Kanonen und deckten die Evakuierung von Rebellenpersonal, während sie überwältigenden imperialen Angriffskräften gegenüberstanden. Die raue Umgebung erforderte ständige Wachsamkeit sowohl gegen feindliche Streitkräfte als auch gegen das tödliche Klima. Stoppel-Details deuten auf Erschöpfung und harte Lebensbedingungen an der abgelegenen Basis hin und fügen der militärischen Ästhetik Realismus hinzu. Diese Soldaten demonstrierten außergewöhnlichen Mut, als sie die Linie gegen AT-AT-Läufer und Schneetruppler hielten, obwohl sie unterlegen und zahlenmäßig unterlegen waren. Veröffentlicht im Set 75098 Angriff auf Hoth, fügt diese Variante Gesichtsvielfalt zum Armeeaufbau hinzu. Unverzichtbar für Schlacht-von-Hoth-Dioramen und Sammler, die realistische Rebellenverteidigungsformationen aus einer der ikonischsten Schlachten der Original-Trilogie erstellen.',
    fr: 'Le Soldat Rebelle de Hoth avec barbe naissante représente un autre courageux soldat défendant la Base Echo pendant la Bataille désespérée de Hoth. Cette minifigurine de 2013 présente l\'uniforme beige pour temps froid avec impression de barbe naissante, suggérant un soldat vétéran qui a enduré les conditions brutales de Hoth. Ces soldats ont occupé des positions défensives, opéré des canons antivéhicules et couvert l\'évacuation du personnel Rebelle tout en faisant face à des forces d\'assaut Impériales écrasantes. L\'environnement hostile nécessitait une vigilance constante contre les forces ennemies et le climat mortel. Les détails de barbe naissante suggèrent l\'épuisement et les conditions de vie difficiles à la base éloignée, ajoutant du réalisme à l\'esthétique militaire. Ces soldats ont démontré un courage exceptionnel en tenant la ligne contre les marcheurs AT-AT et les snowtroopers malgré être surarmés et en sous-nombre. Sortie dans le set 75098 Assaut sur Hoth, cette variante ajoute de la diversité faciale à la construction d\'armée. Essentielle pour les dioramas de la Bataille de Hoth et les collectionneurs créant des formations défensives Rebelles réalistes de l\'une des batailles les plus iconiques de la Trilogie Originale.',
    es: 'El Soldado Rebelde de Hoth con barba incipiente representa a otro valiente soldado defendiendo la Base Eco durante la desesperada Batalla de Hoth. Esta minifigura de 2013 presenta el uniforme beige para clima frío con impresión de barba incipiente, sugiriendo un soldado veterano que ha soportado las brutales condiciones de Hoth. Estos soldados ocuparon posiciones defensivas, operaron cañones antivehículo y cubrieron la evacuación de personal Rebelde mientras enfrentaban abrumadoras fuerzas de asalto Imperiales. El ambiente hostil requería vigilancia constante contra fuerzas enemigas y el clima mortal. Los detalles de barba incipiente sugieren el agotamiento y duras condiciones de vida en la base remota, añadiendo realismo a la estética militar. Estos soldados demostraron valentía excepcional sosteniendo la línea contra caminantes AT-AT y soldados de nieve a pesar de estar superados en armas y número. Lanzada en el set 75098 Asalto en Hoth, esta variante añade diversidad facial a construcción de ejército. Esencial para dioramas de Batalla de Hoth y coleccionistas creando formaciones defensivas Rebeldes realistas de una de las batallas más icónicas de la Trilogía Original.'
  }
];

async function saveBatch() {
  console.log(`Processing ${batch.length} minifigs...\n`);

  for (const minifig of batch) {
    try {
      await prisma.minifigCatalog.update({
        where: { minifigure_no: minifig.no },
        data: {
          description_en: minifig.en,
          description_de: minifig.de,
          description_fr: minifig.fr,
          description_es: minifig.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        }
      });
      console.log(`✅ Saved ${minifig.no}: ${minifig.name}`);
    } catch (error: any) {
      console.error(`❌ Error saving ${minifig.no}: ${error.message}`);
    }
  }

  console.log(`\n✨ Batch complete!\n`);
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
