import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    minifigure_no: 'sw0641',
    name: 'Naboo Fighter Pilot - Medium Nougat Jacket',
    description_en: 'Naboo Fighter Pilots flew the elegant N-1 starfighters defending their homeworld during the Trade Federation blockade and subsequent invasion. This minifigure features a medium nougat colored jacket representing the distinctive yellow flight suits worn by Naboo\'s Royal Space Fighter Corps. These pilots combined ceremonial elegance with combat effectiveness, reflecting Naboo\'s culture of beauty and functionality. During the Battle of Naboo, these pilots engaged Trade Federation droid starfighters while young Anakin accidentally flew into the Droid Control Ship. The N-1 starfighter\'s sleek chrome design and powerful engines made it one of the galaxy\'s most beautiful combat spacecraft. The medium nougat jacket color distinguishes these pilots from other galactic flight crews. Collectors value Naboo pilots for their unique aesthetic, connection to The Phantom Menace climactic space battle, and for displaying the refined military traditions of Queen Amidala\'s peaceful world.',
    description_de: 'Naboo-Jägerpiloten flogen die eleganten N-1-Sternenjäger zur Verteidigung ihrer Heimatwelt während der Blockade und anschließenden Invasion der Handelsföderation. Diese Minifigur zeigt eine mittlere Nougat-farbene Jacke, die die markanten gelben Fluganzüge repräsentiert, die von Naboos Royal Space Fighter Corps getragen wurden. Diese Piloten kombinierten zeremonielle Eleganz mit Kampfwirksamkeit und spiegelten Naboos Kultur von Schönheit und Funktionalität wider. Während der Schlacht um Naboo kämpften diese Piloten gegen Droiden-Sternenjäger der Handelsföderation, während der junge Anakin versehentlich in das Droiden-Kontrollschiff flog. Das schlanke Chrom-Design und die kraftvollen Motoren des N-1-Sternenjägers machten ihn zu einem der schönsten Kampfraumschiffe der Galaxis. Die mittlere Nougat-Jackenfarbe unterscheidet diese Piloten von anderen galaktischen Flugbesatzungen. Sammler schätzen Naboo-Piloten für ihre einzigartige Ästhetik, Verbindung zur climaktischen Weltraumschlacht von Die dunkle Bedrohung und für die Darstellung der verfeinerten militärischen Traditionen von Königin Amidalas friedlicher Welt.',
    description_fr: 'Les Pilotes de Chasseurs de Naboo pilotaient les élégants chasseurs stellaires N-1 défendant leur monde natal pendant le blocus de la Fédération du Commerce et l\'invasion ultérieure. Cette minifigurine présente une veste de couleur nougat moyen représentant les combinaisons de vol jaunes distinctives portées par le Corps de Chasseurs Spatiaux Royaux de Naboo. Ces pilotes combinaient élégance cérémonielle et efficacité au combat, reflétant la culture de Naboo de beauté et de fonctionnalité. Pendant la Bataille de Naboo, ces pilotes ont affronté les chasseurs stellaires droïdes de la Fédération du Commerce pendant que le jeune Anakin volait accidentellement dans le Vaisseau de Contrôle Droïde. Le design chromé élégant et les moteurs puissants du chasseur stellaire N-1 en faisaient l\'un des vaisseaux de combat spatiaux les plus beaux de la galaxie. La couleur de veste nougat moyen distingue ces pilotes des autres équipages de vol galactiques. Les collectionneurs apprécient les pilotes de Naboo pour leur esthétique unique, leur connexion à la bataille spatiale climactique de La Menace Fantôme et pour afficher les traditions militaires raffinées du monde pacifique de la Reine Amidala.',
    description_es: 'Los Pilotos de Cazas de Naboo volaban los elegantes cazas estelares N-1 defendiendo su mundo natal durante el bloqueo de la Federación de Comercio y la subsiguiente invasión. Esta minifigura presenta una chaqueta de color beige medio representando los distintivos trajes de vuelo amarillos usados por el Cuerpo de Cazas Espaciales Reales de Naboo. Estos pilotos combinaban elegancia ceremonial con efectividad de combate, reflejando la cultura de Naboo de belleza y funcionalidad. Durante la Batalla de Naboo, estos pilotos enfrentaron cazas estelares droides de la Federación de Comercio mientras el joven Anakin accidentalmente voló hacia la Nave de Control de Droides. El diseño cromado elegante y los motores potentes del caza estelar N-1 lo convirtieron en una de las naves de combate espaciales más hermosas de la galaxia. El color de chaqueta beige medio distingue a estos pilotos de otras tripulaciones de vuelo galácticas. Los coleccionistas valoran a los pilotos de Naboo por su estética única, conexión con la batalla espacial climática de La Amenaza Fantasma y por mostrar las refinadas tradiciones militares del mundo pacífico de la Reina Amidala.'
  },
  {
    minifigure_no: 'sw0642',
    name: 'Droideka (Destroyer Droid) - Reddish Brown Triangles without Stickers',
    description_en: 'Droidekas, also known as Destroyer Droids, were devastating rolling combat units deployed by the Trade Federation and Separatists throughout the Clone Wars. This minifigure features reddish brown triangular sections representing the droid\'s shield generator configuration without additional stickers. Droidekas could transform from wheel mode for rapid deployment to combat stance with twin blaster cannons and powerful deflector shields. Their shields could withstand lightsaber strikes and sustained blaster fire, making them extremely dangerous opponents even for Jedi. The bronze-brown coloring represents the battle-worn appearance of these feared droids. Droidekas appeared in pivotal moments including the Naboo palace invasion and numerous Clone Wars battles. The specialized build represents one of LEGO\'s most creative non-standard minifigure designs. Collectors value Droidekas for their unique construction, memorable rolling attack scenes, and representation of the Separatists\' most effective infantry weapon.',
    description_de: 'Droidekas, auch bekannt als Zerstörer-Droiden, waren verheerende rollende Kampfeinheiten, die von der Handelsföderation und Separatisten während der Klonkriege eingesetzt wurden. Diese Minifigur zeigt rotbraune dreieckige Abschnitte, die die Schildgenerator-Konfiguration des Droiden ohne zusätzliche Aufkleber repräsentieren. Droidekas konnten sich vom Radmodus für schnellen Einsatz in Kampfhaltung mit zwei Blasterkanonen und kraftvollen Deflektorschilden verwandeln. Ihre Schilde konnten Lichtschwerttreffer und anhaltende Blasterfeuern widerstehen, was sie zu extrem gefährlichen Gegnern selbst für Jedi machte. Die bronze-braune Färbung repräsentiert das kampferprobte Erscheinungsbild dieser gefürchteten Droiden. Droidekas erschienen in entscheidenden Momenten einschließlich der Naboo-Palast-Invasion und zahlreichen Klonkriegs-Schlachten. Der spezialisierte Bau repräsentiert eines von LEGOs kreativsten nicht-standardmäßigen Minifiguren-Designs. Sammler schätzen Droidekas für ihre einzigartige Konstruktion, unvergessliche Rollangriff-Szenen und Darstellung der effektivsten Infanteriewaffe der Separatisten.',
    description_fr: 'Les Droidekas, également connus sous le nom de Droïdes Destructeurs, étaient des unités de combat roulantes dévastatrices déployées par la Fédération du Commerce et les Séparatistes tout au long de la Guerre des Clones. Cette minifigurine présente des sections triangulaires brun rougeâtre représentant la configuration du générateur de bouclier du droïde sans autocollants supplémentaires. Les Droidekas pouvaient se transformer du mode roue pour un déploiement rapide en position de combat avec deux canons blasters jumeaux et de puissants boucliers déflecteurs. Leurs boucliers pouvaient résister aux coups de sabre laser et aux tirs de blaster soutenus, en faisant des adversaires extrêmement dangereux même pour les Jedi. La coloration bronze-brun représente l\'apparence éprouvée au combat de ces droïdes redoutés. Les Droidekas sont apparus dans des moments cruciaux incluant l\'invasion du palais de Naboo et de nombreuses batailles de la Guerre des Clones. La construction spécialisée représente l\'un des designs de minifigurine non standard les plus créatifs de LEGO. Les collectionneurs apprécient les Droidekas pour leur construction unique, leurs scènes d\'attaque en roulant mémorables et la représentation de l\'arme d\'infanterie la plus efficace des Séparatistes.',
    description_es: 'Los Droidekas, también conocidos como Droides Destructores, eran devastadoras unidades de combate rodantes desplegadas por la Federación de Comercio y los Separatistas durante las Guerras Clon. Esta minifigura presenta secciones triangulares marrón rojizo representando la configuración del generador de escudo del droide sin calcomanías adicionales. Los Droidekas podían transformarse del modo rueda para despliegue rápido a postura de combate con cañones blaster gemelos y poderosos escudos deflectores. Sus escudos podían resistir golpes de sable de luz y fuego de blaster sostenido, convirtiéndolos en oponentes extremadamente peligrosos incluso para Jedi. La coloración bronce-marrón representa la apariencia curtida en batalla de estos temidos droides. Los Droidekas aparecieron en momentos cruciales incluyendo la invasión del palacio de Naboo y numerosas batallas de las Guerras Clon. La construcción especializada representa uno de los diseños de minifiguras no estándar más creativos de LEGO. Los coleccionistas valoran a los Droidekas por su construcción única, escenas de ataque rodante memorables y representación del arma de infantería más efectiva de los Separatistas.'
  },
  {
    minifigure_no: 'sw0643',
    name: 'Princess Leia - Endor Outfit, Dark Tan Jacket, Camouflage Cape, Sand Blue Legs',
    description_en: 'Princess Leia\'s Endor outfit represents her combat gear during the crucial mission to destroy the Death Star II\'s shield generator on the forest moon. This minifigure features a dark tan jacket, camouflage cape for forest operations, and sand blue legs showing her practical military attire. During the Endor mission, Leia demonstrated leadership, combat skills, and formed an important connection with the Ewoks. Her capture by Imperial scouts and rescue by Wicket W. Warrick led to the crucial Ewok alliance. The camouflage colors reflect the Rebel Alliance\'s guerrilla warfare tactics against overwhelming Imperial forces. This outfit shows Leia as a field commander rather than diplomat or prisoner, emphasizing her evolution into a complete military leader. Collectors value this Endor variant for its connection to Return of the Jedi\'s climactic battle, detailed camouflage printing, and representation of Leia at her most action-oriented.',
    description_de: 'Prinzessin Leias Endor-Outfit repräsentiert ihre Kampfausrüstung während der entscheidenden Mission zur Zerstörung des Schildgenerators des Todessterns II auf dem Waldmond. Diese Minifigur zeigt eine dunkle beige Jacke, Tarnumhang für Waldoperationen und sandblaue Beine, die ihre praktische Militärkleidung zeigen. Während der Endor-Mission demonstrierte Leia Führung, Kampffähigkeiten und bildete eine wichtige Verbindung mit den Ewoks. Ihre Gefangennahme durch imperiale Späher und Rettung durch Wicket W. Warrick führte zur entscheidenden Ewok-Allianz. Die Tarnfarben spiegeln die Guerilla-Kriegstaktiken der Rebellenallianz gegen überwältigende imperiale Streitkräfte wider. Dieses Outfit zeigt Leia als Feldkommandeurin statt als Diplomatin oder Gefangene und betont ihre Entwicklung zu einer vollständigen militärischen Führerin. Sammler schätzen diese Endor-Variante für ihre Verbindung zur climaktischen Schlacht von Die Rückkehr der Jedi-Ritter, detaillierte Tarnbedruckung und Darstellung von Leia in ihrer aktionsorientiertesten Form.',
    description_fr: 'La tenue d\'Endor de la Princesse Leia représente son équipement de combat pendant la mission cruciale pour détruire le générateur de bouclier de l\'Étoile de la Mort II sur la lune forestière. Cette minifigurine présente une veste beige foncé, une cape de camouflage pour les opérations forestières et des jambes bleu sable montrant sa tenue militaire pratique. Pendant la mission d\'Endor, Leia a démontré du leadership, des compétences de combat et a formé une connexion importante avec les Ewoks. Sa capture par les éclaireurs impériaux et son sauvetage par Wicket W. Warrick ont conduit à l\'alliance cruciale avec les Ewoks. Les couleurs de camouflage reflètent les tactiques de guérilla de l\'Alliance Rebelle contre les forces impériales écrasantes. Cette tenue montre Leia comme commandant de terrain plutôt que diplomate ou prisonnière, soulignant son évolution en leader militaire complet. Les collectionneurs apprécient cette variante d\'Endor pour sa connexion à la bataille climactique du Retour du Jedi, l\'impression de camouflage détaillée et la représentation de Leia à son plus orienté action.',
    description_es: 'El atuendo de Endor de la Princesa Leia representa su equipo de combate durante la misión crucial para destruir el generador de escudo de la Estrella de la Muerte II en la luna boscosa. Esta minifigura presenta una chaqueta beige oscuro, capa de camuflaje para operaciones forestales y piernas azul arena mostrando su atuendo militar práctico. Durante la misión de Endor, Leia demostró liderazgo, habilidades de combate y formó una conexión importante con los Ewoks. Su captura por exploradores imperiales y rescate por Wicket W. Warrick llevó a la crucial alianza Ewok. Los colores de camuflaje reflejan las tácticas de guerra de guerrillas de la Alianza Rebelde contra abrumadoras fuerzas imperiales. Este atuendo muestra a Leia como comandante de campo en lugar de diplomática o prisionera, enfatizando su evolución a líder militar completo. Los coleccionistas valoran esta variante de Endor por su conexión con la batalla climática de El Retorno del Jedi, impresión de camuflaje detallada y representación de Leia en su forma más orientada a la acción.'
  },
  {
    minifigure_no: 'sw0644',
    name: 'Han Solo - Endor Outfit, Dark Tan Camouflage Jacket, Smooth Hair',
    description_en: 'Han Solo\'s Endor outfit shows the reformed smuggler as a Rebel Alliance general leading the crucial mission to destroy the Death Star II shield generator. This minifigure features his dark tan camouflage jacket for forest operations, smooth hair style, and military gear replacing his signature vest. As general, Han commanded the strike team including Luke, Leia, Chewbacca, and specialized Rebel troops. His leadership during the Endor mission combined his natural cunning with newfound military discipline. The camouflage reflects the guerrilla tactics necessary against superior Imperial forces. Han\'s journey from selfish smuggler to selfless hero culminated in this battle, where he helped destroy the Empire. The smooth hair and military bearing show Han\'s maturation from his scruffy appearance in earlier films. Collectors value this general variant for representing Han\'s character arc completion, connection to Return of the Jedi\'s climax, and displaying his transformation into a committed Rebel leader.',
    description_de: 'Han Solos Endor-Outfit zeigt den reformierten Schmuggler als General der Rebellenallianz, der die entscheidende Mission zur Zerstörung des Todesstern-II-Schildgenerators anführt. Diese Minifigur zeigt seine dunkle beige Tarnjacke für Waldoperationen, glatten Haarstil und Militärausrüstung, die seine charakteristische Weste ersetzt. Als General befehligte Han das Stoßtrupp einschließlich Luke, Leia, Chewbacca und spezialisierter Rebellentruppen. Seine Führung während der Endor-Mission kombinierte seine natürliche List mit neu gefundener militärischer Disziplin. Die Tarnung spiegelt die Guerilla-Taktiken wider, die gegen überlegene imperiale Streitkräfte notwendig waren. Hans Reise vom egoistischen Schmuggler zum selbstlosen Helden gipfelte in dieser Schlacht, wo er half, das Imperium zu zerstören. Das glatte Haar und militärische Auftreten zeigen Hans Reifung von seinem schäbigen Erscheinungsbild in früheren Filmen. Sammler schätzen diese General-Variante für die Darstellung von Hans Charakterbogen-Vollendung, Verbindung zum Höhepunkt von Die Rückkehr der Jedi-Ritter und Darstellung seiner Transformation zu einem engagierten Rebellenführer.',
    description_fr: 'La tenue d\'Endor de Han Solo montre le contrebandier réformé comme général de l\'Alliance Rebelle menant la mission cruciale pour détruire le générateur de bouclier de l\'Étoile de la Mort II. Cette minifigurine présente sa veste de camouflage beige foncé pour les opérations forestières, un style de cheveux lisse et un équipement militaire remplaçant son gilet signature. En tant que général, Han commandait l\'équipe d\'assaut incluant Luke, Leia, Chewbacca et des troupes rebelles spécialisées. Son leadership pendant la mission d\'Endor combinait sa ruse naturelle avec une discipline militaire nouvellement trouvée. Le camouflage reflète les tactiques de guérilla nécessaires contre les forces impériales supérieures. Le voyage de Han de contrebandier égoïste à héros désintéressé a culminé dans cette bataille, où il a aidé à détruire l\'Empire. Les cheveux lisses et l\'allure militaire montrent la maturation de Han depuis son apparence négligée dans les films précédents. Les collectionneurs apprécient cette variante de général pour représenter l\'achèvement de l\'arc de personnage de Han, la connexion au point culminant du Retour du Jedi et l\'affichage de sa transformation en leader rebelle engagé.',
    description_es: 'El atuendo de Endor de Han Solo muestra al contrabandista reformado como general de la Alianza Rebelde liderando la misión crucial para destruir el generador de escudo de la Estrella de la Muerte II. Esta minifigura presenta su chaqueta de camuflaje beige oscuro para operaciones forestales, estilo de cabello liso y equipo militar reemplazando su chaleco característico. Como general, Han comandó el equipo de asalto incluyendo a Luke, Leia, Chewbacca y tropas rebeldes especializadas. Su liderazgo durante la misión de Endor combinó su astucia natural con disciplina militar recién encontrada. El camuflaje refleja las tácticas de guerrilla necesarias contra fuerzas imperiales superiores. El viaje de Han de contrabandista egoísta a héroe desinteresado culminó en esta batalla, donde ayudó a destruir el Imperio. El cabello liso y porte militar muestran la maduración de Han desde su apariencia desaliñada en películas anteriores. Los coleccionistas valoran esta variante de general por representar la culminación del arco de personaje de Han, conexión con el clímax de El Retorno del Jedi y mostrar su transformación en líder rebelde comprometido.'
  },
  {
    minifigure_no: 'sw0645',
    name: 'Endor Rebel Trooper - Olive Green',
    description_en: 'Endor Rebel Troopers were specialized commandos trained for forest warfare who participated in the crucial mission to destroy the Death Star II shield generator. This minifigure features olive green camouflage appropriate for the forest moon\'s dense vegetation. These elite soldiers formed the strike team alongside Han Solo, conducting guerrilla operations against superior Imperial forces. The olive coloring reflects military camouflage traditions adapted for Endor\'s specific environment. Rebel commandos used hit-and-run tactics, worked with native Ewoks, and ultimately captured the shield generator bunker. Their training emphasized stealth, woodland survival, and unconventional warfare against the Empire\'s technological advantages. The generic trooper design allows collectors to build diverse Rebel strike teams. Collectors value Endor troopers for army building, recreating the Battle of Endor ground assault, and representing the specialized units that made the Rebellion\'s final victory possible.',
    description_de: 'Endor-Rebellentruppen waren spezialisierte Kommandos, die für Waldkriegsführung trainiert wurden und an der entscheidenden Mission zur Zerstörung des Todesstern-II-Schildgenerators teilnahmen. Diese Minifigur zeigt olivgrüne Tarnung, die für die dichte Vegetation des Waldmondes geeignet ist. Diese Elite-Soldaten bildeten das Stoßtrupp neben Han Solo und führten Guerilla-Operationen gegen überlegene imperiale Streitkräfte durch. Die olivgrüne Färbung spiegelt militärische Tarntradition wider, die für Endors spezifische Umgebung angepasst wurde. Rebellenkommandos nutzten Hit-and-Run-Taktiken, arbeiteten mit einheimischen Ewoks und eroberten schließlich den Schildgenerator-Bunker. Ihr Training betonte Heimlichkeit, Waldüberleben und unkonventionelle Kriegsführung gegen die technologischen Vorteile des Imperiums. Das generische Truppen-Design ermöglicht es Sammlern, vielfältige Rebellenstoßtrupps aufzubauen. Sammler schätzen Endor-Truppen für Army-Building, die Nachstellung des Bodenangriffs der Schlacht von Endor und die Darstellung der spezialisierten Einheiten, die den finalen Sieg der Rebellion ermöglichten.',
    description_fr: 'Les Soldats Rebelles d\'Endor étaient des commandos spécialisés formés pour la guerre forestière qui ont participé à la mission cruciale pour détruire le générateur de bouclier de l\'Étoile de la Mort II. Cette minifigurine présente un camouflage vert olive approprié pour la végétation dense de la lune forestière. Ces soldats d\'élite formaient l\'équipe d\'assaut aux côtés de Han Solo, menant des opérations de guérilla contre les forces impériales supérieures. La coloration olive reflète les traditions de camouflage militaire adaptées à l\'environnement spécifique d\'Endor. Les commandos rebelles utilisaient des tactiques de hit-and-run, travaillaient avec les Ewoks natifs et ont finalement capturé le bunker du générateur de bouclier. Leur formation mettait l\'accent sur la furtivité, la survie en forêt et la guerre non conventionnelle contre les avantages technologiques de l\'Empire. Le design de soldat générique permet aux collectionneurs de construire des équipes d\'assaut rebelles diverses. Les collectionneurs apprécient les soldats d\'Endor pour la construction d\'armée, la recréation de l\'assaut au sol de la Bataille d\'Endor et la représentation des unités spécialisées qui ont rendu possible la victoire finale de la Rébellion.',
    description_es: 'Los Soldados Rebeldes de Endor eran comandos especializados entrenados para guerra forestal que participaron en la misión crucial para destruir el generador de escudo de la Estrella de la Muerte II. Esta minifigura presenta camuflaje verde oliva apropiado para la densa vegetación de la luna boscosa. Estos soldados de élite formaron el equipo de asalto junto a Han Solo, conduciendo operaciones de guerrilla contra fuerzas imperiales superiores. La coloración oliva refleja tradiciones de camuflaje militar adaptadas al ambiente específico de Endor. Los comandos rebeldes usaban tácticas de golpear y correr, trabajaban con Ewoks nativos y finalmente capturaron el búnker del generador de escudo. Su entrenamiento enfatizaba sigilo, supervivencia en bosque y guerra no convencional contra las ventajas tecnológicas del Imperio. El diseño genérico de soldado permite a coleccionistas construir diversos equipos de asalto rebeldes. Los coleccionistas valoran a los soldados de Endor para construcción de ejércitos, recrear el asalto terrestre de la Batalla de Endor y representar las unidades especializadas que hicieron posible la victoria final de la Rebelión.'
  },
  {
    minifigure_no: 'sw0646',
    name: 'Endor Rebel Trooper - Dark Tan Vest, Tan Beard (Commander Rex)',
    description_en: 'This Endor Rebel Trooper features a dark tan vest and tan beard, with many fans speculating this represents the aged Clone Wars hero Captain Rex fighting in the Battle of Endor. The distinctive beard and veteran appearance suggest an older soldier with extensive combat experience. If this is Rex, it represents the legendary clone trooper who served with Anakin Skywalker during the Clone Wars continuing his fight against the Empire decades later. The dark tan vest matches Endor forest camouflage while the weathered appearance reflects years of guerrilla warfare. Rex\'s potential presence at Endor would complete his journey from Republic clone to Rebel veteran, spanning the entire galactic conflict. Whether officially Rex or simply a veteran Rebel commando, this figure represents the experienced warriors who formed the backbone of specialized strike teams. Collectors value this bearded variant for its potential Rex connection, veteran appearance, and representation of the Rebellion\'s seasoned fighters.',
    description_de: 'Dieser Endor-Rebellensoldat zeigt eine dunkle beige Weste und beigen Bart, wobei viele Fans spekulieren, dass dies den gealterten Klonkriegs-Helden Captain Rex darstellt, der in der Schlacht von Endor kämpft. Der markante Bart und das Veteranen-Erscheinungsbild deuten auf einen älteren Soldaten mit umfangreicher Kampferfahrung hin. Wenn dies Rex ist, repräsentiert es den legendären Klonkrieger, der während der Klonkriege mit Anakin Skywalker diente und seinen Kampf gegen das Imperium Jahrzehnte später fortsetzte. Die dunkle beige Weste passt zur Endor-Waldtarnung, während das verwitterte Erscheinungsbild Jahre der Guerilla-Kriegsführung widerspiegelt. Rex\' potenzielle Präsenz bei Endor würde seine Reise vom Republik-Klon zum Rebellenveteranen vervollständigen und den gesamten galaktischen Konflikt umspannen. Ob offiziell Rex oder einfach ein Veteranen-Rebellenkommando, diese Figur repräsentiert die erfahrenen Krieger, die das Rückgrat spezialisierter Stoßtrupps bildeten. Sammler schätzen diese bärtige Variante für ihre potenzielle Rex-Verbindung, Veteranen-Erscheinungsbild und Darstellung der erfahrenen Kämpfer der Rebellion.',
    description_fr: 'Ce Soldat Rebelle d\'Endor présente un gilet beige foncé et une barbe beige, de nombreux fans spéculant que cela représente le héros vieilli de la Guerre des Clones, le Capitaine Rex, combattant dans la Bataille d\'Endor. La barbe distinctive et l\'apparence de vétéran suggèrent un soldat plus âgé avec une vaste expérience de combat. Si c\'est Rex, cela représente le légendaire clone trooper qui a servi avec Anakin Skywalker pendant la Guerre des Clones continuant sa lutte contre l\'Empire des décennies plus tard. Le gilet beige foncé correspond au camouflage forestier d\'Endor tandis que l\'apparence patinée reflète des années de guerre de guérilla. La présence potentielle de Rex à Endor compléterait son voyage de clone de la République à vétéran rebelle, couvrant l\'ensemble du conflit galactique. Qu\'il soit officiellement Rex ou simplement un commando rebelle vétéran, cette figurine représente les guerriers expérimentés qui formaient l\'épine dorsale des équipes d\'assaut spécialisées. Les collectionneurs apprécient cette variante barbue pour sa connexion potentielle à Rex, son apparence de vétéran et la représentation des combattants aguerris de la Rébellion.',
    description_es: 'Este Soldado Rebelde de Endor presenta un chaleco beige oscuro y barba beige, con muchos fans especulando que esto representa al envejecido héroe de las Guerras Clon, el Capitán Rex, luchando en la Batalla de Endor. La barba distintiva y apariencia de veterano sugieren un soldado mayor con extensa experiencia de combate. Si este es Rex, representa al legendario clone trooper que sirvió con Anakin Skywalker durante las Guerras Clon continuando su lucha contra el Imperio décadas después. El chaleco beige oscuro coincide con el camuflaje del bosque de Endor mientras que la apariencia desgastada refleja años de guerra de guerrillas. La presencia potencial de Rex en Endor completaría su viaje desde clon de la República a veterano rebelde, abarcando todo el conflicto galáctico. Ya sea oficialmente Rex o simplemente un comando rebelde veterano, esta figura representa a los guerreros experimentados que formaron la columna vertebral de equipos de asalto especializados. Los coleccionistas valoran esta variante con barba por su potencial conexión con Rex, apariencia de veterano y representación de los luchadores experimentados de la Rebelión.'
  },
  {
    minifigure_no: 'sw0647',
    name: 'Agent Alexsandr Kallus - Hair',
    description_en: 'This Agent Kallus variant shows him without his combat helmet, featuring his distinctive hair and facial features as seen during his tenure with the Imperial Security Bureau. Kallus began as a ruthless ISB agent hunting Rebel cells with calculated efficiency, wielding his bo-rifle trophy taken from a defeated Lasat Honor Guard. His character arc in Star Wars Rebels evolved from cold Imperial enforcer to conflicted operative and ultimately Rebel spy codenamed Fulcrum. The hair-visible version represents Kallus during command briefings and strategic planning rather than frontline combat. His complex journey from believing in Imperial order to recognizing the Empire\'s evil made him one of Rebels\' most compelling characters. The unmasked appearance shows the man behind the ISB authority. Collectors value this variant for displaying Kallus\'s full character detail, representing his transformation arc, and creating more personal displays showing his internal conflict between duty and morality.',
    description_de: 'Diese Agent-Kallus-Variante zeigt ihn ohne Kampfhelm mit seinem markanten Haar und Gesichtszügen, wie während seiner Zeit beim Kaiserlichen Sicherheitsbüro gesehen. Kallus begann als rücksichtsloser ISB-Agent, der Rebellenzellen mit kalkulierter Effizienz jagte und sein Bo-Gewehr-Trophäe führte, die er von einem besiegten Lasat-Ehrenwächter nahm. Sein Charakterbogen in Star Wars Rebels entwickelte sich vom kalten imperialen Vollstrecker zum konfliktreichen Operativen und schließlich zum Rebellenspion mit Codenamen Fulcrum. Die sichtbare Haar-Version repräsentiert Kallus während Befehlsbriefings und strategischer Planung statt Frontlinienkampf. Seine komplexe Reise vom Glauben an die imperiale Ordnung zum Erkennen des Bösen des Imperiums machte ihn zu einem der überzeugendsten Charaktere von Rebels. Das unmaskierte Erscheinungsbild zeigt den Mann hinter der ISB-Autorität. Sammler schätzen diese Variante für die Darstellung von Kallus\' vollem Charakterdetail, Darstellung seines Transformationsbogens und Erstellung persönlicherer Displays, die seinen inneren Konflikt zwischen Pflicht und Moral zeigen.',
    description_fr: 'Cette variante de l\'Agent Kallus le montre sans son casque de combat, présentant ses cheveux distinctifs et ses traits faciaux comme on le voit pendant son mandat au Bureau de Sécurité Impérial. Kallus a commencé comme un agent ISB impitoyable chassant les cellules rebelles avec une efficacité calculée, maniant son fusil-bâton trophée pris à un Garde d\'Honneur Lasat vaincu. Son arc de personnage dans Star Wars Rebels a évolué d\'exécuteur impérial froid à opératif en conflit et finalement espion rebelle au nom de code Fulcrum. La version aux cheveux visibles représente Kallus pendant les briefings de commandement et la planification stratégique plutôt que le combat de première ligne. Son voyage complexe de la croyance dans l\'ordre impérial à la reconnaissance du mal de l\'Empire en a fait l\'un des personnages les plus convaincants de Rebels. L\'apparence sans masque montre l\'homme derrière l\'autorité de l\'ISB. Les collectionneurs apprécient cette variante pour afficher les détails complets du personnage de Kallus, représenter son arc de transformation et créer des displays plus personnels montrant son conflit interne entre devoir et moralité.',
    description_es: 'Esta variante del Agente Kallus lo muestra sin su casco de combate, presentando su distintivo cabello y rasgos faciales como se ve durante su mandato en el Buró de Seguridad Imperial. Kallus comenzó como un agente ISB despiadado cazando células rebeldes con eficiencia calculada, empuñando su trofeo de rifle-bastón tomado de un Guardia de Honor Lasat derrotado. Su arco de personaje en Star Wars Rebels evolucionó de ejecutor imperial frío a operativo conflictuado y finalmente espía rebelde con nombre en clave Fulcrum. La versión con cabello visible representa a Kallus durante briefings de comando y planificación estratégica en lugar de combate de primera línea. Su viaje complejo desde creer en el orden imperial a reconocer el mal del Imperio lo convirtió en uno de los personajes más convincentes de Rebels. La apariencia sin máscara muestra al hombre detrás de la autoridad del ISB. Los coleccionistas valoran esta variante por mostrar el detalle completo del personaje de Kallus, representar su arco de transformación y crear exhibiciones más personales mostrando su conflicto interno entre deber y moralidad.'
  }
];

async function saveBatch() {
  console.log('Starting batch save for sw0641-sw0647...');

  for (const minifig of batch) {
    try {
      await prisma.minifigCatalog.update({
        where: { minifigure_no: minifig.minifigure_no },
        data: {
          description_en: minifig.description_en,
          description_de: minifig.description_de,
          description_fr: minifig.description_fr,
          description_es: minifig.description_es,
          description_generated_at: new Date(),
          description_status: 'generated'
        },
      });
      console.log(`✓ Saved ${minifig.minifigure_no}: ${minifig.name}`);
    } catch (error) {
      console.error(`✗ Error saving ${minifig.minifigure_no}:`, error);
    }
  }

  console.log('Batch complete! 7 minifigs saved.');
  await prisma.$disconnect();
}

saveBatch();
