import { PrismaClient as PrismaClientHostinger } from '@prisma/client';

const prisma = new PrismaClientHostinger({
  datasources: {
    db: {
      url: process.env.DATABASE_URL
    }
  }
});

const descriptions = [
  {
    minifigure_no: 'sw1426',
    description_en: "Asajj Ventress with dark purple torso represents the formidable Nightsister assassin and former Sith apprentice. This figure features distinctive costume printing with the dark purple color scheme reflecting her dark side alignment. Ventress's dual-wielding lightsaber combat style and complex character arc make her memorable. Collectors value this variant for its unique color scheme and representation of one of The Clone Wars' most compelling antagonists.",
    description_de: "Asajj Ventress mit dunkelviolettem Torso repräsentiert die beeindruckende Nachtschwestern-Assassinin und ehemalige Sith-Schülerin. Diese Figur zeigt markanten Kostümdruck mit dem dunkelvioletten Farbschema, das ihre Ausrichtung zur dunklen Seite widerspiegelt. Ventress' Doppel-Lichtschwert-Kampfstil und komplexer Charakterbogen machen sie unvergesslich. Sammler schätzen diese Variante für ihr einzigartiges Farbschema und die Darstellung einer der fesselndsten Antagonisten von The Clone Wars.",
    description_fr: "Asajj Ventress avec torse violet foncé représente la formidable assassin Sœur de la Nuit et ancienne apprentie Sith. Cette figurine présente une impression de costume distinctive avec le schéma de couleurs violet foncé reflétant son alignement du côté obscur. Le style de combat au sabre laser double de Ventress et son arc de personnage complexe la rendent mémorable. Les collectionneurs apprécient cette variante pour son schéma de couleurs unique et sa représentation de l'une des antagonistes les plus convaincantes de The Clone Wars.",
    description_es: "Asajj Ventress con torso púrpura oscuro representa a la formidable asesina Hermana de la Noche y ex aprendiz Sith. Esta figura presenta impresión de vestuario distintiva con el esquema de color púrpura oscuro reflejando su alineación con el lado oscuro. El estilo de combate de doble sable de luz de Ventress y arco de personaje complejo la hacen memorable. Los coleccionistas valoran esta variante por su esquema de color único y representación de una de las antagonistas más convincentes de The Clone Wars."
  },
  {
    minifigure_no: 'sw1427',
    description_en: "Commando Droid in pearl dark gray represents the elite Separatist special forces droids. This figure features sleek armor design and unique metallic color scheme distinguishing them from standard battle droids. Commando droids' superior combat abilities and tactical skills make them formidable opponents. Collectors appreciate this droid for its distinctive color and representation of the Separatists' most capable automated soldiers.",
    description_de: "Kommandodroid in Perlendunkelgrau repräsentiert die Elite-Spezialeinheiten-Droiden der Separatisten. Diese Figur zeigt schlankes Rüstungsdesign und einzigartiges metallisches Farbschema, das sie von Standard-Kampfdroiden unterscheidet. Kommandodroiden überlegene Kampffähigkeiten und taktische Fertigkeiten machen sie zu beeindruckenden Gegnern. Sammler schätzen diesen Droiden für seine markante Farbe und Darstellung der fähigsten automatisierten Soldaten der Separatisten.",
    description_fr: "Le Droïde Commando en gris foncé perlé représente les droïdes de forces spéciales d'élite Séparatistes. Cette figurine présente un design d'armure élégant et un schéma de couleurs métalliques unique les distinguant des droïdes de combat standards. Les capacités de combat supérieures et les compétences tactiques des droïdes commando en font des adversaires redoutables. Les collectionneurs apprécient ce droïde pour sa couleur distinctive et sa représentation des soldats automatisés les plus capables des Séparatistes.",
    description_es: "Droide Comando en gris oscuro perlado representa a los droides de fuerzas especiales élite Separatistas. Esta figura presenta diseño de armadura elegante y esquema de color metálico único distinguiéndolos de droides de batalla estándar. Las habilidades de combate superiores y destrezas tácticas de los droides comando los hacen oponentes formidables. Los coleccionistas aprecian este droide por su color distintivo y representación de los soldados automatizados más capaces de los Separatistas."
  },
  {
    minifigure_no: 'sw1428',
    description_en: "Aayla Secura with nougat lips represents the Twi'lek Jedi Master in refined detail. This figure captures Aayla's distinctive blue skin and facial features with enhanced printing. Her role as a skilled Jedi General and tragic victim of Order 66 makes her significant. Collectors value this variant for its improved facial details and representation of one of the prequel trilogy's memorable Jedi Masters.",
    description_de: "Aayla Secura mit beigefarbenen Lippen repräsentiert die Twi'lek-Jedi-Meisterin mit raffiniertem Detail. Diese Figur fängt Aaylas markante blaue Haut und Gesichtszüge mit verbessertem Druck ein. Ihre Rolle als geschickte Jedi-Generalin und tragisches Opfer von Order 66 macht sie bedeutsam. Sammler schätzen diese Variante für ihre verbesserten Gesichtsdetails und Darstellung einer der einprägsamen Jedi-Meisterinnen der Prequel-Trilogie.",
    description_fr: "Aayla Secura avec des lèvres nougat représente le Maître Jedi Twi'lek avec des détails raffinés. Cette figurine capture la peau bleue distinctive d'Aayla et ses traits faciaux avec une impression améliorée. Son rôle en tant que Général Jedi qualifiée et victime tragique de l'Ordre 66 la rend significative. Les collectionneurs apprécient cette variante pour ses détails faciaux améliorés et sa représentation de l'une des Maîtres Jedi mémorables de la trilogie préquelle.",
    description_es: "Aayla Secura con labios nougat representa a la Maestra Jedi Twi'lek con detalle refinado. Esta figura captura la piel azul distintiva de Aayla y rasgos faciales con impresión mejorada. Su papel como General Jedi hábil y víctima trágica de la Orden 66 la hace significativa. Los coleccionistas valoran esta variante por sus detalles faciales mejorados y representación de una de las Maestras Jedi memorables de la trilogía de precuelas."
  },
  {
    minifigure_no: 'sw1429',
    description_en: "Clone Trooper Commander Bly represents the leader of the 327th Star Corps and Aayla Secura's trusted second-in-command. This figure features distinctive yellow markings with commander rank designation. Bly's tragic role in executing Order 66 against Aayla makes him a significant character. Collectors highly value this figure for representing a named clone commander with complex character history.",
    description_de: "Klonkrieger-Kommandant Bly repräsentiert den Anführer des 327. Sternenkorps und Aayla Securas vertrauten zweiten Kommandanten. Diese Figur zeigt markante gelbe Markierungen mit Kommandanten-Rangbezeichnung. Blys tragische Rolle bei der Ausführung von Order 66 gegen Aayla macht ihn zu einem bedeutenden Charakter. Sammler schätzen diese Figur sehr hoch für die Darstellung eines benannten Klonkommandanten mit komplexer Charaktergeschichte.",
    description_fr: "Le Commandant Clone Trooper Bly représente le chef du 327ème Corps Stellaire et le second de confiance d'Aayla Secura. Cette figurine présente des marques jaunes distinctives avec une désignation de rang de commandant. Le rôle tragique de Bly dans l'exécution de l'Ordre 66 contre Aayla en fait un personnage significatif. Les collectionneurs apprécient beaucoup cette figurine pour représenter un commandant clone nommé avec une histoire de personnage complexe.",
    description_es: "Comandante Clon Trooper Bly representa al líder del 327º Cuerpo Estelar y segundo al mando de confianza de Aayla Secura. Esta figura presenta marcas amarillas distintivas con designación de rango de comandante. El papel trágico de Bly al ejecutar la Orden 66 contra Aayla lo hace un personaje significativo. Los coleccionistas valoran altamente esta figura por representar un comandante clon nombrado con historia de personaje compleja."
  },
  {
    minifigure_no: 'sw1430',
    description_en: "Galactic Marine Clone Trooper represents the specialized cold-weather assault troops. This figure features distinctive armor design with unique helmet and color scheme adapted for harsh environments. Galactic Marines served under Commander Bacara during the Clone Wars. Collectors value these troopers for their unique armor design and specialized military role within the Grand Army.",
    description_de: "Galaktischer Marine-Klonkrieger repräsentiert die spezialisierten Kältewetter-Angriffstruppen. Diese Figur zeigt markantes Rüstungsdesign mit einzigartigem Helm und Farbschema, angepasst für raue Umgebungen. Galaktische Marines dienten unter Commander Bacara während der Klonkriege. Sammler schätzen diese Truppler für ihr einzigartiges Rüstungsdesign und spezialisierte militärische Rolle innerhalb der Großen Armee.",
    description_fr: "Le Clone Trooper Marine Galactique représente les troupes d'assaut spécialisées par temps froid. Cette figurine présente un design d'armure distinctif avec un casque unique et un schéma de couleurs adapté aux environnements hostiles. Les Marines Galactiques ont servi sous le Commandant Bacara pendant les Guerres des Clones. Les collectionneurs apprécient ces troopers pour leur design d'armure unique et leur rôle militaire spécialisé au sein de la Grande Armée.",
    description_es: "Soldado Clon Marino Galáctico representa a las tropas de asalto especializadas en clima frío. Esta figura presenta diseño de armadura distintivo con casco único y esquema de color adaptado para ambientes hostiles. Los Marinos Galácticos sirvieron bajo el Comandante Bacara durante las Guerras Clon. Los coleccionistas valoran estos soldados por su diseño de armadura único y papel militar especializado dentro del Gran Ejército."
  },
  {
    minifigure_no: 'sw1431',
    description_en: "Clone Commander Bacara represents the elite commander of the Galactic Marines and Ki-Adi-Mundi's second-in-command. This figure features distinctive armor markings showing his high rank and specialized unit. Bacara's role in executing Order 66 on Mygeeto makes him a significant character. Collectors highly prize this figure for representing a named clone commander with unique armor design and pivotal story moment.",
    description_de: "Klonkommandant Bacara repräsentiert den Elite-Kommandanten der Galaktischen Marines und Ki-Adi-Mundis zweiten Kommandanten. Diese Figur zeigt markante Rüstungsmarkierungen, die seinen hohen Rang und spezialisierte Einheit zeigen. Bacaras Rolle bei der Ausführung von Order 66 auf Mygeeto macht ihn zu einem bedeutenden Charakter. Sammler schätzen diese Figur sehr hoch für die Darstellung eines benannten Klonkommandanten mit einzigartigem Rüstungsdesign und entscheidendem Handlungsmoment.",
    description_fr: "Le Commandant Clone Bacara représente le commandant d'élite des Marines Galactiques et le second de Ki-Adi-Mundi. Cette figurine présente des marques d'armure distinctives montrant son rang élevé et son unité spécialisée. Le rôle de Bacara dans l'exécution de l'Ordre 66 sur Mygeeto en fait un personnage significatif. Les collectionneurs apprécient beaucoup cette figurine pour représenter un commandant clone nommé avec un design d'armure unique et un moment d'histoire crucial.",
    description_es: "Comandante Clon Bacara representa al comandante élite de los Marinos Galácticos y segundo al mando de Ki-Adi-Mundi. Esta figura presenta marcas de armadura distintivas mostrando su alto rango y unidad especializada. El papel de Bacara al ejecutar la Orden 66 en Mygeeto lo hace un personaje significativo. Los coleccionistas valoran altamente esta figura por representar un comandante clon nombrado con diseño de armadura único y momento crucial de la historia."
  },
  {
    minifigure_no: 'sw1432',
    description_en: "Ki-Adi-Mundi with printed legs and straight belt represents the Cerean Jedi Master and Council member in enhanced detail. This figure features improved costume printing showing complete Jedi robe details. Ki-Adi-Mundi's distinctive elongated head and wise presence make him recognizable. Collectors value this variant for its comprehensive printing and representation of a prominent prequel-era Jedi Council member.",
    description_de: "Ki-Adi-Mundi mit bedruckten Beinen und geradem Gürtel repräsentiert den cereanischen Jedi-Meister und Ratsmitglied mit verbessertem Detail. Diese Figur zeigt verbesserten Kostümdruck mit vollständigen Jedi-Robe-Details. Ki-Adi-Mundis markanter verlängerter Kopf und weise Präsenz machen ihn erkennbar. Sammler schätzen diese Variante für ihren umfassenden Druck und die Darstellung eines prominenten Jedi-Ratsmitglieds der Prequel-Ära.",
    description_fr: "Ki-Adi-Mundi avec des jambes imprimées et une ceinture droite représente le Maître Jedi Céréen et membre du Conseil avec des détails améliorés. Cette figurine présente une impression de costume améliorée montrant des détails complets de robe Jedi. La tête allongée distinctive de Ki-Adi-Mundi et sa présence sage le rendent reconnaissable. Les collectionneurs apprécient cette variante pour son impression complète et sa représentation d'un membre éminent du Conseil Jedi de l'ère préquelle.",
    description_es: "Ki-Adi-Mundi con piernas impresas y cinturón recto representa al Maestro Jedi Cereano y miembro del Consejo con detalle mejorado. Esta figura presenta impresión de vestuario mejorada mostrando detalles completos de túnica Jedi. La cabeza alargada distintiva de Ki-Adi-Mundi y presencia sabia lo hacen reconocible. Los coleccionistas valoran esta variante por su impresión completa y representación de un prominente miembro del Consejo Jedi de la era de precuelas."
  },
  {
    minifigure_no: 'sw1433',
    description_en: "Jango Fett with nougat head and plain arms represents a simpler version of the legendary bounty hunter. This figure features the unmasked head showing Jango's face with standard non-printed arms. The plain arms provide a more economical variant while maintaining character recognition. Collectors appreciate having different versions of Jango for various display purposes and building scenarios.",
    description_de: "Jango Fett mit beigefarbenem Kopf und einfachen Armen repräsentiert eine einfachere Version des legendären Kopfgeldjägers. Diese Figur zeigt den unmaskierten Kopf mit Jangos Gesicht mit Standard-nicht-bedruckten Armen. Die einfachen Arme bieten eine wirtschaftlichere Variante bei gleichzeitiger Aufrechterhaltung der Charaktererkennung. Sammler schätzen verschiedene Versionen von Jango für verschiedene Ausstellungszwecke und Bau-Szenarien.",
    description_fr: "Jango Fett avec tête nougat et bras simples représente une version plus simple du chasseur de primes légendaire. Cette figurine présente la tête sans masque montrant le visage de Jango avec des bras standards non imprimés. Les bras simples offrent une variante plus économique tout en maintenant la reconnaissance du personnage. Les collectionneurs apprécient avoir différentes versions de Jango pour divers objectifs d'affichage et scénarios de construction.",
    description_es: "Jango Fett con cabeza nougat y brazos simples representa una versión más simple del legendario cazarrecompensas. Esta figura presenta la cabeza sin máscara mostrando la cara de Jango con brazos estándar no impresos. Los brazos simples proporcionan una variante más económica mientras mantienen el reconocimiento del personaje. Los coleccionistas aprecian tener diferentes versiones de Jango para diversos propósitos de exhibición y escenarios de construcción."
  },
  {
    minifigure_no: 'sw1434',
    description_en: "Lama Su represents the Prime Minister of Kamino who oversaw the creation of the Clone Army. This figure captures the distinctive appearance of the tall, slender Kaminoan species with unique head mold. Lama Su's role in the Republic's secret clone program makes him narratively significant. Collectors value this figure for representing a key character in the clone origins story and distinctive alien design.",
    description_de: "Lama Su repräsentiert den Premierminister von Kamino, der die Erschaffung der Klonarmee überwachte. Diese Figur fängt das markante Aussehen der großen, schlanken Kaminoanischen Spezies mit einzigartiger Kopfform ein. Lama Sus Rolle im geheimen Klonprogramm der Republik macht ihn erzählerisch bedeutsam. Sammler schätzen diese Figur für die Darstellung eines Schlüsselcharakters in der Klon-Ursprungsgeschichte und markantes außerirdisches Design.",
    description_fr: "Lama Su représente le Premier Ministre de Kamino qui a supervisé la création de l'Armée des Clones. Cette figurine capture l'apparence distinctive de l'espèce Kaminoan grande et mince avec un moule de tête unique. Le rôle de Lama Su dans le programme de clones secret de la République le rend narrativement significatif. Les collectionneurs apprécient cette figurine pour représenter un personnage clé dans l'histoire des origines des clones et son design alien distinctif.",
    description_es: "Lama Su representa al Primer Ministro de Kamino que supervisó la creación del Ejército Clon. Esta figura captura la apariencia distintiva de la especie Kaminoana alta y delgada con molde de cabeza único. El papel de Lama Su en el programa clon secreto de la República lo hace narrativamente significativo. Los coleccionistas valoran esta figura por representar un personaje clave en la historia de orígenes clon y diseño alienígena distintivo."
  },
  {
    minifigure_no: 'sw1435',
    description_en: "Wicket with molded dark orange hood featuring wrinkles represents the brave young Ewok warrior who befriended Princess Leia. This figure captures Wicket's distinctive appearance with detailed hood sculpting showing fabric texture. His pivotal role in the Battle of Endor and helping the Rebellion defeat the Empire makes him beloved. Collectors highly value this figure for its enhanced molding detail and representation of the most famous Ewok.",
    description_de: "Wicket mit geformter dunkelorangener Kapuze mit Falten repräsentiert den mutigen jungen Ewok-Krieger, der sich mit Prinzessin Leia anfreundete. Diese Figur fängt Wickets markantes Aussehen mit detaillierter Kapuzenskulptur ein, die Stofftextur zeigt. Seine entscheidende Rolle in der Schlacht von Endor und beim Helfen der Rebellion, das Imperium zu besiegen, macht ihn beliebt. Sammler schätzen diese Figur sehr hoch für ihr verbessertes Formdetail und die Darstellung des berühmtesten Ewoks.",
    description_fr: "Wicket avec capuche orange foncé moulée comportant des rides représente le jeune guerrier Ewok courageux qui s'est lié d'amitié avec la Princesse Leia. Cette figurine capture l'apparence distinctive de Wicket avec une sculpture de capuche détaillée montrant la texture du tissu. Son rôle crucial dans la Bataille d'Endor et dans l'aide à la Rébellion pour vaincre l'Empire le rend adoré. Les collectionneurs apprécient beaucoup cette figurine pour ses détails de moulage améliorés et sa représentation de l'Ewok le plus célèbre.",
    description_es: "Wicket con capucha naranja oscuro moldeada que presenta arrugas representa al valiente joven guerrero Ewok que se hizo amigo de la Princesa Leia. Esta figura captura la apariencia distintiva de Wicket con escultura de capucha detallada mostrando textura de tela. Su papel crucial en la Batalla de Endor y ayudando a la Rebelión a derrotar al Imperio lo hace amado. Los coleccionistas valoran altamente esta figura por su detalle de moldeado mejorado y representación del Ewok más famoso."
  },
  {
    minifigure_no: 'sw1436',
    description_en: "Darth Dev (Darth Devastator) with vest represents an alternate costume for this original dark side character. This figure features vest design instead of cape, showing character variation. The vest provides a different silhouette while maintaining the menacing Sith aesthetic. Collectors appreciate having multiple costume options for original Sith characters in their collections.",
    description_de: "Darth Dev (Darth Devastator) mit Weste repräsentiert ein alternatives Kostüm für diesen originalen Charakter der dunklen Seite. Diese Figur zeigt Westendesign statt Umhang und zeigt Charaktervariation. Die Weste bietet eine andere Silhouette bei gleichzeitiger Beibehaltung der bedrohlichen Sith-Ästhetik. Sammler schätzen mehrere Kostümoptionen für originale Sith-Charaktere in ihren Sammlungen.",
    description_fr: "Darth Dev (Darth Devastator) avec gilet représente un costume alternatif pour ce personnage original du côté obscur. Cette figurine présente un design de gilet au lieu d'une cape, montrant une variation de personnage. Le gilet offre une silhouette différente tout en maintenant l'esthétique Sith menaçante. Les collectionneurs apprécient avoir plusieurs options de costume pour les personnages Sith originaux dans leurs collections.",
    description_es: "Darth Dev (Darth Devastator) con chaleco representa un vestuario alternativo para este personaje original del lado oscuro. Esta figura presenta diseño de chaleco en lugar de capa, mostrando variación de personaje. El chaleco proporciona una silueta diferente mientras mantiene la estética Sith amenazante. Los coleccionistas aprecian tener múltiples opciones de vestuario para personajes Sith originales en sus colecciones."
  },
  {
    minifigure_no: 'sw1437',
    description_en: "Sig Greebling in reddish brown robe represents an alternate costume for this Skeleton Crew character. This figure features Jedi-style robes suggesting different character circumstances or timeline. The reddish brown robe provides visual variety from his other appearance. Collectors appreciate having different costume variants for characters from the latest Star Wars series.",
    description_de: "Sig Greebling in rotbrauner Robe repräsentiert ein alternatives Kostüm für diesen Skeleton Crew-Charakter. Diese Figur zeigt Jedi-ähnliche Roben, die unterschiedliche Charakterumstände oder Zeitlinie suggerieren. Die rotbraune Robe bietet visuelle Vielfalt von seinem anderen Aussehen. Sammler schätzen unterschiedliche Kostümvarianten für Charaktere aus den neuesten Star Wars-Serien.",
    description_fr: "Sig Greebling dans une robe marron rougeâtre représente un costume alternatif pour ce personnage de Skeleton Crew. Cette figurine présente des robes de style Jedi suggérant des circonstances de personnage ou une chronologie différentes. La robe marron rougeâtre offre une variété visuelle par rapport à son autre apparence. Les collectionneurs apprécient avoir différentes variantes de costume pour les personnages des dernières séries Star Wars.",
    description_es: "Sig Greebling en túnica marrón rojizo representa un vestuario alternativo para este personaje de Skeleton Crew. Esta figura presenta túnicas estilo Jedi sugiriendo diferentes circunstancias de personaje o línea temporal. La túnica marrón rojizo proporciona variedad visual de su otra apariencia. Los coleccionistas aprecian tener diferentes variantes de vestuario para personajes de las series más recientes de Star Wars."
  },
  {
    minifigure_no: 'sw1438',
    description_en: "Solitus represents a character from Star Wars: Young Jedi Adventures, expanding the roster of High Republic era younglings. This figure captures a young Force-sensitive student with distinctive costume details. The Young Jedi Adventures characters introduce Star Wars to younger audiences. Collectors appreciate these figures for building complete High Republic collections and representing the franchise's educational content.",
    description_de: "Solitus repräsentiert einen Charakter aus Star Wars: Young Jedi Adventures und erweitert die Liste der Jünglinge der Ära der Hohen Republik. Diese Figur fängt einen jungen machtsensitiven Schüler mit markanten Kostümdetails ein. Die Young Jedi Adventures-Charaktere führen jüngere Zuschauer an Star Wars heran. Sammler schätzen diese Figuren für den Aufbau vollständiger Sammlungen der Hohen Republik und die Darstellung der Bildungsinhalte des Franchise.",
    description_fr: "Solitus représente un personnage de Star Wars: Young Jedi Adventures, élargissant la liste des jeunes de l'ère de la Haute République. Cette figurine capture un jeune étudiant sensible à la Force avec des détails de costume distinctifs. Les personnages de Young Jedi Adventures introduisent Star Wars à un public plus jeune. Les collectionneurs apprécient ces figurines pour construire des collections complètes de la Haute République et représenter le contenu éducatif de la franchise.",
    description_es: "Solitus representa un personaje de Star Wars: Young Jedi Adventures, expandiendo el elenco de jóvenes de la era de la Alta República. Esta figura captura a un joven estudiante sensible a la Fuerza con detalles de vestuario distintivos. Los personajes de Young Jedi Adventures introducen Star Wars a audiencias más jóvenes. Los coleccionistas aprecian estas figuras para construir colecciones completas de Alta República y representar el contenido educativo de la franquicia."
  },
  {
    minifigure_no: 'sw1439',
    description_en: "Babu Frik represents the tiny Anzellan droidsmith from The Rise of Skywalker who helped reprogram C-3PO. This figure captures Babu's diminutive size and distinctive alien features with detailed head mold. His technical expertise and cheerful personality made him an instant fan favorite. Collectors highly value this figure for its unique scale and representation of one of the sequel trilogy's most charming new characters.",
    description_de: "Babu Frik repräsentiert den winzigen Anzellan-Droidschmied aus Der Aufstieg Skywalkers, der half, C-3PO umzuprogrammieren. Diese Figur fängt Babus winzige Größe und markante außerirdische Merkmale mit detaillierter Kopfform ein. Seine technische Expertise und fröhliche Persönlichkeit machten ihn zum sofortigen Fan-Liebling. Sammler schätzen diese Figur sehr hoch für ihren einzigartigen Maßstab und die Darstellung eines der charmantesten neuen Charaktere der Sequel-Trilogie.",
    description_fr: "Babu Frik représente le minuscule forgeron de droïdes Anzellan de L'Ascension de Skywalker qui a aidé à reprogrammer C-3PO. Cette figurine capture la taille diminutive de Babu et ses traits aliens distinctifs avec un moule de tête détaillé. Son expertise technique et sa personnalité joyeuse en ont fait un favori instantané des fans. Les collectionneurs apprécient beaucoup cette figurine pour son échelle unique et sa représentation de l'un des nouveaux personnages les plus charmants de la trilogie suite.",
    description_es: "Babu Frik representa al diminuto herrero de droides Anzellan de El Ascenso de Skywalker que ayudó a reprogramar a C-3PO. Esta figura captura el tamaño diminuto de Babu y rasgos alienígenas distintivos con molde de cabeza detallado. Su experiencia técnica y personalidad alegre lo hicieron un favorito instantáneo de los fans. Los coleccionistas valoran altamente esta figura por su escala única y representación de uno de los personajes nuevos más encantadores de la trilogía secuela."
  },
  {
    minifigure_no: 'sw1440',
    description_en: "C-3PO with printed legs, toes, arms, and red eyes represents a dark side or corrupted version of the protocol droid. This figure features comprehensive printing with ominous red eyes instead of standard yellow. The red eyes suggest evil programming or Sith corruption. Collectors highly prize this variant for its complete printing and unique dark side interpretation of the beloved droid.",
    description_de: "C-3PO mit bedruckten Beinen, Zehen, Armen und roten Augen repräsentiert eine Version des Protokolldroiden der dunklen Seite oder korrumpiert. Diese Figur zeigt umfassenden Druck mit ominösen roten Augen statt standardmäßigem Gelb. Die roten Augen suggerieren böse Programmierung oder Sith-Korruption. Sammler schätzen diese Variante sehr hoch für ihren vollständigen Druck und einzigartige Interpretation der dunklen Seite des beliebten Droiden.",
    description_fr: "C-3PO avec jambes, orteils, bras imprimés et yeux rouges représente une version côté obscur ou corrompue du droïde de protocole. Cette figurine présente une impression complète avec des yeux rouges inquiétants au lieu du jaune standard. Les yeux rouges suggèrent une programmation maléfique ou une corruption Sith. Les collectionneurs apprécient beaucoup cette variante pour son impression complète et son interprétation unique du côté obscur du droïde bien-aimé.",
    description_es: "C-3PO con piernas, dedos de los pies, brazos impresos y ojos rojos representa una versión de lado oscuro o corrupta del droide de protocolo. Esta figura presenta impresión completa con ojos rojos ominosos en lugar de amarillo estándar. Los ojos rojos sugieren programación malvada o corrupción Sith. Los coleccionistas valoran altamente esta variante por su impresión completa e interpretación única de lado oscuro del droide amado."
  },
  {
    minifigure_no: 'sw1441',
    description_en: "Pit Droid with reddish brown skeleton arms represents a variant build for these maintenance droids. This figure features different arm construction showing mechanical variety. The skeleton arms provide visual interest and suggest worn or exposed mechanics. Collectors appreciate having different build options for pit droids to create varied repair bay scenes.",
    description_de: "Pit-Droid mit rotbraunen Skelettarmen repräsentiert eine Variantenkonstruktion für diese Wartungsdroiden. Diese Figur zeigt unterschiedliche Armkonstruktion mit mechanischer Vielfalt. Die Skelettarme bieten visuelles Interesse und suggerieren abgenutzte oder freiliegende Mechanik. Sammler schätzen unterschiedliche Bauoptionen für Pit-Droiden, um vielfältige Reparaturbucht-Szenen zu erstellen.",
    description_fr: "Le Droïde de Fosse avec des bras squelettiques marron rougeâtre représente une construction variante pour ces droïdes de maintenance. Cette figurine présente une construction de bras différente montrant une variété mécanique. Les bras squelettiques offrent un intérêt visuel et suggèrent une mécanique usée ou exposée. Les collectionneurs apprécient avoir différentes options de construction pour les droïdes de fosse pour créer des scènes de baie de réparation variées.",
    description_es: "Droide de Foso con brazos esqueleto marrón rojizo representa una construcción variante para estos droides de mantenimiento. Esta figura presenta construcción de brazo diferente mostrando variedad mecánica. Los brazos esqueleto proporcionan interés visual y sugieren mecánica desgastada o expuesta. Los coleccionistas aprecian tener diferentes opciones de construcción para droides de foso para crear escenas variadas de bahía de reparación."
  },
  {
    minifigure_no: 'sw1442',
    description_en: "Gonk Droid with body featuring trans-dark blue and trans-dark pink lights represents a festive variant of the GNK Power Droid. This figure features translucent colored elements suggesting holiday lighting or special event decoration. The colored lights add whimsy to the utilitarian droid design. Collectors appreciate this variant for its unique decorative elements and seasonal appeal.",
    description_de: "Gonk-Droid mit Körper mit transdunkelblauem und transdunkelrosa Lichtern repräsentiert eine festliche Variante des GNK-Stromdroiden. Diese Figur zeigt durchscheinende farbige Elemente, die Feiertagsbeleuchtung oder spezielle Eventdekoration suggerieren. Die farbigen Lichter fügen dem utilitaristischen Droid-Design Verspieltheit hinzu. Sammler schätzen diese Variante für ihre einzigartigen dekorativen Elemente und saisonale Anziehungskraft.",
    description_fr: "Le Droïde Gonk avec corps comportant des lumières bleu foncé transparent et rose foncé transparent représente une variante festive du Droïde d'Alimentation GNK. Cette figurine présente des éléments colorés translucides suggérant un éclairage de fête ou une décoration d'événement spécial. Les lumières colorées ajoutent de la fantaisie au design de droïde utilitaire. Les collectionneurs apprécient cette variante pour ses éléments décoratifs uniques et son attrait saisonnier.",
    description_es: "Droide Gonk con cuerpo que presenta luces azul oscuro transparente y rosa oscuro transparente representa una variante festiva del Droide de Energía GNK. Esta figura presenta elementos de color translúcido sugiriendo iluminación navideña o decoración de evento especial. Las luces de colores añaden capricho al diseño de droide utilitario. Los coleccionistas aprecian esta variante por sus elementos decorativos únicos y atractivo estacional."
  },
  {
    minifigure_no: 'sw1443',
    description_en: "Buzz Droid with tan dome tops represents the Separatist sabotage droids that attack starfighters. This figure features distinctive spider-like construction with cutting tools and grasping appendages. Buzz droids' swarming attacks on Republic ships during space battles made them memorable. Collectors value these droids for their unique construction and representation of Separatist anti-starfighter tactics.",
    description_de: "Buzz-Droid mit beigefarbenen Kuppelspitzen repräsentiert die Separatisten-Sabotage-Droiden, die Sternenjäger angreifen. Diese Figur zeigt markante spinnenähnliche Konstruktion mit Schneidewerkzeugen und greifenden Anhängseln. Buzz-Droiden schwärmende Angriffe auf republikanische Schiffe während Weltraumschlachten machten sie einprägsam. Sammler schätzen diese Droiden für ihre einzigartige Konstruktion und Darstellung separatistischer Anti-Sternenjäger-Taktiken.",
    description_fr: "Le Buzz Droïde avec des sommets de dôme beiges représente les droïdes de sabotage Séparatistes qui attaquent les chasseurs stellaires. Cette figurine présente une construction distinctive en forme d'araignée avec des outils de coupe et des appendices de préhension. Les attaques en essaim des Buzz droïdes sur les vaisseaux de la République pendant les batailles spatiales les ont rendus mémorables. Les collectionneurs apprécient ces droïdes pour leur construction unique et leur représentation des tactiques anti-chasseurs stellaires Séparatistes.",
    description_es: "Droide Buzz con partes superiores de cúpula beige representa a los droides de sabotaje Separatistas que atacan cazas estelares. Esta figura presenta construcción distintiva similar a araña con herramientas de corte y apéndices de agarre. Los ataques de enjambre de droides Buzz en naves de la República durante batallas espaciales los hicieron memorables. Los coleccionistas valoran estos droides por su construcción única y representación de tácticas anti-caza estelar Separatistas."
  },
  {
    minifigure_no: 'sw1444',
    description_en: "B2EMO (Bee-too-emo) represents Cassian Andor's loyal salvage droid from the Andor series. This figure captures the distinctive boxy design with weathered appearance and personality. B2EMO's emotional programming and companionship add heart to Cassian's origin story. Collectors highly value this droid for its unique design and representation of a beloved character from the critically acclaimed Andor series.",
    description_de: "B2EMO (Bee-too-emo) repräsentiert Cassian Andors treuen Bergungsdroiden aus der Andor-Serie. Diese Figur fängt das markante kastenförmige Design mit verwittertem Aussehen und Persönlichkeit ein. B2EMOs emotionale Programmierung und Kameradschaft fügen Cassians Ursprungsgeschichte Herz hinzu. Sammler schätzen diesen Droiden sehr hoch für sein einzigartiges Design und die Darstellung eines beliebten Charakters aus der von Kritikern gefeierten Andor-Serie.",
    description_fr: "B2EMO (Bee-too-emo) représente le droïde de récupération loyal de Cassian Andor de la série Andor. Cette figurine capture le design carré distinctif avec une apparence vieillie et de la personnalité. La programmation émotionnelle de B2EMO et sa compagnie ajoutent du cœur à l'histoire d'origine de Cassian. Les collectionneurs apprécient beaucoup ce droïde pour son design unique et sa représentation d'un personnage bien-aimé de la série Andor acclamée par la critique.",
    description_es: "B2EMO (Bee-too-emo) representa al droide de salvamento leal de Cassian Andor de la serie Andor. Esta figura captura el diseño distintivo cuadrado con apariencia desgastada y personalidad. La programación emocional de B2EMO y compañerismo añaden corazón a la historia de origen de Cassian. Los coleccionistas valoran altamente este droide por su diseño único y representación de un personaje querido de la aclamada por la crítica serie Andor."
  },
  {
    minifigure_no: 'sw1445',
    description_en: "Jawa in holiday sweater brings festive charm to the mysterious Tatooine scavengers. This figure features the iconic hooded robe with added holiday-themed costume elements. The design playfully combines Jawa mystique with seasonal celebration. Collectors value this figure for its limited seasonal availability and humorous crossover of Star Wars with holiday traditions.",
    description_de: "Jawa in Feiertagspullover bringt festlichen Charme zu den mysteriösen Tatooine-Plünderern. Diese Figur zeigt die ikonische Kapuzenrobe mit hinzugefügten feiertagsthematischen Kostümelementen. Das Design kombiniert spielerisch Jawa-Mystik mit saisonaler Feier. Sammler schätzen diese Figur für ihre begrenzte saisonale Verfügbarkeit und humorvolle Kreuzung von Star Wars mit Feiertagstraditionen.",
    description_fr: "Le Jawa dans un pull de fête apporte un charme festif aux mystérieux récupérateurs de Tatooine. Cette figurine présente la robe à capuche iconique avec des éléments de costume ajoutés sur le thème des fêtes. Le design combine de manière ludique le mystique Jawa avec la célébration saisonnière. Les collectionneurs apprécient cette figurine pour sa disponibilité saisonnière limitée et son croisement humoristique de Star Wars avec les traditions de fêtes.",
    description_es: "Jawa en suéter navideño trae encanto festivo a los misteriosos carroñeros de Tatooine. Esta figura presenta la túnica con capucha icónica con elementos de vestuario añadidos con temática navideña. El diseño combina juguetonamente la mística Jawa con celebración estacional. Los coleccionistas valoran esta figura por su disponibilidad estacional limitada y cruce humorístico de Star Wars con tradiciones navideñas."
  },
  {
    minifigure_no: 'sw1446',
    description_en: "Treadwell Droid in white and red body with light bluish gray binoculars represents the maintenance droids from moisture farms. This figure captures the distinctive cylindrical body with multiple tool appendages. Treadwells' appearance in A New Hope connecting to Owen Lars' farm makes them recognizable. Collectors appreciate this droid for its connection to the saga's origins and unique utilitarian design.",
    description_de: "Treadwell-Droid in weiß-rotem Körper mit hellblaugrauen Ferngläsern repräsentiert die Wartungsdroiden von Feuchtigkeitsfarmen. Diese Figur fängt den markanten zylindrischen Körper mit mehreren Werkzeuganhängseln ein. Treadwells Auftritt in Eine neue Hoffnung in Verbindung mit Owen Lars' Farm macht sie erkennbar. Sammler schätzen diesen Droiden für seine Verbindung zu den Ursprüngen der Saga und einzigartiges utilitaristisches Design.",
    description_fr: "Le Droïde Treadwell dans un corps blanc et rouge avec des jumelles gris bleuâtre clair représente les droïdes de maintenance des fermes d'humidité. Cette figurine capture le corps cylindrique distinctif avec plusieurs appendices d'outils. L'apparition des Treadwells dans Un Nouvel Espoir en connexion avec la ferme d'Owen Lars les rend reconnaissables. Les collectionneurs apprécient ce droïde pour sa connexion aux origines de la saga et son design utilitaire unique.",
    description_es: "Droide Treadwell en cuerpo blanco y rojo con binoculares gris azulado claro representa a los droides de mantenimiento de granjas de humedad. Esta figura captura el cuerpo cilíndrico distintivo con múltiples apéndices de herramientas. La aparición de Treadwells en Una Nueva Esperanza conectando con la granja de Owen Lars los hace reconocibles. Los coleccionistas aprecian este droide por su conexión con los orígenes de la saga y diseño utilitario único."
  },
  {
    minifigure_no: 'sw1447',
    description_en: "Battle Droid in tan with dark bluish gray left arm and antenna represents a damaged or scrap variant. This figure shows battle wear with mismatched parts suggesting field repairs or salvage. The antenna and mixed parts create a weathered battlefield aesthetic. Collectors appreciate this variant for adding realism to Separatist droid armies and representing the toll of Clone Wars combat.",
    description_de: "Kampfdroid in Beige mit dunkelblaugrauem linkem Arm und Antenne repräsentiert eine beschädigte oder Schrott-Variante. Diese Figur zeigt Kampfabnutzung mit unpassenden Teilen, die Feldreparaturen oder Bergung suggerieren. Die Antenne und gemischten Teile schaffen eine verwitterte Schlachtfeld-Ästhetik. Sammler schätzen diese Variante für das Hinzufügen von Realismus zu Separatisten-Droidarmeen und die Darstellung der Auswirkungen von Klonkriegskämpfen.",
    description_fr: "Le Droïde de Combat en beige avec bras gauche gris bleuâtre foncé et antenne représente une variante endommagée ou de ferraille. Cette figurine montre une usure de combat avec des pièces dépareillées suggérant des réparations sur le terrain ou de la récupération. L'antenne et les pièces mélangées créent une esthétique de champ de bataille vieillie. Les collectionneurs apprécient cette variante pour ajouter du réalisme aux armées de droïdes Séparatistes et représenter le tribut des combats des Guerres des Clones.",
    description_es: "Droide de Batalla en beige con brazo izquierdo gris azulado oscuro y antena representa una variante dañada o de chatarra. Esta figura muestra desgaste de batalla con partes desiguales sugiriendo reparaciones de campo o salvamento. La antena y partes mixtas crean una estética de campo de batalla desgastada. Los coleccionistas aprecian esta variante por añadir realismo a ejércitos de droides Separatistas y representar el costo de combates de Guerras Clon."
  },
  {
    minifigure_no: 'sw1448',
    description_en: "Mouse Droid (MSE-6) in holiday outfit brings seasonal cheer to the Empire's utility droids. This figure features the compact rectangular design with festive decorative elements. The holiday outfit playfully transforms the utilitarian Imperial droid. Collectors value this variant for its novelty and limited seasonal availability, adding whimsy to Star Wars holiday collections.",
    description_de: "Mausdroid (MSE-6) in Feiertagsoutfit bringt saisonale Freude zu den Nutzendroiden des Imperiums. Diese Figur zeigt das kompakte rechteckige Design mit festlichen dekorativen Elementen. Das Feiertagsoutfit verwandelt spielerisch den utilitaristischen imperialen Droiden. Sammler schätzen diese Variante für ihren Neuheitswert und begrenzte saisonale Verfügbarkeit, die Verspieltheit zu Star Wars-Feiertagssammlungen hinzufügt.",
    description_fr: "Le Droïde Souris (MSE-6) dans une tenue de fête apporte de la joie saisonnière aux droïdes utilitaires de l'Empire. Cette figurine présente le design rectangulaire compact avec des éléments décoratifs festifs. La tenue de fête transforme de manière ludique le droïde Impérial utilitaire. Les collectionneurs apprécient cette variante pour sa nouveauté et sa disponibilité saisonnière limitée, ajoutant de la fantaisie aux collections de fêtes Star Wars.",
    description_es: "Droide Ratón (MSE-6) en atuendo navideño trae alegría estacional a los droides utilitarios del Imperio. Esta figura presenta el diseño rectangular compacto con elementos decorativos festivos. El atuendo navideño transforma juguetonamente el droide Imperial utilitario. Los coleccionistas valoran esta variante por su novedad y disponibilidad estacional limitada, añadiendo capricho a colecciones navideñas de Star Wars."
  },
  {
    minifigure_no: 'sw1449',
    description_en: "Imperial Probe Droid with black and dark bluish gray body and trans-clear dish stand represents the reconnaissance droids deployed by the Empire. This figure captures the distinctive hovering design with multiple sensor appendages. The probe droid's role discovering the Rebel base on Hoth makes it narratively significant. Collectors highly value this figure for its unique construction and connection to The Empire Strikes Back's opening act.",
    description_de: "Imperialer Sondendroid mit schwarzem und dunkelblaugrauem Körper und transparentem Schüsselständer repräsentiert die vom Imperium eingesetzten Aufklärungsdroiden. Diese Figur fängt das markante schwebende Design mit mehreren Sensoranhängseln ein. Die Rolle des Sondendroiden bei der Entdeckung der Rebellenbasis auf Hoth macht ihn erzählerisch bedeutsam. Sammler schätzen diese Figur sehr hoch für ihre einzigartige Konstruktion und Verbindung zum Eröffnungsakt von Das Imperium schlägt zurück.",
    description_fr: "Le Droïde Sonde Impérial avec corps noir et gris bleuâtre foncé et support de plat transparent représente les droïdes de reconnaissance déployés par l'Empire. Cette figurine capture le design flottant distinctif avec plusieurs appendices de capteurs. Le rôle du droïde sonde dans la découverte de la base Rebelle sur Hoth le rend narrativement significatif. Les collectionneurs apprécient beaucoup cette figurine pour sa construction unique et sa connexion à l'acte d'ouverture de L'Empire Contre-Attaque.",
    description_es: "Droide Sonda Imperial con cuerpo negro y gris azulado oscuro y soporte de plato transparente representa a los droides de reconocimiento desplegados por el Imperio. Esta figura captura el diseño flotante distintivo con múltiples apéndices de sensores. El papel del droide sonda descubriendo la base Rebelde en Hoth lo hace narrativamente significativo. Los coleccionistas valoran altamente esta figura por su construcción única y conexión con el acto de apertura de El Imperio Contraataca."
  },
  {
    minifigure_no: 'sw1450',
    description_en: "Medical Droid in holiday outfit brings festive cheer to the galaxy's healthcare droids. This figure features medical droid design with added seasonal decorative elements. The holiday outfit playfully transforms the utilitarian medical assistant into a seasonal character. Collectors appreciate this variant for its novelty value and limited availability as part of Star Wars holiday collections.",
    description_de: "Medizinischer Droid in Feiertagsoutfit bringt festliche Freude zu den Gesundheitsdroiden der Galaxie. Diese Figur zeigt medizinisches Droid-Design mit hinzugefügten saisonalen dekorativen Elementen. Das Feiertagsoutfit verwandelt den utilitaristischen medizinischen Assistenten spielerisch in einen saisonalen Charakter. Sammler schätzen diese Variante für ihren Neuheitswert und begrenzte Verfügbarkeit als Teil von Star Wars-Feiertagssammlungen.",
    description_fr: "Le Droïde Médical dans une tenue de fête apporte de la joie festive aux droïdes de soins de santé de la galaxie. Cette figurine présente un design de droïde médical avec des éléments décoratifs saisonniers ajoutés. La tenue de fête transforme de manière ludique l'assistant médical utilitaire en personnage saisonnier. Les collectionneurs apprécient cette variante pour sa valeur de nouveauté et sa disponibilité limitée dans le cadre des collections de fêtes Star Wars.",
    description_es: "Droide Médico en atuendo navideño trae alegría festiva a los droides de atención médica de la galaxia. Esta figura presenta diseño de droide médico con elementos decorativos estacionales añadidos. El atuendo navideño transforma juguetonamente el asistente médico utilitario en un personaje estacional. Los coleccionistas aprecian esta variante por su valor de novedad y disponibilidad limitada como parte de colecciones navideñas de Star Wars."
  }
];

async function main() {
  console.log('Starting batch save for sw1426-sw1450...');

  for (const desc of descriptions) {
    await prisma.minifigCatalog.update({
      where: { minifigure_no: desc.minifigure_no },
      data: {
        description_en: desc.description_en,
        description_de: desc.description_de,
        description_fr: desc.description_fr,
        description_es: desc.description_es,
        description_generated_at: new Date(),
        description_status: 'completed'
      }
    });
    console.log(`✓ Saved ${desc.minifigure_no}: ${desc.minifigure_no}`);
  }

  await prisma.$disconnect();
  console.log(`Batch complete! 25 minifigs saved (sw1426-sw1450).`);
}

main().catch(async (e) => {
  console.error('Error:', e);
  await prisma.$disconnect();
  process.exit(1);
});
