import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0409',
    name: 'Obi-Wan Kenobi (Breathing Apparatus)',
    en: 'Young Obi-Wan Kenobi appears in this 2012 minifigure wearing an underwater breathing apparatus during the opening sequence of The Phantom Menace aboard the Trade Federation battleship. This version features Obi-Wan in his Jedi Padawan robes with detailed torso printing, along with a transparent breathing mask accessory that covers the lower face. The figure captures the moment when Qui-Gon and Obi-Wan infiltrate the Trade Federation ship to negotiate the Naboo blockade, only to be ambushed and forced to escape through the ventilation system. The breathing apparatus represents the Jedi\'s resourcefulness and preparedness for dangerous missions. Released in set 9499 Gungan Sub, this specialized variant is essential for recreating the underwater escape sequence. Highly valued by Episode I collectors and fans of young Obi-Wan during his Padawan years under Qui-Gon Jinn\'s tutelage.',
    de: 'Der junge Obi-Wan Kenobi erscheint in dieser 2012er-Minifigur mit einem Unterwasser-Atemgerät während der Eröffnungssequenz von Die dunkle Bedrohung an Bord des Handelsföderation-Schlachtschiffs. Diese Version zeigt Obi-Wan in seinen Jedi-Padawan-Roben mit detailliertem Torso-Druck, zusammen mit einem transparenten Atemmasken-Zubehör, das das untere Gesicht bedeckt. Die Figur erfasst den Moment, als Qui-Gon und Obi-Wan das Handelsföderation-Schiff infiltrieren, um die Naboo-Blockade zu verhandeln, nur um in einen Hinterhalt zu geraten und gezwungen zu werden, durch das Lüftungssystem zu fliehen. Das Atemgerät repräsentiert die Findigkeit und Vorbereitung der Jedi für gefährliche Missionen. Veröffentlicht im Set 9499 Gungan U-Boot, ist diese spezialisierte Variante unverzichtbar für die Nachstellung der Unterwasser-Fluchtsequenz. Hoch geschätzt von Episode-I-Sammlern und Fans des jungen Obi-Wan während seiner Padawan-Jahre unter Qui-Gon Jinn\'s Anleitung.',
    fr: 'Le jeune Obi-Wan Kenobi apparaît dans cette minifigurine de 2012 portant un appareil respiratoire sous-marin pendant la séquence d\'ouverture de La Menace Fantôme à bord du vaisseau de guerre de la Fédération du Commerce. Cette version présente Obi-Wan dans ses robes de Padawan Jedi avec une impression de torse détaillée, ainsi qu\'un accessoire de masque respiratoire transparent qui couvre le bas du visage. La figurine capture le moment où Qui-Gon et Obi-Wan infiltrent le vaisseau de la Fédération du Commerce pour négocier le blocus de Naboo, seulement pour être pris en embuscade et forcés de s\'échapper par le système de ventilation. L\'appareil respiratoire représente l\'ingéniosité et la préparation des Jedi pour les missions dangereuses. Sortie dans le set 9499 Sous-marin Gungan, cette variante spécialisée est essentielle pour recréer la séquence d\'évasion sous-marine. Très appréciée des collectionneurs de l\'Épisode I et des fans du jeune Obi-Wan pendant ses années de Padawan sous la tutelle de Qui-Gon Jinn.',
    es: 'El joven Obi-Wan Kenobi aparece en esta minifigura de 2012 usando un aparato de respiración subacuático durante la secuencia de apertura de La Amenaza Fantasma a bordo del acorazado de la Federación de Comercio. Esta versión presenta a Obi-Wan en sus túnicas de Padawan Jedi con impresión de torso detallada, junto con un accesorio de máscara respiratoria transparente que cubre la parte inferior del rostro. La figura captura el momento cuando Qui-Gon y Obi-Wan infiltran la nave de la Federación de Comercio para negociar el bloqueo de Naboo, solo para ser emboscados y forzados a escapar a través del sistema de ventilación. El aparato de respiración representa el ingenio y preparación de los Jedi para misiones peligrosas. Lanzada en el set 9499 Submarino Gungan, esta variante especializada es esencial para recrear la secuencia de escape submarino. Muy valorada por coleccionistas del Episodio I y fans del joven Obi-Wan durante sus años de Padawan bajo la tutela de Qui-Gon Jinn.'
  },
  {
    no: 'sw0410',
    name: 'Qui-Gon Jinn (Breathing Apparatus)',
    en: 'Jedi Master Qui-Gon Jinn appears in this 2012 minifigure equipped with an underwater breathing apparatus from the opening of The Phantom Menace. This version shows Qui-Gon in his tan Jedi robes with detailed torso printing and long brown hair, accompanied by a transparent breathing mask that enabled him and Obi-Wan to survive their escape from the Trade Federation battleship through the underwater core of Naboo. The breathing apparatus demonstrates Qui-Gon\'s wisdom and preparation for unexpected dangers during diplomatic missions. His calm demeanor even in crisis situations exemplifies his mastery of the Force and role as Obi-Wan\'s mentor. Released in set 9499 Gungan Sub, this specialized figure is essential for recreating the Naboo underwater journey and the Jedi\'s first encounter with Jar Jar Binks. Highly collectible for Episode I fans and those building complete Qui-Gon Jinn variant collections from his brief but impactful appearances.',
    de: 'Jedi-Meister Qui-Gon Jinn erscheint in dieser 2012er-Minifigur ausgestattet mit einem Unterwasser-Atemgerät aus der Eröffnung von Die dunkle Bedrohung. Diese Version zeigt Qui-Gon in seinen sandfarbenen Jedi-Roben mit detailliertem Torso-Druck und langem braunem Haar, begleitet von einer transparenten Atemmaske, die ihm und Obi-Wan ermöglichte, ihre Flucht vom Handelsföderation-Schlachtschiff durch den Unterwasserkern von Naboo zu überleben. Das Atemgerät demonstriert Qui-Gon\'s Weisheit und Vorbereitung auf unerwartete Gefahren während diplomatischer Missionen. Seine ruhige Haltung selbst in Krisensituationen verkörpert seine Beherrschung der Macht und Rolle als Obi-Wan\'s Mentor. Veröffentlicht im Set 9499 Gungan U-Boot, ist diese spezialisierte Figur unverzichtbar für die Nachstellung der Naboo-Unterwasser-Reise und der ersten Begegnung der Jedi mit Jar Jar Binks. Sehr sammelbar für Episode-I-Fans und jene, die vollständige Qui-Gon Jinn-Varianten-Sammlungen aus seinen kurzen, aber eindrucksvollen Auftritten aufbauen.',
    fr: 'Le Maître Jedi Qui-Gon Jinn apparaît dans cette minifigurine de 2012 équipé d\'un appareil respiratoire sous-marin de l\'ouverture de La Menace Fantôme. Cette version montre Qui-Gon dans ses robes Jedi beiges avec une impression de torse détaillée et de longs cheveux bruns, accompagné d\'un masque respiratoire transparent qui lui a permis ainsi qu\'à Obi-Wan de survivre à leur évasion du vaisseau de guerre de la Fédération du Commerce à travers le noyau sous-marin de Naboo. L\'appareil respiratoire démontre la sagesse et la préparation de Qui-Gon pour les dangers inattendus lors de missions diplomatiques. Son comportement calme même dans les situations de crise exemplifie sa maîtrise de la Force et son rôle de mentor d\'Obi-Wan. Sortie dans le set 9499 Sous-marin Gungan, cette figurine spécialisée est essentielle pour recréer le voyage sous-marin de Naboo et la première rencontre des Jedi avec Jar Jar Binks. Hautement collectionnable pour les fans de l\'Épisode I et ceux qui construisent des collections complètes de variantes de Qui-Gon Jinn de ses apparitions brèves mais marquantes.',
    es: 'El Maestro Jedi Qui-Gon Jinn aparece en esta minifigura de 2012 equipado con un aparato de respiración subacuático de la apertura de La Amenaza Fantasma. Esta versión muestra a Qui-Gon en sus túnicas Jedi beige con impresión de torso detallada y cabello largo marrón, acompañado de una máscara respiratoria transparente que le permitió a él y a Obi-Wan sobrevivir su escape del acorazado de la Federación de Comercio a través del núcleo submarino de Naboo. El aparato de respiración demuestra la sabiduría y preparación de Qui-Gon para peligros inesperados durante misiones diplomáticas. Su comportamiento calmado incluso en situaciones de crisis ejemplifica su maestría de la Fuerza y papel como mentor de Obi-Wan. Lanzada en el set 9499 Submarino Gungan, esta figura especializada es esencial para recrear el viaje submarino de Naboo y el primer encuentro de los Jedi con Jar Jar Binks. Altamente coleccionable para fans del Episodio I y aquellos construyendo colecciones completas de variantes de Qui-Gon Jinn de sus apariciones breves pero impactantes.'
  },
  {
    no: 'sw0411',
    name: 'Padmé Amidala - Senator, Large Eyes, Red Lips',
    en: 'Senator Padmé Amidala appears in this 2012 minifigure representing her role as Naboo\'s representative in the Galactic Senate during The Clone Wars era. This version features Padmé in elegant senatorial attire with detailed torso printing showing ornate robes and jewelry befitting her diplomatic position. The large expressive eyes and red lips capture her beauty and determination as she fights for peace and democracy while secretly married to Anakin Skywalker. This senator costume reflects Padmé\'s evolution from Queen to political leader working to prevent the Republic\'s collapse. Released in set 9515 The Malevolence, this figure represents Padmé during her most politically active period balancing her public duties with her forbidden romance. Essential for Clone Wars collectors and fans of Padmé\'s character as she transforms from monarch to one of the Republic\'s most vocal opponents of the growing conflict and Palpatine\'s consolidation of power.',
    de: 'Senatorin Padmé Amidala erscheint in dieser 2012er-Minifigur und repräsentiert ihre Rolle als Naboo\'s Vertreterin im Galaktischen Senat während der Clone Wars-Ära. Diese Version zeigt Padmé in eleganter Senatoren-Kleidung mit detailliertem Torso-Druck, der verzierte Roben und Schmuck zeigt, die ihrer diplomatischen Position entsprechen. Die großen ausdrucksvollen Augen und roten Lippen erfassen ihre Schönheit und Entschlossenheit, während sie für Frieden und Demokratie kämpft, während sie heimlich mit Anakin Skywalker verheiratet ist. Dieses Senatoren-Kostüm spiegelt Padmé\'s Entwicklung von der Königin zur politischen Führerin wider, die daran arbeitet, den Zusammenbruch der Republik zu verhindern. Veröffentlicht im Set 9515 Die Malevolence, repräsentiert diese Figur Padmé während ihrer politisch aktivsten Periode, in der sie ihre öffentlichen Pflichten mit ihrer verbotenen Romanze in Einklang bringt. Unverzichtbar für Clone Wars-Sammler und Fans von Padmé\'s Charakter, während sie sich von Monarchin zu einer der lautstärksten Gegnerinnen der Republik gegen den wachsenden Konflikt und Palpatine\'s Machtkonsolidierung verwandelt.',
    fr: 'La Sénatrice Padmé Amidala apparaît dans cette minifigurine de 2012 représentant son rôle de représentante de Naboo au Sénat Galactique pendant l\'ère des Guerres des Clones. Cette version présente Padmé dans une tenue sénatoriale élégante avec une impression de torse détaillée montrant des robes ornées et des bijoux correspondant à sa position diplomatique. Les grands yeux expressifs et les lèvres rouges capturent sa beauté et sa détermination alors qu\'elle se bat pour la paix et la démocratie tout en étant secrètement mariée à Anakin Skywalker. Ce costume de sénatrice reflète l\'évolution de Padmé de Reine à dirigeante politique travaillant pour empêcher l\'effondrement de la République. Sortie dans le set 9515 La Malevolence, cette figurine représente Padmé pendant sa période la plus politiquement active équilibrant ses devoirs publics avec sa romance interdite. Essentielle pour les collectionneurs de Clone Wars et les fans du personnage de Padmé alors qu\'elle se transforme de monarque en l\'une des opposantes les plus virulentes de la République contre le conflit croissant et la consolidation du pouvoir de Palpatine.',
    es: 'La Senadora Padmé Amidala aparece en esta minifigura de 2012 representando su papel como representante de Naboo en el Senado Galáctico durante la era de las Guerras Clon. Esta versión presenta a Padmé en elegante atuendo senatorial con impresión de torso detallada mostrando túnicas ornamentadas y joyas apropiadas para su posición diplomática. Los grandes ojos expresivos y labios rojos capturan su belleza y determinación mientras lucha por la paz y la democracia mientras está secretamente casada con Anakin Skywalker. Este vestuario de senadora refleja la evolución de Padmé de Reina a líder política trabajando para prevenir el colapso de la República. Lanzada en el set 9515 El Malevolencia, esta figura representa a Padmé durante su período más políticamente activo equilibrando sus deberes públicos con su romance prohibido. Esencial para coleccionistas de Clone Wars y fans del personaje de Padmé mientras se transforma de monarca a una de las opositoras más vocales de la República contra el creciente conflicto y la consolidación del poder de Palpatine.'
  },
  {
    no: 'sw0412',
    name: 'B\'Omarr Monk - Trans-Orange Plate',
    en: 'The B\'omarr Monk represents one of Star Wars\' most bizarre and unsettling creatures - disembodied brains housed in transparent jars mounted on spider-like droid walkers. This 2012 figure captures the eerie design with a trans-orange plate representing the preservation fluid in which the monk\'s brain floats, mounted on mechanical legs. These ascetic monks voluntarily remove their brains to eliminate physical distractions and achieve enlightenment, residing in their monastery beneath Jabba\'s Palace on Tatooine long before the Hutt crime lord claimed it. The mechanical walker allows the brain to move about while contemplating the universe. Released in set 9516 Jabba\'s Palace, this deeply unsettling figure adds authentic atmosphere to palace displays. Highly collectible for its unique and disturbing design, essential for fans of Star Wars\' stranger alien species and those seeking to complete comprehensive Jabba\'s Palace collections with every bizarre inhabitant.',
    de: 'Der B\'omarr-Mönch repräsentiert eine von Star Wars\' bizarrsten und verstörendsten Kreaturen - körperlose Gehirne in transparenten Gläsern untergebracht, die auf spinnenartigen Droiden-Läufern montiert sind. Diese 2012er-Figur erfasst das unheimliche Design mit einer trans-orangefarbenen Platte, die die Konservierungsflüssigkeit repräsentiert, in der das Gehirn des Mönchs schwimmt, montiert auf mechanischen Beinen. Diese asketischen Mönche entfernen freiwillig ihre Gehirne, um körperliche Ablenkungen zu eliminieren und Erleuchtung zu erlangen, und residieren in ihrem Kloster unter Jabba\'s Palast auf Tatooine lange bevor der Hutten-Verbrecherlord es beanspruchte. Der mechanische Läufer ermöglicht es dem Gehirn, sich zu bewegen, während es über das Universum nachdenkt. Veröffentlicht im Set 9516 Jabba\'s Palast, fügt diese zutiefst verstörende Figur authentische Atmosphäre zu Palast-Darstellungen hinzu. Sehr sammelbar für ihr einzigartiges und verstörendes Design, unverzichtbar für Fans von Star Wars\' seltsameren außerirdischen Spezies und jene, die umfassende Jabba\'s Palast-Sammlungen mit jedem bizarren Bewohner vervollständigen möchten.',
    fr: 'Le Moine B\'omarr représente l\'une des créatures les plus bizarres et troublantes de Star Wars - des cerveaux désincarnés logés dans des bocaux transparents montés sur des marcheurs droïdes ressemblant à des araignées. Cette figurine de 2012 capture le design inquiétant avec une plaque trans-orange représentant le fluide de préservation dans lequel flotte le cerveau du moine, monté sur des jambes mécaniques. Ces moines ascétiques retirent volontairement leurs cerveaux pour éliminer les distractions physiques et atteindre l\'illumination, résidant dans leur monastère sous le Palais de Jabba sur Tatooine bien avant que le seigneur du crime Hutt ne le revendique. Le marcheur mécanique permet au cerveau de se déplacer tout en contemplant l\'univers. Sortie dans le set 9516 Palais de Jabba, cette figurine profondément troublante ajoute une atmosphère authentique aux affichages du palais. Hautement collectionnable pour son design unique et dérangeant, essentielle pour les fans des espèces extraterrestres les plus étranges de Star Wars et ceux cherchant à compléter des collections complètes du Palais de Jabba avec chaque habitant bizarre.',
    es: 'El Monje B\'omarr representa una de las criaturas más bizarras e inquietantes de Star Wars - cerebros desencarnados alojados en frascos transparentes montados en caminantes droide similares a arañas. Esta figura de 2012 captura el diseño espeluznante con una placa trans-naranja representando el fluido de preservación en el que flota el cerebro del monje, montado sobre piernas mecánicas. Estos monjes ascéticos voluntariamente remueven sus cerebros para eliminar distracciones físicas y alcanzar la iluminación, residiendo en su monasterio bajo el Palacio de Jabba en Tatooine mucho antes de que el señor del crimen Hutt lo reclamara. El caminante mecánico permite al cerebro moverse mientras contempla el universo. Lanzada en el set 9516 Palacio de Jabba, esta figura profundamente inquietante añade atmósfera auténtica a exhibiciones del palacio. Altamente coleccionable por su diseño único y perturbador, esencial para fans de las especies alienígenas más extrañas de Star Wars y aquellos buscando completar colecciones completas del Palacio de Jabba con cada habitante bizarro.'
  },
  {
    no: 'sw0413',
    name: 'Darth Malgus',
    en: 'Darth Malgus, one of the most powerful Sith Lords of the Old Republic era, appears in this 2012 minifigure representing the brutal warrior who led the Sacking of Coruscant. This figure captures Malgus\'s distinctive appearance with detailed printing showing his black armor, scarred face, and the breathing apparatus required after severe injuries sustained in battle. His red lightsaber and imposing presence reflect his role as a fearsome Sith warrior who believed in purifying the Empire through conflict. Malgus\'s philosophy of strength through combat and his eventual rebellion against the Dark Council make him one of the most complex Sith characters in Star Wars Legends. Released as a promotional item and in limited sets, Darth Malgus is exceptionally rare and highly sought by collectors. Essential for Old Republic fans and those collecting powerful Sith Lords, this figure represents one of the era\'s most iconic dark side users from The Old Republic video game and novels.',
    de: 'Darth Malgus, einer der mächtigsten Sith-Lords der Ära der Alten Republik, erscheint in dieser 2012er-Minifigur und repräsentiert den brutalen Krieger, der die Plünderung von Coruscant anführte. Diese Figur erfasst Malgus\'s charakteristisches Erscheinungsbild mit detailliertem Druck, der seine schwarze Rüstung, vernarbtes Gesicht und das Atemgerät zeigt, das nach schweren im Kampf erlittenen Verletzungen erforderlich ist. Sein rotes Lichtschwert und seine imposante Präsenz spiegeln seine Rolle als furchteinflößender Sith-Krieger wider, der an die Reinigung des Imperiums durch Konflikt glaubte. Malgus\'s Philosophie der Stärke durch Kampf und seine spätere Rebellion gegen den Dunklen Rat machen ihn zu einem der komplexesten Sith-Charaktere in Star Wars Legends. Veröffentlicht als Werbeartikel und in limitierten Sets, ist Darth Malgus außergewöhnlich selten und von Sammlern sehr begehrt. Unverzichtbar für Fans der Alten Republik und jene, die mächtige Sith-Lords sammeln, repräsentiert diese Figur einen der ikonischsten Nutzer der dunklen Seite der Ära aus dem The Old Republic Videospiel und Romanen.',
    fr: 'Dark Malgus, l\'un des Seigneurs Sith les plus puissants de l\'ère de l\'Ancienne République, apparaît dans cette minifigurine de 2012 représentant le guerrier brutal qui a mené le Sac de Coruscant. Cette figurine capture l\'apparence distinctive de Malgus avec une impression détaillée montrant son armure noire, son visage cicatrisé et l\'appareil respiratoire requis après de graves blessures subies au combat. Son sabre laser rouge et sa présence imposante reflètent son rôle de guerrier Sith redoutable qui croyait en la purification de l\'Empire par le conflit. La philosophie de Malgus de la force par le combat et sa rébellion éventuelle contre le Conseil Noir en font l\'un des personnages Sith les plus complexes de Star Wars Legends. Sortie comme article promotionnel et dans des sets limités, Dark Malgus est exceptionnellement rare et très recherché par les collectionneurs. Essentielle pour les fans de l\'Ancienne République et ceux qui collectionnent les puissants Seigneurs Sith, cette figurine représente l\'un des utilisateurs du côté obscur les plus iconiques de l\'ère du jeu vidéo et des romans The Old Republic.',
    es: 'Darth Malgus, uno de los Señores Sith más poderosos de la era de la Antigua República, aparece en esta minifigura de 2012 representando al brutal guerrero que lideró el Saqueo de Coruscant. Esta figura captura la apariencia distintiva de Malgus con impresión detallada mostrando su armadura negra, rostro cicatrizado y el aparato respiratorio requerido después de graves lesiones sufridas en batalla. Su sable de luz rojo y presencia imponente reflejan su papel como temible guerrero Sith que creía en purificar el Imperio a través del conflicto. La filosofía de Malgus de fuerza a través del combate y su eventual rebelión contra el Consejo Oscuro lo convierten en uno de los personajes Sith más complejos en Star Wars Legends. Lanzado como artículo promocional y en sets limitados, Darth Malgus es excepcionalmente raro y muy buscado por coleccionistas. Esencial para fans de la Antigua República y aquellos coleccionando poderosos Señores Sith, esta figura representa a uno de los usuarios del lado oscuro más icónicos de la era del videojuego y novelas The Old Republic.'
  },
  {
    no: 'sw0414',
    name: 'Sith Trooper - Black Armor, Plain Legs',
    en: 'The Sith Trooper serves as elite infantry for the reconstituted Sith Empire during The Old Republic era, clad in distinctive black armor that contrasts sharply with Republic forces. This 2012 minifigure features detailed printing showing the angular, menacing armor design with red accents that mark these soldiers as Sith military forces. Unlike the individual Sith Lords, these troopers represent the Empire\'s massive military machine powered by countless soldiers following the dark side\'s philosophy of strength and domination. The plain legs design keeps focus on the iconic chest armor that became synonymous with Old Republic Sith military aesthetics. Released in set 9500 Fury-class Interceptor, Sith Troopers are perfect for army building to create imposing Sith invasion forces. Essential for Old Republic collectors recreating the Great Galactic War and fans who appreciate the distinct visual identity of the ancient Sith Empire\'s military forces.',
    de: 'Der Sith-Soldat dient als Elite-Infanterie für das wiederhergestellte Sith-Imperium während der Ära der Alten Republik, bekleidet mit charakteristischer schwarzer Rüstung, die scharf mit den Republik-Streitkräften kontrastiert. Diese 2012er-Minifigur zeigt detaillierten Druck, der das kantige, bedrohliche Rüstungsdesign mit roten Akzenten zeigt, die diese Soldaten als Sith-Militärkräfte kennzeichnen. Im Gegensatz zu den einzelnen Sith-Lords repräsentieren diese Soldaten die massive Militärmaschine des Imperiums, angetrieben von unzähligen Soldaten, die der Philosophie der dunklen Seite von Stärke und Herrschaft folgen. Das schlichte Beindesign hält den Fokus auf der ikonischen Brustrüstung, die zum Synonym für die militärische Ästhetik der Sith der Alten Republik wurde. Veröffentlicht im Set 9500 Fury-class Interceptor, sind Sith-Soldaten perfekt für Armeeaufbau, um imposante Sith-Invasionskräfte zu schaffen. Unverzichtbar für Sammler der Alten Republik, die den Großen Galaktischen Krieg nachstellen, und Fans, die die charakteristische visuelle Identität der militärischen Streitkräfte des alten Sith-Imperiums schätzen.',
    fr: 'Le Soldat Sith sert d\'infanterie d\'élite pour l\'Empire Sith reconstitué pendant l\'ère de l\'Ancienne République, vêtu d\'une armure noire distinctive qui contraste fortement avec les forces de la République. Cette minifigurine de 2012 présente une impression détaillée montrant le design d\'armure angulaire et menaçant avec des accents rouges qui marquent ces soldats comme forces militaires Sith. Contrairement aux Seigneurs Sith individuels, ces soldats représentent la machine militaire massive de l\'Empire alimentée par d\'innombrables soldats suivant la philosophie du côté obscur de la force et de la domination. Le design de jambes simples maintient l\'accent sur l\'armure de poitrine iconique qui est devenue synonyme de l\'esthétique militaire Sith de l\'Ancienne République. Sortis dans le set 9500 Intercepteur classe Fury, les Soldats Sith sont parfaits pour la construction d\'armée pour créer des forces d\'invasion Sith imposantes. Essentiels pour les collectionneurs de l\'Ancienne République recréant la Grande Guerre Galactique et les fans qui apprécient l\'identité visuelle distincte des forces militaires de l\'ancien Empire Sith.',
    es: 'El Soldado Sith sirve como infantería de élite para el Imperio Sith reconstituido durante la era de la Antigua República, vestido con distintiva armadura negra que contrasta marcadamente con las fuerzas de la República. Esta minifigura de 2012 presenta impresión detallada mostrando el diseño de armadura angular y amenazante con acentos rojos que marcan a estos soldados como fuerzas militares Sith. A diferencia de los Señores Sith individuales, estos soldados representan la masiva máquina militar del Imperio impulsada por innumerables soldados siguiendo la filosofía del lado oscuro de fuerza y dominación. El diseño de piernas lisas mantiene el enfoque en la armadura de pecho icónica que se volvió sinónimo de la estética militar Sith de la Antigua República. Lanzados en el set 9500 Interceptor clase Fury, los Soldados Sith son perfectos para construcción de ejército para crear imponentes fuerzas de invasión Sith. Esenciales para coleccionistas de la Antigua República recreando la Gran Guerra Galáctica y fans que aprecian la identidad visual distinta de las fuerzas militares del antiguo Imperio Sith.'
  },
  {
    no: 'sw0415',
    name: 'Battle Droid Commander - Tan with Dot, Angled Arm and Straight Arm',
    en: 'The OOM-series Battle Droid Commander leads Trade Federation and Separatist droid forces with yellow command markings that distinguish them from standard battle droids. This 2012 minifigure features tan coloring with a distinctive yellow dot on the head indicating command status, along with the characteristic skeletal droid design. The angled and straight arm configuration allows for various poses mimicking the droids\' stiff movements. These commanders coordinate droid armies during the Clone Wars and earlier conflicts, relaying orders from Separatist leadership to the mindless infantry units. Despite limited intelligence compared to organic officers, their networked programming allows rapid tactical adjustments across entire battalions. Released in various prequel-era sets, Battle Droid Commanders are essential for army building and recreating large-scale droid forces. Their yellow markings make them stand out among standard battle droids, perfect for collectors building authentic Trade Federation and Separatist military displays.',
    de: 'Der OOM-Serien-Kampfdroiden-Kommandant führt Handelsföderation- und Separatisten-Droidenkräfte mit gelben Kommando-Markierungen, die sie von Standard-Kampfdroiden unterscheiden. Diese 2012er-Minifigur zeigt sandfarbene Färbung mit einem charakteristischen gelben Punkt auf dem Kopf, der den Kommandostatus anzeigt, zusammen mit dem charakteristischen skelettartigen Droiden-Design. Die gewinkelte und gerade Arm-Konfiguration ermöglicht verschiedene Posen, die die steifen Bewegungen der Droiden nachahmen. Diese Kommandanten koordinieren Droiden-Armeen während der Klonkriege und früherer Konflikte und übermitteln Befehle von der Separatisten-Führung an die geistlosen Infanterie-Einheiten. Trotz begrenzter Intelligenz im Vergleich zu organischen Offizieren ermöglicht ihre vernetzte Programmierung schnelle taktische Anpassungen über ganze Bataillone hinweg. Veröffentlicht in verschiedenen Prequel-Ära-Sets, sind Kampfdroiden-Kommandanten unverzichtbar für Armeeaufbau und die Nachstellung großangelegter Droidenkräfte. Ihre gelben Markierungen lassen sie unter Standard-Kampfdroiden hervorstechen, perfekt für Sammler, die authentische Handelsföderation- und Separatisten-Militärdarstellungen aufbauen.',
    fr: 'Le Commandant de Droïde de Combat série OOM dirige les forces de droïdes de la Fédération du Commerce et Séparatistes avec des marquages de commandement jaunes qui les distinguent des droïdes de combat standard. Cette minifigurine de 2012 présente une coloration beige avec un point jaune distinctif sur la tête indiquant le statut de commandement, ainsi que le design de droïde squelettique caractéristique. La configuration de bras angulaire et droit permet diverses poses imitant les mouvements raides des droïdes. Ces commandants coordonnent les armées de droïdes pendant les Guerres des Clones et les conflits antérieurs, relayant les ordres du leadership Séparatiste aux unités d\'infanterie sans esprit. Malgré une intelligence limitée par rapport aux officiers organiques, leur programmation en réseau permet des ajustements tactiques rapides à travers des bataillons entiers. Sortis dans divers sets de l\'ère préquelle, les Commandants de Droïdes de Combat sont essentiels pour la construction d\'armée et la recréation de forces de droïdes à grande échelle. Leurs marquages jaunes les font ressortir parmi les droïdes de combat standard, parfaits pour les collectionneurs construisant des affichages militaires authentiques de la Fédération du Commerce et Séparatistes.',
    es: 'El Comandante de Droide de Batalla serie OOM lidera las fuerzas de droides de la Federación de Comercio y Separatistas con marcas de comando amarillas que los distinguen de los droides de batalla estándar. Esta minifigura de 2012 presenta coloración beige con un distintivo punto amarillo en la cabeza indicando estatus de comando, junto con el característico diseño de droide esquelético. La configuración de brazo angular y recto permite varias poses imitando los movimientos rígidos de los droides. Estos comandantes coordinan ejércitos de droides durante las Guerras Clon y conflictos anteriores, transmitiendo órdenes del liderazgo Separatista a las unidades de infantería sin mente. A pesar de inteligencia limitada comparada con oficiales orgánicos, su programación en red permite ajustes tácticos rápidos a través de batallones enteros. Lanzados en varios sets de la era de precuelas, los Comandantes de Droides de Batalla son esenciales para construcción de ejército y recrear fuerzas de droides a gran escala. Sus marcas amarillas los hacen destacar entre droides de batalla estándar, perfectos para coleccionistas construyendo exhibiciones militares auténticas de la Federación de Comercio y Separatistas.'
  },
  {
    no: 'sw0416',
    name: 'Pre Vizsla',
    en: 'Pre Vizsla, leader of the Mandalorian Death Watch faction and wielder of the ancient Darksaber, appears in this 2012 minifigure from The Clone Wars animated series. This figure captures Vizsla\'s distinctive Mandalorian armor in Death Watch colors - black and blue - with detailed printing showing the faction\'s insignia and combat gear. His blue helmet with traditional T-shaped visor marks him as a Mandalorian warrior committed to the ancient warrior traditions rejected by Duchess Satine\'s pacifist government. Pre Vizsla\'s possession of the Darksaber, a unique black-bladed lightsaber created by the first Mandalorian Jedi, makes him one of the most significant Mandalorian characters. Released in set 9525 Pre Vizsla\'s Mandalorian Fighter, this figure is essential for Clone Wars collectors and fans of Mandalorian lore. His rivalry with Darth Maul and role in Mandalore\'s civil war make him a pivotal character, highly valued by collectors of Mandalorian warriors.',
    de: 'Pre Vizsla, Anführer der mandalorianischen Death Watch-Fraktion und Träger des antiken Dunkelschwerts, erscheint in dieser 2012er-Minifigur aus der animierten Serie The Clone Wars. Diese Figur erfasst Vizsla\'s charakteristische mandalorianische Rüstung in Death Watch-Farben - schwarz und blau - mit detailliertem Druck, der das Emblem der Fraktion und Kampfausrüstung zeigt. Sein blauer Helm mit traditionellem T-förmigem Visier kennzeichnet ihn als mandalorianischen Krieger, der sich den alten Kriegertraditionen verpflichtet hat, die von Herzogin Satine\'s pazifistischer Regierung abgelehnt wurden. Pre Vizsla\'s Besitz des Dunkelschwerts, eines einzigartigen schwarz-klingigen Lichtschwertes, das vom ersten mandalorianischen Jedi geschaffen wurde, macht ihn zu einem der bedeutendsten mandalorianischen Charaktere. Veröffentlicht im Set 9525 Pre Vizsla\'s Mandalorian Fighter, ist diese Figur unverzichtbar für Clone Wars-Sammler und Fans der mandalorianischen Überlieferung. Seine Rivalität mit Darth Maul und seine Rolle in Mandalores Bürgerkrieg machen ihn zu einer zentralen Figur, hoch geschätzt von Sammlern mandalorianischer Krieger.',
    fr: 'Pre Vizsla, chef de la faction mandalorienne Death Watch et porteur du Sabre Noir antique, apparaît dans cette minifigurine de 2012 de la série animée The Clone Wars. Cette figurine capture l\'armure mandalorienne distinctive de Vizsla aux couleurs Death Watch - noir et bleu - avec une impression détaillée montrant l\'insigne de la faction et l\'équipement de combat. Son casque bleu avec visière en T traditionnelle le marque comme un guerrier mandalorien engagé dans les traditions guerrières anciennes rejetées par le gouvernement pacifiste de la Duchesse Satine. La possession par Pre Vizsla du Sabre Noir, un sabre laser à lame noire unique créé par le premier Jedi mandalorien, fait de lui l\'un des personnages mandaloriens les plus importants. Sortie dans le set 9525 Chasseur Mandalorien de Pre Vizsla, cette figurine est essentielle pour les collectionneurs de Clone Wars et les fans de la tradition mandalorienne. Sa rivalité avec Dark Maul et son rôle dans la guerre civile de Mandalore en font un personnage central, très apprécié des collectionneurs de guerriers mandaloriens.',
    es: 'Pre Vizsla, líder de la facción mandaloriana Death Watch y portador del antiguo Sable Oscuro, aparece en esta minifigura de 2012 de la serie animada The Clone Wars. Esta figura captura la distintiva armadura mandaloriana de Vizsla en colores Death Watch - negro y azul - con impresión detallada mostrando la insignia de la facción y equipo de combate. Su casco azul con visera en forma de T tradicional lo marca como un guerrero mandaloriano comprometido con las antiguas tradiciones guerreras rechazadas por el gobierno pacifista de la Duquesa Satine. La posesión de Pre Vizsla del Sable Oscuro, un sable de luz de hoja negra único creado por el primer Jedi mandaloriano, lo convierte en uno de los personajes mandalorianos más significativos. Lanzada en el set 9525 Caza Mandaloriano de Pre Vizsla, esta figura es esencial para coleccionistas de Clone Wars y fans de la tradición mandaloriana. Su rivalidad con Darth Maul y papel en la guerra civil de Mandalore lo convierten en un personaje fundamental, muy valorado por coleccionistas de guerreros mandalorianos.'
  }
];

async function saveBatch() {
  console.log(`Processing ${batch.length} minifigs...\n`);

  for (const minifig of batch) {
    try {
      await prisma.minifigCatalog.update({
        where: { minifigure_no: minifig.no },
        data: {
          description_en: minifig.en,
          description_de: minifig.de,
          description_fr: minifig.fr,
          description_es: minifig.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        }
      });
      console.log(`✅ Saved ${minifig.no}: ${minifig.name}`);
    } catch (error: any) {
      console.error(`❌ Error saving ${minifig.no}: ${error.message}`);
    }
  }

  console.log(`\n✨ Batch complete!\n`);
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
