import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0403',
    name: 'Han Solo - White Shirt with Wrinkles on Front, Reddish Brown Legs, Dual Sided Head',
    en: 'Han Solo, the charismatic smuggler turned Rebel hero, appears in this 2012 minifigure wearing his iconic white shirt with wrinkles and reddish brown legs, representing his classic look from A New Hope and The Empire Strikes Back. The detailed torso printing captures Han\'s rumpled pirate-style shirt with black vest details, while the dual-sided head offers both his confident smirk and concerned expression. This costume represents Han during his early adventures with Luke and Leia, before being frozen in carbonite by Jabba. The white shirt variant is one of Han\'s most recognizable outfits from the original trilogy. Released in set 9516 Jabba\'s Palace, this figure is essential for recreating Han\'s capture and rescue storyline. As one of Star Wars\' most beloved characters, any Han Solo minifigure is a must-have, and this classic costume version is perfect for fans of the original trilogy and collectors of main saga heroes.',
    de: 'Han Solo, der charismatische Schmuggler, der zum Rebellenhelden wurde, erscheint in dieser 2012er-Minifigur in seinem ikonischen weißen Hemd mit Falten und rotbraunen Beinen und repräsentiert seinen klassischen Look aus Eine neue Hoffnung und Das Imperium schlägt zurück. Der detaillierte Torso-Druck erfasst Han\'s zerknittertes Piraten-Hemd mit schwarzen Westen-Details, während der doppelseitige Kopf sowohl sein selbstbewusstes Grinsen als auch seinen besorgten Ausdruck bietet. Dieses Kostüm repräsentiert Han während seiner frühen Abenteuer mit Luke und Leia, bevor er von Jabba in Karbonit eingefroren wurde. Die weiße Hemd-Variante ist eines von Han\'s bekanntesten Outfits aus der ursprünglichen Trilogie. Veröffentlicht im Set 9516 Jabba\'s Palast, ist diese Figur unverzichtbar für die Nachstellung von Han\'s Gefangennahme und Rettung. Als eine von Star Wars\' beliebtesten Figuren ist jede Han Solo-Minifigur ein Muss, und diese klassische Kostümversion ist perfekt für Fans der Original-Trilogie und Sammler von Hauptsaga-Helden.',
    fr: 'Han Solo, le contrebandier charismatique devenu héros Rebelle, apparaît dans cette minifigurine de 2012 portant sa chemise blanche iconique avec des plis et des jambes brun rougeâtre, représentant son look classique d\'Un Nouvel Espoir et L\'Empire Contre-Attaque. L\'impression de torse détaillée capture la chemise de style pirate froissée de Han avec des détails de gilet noir, tandis que la tête à double face offre à la fois son sourire confiant et son expression préoccupée. Ce costume représente Han pendant ses premières aventures avec Luke et Leia, avant d\'être congelé dans la carbonite par Jabba. La variante de chemise blanche est l\'une des tenues les plus reconnaissables de Han de la trilogie originale. Sortie dans le set 9516 Palais de Jabba, cette figurine est essentielle pour recréer la capture et le sauvetage de Han. En tant que l\'un des personnages les plus aimés de Star Wars, toute minifigurine Han Solo est un incontournable, et cette version de costume classique est parfaite pour les fans de la trilogie originale et les collectionneurs de héros de la saga principale.',
    es: 'Han Solo, el carismático contrabandista convertido en héroe Rebelde, aparece en esta minifigura de 2012 vistiendo su icónica camisa blanca con arrugas y piernas marrón rojizo, representando su look clásico de Una Nueva Esperanza y El Imperio Contraataca. La impresión de torso detallada captura la camisa arrugada de estilo pirata de Han con detalles de chaleco negro, mientras que la cabeza de doble cara ofrece tanto su sonrisa confiada como su expresión preocupada. Este vestuario representa a Han durante sus primeras aventuras con Luke y Leia, antes de ser congelado en carbonita por Jabba. La variante de camisa blanca es uno de los atuendos más reconocibles de Han de la trilogía original. Lanzada en el set 9516 Palacio de Jabba, esta figura es esencial para recrear la captura y rescate de Han. Como uno de los personajes más queridos de Star Wars, cualquier minifigura de Han Solo es imprescindible, y esta versión de vestuario clásico es perfecta para fans de la trilogía original y coleccionistas de héroes de la saga principal.'
  },
  {
    no: 'sw0404',
    name: 'Bib Fortuna - Dark Blue Robe, Light Nougat Skin',
    en: 'Bib Fortuna, Jabba the Hutt\'s sinister Twi\'lek majordomo and right-hand man, appears in this 2012 minifigure with his distinctive pale skin and head-tails (lekku). This version features a dark blue robe with detailed printing showing ornate palace attire befitting his role as Jabba\'s chief advisor and gatekeeper. The light nougat colored head piece captures his pale complexion and menacing expression, with the characteristic Twi\'lek head-tails extending from his skull. Bib Fortuna\'s manipulative nature and position of power in Jabba\'s organization make him a memorable villain despite limited screen time in Return of the Jedi. Released in set 9516 Jabba\'s Palace, this figure is essential for the palace diorama and represents one of the crime lord\'s most trusted lieutenants. Highly valued by collectors of Jabba\'s court characters and fans of the Tatooine underworld storyline from the Original Trilogy.',
    de: 'Bib Fortuna, Jabba dem Hutten\'s finsterer Twi\'lek-Majordomus und rechte Hand, erscheint in dieser 2012er-Minifigur mit seiner charakteristischen blassen Haut und Kopftentakeln (Lekku). Diese Version zeigt eine dunkelblaue Robe mit detailliertem Druck, der verzierte Palastkleidung zeigt, die seiner Rolle als Jabba\'s Chefberater und Pförtner entspricht. Das hellbeige Kopfteil erfasst seinen blassen Teint und bedrohlichen Ausdruck, mit den charakteristischen Twi\'lek-Kopftentakeln, die sich von seinem Schädel erstrecken. Bib Fortuna\'s manipulative Natur und Machtposition in Jabba\'s Organisation machen ihn zu einem einprägsamen Schurken trotz begrenzter Leinwandzeit in Die Rückkehr der Jedi-Ritter. Veröffentlicht im Set 9516 Jabba\'s Palast, ist diese Figur unverzichtbar für das Palast-Diorama und repräsentiert einen von dem Verbrecherlord\'s vertrauenswürdigsten Leutnants. Hoch geschätzt von Sammlern von Jabba\'s Hof-Charakteren und Fans der Tatooine-Unterwelt-Handlung aus der Original-Trilogie.',
    fr: 'Bib Fortuna, le sinistre majordome Twi\'lek et bras droit de Jabba le Hutt, apparaît dans cette minifigurine de 2012 avec sa peau pâle distinctive et ses queues de tête (lekku). Cette version présente une robe bleue foncée avec une impression détaillée montrant une tenue de palais ornée correspondant à son rôle de conseiller en chef et gardien de Jabba. La pièce de tête couleur noisette claire capture son teint pâle et son expression menaçante, avec les queues de tête Twi\'lek caractéristiques s\'étendant de son crâne. La nature manipulatrice de Bib Fortuna et sa position de pouvoir dans l\'organisation de Jabba en font un méchant mémorable malgré un temps d\'écran limité dans Le Retour du Jedi. Sortie dans le set 9516 Palais de Jabba, cette figurine est essentielle pour le diorama du palais et représente l\'un des lieutenants les plus fiables du seigneur du crime. Très appréciée des collectionneurs de personnages de la cour de Jabba et des fans de l\'intrigue de la pègre de Tatooine de la Trilogie Originale.',
    es: 'Bib Fortuna, el siniestro mayordomo Twi\'lek y mano derecha de Jabba el Hutt, aparece en esta minifigura de 2012 con su distintiva piel pálida y colas de cabeza (lekku). Esta versión presenta una túnica azul oscuro con impresión detallada mostrando atuendo de palacio ornamentado apropiado para su papel como consejero principal y guardián de Jabba. La pieza de cabeza color crema claro captura su tez pálida y expresión amenazante, con las características colas de cabeza Twi\'lek extendiéndose desde su cráneo. La naturaleza manipuladora de Bib Fortuna y su posición de poder en la organización de Jabba lo convierten en un villano memorable a pesar del tiempo limitado en pantalla en El Retorno del Jedi. Lanzada en el set 9516 Palacio de Jabba, esta figura es esencial para el diorama del palacio y representa a uno de los lugartenientes más confiables del señor del crimen. Muy valorada por coleccionistas de personajes de la corte de Jabba y fans de la trama del submundo de Tatooine de la Trilogía Original.'
  },
  {
    no: 'sw0405',
    name: 'Gamorrean Guard - Olive Green, Dark Tan Hips',
    en: 'The Gamorrean Guard, one of Jabba the Hutt\'s brutish porcine enforcers, appears in this 2012 minifigure with olive green skin and dark tan hips. These pig-like aliens serve as muscle for Jabba\'s criminal organization, wielding vibro-axes and clubs to intimidate visitors and enemies at the palace entrance. The figure features detailed printing showing the Gamorrean\'s primitive armor plates, tusks protruding from the snout, and fierce warrior expression. Their limited intelligence but fierce loyalty make them perfect guards for the crime lord\'s throne room. Released in set 9516 Jabba\'s Palace, Gamorrean Guards are essential for palace scenes and army building to create an imposing security force. The distinctive alien design and memorable appearance from Return of the Jedi make them popular with collectors of Jabba\'s court and fans who appreciate the diverse creature designs from the original trilogy.',
    de: 'Der Gamorreaner-Wächter, einer von Jabba dem Hutten\'s brutalen schweineartigen Vollstreckern, erscheint in dieser 2012er-Minifigur mit olivgrüner Haut und dunkelbraunen Hüften. Diese schweineähnlichen Außerirdischen dienen als Muskelkraft für Jabba\'s kriminelle Organisation und schwingen Vibro-Äxte und Keulen, um Besucher und Feinde am Palasteingang einzuschüchtern. Die Figur zeigt detaillierten Druck, der die primitiven Rüstungsplatten des Gamorreaners, aus der Schnauze ragende Stoßzähne und einen wilden Kriegerausdruck zeigt. Ihre begrenzte Intelligenz, aber wilde Loyalität machen sie zu perfekten Wächtern für den Thronsaal des Verbrecherlords. Veröffentlicht im Set 9516 Jabba\'s Palast, sind Gamorreaner-Wächter unverzichtbar für Palastszenen und Armeeaufbau, um eine imposante Sicherheitstruppe zu schaffen. Das charakteristische außerirdische Design und einprägsame Erscheinungsbild aus Die Rückkehr der Jedi-Ritter machen sie bei Sammlern von Jabba\'s Hof und Fans, die die vielfältigen Kreaturdesigns aus der Original-Trilogie schätzen, beliebt.',
    fr: 'Le Garde Gamorréen, l\'un des exécuteurs porcins brutaux de Jabba le Hutt, apparaît dans cette minifigurine de 2012 avec une peau vert olive et des hanches beiges foncées. Ces extraterrestres ressemblant à des cochons servent de muscles pour l\'organisation criminelle de Jabba, maniant des haches vibro et des massues pour intimider les visiteurs et les ennemis à l\'entrée du palais. La figurine présente une impression détaillée montrant les plaques d\'armure primitives du Gamorréen, des défenses dépassant du museau et une expression de guerrier féroce. Leur intelligence limitée mais leur loyauté féroce en font des gardes parfaits pour la salle du trône du seigneur du crime. Sortis dans le set 9516 Palais de Jabba, les Gardes Gamorréens sont essentiels pour les scènes de palais et la construction d\'armée pour créer une force de sécurité imposante. Le design extraterrestre distinctif et l\'apparence mémorable du Retour du Jedi les rendent populaires auprès des collectionneurs de la cour de Jabba et des fans qui apprécient les diverses créations de créatures de la trilogie originale.',
    es: 'El Guardia Gamorreano, uno de los brutales ejecutores porcinos de Jabba el Hutt, aparece en esta minifigura de 2012 con piel verde oliva y caderas beige oscuro. Estos alienígenas parecidos a cerdos sirven como músculo para la organización criminal de Jabba, blandiendo hachas vibro y mazas para intimidar a visitantes y enemigos en la entrada del palacio. La figura presenta impresión detallada mostrando las placas de armadura primitivas del Gamorreano, colmillos sobresaliendo del hocico y expresión de guerrero feroz. Su inteligencia limitada pero lealtad feroz los convierte en guardias perfectos para la sala del trono del señor del crimen. Lanzados en el set 9516 Palacio de Jabba, los Guardias Gamorreanos son esenciales para escenas del palacio y construcción de ejército para crear una fuerza de seguridad imponente. El distintivo diseño alienígena y apariencia memorable de El Retorno del Jedi los hacen populares entre coleccionistas de la corte de Jabba y fans que aprecian los diversos diseños de criaturas de la trilogía original.'
  },
  {
    no: 'sw0406',
    name: 'Oola',
    en: 'Oola, the tragic Twi\'lek dancer enslaved by Jabba the Hutt, appears in this 2012 minifigure representing one of the palace\'s most sympathetic characters from Return of the Jedi. This figure captures Oola\'s green skin and distinctive Twi\'lek head-tails (lekku) along with detailed printing showing her dancer\'s costume with metallic bikini top and flowing skirt. Her fate as entertainment for Jabba before being fed to the Rancor monster showcases the crime lord\'s cruelty. The figure\'s detailed facial printing conveys both her beauty and the fear of her captivity. Released in set 9516 Jabba\'s Palace, Oola is essential for recreating the throne room scenes and represents the grim reality of life under Jabba\'s rule. Highly collectible as one of the few named female characters from the palace sequence, valuable to fans of Jabba\'s court and collectors seeking to complete the iconic throne room diorama.',
    de: 'Oola, die tragische Twi\'lek-Tänzerin, die von Jabba dem Hutten versklavt wurde, erscheint in dieser 2012er-Minifigur und repräsentiert eine der sympathischsten Figuren des Palastes aus Die Rückkehr der Jedi-Ritter. Diese Figur erfasst Oola\'s grüne Haut und charakteristische Twi\'lek-Kopftentakel (Lekku) zusammen mit detailliertem Druck, der ihr Tänzerinnenkostüm mit metallischem Bikini-Oberteil und fließendem Rock zeigt. Ihr Schicksal als Unterhaltung für Jabba, bevor sie dem Rancor-Monster zum Fraß vorgeworfen wird, zeigt die Grausamkeit des Verbrecherlords. Der detaillierte Gesichtsdruck der Figur vermittelt sowohl ihre Schönheit als auch die Angst ihrer Gefangenschaft. Veröffentlicht im Set 9516 Jabba\'s Palast, ist Oola unverzichtbar für die Nachstellung der Thronsaalszenen und repräsentiert die düstere Realität des Lebens unter Jabba\'s Herrschaft. Sehr sammelbar als eine der wenigen benannten weiblichen Charaktere aus der Palast-Sequenz, wertvoll für Fans von Jabba\'s Hof und Sammler, die das ikonische Thronsaal-Diorama vervollständigen möchten.',
    fr: 'Oola, la tragique danseuse Twi\'lek asservie par Jabba le Hutt, apparaît dans cette minifigurine de 2012 représentant l\'un des personnages les plus sympathiques du palais du Retour du Jedi. Cette figurine capture la peau verte d\'Oola et les queues de tête Twi\'lek distinctives (lekku) ainsi qu\'une impression détaillée montrant son costume de danseuse avec haut de bikini métallique et jupe fluide. Son destin comme divertissement pour Jabba avant d\'être jetée au monstre Rancor montre la cruauté du seigneur du crime. L\'impression faciale détaillée de la figurine transmet à la fois sa beauté et la peur de sa captivité. Sortie dans le set 9516 Palais de Jabba, Oola est essentielle pour recréer les scènes de la salle du trône et représente la sombre réalité de la vie sous le règne de Jabba. Hautement collectionnable en tant que l\'un des rares personnages féminins nommés de la séquence du palais, précieuse pour les fans de la cour de Jabba et les collectionneurs cherchant à compléter le diorama iconique de la salle du trône.',
    es: 'Oola, la trágica bailarina Twi\'lek esclavizada por Jabba el Hutt, aparece en esta minifigura de 2012 representando a uno de los personajes más simpáticos del palacio de El Retorno del Jedi. Esta figura captura la piel verde de Oola y las distintivas colas de cabeza Twi\'lek (lekku) junto con impresión detallada mostrando su traje de bailarina con top de bikini metálico y falda fluida. Su destino como entretenimiento para Jabba antes de ser arrojada al monstruo Rancor muestra la crueldad del señor del crimen. La impresión facial detallada de la figura transmite tanto su belleza como el miedo de su cautiverio. Lanzada en el set 9516 Palacio de Jabba, Oola es esencial para recrear las escenas de la sala del trono y representa la sombría realidad de la vida bajo el gobierno de Jabba. Altamente coleccionable como uno de los pocos personajes femeninos nombrados de la secuencia del palacio, valiosa para fans de la corte de Jabba y coleccionistas que buscan completar el icónico diorama de la sala del trono.'
  },
  {
    no: 'sw0407',
    name: 'Boushh',
    en: 'Boushh, the Ubese bounty hunter disguise worn by Princess Leia to infiltrate Jabba\'s Palace and rescue Han Solo, appears in this 2012 minifigure. This figure captures the distinctive armored costume with detailed printing showing the layered protective gear, bandoliers, and equipment pouches of a professional bounty hunter. The characteristic wrapped helmet with breathing apparatus completely conceals the wearer\'s identity, making it the perfect disguise for Leia\'s daring rescue mission. Released in set 9516 Jabba\'s Palace, this figure represents one of the most iconic scenes from Return of the Jedi where Leia demonstrates her courage and resourcefulness. The Boushh disguise showcases Leia\'s versatility as a character beyond the metal bikini outfit. Essential for collectors recreating the Han Solo rescue sequence and fans of Princess Leia\'s heroic moments, this figure captures one of the Original Trilogy\'s most memorable infiltration scenes.',
    de: 'Boushh, die Ubese-Kopfgeldjäger-Verkleidung, die von Prinzessin Leia getragen wird, um Jabba\'s Palast zu infiltrieren und Han Solo zu retten, erscheint in dieser 2012er-Minifigur. Diese Figur erfasst das charakteristische gepanzerte Kostüm mit detailliertem Druck, der die geschichtete Schutzausrüstung, Patronengurte und Ausrüstungstaschen eines professionellen Kopfgeldjägers zeigt. Der charakteristische umwickelte Helm mit Atemgerät verbirgt die Identität des Trägers vollständig und macht ihn zur perfekten Verkleidung für Leia\'s gewagte Rettungsmission. Veröffentlicht im Set 9516 Jabba\'s Palast, repräsentiert diese Figur eine der ikonischsten Szenen aus Die Rückkehr der Jedi-Ritter, in der Leia ihren Mut und ihre Findigkeit demonstriert. Die Boushh-Verkleidung zeigt Leia\'s Vielseitigkeit als Charakter jenseits des Metall-Bikini-Outfits. Unverzichtbar für Sammler, die die Han Solo-Rettungssequenz nachstellen, und Fans von Prinzessin Leia\'s heroischen Momenten, erfasst diese Figur eine der einprägsamsten Infiltrationsszenen der Original-Trilogie.',
    fr: 'Boushh, le déguisement de chasseur de primes Ubese porté par la Princesse Leia pour infiltrer le Palais de Jabba et sauver Han Solo, apparaît dans cette minifigurine de 2012. Cette figurine capture le costume blindé distinctif avec une impression détaillée montrant l\'équipement de protection en couches, les cartouchières et les poches d\'équipement d\'un chasseur de primes professionnel. Le casque enveloppé caractéristique avec appareil respiratoire dissimule complètement l\'identité du porteur, en faisant le déguisement parfait pour la mission de sauvetage audacieuse de Leia. Sortie dans le set 9516 Palais de Jabba, cette figurine représente l\'une des scènes les plus iconiques du Retour du Jedi où Leia démontre son courage et son ingéniosité. Le déguisement de Boushh montre la polyvalence de Leia en tant que personnage au-delà de la tenue de bikini métallique. Essentielle pour les collectionneurs recréant la séquence de sauvetage de Han Solo et les fans des moments héroïques de la Princesse Leia, cette figurine capture l\'une des scènes d\'infiltration les plus mémorables de la Trilogie Originale.',
    es: 'Boushh, el disfraz de cazarrecompensas Ubese usado por la Princesa Leia para infiltrarse en el Palacio de Jabba y rescatar a Han Solo, aparece en esta minifigura de 2012. Esta figura captura el distintivo traje blindado con impresión detallada mostrando el equipo protector en capas, cartucheras y bolsas de equipo de un cazarrecompensas profesional. El característico casco envuelto con aparato respiratorio oculta completamente la identidad del portador, convirtiéndolo en el disfraz perfecto para la atrevida misión de rescate de Leia. Lanzada en el set 9516 Palacio de Jabba, esta figura representa una de las escenas más icónicas de El Retorno del Jedi donde Leia demuestra su valentía e ingenio. El disfraz de Boushh muestra la versatilidad de Leia como personaje más allá del atuendo de bikini metálico. Esencial para coleccionistas recreando la secuencia de rescate de Han Solo y fans de los momentos heroicos de la Princesa Leia, esta figura captura una de las escenas de infiltración más memorables de la Trilogía Original.'
  },
  {
    no: 'sw0408',
    name: 'Salacious B. Crumb - Bright Light Orange Eyes with Black Pupils (6008131 / 6034978)',
    en: 'Salacious B. Crumb, Jabba the Hutt\'s cackling Kowakian monkey-lizard court jester, appears in this 2012 small creature figure with bright light orange eyes and black pupils. This diminutive pest serves as comic relief and mockery amplifier in Jabba\'s throne room, perching on the Hutt\'s dais and laughing at the misfortune of prisoners and visitors. The detailed molding captures Crumb\'s reptilian features, pointed ears, and mischievous expression, while his small 0.92-gram size accurately represents the creature\'s tiny stature. His irritating laugh and sycophantic behavior toward Jabba make him one of the most memorable minor characters from Return of the Jedi. Released in set 9516 Jabba\'s Palace, Salacious Crumb is essential for completing the throne room scene and adds authentic detail to Jabba\'s court. Highly valued by collectors for his unique creature design and iconic comedic presence in the palace.',
    de: 'Salacious B. Crumb, Jabba dem Hutten\'s kichernder Kowakianischer Affen-Echsen-Hofnarr, erscheint in dieser 2012er-kleinen Kreaturfigur mit hellorangen Augen und schwarzen Pupillen. Dieser winzige Plagegeist dient als komische Erleichterung und Spott-Verstärker in Jabba\'s Thronsaal, hockt auf dem Podest des Hutten und lacht über das Unglück von Gefangenen und Besuchern. Die detaillierte Formgebung erfasst Crumb\'s reptilienartige Merkmale, spitze Ohren und schelmischen Ausdruck, während seine kleine 0,92-Gramm-Größe die winzige Statur der Kreatur genau darstellt. Sein irritierendes Lachen und kriecherisches Verhalten gegenüber Jabba machen ihn zu einer der einprägsamsten Nebenfiguren aus Die Rückkehr der Jedi-Ritter. Veröffentlicht im Set 9516 Jabba\'s Palast, ist Salacious Crumb unverzichtbar für die Vervollständigung der Thronsaalszene und fügt Jabba\'s Hof authentische Details hinzu. Hoch geschätzt von Sammlern für sein einzigartiges Kreaturdesign und ikonische komische Präsenz im Palast.',
    fr: 'Salacious B. Crumb, le bouffon de cour singe-lézard Kowakien ricanant de Jabba le Hutt, apparaît dans cette petite figurine de créature de 2012 avec des yeux orange clair brillants et des pupilles noires. Ce minuscule parasite sert de soulagement comique et d\'amplificateur de moquerie dans la salle du trône de Jabba, perché sur l\'estrade du Hutt et riant du malheur des prisonniers et des visiteurs. Le moulage détaillé capture les traits reptiliens de Crumb, les oreilles pointues et l\'expression espiègle, tandis que sa petite taille de 0,92 gramme représente avec précision la stature minuscule de la créature. Son rire irritant et son comportement obséquieux envers Jabba en font l\'un des personnages mineurs les plus mémorables du Retour du Jedi. Sorti dans le set 9516 Palais de Jabba, Salacious Crumb est essentiel pour compléter la scène de la salle du trône et ajoute des détails authentiques à la cour de Jabba. Très apprécié des collectionneurs pour son design de créature unique et sa présence comique iconique dans le palais.',
    es: 'Salacious B. Crumb, el bufón de corte mono-lagarto Kowakiano cacareante de Jabba el Hutt, aparece en esta pequeña figura de criatura de 2012 con ojos naranja claro brillante y pupilas negras. Esta diminuta plaga sirve como alivio cómico y amplificador de burla en la sala del trono de Jabba, posado en la tarima del Hutt y riéndose de la desgracia de prisioneros y visitantes. El moldeado detallado captura los rasgos reptilianos de Crumb, orejas puntiagudas y expresión traviesa, mientras que su pequeño tamaño de 0.92 gramos representa con precisión la estatura diminuta de la criatura. Su risa irritante y comportamiento servil hacia Jabba lo convierten en uno de los personajes menores más memorables de El Retorno del Jedi. Lanzado en el set 9516 Palacio de Jabba, Salacious Crumb es esencial para completar la escena de la sala del trono y añade detalle auténtico a la corte de Jabba. Muy valorado por coleccionistas por su diseño de criatura único y presencia cómica icónica en el palacio.'
  }
];

async function saveBatch() {
  console.log(`Processing ${batch.length} minifigs...\n`);

  for (const minifig of batch) {
    try {
      await prisma.minifigCatalog.update({
        where: { minifigure_no: minifig.no },
        data: {
          description_en: minifig.en,
          description_de: minifig.de,
          description_fr: minifig.fr,
          description_es: minifig.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        }
      });
      console.log(`✅ Saved ${minifig.no}: ${minifig.name}`);
    } catch (error: any) {
      console.error(`❌ Error saving ${minifig.no}: ${error.message}`);
    }
  }

  console.log(`\n✨ Batch complete!\n`);
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
