import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    minifigure_no: 'sw0833',
    name: 'Aayla Secura - Dark Pink Lips',
    description_en: 'Aayla Secura, the Twi\'lek Jedi Master known for her distinctive blue skin and combat prowess, appears in this minifigure variant with dark pink lip printing. A skilled warrior who fought in the Clone Wars, Aayla led the 327th Star Corps alongside Commander Bly until Order 66 was executed on Felucia. Her blue skin tone, head-tails (lekku), and Jedi robes are faithfully recreated. The dark pink lips add feminine detail to distinguish her from other blue-skinned characters. This version is valued by collectors building Clone Wars-era Jedi councils and battlefield scenes from Revenge of the Sith.',
    description_de: 'Aayla Secura, die Twi\'lek-Jedi-Meisterin bekannt für ihre charakteristische blaue Haut und Kampfstärke, erscheint in dieser Minifigur-Variante mit dunkelrosa Lippendruck. Als geschickte Kriegerin, die in den Klonkriegen kämpfte, führte Aayla das 327. Sternkorps neben Commander Bly, bis Order 66 auf Felucia ausgeführt wurde. Ihr blauer Hautton, Kopfschwänze (Lekku) und Jedi-Roben sind originalgetreu nachgebildet. Die dunkelrosa Lippen fügen feminine Details hinzu, um sie von anderen blau-hautigen Charakteren zu unterscheiden. Diese Version wird von Sammlern geschätzt, die Klonkriegs-Ära-Jedi-Räte und Schlachtfeldszenen aus Die Rache der Sith aufbauen.',
    description_fr: 'Aayla Secura, la Maître Jedi Twi\'lek connue pour sa peau bleue distinctive et ses prouesses au combat, apparaît dans cette variante de figurine avec une impression de lèvres rose foncé. Guerrière compétente qui combattit dans les Guerres des Clones, Aayla dirigea le 327e Corps Stellaire aux côtés du Commandant Bly jusqu\'à ce que l\'Ordre 66 soit exécuté sur Felucia. Son ton de peau bleu, ses queues de tête (lekku) et ses robes Jedi sont fidèlement recréés. Les lèvres rose foncé ajoutent un détail féminin pour la distinguer des autres personnages à peau bleue. Cette version est appréciée par les collectionneurs construisant des conseils Jedi de l\'ère des Guerres des Clones et des scènes de bataille de La Revanche des Sith.',
    description_es: 'Aayla Secura, la Maestra Jedi Twi\'lek conocida por su distintiva piel azul y destreza en combate, aparece en esta variante de minifigura con impresión de labios rosa oscuro. Una guerrera hábil que luchó en las Guerras Clon, Aayla lideró el 327° Cuerpo Estelar junto al Comandante Bly hasta que la Orden 66 fue ejecutada en Felucia. Su tono de piel azul, colas de cabeza (lekku) y túnicas Jedi están fielmente recreados. Los labios rosa oscuro añaden detalle femenino para distinguirla de otros personajes de piel azul. Esta versión es valorada por coleccionistas construyendo consejos Jedi de la era de las Guerras Clon y escenas de batalla de La Venganza de los Sith.'
  },
  {
    minifigure_no: 'sw0834',
    name: 'Darth Vader (Light Nougat Head, Plain Arms)',
    description_en: 'This Darth Vader variant features a light nougat flesh-toned head beneath the iconic black helmet, representing the scarred Anakin Skywalker hidden within the armor. The plain black arms without printing offer a simplified design compared to more detailed variants. This version emphasizes the duality of Vader\'s character - the fallen Jedi Anakin still exists beneath the mechanical suit. The inclusion of the flesh head allows for helmet-removal displays, recreating moments like his unmasking in Return of the Jedi. This variant appeals to collectors who appreciate the human element behind the Dark Lord\'s fearsome exterior.',
    description_de: 'Diese Darth-Vader-Variante zeigt einen hellnougatfarbenen Fleischton-Kopf unter dem ikonischen schwarzen Helm und repräsentiert den vernarbten Anakin Skywalker, der in der Rüstung verborgen ist. Die schlichten schwarzen Arme ohne Druck bieten ein vereinfachtes Design im Vergleich zu detaillierteren Varianten. Diese Version betont die Dualität von Vaders Charakter - der gefallene Jedi Anakin existiert noch unter dem mechanischen Anzug. Die Einbeziehung des Fleischkopfes ermöglicht Helm-Abnahme-Displays und stellt Momente wie seine Demaskierung in Die Rückkehr der Jedi-Ritter nach. Diese Variante spricht Sammler an, die das menschliche Element hinter der furchteinflößenden Äußerlichkeit des Dunklen Lords schätzen.',
    description_fr: 'Cette variante de Dark Vador présente une tête de couleur chair nougat clair sous le casque noir iconique, représentant l\'Anakin Skywalker scarifié caché dans l\'armure. Les bras noirs unis sans impression offrent un design simplifié par rapport aux variantes plus détaillées. Cette version met l\'accent sur la dualité du personnage de Vador - le Jedi déchu Anakin existe toujours sous la combinaison mécanique. L\'inclusion de la tête de chair permet des displays de retrait de casque, recréant des moments comme son démasquage dans Le Retour du Jedi. Cette variante plaît aux collectionneurs qui apprécient l\'élément humain derrière l\'extérieur redoutable du Seigneur Noir.',
    description_es: 'Esta variante de Darth Vader presenta una cabeza de tono carne nougat claro bajo el icónico casco negro, representando al cicatrizado Anakin Skywalker oculto dentro de la armadura. Los brazos negros lisos sin impresión ofrecen un diseño simplificado comparado con variantes más detalladas. Esta versión enfatiza la dualidad del personaje de Vader - el Jedi caído Anakin aún existe bajo el traje mecánico. La inclusión de la cabeza de carne permite displays de remoción de casco, recreando momentos como su desenmascaramiento en El Retorno del Jedi. Esta variante atrae a coleccionistas que aprecian el elemento humano detrás del exterior temible del Señor Oscuro.'
  },
  {
    minifigure_no: 'sw0835',
    name: 'DD-13 Medical Assistant Droid',
    description_en: 'The DD-13 medical assistant droid served in the Polis Massa medical facility where Padmé Amidala gave birth to Luke and Leia before dying. These specialized medical droids provided surgical assistance and patient monitoring with their advanced sensor arrays. This minifigure captures the distinctive cylindrical design with medical equipment attachments. DD-13 units were present during one of the saga\'s most pivotal moments - the birth of the twins who would defeat the Empire and the death of Padmé that completed Anakin\'s transformation to Vader. Essential for recreating the tragic medical bay scene from Revenge of the Sith.',
    description_de: 'Der DD-13-Medizinassistent-Droide diente in der medizinischen Einrichtung von Polis Massa, wo Padmé Amidala Luke und Leia zur Welt brachte, bevor sie starb. Diese spezialisierten Medizindroiden leisteten chirurgische Assistenz und Patientenüberwachung mit ihren fortgeschrittenen Sensor-Arrays. Diese Minifigur fängt das charakteristische zylindrische Design mit medizinischen Ausrüstungsanbauteilen ein. DD-13-Einheiten waren während eines der entscheidendsten Momente der Saga anwesend - der Geburt der Zwillinge, die das Imperium besiegen würden, und dem Tod Padmés, der Anakins Verwandlung zu Vader vervollständigte. Essentiell zum Nachstellen der tragischen Krankenstation-Szene aus Die Rache der Sith.',
    description_fr: 'Le droïde assistant médical DD-13 servit dans l\'installation médicale de Polis Massa où Padmé Amidala donna naissance à Luke et Leia avant de mourir. Ces droïdes médicaux spécialisés fournissaient une assistance chirurgicale et une surveillance des patients avec leurs rangées de capteurs avancées. Cette figurine capture le design cylindrique distinctif avec des attachements d\'équipement médical. Les unités DD-13 étaient présentes pendant l\'un des moments les plus cruciaux de la saga - la naissance des jumeaux qui vaincraient l\'Empire et la mort de Padmé qui complétait la transformation d\'Anakin en Vador. Essentielle pour recréer la scène tragique de la baie médicale de La Revanche des Sith.',
    description_es: 'El droide asistente médico DD-13 sirvió en la instalación médica de Polis Massa donde Padmé Amidala dio a luz a Luke y Leia antes de morir. Estos droides médicos especializados proporcionaban asistencia quirúrgica y monitoreo de pacientes con sus avanzadas matrices de sensores. Esta minifigura captura el distintivo diseño cilíndrico con accesorios de equipo médico. Las unidades DD-13 estuvieron presentes durante uno de los momentos más fundamentales de la saga - el nacimiento de los gemelos que derrotarían al Imperio y la muerte de Padmé que completó la transformación de Anakin a Vader. Esencial para recrear la trágica escena de la bahía médica de La Venganza de los Sith.'
  },
  {
    minifigure_no: 'sw0836',
    name: 'FX-9 Surgical Assistant Droid',
    description_en: 'The FX-9 surgical assistant droid was present during the most critical medical procedure in galactic history - the reconstruction of Darth Vader on Mustafar. These specialized droids featured multiple surgical arms and precision instruments to perform complex cybernetic surgeries. This minifigure represents the droids that sealed Anakin Skywalker into his life-sustaining armor after his catastrophic injuries. FX-9 units also appeared in the Polis Massa medical facility. The distinctive multi-armed design makes this an instantly recognizable minifigure, perfect for recreating the dramatic Vader transformation scene or medical facility dioramas from Revenge of the Sith.',
    description_de: 'Der FX-9-Chirurgieassistent-Droide war während des kritischsten medizinischen Eingriffs in der galaktischen Geschichte anwesend - der Rekonstruktion von Darth Vader auf Mustafar. Diese spezialisierten Droiden verfügten über mehrere chirurgische Arme und Präzisionsinstrumente, um komplexe kybernetische Operationen durchzuführen. Diese Minifigur repräsentiert die Droiden, die Anakin Skywalker nach seinen katastrophalen Verletzungen in seine lebenserhaltende Rüstung versiegelten. FX-9-Einheiten erschienen auch in der medizinischen Einrichtung von Polis Massa. Das charakteristische mehrarmige Design macht dies zu einer sofort erkennbaren Minifigur, perfekt zum Nachstellen der dramatischen Vader-Transformationsszene oder medizinischen Einrichtungs-Dioramen aus Die Rache der Sith.',
    description_fr: 'Le droïde assistant chirurgical FX-9 était présent lors de la procédure médicale la plus critique de l\'histoire galactique - la reconstruction de Dark Vador sur Mustafar. Ces droïdes spécialisés disposaient de multiples bras chirurgicaux et d\'instruments de précision pour effectuer des chirurgies cybernétiques complexes. Cette figurine représente les droïdes qui scellèrent Anakin Skywalker dans son armure de survie après ses blessures catastrophiques. Les unités FX-9 apparurent également dans l\'installation médicale de Polis Massa. Le design distinctif multi-bras rend cette figurine instantanément reconnaissable, parfaite pour recréer la scène dramatique de transformation de Vador ou des dioramas d\'installations médicales de La Revanche des Sith.',
    description_es: 'El droide asistente quirúrgico FX-9 estuvo presente durante el procedimiento médico más crítico en la historia galáctica - la reconstrucción de Darth Vader en Mustafar. Estos droides especializados presentaban múltiples brazos quirúrgicos e instrumentos de precisión para realizar cirugías cibernéticas complejas. Esta minifigura representa a los droides que sellaron a Anakin Skywalker en su armadura de soporte vital después de sus lesiones catastróficas. Las unidades FX-9 también aparecieron en la instalación médica de Polis Massa. El distintivo diseño multi-brazo hace de esta una minifigura instantáneamente reconocible, perfecta para recrear la dramática escena de transformación de Vader o dioramas de instalaciones médicas de La Venganza de los Sith.'
  },
  {
    minifigure_no: 'sw0837',
    name: 'Clone Trooper Gunner (Phase 2) - Scowl',
    description_en: 'This Phase 2 clone trooper gunner features the distinctive scowling facial expression beneath his helmet, representing the battle-hardened veterans of the Clone Wars. Gunners operated heavy weapons including LAAT gunship turrets, AT-TE cannons, and artillery emplacements during major battles. The Phase 2 armor design improved upon earlier models with better combat efficiency and communication systems. The scowl expression adds personality and suggests the weariness of endless combat that clone troopers experienced. This variant is valuable for building diverse clone armies and represents the specialized roles that clones filled beyond standard infantry.',
    description_de: 'Dieser Phase-2-Klonkrieger-Schütze zeigt den charakteristischen mürrischen Gesichtsausdruck unter seinem Helm und repräsentiert die kampferprobten Veteranen der Klonkriege. Schützen bedienten schwere Waffen einschließlich LAAT-Kanonenboot-Geschütztürmen, AT-TE-Kanonen und Artilleriestellungen während großer Schlachten. Das Phase-2-Rüstungsdesign verbesserte frühere Modelle mit besserer Kampfeffizienz und Kommunikationssystemen. Der mürrische Ausdruck fügt Persönlichkeit hinzu und suggeriert die Erschöpfung durch endlosen Kampf, den Klonkrieger erlebten. Diese Variante ist wertvoll zum Aufbau vielfältiger Klonarmeen und repräsentiert die spezialisierten Rollen, die Klone über Standard-Infanterie hinaus ausfüllten.',
    description_fr: 'Ce clone trooper tireur Phase 2 présente l\'expression faciale renfrognée distinctive sous son casque, représentant les vétérans endurcis par les combats des Guerres des Clones. Les tireurs opéraient des armes lourdes incluant des tourelles de canonnière LAAT, des canons AT-TE et des emplacements d\'artillerie pendant les batailles majeures. Le design d\'armure Phase 2 améliora les modèles antérieurs avec une meilleure efficacité au combat et des systèmes de communication. L\'expression renfrognée ajoute de la personnalité et suggère la lassitude du combat sans fin que les clone troopers expérimentèrent. Cette variante est précieuse pour construire des armées clones diverses et représente les rôles spécialisés que les clones remplissaient au-delà de l\'infanterie standard.',
    description_es: 'Este artillero clon de Fase 2 presenta la distintiva expresión facial ceñuda bajo su casco, representando a los veteranos curtidos en batalla de las Guerras Clon. Los artilleros operaban armas pesadas incluyendo torretas de cañonera LAAT, cañones AT-TE y emplazamientos de artillería durante batallas importantes. El diseño de armadura de Fase 2 mejoró modelos anteriores con mejor eficiencia de combate y sistemas de comunicación. La expresión ceñuda añade personalidad y sugiere el cansancio del combate interminable que los soldados clon experimentaron. Esta variante es valiosa para construir ejércitos clon diversos y representa los roles especializados que los clones cumplían más allá de infantería estándar.'
  },
  {
    minifigure_no: 'sw0838',
    name: 'Prowler 1000 Exploration Droid',
    description_en: 'The Prowler 1000 exploration droid represents a specialized reconnaissance unit designed for surveying dangerous or unknown terrain. These droids featured advanced sensor packages and rugged construction to operate in hostile environments without risking organic life. The unique design with specialized attachments makes this an unusual addition to Star Wars droid collections. Exploration droids like the Prowler 1000 were deployed across the galaxy for planetary surveys, archaeological investigations, and advance scouting. This minifigure appeals to collectors interested in the diverse array of specialized droids that populated the Star Wars universe beyond the famous protocol and astromech units.',
    description_de: 'Der Prowler-1000-Erkundungsdroide repräsentiert eine spezialisierte Aufklärungseinheit, die zum Vermessen gefährlichen oder unbekannten Geländes entwickelt wurde. Diese Droiden verfügten über fortgeschrittene Sensorpakete und robuste Konstruktion, um in feindlichen Umgebungen ohne Risiko für organisches Leben zu operieren. Das einzigartige Design mit spezialisierten Anbauteilen macht dies zu einer ungewöhnlichen Ergänzung für Star-Wars-Droiden-Sammlungen. Erkundungsdroiden wie der Prowler 1000 wurden quer durch die Galaxis für planetare Vermessungen, archäologische Untersuchungen und Vorhut-Aufklärung eingesetzt. Diese Minifigur spricht Sammler an, die an der vielfältigen Auswahl spezialisierter Droiden interessiert sind, die das Star-Wars-Universum über die berühmten Protokoll- und Astromech-Einheiten hinaus bevölkerten.',
    description_fr: 'Le droïde d\'exploration Prowler 1000 représente une unité de reconnaissance spécialisée conçue pour arpenter des terrains dangereux ou inconnus. Ces droïdes disposaient de paquets de capteurs avancés et d\'une construction robuste pour opérer dans des environnements hostiles sans risquer la vie organique. Le design unique avec des attachements spécialisés en fait un ajout inhabituel aux collections de droïdes Star Wars. Les droïdes d\'exploration comme le Prowler 1000 étaient déployés à travers la galaxie pour des relevés planétaires, des investigations archéologiques et de l\'éclairage avancé. Cette figurine plaît aux collectionneurs intéressés par la diversité des droïdes spécialisés qui peuplaient l\'univers Star Wars au-delà des fameuses unités de protocole et astromech.',
    description_es: 'El droide de exploración Prowler 1000 representa una unidad de reconocimiento especializada diseñada para inspeccionar terreno peligroso o desconocido. Estos droides presentaban paquetes de sensores avanzados y construcción robusta para operar en ambientes hostiles sin arriesgar vida orgánica. El diseño único con accesorios especializados hace de esta una adición inusual a colecciones de droides de Star Wars. Droides de exploración como el Prowler 1000 fueron desplegados a través de la galaxia para estudios planetarios, investigaciones arqueológicas y exploración avanzada. Esta minifigura atrae a coleccionistas interesados en la diversa variedad de droides especializados que poblaban el universo Star Wars más allá de las famosas unidades de protocolo y astromecánicas.'
  },
  {
    minifigure_no: 'sw0839',
    name: 'Guavian Security Soldier',
    description_en: 'Guavian security soldiers served as heavily armored enforcers for the Guavian Death Gang, a criminal syndicate operating during the sequel trilogy era. This minifigure features the distinctive red and black armor with an intimidating helmet design that completely conceals the wearer\'s identity. These soldiers were cybernetically enhanced, with mechanical augmentations improving their combat capabilities. They confronted Han Solo aboard his freighter, demanding repayment for a failed smuggling job. The unique armor design and connection to Han\'s criminal past make this an essential minifigure for recreating The Force Awakens scenes and representing the dangerous underworld Han navigated.',
    description_de: 'Guavianische Sicherheitssoldaten dienten als schwer gepanzerte Vollstrecker für die Guavianische Todesgang, ein kriminelles Syndikat, das während der Sequel-Trilogie-Ära operierte. Diese Minifigur zeigt die charakteristische rot-schwarze Rüstung mit einem einschüchternden Helmdesign, das die Identität des Trägers vollständig verbirgt. Diese Soldaten waren kybernetisch verbessert, mit mechanischen Augmentierungen, die ihre Kampffähigkeiten verbesserten. Sie konfrontierten Han Solo an Bord seines Frachters und forderten Rückzahlung für einen gescheiterten Schmuggelauftrag. Das einzigartige Rüstungsdesign und die Verbindung zu Hans krimineller Vergangenheit machen dies zu einer essentiellen Minifigur zum Nachstellen von Das Erwachen der Macht-Szenen und Repräsentieren der gefährlichen Unterwelt, die Han navigierte.',
    description_fr: 'Les soldats de sécurité Guavian servaient comme exécuteurs lourdement blindés pour le Gang de la Mort Guavian, un syndicat criminel opérant pendant l\'ère de la trilogie suite. Cette figurine présente l\'armure rouge et noire distinctive avec un design de casque intimidant qui dissimule complètement l\'identité du porteur. Ces soldats étaient améliorés cybernétiquement, avec des augmentations mécaniques améliorant leurs capacités de combat. Ils confrontèrent Han Solo à bord de son cargo, exigeant le remboursement d\'un travail de contrebande raté. Le design d\'armure unique et la connexion au passé criminel de Han en font une figurine essentielle pour recréer les scènes du Réveil de la Force et représenter le monde souterrain dangereux que Han naviguait.',
    description_es: 'Los soldados de seguridad Guavianos servían como ejecutores fuertemente acorazados para la Banda de la Muerte Guaviana, un sindicato criminal operando durante la era de la trilogía secuela. Esta minifigura presenta la distintiva armadura roja y negra con un diseño de casco intimidante que oculta completamente la identidad del portador. Estos soldados estaban mejorados cibernéticamente, con aumentos mecánicos mejorando sus capacidades de combate. Confrontaron a Han Solo a bordo de su carguero, exigiendo reembolso por un trabajo de contrabando fallido. El diseño único de armadura y conexión con el pasado criminal de Han hacen de esta una minifigura esencial para recrear escenas de El Despertar de la Fuerza y representar el peligroso submundo que Han navegaba.'
  },
  {
    minifigure_no: 'sw0840',
    name: 'Bala-Tik',
    description_en: 'Bala-Tik was a high-ranking member of the Guavian Death Gang who personally confronted Han Solo demanding payment for a botched smuggling run. This minifigure captures his distinctive appearance with detailed printing showing his tactical vest and equipment. As spokesman for the gang, Bala-Tik demonstrated both intelligence and ruthlessness in his brief appearance in The Force Awakens. His encounter with Han aboard the freighter revealed how far the legendary smuggler had fallen after losing the Millennium Falcon. This named character adds narrative depth to Force Awakens collections and represents the criminal underworld catching up with Han\'s past.',
    description_de: 'Bala-Tik war ein hochrangiges Mitglied der Guavianischen Todesgang, der Han Solo persönlich konfrontierte und Zahlung für einen verpfuschten Schmuggelauftrag forderte. Diese Minifigur fängt sein charakteristisches Erscheinungsbild mit detailliertem Druck ein, der seine taktische Weste und Ausrüstung zeigt. Als Sprecher der Gang demonstrierte Bala-Tik sowohl Intelligenz als auch Rücksichtslosigkeit in seinem kurzen Auftritt in Das Erwachen der Macht. Seine Begegnung mit Han an Bord des Frachters enthüllte, wie tief der legendäre Schmuggler gefallen war, nachdem er den Millennium Falcon verloren hatte. Dieser benannte Charakter fügt Das-Erwachen-der-Macht-Sammlungen narrative Tiefe hinzu und repräsentiert die kriminelle Unterwelt, die Hans Vergangenheit einholte.',
    description_fr: 'Bala-Tik était un membre haut placé du Gang de la Mort Guavian qui confronta personnellement Han Solo exigeant le paiement pour une course de contrebande ratée. Cette figurine capture son apparence distinctive avec une impression détaillée montrant son gilet tactique et son équipement. En tant que porte-parole du gang, Bala-Tik démontra à la fois intelligence et impitoyabilité dans sa brève apparition dans Le Réveil de la Force. Sa rencontre avec Han à bord du cargo révéla à quel point le contrebandier légendaire était tombé après avoir perdu le Faucon Millenium. Ce personnage nommé ajoute de la profondeur narrative aux collections du Réveil de la Force et représente le monde souterrain criminel rattrapant le passé de Han.',
    description_es: 'Bala-Tik fue un miembro de alto rango de la Banda de la Muerte Guaviana que confrontó personalmente a Han Solo exigiendo pago por una carrera de contrabando arruinada. Esta minifigura captura su apariencia distintiva con impresión detallada mostrando su chaleco táctico y equipo. Como portavoz de la banda, Bala-Tik demostró tanto inteligencia como despiadada en su breve aparición en El Despertar de la Fuerza. Su encuentro con Han a bordo del carguero reveló cuán bajo había caído el legendario contrabandista después de perder el Halcón Milenario. Este personaje nombrado añade profundidad narrativa a colecciones de El Despertar de la Fuerza y representa el submundo criminal alcanzando el pasado de Han.'
  },
  {
    minifigure_no: 'sw0841',
    name: 'Han Solo, Old',
    description_en: 'This older Han Solo minifigure captures the legendary smuggler decades after the original trilogy, showing him weathered and world-weary in The Force Awakens. The printing includes gray-streaked hair and aged facial features, reflecting the years spent running from his past after losing Ben Solo to the dark side. Despite his age, Han retained his roguish charm and piloting skills. His return to smuggling after the collapse of his relationship with Leia made him a tragic figure - still trying to outrun his failures. This essential sequel trilogy minifigure represents Han\'s final chapter and his ultimate sacrifice to try reaching his son.',
    description_de: 'Diese ältere Han-Solo-Minifigur fängt den legendären Schmuggler Jahrzehnte nach der Originaltrilogie ein und zeigt ihn verwittert und weltmüde in Das Erwachen der Macht. Der Druck umfasst grau durchzogenes Haar und gealterte Gesichtszüge, die die Jahre widerspiegeln, die damit verbracht wurden, vor seiner Vergangenheit zu fliehen, nachdem er Ben Solo an die dunkle Seite verloren hatte. Trotz seines Alters behielt Han seinen schurkischen Charme und Pilotfähigkeiten. Seine Rückkehr zum Schmuggeln nach dem Zusammenbruch seiner Beziehung mit Leia machte ihn zu einer tragischen Figur - die immer noch versuchte, ihren Misserfolgen davonzulaufen. Diese essentielle Sequel-Trilogie-Minifigur repräsentiert Hans letztes Kapitel und sein ultimatives Opfer beim Versuch, seinen Sohn zu erreichen.',
    description_fr: 'Cette figurine de Han Solo plus âgé capture le contrebandier légendaire des décennies après la trilogie originale, le montrant éprouvé et las du monde dans Le Réveil de la Force. L\'impression inclut des cheveux striés de gris et des traits faciaux vieillis, reflétant les années passées à fuir son passé après avoir perdu Ben Solo du côté obscur. Malgré son âge, Han conserva son charme de voyou et ses compétences de pilotage. Son retour à la contrebande après l\'effondrement de sa relation avec Leia en fit une figure tragique - essayant toujours de distancer ses échecs. Cette figurine essentielle de la trilogie suite représente le dernier chapitre de Han et son sacrifice ultime pour tenter d\'atteindre son fils.',
    description_es: 'Esta minifigura de Han Solo mayor captura al legendario contrabandista décadas después de la trilogía original, mostrándolo curtido y hastiado del mundo en El Despertar de la Fuerza. La impresión incluye cabello con vetas grises y rasgos faciales envejecidos, reflejando los años pasados huir de su pasado después de perder a Ben Solo al lado oscuro. A pesar de su edad, Han retuvo su encanto pícaro y habilidades de pilotaje. Su regreso al contrabando después del colapso de su relación con Leia lo convirtió en una figura trágica - aún tratando de escapar de sus fracasos. Esta minifigura esencial de la trilogía secuela representa el capítulo final de Han y su sacrificio supremo al intentar alcanzar a su hijo.'
  },
  {
    minifigure_no: 'sw0842',
    name: 'First Order Heavy Assault Stormtrooper (Rounded Mouth Pattern) - Backpack',
    description_en: 'First Order heavy assault stormtroopers, also known as megablasters or flametroopers, specialized in frontline combat with heavy weapons. This variant features the distinctive rounded mouth pattern helmet design and includes a backpack for ammunition or fuel supplies. These elite troopers wore specialized armor modifications to support their heavy weaponry, making them formidable opponents in ground assaults. The rounded mouth grille distinguishes this variant from standard First Order stormtroopers. Essential for building First Order armies and recreating ground battle scenes from the sequel trilogy, these specialized troops represented the enhanced military capabilities of the resurgent Imperial remnant.',
    description_de: 'First-Order-Schwer-Angriffs-Stormtrooper, auch bekannt als Megablaster oder Flammenwerfer, spezialisierten sich auf Frontkampf mit schweren Waffen. Diese Variante zeigt das charakteristische abgerundete Mundmuster-Helmdesign und enthält einen Rucksack für Munitions- oder Treibstoffvorräte. Diese Elite-Truppen trugen spezialisierte Rüstungsmodifikationen, um ihre schweren Waffen zu unterstützen, was sie zu beeindruckenden Gegnern in Bodenangriffen machte. Das abgerundete Mundgitter unterscheidet diese Variante von Standard-First-Order-Stormtroopers. Essentiell zum Aufbau von First-Order-Armeen und Nachstellen von Bodenkampf-Szenen aus der Sequel-Trilogie repräsentierten diese spezialisierten Truppen die verbesserten militärischen Fähigkeiten des wiederauflebenden imperialen Überrests.',
    description_fr: 'Les stormtroopers d\'assaut lourd du Premier Ordre, également connus sous le nom de megablasters ou lance-flammes, se spécialisaient dans le combat de première ligne avec des armes lourdes. Cette variante présente le design de casque distinctif à motif de bouche arrondie et inclut un sac à dos pour les munitions ou les réserves de carburant. Ces troopers d\'élite portaient des modifications d\'armure spécialisées pour soutenir leur armement lourd, en faisant des adversaires formidables dans les assauts terrestres. La grille de bouche arrondie distingue cette variante des stormtroopers standard du Premier Ordre. Essentielle pour construire des armées du Premier Ordre et recréer des scènes de bataille au sol de la trilogie suite, ces troupes spécialisées représentaient les capacités militaires améliorées du vestige Impérial ressurgent.',
    description_es: 'Los stormtroopers de asalto pesado de la Primera Orden, también conocidos como megablasters o lanzallamas, se especializaban en combate de primera línea con armas pesadas. Esta variante presenta el distintivo diseño de casco con patrón de boca redondeada e incluye una mochila para suministros de munición o combustible. Estos soldados de élite llevaban modificaciones de armadura especializadas para soportar su armamento pesado, haciéndolos oponentes formidables en asaltos terrestres. La rejilla de boca redondeada distingue esta variante de stormtroopers estándar de la Primera Orden. Esencial para construir ejércitos de la Primera Orden y recrear escenas de batalla terrestre de la trilogía secuela, estas tropas especializadas representaban las capacidades militares mejoradas del remanente Imperial resurgente.'
  }
];

async function saveBatch() {
  console.log('Starting batch save for sw0833-sw0842...');

  for (const minifig of batch) {
    try {
      await prisma.minifigCatalog.update({
        where: { minifigure_no: minifig.minifigure_no },
        data: {
          description_en: minifig.description_en,
          description_de: minifig.description_de,
          description_fr: minifig.description_fr,
          description_es: minifig.description_es,
          description_generated_at: new Date(),
          description_status: 'completed'
        }
      });
      console.log(`✓ Saved ${minifig.minifigure_no}: ${minifig.name}`);
    } catch (error) {
      console.error(`✗ Failed to save ${minifig.minifigure_no}:`, error);
    }
  }

  console.log(`Batch complete! ${batch.length} minifigs saved (sw0833-sw0842).`);
  await prisma.$disconnect();
}

saveBatch();