import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    minifigure_no: 'sw0662',
    name: 'General Hux - Cap',
    description_en: 'General Armitage Hux commanded First Order military operations as a ruthless young officer obsessed with order and Imperial legacy. This minifigure shows Hux wearing his distinctive officer cap and black uniform with rank insignia. Hux controlled Starkiller Base and delivered the famous speech before destroying the Hosnian system. His rivalry with Kylo Ren created tension within First Order leadership. Despite his tactical competence, Hux\'s fanaticism and ambition often clouded his judgment. The cap distinguishes this variant from bareheaded versions. Collectors value General Hux for First Order command displays and Starkiller Base scenes.',
    description_de: 'General Armitage Hux befehligte militärische Operationen der Ersten Ordnung als rücksichtsloser junger Offizier, besessen von Ordnung und imperialem Erbe. Diese Minifigur zeigt Hux mit seiner markanten Offizierskappe und schwarzer Uniform mit Rangabzeichen. Hux kontrollierte Starkiller Base und hielt die berühmte Rede vor der Zerstörung des Hosnian-Systems. Seine Rivalität mit Kylo Ren schuf Spannungen innerhalb der Ersten-Ordnung-Führung. Trotz seiner taktischen Kompetenz trübten Hux\' Fanatismus und Ehrgeiz oft sein Urteilsvermögen. Die Kappe unterscheidet diese Variante von Versionen ohne Kopfbedeckung. Sammler schätzen General Hux für Erste-Ordnung-Befehls-Displays und Starkiller-Base-Szenen.',
    description_fr: 'Le Général Armitage Hux commandait les opérations militaires du Premier Ordre en tant que jeune officier impitoyable obsédé par l\'ordre et l\'héritage impérial. Cette minifigurine montre Hux portant sa casquette d\'officier distinctive et son uniforme noir avec insignes de rang. Hux contrôlait la Base Starkiller et a prononcé le célèbre discours avant de détruire le système Hosnian. Sa rivalité avec Kylo Ren créait des tensions au sein du leadership du Premier Ordre. Malgré sa compétence tactique, le fanatisme et l\'ambition de Hux obscurcissaient souvent son jugement. La casquette distingue cette variante des versions tête nue. Les collectionneurs apprécient le Général Hux pour les displays de commandement du Premier Ordre et les scènes de Base Starkiller.',
    description_es: 'El General Armitage Hux comandaba operaciones militares de la Primera Orden como un oficial joven despiadado obsesionado con el orden y el legado imperial. Esta minifigura muestra a Hux usando su distintiva gorra de oficial y uniforme negro con insignias de rango. Hux controlaba la Base Starkiller y pronunció el famoso discurso antes de destruir el sistema Hosnian. Su rivalidad con Kylo Ren creó tensión dentro del liderazgo de la Primera Orden. A pesar de su competencia táctica, el fanatismo y ambición de Hux a menudo nublaban su juicio. La gorra distingue esta variante de versiones sin sombrero. Los coleccionistas valoran al General Hux para exhibiciones de comando de la Primera Orden y escenas de Base Starkiller.'
  },
  {
    minifigure_no: 'sw0663',
    name: 'Kylo Ren (Helmet)',
    description_en: 'Kylo Ren was the dark warrior leading the Knights of Ren and serving Supreme Leader Snoke while struggling with light side temptation. This helmeted variant shows his intimidating masked appearance with distinctive crossguard lightsaber. Born Ben Solo, he fell to darkness under Snoke\'s manipulation. His unstable red lightsaber reflected his inner conflict and raw power. Kylo\'s mask emulated Darth Vader while seeking to finish what his grandfather started. The helmet concealed his identity and enhanced his fearsome presence. Collectors highly value Kylo Ren for sequel trilogy displays and as the saga\'s conflicted antagonist.',
    description_de: 'Kylo Ren war der dunkle Krieger, der die Ritter von Ren anführte und dem Obersten Anführer Snoke diente, während er mit der Versuchung der hellen Seite kämpfte. Diese behelmte Variante zeigt sein einschüchterndes maskiertes Erscheinungsbild mit markanter Kreuzparierstange-Lichtschwert. Geboren als Ben Solo, fiel er unter Snokes Manipulation in die Dunkelheit. Sein instabiles rotes Lichtschwert spiegelte seinen inneren Konflikt und rohe Macht wider. Kylos Maske ahmte Darth Vader nach und versuchte zu vollenden, was sein Großvater begonnen hatte. Der Helm verbarg seine Identität und verstärkte seine furchteinflößende Präsenz. Sammler schätzen Kylo Ren sehr für Sequel-Trilogie-Displays und als konflikthaften Antagonisten der Saga.',
    description_fr: 'Kylo Ren était le guerrier sombre dirigeant les Chevaliers de Ren et servant le Leader Suprême Snoke tout en luttant contre la tentation du côté lumineux. Cette variante casquée montre son apparence masquée intimidante avec un sabre laser à garde croisée distinctif. Né Ben Solo, il est tombé dans les ténèbres sous la manipulation de Snoke. Son sabre laser rouge instable reflétait son conflit intérieur et sa puissance brute. Le masque de Kylo imitait Dark Vador tout en cherchant à terminer ce que son grand-père avait commencé. Le casque dissimulait son identité et renforçait sa présence redoutable. Les collectionneurs apprécient hautement Kylo Ren pour les displays de trilogie des suites et comme antagoniste conflictuel de la saga.',
    description_es: 'Kylo Ren era el guerrero oscuro liderando los Caballeros de Ren y sirviendo al Líder Supremo Snoke mientras luchaba con la tentación del lado luminoso. Esta variante con casco muestra su intimidante apariencia enmascarada con distintivo sable de luz de guardamano cruzado. Nacido Ben Solo, cayó en la oscuridad bajo la manipulación de Snoke. Su inestable sable de luz rojo reflejaba su conflicto interno y poder crudo. La máscara de Kylo emulaba a Darth Vader mientras buscaba terminar lo que su abuelo comenzó. El casco ocultaba su identidad y mejoraba su presencia temible. Los coleccionistas valoran altamente a Kylo Ren para exhibiciones de trilogía de secuelas y como antagonista conflictuado de la saga.'
  },
  {
    minifigure_no: 'sw0664',
    name: 'First Order Stormtrooper Officer (Rounded Mouth Pattern)',
    description_en: 'First Order Stormtrooper Officers commanded infantry squads with distinctive armor markings indicating rank. This variant features the rounded mouth pattern helmet design. Officers led frontline troops during planetary assaults and security operations. Their enhanced armor included communication systems for coordinating squad tactics. The rounded mouth pattern represents updated First Order helmet aesthetics. Officers maintained discipline and executed Supreme Leader directives. Collectors value officer variants for building command structures and diverse trooper displays.',
    description_de: 'Erste-Ordnung-Sturmtruppler-Offiziere befehligten Infanterie-Trupps mit markanten Rüstungsmarkierungen, die den Rang anzeigen. Diese Variante zeigt das Helmdesign mit rundem Mundmuster. Offiziere führten Frontlinien-Truppen während planetarischer Angriffe und Sicherheitsoperationen an. Ihre verbesserte Rüstung umfasste Kommunikationssysteme zur Koordinierung von Truppentaktiken. Das runde Mundmuster repräsentiert aktualisierte Erste-Ordnung-Helm-Ästhetik. Offiziere hielten Disziplin aufrecht und führten Direktiven des Obersten Anführers aus. Sammler schätzen Offiziersvarianten für den Aufbau von Befehlsstrukturen und vielfältigen Truppen-Displays.',
    description_fr: 'Les Officiers Stormtroopers du Premier Ordre commandaient des escouades d\'infanterie avec des marques d\'armure distinctives indiquant le rang. Cette variante présente le design de casque à motif de bouche arrondie. Les officiers dirigeaient les troupes de première ligne lors d\'assauts planétaires et d\'opérations de sécurité. Leur armure améliorée incluait des systèmes de communication pour coordonner les tactiques d\'escouade. Le motif de bouche arrondie représente l\'esthétique de casque mise à jour du Premier Ordre. Les officiers maintenaient la discipline et exécutaient les directives du Leader Suprême. Les collectionneurs apprécient les variantes d\'officiers pour construire des structures de commandement et des displays de troupes diverses.',
    description_es: 'Los Oficiales Stormtrooper de la Primera Orden comandaban escuadrones de infantería con marcas distintivas de armadura indicando rango. Esta variante presenta el diseño de casco con patrón de boca redondeada. Los oficiales lideraban tropas de primera línea durante asaltos planetarios y operaciones de seguridad. Su armadura mejorada incluía sistemas de comunicación para coordinar tácticas de escuadrón. El patrón de boca redondeada representa estética actualizada de casco de la Primera Orden. Los oficiales mantenían disciplina y ejecutaban directivas del Líder Supremo. Los coleccionistas valoran variantes de oficiales para construir estructuras de comando y exhibiciones diversas de tropas.'
  },
  {
    minifigure_no: 'sw0665',
    name: 'First Order Officer (Lieutenant / Captain) - Female',
    description_en: 'Female First Order Officers served in command positions aboard Star Destroyers and military installations. This minifigure represents the gender diversity within First Order ranks. Officers wore black uniforms with rank insignia managing crew and coordinating operations. Female officers held equal authority commanding vessels and ground forces. Their presence showed the First Order recruited talent regardless of gender. The black uniform with rank plaques identified mid-level command personnel. Collectors value female officer figures for diversity in displays and realistic crew compositions.',
    description_de: 'Weibliche Erste-Ordnung-Offiziere dienten in Befehlspositionen an Bord von Sternenzerstörern und Militäranlagen. Diese Minifigur repräsentiert die Geschlechtervielfalt innerhalb der Ersten-Ordnung-Ränge. Offiziere trugen schwarze Uniformen mit Rangabzeichen, die Besatzung verwalteten und Operationen koordinierten. Weibliche Offiziere hatten gleiche Autorität beim Befehligen von Schiffen und Bodentruppen. Ihre Präsenz zeigte, dass die Erste Ordnung Talente unabhängig vom Geschlecht rekrutierte. Die schwarze Uniform mit Rangplaketten identifizierte mittleres Befehlspersonal. Sammler schätzen weibliche Offiziersfiguren für Vielfalt in Displays und realistische Besatzungszusammensetzungen.',
    description_fr: 'Les Officiers Féminins du Premier Ordre servaient dans des positions de commandement à bord des Destroyers Stellaires et des installations militaires. Cette minifigurine représente la diversité des genres au sein des rangs du Premier Ordre. Les officiers portaient des uniformes noirs avec des insignes de rang gérant l\'équipage et coordonnant les opérations. Les officiers féminins détenaient une autorité égale commandant des vaisseaux et des forces terrestres. Leur présence montrait que le Premier Ordre recrutait des talents indépendamment du genre. L\'uniforme noir avec plaques de rang identifiait le personnel de commandement de niveau intermédiaire. Les collectionneurs apprécient les figurines d\'officiers féminins pour la diversité dans les displays et les compositions d\'équipage réalistes.',
    description_es: 'Las Oficiales Femeninas de la Primera Orden servían en posiciones de comando a bordo de Destructores Estelares e instalaciones militares. Esta minifigura representa la diversidad de género dentro de los rangos de la Primera Orden. Las oficiales usaban uniformes negros con insignias de rango gestionando tripulación y coordinando operaciones. Las oficiales femeninas tenían igual autoridad comandando naves y fuerzas terrestres. Su presencia mostraba que la Primera Orden reclutaba talento independientemente del género. El uniforme negro con placas de rango identificaba personal de comando de nivel medio. Los coleccionistas valoran figuras de oficiales femeninas para diversidad en exhibiciones y composiciones de tripulación realistas.'
  },
  {
    minifigure_no: 'sw0666',
    name: 'First Order Flametrooper',
    description_en: 'First Order Flametroopers were specialized incendiary troops using flamethrowers for area denial and bunker clearing. This minifigure features distinctive red-marked armor and flame weapon. Flametroopers wore heat-resistant suits with enhanced protection against their own weapons. They deployed during the Jakku village massacre and other ground operations. The red armor markings identified their hazardous specialty. Flametroopers represented the First Order\'s brutal tactics. Collectors value flametroopers for their unique red accents and specialized role.',
    description_de: 'Erste-Ordnung-Flammentruppen waren spezialisierte Brandtruppen, die Flammenwerfer für Gebietsverweigerung und Bunkerräumung nutzten. Diese Minifigur zeigt markante rot markierte Rüstung und Flammenwaffe. Flammentruppen trugen hitzebeständige Anzüge mit verstärktem Schutz gegen ihre eigenen Waffen. Sie wurden während des Jakku-Dorf-Massakers und anderen Bodenoperationen eingesetzt. Die roten Rüstungsmarkierungen identifizierten ihre gefährliche Spezialisierung. Flammentruppen repräsentierten die brutalen Taktiken der Ersten Ordnung. Sammler schätzen Flammentruppen für ihre einzigartigen roten Akzente und spezialisierte Rolle.',
    description_fr: 'Les Flametroopers du Premier Ordre étaient des troupes incendiaires spécialisées utilisant des lance-flammes pour le déni de zone et le nettoyage de bunkers. Cette minifigurine présente une armure marquée de rouge distinctive et une arme à flamme. Les Flametroopers portaient des combinaisons résistantes à la chaleur avec une protection renforcée contre leurs propres armes. Ils ont été déployés lors du massacre du village de Jakku et d\'autres opérations terrestres. Les marques d\'armure rouges identifiaient leur spécialité dangereuse. Les Flametroopers représentaient les tactiques brutales du Premier Ordre. Les collectionneurs apprécient les flametroopers pour leurs accents rouges uniques et leur rôle spécialisé.',
    description_es: 'Los Flametroopers de la Primera Orden eran tropas incendiarias especializadas usando lanzallamas para negación de área y limpieza de búnkeres. Esta minifigura presenta armadura distintiva marcada en rojo y arma de llamas. Los Flametroopers usaban trajes resistentes al calor con protección mejorada contra sus propias armas. Se desplegaron durante la masacre de la aldea de Jakku y otras operaciones terrestres. Las marcas rojas de armadura identificaban su peligrosa especialidad. Los Flametroopers representaban las tácticas brutales de la Primera Orden. Los coleccionistas valoran a los flametroopers por sus acentos rojos únicos y papel especializado.'
  },
  {
    minifigure_no: 'sw0667',
    name: 'First Order Stormtrooper (Rounded Mouth Pattern)',
    description_en: 'First Order Stormtroopers formed the infantry backbone trained from childhood for absolute loyalty. This variant shows the rounded mouth pattern helmet design. Unlike Imperial stormtroopers, First Order troops underwent lifelong conditioning. They served across the galaxy enforcing Supreme Leader directives. The rounded mouth represents updated armor aesthetics. Standard troopers formed the bulk of ground forces. Collectors value stormtroopers for army building and battalion displays.',
    description_de: 'Erste-Ordnung-Sturmtruppler bildeten das Infanterie-Rückgrat, trainiert von Kindheit an für absolute Loyalität. Diese Variante zeigt das Helmdesign mit rundem Mundmuster. Im Gegensatz zu imperialen Sturmtrupplern durchliefen Erste-Ordnung-Truppen lebenslange Konditionierung. Sie dienten in der ganzen Galaxis und setzten Direktiven des Obersten Anführers durch. Der runde Mund repräsentiert aktualisierte Rüstungsästhetik. Standard-Truppen bildeten die Masse der Bodentruppen. Sammler schätzen Sturmtruppler für Army-Building und Bataillons-Displays.',
    description_fr: 'Les Stormtroopers du Premier Ordre formaient l\'épine dorsale de l\'infanterie formée dès l\'enfance pour une loyauté absolue. Cette variante montre le design de casque à motif de bouche arrondie. Contrairement aux stormtroopers impériaux, les troupes du Premier Ordre subissaient un conditionnement à vie. Ils servaient à travers la galaxie appliquant les directives du Leader Suprême. La bouche arrondie représente une esthétique d\'armure mise à jour. Les troupes standard formaient la masse des forces terrestres. Les collectionneurs apprécient les stormtroopers pour la construction d\'armée et les displays de bataillon.',
    description_es: 'Los Stormtroopers de la Primera Orden formaban la columna vertebral de infantería entrenada desde la infancia para lealtad absoluta. Esta variante muestra el diseño de casco con patrón de boca redondeada. A diferencia de los stormtroopers imperiales, las tropas de la Primera Orden se sometían a condicionamiento de por vida. Servían a través de la galaxia aplicando directivas del Líder Supremo. La boca redondeada representa estética de armadura actualizada. Las tropas estándar formaban la masa de fuerzas terrestres. Los coleccionistas valoran a los stormtroopers para construcción de ejércitos y exhibiciones de batallón.'
  }
];

async function saveBatch() {
  console.log('Starting batch save for sw0662-sw0667...');
  for (const minifig of batch) {
    try {
      await prisma.minifigCatalog.update({
        where: { minifigure_no: minifig.minifigure_no },
        data: {
          description_en: minifig.description_en,
          description_de: minifig.description_de,
          description_fr: minifig.description_fr,
          description_es: minifig.description_es,
          description_generated_at: new Date(),
          description_status: 'generated'
        },
      });
      console.log(`✓ Saved ${minifig.minifigure_no}: ${minifig.name}`);
    } catch (error) {
      console.error(`✗ Error saving ${minifig.minifigure_no}:`, error);
    }
  }
  console.log('Batch complete! 6 minifigs saved.');
  await prisma.$disconnect();
}
saveBatch();
