import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    minifigure_no: 'sw0648',
    name: 'Astromech Droid, Imperial, Black',
    description_en: 'Imperial Astromech Droids served aboard Star Destroyers, TIE fighters, and other Imperial spacecraft providing navigation, repair, and technical support. This black variant represents the Empire\'s utilitarian approach to droid labor, lacking the personality and individuality of Rebel astromechs like R2-D2. Imperial astromechs were often memory-wiped regularly to prevent loyalty development or information retention that could compromise security. The black coloring distinguishes Imperial service droids from the more colorful Rebel and civilian models. These droids maintained Imperial starfighters, calculated hyperspace jumps, and performed routine repairs across the Imperial fleet. Unlike Rebel droids treated as companions, Imperial astromechs were viewed as disposable tools. Collectors value Imperial astromechs for building Star Destroyer maintenance bays, TIE fighter hangars, and showing the cold, mechanical nature of Imperial military operations that contrasted with the Rebellion\'s more personal approach.',
    description_de: 'Imperiale Astromech-Droiden dienten an Bord von Sternenzerstörern, TIE-Jägern und anderen imperialen Raumschiffen und boten Navigation, Reparatur und technische Unterstützung. Diese schwarze Variante repräsentiert den utilitaristischen Ansatz des Imperiums zur Droiden-Arbeitskraft und fehlt die Persönlichkeit und Individualität von Rebellenastromechs wie R2-D2. Imperiale Astromechs wurden oft regelmäßig speichergelöscht, um Loyalitätsentwicklung oder Informationsspeicherung zu verhindern, die die Sicherheit gefährden könnte. Die schwarze Färbung unterscheidet imperiale Dienstdroiden von den farbenfroheren Rebellen- und Zivilmodellen. Diese Droiden warteten imperiale Sternenjäger, berechneten Hyperraumsprünge und führten Routinereparaturen in der gesamten imperialen Flotte durch. Im Gegensatz zu Rebellendroiden, die als Gefährten behandelt wurden, wurden imperiale Astromechs als Wegwerfwerkzeuge angesehen. Sammler schätzen imperiale Astromechs für den Aufbau von Sternenzerstörer-Wartungsbuchten, TIE-Jäger-Hangars und die Darstellung der kalten, mechanischen Natur imperialer Militäroperationen, die mit dem persönlicheren Ansatz der Rebellion kontrastierte.',
    description_fr: 'Les Droïdes Astromech Impériaux servaient à bord des Destroyers Stellaires, des chasseurs TIE et d\'autres vaisseaux spatiaux impériaux fournissant navigation, réparation et support technique. Cette variante noire représente l\'approche utilitaire de l\'Empire envers la main-d\'œuvre droïde, manquant la personnalité et l\'individualité des astromechs rebelles comme R2-D2. Les astromechs impériaux subissaient souvent des effacements de mémoire réguliers pour prévenir le développement de loyauté ou la rétention d\'informations qui pourrait compromettre la sécurité. La coloration noire distingue les droïdes de service impériaux des modèles rebelles et civils plus colorés. Ces droïdes maintenaient les chasseurs stellaires impériaux, calculaient les sauts en hyperespace et effectuaient des réparations de routine à travers la flotte impériale. Contrairement aux droïdes rebelles traités comme des compagnons, les astromechs impériaux étaient vus comme des outils jetables. Les collectionneurs apprécient les astromechs impériaux pour construire des baies de maintenance de Destroyer Stellaire, des hangars de chasseurs TIE et montrer la nature froide et mécanique des opérations militaires impériales qui contrastait avec l\'approche plus personnelle de la Rébellion.',
    description_es: 'Los Droides Astromech Imperiales servían a bordo de Destructores Estelares, cazas TIE y otras naves espaciales imperiales proporcionando navegación, reparación y soporte técnico. Esta variante negra representa el enfoque utilitario del Imperio hacia la mano de obra droide, careciendo de la personalidad e individualidad de astromechs rebeldes como R2-D2. Los astromechs imperiales a menudo tenían borrado de memoria regular para prevenir desarrollo de lealtad o retención de información que pudiera comprometer la seguridad. La coloración negra distingue a los droides de servicio imperiales de los modelos rebeldes y civiles más coloridos. Estos droides mantenían cazas estelares imperiales, calculaban saltos de hiperespacio y realizaban reparaciones rutinarias a través de la flota imperial. A diferencia de los droides rebeldes tratados como compañeros, los astromechs imperiales eran vistos como herramientas desechables. Los coleccionistas valoran a los astromechs imperiales para construir bahías de mantenimiento de Destructores Estelares, hangares de cazas TIE y mostrar la naturaleza fría y mecánica de las operaciones militares imperiales que contrastaba con el enfoque más personal de la Rebelión.'
  },
  {
    minifigure_no: 'sw0649',
    name: 'Watto - Sand Blue, Printed Head, Tan Hands',
    description_en: 'Watto was the Toydarian junk dealer who owned Anakin and Shmi Skywalker as slaves on Tatooine before Qui-Gon Jinn freed Anakin through the famous podrace wager. This minifigure features sand blue coloring representing Watto\'s Toydarian skin, printed head details showing his distinctive trunk and tusks, and tan hands. Watto\'s immunity to Jedi mind tricks due to his Toydarian species made him a shrewd but ultimately fair dealer. His role in The Phantom Menace was crucial - if he hadn\'t agreed to the podrace bet, Anakin might never have left Tatooine. The detailed head printing captures Watto\'s unique alien features including his proboscis and small wings. His character represented the ordinary beings of the Star Wars universe caught up in galaxy-changing events. Collectors value Watto for his distinctive species design, connection to Anakin\'s origin story, and representation of Tatooine\'s colorful merchants and slave owners.',
    description_de: 'Watto war der Toydorianische Schrotthändler, der Anakin und Shmi Skywalker als Sklaven auf Tatooine besaß, bevor Qui-Gon Jinn Anakin durch die berühmte Podrennen-Wette befreite. Diese Minifigur zeigt sandblaue Färbung, die Wattos Toydorianische Haut repräsentiert, bedruckte Kopfdetails, die seinen markanten Rüssel und Stoßzähne zeigen, und beige Hände. Wattos Immunität gegen Jedi-Gedankentricks aufgrund seiner Toydorianischen Spezies machte ihn zu einem schlauen, aber letztendlich fairen Händler. Seine Rolle in Die dunkle Bedrohung war entscheidend - hätte er der Podrennen-Wette nicht zugestimmt, hätte Anakin Tatooine vielleicht nie verlassen. Die detaillierte Kopfbedruckung erfasst Wattos einzigartige Alien-Merkmale einschließlich seines Rüssels und kleiner Flügel. Sein Charakter repräsentierte die gewöhnlichen Wesen des Star-Wars-Universums, die in galaxie-verändernde Ereignisse verwickelt wurden. Sammler schätzen Watto für sein markantes Spezies-Design, Verbindung zu Anakins Ursprungsgeschichte und Darstellung von Tatooines farbenfrohen Händlern und Sklavenbesitzern.',
    description_fr: 'Watto était le ferrailleur Toydarian qui possédait Anakin et Shmi Skywalker comme esclaves sur Tatooine avant que Qui-Gon Jinn ne libère Anakin grâce au célèbre pari de course de modules. Cette minifigurine présente une coloration bleu sable représentant la peau Toydarian de Watto, des détails de tête imprimés montrant sa trompe et ses défenses distinctives, et des mains beiges. L\'immunité de Watto aux tours de l\'esprit Jedi en raison de son espèce Toydarian en faisait un négociant rusé mais finalement juste. Son rôle dans La Menace Fantôme était crucial - s\'il n\'avait pas accepté le pari de course de modules, Anakin n\'aurait peut-être jamais quitté Tatooine. L\'impression détaillée de la tête capture les caractéristiques alien uniques de Watto incluant sa trompe et ses petites ailes. Son personnage représentait les êtres ordinaires de l\'univers Star Wars pris dans des événements changeant la galaxie. Les collectionneurs apprécient Watto pour son design d\'espèce distinctif, sa connexion à l\'histoire d\'origine d\'Anakin et la représentation des marchands colorés et propriétaires d\'esclaves de Tatooine.',
    description_es: 'Watto era el chatarrero Toydoriano que poseía a Anakin y Shmi Skywalker como esclavos en Tatooine antes de que Qui-Gon Jinn liberara a Anakin mediante la famosa apuesta de carrera de vainas. Esta minifigura presenta coloración azul arena representando la piel Toydoriana de Watto, detalles de cabeza impresos mostrando su distintiva trompa y colmillos, y manos beige. La inmunidad de Watto a los trucos mentales Jedi debido a su especie Toydoriana lo convirtió en un comerciante astuto pero finalmente justo. Su papel en La Amenaza Fantasma fue crucial - si no hubiera aceptado la apuesta de carrera de vainas, Anakin quizás nunca hubiera dejado Tatooine. La impresión detallada de cabeza captura las características alienígenas únicas de Watto incluyendo su probóscide y pequeñas alas. Su personaje representaba a los seres ordinarios del universo Star Wars atrapados en eventos que cambian la galaxia. Los coleccionistas valoran a Watto por su diseño de especie distintivo, conexión con la historia de origen de Anakin y representación de los coloridos comerciantes y dueños de esclavos de Tatooine.'
  },
  {
    minifigure_no: 'sw0650',
    name: 'Darth Maul - Horns and Cape, Printed Legs',
    description_en: 'Darth Maul was the fearsome Zabrak Sith apprentice who emerged from shadows to confront the Jedi in The Phantom Menace, wielding his iconic double-bladed lightsaber. This minifigure features his distinctive horned head, black and red Zabrak facial tattoos, flowing black cape, and printed legs showing his martial arts-inspired outfit. Maul\'s aggressive lightsaber combat and acrobatic fighting style made him one of cinema\'s most memorable villains despite limited dialogue. His defeat of Qui-Gon Jinn and subsequent bisection by Obi-Wan became an iconic Star Wars moment. The printed legs detail shows LEGO\'s commitment to capturing Maul\'s complete appearance. Maul\'s survival and return in The Clone Wars and Rebels expanded his character significantly. Collectors highly value Darth Maul figures for their striking red and black color scheme, dual lightsaber display potential, and representation of the Sith\'s return to galactic affairs after centuries of hiding.',
    description_de: 'Darth Maul war der furchterregende Zabrak-Sith-Schüler, der aus Schatten auftauchte, um die Jedi in Die dunkle Bedrohung zu konfrontieren und sein ikonisches doppelklingiges Lichtschwert zu führen. Diese Minifigur zeigt seinen markanten gehörnten Kopf, schwarz-rote Zabrak-Gesichtstätowierungen, fließenden schwarzen Umhang und bedruckte Beine, die sein von Kampfkünsten inspiriertes Outfit zeigen. Mauls aggressiver Lichtschwertkampf und akrobatischer Kampfstil machten ihn trotz begrenztem Dialog zu einem der unvergesslichsten Schurken des Kinos. Seine Niederlage von Qui-Gon Jinn und anschließende Durchtrennung durch Obi-Wan wurde zu einem ikonischen Star-Wars-Moment. Das bedruckte Beindetail zeigt LEGOs Engagement, Mauls vollständiges Erscheinungsbild einzufangen. Mauls Überleben und Rückkehr in The Clone Wars und Rebels erweiterte seinen Charakter erheblich. Sammler schätzen Darth-Maul-Figuren sehr für ihr auffälliges rot-schwarzes Farbschema, duales Lichtschwert-Display-Potenzial und Darstellung der Rückkehr der Sith in galaktische Angelegenheiten nach Jahrhunderten des Versteckens.',
    description_fr: 'Dark Maul était le redoutable apprenti Sith Zabrak qui a émergé des ombres pour affronter les Jedi dans La Menace Fantôme, maniant son iconique sabre laser à double lame. Cette minifigurine présente sa tête à cornes distinctive, des tatouages faciaux Zabrak noirs et rouges, une cape noire fluide et des jambes imprimées montrant sa tenue inspirée des arts martiaux. Le combat au sabre laser agressif de Maul et son style de combat acrobatique en ont fait l\'un des méchants les plus mémorables du cinéma malgré un dialogue limité. Sa défaite de Qui-Gon Jinn et sa bissection ultérieure par Obi-Wan sont devenues un moment iconique de Star Wars. Le détail des jambes imprimées montre l\'engagement de LEGO à capturer l\'apparence complète de Maul. La survie et le retour de Maul dans The Clone Wars et Rebels ont considérablement élargi son personnage. Les collectionneurs apprécient hautement les figurines Dark Maul pour leur schéma de couleurs rouge et noir frappant, leur potentiel d\'affichage à double sabre laser et la représentation du retour des Sith dans les affaires galactiques après des siècles de cachette.',
    description_es: 'Darth Maul era el temible aprendiz Sith Zabrak que emergió de las sombras para confrontar a los Jedi en La Amenaza Fantasma, empuñando su icónico sable de luz de doble hoja. Esta minifigura presenta su distintiva cabeza con cuernos, tatuajes faciales Zabrak negros y rojos, capa negra fluida y piernas impresas mostrando su atuendo inspirado en artes marciales. El combate agresivo con sable de luz de Maul y estilo de lucha acrobático lo convirtieron en uno de los villanos más memorables del cine a pesar del diálogo limitado. Su derrota de Qui-Gon Jinn y subsiguiente bisección por Obi-Wan se convirtió en un momento icónico de Star Wars. El detalle de piernas impresas muestra el compromiso de LEGO en capturar la apariencia completa de Maul. La supervivencia y regreso de Maul en The Clone Wars y Rebels expandió su personaje significativamente. Los coleccionistas valoran altamente las figuras de Darth Maul por su llamativo esquema de colores rojo y negro, potencial de exhibición de sable de luz dual y representación del regreso de los Sith a los asuntos galácticos después de siglos de ocultamiento.'
  },
  {
    minifigure_no: 'sw0651',
    name: 'Qui-Gon Jinn - Poncho, Reddish Brown Beard',
    description_en: 'This Qui-Gon Jinn variant features the Jedi Master wearing a practical poncho over his traditional robes and sporting his distinctive reddish brown beard. The poncho represents Qui-Gon during his mission to Tatooine where desert conditions required additional protection. As Obi-Wan\'s master and discoverer of Anakin Skywalker, Qui-Gon played a pivotal role in galactic history despite his death at Darth Maul\'s hands. His unconventional approach to the Force and willingness to defy the Jedi Council made him a maverick who trusted in the living Force over rigid doctrine. Qui-Gon\'s belief that Anakin was the Chosen One set events in motion that would reshape the galaxy. The poncho detail shows LEGO\'s attention to specific scenes and environmental adaptations. Collectors value this variant for its unique poncho accessory, connection to The Phantom Menace Tatooine sequences, and representation of the wise Jedi Master whose actions had far-reaching consequences.',
    description_de: 'Diese Qui-Gon-Jinn-Variante zeigt den Jedi-Meister, der einen praktischen Poncho über seinen traditionellen Roben trägt und seinen markanten rotbraunen Bart trägt. Der Poncho repräsentiert Qui-Gon während seiner Mission nach Tatooine, wo Wüstenbedingungen zusätzlichen Schutz erforderten. Als Obi-Wans Meister und Entdecker von Anakin Skywalker spielte Qui-Gon eine entscheidende Rolle in der galaktischen Geschichte trotz seines Todes durch Darth Mauls Hand. Sein unkonventioneller Ansatz zur Macht und Bereitschaft, dem Jedi-Rat zu widersprechen, machten ihn zu einem Einzelgänger, der der lebendigen Macht über starre Doktrin vertraute. Qui-Gons Glaube, dass Anakin der Auserwählte war, setzte Ereignisse in Gang, die die Galaxis umgestalten würden. Das Poncho-Detail zeigt LEGOs Aufmerksamkeit für spezifische Szenen und Umweltanpassungen. Sammler schätzen diese Variante für ihr einzigartiges Poncho-Accessoire, Verbindung zu Die dunkle Bedrohung Tatooine-Sequenzen und Darstellung des weisen Jedi-Meisters, dessen Handlungen weitreichende Konsequenzen hatten.',
    description_fr: 'Cette variante de Qui-Gon Jinn présente le Maître Jedi portant un poncho pratique sur ses robes traditionnelles et arborant sa barbe brun rougeâtre distinctive. Le poncho représente Qui-Gon pendant sa mission sur Tatooine où les conditions désertiques nécessitaient une protection supplémentaire. En tant que maître d\'Obi-Wan et découvreur d\'Anakin Skywalker, Qui-Gon a joué un rôle central dans l\'histoire galactique malgré sa mort aux mains de Dark Maul. Son approche non conventionnelle de la Force et sa volonté de défier le Conseil Jedi en faisaient un franc-tireur qui faisait confiance à la Force vivante plutôt qu\'à une doctrine rigide. La croyance de Qui-Gon qu\'Anakin était l\'Élu a mis en mouvement des événements qui remodeleraient la galaxie. Le détail du poncho montre l\'attention de LEGO aux scènes spécifiques et aux adaptations environnementales. Les collectionneurs apprécient cette variante pour son accessoire poncho unique, sa connexion aux séquences de Tatooine de La Menace Fantôme et la représentation du sage Maître Jedi dont les actions ont eu des conséquences considérables.',
    description_es: 'Esta variante de Qui-Gon Jinn presenta al Maestro Jedi usando un poncho práctico sobre sus túnicas tradicionales y luciendo su distintiva barba marrón rojizo. El poncho representa a Qui-Gon durante su misión a Tatooine donde las condiciones desérticas requerían protección adicional. Como maestro de Obi-Wan y descubridor de Anakin Skywalker, Qui-Gon jugó un papel fundamental en la historia galáctica a pesar de su muerte a manos de Darth Maul. Su enfoque no convencional de la Fuerza y disposición a desafiar al Consejo Jedi lo convirtieron en un inconformista que confiaba en la Fuerza viviente sobre la doctrina rígida. La creencia de Qui-Gon de que Anakin era el Elegido puso en movimiento eventos que remodelarían la galaxia. El detalle del poncho muestra la atención de LEGO a escenas específicas y adaptaciones ambientales. Los coleccionistas valoran esta variante por su accesorio único de poncho, conexión con las secuencias de Tatooine de La Amenaza Fantasma y representación del sabio Maestro Jedi cuyas acciones tuvieron consecuencias de largo alcance.'
  },
  {
    minifigure_no: 'sw0652',
    name: 'DRK-1 Dark Eye Probe Droid - Black',
    description_en: 'The DRK-1 Dark Eye Probe Droid was a Sith surveillance unit deployed by Darth Maul to locate Queen Amidala during The Phantom Menace. This black spherical droid featured advanced sensor arrays and repulsorlift technology for silent reconnaissance. Dark Eye probes were specifically designed for covert operations, gathering intelligence without detection. Maul deployed several of these droids on Tatooine, with one successfully locating the Queen\'s party in Mos Espa. The probe\'s discovery led directly to the climactic lightsaber duel where Qui-Gon Jinn died. The spherical design represents one of LEGO\'s specialized droid builds distinct from standard minifigure construction. Dark Eye probes symbolized the Sith\'s patient, methodical approach to tracking their enemies. Collectors value this probe droid for its unique spherical construction, connection to pivotal plot moments, and representation of Sith technology and surveillance tactics during their secret operations.',
    description_de: 'Die DRK-1 Dark Eye Sondendroide war eine Sith-Überwachungseinheit, die von Darth Maul eingesetzt wurde, um Königin Amidala während Die dunkle Bedrohung zu lokalisieren. Dieser schwarze kugelförmige Droide verfügte über fortschrittliche Sensor-Arrays und Repulsorlift-Technologie für stille Aufklärung. Dark-Eye-Sonden waren speziell für verdeckte Operationen entwickelt und sammelten Informationen ohne Entdeckung. Maul setzte mehrere dieser Droiden auf Tatooine ein, wobei einer erfolgreich die Gruppe der Königin in Mos Espa lokalisierte. Die Entdeckung der Sonde führte direkt zum climaktischen Lichtschwertkampf, bei dem Qui-Gon Jinn starb. Das kugelförmige Design repräsentiert einen von LEGOs spezialisierten Droiden-Builds, der sich von Standard-Minifiguren-Konstruktion unterscheidet. Dark-Eye-Sonden symbolisierten den geduldigen, methodischen Ansatz der Sith zur Verfolgung ihrer Feinde. Sammler schätzen diese Sondendroide für ihre einzigartige kugelförmige Konstruktion, Verbindung zu entscheidenden Handlungsmomenten und Darstellung von Sith-Technologie und Überwachungstaktiken während ihrer geheimen Operationen.',
    description_fr: 'Le Droïde Sonde DRK-1 Dark Eye était une unité de surveillance Sith déployée par Dark Maul pour localiser la Reine Amidala pendant La Menace Fantôme. Ce droïde sphérique noir présentait des réseaux de capteurs avancés et une technologie répulseur pour une reconnaissance silencieuse. Les sondes Dark Eye étaient spécifiquement conçues pour des opérations secrètes, recueillant des renseignements sans détection. Maul a déployé plusieurs de ces droïdes sur Tatooine, l\'un localisant avec succès le groupe de la Reine à Mos Espa. La découverte de la sonde a conduit directement au duel au sabre laser climactique où Qui-Gon Jinn est mort. Le design sphérique représente l\'une des constructions de droïdes spécialisées de LEGO distinctes de la construction standard de minifigurine. Les sondes Dark Eye symbolisaient l\'approche patiente et méthodique des Sith pour traquer leurs ennemis. Les collectionneurs apprécient ce droïde sonde pour sa construction sphérique unique, sa connexion à des moments d\'intrigue cruciaux et la représentation de la technologie Sith et des tactiques de surveillance pendant leurs opérations secrètes.',
    description_es: 'El Droide Sonda DRK-1 Dark Eye era una unidad de vigilancia Sith desplegada por Darth Maul para localizar a la Reina Amidala durante La Amenaza Fantasma. Este droide esférico negro presentaba arrays de sensores avanzados y tecnología repulsora para reconocimiento silencioso. Las sondas Dark Eye fueron diseñadas específicamente para operaciones encubiertas, reuniendo inteligencia sin detección. Maul desplegó varios de estos droides en Tatooine, con uno localizando exitosamente al grupo de la Reina en Mos Espa. El descubrimiento de la sonda llevó directamente al duelo climático de sables de luz donde Qui-Gon Jinn murió. El diseño esférico representa una de las construcciones de droides especializados de LEGO distinta de la construcción estándar de minifiguras. Las sondas Dark Eye simbolizaban el enfoque paciente y metódico de los Sith para rastrear a sus enemigos. Los coleccionistas valoran este droide sonda por su construcción esférica única, conexión con momentos cruciales de la trama y representación de tecnología Sith y tácticas de vigilancia durante sus operaciones secretas.'
  },
  {
    minifigure_no: 'sw0653',
    name: 'C-3PO - Dark Red Arm',
    description_en: 'This C-3PO variant features a distinctive dark red replacement arm, representing the protocol droid\'s mismatched appearance in The Force Awakens. After decades of adventures, C-3PO sustained damage requiring replacement parts from other droids. The red arm came from another protocol droid named Omri who sacrificed himself to help C-3PO complete a Resistance mission. This variant symbolizes C-3PO\'s continued service to his friends decades after the original trilogy, now working with the Resistance against the First Order. The mismatched arm detail shows LEGO\'s attention to specific character appearances from different film eras. C-3PO eventually had the arm replaced with his standard gold plating, but this red-armed version captured fan attention during The Force Awakens marketing. Collectors value this variant for its unique visual distinctiveness, connection to sequel trilogy storytelling, and representation of C-3PO\'s enduring loyalty across multiple generations of galactic conflict.',
    description_de: 'Diese C-3PO-Variante zeigt einen markanten dunkelroten Ersatzarm, der das nicht übereinstimmende Erscheinungsbild des Protokolldroiden in Das Erwachen der Macht repräsentiert. Nach Jahrzehnten von Abenteuern erlitt C-3PO Schäden, die Ersatzteile von anderen Droiden erforderten. Der rote Arm stammte von einem anderen Protokolldroiden namens Omri, der sich opferte, um C-3PO zu helfen, eine Widerstands-Mission abzuschließen. Diese Variante symbolisiert C-3POs fortgesetzten Dienst für seine Freunde Jahrzehnte nach der Original-Trilogie, nun mit dem Widerstand gegen die Erste Ordnung arbeitend. Das nicht übereinstimmende Arm-Detail zeigt LEGOs Aufmerksamkeit für spezifische Charaktererscheinungen aus verschiedenen Film-Ären. C-3PO ließ den Arm schließlich durch seine Standard-Goldplattierung ersetzen, aber diese rotarmige Version erregte Fan-Aufmerksamkeit während des Das Erwachen der Macht Marketings. Sammler schätzen diese Variante für ihre einzigartige visuelle Unterscheidbarkeit, Verbindung zum Sequel-Trilogie-Storytelling und Darstellung von C-3POs dauerhafter Loyalität über mehrere Generationen galaktischer Konflikte.',
    description_fr: 'Cette variante de C-3PO présente un bras de remplacement rouge foncé distinctif, représentant l\'apparence dépareillée du droïde de protocole dans Le Réveil de la Force. Après des décennies d\'aventures, C-3PO a subi des dommages nécessitant des pièces de remplacement d\'autres droïdes. Le bras rouge provenait d\'un autre droïde de protocole nommé Omri qui s\'est sacrifié pour aider C-3PO à accomplir une mission de la Résistance. Cette variante symbolise le service continu de C-3PO envers ses amis des décennies après la trilogie originale, travaillant maintenant avec la Résistance contre le Premier Ordre. Le détail du bras dépareillé montre l\'attention de LEGO aux apparences spécifiques des personnages de différentes ères cinématographiques. C-3PO a finalement fait remplacer le bras par son placage doré standard, mais cette version à bras rouge a capturé l\'attention des fans pendant le marketing du Réveil de la Force. Les collectionneurs apprécient cette variante pour sa distinction visuelle unique, sa connexion à la narration de la trilogie des suites et la représentation de la loyauté durable de C-3PO à travers plusieurs générations de conflit galactique.',
    description_es: 'Esta variante de C-3PO presenta un distintivo brazo de reemplazo rojo oscuro, representando la apariencia desigual del droide de protocolo en El Despertar de la Fuerza. Después de décadas de aventuras, C-3PO sufrió daños que requerían piezas de reemplazo de otros droides. El brazo rojo provino de otro droide de protocolo llamado Omri que se sacrificó para ayudar a C-3PO a completar una misión de la Resistencia. Esta variante simboliza el servicio continuo de C-3PO a sus amigos décadas después de la trilogía original, ahora trabajando con la Resistencia contra la Primera Orden. El detalle del brazo desigual muestra la atención de LEGO a las apariencias específicas de personajes de diferentes eras cinematográficas. C-3PO eventualmente reemplazó el brazo con su enchapado dorado estándar, pero esta versión de brazo rojo capturó la atención de los fans durante el marketing de El Despertar de la Fuerza. Los coleccionistas valoran esta variante por su distintiva singularidad visual, conexión con la narrativa de la trilogía de secuelas y representación de la lealtad duradera de C-3PO a través de múltiples generaciones de conflicto galáctico.'
  },
  {
    minifigure_no: 'sw0654',
    name: 'First Order Crew Member (Fleet Engineer / Gunner) - Reddish Brown Head',
    description_en: 'First Order Crew Members served as the technical specialists manning the weapons, engines, and systems aboard Star Destroyers and other capital ships of the resurgent Imperial successor state. This minifigure with reddish brown head represents fleet engineers or gunners in their distinctive black uniforms with red accents. Unlike stormtroopers who served as infantry, crew members operated the sophisticated technology of First Order warships. These specialists maintained turbolaser batteries, coordinated TIE fighter launches, and managed the complex systems of vessels like the Finalizer. The black uniform with red trim distinguished naval crew from army personnel and reflected the First Order\'s militaristic aesthetic inherited from the Galactic Empire. Crew members represented the thousands of personnel required to operate massive Star Destroyers. Collectors value First Order crew for building Star Destroyer bridge and hangar displays, showing the military infrastructure behind the First Order\'s might, and army building nameless technicians.',
    description_de: 'Erste-Ordnung-Besatzungsmitglieder dienten als technische Spezialisten, die die Waffen, Motoren und Systeme an Bord von Sternenzerstörern und anderen Großkampfschiffen des wiedererstarkten imperialen Nachfolgestaates bemannten. Diese Minifigur mit rotbraunem Kopf repräsentiert Flotteningenieure oder Kanoniere in ihren markanten schwarzen Uniformen mit roten Akzenten. Im Gegensatz zu Sturmtrupplern, die als Infanterie dienten, operierten Besatzungsmitglieder die ausgeklügelte Technologie der Kriegsschiffe der Ersten Ordnung. Diese Spezialisten warteten Turbolaser-Batterien, koordinierten TIE-Jäger-Starts und verwalteten die komplexen Systeme von Schiffen wie der Finalizer. Die schwarze Uniform mit rotem Besatz unterschied Marinebesatzung von Armeepersonal und spiegelte die militaristische Ästhetik der Ersten Ordnung wider, die vom Galaktischen Imperium geerbt wurde. Besatzungsmitglieder repräsentierten die Tausende von Personal, die zum Betrieb massiver Sternenzerstörer erforderlich waren. Sammler schätzen Erste-Ordnung-Besatzung für den Aufbau von Sternenzerstörer-Brücken- und Hangar-Displays, die Darstellung der militärischen Infrastruktur hinter der Macht der Ersten Ordnung und Army-Building namenloser Techniker.',
    description_fr: 'Les Membres d\'Équipage du Premier Ordre servaient de spécialistes techniques opérant les armes, moteurs et systèmes à bord des Destroyers Stellaires et autres vaisseaux capitaux de l\'État successeur impérial ressurgent. Cette minifigurine à tête brun rougeâtre représente des ingénieurs de flotte ou des artilleurs dans leurs uniformes noirs distinctifs avec des accents rouges. Contrairement aux stormtroopers qui servaient d\'infanterie, les membres d\'équipage opéraient la technologie sophistiquée des vaisseaux de guerre du Premier Ordre. Ces spécialistes maintenaient les batteries de turbolasers, coordonnaient les lancements de chasseurs TIE et géraient les systèmes complexes de vaisseaux comme le Finalizer. L\'uniforme noir avec garniture rouge distinguait l\'équipage naval du personnel de l\'armée et reflétait l\'esthétique militariste du Premier Ordre héritée de l\'Empire Galactique. Les membres d\'équipage représentaient les milliers de personnel nécessaires pour opérer les Destroyers Stellaires massifs. Les collectionneurs apprécient l\'équipage du Premier Ordre pour construire des displays de pont et de hangar de Destroyer Stellaire, montrer l\'infrastructure militaire derrière la puissance du Premier Ordre et construire des techniciens sans nom.',
    description_es: 'Los Miembros de Tripulación de la Primera Orden servían como especialistas técnicos operando las armas, motores y sistemas a bordo de Destructores Estelares y otras naves capitales del estado sucesor imperial resurgente. Esta minifigura con cabeza marrón rojizo representa a ingenieros de flota o artilleros en sus distintivos uniformes negros con acentos rojos. A diferencia de los stormtroopers que servían como infantería, los miembros de tripulación operaban la tecnología sofisticada de las naves de guerra de la Primera Orden. Estos especialistas mantenían baterías de turboláser, coordinaban lanzamientos de cazas TIE y gestionaban los sistemas complejos de naves como el Finalizer. El uniforme negro con ribete rojo distinguía a la tripulación naval del personal del ejército y reflejaba la estética militarista de la Primera Orden heredada del Imperio Galáctico. Los miembros de tripulación representaban a los miles de personal requeridos para operar Destructores Estelares masivos. Los coleccionistas valoran a la tripulación de la Primera Orden para construir exhibiciones de puente y hangar de Destructores Estelares, mostrar la infraestructura militar detrás del poder de la Primera Orden y construcción de ejércitos de técnicos sin nombre.'
  }
];

async function saveBatch() {
  console.log('Starting batch save for sw0648-sw0654...');

  for (const minifig of batch) {
    try {
      await prisma.minifigCatalog.update({
        where: { minifigure_no: minifig.minifigure_no },
        data: {
          description_en: minifig.description_en,
          description_de: minifig.description_de,
          description_fr: minifig.description_fr,
          description_es: minifig.description_es,
          description_generated_at: new Date(),
          description_status: 'generated'
        },
      });
      console.log(`✓ Saved ${minifig.minifigure_no}: ${minifig.name}`);
    } catch (error) {
      console.error(`✗ Error saving ${minifig.minifigure_no}:`, error);
    }
  }

  console.log('Batch complete! 7 minifigs saved.');
  await prisma.$disconnect();
}

saveBatch();
