import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasources: {
    db: {
      url: process.env.DATABASE_URL,
    },
  },
});

interface MinifigDescription {
  minifigure_no: string;
  description_en: string;
  description_de: string;
  description_fr: string;
  description_es: string;
}

const descriptions: MinifigDescription[] = [
  {
    minifigure_no: 'sw1071',
    description_en: 'Festive Yoda in red Santa jacket represents the beloved Jedi Master celebrating holiday traditions in the Star Wars universe. This whimsical holiday variant brings seasonal cheer to collections with Yoda\'s iconic wisdom wrapped in festive attire. The combination of Jedi mysticism and holiday spirit creates a unique collectible. A fun and limited piece for fans who appreciate holiday-themed Star Wars variants and the enduring charm of Master Yoda.',
    description_de: 'Festlicher Yoda in roter Weihnachtsmann-Jacke repräsentiert den geliebten Jedi-Meister, der Feiertagstraditionen im Star Wars-Universum feiert. Diese verspielte Feiertagsvariante bringt saisonale Freude in Sammlungen mit Yodas ikonischer Weisheit in festlicher Kleidung. Die Kombination aus Jedi-Mystizismus und Feiertagsgeist schafft ein einzigartiges Sammlerstück. Ein unterhaltsames und limitiertes Stück für Fans, die feiertagsthematische Star Wars-Varianten und den anhaltenden Charme von Meister Yoda schätzen.',
    description_fr: 'Le Yoda festif en veste rouge de Père Noël représente le Maître Jedi bien-aimé célébrant les traditions de fêtes dans l\'univers Star Wars. Cette variante festive fantaisiste apporte la joie saisonnière aux collections avec la sagesse iconique de Yoda enveloppée dans une tenue festive. La combinaison de mysticisme Jedi et d\'esprit de fête crée un objet de collection unique. Une pièce amusante et limitée pour les fans qui apprécient les variantes Star Wars sur le thème des fêtes et le charme durable du Maître Yoda.',
    description_es: 'Yoda Festivo en chaqueta roja de Santa representa al amado Maestro Jedi celebrando tradiciones navideñas en el universo Star Wars. Esta caprichosa variante navideña trae alegría estacional a las colecciones con la sabiduría icónica de Yoda envuelta en atuendo festivo. La combinación de misticismo Jedi y espíritu navideño crea un coleccionable único. Una pieza divertida y limitada para fanáticos que aprecian variantes de Star Wars temáticas navideñas y el encanto perdurable del Maestro Yoda.'
  },
  {
    minifigure_no: 'sw1072',
    description_en: 'This Supreme Leader Kylo Ren variant represents Ben Solo at the pinnacle of his dark side authority commanding the First Order. The design captures Kylo\'s conflicted leadership and ultimate power. This version showcases his evolution from apprentice to supreme leader before his eventual redemption. An important character piece for collectors tracking Kylo Ren\'s complete transformation throughout the sequel trilogy.',
    description_de: 'Diese Oberste Führer Kylo Ren-Variante repräsentiert Ben Solo auf dem Höhepunkt seiner dunklen Seiten-Autorität, die die Erste Ordnung befehligt. Das Design erfasst Kylos innerlich zerrissene Führung und ultimative Macht. Diese Version zeigt seine Entwicklung vom Lehrling zum obersten Führer vor seiner eventuellen Erlösung. Ein wichtiges Charakterstück für Sammler, die Kylo Rens vollständige Transformation während der Sequel-Trilogie verfolgen.',
    description_fr: 'Cette variante de Suprême Leader Kylo Ren représente Ben Solo au sommet de son autorité du côté obscur commandant le Premier Ordre. Le design capture le leadership conflictuel et le pouvoir ultime de Kylo. Cette version présente son évolution d\'apprenti à leader suprême avant sa rédemption éventuelle. Une pièce de personnage importante pour les collectionneurs suivant la transformation complète de Kylo Ren tout au long de la trilogie suite.',
    description_es: 'Esta variante de Líder Supremo Kylo Ren representa a Ben Solo en el pináculo de su autoridad del lado oscuro comandando la Primera Orden. El diseño captura el liderazgo en conflicto y poder definitivo de Kylo. Esta versión muestra su evolución de aprendiz a líder supremo antes de su eventual redención. Una pieza de personaje importante para coleccionistas que siguen la transformación completa de Kylo Ren a lo largo de la trilogía secuela.'
  },
  {
    minifigure_no: 'sw1073',
    description_en: 'The T-16 Skyhopper Pilot represents the recreational racing pilots on Tatooine who flew through Beggar\'s Canyon. Luke Skywalker honed his piloting skills on these civilian speeders before joining the Rebellion. The detailed belt printing shows the practical equipment worn by these thrill-seeking pilots. An important character for collectors building Tatooine civilian scenes and understanding Luke\'s background as a skilled pilot.',
    description_de: 'Der T-16 Skyhopper-Pilot repräsentiert die Freizeit-Rennpiloten auf Tatooine, die durch Beggar\'s Canyon flogen. Luke Skywalker schärfte seine Pilotenfähigkeiten auf diesen zivilen Speedern, bevor er sich der Rebellion anschloss. Der detaillierte Gürteldruck zeigt die praktische Ausrüstung, die von diesen nervenkitzelsuchenden Piloten getragen wurde. Ein wichtiger Charakter für Sammler, die Tatooine-Zivilszenen aufbauen und Lukes Hintergrund als geschickter Pilot verstehen.',
    description_fr: 'Le pilote T-16 Skyhopper représente les pilotes de course récréatifs sur Tatooine qui volaient à travers le Canyon du Mendiant. Luke Skywalker a perfectionné ses compétences de pilotage sur ces speeders civils avant de rejoindre la Rébellion. L\'impression détaillée de ceinture montre l\'équipement pratique porté par ces pilotes en quête de sensations fortes. Un personnage important pour les collectionneurs construisant des scènes civiles de Tatooine et comprenant le passé de Luke en tant que pilote qualifié.',
    description_es: 'El piloto de T-16 Skyhopper representa a los pilotos de carreras recreativas en Tatooine que volaban por el Cañón del Mendigo. Luke Skywalker perfeccionó sus habilidades de pilotaje en estos deslizadores civiles antes de unirse a la Rebelión. La impresión detallada del cinturón muestra el equipo práctico usado por estos pilotos buscadores de emociones. Un personaje importante para coleccionistas que construyen escenas civiles de Tatooine y comprenden el trasfondo de Luke como piloto hábil.'
  },
  {
    minifigure_no: 'sw1074',
    description_en: 'This Tusken Raider variant with spiked head wrappings, diagonal belt, and printed legs represents the fierce Sand People of Tatooine. The detailed printing captures the scavenged equipment and traditional garb of these desert nomads. Tusken Raiders remain one of Star Wars\' most iconic and mysterious alien cultures. An enhanced variant for collectors building Tatooine desert scenes and diverse alien warrior displays.',
    description_de: 'Diese Tusken-Räuber-Variante mit bestachelten Kopfumwicklungen, diagonalem Gürtel und bedruckten Beinen repräsentiert die wilden Sandleute von Tatooine. Der detaillierte Druck erfasst die zusammengesammelte Ausrüstung und traditionelle Kleidung dieser Wüstennomaden. Tusken-Räuber bleiben eine der ikonischsten und mysteriösesten außerirdischen Kulturen von Star Wars. Eine verbesserte Variante für Sammler, die Tatooine-Wüstenszenen und vielfältige außerirdische Krieger-Displays aufbauen.',
    description_fr: 'Cette variante de Tusken Raider avec enveloppements de tête à pointes, ceinture diagonale et jambes imprimées représente le féroce Peuple des Sables de Tatooine. L\'impression détaillée capture l\'équipement récupéré et la tenue traditionnelle de ces nomades du désert. Les Tusken Raiders restent l\'une des cultures aliens les plus iconiques et mystérieuses de Star Wars. Une variante améliorée pour les collectionneurs construisant des scènes de désert de Tatooine et diverses présentations de guerriers aliens.',
    description_es: 'Esta variante de Asaltante Tusken con envolturas de cabeza con púas, cinturón diagonal y piernas impresas representa al feroz Pueblo de Arena de Tatooine. La impresión detallada captura el equipo recuperado y atuendo tradicional de estos nómadas del desierto. Los Asaltantes Tusken siguen siendo una de las culturas alienígenas más icónicas y misteriosas de Star Wars. Una variante mejorada para coleccionistas que construyen escenas de desierto de Tatooine y diversas exhibiciones de guerreros alienígenas.'
  },
  {
    minifigure_no: 'sw1075',
    description_en: 'The Sith Jet Trooper represents elite airborne specialists serving Palpatine\'s Final Order fleet equipped with experimental jetpack technology. These crimson-armored soldiers combined aerial superiority with Sith loyalty. The distinctive red armor and flight equipment made them among the most feared Final Order forces. A striking character for collectors building Sith military displays and aerial combat units.',
    description_de: 'Der Sith-Jet-Trooper repräsentiert Elite-Luftspeziallisten, die Palpatines Letzte Ordnung-Flotte dienen, ausgestattet mit experimenteller Jetpack-Technologie. Diese karmesinrot gepanzerten Soldaten kombinierten Luftüberlegenheit mit Sith-Loyalität. Die markante rote Rüstung und Flugausrüstung machten sie zu den gefürchtetsten Kräften der Letzten Ordnung. Ein auffälliger Charakter für Sammler, die Sith-Militärdisplays und Luftkampfeinheiten aufbauen.',
    description_fr: 'Le Sith Jet Trooper représente les spécialistes aéroportés d\'élite servant la flotte de l\'Ordre Final de Palpatine équipés de technologie de jetpack expérimentale. Ces soldats en armure cramoisie combinaient supériorité aérienne et loyauté Sith. L\'armure rouge distinctive et l\'équipement de vol en faisaient parmi les forces de l\'Ordre Final les plus redoutées. Un personnage frappant pour les collectionneurs construisant des présentations militaires Sith et des unités de combat aérien.',
    description_es: 'El Soldado Jet Sith representa especialistas aerotransportados de élite que sirven a la flota de la Orden Final de Palpatine equipados con tecnología experimental de mochila propulsora. Estos soldados con armadura carmesí combinaron superioridad aérea con lealtad Sith. La distintiva armadura roja y equipo de vuelo los convirtieron en las fuerzas más temidas de la Orden Final. Un personaje llamativo para coleccionistas que construyen exhibiciones militares Sith y unidades de combate aéreo.'
  },
  {
    minifigure_no: 'sw1076',
    description_en: 'The Sith Fleet Officer commanded Imperial Star Destroyers and vessels in Palpatine\'s hidden Sith Eternal fleet. These officers maintained the Emperor\'s secret armada on Exegol awaiting the Final Order\'s revelation. The distinctive uniform marks them as elite commanders of the galaxy\'s most powerful fleet. An important character for collectors building Sith fleet command structures and Final Order military hierarchy displays.',
    description_de: 'Der Sith-Flottenoffizier befehligte Imperiale Sternzerstörer und Schiffe in Palpatines versteckter Sith-Eternal-Flotte. Diese Offiziere erhielten die geheime Armada des Imperators auf Exegol aufrecht und erwarteten die Enthüllung der Letzten Ordnung. Die markante Uniform kennzeichnet sie als Elite-Kommandanten der mächtigsten Flotte der Galaxis. Ein wichtiger Charakter für Sammler, die Sith-Flottenkommandostrukturen und militärische Hierarchie-Displays der Letzten Ordnung aufbauen.',
    description_fr: 'L\'officier de flotte Sith commandait les Star Destroyers impériaux et les vaisseaux de la flotte Sith Éternelle cachée de Palpatine. Ces officiers maintenaient l\'armada secrète de l\'Empereur sur Exegol en attendant la révélation de l\'Ordre Final. L\'uniforme distinctif les marque comme des commandants d\'élite de la flotte la plus puissante de la galaxie. Un personnage important pour les collectionneurs construisant des structures de commandement de flotte Sith et des présentations de hiérarchie militaire de l\'Ordre Final.',
    description_es: 'El Oficial de Flota Sith comandaba Destructores Estelares Imperiales y naves en la flota Sith Eterna oculta de Palpatine. Estos oficiales mantuvieron la armada secreta del Emperador en Exegol esperando la revelación de la Orden Final. El uniforme distintivo los marca como comandantes de élite de la flota más poderosa de la galaxia. Un personaje importante para coleccionistas que construyen estructuras de comando de flota Sith y exhibiciones de jerarquía militar de la Orden Final.'
  },
  {
    minifigure_no: 'sw1077',
    description_en: 'This female Mandalorian Tribe Warrior with black cape and light bluish gray helmet represents the diverse members of Din Djarin\'s covert. These warriors maintained ancient Mandalorian traditions in hiding. The distinctive helmet with antenna and rangefinder shows specialized combat equipment. An important character for collectors building the complete Mandalorian covert and honoring the warrior culture.',
    description_de: 'Diese weibliche Mandalorianer-Stammeskriegerin mit schwarzem Umhang und hellbläulich-grauem Helm repräsentiert die vielfältigen Mitglieder von Din Djarins Geheimbund. Diese Krieger erhielten alte mandalorianische Traditionen im Versteckten aufrecht. Der markante Helm mit Antenne und Entfernungsmesser zeigt spezialisierte Kampfausrüstung. Ein wichtiger Charakter für Sammler, die den vollständigen mandalorianischen Geheimbund aufbauen und die Kriegerkultur ehren.',
    description_fr: 'Cette guerrière de tribu mandalorienne avec cape noire et casque gris bleu clair représente les divers membres du couvent de Din Djarin. Ces guerriers maintenaient d\'anciennes traditions mandaloréennes dans la clandestinité. Le casque distinctif avec antenne et télémètre montre un équipement de combat spécialisé. Un personnage important pour les collectionneurs construisant le couvent mandaloréen complet et honorant la culture guerrière.',
    description_es: 'Esta guerrera de tribu Mandaloriana con capa negra y casco gris azulado claro representa a los diversos miembros del encubierto de Din Djarin. Estos guerreros mantuvieron antiguas tradiciones Mandalorianas en ocultación. El distintivo casco con antena y telémetro muestra equipo de combate especializado. Un personaje importante para coleccionistas que construyen el encubierto Mandaloriano completo y honran la cultura guerrera.'
  },
  {
    minifigure_no: 'sw1078',
    description_en: 'This female Mandalorian Tribe Warrior with dark brown cape and green helmet adds diversity to the hidden covert. Each warrior\'s unique armor colors reflect their individual identity within the collective. The green helmet with antenna shows the varied equipment configurations used by covert members. A collectible character for building the complete Mandalorian tribe and diverse warrior displays.',
    description_de: 'Diese weibliche Mandalorianer-Stammeskriegerin mit dunkelbraunem Umhang und grünem Helm fügt dem versteckten Geheimbund Vielfalt hinzu. Die einzigartigen Rüstungsfarben jedes Kriegers spiegeln ihre individuelle Identität innerhalb des Kollektivs wider. Der grüne Helm mit Antenne zeigt die vielfältigen Ausrüstungskonfigurationen, die von Geheimbundmitgliedern verwendet werden. Ein sammelbarer Charakter für den Bau des vollständigen mandalorianischen Stammes und vielfältiger Krieger-Displays.',
    description_fr: 'Cette guerrière de tribu mandalorienne avec cape brun foncé et casque vert ajoute de la diversité au couvent caché. Les couleurs d\'armure uniques de chaque guerrier reflètent leur identité individuelle au sein du collectif. Le casque vert avec antenne montre les configurations d\'équipement variées utilisées par les membres du couvent. Un personnage collectionnable pour construire la tribu mandalorienne complète et diverses présentations de guerriers.',
    description_es: 'Esta guerrera de tribu Mandaloriana con capa marrón oscuro y casco verde añade diversidad al encubierto oculto. Los colores únicos de armadura de cada guerrero reflejan su identidad individual dentro del colectivo. El casco verde con antena muestra las configuraciones de equipo variadas usadas por miembros del encubierto. Un personaje coleccionable para construir la tribu Mandaloriana completa y diversas exhibiciones de guerreros.'
  },
  {
    minifigure_no: 'sw1079',
    description_en: 'This male Mandalorian Tribe Warrior with dark brown cape and dark orange helmet represents another member of the hidden covert. The distinctive armor coloring reflects individual warrior heritage and specialization. These warriors lived by the ancient Mandalorian code while protecting their secrecy. A character piece for collectors building the diverse Mandalorian tribe and understanding their warrior society.',
    description_de: 'Dieser männliche Mandalorianer-Stammeskrieger mit dunkelbraunem Umhang und dunkelorangefarbenem Helm repräsentiert ein weiteres Mitglied des versteckten Geheimbundes. Die markante Rüstungsfärbung spiegelt individuelles Kriegererbe und Spezialisierung wider. Diese Krieger lebten nach dem alten mandalorianischen Kodex, während sie ihre Geheimhaltung schützten. Ein Charakterstück für Sammler, die den vielfältigen mandalorianischen Stamm aufbauen und ihre Kriegergesellschaft verstehen.',
    description_fr: 'Ce guerrier de tribu mandalorien avec cape brun foncé et casque orange foncé représente un autre membre du couvent caché. La coloration d\'armure distinctive reflète l\'héritage et la spécialisation individuels du guerrier. Ces guerriers vivaient selon l\'ancien code mandaloréen tout en protégeant leur secret. Une pièce de personnage pour les collectionneurs construisant la tribu mandalorienne diversifiée et comprenant leur société guerrière.',
    description_es: 'Este guerrero de tribu Mandaloriano con capa marrón oscuro y casco naranja oscuro representa otro miembro del encubierto oculto. La coloración distintiva de armadura refleja herencia y especialización individual del guerrero. Estos guerreros vivieron según el antiguo código Mandaloriano mientras protegían su secreto. Una pieza de personaje para coleccionistas que construyen la diversa tribu Mandaloriana y comprenden su sociedad guerrera.'
  },
  {
    minifigure_no: 'sw1080',
    description_en: 'This male Mandalorian Tribe Warrior with olive green cape and dark azure helmet adds further diversity to the covert. The striking blue armor represents the varied backgrounds of warriors who found refuge in the hidden tribe. Each member\'s unique appearance while maintaining traditional Mandalorian values shows the culture\'s balance of individuality and unity. A collectible character for completing the diverse Mandalorian covert roster.',
    description_de: 'Dieser männliche Mandalorianer-Stammeskrieger mit olivgrünem Umhang und dunkelazurblauem Helm fügt dem Geheimbund weitere Vielfalt hinzu. Die auffällige blaue Rüstung repräsentiert die vielfältigen Hintergründe von Kriegern, die Zuflucht im versteckten Stamm fanden. Das einzigartige Erscheinungsbild jedes Mitglieds bei gleichzeitiger Beibehaltung traditioneller mandalorianischer Werte zeigt das Gleichgewicht der Kultur zwischen Individualität und Einheit. Ein sammelbarer Charakter für die Vervollständigung der vielfältigen mandalorianischen Geheimbund-Aufstellung.',
    description_fr: 'Ce guerrier de tribu mandalorien avec cape vert olive et casque bleu azur foncé ajoute une diversité supplémentaire au couvent. L\'armure bleue frappante représente les origines variées des guerriers qui ont trouvé refuge dans la tribu cachée. L\'apparence unique de chaque membre tout en maintenant les valeurs mandaloréennes traditionnelles montre l\'équilibre de la culture entre individualité et unité. Un personnage collectionnable pour compléter la liste diversifiée du couvent mandaloréen.',
    description_es: 'Este guerrero de tribu Mandaloriano con capa verde oliva y casco azul oscuro añade mayor diversidad al encubierto. La llamativa armadura azul representa los variados trasfondos de guerreros que encontraron refugio en la tribu oculta. La apariencia única de cada miembro mientras mantiene valores Mandalorianos tradicionales muestra el equilibrio de la cultura entre individualidad y unidad. Un personaje coleccionable para completar la lista diversa del encubierto Mandaloriano.'
  },
  {
    minifigure_no: 'sw1081',
    description_en: 'Wedge Antilles with printed legs and three bullets represents the legendary Rebel pilot and Red Squadron member who survived both Death Star battles. This enhanced variant captures Wedge\'s appearance with detailed equipment printing. His consistent bravery and skill made him one of the Rebellion\'s most decorated pilots. An important character for collectors building complete Red Squadron rosters and honoring the Rebellion\'s ace pilots.',
    description_de: 'Wedge Antilles mit bedruckten Beinen und drei Kugeln repräsentiert den legendären Rebellen-Piloten und Rotes Geschwader-Mitglied, der beide Todesstern-Schlachten überlebte. Diese verbesserte Variante erfasst Wedges Erscheinungsbild mit detailliertem Ausrüstungsdruck. Sein beständiger Mut und seine Fähigkeiten machten ihn zu einem der meist ausgezeichneten Piloten der Rebellion. Ein wichtiger Charakter für Sammler, die vollständige Rotes Geschwader-Aufstellungen aufbauen und die Ass-Piloten der Rebellion ehren.',
    description_fr: 'Wedge Antilles avec jambes imprimées et trois balles représente le pilote rebelle légendaire et membre de l\'Escadron Rouge qui a survécu aux deux batailles de l\'Étoile de la Mort. Cette variante améliorée capture l\'apparence de Wedge avec une impression d\'équipement détaillée. Son courage et ses compétences constants en ont fait l\'un des pilotes les plus décorés de la Rébellion. Un personnage important pour les collectionneurs construisant des listes complètes de l\'Escadron Rouge et honorant les pilotes as de la Rébellion.',
    description_es: 'Wedge Antilles con piernas impresas y tres balas representa al legendario piloto rebelde y miembro del Escuadrón Rojo que sobrevivió ambas batallas de la Estrella de la Muerte. Esta variante mejorada captura la apariencia de Wedge con impresión de equipo detallada. Su valentía y habilidad consistentes lo convirtieron en uno de los pilotos más condecorados de la Rebelión. Un personaje importante para coleccionistas que construyen listas completas del Escuadrón Rojo y honran a los pilotos as de la Rebelión.'
  },
  {
    minifigure_no: 'sw1082',
    description_en: 'Obi-Wan Kenobi with dirt stains captures the Jedi Master during intense combat on various battlefields throughout the Clone Wars. The weathered appearance reflects the harsh realities of war and constant fighting. This battle-worn variant shows Obi-Wan\'s dedication to the front lines despite being a Jedi General. A realistic character piece for collectors building Clone Wars battle scenes and action-oriented displays.',
    description_de: 'Obi-Wan Kenobi mit Schmutzflecken erfasst den Jedi-Meister während intensiver Kämpfe auf verschiedenen Schlachtfeldern während der Klonkriege. Das verwitterte Erscheinungsbild spiegelt die harten Realitäten des Krieges und ständigen Kämpfens wider. Diese kampferprobte Variante zeigt Obi-Wans Hingabe an die Frontlinien, obwohl er ein Jedi-General ist. Ein realistisches Charakterstück für Sammler, die Klonkrieg-Kampfszenen und aktionsorientierte Displays aufbauen.',
    description_fr: 'Obi-Wan Kenobi avec taches de saleté capture le Maître Jedi lors de combats intenses sur divers champs de bataille tout au long de la Guerre des Clones. L\'apparence altérée reflète les dures réalités de la guerre et des combats constants. Cette variante usée par le combat montre le dévouement d\'Obi-Wan aux lignes de front malgré être un Général Jedi. Une pièce de personnage réaliste pour les collectionneurs construisant des scènes de bataille de la Guerre des Clones et des présentations orientées action.',
    description_es: 'Obi-Wan Kenobi con manchas de suciedad captura al Maestro Jedi durante combate intenso en varios campos de batalla a lo largo de las Guerras Clon. La apariencia desgastada refleja las duras realidades de la guerra y lucha constante. Esta variante desgastada por batalla muestra la dedicación de Obi-Wan a las líneas del frente a pesar de ser un General Jedi. Una pieza de personaje realista para coleccionistas que construyen escenas de batalla de las Guerras Clon y exhibiciones orientadas a la acción.'
  },
  {
    minifigure_no: 'sw1083',
    description_en: 'Anakin Skywalker with dirt stains represents the warrior Jedi during brutal Clone Wars campaigns. The battle-worn appearance shows Anakin\'s aggressive combat style and frequent exposure to danger. This variant captures his evolution from Padawan to war-hardened general. A dynamic character piece for collectors building intense battle scenes and tracking Anakin\'s journey toward the dark side.',
    description_de: 'Anakin Skywalker mit Schmutzflecken repräsentiert den Krieger-Jedi während brutaler Klonkrieg-Kampagnen. Das kampferprobte Erscheinungsbild zeigt Anakins aggressiven Kampfstil und häufige Gefährdung. Diese Variante erfasst seine Entwicklung vom Padawan zum kriegsgehärteten General. Ein dynamisches Charakterstück für Sammler, die intensive Kampfszenen aufbauen und Anakins Reise zur dunklen Seite verfolgen.',
    description_fr: 'Anakin Skywalker avec taches de saleté représente le Jedi guerrier lors de campagnes brutales de la Guerre des Clones. L\'apparence usée par le combat montre le style de combat agressif d\'Anakin et l\'exposition fréquente au danger. Cette variante capture son évolution de Padawan à général endurci par la guerre. Une pièce de personnage dynamique pour les collectionneurs construisant des scènes de bataille intenses et suivant le voyage d\'Anakin vers le côté obscur.',
    description_es: 'Anakin Skywalker con manchas de suciedad representa al Jedi guerrero durante brutales campañas de las Guerras Clon. La apariencia desgastada por batalla muestra el estilo de combate agresivo de Anakin y exposición frecuente al peligro. Esta variante captura su evolución de Padawan a general endurecido por la guerra. Una pieza de personaje dinámica para coleccionistas que construyen escenas de batalla intensas y siguen el viaje de Anakin hacia el lado oscuro.'
  },
  {
    minifigure_no: 'sw1084',
    description_en: 'Old Obi-Wan Kenobi with light bluish gray hair and white-highlighted beard represents the aged Jedi Master during his Tatooine exile. The distinguished silver hair shows decades of solitary meditation and waiting. This variant captures Ben Kenobi\'s wisdom and patience as he watched over young Luke. A premium character piece for collectors building the hermit years and honoring Obi-Wan\'s complete life journey.',
    description_de: 'Der alte Obi-Wan Kenobi mit hellbläulich-grauem Haar und weiß-hervorgehobenem Bart repräsentiert den gealterten Jedi-Meister während seines Tatooine-Exils. Das vornehme silberne Haar zeigt Jahrzehnte einsamer Meditation und Wartens. Diese Variante erfasst Ben Kenobis Weisheit und Geduld, als er den jungen Luke beobachtete. Ein Premium-Charakterstück für Sammler, die die Einsiedlerjahre aufbauen und Obi-Wans vollständige Lebensreise ehren.',
    description_fr: 'Le vieux Obi-Wan Kenobi avec cheveux gris bleu clair et barbe mise en valeur de blanc représente le Maître Jedi vieilli pendant son exil sur Tatooine. Les cheveux argentés distingués montrent des décennies de méditation solitaire et d\'attente. Cette variante capture la sagesse et la patience de Ben Kenobi alors qu\'il veillait sur le jeune Luke. Une pièce de personnage premium pour les collectionneurs construisant les années d\'ermite et honorant le parcours de vie complet d\'Obi-Wan.',
    description_es: 'El viejo Obi-Wan Kenobi con cabello gris azulado claro y barba resaltada en blanco representa al envejecido Maestro Jedi durante su exilio en Tatooine. El distinguido cabello plateado muestra décadas de meditación solitaria y espera. Esta variante captura la sabiduría y paciencia de Ben Kenobi mientras vigilaba al joven Luke. Una pieza de personaje premium para coleccionistas que construyen los años de ermitaño y honran el viaje de vida completo de Obi-Wan.'
  },
  {
    minifigure_no: 'sw1085',
    description_en: 'This R2-D2 variant with flat silver head and dark pink dots represents a unique color scheme for the beloved astromech droid. The large receptor and distinctive coloring may indicate special commemorative or promotional edition. R2-D2\'s iconic design allows for creative variants while maintaining instant recognizability. A collectible droid variant for fans of special edition releases and R2-D2\'s enduring legacy.',
    description_de: 'Diese R2-D2-Variante mit flachem Silberkopf und dunkelpinken Punkten repräsentiert ein einzigartiges Farbschema für die geliebte Astromech-Droide. Der große Rezeptor und die markante Färbung können auf eine spezielle Gedenk- oder Werbeausgabe hinweisen. R2-D2s ikonisches Design ermöglicht kreative Varianten bei gleichzeitiger Beibehaltung sofortiger Erkennbarkeit. Eine sammelbare Droiden-Variante für Fans von Sonderausgaben und R2-D2s anhaltendem Erbe.',
    description_fr: 'Cette variante de R2-D2 avec tête argentée plate et points rose foncé représente un schéma de couleurs unique pour le droïde astromech bien-aimé. Le grand récepteur et la coloration distinctive peuvent indiquer une édition commémorative ou promotionnelle spéciale. Le design iconique de R2-D2 permet des variantes créatives tout en maintenant une reconnaissance instantanée. Une variante de droïde collectionnable pour les fans de sorties en édition spéciale et de l\'héritage durable de R2-D2.',
    description_es: 'Esta variante de R2-D2 con cabeza plateada plana y puntos rosa oscuro representa un esquema de color único para el amado droide astromecánico. El gran receptor y coloración distintiva pueden indicar edición conmemorativa o promocional especial. El diseño icónico de R2-D2 permite variantes creativas mientras mantiene reconocimiento instantáneo. Una variante de droide coleccionable para fanáticos de lanzamientos de edición especial y el legado perdurable de R2-D2.'
  },
  {
    minifigure_no: 'sw1086',
    description_en: 'Luke Skywalker in poncho represents the Jedi during his undercover mission to Jabba\'s Palace on Tatooine. This disguised appearance allowed Luke to infiltrate the crime lord\'s fortress to rescue Han Solo. The simple poncho conceals Luke\'s identity and lightsaber until the dramatic reveal. An iconic costume variant for collectors building the Jabba\'s Palace rescue mission and Return of the Jedi opening scenes.',
    description_de: 'Luke Skywalker im Poncho repräsentiert den Jedi während seiner verdeckten Mission zu Jabbas Palast auf Tatooine. Dieses getarnte Erscheinungsbild ermöglichte es Luke, die Festung des Verbrecher-Lords zu infiltrieren, um Han Solo zu retten. Der einfache Poncho verbirgt Lukes Identität und Lichtschwert bis zur dramatischen Enthüllung. Eine ikonische Kostümvariante für Sammler, die die Jabbas Palast-Rettungsmission und Die Rückkehr der Jedi-Eröffnungsszenen aufbauen.',
    description_fr: 'Luke Skywalker en poncho représente le Jedi lors de sa mission d\'infiltration au Palais de Jabba sur Tatooine. Cette apparence déguisée a permis à Luke d\'infiltrer la forteresse du seigneur du crime pour sauver Han Solo. Le simple poncho cache l\'identité et le sabre laser de Luke jusqu\'à la révélation dramatique. Une variante de costume iconique pour les collectionneurs construisant la mission de sauvetage du Palais de Jabba et les scènes d\'ouverture du Retour du Jedi.',
    description_es: 'Luke Skywalker en poncho representa al Jedi durante su misión encubierta al Palacio de Jabba en Tatooine. Esta apariencia disfrazada permitió a Luke infiltrarse en la fortaleza del señor del crimen para rescatar a Han Solo. El simple poncho oculta la identidad y sable de luz de Luke hasta la revelación dramática. Una variante de vestuario icónica para coleccionistas que construyen la misión de rescate del Palacio de Jabba y escenas de apertura de El Retorno del Jedi.'
  },
  {
    minifigure_no: 'sw1087',
    description_en: 'Trudgen is one of the Knights of Ren, wielding a distinctive heavy blade weapon and wearing battle-scarred armor. Each Knight\'s unique appearance and fighting style contributed to their fearsome reputation. These dark warriors represented Kylo Ren\'s personal enforcers and connection to ancient dark side traditions. A collectible character for completing the Knights of Ren roster and sequel trilogy villain collections.',
    description_de: 'Trudgen ist einer der Ritter von Ren und führt eine markante schwere Klingenwaffe und trägt kampfvernarbte Rüstung. Das einzigartige Erscheinungsbild und der Kampfstil jedes Ritters trugen zu ihrem furchterregenden Ruf bei. Diese dunklen Krieger repräsentierten Kylo Rens persönliche Vollstrecker und Verbindung zu alten dunklen Seiten-Traditionen. Ein sammelbarer Charakter für die Vervollständigung der Ritter von Ren-Aufstellung und Sequel-Trilogie-Schurken-Sammlungen.',
    description_fr: 'Trudgen est l\'un des Chevaliers de Ren, maniant une arme à lame lourde distinctive et portant une armure marquée par le combat. L\'apparence unique et le style de combat de chaque Chevalier ont contribué à leur réputation redoutable. Ces guerriers obscurs représentaient les exécuteurs personnels de Kylo Ren et la connexion aux anciennes traditions du côté obscur. Un personnage collectionnable pour compléter la liste des Chevaliers de Ren et les collections de méchants de la trilogie suite.',
    description_es: 'Trudgen es uno de los Caballeros de Ren, empuñando un arma de cuchilla pesada distintiva y usando armadura marcada por batalla. La apariencia única y estilo de lucha de cada Caballero contribuyó a su reputación temible. Estos guerreros oscuros representaron los ejecutores personales de Kylo Ren y conexión con antiguas tradiciones del lado oscuro. Un personaje coleccionable para completar la lista de Caballeros de Ren y colecciones de villanos de la trilogía secuela.'
  },
  {
    minifigure_no: 'sw1088',
    description_en: 'Jannah is the former First Order stormtrooper who defected and led a community of liberated soldiers in The Rise of Skywalker. This brave warrior connected with Finn over their shared experience leaving the First Order. Her archery skills and leadership made her valuable to the Resistance. A notable character for collectors of sequel trilogy heroes and stories of redemption and freedom.',
    description_de: 'Jannah ist die ehemalige Erste Ordnung-Stormtrooper, die überlief und eine Gemeinschaft befreiter Soldaten in Der Aufstieg Skywalkers anführte. Diese mutige Kriegerin verband sich mit Finn über ihre gemeinsame Erfahrung, die Erste Ordnung zu verlassen. Ihre Bogenschießkünste und Führung machten sie für den Widerstand wertvoll. Ein bemerkenswerter Charakter für Sammler von Sequel-Trilogie-Helden und Geschichten von Erlösung und Freiheit.',
    description_fr: 'Jannah est l\'ancienne stormtrooper du Premier Ordre qui a fait défection et dirigé une communauté de soldats libérés dans L\'Ascension de Skywalker. Cette guerrière courageuse s\'est connectée avec Finn sur leur expérience partagée de quitter le Premier Ordre. Ses compétences en tir à l\'arc et son leadership l\'ont rendue précieuse pour la Résistance. Un personnage notable pour les collectionneurs de héros de la trilogie suite et d\'histoires de rédemption et de liberté.',
    description_es: 'Jannah es la ex stormtrooper de la Primera Orden que desertó y lideró una comunidad de soldados liberados en El Ascenso de Skywalker. Esta valiente guerrera conectó con Finn por su experiencia compartida de dejar la Primera Orden. Sus habilidades de tiro con arco y liderazgo la hicieron valiosa para la Resistencia. Un personaje notable para coleccionistas de héroes de la trilogía secuela e historias de redención y libertad.'
  },
  {
    minifigure_no: 'sw1089',
    description_en: 'Vicrul is another Knight of Ren, known for his aggressive fighting style and distinctive weaponry. Each Knight brought unique combat specializations to Kylo Ren\'s elite force. These mysterious warriors added depth to the dark side mythology beyond the Sith. A collectible character for completing the Knights of Ren set and building sequel trilogy dark side warrior displays.',
    description_de: 'Vicrul ist ein weiterer Ritter von Ren, bekannt für seinen aggressiven Kampfstil und markante Bewaffnung. Jeder Ritter brachte einzigartige Kampfspezialisierungen in Kylo Rens Elite-Truppe. Diese mysteriösen Krieger fügten der dunklen Seiten-Mythologie jenseits der Sith Tiefe hinzu. Ein sammelbarer Charakter für die Vervollständigung des Ritter von Ren-Sets und den Bau von Sequel-Trilogie-Dunkle-Seiten-Krieger-Displays.',
    description_fr: 'Vicrul est un autre Chevalier de Ren, connu pour son style de combat agressif et son armement distinctif. Chaque Chevalier apportait des spécialisations de combat uniques à la force d\'élite de Kylo Ren. Ces guerriers mystérieux ont ajouté de la profondeur à la mythologie du côté obscur au-delà des Sith. Un personnage collectionnable pour compléter l\'ensemble des Chevaliers de Ren et construire des présentations de guerriers du côté obscur de la trilogie suite.',
    description_es: 'Vicrul es otro Caballero de Ren, conocido por su estilo de lucha agresivo y armamento distintivo. Cada Caballero aportó especializaciones de combate únicas a la fuerza de élite de Kylo Ren. Estos misteriosos guerreros añadieron profundidad a la mitología del lado oscuro más allá de los Sith. Un personaje coleccionable para completar el set de Caballeros de Ren y construir exhibiciones de guerreros del lado oscuro de la trilogía secuela.'
  },
  {
    minifigure_no: 'sw1090',
    description_en: 'This Clone Trooper with large blue eyes represents Phase 1 armor during the early Clone Wars campaigns. The distinctive eye printing adds personality and humanity to the clone soldiers. These brave troopers served the Republic with unwavering loyalty before Order 66. A character-focused variant for collectors building diverse clone trooper displays and honoring the soldiers of the Grand Army.',
    description_de: 'Dieser Klontrooper mit großen blauen Augen repräsentiert Phase-1-Rüstung während der frühen Klonkrieg-Kampagnen. Der markante Augendruck verleiht den Klonsoldaten Persönlichkeit und Menschlichkeit. Diese mutigen Trooper dienten der Republik mit unerschütterlicher Loyalität vor Befehl 66. Eine charakterfokussierte Variante für Sammler, die vielfältige Klontrooper-Displays aufbauen und die Soldaten der Großen Armee ehren.',
    description_fr: 'Ce Clone Trooper avec de grands yeux bleus représente l\'armure de Phase 1 lors des premières campagnes de la Guerre des Clones. L\'impression distinctive des yeux ajoute de la personnalité et de l\'humanité aux soldats clones. Ces soldats courageux ont servi la République avec une loyauté inébranlable avant l\'Ordre 66. Une variante centrée sur le personnage pour les collectionneurs construisant diverses présentations de soldats clones et honorant les soldats de la Grande Armée.',
    description_es: 'Este Soldado Clon con grandes ojos azules representa armadura de Fase 1 durante las primeras campañas de las Guerras Clon. La distintiva impresión de ojos añade personalidad y humanidad a los soldados clones. Estos valientes soldados sirvieron a la República con lealtad inquebrantable antes de la Orden 66. Una variante centrada en el personaje para coleccionistas que construyen diversas exhibiciones de soldados clones y honran a los soldados del Gran Ejército.'
  }
];

async function main() {
  console.log('Starting batch save for sw1071-sw1090...');

  for (const desc of descriptions) {
    await prisma.minifigCatalog.update({
      where: { minifigure_no: desc.minifigure_no },
      data: {
        description_en: desc.description_en,
        description_de: desc.description_de,
        description_fr: desc.description_fr,
        description_es: desc.description_es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`✓ Saved ${desc.minifigure_no}: ${descriptions.find(d => d.minifigure_no === desc.minifigure_no)?.minifigure_no}`);
  }

  console.log(`Batch complete! ${descriptions.length} minifigs saved (sw1071-sw1090).`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
