import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0483',
    name: 'Ree-Yees',
    en: 'Ree-Yees is a three-eyed Gran criminal and smuggler who became one of Jabba the Hutt\'s henchmen at his palace on Tatooine. The Gran species is characterized by their distinctive three eyestalks protruding from their heads, giving them exceptional peripheral vision. In Return of the Jedi, Ree-Yees appears as part of Jabba\'s motley crew of bounty hunters, criminals, and hangers-on who populated the crime lord\'s desert fortress. The minifigure captures his unique alien physiology with detailed printing showing his triple-eyed appearance and distinctive facial features. Jabba\'s Palace inhabitants are beloved by collectors for their bizarre and memorable character designs that expanded the Star Wars galaxy\'s visual diversity. Released around 2013 in Jabba\'s Palace-themed sets, Ree-Yees represents the colorful criminal underworld that surrounded the notorious Hutt gangster. For collectors building complete Jabba\'s Palace displays, this distinctive alien is an essential character from one of Star Wars\' most iconic locations.',
    de: 'Ree-Yees ist ein dreiäugiger Gran-Krimineller und Schmuggler, der einer von Jabba dem Hutts Handlangern in seinem Palast auf Tatooine wurde. Die Gran-Spezies zeichnet sich durch ihre charakteristischen drei Augenstiele aus, die aus ihren Köpfen ragen und ihnen außergewöhnliches peripheres Sehen verleihen. In Die Rückkehr der Jedi-Ritter erscheint Ree-Yees als Teil von Jabbas bunt zusammengewürfelter Crew aus Kopfgeldjägern, Kriminellen und Mitläufern, die die Wüstenfestung des Verbrecherlords bevölkerten. Die Minifigur fängt seine einzigartige außerirdische Physiologie mit detaillierter Bedruckung ein, die sein dreiäugiges Aussehen und charakteristische Gesichtszüge zeigt. Jabbas Palast-Bewohner sind bei Sammlern beliebt für ihre bizarren und unvergesslichen Charakterdesigns, die die visuelle Vielfalt der Star Wars-Galaxie erweiterten. Veröffentlicht um 2013 in Jabbas Palast-thematischen Sets, repräsentiert Ree-Yees die farbenfrohe kriminelle Unterwelt, die den berüchtigten Hutt-Gangster umgab. Für Sammler, die vollständige Jabbas Palast-Displays bauen, ist dieser charakteristische Außerirdische ein unverzichtbarer Charakter aus einer der ikonischsten Star Wars-Locations.',
    fr: 'Ree-Yees est un criminel et contrebandier Gran à trois yeux qui est devenu l\'un des hommes de main de Jabba le Hutt dans son palais sur Tatooine. L\'espèce Gran est caractérisée par leurs trois tiges oculaires distinctives sortant de leurs têtes, leur donnant une vision périphérique exceptionnelle. Dans Le Retour du Jedi, Ree-Yees apparaît comme partie de l\'équipage hétéroclite de Jabba composé de chasseurs de primes, criminels et suiveurs qui peuplaient la forteresse désertique du seigneur du crime. La minifigurine capture sa physiologie extraterrestre unique avec une impression détaillée montrant son apparence à trois yeux et traits faciaux distinctifs. Les habitants du Palais de Jabba sont aimés par les collectionneurs pour leurs designs de personnages bizarres et mémorables qui ont élargi la diversité visuelle de la galaxie Star Wars. Sortie vers 2013 dans des ensembles sur le thème du Palais de Jabba, Ree-Yees représente la pègre criminelle colorée qui entourait le gangster Hutt notoire. Pour les collectionneurs construisant des affichages complets du Palais de Jabba, cet extraterrestre distinctif est un personnage essentiel d\'un des lieux les plus iconiques de Star Wars.',
    es: 'Ree-Yees es un criminal y contrabandista Gran de tres ojos que se convirtió en uno de los secuaces de Jabba el Hutt en su palacio en Tatooine. La especie Gran se caracteriza por sus distintivos tres tallos oculares que sobresalen de sus cabezas, dándoles una visión periférica excepcional. En El Retorno del Jedi, Ree-Yees aparece como parte de la variopinta tripulación de Jabba de cazarrecompensas, criminales y parásitos que poblaban la fortaleza desértica del señor del crimen. La minifigura captura su fisiología alienígena única con impresión detallada que muestra su apariencia de tres ojos y rasgos faciales distintivos. Los habitantes del Palacio de Jabba son amados por los coleccionistas por sus diseños de personajes extraños y memorables que expandieron la diversidad visual de la galaxia Star Wars. Lanzada alrededor de 2013 en sets temáticos del Palacio de Jabba, Ree-Yees representa el colorido submundo criminal que rodeaba al notorio gánster Hutt. Para los coleccionistas que construyen exhibiciones completas del Palacio de Jabba, este alienígena distintivo es un personaje esencial de una de las ubicaciones más icónicas de Star Wars.',
  },
  {
    no: 'sw0485',
    name: 'Princess Leia - Jabba Slave Outfit, Dark Brown Long Braid, Neck Bracket',
    en: 'This Princess Leia minifigure depicts one of the most iconic and controversial costume moments from Return of the Jedi, when she was captured and enslaved by Jabba the Hutt. The dark brown long braid represents her hairstyle during this sequence, different from her typical side buns. The neck bracket is a specialized LEGO element representing the chain that bound her to Jabba\'s throne platform. Despite the demeaning circumstances, this scene became pivotal as Leia ultimately used that very chain to strangle and kill Jabba, demonstrating her strength and resourcefulness. The costume has become one of the most recognizable outfits in science fiction cinema history. Released around 2013 in Jabba\'s Palace sets, this minifigure is highly sought after by collectors for its connection to a memorable Star Wars moment. The design captures both the vulnerability of Leia\'s captivity and the strength she displayed in her ultimate revenge against her captor.',
    de: 'Diese Prinzessin Leia-Minifigur zeigt einen der ikonischsten und kontroversesten Kostümmomente aus Die Rückkehr der Jedi-Ritter, als sie von Jabba dem Hutt gefangen genommen und versklavt wurde. Der dunkelbraune lange Zopf repräsentiert ihre Frisur während dieser Sequenz, anders als ihre typischen Seitenzöpfe. Das Halsbracket ist ein spezialisiertes LEGO-Element, das die Kette repräsentiert, die sie an Jabbas Thronplattform fesselte. Trotz der erniedrigenden Umstände wurde diese Szene entscheidend, als Leia letztendlich genau diese Kette benutzte, um Jabba zu erwürgen und zu töten, was ihre Stärke und Findigkeit demonstrierte. Das Kostüm ist zu einem der erkennbarsten Outfits in der Science-Fiction-Kinogeschichte geworden. Veröffentlicht um 2013 in Jabbas Palast-Sets, ist diese Minifigur bei Sammlern sehr begehrt für ihre Verbindung zu einem unvergesslichen Star Wars-Moment. Das Design fängt sowohl die Verletzlichkeit von Leias Gefangenschaft als auch die Stärke ein, die sie bei ihrer ultimativen Rache an ihrem Entführer zeigte.',
    fr: 'Cette minifigurine Princesse Leia représente l\'un des moments de costume les plus iconiques et controversés du Retour du Jedi, lorsqu\'elle a été capturée et réduite en esclavage par Jabba le Hutt. La longue tresse brun foncé représente sa coiffure pendant cette séquence, différente de ses chignons latéraux typiques. Le support de cou est un élément LEGO spécialisé représentant la chaîne qui l\'attachait à la plateforme du trône de Jabba. Malgré les circonstances dégradantes, cette scène est devenue cruciale car Leia a finalement utilisé cette même chaîne pour étrangler et tuer Jabba, démontrant sa force et son ingéniosité. Le costume est devenu l\'une des tenues les plus reconnaissables de l\'histoire du cinéma de science-fiction. Sortie vers 2013 dans les ensembles du Palais de Jabba, cette minifigurine est très recherchée par les collectionneurs pour sa connexion à un moment mémorable de Star Wars. Le design capture à la fois la vulnérabilité de la captivité de Leia et la force qu\'elle a démontrée dans sa revanche ultime contre son ravisseur.',
    es: 'Esta minifigura de la Princesa Leia representa uno de los momentos de vestuario más icónicos y controvertidos de El Retorno del Jedi, cuando fue capturada y esclavizada por Jabba el Hutt. La trenza larga marrón oscuro representa su peinado durante esta secuencia, diferente de sus moños laterales típicos. El soporte de cuello es un elemento LEGO especializado que representa la cadena que la ataba a la plataforma del trono de Jabba. A pesar de las circunstancias degradantes, esta escena se volvió fundamental cuando Leia finalmente usó esa misma cadena para estrangular y matar a Jabba, demostrando su fuerza e ingenio. El vestuario se ha convertido en uno de los atuendos más reconocibles en la historia del cine de ciencia ficción. Lanzada alrededor de 2013 en sets del Palacio de Jabba, esta minifigura es muy codiciada por los coleccionistas por su conexión con un momento memorable de Star Wars. El diseño captura tanto la vulnerabilidad del cautiverio de Leia como la fuerza que mostró en su venganza definitiva contra su captor.',
  },
  {
    no: 'sw0486',
    name: 'Max Rebo',
    en: 'Max Rebo is the blue-skinned Ortolan musician who leads the Max Rebo Band, the house band performing at Jabba the Hutt\'s palace in Return of the Jedi. Playing a red ball jett organ, Max Rebo and his band provided entertainment during Jabba\'s court sessions and the notorious sail barge party. The Ortolans are characterized by their distinctive blue skin, large eyes, and trunk-like snouts. Max Rebo\'s band, which included famous members like Sy Snootles and Droopy McCool, became one of the most memorable and quirky elements of Jabba\'s Palace scenes. The minifigure captures Max Rebo\'s unique alien appearance with detailed printing showing his distinctive features. Released around 2013 in Jabba\'s Palace-themed sets, this minifigure is highly collectible due to its unique character design and connection to one of Star Wars\' most beloved creature cantina scenes. For collectors building Jabba\'s Palace, Max Rebo adds authentic musical atmosphere to the crime lord\'s court.',
    de: 'Max Rebo ist der blau-häutige Ortolaner-Musiker, der die Max Rebo Band anführt, die Hausband, die in Jabba dem Hutts Palast in Die Rückkehr der Jedi-Ritter auftritt. Mit einer roten Ball-Jett-Orgel spielend, boten Max Rebo und seine Band Unterhaltung während Jabbas Hofversammlungen und der berüchtigten Segelbarkassen-Party. Die Ortolaner zeichnen sich durch ihre charakteristische blaue Haut, große Augen und rüsselartige Schnauzen aus. Max Rebos Band, die berühmte Mitglieder wie Sy Snootles und Droopy McCool umfasste, wurde zu einem der unvergesslichsten und schrulligsten Elemente der Jabbas Palast-Szenen. Die Minifigur fängt Max Rebos einzigartige außerirdische Erscheinung mit detaillierter Bedruckung ein, die seine charakteristischen Merkmale zeigt. Veröffentlicht um 2013 in Jabbas Palast-thematischen Sets, ist diese Minifigur aufgrund ihres einzigartigen Charakterdesigns und ihrer Verbindung zu einer der beliebtesten Kreatur-Kantinen-Szenen von Star Wars sehr sammelwürdig. Für Sammler, die Jabbas Palast bauen, fügt Max Rebo authentische musikalische Atmosphäre zum Hof des Verbrecherlords hinzu.',
    fr: 'Max Rebo est le musicien Ortolan à peau bleue qui dirige le groupe Max Rebo Band, le groupe résident se produisant au palais de Jabba le Hutt dans Le Retour du Jedi. Jouant d\'un orgue à boule jett rouge, Max Rebo et son groupe fournissaient du divertissement pendant les sessions de cour de Jabba et la fête notoire sur la barge à voile. Les Ortolans sont caractérisés par leur peau bleue distinctive, leurs grands yeux et leurs museaux en forme de trompe. Le groupe de Max Rebo, qui incluait des membres célèbres comme Sy Snootles et Droopy McCool, est devenu l\'un des éléments les plus mémorables et excentriques des scènes du Palais de Jabba. La minifigurine capture l\'apparence extraterrestre unique de Max Rebo avec une impression détaillée montrant ses caractéristiques distinctives. Sortie vers 2013 dans des ensembles sur le thème du Palais de Jabba, cette minifigurine est hautement collectionnable en raison de son design de personnage unique et de sa connexion à l\'une des scènes de cantina de créatures les plus aimées de Star Wars. Pour les collectionneurs construisant le Palais de Jabba, Max Rebo ajoute une atmosphère musicale authentique à la cour du seigneur du crime.',
    es: 'Max Rebo es el músico Ortolan de piel azul que lidera la Banda de Max Rebo, la banda residente que actuaba en el palacio de Jabba el Hutt en El Retorno del Jedi. Tocando un órgano de bola jett roja, Max Rebo y su banda proporcionaban entretenimiento durante las sesiones de corte de Jabba y la notoria fiesta en la barcaza de vela. Los Ortolanos se caracterizan por su distintiva piel azul, grandes ojos y hocicos similares a trompas. La banda de Max Rebo, que incluía miembros famosos como Sy Snootles y Droopy McCool, se convirtió en uno de los elementos más memorables y peculiares de las escenas del Palacio de Jabba. La minifigura captura la apariencia alienígena única de Max Rebo con impresión detallada que muestra sus características distintivas. Lanzada alrededor de 2013 en sets temáticos del Palacio de Jabba, esta minifigura es altamente coleccionable debido a su diseño de personaje único y conexión con una de las escenas de cantina de criaturas más amadas de Star Wars. Para los coleccionistas que construyen el Palacio de Jabba, Max Rebo agrega atmósfera musical auténtica a la corte del señor del crimen.',
  },
  {
    no: 'sw0487',
    name: 'Weequay Skiff Guard (Pagetti Rook)',
    en: 'Pagetti Rook is a Weequay skiff guard in Jabba the Hutt\'s employ, appearing during the attempted execution of Luke Skywalker, Han Solo, and Chewbacca at the Great Pit of Carkoon in Return of the Jedi. The Weequay species is characterized by their leathery, wrinkled skin and distinctive braided topknots. Skiff guards like Pagetti Rook were responsible for security and prisoner transport during Jabba\'s operations, often meeting violent ends during Luke\'s rescue mission above the Sarlacc pit. The minifigure captures the distinctive Weequay appearance with detailed printing showing the species\' characteristic facial features and typically includes weaponry appropriate for a desert guard. Released around 2013 in Jabba\'s Sail Barge or Desert Skiff sets, Weequay guards are essential for collectors recreating the iconic Sarlacc pit battle scene. Multiple Weequay figures help populate skiff and barge displays, representing the diverse criminal hirelings that worked for Jabba\'s criminal empire.',
    de: 'Pagetti Rook ist ein Weequay-Skiff-Wächter in Jabba dem Hutts Diensten und erscheint während der versuchten Hinrichtung von Luke Skywalker, Han Solo und Chewbacca an der Großen Grube von Carkoon in Die Rückkehr der Jedi-Ritter. Die Weequay-Spezies zeichnet sich durch ihre ledrige, faltige Haut und charakteristische geflochtene Zöpfe aus. Skiff-Wächter wie Pagetti Rook waren für Sicherheit und Gefangenentransport während Jabbas Operationen verantwortlich und trafen oft gewaltsame Enden während Lukes Rettungsmission über der Sarlacc-Grube. Die Minifigur fängt das charakteristische Weequay-Aussehen mit detaillierter Bedruckung ein, die die charakteristischen Gesichtszüge der Spezies zeigt, und enthält typischerweise Waffen, die für einen Wüstenwächter geeignet sind. Veröffentlicht um 2013 in Jabbas Segelbarkasse- oder Wüsten-Skiff-Sets, sind Weequay-Wächter für Sammler unverzichtbar, die die ikonische Sarlacc-Gruben-Kampfszene nachstellen. Mehrere Weequay-Figuren helfen, Skiff- und Barkassen-Displays zu bevölkern und repräsentieren die vielfältigen kriminellen Mietlinge, die für Jabbas Verbrecherimperium arbeiteten.',
    fr: 'Pagetti Rook est un garde de skiff Weequay employé par Jabba le Hutt, apparaissant lors de la tentative d\'exécution de Luke Skywalker, Han Solo et Chewbacca à la Grande Fosse de Carkoon dans Le Retour du Jedi. L\'espèce Weequay est caractérisée par leur peau coriace et ridée et leurs chignons tressés distinctifs. Les gardes de skiff comme Pagetti Rook étaient responsables de la sécurité et du transport des prisonniers pendant les opérations de Jabba, rencontrant souvent des fins violentes pendant la mission de sauvetage de Luke au-dessus de la fosse Sarlacc. La minifigurine capture l\'apparence Weequay distinctive avec une impression détaillée montrant les traits faciaux caractéristiques de l\'espèce et inclut généralement l\'armement approprié pour un garde du désert. Sortie vers 2013 dans les ensembles de la Barge à Voile de Jabba ou du Skiff du Désert, les gardes Weequay sont essentiels pour les collectionneurs recréant la scène de bataille iconique de la fosse Sarlacc. Plusieurs figurines Weequay aident à peupler les affichages de skiff et de barge, représentant les divers mercenaires criminels qui travaillaient pour l\'empire criminel de Jabba.',
    es: 'Pagetti Rook es un guardia de esquife Weequay al servicio de Jabba el Hutt, apareciendo durante el intento de ejecución de Luke Skywalker, Han Solo y Chewbacca en el Gran Pozo de Carkoon en El Retorno del Jedi. La especie Weequay se caracteriza por su piel curtida y arrugada y distintivos moños trenzados. Los guardias de esquife como Pagetti Rook eran responsables de la seguridad y transporte de prisioneros durante las operaciones de Jabba, frecuentemente encontrando finales violentos durante la misión de rescate de Luke sobre el pozo Sarlacc. La minifigura captura la apariencia distintiva Weequay con impresión detallada que muestra los rasgos faciales característicos de la especie y típicamente incluye armamento apropiado para un guardia del desierto. Lanzada alrededor de 2013 en sets de la Barcaza de Vela de Jabba o Esquife del Desierto, los guardias Weequay son esenciales para los coleccionistas que recrean la icónica escena de batalla del pozo Sarlacc. Múltiples figuras Weequay ayudan a poblar exhibiciones de esquife y barcaza, representando a los diversos mercenarios criminales que trabajaban para el imperio criminal de Jabba.',
  },
  {
    no: 'sw0488',
    name: 'Anakin Skywalker (Padawan, Combed Hair)',
    en: 'This Anakin Skywalker minifigure depicts the young Jedi Padawan during his apprenticeship under Obi-Wan Kenobi in Attack of the Clones. The combed hair style represents Anakin\'s more disciplined appearance as a Jedi learner, distinct from his Episode I child version or his later Episode III look. As a Padawan, Anakin was already demonstrating exceptional Force abilities and piloting skills that would eventually make him one of the most powerful Jedi. This period shows Anakin before his fall to the dark side, still hopeful and heroic despite his impulsive nature and forbidden romance with Padmé Amidala. Released in Episode II-themed sets around 2013, this minifigure captures a crucial transitional period in Anakin\'s journey from slave child to Darth Vader. For collectors, Padawan Anakin represents the tragic hero at a moment when his destiny could have gone differently, making this an emotionally significant minifigure for those following Anakin\'s complete character arc.',
    de: 'Diese Anakin Skywalker-Minifigur zeigt den jungen Jedi-Padawan während seiner Lehre unter Obi-Wan Kenobi in Angriff der Klonkrieger. Der gekämmte Haarstil repräsentiert Anakins disziplinierteres Aussehen als Jedi-Schüler, unterscheidet sich von seiner Episode I-Kinderversion oder seinem späteren Episode III-Look. Als Padawan demonstrierte Anakin bereits außergewöhnliche Macht-Fähigkeiten und Pilotenfähigkeiten, die ihn schließlich zu einem der mächtigsten Jedi machen würden. Diese Periode zeigt Anakin vor seinem Fall zur dunklen Seite, noch hoffnungsvoll und heroisch trotz seiner impulsiven Natur und verbotenen Romanze mit Padmé Amidala. Veröffentlicht in Episode II-thematischen Sets um 2013, fängt diese Minifigur eine entscheidende Übergangsperiode in Anakins Reise vom Sklavenkind zu Darth Vader ein. Für Sammler repräsentiert Padawan Anakin den tragischen Helden in einem Moment, in dem sein Schicksal anders hätte verlaufen können, was dies zu einer emotional bedeutsamen Minifigur für diejenigen macht, die Anakins vollständigen Charakterbogen verfolgen.',
    fr: 'Cette minifigurine Anakin Skywalker représente le jeune Padawan Jedi pendant son apprentissage sous Obi-Wan Kenobi dans L\'Attaque des Clones. Le style de cheveux peignés représente l\'apparence plus disciplinée d\'Anakin en tant qu\'apprenant Jedi, distincte de sa version enfant de l\'Épisode I ou de son look ultérieur de l\'Épisode III. En tant que Padawan, Anakin démontrait déjà des capacités de Force exceptionnelles et des compétences de pilotage qui feraient éventuellement de lui l\'un des Jedi les plus puissants. Cette période montre Anakin avant sa chute vers le côté obscur, encore plein d\'espoir et héroïque malgré sa nature impulsive et sa romance interdite avec Padmé Amidala. Sortie dans des ensembles sur le thème de l\'Épisode II vers 2013, cette minifigurine capture une période de transition cruciale dans le voyage d\'Anakin de l\'enfant esclave à Dark Vador. Pour les collectionneurs, le Padawan Anakin représente le héros tragique à un moment où son destin aurait pu être différent, faisant de celle-ci une minifigurine émotionnellement significative pour ceux qui suivent l\'arc complet du personnage d\'Anakin.',
    es: 'Esta minifigura de Anakin Skywalker representa al joven Padawan Jedi durante su aprendizaje bajo Obi-Wan Kenobi en El Ataque de los Clones. El estilo de cabello peinado representa la apariencia más disciplinada de Anakin como aprendiz Jedi, distinta de su versión infantil del Episodio I o su aspecto posterior del Episodio III. Como Padawan, Anakin ya estaba demostrando habilidades excepcionales de la Fuerza y habilidades de pilotaje que eventualmente lo convertirían en uno de los Jedi más poderosos. Este período muestra a Anakin antes de su caída al lado oscuro, todavía esperanzado y heroico a pesar de su naturaleza impulsiva y romance prohibido con Padmé Amidala. Lanzada en sets temáticos del Episodio II alrededor de 2013, esta minifigura captura un período de transición crucial en el viaje de Anakin desde niño esclavo hasta Darth Vader. Para los coleccionistas, el Padawan Anakin representa al héroe trágico en un momento cuando su destino podría haber sido diferente, haciendo de esta una minifigura emocionalmente significativa para aquellos que siguen el arco completo del personaje de Anakin.',
  },
  {
    no: 'sw0489',
    name: 'Obi-Wan Kenobi (Mid-Length Tousled with Center Part Hair)',
    en: 'This Obi-Wan Kenobi minifigure represents the Jedi Knight during Attack of the Clones, featuring mid-length tousled hair with a center part that defines his appearance during this period. At this stage, Obi-Wan is a full Jedi Knight training his Padawan Anakin Skywalker, demonstrating the patience and wisdom that would define his character. During Episode II, Obi-Wan conducts critical detective work uncovering the clone army on Kamino and confronts Count Dooku, advancing the mystery of the Sith\'s return. The hairstyle distinguishes this version from his Episode I Padawan look or his later bearded Episode III appearance, marking a specific point in his character development. Released in Episode II-themed sets around 2013, this Obi-Wan variant captures him at the height of his Jedi Knight career, before the Clone Wars would test his skills and character to their limits. For collectors tracking Obi-Wan\'s journey from Padawan to Jedi Master to hermit, this mid-career version represents an important transitional period.',
    de: 'Diese Obi-Wan Kenobi-Minifigur repräsentiert den Jedi-Ritter während Angriff der Klonkrieger und zeigt mittellanges zerzaustes Haar mit einem Mittelscheitel, der sein Aussehen während dieser Periode definiert. In diesem Stadium ist Obi-Wan ein vollwertiger Jedi-Ritter, der seinen Padawan Anakin Skywalker ausbildet und die Geduld und Weisheit demonstriert, die seinen Charakter definieren würden. Während Episode II führt Obi-Wan kritische Detektivarbeit durch, entdeckt die Klonarmee auf Kamino und konfrontiert Count Dooku, was das Geheimnis der Rückkehr der Sith vorantreibt. Die Frisur unterscheidet diese Version von seinem Episode I-Padawan-Look oder seinem späteren bärtigen Episode III-Aussehen und markiert einen spezifischen Punkt in seiner Charakterentwicklung. Veröffentlicht in Episode II-thematischen Sets um 2013, fängt diese Obi-Wan-Variante ihn auf dem Höhepunkt seiner Jedi-Ritter-Karriere ein, bevor die Klonkriege seine Fähigkeiten und seinen Charakter bis an ihre Grenzen testen würden. Für Sammler, die Obi-Wans Reise vom Padawan zum Jedi-Meister zum Eremiten verfolgen, repräsentiert diese Mittelkarriere-Version eine wichtige Übergangsperiode.',
    fr: 'Cette minifigurine Obi-Wan Kenobi représente le Chevalier Jedi pendant L\'Attaque des Clones, présentant des cheveux ébouriffés mi-longs avec une raie au milieu qui définit son apparence pendant cette période. À ce stade, Obi-Wan est un Chevalier Jedi à part entière formant son Padawan Anakin Skywalker, démontrant la patience et la sagesse qui définiraient son personnage. Pendant l\'Épisode II, Obi-Wan mène un travail de détective critique découvrant l\'armée clone sur Kamino et confronte le Comte Dooku, faisant progresser le mystère du retour des Sith. La coiffure distingue cette version de son look Padawan de l\'Épisode I ou de son apparence barbue ultérieure de l\'Épisode III, marquant un point spécifique dans son développement de personnage. Sortie dans des ensembles sur le thème de l\'Épisode II vers 2013, cette variante d\'Obi-Wan le capture à l\'apogée de sa carrière de Chevalier Jedi, avant que les Guerres des Clones ne testent ses compétences et son caractère à leurs limites. Pour les collectionneurs suivant le voyage d\'Obi-Wan de Padawan à Maître Jedi à ermite, cette version mi-carrière représente une période de transition importante.',
    es: 'Esta minifigura de Obi-Wan Kenobi representa al Caballero Jedi durante El Ataque de los Clones, presentando cabello despeinado de longitud media con raya al centro que define su apariencia durante este período. En esta etapa, Obi-Wan es un Caballero Jedi completo entrenando a su Padawan Anakin Skywalker, demostrando la paciencia y sabiduría que definirían su carácter. Durante el Episodio II, Obi-Wan realiza trabajo de detective crítico descubriendo el ejército clon en Kamino y confronta al Conde Dooku, avanzando el misterio del regreso de los Sith. El peinado distingue esta versión de su aspecto de Padawan del Episodio I o su apariencia barbada posterior del Episodio III, marcando un punto específico en su desarrollo de personaje. Lanzada en sets temáticos del Episodio II alrededor de 2013, esta variante de Obi-Wan lo captura en la cima de su carrera como Caballero Jedi, antes de que las Guerras Clon probaran sus habilidades y carácter hasta sus límites. Para los coleccionistas que siguen el viaje de Obi-Wan desde Padawan hasta Maestro Jedi hasta ermitaño, esta versión de media carrera representa un período de transición importante.',
  },
  {
    no: 'sw0490',
    name: 'Padmé Amidala - Geonosis Arena',
    en: 'This Padmé Amidala minifigure depicts the Senator and former Queen of Naboo during the climactic Geonosis arena battle in Attack of the Clones. The outfit features her distinctive white arena combat costume, which became iconic due to its practicality and the memorable action sequence where Padmé fought alongside Jedi during the opening battle of the Clone Wars. This scene marked a dramatic shift for Padmé from diplomat to active combatant, demonstrating her courage and combat skills. The white outfit with its distinctive midriff-baring design became one of Padmé\'s most recognizable costumes throughout the prequel trilogy. Released around 2013 in Geonosis arena-themed sets, this minifigure captures Padmé at a pivotal moment when the galaxy descended into war. For collectors, the Geonosis arena Padmé represents a key moment in Star Wars history and showcases the character\'s evolution from political leader to warrior fighting for the Republic\'s survival.',
    de: 'Diese Padmé Amidala-Minifigur zeigt die Senatorin und ehemalige Königin von Naboo während der klimatischen Geonosis-Arena-Schlacht in Angriff der Klonkrieger. Das Outfit zeigt ihr charakteristisches weißes Arena-Kampfkostüm, das aufgrund seiner Praktikabilität und der unvergesslichen Action-Sequenz ikonisch wurde, in der Padmé während der Eröffnungsschlacht der Klonkriege an der Seite der Jedi kämpfte. Diese Szene markierte einen dramatischen Wandel für Padmé von der Diplomatin zur aktiven Kämpferin und demonstrierte ihren Mut und ihre Kampffähigkeiten. Das weiße Outfit mit seinem charakteristischen bauchfreien Design wurde zu einem von Padmés erkennbarsten Kostümen in der Prequel-Trilogie. Veröffentlicht um 2013 in Geonosis-Arena-thematischen Sets, fängt diese Minifigur Padmé in einem entscheidenden Moment ein, als die Galaxie in den Krieg abstieg. Für Sammler repräsentiert die Geonosis-Arena Padmé einen Schlüsselmoment in der Star Wars-Geschichte und zeigt die Evolution des Charakters von politischer Führerin zur Kriegerin, die für das Überleben der Republik kämpft.',
    fr: 'Cette minifigurine Padmé Amidala représente la Sénatrice et ancienne Reine de Naboo pendant la bataille climatique de l\'arène de Géonosis dans L\'Attaque des Clones. La tenue présente son costume de combat d\'arène blanc distinctif, devenu iconique en raison de sa praticité et de la séquence d\'action mémorable où Padmé combattait aux côtés des Jedi pendant la bataille d\'ouverture des Guerres des Clones. Cette scène a marqué un changement dramatique pour Padmé de diplomate à combattante active, démontrant son courage et ses compétences au combat. La tenue blanche avec son design distinctif montrant le ventre est devenue l\'un des costumes les plus reconnaissables de Padmé dans la trilogie préquel. Sortie vers 2013 dans des ensembles sur le thème de l\'arène de Géonosis, cette minifigurine capture Padmé à un moment charnière où la galaxie a sombré dans la guerre. Pour les collectionneurs, la Padmé de l\'arène de Géonosis représente un moment clé de l\'histoire de Star Wars et montre l\'évolution du personnage de leader politique à guerrière combattant pour la survie de la République.',
    es: 'Esta minifigura de Padmé Amidala representa a la Senadora y ex Reina de Naboo durante la climática batalla de la arena de Geonosis en El Ataque de los Clones. El atuendo presenta su distintivo traje de combate de arena blanco, que se volvió icónico debido a su practicidad y la memorable secuencia de acción donde Padmé luchó junto a los Jedi durante la batalla de apertura de las Guerras Clon. Esta escena marcó un cambio dramático para Padmé de diplomática a combatiente activa, demostrando su coraje y habilidades de combate. El atuendo blanco con su distintivo diseño que muestra el vientre se convirtió en uno de los vestuarios más reconocibles de Padmé a lo largo de la trilogía de precuelas. Lanzada alrededor de 2013 en sets temáticos de la arena de Geonosis, esta minifigura captura a Padmé en un momento crucial cuando la galaxia descendió a la guerra. Para los coleccionistas, la Padmé de la arena de Geonosis representa un momento clave en la historia de Star Wars y muestra la evolución del personaje de líder política a guerrera luchando por la supervivencia de la República.',
  },
];

async function saveBatch() {
  console.log('Starting batch save for sw0483, sw0485-sw0490...');

  for (const minifig of batch) {
    try {
      await prisma.minifigCatalog.update({
        where: { minifigure_no: minifig.no },
        data: {
          description_en: minifig.en,
          description_de: minifig.de,
          description_fr: minifig.fr,
          description_es: minifig.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        }
      });
      console.log(`✓ Saved ${minifig.no}: ${minifig.name}`);
    } catch (error) {
      console.error(`✗ Error saving ${minifig.no}:`, error);
      throw error;
    }
  }

  console.log('Batch complete! 7 minifigs saved.');
  await prisma.$disconnect();
}

saveBatch();
