// Disney sets
module.exports = {
  '71040-1': {
    en: "The Disney Castle features 4,080 pieces recreating the iconic Cinderella Castle. Includes 5 minifigures: Mickey, Minnie, Donald, Daisy, and Tinker Bell. Features detailed interior with grand entrance hall, rotating dance floor, and fireworks display. Includes Disney train and station. Measures over 29 inches high with authentic architectural details inspired by Disney Parks.",
    de: "Das Disney Schloss enthält 4.080 Teile und stellt das ikonische Cinderella-Schloss nach. Mit 5 Minifiguren: Mickey, Minnie, Donald, Daisy und Tinker Bell. Mit detailliertem Innenraum mit großer Eingangshalle, rotierender Tanzfläche und Feuerwerks-Display. Mit Disney-Zug und Bahnhof. Über 74 cm hoch mit authentischen architektonischen Details inspiriert von Disney Parks.",
    fr: "Le Château Disney comprend 4 080 pièces recréant l'emblématique Château de Cendrillon. Comprend 5 minifigurines : Mickey, Minnie, Donald, Daisy et la Fée Clochette. Intérieur détaillé avec grand hall d'entrée, piste de danse rotative et spectacle de feux d'artifice. Comprend train et gare Disney. Mesure plus de 74 cm de haut avec détails architecturaux authentiques inspirés des Parcs Disney.",
    es: "El Castillo Disney contiene 4.080 piezas recreando el icónico Castillo de Cenicienta. Incluye 5 minifiguras: Mickey, Minnie, Donald, Daisy y Campanita. Con interior detallado con gran vestíbulo de entrada, pista de baile giratoria y exhibición de fuegos artificiales. Incluye tren y estación Disney. Mide más de 74 cm de alto con detalles arquitectónicos auténticos inspirados en los Parques Disney."
  },
  '43197-1': {
    en: "The Ice Castle features 1,709 pieces recreating Elsa's palace from Frozen. Includes 4 minifigures: Anna, Elsa, Olaf, and Kristoff. Features grand staircase, ice chandelier, throne room, bedroom, and ice bridge. Includes special transparent and glittering elements for ice effect. Measures over 17 inches high with stunning crystalline design capturing the movie's magic.",
    de: "Der Eispalast enthält 1.709 Teile und stellt Elsas Palast aus Frozen nach. Mit 4 Minifiguren: Anna, Elsa, Olaf und Kristoff. Mit großer Treppe, Eiskronleuchter, Thronsaal, Schlafzimmer und Eisbrücke. Mit speziellen transparenten und glitzernden Elementen für Eiseffekt. Über 43 cm hoch mit atemberaubendem kristallinem Design, das die Magie des Films einfängt.",
    fr: "Le Château de Glace comprend 1 709 pièces recréant le palais d'Elsa de La Reine des Neiges. Comprend 4 minifigurines : Anna, Elsa, Olaf et Kristoff. Grand escalier, lustre de glace, salle du trône, chambre et pont de glace. Comprend éléments transparents et scintillants spéciaux pour effet de glace. Mesure plus de 43 cm de haut avec design cristallin époustouflant capturant la magie du film.",
    es: "El Castillo de Hielo contiene 1.709 piezas recreando el palacio de Elsa de Frozen. Incluye 4 minifiguras: Anna, Elsa, Olaf y Kristoff. Con gran escalera, candelabro de hielo, sala del trono, dormitorio y puente de hielo. Incluye elementos especiales transparentes y brillantes para efecto de hielo. Mide más de 43 cm de alto con impresionante diseño cristalino capturando la magia de la película."
  },
  '43230-1': {
    en: "Walt Disney Tribute Camera features 811 pieces recreating a vintage movie camera. Includes 3 minifigures: Walt Disney, Minnie Mouse, and Mickey Mouse. Features rotating crank handle, movable viewfinder, director's clapperboard, and multiplane camera. Includes film strip showing scenes from Steamboat Willie. Measures over 5 inches high celebrating 100 years of Disney animation.",
    de: "Walt Disney Tribute Kamera enthält 811 Teile und stellt eine Vintage-Filmkamera nach. Mit 3 Minifiguren: Walt Disney, Minnie Mouse und Mickey Mouse. Mit rotierender Kurbel, beweglichem Sucher, Regieklappe und Multiplan-Kamera. Mit Filmstreifen mit Szenen aus Steamboat Willie. Über 14 cm hoch, feiert 100 Jahre Disney-Animation.",
    fr: "Caméra Hommage à Walt Disney comprend 811 pièces recréant une caméra de cinéma vintage. Comprend 3 minifigurines : Walt Disney, Minnie Mouse et Mickey Mouse. Manivelle rotative, viseur mobile, clap de réalisateur et caméra multiplan. Comprend bande de film montrant des scènes de Steamboat Willie. Mesure plus de 14 cm de haut célébrant 100 ans d'animation Disney.",
    es: "Cámara Tributo a Walt Disney contiene 811 piezas recreando una cámara de cine vintage. Incluye 3 minifiguras: Walt Disney, Minnie Mouse y Mickey Mouse. Con manivela giratoria, visor móvil, claqueta de director y cámara multiplano. Incluye tira de película mostrando escenas de Steamboat Willie. Mide más de 14 cm de alto celebrando 100 años de animación Disney."
  },
  '43222-1': {
    en: "Disney Castle features 4,842 pieces recreating the ultimate Disney castle. Includes 12 minifigures: Mickey, Minnie, Donald, Daisy, Tinker Bell, Cinderella, Moana, Rapunzel, and more. Features detailed rooms inspired by multiple Disney films, rotating dance floor, fireworks display, and intricate architectural details. Measures over 31 inches high with enhanced details from 2023 redesign.",
    de: "Disney Schloss enthält 4.842 Teile und stellt das ultimative Disney-Schloss nach. Mit 12 Minifiguren: Mickey, Minnie, Donald, Daisy, Tinker Bell, Cinderella, Vaiana, Rapunzel und mehr. Mit detaillierten Räumen inspiriert von mehreren Disney-Filmen, rotierender Tanzfläche, Feuerwerks-Display und aufwendigen architektonischen Details. Über 80 cm hoch mit verbesserten Details aus dem Redesign 2023.",
    fr: "Château Disney comprend 4 842 pièces recréant le château Disney ultime. Comprend 12 minifigurines : Mickey, Minnie, Donald, Daisy, Fée Clochette, Cendrillon, Vaiana, Raiponce et plus. Pièces détaillées inspirées de plusieurs films Disney, piste de danse rotative, spectacle de feux d'artifice et détails architecturaux complexes. Mesure plus de 80 cm de haut avec détails améliorés de la refonte 2023.",
    es: "Castillo Disney contiene 4.842 piezas recreando el castillo Disney definitivo. Incluye 12 minifiguras: Mickey, Minnie, Donald, Daisy, Campanita, Cenicienta, Moana, Rapunzel y más. Con habitaciones detalladas inspiradas en múltiples películas Disney, pista de baile giratoria, exhibición de fuegos artificiales y detalles arquitectónicos intrincados. Mide más de 80 cm de alto con detalles mejorados del rediseño 2023."
  },
  '43205-1': {
    en: "Ultimate Adventure Castle features 698 pieces recreating a modular Disney castle. Includes 5 minifigures: Anna, Elsa, Moana, Snow White, and Rapunzel. Features throne room, bedroom, kitchen, balcony, and fireworks display. Includes modular design allowing multiple building configurations. Measures over 12 inches high with colorful design representing multiple Disney princesses.",
    de: "Ultimatives Abenteuer-Schloss enthält 698 Teile und stellt ein modulares Disney-Schloss nach. Mit 5 Minifiguren: Anna, Elsa, Vaiana, Schneewittchen und Rapunzel. Mit Thronsaal, Schlafzimmer, Küche, Balkon und Feuerwerks-Display. Mit modularem Design, das mehrere Baukonfigurationen ermöglicht. Über 31 cm hoch mit farbenfrohem Design, das mehrere Disney-Prinzessinnen repräsentiert.",
    fr: "Château d'Aventure Ultime comprend 698 pièces recréant un château Disney modulaire. Comprend 5 minifigurines : Anna, Elsa, Vaiana, Blanche-Neige et Raiponce. Salle du trône, chambre, cuisine, balcon et spectacle de feux d'artifice. Comprend conception modulaire permettant plusieurs configurations de construction. Mesure plus de 31 cm de haut avec design coloré représentant plusieurs princesses Disney.",
    es: "Castillo de Aventura Definitivo contiene 698 piezas recreando un castillo Disney modular. Incluye 5 minifiguras: Anna, Elsa, Moana, Blancanieves y Rapunzel. Con sala del trono, dormitorio, cocina, balcón y exhibición de fuegos artificiales. Incluye diseño modular permitiendo múltiples configuraciones de construcción. Mide más de 31 cm de alto con diseño colorido representando múltiples princesas Disney."
  }
};
