import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0094',
    name: 'Rebel Pilot Y-wing (Jon \'Dutch\' Vander, Gold Leader) - Light Nougat Head',
    en: 'Jon "Dutch" Vander, callsign Gold Leader, commanded the Y-wing squadron during the Battle of Yavin in A New Hope. This LEGO minifigure features the light nougat head, yellow flight suit, and distinctive helmet that identifies Y-wing bomber pilots. The figure captures Dutch Vander during his critical role leading the first attack run on the Death Star\'s thermal exhaust port. Released in 2007 as part of Y-wing Starfighter sets, this named character represents one of the few non-main hero pilots to receive a dedicated minifigure. The yellow flight suit distinguishes Y-wing pilots from the orange X-wing and green A-wing pilots. As Gold Leader and a key participant in the Death Star battle who nearly succeeded before being shot down by Darth Vader, Dutch Vander is highly valued by collectors who focus on named Rebel Alliance heroes and complete squadron rosters.',
    de: 'Jon "Dutch" Vander, Rufzeichen Gold Leader, kommandierte die Y-Wing-Staffel während der Schlacht von Yavin in Eine neue Hoffnung. Diese LEGO Minifigur zeigt den hellen Nougat-Kopf, gelben Fluganzug und den charakteristischen Helm, der Y-Wing-Bomber-Piloten identifiziert. Die Figur fängt Dutch Vander während seiner kritischen Rolle ein, als er den ersten Angriffsflug auf die thermale Abluftöffnung des Todessterns leitete. Veröffentlicht im Jahr 2007 als Teil von Y-Wing-Starfighter-Sets, repräsentiert dieser benannte Charakter einen der wenigen Nicht-Haupthelden-Piloten, die eine dedizierte Minifigur erhielten. Der gelbe Fluganzug unterscheidet Y-Wing-Piloten von den orangefarbenen X-Wing- und grünen A-Wing-Piloten. Als Gold Leader und wichtiger Teilnehmer der Todesstern-Schlacht, der fast erfolgreich war, bevor er von Darth Vader abgeschossen wurde, wird Dutch Vander von Sammlern hoch geschätzt, die sich auf benannte Rebellenallianz-Helden und vollständige Staffellisten konzentrieren.',
    fr: 'Jon "Dutch" Vander, indicatif Gold Leader, commandait l\'escadron de Y-wing pendant la Bataille de Yavin dans Un Nouvel Espoir. Cette minifigurine LEGO présente la tête nougat clair, la combinaison de vol jaune et le casque distinctif qui identifie les pilotes de bombardiers Y-wing. La figurine capture Dutch Vander pendant son rôle critique en dirigeant la première course d\'attaque sur le port d\'échappement thermique de l\'Étoile de la Mort. Sortie en 2007 dans des sets de Chasseur Stellaire Y-wing, ce personnage nommé représente l\'un des rares pilotes non-héros principaux à recevoir une minifigurine dédiée. La combinaison de vol jaune distingue les pilotes Y-wing des pilotes X-wing orange et A-wing verts. En tant que Gold Leader et participant clé de la bataille de l\'Étoile de la Mort qui a presque réussi avant d\'être abattu par Dark Vador, Dutch Vander est très valorisé par les collectionneurs qui se concentrent sur les héros nommés de l\'Alliance Rebelle et les listes complètes d\'escadron.',
    es: 'Jon "Dutch" Vander, indicativo Gold Leader, comandó el escuadrón de Y-wing durante la Batalla de Yavin en Una Nueva Esperanza. Esta minifigura LEGO presenta la cabeza nougat claro, traje de vuelo amarillo y distintivo casco que identifica a pilotos de bombarderos Y-wing. La figura captura a Dutch Vander durante su papel crítico liderando la primera carrera de ataque en el puerto de escape térmico de la Estrella de la Muerte. Lanzada en 2007 como parte de sets de Caza Estelar Y-wing, este personaje nombrado representa uno de los pocos pilotos no héroes principales en recibir una minifigura dedicada. El traje de vuelo amarillo distingue a pilotos Y-wing de los pilotos X-wing naranja y A-wing verdes. Como Gold Leader y participante clave en la batalla de la Estrella de la Muerte que casi tuvo éxito antes de ser derribado por Darth Vader, Dutch Vander es altamente valorado por coleccionistas que se enfocan en héroes nombrados de la Alianza Rebelde y listas completas de escuadrón.'
  },
  {
    no: 'sw0128a',
    name: 'Clone Trooper, 327th Star Corps (Phase 2) - Black Head',
    en: 'The 327th Star Corps Clone Trooper served under Commander Bly during the Clone Wars, most notably during the Battle of Utapau. This LEGO minifigure features the Phase 2 armor with distinctive yellow markings and black head piece that identifies the 327th Star Corps. The figure includes detailed printing showing the gold/yellow unit markings, advanced armor plating, and tactical gear used by this elite unit. Released in 2007 as part of Clone Wars sets, this trooper represents the forces that fought alongside Obi-Wan Kenobi on Utapau and tragically executed Order 66. The yellow markings distinguish the 327th from other clone units like the 501st Legion (blue) and Coruscant Guard (red). As troops who played a crucial role in both the Clone Wars and Order 66, the 327th Star Corps troopers are essential for collectors building Clone Wars battle scenes and Order 66 dioramas.',
    de: 'Der 327. Sternkorps-Klon-Trooper diente unter Commander Bly während der Klonkriege, besonders während der Schlacht von Utapau. Diese LEGO Minifigur zeigt die Phase-2-Rüstung mit charakteristischen gelben Markierungen und schwarzem Kopfteil, das das 327. Sternkorps identifiziert. Die Figur enthält detaillierte Bedruckung, die die gold-/gelben Einheitsmarkierungen, fortschrittliche Rüstungsplattierung und taktische Ausrüstung zeigt, die von dieser Elite-Einheit verwendet wird. Veröffentlicht im Jahr 2007 als Teil von Klonkriegs-Sets, repräsentiert dieser Trooper die Streitkräfte, die an der Seite von Obi-Wan Kenobi auf Utapau kämpften und tragischerweise Order 66 ausführten. Die gelben Markierungen unterscheiden das 327. von anderen Klon-Einheiten wie der 501. Legion (blau) und der Coruscant Guard (rot). Als Truppen, die eine entscheidende Rolle sowohl in den Klonkriegen als auch bei Order 66 spielten, sind die 327.-Sternkorps-Trooper für Sammler unverzichtbar, die Klonkriegs-Kampfszenen und Order-66-Dioramen bauen.',
    fr: 'Le Clone Trooper du 327ème Corps d\'Étoiles a servi sous le Commandant Bly pendant la Guerre des Clones, notamment pendant la Bataille d\'Utapau. Cette minifigurine LEGO présente l\'armure de Phase 2 avec des marquages jaunes distinctifs et une pièce de tête noire qui identifie le 327ème Corps d\'Étoiles. La figurine comprend une impression détaillée montrant les marquages d\'unité or/jaune, le blindage d\'armure avancé et l\'équipement tactique utilisé par cette unité d\'élite. Sortie en 2007 dans des sets de la Guerre des Clones, ce trooper représente les forces qui ont combattu aux côtés d\'Obi-Wan Kenobi sur Utapau et ont tragiquement exécuté l\'Ordre 66. Les marquages jaunes distinguent le 327ème des autres unités de clones comme la 501ème Légion (bleue) et la Garde de Coruscant (rouge). En tant que troupes qui ont joué un rôle crucial à la fois dans la Guerre des Clones et l\'Ordre 66, les troopers du 327ème Corps d\'Étoiles sont essentiels pour les collectionneurs construisant des scènes de bataille de la Guerre des Clones et des dioramas de l\'Ordre 66.',
    es: 'El Clone Trooper del 327° Cuerpo Estelar sirvió bajo el Comandante Bly durante las Guerras Clon, más notablemente durante la Batalla de Utapau. Esta minifigura LEGO presenta la armadura de Fase 2 con distintivas marcas amarillas y pieza de cabeza negra que identifica al 327° Cuerpo Estelar. La figura incluye impresión detallada mostrando las marcas de unidad oro/amarillo, blindaje de armadura avanzado y equipo táctico usado por esta unidad de élite. Lanzada en 2007 como parte de sets de las Guerras Clon, este trooper representa las fuerzas que lucharon junto a Obi-Wan Kenobi en Utapau y trágicamente ejecutaron la Orden 66. Las marcas amarillas distinguen al 327° de otras unidades clon como la Legión 501 (azul) y Guardia de Coruscant (roja). Como tropas que jugaron un papel crucial tanto en las Guerras Clon como en la Orden 66, los troopers del 327° Cuerpo Estelar son esenciales para coleccionistas construyendo escenas de batalla de las Guerras Clon y dioramas de la Orden 66.'
  },
  {
    no: 'sw0036b',
    name: 'Imperial Stormtrooper - Black Head, Solid Mouth Helmet',
    en: 'The Imperial Stormtrooper with black head represents a production variant of the Empire\'s iconic soldiers. This LEGO minifigure features the black head beneath white armor and the solid mouth helmet design that characterized specific manufacturing runs. The figure includes detailed printing of the chest plate armor, utility belt, and the distinctive white armor that made Stormtroopers the face of Imperial military power. Released in 2007 as part of numerous Imperial sets, the black head variant distinguishes this from flesh-toned and light nougat versions. The solid mouth helmet refers to the printed mouth area rather than vented designs. As the most numerous and recognizable Imperial troops, Stormtroopers are among the most army-built minifigures in LEGO Star Wars, with collectors often acquiring dozens or even hundreds to create massive Imperial battalion displays and Death Star garrison scenes.',
    de: 'Der imperiale Stormtrooper mit schwarzem Kopf repräsentiert eine Produktionsvariante der ikonischen Soldaten des Imperiums. Diese LEGO Minifigur zeigt den schwarzen Kopf unter weißer Rüstung und das feste Mund-Helm-Design, das spezifische Fertigungsläufe charakterisierte. Die Figur enthält detaillierte Bedruckung der Brustplatten-Rüstung, des Werkzeuggürtels und der charakteristischen weißen Rüstung, die Stormtroopers zum Gesicht imperialer Militärmacht machte. Veröffentlicht im Jahr 2007 als Teil zahlreicher imperialer Sets, unterscheidet die schwarze Kopfvariante diese von hauttonigen und hellen Nougat-Versionen. Der feste Mundhelm bezieht sich auf den bedruckten Mundbereich statt belüfteter Designs. Als zahlreichste und erkennbarste imperiale Truppen gehören Stormtroopers zu den am meisten armeebauenden Minifiguren in LEGO Star Wars, wobei Sammler oft Dutzende oder sogar Hunderte erwerben, um massive imperiale Bataillonsausstellungen und Todesstern-Garnisonsszenen zu erstellen.',
    fr: 'Le Stormtrooper Impérial avec tête noire représente une variante de production des soldats iconiques de l\'Empire. Cette minifigurine LEGO présente la tête noire sous l\'armure blanche et la conception de casque à bouche solide qui caractérisait des séries de fabrication spécifiques. La figurine comprend une impression détaillée de l\'armure de plaque de poitrine, de la ceinture utilitaire et de l\'armure blanche distinctive qui a fait des Stormtroopers le visage de la puissance militaire impériale. Sortie en 2007 dans de nombreux sets impériaux, la variante à tête noire distingue celle-ci des versions à teint chair et nougat clair. Le casque à bouche solide fait référence à la zone de bouche imprimée plutôt qu\'aux conceptions ventilées. En tant que troupes impériales les plus nombreuses et les plus reconnaissables, les Stormtroopers sont parmi les minifigurines les plus construites en armée dans LEGO Star Wars, les collectionneurs en acquérant souvent des dizaines voire des centaines pour créer d\'énormes affichages de bataillons impériaux et des scènes de garnison de l\'Étoile de la Mort.',
    es: 'El Stormtrooper Imperial con cabeza negra representa una variante de producción de los soldados icónicos del Imperio. Esta minifigura LEGO presenta la cabeza negra debajo de armadura blanca y el diseño de casco de boca sólida que caracterizó tiradas de fabricación específicas. La figura incluye impresión detallada de la armadura de placa de pecho, cinturón utilitario y la distintiva armadura blanca que hizo a los Stormtroopers la cara del poder militar Imperial. Lanzada en 2007 como parte de numerosos sets Imperiales, la variante de cabeza negra distingue esta de versiones de tono carne y nougat claro. El casco de boca sólida se refiere al área de boca impresa en lugar de diseños ventilados. Como las tropas Imperiales más numerosas y reconocibles, los Stormtroopers están entre las minifiguras más construidas en ejército en LEGO Star Wars, con coleccionistas a menudo adquiriendo docenas o incluso cientos para crear exhibiciones masivas de batallón Imperial y escenas de guarnición de la Estrella de la Muerte.'
  },
  {
    no: 'sw0109a',
    name: 'Sandtrooper - Orange Pauldron (Solid), No Survival Backpack, No Dirt Stains, Helmet with Solid Mouth Pattern and Solid Black Head',
    en: 'The Sandtrooper with orange pauldron represents the squad leaders of the Imperial desert troops deployed on Tatooine in A New Hope. This LEGO minifigure features the distinctive orange shoulder pauldron, solid black head, and clean white armor without dirt stains. The figure captures the appearance of Sandtrooper squad leaders who searched for R2-D2 and C-3PO in the Tatooine deserts. Released in 2007, this variant with solid orange pauldron and no survival backpack represents a specific production configuration. The orange pauldron indicates squad leader rank, distinguishing them from white-pauldron enlisted troopers and black-pauldron sergeants. As specialized Imperial desert warfare troops and key antagonists in the search for the droids, Sandtroopers are essential for collectors building Tatooine scenes with dewback mounts and desert patrol squads.',
    de: 'Der Sandtrooper mit orangefarbener Schulterklappe repräsentiert die Squad-Leader der imperialen Wüstentruppen, die auf Tatooine in Eine neue Hoffnung eingesetzt wurden. Diese LEGO Minifigur zeigt die charakteristische orangefarbene Schulterklappe, soliden schwarzen Kopf und saubere weiße Rüstung ohne Schmutzflecken. Die Figur fängt das Aussehen von Sandtrooper-Squad-Leadern ein, die in den Tatooine-Wüsten nach R2-D2 und C-3PO suchten. Veröffentlicht im Jahr 2007, repräsentiert diese Variante mit solider orangefarbener Schulterklappe und ohne Überlebensrucksack eine spezifische Produktionskonfiguration. Die orangefarbene Schulterklappe zeigt Squad-Leader-Rang an und unterscheidet sie von weißen Schulterklappenträger-Mannschafts-Troopers und schwarzen Schulterklappenträger-Sergeants. Als spezialisierte imperiale Wüstenkriegsführungstruppen und wichtige Antagonisten bei der Suche nach den Droiden sind Sandtroopers für Sammler unverzichtbar, die Tatooine-Szenen mit Dewback-Reittieren und Wüstenpatrouille-Squads bauen.',
    fr: 'Le Sandtrooper avec épaulière orange représente les chefs d\'escouade des troupes du désert impériales déployées sur Tatooine dans Un Nouvel Espoir. Cette minifigurine LEGO présente l\'épaulière orange distinctive, la tête noire solide et l\'armure blanche propre sans taches de saleté. La figurine capture l\'apparence des chefs d\'escouade Sandtrooper qui cherchaient R2-D2 et C-3PO dans les déserts de Tatooine. Sortie en 2007, cette variante avec épaulière orange solide et sans sac à dos de survie représente une configuration de production spécifique. L\'épaulière orange indique le rang de chef d\'escouade, les distinguant des troopers engagés à épaulière blanche et des sergents à épaulière noire. En tant que troupes spécialisées de guerre du désert impériales et antagonistes clés dans la recherche des droïdes, les Sandtroopers sont essentiels pour les collectionneurs construisant des scènes de Tatooine avec des montures dewback et des escouades de patrouille du désert.',
    es: 'El Sandtrooper con hombrera naranja representa a los líderes de escuadrón de las tropas del desierto Imperiales desplegadas en Tatooine en Una Nueva Esperanza. Esta minifigura LEGO presenta la distintiva hombrera naranja, cabeza negra sólida y armadura blanca limpia sin manchas de suciedad. La figura captura la apariencia de líderes de escuadrón Sandtrooper que buscaron a R2-D2 y C-3PO en los desiertos de Tatooine. Lanzada en 2007, esta variante con hombrera naranja sólida y sin mochila de supervivencia representa una configuración de producción específica. La hombrera naranja indica rango de líder de escuadrón, distinguiéndolos de troopers alistados de hombrera blanca y sargentos de hombrera negra. Como tropas especializadas de guerra del desierto Imperial y antagonistas clave en la búsqueda de los droides, los Sandtroopers son esenciales para coleccionistas construyendo escenas de Tatooine con monturas dewback y escuadrones de patrulla del desierto.'
  },
  {
    no: 'sw0134a',
    name: 'General Grievous - Straight Legs',
    en: 'General Grievous without cape represents a variant of the fearsome cyborg commander of the Droid Army. This LEGO minifigure features straight leg pieces and the distinctive four-armed design without the flowing black cape. The figure includes detailed printing of his cybernetic body armor, skeletal face mask, and the mechanical limbs that allowed him to wield multiple lightsabers simultaneously. Released in 2007 as a variant of earlier releases, this cape-less version with straight legs shows a different configuration of the character. The absence of the cape emphasizes Grievous\'s mechanical nature and his role as a droid general. As one of the most distinctive villains from Revenge of the Sith and the Clone Wars, General Grievous minifigures in various configurations are highly collectible among fans who appreciate the prequel era\'s unique antagonists.',
    de: 'General Grievous ohne Umhang repräsentiert eine Variante des furchteinflößenden kybernetischen Kommandanten der Droiden-Armee. Diese LEGO Minifigur zeigt gerade Beinteile und das charakteristische vierarmige Design ohne den fließenden schwarzen Umhang. Die Figur enthält detaillierte Bedruckung seiner kybernetischen Körperpanzerung, Skelett-Gesichtsmaske und der mechanischen Gliedmaßen, die es ihm ermöglichten, mehrere Lichtschwerter gleichzeitig zu führen. Veröffentlicht im Jahr 2007 als Variante früherer Veröffentlichungen, zeigt diese umhanglose Version mit geraden Beinen eine andere Konfiguration des Charakters. Das Fehlen des Umhangs betont Grievous\' mechanische Natur und seine Rolle als Droiden-General. Als einer der markantesten Bösewichte aus Die Rache der Sith und den Klonkriegen sind General-Grievous-Minifiguren in verschiedenen Konfigurationen bei Fans sehr sammelwürdig, die die einzigartigen Antagonisten der Prequel-Ära schätzen.',
    fr: 'Le Général Grievous sans cape représente une variante du redoutable commandant cyborg de l\'Armée Droïde. Cette minifigurine LEGO présente des pièces de jambes droites et la conception à quatre bras distinctive sans la cape noire fluide. La figurine comprend une impression détaillée de son armure corporelle cybernétique, son masque facial squelettique et les membres mécaniques qui lui permettaient de manier plusieurs sabres laser simultanément. Sortie en 2007 comme variante de sorties antérieures, cette version sans cape avec jambes droites montre une configuration différente du personnage. L\'absence de cape met l\'accent sur la nature mécanique de Grievous et son rôle de général droïde. En tant que l\'un des méchants les plus distinctifs de La Revanche des Sith et de la Guerre des Clones, les minifigurines du Général Grievous dans diverses configurations sont très collectionnables parmi les fans qui apprécient les antagonistes uniques de l\'ère des préquelles.',
    es: 'El General Grievous sin capa representa una variante del temible comandante cyborg del Ejército Droide. Esta minifigura LEGO presenta piezas de piernas rectas y el distintivo diseño de cuatro brazos sin la capa negra fluida. La figura incluye impresión detallada de su armadura corporal cibernética, máscara facial esquelética y las extremidades mecánicas que le permitían blandir múltiples sables de luz simultáneamente. Lanzada en 2007 como variante de lanzamientos anteriores, esta versión sin capa con piernas rectas muestra una configuración diferente del personaje. La ausencia de capa enfatiza la naturaleza mecánica de Grievous y su papel como general droide. Como uno de los villanos más distintivos de La Venganza de los Sith y las Guerras Clon, las minifiguras del General Grievous en varias configuraciones son altamente coleccionables entre fans que aprecian los antagonistas únicos de la era de las precuelas.'
  },
  {
    no: 'sw0158',
    name: 'C-3PO - Chrome Gold (SW 30th Anniversary Edition)',
    en: 'C-3PO in chrome gold represents a special 30th Anniversary commemorative edition of Star Wars\' most beloved protocol droid. This LEGO minifigure features a stunning chrome gold finish that creates a mirror-like reflective surface, far more luxurious than standard pearl gold versions. The figure maintains C-3PO\'s distinctive humanoid design with detailed limb joints and proportions. Released in 2007 to celebrate Star Wars\' 30th anniversary, this chrome variant was produced in limited quantities, making it one of the most sought-after promotional minifigures. The mirror-finish chrome gold distinguishes this dramatically from regular C-3PO versions. As a commemorative piece marking three decades of Star Wars and featuring premium chrome plating, this 30th Anniversary C-3PO commands significant collector value and is considered one of the crown jewels of LEGO Star Wars collecting.',
    de: 'C-3PO in Chromgold repräsentiert eine spezielle 30-jährige Jubiläumsausgabe von Star Wars\' beliebtestem Protokoll-Droiden. Diese LEGO Minifigur zeigt ein atemberaubendes Chromgold-Finish, das eine spiegelartige reflektierende Oberfläche erzeugt, weitaus luxuriöser als standardmäßige Perlen-Gold-Versionen. Die Figur behält C-3POs charakteristisches humanoiden Design mit detaillierten Gelenkverbindungen und Proportionen bei. Veröffentlicht im Jahr 2007 zur Feier des 30-jährigen Jubiläums von Star Wars, wurde diese Chrom-Variante in begrenzten Mengen produziert, was sie zu einer der begehrtesten Werbe-Minifiguren macht. Das Spiegelfinish-Chromgold unterscheidet diese dramatisch von regulären C-3PO-Versionen. Als Gedenkstück, das drei Jahrzehnte Star Wars markiert und Premium-Chrom-Plattierung aufweist, erzielt dieser 30-Jubiläums-C-3PO erheblichen Sammlerwert und gilt als eines der Kronjuwelen des LEGO-Star-Wars-Sammelns.',
    fr: 'C-3PO en or chromé représente une édition commémorative spéciale du 30ème anniversaire du droïde de protocole le plus aimé de Star Wars. Cette minifigurine LEGO présente une finition or chromé époustouflante qui crée une surface réfléchissante semblable à un miroir, beaucoup plus luxueuse que les versions or nacré standard. La figurine maintient la conception humanoïde distinctive de C-3PO avec des articulations de membres détaillées et des proportions. Sortie en 2007 pour célébrer le 30ème anniversaire de Star Wars, cette variante chromée a été produite en quantités limitées, en faisant l\'une des minifigurines promotionnelles les plus recherchées. L\'or chromé à finition miroir distingue celle-ci de manière spectaculaire des versions C-3PO régulières. En tant que pièce commémorative marquant trois décennies de Star Wars et présentant un placage chromé premium, ce C-3PO du 30ème anniversaire commande une valeur de collectionneur significative et est considéré comme l\'un des joyaux de la couronne de la collection LEGO Star Wars.',
    es: 'C-3PO en oro cromado representa una edición conmemorativa especial del 30 aniversario del droide de protocolo más querido de Star Wars. Esta minifigura LEGO presenta un impresionante acabado de oro cromado que crea una superficie reflectante similar a un espejo, mucho más lujosa que versiones estándar de oro perlado. La figura mantiene el distintivo diseño humanoide de C-3PO con articulaciones de extremidades detalladas y proporciones. Lanzada en 2007 para celebrar el 30 aniversario de Star Wars, esta variante cromada fue producida en cantidades limitadas, haciéndola una de las minifiguras promocionales más buscadas. El oro cromado con acabado de espejo distingue esta dramáticamente de versiones regulares de C-3PO. Como pieza conmemorativa marcando tres décadas de Star Wars y presentando plateado cromado premium, este C-3PO del 30 Aniversario obtiene valor significativo de coleccionista y es considerado una de las joyas de la corona de colección de LEGO Star Wars.'
  },
  {
    no: 'sw0159',
    name: 'Anakin Skywalker - Short Legs, Short Tousled Hair, Reddish Brown Belt',
    en: 'Young Anakin Skywalker as a child represents his early days as a slave on Tatooine before his Jedi training in The Phantom Menace. This LEGO minifigure features short legs indicating his youth, short tousled hair, and reddish brown belt on simple clothing. The figure captures Anakin\'s appearance as the young pod racer who would eventually become Darth Vader. Released in 2007 as part of Tatooine-themed sets, this child version shows Anakin at his most innocent, before the dark path that defined his future. The short legs and youthful hair distinguish this from adult Anakin variants. As the origin story of Star Wars\' most tragic character, young Anakin minifigures are valued by collectors who focus on complete character arcs from childhood through redemption, documenting the fall and rise of the Chosen One.',
    de: 'Der junge Anakin Skywalker als Kind repräsentiert seine frühen Tage als Sklave auf Tatooine vor seinem Jedi-Training in Die dunkle Bedrohung. Diese LEGO Minifigur zeigt kurze Beine, die seine Jugend anzeigen, kurzes zerzaustes Haar und einen rotbraunen Gürtel auf einfacher Kleidung. Die Figur fängt Anakins Aussehen als junger Pod-Racer ein, der schließlich zu Darth Vader werden würde. Veröffentlicht im Jahr 2007 als Teil von Tatooine-thematisierten Sets, zeigt diese Kinderversion Anakin in seinem unschuldigsten Zustand, vor dem dunklen Pfad, der seine Zukunft definierte. Die kurzen Beine und das jugendliche Haar unterscheiden diese von erwachsenen Anakin-Varianten. Als Ursprungsgeschichte von Star Wars\' tragischstem Charakter werden junge Anakin-Minifiguren von Sammlern geschätzt, die sich auf vollständige Charakterbögen von der Kindheit bis zur Erlösung konzentrieren und den Fall und Aufstieg des Auserwählten dokumentieren.',
    fr: 'Le jeune Anakin Skywalker en tant qu\'enfant représente ses premiers jours en tant qu\'esclave sur Tatooine avant sa formation Jedi dans La Menace Fantôme. Cette minifigurine LEGO présente des jambes courtes indiquant sa jeunesse, des cheveux courts ébouriffés et une ceinture brun rougeâtre sur des vêtements simples. La figurine capture l\'apparence d\'Anakin en tant que jeune pilote de pod qui deviendrait finalement Dark Vador. Sortie en 2007 dans des sets à thème Tatooine, cette version enfant montre Anakin à son plus innocent, avant le chemin sombre qui a défini son avenir. Les jambes courtes et les cheveux juvéniles distinguent celle-ci des variantes Anakin adultes. En tant qu\'histoire d\'origine du personnage le plus tragique de Star Wars, les minifigurines du jeune Anakin sont valorisées par les collectionneurs qui se concentrent sur des arcs de personnage complets de l\'enfance à la rédemption, documentant la chute et la montée de l\'Élu.',
    es: 'El joven Anakin Skywalker como niño representa sus primeros días como esclavo en Tatooine antes de su entrenamiento Jedi en La Amenaza Fantasma. Esta minifigura LEGO presenta piernas cortas indicando su juventud, cabello corto despeinado y cinturón marrón rojizo en ropa simple. La figura captura la apariencia de Anakin como el joven corredor de vainas que eventualmente se convertiría en Darth Vader. Lanzada en 2007 como parte de sets temáticos de Tatooine, esta versión infantil muestra a Anakin en su momento más inocente, antes del camino oscuro que definió su futuro. Las piernas cortas y cabello juvenil distinguen esta de variantes adultas de Anakin. Como historia de origen del personaje más trágico de Star Wars, las minifiguras del joven Anakin son valoradas por coleccionistas que se enfocan en arcos de personaje completos desde la infancia hasta la redención, documentando la caída y ascenso del Elegido.'
  },
  {
    no: 'sw0160',
    name: 'Naboo Fighter Pilot - Tan Jacket',
    en: 'The Naboo Fighter Pilot represents the Royal Naboo Security Forces who defended the planet during the Trade Federation invasion in The Phantom Menace. This LEGO minifigure features the distinctive tan jacket, flight helmet, and the formal military styling of Naboo\'s elite starfighter corps. The figure includes detailed printing showing the practical flight suit worn by N-1 starfighter pilots. Released in 2007 as part of Naboo Starfighter sets, this pilot captures the appearance of the forces that participated in the Battle of Naboo. The tan jacket color scheme distinguishes Naboo pilots from other faction\'s flight crews. As the defenders of one of the prequel trilogy\'s most elegant civilizations and participants in young Anakin\'s accidental destruction of the droid control ship, Naboo pilots are valued by collectors who focus on Episode I forces and the chrome-accented N-1 starfighters.',
    de: 'Der Naboo-Jägerpilot repräsentiert die königlichen Naboo-Sicherheitskräfte, die den Planeten während der Handelsföderation-Invasion in Die dunkle Bedrohung verteidigten. Diese LEGO Minifigur zeigt die charakteristische beige Jacke, Flughelm und den formellen militärischen Stil von Naboos Elite-Sternenjäger-Korps. Die Figur enthält detaillierte Bedruckung, die den praktischen Fluganzug zeigt, der von N-1-Sternenjäger-Piloten getragen wurde. Veröffentlicht im Jahr 2007 als Teil von Naboo-Starfighter-Sets, fängt dieser Pilot das Aussehen der Streitkräfte ein, die an der Schlacht von Naboo teilnahmen. Das beige Jacken-Farbschema unterscheidet Naboo-Piloten von Flugbesatzungen anderer Fraktionen. Als Verteidiger einer der elegantesten Zivilisationen der Prequel-Trilogie und Teilnehmer an jungen Anakins versehentlicher Zerstörung des Droiden-Kontrollschiffs werden Naboo-Piloten von Sammlern geschätzt, die sich auf Episode-I-Streitkräfte und die chromakzentuierten N-1-Sternenjäger konzentrieren.',
    fr: 'Le Pilote de Chasseur Naboo représente les Forces de Sécurité Royales de Naboo qui ont défendu la planète pendant l\'invasion de la Fédération du Commerce dans La Menace Fantôme. Cette minifigurine LEGO présente la veste beige distinctive, le casque de vol et le style militaire formel du corps de chasseurs stellaires d\'élite de Naboo. La figurine comprend une impression détaillée montrant la combinaison de vol pratique portée par les pilotes de chasseurs stellaires N-1. Sortie en 2007 dans des sets de Chasseur Stellaire Naboo, ce pilote capture l\'apparence des forces qui ont participé à la Bataille de Naboo. Le schéma de couleur de veste beige distingue les pilotes Naboo des équipages de vol d\'autres factions. En tant que défenseurs de l\'une des civilisations les plus élégantes de la trilogie des préquelles et participants à la destruction accidentelle du vaisseau de contrôle droïde par le jeune Anakin, les pilotes Naboo sont valorisés par les collectionneurs qui se concentrent sur les forces de l\'Épisode I et les chasseurs stellaires N-1 accentués de chrome.',
    es: 'El Piloto de Caza Naboo representa las Fuerzas de Seguridad Real de Naboo que defendieron el planeta durante la invasión de la Federación de Comercio en La Amenaza Fantasma. Esta minifigura LEGO presenta la distintiva chaqueta beige, casco de vuelo y el estilo militar formal del cuerpo de cazas estelares de élite de Naboo. La figura incluye impresión detallada mostrando el traje de vuelo práctico usado por pilotos de cazas estelares N-1. Lanzada en 2007 como parte de sets de Caza Estelar Naboo, este piloto captura la apariencia de las fuerzas que participaron en la Batalla de Naboo. El esquema de color de chaqueta beige distingue a pilotos Naboo de tripulaciones de vuelo de otras facciones. Como defensores de una de las civilizaciones más elegantes de la trilogía de las precuelas y participantes en la destrucción accidental de la nave de control droide del joven Anakin, los pilotos Naboo son valorados por coleccionistas que se enfocan en fuerzas del Episodio I y los cazas estelares N-1 acentuados en cromo.'
  },
  {
    no: 'sw0161',
    name: 'C-3PO - Pearl Gold with Pearl Light Gold Hands',
    en: 'C-3PO in pearl gold with pearl light gold hands represents a refined color variant of Star Wars\' fussy protocol droid. This LEGO minifigure features the standard pearl gold body with lighter pearl gold hands, creating a subtle two-tone effect. The figure maintains C-3PO\'s distinctive humanoid proportions, detailed joint printing, and his characteristic worried personality captured in the design. Released in 2007 as part of various Original Trilogy sets, this variant with contrasting hand color adds visual interest to the beloved character. The pearl light gold hands distinguish this from solid single-color C-3PO versions. As the Rebellion\'s accidental diplomat and constant companion to R2-D2 throughout the saga, C-3PO minifigures are essential for collectors building complete Original Trilogy character rosters, and variant colorations like this two-tone version appeal to completionists.',
    de: 'C-3PO in Perlengold mit perlenhellgoldenen Händen repräsentiert eine verfeinerte Farbvariante von Star Wars\' pedantischem Protokoll-Droiden. Diese LEGO Minifigur zeigt den Standard-Perlengold-Körper mit helleren perlengoldenen Händen, die einen subtilen zweifarbigen Effekt erzeugen. Die Figur behält C-3POs charakteristische humanoide Proportionen, detaillierte Gelenkbedruckung und seine charakteristische besorgte Persönlichkeit bei, die im Design eingefangen ist. Veröffentlicht im Jahr 2007 als Teil verschiedener Original-Trilogie-Sets, fügt diese Variante mit kontrastierender Handfarbe dem beliebten Charakter visuelles Interesse hinzu. Die perlenhellgoldenen Hände unterscheiden diese von soliden einfarbigen C-3PO-Versionen. Als versehentlicher Diplomat der Rebellion und ständiger Begleiter von R2-D2 durch die gesamte Saga sind C-3PO-Minifiguren für Sammler unverzichtbar, die vollständige Original-Trilogie-Charakterlisten aufbauen, und Variantenfärbungen wie diese zweifarbige Version sprechen Vervollständiger an.',
    fr: 'C-3PO en or nacré avec mains or clair nacré représente une variante de couleur raffinée du droïde de protocole pointilleux de Star Wars. Cette minifigurine LEGO présente le corps or nacré standard avec des mains or clair nacré plus claires, créant un effet bicolore subtil. La figurine maintient les proportions humanoïdes distinctives de C-3PO, l\'impression d\'articulation détaillée et sa personnalité inquiète caractéristique capturée dans la conception. Sortie en 2007 dans divers sets de la Trilogie Originale, cette variante avec couleur de main contrastée ajoute un intérêt visuel au personnage bien-aimé. Les mains or clair nacré distinguent celle-ci des versions C-3PO unicolores solides. En tant que diplomate accidentel de la Rébellion et compagnon constant de R2-D2 tout au long de la saga, les minifigurines C-3PO sont essentielles pour les collectionneurs construisant des listes complètes de personnages de la Trilogie Originale, et les colorations de variantes comme cette version bicolore plaisent aux complétistes.',
    es: 'C-3PO en oro perlado con manos de oro claro perlado representa una variante de color refinada del droide de protocolo quisquilloso de Star Wars. Esta minifigura LEGO presenta el cuerpo estándar de oro perlado con manos de oro claro perlado más claras, creando un efecto bicolor sutil. La figura mantiene las proporciones humanoides distintivas de C-3PO, impresión de articulación detallada y su personalidad preocupada característica capturada en el diseño. Lanzada en 2007 como parte de varios sets de la Trilogía Original, esta variante con color de mano contrastante añade interés visual al personaje querido. Las manos de oro claro perlado distinguen esta de versiones de C-3PO de un solo color sólido. Como diplomático accidental de la Rebelión y compañero constante de R2-D2 a lo largo de la saga, las minifiguras de C-3PO son esenciales para coleccionistas construyendo listas completas de personajes de la Trilogía Original, y coloraciones variantes como esta versión bicolor atraen a completistas.'
  },
  {
    no: 'sw0001c',
    name: 'Battle Droid - Tan, Angled Arm and Straight Arm',
    en: 'The Battle Droid with mixed arm configuration represents an unusual production variant from the early days of LEGO Star Wars. This minifigure features the tan color scheme with one angled arm and one straight arm, creating an asymmetrical design. The figure maintains the distinctive skeletal appearance, narrow head, and hinged limbs of standard battle droids. Released in 1999-2000 as a production anomaly, this mixed-arm variant resulted from manufacturing inconsistencies during the launch of the LEGO Star Wars line. The sw0001c designation indicates this is the third variant of the original battle droid mold. As a quirky production error from the very beginning of LEGO Star Wars history, this asymmetrical battle droid is highly sought by variant collectors and LEGO Star Wars historians who document the evolution of minifigure production standards.',
    de: 'Der Battle Droid mit gemischter Armkonfiguration repräsentiert eine ungewöhnliche Produktionsvariante aus den frühen Tagen von LEGO Star Wars. Diese Minifigur zeigt das beige Farbschema mit einem abgewinkelten Arm und einem geraden Arm, was ein asymmetrisches Design erzeugt. Die Figur behält das charakteristische skelettartige Aussehen, schmalen Kopf und bewegliche Gliedmaßen von Standard-Kampfdroiden bei. Veröffentlicht 1999-2000 als Produktionsanomalie, resultierte diese gemischte Armvariante aus Fertigungsinkonsistenzen während des Starts der LEGO-Star-Wars-Linie. Die Bezeichnung sw0001c zeigt an, dass dies die dritte Variante der ursprünglichen Battle-Droid-Form ist. Als skurriler Produktionsfehler vom allerersten Beginn der LEGO-Star-Wars-Geschichte ist dieser asymmetrische Battle Droid bei Varianten-Sammlern und LEGO-Star-Wars-Historikern sehr begehrt, die die Entwicklung von Minifiguren-Produktionsstandards dokumentieren.',
    fr: 'Le Battle Droid avec configuration de bras mixte représente une variante de production inhabituelle des débuts de LEGO Star Wars. Cette minifigurine présente le schéma de couleur beige avec un bras incliné et un bras droit, créant une conception asymétrique. La figurine maintient l\'apparence squelettique distinctive, la tête étroite et les membres articulés des battle droids standard. Sortie en 1999-2000 comme anomalie de production, cette variante à bras mixtes résultait d\'incohérences de fabrication pendant le lancement de la ligne LEGO Star Wars. La désignation sw0001c indique qu\'il s\'agit de la troisième variante du moule de battle droid original. En tant qu\'erreur de production originale des tout débuts de l\'histoire de LEGO Star Wars, ce battle droid asymétrique est très recherché par les collectionneurs de variantes et les historiens LEGO Star Wars qui documentent l\'évolution des normes de production de minifigurines.',
    es: 'El Battle Droid con configuración de brazo mixta representa una variante de producción inusual de los primeros días de LEGO Star Wars. Esta minifigura presenta el esquema de color beige con un brazo angulado y un brazo recto, creando un diseño asimétrico. La figura mantiene la apariencia esquelética distintiva, cabeza estrecha y extremidades articuladas de battle droids estándar. Lanzada en 1999-2000 como anomalía de producción, esta variante de brazo mixto resultó de inconsistencias de fabricación durante el lanzamiento de la línea LEGO Star Wars. La designación sw0001c indica que esta es la tercera variante del molde original de battle droid. Como error de producción peculiar desde el mismísimo comienzo de la historia de LEGO Star Wars, este battle droid asimétrico es muy buscado por coleccionistas de variantes e historiadores de LEGO Star Wars que documentan la evolución de estándares de producción de minifiguras.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 021 (sw0094-sw0001c) - 10 minifigs...\n');

  let successCount = 0;
  let skipCount = 0;

  for (const m of batch) {
    try {
      await prisma.minifigCatalog.update({
        where: { minifigure_no: m.no },
        data: {
          description_en: m.en,
          description_de: m.de,
          description_fr: m.fr,
          description_es: m.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        }
      });
      console.log(`  ✅ ${m.no}: ${m.name}`);
      successCount++;
    } catch (error: any) {
      console.log(`  ⚠️  ${m.no}: NOT IN DATABASE (skipped)`);
      skipCount++;
    }
  }

  console.log(`\n✨ Batch 021 complete: ${batch.length} minifigs (${successCount * 4} descriptions)\n`);

  await prisma.$disconnect();
}

saveBatch().catch(console.error);
