import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch040 = [
  {
    no: 'sw0324',
    name: 'Darth Vader (7251)',
    en: 'This Darth Vader represents the Dark Lord of the Sith immediately after his transformation on Mustafar in Revenge of the Sith, wearing the iconic black armor and life support suit that became synonymous with Imperial tyranny across the galaxy. The minifigure features detailed printing showing the chest control panel with life support systems, cape, and helmet concealing the scarred remnants of Anakin Skywalker. Released in 2005 in set 7251 (Darth Vader Transformation), this variant captures the pivotal moment when the fallen Jedi became Emperor Palpatine\'s enforcer. As one of the most iconic villains in cinema history, Vader is perpetually essential for any Star Wars collection, with this transformation-era variant particularly valued for representing the tragic birth of the Empire\'s most feared warrior and the completion of Anakin\'s fall from Jedi hero to Sith apprentice.',
    de: 'Dieser Darth Vader repräsentiert den Dunklen Lord der Sith unmittelbar nach seiner Verwandlung auf Mustafar in Die Rache der Sith, trägt die ikonische schwarze Rüstung und Lebenserhaltungsanzug, der zum Synonym für imperiale Tyrannei in der ganzen Galaxis wurde. Die Minifigur zeigt detaillierten Druck mit dem Brustbedienfeld mit Lebenserhaltungssystemen, Umhang und Helm, der die vernarbten Überreste von Anakin Skywalker verbirgt. 2005 im Set 7251 (Darth Vader Transformation) veröffentlicht, fängt diese Variante den entscheidenden Moment ein, als der gefallene Jedi zu Imperator Palpatines Vollstrecker wurde. Als einer der ikonischsten Schurken in der Kinogeschichte ist Vader dauerhaft wesentlich für jede Star Wars-Sammlung, wobei diese Transformations-Ära-Variante besonders geschätzt wird für die Darstellung der tragischen Geburt des gefürchtetsten Kriegers des Imperiums und den Abschluss von Anakins Fall vom Jedi-Helden zum Sith-Schüler.',
    fr: 'Ce Dark Vador représente le Seigneur Noir des Sith immédiatement après sa transformation sur Mustafar dans La Revanche des Sith, portant l\'armure noire emblématique et le costume de support vital qui est devenu synonyme de tyrannie Impériale à travers la galaxie. La minifigurine présente une impression détaillée montrant le panneau de commande de poitrine avec systèmes de support vital, une cape et un casque cachant les restes cicatrisés d\'Anakin Skywalker. Sortie en 2005 dans le set 7251 (Darth Vader Transformation), cette variante capture le moment pivot lorsque le Jedi déchu est devenu l\'exécuteur de l\'Empereur Palpatine. En tant que l\'un des méchants les plus emblématiques de l\'histoire du cinéma, Vador est perpétuellement essentiel pour toute collection Star Wars, cette variante de l\'ère de transformation étant particulièrement appréciée pour représenter la naissance tragique du guerrier le plus craint de l\'Empire et l\'achèvement de la chute d\'Anakin du héros Jedi à l\'apprenti Sith.',
    es: 'Este Darth Vader representa al Señor Oscuro de los Sith inmediatamente después de su transformación en Mustafar en La Venganza de los Sith, vistiendo la icónica armadura negra y traje de soporte vital que se convirtió en sinónimo de tiranía Imperial a través de la galaxia. La minifigura presenta impresión detallada mostrando el panel de control de pecho con sistemas de soporte vital, capa y casco ocultando los restos cicatrizados de Anakin Skywalker. Lanzado en 2005 en el set 7251 (Darth Vader Transformation), esta variante captura el momento fundamental cuando el Jedi caído se convirtió en el ejecutor del Emperador Palpatine. Como uno de los villanos más icónicos en la historia del cine, Vader es perpetuamente esencial para cualquier colección de Star Wars, con esta variante de la era de transformación particularmente valorada por representar el nacimiento trágico del guerrero más temido del Imperio y la culminación de la caída de Anakin de héroe Jedi a aprendiz Sith.'
  },
  {
    no: 'sw0325',
    name: 'Emperor Palpatine (7251)',
    en: 'Emperor Palpatine is the mastermind behind the fall of the Republic and rise of the Galactic Empire, a Sith Lord who manipulated galactic events for decades to achieve absolute power and nearly destroy the Jedi Order. This minifigure features his disfigured face showing the effects of Force lightning reflected during his battle with Mace Windu, dark hooded Sith robes, and cane that conceals his true power. Released in 2005 in set 7251 (Darth Vader Transformation), this Emperor represents the moment of his ultimate triumph when the Empire was declared and Vader knelt before him. As the saga\'s primary antagonist whose schemes drove the entire prequel trilogy and original trilogy, Palpatine is essential for any Star Wars collection, with this transformation-era variant capturing him at his moment of greatest victory when democracy died and tyranny was born.',
    de: 'Imperator Palpatine ist der Drahtzieher hinter dem Fall der Republik und Aufstieg des Galaktischen Imperiums, ein Sith-Lord, der galaktische Ereignisse jahrzehntelang manipulierte, um absolute Macht zu erlangen und den Jedi-Orden fast zu zerstören. Diese Minifigur zeigt sein entstelltes Gesicht, das die Auswirkungen des Machtblitzes zeigt, der während seiner Schlacht mit Mace Windu reflektiert wurde, dunkle vermummte Sith-Roben und Gehstock, der seine wahre Macht verbirgt. 2005 im Set 7251 (Darth Vader Transformation) veröffentlicht, repräsentiert dieser Imperator den Moment seines ultimativen Triumphs, als das Imperium erklärt wurde und Vader vor ihm kniete. Als primärer Antagonist der Saga, dessen Pläne die gesamte Prequel-Trilogie und Original-Trilogie antrieben, ist Palpatine wesentlich für jede Star Wars-Sammlung, wobei diese Transformations-Ära-Variante ihn in seinem Moment des größten Sieges einfängt, als die Demokratie starb und Tyrannei geboren wurde.',
    fr: 'L\'Empereur Palpatine est le cerveau derrière la chute de la République et la montée de l\'Empire Galactique, un Seigneur Sith qui a manipulé les événements galactiques pendant des décennies pour atteindre le pouvoir absolu et presque détruire l\'Ordre Jedi. Cette minifigurine présente son visage défiguré montrant les effets de la foudre de la Force réfléchie pendant sa bataille avec Mace Windu, des robes Sith sombres à capuche et une canne qui cache son véritable pouvoir. Sortie en 2005 dans le set 7251 (Darth Vader Transformation), cet Empereur représente le moment de son triomphe ultime lorsque l\'Empire a été déclaré et Vador s\'est agenouillé devant lui. En tant qu\'antagoniste principal de la saga dont les machinations ont conduit toute la trilogie préquelle et la trilogie originale, Palpatine est essentiel pour toute collection Star Wars, cette variante de l\'ère de transformation le capturant à son moment de plus grande victoire lorsque la démocratie est morte et la tyrannie est née.',
    es: 'El Emperador Palpatine es el cerebro detrás de la caída de la República y ascenso del Imperio Galáctico, un Señor Sith que manipuló eventos galácticos durante décadas para lograr poder absoluto y casi destruir la Orden Jedi. Esta minifigura presenta su rostro desfigurado mostrando los efectos del relámpago de la Fuerza reflejado durante su batalla con Mace Windu, túnicas Sith oscuras con capucha y bastón que oculta su verdadero poder. Lanzado en 2005 en el set 7251 (Darth Vader Transformation), este Emperador representa el momento de su triunfo final cuando el Imperio fue declarado y Vader se arrodilló ante él. Como el antagonista principal de la saga cuyas maquinaciones impulsaron toda la trilogía precuela y trilogía original, Palpatine es esencial para cualquier colección de Star Wars, con esta variante de la era de transformación capturándolo en su momento de mayor victoria cuando la democracia murió y la tiranía nació.'
  },
  {
    no: 'sw0326',
    name: 'Clone Trooper (7250)',
    en: 'This Clone Trooper represents the standard infantry soldier of the Republic\'s Grand Army during the Clone Wars, wearing Phase 2 white armor that provided improved protection and mobility compared to earlier Phase 1 designs seen at the war\'s beginning. The minifigure features the iconic white armor with black bodysuit, distinctive helmet with updated visor design, and clean appearance of mass-produced soldiers created from Jango Fett\'s genetic template. Released in 2005 in set 7250 (Clone Scout Walker), this trooper exemplifies the millions of identical soldiers who fought for the Republic. Standard white Clone Troopers remain essential for army building as collectors need multiple figures to create the massive formations that gave the Republic military superiority, with Phase 2 variants particularly valued for representing the war\'s later stages when clone forces had evolved their tactics and equipment through hard-won battlefield experience.',
    de: 'Dieser Klonkrieger repräsentiert den Standard-Infanterie-Soldaten der Großen Armee der Republik während der Klonkriege, trägt Phase-2-weiße Rüstung, die verbesserten Schutz und Mobilität im Vergleich zu früheren Phase-1-Designs bot, die zu Beginn des Krieges zu sehen waren. Die Minifigur zeigt die ikonische weiße Rüstung mit schwarzem Körperanzug, charakteristischen Helm mit aktualisiertem Visier-Design und sauberem Aussehen von massenproduzierten Soldaten, die aus Jango Fetts genetischer Vorlage erstellt wurden. 2005 im Set 7250 (Clone Scout Walker) veröffentlicht, verkörpert dieser Soldat die Millionen identischer Soldaten, die für die Republik kämpften. Standard-weiße Klonkrieger bleiben wesentlich für den Armeeaufbau, da Sammler mehrere Figuren benötigen, um die massiven Formationen zu erstellen, die der Republik militärische Überlegenheit gaben, wobei Phase-2-Varianten besonders geschätzt werden für die Darstellung der späteren Phasen des Krieges, als Klon-Streitkräfte ihre Taktiken und Ausrüstung durch hart erkämpfte Schlachtfeld-Erfahrung entwickelt hatten.',
    fr: 'Ce Clone Trooper représente le soldat d\'infanterie standard de la Grande Armée de la République pendant les Guerres des Clones, portant une armure blanche de Phase 2 qui offrait une protection et une mobilité améliorées par rapport aux conceptions de Phase 1 antérieures vues au début de la guerre. La minifigurine présente l\'armure blanche emblématique avec combinaison noire, un casque distinctif avec un design de visière mis à jour et l\'apparence propre des soldats produits en masse créés à partir du modèle génétique de Jango Fett. Sortie en 2005 dans le set 7250 (Clone Scout Walker), ce soldat illustre les millions de soldats identiques qui ont combattu pour la République. Les Clone Troopers blancs standard restent essentiels pour la construction d\'armées car les collectionneurs ont besoin de plusieurs figurines pour créer les formations massives qui ont donné à la République la supériorité militaire, les variantes de Phase 2 étant particulièrement appréciées pour représenter les dernières étapes de la guerre lorsque les forces clones avaient développé leurs tactiques et équipements grâce à l\'expérience du champ de bataille durement gagnée.',
    es: 'Este Clone Trooper representa al soldado de infantería estándar del Gran Ejército de la República durante las Guerras Clon, vistiendo armadura blanca de Fase 2 que proporcionó protección y movilidad mejoradas comparado con diseños anteriores de Fase 1 vistos al comienzo de la guerra. La minifigura presenta la icónica armadura blanca con traje negro, casco distintivo con diseño de visor actualizado y apariencia limpia de soldados producidos en masa creados de la plantilla genética de Jango Fett. Lanzado en 2005 en el set 7250 (Clone Scout Walker), este soldado ejemplifica los millones de soldados idénticos que lucharon por la República. Los Clone Troopers blancos estándar permanecen esenciales para construcción de ejércitos ya que coleccionistas necesitan múltiples figuras para crear las formaciones masivas que dieron a la República superioridad militar, con variantes de Fase 2 particularmente valoradas por representar las etapas posteriores de la guerra cuando fuerzas clon habían evolucionado sus tácticas y equipo mediante experiencia de campo de batalla duramente ganada.'
  },
  {
    no: 'sw0327',
    name: 'Obi-Wan Kenobi (7250)',
    en: 'This Obi-Wan Kenobi represents the legendary Jedi Master during the Clone Wars era, serving as a Republic general who led clone forces in countless battles while maintaining his commitment to Jedi principles despite the moral compromises of war. The minifigure features his characteristic auburn hair and beard, detailed Clone Wars-style Jedi robes with printing showing armor and equipment, and blue lightsaber befitting one of the Order\'s greatest warriors. Released in 2005 in set 7250 (Clone Scout Walker), this variant captures Obi-Wan during his prime as both military commander and Jedi mentor to Anakin Skywalker. As one of Star Wars\' most beloved characters who appears across all eras from padawan to Force ghost, Obi-Wan is essential for any collection, with this Clone Wars variant particularly valued for representing him at the height of his powers before the tragic events that would force him into exile on Tatooine.',
    de: 'Dieser Obi-Wan Kenobi repräsentiert den legendären Jedi-Meister während der Klonkrieg-Ära, dient als republikanischer General, der Klon-Streitkräfte in unzähligen Schlachten führte, während er sein Engagement für Jedi-Prinzipien trotz der moralischen Kompromisse des Krieges beibehielt. Die Minifigur zeigt sein charakteristisches kastanienbraunes Haar und Bart, detaillierte Clone Wars-Stil Jedi-Roben mit Druck, der Rüstung und Ausrüstung zeigt, und blaues Lichtschwert, das einem der größten Krieger des Ordens würdig ist. 2005 im Set 7250 (Clone Scout Walker) veröffentlicht, fängt diese Variante Obi-Wan während seiner Blütezeit sowohl als Militärkommandant als auch als Jedi-Mentor von Anakin Skywalker ein. Als einer der beliebtesten Charaktere von Star Wars, der über alle Epochen vom Padawan bis zum Machtgeist erscheint, ist Obi-Wan wesentlich für jede Sammlung, wobei diese Clone Wars-Variante besonders geschätzt wird für die Darstellung auf dem Höhepunkt seiner Kräfte vor den tragischen Ereignissen, die ihn ins Exil auf Tatooine zwingen würden.',
    fr: 'Cet Obi-Wan Kenobi représente le légendaire Maître Jedi pendant l\'ère des Guerres des Clones, servant de général de la République qui a mené les forces clones dans d\'innombrables batailles tout en maintenant son engagement envers les principes Jedi malgré les compromis moraux de la guerre. La minifigurine présente ses cheveux et sa barbe auburn caractéristiques, des robes Jedi détaillées de style Clone Wars avec impression montrant armure et équipement, et un sabre laser bleu convenant à l\'un des plus grands guerriers de l\'Ordre. Sortie en 2005 dans le set 7250 (Clone Scout Walker), cette variante capture Obi-Wan pendant son apogée à la fois comme commandant militaire et mentor Jedi d\'Anakin Skywalker. En tant que l\'un des personnages les plus aimés de Star Wars qui apparaît à travers toutes les époques du padawan au fantôme de la Force, Obi-Wan est essentiel pour toute collection, cette variante Clone Wars étant particulièrement appréciée pour le représenter au sommet de ses pouvoirs avant les événements tragiques qui le forceraient à l\'exil sur Tatooine.',
    es: 'Este Obi-Wan Kenobi representa al legendario Maestro Jedi durante la era de las Guerras Clon, sirviendo como general de la República que lideró fuerzas clon en incontables batallas mientras mantenía su compromiso con principios Jedi a pesar de los compromisos morales de la guerra. La minifigura presenta su característico cabello castaño rojizo y barba, túnicas Jedi detalladas estilo Clone Wars con impresión mostrando armadura y equipo, y sable de luz azul apropiado para uno de los más grandes guerreros de la Orden. Lanzado en 2005 en el set 7250 (Clone Scout Walker), esta variante captura a Obi-Wan durante su apogeo tanto como comandante militar como mentor Jedi de Anakin Skywalker. Como uno de los personajes más amados de Star Wars que aparece a través de todas las eras desde padawan hasta fantasma de la Fuerza, Obi-Wan es esencial para cualquier colección, con esta variante de Clone Wars particularmente valorada por representarlo en la cima de sus poderes antes de los eventos trágicos que lo forzarían al exilio en Tatooine.'
  },
  {
    no: 'sw0328',
    name: 'Clone Trooper (Episode 3, White)',
    en: 'This Clone Trooper represents the standard Phase 2 armored infantry who fought in the final battles of the Clone Wars shown in Revenge of the Sith, including the tragic execution of Order 66 that turned clone soldiers against their Jedi commanders. The minifigure features the evolved Phase 2 white armor with improved helmet design, black bodysuit visible at joints, and the clean appearance that would soon be marked by the moral stain of betraying the Jedi Order. Released in 2005, this Episode 3-era trooper represents the final evolution of clone design before the transition to stormtroopers. Standard white clones from this era are particularly significant for collectors as they represent both the Republic\'s military might at its peak and the tragic instruments of the Jedi\'s downfall, making them essential for recreating the Clone Wars\' heartbreaking conclusion when loyal soldiers became unknowing executioners.',
    de: 'Dieser Klonkrieger repräsentiert die Standard-Phase-2-gepanzerte Infanterie, die in den letzten Schlachten der Klonkriege kämpfte, die in Die Rache der Sith gezeigt wurden, einschließlich der tragischen Ausführung von Order 66, die Klon-Soldaten gegen ihre Jedi-Kommandanten wendete. Die Minifigur zeigt die entwickelte Phase-2-weiße Rüstung mit verbessertem Helmdesign, schwarzem Körperanzug sichtbar an Gelenken und dem sauberen Aussehen, das bald durch den moralischen Makel des Verrats am Jedi-Orden gezeichnet würde. 2005 veröffentlicht, repräsentiert dieser Episode-3-Ära-Soldat die finale Evolution des Klon-Designs vor dem Übergang zu Sturmtruppen. Standard-weiße Klone aus dieser Ära sind besonders bedeutsam für Sammler, da sie sowohl die militärische Macht der Republik auf ihrem Höhepunkt als auch die tragischen Instrumente des Untergangs der Jedi repräsentieren, was sie wesentlich macht für die Nachstellung des herzzerreißenden Abschlusses der Klonkriege, als loyale Soldaten zu unwissenden Henkern wurden.',
    fr: 'Ce Clone Trooper représente l\'infanterie blindée standard de Phase 2 qui a combattu dans les batailles finales des Guerres des Clones montrées dans La Revanche des Sith, y compris l\'exécution tragique de l\'Ordre 66 qui a retourné les soldats clones contre leurs commandants Jedi. La minifigurine présente l\'armure blanche évoluée de Phase 2 avec un design de casque amélioré, une combinaison noire visible aux articulations et l\'apparence propre qui serait bientôt marquée par la tache morale de trahir l\'Ordre Jedi. Sortie en 2005, ce soldat de l\'ère de l\'Épisode 3 représente l\'évolution finale de la conception clone avant la transition vers les stormtroopers. Les clones blancs standard de cette époque sont particulièrement significatifs pour les collectionneurs car ils représentent à la fois la puissance militaire de la République à son apogée et les instruments tragiques de la chute des Jedi, les rendant essentiels pour recréer la conclusion déchirante des Guerres des Clones lorsque des soldats loyaux sont devenus des bourreaux involontaires.',
    es: 'Este Clone Trooper representa a la infantería blindada estándar de Fase 2 que luchó en las batallas finales de las Guerras Clon mostradas en La Venganza de los Sith, incluyendo la trágica ejecución de la Orden 66 que volvió a soldados clon contra sus comandantes Jedi. La minifigura presenta la armadura blanca evolucionada de Fase 2 con diseño de casco mejorado, traje negro visible en articulaciones y la apariencia limpia que pronto estaría marcada por la mancha moral de traicionar a la Orden Jedi. Lanzado en 2005, este soldado de la era del Episodio 3 representa la evolución final del diseño clon antes de la transición a stormtroopers. Los clones blancos estándar de esta era son particularmente significativos para coleccionistas ya que representan tanto el poderío militar de la República en su apogeo como los instrumentos trágicos de la caída de los Jedi, haciéndolos esenciales para recrear la conclusión desgarradora de las Guerras Clon cuando soldados leales se convirtieron en verdugos involuntarios.'
  },
  {
    no: 'sw0329',
    name: 'Super Battle Droid (7250)',
    en: 'Super Battle Droids are heavily armored combat droids deployed by the Separatists as frontline assault units, featuring thicker armor plating and integrated arm-mounted blasters that made them far more dangerous than standard B1 battle droids throughout the Clone Wars. This minifigure captures the distinctive bulky build with blue-gray metallic coloring, hunched posture, and built-in weaponry that defined these fearsome machines. Released in 2005 in set 7250 (Clone Scout Walker), Super Battle Droids represent the Separatist military\'s attempt to create unstoppable mechanical soldiers. As one of the most iconic Separatist droid types appearing throughout the prequel trilogy and Clone Wars, Super Battle Droids are essential for army building Separatist forces, valued for their intimidating appearance and role as the muscle behind Count Dooku\'s droid armies that nearly overwhelmed the Republic during the war\'s darkest hours.',
    de: 'Super-Kampfdroiden sind schwer gepanzerte Kampfdroiden, die von den Separatisten als Frontangriffs-Einheiten eingesetzt wurden, mit dickerer Rüstungsplattierung und integrierten am Arm montierten Blastern, die sie während der Klonkriege weitaus gefährlicher machten als Standard-B1-Kampfdroiden. Diese Minifigur fängt den charakteristischen klobigen Körperbau mit blaugrauer metallischer Färbung, gebeugter Haltung und eingebauter Bewaffnung ein, die diese furchterregenden Maschinen definierten. 2005 im Set 7250 (Clone Scout Walker) veröffentlicht, repräsentieren Super-Kampfdroiden den Versuch des Separatisten-Militärs, unaufhaltsame mechanische Soldaten zu schaffen. Als einer der ikonischsten Separatisten-Droidentypen, die während der Prequel-Trilogie und Clone Wars erscheinen, sind Super-Kampfdroiden wesentlich für den Armeeaufbau von Separatisten-Streitkräften, geschätzt für ihr einschüchterndes Aussehen und ihre Rolle als Muskelkraft hinter Graf Dookus Droiden-Armeen, die die Republik während der dunkelsten Stunden des Krieges fast überwältigten.',
    fr: 'Les Super Droïdes de Combat sont des droïdes de combat lourdement blindés déployés par les Séparatistes comme unités d\'assaut de première ligne, présentant un blindage plus épais et des blasters intégrés montés sur les bras qui les rendaient bien plus dangereux que les droïdes de combat B1 standard tout au long des Guerres des Clones. Cette minifigurine capture la carrure volumineuse distinctive avec coloration métallique gris-bleu, posture voûtée et armement intégré qui définissaient ces machines redoutables. Sortie en 2005 dans le set 7250 (Clone Scout Walker), les Super Droïdes de Combat représentent la tentative de l\'armée Séparatiste de créer des soldats mécaniques inarrêtables. En tant que l\'un des types de droïdes Séparatistes les plus emblématiques apparaissant tout au long de la trilogie préquelle et Clone Wars, les Super Droïdes de Combat sont essentiels pour construire des forces Séparatistes, appréciés pour leur apparence intimidante et leur rôle de muscle derrière les armées de droïdes du Comte Dooku qui ont presque submergé la République pendant les heures les plus sombres de la guerre.',
    es: 'Los Super Droides de Batalla son droides de combate fuertemente blindados desplegados por los Separatistas como unidades de asalto de primera línea, presentando blindaje más grueso y blásters integrados montados en brazos que los hicieron mucho más peligrosos que droides de batalla B1 estándar a lo largo de las Guerras Clon. Esta minifigura captura la distintiva construcción voluminosa con coloración metálica gris-azul, postura encorvada y armamento incorporado que definieron estas máquinas temibles. Lanzado en 2005 en el set 7250 (Clone Scout Walker), los Super Droides de Batalla representan el intento del ejército Separatista de crear soldados mecánicos imparables. Como uno de los tipos de droides Separatistas más icónicos apareciendo a lo largo de la trilogía precuela y Clone Wars, los Super Droides de Batalla son esenciales para construir ejércitos de fuerzas Separatistas, valorados por su apariencia intimidante y papel como músculo detrás de los ejércitos de droides del Conde Dooku que casi abrumaron a la República durante las horas más oscuras de la guerra.'
  },
  {
    no: 'sw0330',
    name: 'Battle Droid (7250)',
    en: 'Battle Droids are the mass-produced skeletal combat robots that formed the backbone of the Separatist Droid Army during the Clone Wars, designed by the Trade Federation for cost-effective military force despite their limited intelligence and fragility. This minifigure features the characteristic tan coloring, thin skeletal frame, and distinctive elongated head design that made these droids instantly recognizable throughout the prequel trilogy. Released in 2005 in set 7250 (Clone Scout Walker), this standard battle droid represents the countless mechanical soldiers who fought for the Separatist cause. Battle Droids are perpetually essential for army building Separatist forces as their sheer numbers were their primary advantage, with collectors needing multiple figures to recreate the overwhelming droid formations that nearly conquered the Republic through quantity over quality, making them fundamental pieces for any Clone Wars battle scene.',
    de: 'Kampfdroiden sind die massenproduzierten skelettartigen Kampfroboter, die das Rückgrat der Separatisten-Droiden-Armee während der Klonkriege bildeten, entworfen von der Handelsföderation für kosteneffektive Militärmacht trotz ihrer begrenzten Intelligenz und Zerbrechlichkeit. Diese Minifigur zeigt die charakteristische beige Färbung, dünnen Skelettrahmen und charakteristische längliche Kopfform, die diese Droiden während der Prequel-Trilogie sofort erkennbar machten. 2005 im Set 7250 (Clone Scout Walker) veröffentlicht, repräsentiert dieser Standard-Kampfdroide die zahllosen mechanischen Soldaten, die für die Separatisten-Sache kämpften. Kampfdroiden sind dauerhaft wesentlich für den Armeeaufbau von Separatisten-Streitkräften, da ihre schiere Anzahl ihr primärer Vorteil war, wobei Sammler mehrere Figuren benötigen, um die überwältigenden Droiden-Formationen nachzustellen, die die Republik durch Quantität über Qualität fast eroberten, was sie zu fundamentalen Stücken für jede Clone Wars-Kampfszene macht.',
    fr: 'Les Droïdes de Combat sont les robots de combat squelettiques produits en masse qui formaient la colonne vertébrale de l\'Armée Droïde Séparatiste pendant les Guerres des Clones, conçus par la Fédération du Commerce pour une force militaire rentable malgré leur intelligence limitée et leur fragilité. Cette minifigurine présente la coloration beige caractéristique, un cadre squelettique mince et un design de tête allongé distinctif qui rendaient ces droïdes instantanément reconnaissables tout au long de la trilogie préquelle. Sortie en 2005 dans le set 7250 (Clone Scout Walker), ce droïde de combat standard représente les innombrables soldats mécaniques qui ont combattu pour la cause Séparatiste. Les Droïdes de Combat sont perpétuellement essentiels pour construire des forces Séparatistes car leur simple nombre était leur avantage principal, les collectionneurs ayant besoin de plusieurs figurines pour recréer les formations de droïdes écrasantes qui ont presque conquis la République par la quantité plutôt que la qualité, en faisant des pièces fondamentales pour toute scène de bataille Clone Wars.',
    es: 'Los Droides de Batalla son los robots de combate esqueléticos producidos en masa que formaron la columna vertebral del Ejército Droide Separatista durante las Guerras Clon, diseñados por la Federación de Comercio para fuerza militar rentable a pesar de su inteligencia limitada y fragilidad. Esta minifigura presenta la coloración beige característica, marco esquelético delgado y distintivo diseño de cabeza alargada que hicieron a estos droides instantáneamente reconocibles a lo largo de la trilogía precuela. Lanzado en 2005 en el set 7250 (Clone Scout Walker), este droide de batalla estándar representa a los incontables soldados mecánicos que lucharon por la causa Separatista. Los Droides de Batalla son perpetuamente esenciales para construir ejércitos de fuerzas Separatistas ya que su simple número era su ventaja principal, con coleccionistas necesitando múltiples figuras para recrear las formaciones de droides abrumadoras que casi conquistaron la República mediante cantidad sobre calidad, haciéndolos piezas fundamentales para cualquier escena de batalla de Clone Wars.'
  },
  {
    no: 'sw0331',
    name: 'Clone Trooper (Episode 3, Green Markings)',
    en: 'This Clone Trooper features green armor markings indicating specialized training or unit designation within the Grand Army of the Republic during Revenge of the Sith, representing the diverse roles and battalions that made the clone military an effective fighting force. The minifigure displays Phase 2 white armor with distinctive green striping, updated helmet design, and equipment showing the evolution of clone gear by the war\'s final battles. Released in 2005, this green-marked variant represents the specialized clone units who served alongside Jedi commanders during the Clone Wars\' conclusion. Clone Troopers with color-coded markings are particularly valued by collectors for building diverse unit displays, as the green designation distinguishes this trooper from standard white clones and other color variants, allowing collectors to recreate the specialized battalions and companies that gave the Republic tactical flexibility across different combat environments and mission types.',
    de: 'Dieser Klonkrieger zeigt grüne Rüstungsmarkierungen, die spezialisiertes Training oder Einheitenbezeichnung innerhalb der Großen Armee der Republik während Die Rache der Sith anzeigen und die vielfältigen Rollen und Bataillone repräsentieren, die das Klon-Militär zu einer effektiven Kampftruppe machten. Die Minifigur zeigt Phase-2-weiße Rüstung mit charakteristischen grünen Streifen, aktualisiertem Helmdesign und Ausrüstung, die die Evolution der Klon-Ausrüstung in den finalen Schlachten des Krieges zeigt. 2005 veröffentlicht, repräsentiert diese grün markierte Variante die spezialisierten Klon-Einheiten, die während des Abschlusses der Klonkriege an der Seite von Jedi-Kommandanten dienten. Klonkrieger mit farbkodierten Markierungen werden von Sammlern besonders geschätzt für den Aufbau vielfältiger Einheiten-Displays, da die grüne Bezeichnung diesen Soldaten von Standard-weißen Klonen und anderen Farbvarianten unterscheidet und es Sammlern ermöglicht, die spezialisierten Bataillone und Kompanien nachzustellen, die der Republik taktische Flexibilität über verschiedene Kampfumgebungen und Missionstypen hinweg gaben.',
    fr: 'Ce Clone Trooper présente des marques d\'armure vertes indiquant une formation spécialisée ou une désignation d\'unité au sein de la Grande Armée de la République pendant La Revanche des Sith, représentant les divers rôles et bataillons qui ont fait de l\'armée clone une force de combat efficace. La minifigurine affiche une armure blanche de Phase 2 avec des rayures vertes distinctives, un design de casque mis à jour et un équipement montrant l\'évolution de l\'équipement clone lors des batailles finales de la guerre. Sortie en 2005, cette variante marquée de vert représente les unités clones spécialisées qui ont servi aux côtés des commandants Jedi pendant la conclusion des Guerres des Clones. Les Clone Troopers avec des marques codées par couleur sont particulièrement appréciés par les collectionneurs pour construire des displays d\'unités diverses, car la désignation verte distingue ce soldat des clones blancs standard et d\'autres variantes de couleur, permettant aux collectionneurs de recréer les bataillons et compagnies spécialisés qui ont donné à la République une flexibilité tactique à travers différents environnements de combat et types de missions.',
    es: 'Este Clone Trooper presenta marcas de armadura verdes indicando entrenamiento especializado o designación de unidad dentro del Gran Ejército de la República durante La Venganza de los Sith, representando los diversos roles y batallones que hicieron del ejército clon una fuerza de combate efectiva. La minifigura muestra armadura blanca de Fase 2 con rayas verdes distintivas, diseño de casco actualizado y equipo mostrando la evolución del equipo clon para las batallas finales de la guerra. Lanzado en 2005, esta variante marcada en verde representa las unidades clon especializadas que sirvieron junto a comandantes Jedi durante la conclusión de las Guerras Clon. Los Clone Troopers con marcas codificadas por color son particularmente valorados por coleccionistas para construir exhibiciones de unidades diversas, ya que la designación verde distingue a este soldado de clones blancos estándar y otras variantes de color, permitiendo a coleccionistas recrear los batallones y compañías especializados que dieron a la República flexibilidad táctica a través de diferentes entornos de combate y tipos de misiones.'
  },
  {
    no: 'sw0332',
    name: 'Wookiee Warrior (7258)',
    en: 'This Wookiee Warrior represents the fierce defenders of Kashyyyk who fought alongside Republic clone forces during the planet\'s invasion in Revenge of the Sith, combining their species\' legendary strength and loyalty with modern weaponry to protect their forested homeworld. The minifigure features characteristic brown fur, bandolier with ammunition pouches, and powerful build that embodies the Wookiee reputation as formidable hand-to-hand combatants. Released in 2005 in set 7258 (Wookiee Attack), this warrior represents the indigenous forces who defended their tree cities during the Clone Wars\' final battles. Wookiee Warriors are valued by collectors for their connection to one of Star Wars\' most beloved species, their role in the crucial Battle of Kashyyyk where Yoda commanded clone forces, and their representation of the diverse alien allies who fought for freedom, making them essential for recreating the defense of the Wookiee homeworld that gave the galaxy heroes like Chewbacca.',
    de: 'Dieser Wookiee-Krieger repräsentiert die wilden Verteidiger von Kashyyyk, die während der Invasion des Planeten in Die Rache der Sith an der Seite republikanischer Klon-Streitkräfte kämpften und die legendäre Stärke und Loyalität ihrer Spezies mit modernen Waffen kombinierten, um ihre bewaldete Heimatwelt zu schützen. Die Minifigur zeigt charakteristisches braunes Fell, Bandolier mit Munitionstaschen und kräftigen Körperbau, der den Wookiee-Ruf als beeindruckende Nahkämpfer verkörpert. 2005 im Set 7258 (Wookiee Attack) veröffentlicht, repräsentiert dieser Krieger die einheimischen Streitkräfte, die ihre Baumstädte während der finalen Schlachten der Klonkriege verteidigten. Wookiee-Krieger werden von Sammlern geschätzt für ihre Verbindung zu einer der beliebtesten Spezies in Star Wars, ihre Rolle in der entscheidenden Schlacht von Kashyyyk, wo Yoda Klon-Streitkräfte kommandierte, und ihre Darstellung der vielfältigen außerirdischen Verbündeten, die für Freiheit kämpften, was sie wesentlich macht für die Nachstellung der Verteidigung der Wookiee-Heimatwelt, die der Galaxis Helden wie Chewbacca gab.',
    fr: 'Ce Guerrier Wookiee représente les féroces défenseurs de Kashyyyk qui ont combattu aux côtés des forces clones de la République pendant l\'invasion de la planète dans La Revanche des Sith, combinant la force et la loyauté légendaires de leur espèce avec des armes modernes pour protéger leur monde natal forestier. La minifigurine présente une fourrure brune caractéristique, une bandoulière avec des poches de munitions et une carrure puissante qui incarne la réputation des Wookiees comme combattants redoutables au corps à corps. Sortie en 2005 dans le set 7258 (Wookiee Attack), ce guerrier représente les forces indigènes qui ont défendu leurs cités dans les arbres pendant les batailles finales des Guerres des Clones. Les Guerriers Wookiees sont appréciés par les collectionneurs pour leur connexion à l\'une des espèces les plus aimées de Star Wars, leur rôle dans la Bataille cruciale de Kashyyyk où Yoda commandait les forces clones, et leur représentation des alliés extraterrestres divers qui ont combattu pour la liberté, les rendant essentiels pour recréer la défense du monde natal Wookiee qui a donné à la galaxie des héros comme Chewbacca.',
    es: 'Este Guerrero Wookiee representa a los feroces defensores de Kashyyyk que lucharon junto a fuerzas clon de la República durante la invasión del planeta en La Venganza de los Sith, combinando la legendaria fuerza y lealtad de su especie con armamento moderno para proteger su mundo natal boscoso. La minifigura presenta pelaje marrón característico, bandolera con bolsas de munición y complexión poderosa que encarna la reputación Wookiee como formidables combatientes cuerpo a cuerpo. Lanzado en 2005 en el set 7258 (Wookiee Attack), este guerrero representa a las fuerzas indígenas que defendieron sus ciudades en árboles durante las batallas finales de las Guerras Clon. Los Guerreros Wookiee son valorados por coleccionistas por su conexión con una de las especies más amadas de Star Wars, su papel en la crucial Batalla de Kashyyyk donde Yoda comandó fuerzas clon, y su representación de los diversos aliados alienígenas que lucharon por la libertad, haciéndolos esenciales para recrear la defensa del mundo natal Wookiee que le dio a la galaxia héroes como Chewbacca.'
  },
  {
    no: 'sw0333',
    name: 'Clone Trooper (Episode 3, Dark Red Markings)',
    en: 'This Clone Trooper features dark red armor markings indicating elite specialized training or command rank within the Grand Army of the Republic during Revenge of the Sith, representing the highly trained soldiers who served in critical roles during the Clone Wars\' final campaigns. The minifigure displays Phase 2 white armor with distinctive dark red striping, advanced helmet design, and equipment showing the sophistication of clone forces by the war\'s end. Released in 2005, this dark red-marked variant represents the specialized clone units who demonstrated exceptional skill and leadership. Clone Troopers with unique color markings are essential for collectors building diverse battalion displays, as the dark red designation distinguishes elite or command personnel from standard infantry, allowing collectors to recreate the military hierarchy and specialized units that made the Republic\'s clone army the most effective fighting force in the galaxy during their brief existence.',
    de: 'Dieser Klonkrieger zeigt dunkelrote Rüstungsmarkierungen, die Elite-Spezialtraining oder Kommandorang innerhalb der Großen Armee der Republik während Die Rache der Sith anzeigen und die hochtrainierten Soldaten repräsentieren, die in kritischen Rollen während der finalen Kampagnen der Klonkriege dienten. Die Minifigur zeigt Phase-2-weiße Rüstung mit charakteristischen dunkelroten Streifen, fortschrittlichem Helmdesign und Ausrüstung, die die Raffinesse der Klon-Streitkräfte am Ende des Krieges zeigt. 2005 veröffentlicht, repräsentiert diese dunkelrot markierte Variante die spezialisierten Klon-Einheiten, die außergewöhnliche Fähigkeiten und Führung demonstrierten. Klonkrieger mit einzigartigen Farbmarkierungen sind wesentlich für Sammler, die vielfältige Bataillons-Displays aufbauen, da die dunkelrote Bezeichnung Elite- oder Kommandopersonal von Standard-Infanterie unterscheidet und es Sammlern ermöglicht, die Militärhierarchie und spezialisierten Einheiten nachzustellen, die die Klon-Armee der Republik zur effektivsten Kampftruppe in der Galaxis während ihrer kurzen Existenz machten.',
    fr: 'Ce Clone Trooper présente des marques d\'armure rouge foncé indiquant une formation spécialisée d\'élite ou un rang de commandement au sein de la Grande Armée de la République pendant La Revanche des Sith, représentant les soldats hautement entraînés qui ont servi dans des rôles critiques pendant les campagnes finales des Guerres des Clones. La minifigurine affiche une armure blanche de Phase 2 avec des rayures rouge foncé distinctives, un design de casque avancé et un équipement montrant la sophistication des forces clones à la fin de la guerre. Sortie en 2005, cette variante marquée de rouge foncé représente les unités clones spécialisées qui ont démontré des compétences et un leadership exceptionnels. Les Clone Troopers avec des marques de couleur uniques sont essentiels pour les collectionneurs construisant des displays de bataillons divers, car la désignation rouge foncé distingue le personnel d\'élite ou de commandement de l\'infanterie standard, permettant aux collectionneurs de recréer la hiérarchie militaire et les unités spécialisées qui ont fait de l\'armée clone de la République la force de combat la plus efficace de la galaxie pendant leur brève existence.',
    es: 'Este Clone Trooper presenta marcas de armadura rojo oscuro indicando entrenamiento especializado de élite o rango de comando dentro del Gran Ejército de la República durante La Venganza de los Sith, representando a los soldados altamente entrenados que sirvieron en roles críticos durante las campañas finales de las Guerras Clon. La minifigura muestra armadura blanca de Fase 2 con rayas rojo oscuro distintivas, diseño de casco avanzado y equipo mostrando la sofisticación de fuerzas clon al final de la guerra. Lanzado en 2005, esta variante marcada en rojo oscuro representa las unidades clon especializadas que demostraron habilidad y liderazgo excepcionales. Los Clone Troopers con marcas de color únicas son esenciales para coleccionistas construyendo exhibiciones de batallones diversos, ya que la designación rojo oscuro distingue personal de élite o comando de infantería estándar, permitiendo a coleccionistas recrear la jerarquía militar y unidades especializadas que hicieron del ejército clon de la República la fuerza de combate más efectiva en la galaxia durante su breve existencia.'
  }
];

async function saveBatch040() {
  console.log('💾 Saving batch 040 (sw0324-sw0333) - 10 minifigs...\n');

  let saved = 0;
  let skipped = 0;

  for (const m of batch040) {
    try {
      await prisma.minifigCatalog.update({
        where: { minifigure_no: m.no },
        data: {
          description_en: m.en,
          description_de: m.de,
          description_fr: m.fr,
          description_es: m.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        }
      });
      console.log(`  ✅ ${m.no}: ${m.name}`);
      saved++;
    } catch (error: any) {
      console.log(`  ⚠️  ${m.no}: NOT IN DATABASE (skipped)`);
      skipped++;
    }
  }

  console.log(`\n✨ Batch 040 complete: ${saved} saved, ${skipped} skipped (40 descriptions)\n`);
  await prisma.$disconnect();
}

saveBatch040().catch(console.error);
