import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0439',
    name: 'Barriss Offee',
    en: 'Barriss Offee is the Mirialan Jedi Padawan who served under Luminara Unduli and fought in the Battle of Geonosis in Attack of the Clones. This minifigure depicts the young Jedi with her distinctive blue geometric facial tattoos, dark hooded robes, and blue-bladed lightsaber. Known for her healing abilities and later tragic fall from the Jedi path in The Clone Wars series, Barriss represents the pressures faced by young Jedi during wartime. Released in limited Geonosis battle sets, this minifigure is sought after by Clone Wars collectors for her connection to the animated series.',
    de: 'Barriss Offee ist die Mirialanische Jedi-Padawan, die unter Luminara Unduli diente und in der Schlacht von Geonosis in Angriff der Klonkrieger kämpfte. Diese Minifigur zeigt die junge Jedi mit ihren charakteristischen blauen geometrischen Gesichtstätowierungen, dunklen Kapuzenroben und blauklingigem Lichtschwert. Bekannt für ihre Heilfähigkeiten und späteren tragischen Fall vom Jedi-Pfad in der Klonkriege-Serie, repräsentiert Barriss die Belastungen, denen junge Jedi während der Kriegszeit ausgesetzt waren. Veröffentlicht in begrenzten Geonosis-Schlacht-Sets, wird diese Minifigur von Klonkriegs-Sammlern wegen ihrer Verbindung zur animierten Serie gesucht.',
    fr: 'Barriss Offee est la Padawan Jedi Mirialan qui a servi sous Luminara Unduli et combattu dans la Bataille de Geonosis dans L\'Attaque des Clones. Cette minifigurine dépeint la jeune Jedi avec ses tatouages faciaux géométriques bleus distinctifs, robes à capuche sombres, et sabre laser à lame bleue. Connue pour ses capacités de guérison et sa chute tragique ultérieure de la voie Jedi dans la série The Clone Wars, Barriss représente les pressions auxquelles sont confrontés les jeunes Jedi en temps de guerre. Sortie dans des sets de bataille de Geonosis limités, cette minifigurine est recherchée par les collectionneurs des Guerres des Clones pour sa connexion à la série animée.',
    es: 'Barriss Offee es la Padawan Jedi Mirialan que sirvió bajo Luminara Unduli y luchó en la Batalla de Geonosis en El Ataque de los Clones. Esta minifigura representa a la joven Jedi con sus distintivos tatuajes faciales geométricos azules, túnicas oscuras con capucha y sable de luz de hoja azul. Conocida por sus habilidades de curación y su posterior caída trágica del camino Jedi en la serie The Clone Wars, Barriss representa las presiones enfrentadas por jóvenes Jedi durante tiempos de guerra. Lanzada en sets limitados de batalla de Geonosis, esta minifigura es buscada por coleccionistas de las Guerras Clon por su conexión con la serie animada.'
  },
  {
    no: 'sw0440',
    name: 'Shaak Ti',
    en: 'Shaak Ti is the Togruta Jedi Master known for her distinctive head-tails, facial markings, and role overseeing the clone training facilities on Kamino. This minifigure depicts the elegant Jedi with her characteristic orange skin, white facial patterns, striped head-tails (montrals and lekku), and blue-bladed lightsaber. Fighting on Geonosis and later playing a crucial role in the Clone Wars, Shaak Ti represents the Jedi\'s connection to the clone army. Released in various Clone Wars sets, this unique alien Jedi is popular with collectors for her distinctive Togruta design.',
    de: 'Shaak Ti ist die Togruta-Jedi-Meisterin, bekannt für ihre charakteristischen Kopfschwänze, Gesichtsmarkierungen und Rolle bei der Überwachung der Klon-Trainingseinrichtungen auf Kamino. Diese Minifigur zeigt die elegante Jedi mit ihrer charakteristischen orangen Haut, weißen Gesichtsmustern, gestreiften Kopfschwänzen (Montrals und Lekku) und blauklingigem Lichtschwert. Kämpfend auf Geonosis und später eine entscheidende Rolle in den Klonkriegen spielend, repräsentiert Shaak Ti die Verbindung der Jedi zur Klon-Armee. Veröffentlicht in verschiedenen Klonkriegs-Sets, ist diese einzigartige außerirdische Jedi bei Sammlern wegen ihres charakteristischen Togruta-Designs beliebt.',
    fr: 'Shaak Ti est la Maître Jedi Togruta connue pour ses queues de tête distinctives, marques faciales, et rôle supervisant les installations d\'entraînement de clones sur Kamino. Cette minifigurine dépeint la Jedi élégante avec sa peau orange caractéristique, motifs faciaux blancs, queues de tête rayées (montrals et lekku), et sabre laser à lame bleue. Combattant sur Geonosis et jouant plus tard un rôle crucial dans les Guerres des Clones, Shaak Ti représente la connexion des Jedi à l\'armée de clones. Sortie dans divers sets des Guerres des Clones, cette Jedi extraterrestre unique est populaire auprès des collectionneurs pour son design Togruta distinctif.',
    es: 'Shaak Ti es la Maestra Jedi Togruta conocida por sus distintivas colas de cabeza, marcas faciales y papel supervisando las instalaciones de entrenamiento de clones en Kamino. Esta minifigura representa a la elegante Jedi con su característica piel naranja, patrones faciales blancos, colas de cabeza rayadas (montrals y lekku) y sable de luz de hoja azul. Luchando en Geonosis y más tarde jugando un papel crucial en las Guerras Clon, Shaak Ti representa la conexión de los Jedi con el ejército clon. Lanzada en varios sets de las Guerras Clon, esta Jedi alienígena única es popular entre coleccionistas por su distintivo diseño Togruta.'
  },
  {
    no: 'sw0441',
    name: 'Coleman Trebor',
    en: 'Coleman Trebor is the Vurk Jedi Master who attempted to assassinate Count Dooku during the Battle of Geonosis but was killed by Jango Fett in Attack of the Clones. This minifigure depicts the reptilian Jedi with his distinctive elongated head, green skin, Jedi robes, and green-bladed lightsaber. His brief but memorable appearance showcases the dangers faced by the Jedi during the Clone Wars outbreak. Released in limited Geonosis arena sets, this obscure Jedi is valued by completist collectors seeking all Jedi Council members.',
    de: 'Coleman Trebor ist der Vurk-Jedi-Meister, der versuchte, Graf Dooku während der Schlacht von Geonosis zu ermorden, aber von Jango Fett in Angriff der Klonkrieger getötet wurde. Diese Minifigur zeigt den reptilienartigen Jedi mit seinem charakteristischen verlängerten Kopf, grüner Haut, Jedi-Roben und grünklingigem Lichtschwert. Sein kurzer, aber einprägsamer Auftritt zeigt die Gefahren, denen die Jedi während des Ausbruchs der Klonkriege ausgesetzt waren. Veröffentlicht in begrenzten Geonosis-Arena-Sets, wird dieser obskure Jedi von Komplettisten-Sammlern geschätzt, die alle Jedi-Ratsmitglieder suchen.',
    fr: 'Coleman Trebor est le Maître Jedi Vurk qui a tenté d\'assassiner le Comte Dooku pendant la Bataille de Geonosis mais a été tué par Jango Fett dans L\'Attaque des Clones. Cette minifigurine dépeint le Jedi reptilien avec sa tête allongée distinctive, peau verte, robes Jedi, et sabre laser à lame verte. Son apparition brève mais mémorable montre les dangers auxquels sont confrontés les Jedi pendant le déclenchement des Guerres des Clones. Sortie dans des sets d\'arène de Geonosis limités, ce Jedi obscur est apprécié par les collectionneurs complétistes cherchant tous les membres du Conseil Jedi.',
    es: 'Coleman Trebor es el Maestro Jedi Vurk que intentó asesinar al Conde Dooku durante la Batalla de Geonosis pero fue asesinado por Jango Fett en El Ataque de los Clones. Esta minifigura representa al Jedi reptiliano con su distintiva cabeza alargada, piel verde, túnicas Jedi y sable de luz de hoja verde. Su aparición breve pero memorable muestra los peligros enfrentados por los Jedi durante el estallido de las Guerras Clon. Lanzada en sets limitados de arena de Geonosis, este Jedi oscuro es valorado por coleccionistas completistas que buscan todos los miembros del Consejo Jedi.'
  },
  {
    no: 'sw0442',
    name: 'Saesee Tiin',
    en: 'Saesee Tiin is the Iktotchi Jedi Master and exceptional starfighter pilot who sits on the Jedi Council in Attack of the Clones. This minifigure depicts the horned alien Jedi with his distinctive cranial horns, brown skin tone, traditional Jedi robes, and lightsaber. Known for his telepathic abilities and piloting skills, Saesee represents the Jedi\'s diverse species and talents. Released in various Clone Wars sets, this Council member is sought by collectors completing their Jedi Council displays.',
    de: 'Saesee Tiin ist der Iktotchi-Jedi-Meister und außergewöhnliche Sternenjägerpilot, der im Jedi-Rat in Angriff der Klonkrieger sitzt. Diese Minifigur zeigt den gehörnten außerirdischen Jedi mit seinen charakteristischen Schädelhörnern, braunem Hautton, traditionellen Jedi-Roben und Lichtschwert. Bekannt für seine telepathischen Fähigkeiten und Pilotenfähigkeiten, repräsentiert Saesee die vielfältigen Spezies und Talente der Jedi. Veröffentlicht in verschiedenen Klonkriegs-Sets, wird dieses Ratsmitglied von Sammlern gesucht, die ihre Jedi-Rats-Displays vervollständigen.',
    fr: 'Saesee Tiin est le Maître Jedi Iktotchi et pilote de chasseur stellaire exceptionnel qui siège au Conseil Jedi dans L\'Attaque des Clones. Cette minifigurine dépeint le Jedi extraterrestre cornu avec ses cornes crâniennes distinctives, ton de peau brun, robes Jedi traditionnelles, et sabre laser. Connu pour ses capacités télépathiques et ses compétences de pilotage, Saesee représente les espèces et talents divers des Jedi. Sortie dans divers sets des Guerres des Clones, ce membre du Conseil est recherché par les collectionneurs complétant leurs displays du Conseil Jedi.',
    es: 'Saesee Tiin es el Maestro Jedi Iktotchi y piloto de caza estelar excepcional que se sienta en el Consejo Jedi en El Ataque de los Clones. Esta minifigura representa al Jedi alienígena con cuernos con sus distintivos cuernos craneales, tono de piel marrón, túnicas Jedi tradicionales y sable de luz. Conocido por sus habilidades telepáticas y habilidades de pilotaje, Saesee representa las diversas especies y talentos de los Jedi. Lanzada en varios sets de las Guerras Clon, este miembro del Consejo es buscado por coleccionistas completando sus exhibiciones del Consejo Jedi.'
  },
  {
    no: 'sw0443',
    name: 'Stass Allie',
    en: 'Stass Allie is the Tholothian Jedi Master and skilled healer who serves on the Jedi Council during the Clone Wars. This minifigure depicts the female Jedi with her distinctive tendrils and head covering, Jedi robes, and blue-bladed lightsaber. As a cousin to Adi Gallia, Stass represents the familial connections within the Jedi Order. Released in limited Clone Wars sets, this lesser-known Council member is valued by completist collectors seeking all Jedi Masters.',
    de: 'Stass Allie ist die Tholothianische Jedi-Meisterin und geschickte Heilerin, die während der Klonkriege im Jedi-Rat dient. Diese Minifigur zeigt die weibliche Jedi mit ihren charakteristischen Ranken und Kopfbedeckung, Jedi-Roben und blauklingigem Lichtschwert. Als Cousine von Adi Gallia repräsentiert Stass die familiären Verbindungen innerhalb des Jedi-Ordens. Veröffentlicht in begrenzten Klonkriegs-Sets, wird dieses weniger bekannte Ratsmitglied von Komplettisten-Sammlern geschätzt, die alle Jedi-Meister suchen.',
    fr: 'Stass Allie est la Maître Jedi Tholothienne et guérisseuse qualifiée qui sert au Conseil Jedi pendant les Guerres des Clones. Cette minifigurine dépeint la Jedi féminine avec ses vrilles distinctives et couvre-chef, robes Jedi, et sabre laser à lame bleue. En tant que cousine d\'Adi Gallia, Stass représente les connexions familiales au sein de l\'Ordre Jedi. Sortie dans des sets des Guerres des Clones limités, ce membre du Conseil moins connu est apprécié par les collectionneurs complétistes cherchant tous les Maîtres Jedi.',
    es: 'Stass Allie es la Maestra Jedi Tholothiana y hábil sanadora que sirve en el Consejo Jedi durante las Guerras Clon. Esta minifigura representa a la Jedi femenina con sus distintivos zarcillos y cubierta de cabeza, túnicas Jedi y sable de luz de hoja azul. Como prima de Adi Gallia, Stass representa las conexiones familiares dentro de la Orden Jedi. Lanzada en sets limitados de las Guerras Clon, este miembro del Consejo menos conocido es valorado por coleccionistas completistas que buscan todos los Maestros Jedi.'
  },
  {
    no: 'sw0444',
    name: 'Obi-Wan Kenobi - Episode III',
    en: 'Obi-Wan Kenobi as a Jedi General leads clone forces during the Clone Wars and faces his greatest tragedy in confronting fallen Anakin on Mustafar in Revenge of the Sith. This minifigure depicts the war-weary Obi-Wan with brown Jedi robes, clone armor pieces, and his blue-bladed lightsaber. From rescuing Palpatine to his heartbreaking duel with Anakin, this version represents Obi-Wan at his most tested. Released in numerous Episode III sets, this variant captures the legendary Jedi Master during the fall of the Republic.',
    de: 'Obi-Wan Kenobi als Jedi-General führt Klonstruppen während der Klonkriege und steht seiner größten Tragödie gegenüber, als er den gefallenen Anakin auf Mustafar in Die Rache der Sith konfrontiert. Diese Minifigur zeigt den kriegsmüden Obi-Wan mit braunen Jedi-Roben, Klon-Rüstungsteilen und seinem blauklingigen Lichtschwert. Von der Rettung Palpatines bis zu seinem herzzerreißenden Duell mit Anakin repräsentiert diese Version Obi-Wan in seinem am meisten geprüften Zustand. Veröffentlicht in zahlreichen Episode III-Sets, erfasst diese Variante den legendären Jedi-Meister während des Falls der Republik.',
    fr: 'Obi-Wan Kenobi en tant que Général Jedi dirige les forces de clones pendant les Guerres des Clones et fait face à sa plus grande tragédie en confrontant Anakin déchu sur Mustafar dans La Revanche des Sith. Cette minifigurine dépeint l\'Obi-Wan las de guerre avec robes Jedi brunes, pièces d\'armure de clone, et son sabre laser à lame bleue. Du sauvetage de Palpatine à son duel déchirant avec Anakin, cette version représente Obi-Wan à son plus éprouvé. Sortie dans de nombreux sets Épisode III, cette variante capture le légendaire Maître Jedi pendant la chute de la République.',
    es: 'Obi-Wan Kenobi como General Jedi lidera fuerzas clon durante las Guerras Clon y enfrenta su mayor tragedia al confrontar al caído Anakin en Mustafar en La Venganza de los Sith. Esta minifigura representa al Obi-Wan cansado de guerra con túnicas Jedi marrones, piezas de armadura clon y su sable de luz de hoja azul. Desde rescatar a Palpatine hasta su desgarrador duelo con Anakin, esta versión representa a Obi-Wan en su momento más probado. Lanzada en numerosos sets del Episodio III, esta variante captura al legendario Maestro Jedi durante la caída de la República.'
  },
  {
    no: 'sw0445',
    name: 'Anakin Skywalker - Episode III',
    en: 'Anakin Skywalker as a Jedi Knight fights in the Clone Wars and ultimately falls to the dark side, becoming Darth Vader in Revenge of the Sith. This minifigure depicts Anakin in his darker Jedi robes with battle-worn appearance and blue-bladed lightsaber before his transformation. From rescuing Palpatine to his tragic duel on Mustafar, this version captures Anakin at his most conflicted. Released in numerous Episode III sets, this variant represents the final stage of Anakin\'s descent into darkness and remains one of the most pivotal character moments in Star Wars.',
    de: 'Anakin Skywalker als Jedi-Ritter kämpft in den Klonkriegen und fällt letztendlich der dunklen Seite anheim und wird Darth Vader in Die Rache der Sith. Diese Minifigur zeigt Anakin in seinen dunkleren Jedi-Roben mit kampferprobtem Aussehen und blauklingigem Lichtschwert vor seiner Transformation. Von der Rettung Palpatines bis zu seinem tragischen Duell auf Mustafar erfasst diese Version Anakin in seinem zerrissensten Zustand. Veröffentlicht in zahlreichen Episode III-Sets, repräsentiert diese Variante die finale Phase von Anakins Abstieg in die Dunkelheit und bleibt einer der entscheidendsten Charaktermomente in Star Wars.',
    fr: 'Anakin Skywalker en tant que Chevalier Jedi combat dans les Guerres des Clones et tombe finalement au côté obscur, devenant Darth Vader dans La Revanche des Sith. Cette minifigurine dépeint Anakin dans ses robes Jedi plus sombres avec apparence usée par la bataille et sabre laser à lame bleue avant sa transformation. Du sauvetage de Palpatine à son duel tragique sur Mustafar, cette version capture Anakin à son plus conflictuel. Sortie dans de nombreux sets Épisode III, cette variante représente l\'étape finale de la descente d\'Anakin dans les ténèbres et reste l\'un des moments de personnage les plus cruciaux dans Star Wars.',
    es: 'Anakin Skywalker como Caballero Jedi lucha en las Guerras Clon y finalmente cae al lado oscuro, convirtiéndose en Darth Vader en La Venganza de los Sith. Esta minifigura representa a Anakin en sus túnicas Jedi más oscuras con apariencia desgastada por batalla y sable de luz de hoja azul antes de su transformación. Desde rescatar a Palpatine hasta su trágico duelo en Mustafar, esta versión captura a Anakin en su momento más conflictuado. Lanzada en numerosos sets del Episodio III, esta variante representa la etapa final del descenso de Anakin a la oscuridad y sigue siendo uno de los momentos de personaje más cruciales en Star Wars.'
  },
  {
    no: 'sw0446',
    name: 'Darth Vader - Transformation',
    en: 'Darth Vader\'s transformation represents the moment when the burned and defeated Anakin Skywalker is rebuilt as the Dark Lord in Revenge of the Sith. This minifigure depicts Vader immediately after his reconstruction with his iconic black armor, cape, helmet, and life support systems. The tragic moment when Vader learns of Padmé\'s death and unleashes his anguish marks the complete fall of Anakin. Released in medical bay and transformation chamber sets, this variant represents one of cinema\'s most tragic villain origins.',
    de: 'Darth Vaders Transformation repräsentiert den Moment, in dem der verbrannte und besiegte Anakin Skywalker als Dunkler Lord in Die Rache der Sith wiederaufgebaut wird. Diese Minifigur zeigt Vader unmittelbar nach seiner Rekonstruktion mit seiner ikonischen schwarzen Rüstung, Umhang, Helm und Lebenserhaltungssystemen. Der tragische Moment, in dem Vader von Padmés Tod erfährt und seine Qual entfesselt, markiert Anakins vollständigen Fall. Veröffentlicht in Medizinstation- und Transformationskammer-Sets, repräsentiert diese Variante einen der tragischsten Schurken-Ursprünge des Kinos.',
    fr: 'La transformation de Darth Vader représente le moment où l\'Anakin Skywalker brûlé et vaincu est reconstruit en tant que Seigneur Noir dans La Revanche des Sith. Cette minifigurine dépeint Vader immédiatement après sa reconstruction avec son armure noire iconique, cape, casque, et systèmes de survie. Le moment tragique où Vader apprend la mort de Padmé et libère son angoisse marque la chute complète d\'Anakin. Sortie dans des sets de baie médicale et chambre de transformation, cette variante représente l\'une des origines de méchant les plus tragiques du cinéma.',
    es: 'La transformación de Darth Vader representa el momento cuando el quemado y derrotado Anakin Skywalker es reconstruido como el Señor Oscuro en La Venganza de los Sith. Esta minifigura representa a Vader inmediatamente después de su reconstrucción con su icónica armadura negra, capa, casco y sistemas de soporte vital. El momento trágico cuando Vader se entera de la muerte de Padmé y desata su angustia marca la caída completa de Anakin. Lanzada en sets de bahía médica y cámara de transformación, esta variante representa uno de los orígenes de villano más trágicos del cine.'
  },
  {
    no: 'sw0447',
    name: 'General Grievous',
    en: 'General Grievous is the cyborg Supreme Commander of the Droid Army, wielding four lightsabers and terrorizing the Republic in Revenge of the Sith. This minifigure captures Grievous\'s distinctive skeletal droid body with cape, hunched posture, and ability to split arms for quad-wielding lightsabers. As the Separatists\' military leader and Jedi killer, Grievous represents the escalating brutality of the Clone Wars. Released in numerous sets including his starfighter and wheel bike, this unique villain is highly popular with collectors for his complex design and menacing presence.',
    de: 'General Grievous ist der kybernetische Oberbefehlshaber der Droiden-Armee, der vier Lichtschwerter führt und die Republik in Die Rache der Sith terrorisiert. Diese Minifigur erfasst Grievous\' charakteristischen skelettartigen Droiden-Körper mit Umhang, gebeugter Haltung und Fähigkeit, Arme für das Führen von vier Lichtschwertern zu teilen. Als militärischer Führer der Separatisten und Jedi-Killer repräsentiert Grievous die eskalierende Brutalität der Klonkriege. Veröffentlicht in zahlreichen Sets, darunter sein Sternenjäger und Radbike, ist dieser einzigartige Schurke bei Sammlern wegen seines komplexen Designs und seiner bedrohlichen Präsenz sehr beliebt.',
    fr: 'Le Général Grievous est le Commandant Suprême cyborg de l\'Armée Droïde, maniant quatre sabres laser et terrorisant la République dans La Revanche des Sith. Cette minifigurine capture le corps de droïde squelettique distinctif de Grievous avec cape, posture voûtée, et capacité à diviser les bras pour manier quatre sabres laser. En tant que leader militaire des Séparatistes et tueur de Jedi, Grievous représente la brutalité croissante des Guerres des Clones. Sortie dans de nombreux sets, y compris son chasseur stellaire et moto à roue, ce méchant unique est très populaire auprès des collectionneurs pour son design complexe et sa présence menaçante.',
    es: 'El General Grievous es el Comandante Supremo ciborg del Ejército Droide, empuñando cuatro sables de luz y aterrorizando a la República en La Venganza de los Sith. Esta minifigura captura el distintivo cuerpo droide esquelético de Grievous con capa, postura encorvada y capacidad para dividir brazos para empuñar cuatro sables de luz. Como líder militar de los Separatistas y asesino de Jedi, Grievous representa la brutalidad escalada de las Guerras Clon. Lanzada en numerosos sets incluyendo su caza estelar y moto de rueda, este villano único es muy popular entre coleccionistas por su diseño complejo y presencia amenazante.'
  },
  {
    no: 'sw0448',
    name: 'Commander Cody',
    en: 'Commander Cody (CC-2224) is the distinguished clone trooper who serves as Obi-Wan Kenobi\'s second-in-command during the Clone Wars in Revenge of the Sith. This minifigure features Phase II armor with distinctive orange markings, specialized equipment, and pauldron denoting his rank. Tragically, Cody executes Order 66 and attempts to kill Obi-Wan on Utapau. Released in various Clone Wars sets, this named clone commander is highly sought after by army builders and represents the elite clone officers of the Grand Army.',
    de: 'Commander Cody (CC-2224) ist der ausgezeichnete Klonkrieger, der während der Klonkriege in Die Rache der Sith als Obi-Wan Kenobis Stellvertreter dient. Diese Minifigur zeigt Phase-II-Rüstung mit charakteristischen orangen Markierungen, spezialisierter Ausrüstung und Schulterstück, das seinen Rang bezeichnet. Tragischerweise führt Cody Order 66 aus und versucht, Obi-Wan auf Utapau zu töten. Veröffentlicht in verschiedenen Klonkriegs-Sets, wird dieser benannte Klon-Kommandant von Armee-Bauern sehr begehrt und repräsentiert die Elite-Klon-Offiziere der Großen Armee.',
    fr: 'Le Commandant Cody (CC-2224) est le clone trooper distingué qui sert comme second d\'Obi-Wan Kenobi pendant les Guerres des Clones dans La Revanche des Sith. Cette minifigurine présente une armure de Phase II avec marques orange distinctives, équipement spécialisé, et épaulette dénotant son rang. Tragiquement, Cody exécute l\'Ordre 66 et tente de tuer Obi-Wan sur Utapau. Sortie dans divers sets des Guerres des Clones, ce commandant de clone nommé est très recherché par les constructeurs d\'armée et représente les officiers de clone d\'élite de la Grande Armée.',
    es: 'El Comandante Cody (CC-2224) es el distinguido clone trooper que sirve como segundo al mando de Obi-Wan Kenobi durante las Guerras Clon en La Venganza de los Sith. Esta minifigura presenta armadura de Fase II con distintivas marcas naranjas, equipo especializado y hombrera denotando su rango. Trágicamente, Cody ejecuta la Orden 66 e intenta matar a Obi-Wan en Utapau. Lanzada en varios sets de las Guerras Clon, este comandante clon nombrado es muy buscado por constructores de ejércitos y representa a los oficiales clon de élite del Gran Ejército.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 331-340 (sw0439-sw0448) - 10 minifigs...\n');

  for (const m of batch) {
    try {
      await prisma.minifigCatalog.upsert({
        where: { minifigure_no: m.no },
        update: {
          description_en: m.en,
          description_de: m.de,
          description_fr: m.fr,
          description_es: m.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        },
        create: {
          minifigure_no: m.no,
          name: m.name,
          category_id: 1,
          category_name: 'Star Wars',
          search_name: m.name.toLowerCase(),
          description_en: m.en,
          description_de: m.de,
          description_fr: m.fr,
          description_es: m.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        }
      });
      console.log(`  ✅ ${m.no}: ${m.name}`);
    } catch (error: any) {
      console.error(`  ❌ ${m.no}: ${error.message}`);
    }
  }

  console.log('\n✨ Batch 331-340 complete: 10 minifigs (40 descriptions)');
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
