import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0169',
    name: 'Republic Captain',
    en: 'The Republic Captain represents the commanding officers of the Grand Army of the Republic during the Clone Wars. This LEGO minifigure features distinctive officer markings, specialized armor, and command insignia that identify Republic military leadership. The figure includes detailed printing showing rank indicators, tactical gear, and the formal elements that distinguish captains from standard clone troopers. Released in 2007 as part of Clone Wars sets, this officer adds command structure authenticity to Republic military displays. The captain rank markings distinguish this from standard clone troopers and higher-ranking commanders. As the mid-level officers who led clone trooper squads and platoons in battle, Republic Captains are essential for collectors building complete military hierarchies and recreating the organized structure of the Republic\'s massive clone army during the prequel era.',
    de: 'Der Republik-Hauptmann repräsentiert die kommandierenden Offiziere der Großen Armee der Republik während der Klonkriege. Diese LEGO Minifigur zeigt charakteristische Offiziersmarkierungen, spezialisierte Rüstung und Kommando-Insignien, die die militärische Führung der Republik identifizieren. Die Figur enthält detaillierte Bedruckung, die Rangabzeichen, taktische Ausrüstung und die formellen Elemente zeigt, die Hauptmänner von Standard-Klon-Troopern unterscheiden. Veröffentlicht im Jahr 2007 als Teil von Klonkriegs-Sets, fügt dieser Offizier Kommandostruktur-Authentizität zu republikanischen Militärausstellungen hinzu. Die Hauptmanns-Rangmarkierungen unterscheiden diese von Standard-Klon-Troopern und höherrangigen Kommandeuren. Als mittlere Offiziere, die Klon-Trooper-Squads und Züge im Kampf führten, sind Republik-Hauptmänner für Sammler unverzichtbar, die vollständige militärische Hierarchien aufbauen und die organisierte Struktur der massiven Klon-Armee der Republik während der Prequel-Ära nachstellen.',
    fr: 'Le Capitaine de la République représente les officiers commandants de la Grande Armée de la République pendant la Guerre des Clones. Cette minifigurine LEGO présente des marquages d\'officier distinctifs, une armure spécialisée et des insignes de commandement qui identifient la direction militaire de la République. La figurine comprend une impression détaillée montrant des indicateurs de rang, de l\'équipement tactique et les éléments formels qui distinguent les capitaines des clone troopers standard. Sortie en 2007 dans des sets de la Guerre des Clones, cet officier ajoute de l\'authenticité de structure de commandement aux affichages militaires de la République. Les marquages de rang de capitaine distinguent celui-ci des clone troopers standard et des commandants de rang supérieur. En tant qu\'officiers de niveau intermédiaire qui dirigeaient des escouades et des pelotons de clone troopers au combat, les Capitaines de la République sont essentiels pour les collectionneurs construisant des hiérarchies militaires complètes et recréant la structure organisée de l\'armée clone massive de la République pendant l\'ère des préquelles.',
    es: 'El Capitán de la República representa a los oficiales comandantes del Gran Ejército de la República durante las Guerras Clon. Esta minifigura LEGO presenta distintivas marcas de oficial, armadura especializada e insignias de comando que identifican el liderazgo militar de la República. La figura incluye impresión detallada mostrando indicadores de rango, equipo táctico y los elementos formales que distinguen a capitanes de clone troopers estándar. Lanzada en 2007 como parte de sets de las Guerras Clon, este oficial añade autenticidad de estructura de comando a exhibiciones militares de la República. Las marcas de rango de capitán distinguen este de clone troopers estándar y comandantes de mayor rango. Como oficiales de nivel medio que lideraron escuadrones y pelotones de clone troopers en batalla, los Capitanes de la República son esenciales para coleccionistas construyendo jerarquías militares completas y recreando la estructura organizada del ejército clon masivo de la República durante la era de las precuelas.'
  },
  {
    no: 'sw0170',
    name: 'Republic Pilot',
    en: 'The Republic Pilot represents the starfighter corps who flew various Republic craft during the Clone Wars. This LEGO minifigure features the standard Republic flight suit, pilot helmet, and equipment worn by non-Jedi pilots serving the Grand Army. The figure includes detailed printing showing life support gear, communication systems, and the practical attire of Republic military aviators. Released in 2007 as part of Republic vehicle sets, these pilots flew gunships, transports, and support craft alongside Jedi starfighters. The Republic military styling distinguishes these pilots from Rebel Alliance flight crews. As the professional pilots who operated the Republic\'s massive fleet of military transports and support vessels, Republic Pilots are essential for collectors building complete Clone Wars military displays with proper crew complements for LAAT gunships, ARC-170s, and other Republic vehicles.',
    de: 'Der Republik-Pilot repräsentiert das Sternenjäger-Korps, das während der Klonkriege verschiedene Republik-Raumschiffe flog. Diese LEGO Minifigur zeigt den Standard-Republik-Fluganzug, Pilotenhelm und Ausrüstung, die von Nicht-Jedi-Piloten getragen wurden, die der Großen Armee dienten. Die Figur enthält detaillierte Bedruckung, die Lebenserhaltungsausrüstung, Kommunikationssysteme und die praktische Kleidung republikanischer Militärflieger zeigt. Veröffentlicht im Jahr 2007 als Teil von Republik-Fahrzeugsets, flogen diese Piloten Kanonenboote, Transporter und Unterstützungsschiffe an der Seite von Jedi-Sternenjägern. Der republikanische Militärstil unterscheidet diese Piloten von Rebellenallianz-Flugbesatzungen. Als professionelle Piloten, die die massive Flotte von Militärtransportern und Unterstützungsschiffen der Republik betrieben, sind Republik-Piloten für Sammler unverzichtbar, die vollständige Klonkriegs-Militärausstellungen mit angemessenen Besatzungsergänzungen für LAAT-Kanonenboote, ARC-170s und andere Republik-Fahrzeuge aufbauen.',
    fr: 'Le Pilote de la République représente le corps de chasseurs stellaires qui pilotaient divers vaisseaux de la République pendant la Guerre des Clones. Cette minifigurine LEGO présente la combinaison de vol standard de la République, le casque de pilote et l\'équipement porté par les pilotes non-Jedi servant la Grande Armée. La figurine comprend une impression détaillée montrant l\'équipement de survie, les systèmes de communication et la tenue pratique des aviateurs militaires de la République. Sortie en 2007 dans des sets de véhicules de la République, ces pilotes pilotaient des canonnières, des transports et des vaisseaux de soutien aux côtés des chasseurs stellaires Jedi. Le style militaire de la République distingue ces pilotes des équipages de vol de l\'Alliance Rebelle. En tant que pilotes professionnels qui opéraient la flotte massive de transports militaires et de vaisseaux de soutien de la République, les Pilotes de la République sont essentiels pour les collectionneurs construisant des affichages militaires complets de la Guerre des Clones avec des compléments d\'équipage appropriés pour les canonnières LAAT, les ARC-170 et autres véhicules de la République.',
    es: 'El Piloto de la República representa al cuerpo de cazas estelares que volaron varias naves de la República durante las Guerras Clon. Esta minifigura LEGO presenta el traje de vuelo estándar de la República, casco de piloto y equipo usado por pilotos no Jedi sirviendo al Gran Ejército. La figura incluye impresión detallada mostrando equipo de soporte vital, sistemas de comunicación y el atuendo práctico de aviadores militares de la República. Lanzada en 2007 como parte de sets de vehículos de la República, estos pilotos volaron cañoneras, transportes y naves de apoyo junto a cazas estelares Jedi. El estilo militar de la República distingue a estos pilotos de tripulaciones de vuelo de la Alianza Rebelde. Como pilotos profesionales que operaron la flota masiva de transportes militares y naves de apoyo de la República, los Pilotos de la República son esenciales para coleccionistas construyendo exhibiciones militares completas de las Guerras Clon con complementos apropiados de tripulación para cañoneras LAAT, ARC-170 y otros vehículos de la República.'
  },
  {
    no: 'sw0171',
    name: 'Imperial Probe Droid - White Dish Stand, Lever on Top',
    en: 'The Imperial Probe Droid, also known as a Probot, represents the autonomous reconnaissance units that the Empire deployed across the galaxy. This LEGO minifigure features the distinctive white dish stand, top lever, and spherical body with multiple sensor appendages. The figure captures the Probe Droid\'s menacing appearance as it hovered on repulsorlift technology gathering intelligence. Released in 2007 as part of Hoth-themed sets, this droid is most famous for discovering Echo Base\'s location in The Empire Strikes Back. The white dish stand and lever configuration distinguish this variant from other production versions. As the scout that led the Empire directly to the Rebel base and triggered the Battle of Hoth, the Probe Droid is essential for collectors building complete Hoth scenes and representing the Empire\'s galaxy-spanning surveillance network.',
    de: 'Der Imperial Probe Droid, auch bekannt als Probot, repräsentiert die autonomen Aufklärungseinheiten, die das Imperium über die Galaxie verteilte. Diese LEGO Minifigur zeigt den charakteristischen weißen Schüsselständer, oberen Hebel und kugelförmigen Körper mit mehreren Sensor-Anhängseln. Die Figur fängt das bedrohliche Aussehen des Probe Droids ein, wie er auf Repulsorlift-Technologie schwebte und Informationen sammelte. Veröffentlicht im Jahr 2007 als Teil von Hoth-thematisierten Sets, ist dieser Droide am berühmtesten dafür, den Standort der Echo-Basis in Das Imperium schlägt zurück zu entdecken. Der weiße Schüsselständer und die Hebelkonfiguration unterscheiden diese Variante von anderen Produktionsversionen. Als Späher, der das Imperium direkt zur Rebellenbasis führte und die Schlacht von Hoth auslöste, ist der Probe Droid für Sammler unverzichtbar, die vollständige Hoth-Szenen aufbauen und das galaxisweit reichende Überwachungsnetzwerk des Imperiums repräsentieren.',
    fr: 'Le Droïde de Sonde Impérial, également connu sous le nom de Probot, représente les unités de reconnaissance autonomes que l\'Empire déployait à travers la galaxie. Cette minifigurine LEGO présente le support de parabole blanc distinctif, le levier supérieur et le corps sphérique avec plusieurs appendices de capteurs. La figurine capture l\'apparence menaçante du Droïde de Sonde alors qu\'il planait sur la technologie de répulseur en collectant des renseignements. Sortie en 2007 dans des sets à thème Hoth, ce droïde est le plus célèbre pour avoir découvert l\'emplacement de la Base Echo dans L\'Empire contre-attaque. Le support de parabole blanc et la configuration de levier distinguent cette variante des autres versions de production. En tant qu\'éclaireur qui a mené l\'Empire directement à la base Rebelle et déclenché la Bataille de Hoth, le Droïde de Sonde est essentiel pour les collectionneurs construisant des scènes complètes de Hoth et représentant le réseau de surveillance à l\'échelle galactique de l\'Empire.',
    es: 'El Droide de Sonda Imperial, también conocido como Probot, representa las unidades de reconocimiento autónomas que el Imperio desplegó a través de la galaxia. Esta minifigura LEGO presenta el distintivo soporte de plato blanco, palanca superior y cuerpo esférico con múltiples apéndices de sensor. La figura captura la apariencia amenazante del Droide de Sonda mientras flotaba en tecnología de repulsión recopilando inteligencia. Lanzada en 2007 como parte de sets temáticos de Hoth, este droide es más famoso por descubrir la ubicación de la Base Eco en El Imperio Contraataca. El soporte de plato blanco y configuración de palanca distinguen esta variante de otras versiones de producción. Como explorador que llevó al Imperio directamente a la base Rebelde y desencadenó la Batalla de Hoth, el Droide de Sonda es esencial para coleccionistas construyendo escenas completas de Hoth y representando la red de vigilancia a escala galáctica del Imperio.'
  },
  {
    no: 'sw0172',
    name: 'Qui-Gon Jinn - Light Nougat Head, Brown Hood and Cape',
    en: 'Qui-Gon Jinn is the wise Jedi Master who discovered Anakin Skywalker and set in motion the events of the entire Star Wars saga. This LEGO minifigure features the light nougat head, long brown hair, beard, and flowing brown hood and cape that defined his appearance in The Phantom Menace. The figure includes detailed printing of his Jedi robes and the serene expression that captured Liam Neeson\'s portrayal of the maverick Jedi. Released in 2007 as part of Episode I sets, this minifigure represents Qui-Gon during his final mission to Naboo. The brown hood and cape combination distinguishes this from cape-less variants. As Obi-Wan\'s master and the Jedi who believed Anakin was the Chosen One, Qui-Gon is essential for collectors building Episode I scenes and representing the tragic irony of discovering the future Darth Vader.',
    de: 'Qui-Gon Jinn ist der weise Jedi-Meister, der Anakin Skywalker entdeckte und die Ereignisse der gesamten Star-Wars-Saga in Gang setzte. Diese LEGO Minifigur zeigt den hellen Nougat-Kopf, langes braunes Haar, Bart und fließende braune Kapuze und Umhang, die sein Aussehen in Die dunkle Bedrohung definierten. Die Figur enthält detaillierte Bedruckung seiner Jedi-Roben und den gelassenen Ausdruck, der Liam Neesons Darstellung des eigensinnigen Jedi einfing. Veröffentlicht im Jahr 2007 als Teil von Episode-I-Sets, repräsentiert diese Minifigur Qui-Gon während seiner letzten Mission nach Naboo. Die Kombination aus brauner Kapuze und Umhang unterscheidet diese von umhanglosen Varianten. Als Obi-Wans Meister und der Jedi, der glaubte, Anakin sei der Auserwählte, ist Qui-Gon für Sammler unverzichtbar, die Episode-I-Szenen aufbauen und die tragische Ironie repräsentieren, den zukünftigen Darth Vader zu entdecken.',
    fr: 'Qui-Gon Jinn est le sage Maître Jedi qui a découvert Anakin Skywalker et mis en mouvement les événements de toute la saga Star Wars. Cette minifigurine LEGO présente la tête nougat clair, les longs cheveux bruns, la barbe et la capuche et cape brunes fluides qui définissaient son apparence dans La Menace Fantôme. La figurine comprend une impression détaillée de ses robes Jedi et l\'expression sereine qui capturait la représentation de Liam Neeson du Jedi anticonformiste. Sortie en 2007 dans des sets de l\'Épisode I, cette minifigurine représente Qui-Gon pendant sa dernière mission à Naboo. La combinaison de capuche et cape brunes distingue celle-ci des variantes sans cape. En tant que maître d\'Obi-Wan et le Jedi qui croyait qu\'Anakin était l\'Élu, Qui-Gon est essentiel pour les collectionneurs construisant des scènes de l\'Épisode I et représentant l\'ironie tragique de découvrir le futur Dark Vador.',
    es: 'Qui-Gon Jinn es el sabio Maestro Jedi que descubrió a Anakin Skywalker y puso en movimiento los eventos de toda la saga de Star Wars. Esta minifigura LEGO presenta la cabeza nougat claro, cabello largo marrón, barba y capucha y capa marrones fluidas que definieron su apariencia en La Amenaza Fantasma. La figura incluye impresión detallada de sus túnicas Jedi y la expresión serena que capturó la interpretación de Liam Neeson del Jedi inconformista. Lanzada en 2007 como parte de sets del Episodio I, esta minifigura representa a Qui-Gon durante su misión final a Naboo. La combinación de capucha y capa marrón distingue esta de variantes sin capa. Como maestro de Obi-Wan y el Jedi que creyó que Anakin era el Elegido, Qui-Gon es esencial para coleccionistas construyendo escenas del Episodio I y representando la ironía trágica de descubrir al futuro Darth Vader.'
  },
  {
    no: 'sw0173',
    name: 'Obi-Wan Kenobi - Young, Light Nougat, Brown Hood and Cape, Tan Legs',
    en: 'Young Obi-Wan Kenobi as a Jedi Padawan represents his early years training under Qui-Gon Jinn in The Phantom Menace. This LEGO minifigure features the light nougat skin tone, brown hood and cape, and tan legs that show his apprentice status. The figure includes detailed printing of his Padawan braid, simple Jedi robes, and the determined expression of a young man eager to prove himself. Released in 2007 as part of Episode I sets, this young Obi-Wan captures his appearance before he became a Jedi Knight. The brown hood and tan legs distinguish this Padawan version from his later Jedi Master variants. As the protagonist who defeated Darth Maul and took Anakin as his apprentice after Qui-Gon\'s death, young Obi-Wan is essential for collectors building Episode I scenes and representing the beginning of his legendary career.',
    de: 'Der junge Obi-Wan Kenobi als Jedi-Padawan repräsentiert seine frühen Jahre unter der Ausbildung von Qui-Gon Jinn in Die dunkle Bedrohung. Diese LEGO Minifigur zeigt den hellen Nougat-Hautton, braune Kapuze und Umhang und beige Beine, die seinen Lehrlingsstatus zeigen. Die Figur enthält detaillierte Bedruckung seines Padawan-Zopfs, einfacher Jedi-Roben und des entschlossenen Ausdrucks eines jungen Mannes, der sich beweisen möchte. Veröffentlicht im Jahr 2007 als Teil von Episode-I-Sets, fängt dieser junge Obi-Wan sein Aussehen ein, bevor er Jedi-Ritter wurde. Die braune Kapuze und beigen Beine unterscheiden diese Padawan-Version von seinen späteren Jedi-Meister-Varianten. Als Protagonist, der Darth Maul besiegte und Anakin als seinen Lehrling annahm nach Qui-Gons Tod, ist der junge Obi-Wan für Sammler unverzichtbar, die Episode-I-Szenen aufbauen und den Beginn seiner legendären Karriere repräsentieren.',
    fr: 'Le jeune Obi-Wan Kenobi en tant que Padawan Jedi représente ses premières années d\'entraînement sous Qui-Gon Jinn dans La Menace Fantôme. Cette minifigurine LEGO présente le teint nougat clair, la capuche et cape brunes et les jambes beiges qui montrent son statut d\'apprenti. La figurine comprend une impression détaillée de sa tresse de Padawan, de simples robes Jedi et l\'expression déterminée d\'un jeune homme désireux de faire ses preuves. Sortie en 2007 dans des sets de l\'Épisode I, ce jeune Obi-Wan capture son apparence avant qu\'il ne devienne Chevalier Jedi. La capuche brune et les jambes beiges distinguent cette version Padawan de ses variantes ultérieures de Maître Jedi. En tant que protagoniste qui a vaincu Dark Maul et pris Anakin comme apprenti après la mort de Qui-Gon, le jeune Obi-Wan est essentiel pour les collectionneurs construisant des scènes de l\'Épisode I et représentant le début de sa carrière légendaire.',
    es: 'El joven Obi-Wan Kenobi como Padawan Jedi representa sus primeros años entrenando bajo Qui-Gon Jinn en La Amenaza Fantasma. Esta minifigura LEGO presenta el tono de piel nougat claro, capucha y capa marrón y piernas beige que muestran su estatus de aprendiz. La figura incluye impresión detallada de su trenza Padawan, túnicas Jedi simples y la expresión determinada de un joven ansioso por probarse. Lanzada en 2007 como parte de sets del Episodio I, este joven Obi-Wan captura su apariencia antes de convertirse en Caballero Jedi. La capucha marrón y piernas beige distinguen esta versión Padawan de sus variantes posteriores de Maestro Jedi. Como protagonista que derrotó a Darth Maul y tomó a Anakin como su aprendiz después de la muerte de Qui-Gon, el joven Obi-Wan es esencial para coleccionistas construyendo escenas del Episodio I y representando el comienzo de su carrera legendaria.'
  },
  {
    no: 'sw0174',
    name: 'Obi-Wan Kenobi - Old, Light Bluish Gray Hair and Beard, Black Eyes',
    en: 'Old Ben Kenobi represents the aged Jedi Master living in exile on Tatooine in A New Hope, having watched over Luke Skywalker for nearly two decades. This LEGO minifigure features the light bluish gray hair and beard, tan Jedi robes, and the wise expression that captured Alec Guinness\'s iconic portrayal. The figure includes detailed printing showing the weathered robes of a hermit and the serene face of a man who has known both triumph and tragedy. Released in 2007 as part of Original Trilogy sets, this old Obi-Wan represents his appearance when training Luke and sacrificing himself aboard the Death Star. The black eyes and gray beard distinguish this from younger variants. As Luke\'s first mentor and the Jedi who set the young farm boy on his hero\'s journey, Old Ben Kenobi is essential for collectors building Tatooine and Death Star scenes from the original film.',
    de: 'Der alte Ben Kenobi repräsentiert den gealterten Jedi-Meister, der im Exil auf Tatooine in Eine neue Hoffnung lebte und fast zwei Jahrzehnte über Luke Skywalker gewacht hatte. Diese LEGO Minifigur zeigt das hellblaugraue Haar und Bart, beige Jedi-Roben und den weisen Ausdruck, der Alec Guinness\' ikonische Darstellung einfing. Die Figur enthält detaillierte Bedruckung, die die verwitterten Roben eines Einsiedlers und das gelassene Gesicht eines Mannes zeigt, der sowohl Triumph als auch Tragödie gekannt hat. Veröffentlicht im Jahr 2007 als Teil von Original-Trilogie-Sets, repräsentiert dieser alte Obi-Wan sein Aussehen beim Training von Luke und seinem Opfer an Bord des Todessterns. Die schwarzen Augen und der graue Bart unterscheiden diese von jüngeren Varianten. Als Lukes erster Mentor und der Jedi, der den jungen Farmjungen auf seine Heldenreise schickte, ist der alte Ben Kenobi für Sammler unverzichtbar, die Tatooine- und Todesstern-Szenen aus dem Originalfilm bauen.',
    fr: 'Le vieux Ben Kenobi représente le Maître Jedi vieilli vivant en exil sur Tatooine dans Un Nouvel Espoir, ayant veillé sur Luke Skywalker pendant près de deux décennies. Cette minifigurine LEGO présente les cheveux et la barbe gris bleuté clair, les robes Jedi beiges et l\'expression sage qui capturait la représentation iconique d\'Alec Guinness. La figurine comprend une impression détaillée montrant les robes usées d\'un ermite et le visage serein d\'un homme qui a connu à la fois le triomphe et la tragédie. Sortie en 2007 dans des sets de la Trilogie Originale, ce vieil Obi-Wan représente son apparence lors de l\'entraînement de Luke et de son sacrifice à bord de l\'Étoile de la Mort. Les yeux noirs et la barbe grise distinguent celle-ci des variantes plus jeunes. En tant que premier mentor de Luke et le Jedi qui a mis le jeune garçon de ferme sur son voyage de héros, le vieux Ben Kenobi est essentiel pour les collectionneurs construisant des scènes de Tatooine et de l\'Étoile de la Mort du film original.',
    es: 'El viejo Ben Kenobi representa al Maestro Jedi envejecido viviendo en exilio en Tatooine en Una Nueva Esperanza, habiendo vigilado a Luke Skywalker durante casi dos décadas. Esta minifigura LEGO presenta el cabello y barba gris azulado claro, túnicas Jedi beige y la expresión sabia que capturó la interpretación icónica de Alec Guinness. La figura incluye impresión detallada mostrando las túnicas desgastadas de un ermitaño y el rostro sereno de un hombre que ha conocido tanto triunfo como tragedia. Lanzada en 2007 como parte de sets de la Trilogía Original, este viejo Obi-Wan representa su apariencia cuando entrenaba a Luke y se sacrificaba a bordo de la Estrella de la Muerte. Los ojos negros y barba gris distinguen esta de variantes más jóvenes. Como primer mentor de Luke y el Jedi que puso al joven chico de granja en su viaje del héroe, el viejo Ben Kenobi es esencial para coleccionistas construyendo escenas de Tatooine y la Estrella de la Muerte de la película original.'
  },
  {
    no: 'sw0175',
    name: 'Princess Leia - White Dress, Simple Belt, Small Eyes, Textured Hair',
    en: 'Princess Leia in her iconic white dress represents her appearance at the beginning of A New Hope when she recorded the holographic message for Obi-Wan Kenobi. This LEGO minifigure features the white senatorial gown, simple belt, textured hair piece representing her distinctive side buns, and small eye printing. The figure captures Leia\'s appearance as the diplomatic princess before the Rebellion\'s desperate fight against the Empire. Released in 2007 as part of Original Trilogy sets, this white dress variant shows Leia during her mission to deliver the Death Star plans. The textured hair and simple belt distinguish this from other Leia variants. As the princess whose stolen plans started the entire Original Trilogy and whose plea "Help me, Obi-Wan Kenobi" became one of cinema\'s most famous lines, this white dress Leia is essential for collectors building the opening sequences of A New Hope.',
    de: 'Prinzessin Leia in ihrem ikonischen weißen Kleid repräsentiert ihr Aussehen zu Beginn von Eine neue Hoffnung, als sie die holographische Nachricht für Obi-Wan Kenobi aufnahm. Diese LEGO Minifigur zeigt das weiße Senatorenkleid, einfachen Gürtel, strukturiertes Haarteil, das ihre charakteristischen Seitenschnecken repräsentiert, und kleine Augenbedruckung. Die Figur fängt Leias Aussehen als diplomatische Prinzessin vor dem verzweifelten Kampf der Rebellion gegen das Imperium ein. Veröffentlicht im Jahr 2007 als Teil von Original-Trilogie-Sets, zeigt diese weiße Kleid-Variante Leia während ihrer Mission, die Todesstern-Pläne zu liefern. Das strukturierte Haar und der einfache Gürtel unterscheiden diese von anderen Leia-Varianten. Als Prinzessin, deren gestohlene Pläne die gesamte Original-Trilogie starteten und deren Flehen "Hilf mir, Obi-Wan Kenobi" zu einer der berühmtesten Filmzeilen wurde, ist diese weiße Kleid-Leia für Sammler unverzichtbar, die die Eröffnungssequenzen von Eine neue Hoffnung bauen.',
    fr: 'La Princesse Leia dans sa robe blanche iconique représente son apparence au début d\'Un Nouvel Espoir lorsqu\'elle a enregistré le message holographique pour Obi-Wan Kenobi. Cette minifigurine LEGO présente la robe sénatoriale blanche, la ceinture simple, la pièce de cheveux texturée représentant ses chignons latéraux distinctifs et la petite impression d\'yeux. La figurine capture l\'apparence de Leia en tant que princesse diplomatique avant le combat désespéré de la Rébellion contre l\'Empire. Sortie en 2007 dans des sets de la Trilogie Originale, cette variante en robe blanche montre Leia pendant sa mission de livrer les plans de l\'Étoile de la Mort. Les cheveux texturés et la ceinture simple distinguent celle-ci des autres variantes de Leia. En tant que princesse dont les plans volés ont lancé toute la Trilogie Originale et dont la supplication "Aidez-moi, Obi-Wan Kenobi" est devenue l\'une des répliques les plus célèbres du cinéma, cette Leia en robe blanche est essentielle pour les collectionneurs construisant les séquences d\'ouverture d\'Un Nouvel Espoir.',
    es: 'La Princesa Leia en su icónico vestido blanco representa su apariencia al comienzo de Una Nueva Esperanza cuando grabó el mensaje holográfico para Obi-Wan Kenobi. Esta minifigura LEGO presenta el vestido senatorial blanco, cinturón simple, pieza de cabello texturizado representando sus distintivos moños laterales y pequeña impresión de ojos. La figura captura la apariencia de Leia como la princesa diplomática antes de la lucha desesperada de la Rebelión contra el Imperio. Lanzada en 2007 como parte de sets de la Trilogía Original, esta variante de vestido blanco muestra a Leia durante su misión de entregar los planos de la Estrella de la Muerte. El cabello texturizado y cinturón simple distinguen esta de otras variantes de Leia. Como la princesa cuyos planos robados iniciaron toda la Trilogía Original y cuya súplica "Ayúdame, Obi-Wan Kenobi" se convirtió en una de las líneas más famosas del cine, esta Leia de vestido blanco es esencial para coleccionistas construyendo las secuencias de apertura de Una Nueva Esperanza.'
  },
  {
    no: 'sw0176',
    name: 'Luke Skywalker - Tatooine, Light Nougat, Long Hair, White Tunic, Tan Legs',
    en: 'Luke Skywalker as a Tatooine farm boy represents his humble beginnings before discovering his destiny as a Jedi. This LEGO minifigure features the light nougat skin tone, long blonde hair, white tunic, and tan legs that capture his appearance as a moisture farmer in A New Hope. The figure includes simple clothing printing showing the practical desert attire Luke wore while dreaming of adventure. Released in 2007 as part of Original Trilogy sets, this Tatooine Luke shows him at his most innocent, before the events that would make him a galactic hero. The white tunic and tan legs distinguish this farm boy version from his later pilot and Jedi variants. As the protagonist at the beginning of his hero\'s journey, this Tatooine Luke is essential for collectors building Lars Homestead scenes and representing Luke\'s transformation from farm boy to legendary Jedi Knight.',
    de: 'Luke Skywalker als Tatooine-Farmjunge repräsentiert seine bescheidenen Anfänge, bevor er sein Schicksal als Jedi entdeckte. Diese LEGO Minifigur zeigt den hellen Nougat-Hautton, langes blondes Haar, weiße Tunika und beige Beine, die sein Aussehen als Feuchtigkeitsfarmer in Eine neue Hoffnung einfangen. Die Figur enthält einfache Kleidungsbedruckung, die die praktische Wüstenkleidung zeigt, die Luke trug, während er von Abenteuern träumte. Veröffentlicht im Jahr 2007 als Teil von Original-Trilogie-Sets, zeigt dieser Tatooine-Luke ihn in seinem unschuldigsten Zustand, vor den Ereignissen, die ihn zu einem galaktischen Helden machen würden. Die weiße Tunika und beigen Beine unterscheiden diese Farmjungen-Version von seinen späteren Piloten- und Jedi-Varianten. Als Protagonist am Beginn seiner Heldenreise ist dieser Tatooine-Luke für Sammler unverzichtbar, die Lars-Gehöft-Szenen aufbauen und Lukes Verwandlung vom Farmjungen zum legendären Jedi-Ritter repräsentieren.',
    fr: 'Luke Skywalker en tant que garçon de ferme de Tatooine représente ses humbles débuts avant de découvrir son destin en tant que Jedi. Cette minifigurine LEGO présente le teint nougat clair, les longs cheveux blonds, la tunique blanche et les jambes beiges qui capturent son apparence en tant que fermier d\'humidité dans Un Nouvel Espoir. La figurine comprend une impression de vêtements simple montrant la tenue de désert pratique que Luke portait en rêvant d\'aventure. Sortie en 2007 dans des sets de la Trilogie Originale, ce Luke de Tatooine le montre à son plus innocent, avant les événements qui feraient de lui un héros galactique. La tunique blanche et les jambes beiges distinguent cette version de garçon de ferme de ses variantes ultérieures de pilote et Jedi. En tant que protagoniste au début de son voyage de héros, ce Luke de Tatooine est essentiel pour les collectionneurs construisant des scènes de la Ferme Lars et représentant la transformation de Luke de garçon de ferme à Chevalier Jedi légendaire.',
    es: 'Luke Skywalker como chico de granja de Tatooine representa sus humildes comienzos antes de descubrir su destino como Jedi. Esta minifigura LEGO presenta el tono de piel nougat claro, cabello rubio largo, túnica blanca y piernas beige que capturan su apariencia como granjero de humedad en Una Nueva Esperanza. La figura incluye impresión de ropa simple mostrando el atuendo práctico del desierto que Luke usó mientras soñaba con aventuras. Lanzada en 2007 como parte de sets de la Trilogía Original, este Luke de Tatooine lo muestra en su momento más inocente, antes de los eventos que lo convertirían en héroe galáctico. La túnica blanca y piernas beige distinguen esta versión de chico de granja de sus variantes posteriores de piloto y Jedi. Como protagonista al comienzo de su viaje del héroe, este Luke de Tatooine es esencial para coleccionistas construyendo escenas de la Granja Lars y representando la transformación de Luke de chico de granja a legendario Caballero Jedi.'
  },
  {
    no: 'sw0172a',
    name: 'Qui-Gon Jinn - Light Nougat Head with Black Chin Dimple, Brown Hood and Cape',
    en: 'Qui-Gon Jinn with chin dimple represents a detailed variant of the wise Jedi Master from The Phantom Menace. This LEGO minifigure features the light nougat head with distinctive black chin dimple printing, long brown hair, beard, and flowing brown hood and cape. The figure includes enhanced facial detail printing that more accurately captures Liam Neeson\'s features. Released in 2007 as a production variant, the black chin dimple distinguishes this from the standard sw0172 version. The additional facial detail adds character depth and collector appeal. As Obi-Wan\'s master and the Jedi who discovered Anakin, detailed Qui-Gon variants like this are valued by collectors who appreciate the improved printing techniques that make minifigures more screen-accurate and recognize the tragic importance of the Jedi who set the entire prequel trilogy in motion.',
    de: 'Qui-Gon Jinn mit Kinngrübchen repräsentiert eine detaillierte Variante des weisen Jedi-Meisters aus Die dunkle Bedrohung. Diese LEGO Minifigur zeigt den hellen Nougat-Kopf mit charakteristischer schwarzer Kinngrübchen-Bedruckung, langes braunes Haar, Bart und fließende braune Kapuze und Umhang. Die Figur enthält verbesserte Gesichtsdetail-Bedruckung, die Liam Neesons Merkmale genauer einfängt. Veröffentlicht im Jahr 2007 als Produktionsvariante, unterscheidet das schwarze Kinngrübchen diese von der Standard-sw0172-Version. Das zusätzliche Gesichtsdetail fügt Charaktertiefe und Sammlerattraktivität hinzu. Als Obi-Wans Meister und der Jedi, der Anakin entdeckte, werden detaillierte Qui-Gon-Varianten wie diese von Sammlern geschätzt, die die verbesserten Drucktechniken schätzen, die Minifiguren bildschirmgenauer machen, und die tragische Bedeutung des Jedi erkennen, der die gesamte Prequel-Trilogie in Gang setzte.',
    fr: 'Qui-Gon Jinn avec fossette au menton représente une variante détaillée du sage Maître Jedi de La Menace Fantôme. Cette minifigurine LEGO présente la tête nougat clair avec impression distinctive de fossette au menton noire, les longs cheveux bruns, la barbe et la capuche et cape brunes fluides. La figurine comprend une impression de détail facial améliorée qui capture plus précisément les traits de Liam Neeson. Sortie en 2007 comme variante de production, la fossette au menton noire distingue celle-ci de la version sw0172 standard. Le détail facial supplémentaire ajoute de la profondeur de personnage et de l\'attrait pour les collectionneurs. En tant que maître d\'Obi-Wan et le Jedi qui a découvert Anakin, les variantes détaillées de Qui-Gon comme celle-ci sont valorisées par les collectionneurs qui apprécient les techniques d\'impression améliorées qui rendent les minifigurines plus fidèles à l\'écran et reconnaissent l\'importance tragique du Jedi qui a mis toute la trilogie des préquelles en mouvement.',
    es: 'Qui-Gon Jinn con hoyuelo en barbilla representa una variante detallada del sabio Maestro Jedi de La Amenaza Fantasma. Esta minifigura LEGO presenta la cabeza nougat claro con distintiva impresión de hoyuelo de barbilla negro, cabello largo marrón, barba y capucha y capa marrones fluidas. La figura incluye impresión de detalle facial mejorado que captura más precisamente los rasgos de Liam Neeson. Lanzada en 2007 como variante de producción, el hoyuelo de barbilla negro distingue esta de la versión estándar sw0172. El detalle facial adicional añade profundidad de personaje y atractivo de coleccionista. Como maestro de Obi-Wan y el Jedi que descubrió a Anakin, variantes detalladas de Qui-Gon como esta son valoradas por coleccionistas que aprecian las técnicas de impresión mejoradas que hacen minifiguras más fieles a pantalla y reconocen la importancia trágica del Jedi que puso en movimiento toda la trilogía de las precuelas.'
  },
  {
    no: 'sw0177',
    name: 'AT-AT Driver - Red Imperial Logo, Bluish Grays, Black Head, Stormtrooper Helmet',
    en: 'The AT-AT Driver with red Imperial logo represents the elite pilots who commanded the massive All Terrain Armored Transport walkers. This LEGO minifigure features distinctive bluish gray uniform, red Imperial logo, black head, and modified Stormtrooper helmet with specialized equipment. The figure captures the appearance of the highly-trained operators who manned the Empire\'s most intimidating ground assault vehicles during the Battle of Hoth. Released in 2008 as part of AT-AT sets, this variant with red logo distinguishes it from other production versions. The bluish gray color scheme and specialized helmet identify these pilots as elite Imperial vehicle crews. As the operators who commanded the walkers that nearly destroyed Echo Base, AT-AT Drivers with the red Imperial insignia are essential for collectors building complete AT-AT cockpit crews and Hoth battle scenes from The Empire Strikes Back.',
    de: 'Der AT-AT-Fahrer mit rotem imperialem Logo repräsentiert die Elite-Piloten, die die massiven All-Terrain-Gepanzerten-Transport-Läufer kommandierten. Diese LEGO Minifigur zeigt charakteristische blaugraue Uniform, rotes imperiales Logo, schwarzen Kopf und modifizierten Stormtrooper-Helm mit spezialisierter Ausrüstung. Die Figur fängt das Aussehen der hochtrainierten Operatoren ein, die die einschüchterndsten Bodenangrifffahrzeuge des Imperiums während der Schlacht von Hoth bemannten. Veröffentlicht im Jahr 2008 als Teil von AT-AT-Sets, unterscheidet diese Variante mit rotem Logo sie von anderen Produktionsversionen. Das blaugraue Farbschema und der spezialisierte Helm identifizieren diese Piloten als Elite-Imperiale-Fahrzeugbesatzungen. Als Operatoren, die die Läufer kommandierten, die fast die Echo-Basis zerstörten, sind AT-AT-Fahrer mit dem roten imperialen Abzeichen für Sammler unverzichtbar, die vollständige AT-AT-Cockpit-Besatzungen und Hoth-Kampfszenen aus Das Imperium schlägt zurück bauen.',
    fr: 'Le Pilote d\'AT-AT avec logo Impérial rouge représente les pilotes d\'élite qui commandaient les marcheurs massifs All Terrain Armored Transport. Cette minifigurine LEGO présente un uniforme gris bleuté distinctif, un logo Impérial rouge, une tête noire et un casque de Stormtrooper modifié avec équipement spécialisé. La figurine capture l\'apparence des opérateurs hautement entraînés qui pilotaient les véhicules d\'assaut terrestre les plus intimidants de l\'Empire pendant la Bataille de Hoth. Sortie en 2008 dans des sets d\'AT-AT, cette variante avec logo rouge la distingue des autres versions de production. Le schéma de couleur gris bleuté et le casque spécialisé identifient ces pilotes comme équipages de véhicules impériaux d\'élite. En tant qu\'opérateurs qui commandaient les marcheurs qui ont presque détruit la Base Echo, les Pilotes d\'AT-AT avec l\'insigne Impérial rouge sont essentiels pour les collectionneurs construisant des équipages complets de cockpit d\'AT-AT et des scènes de bataille de Hoth de L\'Empire contre-attaque.',
    es: 'El Piloto de AT-AT con logo Imperial rojo representa a los pilotos de élite que comandaban los masivos caminantes de Transporte Blindado Todo Terreno. Esta minifigura LEGO presenta distintivo uniforme gris azulado, logo Imperial rojo, cabeza negra y casco modificado de Stormtrooper con equipo especializado. La figura captura la apariencia de los operadores altamente entrenados que tripularon los vehículos de asalto terrestre más intimidantes del Imperio durante la Batalla de Hoth. Lanzada en 2008 como parte de sets de AT-AT, esta variante con logo rojo la distingue de otras versiones de producción. El esquema de color gris azulado y casco especializado identifican a estos pilotos como tripulaciones de vehículos Imperiales de élite. Como operadores que comandaron los caminantes que casi destruyeron la Base Eco, los Pilotos de AT-AT con la insignia Imperial roja son esenciales para coleccionistas construyendo tripulaciones completas de cabina de AT-AT y escenas de batalla de Hoth de El Imperio Contraataca.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 023 (sw0169-sw0177) - 10 minifigs...\n');

  let successCount = 0;
  let skipCount = 0;

  for (const m of batch) {
    try {
      await prisma.minifigCatalog.update({
        where: { minifigure_no: m.no },
        data: {
          description_en: m.en,
          description_de: m.de,
          description_fr: m.fr,
          description_es: m.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        }
      });
      console.log(`  ✅ ${m.no}: ${m.name}`);
      successCount++;
    } catch (error: any) {
      console.log(`  ⚠️  ${m.no}: NOT IN DATABASE (skipped)`);
      skipCount++;
    }
  }

  console.log(`\n✨ Batch 023 complete: ${batch.length} minifigs (${successCount * 4} descriptions)\n`);

  await prisma.$disconnect();
}

saveBatch().catch(console.error);
