import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0204',
    name: 'Y-Wing Pilot',
    en: "Y-Wing Pilots fly the Rebellion's heavy bomber starfighters, providing assault capabilities during critical missions like the Battle of Yavin. This LEGO minifigure features the distinctive gray flight suit with yellow accents and specialized helmet worn by Gold Squadron bomber crews. First released in 1999, the Y-Wing Pilot represents the Rebellion's tactical bombing specialists who cleared the way for X-Wing attacks. The figure's detailed printing shows squadron markings and equipment that distinguish bomber pilots from fighter jockeys. Collectors value Y-Wing Pilots for their crucial support role during the Death Star assault and for completing diverse Rebel pilot rosters. Their slower but heavily armed craft made these pilots essential for ship-to-ship combat and strategic target destruction across the Original Trilogy.",
    de: "Y-Flügler-Piloten fliegen die schweren Bomber-Sternenjäger der Rebellion und bieten Angriffsfähigkeiten während kritischer Missionen wie der Schlacht von Yavin. Diese LEGO-Minifigur zeigt den charakteristischen grauen Fluganzug mit gelben Akzenten und spezialisierten Helm, der von Gold-Staffel-Bomberbesatzungen getragen wird. Erstmals 1999 veröffentlicht, repräsentiert der Y-Flügler-Pilot die taktischen Bomberspezialisten der Rebellion, die den Weg für X-Flügler-Angriffe ebneten. Die detaillierte Bedruckung der Figur zeigt Staffelmarkierungen und Ausrüstung, die Bomberpiloten von Jägerpiloten unterscheiden. Sammler schätzen Y-Flügler-Piloten für ihre entscheidende Unterstützungsrolle während des Todesstern-Angriffs und für die Vervollständigung vielfältiger Rebellenpiloten-Aufstellungen. Ihre langsameren aber schwer bewaffneten Schiffe machten diese Piloten unverzichtbar für Schiff-zu-Schiff-Kampf und strategische Zielzerstörung über die Original-Trilogie hinweg.",
    fr: "Les Pilotes Y-Wing pilotent les chasseurs stellaires bombardiers lourds de la Rébellion, fournissant des capacités d'assaut pendant les missions critiques comme la Bataille de Yavin. Cette minifigurine LEGO présente la combinaison de vol grise distinctive avec des accents jaunes et un casque spécialisé porté par les équipages de bombardiers de l'Escadron Or. Sortie pour la première fois en 1999, le Pilote Y-Wing représente les spécialistes de bombardement tactique de la Rébellion qui ont ouvert la voie aux attaques X-Wing. L'impression détaillée de la figurine montre les marquages d'escadron et l'équipement qui distinguent les pilotes bombardiers des pilotes de chasse. Les collectionneurs apprécient les Pilotes Y-Wing pour leur rôle de soutien crucial pendant l'assaut de l'Étoile de la Mort et pour compléter des listes diverses de pilotes Rebelles. Leurs vaisseaux plus lents mais lourdement armés ont rendu ces pilotes essentiels pour le combat vaisseau-à-vaisseau et la destruction de cibles stratégiques à travers la trilogie originale.",
    es: "Los Pilotos de Ala-Y vuelan los cazas estelares bombarderos pesados de la Rebelión, proporcionando capacidades de asalto durante misiones críticas como la Batalla de Yavin. Esta minifigura LEGO presenta el distintivo traje de vuelo gris con acentos amarillos y casco especializado usado por tripulaciones de bombarderos del Escuadrón Oro. Lanzada por primera vez en 1999, el Piloto de Ala-Y representa a los especialistas en bombardeo táctico de la Rebelión que abrieron el camino para ataques de Ala-X. La impresión detallada de la figura muestra marcas de escuadrón y equipo que distinguen a los pilotos bombarderos de los pilotos de cazas. Los coleccionistas valoran a los Pilotos de Ala-Y por su papel de apoyo crucial durante el asalto a la Estrella de la Muerte y por completar listas diversas de pilotos Rebeldes. Sus naves más lentas pero fuertemente armadas hicieron que estos pilotos fueran esenciales para combate nave-a-nave y destrucción de objetivos estratégicos a través de la trilogía original."
  },
  {
    no: 'sw0205',
    name: 'Sandtrooper',
    en: "Sandtroopers are specialized Imperial stormtroopers adapted for desert operations, searching Tatooine for the stolen Death Star plans and the missing droids. This LEGO minifigure features distinctive desert gear with survival backpack, pauldron shoulder armor, and weathered white armor showing sand damage. First released in 2001, the Sandtrooper has become iconic for its unique loadout among Imperial forces. The figure's detailed printing shows equipment modifications for harsh desert environments including cooling systems and extended supplies. Collectors value Sandtroopers for their search for R2-D2 and C-3PO and for representing Imperial environmental specialization. Multiple sandtroopers with varying rank pauldrons (white, orange, black) are essential for recreating the Tatooine manhunt scenes from A New Hope.",
    de: "Sandtruppler sind spezialisierte imperiale Sturmtruppen, die für Wüstenoperationen angepasst sind und Tatooine nach den gestohlenen Todesstern-Plänen und den vermissten Droiden durchsuchen. Diese LEGO-Minifigur zeigt charakteristische Wüstenausrüstung mit Überlebensrucksack, Pauldron-Schulterpanzerung und verwitterter weißer Rüstung mit Sandschäden. Erstmals 2001 veröffentlicht, ist der Sandtruppler ikonisch geworden für seine einzigartige Ausrüstung unter den imperialen Streitkräften. Die detaillierte Bedruckung der Figur zeigt Ausrüstungsmodifikationen für raue Wüstenumgebungen einschließlich Kühlsystemen und erweiterten Vorräten. Sammler schätzen Sandtruppler für ihre Suche nach R2-D2 und C-3PO und für die Darstellung imperialer Umweltspezialisierung. Mehrere Sandtruppler mit variierenden Rang-Pauldronen (weiß, orange, schwarz) sind unverzichtbar für die Nachbildung der Tatooine-Menschenjagd-Szenen aus Eine neue Hoffnung.",
    fr: "Les Sandtroopers sont des stormtroopers Impériaux spécialisés adaptés pour les opérations désertiques, recherchant sur Tatooine les plans volés de l'Étoile de la Mort et les droïdes manquants. Cette minifigurine LEGO présente un équipement désertique distinctif avec sac à dos de survie, armure d'épaule pauldron et armure blanche altérée montrant des dommages de sable. Sortie pour la première fois en 2001, le Sandtrooper est devenu iconique pour son chargement unique parmi les forces Impériales. L'impression détaillée de la figurine montre des modifications d'équipement pour les environnements désertiques difficiles, y compris les systèmes de refroidissement et les approvisionnements étendus. Les collectionneurs apprécient les Sandtroopers pour leur recherche de R2-D2 et C-3PO et pour représenter la spécialisation environnementale Impériale. Plusieurs sandtroopers avec des pauldrons de rang variables (blanc, orange, noir) sont essentiels pour recréer les scènes de chasse à l'homme sur Tatooine d'Un Nouvel Espoir.",
    es: "Los Soldados de Arena son soldados de asalto Imperiales especializados adaptados para operaciones desérticas, buscando en Tatooine los planos robados de la Estrella de la Muerte y los droides perdidos. Esta minifigura LEGO presenta equipo desértico distintivo con mochila de supervivencia, armadura de hombro pauldron y armadura blanca desgastada mostrando daño de arena. Lanzada por primera vez en 2001, el Soldado de Arena se ha vuelto icónico por su carga única entre las fuerzas Imperiales. La impresión detallada de la figura muestra modificaciones de equipo para ambientes desérticos duros incluyendo sistemas de enfriamiento y suministros extendidos. Los coleccionistas valoran a los Soldados de Arena por su búsqueda de R2-D2 y C-3PO y por representar la especialización ambiental Imperial. Múltiples soldados de arena con pauldrons de rango variables (blanco, naranja, negro) son esenciales para recrear las escenas de búsqueda en Tatooine de Una Nueva Esperanza."
  },
  {
    no: 'sw0206',
    name: 'Dewback',
    en: "Dewbacks are large reptilian pack animals native to Tatooine, used by Imperial sandtroopers as mounts for desert patrol and reconnaissance operations. This LEGO figure captures the dewback's distinctive lizard-like appearance with saddle equipment for trooper mounting. First released in 2001, the Dewback represents the Empire's adaptation to local resources for ground operations. The figure features unique construction showing its quadrupedal stance and reptilian features that make it ideal for desert travel. Collectors value Dewbacks for their memorable appearance in A New Hope's Special Edition and for completing Tatooine Imperial patrol displays. The combination of sandtrooper riders and dewback mounts creates authentic desert search scenes as the Empire hunts for the stolen Death Star plans.",
    de: "Dewbacks sind große reptilische Lasttiere, die auf Tatooine heimisch sind und von imperialen Sandtrupplern als Reittiere für Wüstenpatrouille und Aufklärungsoperationen verwendet werden. Diese LEGO-Figur fängt das charakteristische echsenartige Aussehen des Dewbacks mit Sattelausrüstung für Truppler-Aufstieg ein. Erstmals 2001 veröffentlicht, repräsentiert der Dewback die Anpassung des Imperiums an lokale Ressourcen für Bodenoperationen. Die Figur zeigt einzigartige Konstruktion mit seiner vierbeinigen Haltung und reptilischen Zügen, die ihn ideal für Wüstenreisen machen. Sammler schätzen Dewbacks für ihr unvergessliches Auftreten in der Special Edition von Eine neue Hoffnung und für die Vervollständigung von Tatooine-Imperialpatrouillen-Ausstellungen. Die Kombination von Sandtruppler-Reitern und Dewback-Reittieren schafft authentische Wüstensuch-Szenen, während das Imperium nach den gestohlenen Todesstern-Plänen jagt.",
    fr: "Les Dewbacks sont de grands animaux de bât reptiliens natifs de Tatooine, utilisés par les sandtroopers Impériaux comme montures pour les opérations de patrouille et de reconnaissance dans le désert. Cette figurine LEGO capture l'apparence distinctive de lézard du dewback avec équipement de selle pour le montage des soldats. Sortie pour la première fois en 2001, le Dewback représente l'adaptation de l'Empire aux ressources locales pour les opérations terrestres. La figurine présente une construction unique montrant sa position quadrupède et ses caractéristiques reptiliennes qui le rendent idéal pour les voyages dans le désert. Les collectionneurs apprécient les Dewbacks pour leur apparition mémorable dans l'Édition Spéciale d'Un Nouvel Espoir et pour compléter les expositions de patrouille Impériale sur Tatooine. La combinaison de cavaliers sandtroopers et de montures dewback crée des scènes de recherche dans le désert authentiques alors que l'Empire chasse les plans volés de l'Étoile de la Mort.",
    es: "Los Dewbacks son grandes animales de carga reptilianos nativos de Tatooine, usados por soldados de arena Imperiales como monturas para patrulla desértica y operaciones de reconocimiento. Esta figura LEGO captura la apariencia distintiva de lagarto del dewback con equipo de montura para montaje de soldado. Lanzada por primera vez en 2001, el Dewback representa la adaptación del Imperio a recursos locales para operaciones terrestres. La figura presenta construcción única mostrando su postura cuadrúpeda y características reptilianas que lo hacen ideal para viaje desértico. Los coleccionistas valoran a los Dewbacks por su aparición memorable en la Edición Especial de Una Nueva Esperanza y por completar exhibiciones de patrulla Imperial de Tatooine. La combinación de jinetes soldados de arena y monturas dewback crea escenas auténticas de búsqueda desértica mientras el Imperio caza los planos robados de la Estrella de la Muerte."
  },
  {
    no: 'sw0207',
    name: 'Jawa',
    en: "Jawas are diminutive scavengers who roam Tatooine's deserts in massive sandcrawlers, collecting and selling droids and salvaged technology. This LEGO minifigure captures the Jawa's distinctive hooded brown robes and glowing yellow eyes that peer from the darkness. First released in 1999, the Jawa has become iconic for its mysterious appearance and role in bringing R2-D2 and C-3PO to Luke Skywalker. The figure features short legs and detailed printing showing the tattered desert garments worn by these secretive traders. Collectors value Jawas for their crucial role starting A New Hope's adventure and for representing Tatooine's unique alien culture. Multiple Jawas are essential for recreating sandcrawler scenes and the droid sale that sets the entire Original Trilogy in motion.",
    de: "Jawas sind winzige Plünderer, die Tatooines Wüsten in massiven Sandkriechern durchstreifen und Droiden und geborgene Technologie sammeln und verkaufen. Diese LEGO-Minifigur fängt die charakteristischen braunen Kapuzenroben und glühenden gelben Augen der Jawas ein, die aus der Dunkelheit spähen. Erstmals 1999 veröffentlicht, ist der Jawa ikonisch geworden für sein mysteriöses Aussehen und seine Rolle dabei, R2-D2 und C-3PO zu Luke Skywalker zu bringen. Die Figur zeigt kurze Beine und detaillierte Bedruckung mit den zerfetzten Wüstengewändern, die von diesen geheimniskrämerischen Händlern getragen werden. Sammler schätzen Jawas für ihre entscheidende Rolle beim Start des Abenteuers von Eine neue Hoffnung und für die Darstellung von Tatooines einzigartiger außerirdischer Kultur. Mehrere Jawas sind unverzichtbar für die Nachbildung von Sandkriecher-Szenen und dem Droiden-Verkauf, der die gesamte Original-Trilogie in Bewegung setzt.",
    fr: "Les Jawas sont de minuscules récupérateurs qui parcourent les déserts de Tatooine dans d'immenses sandcrawlers, collectant et vendant des droïdes et de la technologie récupérée. Cette minifigurine LEGO capture les robes brunes à capuche distinctives du Jawa et les yeux jaunes brillants qui regardent depuis l'obscurité. Sortie pour la première fois en 1999, le Jawa est devenu iconique pour son apparence mystérieuse et son rôle dans l'amener de R2-D2 et C-3PO à Luke Skywalker. La figurine présente des jambes courtes et une impression détaillée montrant les vêtements de désert en lambeaux portés par ces commerçants secrets. Les collectionneurs apprécient les Jawas pour leur rôle crucial dans le démarrage de l'aventure d'Un Nouvel Espoir et pour représenter la culture extraterrestre unique de Tatooine. Plusieurs Jawas sont essentiels pour recréer les scènes de sandcrawler et la vente de droïdes qui met en mouvement toute la trilogie originale.",
    es: "Los Jawas son diminutos carroñeros que recorren los desiertos de Tatooine en masivos oruga de arena, recolectando y vendiendo droides y tecnología recuperada. Esta minifigura LEGO captura las distintivas túnicas marrones con capucha de los Jawas y ojos amarillos brillantes que miran desde la oscuridad. Lanzada por primera vez en 1999, el Jawa se ha vuelto icónico por su apariencia misteriosa y papel en traer a R2-D2 y C-3PO a Luke Skywalker. La figura presenta piernas cortas e impresión detallada mostrando las vestimentas desérticas andrajosas usadas por estos comerciantes secretos. Los coleccionistas valoran a los Jawas por su papel crucial iniciando la aventura de Una Nueva Esperanza y por representar la cultura alienígena única de Tatooine. Múltiples Jawas son esenciales para recrear escenas de oruga de arena y la venta de droides que pone en marcha toda la trilogía original."
  },
  {
    no: 'sw0208',
    name: 'Tusken Raider (Sand People)',
    en: "Tusken Raiders, also known as Sand People, are fierce nomadic warriors who attack Luke Skywalker in the Tatooine desert before Obi-Wan's rescue. This LEGO minifigure captures the Tusken's intimidating appearance with wrapped desert robes, breathing mask, and signature gaderffii stick weapon. First released in 1999, the Tusken Raider represents the dangerous native population that makes Tatooine's wastes so treacherous. The figure features detailed printing showing tribal garments and survival equipment adapted for harsh desert life. Collectors value Tusken Raiders for their memorable attack on Luke and for representing Tatooine's indigenous warrior culture. Multiple Tuskens are essential for recreating their tribal raids and the threatening presence they bring to desert scenes throughout A New Hope.",
    de: "Tusken-Räuber, auch bekannt als Sandleute, sind wilde nomadische Krieger, die Luke Skywalker in der Tatooine-Wüste angreifen, bevor Obi-Wan ihn rettet. Diese LEGO-Minifigur fängt das einschüchternde Aussehen der Tusken mit gewickelten Wüstenroben, Atemmaske und charakteristischer Gaderffii-Stock-Waffe ein. Erstmals 1999 veröffentlicht, repräsentiert der Tusken-Räuber die gefährliche einheimische Bevölkerung, die Tatooines Ödland so tückisch macht. Die Figur zeigt detaillierte Bedruckung mit Stammesgewändern und Überlebensausrüstung, die für das harte Wüstenleben angepasst ist. Sammler schätzen Tusken-Räuber für ihren unvergesslichen Angriff auf Luke und für die Darstellung von Tatooines indigener Kriegerkultur. Mehrere Tusken sind unverzichtbar für die Nachbildung ihrer Stammesüberfälle und der bedrohlichen Präsenz, die sie zu Wüstenszenen in Eine neue Hoffnung bringen.",
    fr: "Les Pillards Tusken, également connus sous le nom de Peuple des Sables, sont de féroces guerriers nomades qui attaquent Luke Skywalker dans le désert de Tatooine avant le sauvetage d'Obi-Wan. Cette minifigurine LEGO capture l'apparence intimidante du Tusken avec des robes de désert enroulées, un masque respiratoire et l'arme signature bâton gaderffii. Sortie pour la première fois en 1999, le Pillard Tusken représente la population indigène dangereuse qui rend les déserts de Tatooine si traîtres. La figurine présente une impression détaillée montrant des vêtements tribaux et un équipement de survie adapté à la vie dure du désert. Les collectionneurs apprécient les Pillards Tusken pour leur attaque mémorable contre Luke et pour représenter la culture guerrière indigène de Tatooine. Plusieurs Tuskens sont essentiels pour recréer leurs raids tribaux et la présence menaçante qu'ils apportent aux scènes de désert tout au long d'Un Nouvel Espoir.",
    es: "Los Moradores de las Arenas Tusken, también conocidos como Gente de Arena, son feroces guerreros nómadas que atacan a Luke Skywalker en el desierto de Tatooine antes del rescate de Obi-Wan. Esta minifigura LEGO captura la apariencia intimidante de los Tusken con túnicas desérticas envueltas, máscara respiratoria y arma característica palo gaderffii. Lanzada por primera vez en 1999, el Morador Tusken representa la peligrosa población nativa que hace que los páramos de Tatooine sean tan traicioneros. La figura presenta impresión detallada mostrando vestimentas tribales y equipo de supervivencia adaptado para la dura vida desértica. Los coleccionistas valoran a los Moradores Tusken por su ataque memorable a Luke y por representar la cultura guerrera indígena de Tatooine. Múltiples Tuskens son esenciales para recrear sus incursiones tribales y la presencia amenazante que traen a escenas desérticas a lo largo de Una Nueva Esperanza."
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 96-100 (sw0204-sw0208)...\n');

  for (const m of batch) {
    await prisma.minifigCatalog.upsert({
      where: { minifigure_no: m.no },
      update: {
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      },
      create: {
        minifigure_no: m.no,
        name: m.name,
        category_id: 1,
        category_name: 'Star Wars',
        search_name: m.name.toLowerCase(),
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`  ✅ ${m.no}: ${m.name}`);
  }

  console.log(`\n✨ Batch 96-100 complete: 5 minifigs (20 descriptions)`);
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
