import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch053 = [
  {
    no: 'sw0454',
    name: 'Asajj Ventress',
    en: 'Asajj Ventress, the deadly Dathomirian assassin and dark side warrior, served as Count Dooku\'s personal apprentice and enforcer during the Clone Wars, wielding twin red lightsabers with lethal precision before her eventual redemption. This 2009 minifigure features Ventress\'s distinctive pale skin tone, bald head with tribal tattoos, detailed printing of her dark combat outfit with armor plating, and her characteristic dual curved-hilt lightsabers. Released in set 7676 (Republic Attack Gunship), this is the first LEGO minifigure of Asajj Ventress. The unique design and dual lightsabers make this figure highly collectible, and Ventress\'s complex character arc from Sith assassin to reluctant hero in The Clone Wars animated series ensures this fierce warrior remains one of the most popular extended universe characters in LEGO Star Wars collections.',
    de: 'Asajj Ventress, die tödliche Dathomirische Attentäterin und Kriegerin der dunklen Seite, diente während der Klonkriege als Count Dookus persönliche Schülerin und Vollstreckerin und schwang zwei rote Lichtschwerter mit tödlicher Präzision vor ihrer eventuellen Erlösung. Diese Minifigur von 2009 zeigt Ventress\' markanten blassen Hautton, kahlen Kopf mit Stammestattoos, detaillierten Druck ihres dunklen Kampfoutfits mit Rüstungsplatten und ihre charakteristischen doppelten gekrümmten Lichtschwerter. Veröffentlicht in Set 7676 (Republic Attack Gunship), ist dies die erste LEGO-Minifigur von Asajj Ventress. Das einzigartige Design und die doppelten Lichtschwerter machen diese Figur sehr sammelwürdig, und Ventress\' komplexer Charakterbogen von Sith-Attentäterin zu widerwilliger Heldin in der animierten Serie The Clone Wars stellt sicher, dass diese wilde Kriegerin einer der beliebtesten Extended-Universe-Charaktere in LEGO Star Wars-Sammlungen bleibt.',
    fr: 'Asajj Ventress, l\'assassin Dathomirienne mortelle et guerrière du côté obscur, servait d\'apprentie et d\'exécutrice personnelle du Comte Dooku pendant la Guerre des Clones, maniant deux sabres laser rouges avec une précision mortelle avant sa rédemption éventuelle. Cette minifigurine de 2009 présente le teint de peau pâle distinctif de Ventress, une tête chauve avec des tatouages tribaux, des impressions détaillées de sa tenue de combat sombre avec des plaques d\'armure, et ses sabres laser doubles à poignée courbée caractéristiques. Sortie dans le set 7676 (Canonnière d\'Attaque de la République), c\'est la première minifigurine LEGO d\'Asajj Ventress. Le design unique et les doubles sabres laser rendent cette figurine très collectionnable, et l\'arc de personnage complexe de Ventress d\'assassin Sith à héros réticent dans la série animée The Clone Wars garantit que cette guerrière féroce reste l\'un des personnages d\'univers étendu les plus populaires dans les collections LEGO Star Wars.',
    es: 'Asajj Ventress, la mortal asesina Dathomiriana y guerrera del lado oscuro, sirvió como aprendiz personal y ejecutora del Conde Dooku durante las Guerras Clon, blandiendo sables de luz rojos gemelos con precisión letal antes de su eventual redención. Esta minifigura de 2009 presenta el distintivo tono de piel pálido de Ventress, cabeza calva con tatuajes tribales, impresiones detalladas de su atuendo de combate oscuro con placas de armadura, y sus característicos sables de luz dobles de empuñadura curva. Lanzado en el set 7676 (Cañonera de Ataque de la República), esta es la primera minifigura LEGO de Asajj Ventress. El diseño único y sables de luz dobles hacen esta figura altamente coleccionable, y el arco de personaje complejo de Ventress de asesina Sith a heroína reacia en la serie animada The Clone Wars asegura que esta feroz guerrera permanezca uno de los personajes de universo extendido más populares en colecciones LEGO Star Wars.'
  },
  {
    no: 'sw0455',
    name: 'Obi-Wan Kenobi (Clone Wars)',
    en: 'Obi-Wan Kenobi appears in this 2009 variant during his service as a Jedi General in the Clone Wars, representing Ewan McGregor\'s character leading the 212th Attack Battalion and serving as one of the Republic\'s most respected military commanders. This minifigure features detailed printing of Obi-Wan\'s Jedi robes with brown and tan layered garments, Clone Wars-era hair and beard styling, tactical equipment belt, and blue lightsaber for countless battles. Released in set 7676 (Republic Attack Gunship), this Clone Wars Obi-Wan captures the mature Jedi Master at his tactical peak. The battle-ready appearance and command presence make this one of the most popular Obi-Wan variants, representing the diplomatic warrior who exemplified the Jedi Order\'s ideals even as he unknowingly led troops toward Order 66 and the destruction of everything he fought to protect.',
    de: 'Obi-Wan Kenobi erscheint in dieser Variante von 2009 während seines Dienstes als Jedi-General in den Klonkriegen und repräsentiert Ewan McGregors Charakter, der das 212. Angriffsbataillon anführt und als einer der angesehensten militärischen Kommandeure der Republik dient. Diese Minifigur zeigt detaillierten Druck von Obi-Wans Jedi-Roben mit braunen und beigen mehrschichtigen Gewändern, Klonkriegs-Ära-Haar- und Bartstil, taktischen Ausrüstungsgürtel und blaues Lichtschwert für unzählige Schlachten. Veröffentlicht in Set 7676 (Republic Attack Gunship), fängt dieser Klonkriegs-Obi-Wan den reifen Jedi-Meister auf seinem taktischen Höhepunkt ein. Das kampfbereite Aussehen und die Kommandopräsenz machen dies zu einer der beliebtesten Obi-Wan-Varianten und repräsentieren den diplomatischen Krieger, der die Ideale des Jedi-Ordens verkörperte, selbst als er unwissentlich Truppen in Richtung Order 66 und die Zerstörung von allem führte, was er zu schützen versuchte.',
    fr: 'Obi-Wan Kenobi apparaît dans cette variante de 2009 pendant son service en tant que Général Jedi dans la Guerre des Clones, représentant le personnage d\'Ewan McGregor dirigeant le 212e Bataillon d\'Attaque et servant comme l\'un des commandants militaires les plus respectés de la République. Cette minifigurine présente des impressions détaillées des robes Jedi d\'Obi-Wan avec des vêtements superposés bruns et beiges, un style de cheveux et de barbe de l\'ère de la Guerre des Clones, une ceinture d\'équipement tactique et un sabre laser bleu pour d\'innombrables batailles. Sortie dans le set 7676 (Canonnière d\'Attaque de la République), cet Obi-Wan de la Guerre des Clones capture le Maître Jedi mature à son apogée tactique. L\'apparence prête au combat et la présence de commandement font de celle-ci l\'une des variantes d\'Obi-Wan les plus populaires, représentant le guerrier diplomatique qui incarnait les idéaux de l\'Ordre Jedi même alors qu\'il dirigeait inconsciemment les troupes vers l\'Ordre 66 et la destruction de tout ce qu\'il combattait pour protéger.',
    es: 'Obi-Wan Kenobi aparece en esta variante de 2009 durante su servicio como General Jedi en las Guerras Clon, representando al personaje de Ewan McGregor liderando el Batallón de Ataque 212 y sirviendo como uno de los comandantes militares más respetados de la República. Esta minifigura presenta impresiones detalladas de las túnicas Jedi de Obi-Wan con prendas en capas marrones y beige, estilo de cabello y barba de la era Clone Wars, cinturón de equipo táctico y sable de luz azul para incontables batallas. Lanzado en el set 7676 (Cañonera de Ataque de la República), este Obi-Wan de Clone Wars captura al Maestro Jedi maduro en su pico táctico. La apariencia lista para batalla y presencia de comando hacen esta una de las variantes de Obi-Wan más populares, representando al guerrero diplomático que ejemplificó los ideales de la Orden Jedi incluso mientras inconscientemente lideraba tropas hacia la Orden 66 y la destrucción de todo lo que luchó por proteger.'
  },
  {
    no: 'sw0456',
    name: 'Clone Trooper (Episode 2, Red Markings)',
    en: 'Clone Troopers with red markings served in specialized Republic units during the Battle of Geonosis and early Clone Wars campaigns, with red coloring typically indicating elite status or service in particular battalions under Jedi command. This 2009 minifigure features Phase I armor with distinctive red stripe patterns, clean white armor showing newly-deployed appearance, and standard clone equipment from the opening battles of the war. Released in set 7163 (Republic Gunship), this red-marked variant provides collectors with a distinctive color scheme for early-war clone forces. The red markings and Episode II context make this figure valuable for army builders recreating the Battle of Geonosis, and collectors appreciate having various color-coded Phase I clones to represent the diverse unit designations that emerged during the Republic\'s initial mobilization of the clone army.',
    de: 'Klontruppen mit roten Markierungen dienten während der Schlacht von Geonosis und frühen Klonkriegs-Kampagnen in spezialisierten republikanischen Einheiten, wobei die rote Färbung typischerweise Elite-Status oder Dienst in bestimmten Bataillonen unter Jedi-Kommando anzeigte. Diese Minifigur von 2009 zeigt Phase-I-Rüstung mit markanten roten Streifenmustern, saubere weiße Rüstung, die neu eingesetzte Erscheinung zeigt, und Standard-Klonausrüstung aus den Eröffnungsschlachten des Krieges. Veröffentlicht in Set 7163 (Republic Gunship), bietet diese rot markierte Variante Sammlern ein markantes Farbschema für Klonstruppen aus dem Früh-Krieg. Die roten Markierungen und der Episode-II-Kontext machen diese Figur wertvoll für Armeebauer, die die Schlacht von Geonosis nachstellen, und Sammler schätzen verschiedene farbcodierte Phase-I-Klone, um die vielfältigen Einheitsbezeichnungen zu repräsentieren, die während der anfänglichen Mobilisierung der Klonarmee durch die Republik entstanden.',
    fr: 'Les Clone Troopers avec des marques rouges servaient dans des unités spécialisées de la République pendant la Bataille de Geonosis et les premières campagnes de la Guerre des Clones, la coloration rouge indiquant généralement un statut d\'élite ou un service dans des bataillons particuliers sous commandement Jedi. Cette minifigurine de 2009 présente une armure Phase I avec des motifs de rayures rouges distinctifs, une armure blanche propre montrant une apparence nouvellement déployée et un équipement de clone standard des premières batailles de la guerre. Sortie dans le set 7163 (Canonnière de la République), cette variante marquée de rouge fournit aux collectionneurs un schéma de couleurs distinctif pour les forces de clones du début de la guerre. Les marques rouges et le contexte de l\'Épisode II rendent cette figurine précieuse pour les constructeurs d\'armées recréant la Bataille de Geonosis, et les collectionneurs apprécient d\'avoir divers clones Phase I codés par couleur pour représenter les diverses désignations d\'unités qui ont émergé pendant la mobilisation initiale de l\'armée clone par la République.',
    es: 'Los Clone Troopers con marcas rojas sirvieron en unidades especializadas de la República durante la Batalla de Geonosis y primeras campañas de las Guerras Clon, con coloración roja típicamente indicando estatus de élite o servicio en batallones particulares bajo comando Jedi. Esta minifigura de 2009 presenta armadura Fase I con distintivos patrones de rayas rojas, armadura blanca limpia mostrando apariencia recién desplegada y equipo de clon estándar de las batallas iniciales de la guerra. Lanzado en el set 7163 (Cañonera de la República), esta variante marcada en rojo proporciona a los coleccionistas un esquema de color distintivo para fuerzas clon de guerra temprana. Las marcas rojas y contexto del Episodio II hacen esta figura valiosa para constructores de ejércitos recreando la Batalla de Geonosis, y los coleccionistas aprecian tener varios clones Fase I codificados por color para representar las diversas designaciones de unidades que emergieron durante la movilización inicial del ejército clon por la República.'
  },
  {
    no: 'sw0457',
    name: 'Yoda (Clone Wars)',
    en: 'Yoda, the ancient and wise Grand Master of the Jedi Order, served as the Republic\'s supreme military advisor during the Clone Wars despite his deep reservations about the Jedi becoming warriors. This 2009 minifigure features Yoda\'s distinctive small green body with detailed robe printing, wrinkled face showing his 900 years of wisdom, gimer stick walking cane, and green lightsaber for his rare but devastating combat appearances. Released in set 7964 (Republic Frigate), this Clone Wars Yoda captures the diminutive master during his battlefield leadership. The small stature and wise expression make this one of the most beloved Star Wars minifigures, and Yoda\'s tragic role watching the Jedi Order fall despite his best efforts gives this ancient master figure poignant significance for collectors understanding the full scope of Palpatine\'s manipulation.',
    de: 'Yoda, der uralte und weise Großmeister des Jedi-Ordens, diente während der Klonkriege als oberster militärischer Berater der Republik, trotz seiner tiefen Vorbehalte gegenüber den Jedi, die zu Kriegern wurden. Diese Minifigur von 2009 zeigt Yodas markanten kleinen grünen Körper mit detailliertem Robendruck, faltiges Gesicht, das seine 900 Jahre Weisheit zeigt, Gimer-Stick-Gehstock und grünes Lichtschwert für seine seltenen, aber verheerenden Kampfauftritte. Veröffentlicht in Set 7964 (Republic Frigate), fängt dieser Klonkriegs-Yoda den winzigen Meister während seiner Schlachtfeldführung ein. Die kleine Statur und der weise Ausdruck machen dies zu einer der beliebtesten Star Wars-Minifiguren, und Yodas tragische Rolle beim Zusehen, wie der Jedi-Orden trotz seiner besten Bemühungen fällt, verleiht dieser uralten Meister-Figur ergreifende Bedeutung für Sammler, die das volle Ausmaß von Palpatines Manipulation verstehen.',
    fr: 'Yoda, le Grand Maître ancien et sage de l\'Ordre Jedi, servait de conseiller militaire suprême de la République pendant la Guerre des Clones malgré ses profondes réserves sur le fait que les Jedi deviennent des guerriers. Cette minifigurine de 2009 présente le petit corps vert distinctif de Yoda avec des impressions de robe détaillées, un visage ridé montrant ses 900 ans de sagesse, une canne gimer stick, et un sabre laser vert pour ses apparitions au combat rares mais dévastatrices. Sortie dans le set 7964 (Frégate de la République), ce Yoda de la Guerre des Clones capture le maître diminutif pendant son leadership sur le champ de bataille. La petite stature et l\'expression sage font de celle-ci l\'une des minifigurines Star Wars les plus aimées, et le rôle tragique de Yoda regardant l\'Ordre Jedi tomber malgré ses meilleurs efforts donne à cette figurine de maître ancien une signification poignante pour les collectionneurs comprenant toute l\'étendue de la manipulation de Palpatine.',
    es: 'Yoda, el antiguo y sabio Gran Maestro de la Orden Jedi, sirvió como asesor militar supremo de la República durante las Guerras Clon a pesar de sus profundas reservas sobre los Jedi convirtiéndose en guerreros. Esta minifigura de 2009 presenta el distintivo cuerpo verde pequeño de Yoda con impresiones de túnica detalladas, rostro arrugado mostrando sus 900 años de sabiduría, bastón de caminar gimer stick, y sable de luz verde para sus raras pero devastadoras apariciones de combate. Lanzado en el set 7964 (Fragata de la República), este Yoda de Clone Wars captura al diminuto maestro durante su liderazgo de campo de batalla. La pequeña estatura y expresión sabia hacen esta una de las minifiguras Star Wars más queridas, y el papel trágico de Yoda observando la Orden Jedi caer a pesar de sus mejores esfuerzos le da a esta figura de maestro antiguo significancia conmovedora para coleccionistas entendiendo el alcance completo de la manipulación de Palpatine.'
  },
  {
    no: 'sw0458',
    name: 'Quinlan Vos',
    en: 'Quinlan Vos, the maverick Jedi Master known for his unorthodox methods and ability to read object histories through psychometry, served as one of the Republic\'s most effective undercover operatives during the Clone Wars. This 2009 minifigure features Quinlan\'s distinctive long dreadlocked hair, yellow facial markings identifying his Kiffar heritage, detailed printing of his rugged Jedi robes with tactical vest, and green lightsaber. Released in set 7964 (Republic Frigate), this is the first LEGO minifigure of Quinlan Vos. The unique appearance and unconventional Jedi approach make this figure highly sought after by collectors, and Quinlan\'s complex storylines in The Clone Wars including his romance with Asajj Ventress and flirtation with the dark side ensure this rogue Jedi remains a fan-favorite expanded universe character.',
    de: 'Quinlan Vos, der eigenwillige Jedi-Meister, bekannt für seine unorthodoxen Methoden und seine Fähigkeit, Objektgeschichten durch Psychometrie zu lesen, diente während der Klonkriege als einer der effektivsten verdeckten Agenten der Republik. Diese Minifigur von 2009 zeigt Quinlans markante lange Dreadlock-Haare, gelbe Gesichtsmarkierungen, die sein Kiffar-Erbe identifizieren, detaillierten Druck seiner robusten Jedi-Roben mit taktischer Weste und grünes Lichtschwert. Veröffentlicht in Set 7964 (Republic Frigate), ist dies die erste LEGO-Minifigur von Quinlan Vos. Das einzigartige Aussehen und der unkonventionelle Jedi-Ansatz machen diese Figur bei Sammlern sehr begehrt, und Quinlans komplexe Handlungen in The Clone Wars, einschließlich seiner Romanze mit Asajj Ventress und seinem Flirt mit der dunklen Seite, stellen sicher, dass dieser Schurken-Jedi ein Fan-Liebling unter den Extended-Universe-Charakteren bleibt.',
    fr: 'Quinlan Vos, le Maître Jedi anticonformiste connu pour ses méthodes non orthodoxes et sa capacité à lire les histoires d\'objets par psychométrie, servait comme l\'un des agents infiltrés les plus efficaces de la République pendant la Guerre des Clones. Cette minifigurine de 2009 présente les longs cheveux en dreadlocks distinctifs de Quinlan, des marques faciales jaunes identifiant son héritage Kiffar, des impressions détaillées de ses robes Jedi robustes avec gilet tactique et un sabre laser vert. Sortie dans le set 7964 (Frégate de la République), c\'est la première minifigurine LEGO de Quinlan Vos. L\'apparence unique et l\'approche Jedi non conventionnelle rendent cette figurine très recherchée par les collectionneurs, et les intrigues complexes de Quinlan dans The Clone Wars, y compris sa romance avec Asajj Ventress et son flirt avec le côté obscur, garantissent que ce Jedi voyou reste un personnage favori des fans de l\'univers étendu.',
    es: 'Quinlan Vos, el Maestro Jedi inconformista conocido por sus métodos poco ortodoxos y habilidad para leer historias de objetos a través de psicometría, sirvió como uno de los operativos encubiertos más efectivos de la República durante las Guerras Clon. Esta minifigura de 2009 presenta el distintivo cabello largo en rastas de Quinlan, marcas faciales amarillas identificando su herencia Kiffar, impresiones detalladas de sus robustas túnicas Jedi con chaleco táctico, y sable de luz verde. Lanzado en el set 7964 (Fragata de la República), esta es la primera minifigura LEGO de Quinlan Vos. La apariencia única y enfoque Jedi no convencional hacen esta figura altamente codiciada por coleccionistas, y las tramas complejas de Quinlan en The Clone Wars incluyendo su romance con Asajj Ventress y coqueteo con el lado oscuro aseguran que este Jedi rebelde permanezca un personaje favorito de fanáticos del universo extendido.'
  },
  {
    no: 'sw0459',
    name: 'Clone Pilot (Phase I)',
    en: 'Clone Pilots in Phase I armor operated Republic starfighters, gunships, and assault craft during the early Clone Wars, providing critical air support and transport capabilities with their specialized flight training. This 2009 minifigure features Phase I armor with distinctive yellow pilot markings, detailed chest printing showing flight harness equipment, specialized helmet with targeting visor, and the color scheme identifying aerial vehicle crews. Released in set 7964 (Republic Frigate), this Phase I pilot variant represents the early-war aviators. The yellow markings and Phase I armor make this figure valuable for collectors building complete early Clone Wars displays, and the pilot designation distinguishes these specialized operators from infantry clones, showing the diverse training and roles within the Grand Army of the Republic\'s military structure.',
    de: 'Klonpiloten in Phase-I-Rüstung operierten während der frühen Klonkriege republikanische Sternenjäger, Kanonenboote und Angriffsschiffe und boten mit ihrem spezialisierten Flugtraining kritische Luftunterstützung und Transportfähigkeiten. Diese Minifigur von 2009 zeigt Phase-I-Rüstung mit markanten gelben Pilotenmarkierungen, detailliertem Brustdruck, der Fluggeschirr-Ausrüstung zeigt, spezialisiertem Helm mit Zielvisier und dem Farbschema, das Luftfahrzeug-Besatzungen identifiziert. Veröffentlicht in Set 7964 (Republic Frigate), repräsentiert diese Phase-I-Piloten-Variante die Flieger aus dem Früh-Krieg. Die gelben Markierungen und Phase-I-Rüstung machen diese Figur wertvoll für Sammler, die vollständige frühe Klonkriegs-Displays aufbauen, und die Pilotenbezeichnung unterscheidet diese spezialisierten Operateure von Infanterie-Klonen und zeigt die vielfältige Ausbildung und Rollen innerhalb der Militärstruktur der Großen Armee der Republik.',
    fr: 'Les Pilotes Clones en armure Phase I opéraient des chasseurs stellaires, des canonnières et des vaisseaux d\'assaut de la République pendant le début de la Guerre des Clones, fournissant un soutien aérien et des capacités de transport critiques avec leur formation de vol spécialisée. Cette minifigurine de 2009 présente une armure Phase I avec des marques de pilote jaunes distinctives, des impressions de poitrine détaillées montrant l\'équipement de harnais de vol, un casque spécialisé avec viseur de ciblage et le schéma de couleurs identifiant les équipages de véhicules aériens. Sortie dans le set 7964 (Frégate de la République), cette variante de pilote Phase I représente les aviateurs du début de la guerre. Les marques jaunes et l\'armure Phase I rendent cette figurine précieuse pour les collectionneurs construisant des présentations complètes du début de la Guerre des Clones, et la désignation de pilote distingue ces opérateurs spécialisés des clones d\'infanterie, montrant la formation et les rôles diversifiés au sein de la structure militaire de la Grande Armée de la République.',
    es: 'Los Pilotos Clon en armadura Fase I operaban cazas estelares, cañoneras y naves de asalto de la República durante las primeras Guerras Clon, proporcionando apoyo aéreo crítico y capacidades de transporte con su entrenamiento de vuelo especializado. Esta minifigura de 2009 presenta armadura Fase I con distintivas marcas de piloto amarillas, impresiones de pecho detalladas mostrando equipo de arnés de vuelo, casco especializado con visor de apuntado y el esquema de color identificando tripulaciones de vehículos aéreos. Lanzado en el set 7964 (Fragata de la República), esta variante de piloto Fase I representa los aviadores de guerra temprana. Las marcas amarillas y armadura Fase I hacen esta figura valiosa para coleccionistas construyendo exhibiciones completas de Clone Wars tempranas, y la designación de piloto distingue estos operadores especializados de clones de infantería, mostrando el entrenamiento diverso y roles dentro de la estructura militar del Gran Ejército de la República.'
  },
  {
    no: 'sw0460',
    name: 'Eeth Koth',
    en: 'Eeth Koth, the Zabrak Jedi Master and member of the High Council, served as one of the Republic\'s military leaders during the Clone Wars, known for his strong connection to the Force and exceptional pain tolerance. This 2009 minifigure features Zabrak horned head with distinctive facial markings, detailed printing of brown Jedi robes with tactical equipment, and green lightsaber representing the Council member from The Phantom Menace and Clone Wars. Released in set 7964 (Republic Frigate), this is the first LEGO minifigure of Eeth Koth. The unique Zabrak design and Council membership make this figure significant for Jedi collections, and Eeth Koth\'s dramatic rescue from General Grievous in The Clone Wars animated series where he endured brutal torture showcases the character\'s resilience that makes this figure memorable despite limited screen time.',
    de: 'Eeth Koth, der Zabrak-Jedi-Meister und Mitglied des Hohen Rats, diente während der Klonkriege als einer der militärischen Führer der Republik, bekannt für seine starke Verbindung zur Macht und außergewöhnliche Schmerztoleranz. Diese Minifigur von 2009 zeigt einen Zabrak-gehörnten Kopf mit markanten Gesichtsmarkierungen, detaillierten Druck brauner Jedi-Roben mit taktischer Ausrüstung und grünes Lichtschwert, das das Ratsmitglied aus Die dunkle Bedrohung und Clone Wars repräsentiert. Veröffentlicht in Set 7964 (Republic Frigate), ist dies die erste LEGO-Minifigur von Eeth Koth. Das einzigartige Zabrak-Design und die Ratsmitgliedschaft machen diese Figur bedeutsam für Jedi-Sammlungen, und Eeth Koths dramatische Rettung von General Grievous in der animierten Serie The Clone Wars, wo er brutale Folter ertrug, zeigt die Widerstandsfähigkeit des Charakters, die diese Figur trotz begrenzter Bildschirmzeit unvergesslich macht.',
    fr: 'Eeth Koth, le Maître Jedi Zabrak et membre du Haut Conseil, servait comme l\'un des leaders militaires de la République pendant la Guerre des Clones, connu pour sa forte connexion à la Force et sa tolérance exceptionnelle à la douleur. Cette minifigurine de 2009 présente une tête Zabrak cornue avec des marques faciales distinctives, des impressions détaillées de robes Jedi brunes avec équipement tactique et un sabre laser vert représentant le membre du Conseil de La Menace Fantôme et Clone Wars. Sortie dans le set 7964 (Frégate de la République), c\'est la première minifigurine LEGO d\'Eeth Koth. Le design Zabrak unique et l\'adhésion au Conseil rendent cette figurine significative pour les collections Jedi, et le sauvetage dramatique d\'Eeth Koth du Général Grievous dans la série animée The Clone Wars où il a enduré une torture brutale montre la résilience du personnage qui rend cette figurine mémorable malgré un temps d\'écran limité.',
    es: 'Eeth Koth, el Maestro Jedi Zabrak y miembro del Alto Consejo, sirvió como uno de los líderes militares de la República durante las Guerras Clon, conocido por su fuerte conexión con la Fuerza y excepcional tolerancia al dolor. Esta minifigura de 2009 presenta cabeza Zabrak con cuernos con distintivas marcas faciales, impresiones detalladas de túnicas Jedi marrones con equipo táctico, y sable de luz verde representando al miembro del Consejo de La Amenaza Fantasma y Clone Wars. Lanzado en el set 7964 (Fragata de la República), esta es la primera minifigura LEGO de Eeth Koth. El diseño Zabrak único y membresía del Consejo hacen esta figura significativa para colecciones Jedi, y el dramático rescate de Eeth Koth del General Grievous en la serie animada The Clone Wars donde soportó brutal tortura muestra la resiliencia del personaje que hace esta figura memorable a pesar del tiempo de pantalla limitado.'
  },
  {
    no: 'sw0461',
    name: 'Adi Gallia',
    en: 'Adi Gallia, the Tholothian Jedi Master and member of the High Council, served as one of the Republic\'s respected military commanders during the Clone Wars, known for her diplomatic skills and strategic thinking. This 2009 minifigure features distinctive Tholothian head with ornate cranial ridges and tendrils, detailed printing of brown Jedi robes with council regalia, and blue lightsaber representing Michelle Taylor\'s character from The Phantom Menace onward. Released in set 7964 (Republic Frigate), this is the first LEGO minifigure of Adi Gallia. The unique alien design and Council membership make this figure essential for comprehensive Jedi High Council displays, and Adi Gallia\'s tragic death at the hands of Savage Opress in The Clone Wars gives this diplomatic master figure poignant significance for collectors building complete prequel-era Jedi rosters.',
    de: 'Adi Gallia, die Tholothianische Jedi-Meisterin und Mitglied des Hohen Rats, diente während der Klonkriege als eine der angesehenen militärischen Kommandeure der Republik, bekannt für ihre diplomatischen Fähigkeiten und strategisches Denken. Diese Minifigur von 2009 zeigt einen markanten Tholothianischen Kopf mit kunstvollen Schädelgraten und Ranken, detaillierten Druck brauner Jedi-Roben mit Ratsinsignien und blaues Lichtschwert, das Michelle Taylors Charakter ab Die dunkle Bedrohung repräsentiert. Veröffentlicht in Set 7964 (Republic Frigate), ist dies die erste LEGO-Minifigur von Adi Gallia. Das einzigartige Alien-Design und die Ratsmitgliedschaft machen diese Figur unerlässlich für umfassende Jedi-Hoher-Rat-Displays, und Adi Gallias tragischer Tod durch die Hände von Savage Opress in The Clone Wars verleiht dieser diplomatischen Meister-Figur ergreifende Bedeutung für Sammler, die vollständige Jedi-Listen aus der Prequel-Ära aufbauen.',
    fr: 'Adi Gallia, la Maître Jedi Tholothienne et membre du Haut Conseil, servait comme l\'un des commandants militaires respectés de la République pendant la Guerre des Clones, connue pour ses compétences diplomatiques et sa pensée stratégique. Cette minifigurine de 2009 présente une tête Tholothienne distinctive avec des crêtes crâniennes et des vrilles ornées, des impressions détaillées de robes Jedi brunes avec regalia du conseil et un sabre laser bleu représentant le personnage de Michelle Taylor de La Menace Fantôme en avant. Sortie dans le set 7964 (Frégate de la République), c\'est la première minifigurine LEGO d\'Adi Gallia. Le design alien unique et l\'adhésion au Conseil rendent cette figurine essentielle pour des présentations complètes du Haut Conseil Jedi, et la mort tragique d\'Adi Gallia aux mains de Savage Opress dans The Clone Wars donne à cette figurine de maître diplomatique une signification poignante pour les collectionneurs construisant des listes Jedi complètes de l\'ère des préquelles.',
    es: 'Adi Gallia, la Maestra Jedi Tholothiana y miembro del Alto Consejo, sirvió como una de los comandantes militares respetados de la República durante las Guerras Clon, conocida por sus habilidades diplomáticas y pensamiento estratégico. Esta minifigura de 2009 presenta distintiva cabeza Tholothiana con crestas craneales ornamentadas y zarcillos, impresiones detalladas de túnicas Jedi marrones con insignias del consejo, y sable de luz azul representando al personaje de Michelle Taylor desde La Amenaza Fantasma en adelante. Lanzado en el set 7964 (Fragata de la República), esta es la primera minifigura LEGO de Adi Gallia. El diseño alienígena único y membresía del Consejo hacen esta figura esencial para exhibiciones completas del Alto Consejo Jedi, y la trágica muerte de Adi Gallia a manos de Savage Opress en The Clone Wars le da a esta figura de maestra diplomática significancia conmovedora para coleccionistas construyendo listas Jedi completas de la era de precuelas.'
  },
  {
    no: 'sw0462',
    name: 'Nahdar Vebb',
    en: 'Nahdar Vebb, the Mon Calamari Jedi Knight and former Padawan of Kit Fisto, served the Republic during the Clone Wars until his tragic death at the hands of General Grievous while attempting to capture the cyborg general. This 2009 minifigure features distinctive Mon Calamari salmon-colored head with large eyes and mouth tentacles, detailed printing of Jedi robes with tactical gear, and blue lightsaber. Released in set 8095 (General Grievous\' Starfighter), this is the first and only LEGO minifigure of Nahdar Vebb. The unique Mon Calamari Jedi design makes this figure rare and collectible, and Nahdar\'s brave but ultimately fatal confrontation with Grievous in The Clone Wars animated series showcases the dangers Jedi faced during the war, making this figure a poignant reminder of the Order\'s losses.',
    de: 'Nahdar Vebb, der Mon-Calamari-Jedi-Ritter und ehemalige Padawan von Kit Fisto, diente während der Klonkriege der Republik bis zu seinem tragischen Tod durch die Hände von General Grievous beim Versuch, den kybernetischen General zu fangen. Diese Minifigur von 2009 zeigt einen markanten lachsfarbenen Mon-Calamari-Kopf mit großen Augen und Mundtentakeln, detaillierten Druck von Jedi-Roben mit taktischer Ausrüstung und blaues Lichtschwert. Veröffentlicht in Set 8095 (General Grievous\' Starfighter), ist dies die erste und einzige LEGO-Minifigur von Nahdar Vebb. Das einzigartige Mon-Calamari-Jedi-Design macht diese Figur selten und sammelwürdig, und Nahdars tapfere, aber letztlich tödliche Konfrontation mit Grievous in der animierten Serie The Clone Wars zeigt die Gefahren, denen Jedi während des Krieges ausgesetzt waren, und macht diese Figur zu einer ergreifenden Erinnerung an die Verluste des Ordens.',
    fr: 'Nahdar Vebb, le Chevalier Jedi Mon Calamari et ancien Padawan de Kit Fisto, servait la République pendant la Guerre des Clones jusqu\'à sa mort tragique aux mains du Général Grievous en tentant de capturer le général cyborg. Cette minifigurine de 2009 présente une tête Mon Calamari de couleur saumon distinctive avec de grands yeux et des tentacules buccaux, des impressions détaillées de robes Jedi avec équipement tactique et un sabre laser bleu. Sortie dans le set 8095 (Le Chasseur Stellaire du Général Grievous), c\'est la première et unique minifigurine LEGO de Nahdar Vebb. Le design unique de Jedi Mon Calamari rend cette figurine rare et collectionnable, et la confrontation courageuse mais finalement fatale de Nahdar avec Grievous dans la série animée The Clone Wars montre les dangers auxquels les Jedi étaient confrontés pendant la guerre, faisant de cette figurine un rappel poignant des pertes de l\'Ordre.',
    es: 'Nahdar Vebb, el Caballero Jedi Mon Calamari y ex Padawan de Kit Fisto, sirvió a la República durante las Guerras Clon hasta su trágica muerte a manos del General Grievous mientras intentaba capturar al general cyborg. Esta minifigura de 2009 presenta distintiva cabeza Mon Calamari color salmón con ojos grandes y tentáculos bucales, impresiones detalladas de túnicas Jedi con equipo táctico, y sable de luz azul. Lanzado en el set 8095 (Caza Estelar del General Grievous), esta es la primera y única minifigura LEGO de Nahdar Vebb. El diseño único de Jedi Mon Calamari hace esta figura rara y coleccionable, y la confrontación valiente pero finalmente fatal de Nahdar con Grievous en la serie animada The Clone Wars muestra los peligros que los Jedi enfrentaron durante la guerra, haciendo esta figura un recordatorio conmovedor de las pérdidas de la Orden.'
  },
  {
    no: 'sw0463',
    name: 'General Grievous (Clone Wars)',
    en: 'General Grievous, the fearsome cyborg commander of the Separatist droid armies, terrorized the Republic with his collection of Jedi lightsabers and ability to wield four blades simultaneously during the Clone Wars. This 2009 minifigure features Grievous\'s distinctive skeletal mechanical body with white armor plating, cape, clawed feet, four arms for wielding multiple lightsabers, and menacing masked face showing his remaining organic eyes. Released in set 8095 (General Grievous\' Starfighter), this Clone Wars Grievous captures the cyborg general at his most threatening. The four-armed construction and intimidating design make this one of the most impressive Star Wars villain figures, and Grievous\'s reputation as a Jedi killer who collected trophies from fallen warriors ensures this mechanical monster remains essential for any Clone Wars collection.',
    de: 'General Grievous, der furchterregende kybernetische Kommandant der Separatisten-Droideenarmeen, terrorisierte während der Klonkriege die Republik mit seiner Sammlung von Jedi-Lichtschwertern und seiner Fähigkeit, vier Klingen gleichzeitig zu schwingen. Diese Minifigur von 2009 zeigt Grievous\' markanten skelettartigen mechanischen Körper mit weißen Rüstungsplatten, Umhang, Klauenfüßen, vier Armen zum Schwingen mehrerer Lichtschwerter und bedrohlichem maskiertem Gesicht, das seine verbleibenden organischen Augen zeigt. Veröffentlicht in Set 8095 (General Grievous\' Starfighter), fängt dieser Klonkriegs-Grievous den kybernetischen General auf seinem bedrohlichsten Punkt ein. Die vierarmige Konstruktion und das einschüchternde Design machen dies zu einer der beeindruckendsten Star Wars-Bösewicht-Figuren, und Grievous\' Ruf als Jedi-Killer, der Trophäen von gefallenen Kriegern sammelte, stellt sicher, dass dieses mechanische Monster für jede Clone Wars-Sammlung unerlässlich bleibt.',
    fr: 'Le Général Grievous, le commandant cyborg redoutable des armées de droïdes Séparatistes, terrorisait la République avec sa collection de sabres laser Jedi et sa capacité à manier quatre lames simultanément pendant la Guerre des Clones. Cette minifigurine de 2009 présente le corps mécanique squelettique distinctif de Grievous avec des plaques d\'armure blanches, une cape, des pieds griffus, quatre bras pour manier plusieurs sabres laser et un visage masqué menaçant montrant ses yeux organiques restants. Sortie dans le set 8095 (Le Chasseur Stellaire du Général Grievous), ce Grievous de la Guerre des Clones capture le général cyborg à son point le plus menaçant. La construction à quatre bras et le design intimidant font de celle-ci l\'une des figurines de méchants Star Wars les plus impressionnantes, et la réputation de Grievous en tant que tueur de Jedi qui collectait des trophées de guerriers tombés garantit que ce monstre mécanique reste essentiel pour toute collection Clone Wars.',
    es: 'El General Grievous, el temible comandante cyborg de los ejércitos de droides Separatistas, aterrorizó a la República con su colección de sables de luz Jedi y habilidad para blandir cuatro hojas simultáneamente durante las Guerras Clon. Esta minifigura de 2009 presenta el distintivo cuerpo mecánico esquelético de Grievous con placas de armadura blancas, capa, pies con garras, cuatro brazos para blandir múltiples sables de luz, y amenazante rostro enmascarado mostrando sus ojos orgánicos restantes. Lanzado en el set 8095 (Caza Estelar del General Grievous), este Grievous de Clone Wars captura al general cyborg en su punto más amenazante. La construcción de cuatro brazos y diseño intimidante hacen esta una de las figuras de villanos Star Wars más impresionantes, y la reputación de Grievous como asesino de Jedi que coleccionaba trofeos de guerreros caídos asegura que este monstruo mecánico permanezca esencial para cualquier colección Clone Wars.'
  }
];

async function saveBatch053() {
  console.log('💾 Saving batch 053 (sw0454-sw0463) - 10 minifigs...\n');

  let saved = 0;
  let skipped = 0;

  for (const m of batch053) {
    try {
      await prisma.minifigCatalog.update({
        where: { minifigure_no: m.no },
        data: {
          description_en: m.en,
          description_de: m.de,
          description_fr: m.fr,
          description_es: m.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        }
      });
      console.log(`  ✅ ${m.no}: ${m.name}`);
      saved++;
    } catch (error: any) {
      console.log(`  ⚠️  ${m.no}: NOT IN DATABASE (skipped)`);
      skipped++;
    }
  }

  console.log(`\n✨ Batch 053 complete: ${saved} saved, ${skipped} skipped (${saved * 4} descriptions)\n`);

  await prisma.$disconnect();
}

saveBatch053().catch(console.error);
