import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0028a',
    name: 'Astromech Droid, R2-D2 - Dark Bluish Gray Serving Tray',
    en: 'R2-D2 with serving tray represents one of the most charming moments from Return of the Jedi when he served drinks aboard Jabba\'s sail barge. This LEGO minifigure features the iconic blue and white astromech droid with an attached dark bluish gray serving tray accessory. The figure includes R2-D2\'s detailed printing showing sensor ports, panel lines, and the distinctive dome head design that made him one of Star Wars\' most beloved characters. Released in 2006 as part of Jabba\'s Sail Barge sets, this variant captures R2-D2\'s brief role as a servant droid during the rescue mission. The dark bluish gray serving tray accessory is unique to this version, distinguishing it from standard R2-D2 minifigures. As a memorable character moment showing R2-D2\'s versatility and the heroes\' disguised infiltration, this serving tray R2-D2 is highly collectible among fans who appreciate the details of Return of the Jedi scenes.',
    de: 'R2-D2 mit Serviertablett repräsentiert einen der charmantesten Momente aus Die Rückkehr der Jedi-Ritter, als er Getränke an Bord von Jabbas Segelkahn servierte. Diese LEGO Minifigur zeigt den ikonischen blau-weißen Astromech-Droiden mit einem angebrachten dunkelblaugrauen Serviertablett-Zubehör. Die Figur enthält R2-D2s detaillierte Bedruckung, die Sensoröffnungen, Panellinien und das charakteristische Kuppelkopf-Design zeigt, das ihn zu einem der beliebtesten Charaktere von Star Wars machte. Veröffentlicht im Jahr 2006 als Teil von Jabbas-Segelkahn-Sets, fängt diese Variante R2-D2s kurze Rolle als Diener-Droide während der Rettungsmission ein. Das dunkelblaugraue Serviertablett-Zubehör ist einzigartig für diese Version und unterscheidet sie von Standard-R2-D2-Minifiguren. Als unvergesslicher Charaktermoment, der R2-D2s Vielseitigkeit und die verkleidete Infiltration der Helden zeigt, ist dieser Serviertablett-R2-D2 bei Fans sehr sammelwürdig, die die Details von Die-Rückkehr-der-Jedi-Ritter-Szenen schätzen.',
    fr: 'R2-D2 avec plateau de service représente l\'un des moments les plus charmants du Retour du Jedi lorsqu\'il servait des boissons à bord de la barge à voile de Jabba. Cette minifigurine LEGO présente le droïde astromech bleu et blanc iconique avec un accessoire de plateau de service gris bleuté foncé attaché. La figurine comprend l\'impression détaillée de R2-D2 montrant des ports de capteurs, des lignes de panneaux et la conception de tête en dôme distinctive qui a fait de lui l\'un des personnages les plus aimés de Star Wars. Sortie en 2006 dans des sets de la Barge à Voile de Jabba, cette variante capture le bref rôle de R2-D2 comme droïde serviteur pendant la mission de sauvetage. L\'accessoire de plateau de service gris bleuté foncé est unique à cette version, la distinguant des minifigurines R2-D2 standard. En tant que moment de personnage mémorable montrant la polyvalence de R2-D2 et l\'infiltration déguisée des héros, ce R2-D2 avec plateau de service est très collectionnable parmi les fans qui apprécient les détails des scènes du Retour du Jedi.',
    es: 'R2-D2 con bandeja de servicio representa uno de los momentos más encantadores de El Retorno del Jedi cuando servía bebidas a bordo de la barcaza vela de Jabba. Esta minifigura LEGO presenta el icónico droide astromecánico azul y blanco con un accesorio de bandeja de servicio gris azulado oscuro adjunto. La figura incluye la impresión detallada de R2-D2 mostrando puertos de sensores, líneas de panel y el distintivo diseño de cabeza con cúpula que lo convirtió en uno de los personajes más queridos de Star Wars. Lanzada en 2006 como parte de sets de la Barcaza Vela de Jabba, esta variante captura el breve papel de R2-D2 como droide servidor durante la misión de rescate. El accesorio de bandeja de servicio gris azulado oscuro es único para esta versión, distinguiéndola de minifiguras R2-D2 estándar. Como momento memorable del personaje mostrando la versatilidad de R2-D2 y la infiltración disfrazada de los héroes, este R2-D2 con bandeja de servicio es altamente coleccionable entre fans que aprecian los detalles de escenas de El Retorno del Jedi.'
  },
  {
    no: 'sw0087',
    name: 'Gamorrean Guard - Sand Green, Reddish Brown Arms',
    en: 'The Gamorrean Guard represents the brutish pig-like warriors who served as Jabba the Hutt\'s palace guards in Return of the Jedi. This LEGO minifigure features the sand green body with reddish brown arms, detailed printing showing armor plates and weapon harness, and the distinctive pig snout head piece. The figure captures the intimidating appearance of these muscular guards with their crude armor and axes. Released in 2006 as part of Jabba\'s Palace sets, this variant with sand green body and reddish brown arms represents the classic Gamorrean coloring. The combination of green skin tone and brown leather armor creates an authentic look from the original trilogy. As iconic henchmen from one of Star Wars\' most memorable locations, Gamorrean Guards are essential for collectors building Jabba\'s Palace throne room scenes and are often acquired in multiples to create the full guard contingent.',
    de: 'Der Gamorreaner-Wächter repräsentiert die brutalen schweineartigen Krieger, die als Jabbas des Hutten Palastwächter in Die Rückkehr der Jedi-Ritter dienten. Diese LEGO Minifigur zeigt den sandgrünen Körper mit rotbraunen Armen, detaillierte Bedruckung, die Rüstungsplatten und Waffengeschirr zeigt, und das charakteristische Schweineschnauzen-Kopfteil. Die Figur fängt das einschüchternde Aussehen dieser muskulösen Wächter mit ihrer groben Rüstung und Äxten ein. Veröffentlicht im Jahr 2006 als Teil von Jabbas-Palast-Sets, repräsentiert diese Variante mit sandgrünem Körper und rotbraunen Armen die klassische Gamorreaner-Färbung. Die Kombination aus grünem Hautton und brauner Lederrüstung schafft einen authentischen Look aus der Original-Trilogie. Als ikonische Schergen aus einem der unvergesslichsten Orte von Star Wars sind Gamorreaner-Wächter für Sammler unverzichtbar, die Jabbas Palast-Thronsaal-Szenen bauen, und werden oft in Vielfachen erworben, um das volle Wächter-Kontingent zu erstellen.',
    fr: 'Le Garde Gamorréen représente les guerriers brutaux ressemblant à des cochons qui servaient de gardes du palais de Jabba le Hutt dans Le Retour du Jedi. Cette minifigurine LEGO présente le corps vert sable avec des bras brun rougeâtre, une impression détaillée montrant des plaques d\'armure et un harnais d\'armes, et la pièce de tête distinctive de museau de cochon. La figurine capture l\'apparence intimidante de ces gardes musclés avec leur armure grossière et leurs haches. Sortie en 2006 dans des sets du Palais de Jabba, cette variante avec corps vert sable et bras brun rougeâtre représente la coloration Gamorréenne classique. La combinaison de teint de peau vert et d\'armure de cuir marron crée un look authentique de la trilogie originale. En tant que hommes de main iconiques de l\'un des lieux les plus mémorables de Star Wars, les Gardes Gamorréens sont essentiels pour les collectionneurs construisant des scènes de salle du trône du Palais de Jabba et sont souvent acquis en multiples pour créer le contingent complet de gardes.',
    es: 'El Guardia Gamorreano representa a los guerreros brutales parecidos a cerdos que sirvieron como guardias del palacio de Jabba el Hutt en El Retorno del Jedi. Esta minifigura LEGO presenta el cuerpo verde arena con brazos marrón rojizo, impresión detallada mostrando placas de armadura y arnés de armas, y la distintiva pieza de cabeza de hocico de cerdo. La figura captura la apariencia intimidante de estos guardias musculosos con su armadura tosca y hachas. Lanzada en 2006 como parte de sets del Palacio de Jabba, esta variante con cuerpo verde arena y brazos marrón rojizo representa la coloración Gamorreana clásica. La combinación de tono de piel verde y armadura de cuero marrón crea un look auténtico de la trilogía original. Como secuaces icónicos de uno de los lugares más memorables de Star Wars, los Guardias Gamorreanos son esenciales para coleccionistas construyendo escenas de sala del trono del Palacio de Jabba y son a menudo adquiridos en múltiplos para crear el contingente completo de guardias.'
  },
  {
    no: 'sw0090',
    name: 'Luke Skywalker - Pilot Suit, Simple Torso and Helmet, Light Nougat Head',
    en: 'Luke Skywalker in his Rebel pilot suit represents his role as Red Five during the Battle of Yavin in A New Hope. This LEGO minifigure features the light nougat head, simple torso printing showing the orange flight suit, and the distinctive Rebel pilot helmet. The figure captures Luke\'s appearance during his famous trench run that destroyed the Death Star. Released in 2006 as part of X-wing Starfighter sets, this variant with simple torso design represents an earlier, less detailed printing style. The orange flight suit and white helmet combination is instantly recognizable as Luke\'s most heroic moment. As the pilot who fired the shot that destroyed the Empire\'s ultimate weapon, this X-wing pilot Luke is essential for collectors building Death Star trench run scenes and Rebel starfighter squadrons from the Original Trilogy\'s climactic battle.',
    de: 'Luke Skywalker in seinem Rebellenpiloten-Anzug repräsentiert seine Rolle als Rot Fünf während der Schlacht von Yavin in Eine neue Hoffnung. Diese LEGO Minifigur zeigt den hellen Nougat-Kopf, einfache Torso-Bedruckung, die den orangefarbenen Fluganzug zeigt, und den charakteristischen Rebellenpiloten-Helm. Die Figur fängt Lukes Aussehen während seines berühmten Grabenlaufs ein, der den Todesstern zerstörte. Veröffentlicht im Jahr 2006 als Teil von X-Wing-Starfighter-Sets, repräsentiert diese Variante mit einfachem Torso-Design einen früheren, weniger detaillierten Druckstil. Die Kombination aus orangefarbenem Fluganzug und weißem Helm ist sofort als Lukes heroischster Moment erkennbar. Als Pilot, der den Schuss abfeuerte, der die ultimative Waffe des Imperiums zerstörte, ist dieser X-Wing-Pilot-Luke für Sammler unverzichtbar, die Todesstern-Grabenlauf-Szenen und Rebellen-Sternenjäger-Staffeln aus der klimatischen Schlacht der Original-Trilogie bauen.',
    fr: 'Luke Skywalker dans sa combinaison de pilote Rebelle représente son rôle de Rouge Cinq pendant la Bataille de Yavin dans Un Nouvel Espoir. Cette minifigurine LEGO présente la tête nougat clair, une impression de torse simple montrant la combinaison de vol orange et le casque de pilote Rebelle distinctif. La figurine capture l\'apparence de Luke pendant sa célèbre course de tranchée qui a détruit l\'Étoile de la Mort. Sortie en 2006 dans des sets de Chasseur Stellaire X-wing, cette variante avec conception de torse simple représente un style d\'impression antérieur, moins détaillé. La combinaison de combinaison de vol orange et de casque blanc est instantanément reconnaissable comme le moment le plus héroïque de Luke. En tant que pilote qui a tiré le coup qui a détruit l\'arme ultime de l\'Empire, ce Luke pilote d\'X-wing est essentiel pour les collectionneurs construisant des scènes de course de tranchée de l\'Étoile de la Mort et des escadrons de chasseurs stellaires Rebelles de la bataille climatique de la Trilogie Originale.',
    es: 'Luke Skywalker en su traje de piloto Rebelde representa su papel como Rojo Cinco durante la Batalla de Yavin en Una Nueva Esperanza. Esta minifigura LEGO presenta la cabeza nougat claro, impresión de torso simple mostrando el traje de vuelo naranja y el distintivo casco de piloto Rebelde. La figura captura la apariencia de Luke durante su famosa carrera de trinchera que destruyó la Estrella de la Muerte. Lanzada en 2006 como parte de sets de Caza Estelar X-wing, esta variante con diseño de torso simple representa un estilo de impresión más temprano, menos detallado. La combinación de traje de vuelo naranja y casco blanco es instantáneamente reconocible como el momento más heroico de Luke. Como el piloto que disparó el tiro que destruyó el arma definitiva del Imperio, este Luke piloto de X-wing es esencial para coleccionistas construyendo escenas de carrera de trinchera de la Estrella de la Muerte y escuadrones de cazas estelares Rebeldes de la batalla climática de la Trilogía Original.'
  },
  {
    no: 'sw0088',
    name: 'Han Solo - Light Nougat, Reddish Brown Legs with Holster',
    en: 'Han Solo with detailed holster printing represents his classic smuggler appearance from the Original Trilogy. This LEGO minifigure features the light nougat skin tone and reddish brown legs with holster printing that shows his signature DL-44 blaster placement. The figure includes detailed torso printing of his vest, utility belt, and the practical attire that defined Han\'s roguish character. Released in 2007 as part of various sets, this variant with leg holster printing represents an upgrade in detail over earlier versions. The holster printing on the legs distinguishes this from simpler Han Solo variants without leg detail. As one of the most beloved characters in Star Wars and the ultimate space scoundrel, Han Solo minifigures with enhanced details like holster printing are highly sought after by collectors who appreciate the improved accuracy and visual interest.',
    de: 'Han Solo mit detaillierter Halfter-Bedruckung repräsentiert sein klassisches Schmuggler-Aussehen aus der Original-Trilogie. Diese LEGO Minifigur zeigt den hellen Nougat-Hautton und rotbraune Beine mit Halfter-Bedruckung, die seine charakteristische DL-44-Blaster-Platzierung zeigt. Die Figur enthält detaillierte Torso-Bedruckung seiner Weste, Werkzeuggürtel und der praktischen Kleidung, die Hans schelmischen Charakter definierte. Veröffentlicht im Jahr 2007 als Teil verschiedener Sets, repräsentiert diese Variante mit Bein-Halfter-Bedruckung ein Upgrade in Details gegenüber früheren Versionen. Die Halfter-Bedruckung auf den Beinen unterscheidet diese von einfacheren Han-Solo-Varianten ohne Beindetail. Als einer der beliebtesten Charaktere in Star Wars und der ultimative Weltraum-Schurke sind Han-Solo-Minifiguren mit verbesserten Details wie Halfter-Bedruckung bei Sammlern sehr begehrt, die die verbesserte Genauigkeit und visuelles Interesse schätzen.',
    fr: 'Han Solo avec impression d\'étui détaillée représente son apparence de contrebandier classique de la Trilogie Originale. Cette minifigurine LEGO présente le teint nougat clair et les jambes brun rougeâtre avec impression d\'étui qui montre le placement de son blaster DL-44 signature. La figurine comprend une impression de torse détaillée de son gilet, sa ceinture utilitaire et la tenue pratique qui définissait le personnage roué de Han. Sortie en 2007 dans divers sets, cette variante avec impression d\'étui de jambe représente une amélioration de détail par rapport aux versions antérieures. L\'impression d\'étui sur les jambes distingue celle-ci des variantes Han Solo plus simples sans détail de jambe. En tant que l\'un des personnages les plus aimés de Star Wars et le contrebandier spatial ultime, les minifigurines Han Solo avec des détails améliorés comme l\'impression d\'étui sont très recherchées par les collectionneurs qui apprécient la précision améliorée et l\'intérêt visuel.',
    es: 'Han Solo con impresión de funda detallada representa su apariencia clásica de contrabandista de la Trilogía Original. Esta minifigura LEGO presenta el tono de piel nougat claro y piernas marrón rojizo con impresión de funda que muestra la colocación de su blaster DL-44 característico. La figura incluye impresión de torso detallada de su chaleco, cinturón utilitario y el atuendo práctico que definió el personaje pícaro de Han. Lanzada en 2007 como parte de varios sets, esta variante con impresión de funda de pierna representa una mejora en detalle sobre versiones anteriores. La impresión de funda en las piernas distingue esta de variantes más simples de Han Solo sin detalle de pierna. Como uno de los personajes más queridos en Star Wars y el bribón espacial definitivo, las minifiguras de Han Solo con detalles mejorados como impresión de funda son muy buscadas por coleccionistas que aprecian la precisión mejorada e interés visual.'
  },
  {
    no: 'sw0089',
    name: 'Wedge Antilles',
    en: 'Wedge Antilles is one of the greatest starfighter pilots in the Rebel Alliance, second only to Luke Skywalker in skill and accomplishment. This LEGO minifigure features the orange flight suit and Rebel pilot helmet that identifies him as a member of Red Squadron during the Battle of Yavin. The figure includes detailed printing showing life support equipment and the practical gear worn by X-wing pilots. Released in 2007 as part of X-wing Starfighter sets, this minifigure represents the only Rebel pilot to survive both Death Star battles. Wedge\'s participation in the destruction of both Death Stars makes him one of the most accomplished combat pilots in Star Wars history. As a named hero character rather than a generic pilot, Wedge Antilles is highly valued by collectors who focus on Rebel Alliance aces and the elite pilots who flew in the Original Trilogy\'s most important battles.',
    de: 'Wedge Antilles ist einer der größten Sternenjäger-Piloten in der Rebellenallianz, an Geschick und Leistung nur Luke Skywalker unterlegen. Diese LEGO Minifigur zeigt den orangefarbenen Fluganzug und Rebellenpiloten-Helm, der ihn als Mitglied der Roten Staffel während der Schlacht von Yavin identifiziert. Die Figur enthält detaillierte Bedruckung, die Lebenserhaltungsausrüstung und die praktische Ausrüstung zeigt, die von X-Wing-Piloten getragen wurde. Veröffentlicht im Jahr 2007 als Teil von X-Wing-Starfighter-Sets, repräsentiert diese Minifigur den einzigen Rebellenpiloten, der beide Todesstern-Schlachten überlebte. Wedges Teilnahme an der Zerstörung beider Todessterne macht ihn zu einem der erfolgreichsten Kampfpiloten in der Geschichte von Star Wars. Als benannter Heldencharakter statt eines generischen Piloten wird Wedge Antilles von Sammlern hoch geschätzt, die sich auf Rebellenallianz-Asse und die Elite-Piloten konzentrieren, die in den wichtigsten Schlachten der Original-Trilogie flogen.',
    fr: 'Wedge Antilles est l\'un des plus grands pilotes de chasseurs stellaires de l\'Alliance Rebelle, deuxième seulement derrière Luke Skywalker en compétence et accomplissement. Cette minifigurine LEGO présente la combinaison de vol orange et le casque de pilote Rebelle qui l\'identifie comme membre de l\'Escadron Rouge pendant la Bataille de Yavin. La figurine comprend une impression détaillée montrant l\'équipement de survie et l\'équipement pratique porté par les pilotes d\'X-wing. Sortie en 2007 dans des sets de Chasseur Stellaire X-wing, cette minifigurine représente le seul pilote Rebelle à avoir survécu aux deux batailles de l\'Étoile de la Mort. La participation de Wedge à la destruction des deux Étoiles de la Mort fait de lui l\'un des pilotes de combat les plus accomplis de l\'histoire de Star Wars. En tant que personnage héros nommé plutôt qu\'un pilote générique, Wedge Antilles est très valorisé par les collectionneurs qui se concentrent sur les as de l\'Alliance Rebelle et les pilotes d\'élite qui ont volé dans les batailles les plus importantes de la Trilogie Originale.',
    es: 'Wedge Antilles es uno de los mejores pilotos de cazas estelares en la Alianza Rebelde, segundo solo después de Luke Skywalker en habilidad y logro. Esta minifigura LEGO presenta el traje de vuelo naranja y casco de piloto Rebelde que lo identifica como miembro del Escuadrón Rojo durante la Batalla de Yavin. La figura incluye impresión detallada mostrando equipo de soporte vital y el equipo práctico usado por pilotos de X-wing. Lanzada en 2007 como parte de sets de Caza Estelar X-wing, esta minifigura representa el único piloto Rebelde en sobrevivir ambas batallas de la Estrella de la Muerte. La participación de Wedge en la destrucción de ambas Estrellas de la Muerte lo convierte en uno de los pilotos de combate más logrados en la historia de Star Wars. Como personaje héroe nombrado en lugar de un piloto genérico, Wedge Antilles es altamente valorado por coleccionistas que se enfocan en ases de la Alianza Rebelde y los pilotos de élite que volaron en las batallas más importantes de la Trilogía Original.'
  },
  {
    no: 'sw0040b',
    name: 'Imperial Royal Guard - Black Hands',
    en: 'The Imperial Royal Guard represents the Emperor\'s elite personal bodyguards who protected Palpatine in Return of the Jedi. This LEGO minifigure features the distinctive all-red robes and armor with black hands that creates their menacing, faceless appearance. The figure includes detailed printing showing the armored chest plate beneath the flowing crimson robes and the helmet that conceals their identity. Released in 2007 as part of Death Star and Imperial sets, the black hands variant distinguishes this from other Royal Guard color variations. The combination of blood-red robes and black gloves emphasizes their role as silent, deadly protectors. As the Emperor\'s most trusted guards and symbols of Imperial power, Royal Guards are essential for collectors building Emperor\'s Throne Room scenes and are often acquired in pairs to flank Palpatine\'s seat of power.',
    de: 'Die imperiale Königsgarde repräsentiert die Elite-Leibwächter des Imperators, die Palpatine in Die Rückkehr der Jedi-Ritter schützten. Diese LEGO Minifigur zeigt die charakteristischen ganz roten Roben und Rüstung mit schwarzen Händen, die ihr bedrohliches, gesichtsloses Aussehen erzeugen. Die Figur enthält detaillierte Bedruckung, die die gepanzerte Brustplatte unter den fließenden karmesinroten Roben und den Helm zeigt, der ihre Identität verbirgt. Veröffentlicht im Jahr 2007 als Teil von Todesstern- und imperialen Sets, unterscheidet die schwarze Hände-Variante diese von anderen Königsgarden-Farbvariationen. Die Kombination aus blutroten Roben und schwarzen Handschuhen betont ihre Rolle als stille, tödliche Beschützer. Als die vertrauenswürdigsten Wachen des Imperators und Symbole imperialer Macht sind Königsgarden für Sammler unverzichtbar, die Imperators-Thronsaal-Szenen bauen, und werden oft paarweise erworben, um Palpatines Machtsitz zu flankieren.',
    fr: 'La Garde Royale Impériale représente les gardes du corps personnels d\'élite de l\'Empereur qui protégeaient Palpatine dans Le Retour du Jedi. Cette minifigurine LEGO présente les robes et armure entièrement rouges distinctives avec des mains noires qui créent leur apparence menaçante et sans visage. La figurine comprend une impression détaillée montrant la plaque de poitrine blindée sous les robes cramoisies fluides et le casque qui dissimule leur identité. Sortie en 2007 dans des sets d\'Étoile de la Mort et impériaux, la variante à mains noires distingue celle-ci des autres variations de couleur de Garde Royale. La combinaison de robes rouge sang et de gants noirs souligne leur rôle de protecteurs silencieux et mortels. En tant que gardes les plus fiables de l\'Empereur et symboles du pouvoir Impérial, les Gardes Royaux sont essentiels pour les collectionneurs construisant des scènes de Salle du Trône de l\'Empereur et sont souvent acquis par paires pour flanquer le siège du pouvoir de Palpatine.',
    es: 'La Guardia Real Imperial representa a los guardaespaldas personales de élite del Emperador que protegían a Palpatine en El Retorno del Jedi. Esta minifigura LEGO presenta las distintivas túnicas y armadura completamente rojas con manos negras que crean su apariencia amenazante y sin rostro. La figura incluye impresión detallada mostrando la placa de pecho blindada debajo de las túnicas carmesí fluidas y el casco que oculta su identidad. Lanzada en 2007 como parte de sets de la Estrella de la Muerte e Imperiales, la variante de manos negras distingue esta de otras variaciones de color de Guardia Real. La combinación de túnicas rojo sangre y guantes negros enfatiza su papel como protectores silenciosos y mortales. Como los guardias más confiables del Emperador y símbolos del poder Imperial, las Guardias Reales son esenciales para coleccionistas construyendo escenas de Sala del Trono del Emperador y son a menudo adquiridas en pares para flanquear el asiento del poder de Palpatine.'
  },
  {
    no: 'sw0106',
    name: 'Luke Skywalker (Dagobah, Sand Green Tank Top, Backpack)',
    en: 'Luke Skywalker training on Dagobah represents one of the most important character development moments in The Empire Strikes Back. This LEGO minifigure features the sand green tank top and backpack that Luke wore during his intensive Jedi training with Master Yoda. The figure captures Luke\'s appearance as he carried Yoda through the swamps, performing physical and mental exercises to unlock his Force potential. Released in 2007 as part of Dagobah-themed sets, this variant with tank top and backpack shows Luke at his most vulnerable and determined. The sand green color and backpack accessory are unique to this Dagobah training version. As a pivotal moment in Luke\'s journey from farm boy to Jedi Knight, this training outfit Luke is essential for collectors building Dagobah swamp scenes with Yoda\'s hut and the iconic Force training sequences.',
    de: 'Luke Skywalkers Training auf Dagobah repräsentiert einen der wichtigsten Charakterentwicklungsmomente in Das Imperium schlägt zurück. Diese LEGO Minifigur zeigt das sandgrüne Tank-Top und den Rucksack, die Luke während seines intensiven Jedi-Trainings mit Meister Yoda trug. Die Figur fängt Lukes Aussehen ein, als er Yoda durch die Sümpfe trug und physische und mentale Übungen ausführte, um sein Macht-Potenzial freizusetzen. Veröffentlicht im Jahr 2007 als Teil von Dagobah-thematisierten Sets, zeigt diese Variante mit Tank-Top und Rucksack Luke in seinem verletzlichsten und entschlossensten Zustand. Die sandgrüne Farbe und das Rucksack-Zubehör sind einzigartig für diese Dagobah-Trainingsversion. Als entscheidender Moment in Lukes Reise vom Farmjungen zum Jedi-Ritter ist dieser Trainingsoutfit-Luke für Sammler unverzichtbar, die Dagobah-Sumpfszenen mit Yodas Hütte und den ikonischen Macht-Trainingssequenzen bauen.',
    fr: 'Luke Skywalker s\'entraînant sur Dagobah représente l\'un des moments de développement de personnage les plus importants de L\'Empire contre-attaque. Cette minifigurine LEGO présente le débardeur vert sable et le sac à dos que Luke portait pendant son entraînement Jedi intensif avec Maître Yoda. La figurine capture l\'apparence de Luke alors qu\'il portait Yoda à travers les marais, effectuant des exercices physiques et mentaux pour déverrouiller son potentiel de Force. Sortie en 2007 dans des sets à thème Dagobah, cette variante avec débardeur et sac à dos montre Luke à son plus vulnérable et déterminé. La couleur vert sable et l\'accessoire de sac à dos sont uniques à cette version d\'entraînement de Dagobah. En tant que moment crucial dans le voyage de Luke de garçon de ferme à Chevalier Jedi, ce Luke en tenue d\'entraînement est essentiel pour les collectionneurs construisant des scènes de marais de Dagobah avec la hutte de Yoda et les séquences d\'entraînement à la Force iconiques.',
    es: 'Luke Skywalker entrenando en Dagobah representa uno de los momentos de desarrollo de personaje más importantes en El Imperio Contraataca. Esta minifigura LEGO presenta la camiseta sin mangas verde arena y mochila que Luke usó durante su intensivo entrenamiento Jedi con el Maestro Yoda. La figura captura la apariencia de Luke mientras cargaba a Yoda por los pantanos, realizando ejercicios físicos y mentales para desbloquear su potencial de la Fuerza. Lanzada en 2007 como parte de sets temáticos de Dagobah, esta variante con camiseta sin mangas y mochila muestra a Luke en su momento más vulnerable y decidido. El color verde arena y accesorio de mochila son únicos para esta versión de entrenamiento de Dagobah. Como momento crucial en el viaje de Luke de chico de granja a Caballero Jedi, este Luke con atuendo de entrenamiento es esencial para coleccionistas construyendo escenas de pantano de Dagobah con la cabaña de Yoda y las icónicas secuencias de entrenamiento de la Fuerza.'
  },
  {
    no: 'sw0091',
    name: 'Clone Shock Trooper, Coruscant Guard (Phase 2) - Black Head',
    en: 'The Clone Shock Trooper of the Coruscant Guard represents the elite security forces who protected the Republic capital during the Clone Wars. This LEGO minifigure features the distinctive red-marked Phase 2 armor with black head piece that identifies Coruscant Guard personnel. The figure includes detailed printing showing the crimson markings, advanced armor plating, and the specialized equipment used by these urban combat specialists. Released in 2007 as part of Clone Wars sets, this Shock Trooper captures the appearance of clone units who served under Commander Fox. The red armor markings distinguish Shock Troopers from other clone variants and create an intimidating ceremonial appearance. As the Republic\'s capital guardians who also hunted Jedi during Order 66, Shock Troopers are highly collectible among fans who focus on Clone Wars-era forces and the transition from Republic to Empire.',
    de: 'Der Clone Shock Trooper der Coruscant Guard repräsentiert die Elite-Sicherheitskräfte, die die Hauptstadt der Republik während der Klonkriege schützten. Diese LEGO Minifigur zeigt die charakteristische rot markierte Phase-2-Rüstung mit schwarzem Kopfteil, das Coruscant-Guard-Personal identifiziert. Die Figur enthält detaillierte Bedruckung, die die karmesinroten Markierungen, fortschrittliche Rüstungsplattierung und die spezialisierte Ausrüstung zeigt, die von diesen urbanen Kampfspezialisten verwendet wird. Veröffentlicht im Jahr 2007 als Teil von Klonkriegs-Sets, fängt dieser Shock Trooper das Aussehen von Klon-Einheiten ein, die unter Commander Fox dienten. Die roten Rüstungsmarkierungen unterscheiden Shock Troopers von anderen Klon-Varianten und erzeugen ein einschüchterndes zeremonielles Aussehen. Als Wächter der Hauptstadt der Republik, die auch Jedi während Order 66 jagten, sind Shock Troopers bei Fans sehr sammelwürdig, die sich auf Klonkriegs-Ära-Streitkräfte und den Übergang von der Republik zum Imperium konzentrieren.',
    fr: 'Le Clone Shock Trooper de la Garde de Coruscant représente les forces de sécurité d\'élite qui protégeaient la capitale de la République pendant la Guerre des Clones. Cette minifigurine LEGO présente l\'armure de Phase 2 distinctivement marquée de rouge avec une pièce de tête noire qui identifie le personnel de la Garde de Coruscant. La figurine comprend une impression détaillée montrant les marquages cramoisis, le blindage d\'armure avancé et l\'équipement spécialisé utilisé par ces spécialistes du combat urbain. Sortie en 2007 dans des sets de la Guerre des Clones, ce Shock Trooper capture l\'apparence des unités de clones qui servaient sous le Commandant Fox. Les marquages d\'armure rouges distinguent les Shock Troopers des autres variantes de clones et créent une apparence cérémonielle intimidante. En tant que gardiens de la capitale de la République qui ont également chassé les Jedi pendant l\'Ordre 66, les Shock Troopers sont très collectionnables parmi les fans qui se concentrent sur les forces de l\'ère de la Guerre des Clones et la transition de la République à l\'Empire.',
    es: 'El Clone Shock Trooper de la Guardia de Coruscant representa las fuerzas de seguridad de élite que protegían la capital de la República durante las Guerras Clon. Esta minifigura LEGO presenta la distintiva armadura de Fase 2 marcada en rojo con pieza de cabeza negra que identifica al personal de la Guardia de Coruscant. La figura incluye impresión detallada mostrando las marcas carmesí, blindaje de armadura avanzado y el equipo especializado usado por estos especialistas de combate urbano. Lanzada en 2007 como parte de sets de las Guerras Clon, este Shock Trooper captura la apariencia de unidades clon que sirvieron bajo el Comandante Fox. Las marcas de armadura roja distinguen a los Shock Troopers de otras variantes clon y crean una apariencia ceremonial intimidante. Como guardianes de la capital de la República que también cazaron Jedi durante la Orden 66, los Shock Troopers son altamente coleccionables entre fans que se enfocan en fuerzas de la era de las Guerras Clon y la transición de República a Imperio.'
  },
  {
    no: 'sw0092',
    name: 'Super Battle Droid - Pearl Dark Gray, Wide Head',
    en: 'The Super Battle Droid represents the upgraded combat droids deployed by the Separatists during the Clone Wars. This LEGO minifigure features the pearl dark gray color scheme and distinctive wide head design that made these droids far more formidable than standard battle droids. The figure includes detailed printing showing armor plating, integrated wrist blasters, and the bulky design that gave Super Battle Droids superior firepower and durability. Released in 2007 as part of various Clone Wars sets, this variant with pearl dark gray coloring and wide head represents an updated design. The metallic sheen and broader head configuration distinguish this from earlier Super Battle Droid versions. As the backbone of Separatist ground forces and a significant threat to clone troopers, Super Battle Droids are essential for army builders creating large-scale Clone Wars battle scenes.',
    de: 'Der Super Battle Droid repräsentiert die verbesserten Kampfdroiden, die von den Separatisten während der Klonkriege eingesetzt wurden. Diese LEGO Minifigur zeigt das perlendunkelgraue Farbschema und das charakteristische breite Kopfdesign, das diese Droiden weitaus beeindruckender als Standard-Kampfdroiden machte. Die Figur enthält detaillierte Bedruckung, die Rüstungsplattierung, integrierte Handgelenk-Blaster und das sperrige Design zeigt, das Super Battle Droids überlegene Feuerkraft und Haltbarkeit verlieh. Veröffentlicht im Jahr 2007 als Teil verschiedener Klonkriegs-Sets, repräsentiert diese Variante mit perlendunkelgrauer Färbung und breitem Kopf ein aktualisiertes Design. Der metallische Glanz und die breitere Kopfkonfiguration unterscheiden diese von früheren Super-Battle-Droid-Versionen. Als Rückgrat der separatistischen Bodentruppen und eine bedeutende Bedrohung für Klon-Trooper sind Super Battle Droids für Armeeerbauer unverzichtbar, die groß angelegte Klonkriegs-Kampfszenen erstellen.',
    fr: 'Le Super Battle Droid représente les droïdes de combat améliorés déployés par les Séparatistes pendant la Guerre des Clones. Cette minifigurine LEGO présente le schéma de couleur gris foncé nacré et la conception de tête large distinctive qui rendait ces droïdes beaucoup plus formidables que les battle droids standard. La figurine comprend une impression détaillée montrant le blindage, les blasters de poignet intégrés et la conception volumineuse qui donnait aux Super Battle Droids une puissance de feu et une durabilité supérieures. Sortie en 2007 dans divers sets de la Guerre des Clones, cette variante avec coloration gris foncé nacré et tête large représente une conception mise à jour. Le lustre métallique et la configuration de tête plus large distinguent celle-ci des versions antérieures de Super Battle Droid. En tant qu\'épine dorsale des forces terrestres Séparatistes et menace significative pour les clone troopers, les Super Battle Droids sont essentiels pour les constructeurs d\'armée créant des scènes de bataille de la Guerre des Clones à grande échelle.',
    es: 'El Super Battle Droid representa los droides de combate mejorados desplegados por los Separatistas durante las Guerras Clon. Esta minifigura LEGO presenta el esquema de color gris oscuro perlado y distintivo diseño de cabeza ancha que hizo a estos droides mucho más formidables que los droides de batalla estándar. La figura incluye impresión detallada mostrando blindaje, blasters de muñeca integrados y el diseño voluminoso que dio a los Super Battle Droids potencia de fuego y durabilidad superior. Lanzada en 2007 como parte de varios sets de las Guerras Clon, esta variante con coloración gris oscuro perlado y cabeza ancha representa un diseño actualizado. El brillo metálico y configuración de cabeza más ancha distinguen esta de versiones anteriores de Super Battle Droid. Como columna vertebral de fuerzas terrestres Separatistas y amenaza significativa para clone troopers, los Super Battle Droids son esenciales para constructores de ejército creando escenas de batalla de las Guerras Clon a gran escala.'
  },
  {
    no: 'sw0093',
    name: 'Imperial AT-ST Pilot / Driver (Plain Helmet)',
    en: 'The Imperial AT-ST Pilot represents the specialized drivers who operated the All Terrain Scout Transport walkers. This LEGO minifigure features the plain helmet design without detailed printing, gray flight suit, and the distinctive armor that identifies AT-ST crew members. The figure captures the appearance of the pilots who manned these agile two-legged walkers during the Battle of Endor. Released in 2007 as part of AT-ST sets, this variant with plain helmet represents an earlier, simpler production style. The gray uniform and minimalist helmet distinguish AT-ST pilots from AT-AT drivers and standard Imperial officers. As the operators of one of the Empire\'s most versatile ground vehicles, AT-ST pilots are essential for collectors building Imperial ground forces and forest battle scenes from Return of the Jedi where these walkers were famously defeated by Ewoks.',
    de: 'Der imperiale AT-ST-Pilot repräsentiert die spezialisierten Fahrer, die die All-Terrain-Scout-Transport-Läufer betrieben. Diese LEGO Minifigur zeigt das schlichte Helm-Design ohne detaillierte Bedruckung, grauen Fluganzug und die charakteristische Rüstung, die AT-ST-Besatzungsmitglieder identifiziert. Die Figur fängt das Aussehen der Piloten ein, die diese agilen zweibeinigen Läufer während der Schlacht von Endor bemannten. Veröffentlicht im Jahr 2007 als Teil von AT-ST-Sets, repräsentiert diese Variante mit schlichtem Helm einen früheren, einfacheren Produktionsstil. Die graue Uniform und der minimalistische Helm unterscheiden AT-ST-Piloten von AT-AT-Fahrern und Standard-Imperialen-Offizieren. Als Operatoren eines der vielseitigsten Bodenfahrzeuge des Imperiums sind AT-ST-Piloten für Sammler unverzichtbar, die imperiale Bodentruppen und Waldschlacht-Szenen aus Die Rückkehr der Jedi-Ritter bauen, wo diese Läufer berühmt von Ewoks besiegt wurden.',
    fr: 'Le Pilote d\'AT-ST Impérial représente les conducteurs spécialisés qui opéraient les marcheurs All Terrain Scout Transport. Cette minifigurine LEGO présente la conception de casque simple sans impression détaillée, la combinaison de vol grise et l\'armure distinctive qui identifie les membres d\'équipage d\'AT-ST. La figurine capture l\'apparence des pilotes qui pilotaient ces marcheurs agiles à deux pattes pendant la Bataille d\'Endor. Sortie en 2007 dans des sets d\'AT-ST, cette variante avec casque simple représente un style de production antérieur plus simple. L\'uniforme gris et le casque minimaliste distinguent les pilotes d\'AT-ST des conducteurs d\'AT-AT et des officiers impériaux standard. En tant qu\'opérateurs de l\'un des véhicules terrestres les plus polyvalents de l\'Empire, les pilotes d\'AT-ST sont essentiels pour les collectionneurs construisant des forces terrestres impériales et des scènes de bataille forestière du Retour du Jedi où ces marcheurs ont été célèbrement vaincus par les Ewoks.',
    es: 'El Piloto de AT-ST Imperial representa a los conductores especializados que operaban los caminantes de Transporte Explorador Todo Terreno. Esta minifigura LEGO presenta el diseño de casco simple sin impresión detallada, traje de vuelo gris y la distintiva armadura que identifica a miembros de tripulación de AT-ST. La figura captura la apariencia de los pilotos que manejaban estos ágiles caminantes de dos patas durante la Batalla de Endor. Lanzada en 2007 como parte de sets de AT-ST, esta variante con casco simple representa un estilo de producción más temprano y simple. El uniforme gris y casco minimalista distinguen a pilotos de AT-ST de conductores de AT-AT y oficiales Imperiales estándar. Como operadores de uno de los vehículos terrestres más versátiles del Imperio, los pilotos de AT-ST son esenciales para coleccionistas construyendo fuerzas terrestres Imperiales y escenas de batalla forestal de El Retorno del Jedi donde estos caminantes fueron famosamente derrotados por Ewoks.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 020 (sw0028a-sw0093) - 10 minifigs...\n');

  let successCount = 0;
  let skipCount = 0;

  for (const m of batch) {
    try {
      await prisma.minifigCatalog.update({
        where: { minifigure_no: m.no },
        data: {
          description_en: m.en,
          description_de: m.de,
          description_fr: m.fr,
          description_es: m.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        }
      });
      console.log(`  ✅ ${m.no}: ${m.name}`);
      successCount++;
    } catch (error: any) {
      console.log(`  ⚠️  ${m.no}: NOT IN DATABASE (skipped)`);
      skipCount++;
    }
  }

  console.log(`\n✨ Batch 020 complete: ${batch.length} minifigs (${successCount * 4} descriptions)\n`);

  await prisma.$disconnect();
}

saveBatch().catch(console.error);
