import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0139',
    name: 'Bib Fortuna',
    en: "Bib Fortuna serves as Jabba the Hutt's majordomo and right-hand Twi'lek in Return of the Jedi. This LEGO minifigure features his distinctive pale pink skin, long head-tails (lekku), and dark robes that mark his position in Jabba's criminal empire. First released in 2003 in the Jabba's Palace set, Bib Fortuna has become a sought-after character for collectors building complete Tatooine palace displays. His menacing presence and key role in the Jabba's court storyline make this minifigure essential for Original Trilogy fans. Versions with detailed facial printing and accurate costume elements command premium prices in the collector market.",
    de: "Bib Fortuna dient als Majordomus und rechte Hand des Twi'lek von Jabba dem Hutten in Die Rückkehr der Jedi-Ritter. Diese LEGO-Minifigur zeigt seine charakteristische blasspinke Haut, lange Kopftentakel (Lekku) und dunkle Roben, die seine Position in Jabbas kriminellem Imperium kennzeichnen. Erstmals 2003 im Jabba's Palace Set veröffentlicht, ist Bib Fortuna zu einer begehrten Figur für Sammler geworden, die vollständige Tatooine-Palast-Displays aufbauen. Seine bedrohliche Präsenz und zentrale Rolle in der Jabba-Hof-Handlung machen diese Minifigur für Original-Trilogie-Fans unverzichtbar. Versionen mit detailliertem Gesichtsdruck und akkuraten Kostümelementen erzielen Premiumpreise auf dem Sammlermarkt.",
    fr: "Bib Fortuna est le majordome et bras droit Twi'lek de Jabba le Hutt dans Le Retour du Jedi. Cette minifigurine LEGO présente sa peau rose pâle distinctive, ses longs tentacules crâniens (lekku) et ses robes sombres qui marquent sa position dans l'empire criminel de Jabba. Sortie pour la première fois en 2003 dans le set Le Palais de Jabba, Bib Fortuna est devenue une figurine recherchée par les collectionneurs construisant des décors complets du palais de Tatooine. Sa présence menaçante et son rôle clé dans la cour de Jabba rendent cette minifigurine essentielle pour les fans de la trilogie originale. Les versions avec impression faciale détaillée et éléments de costume précis atteignent des prix premium sur le marché des collectionneurs.",
    es: "Bib Fortuna sirve como mayordomo y mano derecha Twi'lek de Jabba el Hutt en El Retorno del Jedi. Esta minifigura LEGO presenta su distintiva piel rosa pálido, largos tentáculos cefálicos (lekku) y túnicas oscuras que marcan su posición en el imperio criminal de Jabba. Lanzada por primera vez en 2003 en el set Palacio de Jabba, Bib Fortuna se ha convertido en una figura codiciada para coleccionistas que construyen exhibiciones completas del palacio de Tatooine. Su presencia amenazante y papel clave en la corte de Jabba hacen que esta minifigura sea esencial para los fans de la trilogía original. Las versiones con impresión facial detallada y elementos de vestuario precisos alcanzan precios premium en el mercado de coleccionistas."
  },
  {
    no: 'sw0140',
    name: 'Gamorrean Guard',
    en: "The Gamorrean Guard represents one of Jabba the Hutt's brutish pig-like alien enforcers who patrol his palace on Tatooine. This LEGO minifigure captures the creature's distinctive green skin, tusked snout, and crude armor with vibrant molded details. Released in 2003 as part of the Jabba's Palace set, the Gamorrean Guard adds authentic muscle to any Return of the Jedi collection. The figure typically includes a vibro-ax weapon and horned helmet, matching the guards seen throughout Jabba's throne room. Collectors prize this minifigure for its unique species representation and essential role in recreating the palace's intimidating atmosphere. Multiple Gamorrean Guards are often desired to properly staff a complete palace display.",
    de: "Der Gamorreaner-Wache repräsentiert einen von Jabba dem Huttens brutalen schweineartigen außerirdischen Vollstreckern, die seinen Palast auf Tatooine patrouillieren. Diese LEGO-Minifigur fängt die charakteristische grüne Haut, die mit Hauern versehene Schnauze und die grobe Rüstung der Kreatur mit lebhaften geformten Details ein. 2003 als Teil des Jabba's Palace Sets veröffentlicht, fügt der Gamorreaner-Wache jeder Die Rückkehr der Jedi-Ritter Sammlung authentische Kraft hinzu. Die Figur enthält typischerweise eine Vibro-Axt-Waffe und einen gehörnten Helm, passend zu den Wachen im Thronsaal von Jabba. Sammler schätzen diese Minifigur für ihre einzigartige Speziesdarstellung und wesentliche Rolle bei der Nachbildung der einschüchternden Atmosphäre des Palastes. Mehrere Gamorreaner-Wachen werden oft gewünscht, um eine vollständige Palast-Ausstellung angemessen zu bestücken.",
    fr: "Le Garde Gamorréen représente l'un des exécuteurs extraterrestres brutaux ressemblant à des cochons de Jabba le Hutt qui patrouillent son palais sur Tatooine. Cette minifigurine LEGO capture la peau verte distinctive de la créature, son museau à défenses et son armure grossière avec des détails moulés vibrants. Sortie en 2003 dans le set Le Palais de Jabba, le Garde Gamorréen ajoute un muscle authentique à toute collection Le Retour du Jedi. La figurine comprend généralement une arme vibro-hache et un casque à cornes, correspondant aux gardes vus dans la salle du trône de Jabba. Les collectionneurs apprécient cette minifigurine pour sa représentation d'espèce unique et son rôle essentiel dans la recréation de l'atmosphère intimidante du palais. Plusieurs Gardes Gamorréens sont souvent désirés pour équiper correctement une exposition complète du palais.",
    es: "El Guardia Gamorreano representa a uno de los brutales ejecutores alienígenas parecidos a cerdos de Jabba el Hutt que patrullan su palacio en Tatooine. Esta minifigura LEGO captura la piel verde distintiva de la criatura, su hocico con colmillos y armadura tosca con detalles moldeados vibrantes. Lanzada en 2003 como parte del set Palacio de Jabba, el Guardia Gamorreano añade músculo auténtico a cualquier colección de El Retorno del Jedi. La figura típicamente incluye un arma vibro-hacha y casco con cuernos, coincidiendo con los guardias vistos en la sala del trono de Jabba. Los coleccionistas valoran esta minifigura por su representación única de especie y papel esencial en recrear la atmósfera intimidante del palacio. Múltiples Guardias Gamorreanos son frecuentemente deseados para equipar apropiadamente una exhibición completa del palacio."
  },
  {
    no: 'sw0141',
    name: 'Max Rebo',
    en: "Max Rebo is the blue-skinned Ortolan keyboard player who leads the Max Rebo Band in Jabba's Palace throne room. This LEGO minifigure faithfully recreates his distinctive elephant-like trunk, short stature, and blue coloring that made him memorable in Return of the Jedi. Released in 2006 in the Jabba's Prize set, Max Rebo represents one of the more unusual and whimsical characters in the Star Wars cantina scene. The figure's unique body mold and specialized printing make it a favorite among collectors who appreciate the quirky musical element of Jabba's court. As a band leader who provided entertainment for the galaxy's most notorious crime lord, Max Rebo adds personality and authenticity to any palace display.",
    de: "Max Rebo ist der blau-häutige Ortolan-Keyboardspieler, der die Max Rebo Band im Thronsaal von Jabba's Palast anführt. Diese LEGO-Minifigur reproduziert getreu seinen charakteristischen elefantenartigen Rüssel, kleine Statur und blaue Färbung, die ihn in Die Rückkehr der Jedi-Ritter unvergesslich machten. 2006 im Jabba's Prize Set veröffentlicht, repräsentiert Max Rebo einen der ungewöhnlicheren und skurrileren Charaktere in der Star Wars Cantina-Szene. Die einzigartige Körperform und spezialisierte Bedruckung der Figur machen sie zu einem Favoriten unter Sammlern, die das schrullige musikalische Element von Jabbas Hof schätzen. Als Bandleader, der Unterhaltung für den berüchtigtsten Verbrecherlord der Galaxie bot, fügt Max Rebo Persönlichkeit und Authentizität zu jeder Palast-Ausstellung hinzu.",
    fr: "Max Rebo est le joueur de clavier Ortolan à peau bleue qui dirige le Max Rebo Band dans la salle du trône du Palais de Jabba. Cette minifigurine LEGO recrée fidèlement sa trompe distinctive ressemblant à un éléphant, sa petite taille et sa coloration bleue qui l'ont rendu mémorable dans Le Retour du Jedi. Sortie en 2006 dans le set Le Prix de Jabba, Max Rebo représente l'un des personnages les plus inhabituels et fantaisistes de la scène de cantina Star Wars. Le moule de corps unique et l'impression spécialisée de la figurine en font un favori parmi les collectionneurs qui apprécient l'élément musical loufoque de la cour de Jabba. En tant que chef d'orchestre qui fournissait du divertissement au seigneur du crime le plus notoire de la galaxie, Max Rebo ajoute personnalité et authenticité à toute exposition du palais.",
    es: "Max Rebo es el tecladista Ortolan de piel azul que lidera la Banda de Max Rebo en la sala del trono del Palacio de Jabba. Esta minifigura LEGO recrea fielmente su distintiva trompa similar a un elefante, baja estatura y coloración azul que lo hicieron memorable en El Retorno del Jedi. Lanzada en 2006 en el set El Premio de Jabba, Max Rebo representa a uno de los personajes más inusuales y caprichosos en la escena de cantina de Star Wars. El molde de cuerpo único y la impresión especializada de la figura la convierten en favorita entre coleccionistas que aprecian el elemento musical peculiar de la corte de Jabba. Como líder de banda que proporcionaba entretenimiento al señor del crimen más notorio de la galaxia, Max Rebo añade personalidad y autenticidad a cualquier exhibición del palacio."
  },
  {
    no: 'sw0142',
    name: 'Droopy McCool',
    en: "Droopy McCool is the Kitonak wind instrument player in the Max Rebo Band, recognizable by his pale smooth skin and drooping facial features in Return of the Jedi. This LEGO minifigure captures his unique alien physiology with specialized printing and molding that reflects his melancholy appearance. Released in 2006 as part of Jabba's Palace-related sets, Droopy McCool completes the musical trio that entertained in Jabba's throne room. The figure typically features a simple tan body with distinctive head sculpting that sets him apart from standard minifigures. Collectors appreciate Droopy McCool for his oddball character design and role in one of Star Wars' most memorable location scenes. As part of the complete band ensemble, this minifigure adds depth and completeness to Jabba's Palace recreations.",
    de: "Droopy McCool ist der Kitonak-Blasinstrumentenspieler in der Max Rebo Band, erkennbar an seiner blassen glatten Haut und hängenden Gesichtszügen in Die Rückkehr der Jedi-Ritter. Diese LEGO-Minifigur fängt seine einzigartige außerirdische Physiologie mit spezialisierter Bedruckung und Formgebung ein, die sein melancholisches Aussehen widerspiegelt. 2006 als Teil von Jabba's Palace-bezogenen Sets veröffentlicht, vervollständigt Droopy McCool das musikalische Trio, das in Jabbas Thronsaal unterhielt. Die Figur verfügt typischerweise über einen einfachen beigefarbenen Körper mit charakteristischer Kopfformung, die sie von Standard-Minifiguren abhebt. Sammler schätzen Droopy McCool für sein skurriles Charakterdesign und seine Rolle in einer der denkwürdigsten Ortsszenen von Star Wars. Als Teil des vollständigen Bandensembles fügt diese Minifigur Tiefe und Vollständigkeit zu Jabba's Palace Nachbildungen hinzu.",
    fr: "Droopy McCool est le joueur d'instrument à vent Kitonak dans le Max Rebo Band, reconnaissable à sa peau lisse pâle et ses traits faciaux tombants dans Le Retour du Jedi. Cette minifigurine LEGO capture sa physiologie extraterrestre unique avec une impression et un moulage spécialisés qui reflètent son apparence mélancolique. Sortie en 2006 dans des sets liés au Palais de Jabba, Droopy McCool complète le trio musical qui divertissait dans la salle du trône de Jabba. La figurine présente généralement un corps beige simple avec une sculpture de tête distinctive qui la distingue des minifigurines standard. Les collectionneurs apprécient Droopy McCool pour son design de personnage excentrique et son rôle dans l'une des scènes de lieu les plus mémorables de Star Wars. Faisant partie de l'ensemble complet du groupe, cette minifigurine ajoute profondeur et complétude aux recréations du Palais de Jabba.",
    es: "Droopy McCool es el instrumentista de viento Kitonak en la Banda de Max Rebo, reconocible por su piel lisa pálida y rasgos faciales caídos en El Retorno del Jedi. Esta minifigura LEGO captura su fisiología alienígena única con impresión y moldeado especializado que refleja su apariencia melancólica. Lanzada en 2006 como parte de sets relacionados con el Palacio de Jabba, Droopy McCool completa el trío musical que entretenía en la sala del trono de Jabba. La figura típicamente presenta un cuerpo beige simple con escultura de cabeza distintiva que la distingue de las minifiguras estándar. Los coleccionistas aprecian a Droopy McCool por su diseño de personaje peculiar y papel en una de las escenas de ubicación más memorables de Star Wars. Como parte del ensamble completo de la banda, esta minifigura añade profundidad y completitud a las recreaciones del Palacio de Jabba."
  },
  {
    no: 'sw0143',
    name: 'Sy Snootles',
    en: "Sy Snootles is the Pa'lowick lead vocalist of the Max Rebo Band, known for her distinctive long snout and vibrant performance style in Jabba's Palace. This LEGO minifigure recreates her unique alien appearance with specialized head molding and colorful printing that captures her exotic look from Return of the Jedi. Released in 2006, Sy Snootles represents the final member of the iconic musical trio that performed for Jabba the Hutt. The figure features detailed printing showing her elaborate costume and distinctive facial features that made her a memorable background character. Collectors value Sy Snootles for completing the Max Rebo Band ensemble and for her representation of one of the Original Trilogy's more visually interesting aliens. Her presence adds authenticity and musical atmosphere to any Jabba's Palace display.",
    de: "Sy Snootles ist die Pa'lowick-Leadsängerin der Max Rebo Band, bekannt für ihre charakteristische lange Schnauze und lebendigen Auftrittstil in Jabba's Palast. Diese LEGO-Minifigur reproduziert ihr einzigartiges außerirdisches Aussehen mit spezialisierter Kopfformung und farbenfroher Bedruckung, die ihren exotischen Look aus Die Rückkehr der Jedi-Ritter einfängt. 2006 veröffentlicht, repräsentiert Sy Snootles das letzte Mitglied des ikonischen musikalischen Trios, das für Jabba den Hutten auftrat. Die Figur zeigt detaillierte Bedruckung mit ihrem elaborierten Kostüm und charakteristischen Gesichtszügen, die sie zu einem unvergesslichen Hintergrundcharakter machten. Sammler schätzen Sy Snootles für die Vervollständigung des Max Rebo Band Ensembles und für ihre Darstellung einer der visuell interessanteren Außerirdischen der Original-Trilogie. Ihre Präsenz fügt Authentizität und musikalische Atmosphäre zu jeder Jabba's Palace Ausstellung hinzu.",
    fr: "Sy Snootles est la chanteuse principale Pa'lowick du Max Rebo Band, connue pour son museau long distinctif et son style de performance vibrant dans le Palais de Jabba. Cette minifigurine LEGO recrée son apparence extraterrestre unique avec un moulage de tête spécialisé et une impression colorée qui capture son look exotique du Retour du Jedi. Sortie en 2006, Sy Snootles représente le dernier membre du trio musical iconique qui se produisait pour Jabba le Hutt. La figurine présente une impression détaillée montrant son costume élaboré et ses traits faciaux distinctifs qui en ont fait un personnage d'arrière-plan mémorable. Les collectionneurs apprécient Sy Snootles pour compléter l'ensemble du Max Rebo Band et pour sa représentation de l'un des extraterrestres les plus visuellement intéressants de la trilogie originale. Sa présence ajoute authenticité et atmosphère musicale à toute exposition du Palais de Jabba.",
    es: "Sy Snootles es la vocalista principal Pa'lowick de la Banda de Max Rebo, conocida por su distintivo hocico largo y estilo de actuación vibrante en el Palacio de Jabba. Esta minifigura LEGO recrea su apariencia alienígena única con moldeado de cabeza especializado e impresión colorida que captura su aspecto exótico de El Retorno del Jedi. Lanzada en 2006, Sy Snootles representa el miembro final del icónico trío musical que actuaba para Jabba el Hutt. La figura presenta impresión detallada mostrando su vestuario elaborado y rasgos faciales distintivos que la hicieron un personaje de fondo memorable. Los coleccionistas valoran a Sy Snootles por completar el ensamble de la Banda de Max Rebo y por su representación de uno de los alienígenas visualmente más interesantes de la trilogía original. Su presencia añade autenticidad y atmósfera musical a cualquier exhibición del Palacio de Jabba."
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 31-35 (sw0139-sw0143)...\n');

  for (const m of batch) {
    await prisma.minifigCatalog.upsert({
      where: { minifigure_no: m.no },
      update: {
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      },
      create: {
        minifigure_no: m.no,
        name: m.name,
        category_id: 1,
        category_name: 'Star Wars',
        search_name: m.name.toLowerCase(),
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`  ✅ ${m.no}: ${m.name}`);
  }

  console.log(`\n✨ Batch 31-35 complete: 5 minifigs (20 descriptions)`);
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
