import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch044 = [
  {
    no: 'sw0364',
    name: 'Clone Pilot',
    en: 'Clone Pilots served as the skilled aviators of the Republic fleet during the Clone Wars, operating V-19 Torrents, ARC-170 starfighters, and Y-wing bombers in critical space battles. This minifigure features distinctive yellow-marked armor with specialized flight gear, including a unique printed helmet design that distinguishes pilots from standard infantry clones. Released in 2009 as part of set 7674 (V-19 Torrent), this figure represents the Republic\'s elite aerial forces who flew dangerous missions across the galaxy. The yellow markings and specialized equipment make this Clone Pilot a sought-after variant for collectors building Republic military displays, and its appearance in only a few sets between 2009-2011 has made it increasingly valuable in the secondary market.',
    de: 'Klonpiloten dienten während der Klonkriege als die geschickten Flieger der republikanischen Flotte und steuerten V-19 Torrents, ARC-170-Sternenjäger und Y-Flügel-Bomber in kritischen Weltraumschlachten. Diese Minifigur zeigt eine markante gelb markierte Rüstung mit spezialisierter Flugausrüstung, einschließlich eines einzigartigen bedruckten Helmdesigns, das Piloten von Standard-Infanterieklonen unterscheidet. 2009 als Teil von Set 7674 (V-19 Torrent) veröffentlicht, repräsentiert diese Figur die Elite-Luftstreitkräfte der Republik, die gefährliche Missionen durch die gesamte Galaxis flogen. Die gelben Markierungen und die spezialisierte Ausrüstung machen diesen Klonpiloten zu einer begehrten Variante für Sammler, die republikanische Militärdisplays aufbauen, und sein Erscheinen in nur wenigen Sets zwischen 2009 und 2011 hat ihn auf dem Sekundärmarkt zunehmend wertvoll gemacht.',
    fr: 'Les Pilotes Clones servaient de pilotes qualifiés de la flotte de la République pendant la Guerre des Clones, opérant des V-19 Torrent, des chasseurs stellaires ARC-170 et des bombardiers Y-wing dans des batailles spatiales critiques. Cette minifigurine présente une armure distinctive marquée de jaune avec un équipement de vol spécialisé, y compris un design de casque imprimé unique qui distingue les pilotes des clones d\'infanterie standard. Sortie en 2009 dans le cadre du set 7674 (V-19 Torrent), cette figurine représente les forces aériennes d\'élite de la République qui ont effectué des missions dangereuses à travers la galaxie. Les marques jaunes et l\'équipement spécialisé font de ce Pilote Clone une variante recherchée pour les collectionneurs construisant des présentations militaires de la République, et son apparition dans seulement quelques sets entre 2009 et 2011 l\'a rendu de plus en plus précieux sur le marché secondaire.',
    es: 'Los Pilotos Clon sirvieron como los hábiles aviadores de la flota de la República durante las Guerras Clon, operando V-19 Torrents, cazas estelares ARC-170 y bombarderos Ala-Y en batallas espaciales críticas. Esta minifigura presenta una distintiva armadura marcada en amarillo con equipo de vuelo especializado, incluyendo un diseño de casco impreso único que distingue a los pilotos de los clones de infantería estándar. Lanzada en 2009 como parte del set 7674 (V-19 Torrent), esta figura representa las fuerzas aéreas de élite de la República que volaron misiones peligrosas a través de la galaxia. Las marcas amarillas y el equipo especializado hacen de este Piloto Clon una variante codiciada para coleccionistas que construyen exhibiciones militares de la República, y su aparición en solo unos pocos sets entre 2009 y 2011 lo ha hecho cada vez más valioso en el mercado secundario.'
  },
  {
    no: 'sw0365',
    name: 'Han Solo (Hoth Outfit)',
    en: 'Han Solo in his iconic Hoth outfit appears as the smuggler-turned-hero braves the freezing temperatures of the ice planet Hoth in The Empire Strikes Back. This minifigure captures Han\'s cold-weather gear with detailed printing showing his distinctive blue parka with brown accents, fur-lined hood, and utility belt from the Battle of Hoth sequence. First released in 2009 as part of the classic set 7666 (Hoth Rebel Base), this figure represents one of Han\'s most memorable costume changes and his leadership during the Rebel Alliance\'s desperate defense. The Hoth Han variant remains a fan favorite for collectors recreating the opening scenes of Episode V, and its inclusion in several premium sets has made it a staple of any serious Star Wars LEGO collection focused on the original trilogy.',
    de: 'Han Solo in seinem ikonischen Hoth-Outfit erscheint als der zum Helden gewordene Schmuggler, der die eisigen Temperaturen des Eisplaneten Hoth in Das Imperium schlägt zurück trotzt. Diese Minifigur zeigt Hans Kaltwetterausrüstung mit detailliertem Druck, der seine markante blaue Parka mit braunen Akzenten, pelzgefütterte Kapuze und Gürtel aus der Schlacht von Hoth-Sequenz darstellt. Erstmals 2009 als Teil des klassischen Sets 7666 (Hoth-Rebellenbasis) veröffentlicht, repräsentiert diese Figur einen von Hans unvergesslichsten Kostümwechseln und seine Führung während der verzweifelten Verteidigung der Rebellenallianz. Die Hoth-Han-Variante bleibt ein Favorit unter Sammlern, die die Eröffnungsszenen von Episode V nachstellen, und ihre Aufnahme in mehrere Premium-Sets hat sie zu einem festen Bestandteil jeder seriösen Star Wars LEGO-Sammlung mit Fokus auf die ursprüngliche Trilogie gemacht.',
    fr: 'Han Solo dans sa tenue iconique de Hoth apparaît comme le contrebandier devenu héros bravant les températures glaciales de la planète de glace Hoth dans L\'Empire contre-attaque. Cette minifigurine capture l\'équipement par temps froid de Han avec des impressions détaillées montrant sa parka bleue distinctive avec des accents marron, une capuche doublée de fourrure et une ceinture utilitaire de la séquence de la Bataille de Hoth. Sortie pour la première fois en 2009 dans le cadre du set classique 7666 (Base Rebelle de Hoth), cette figurine représente l\'un des changements de costume les plus mémorables de Han et son leadership pendant la défense désespérée de l\'Alliance Rebelle. La variante Han de Hoth reste une favorite des collectionneurs recréant les scènes d\'ouverture de l\'Épisode V, et son inclusion dans plusieurs sets premium en a fait un incontournable de toute collection LEGO Star Wars sérieuse axée sur la trilogie originale.',
    es: 'Han Solo en su icónico atuendo de Hoth aparece como el contrabandista convertido en héroe desafiando las temperaturas heladas del planeta de hielo Hoth en El Imperio Contraataca. Esta minifigura captura el equipo para clima frío de Han con impresiones detalladas que muestran su distintiva parka azul con acentos marrones, capucha forrada de piel y cinturón utilitario de la secuencia de la Batalla de Hoth. Lanzada por primera vez en 2009 como parte del set clásico 7666 (Base Rebelde de Hoth), esta figura representa uno de los cambios de vestuario más memorables de Han y su liderazgo durante la defensa desesperada de la Alianza Rebelde. La variante de Han de Hoth sigue siendo una favorita de los coleccionistas que recrean las escenas iniciales del Episodio V, y su inclusión en varios sets premium la ha convertido en un elemento básico de cualquier colección seria de LEGO Star Wars centrada en la trilogía original.'
  },
  {
    no: 'sw0366',
    name: 'Snowtrooper (Hoth Battle Pack)',
    en: 'Snowtroopers served as the Empire\'s specialized cold assault stormtroopers, specifically trained and equipped for combat in arctic environments like the ice planet Hoth. This minifigure variant from 2009\'s Battle Pack features the distinctive white armor with insulated fabric oversuit, face-mask respirator, and unique helmet design optimized for sub-zero operations during the assault on Echo Base. Released in set 8083 (Rebel Trooper Battle Pack), this Snowtrooper became one of the most accessible Imperial cold-weather troopers for army builders. The simplified yet accurate design and its availability in an affordable battle pack made this version particularly popular for collectors recreating the Battle of Hoth, and multiple copies are essential for building proper Imperial assault formations from The Empire Strikes Back.',
    de: 'Schneetruppen dienten als die spezialisierten Kälteangriffs-Sturmtruppen des Imperiums, speziell ausgebildet und ausgerüstet für den Kampf in arktischen Umgebungen wie dem Eisplaneten Hoth. Diese Minifigur-Variante aus dem Battle Pack von 2009 zeigt die markante weiße Rüstung mit isoliertem Stoffüberzug, Gesichtsmaske mit Atemgerät und einzigartigem Helmdesign, optimiert für Operationen unter null Grad während des Angriffs auf Echo-Basis. Veröffentlicht in Set 8083 (Rebellentruppen Battle Pack), wurde dieser Schneetruppler zu einem der zugänglichsten imperialen Kältewettertruppen für Armeebauer. Das vereinfachte, aber präzise Design und seine Verfügbarkeit in einem erschwinglichen Battle Pack machten diese Version besonders beliebt bei Sammlern, die die Schlacht von Hoth nachstellen, und mehrere Exemplare sind unerlässlich für den Aufbau angemessener imperialer Angriffsformationen aus Das Imperium schlägt zurück.',
    fr: 'Les Snowtroopers servaient de stormtroopers d\'assaut spécialisés pour le froid de l\'Empire, spécifiquement entraînés et équipés pour le combat dans des environnements arctiques comme la planète de glace Hoth. Cette variante de minifigurine du Battle Pack de 2009 présente l\'armure blanche distinctive avec une combinaison en tissu isolant, un masque respiratoire facial et un design de casque unique optimisé pour les opérations sous zéro lors de l\'assaut sur la Base Echo. Sortie dans le set 8083 (Battle Pack Soldat Rebelle), ce Snowtrooper est devenu l\'un des soldats impériaux par temps froid les plus accessibles pour les constructeurs d\'armées. Le design simplifié mais précis et sa disponibilité dans un battle pack abordable ont rendu cette version particulièrement populaire pour les collectionneurs recréant la Bataille de Hoth, et plusieurs exemplaires sont essentiels pour construire des formations d\'assaut impériales appropriées de L\'Empire contre-attaque.',
    es: 'Los Snowtroopers sirvieron como los stormtroopers de asalto especializado en frío del Imperio, específicamente entrenados y equipados para combate en ambientes árticos como el planeta de hielo Hoth. Esta variante de minifigura del Battle Pack de 2009 presenta la distintiva armadura blanca con traje exterior de tela aislante, respirador de máscara facial y diseño de casco único optimizado para operaciones bajo cero durante el asalto a la Base Eco. Lanzado en el set 8083 (Battle Pack Soldado Rebelde), este Snowtrooper se convirtió en uno de los soldados imperiales para clima frío más accesibles para los constructores de ejércitos. El diseño simplificado pero preciso y su disponibilidad en un battle pack asequible hicieron esta versión particularmente popular para coleccionistas recreando la Batalla de Hoth, y múltiples copias son esenciales para construir formaciones de asalto imperiales apropiadas de El Imperio Contraataca.'
  },
  {
    no: 'sw0367',
    name: 'Luke Skywalker (Hoth Outfit)',
    en: 'Luke Skywalker in his Hoth outfit represents the young Jedi-in-training during the opening act of The Empire Strikes Back, before his fateful encounter with the Wampa and vision of Obi-Wan Kenobi. This 2009 minifigure features detailed printing of Luke\'s insulated Rebel pilot flight suit with orange accents, utility belt, and cold-weather gear worn during patrol duties on the ice planet. First appearing in set 7666 (Hoth Rebel Base), this figure captures Luke\'s role as a snowspeeder pilot and key leader in the Rebel Alliance\'s defense of Echo Base. The Hoth Luke variant is essential for collectors recreating iconic scenes like the Tauntaun patrol or the Battle of Hoth, and it remains one of the most frequently re-released Luke variants due to the enduring popularity of the Hoth setting in LEGO Star Wars.',
    de: 'Luke Skywalker in seinem Hoth-Outfit repräsentiert den jungen Jedi-Schüler während des Eröffnungsakts von Das Imperium schlägt zurück, vor seiner schicksalhaften Begegnung mit dem Wampa und der Vision von Obi-Wan Kenobi. Diese Minifigur von 2009 zeigt detaillierten Druck von Lukes isoliertem Rebellen-Pilotenfluganzug mit orangefarbenen Akzenten, Gürtel und Kaltwetterausrüstung, die während der Patrouillenpflichten auf dem Eisplaneten getragen wurde. Erstmals erscheinend in Set 7666 (Hoth-Rebellenbasis), zeigt diese Figur Lukes Rolle als Schneespeeder-Pilot und Schlüsselführer in der Verteidigung der Echo-Basis durch die Rebellenallianz. Die Hoth-Luke-Variante ist unerlässlich für Sammler, die ikonische Szenen wie die Tauntaun-Patrouille oder die Schlacht von Hoth nachstellen, und sie bleibt eine der am häufigsten neu aufgelegten Luke-Varianten aufgrund der anhaltenden Beliebtheit des Hoth-Settings in LEGO Star Wars.',
    fr: 'Luke Skywalker dans sa tenue de Hoth représente le jeune Jedi en formation pendant l\'acte d\'ouverture de L\'Empire contre-attaque, avant sa rencontre fatidique avec le Wampa et sa vision d\'Obi-Wan Kenobi. Cette minifigurine de 2009 présente des impressions détaillées de la combinaison de vol de pilote Rebelle isolée de Luke avec des accents orange, une ceinture utilitaire et un équipement par temps froid porté pendant les patrouilles sur la planète de glace. Apparaissant pour la première fois dans le set 7666 (Base Rebelle de Hoth), cette figurine capture le rôle de Luke en tant que pilote de snowspeeder et leader clé dans la défense de la Base Echo par l\'Alliance Rebelle. La variante Luke de Hoth est essentielle pour les collectionneurs recréant des scènes iconiques comme la patrouille en Tauntaun ou la Bataille de Hoth, et elle reste l\'une des variantes de Luke les plus fréquemment rééditées en raison de la popularité durable du cadre de Hoth dans LEGO Star Wars.',
    es: 'Luke Skywalker en su atuendo de Hoth representa al joven Jedi en entrenamiento durante el acto inicial de El Imperio Contraataca, antes de su fatídico encuentro con el Wampa y la visión de Obi-Wan Kenobi. Esta minifigura de 2009 presenta impresiones detalladas del traje de vuelo de piloto Rebelde aislado de Luke con acentos naranjas, cinturón utilitario y equipo para clima frío usado durante los deberes de patrulla en el planeta de hielo. Apareciendo por primera vez en el set 7666 (Base Rebelde de Hoth), esta figura captura el papel de Luke como piloto de snowspeeder y líder clave en la defensa de la Base Eco por la Alianza Rebelde. La variante de Luke de Hoth es esencial para coleccionistas recreando escenas icónicas como la patrulla en Tauntaun o la Batalla de Hoth, y sigue siendo una de las variantes de Luke más frecuentemente relanzadas debido a la popularidad duradera del escenario de Hoth en LEGO Star Wars.'
  },
  {
    no: 'sw0368',
    name: 'Rebel Trooper (Hoth)',
    en: 'Rebel Troopers stationed at Echo Base on Hoth served as the backbone infantry defending the Alliance\'s hidden headquarters against the Imperial assault in The Empire Strikes Back. This 2009 minifigure depicts a Hoth Rebel soldier wearing insulated white and tan winter combat gear with distinctive vest printing, survival equipment, and cold-weather helmet designed for the harsh ice planet conditions. Released in set 7666 (Hoth Rebel Base), this trooper represents the brave defenders who manned the trenches and defense installations during the Empire\'s ground assault. The Hoth Rebel Trooper is highly valued by army builders recreating the Battle of Hoth dioramas, and its neutral design allows collectors to populate their Echo Base MOCs with generic but screen-accurate personnel from one of the saga\'s most iconic battles.',
    de: 'Rebellentruppen, die in der Echo-Basis auf Hoth stationiert waren, dienten als Rückgrat-Infanterie zur Verteidigung des versteckten Hauptquartiers der Allianz gegen den imperialen Angriff in Das Imperium schlägt zurück. Diese Minifigur von 2009 zeigt einen Hoth-Rebellensoldaten, der isolierte weiße und hellbraune Winterkampfausrüstung mit markanter Westendruck, Überlebensausrüstung und Kaltwetterhelm trägt, der für die rauen Eisplanetenbedingungen entwickelt wurde. Veröffentlicht in Set 7666 (Hoth-Rebellenbasis), repräsentiert dieser Soldat die tapferen Verteidiger, die während des Bodenangriffs des Imperiums die Schützengräben und Verteidigungsanlagen besetzten. Der Hoth-Rebellensoldat wird von Armeebauern hoch geschätzt, die Dioramen der Schlacht von Hoth nachstellen, und sein neutrales Design ermöglicht es Sammlern, ihre Echo-Basis-MOCs mit generischem, aber filmgetreuem Personal aus einer der ikonischsten Schlachten der Saga zu bevölkern.',
    fr: 'Les Soldats Rebelles stationnés à la Base Echo sur Hoth servaient d\'infanterie de base défendant le quartier général caché de l\'Alliance contre l\'assaut Impérial dans L\'Empire contre-attaque. Cette minifigurine de 2009 représente un soldat Rebelle de Hoth portant un équipement de combat hivernal isolé blanc et beige avec des impressions de gilet distinctives, un équipement de survie et un casque par temps froid conçu pour les conditions difficiles de la planète de glace. Sortie dans le set 7666 (Base Rebelle de Hoth), ce soldat représente les braves défenseurs qui ont occupé les tranchées et les installations de défense pendant l\'assaut terrestre de l\'Empire. Le Soldat Rebelle de Hoth est très apprécié par les constructeurs d\'armées recréant des dioramas de la Bataille de Hoth, et son design neutre permet aux collectionneurs de peupler leurs MOCs de la Base Echo avec du personnel générique mais fidèle à l\'écran de l\'une des batailles les plus iconiques de la saga.',
    es: 'Los Soldados Rebeldes estacionados en la Base Eco en Hoth sirvieron como la infantería central defendiendo el cuartel general oculto de la Alianza contra el asalto Imperial en El Imperio Contraataca. Esta minifigura de 2009 representa a un soldado Rebelde de Hoth vistiendo equipo de combate invernal aislado blanco y beige con impresiones distintivas de chaleco, equipo de supervivencia y casco para clima frío diseñado para las duras condiciones del planeta de hielo. Lanzado en el set 7666 (Base Rebelde de Hoth), este soldado representa a los valientes defensores que ocuparon las trincheras e instalaciones de defensa durante el asalto terrestre del Imperio. El Soldado Rebelde de Hoth es muy valorado por los constructores de ejércitos recreando dioramas de la Batalla de Hoth, y su diseño neutral permite a los coleccionistas poblar sus MOCs de la Base Eco con personal genérico pero fiel a la pantalla de una de las batallas más icónicas de la saga.'
  },
  {
    no: 'sw0369',
    name: 'K-3PO',
    en: 'K-3PO is a white protocol droid serving the Rebel Alliance at Echo Base on Hoth, briefly appearing in The Empire Strikes Back as one of the background droids in the Rebel command center. This 2009 minifigure features all-white body printing with mechanical detail and the characteristic protocol droid head design, representing one of the rarer background droids from the original trilogy. First released in set 7666 (Hoth Rebel Base), K-3PO adds authenticity to Hoth diorama displays by representing the diverse support personnel and equipment used by the Rebellion. As a lesser-known character compared to C-3PO, K-3PO has become a collector favorite for fans seeking to complete their roster of protocol droids, and its single appearance in this 2009 set has made it increasingly scarce and valuable in the secondary market.',
    de: 'K-3PO ist ein weißer Protokolldroide im Dienst der Rebellenallianz in der Echo-Basis auf Hoth, der kurz in Das Imperium schlägt zurück als einer der Hintergrunddroiden im Rebellenkommandozentrum erscheint. Diese Minifigur von 2009 zeigt einen vollständig weißen Körperdruck mit mechanischen Details und dem charakteristischen Protokolldroidenkopfdesign und repräsentiert einen der selteneren Hintergrunddroiden aus der ursprünglichen Trilogie. Erstmals veröffentlicht in Set 7666 (Hoth-Rebellenbasis), fügt K-3PO Hoth-Diorama-Displays Authentizität hinzu, indem er das vielfältige Unterstützungspersonal und die Ausrüstung repräsentiert, die von der Rebellion verwendet wurden. Als weniger bekannter Charakter im Vergleich zu C-3PO ist K-3PO zu einem Sammlerfavoriten für Fans geworden, die ihr Protokolldroiden-Roster vervollständigen möchten, und sein einziges Erscheinen in diesem Set von 2009 hat ihn auf dem Sekundärmarkt zunehmend knapp und wertvoll gemacht.',
    fr: 'K-3PO est un droïde de protocole blanc servant l\'Alliance Rebelle à la Base Echo sur Hoth, apparaissant brièvement dans L\'Empire contre-attaque comme l\'un des droïdes d\'arrière-plan dans le centre de commandement Rebelle. Cette minifigurine de 2009 présente un corps entièrement blanc avec des détails mécaniques et le design caractéristique de tête de droïde de protocole, représentant l\'un des droïdes d\'arrière-plan les plus rares de la trilogie originale. Sortie pour la première fois dans le set 7666 (Base Rebelle de Hoth), K-3PO ajoute de l\'authenticité aux présentations de dioramas de Hoth en représentant le personnel de soutien diversifié et l\'équipement utilisés par la Rébellion. En tant que personnage moins connu par rapport à C-3PO, K-3PO est devenu un favori des collectionneurs pour les fans cherchant à compléter leur liste de droïdes de protocole, et sa seule apparition dans ce set de 2009 l\'a rendu de plus en plus rare et précieux sur le marché secondaire.',
    es: 'K-3PO es un droide de protocolo blanco sirviendo a la Alianza Rebelde en la Base Eco en Hoth, apareciendo brevemente en El Imperio Contraataca como uno de los droides de fondo en el centro de comando Rebelde. Esta minifigura de 2009 presenta impresiones de cuerpo completamente blanco con detalle mecánico y el diseño característico de cabeza de droide de protocolo, representando uno de los droides de fondo más raros de la trilogía original. Lanzado por primera vez en el set 7666 (Base Rebelde de Hoth), K-3PO agrega autenticidad a las exhibiciones de dioramas de Hoth al representar el diverso personal de apoyo y equipo utilizado por la Rebelión. Como un personaje menos conocido en comparación con C-3PO, K-3PO se ha convertido en un favorito de los coleccionistas para fanáticos que buscan completar su lista de droides de protocolo, y su única aparición en este set de 2009 lo ha hecho cada vez más escaso y valioso en el mercado secundario.'
  },
  {
    no: 'sw0370',
    name: 'Medical Droid',
    en: 'Medical Droids, also known as FX-series medical assistant droids, served in the Alliance\'s bacta tank medical facilities on Hoth, famously treating Luke Skywalker after his Wampa attack in The Empire Strikes Back. This 2009 minifigure features a distinctive black body with transparent head element, mechanical arm printing, and the characteristic medical scanner equipment representing the surgical droids seen in Echo Base\'s medical bay. Released in set 7666 (Hoth Rebel Base), this droid is essential for recreating the iconic bacta tank scene where Luke recovers from his injuries. The Medical Droid\'s unique transparent head piece and specialized design make it a standout figure for Star Wars medical facility builds, and its appearance in only this single Hoth-themed set has made it a valuable piece for collectors seeking complete Echo Base displays.',
    de: 'Medizinische Droiden, auch bekannt als medizinische Assistenzdroiden der FX-Serie, dienten in den Bacta-Tank-medizinischen Einrichtungen der Allianz auf Hoth und behandelten berühmt Luke Skywalker nach seinem Wampa-Angriff in Das Imperium schlägt zurück. Diese Minifigur von 2009 zeigt einen markanten schwarzen Körper mit transparentem Kopfelement, mechanischem Armdruck und der charakteristischen medizinischen Scanner-Ausrüstung, die die chirurgischen Droiden in der Krankenstation der Echo-Basis repräsentiert. Veröffentlicht in Set 7666 (Hoth-Rebellenbasis), ist dieser Droide unerlässlich für die Nachstellung der ikonischen Bacta-Tank-Szene, in der Luke sich von seinen Verletzungen erholt. Das einzigartige transparente Kopfteil und das spezialisierte Design des Medizinischen Droiden machen ihn zu einer herausragenden Figur für Star Wars-Medizineinrichtungsbauten, und sein Erscheinen in nur diesem einzelnen Hoth-thematischen Set hat ihn zu einem wertvollen Stück für Sammler gemacht, die vollständige Echo-Basis-Displays suchen.',
    fr: 'Les Droïdes Médicaux, également connus sous le nom de droïdes assistants médicaux de la série FX, servaient dans les installations médicales à réservoir de bacta de l\'Alliance sur Hoth, traitant notamment Luke Skywalker après son attaque de Wampa dans L\'Empire contre-attaque. Cette minifigurine de 2009 présente un corps noir distinctif avec un élément de tête transparent, des impressions de bras mécaniques et l\'équipement de scanner médical caractéristique représentant les droïdes chirurgicaux vus dans l\'infirmerie de la Base Echo. Sortie dans le set 7666 (Base Rebelle de Hoth), ce droïde est essentiel pour recréer la scène iconique du réservoir de bacta où Luke récupère de ses blessures. La pièce de tête transparente unique et le design spécialisé du Droïde Médical en font une figurine remarquable pour les constructions d\'installations médicales Star Wars, et son apparition dans seulement ce set unique à thème Hoth en a fait une pièce précieuse pour les collectionneurs recherchant des présentations complètes de la Base Echo.',
    es: 'Los Droides Médicos, también conocidos como droides asistentes médicos de la serie FX, sirvieron en las instalaciones médicas de tanque bacta de la Alianza en Hoth, tratando famosamente a Luke Skywalker después de su ataque de Wampa en El Imperio Contraataca. Esta minifigura de 2009 presenta un distintivo cuerpo negro con elemento de cabeza transparente, impresiones de brazo mecánico y el característico equipo de escáner médico representando los droides quirúrgicos vistos en la bahía médica de la Base Eco. Lanzado en el set 7666 (Base Rebelde de Hoth), este droide es esencial para recrear la icónica escena del tanque bacta donde Luke se recupera de sus heridas. La pieza de cabeza transparente única y el diseño especializado del Droide Médico lo hacen una figura destacada para construcciones de instalaciones médicas de Star Wars, y su aparición en solo este único set temático de Hoth lo ha hecho una pieza valiosa para coleccionistas que buscan exhibiciones completas de la Base Eco.'
  },
  {
    no: 'sw0371',
    name: 'Wampa',
    en: 'The Wampa is a fearsome carnivorous ice creature native to the planet Hoth, infamous for capturing Luke Skywalker and hanging him upside-down in its cave lair in the opening of The Empire Strikes Back. This 2009 minifigure features a large white furry body with aggressive printing showing sharp claws, fierce teeth, and bloodied mouth details from its predatory nature on the frozen wasteland. Released in set 8089 (Hoth Wampa Cave), this figure captures one of the original trilogy\'s most memorable creature encounters and Luke\'s first test with his lightsaber skills. The Wampa\'s imposing size and detailed design make it a centerpiece figure for Hoth dioramas, and its role in such an iconic scene has made this minifigure highly sought-after by collectors recreating the complete Hoth storyline from Episode V.',
    de: 'Der Wampa ist eine furchterregende fleischfressende Eiskreatur, die auf dem Planeten Hoth heimisch ist, berüchtigt dafür, Luke Skywalker gefangen zu nehmen und ihn kopfüber in seiner Höhle aufzuhängen, am Anfang von Das Imperium schlägt zurück. Diese Minifigur von 2009 zeigt einen großen weißen pelzigen Körper mit aggressivem Druck, der scharfe Krallen, wilde Zähne und blutige Munddetails von seiner räuberischen Natur in der gefrorenen Einöde zeigt. Veröffentlicht in Set 8089 (Hoth Wampa-Höhle), fängt diese Figur eine der unvergesslichsten Kreaturenbegegnungen der ursprünglichen Trilogie und Lukes ersten Test mit seinen Lichtschwertkünsten ein. Die imposante Größe und das detaillierte Design des Wampas machen ihn zu einer Kernstückfigur für Hoth-Dioramen, und seine Rolle in einer so ikonischen Szene hat diese Minifigur bei Sammlern, die die vollständige Hoth-Handlung aus Episode V nachstellen, sehr begehrt gemacht.',
    fr: 'Le Wampa est une créature de glace carnivore redoutable native de la planète Hoth, tristement célèbre pour avoir capturé Luke Skywalker et l\'avoir suspendu la tête en bas dans sa tanière de grotte au début de L\'Empire contre-attaque. Cette minifigurine de 2009 présente un grand corps blanc poilu avec des impressions agressives montrant des griffes acérées, des dents féroces et des détails de bouche ensanglantée de sa nature prédatrice dans le désert gelé. Sortie dans le set 8089 (Grotte du Wampa de Hoth), cette figurine capture l\'une des rencontres de créatures les plus mémorables de la trilogie originale et le premier test de Luke avec ses compétences au sabre laser. La taille imposante et le design détaillé du Wampa en font une pièce maîtresse pour les dioramas de Hoth, et son rôle dans une scène si iconique a rendu cette minifigurine très recherchée par les collectionneurs recréant l\'histoire complète de Hoth de l\'Épisode V.',
    es: 'El Wampa es una temible criatura de hielo carnívora nativa del planeta Hoth, infame por capturar a Luke Skywalker y colgarlo boca abajo en su guarida de cueva en la apertura de El Imperio Contraataca. Esta minifigura de 2009 presenta un gran cuerpo peludo blanco con impresiones agresivas mostrando garras afiladas, dientes feroces y detalles de boca ensangrentada de su naturaleza depredadora en el páramo helado. Lanzada en el set 8089 (Cueva Wampa de Hoth), esta figura captura uno de los encuentros de criaturas más memorables de la trilogía original y la primera prueba de Luke con sus habilidades de sable de luz. El tamaño imponente y el diseño detallado del Wampa lo hacen una figura central para dioramas de Hoth, y su papel en una escena tan icónica ha hecho esta minifigura muy codiciada por coleccionistas recreando la historia completa de Hoth del Episodio V.'
  },
  {
    no: 'sw0372',
    name: 'ARC Trooper (Blue)',
    en: 'ARC Troopers (Advanced Recon Commandos) were elite clone soldiers who received specialized training directly from Jango Fett, serving as some of the Republic\'s most capable warriors during the Clone Wars. This 2009 minifigure features distinctive blue-marked armor with detailed kama (waist skirt), pauldron shoulder armor, and Phase I helmet design with rangefinder attachment, representing the ARC trooper visual design from the 2003 Clone Wars animated series. Released in set 8014 (Clone Walker Battle Pack), this blue ARC trooper became highly valued by collectors for its unique color scheme and elite soldier status. The combination of specialized armor printing, cloth kama piece, and commanding presence make this figure perfect for leading clone trooper squads in Republic military displays, and its battle pack availability made army building these elite commandos surprisingly accessible.',
    de: 'ARC-Truppen (Advanced Recon Commandos) waren Elite-Klonsoldaten, die spezialisiertes Training direkt von Jango Fett erhielten und während der Klonkriege als einige der fähigsten Krieger der Republik dienten. Diese Minifigur von 2009 zeigt eine markante blau markierte Rüstung mit detailliertem Kama (Taillenrock), Pauldron-Schulterrüstung und Phase-I-Helmdesign mit Entfernungsmesser-Aufsatz, der das visuelle ARC-Truppen-Design aus der animierten Clone Wars-Serie von 2003 repräsentiert. Veröffentlicht in Set 8014 (Clone Walker Battle Pack), wurde dieser blaue ARC-Truppen von Sammlern für sein einzigartiges Farbschema und seinen Elite-Soldatenstatus sehr geschätzt. Die Kombination aus spezialisiertem Rüstungsdruck, Stoff-Kama-Teil und kommandierender Präsenz machen diese Figur perfekt für die Führung von Klontruppen-Trupps in republikanischen Militärdisplays, und seine Battle-Pack-Verfügbarkeit machte den Armeeaufbau dieser Elite-Kommandos überraschend zugänglich.',
    fr: 'Les ARC Troopers (Advanced Recon Commandos) étaient des soldats clones d\'élite qui ont reçu un entraînement spécialisé directement de Jango Fett, servant parmi les guerriers les plus capables de la République pendant la Guerre des Clones. Cette minifigurine de 2009 présente une armure distinctive marquée de bleu avec un kama détaillé (jupe de taille), une armure d\'épaule pauldron et un design de casque Phase I avec une pièce jointe de télémètre, représentant le design visuel des ARC troopers de la série animée Clone Wars de 2003. Sortie dans le set 8014 (Battle Pack Clone Walker), ce ARC trooper bleu est devenu très apprécié par les collectionneurs pour son schéma de couleurs unique et son statut de soldat d\'élite. La combinaison de l\'impression d\'armure spécialisée, de la pièce de kama en tissu et de la présence commandante rendent cette figurine parfaite pour diriger des escouades de clone troopers dans des présentations militaires de la République, et sa disponibilité en battle pack a rendu la construction d\'armées de ces commandos d\'élite étonnamment accessible.',
    es: 'Los ARC Troopers (Comandos de Reconocimiento Avanzado) eran soldados clon de élite que recibieron entrenamiento especializado directamente de Jango Fett, sirviendo como algunos de los guerreros más capaces de la República durante las Guerras Clon. Esta minifigura de 2009 presenta una distintiva armadura marcada en azul con kama detallado (falda de cintura), armadura de hombro pauldron y diseño de casco Fase I con accesorio de telémetro, representando el diseño visual del ARC trooper de la serie animada Clone Wars de 2003. Lanzado en el set 8014 (Battle Pack Clone Walker), este ARC trooper azul se volvió muy valorado por coleccionistas por su esquema de color único y estatus de soldado de élite. La combinación de impresiones de armadura especializada, pieza de kama de tela y presencia comandante hacen esta figura perfecta para liderar escuadrones de clone troopers en exhibiciones militares de la República, y su disponibilidad en battle pack hizo la construcción de ejércitos de estos comandos de élite sorprendentemente accesible.'
  },
  {
    no: 'sw0373',
    name: 'Clone Trooper (Episode 3, Dark Tan)',
    en: 'Clone Troopers in dark tan camouflage armor served in desert and arid environment campaigns during the final stages of the Clone Wars, representing the Republic\'s specialized environmental adaptation strategies in Episode III. This 2009 minifigure features Phase II armor with distinctive dark tan and white color scheme, representing clone forces deployed to desert worlds like Utapau, Geonosis, or other sandy battlefields. Released in set 8014 (Clone Walker Battle Pack), this variant provided collectors with an alternative color scheme for diversifying their Republic armies beyond the standard white armor. The desert camouflage design and its inclusion in an affordable battle pack made this clone trooper particularly popular for army builders creating large-scale Republic military forces, and the dark tan coloring offers visual variety essential for realistic battlefield dioramas across multiple planetary environments.',
    de: 'Klontruppen in dunkler Tarnrüstung dienten in Wüsten- und Trockenumgebungskampagnen während der letzten Phasen der Klonkriege und repräsentierten die spezialisierten Umweltanpassungsstrategien der Republik in Episode III. Diese Minifigur von 2009 zeigt Phase-II-Rüstung mit markanter dunkelbrauner und weißer Farbgebung, die Klonstreitkräfte repräsentiert, die auf Wüstenwelten wie Utapau, Geonosis oder anderen sandigen Schlachtfeldern eingesetzt wurden. Veröffentlicht in Set 8014 (Clone Walker Battle Pack), bot diese Variante Sammlern ein alternatives Farbschema zur Diversifizierung ihrer republikanischen Armeen über die standardmäßige weiße Rüstung hinaus. Das Wüstentarnungsdesign und seine Aufnahme in ein erschwingliches Battle Pack machten diesen Klontruppler besonders beliebt bei Armeebauern, die groß angelegte republikanische Militärstreitkräfte erschaffen, und die dunkle Tarnfärbung bietet visuelle Vielfalt, die für realistische Schlachtfeld-Dioramen über mehrere planetare Umgebungen hinweg unerlässlich ist.',
    fr: 'Les Clone Troopers en armure de camouflage brun foncé servaient dans des campagnes de désert et d\'environnement aride pendant les dernières étapes de la Guerre des Clones, représentant les stratégies d\'adaptation environnementale spécialisées de la République dans l\'Épisode III. Cette minifigurine de 2009 présente une armure Phase II avec un schéma de couleurs brun foncé et blanc distinctif, représentant les forces clones déployées sur des mondes désertiques comme Utapau, Geonosis ou d\'autres champs de bataille sablonneux. Sortie dans le set 8014 (Battle Pack Clone Walker), cette variante a fourni aux collectionneurs un schéma de couleurs alternatif pour diversifier leurs armées de la République au-delà de l\'armure blanche standard. Le design de camouflage désertique et son inclusion dans un battle pack abordable ont rendu ce clone trooper particulièrement populaire pour les constructeurs d\'armées créant des forces militaires de la République à grande échelle, et la coloration brun foncé offre une variété visuelle essentielle pour des dioramas de champs de bataille réalistes à travers plusieurs environnements planétaires.',
    es: 'Los Clone Troopers en armadura de camuflaje marrón oscuro sirvieron en campañas de desierto y ambientes áridos durante las etapas finales de las Guerras Clon, representando las estrategias de adaptación ambiental especializadas de la República en el Episodio III. Esta minifigura de 2009 presenta armadura Fase II con un distintivo esquema de color marrón oscuro y blanco, representando fuerzas clon desplegadas en mundos desérticos como Utapau, Geonosis u otros campos de batalla arenosos. Lanzado en el set 8014 (Battle Pack Clone Walker), esta variante proporcionó a los coleccionistas un esquema de color alternativo para diversificar sus ejércitos de la República más allá de la armadura blanca estándar. El diseño de camuflaje desértico y su inclusión en un battle pack asequible hicieron este clone trooper particularmente popular para constructores de ejércitos creando fuerzas militares de la República a gran escala, y la coloración marrón oscura ofrece variedad visual esencial para dioramas de campo de batalla realistas a través de múltiples ambientes planetarios.'
  }
];

async function saveBatch044() {
  console.log('💾 Saving batch 044 (sw0364-sw0373) - 10 minifigs...\n');

  let saved = 0;
  let skipped = 0;

  for (const m of batch044) {
    try {
      await prisma.minifigCatalog.update({
        where: { minifigure_no: m.no },
        data: {
          description_en: m.en,
          description_de: m.de,
          description_fr: m.fr,
          description_es: m.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        }
      });
      console.log(`  ✅ ${m.no}: ${m.name}`);
      saved++;
    } catch (error: any) {
      console.log(`  ⚠️  ${m.no}: NOT IN DATABASE (skipped)`);
      skipped++;
    }
  }

  console.log(`\n✨ Batch 044 complete: ${saved} saved, ${skipped} skipped (${saved * 4} descriptions)\n`);

  await prisma.$disconnect();
}

saveBatch044().catch(console.error);
