import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0619',
    name: 'Sabine Wren',
    en: 'Sabine Wren is the Mandalorian explosives expert and graffiti artist who fights with the Ghost crew against the Empire in Star Wars Rebels, wielding dual blaster pistols and distinctive customized armor. This LEGO minifigure captures Sabine\'s colorful appearance with orange, purple, and teal armor design featuring her artistic paint schemes, dual-molded helmet with Mandalorian styling, and weapon accessories. Released in 2014-2017 across multiple Rebels sets including 75150 and 75106, Sabine represents the creative warrior spirit of the Mandalorian people. Her artistic talent, explosive expertise, and role in the early Rebellion make this minifigure essential for collectors building Rebels character rosters and Mandalorian warrior collections.',
    de: 'Sabine Wren ist die mandalorianische Sprengstoff-Expertin und Graffiti-Künstlerin, die mit der Ghost-Crew in Star Wars Rebels gegen das Imperium kämpft und doppelte Blaster-Pistolen sowie charakteristische angepasste Rüstung führt. Diese LEGO Minifigur fängt Sabines farbenfrohes Aussehen mit orange-lila-türkisfarbenem Rüstungsdesign ein, das ihre künstlerischen Lackierungen zeigt, doppelt geformten Helm mit mandalorianischem Stil und Waffen-Accessoires. Veröffentlicht 2014-2017 in mehreren Rebels-Sets einschließlich 75150 und 75106, repräsentiert Sabine den kreativen Kriegergeist des mandalorianischen Volkes. Ihr künstlerisches Talent, Sprengstoff-Expertise und Rolle in der frühen Rebellion machen diese Minifigur unverzichtbar für Sammler, die Rebels-Charakter-Rosters und mandalorianische Krieger-Sammlungen aufbauen.',
    fr: 'Sabine Wren est l\'experte en explosifs Mandalorienne et artiste graffiti qui combat avec l\'équipage du Ghost contre l\'Empire dans Star Wars Rebels, maniant deux pistolets blasters et une armure personnalisée distinctive. Cette minifigurine LEGO capture l\'apparence colorée de Sabine avec un design d\'armure orange, violet et turquoise présentant ses schémas de peinture artistiques, casque à double moulage de style Mandalorien et accessoires d\'armes. Sortie en 2014-2017 dans plusieurs sets Rebels dont 75150 et 75106, Sabine représente l\'esprit guerrier créatif du peuple Mandalorien. Son talent artistique, son expertise en explosifs et son rôle dans la Rébellion primitive rendent cette minifigurine essentielle pour les collectionneurs construisant des listes de personnages Rebels et des collections de guerriers Mandaloriens.',
    es: 'Sabine Wren es la experta en explosivos Mandaloriana y artista de grafiti que lucha con la tripulación del Fantasma contra el Imperio en Star Wars Rebels, empuñando pistolas bláster duales y distintiva armadura personalizada. Esta minifigura LEGO captura la colorida apariencia de Sabine con diseño de armadura naranja, púrpura y turquesa presentando sus esquemas de pintura artística, casco de doble molde con estilo Mandaloriano y accesorios de armas. Lanzada en 2014-2017 en múltiples sets de Rebels incluyendo 75150 y 75106, Sabine representa el espíritu guerrero creativo del pueblo Mandaloriano. Su talento artístico, experiencia en explosivos y papel en la Rebelión temprana hacen de esta minifigura esencial para coleccionistas construyendo listas de personajes de Rebels y colecciones de guerreros Mandalorianos.'
  },
  {
    no: 'sw0620',
    name: 'Ezra Bridger',
    en: 'Ezra Bridger is the Force-sensitive street thief from Lothal who becomes Kanan Jarrus\' Padawan and a key member of the Ghost crew in Star Wars Rebels. This LEGO minifigure captures Ezra\'s appearance with dark hair, orange and blue jumpsuit with armor pieces, and lightsaber-blaster hybrid weapon representing his unconventional Jedi training. Released in 2014-2017 across multiple Rebels sets including 75053 and 75150, Ezra represents a new generation discovering the Force during the dark times of Imperial rule. His journey from orphan to Jedi and connection to Lothal\'s liberation make this minifigure essential for collectors building Rebels storylines and early Rebellion hero collections.',
    de: 'Ezra Bridger ist der macht-sensitive Straßendieb von Lothal, der Kanan Jarrus\' Padawan und ein Schlüsselmitglied der Ghost-Crew in Star Wars Rebels wird. Diese LEGO Minifigur fängt Ezras Aussehen mit dunklem Haar, orange-blauem Overall mit Rüstungsteilen und Lichtschwert-Blaster-Hybrid-Waffe ein, die sein unkonventionelles Jedi-Training repräsentiert. Veröffentlicht 2014-2017 in mehreren Rebels-Sets einschließlich 75053 und 75150, repräsentiert Ezra eine neue Generation, die die Macht während der dunklen Zeiten der imperialen Herrschaft entdeckt. Seine Reise vom Waisenkind zum Jedi und Verbindung zu Lothals Befreiung machen diese Minifigur unverzichtbar für Sammler, die Rebels-Storylines und frühe Rebellions-Helden-Sammlungen aufbauen.',
    fr: 'Ezra Bridger est le voleur des rues sensible à la Force de Lothal qui devient le Padawan de Kanan Jarrus et un membre clé de l\'équipage du Ghost dans Star Wars Rebels. Cette minifigurine LEGO capture l\'apparence d\'Ezra avec cheveux foncés, combinaison orange et bleue avec pièces d\'armure et arme hybride sabre laser-blaster représentant son entraînement Jedi non conventionnel. Sortie en 2014-2017 dans plusieurs sets Rebels dont 75053 et 75150, Ezra représente une nouvelle génération découvrant la Force pendant les temps sombres de la domination impériale. Son voyage d\'orphelin à Jedi et sa connexion à la libération de Lothal rendent cette minifigurine essentielle pour les collectionneurs construisant des histoires Rebels et des collections de héros de la Rébellion primitive.',
    es: 'Ezra Bridger es el ladrón callejero sensible a la Fuerza de Lothal que se convierte en el Padawan de Kanan Jarrus y un miembro clave de la tripulación del Fantasma en Star Wars Rebels. Esta minifigura LEGO captura la apariencia de Ezra con cabello oscuro, mono naranja y azul con piezas de armadura y arma híbrida sable de luz-bláster representando su entrenamiento Jedi no convencional. Lanzada en 2014-2017 en múltiples sets de Rebels incluyendo 75053 y 75150, Ezra representa una nueva generación descubriendo la Fuerza durante los tiempos oscuros del dominio Imperial. Su viaje de huérfano a Jedi y conexión con la liberación de Lothal hacen de esta minifigura esencial para coleccionistas construyendo historias de Rebels y colecciones de héroes de la Rebelión temprana.'
  },
  {
    no: 'sw0621',
    name: 'Kanan Jarrus',
    en: 'Kanan Jarrus is the former Jedi Padawan who survived Order 66 and leads the Ghost crew while training Ezra Bridger in Star Wars Rebels, hiding his Force abilities as a gunslinger and smuggler. This LEGO minifigure captures Kanan\'s appearance with ponytail hairstyle, teal and brown outfit with armor pieces, blaster, and lightsaber accessories representing his dual identity. Released in 2014-2017 across multiple Rebels sets including 75053 and 75141, Kanan represents the surviving Jedi who kept hope alive during the Empire\'s darkest period. His mentorship of Ezra and sacrifice protecting his crew make this minifigure essential for collectors building Rebels character rosters and Order 66 survivor collections.',
    de: 'Kanan Jarrus ist der ehemalige Jedi-Padawan, der Order 66 überlebte und die Ghost-Crew anführt, während er Ezra Bridger in Star Wars Rebels trainiert und seine Machtfähigkeiten als Revolverheld und Schmuggler verbirgt. Diese LEGO Minifigur fängt Kanans Aussehen mit Pferdeschwanz-Frisur, türkis-braunem Outfit mit Rüstungsteilen, Blaster und Lichtschwert-Accessoires ein, die seine doppelte Identität repräsentieren. Veröffentlicht 2014-2017 in mehreren Rebels-Sets einschließlich 75053 und 75141, repräsentiert Kanan die überlebenden Jedi, die während der dunkelsten Periode des Imperiums die Hoffnung am Leben hielten. Sein Mentoring von Ezra und Opfer zum Schutz seiner Crew machen diese Minifigur unverzichtbar für Sammler, die Rebels-Charakter-Rosters und Order-66-Überlebenden-Sammlungen aufbauen.',
    fr: 'Kanan Jarrus est l\'ancien Padawan Jedi qui a survécu à l\'Ordre 66 et dirige l\'équipage du Ghost tout en entraînant Ezra Bridger dans Star Wars Rebels, cachant ses capacités de Force en tant que tireur et contrebandier. Cette minifigurine LEGO capture l\'apparence de Kanan avec coiffure en queue de cheval, tenue turquoise et marron avec pièces d\'armure, blaster et accessoires de sabre laser représentant sa double identité. Sortie en 2014-2017 dans plusieurs sets Rebels dont 75053 et 75141, Kanan représente les Jedi survivants qui ont maintenu l\'espoir en vie pendant la période la plus sombre de l\'Empire. Son mentorat d\'Ezra et son sacrifice protégeant son équipage rendent cette minifigurine essentielle pour les collectionneurs construisant des listes de personnages Rebels et des collections de survivants de l\'Ordre 66.',
    es: 'Kanan Jarrus es el ex Padawan Jedi que sobrevivió a la Orden 66 y lidera la tripulación del Fantasma mientras entrena a Ezra Bridger en Star Wars Rebels, ocultando sus habilidades de la Fuerza como pistolero y contrabandista. Esta minifigura LEGO captura la apariencia de Kanan con peinado de cola de caballo, atuendo turquesa y marrón con piezas de armadura, bláster y accesorios de sable de luz representando su identidad dual. Lanzada en 2014-2017 en múltiples sets de Rebels incluyendo 75053 y 75141, Kanan representa a los Jedi sobrevivientes que mantuvieron viva la esperanza durante el período más oscuro del Imperio. Su mentoría de Ezra y sacrificio protegiendo a su tripulación hacen de esta minifigura esencial para coleccionistas construyendo listas de personajes de Rebels y colecciones de sobrevivientes de la Orden 66.'
  },
  {
    no: 'sw0622',
    name: 'Hera Syndulla',
    en: 'Hera Syndulla is the talented Twi\'lek pilot who commands the Ghost and leads her crew in early Rebellion operations against the Empire in Star Wars Rebels. This LEGO minifigure captures Hera\'s appearance with green head-tails (lekku), goggles on forehead, tan and brown flight suit with equipment vest representing her piloting expertise. Released in 2014-2017 across multiple Rebels sets including 75053 and 75127, Hera represents leadership and tactical brilliance in the early Rebellion. Her exceptional piloting skills and role organizing Rebel cells make this minifigure essential for collectors building Rebels leadership collections and Ghost crew rosters.',
    de: 'Hera Syndulla ist die talentierte Twi\'lek-Pilotin, die die Ghost kommandiert und ihre Crew in frühen Rebellions-Operationen gegen das Imperium in Star Wars Rebels anführt. Diese LEGO Minifigur fängt Heras Aussehen mit grünen Kopftentakeln (Lekku), Schutzbrille auf der Stirn, beige-braunem Fluganzug mit Ausrüstungsweste ein, die ihre Piloten-Expertise repräsentiert. Veröffentlicht 2014-2017 in mehreren Rebels-Sets einschließlich 75053 und 75127, repräsentiert Hera Führung und taktische Brillanz in der frühen Rebellion. Ihre außergewöhnlichen Pilotenfähigkeiten und Rolle bei der Organisation von Rebellenzellen machen diese Minifigur unverzichtbar für Sammler, die Rebels-Führungs-Sammlungen und Ghost-Crew-Rosters aufbauen.',
    fr: 'Hera Syndulla est la pilote Twi\'lek talentueuse qui commande le Ghost et dirige son équipage dans les premières opérations de la Rébellion contre l\'Empire dans Star Wars Rebels. Cette minifigurine LEGO capture l\'apparence d\'Hera avec queues de tête vertes (lekku), lunettes sur le front, combinaison de vol beige et marron avec gilet d\'équipement représentant son expertise de pilotage. Sortie en 2014-2017 dans plusieurs sets Rebels dont 75053 et 75127, Hera représente le leadership et le génie tactique dans la Rébellion primitive. Ses compétences de pilotage exceptionnelles et son rôle dans l\'organisation des cellules rebelles rendent cette minifigurine essentielle pour les collectionneurs construisant des collections de leadership Rebels et des listes d\'équipage du Ghost.',
    es: 'Hera Syndulla es la talentosa piloto Twi\'lek que comanda el Fantasma y lidera a su tripulación en operaciones tempranas de la Rebelión contra el Imperio en Star Wars Rebels. Esta minifigura LEGO captura la apariencia de Hera con colas de cabeza verdes (lekku), gafas en la frente, traje de vuelo beige y marrón con chaleco de equipo representando su experiencia de pilotaje. Lanzada en 2014-2017 en múltiples sets de Rebels incluyendo 75053 y 75127, Hera representa liderazgo y brillantez táctica en la Rebelión temprana. Sus excepcionales habilidades de pilotaje y papel organizando células Rebeldes hacen de esta minifigura esencial para coleccionistas construyendo colecciones de liderazgo de Rebels y listas de tripulación del Fantasma.'
  },
  {
    no: 'sw0623',
    name: 'Zeb Orrelios',
    en: 'Garazeb "Zeb" Orrelios is the Lasat warrior and former Honor Guard who provides muscle for the Ghost crew in Star Wars Rebels, seeking revenge against the Empire for his people\'s near-extinction. This LEGO minifigure captures Zeb\'s imposing appearance with purple and tan fur pattern, distinctive large build, and bo-rifle weapon accessory representing Lasat combat traditions. Released in 2014-2017 across multiple Rebels sets including 75053 and 75127, Zeb represents the survivors of Imperial atrocities fighting back. His strength, loyalty to his crew, and journey from vengeance to heroism make this minifigure essential for collectors building Rebels character rosters and diverse alien warrior collections.',
    de: 'Garazeb "Zeb" Orrelios ist der Lasat-Krieger und ehemalige Ehrenwächter, der der Ghost-Crew in Star Wars Rebels Muskelkraft bietet und Rache am Imperium für die Fast-Ausrottung seines Volkes sucht. Diese LEGO Minifigur fängt Zebs imposantes Aussehen mit lila-beigem Fellmuster, charakteristisch großem Körperbau und Bo-Gewehr-Waffen-Zubehör ein, das Lasat-Kampftraditionen repräsentiert. Veröffentlicht 2014-2017 in mehreren Rebels-Sets einschließlich 75053 und 75127, repräsentiert Zeb die Überlebenden imperialer Gräueltaten, die zurückschlagen. Seine Stärke, Loyalität zu seiner Crew und Reise von Rache zu Heldentum machen diese Minifigur unverzichtbar für Sammler, die Rebels-Charakter-Rosters und vielfältige Alien-Krieger-Sammlungen aufbauen.',
    fr: 'Garazeb "Zeb" Orrelios est le guerrier Lasat et ancien Garde d\'Honneur qui fournit la force musculaire à l\'équipage du Ghost dans Star Wars Rebels, cherchant vengeance contre l\'Empire pour la quasi-extinction de son peuple. Cette minifigurine LEGO capture l\'apparence imposante de Zeb avec motif de fourrure violet et beige, grande carrure distinctive et accessoire d\'arme bo-rifle représentant les traditions de combat Lasat. Sortie en 2014-2017 dans plusieurs sets Rebels dont 75053 et 75127, Zeb représente les survivants des atrocités impériales ripostant. Sa force, sa loyauté envers son équipage et son voyage de la vengeance à l\'héroïsme rendent cette minifigurine essentielle pour les collectionneurs construisant des listes de personnages Rebels et des collections de guerriers aliens divers.',
    es: 'Garazeb "Zeb" Orrelios es el guerrero Lasat y ex Guardia de Honor que proporciona fuerza muscular a la tripulación del Fantasma en Star Wars Rebels, buscando venganza contra el Imperio por la casi extinción de su pueblo. Esta minifigura LEGO captura la imponente apariencia de Zeb con patrón de pelaje púrpura y beige, distintiva gran constitución y accesorio de arma bo-rifle representando tradiciones de combate Lasat. Lanzada en 2014-2017 en múltiples sets de Rebels incluyendo 75053 y 75127, Zeb representa a los sobrevivientes de atrocidades imperiales contraatacando. Su fuerza, lealtad a su tripulación y viaje desde la venganza al heroísmo hacen de esta minifigura esencial para coleccionistas construyendo listas de personajes de Rebels y colecciones diversas de guerreros alienígenas.'
  },
  {
    no: 'sw0624',
    name: 'Chopper',
    en: 'C1-10P "Chopper" is the cranky astromech droid who serves aboard the Ghost in Star Wars Rebels, providing technical support with a grumpy personality and questionable morals. This LEGO minifigure features Chopper\'s distinctive orange and white body with unique droid design, extending arms, and personality representing his cantankerous nature. Released in 2014-2017 across multiple Rebels sets including 75053 and 75127, Chopper represents the quirky droids with attitude in Star Wars. His technical expertise combined with selfish tendencies and loyalty to Hera make this minifigure essential for collectors building Rebels droid collections and Ghost crew rosters.',
    de: 'C1-10P "Chopper" ist der mürrische Astromech-Droide, der an Bord der Ghost in Star Wars Rebels dient und technische Unterstützung mit griesgrämiger Persönlichkeit und fragwürdiger Moral bietet. Diese LEGO Minifigur zeigt Choppers charakteristischen orange-weißen Körper mit einzigartigem Droiden-Design, ausfahrenden Armen und Persönlichkeit, die seine streitsüchtige Natur repräsentiert. Veröffentlicht 2014-2017 in mehreren Rebels-Sets einschließlich 75053 und 75127, repräsentiert Chopper die schrulligen Droiden mit Attitüde in Star Wars. Seine technische Expertise kombiniert mit egoistischen Tendenzen und Loyalität zu Hera machen diese Minifigur unverzichtbar für Sammler, die Rebels-Droiden-Sammlungen und Ghost-Crew-Rosters aufbauen.',
    fr: 'C1-10P "Chopper" est le droïde astromech grincheux qui sert à bord du Ghost dans Star Wars Rebels, fournissant un soutien technique avec une personnalité grincheuse et une morale discutable. Cette minifigurine LEGO présente le corps orange et blanc distinctif de Chopper avec design de droïde unique, bras extensibles et personnalité représentant sa nature revêche. Sortie en 2014-2017 dans plusieurs sets Rebels dont 75053 et 75127, Chopper représente les droïdes excentriques avec attitude dans Star Wars. Son expertise technique combinée avec des tendances égoïstes et sa loyauté envers Hera rendent cette minifigurine essentielle pour les collectionneurs construisant des collections de droïdes Rebels et des listes d\'équipage du Ghost.',
    es: 'C1-10P "Chopper" es el droide astromecánico cascarrabias que sirve a bordo del Fantasma en Star Wars Rebels, proporcionando soporte técnico con personalidad gruñona y moral cuestionable. Esta minifigura LEGO presenta el distintivo cuerpo naranja y blanco de Chopper con diseño único de droide, brazos extensibles y personalidad representando su naturaleza pendenciera. Lanzada en 2014-2017 en múltiples sets de Rebels incluyendo 75053 y 75127, Chopper representa los droides peculiares con actitud en Star Wars. Su experiencia técnica combinada con tendencias egoístas y lealtad a Hera hacen de esta minifigura esencial para coleccionistas construyendo colecciones de droides de Rebels y listas de tripulación del Fantasma.'
  },
  {
    no: 'sw0625',
    name: 'Agent Kallus',
    en: 'Agent Kallus is the ruthless Imperial Security Bureau officer who hunts the Ghost crew in Star Wars Rebels, wielding his signature bo-rifle taken from a Lasat Honor Guard. This LEGO minifigure captures Kallus\' appearance with black ISB uniform with rank insignia, stern expression, and bo-rifle weapon accessory representing his combat prowess. Released in 2014-2016 across multiple Rebels sets including 75083 and 75106, Kallus represents Imperial law enforcement and later redemption as he defects to the Rebellion. His character arc from antagonist to ally and rivalry with Zeb make this minifigure significant for collectors building Rebels storylines and Imperial officer collections.',
    de: 'Agent Kallus ist der gnadenlose Offizier des Imperialen Sicherheitsbüros, der die Ghost-Crew in Star Wars Rebels jagt und sein charakteristisches Bo-Gewehr führt, das er einem Lasat-Ehrenwächter abgenommen hat. Diese LEGO Minifigur fängt Kallus\' Aussehen mit schwarzer ISB-Uniform mit Rangabzeichen, strengem Ausdruck und Bo-Gewehr-Waffen-Zubehör ein, das seine Kampffähigkeit repräsentiert. Veröffentlicht 2014-2016 in mehreren Rebels-Sets einschließlich 75083 und 75106, repräsentiert Kallus imperiale Strafverfolgung und spätere Erlösung, als er zur Rebellion überläuft. Sein Charakterbogen vom Antagonisten zum Verbündeten und Rivalität mit Zeb machen diese Minifigur bedeutsam für Sammler, die Rebels-Storylines und imperiale Offiziers-Sammlungen aufbauen.',
    fr: 'L\'Agent Kallus est l\'officier impitoyable du Bureau de Sécurité Impérial qui traque l\'équipage du Ghost dans Star Wars Rebels, maniant son bo-rifle signature pris à un Garde d\'Honneur Lasat. Cette minifigurine LEGO capture l\'apparence de Kallus avec uniforme ISB noir avec insignes de rang, expression sévère et accessoire d\'arme bo-rifle représentant ses prouesses au combat. Sortie en 2014-2016 dans plusieurs sets Rebels dont 75083 et 75106, Kallus représente l\'application de la loi impériale et plus tard la rédemption lorsqu\'il fait défection vers la Rébellion. Son arc narratif d\'antagoniste à allié et sa rivalité avec Zeb rendent cette minifigurine significative pour les collectionneurs construisant des histoires Rebels et des collections d\'officiers impériaux.',
    es: 'El Agente Kallus es el despiadado oficial de la Oficina de Seguridad Imperial que caza a la tripulación del Fantasma en Star Wars Rebels, empuñando su característico bo-rifle tomado de un Guardia de Honor Lasat. Esta minifigura LEGO captura la apariencia de Kallus con uniforme negro de la OSI con insignias de rango, expresión severa y accesorio de arma bo-rifle representando su destreza en combate. Lanzada en 2014-2016 en múltiples sets de Rebels incluyendo 75083 y 75106, Kallus representa la aplicación de la ley imperial y posterior redención cuando deserta a la Rebelión. Su arco de personaje de antagonista a aliado y rivalidad con Zeb hacen de esta minifigura significativa para coleccionistas construyendo historias de Rebels y colecciones de oficiales imperiales.'
  },
  {
    no: 'sw0626',
    name: 'The Inquisitor',
    en: 'The Grand Inquisitor is the Pau\'an dark side warrior who leads the Empire\'s Jedi-hunting Inquisitorius in Star Wars Rebels, wielding a distinctive double-bladed spinning lightsaber. This LEGO minifigure captures the Inquisitor\'s menacing appearance with pale gray skin, distinctive ridged head, black robes with armor plating, and unique double-bladed lightsaber accessory. Released in 2014-2015 in sets including 75082 and 75157, the Grand Inquisitor represents the Empire\'s Force-sensitive enforcers hunting surviving Jedi. His formidable combat skills and role as primary antagonist in Rebels Season 1 make this minifigure essential for collectors building Inquisitorius rosters and Rebels villain collections.',
    de: 'Der Großinquisitor ist der Pau\'aner Dunkelseiten-Krieger, der das Jedi-jagende Inquisitorium des Imperiums in Star Wars Rebels anführt und ein charakteristisches doppelschneidiges rotierendes Lichtschwert führt. Diese LEGO Minifigur fängt das bedrohliche Aussehen des Inquisitors mit blassgrauer Haut, charakteristischem gerilltem Kopf, schwarzen Roben mit Rüstungsplatten und einzigartigem doppelschneidigem Lichtschwert-Zubehör ein. Veröffentlicht 2014-2015 in Sets einschließlich 75082 und 75157, repräsentiert der Großinquisitor die macht-sensitiven Vollstrecker des Imperiums, die überlebende Jedi jagen. Seine beeindruckenden Kampffähigkeiten und Rolle als Hauptantagonist in Rebels Staffel 1 machen diese Minifigur unverzichtbar für Sammler, die Inquisitoriums-Rosters und Rebels-Bösewicht-Sammlungen aufbauen.',
    fr: 'Le Grand Inquisiteur est le guerrier du côté obscur Pau\'an qui dirige l\'Inquisitorius chasseur de Jedi de l\'Empire dans Star Wars Rebels, maniant un sabre laser rotatif à double lame distinctif. Cette minifigurine LEGO capture l\'apparence menaçante de l\'Inquisiteur avec peau gris pâle, tête striée distinctive, robes noires avec plaques d\'armure et accessoire de sabre laser à double lame unique. Sortie en 2014-2015 dans des sets dont 75082 et 75157, le Grand Inquisiteur représente les exécuteurs sensibles à la Force de l\'Empire traquant les Jedi survivants. Ses compétences de combat formidables et son rôle d\'antagoniste principal dans la saison 1 de Rebels rendent cette minifigurine essentielle pour les collectionneurs construisant des listes d\'Inquisitorius et des collections de méchants Rebels.',
    es: 'El Gran Inquisidor es el guerrero del lado oscuro Pau\'an que lidera el Inquisitorius cazador de Jedi del Imperio en Star Wars Rebels, empuñando un distintivo sable de luz giratorio de doble hoja. Esta minifigura LEGO captura la amenazante apariencia del Inquisidor con piel gris pálida, distintiva cabeza con crestas, túnicas negras con placas de armadura y único accesorio de sable de luz de doble hoja. Lanzada en 2014-2015 en sets incluyendo 75082 y 75157, el Gran Inquisidor representa a los ejecutores sensibles a la Fuerza del Imperio cazando Jedi sobrevivientes. Sus formidables habilidades de combate y papel como antagonista principal en la Temporada 1 de Rebels hacen de esta minifigura esencial para coleccionistas construyendo listas del Inquisitorius y colecciones de villanos de Rebels.'
  },
  {
    no: 'sw0627',
    name: 'Imperial Combat Driver',
    en: 'Imperial Combat Drivers operate AT-DP walkers and other ground assault vehicles on worlds like Lothal in Star Wars Rebels, representing specialized Imperial Army personnel. This LEGO minifigure features distinctive gray and black uniform with Imperial insignia, enclosed helmet with black visor, and equipment representing vehicle operation expertise. Released in 2014-2015 in sets including 75083 and 75078, Combat Drivers show Imperial ground forces beyond standard Stormtroopers. Their role piloting walkers and participation in Lothal occupation make this minifigure useful for collectors building diverse Imperial military forces and Rebels-era Imperial army displays.',
    de: 'Imperiale Kampffahrer bedienen AT-DP-Läufer und andere Bodenangrifffahrzeuge auf Welten wie Lothal in Star Wars Rebels und repräsentieren spezialisiertes Personal der imperialen Armee. Diese LEGO Minifigur zeigt charakteristische grau-schwarze Uniform mit imperialem Abzeichen, geschlossenen Helm mit schwarzem Visier und Ausrüstung, die Fahrzeugbedienungs-Expertise repräsentiert. Veröffentlicht 2014-2015 in Sets einschließlich 75083 und 75078, zeigen Kampffahrer imperiale Bodentruppen jenseits von Standard-Sturmtruplern. Ihre Rolle beim Pilotieren von Läufern und Teilnahme an der Lothal-Besatzung machen diese Minifigur nützlich für Sammler, die vielfältige imperiale Militärkräfte und Rebels-Ära-Imperiale-Armee-Displays aufbauen.',
    fr: 'Les Conducteurs de Combat Impériaux opèrent des marcheurs AT-DP et autres véhicules d\'assaut terrestres sur des mondes comme Lothal dans Star Wars Rebels, représentant le personnel spécialisé de l\'Armée Impériale. Cette minifigurine LEGO présente un uniforme gris et noir distinctif avec insigne impérial, casque fermé avec visière noire et équipement représentant l\'expertise d\'opération de véhicules. Sortie en 2014-2015 dans des sets dont 75083 et 75078, les Conducteurs de Combat montrent les forces terrestres impériales au-delà des Stormtroopers standards. Leur rôle pilotant des marcheurs et leur participation à l\'occupation de Lothal rendent cette minifigurine utile pour les collectionneurs construisant des forces militaires impériales diverses et des affichages d\'armée impériale de l\'ère Rebels.',
    es: 'Los Conductores de Combate Imperiales operan caminantes AT-DP y otros vehículos de asalto terrestre en mundos como Lothal en Star Wars Rebels, representando personal especializado del Ejército Imperial. Esta minifigura LEGO presenta distintivo uniforme gris y negro con insignia Imperial, casco cerrado con visor negro y equipo representando experiencia en operación de vehículos. Lanzada en 2014-2015 en sets incluyendo 75083 y 75078, los Conductores de Combate muestran fuerzas terrestres imperiales más allá de Stormtroopers estándar. Su papel pilotando caminantes y participación en la ocupación de Lothal hacen de esta minifigura útil para coleccionistas construyendo fuerzas militares imperiales diversas y exhibiciones del ejército imperial de la era Rebels.'
  },
  {
    no: 'sw0628',
    name: 'Stormtrooper (Rebels)',
    en: 'Stormtroopers serve as the Empire\'s primary infantry throughout Star Wars Rebels, enforcing Imperial rule on occupied worlds like Lothal and hunting the Ghost crew. This LEGO minifigure features the classic white armor with black details, helmet with characteristic design, and blaster rifle accessory representing Imperial military might. Released in 2014-2017 across numerous Rebels sets, Stormtroopers from this era show subtle design updates in LEGO\'s minifigure printing. Their ubiquitous presence as Imperial enforcers and role as primary antagonists make this minifigure essential for army builders creating Rebels-era Imperial forces and recreating battles from the series.',
    de: 'Sturmtruppler dienen in Star Wars Rebels als primäre Infanterie des Imperiums, setzen imperiale Herrschaft auf besetzten Welten wie Lothal durch und jagen die Ghost-Crew. Diese LEGO Minifigur zeigt die klassische weiße Rüstung mit schwarzen Details, Helm mit charakteristischem Design und Blastergewehr-Zubehör, das imperiale militärische Macht repräsentiert. Veröffentlicht 2014-2017 in zahlreichen Rebels-Sets, zeigen Sturmtruppler aus dieser Ära subtile Design-Updates in LEGOs Minifigur-Druck. Ihre allgegenwärtige Präsenz als imperiale Vollstrecker und Rolle als primäre Antagonisten machen diese Minifigur unverzichtbar für Army Builder, die Rebels-Ära-Imperiale-Kräfte erstellen und Schlachten aus der Serie nachstellen.',
    fr: 'Les Stormtroopers servent d\'infanterie principale de l\'Empire tout au long de Star Wars Rebels, imposant la domination impériale sur des mondes occupés comme Lothal et traquant l\'équipage du Ghost. Cette minifigurine LEGO présente l\'armure blanche classique avec détails noirs, casque au design caractéristique et accessoire de fusil blaster représentant la puissance militaire impériale. Sortie en 2014-2017 dans de nombreux sets Rebels, les Stormtroopers de cette époque montrent des mises à jour de design subtiles dans l\'impression des minifigurines LEGO. Leur présence omniprésente en tant qu\'exécuteurs impériaux et leur rôle d\'antagonistes principaux rendent cette minifigurine essentielle pour les constructeurs d\'armées créant des forces impériales de l\'ère Rebels et recréant des batailles de la série.',
    es: 'Los Stormtroopers sirven como la infantería principal del Imperio a lo largo de Star Wars Rebels, haciendo cumplir el dominio Imperial en mundos ocupados como Lothal y cazando a la tripulación del Fantasma. Esta minifigura LEGO presenta la clásica armadura blanca con detalles negros, casco con diseño característico y accesorio de rifle bláster representando el poder militar Imperial. Lanzada en 2014-2017 en numerosos sets de Rebels, los Stormtroopers de esta era muestran actualizaciones sutiles de diseño en la impresión de minifiguras de LEGO. Su presencia ubicua como ejecutores imperiales y papel como antagonistas principales hacen de esta minifigura esencial para constructores de ejércitos creando fuerzas imperiales de la era Rebels y recreando batallas de la serie.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 511-520 (sw0619-sw0628) - 10 minifigs...\n');

  for (const m of batch) {
    await prisma.minifigCatalog.upsert({
      where: { minifigure_no: m.no },
      update: {
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      },
      create: {
        minifigure_no: m.no,
        name: m.name,
        category_id: 1,
        category_name: 'Star Wars',
        search_name: m.name.toLowerCase(),
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`  ✅ ${m.no}: ${m.name}`);
  }

  console.log('\n✨ Batch 511-520 complete: 10 minifigs (40 descriptions)');
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
