import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0123',
    name: 'Darth Vader (Imperial Inspection)',
    en: 'Darth Vader Imperial Inspection represents the Dark Lord during his tour of the second Death Star construction in Return of the Jedi. This LEGO minifigure features Darth Vader in his iconic black armor with detailed torso printing, cape, and helmet design capturing his appearance inspecting Imperial installations. Released in 2005, this version shows Vader in his role as the Emperor\'s enforcer overseeing major Imperial projects. The Imperial Inspection designation makes this minifigure valuable for collectors recreating specific film scenes and building complete Death Star command displays with Vader in his administrative capacity.',
    de: 'Darth Vader Imperiale Inspektion repräsentiert den Dunklen Lord während seiner Tour durch den Bau des zweiten Todessterns in Die Rückkehr der Jedi-Ritter. Diese LEGO Minifigur zeigt Darth Vader in seiner ikonischen schwarzen Rüstung mit detailliertem Torso-Druck, Umhang und Helm-Design, das sein Aussehen bei der Inspektion imperialer Installationen einfängt. Veröffentlicht 2005, zeigt diese Version Vader in seiner Rolle als Vollstrecker des Imperators, der große imperiale Projekte überwacht. Die Imperiale Inspektion-Bezeichnung macht diese Minifigur wertvoll für Sammler, die spezifische Filmszenen nachstellen und vollständige Todesstern-Kommando-Displays mit Vader in seiner administrativen Kapazität aufbauen.',
    fr: 'Dark Vador Inspection Impériale représente le Seigneur Noir pendant sa visite de la construction de la seconde Étoile de la Mort dans Le Retour du Jedi. Cette minifigurine LEGO présente Dark Vador dans son armure noire emblématique avec impression de torse détaillée, cape et design de casque capturant son apparence inspectant les installations impériales. Sortie en 2005, cette version montre Vador dans son rôle d\'exécuteur de l\'Empereur supervisant les grands projets impériaux. La désignation Inspection Impériale rend cette minifigurine précieuse pour les collectionneurs recréant des scènes de film spécifiques et construisant des affichages complets de commandement de l\'Étoile de la Mort avec Vador dans sa capacité administrative.',
    es: 'Darth Vader Inspección Imperial representa al Señor Oscuro durante su gira por la construcción de la segunda Estrella de la Muerte en El Retorno del Jedi. Esta minifigura LEGO presenta a Darth Vader en su icónica armadura negra con impresión de torso detallada, capa y diseño de casco capturando su apariencia inspeccionando instalaciones imperiales. Lanzada en 2005, esta versión muestra a Vader en su papel como ejecutor del Emperador supervisando grandes proyectos imperiales. La designación de Inspección Imperial hace de esta minifigura valiosa para coleccionistas recreando escenas específicas de película y construyendo exhibiciones completas de comando de Estrella de la Muerte con Vader en su capacidad administrativa.'
  },
  {
    no: 'sw0124',
    name: 'Emperor Palpatine - Light Bluish Gray Head, Light Bluish Gray Hands',
    en: 'Emperor Palpatine with Light Bluish Gray Head and Hands represents the Dark Lord of the Sith with updated LEGO color standards for improved accuracy. This LEGO minifigure features Emperor Palpatine in black Sith robes with light bluish gray head and hands replacing earlier gray tones, wrinkled face printing, and the sinister appearance of Darth Sidious. Released in 2005, this version shows the Emperor with refined color matching modern LEGO palettes. The light bluish gray head and hands make this minifigure valuable for collectors seeking color-corrected Sith Lords and building updated throne room displays with consistent modern LEGO colors.',
    de: 'Imperator Palpatine mit hellbläulich-grauem Kopf und Händen repräsentiert den Dunklen Lord der Sith mit aktualisierten LEGO-Farbstandards für verbesserte Genauigkeit. Diese LEGO Minifigur zeigt Imperator Palpatine in schwarzen Sith-Roben mit hellbläulich-grauem Kopf und Händen, die frühere Grautöne ersetzen, faltigem Gesichts-Druck und dem finsteren Aussehen von Darth Sidious. Veröffentlicht 2005, zeigt diese Version den Imperator mit verfeinerter Farbe, die modernen LEGO-Paletten entspricht. Der hellbläulich-graue Kopf und Hände machen diese Minifigur wertvoll für Sammler, die farbkorrigierte Sith-Lords suchen und aktualisierte Thronsaal-Displays mit konsistenten modernen LEGO-Farben aufbauen.',
    fr: 'Empereur Palpatine avec Tête et Mains Gris Bleuté Clair représente le Seigneur Noir des Sith avec normes de couleur LEGO mises à jour pour une précision améliorée. Cette minifigurine LEGO présente l\'Empereur Palpatine dans des robes Sith noires avec tête et mains gris bleuté clair remplaçant les tons gris antérieurs, impression de visage ridé et l\'apparence sinistre de Dark Sidious. Sortie en 2005, cette version montre l\'Empereur avec couleur raffinée correspondant aux palettes LEGO modernes. La tête et les mains gris bleuté clair rendent cette minifigurine précieuse pour les collectionneurs recherchant des Seigneurs Sith corrigés en couleur et construisant des affichages de salle du trône mis à jour avec couleurs LEGO modernes cohérentes.',
    es: 'Emperador Palpatine con Cabeza y Manos Gris Azulado Claro representa al Señor Oscuro de los Sith con estándares de color LEGO actualizados para precisión mejorada. Esta minifigura LEGO presenta al Emperador Palpatine en túnicas Sith negras con cabeza y manos gris azulado claro reemplazando tonos grises anteriores, impresión de cara arrugada y la apariencia siniestra de Darth Sidious. Lanzada en 2005, esta versión muestra al Emperador con color refinado coincidiendo con paletas LEGO modernas. La cabeza y manos gris azulado claro hacen de esta minifigura valiosa para coleccionistas buscando Señores Sith corregidos en color y construyendo exhibiciones de sala del trono actualizadas con colores LEGO modernos consistentes.'
  },
  {
    no: 'sw0126',
    name: 'Clone Trooper (Phase 2) - Black Head, Continuous Mouth',
    en: 'Clone Trooper Phase 2 with Black Head and Continuous Mouth represents the Republic\'s elite soldiers during the later Clone Wars with updated armor design. This LEGO minifigure features black head piece, white Phase 2 armor with continuous mouth pattern helmet, and the refined armor worn during the final battles before Order 66. Released in 2005, this version captures clone troopers with the improved Phase 2 design featuring better visibility and communication systems. The continuous mouth pattern makes this minifigure valuable for collectors army-building late-war clone battalions and distinguishing between Phase 1 and Phase 2 armor variants.',
    de: 'Klonkrieger Phase 2 mit schwarzem Kopf und durchgehendem Mund repräsentiert die Elite-Soldaten der Republik während der späteren Klonkriege mit aktualisiertem Rüstungs-Design. Diese LEGO Minifigur zeigt schwarzes Kopfteil, weiße Phase-2-Rüstung mit durchgehendem Mund-Muster-Helm und die verfeinerte Rüstung, die während der finalen Schlachten vor Order 66 getragen wurde. Veröffentlicht 2005, fängt diese Version Klonkrieger mit dem verbesserten Phase-2-Design ein, das bessere Sichtbarkeit und Kommunikationssysteme bietet. Das durchgehende Mund-Muster macht diese Minifigur wertvoll für Sammler, die Klon-Bataillone aus dem späten Krieg für Armeen zusammenstellen und zwischen Phase-1- und Phase-2-Rüstungs-Varianten unterscheiden.',
    fr: 'Clone Trooper Phase 2 avec Tête Noire et Bouche Continue représente les soldats d\'élite de la République pendant les Guerres des Clones ultérieures avec design d\'armure mis à jour. Cette minifigurine LEGO présente une pièce de tête noire, une armure Phase 2 blanche avec casque à motif de bouche continue et l\'armure raffinée portée pendant les batailles finales avant l\'Ordre 66. Sortie en 2005, cette version capture les clone troopers avec le design Phase 2 amélioré offrant une meilleure visibilité et des systèmes de communication. Le motif de bouche continue rend cette minifigurine précieuse pour les collectionneurs assemblant des bataillons de clones de fin de guerre et distinguant entre les variantes d\'armure Phase 1 et Phase 2.',
    es: 'Soldado Clon Fase 2 con Cabeza Negra y Boca Continua representa a los soldados de élite de la República durante las Guerras Clon posteriores con diseño de armadura actualizado. Esta minifigura LEGO presenta pieza de cabeza negra, armadura Fase 2 blanca con casco de patrón de boca continua y la armadura refinada usada durante las batallas finales antes de la Orden 66. Lanzada en 2005, esta versión captura a soldados clon con el diseño Fase 2 mejorado presentando mejor visibilidad y sistemas de comunicación. El patrón de boca continua hace de esta minifigura valiosa para coleccionistas ensamblando batallones de clones de guerra tardía y distinguiendo entre variantes de armadura Fase 1 y Fase 2.'
  },
  {
    no: 'sw0128',
    name: 'Clone Trooper, 327th Star Corps (Phase 2) - Black Head, Orange Cloth Pauldron',
    en: 'Clone Trooper 327th Star Corps Phase 2 with Orange Cloth Pauldron represents the elite clone unit commanded by Jedi General Aayla Secura during the Clone Wars. This LEGO minifigure features black head, white Phase 2 armor with distinctive yellow/orange markings, and orange cloth pauldron shoulder accessory identifying 327th Star Corps troopers. Released in 2005 with Revenge of the Sith sets, this version captures the specialized unit that fought on Felucia and tragically executed Order 66 against their Jedi commander. The orange pauldron and unit markings make this minifigure extremely valuable for collectors building color-coded clone legions and recreating specific battalion displays.',
    de: 'Klonkrieger 327th Star Corps Phase 2 mit orangener Stoff-Schulterklappe repräsentiert die Elite-Klon-Einheit, die von Jedi-General Aayla Secura während der Klonkriege befehligt wurde. Diese LEGO Minifigur zeigt schwarzen Kopf, weiße Phase-2-Rüstung mit charakteristischen gelb-orangen Markierungen und orangene Stoff-Schulterklappe-Schulter-Zubehör, das 327th Star Corps-Krieger identifiziert. Veröffentlicht 2005 mit Die-Rache-der-Sith-Sets, fängt diese Version die spezialisierte Einheit ein, die auf Felucia kämpfte und tragisch Order 66 gegen ihren Jedi-Kommandeur ausführte. Die orangene Schulterklappe und Einheiten-Markierungen machen diese Minifigur extrem wertvoll für Sammler, die farbcodierte Klon-Legionen aufbauen und spezifische Bataillons-Displays nachstellen.',
    fr: 'Clone Trooper 327th Star Corps Phase 2 avec Épaulette en Tissu Orange représente l\'unité de clones d\'élite commandée par le Général Jedi Aayla Secura pendant les Guerres des Clones. Cette minifigurine LEGO présente une tête noire, une armure Phase 2 blanche avec marquages jaunes/oranges distinctifs et un accessoire d\'épaulette en tissu orange identifiant les troopers du 327th Star Corps. Sortie en 2005 avec les sets La Revanche des Sith, cette version capture l\'unité spécialisée qui a combattu sur Felucia et a tragiquement exécuté l\'Ordre 66 contre leur commandant Jedi. L\'épaulette orange et les marquages d\'unité rendent cette minifigurine extrêmement précieuse pour les collectionneurs construisant des légions de clones codées par couleur et recréant des affichages de bataillons spécifiques.',
    es: 'Soldado Clon 327th Star Corps Fase 2 con Hombrera de Tela Naranja representa a la unidad de clones de élite comandada por la General Jedi Aayla Secura durante las Guerras Clon. Esta minifigura LEGO presenta cabeza negra, armadura Fase 2 blanca con distintivas marcas amarillo/naranja y accesorio de hombrera de tela naranja identificando soldados del 327th Star Corps. Lanzada en 2005 con sets de La Venganza de los Sith, esta versión captura a la unidad especializada que luchó en Felucia y trágicamente ejecutó la Orden 66 contra su comandante Jedi. La hombrera naranja y marcas de unidad hacen de esta minifigura extremadamente valiosa para coleccionistas construyendo legiones de clones codificadas por color y recreando exhibiciones de batallones específicos.'
  },
  {
    no: 'sw0129',
    name: 'Clone Trooper, 442nd Siege Battalion (Phase 2) - Black Head',
    en: 'Clone Trooper 442nd Siege Battalion Phase 2 represents the specialized clone unit trained for siege warfare and urban combat during the Clone Wars. This LEGO minifigure features black head, white Phase 2 armor with distinctive green markings identifying the 442nd Siege Battalion, and specialized equipment. Released in 2005, this version captures the unit that specialized in breaking through fortified positions and conducting complex siege operations. The green battalion markings make this minifigure valuable for collectors building diverse clone army compositions and distinguishing between different specialized clone units by their color schemes.',
    de: 'Klonkrieger 442nd Siege Battalion Phase 2 repräsentiert die spezialisierte Klon-Einheit, die für Belagerungskrieg und Stadtkampf während der Klonkriege trainiert wurde. Diese LEGO Minifigur zeigt schwarzen Kopf, weiße Phase-2-Rüstung mit charakteristischen grünen Markierungen, die das 442nd Siege Battalion identifizieren, und spezialisierte Ausrüstung. Veröffentlicht 2005, fängt diese Version die Einheit ein, die sich auf das Durchbrechen befestigter Positionen und die Durchführung komplexer Belagerungsoperationen spezialisierte. Die grünen Bataillons-Markierungen machen diese Minifigur wertvoll für Sammler, die vielfältige Klon-Armee-Zusammensetzungen aufbauen und zwischen verschiedenen spezialisierten Klon-Einheiten anhand ihrer Farbschemata unterscheiden.',
    fr: 'Clone Trooper 442nd Siege Battalion Phase 2 représente l\'unité de clones spécialisée formée pour la guerre de siège et le combat urbain pendant les Guerres des Clones. Cette minifigurine LEGO présente une tête noire, une armure Phase 2 blanche avec marquages verts distinctifs identifiant le 442nd Siege Battalion et un équipement spécialisé. Sortie en 2005, cette version capture l\'unité spécialisée dans la percée de positions fortifiées et la conduite d\'opérations de siège complexes. Les marquages de bataillon verts rendent cette minifigurine précieuse pour les collectionneurs construisant des compositions d\'armée de clones diverses et distinguant entre différentes unités de clones spécialisées par leurs schémas de couleurs.',
    es: 'Soldado Clon 442nd Siege Battalion Fase 2 representa a la unidad de clones especializada entrenada para guerra de asedio y combate urbano durante las Guerras Clon. Esta minifigura LEGO presenta cabeza negra, armadura Fase 2 blanca con distintivas marcas verdes identificando al 442nd Siege Battalion y equipo especializado. Lanzada en 2005, esta versión captura a la unidad que se especializó en atravesar posiciones fortificadas y conducir operaciones de asedio complejas. Las marcas de batallón verdes hacen de esta minifigura valiosa para coleccionistas construyendo composiciones diversas de ejército de clones y distinguiendo entre diferentes unidades de clones especializadas por sus esquemas de color.'
  },
  {
    no: 'sw0130',
    name: 'Clone Trooper, 91st Mobile Reconnaissance Corps (Phase 2) - Black Head',
    en: 'Clone Trooper 91st Mobile Reconnaissance Corps Phase 2 represents the elite scout and reconnaissance unit commanded by Jedi Master Mace Windu during the Clone Wars. This LEGO minifigure features black head, white Phase 2 armor with distinctive purple/maroon markings identifying the 91st Reconnaissance Corps, and scout-specific equipment. Released in 2005, this version captures the specialized unit trained for reconnaissance missions and rapid deployment operations. The purple unit markings make this minifigure valuable for collectors building complete clone legion collections with proper color coding and representing units associated with specific Jedi commanders.',
    de: 'Klonkrieger 91st Mobile Reconnaissance Corps Phase 2 repräsentiert die Elite-Späher- und Aufklärungs-Einheit, die von Jedi-Meister Mace Windu während der Klonkriege befehligt wurde. Diese LEGO Minifigur zeigt schwarzen Kopf, weiße Phase-2-Rüstung mit charakteristischen lila/kastanienbraunen Markierungen, die das 91st Reconnaissance Corps identifizieren, und späher-spezifische Ausrüstung. Veröffentlicht 2005, fängt diese Version die spezialisierte Einheit ein, die für Aufklärungsmissionen und schnelle Einsatzoperationen trainiert wurde. Die lila Einheiten-Markierungen machen diese Minifigur wertvoll für Sammler, die vollständige Klon-Legions-Sammlungen mit ordnungsgemäßer Farbcodierung aufbauen und Einheiten repräsentieren, die mit spezifischen Jedi-Kommandeuren verbunden sind.',
    fr: 'Clone Trooper 91st Mobile Reconnaissance Corps Phase 2 représente l\'unité d\'élite d\'éclaireurs et de reconnaissance commandée par le Maître Jedi Mace Windu pendant les Guerres des Clones. Cette minifigurine LEGO présente une tête noire, une armure Phase 2 blanche avec marquages violets/marron distinctifs identifiant le 91st Reconnaissance Corps et un équipement spécifique aux éclaireurs. Sortie en 2005, cette version capture l\'unité spécialisée formée pour les missions de reconnaissance et les opérations de déploiement rapide. Les marquages d\'unité violets rendent cette minifigurine précieuse pour les collectionneurs construisant des collections complètes de légions de clones avec codage couleur approprié et représentant des unités associées à des commandants Jedi spécifiques.',
    es: 'Soldado Clon 91st Mobile Reconnaissance Corps Fase 2 representa a la unidad de élite de exploración y reconocimiento comandada por el Maestro Jedi Mace Windu durante las Guerras Clon. Esta minifigura LEGO presenta cabeza negra, armadura Fase 2 blanca con distintivas marcas púrpura/granate identificando al 91st Reconnaissance Corps y equipo específico de exploración. Lanzada en 2005, esta versión captura a la unidad especializada entrenada para misiones de reconocimiento y operaciones de despliegue rápido. Las marcas de unidad púrpura hacen de esta minifigura valiosa para coleccionistas construyendo colecciones completas de legiones de clones con codificación de color apropiada y representando unidades asociadas con comandantes Jedi específicos.'
  },
  {
    no: 'sw0131',
    name: 'Clone Scout Trooper Episode 3, \'Kashyyyk Trooper\'',
    en: 'Clone Scout Trooper Kashyyyk Trooper represents the specialized clone scouts who fought alongside Wookiees on Kashyyyk during the final battles of Revenge of the Sith. This LEGO minifigure features distinctive camouflage armor pattern adapted for jungle warfare, specialized helmet design, and green/brown markings. Released in 2005, this version captures the elite reconnaissance forces who operated in the forests of Kashyyyk before Order 66 was executed. The Kashyyyk camouflage pattern makes this minifigure extremely valuable for collectors seeking environment-specific clone variants and building Battle of Kashyyyk displays with authentic trooper designs.',
    de: 'Klon-Scout-Trooper Kashyyyk-Trooper repräsentiert die spezialisierten Klon-Späher, die während der finalen Schlachten von Die Rache der Sith an der Seite von Wookiees auf Kashyyyk kämpften. Diese LEGO Minifigur zeigt charakteristisches Tarnungs-Rüstungs-Muster, das für Dschungelkrieg angepasst ist, spezialisiertes Helm-Design und grün-braune Markierungen. Veröffentlicht 2005, fängt diese Version die Elite-Aufklärungsstreitkräfte ein, die in den Wäldern von Kashyyyk operierten, bevor Order 66 ausgeführt wurde. Das Kashyyyk-Tarnungs-Muster macht diese Minifigur extrem wertvoll für Sammler, die umgebungs-spezifische Klon-Varianten suchen und Schlacht-von-Kashyyyk-Displays mit authentischen Krieger-Designs aufbauen.',
    fr: 'Clone Scout Trooper Trooper Kashyyyk représente les éclaireurs clones spécialisés qui ont combattu aux côtés des Wookiees sur Kashyyyk pendant les batailles finales de La Revanche des Sith. Cette minifigurine LEGO présente un motif d\'armure de camouflage distinctif adapté pour la guerre dans la jungle, design de casque spécialisé et marquages verts/bruns. Sortie en 2005, cette version capture les forces de reconnaissance d\'élite qui ont opéré dans les forêts de Kashyyyk avant l\'exécution de l\'Ordre 66. Le motif de camouflage Kashyyyk rend cette minifigurine extrêmement précieuse pour les collectionneurs recherchant des variantes de clones spécifiques à l\'environnement et construisant des affichages de Bataille de Kashyyyk avec designs de troopers authentiques.',
    es: 'Soldado Clon Explorador Soldado Kashyyyk representa a los exploradores clon especializados quienes lucharon junto a Wookiees en Kashyyyk durante las batallas finales de La Venganza de los Sith. Esta minifigura LEGO presenta distintivo patrón de armadura de camuflaje adaptado para guerra de jungla, diseño de casco especializado y marcas verdes/marrones. Lanzada en 2005, esta versión captura a las fuerzas de reconocimiento de élite quienes operaron en los bosques de Kashyyyk antes de que se ejecutara la Orden 66. El patrón de camuflaje Kashyyyk hace de esta minifigura extremadamente valiosa para coleccionistas buscando variantes de clones específicas de ambiente y construyendo exhibiciones de Batalla de Kashyyyk con diseños de soldados auténticos.'
  },
  {
    no: 'sw0132',
    name: 'Wookiee Warrior - Reddish Brown, Plain Legs',
    en: 'Wookiee Warrior in Reddish Brown with Plain Legs represents the fierce defenders of Kashyyyk who fought alongside Republic clone forces during the Battle of Kashyyyk in Revenge of the Sith. This LEGO minifigure features reddish brown fur coloring, bandolier with ammunition pouches, plain legs, and distinctive Wookiee head design. Released in 2005 with Kashyyyk battle sets, this version captures the brave warriors who defended their homeworld during the Clone Wars. The reddish brown color and plain legs make this minifigure valuable for collectors army-building Wookiee defense forces and recreating the forest battle sequences from Episode III.',
    de: 'Wookiee-Krieger in Rotbraun mit einfachen Beinen repräsentiert die wilden Verteidiger von Kashyyyk, die während der Schlacht von Kashyyyk in Die Rache der Sith an der Seite von Republik-Klon-Streitkräften kämpften. Diese LEGO Minifigur zeigt rotbraune Fell-Färbung, Bandolier mit Munitionstaschen, einfache Beine und charakteristisches Wookiee-Kopf-Design. Veröffentlicht 2005 mit Kashyyyk-Schlacht-Sets, fängt diese Version die mutigen Krieger ein, die während der Klonkriege ihre Heimatwelt verteidigten. Die rotbraune Farbe und einfache Beine machen diese Minifigur wertvoll für Sammler, die Wookiee-Verteidigungsstreitkräfte für Armeen zusammenstellen und die Waldschlacht-Sequenzen aus Episode III nachstellen.',
    fr: 'Guerrier Wookiee en Brun Rougeâtre avec Jambes Simples représente les féroces défenseurs de Kashyyyk qui ont combattu aux côtés des forces clones de la République pendant la Bataille de Kashyyyk dans La Revanche des Sith. Cette minifigurine LEGO présente une coloration de fourrure brun rougeâtre, une bandoulière avec poches de munitions, des jambes simples et un design de tête Wookiee distinctif. Sortie en 2005 avec les sets de bataille de Kashyyyk, cette version capture les guerriers courageux qui ont défendu leur monde natal pendant les Guerres des Clones. La couleur brun rougeâtre et les jambes simples rendent cette minifigurine précieuse pour les collectionneurs assemblant des forces de défense Wookiee et recréant les séquences de bataille forestière de l\'Épisode III.',
    es: 'Guerrero Wookiee en Marrón Rojizo con Piernas Simples representa a los feroces defensores de Kashyyyk quienes lucharon junto a fuerzas clon de la República durante la Batalla de Kashyyyk en La Venganza de los Sith. Esta minifigura LEGO presenta coloración de pelaje marrón rojizo, bandolera con bolsas de munición, piernas simples y distintivo diseño de cabeza Wookiee. Lanzada en 2005 con sets de batalla de Kashyyyk, esta versión captura a los valientes guerreros quienes defendieron su mundo natal durante las Guerras Clon. El color marrón rojizo y piernas simples hacen de esta minifigura valiosa para coleccionistas ensamblando fuerzas de defensa Wookiee y recreando las secuencias de batalla de bosque del Episodio III.'
  },
  {
    no: 'sw0133',
    name: 'Mace Windu - Trans-Light Purple Light-Up Lightsaber',
    en: 'Mace Windu with Trans-Light Purple Light-Up Lightsaber represents the powerful Jedi Master and Council member with his unique purple blade and innovative light-up technology. This LEGO minifigure features Mace Windu with flesh-toned head, Jedi robes, and distinctive transparent light purple lightsaber with integrated light-up mechanism. Released in 2005 with premium sets, this version captures the only Jedi who wielded a purple lightsaber with the special play feature. The trans-light purple light-up lightsaber makes this minifigure extremely valuable as a special edition release and highly sought after for representing one of the most powerful Jedi Masters in the prequel trilogy.',
    de: 'Mace Windu mit trans-helllila Leucht-Lichtschwert repräsentiert den mächtigen Jedi-Meister und Rats-Mitglied mit seiner einzigartigen lila Klinge und innovativer Leucht-Technologie. Diese LEGO Minifigur zeigt Mace Windu mit fleischfarbenem Kopf, Jedi-Roben und charakteristischem transparenten helllila Lichtschwert mit integriertem Leucht-Mechanismus. Veröffentlicht 2005 mit Premium-Sets, fängt diese Version den einzigen Jedi ein, der ein lila Lichtschwert führte, mit der speziellen Spiel-Funktion. Das trans-helllila Leucht-Lichtschwert macht diese Minifigur extrem wertvoll als Sonderausgabe-Veröffentlichung und sehr begehrt für die Darstellung eines der mächtigsten Jedi-Meister in der Prequel-Trilogie.',
    fr: 'Mace Windu avec Sabre Laser Lumineux Trans-Violet Clair représente le puissant Maître Jedi et membre du Conseil avec sa lame violette unique et sa technologie lumineuse innovante. Cette minifigurine LEGO présente Mace Windu avec tête de couleur chair, robes Jedi et sabre laser violet clair transparent distinctif avec mécanisme lumineux intégré. Sortie en 2005 avec des sets premium, cette version capture le seul Jedi qui a manié un sabre laser violet avec la fonction de jeu spéciale. Le sabre laser lumineux trans-violet clair rend cette minifigurine extrêmement précieuse comme sortie en édition spéciale et très recherchée pour représenter l\'un des Maîtres Jedi les plus puissants de la trilogie préquelle.',
    es: 'Mace Windu con Sable de Luz Iluminado Trans-Púrpura Claro representa al poderoso Maestro Jedi y miembro del Consejo con su hoja púrpura única y tecnología de iluminación innovadora. Esta minifigura LEGO presenta a Mace Windu con cabeza de tono de piel, túnicas Jedi y distintivo sable de luz púrpura claro transparente con mecanismo de iluminación integrado. Lanzada en 2005 con sets premium, esta versión captura al único Jedi quien empuñó un sable de luz púrpura con la característica de juego especial. El sable de luz iluminado trans-púrpura claro hace de esta minifigura extremadamente valiosa como lanzamiento de edición especial y muy buscada por representar a uno de los Maestros Jedi más poderosos en la trilogía de precuelas.'
  },
  {
    no: 'sw0134',
    name: 'General Grievous - Straight Legs, Cape',
    en: 'General Grievous with Straight Legs and Cape represents the fearsome cyborg Supreme Commander of the Separatist Droid Army who collected Jedi lightsabers as trophies. This LEGO minifigure features Grievous with distinctive white armor plates, mechanical body construction, straight leg pieces, cape accessory, and unique head design. Released in 2005 with Revenge of the Sith sets, this version captures the deadly cyborg general who wielded four lightsabers and served as Count Dooku\'s successor. The straight legs and cape design make this minifigure valuable for collectors seeking the early General Grievous releases and building Separatist command displays with one of the most dangerous villains from the prequel era.',
    de: 'General Grievous mit geraden Beinen und Umhang repräsentiert den furchterregenden Cyborg-Oberkommandanten der Separatisten-Droiden-Armee, der Jedi-Lichtschwerter als Trophäen sammelte. Diese LEGO Minifigur zeigt Grievous mit charakteristischen weißen Rüstungsplatten, mechanischer Körper-Konstruktion, geraden Beinteilen, Umhang-Zubehör und einzigartigem Kopf-Design. Veröffentlicht 2005 mit Die-Rache-der-Sith-Sets, fängt diese Version den tödlichen Cyborg-General ein, der vier Lichtschwerter führte und als Graf Dookus Nachfolger diente. Die geraden Beine und das Umhang-Design machen diese Minifigur wertvoll für Sammler, die die frühen General Grievous-Veröffentlichungen suchen und Separatisten-Kommando-Displays mit einem der gefährlichsten Bösewichte aus der Prequel-Ära aufbauen.',
    fr: 'Général Grievous avec Jambes Droites et Cape représente le redoutable cyborg Commandant Suprême de l\'Armée Droïde Séparatiste qui collectionnait les sabres laser Jedi comme trophées. Cette minifigurine LEGO présente Grievous avec plaques d\'armure blanches distinctives, construction de corps mécanique, pièces de jambes droites, accessoire de cape et design de tête unique. Sortie en 2005 avec les sets La Revanche des Sith, cette version capture le général cyborg mortel qui maniait quatre sabres laser et servait comme successeur du Comte Dooku. Le design de jambes droites et cape rend cette minifigurine précieuse pour les collectionneurs recherchant les premières sorties du Général Grievous et construisant des affichages de commandement séparatiste avec l\'un des méchants les plus dangereux de l\'ère préquelle.',
    es: 'General Grievous con Piernas Rectas y Capa representa al temible cyborg Comandante Supremo del Ejército Droide Separatista quien coleccionó sables de luz Jedi como trofeos. Esta minifigura LEGO presenta a Grievous con distintivas placas de armadura blancas, construcción de cuerpo mecánico, piezas de piernas rectas, accesorio de capa y diseño de cabeza único. Lanzada en 2005 con sets de La Venganza de los Sith, esta versión captura al general cyborg mortal quien empuñó cuatro sables de luz y sirvió como sucesor del Conde Dooku. El diseño de piernas rectas y capa hacen de esta minifigura valiosa para coleccionistas buscando los lanzamientos tempranos del General Grievous y construyendo exhibiciones de comando separatista con uno de los villanos más peligrosos de la era de precuelas.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 013 (sw0123-sw0134) - 10 minifigs...\n');

  for (const m of batch) {
    try {
      await prisma.minifigCatalog.update({
        where: { minifigure_no: m.no },
        data: {
          description_en: m.en,
          description_de: m.de,
          description_fr: m.fr,
          description_es: m.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        }
      });
      console.log(`  ✅ ${m.no}: ${m.name}`);
    } catch (error: any) {
      console.log(`  ⚠️  ${m.no}: NOT IN DATABASE (skipped)`);
    }
  }

  console.log('\n✨ Batch 013 complete: 10 minifigs (40 descriptions)');
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
