import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch032 = [
  {
    no: 'sw0248',
    name: 'Mon Calamari Officer',
    en: 'The Mon Calamari Officer represents the aquatic species that provides crucial military leadership and starship engineering expertise to the Rebel Alliance. Released in 2009, this minifigure features distinctive salmon-colored skin with large eyes characteristic of Mon Calamari physiology, along with Rebel officer uniform printing. Mon Calamari contributed some of the Rebellion\'s most advanced capital ships, including the iconic Mon Calamari cruisers that formed the backbone of the Rebel fleet. Their technical expertise and commitment to freedom made them invaluable allies against Imperial tyranny. Essential for Rebel fleet displays and command center recreations, this generic Mon Calamari officer adds species diversity to Rebel military forces, representing the multi-species coalition that opposed the human-centric Empire.',
    de: 'Der Mon Calamari Officer repräsentiert die aquatische Spezies, die entscheidende militärische Führung und Raumschiff-Engineering-Expertise für die Rebellen-Allianz bereitstellt. Diese 2009 veröffentlichte Minifigur zeigt charakteristische lachsfarbene Haut mit großen Augen, die für die Mon Calamari-Physiologie typisch sind, zusammen mit Rebellen-Offiziers-Uniform-Druck. Mon Calamari trugen einige der fortschrittlichsten Hauptschiffe der Rebellion bei, einschließlich der ikonischen Mon Calamari-Kreuzer, die das Rückgrat der Rebellenflotte bildeten. Ihre technische Expertise und ihr Engagement für Freiheit machten sie zu unschätzbaren Verbündeten gegen imperiale Tyrannei. Unverzichtbar für Rebellenflotten-Displays und Kommandozentren-Nachstellungen fügt dieser generische Mon Calamari-Offizier Spezies-Vielfalt zu Rebellen-Militärkräften hinzu und repräsentiert die Multi-Spezies-Koalition, die sich dem menschen-zentrischen Imperium widersetzte.',
    fr: 'L\'Officier Mon Calamari représente l\'espèce aquatique qui fournit un leadership militaire crucial et une expertise en ingénierie de vaisseaux spatiaux à l\'Alliance Rebelle. Sortie en 2009, cette minifigurine présente une peau saumon distinctive avec de grands yeux caractéristiques de la physiologie Mon Calamari, avec une impression d\'uniforme d\'officier rebelle. Les Mon Calamari ont contribué certains des vaisseaux capitaux les plus avancés de la Rébellion, y compris les croiseurs Mon Calamari iconiques qui formaient l\'épine dorsale de la flotte rebelle. Leur expertise technique et leur engagement envers la liberté en ont fait des alliés inestimables contre la tyrannie impériale. Essentiel pour les displays de flotte rebelle et les recréations de centre de commandement, cet officier Mon Calamari générique ajoute une diversité d\'espèces aux forces militaires rebelles, représentant la coalition multi-espèces qui s\'opposait à l\'Empire centré sur l\'humain.',
    es: 'El Oficial Mon Calamari representa la especie acuática que proporciona liderazgo militar crucial y experiencia en ingeniería de naves espaciales a la Alianza Rebelde. Lanzada en 2009, esta minifigura presenta distintiva piel color salmón con ojos grandes característicos de la fisiología Mon Calamari, junto con impresión de uniforme de oficial Rebelde. Los Mon Calamari contribuyeron algunas de las naves capitales más avanzadas de la Rebelión, incluyendo los icónicos cruceros Mon Calamari que formaron la columna vertebral de la flota Rebelde. Su experiencia técnica y compromiso con la libertad los hicieron aliados invaluables contra la tiranía Imperial. Esencial para displays de flota Rebelde y recreaciones de centro de comando, este oficial Mon Calamari genérico añade diversidad de especies a fuerzas militares Rebeldes, representando la coalición multi-especies que se opuso al Imperio centrado en humanos.'
  },
  {
    no: 'sw0249',
    name: 'Mon Mothma',
    en: 'Mon Mothma appears as the dignified leader of the Rebel Alliance and founder of the organized Rebellion against the Empire. Released in 2009, this minifigure captures the former Senator\'s elegant white robes and calm leadership presence with detailed printing. As Chief of State for the Alliance, Mon Mothma provides political legitimacy and strategic vision that transforms scattered resistance cells into a unified military force. Her famous briefing before the Battle of Endor demonstrates her role as inspirational leader coordinating the Rebellion\'s most crucial operation. Essential for Rebel command displays and Return of the Jedi recreations, Mon Mothma represents the political heart of the Rebellion, showing that the fight against tyranny required both military force and moral leadership to succeed.',
    de: 'Mon Mothma erscheint als würdevolle Anführerin der Rebellen-Allianz und Gründerin der organisierten Rebellion gegen das Imperium. Diese 2009 veröffentlichte Minifigur zeigt die eleganten weißen Roben der ehemaligen Senatorin und ruhige Führungspräsenz mit detailliertem Druck. Als Staatschefin der Allianz bietet Mon Mothma politische Legitimität und strategische Vision, die verstreute Widerstandszellen in eine vereinte Militärkraft verwandelt. Ihr berühmtes Briefing vor der Schlacht von Endor demonstriert ihre Rolle als inspirierende Anführerin, die die entscheidendste Operation der Rebellion koordiniert. Unverzichtbar für Rebellen-Kommando-Displays und Rückkehr-der-Jedi-Nachstellungen repräsentiert Mon Mothma das politische Herz der Rebellion und zeigt, dass der Kampf gegen Tyrannei sowohl militärische Kraft als auch moralische Führung zum Erfolg benötigte.',
    fr: 'Mon Mothma apparaît comme la leader digne de l\'Alliance Rebelle et fondatrice de la Rébellion organisée contre l\'Empire. Sortie en 2009, cette minifigurine capture les robes blanches élégantes de l\'ancienne Sénatrice et sa présence de leadership calme avec impression détaillée. En tant que Chef d\'État pour l\'Alliance, Mon Mothma fournit une légitimité politique et une vision stratégique qui transforme les cellules de résistance dispersées en une force militaire unifiée. Son briefing célèbre avant la Bataille d\'Endor démontre son rôle de leader inspirante coordonnant l\'opération la plus cruciale de la Rébellion. Essentielle pour les displays de commandement rebelle et les recréations du Retour du Jedi, Mon Mothma représente le cœur politique de la Rébellion, montrant que la lutte contre la tyrannie nécessitait à la fois une force militaire et un leadership moral pour réussir.',
    es: 'Mon Mothma aparece como la digna líder de la Alianza Rebelde y fundadora de la Rebelión organizada contra el Imperio. Lanzada en 2009, esta minifigura captura las elegantes túnicas blancas de la ex Senadora y presencia de liderazgo calmado con impresión detallada. Como Jefa de Estado para la Alianza, Mon Mothma proporciona legitimidad política y visión estratégica que transforma células de resistencia dispersas en una fuerza militar unificada. Su famoso briefing antes de la Batalla de Endor demuestra su rol como líder inspiradora coordinando la operación más crucial de la Rebelión. Esencial para displays de comando Rebelde y recreaciones de El Retorno del Jedi, Mon Mothma representa el corazón político de la Rebelión, mostrando que la lucha contra la tiranía requería tanto fuerza militar como liderazgo moral para tener éxito.'
  },
  {
    no: 'sw0250',
    name: 'Crix Madine, Dark Tan Hips and Legs',
    en: 'General Crix Madine appears with dark tan legs and distinctive beard representing the former Imperial officer who defected to the Rebellion. Released in 2009, this minifigure captures the Rebel special forces commander responsible for planning the crucial Endor ground assault mission. As a defector with inside knowledge of Imperial tactics and procedures, Madine brings valuable strategic expertise to the Rebel Alliance. His background demonstrates that conscience could overcome Imperial indoctrination, with some officers choosing freedom over tyranny. Essential for Rebel command displays and Battle of Endor briefing recreations, General Madine represents the Imperial defectors whose knowledge and courage helped turn the tide against the Empire, showing that redemption remained possible even for those who initially served the dark side.',
    de: 'General Crix Madine erscheint mit dunkelbraunen Beinen und charakteristischem Bart und repräsentiert den ehemaligen imperialen Offizier, der zur Rebellion überlief. Diese 2009 veröffentlichte Minifigur zeigt den Rebellen-Spezialeinheiten-Kommandeur, der für die Planung der entscheidenden Endor-Bodenangriffs-Mission verantwortlich ist. Als Überläufer mit Insider-Wissen über imperiale Taktiken und Verfahren bringt Madine wertvolle strategische Expertise zur Rebellen-Allianz. Sein Hintergrund demonstriert, dass Gewissen imperiale Indoktrination überwinden konnte, wobei einige Offiziere Freiheit über Tyrannei wählten. Unverzichtbar für Rebellen-Kommando-Displays und Schlacht-von-Endor-Briefing-Nachstellungen repräsentiert General Madine die imperialen Überläufer, deren Wissen und Mut halfen, das Blatt gegen das Imperium zu wenden und zeigt, dass Erlösung selbst für diejenigen möglich blieb, die zunächst der dunklen Seite dienten.',
    fr: 'Le Général Crix Madine apparaît avec jambes beige foncé et barbe distinctive représentant l\'ancien officier impérial qui a fait défection vers la Rébellion. Sortie en 2009, cette minifigurine capture le commandant des forces spéciales rebelles responsable de la planification de la mission cruciale d\'assaut au sol d\'Endor. En tant que transfuge avec une connaissance interne des tactiques et procédures impériales, Madine apporte une expertise stratégique précieuse à l\'Alliance Rebelle. Son parcours démontre que la conscience pouvait surmonter l\'endoctrinement impérial, avec certains officiers choisissant la liberté plutôt que la tyrannie. Essentiel pour les displays de commandement rebelle et les recréations de briefing de la Bataille d\'Endor, le Général Madine représente les transfuges impériaux dont la connaissance et le courage ont aidé à renverser la vapeur contre l\'Empire, montrant que la rédemption restait possible même pour ceux qui ont initialement servi le côté obscur.',
    es: 'El General Crix Madine aparece con piernas beige oscuro y distintiva barba representando al ex oficial Imperial que desertó a la Rebelión. Lanzada en 2009, esta minifigura captura al comandante de fuerzas especiales Rebeldes responsable de planear la crucial misión de asalto terrestre de Endor. Como desertor con conocimiento interno de tácticas y procedimientos Imperiales, Madine aporta valiosa experiencia estratégica a la Alianza Rebelde. Su trasfondo demuestra que la conciencia podía superar el adoctrinamiento Imperial, con algunos oficiales eligiendo libertad sobre tiranía. Esencial para displays de comando Rebelde y recreaciones de briefing de Batalla de Endor, el General Madine representa los desertores Imperiales cuyo conocimiento y coraje ayudaron a cambiar el rumbo contra el Imperio, mostrando que la redención permanecía posible incluso para quienes inicialmente sirvieron al lado oscuro.'
  },
  {
    no: 'sw0251',
    name: 'Lando Calrissian - General Insignia (Sand Blue Legs)',
    en: 'Lando Calrissian appears in Rebel General uniform with general insignia and sand blue legs representing his promotion to military leadership during the Battle of Endor. Released in 2009, this minifigure captures the former smuggler and Cloud City administrator turned Rebel hero with detailed military uniform printing. Lando\'s journey from self-interested opportunist to selfless military leader demonstrates the Rebellion\'s transformative power. As General, he commands the Millennium Falcon during the crucial assault on the Death Star II, piloting his old ship through the battle station\'s superstructure to deliver the final blow. Essential for Battle of Endor displays and Rebel fleet recreations, General Lando represents redemption and growth, showing how ordinary people could rise to become extraordinary heroes in the fight against tyranny.',
    de: 'Lando Calrissian erscheint in Rebellen-General-Uniform mit General-Insignien und sandblauen Beinen und repräsentiert seine Beförderung zur militärischen Führung während der Schlacht von Endor. Diese 2009 veröffentlichte Minifigur zeigt den ehemaligen Schmuggler und Cloud City-Administrator, der zum Rebellen-Helden wurde, mit detailliertem Militäruniform-Druck. Landos Reise vom eigeninteressierten Opportunisten zum selbstlosen Militärführer demonstriert die transformative Kraft der Rebellion. Als General kommandiert er den Millennium Falcon während des entscheidenden Angriffs auf den Todesstern II und steuert sein altes Schiff durch die Superstruktur der Kampfstation, um den finalen Schlag zu liefern. Unverzichtbar für Schlacht-von-Endor-Displays und Rebellenflotten-Nachstellungen repräsentiert General Lando Erlösung und Wachstum und zeigt, wie gewöhnliche Menschen zu außergewöhnlichen Helden im Kampf gegen Tyrannei aufsteigen konnten.',
    fr: 'Lando Calrissian apparaît en uniforme de Général Rebelle avec insignes de général et jambes bleu sable représentant sa promotion au leadership militaire pendant la Bataille d\'Endor. Sortie en 2009, cette minifigurine capture l\'ancien contrebandier et administrateur de Cloud City devenu héros rebelle avec impression d\'uniforme militaire détaillée. Le parcours de Lando d\'opportuniste intéressé à leader militaire désintéressé démontre le pouvoir transformateur de la Rébellion. En tant que Général, il commande le Faucon Millenium pendant l\'assaut crucial sur l\'Étoile de la Mort II, pilotant son ancien vaisseau à travers la superstructure de la station de combat pour porter le coup final. Essentiel pour les displays de la Bataille d\'Endor et les recréations de flotte rebelle, le Général Lando représente la rédemption et la croissance, montrant comment des gens ordinaires pouvaient devenir des héros extraordinaires dans la lutte contre la tyrannie.',
    es: 'Lando Calrissian aparece en uniforme de General Rebelde con insignias de general y piernas azul arena representando su promoción a liderazgo militar durante la Batalla de Endor. Lanzada en 2009, esta minifigura captura al ex contrabandista y administrador de Ciudad Nube convertido en héroe Rebelde con impresión detallada de uniforme militar. El viaje de Lando de oportunista interesado a líder militar desinteresado demuestra el poder transformador de la Rebelión. Como General, comanda el Halcón Milenario durante el asalto crucial a la Estrella de la Muerte II, pilotando su vieja nave a través de la superestructura de la estación de batalla para entregar el golpe final. Esencial para displays de Batalla de Endor y recreaciones de flota Rebelde, el General Lando representa redención y crecimiento, mostrando cómo personas ordinarias podían convertirse en héroes extraordinarios en la lucha contra la tiranía.'
  },
  {
    no: 'sw0005a',
    name: 'Imperial Scout Trooper - Plain Black Head, Dark Bluish Gray Torso Print',
    en: 'The Imperial Scout Trooper with plain black head and dark bluish gray torso print represents the specialized reconnaissance forces deployed on Endor and other frontier worlds. Released in 2009, this variant features updated printing details while maintaining the distinctive scout trooper armor design optimized for speeder bike operations. Scout troopers handle reconnaissance, perimeter security, and rapid response missions requiring high mobility. Their lighter armor compared to standard Stormtroopers allows greater agility for speeder bike operations. The plain black head distinguishes this production variant from other scout trooper versions. Essential for Endor battle recreations and speeder bike displays, this scout trooper represents the Empire\'s specialized forces adapted for specific tactical roles beyond standard infantry operations.',
    de: 'Der Imperial Scout Trooper mit einfachem schwarzem Kopf und dunkelblaugrauem Torso-Druck repräsentiert die spezialisierten Aufklärungskräfte, die auf Endor und anderen Grenzwelten eingesetzt werden. Diese 2009 veröffentlichte Variante zeigt aktualisierte Druckdetails, während das charakteristische Scout-Trooper-Rüstungsdesign beibehalten wird, das für Schwebegleiter-Operationen optimiert ist. Scout Troopers übernehmen Aufklärung, Perimetersicherheit und schnelle Reaktionsmissionen, die hohe Mobilität erfordern. Ihre leichtere Rüstung im Vergleich zu Standard-Stormtroopern ermöglicht größere Agilität für Schwebegleiter-Operationen. Der einfache schwarze Kopf unterscheidet diese Produktionsvariante von anderen Scout-Trooper-Versionen. Unverzichtbar für Endor-Schlacht-Nachstellungen und Schwebegleiter-Displays repräsentiert dieser Scout Trooper die spezialisierten Kräfte des Imperiums, die für spezifische taktische Rollen jenseits von Standard-Infanterie-Operationen angepasst wurden.',
    fr: 'Le Scout Trooper Impérial avec tête noire simple et impression de torse gris bleuté foncé représente les forces de reconnaissance spécialisées déployées sur Endor et d\'autres mondes frontières. Sortie en 2009, cette variante présente des détails d\'impression mis à jour tout en maintenant le design d\'armure de scout trooper distinctif optimisé pour les opérations de moto speeder. Les scout troopers gèrent la reconnaissance, la sécurité périmétrique et les missions de réponse rapide nécessitant une grande mobilité. Leur armure plus légère par rapport aux Stormtroopers standard permet une plus grande agilité pour les opérations de moto speeder. La tête noire simple distingue cette variante de production des autres versions de scout trooper. Essentiel pour les recréations de bataille d\'Endor et les displays de moto speeder, ce scout trooper représente les forces spécialisées de l\'Empire adaptées pour des rôles tactiques spécifiques au-delà des opérations d\'infanterie standard.',
    es: 'El Scout Trooper Imperial con cabeza negra simple e impresión de torso gris azulado oscuro representa las fuerzas de reconocimiento especializadas desplegadas en Endor y otros mundos fronterizos. Lanzada en 2009, esta variante presenta detalles de impresión actualizados mientras mantiene el distintivo diseño de armadura scout trooper optimizado para operaciones de moto speeder. Los scout troopers manejan reconocimiento, seguridad perimetral y misiones de respuesta rápida requiriendo alta movilidad. Su armadura más ligera comparada con Stormtroopers estándar permite mayor agilidad para operaciones de moto speeder. La cabeza negra simple distingue esta variante de producción de otras versiones scout trooper. Esencial para recreaciones de batalla de Endor y displays de moto speeder, este scout trooper representa las fuerzas especializadas del Imperio adaptadas para roles tácticos específicos más allá de operaciones de infantería estándar.'
  },
  {
    no: 'sw0252',
    name: 'Hoth Rebel - Light Nougat Head, White Visor Snow Goggles',
    en: 'The Hoth Rebel with light nougat head and white visor snow goggles represents the brave soldiers defending Echo Base during the Imperial assault on Hoth. Released in 2009, this minifigure features distinctive cold weather gear with insulated suit and protective goggles necessary for surviving Hoth\'s frozen environment. These Rebel troops operated defensive positions, manned snowspeeders, and evacuated personnel during the desperate battle to hold the Imperial advance. The snow goggles and thermal suit reflect the harsh conditions Rebels endured while establishing secret bases far from Imperial reach. Essential for Battle of Hoth recreations and Echo Base displays, this Hoth trooper represents the Rebellion\'s resilience and determination, showing their willingness to fight from the galaxy\'s harshest environments in their struggle against tyranny.',
    de: 'Der Hoth Rebel mit hellnougat Kopf und weißer Visier-Schneebrille repräsentiert die mutigen Soldaten, die Echo Base während des imperialen Angriffs auf Hoth verteidigen. Diese 2009 veröffentlichte Minifigur zeigt charakteristische Kälteschutzausrüstung mit isoliertem Anzug und Schutzbrille, die für das Überleben in Hoths gefrorener Umgebung notwendig sind. Diese Rebellen-Truppen bedienten Verteidigungspositionen, bemannten Schneegleiter und evakuierten Personal während der verzweifelten Schlacht, um den imperialen Vormarsch aufzuhalten. Die Schneebrille und der Thermalanzug spiegeln die harschen Bedingungen wider, die Rebellen ertrugen, während sie geheime Basen weit außerhalb imperialer Reichweite errichteten. Unverzichtbar für Schlacht-von-Hoth-Nachstellungen und Echo-Base-Displays repräsentiert dieser Hoth-Soldat die Widerstandsfähigkeit und Entschlossenheit der Rebellion und zeigt ihre Bereitschaft, aus den härtesten Umgebungen der Galaxie in ihrem Kampf gegen Tyrannei zu kämpfen.',
    fr: 'Le Rebelle Hoth avec tête nougat clair et lunettes de neige à visière blanche représente les soldats courageux défendant Echo Base pendant l\'assaut impérial sur Hoth. Sortie en 2009, cette minifigurine présente un équipement de temps froid distinctif avec combinaison isolée et lunettes de protection nécessaires pour survivre à l\'environnement gelé de Hoth. Ces troupes rebelles opéraient des positions défensives, pilotaient des snowspeeders et évacuaient le personnel pendant la bataille désespérée pour tenir l\'avance impériale. Les lunettes de neige et la combinaison thermique reflètent les conditions difficiles que les Rebelles ont endurées en établissant des bases secrètes loin de la portée impériale. Essentiel pour les recréations de la Bataille de Hoth et les displays d\'Echo Base, ce soldat Hoth représente la résilience et la détermination de la Rébellion, montrant leur volonté de combattre depuis les environnements les plus difficiles de la galaxie dans leur lutte contre la tyrannie.',
    es: 'El Rebelde Hoth con cabeza color nougat claro y gafas de nieve de visor blanco representa los valientes soldados defendiendo Base Echo durante el asalto Imperial en Hoth. Lanzada en 2009, esta minifigura presenta distintivo equipo de clima frío con traje aislado y gafas protectoras necesarias para sobrevivir al ambiente congelado de Hoth. Estas tropas Rebeldes operaban posiciones defensivas, tripulaban snowspeeders y evacuaban personal durante la desesperada batalla para detener el avance Imperial. Las gafas de nieve y traje térmico reflejan las duras condiciones que Rebeldes soportaron mientras establecían bases secretas lejos del alcance Imperial. Esencial para recreaciones de Batalla de Hoth y displays de Base Echo, este soldado Hoth representa la resiliencia y determinación de la Rebelión, mostrando su disposición a luchar desde los ambientes más duros de la galaxia en su lucha contra la tiranía.'
  },
  {
    no: 'sw0253',
    name: 'Han Solo - Light Nougat, Parka Hood, Tan Legs with Holster',
    en: 'Han Solo appears in Hoth cold weather gear with light nougat flesh tone, parka hood, and tan legs with holster printing. Released in 2009, this minifigure captures Han during the Battle of Hoth and his desperate search for Luke on the frozen wastes. The distinctive parka and cold weather equipment reflect the harsh conditions on Hoth where Han demonstrates his loyalty by risking his life to save Luke from freezing. This variant represents a pivotal character moment showing Han\'s evolution from self-interested smuggler to devoted friend willing to sacrifice for others. Essential for Empire Strikes Back recreations and Hoth battle displays, this cold weather Han Solo figure remains iconic for representing one of the trilogy\'s most heroic moments of friendship and courage.',
    de: 'Han Solo erscheint in Hoth-Kälteschutzausrüstung mit hellnougat Hautton, Parka-Kapuze und hellbraunen Beinen mit Holster-Druck. Diese 2009 veröffentlichte Minifigur zeigt Han während der Schlacht von Hoth und seiner verzweifelten Suche nach Luke in der gefrorenen Einöde. Der charakteristische Parka und die Kälteschutzausrüstung spiegeln die harschen Bedingungen auf Hoth wider, wo Han seine Loyalität demonstriert, indem er sein Leben riskiert, um Luke vor dem Erfrieren zu retten. Diese Variante repräsentiert einen entscheidenden Charaktermoment, der Hans Entwicklung vom eigeninteressierten Schmuggler zum hingebungsvollen Freund zeigt, der bereit ist, sich für andere zu opfern. Unverzichtbar für Das Imperium schlägt zurück-Nachstellungen und Hoth-Schlacht-Displays bleibt diese Kälteschutz-Han-Solo-Figur ikonisch für die Darstellung eines der heroischsten Momente von Freundschaft und Mut der Trilogie.',
    fr: 'Han Solo apparaît en équipement de temps froid Hoth avec teint chair nougat clair, capuche de parka et jambes beige avec impression d\'étui. Sortie en 2009, cette minifigurine capture Han pendant la Bataille de Hoth et sa recherche désespérée de Luke dans les étendues gelées. Le parka distinctif et l\'équipement de temps froid reflètent les conditions difficiles sur Hoth où Han démontre sa loyauté en risquant sa vie pour sauver Luke du gel. Cette variante représente un moment de personnage pivot montrant l\'évolution de Han de contrebandier intéressé à ami dévoué prêt à se sacrifier pour les autres. Essentielle pour les recréations de L\'Empire contre-attaque et les displays de bataille Hoth, cette figurine Han Solo par temps froid reste iconique pour représenter l\'un des moments d\'amitié et de courage les plus héroïques de la trilogie.',
    es: 'Han Solo aparece en equipo de clima frío Hoth con tono de piel color nougat claro, capucha de parka y piernas beige con impresión de pistolera. Lanzada en 2009, esta minifigura captura a Han durante la Batalla de Hoth y su desesperada búsqueda de Luke en los páramos congelados. La distintiva parka y equipo de clima frío reflejan las duras condiciones en Hoth donde Han demuestra su lealtad arriesgando su vida para salvar a Luke de congelarse. Esta variante representa un momento crucial del personaje mostrando la evolución de Han de contrabandista interesado a amigo devoto dispuesto a sacrificarse por otros. Esencial para recreaciones de El Imperio Contraataca y displays de batalla Hoth, esta figura Han Solo de clima frío permanece icónica por representar uno de los momentos más heroicos de amistad y coraje de la trilogía.'
  },
  {
    no: 'sw0097',
    name: 'Imperial Stormtrooper - Chrome Silver',
    en: 'This chrome silver Imperial Stormtrooper represents one of the most exclusive promotional LEGO Star Wars minifigures ever produced. Released in 2009 through extremely limited distribution channels, this figure features reflective chrome silver plating covering the entire stormtrooper armor, creating a stunning metallic appearance. The chrome finish transforms the standard trooper into an ultra-premium collector piece with mirror-like surface quality. Distributed in very small quantities through special promotions and events, this chrome stormtrooper has become one of the holy grail figures for serious LEGO Star Wars collectors. The rarity and distinctive chrome appearance make this one of the most valuable and sought-after minifigures in the entire LEGO Star Wars line, commanding premium prices in the secondary market due to its extreme scarcity and visual appeal.',
    de: 'Dieser chromsilberne Imperial Stormtrooper repräsentiert eine der exklusivsten Werbe-LEGO Star Wars-Minifiguren, die jemals produziert wurden. Diese 2009 durch extrem limitierte Vertriebskanäle veröffentlichte Figur verfügt über reflektierende Chromsilber-Plattierung, die die gesamte Stormtrooper-Rüstung bedeckt und ein atemberaubendes metallisches Aussehen schafft. Das Chrom-Finish verwandelt den Standard-Soldaten in ein ultra-Premium-Sammlerstück mit spiegelähnlicher Oberflächenqualität. In sehr kleinen Mengen durch Sonderaktionen und Events vertrieben, ist dieser Chrom-Stormtrooper zu einer der heiligen Gral-Figuren für ernsthafte LEGO Star Wars-Sammler geworden. Die Seltenheit und das charakteristische Chrom-Aussehen machen dies zu einer der wertvollsten und begehrtesten Minifiguren in der gesamten LEGO Star Wars-Linie und erzielen auf dem Sekundärmarkt Premium-Preise aufgrund ihrer extremen Knappheit und visuellen Attraktivität.',
    fr: 'Ce Stormtrooper Impérial chromé argenté représente l\'une des minifigurines LEGO Star Wars promotionnelles les plus exclusives jamais produites. Sortie en 2009 par des canaux de distribution extrêmement limités, cette figurine présente un placage chromé argenté réfléchissant couvrant toute l\'armure du stormtrooper, créant une apparence métallique époustouflante. La finition chromée transforme le soldat standard en une pièce de collection ultra-premium avec une qualité de surface miroir. Distribuée en très petites quantités par des promotions et événements spéciaux, ce stormtrooper chromé est devenu l\'une des figurines du Saint Graal pour les collectionneurs sérieux LEGO Star Wars. La rareté et l\'apparence chromée distinctive en font l\'une des minifigurines les plus précieuses et recherchées de toute la ligne LEGO Star Wars, atteignant des prix premium sur le marché secondaire en raison de sa rareté extrême et de son attrait visuel.',
    es: 'Este Stormtrooper Imperial plateado cromado representa una de las minifiguras LEGO Star Wars promocionales más exclusivas jamás producidas. Lanzada en 2009 a través de canales de distribución extremadamente limitados, esta figura presenta recubrimiento plateado cromado reflectante cubriendo toda la armadura stormtrooper, creando una apariencia metálica impresionante. El acabado cromado transforma al soldado estándar en una pieza coleccionista ultra-premium con calidad de superficie tipo espejo. Distribuida en cantidades muy pequeñas a través de promociones y eventos especiales, este stormtrooper cromado se ha convertido en una de las figuras santo grial para coleccionistas serios LEGO Star Wars. La rareza y apariencia cromada distintiva hacen de esta una de las minifiguras más valiosas y buscadas en toda la línea LEGO Star Wars, alcanzando precios premium en el mercado secundario debido a su escasez extrema y atractivo visual.'
  },
  {
    no: 'sw0095a',
    name: 'Battle Droid Pilot - Blue Torso, Angled Arms',
    en: 'The Battle Droid Pilot with blue torso and angled arms represents specialized Separatist droids trained to operate starfighters and transport vehicles during the Clone Wars. Released in 2009, this variant features distinctive blue markings identifying pilot specialization along with the characteristic angled arm design of battle droid figures. Pilot droids handle starfighter operations, transport ships, and vehicle control for the Separatist military machine. The blue coloring distinguishes them from tan infantry droids and yellow commanders, indicating their specific role within droid forces. Essential for Separatist starfighter displays and droid army diversity, this pilot droid represents the automation advantage that allowed the Separatists to field massive military forces without requiring living pilots, demonstrating the technological approach to warfare that defined the Confederacy military strategy.',
    de: 'Der Battle Droid Pilot mit blauem Torso und abgewinkelten Armen repräsentiert spezialisierte separatistische Droiden, die für den Betrieb von Sternenjägern und Transportfahrzeugen während der Klonkriege ausgebildet wurden. Diese 2009 veröffentlichte Variante zeigt charakteristische blaue Markierungen, die Piloten-Spezialisierung kennzeichnen, zusammen mit dem charakteristischen abgewinkelten Arm-Design von Kampfdroiden-Figuren. Pilotendroiden übernehmen Sternenjäger-Operationen, Transportschiffe und Fahrzeugkontrolle für die separatistische Militärmaschine. Die blaue Färbung unterscheidet sie von hellbraunen Infanterie-Droiden und gelben Kommandanten und zeigt ihre spezifische Rolle innerhalb der Droiden-Streitkräfte an. Unverzichtbar für separatistische Sternenjäger-Displays und Droiden-Armee-Vielfalt repräsentiert dieser Pilotendroide den Automatisierungsvorteil, der es den Separatisten ermöglichte, massive Militärkräfte ohne lebende Piloten einzusetzen, und demonstriert den technologischen Kriegsführungs-Ansatz, der die militärische Strategie der Konföderation definierte.',
    fr: 'Le Droïde de Combat Pilote avec torse bleu et bras inclinés représente des droïdes séparatistes spécialisés formés pour opérer des chasseurs stellaires et véhicules de transport pendant les Guerres des Clones. Sortie en 2009, cette variante présente des marquages bleus distinctifs identifiant la spécialisation de pilote avec le design de bras incliné caractéristique des figurines de droïdes de combat. Les droïdes pilotes gèrent les opérations de chasseurs stellaires, les vaisseaux de transport et le contrôle de véhicules pour la machine militaire séparatiste. La coloration bleue les distingue des droïdes d\'infanterie beiges et des commandants jaunes, indiquant leur rôle spécifique au sein des forces droïdes. Essentiel pour les displays de chasseurs stellaires séparatistes et la diversité de l\'armée droïde, ce droïde pilote représente l\'avantage d\'automatisation qui a permis aux Séparatistes de déployer des forces militaires massives sans nécessiter de pilotes vivants, démontrant l\'approche technologique de la guerre qui définissait la stratégie militaire de la Confédération.',
    es: 'El Droide de Batalla Piloto con torso azul y brazos angulados representa droides Separatistas especializados entrenados para operar cazas estelares y vehículos de transporte durante las Guerras Clon. Lanzada en 2009, esta variante presenta distintivas marcas azules identificando especialización de piloto junto con el característico diseño de brazo angulado de figuras droide de batalla. Los droides piloto manejan operaciones de cazas estelares, naves de transporte y control de vehículos para la máquina militar Separatista. La coloración azul los distingue de droides de infantería beige y comandantes amarillos, indicando su rol específico dentro de fuerzas droide. Esencial para displays de cazas estelares Separatistas y diversidad de ejército droide, este droide piloto representa la ventaja de automatización que permitió a Separatistas desplegar fuerzas militares masivas sin requerir pilotos vivientes, demostrando el enfoque tecnológico de guerra que definió la estrategia militar de la Confederación.'
  },
  {
    no: 'sw0255',
    name: 'Astromech Droid, R2-D2, Clone Wars',
    en: 'R2-D2 appears in Clone Wars style representing the loyal astromech droid serving Anakin Skywalker and later Luke Skywalker throughout the saga. Released in 2009, this variant features the iconic blue and white color scheme with Clone Wars era printing details. As one of the most beloved characters in Star Wars history, R2-D2 serves as mechanic, hacker, message courier, and hero in countless adventures across multiple generations. His resourcefulness and loyalty prove instrumental in every major victory from the Clone Wars through the Battle of Endor. Essential for any Star Wars collection, this Clone Wars R2-D2 represents the little droid who repeatedly saves the day, demonstrating that courage and determination come in all sizes and proving indispensable to the fate of the galaxy.',
    de: 'R2-D2 erscheint im Clone Wars-Stil und repräsentiert den treuen Astromech-Droiden, der Anakin Skywalker und später Luke Skywalker durch die gesamte Saga dient. Diese 2009 veröffentlichte Variante zeigt das ikonische blau-weiße Farbschema mit Clone Wars-Ära-Druckdetails. Als einer der beliebtesten Charaktere in der Star Wars-Geschichte dient R2-D2 als Mechaniker, Hacker, Botenkurier und Held in unzähligen Abenteuern über mehrere Generationen hinweg. Sein Einfallsreichtum und seine Loyalität erweisen sich als entscheidend für jeden großen Sieg von den Klonkriegen bis zur Schlacht von Endor. Unverzichtbar für jede Star Wars-Sammlung repräsentiert dieser Clone Wars R2-D2 den kleinen Droiden, der wiederholt den Tag rettet, demonstriert, dass Mut und Entschlossenheit in allen Größen kommen, und beweist sich als unverzichtbar für das Schicksal der Galaxie.',
    fr: 'R2-D2 apparaît dans le style Clone Wars représentant le droïde astromech loyal servant Anakin Skywalker et plus tard Luke Skywalker tout au long de la saga. Sortie en 2009, cette variante présente le schéma de couleurs bleu et blanc iconique avec des détails d\'impression de l\'ère Clone Wars. En tant que l\'un des personnages les plus aimés de l\'histoire Star Wars, R2-D2 sert de mécanicien, hacker, coursier de messages et héros dans d\'innombrables aventures à travers plusieurs générations. Son ingéniosité et sa loyauté s\'avèrent déterminants dans chaque victoire majeure des Guerres des Clones à la Bataille d\'Endor. Essentiel pour toute collection Star Wars, ce R2-D2 Clone Wars représente le petit droïde qui sauve la situation à répétition, démontrant que le courage et la détermination viennent dans toutes les tailles et se révélant indispensable au destin de la galaxie.',
    es: 'R2-D2 aparece en estilo Clone Wars representando al leal droide astromecánico sirviendo a Anakin Skywalker y posteriormente Luke Skywalker a lo largo de la saga. Lanzada en 2009, esta variante presenta el icónico esquema de color azul y blanco con detalles de impresión de era Clone Wars. Como uno de los personajes más queridos en la historia Star Wars, R2-D2 sirve como mecánico, hacker, mensajero y héroe en incontables aventuras a través de múltiples generaciones. Su ingenio y lealtad resultan instrumentales en cada victoria mayor desde las Guerras Clon hasta la Batalla de Endor. Esencial para cualquier colección Star Wars, este R2-D2 Clone Wars representa al pequeño droide que repetidamente salva el día, demostrando que coraje y determinación vienen en todos los tamaños y probando ser indispensable para el destino de la galaxia.'
  }
];

async function saveBatch032() {
  console.log('💾 Saving batch 032 (sw0248-sw0255) - 10 minifigs...\n');

  for (const m of batch032) {
    try {
      await prisma.minifigCatalog.update({
        where: { minifigure_no: m.no },
        data: {
          description_en: m.en,
          description_de: m.de,
          description_fr: m.fr,
          description_es: m.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        }
      });
      console.log(`  ✅ ${m.no}: ${m.name}`);
    } catch (error: any) {
      console.log(`  ⚠️  ${m.no}: NOT IN DATABASE (skipped)`);
    }
  }

  console.log(`\n✨ Batch 032 complete: ${batch032.length} minifigs (${batch032.length * 4} descriptions)`);
  await prisma.$disconnect();
}

saveBatch032().catch(console.error);
