import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0144',
    name: 'Medical Droid - Dark Bluish Gray Tools',
    en: 'Medical Droid with Dark Bluish Gray Tools represents the surgical droids that operated on patients throughout the galaxy including the infamous scene where Darth Vader was rebuilt. This LEGO minifigure features dark bluish gray tool appendages, medical equipment accessories, and specialized construction for medical procedures. Released in 2005, this version captures the droids that performed cybernetic surgery on Anakin Skywalker after his defeat on Mustafar. The dark bluish gray tools make this minifigure valuable for collectors recreating medical facility displays and building complete droid roster collections with specialized utility droids.',
    de: 'Medizin-Droide mit dunkelbläulich-grauen Werkzeugen repräsentiert die chirurgischen Droiden, die Patienten in der gesamten Galaxie operierten, einschließlich der berüchtigten Szene, in der Darth Vader wiederaufgebaut wurde. Diese LEGO Minifigur zeigt dunkelbläulich-graue Werkzeug-Anhänge, medizinische Ausrüstungs-Zubehör und spezialisierte Konstruktion für medizinische Verfahren. Veröffentlicht 2005, fängt diese Version die Droiden ein, die kybernetische Chirurgie an Anakin Skywalker nach seiner Niederlage auf Mustafar durchführten. Die dunkelbläulich-grauen Werkzeuge machen diese Minifigur wertvoll für Sammler, die medizinische Einrichtungs-Displays nachstellen und vollständige Droiden-Kader-Sammlungen mit spezialisierten Nutz-Droiden aufbauen.',
    fr: 'Droïde Médical avec Outils Gris Bleuté Foncé représente les droïdes chirurgicaux qui ont opéré des patients dans toute la galaxie, y compris la scène infâme où Dark Vador a été reconstruit. Cette minifigurine LEGO présente des appendices d\'outils gris bleuté foncé, des accessoires d\'équipement médical et une construction spécialisée pour les procédures médicales. Sortie en 2005, cette version capture les droïdes qui ont effectué une chirurgie cybernétique sur Anakin Skywalker après sa défaite sur Mustafar. Les outils gris bleuté foncé rendent cette minifigurine précieuse pour les collectionneurs recréant des affichages d\'installations médicales et construisant des collections complètes de listes de droïdes avec des droïdes utilitaires spécialisés.',
    es: 'Droide Médico con Herramientas Gris Azulado Oscuro representa a los droides quirúrgicos que operaron pacientes a través de la galaxia incluyendo la infame escena donde Darth Vader fue reconstruido. Esta minifigura LEGO presenta apéndices de herramientas gris azulado oscuro, accesorios de equipo médico y construcción especializada para procedimientos médicos. Lanzada en 2005, esta versión captura a los droides que realizaron cirugía cibernética en Anakin Skywalker después de su derrota en Mustafar. Las herramientas gris azulado oscuro hacen de esta minifigura valiosa para coleccionistas recreando exhibiciones de instalaciones médicas y construyendo colecciones completas de lista de droides con droides utilitarios especializados.'
  },
  {
    no: 'sw0140',
    name: 'Owen Lars - Plain Legs, Smooth Hair',
    en: 'Owen Lars with Plain Legs and Smooth Hair represents Luke Skywalker\'s uncle and moisture farmer on Tatooine who raised Luke after his parents\' deaths. This LEGO minifigure features flesh-toned head, smooth hair piece, plain farmer clothing, and the appearance of the hardworking moisture farmer from A New Hope. Released in 2005 with Tatooine homestead sets, this version captures Owen during his brief but pivotal role in Luke\'s early life. The plain farmer appearance makes this minifigure valuable for collectors building complete Lars homestead displays and Tatooine civilian population collections.',
    de: 'Owen Lars mit einfachen Beinen und glattem Haar repräsentiert Luke Skywalkers Onkel und Feuchtigkeitsfarmer auf Tatooine, der Luke nach dem Tod seiner Eltern großzog. Diese LEGO Minifigur zeigt fleischfarbenen Kopf, glattes Haarteil, einfache Farmer-Kleidung und das Aussehen des hart arbeitenden Feuchtigkeitsfarmers aus Eine neue Hoffnung. Veröffentlicht 2005 mit Tatooine-Gehöft-Sets, fängt diese Version Owen während seiner kurzen aber entscheidenden Rolle in Lukes frühem Leben ein. Das einfache Farmer-Aussehen macht diese Minifigur wertvoll für Sammler, die vollständige Lars-Gehöft-Displays und Tatooine-Zivilbevölkerungs-Sammlungen aufbauen.',
    fr: 'Owen Lars avec Jambes Simples et Cheveux Lisses représente l\'oncle de Luke Skywalker et fermier d\'humidité sur Tatooine qui a élevé Luke après la mort de ses parents. Cette minifigurine LEGO présente une tête de couleur chair, une pièce de cheveux lisses, des vêtements de fermier simples et l\'apparence du fermier d\'humidité travailleur d\'Un nouvel espoir. Sortie en 2005 avec les sets de ferme de Tatooine, cette version capture Owen pendant son rôle bref mais pivot dans la jeunesse de Luke. L\'apparence de fermier simple rend cette minifigurine précieuse pour les collectionneurs construisant des affichages complets de ferme Lars et des collections de population civile de Tatooine.',
    es: 'Owen Lars con Piernas Simples y Cabello Liso representa al tío de Luke Skywalker y granjero de humedad en Tatooine quien crió a Luke después de las muertes de sus padres. Esta minifigura LEGO presenta cabeza de tono de piel, pieza de cabello liso, ropa de granjero simple y la apariencia del trabajador granjero de humedad de Una Nueva Esperanza. Lanzada en 2005 con sets de granja de Tatooine, esta versión captura a Owen durante su papel breve pero crucial en la vida temprana de Luke. La apariencia de granjero simple hace de esta minifigura valiosa para coleccionistas construyendo exhibiciones completas de granja Lars y colecciones de población civil de Tatooine.'
  },
  {
    no: 'sw0141',
    name: 'Jawa with Cape',
    en: 'Jawa with Cape represents the scavenging desert dwellers of Tatooine who salvaged and sold droids and equipment to moisture farmers. This LEGO minifigure features the distinctive brown hooded cape, glowing yellow eyes visible beneath the hood, and small stature of the mysterious Jawas. Released in 2005 with Sandcrawler sets, this version captures the enterprising traders who sold R2-D2 and C-3PO to the Lars family. The cape and glowing eyes make this minifigure essential for collectors building Sandcrawler interior displays and army-building Jawa clans for Tatooine scenes.',
    de: 'Jawa mit Umhang repräsentiert die plündernden Wüstenbewohner von Tatooine, die Droiden und Ausrüstung an Feuchtigkeitsfarmer retteten und verkauften. Diese LEGO Minifigur zeigt den charakteristischen braunen Kapuzenumhang, leuchtende gelbe Augen, die unter der Kapuze sichtbar sind, und kleine Statur der geheimnisvollen Jawas. Veröffentlicht 2005 mit Sandcrawler-Sets, fängt diese Version die unternehmungslustigen Händler ein, die R2-D2 und C-3PO an die Lars-Familie verkauften. Der Umhang und die leuchtenden Augen machen diese Minifigur wesentlich für Sammler, die Sandcrawler-Innenraum-Displays aufbauen und Jawa-Clans für Tatooine-Szenen für Armeen zusammenstellen.',
    fr: 'Jawa avec Cape représente les habitants du désert charognards de Tatooine qui récupéraient et vendaient des droïdes et de l\'équipement aux fermiers d\'humidité. Cette minifigurine LEGO présente la cape à capuche brune distinctive, des yeux jaunes lumineux visibles sous la capuche et la petite stature des Jawas mystérieux. Sortie en 2005 avec les sets Sandcrawler, cette version capture les commerçants entreprenants qui ont vendu R2-D2 et C-3PO à la famille Lars. La cape et les yeux lumineux rendent cette minifigurine essentielle pour les collectionneurs construisant des affichages intérieurs de Sandcrawler et assemblant des clans Jawa pour les scènes de Tatooine.',
    es: 'Jawa con Capa representa a los habitantes del desierto carroñeros de Tatooine quienes rescataron y vendieron droides y equipo a granjeros de humedad. Esta minifigura LEGO presenta la distintiva capa con capucha marrón, ojos amarillos brillantes visibles bajo la capucha y pequeña estatura de los misteriosos Jawas. Lanzada en 2005 con sets Sandcrawler, esta versión captura a los emprendedores comerciantes quienes vendieron R2-D2 y C-3PO a la familia Lars. La capa y ojos brillantes hacen de esta minifigura esencial para coleccionistas construyendo exhibiciones de interior de Sandcrawler y ensamblando clanes Jawa para escenas de Tatooine.'
  },
  {
    no: 'sw0142',
    name: 'Astromech Droid, R5-D4 - Dome Head',
    en: 'R5-D4 Astromech Droid with Dome Head represents the malfunctioning droid with a bad motivator that Luke\'s uncle almost purchased instead of R2-D2. This LEGO minifigure features R5-D4\'s distinctive white and red cylindrical body with red stripe patterns, dome head design, and the appearance of the droid whose breakdown changed galactic history. Released in 2005 with updated color standards, this version captures the brief but memorable astromech whose malfunction ensured R2-D2 would deliver Princess Leia\'s message. The dome head variant makes this minifigure valuable for collectors seeking updated R5 units and complete astromech droid collections.',
    de: 'R5-D4 Astromech-Droide mit Kuppelkopf repräsentiert den defekten Droiden mit schlechtem Motivator, den Lukes Onkel fast anstelle von R2-D2 kaufte. Diese LEGO Minifigur zeigt R5-D4s charakteristischen weiß-roten zylindrischen Körper mit roten Streifenmustern, Kuppelkopf-Design und das Aussehen des Droiden, dessen Zusammenbruch die galaktische Geschichte veränderte. Veröffentlicht 2005 mit aktualisierten Farbstandards, fängt diese Version den kurzen aber einprägsamen Astromech ein, dessen Fehlfunktion sicherstellte, dass R2-D2 Prinzessin Leias Nachricht überbringen würde. Die Kuppelkopf-Variante macht diese Minifigur wertvoll für Sammler, die aktualisierte R5-Einheiten und vollständige Astromech-Droiden-Sammlungen suchen.',
    fr: 'Droïde Astromécano R5-D4 avec Tête en Dôme représente le droïde défectueux avec un mauvais motivateur que l\'oncle de Luke a presque acheté à la place de R2-D2. Cette minifigurine LEGO présente le corps cylindrique blanc et rouge distinctif de R5-D4 avec motifs de rayures rouges, design de tête en dôme et l\'apparence du droïde dont la panne a changé l\'histoire galactique. Sortie en 2005 avec normes de couleur mises à jour, cette version capture l\'astromécano bref mais mémorable dont le dysfonctionnement a assuré que R2-D2 livrerait le message de la Princesse Leia. La variante de tête en dôme rend cette minifigurine précieuse pour les collectionneurs recherchant des unités R5 mises à jour et des collections complètes de droïdes astromécaniques.',
    es: 'Droide Astromecánico R5-D4 con Cabeza de Domo representa al droide defectuoso con un mal motivador que el tío de Luke casi compró en lugar de R2-D2. Esta minifigura LEGO presenta el distintivo cuerpo cilíndrico blanco y rojo de R5-D4 con patrones de rayas rojas, diseño de cabeza de domo y la apariencia del droide cuya avería cambió la historia galáctica. Lanzada en 2005 con estándares de color actualizados, esta versión captura al astromecánico breve pero memorable cuya falla aseguró que R2-D2 entregaría el mensaje de la Princesa Leia. La variante de cabeza de domo hace de esta minifigura valiosa para coleccionistas buscando unidades R5 actualizadas y colecciones completas de droides astromecánicos.'
  },
  {
    no: 'sw0145',
    name: 'ASP Droid',
    en: 'ASP Droid represents the labor droids used for heavy lifting and cargo handling across spaceports throughout the galaxy including Mos Eisley. This LEGO minifigure features distinctive industrial design, mechanical construction, and utilitarian appearance of the work droids. Released in 2005, this version captures the background droids that populated Star Wars locations performing mundane but essential tasks. The ASP Droid design makes this minifigure valuable for collectors adding authentic environmental details to displays and building diverse droid population rosters beyond combat and astromech units.',
    de: 'ASP-Droide repräsentiert die Arbeitsdroiden, die für schweres Heben und Frachthandhabung über Raumhäfen in der gesamten Galaxie einschließlich Mos Eisley verwendet wurden. Diese LEGO Minifigur zeigt charakteristisches industrielles Design, mechanische Konstruktion und utilitaristisches Aussehen der Arbeits-Droiden. Veröffentlicht 2005, fängt diese Version die Hintergrund-Droiden ein, die Star Wars-Orte bevölkerten und alltägliche aber wesentliche Aufgaben ausführten. Das ASP-Droiden-Design macht diese Minifigur wertvoll für Sammler, die authentische Umgebungs-Details zu Displays hinzufügen und vielfältige Droiden-Bevölkerungs-Kader jenseits von Kampf- und Astromech-Einheiten aufbauen.',
    fr: 'Droïde ASP représente les droïdes de travail utilisés pour le levage lourd et la manutention de cargaison dans les spatioports de toute la galaxie, y compris Mos Eisley. Cette minifigurine LEGO présente un design industriel distinctif, une construction mécanique et une apparence utilitaire des droïdes de travail. Sortie en 2005, cette version capture les droïdes d\'arrière-plan qui peuplaient les emplacements Star Wars effectuant des tâches banales mais essentielles. Le design de droïde ASP rend cette minifigurine précieuse pour les collectionneurs ajoutant des détails environnementaux authentiques aux affichages et construisant des listes de population de droïdes diverses au-delà des unités de combat et astromécaniques.',
    es: 'Droide ASP representa a los droides laborales usados para levantamiento pesado y manejo de carga a través de espaciopuertos por toda la galaxia incluyendo Mos Eisley. Esta minifigura LEGO presenta distintivo diseño industrial, construcción mecánica y apariencia utilitaria de los droides de trabajo. Lanzada en 2005, esta versión captura a los droides de fondo que poblaron ubicaciones Star Wars realizando tareas mundanas pero esenciales. El diseño de Droide ASP hace de esta minifigura valiosa para coleccionistas agregando detalles ambientales auténticos a exhibiciones y construyendo listas de población de droides diversas más allá de unidades de combate y astromecánicas.'
  },
  {
    no: 'sw0146',
    name: 'Treadwell Droid - White and Orange Body',
    en: 'Treadwell Droid with White and Orange Body represents the repair and maintenance droids used on moisture farms and throughout Tatooine. This LEGO minifigure features distinctive white and orange coloring, treaded locomotion, tool appendages, and the appearance of the utility droid Uncle Owen sent to repair the vaporators. Released in 2005 with Lars homestead sets, this version captures the working droids that kept Tatooine farms operational. The white and orange body makes this minifigure valuable for collectors building complete Tatooine homestead displays and representing the civilian droid workforce of the Star Wars galaxy.',
    de: 'Treadwell-Droide mit weißem und orangem Körper repräsentiert die Reparatur- und Wartungsdroiden, die auf Feuchtigkeitsfarmen und auf ganz Tatooine verwendet wurden. Diese LEGO Minifigur zeigt charakteristische weiß-orange Färbung, Raupen-Fortbewegung, Werkzeug-Anhänge und das Aussehen des Nutz-Droiden, den Onkel Owen schickte, um die Verdampfer zu reparieren. Veröffentlicht 2005 mit Lars-Gehöft-Sets, fängt diese Version die arbeitenden Droiden ein, die Tatooine-Farmen betriebsbereit hielten. Der weiß-orange Körper macht diese Minifigur wertvoll für Sammler, die vollständige Tatooine-Gehöft-Displays aufbauen und die zivile Droiden-Arbeitskraft der Star Wars-Galaxie repräsentieren.',
    fr: 'Droïde Treadwell avec Corps Blanc et Orange représente les droïdes de réparation et de maintenance utilisés sur les fermes d\'humidité et dans tout Tatooine. Cette minifigurine LEGO présente une coloration blanche et orange distinctive, une locomotion à chenilles, des appendices d\'outils et l\'apparence du droïde utilitaire que l\'Oncle Owen a envoyé pour réparer les évaporateurs. Sortie en 2005 avec les sets de ferme Lars, cette version capture les droïdes de travail qui ont maintenu les fermes de Tatooine opérationnelles. Le corps blanc et orange rend cette minifigurine précieuse pour les collectionneurs construisant des affichages complets de ferme de Tatooine et représentant la main-d\'œuvre droïde civile de la galaxie Star Wars.',
    es: 'Droide Treadwell con Cuerpo Blanco y Naranja representa a los droides de reparación y mantenimiento usados en granjas de humedad y a través de Tatooine. Esta minifigura LEGO presenta distintiva coloración blanca y naranja, locomoción con orugas, apéndices de herramientas y la apariencia del droide utilitario que el Tío Owen envió para reparar los vaporizadores. Lanzada en 2005 con sets de granja Lars, esta versión captura a los droides trabajadores que mantuvieron operativas las granjas de Tatooine. El cuerpo blanco y naranja hace de esta minifigura valiosa para coleccionistas construyendo exhibiciones completas de granja de Tatooine y representando la fuerza laboral de droides civiles de la galaxia Star Wars.'
  },
  {
    no: 'sw0147',
    name: 'Astromech Droid, R1-G4',
    en: 'R1-G4 Astromech Droid represents one of the many astromech units serving the Rebel Alliance throughout the original trilogy. This LEGO minifigure features R1-G4\'s distinctive gray and yellow cylindrical body design, dome head, and unique color scheme identifying this specific astromech model. Released in 2005, this version captures one of the background droids that populated rebel bases and starfighter hangars. The R1-G4 designation makes this minifigure valuable for collectors building diverse astromech rosters and adding variety to rebel base displays beyond the famous R2 units.',
    de: 'R1-G4 Astromech-Droide repräsentiert eine der vielen Astromech-Einheiten, die der Rebellenallianz während der ursprünglichen Trilogie dienten. Diese LEGO Minifigur zeigt R1-G4s charakteristisches grau-gelbes zylindrisches Körper-Design, Kuppelkopf und einzigartiges Farbschema, das dieses spezifische Astromech-Modell identifiziert. Veröffentlicht 2005, fängt diese Version einen der Hintergrund-Droiden ein, die Rebellenbasen und Sternenjäger-Hangars bevölkerten. Die R1-G4-Bezeichnung macht diese Minifigur wertvoll für Sammler, die vielfältige Astromech-Kader aufbauen und Rebellenbasis-Displays jenseits der berühmten R2-Einheiten Vielfalt hinzufügen.',
    fr: 'Droïde Astromécano R1-G4 représente l\'une des nombreuses unités astromécaniques servant l\'Alliance Rebelle tout au long de la trilogie originale. Cette minifigurine LEGO présente le design de corps cylindrique gris et jaune distinctif de R1-G4, une tête en dôme et un schéma de couleurs unique identifiant ce modèle astromécanique spécifique. Sortie en 2005, cette version capture l\'un des droïdes d\'arrière-plan qui peuplaient les bases rebelles et les hangars de chasseurs stellaires. La désignation R1-G4 rend cette minifigurine précieuse pour les collectionneurs construisant des listes d\'astromécaniques diverses et ajoutant de la variété aux affichages de base rebelle au-delà des unités R2 célèbres.',
    es: 'Droide Astromecánico R1-G4 representa a una de las muchas unidades astromecánicas sirviendo a la Alianza Rebelde a lo largo de la trilogía original. Esta minifigura LEGO presenta el distintivo diseño de cuerpo cilíndrico gris y amarillo de R1-G4, cabeza de domo y esquema de color único identificando este modelo astromecánico específico. Lanzada en 2005, esta versión captura a uno de los droides de fondo que poblaron bases rebeldes y hangares de cazas estelares. La designación R1-G4 hace de esta minifigura valiosa para coleccionistas construyendo listas de astromecánicos diversos y agregando variedad a exhibiciones de base rebelde más allá de las famosas unidades R2.'
  },
  {
    no: 'sw0073a',
    name: 'Gonk Droid (GNK Power Droid), Dark Bluish Gray Body and Light Bluish Gray Legs',
    en: 'Gonk Droid GNK Power Droid with Dark Bluish Gray Body and Light Bluish Gray Legs represents the walking battery units with updated LEGO color standards. This LEGO minifigure features the distinctive rectangular box-shaped body in dark bluish gray, light bluish gray legs, and the iconic appearance of the utilitarian power droid. Released in 2005 with color-corrected pieces, this version shows the beloved Gonk droid with refined modern LEGO colors. The dark bluish gray and light bluish gray combination makes this minifigure valuable for collectors seeking updated color variants and building displays with consistent modern LEGO color palettes.',
    de: 'Gonk-Droide GNK Power-Droide mit dunkelbläulich-grauem Körper und hellbläulich-grauen Beinen repräsentiert die gehenden Batterie-Einheiten mit aktualisierten LEGO-Farbstandards. Diese LEGO Minifigur zeigt den charakteristischen rechteckigen kastenförmigen Körper in Dunkelbläulich-Grau, hellbläulich-graue Beine und das ikonische Aussehen des utilitaristischen Power-Droiden. Veröffentlicht 2005 mit farbkorrigierten Teilen, zeigt diese Version den geliebten Gonk-Droiden mit verfeinerten modernen LEGO-Farben. Die dunkelbläulich-grau und hellbläulich-grau-Kombination macht diese Minifigur wertvoll für Sammler, die aktualisierte Farbvarianten suchen und Displays mit konsistenten modernen LEGO-Farbpaletten aufbauen.',
    fr: 'Droïde Gonk Droïde d\'Alimentation GNK avec Corps Gris Bleuté Foncé et Jambes Gris Bleuté Clair représente les unités de batterie marchantes avec normes de couleur LEGO mises à jour. Cette minifigurine LEGO présente le corps en forme de boîte rectangulaire distinctif en gris bleuté foncé, des jambes gris bleuté clair et l\'apparence emblématique du droïde d\'alimentation utilitaire. Sortie en 2005 avec des pièces corrigées en couleur, cette version montre le droïde Gonk bien-aimé avec des couleurs LEGO modernes raffinées. La combinaison gris bleuté foncé et gris bleuté clair rend cette minifigurine précieuse pour les collectionneurs recherchant des variantes de couleur mises à jour et construisant des affichages avec palettes de couleurs LEGO modernes cohérentes.',
    es: 'Droide Gonk Droide de Energía GNK con Cuerpo Gris Azulado Oscuro y Piernas Gris Azulado Claro representa a las unidades de batería ambulantes con estándares de color LEGO actualizados. Esta minifigura LEGO presenta el distintivo cuerpo en forma de caja rectangular en gris azulado oscuro, piernas gris azulado claro y la apariencia icónica del droide de energía utilitario. Lanzada en 2005 con piezas corregidas en color, esta versión muestra al querido droide Gonk con colores LEGO modernos refinados. La combinación gris azulado oscuro y gris azulado claro hace de esta minifigura valiosa para coleccionistas buscando variantes de color actualizadas y construyendo exhibiciones con paletas de color LEGO modernas consistentes.'
  },
  {
    no: 'sw0151',
    name: 'Assassin Droid (IG-88) - Metallic Silver',
    en: 'Assassin Droid IG-88 in Metallic Silver represents one of the most feared bounty hunter droids in the galaxy who answered Darth Vader\'s call in The Empire Strikes Back. This LEGO minifigure features metallic silver coloring, distinctive tall thin construction, weapon accessories, and the menacing appearance of the ruthless assassin droid. Released in 2006 with bounty hunter sets, this version captures the deadly droid that competed with Boba Fett for bounties. The metallic silver finish makes this minifigure extremely valuable for collectors building complete bounty hunter rosters and representing one of the most unique and dangerous characters from the original trilogy.',
    de: 'Assassinen-Droide IG-88 in Metallisch Silber repräsentiert einen der gefürchtetsten Kopfgeldjäger-Droiden in der Galaxie, der Darth Vaders Ruf in Das Imperium schlägt zurück folgte. Diese LEGO Minifigur zeigt metallisch silberne Färbung, charakteristische hohe dünne Konstruktion, Waffen-Zubehör und das bedrohliche Aussehen des rücksichtslosen Assassinen-Droiden. Veröffentlicht 2006 mit Kopfgeldjäger-Sets, fängt diese Version den tödlichen Droiden ein, der mit Boba Fett um Kopfgelder konkurrierte. Die metallisch silberne Oberfläche macht diese Minifigur extrem wertvoll für Sammler, die vollständige Kopfgeldjäger-Kader aufbauen und einen der einzigartigsten und gefährlichsten Charaktere aus der ursprünglichen Trilogie repräsentieren.',
    fr: 'Droïde Assassin IG-88 en Argent Métallique représente l\'un des droïdes chasseurs de primes les plus redoutés de la galaxie qui a répondu à l\'appel de Dark Vador dans L\'Empire contre-attaque. Cette minifigurine LEGO présente une coloration argent métallique, une construction grande et mince distinctive, des accessoires d\'armes et l\'apparence menaçante du droïde assassin impitoyable. Sortie en 2006 avec les sets de chasseurs de primes, cette version capture le droïde mortel qui a rivalisé avec Boba Fett pour des primes. La finition argent métallique rend cette minifigurine extrêmement précieuse pour les collectionneurs construisant des listes complètes de chasseurs de primes et représentant l\'un des personnages les plus uniques et dangereux de la trilogie originale.',
    es: 'Droide Asesino IG-88 en Plateado Metálico representa a uno de los droides cazarrecompensas más temidos en la galaxia quien respondió al llamado de Darth Vader en El Imperio Contraataca. Esta minifigura LEGO presenta coloración plateado metálico, distintiva construcción alta y delgada, accesorios de armas y la apariencia amenazante del despiadado droide asesino. Lanzada en 2006 con sets de cazarrecompensas, esta versión captura al droide mortal que compitió con Boba Fett por recompensas. El acabado plateado metálico hace de esta minifigura extremadamente valiosa para coleccionistas construyendo listas completas de cazarrecompensas y representando a uno de los personajes más únicos y peligrosos de la trilogía original.'
  },
  {
    no: 'sw0149',
    name: 'Dengar - Reddish Brown Torso, White Ninja Wrap',
    en: 'Dengar with Reddish Brown Torso and White Ninja Wrap represents the heavily bandaged bounty hunter who answered Darth Vader\'s call aboard the Executor in The Empire Strikes Back. This LEGO minifigure features reddish brown armor torso, distinctive white head wrapping from battle injuries, weapon accessories, and the appearance of the vengeful hunter. Released in 2006, this version captures one of the bounty hunters competing with Boba Fett to capture Han Solo. The white ninja wrap head design makes this minifigure valuable for collectors building complete Empire Strikes Back bounty hunter lineups and representing the diverse mercenaries of the Star Wars underworld.',
    de: 'Dengar mit rotbraunem Torso und weißer Ninja-Wicklung repräsentiert den schwer bandagierten Kopfgeldjäger, der Darth Vaders Ruf an Bord der Executor in Das Imperium schlägt zurück folgte. Diese LEGO Minifigur zeigt rotbraunen Rüstungs-Torso, charakteristische weiße Kopfwicklung von Kampfverletzungen, Waffen-Zubehör und das Aussehen des rachsüchtigen Jägers. Veröffentlicht 2006, fängt diese Version einen der Kopfgeldjäger ein, die mit Boba Fett konkurrierten, um Han Solo zu fangen. Das weiße Ninja-Wickel-Kopf-Design macht diese Minifigur wertvoll für Sammler, die vollständige Das-Imperium-schlägt-zurück-Kopfgeldjäger-Aufstellungen aufbauen und die vielfältigen Söldner der Star Wars-Unterwelt repräsentieren.',
    fr: 'Dengar avec Torse Brun Rougeâtre et Enveloppement Ninja Blanc représente le chasseur de primes lourdement bandé qui a répondu à l\'appel de Dark Vador à bord de l\'Executor dans L\'Empire contre-attaque. Cette minifigurine LEGO présente un torse d\'armure brun rougeâtre, un enveloppement de tête blanc distinctif des blessures de combat, des accessoires d\'armes et l\'apparence du chasseur vengeur. Sortie en 2006, cette version capture l\'un des chasseurs de primes rivalisant avec Boba Fett pour capturer Han Solo. Le design d\'enveloppement ninja blanc de la tête rend cette minifigurine précieuse pour les collectionneurs construisant des alignements complets de chasseurs de primes de L\'Empire contre-attaque et représentant les mercenaires divers du monde criminel de Star Wars.',
    es: 'Dengar con Torso Marrón Rojizo y Envoltura Ninja Blanca representa al cazarrecompensas fuertemente vendado quien respondió al llamado de Darth Vader a bordo del Executor en El Imperio Contraataca. Esta minifigura LEGO presenta torso de armadura marrón rojizo, distintiva envoltura de cabeza blanca por heridas de batalla, accesorios de armas y la apariencia del cazador vengativo. Lanzada en 2006, esta versión captura a uno de los cazarrecompensas compitiendo con Boba Fett para capturar a Han Solo. El diseño de envoltura ninja blanca de cabeza hace de esta minifigura valiosa para coleccionistas construyendo alineaciones completas de cazarrecompensas de El Imperio Contraataca y representando a los diversos mercenarios del submundo de Star Wars.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 015 (sw0144-sw0149) - 10 minifigs...\n');

  for (const m of batch) {
    try {
      await prisma.minifigCatalog.update({
        where: { minifigure_no: m.no },
        data: {
          description_en: m.en,
          description_de: m.de,
          description_fr: m.fr,
          description_es: m.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        }
      });
      console.log(`  ✅ ${m.no}: ${m.name}`);
    } catch (error: any) {
      console.log(`  ⚠️  ${m.no}: NOT IN DATABASE (skipped)`);
    }
  }

  console.log('\n✨ Batch 015 complete: 10 minifigs (40 descriptions)');
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
