import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0269',
    name: 'Ewok Warrior',
    en: 'The Ewok Warrior LEGO minifigure captures the brave forest dwellers of Endor with their distinctive brown fur, simple tribal attire, and the endearing yet fierce appearance that made them unexpected heroes of the Galactic Civil War. This minifigure features detailed printing showing traditional Ewok clothing and accessories, representing the primitive yet resourceful species that helped topple the Empire through guerrilla warfare and cunning traps. Armed with spears, bows, and captured Imperial technology, Ewoks like Wicket demonstrated that courage and ingenuity could overcome technological superiority during the Battle of Endor. Released in sets from 2009 onwards with various Ewok village and battle pack iterations, this minifigure appeals to collectors building Endor forest scenes, highly sought after due to the Ewoks\' iconic status in Return of the Jedi, their crucial role in destroying the second Death Star\'s shield generator, and their representation of nature triumphing over the Empire\'s mechanical might.',
    de: 'Die LEGO-Minifigur des Ewok-Kriegers fängt die tapferen Waldbewohner von Endor mit ihrem markanten braunen Fell, einfacher Stammeskleidung und dem liebenswerten, aber wilden Aussehen ein, das sie zu unerwarteten Helden des Galaktischen Bürgerkriegs machte. Diese Minifigur verfügt über detaillierte Bedruckung, die traditionelle Ewok-Kleidung und Accessoires zeigt, die die primitive, aber einfallsreiche Spezies repräsentiert, die half, das Imperium durch Guerillakrieg und listige Fallen zu stürzen. Bewaffnet mit Speeren, Bögen und erbeuteter imperialer Technologie demonstrierten Ewoks wie Wicket, dass Mut und Einfallsreichtum während der Schlacht von Endor technologische Überlegenheit überwinden konnten. In Sets ab 2009 mit verschiedenen Ewok-Dorf- und Kampfpack-Iterationen veröffentlicht, spricht diese Minifigur Sammler an, die Endor-Wald-Szenen aufbauen, hochgradig begehrt aufgrund des ikonischen Status der Ewoks in Die Rückkehr der Jedi-Ritter, ihrer entscheidenden Rolle bei der Zerstörung des Schildgenerators des zweiten Todessterns und ihrer Darstellung der Natur, die über die mechanische Macht des Imperiums triumphiert.',
    fr: 'La minifigurine LEGO du Guerrier Ewok capture les courageux habitants des forêts d\'Endor avec leur fourrure brune distinctive, leur tenue tribale simple, et l\'apparence attachante mais féroce qui en a fait des héros inattendus de la Guerre Civile Galactique. Cette minifigurine présente une impression détaillée montrant les vêtements et accessoires Ewok traditionnels, représentant l\'espèce primitive mais ingénieuse qui a aidé à renverser l\'Empire par la guerre de guérilla et des pièges astucieux. Armés de lances, d\'arcs et de technologie Impériale capturée, des Ewoks comme Wicket ont démontré que le courage et l\'ingéniosité pouvaient surmonter la supériorité technologique pendant la Bataille d\'Endor. Sortie dans des sets à partir de 2009 avec diverses itérations de village Ewok et de packs de bataille, cette minifigurine plaît aux collectionneurs construisant des scènes de forêt d\'Endor, très recherchée en raison du statut emblématique des Ewoks dans Le Retour du Jedi, leur rôle crucial dans la destruction du générateur de bouclier de la seconde Étoile de la Mort, et leur représentation de la nature triomphant sur la puissance mécanique de l\'Empire.',
    es: 'La minifigura LEGO del Guerrero Ewok captura a los valientes habitantes del bosque de Endor con su distintivo pelaje marrón, atuendo tribal simple, y la apariencia entrañable pero feroz que los hizo héroes inesperados de la Guerra Civil Galáctica. Esta minifigura presenta impresión detallada mostrando vestimenta y accesorios Ewok tradicionales, representando a la especie primitiva pero ingeniosa que ayudó a derrocar al Imperio mediante guerra de guerrillas y trampas astutas. Armados con lanzas, arcos y tecnología Imperial capturada, Ewoks como Wicket demostraron que el coraje y el ingenio podían superar la superioridad tecnológica durante la Batalla de Endor. Lanzada en sets desde 2009 con varias iteraciones de aldea Ewok y paquetes de batalla, esta minifigura atrae a coleccionistas construyendo escenas del bosque de Endor, muy buscada debido al estatus icónico de los Ewoks en El Retorno del Jedi, su papel crucial en destruir el generador de escudo de la segunda Estrella de la Muerte, y su representación de la naturaleza triunfando sobre el poderío mecánico del Imperio.'
  },
  {
    no: 'sw0270',
    name: 'Admiral Ackbar',
    en: 'Admiral Ackbar\'s LEGO minifigure portrays the legendary Mon Calamari military commander with his distinctive salmon-colored skin, large eyes, and white Rebel Alliance uniform that marked him as supreme commander of the Alliance fleet. This minifigure features detailed printing showing Ackbar\'s admiral insignia and the characteristic Mon Calamari facial features, representing the brilliant tactician who led the Rebel fleet to victory at the Battle of Endor. Known for his famous warning "It\'s a trap!" during the Death Star assault and his decades of service fighting Imperial tyranny, Ackbar embodied the diverse species united against the Empire\'s human-centric regime. Released in sets from 2009 onwards including Home One and various Rebel fleet builds, this minifigure became highly collectible among Star Wars fans, sought after due to Ackbar\'s iconic status in Return of the Jedi, his meme-worthy catchphrase that transcended the films, and his representation of alien leadership in the Rebellion that foreshadowed the New Republic\'s inclusive governance.',
    de: 'Die LEGO-Minifigur von Admiral Ackbar porträtiert den legendären Mon Calamari-Militärkommandanten mit seiner markanten lachsfarbenen Haut, großen Augen und weißer Rebellen-Allianz-Uniform, die ihn als Oberbefehlshaber der Allianzflotte kennzeichnete. Diese Minifigur verfügt über detaillierte Bedruckung, die Ackbars Admiralsabzeichen und die charakteristischen Mon Calamari-Gesichtszüge zeigt, die den brillanten Taktiker repräsentiert, der die Rebellenflotte zum Sieg in der Schlacht von Endor führte. Bekannt für seine berühmte Warnung "Es ist eine Falle!" während des Angriffs auf den Todesstern und seine jahrzehntelangen Dienste im Kampf gegen imperiale Tyrannei, verkörperte Ackbar die vielfältigen Spezies, die gegen das menschenzentrierte Regime des Imperiums vereint waren. In Sets ab 2009 veröffentlicht, einschließlich Home One und verschiedenen Rebellenflotten-Builds, wurde diese Minifigur unter Star Wars-Fans hochgradig sammelwürdig, begehrt aufgrund von Ackbars ikonischem Status in Die Rückkehr der Jedi-Ritter, seinem Meme-würdigen Catchphrase, der die Filme überschritt, und seiner Darstellung außerirdischer Führung in der Rebellion, die die inklusive Regierungsführung der Neuen Republik vorwegnahm.',
    fr: 'La minifigurine LEGO de l\'Amiral Ackbar dépeint le légendaire commandant militaire Mon Calamari avec sa peau de couleur saumon distinctive, ses grands yeux, et son uniforme blanc de l\'Alliance Rebelle qui le marquait comme commandant suprême de la flotte de l\'Alliance. Cette minifigurine présente une impression détaillée montrant les insignes d\'amiral d\'Ackbar et les traits faciaux Mon Calamari caractéristiques, représentant le brillant tacticien qui a mené la flotte Rebelle à la victoire à la Bataille d\'Endor. Connu pour son avertissement célèbre "C\'est un piège !" pendant l\'assaut de l\'Étoile de la Mort et ses décennies de service combattant la tyrannie Impériale, Ackbar incarnait les espèces diverses unies contre le régime anthropocentrique de l\'Empire. Sortie dans des sets à partir de 2009 incluant Home One et diverses constructions de flottes Rebelles, cette minifigurine est devenue hautement collectionnable parmi les fans de Star Wars, recherchée en raison du statut emblématique d\'Ackbar dans Le Retour du Jedi, sa phrase culte digne de mème qui a transcendé les films, et sa représentation du leadership alien dans la Rébellion qui préfigurait la gouvernance inclusive de la Nouvelle République.',
    es: 'La minifigura LEGO del Almirante Ackbar retrata al legendario comandante militar Mon Calamari con su distintiva piel color salmón, ojos grandes, y uniforme blanco de la Alianza Rebelde que lo marcaba como comandante supremo de la flota de la Alianza. Esta minifigura presenta impresión detallada mostrando las insignias de almirante de Ackbar y los característicos rasgos faciales Mon Calamari, representando al brillante táctico que lideró la flota Rebelde a la victoria en la Batalla de Endor. Conocido por su famosa advertencia "¡Es una trampa!" durante el asalto a la Estrella de la Muerte y sus décadas de servicio luchando contra la tiranía Imperial, Ackbar encarnó a las diversas especies unidas contra el régimen humano-céntrico del Imperio. Lanzada en sets desde 2009 incluyendo Home One y varias construcciones de flota Rebelde, esta minifigura se volvió altamente coleccionable entre fans de Star Wars, buscada debido al estatus icónico de Ackbar en El Retorno del Jedi, su frase pegadiza digna de meme que trascendió las películas, y su representación de liderazgo alienígena en la Rebelión que presagió la gobernanza inclusiva de la Nueva República.'
  },
  {
    no: 'sw0271',
    name: 'Mon Mothma',
    en: 'Mon Mothma\'s LEGO minifigure captures the dignified leader of the Rebel Alliance with her distinctive white robes, serene expression, and the commanding presence that made her the political heart of the Rebellion. This minifigure features detailed printing showing her elegant senatorial attire, representing the former Imperial Senator who sacrificed her privileged position to lead the fight for freedom and democracy. As Supreme Commander of the Alliance and architect of the Rebellion\'s political structure, Mon Mothma provided the moral authority and strategic vision that transformed scattered resistance cells into a unified force capable of challenging the Empire. Released in sets from 2009 onwards including Home One command center builds, this minifigure appeals to collectors seeking Rebel leadership figures, highly collectible due to Mon Mothma\'s pivotal role in Return of the Jedi\'s briefing scene, her representation of principled resistance to tyranny, and her status as one of Star Wars\' most powerful female leaders who shaped galactic politics across multiple eras.',
    de: 'Die LEGO-Minifigur von Mon Mothma fängt die würdevolle Anführerin der Rebellen-Allianz mit ihren markanten weißen Roben, gelassenen Ausdruck und der befehlenden Präsenz ein, die sie zum politischen Herzen der Rebellion machte. Diese Minifigur verfügt über detaillierte Bedruckung, die ihre elegante senatorielle Kleidung zeigt, die die ehemalige imperiale Senatorin repräsentiert, die ihre privilegierte Position opferte, um den Kampf für Freiheit und Demokratie anzuführen. Als Oberbefehlshaberin der Allianz und Architektin der politischen Struktur der Rebellion lieferte Mon Mothma die moralische Autorität und strategische Vision, die verstreute Widerstandszellen in eine vereinte Kraft verwandelte, die in der Lage war, das Imperium herauszufordern. In Sets ab 2009 veröffentlicht, einschließlich Home One-Kommandozentrum-Builds, spricht diese Minifigur Sammler an, die Rebellenführungsfiguren suchen, hochgradig sammelwürdig aufgrund von Mon Mothmas entscheidender Rolle in der Briefing-Szene von Die Rückkehr der Jedi-Ritter, ihrer Darstellung prinzipientreuen Widerstands gegen Tyrannei und ihres Status als eine von Star Wars\' mächtigsten weiblichen Anführerinnen, die galaktische Politik über mehrere Epochen hinweg prägten.',
    fr: 'La minifigurine LEGO de Mon Mothma capture la leader digne de l\'Alliance Rebelle avec ses robes blanches distinctives, son expression sereine, et la présence commandante qui en a fait le cœur politique de la Rébellion. Cette minifigurine présente une impression détaillée montrant sa tenue sénatoriale élégante, représentant l\'ancienne Sénatrice Impériale qui a sacrifié sa position privilégiée pour mener le combat pour la liberté et la démocratie. En tant que Commandante Suprême de l\'Alliance et architecte de la structure politique de la Rébellion, Mon Mothma a fourni l\'autorité morale et la vision stratégique qui ont transformé des cellules de résistance dispersées en une force unifiée capable de défier l\'Empire. Sortie dans des sets à partir de 2009 incluant les constructions de centre de commandement Home One, cette minifigurine plaît aux collectionneurs cherchant des figures de leadership Rebelle, hautement collectionnable en raison du rôle pivot de Mon Mothma dans la scène de briefing du Retour du Jedi, sa représentation de résistance principielle à la tyrannie, et son statut comme l\'une des leaders féminines les plus puissantes de Star Wars qui a façonné la politique galactique à travers plusieurs ères.',
    es: 'La minifigura LEGO de Mon Mothma captura a la digna líder de la Alianza Rebelde con sus distintivas túnicas blancas, expresión serena, y la presencia dominante que la hizo el corazón político de la Rebelión. Esta minifigura presenta impresión detallada mostrando su elegante atuendo senatorial, representando a la ex Senadora Imperial que sacrificó su posición privilegiada para liderar la lucha por la libertad y la democracia. Como Comandante Suprema de la Alianza y arquitecta de la estructura política de la Rebelión, Mon Mothma proporcionó la autoridad moral y visión estratégica que transformó células de resistencia dispersas en una fuerza unificada capaz de desafiar al Imperio. Lanzada en sets desde 2009 incluyendo construcciones del centro de comando Home One, esta minifigura atrae a coleccionistas buscando figuras de liderazgo Rebelde, altamente coleccionable debido al papel fundamental de Mon Mothma en la escena de información de El Retorno del Jedi, su representación de resistencia con principios a la tiranía, y su estatus como una de las líderes femeninas más poderosas de Star Wars que moldeó la política galáctica a través de múltiples eras.'
  },
  {
    no: 'sw0272',
    name: 'General Crix Madine',
    en: 'General Crix Madine\'s LEGO minifigure depicts the former Imperial officer turned Rebel commander with his distinctive beard, Rebel uniform, and the weathered appearance that reflected his experience on both sides of the Galactic Civil War. This minifigure features detailed printing showing his general\'s insignia and combat-ready attire, representing the strategic mastermind who planned the ground assault on Endor\'s shield generator. As a defector from Imperial service who brought valuable tactical knowledge to the Rebellion, Madine embodied the principled officers who chose conscience over career when confronted with Imperial atrocities. Released in sets from 2009 onwards in Rebel command center builds, this minifigure appeals to dedicated collectors seeking complete Rebel leadership rosters, sought after due to Madine\'s role in Return of the Jedi\'s crucial briefing scene, his representation of Imperial defectors who strengthened the Alliance, and his status as a deep-cut character beloved by fans who appreciate Star Wars\' extensive military hierarchy and tactical details.',
    de: 'Die LEGO-Minifigur von General Crix Madine zeigt den ehemaligen imperialen Offizier, der zum Rebellenkommandanten wurde, mit seinem markanten Bart, Rebellenuniform und dem verwitterten Aussehen, das seine Erfahrung auf beiden Seiten des Galaktischen Bürgerkriegs widerspiegelte. Diese Minifigur verfügt über detaillierte Bedruckung, die sein Generalsabzeichen und kampfbereite Kleidung zeigt, die das strategische Genie repräsentiert, das den Bodenangriff auf Endors Schildgenerator plante. Als Überläufer aus dem imperialen Dienst, der wertvolles taktisches Wissen zur Rebellion brachte, verkörperte Madine die prinzipientreuen Offiziere, die Gewissen über Karriere wählten, als sie mit imperialen Gräueltaten konfrontiert wurden. In Sets ab 2009 in Rebellenkommandozentrum-Builds veröffentlicht, spricht diese Minifigur engagierte Sammler an, die vollständige Rebellenführungs-Rosters suchen, begehrt aufgrund von Madines Rolle in der entscheidenden Briefing-Szene von Die Rückkehr der Jedi-Ritter, seiner Darstellung imperialer Überläufer, die die Allianz stärkten, und seinem Status als Deep-Cut-Charakter, der von Fans geliebt wird, die Star Wars\' umfangreiche militärische Hierarchie und taktische Details schätzen.',
    fr: 'La minifigurine LEGO du Général Crix Madine dépeint l\'ancien officier Impérial devenu commandant Rebelle avec sa barbe distinctive, son uniforme Rebelle, et l\'apparence marquée qui reflétait son expérience des deux côtés de la Guerre Civile Galactique. Cette minifigurine présente une impression détaillée montrant ses insignes de général et sa tenue prête au combat, représentant le cerveau stratégique qui a planifié l\'assaut au sol sur le générateur de bouclier d\'Endor. En tant que transfuge du service Impérial qui a apporté des connaissances tactiques précieuses à la Rébellion, Madine incarnait les officiers de principes qui ont choisi la conscience plutôt que la carrière lorsqu\'ils ont été confrontés aux atrocités Impériales. Sortie dans des sets à partir de 2009 dans les constructions de centre de commandement Rebelle, cette minifigurine plaît aux collectionneurs dédiés cherchant des listes complètes de leadership Rebelle, recherchée en raison du rôle de Madine dans la scène de briefing cruciale du Retour du Jedi, sa représentation des transfuges Impériaux qui ont renforcé l\'Alliance, et son statut de personnage profond aimé des fans qui apprécient la hiérarchie militaire étendue et les détails tactiques de Star Wars.',
    es: 'La minifigura LEGO del General Crix Madine representa al ex oficial Imperial convertido en comandante Rebelde con su distintiva barba, uniforme Rebelde, y la apariencia curtida que reflejaba su experiencia en ambos lados de la Guerra Civil Galáctica. Esta minifigura presenta impresión detallada mostrando sus insignias de general y atuendo listo para combate, representando a la mente maestra estratégica que planeó el asalto terrestre al generador de escudo de Endor. Como desertor del servicio Imperial que trajo valioso conocimiento táctico a la Rebelión, Madine encarnó a los oficiales con principios que eligieron conciencia sobre carrera cuando se enfrentaron a atrocidades Imperiales. Lanzada en sets desde 2009 en construcciones de centro de comando Rebelde, esta minifigura atrae a coleccionistas dedicados buscando listados completos de liderazgo Rebelde, buscada debido al papel de Madine en la crucial escena de información de El Retorno del Jedi, su representación de desertores Imperiales que fortalecieron la Alianza, y su estatus como personaje de corte profundo amado por fans que aprecian la extensa jerarquía militar y detalles tácticos de Star Wars.'
  },
  {
    no: 'sw0273',
    name: 'Wicket W. Warrick',
    en: 'Wicket W. Warrick\'s LEGO minifigure captures the brave young Ewok scout with his distinctive brown and tan fur pattern, leather hood, and the endearing appearance that made him the most recognizable individual Ewok in Star Wars lore. This minifigure features detailed printing showing Wicket\'s characteristic hood and spear, representing the curious scout who befriended Princess Leia and convinced his tribe to join the Rebel Alliance against the Empire. As the Ewok who bridged the gap between his primitive forest tribe and the technologically advanced Rebellion, Wicket demonstrated that courage and friendship could transcend cultural and technological barriers. Released in sets from 2009 onwards including Ewok Village and AT-ST battle scenarios, this minifigure became the most collectible Ewok variant, highly sought after due to Wicket\'s starring role in Return of the Jedi, his status as the franchise\'s most famous Ewok, and his representation of unlikely heroes whose bravery proved decisive in the Empire\'s ultimate defeat.',
    de: 'Die LEGO-Minifigur von Wicket W. Warrick fängt den tapferen jungen Ewok-Kundschafter mit seinem markanten braun-beigen Fellmuster, Lederkapuze und dem liebenswerten Aussehen ein, das ihn zum bekanntesten individuellen Ewok in der Star Wars-Überlieferung machte. Diese Minifigur verfügt über detaillierte Bedruckung, die Wickets charakteristische Kapuze und Speer zeigt, die den neugierigen Kundschafter repräsentiert, der sich mit Prinzessin Leia anfreundete und seinen Stamm überzeugte, sich der Rebellen-Allianz gegen das Imperium anzuschließen. Als der Ewok, der die Kluft zwischen seinem primitiven Waldstamm und der technologisch fortgeschrittenen Rebellion überbrückte, demonstrierte Wicket, dass Mut und Freundschaft kulturelle und technologische Barrieren überschreiten konnten. In Sets ab 2009 veröffentlicht, einschließlich Ewok-Dorf und AT-ST-Kampfszenarien, wurde diese Minifigur zur sammelwürdigsten Ewok-Variante, hochgradig begehrt aufgrund von Wickets Hauptrolle in Die Rückkehr der Jedi-Ritter, seinem Status als bekanntester Ewok des Franchise und seiner Darstellung unwahrscheinlicher Helden, deren Tapferkeit sich bei der ultimativen Niederlage des Imperiums als entscheidend erwies.',
    fr: 'La minifigurine LEGO de Wicket W. Warrick capture le jeune éclaireur Ewok courageux avec son motif de fourrure brun et beige distinctif, sa capuche en cuir, et l\'apparence attachante qui en a fait l\'Ewok individuel le plus reconnaissable de la tradition Star Wars. Cette minifigurine présente une impression détaillée montrant la capuche et la lance caractéristiques de Wicket, représentant l\'éclaireur curieux qui s\'est lié d\'amitié avec la Princesse Leia et a convaincu sa tribu de rejoindre l\'Alliance Rebelle contre l\'Empire. En tant qu\'Ewok qui a comblé le fossé entre sa tribu forestière primitive et la Rébellion technologiquement avancée, Wicket a démontré que le courage et l\'amitié pouvaient transcender les barrières culturelles et technologiques. Sortie dans des sets à partir de 2009 incluant le Village Ewok et les scénarios de bataille AT-ST, cette minifigurine est devenue la variante Ewok la plus collectionnable, très recherchée en raison du rôle vedette de Wicket dans Le Retour du Jedi, son statut d\'Ewok le plus célèbre de la franchise, et sa représentation de héros improbables dont le courage s\'est avéré décisif dans la défaite ultime de l\'Empire.',
    es: 'La minifigura LEGO de Wicket W. Warrick captura al valiente joven explorador Ewok con su distintivo patrón de pelaje marrón y beige, capucha de cuero, y la apariencia entrañable que lo hizo el Ewok individual más reconocible en la tradición Star Wars. Esta minifigura presenta impresión detallada mostrando la característica capucha y lanza de Wicket, representando al curioso explorador que se hizo amigo de la Princesa Leia y convenció a su tribu de unirse a la Alianza Rebelde contra el Imperio. Como el Ewok que cerró la brecha entre su tribu primitiva del bosque y la Rebelión tecnológicamente avanzada, Wicket demostró que el coraje y la amistad podían trascender barreras culturales y tecnológicas. Lanzada en sets desde 2009 incluyendo Aldea Ewok y escenarios de batalla AT-ST, esta minifigura se convirtió en la variante Ewok más coleccionable, muy buscada debido al papel protagonista de Wicket en El Retorno del Jedi, su estatus como el Ewok más famoso de la franquicia, y su representación de héroes improbables cuya valentía resultó decisiva en la derrota final del Imperio.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 161-165 (sw0269-sw0273)...\n');

  for (const m of batch) {
    await prisma.minifigCatalog.upsert({
      where: { minifigure_no: m.no },
      update: {
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      },
      create: {
        minifigure_no: m.no,
        name: m.name,
        category_id: 1,
        category_name: 'Star Wars',
        search_name: m.name.toLowerCase(),
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`  ✅ ${m.no}: ${m.name}`);
  }

  console.log('\n✨ Batch 161-165 complete: 5 minifigs (20 descriptions)');
  await prisma.$disconnect();
}

saveBatch().catch(console.error);