import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0479',
    name: 'Clone Trooper Episode 3',
    en: 'This Clone Trooper continues the standard Phase II armor design from Revenge of the Sith, representing the backbone of the Grand Army of the Republic during the final stages of the Clone Wars. The minifigure features white Phase II armor plating with black undersuit details, the advanced helmet design with improved field of vision, and detailed printing depicting armor panels and equipment. Widely distributed in Episode III sets from 2005 onward, making it one of the most common and accessible clone trooper variants. Essential for collectors building Republic military forces and recreating major battles from the fall of the Republic. The abundance of this design in sets made it the go-to option for army builders, with many collectors acquiring dozens or even hundreds for large-scale displays. These standard clones represent the tragic soldiers who would eventually become Stormtroopers, making them historically significant figures in LEGO Star Wars collecting.',
    de: 'Dieser Clone Trooper setzt das Standard-Phase-II-Rüstungsdesign aus Die Rache der Sith fort und repräsentiert das Rückgrat der Großen Armee der Republik während der Endphasen der Klonkriege. Die Minifigur zeigt weiße Phase-II-Rüstungsplattierung mit schwarzen Unteranzug-Details, das fortschrittliche Helmdesign mit verbessertem Sichtfeld und detaillierte Bedruckung, die Rüstungspaneele und Ausrüstung darstellt. Sie wurde ab 2005 weitverbreitet in Episode-III-Sets vertrieben und ist eine der häufigsten und zugänglichsten Clone-Trooper-Varianten. Unverzichtbar für Sammler, die militärische Streitkräfte der Republik aufbauen und große Schlachten vom Fall der Republik nachstellen. Die Fülle dieses Designs in Sets machte es zur bevorzugten Option für Armeebauer, wobei viele Sammler Dutzende oder sogar Hunderte für großangelegte Displays erwerben. Diese Standard-Klone repräsentieren die tragischen Soldaten, die schließlich zu Stormtroopern werden würden, was sie zu historisch bedeutenden Figuren im LEGO-Star-Wars-Sammeln macht.',
    fr: 'Ce Clone Trooper continue le design d\'armure standard de Phase II de La Revanche des Sith, représentant l\'épine dorsale de la Grande Armée de la République pendant les phases finales de la Guerre des Clones. La minifigurine présente des plaques d\'armure blanches de Phase II avec des détails de combinaison noire, le design de casque avancé avec champ de vision amélioré, et une impression détaillée représentant des panneaux d\'armure et de l\'équipement. Largement distribuée dans les sets de l\'Épisode III à partir de 2005, en faisant l\'un des variants de clone trooper les plus courants et accessibles. Essentielle pour les collectionneurs construisant des forces militaires de la République et recréant des batailles majeures de la chute de la République. L\'abondance de ce design dans les sets en a fait l\'option privilégiée pour les constructeurs d\'armées, de nombreux collectionneurs acquérant des dizaines voire des centaines pour des affichages à grande échelle. Ces clones standard représentent les soldats tragiques qui deviendraient finalement des Stormtroopers, ce qui en fait des figurines historiquement significatives dans la collection LEGO Star Wars.',
    es: 'Este Soldado Clon continúa el diseño estándar de armadura de Fase II de La Venganza de los Sith, representando la columna vertebral del Gran Ejército de la República durante las etapas finales de las Guerras Clon. La minifigura presenta placas de armadura blanca de Fase II con detalles de traje interior negro, el diseño de casco avanzado con campo de visión mejorado, e impresión detallada representando paneles de armadura y equipo. Ampliamente distribuido en sets del Episodio III desde 2005 en adelante, convirtiéndolo en una de las variantes de soldado clon más comunes y accesibles. Esencial para coleccionistas que construyen fuerzas militares de la República y recrean grandes batallas de la caída de la República. La abundancia de este diseño en sets lo convirtió en la opción preferida para constructores de ejércitos, con muchos coleccionistas adquiriendo docenas o incluso cientos para exhibiciones a gran escala. Estos clones estándar representan los trágicos soldados que eventualmente se convertirían en Stormtroopers, convirtiéndolos en figuras históricamente significativas en el coleccionismo de LEGO Star Wars.'
  },
  {
    no: 'sw0480',
    name: 'Clone Trooper Episode 3',
    en: 'This Clone Trooper variant maintains the Phase II armor design standard established in Revenge of the Sith, featuring white armor with black bodysuit printing and the refined helmet design. The minifigure represents the countless clone troopers who served across the galaxy during the Clone Wars, from Coruscant to the Outer Rim sieges. Released in multiple Episode III sets throughout 2005 and subsequent years, becoming a cornerstone figure for LEGO Star Wars collectors. The widespread availability and army-building appeal make this one of the most reproduced minifigures in the theme. Collectors value these clones for creating authentic military formations, displaying the scale of Republic forces, and recreating pivotal moments from Revenge of the Sith including Order 66. The timeless design ensures continued relevance as new Clone Wars content expands the lore, making these standard troopers perpetually valuable for collectors building comprehensive Republic armies.',
    de: 'Diese Clone Trooper-Variante behält den in Die Rache der Sith etablierten Phase-II-Rüstungsdesign-Standard bei und zeigt weiße Rüstung mit schwarzer Bodysuit-Bedruckung und dem verfeinerten Helmdesign. Die Minifigur repräsentiert die zahllosen Clone Trooper, die während der Klonkriege in der gesamten Galaxis dienten, von Coruscant bis zu den Belagerungen des Äußeren Randes. Sie wurde 2005 und in den Folgejahren in mehreren Episode-III-Sets veröffentlicht und wurde zu einer Eckpfeiler-Figur für LEGO-Star-Wars-Sammler. Die weite Verfügbarkeit und der Armeebau-Appeal machen dies zu einer der am meisten reproduzierten Minifiguren im Thema. Sammler schätzen diese Klone für die Erstellung authentischer Militärformationen, die Darstellung des Umfangs der republikanischen Streitkräfte und die Nachstellung entscheidender Momente aus Die Rache der Sith, einschließlich Order 66. Das zeitlose Design sorgt für anhaltende Relevanz, da neue Clone Wars-Inhalte die Geschichte erweitern, was diese Standard-Trooper dauerhaft wertvoll für Sammler macht, die umfassende republikanische Armeen aufbauen.',
    fr: 'Ce variant de Clone Trooper maintient le standard de design d\'armure de Phase II établi dans La Revanche des Sith, présentant une armure blanche avec une impression de combinaison noire et le design de casque raffiné. La minifigurine représente les innombrables clone troopers qui ont servi à travers la galaxie pendant la Guerre des Clones, de Coruscant aux sièges de la Bordure Extérieure. Sortie dans plusieurs sets de l\'Épisode III tout au long de 2005 et des années suivantes, devenant une figurine pierre angulaire pour les collectionneurs LEGO Star Wars. La large disponibilité et l\'attrait de construction d\'armée en font l\'une des minifigurines les plus reproduites du thème. Les collectionneurs apprécient ces clones pour créer des formations militaires authentiques, afficher l\'échelle des forces de la République, et recréer des moments cruciaux de La Revanche des Sith, y compris l\'Ordre 66. Le design intemporel assure une pertinence continue alors que de nouveaux contenus Clone Wars élargissent l\'histoire, rendant ces soldats standard perpétuellement précieux pour les collectionneurs construisant des armées de la République complètes.',
    es: 'Esta variante de Soldado Clon mantiene el estándar de diseño de armadura de Fase II establecido en La Venganza de los Sith, presentando armadura blanca con impresión de traje negro y el diseño de casco refinado. La minifigura representa los innumerables soldados clon que sirvieron a través de la galaxia durante las Guerras Clon, desde Coruscant hasta los asedios del Borde Exterior. Lanzado en múltiples sets del Episodio III durante 2005 y años posteriores, convirtiéndose en una figura angular para coleccionistas de LEGO Star Wars. La amplia disponibilidad y el atractivo de construcción de ejército la convierten en una de las minifiguras más reproducidas en el tema. Los coleccionistas valoran estos clones para crear formaciones militares auténticas, mostrar la escala de las fuerzas de la República, y recrear momentos cruciales de La Venganza de los Sith incluyendo la Orden 66. El diseño atemporal asegura relevancia continua a medida que nuevo contenido de Clone Wars expande la historia, haciendo que estos soldados estándar sean perpetuamente valiosos para coleccionistas que construyen ejércitos de la República completos.'
  },
  {
    no: 'sw0481',
    name: 'Wookiee Warrior',
    en: 'The Wookiee Warrior represents the fierce defenders of Kashyyyk who fought alongside the Republic during the Clone Wars, as depicted in Revenge of the Sith. This minifigure features brown fur printing with detailed musculature, distinctive facial features including the characteristic Wookiee expression, and often includes weapons like bowcasters or staffs. Released in various Episode III sets featuring Kashyyyk battle scenes starting in 2005. Wookiee Warriors are essential for recreating the Battle of Kashyyyk, one of the most visually impressive conflicts from Revenge of the Sith. Collectors value these figures for building Wookiee defense forces and displaying the alliance between Wookiees and Clone Troopers. The distinctive design and iconic species representation make Wookiee Warriors popular among Star Wars collectors, particularly those building comprehensive Kashyyyk battle scenes with multiple warriors defending their homeworld.',
    de: 'Der Wookiee-Krieger repräsentiert die wilden Verteidiger von Kashyyyk, die während der Klonkriege an der Seite der Republik kämpften, wie in Die Rache der Sith dargestellt. Diese Minifigur zeigt braune Fellbedruckung mit detaillierter Muskulatur, charakteristische Gesichtszüge einschließlich des typischen Wookiee-Ausdrucks und enthält oft Waffen wie Armbrüste oder Stäbe. Sie wurde ab 2005 in verschiedenen Episode-III-Sets mit Kashyyyk-Kampfszenen veröffentlicht. Wookiee-Krieger sind unverzichtbar für die Nachstellung der Schlacht von Kashyyyk, einem der visuell beeindruckendsten Konflikte aus Die Rache der Sith. Sammler schätzen diese Figuren für den Aufbau von Wookiee-Verteidigungskräften und die Darstellung der Allianz zwischen Wookiees und Clone Troopers. Das charakteristische Design und die ikonische Spezies-Darstellung machen Wookiee-Krieger bei Star Wars-Sammlern beliebt, insbesondere bei denen, die umfassende Kashyyyk-Kampfszenen mit mehreren Kriegern aufbauen, die ihre Heimatwelt verteidigen.',
    fr: 'Le Guerrier Wookiee représente les féroces défenseurs de Kashyyyk qui ont combattu aux côtés de la République pendant la Guerre des Clones, tel que représenté dans La Revanche des Sith. Cette minifigurine présente une impression de fourrure brune avec une musculature détaillée, des traits faciaux distinctifs incluant l\'expression caractéristique des Wookiees, et inclut souvent des armes comme des arbalètes ou des bâtons. Sortie dans divers sets de l\'Épisode III présentant des scènes de bataille de Kashyyyk à partir de 2005. Les Guerriers Wookiees sont essentiels pour recréer la Bataille de Kashyyyk, l\'un des conflits les plus visuellement impressionnants de La Revanche des Sith. Les collectionneurs apprécient ces figurines pour construire des forces de défense Wookiees et afficher l\'alliance entre Wookiees et Clone Troopers. Le design distinctif et la représentation d\'espèce emblématique rendent les Guerriers Wookiees populaires parmi les collectionneurs Star Wars, en particulier ceux construisant des scènes de bataille complètes de Kashyyyk avec plusieurs guerriers défendant leur monde natal.',
    es: 'El Guerrero Wookiee representa a los feroces defensores de Kashyyyk que lucharon junto a la República durante las Guerras Clon, como se representa en La Venganza de los Sith. Esta minifigura presenta impresión de pelaje marrón con musculatura detallada, características faciales distintivas incluyendo la expresión característica de los Wookiees, y a menudo incluye armas como ballestas o bastones. Lanzado en varios sets del Episodio III que presentan escenas de batalla de Kashyyyk a partir de 2005. Los Guerreros Wookiee son esenciales para recrear la Batalla de Kashyyyk, uno de los conflictos más visualmente impresionantes de La Venganza de los Sith. Los coleccionistas valoran estas figuras para construir fuerzas de defensa Wookiee y mostrar la alianza entre Wookiees y Soldados Clon. El diseño distintivo y la representación de especie icónica hacen que los Guerreros Wookiee sean populares entre los coleccionistas de Star Wars, particularmente aquellos que construyen escenas de batalla completas de Kashyyyk con múltiples guerreros defendiendo su mundo natal.'
  },
  {
    no: 'sw0482',
    name: 'Grievous\' Bodyguard',
    en: 'Grievous\' Bodyguard, also known as MagnaGuard, is an elite combat droid that serves as General Grievous\' personal protection detail during the Clone Wars. This minifigure features the distinctive elongated head design, gray and burgundy coloring, flowing cape piece, and often includes electrostaff weapons. Released in sets featuring General Grievous starting in 2005, particularly in the Grievous Starfighter and related Episode III sets. These MagnaGuards represent some of the most formidable droid warriors in the Separatist army, trained in lightsaber combat and capable of battling Jedi. Collectors value Grievous\' Bodyguards for their unique design, intimidating appearance, and role as elite antagonists. Multiple MagnaGuards enhance Grievous displays and Clone Wars battle scenes. The distinctive cape and electrostaff accessories make these figures stand out visually, while their combat prowess in Star Wars lore adds to their appeal among collectors building Separatist forces.',
    de: 'Grievous\' Leibwächter, auch bekannt als MagnaGuard, ist ein Elite-Kampfdroide, der während der Klonkriege als persönlicher Schutz von General Grievous dient. Diese Minifigur zeigt das charakteristische längliche Kopfdesign, grau-burgunderfarbene Färbung, ein fließendes Umhangteil und enthält oft Elektrostab-Waffen. Sie wurde ab 2005 in Sets mit General Grievous veröffentlicht, insbesondere im Grievous Starfighter und verwandten Episode-III-Sets. Diese MagnaGuards repräsentieren einige der beeindruckendsten Droiden-Krieger in der Separatisten-Armee, ausgebildet im Lichtschwertkampf und in der Lage, Jedi zu bekämpfen. Sammler schätzen Grievous\' Leibwächter für ihr einzigartiges Design, einschüchterndes Aussehen und ihre Rolle als Elite-Antagonisten. Mehrere MagnaGuards verbessern Grievous-Displays und Clone Wars-Kampfszenen. Der charakteristische Umhang und die Elektrostab-Zubehörteile lassen diese Figuren visuell hervorstechen, während ihre Kampfkraft in der Star Wars-Geschichte ihre Attraktivität bei Sammlern erhöht, die Separatisten-Streitkräfte aufbauen.',
    fr: 'Le Garde du Corps de Grievous, également connu sous le nom de MagnaGuard, est un droïde de combat d\'élite qui sert de détail de protection personnelle du Général Grievous pendant la Guerre des Clones. Cette minifigurine présente le design de tête allongée distinctif, une coloration grise et bordeaux, une pièce de cape fluide, et inclut souvent des armes électro-bâton. Sortie dans des sets mettant en vedette le Général Grievous à partir de 2005, en particulier dans le Chasseur Stellaire de Grievous et les sets connexes de l\'Épisode III. Ces MagnaGuards représentent certains des guerriers droïdes les plus redoutables de l\'armée Séparatiste, formés au combat au sabre laser et capables de combattre les Jedi. Les collectionneurs apprécient les Gardes du Corps de Grievous pour leur design unique, leur apparence intimidante et leur rôle d\'antagonistes d\'élite. Plusieurs MagnaGuards améliorent les affichages de Grievous et les scènes de bataille des Clone Wars. La cape distinctive et les accessoires électro-bâton font ressortir visuellement ces figurines, tandis que leur prouesse au combat dans la tradition Star Wars ajoute à leur attrait parmi les collectionneurs construisant des forces Séparatistes.',
    es: 'El Guardaespaldas de Grievous, también conocido como MagnaGuard, es un droide de combate de élite que sirve como detalle de protección personal del General Grievous durante las Guerras Clon. Esta minifigura presenta el distintivo diseño de cabeza alargada, coloración gris y burdeos, pieza de capa fluida, y a menudo incluye armas de bastón eléctrico. Lanzado en sets que presentan al General Grievous a partir de 2005, particularmente en el Caza Estelar de Grievous y sets relacionados del Episodio III. Estos MagnaGuards representan algunos de los guerreros droide más formidables en el ejército Separatista, entrenados en combate con sables de luz y capaces de luchar contra Jedi. Los coleccionistas valoran los Guardaespaldas de Grievous por su diseño único, apariencia intimidante y papel como antagonistas de élite. Múltiples MagnaGuards mejoran las exhibiciones de Grievous y escenas de batalla de las Guerras Clon. La capa distintiva y los accesorios de bastón eléctrico hacen que estas figuras se destaquen visualmente, mientras que su destreza de combate en la tradición de Star Wars añade a su atractivo entre coleccionistas que construyen fuerzas Separatistas.'
  },
  {
    no: 'sw0483',
    name: 'Obi-Wan Kenobi (Padawan)',
    en: 'This Padawan version of Obi-Wan Kenobi represents the young Jedi apprentice as seen in The Phantom Menace, before he became a Jedi Knight. The minifigure features Obi-Wan\'s distinctive Padawan hairstyle with the braided tail, brown and tan Jedi robes with detailed printing, and typically includes a blue lightsaber. Released in Episode I-themed sets from 2005 onward, particularly in sets depicting the Battle of Naboo and Qui-Gon\'s missions. This version captures Obi-Wan at the beginning of his legendary journey, showing him as Qui-Gon Jinn\'s apprentice before he trained Anakin Skywalker. Highly collectible for fans tracking Obi-Wan\'s evolution throughout the saga, and essential for recreating key Phantom Menace moments including the Duel of the Fates. The Padawan design with its distinctive hair piece and youthful appearance makes this Obi-Wan variant particularly desirable for collectors building comprehensive character collections across different eras.',
    de: 'Diese Padawan-Version von Obi-Wan Kenobi repräsentiert den jungen Jedi-Lehrling, wie er in Die dunkle Bedrohung zu sehen ist, bevor er ein Jedi-Ritter wurde. Die Minifigur zeigt Obi-Wans charakteristische Padawan-Frisur mit dem geflochtenen Zopf, braune und beige Jedi-Roben mit detaillierter Bedruckung und enthält typischerweise ein blaues Lichtschwert. Sie wurde ab 2005 in Episode-I-thematischen Sets veröffentlicht, insbesondere in Sets, die die Schlacht von Naboo und Qui-Gons Missionen darstellen. Diese Version fängt Obi-Wan am Beginn seiner legendären Reise ein und zeigt ihn als Qui-Gon Jinns Lehrling, bevor er Anakin Skywalker trainierte. Sehr sammelwürdig für Fans, die Obi-Wans Entwicklung durch die gesamte Saga verfolgen, und unverzichtbar für die Nachstellung wichtiger Momente aus Die dunkle Bedrohung, einschließlich des Duells der Schicksale. Das Padawan-Design mit seinem charakteristischen Haarteil und jugendlichen Aussehen macht diese Obi-Wan-Variante besonders begehrenswert für Sammler, die umfassende Charaktersammlungen über verschiedene Epochen hinweg aufbauen.',
    fr: 'Cette version Padawan d\'Obi-Wan Kenobi représente le jeune apprenti Jedi tel qu\'il apparaît dans La Menace Fantôme, avant qu\'il ne devienne un Chevalier Jedi. La minifigurine présente la coiffure distinctive de Padawan d\'Obi-Wan avec la queue tressée, des robes Jedi brunes et beiges avec impression détaillée, et inclut généralement un sabre laser bleu. Sortie dans des sets à thème de l\'Épisode I à partir de 2005, en particulier dans des sets représentant la Bataille de Naboo et les missions de Qui-Gon. Cette version capture Obi-Wan au début de son voyage légendaire, le montrant comme l\'apprenti de Qui-Gon Jinn avant qu\'il n\'entraîne Anakin Skywalker. Hautement collectionnable pour les fans suivant l\'évolution d\'Obi-Wan tout au long de la saga, et essentiel pour recréer des moments clés de La Menace Fantôme, y compris le Duel des Destins. Le design Padawan avec sa pièce de cheveux distinctive et son apparence juvénile rend ce variant d\'Obi-Wan particulièrement désirable pour les collectionneurs construisant des collections de personnages complètes à travers différentes époques.',
    es: 'Esta versión Padawan de Obi-Wan Kenobi representa al joven aprendiz Jedi como se ve en La Amenaza Fantasma, antes de convertirse en un Caballero Jedi. La minifigura presenta el distintivo peinado Padawan de Obi-Wan con la cola trenzada, túnicas Jedi marrones y beige con impresión detallada, y típicamente incluye un sable de luz azul. Lanzado en sets temáticos del Episodio I desde 2005 en adelante, particularmente en sets que representan la Batalla de Naboo y las misiones de Qui-Gon. Esta versión captura a Obi-Wan al comienzo de su viaje legendario, mostrándolo como el aprendiz de Qui-Gon Jinn antes de entrenar a Anakin Skywalker. Altamente coleccionable para fanáticos que siguen la evolución de Obi-Wan a lo largo de la saga, y esencial para recrear momentos clave de La Amenaza Fantasma incluyendo el Duelo de los Destinos. El diseño Padawan con su pieza de cabello distintiva y apariencia juvenil hace que esta variante de Obi-Wan sea particularmente deseable para coleccionistas que construyen colecciones de personajes completas a través de diferentes eras.'
  },
  {
    no: 'sw0484',
    name: 'Qui-Gon Jinn',
    en: 'Qui-Gon Jinn is the wise Jedi Master who discovered Anakin Skywalker and served as Obi-Wan Kenobi\'s mentor in The Phantom Menace. This minifigure features Qui-Gon\'s distinctive long brown hair, detailed facial printing with beard, tan and brown Jedi robes with intricate printing, and a green lightsaber. Released in multiple Episode I sets starting in 2005, including the Naboo Swamp scene and Duel with Darth Maul sets. Qui-Gon represents a pivotal figure in Star Wars lore, whose discovery of Anakin set in motion the events of the entire saga. Essential for collectors recreating The Phantom Menace storyline and the legendary Duel of the Fates against Darth Maul. The character\'s tragic fate and profound influence on the Jedi Order make this minifigure highly desirable. Qui-Gon\'s unique philosophy and maverick nature within the Jedi Council add depth to displays, making him a cornerstone figure for any Prequel Trilogy collection.',
    de: 'Qui-Gon Jinn ist der weise Jedi-Meister, der Anakin Skywalker entdeckte und als Obi-Wan Kenobis Mentor in Die dunkle Bedrohung diente. Diese Minifigur zeigt Qui-Gons charakteristisches langes braunes Haar, detaillierte Gesichtsbedruckung mit Bart, beige und braune Jedi-Roben mit aufwendiger Bedruckung und ein grünes Lichtschwert. Sie wurde ab 2005 in mehreren Episode-I-Sets veröffentlicht, darunter die Naboo-Sumpf-Szene und Duell mit Darth Maul-Sets. Qui-Gon repräsentiert eine zentrale Figur in der Star Wars-Geschichte, dessen Entdeckung von Anakin die Ereignisse der gesamten Saga in Gang setzte. Unverzichtbar für Sammler, die die Geschichte von Die dunkle Bedrohung nachstellen, und das legendäre Duell der Schicksale gegen Darth Maul. Das tragische Schicksal der Figur und ihr tiefgreifender Einfluss auf den Jedi-Orden machen diese Minifigur sehr begehrenswert. Qui-Gons einzigartige Philosophie und rebellische Natur innerhalb des Jedi-Rates verleihen Displays Tiefe und machen ihn zu einer Eckpfeiler-Figur für jede Prequel-Trilogie-Sammlung.',
    fr: 'Qui-Gon Jinn est le sage Maître Jedi qui a découvert Anakin Skywalker et a servi de mentor à Obi-Wan Kenobi dans La Menace Fantôme. Cette minifigurine présente les longs cheveux bruns distinctifs de Qui-Gon, une impression faciale détaillée avec barbe, des robes Jedi beiges et brunes avec impression complexe, et un sabre laser vert. Sortie dans plusieurs sets de l\'Épisode I à partir de 2005, y compris la scène du Marais de Naboo et les sets de Duel avec Dark Maul. Qui-Gon représente une figure centrale dans la tradition Star Wars, dont la découverte d\'Anakin a mis en mouvement les événements de toute la saga. Essentiel pour les collectionneurs recréant l\'histoire de La Menace Fantôme et le légendaire Duel des Destins contre Dark Maul. Le destin tragique du personnage et son influence profonde sur l\'Ordre Jedi rendent cette minifigurine très désirable. La philosophie unique de Qui-Gon et sa nature indépendante au sein du Conseil Jedi ajoutent de la profondeur aux affichages, faisant de lui une figurine pierre angulaire pour toute collection de la Trilogie Préquelle.',
    es: 'Qui-Gon Jinn es el sabio Maestro Jedi que descubrió a Anakin Skywalker y sirvió como mentor de Obi-Wan Kenobi en La Amenaza Fantasma. Esta minifigura presenta el distintivo cabello largo marrón de Qui-Gon, impresión facial detallada con barba, túnicas Jedi beige y marrones con impresión intrincada, y un sable de luz verde. Lanzado en múltiples sets del Episodio I a partir de 2005, incluyendo la escena del Pantano de Naboo y sets de Duelo con Darth Maul. Qui-Gon representa una figura fundamental en la tradición de Star Wars, cuyo descubrimiento de Anakin puso en movimiento los eventos de toda la saga. Esencial para coleccionistas que recrean la historia de La Amenaza Fantasma y el legendario Duelo de los Destinos contra Darth Maul. El destino trágico del personaje y su profunda influencia en la Orden Jedi hacen que esta minifigura sea altamente deseable. La filosofía única de Qui-Gon y su naturaleza independiente dentro del Consejo Jedi añaden profundidad a las exhibiciones, convirtiéndolo en una figura angular para cualquier colección de la Trilogía Precuela.'
  },
  {
    no: 'sw0485',
    name: 'Darth Maul',
    en: 'Darth Maul is the fearsome Sith Lord apprentice to Darth Sidious, known for his distinctive red and black facial tattoos and double-bladed lightsaber in The Phantom Menace. This minifigure features Maul\'s iconic horned head with detailed red and black printing, black Sith robes with printing details, and a red double-bladed lightsaber accessory. Released in numerous Episode I sets starting in 2005, particularly in sets depicting the Duel of the Fates on Naboo. Darth Maul became an instant icon of the Prequel Trilogy, representing the return of the Sith after centuries in hiding. Highly sought after by collectors for his striking visual design and role as one of Star Wars\' most memorable villains. The double-bladed lightsaber and unique head printing make this figure instantly recognizable. Essential for recreating the climactic lightsaber duel with Qui-Gon and Obi-Wan, and a cornerstone figure for any Sith or villain collection.',
    de: 'Darth Maul ist der furchteinflößende Sith-Lord-Lehrling von Darth Sidious, bekannt für seine charakteristischen rot-schwarzen Gesichtstätowierungen und sein doppelklingiges Lichtschwert in Die dunkle Bedrohung. Diese Minifigur zeigt Mauls ikonischen gehörnten Kopf mit detaillierter rot-schwarzer Bedruckung, schwarze Sith-Roben mit Bedruckungsdetails und ein rotes doppelklingiges Lichtschwert-Zubehör. Sie wurde ab 2005 in zahlreichen Episode-I-Sets veröffentlicht, insbesondere in Sets, die das Duell der Schicksale auf Naboo darstellen. Darth Maul wurde zu einer sofortigen Ikone der Prequel-Trilogie und repräsentiert die Rückkehr der Sith nach jahrhundertelanger Verborgenheit. Sehr begehrt bei Sammlern wegen seines auffälligen visuellen Designs und seiner Rolle als einer der denkwürdigsten Bösewichte von Star Wars. Das doppelklingige Lichtschwert und die einzigartige Kopfbedruckung machen diese Figur sofort erkennbar. Unverzichtbar für die Nachstellung des klimatischen Lichtschwertkampfes mit Qui-Gon und Obi-Wan und eine Eckpfeiler-Figur für jede Sith- oder Bösewicht-Sammlung.',
    fr: 'Dark Maul est le redoutable apprenti Seigneur Sith de Dark Sidious, connu pour ses tatouages faciaux rouges et noirs distinctifs et son sabre laser à double lame dans La Menace Fantôme. Cette minifigurine présente la tête emblématique à cornes de Maul avec impression rouge et noire détaillée, des robes Sith noires avec détails d\'impression, et un accessoire de sabre laser à double lame rouge. Sortie dans de nombreux sets de l\'Épisode I à partir de 2005, en particulier dans des sets représentant le Duel des Destins sur Naboo. Dark Maul est devenu une icône instantanée de la Trilogie Préquelle, représentant le retour des Sith après des siècles de clandestinité. Très recherché par les collectionneurs pour son design visuel saisissant et son rôle comme l\'un des méchants les plus mémorables de Star Wars. Le sabre laser à double lame et l\'impression de tête unique rendent cette figurine instantanément reconnaissable. Essentielle pour recréer le duel au sabre laser final avec Qui-Gon et Obi-Wan, et une figurine pierre angulaire pour toute collection de Sith ou de méchants.',
    es: 'Darth Maul es el temible aprendiz de Señor Sith de Darth Sidious, conocido por sus distintivos tatuajes faciales rojos y negros y su sable de luz de doble hoja en La Amenaza Fantasma. Esta minifigura presenta la icónica cabeza con cuernos de Maul con impresión roja y negra detallada, túnicas Sith negras con detalles de impresión, y un accesorio de sable de luz de doble hoja rojo. Lanzado en numerosos sets del Episodio I a partir de 2005, particularmente en sets que representan el Duelo de los Destinos en Naboo. Darth Maul se convirtió en un ícono instantáneo de la Trilogía Precuela, representando el regreso de los Sith después de siglos ocultos. Muy buscado por coleccionistas por su llamativo diseño visual y su papel como uno de los villanos más memorables de Star Wars. El sable de luz de doble hoja y la impresión de cabeza única hacen que esta figura sea instantáneamente reconocible. Esencial para recrear el duelo climático con sables de luz con Qui-Gon y Obi-Wan, y una figura angular para cualquier colección de Sith o villanos.'
  },
  {
    no: 'sw0486',
    name: 'Battle Droid',
    en: 'The Battle Droid is the standard infantry unit of the Separatist Droid Army, mass-produced to serve as the primary fighting force during the Clone Wars. This minifigure features tan coloring representing the desert/standard variant, distinctive thin mechanical body design, articulated limbs, and the characteristic head with antenna. Released in countless sets throughout the LEGO Star Wars theme since 1999, making it one of the most produced Star Wars minifigures ever. Battle Droids are essential for army building Separatist forces and recreating Clone Wars battles across all eras. Despite being individually weak in Star Wars lore, their strength lies in numbers, making them perfect for mass army building. Collectors often acquire dozens or hundreds of Battle Droids to achieve authentic battle scale. The simple but iconic design and widespread availability make Battle Droids a foundational element of any Clone Wars or Prequel Trilogy collection, representing the faceless mechanical antagonists that opposed the Clone Army.',
    de: 'Der Kampfdroide ist die Standard-Infanterieeinheit der Separatisten-Droiden-Armee, massenweise produziert, um während der Klonkriege als primäre Kampftruppe zu dienen. Diese Minifigur zeigt beige Färbung, die die Wüsten-/Standardvariante repräsentiert, charakteristisches dünnes mechanisches Körperdesign, artikulierte Gliedmaßen und den typischen Kopf mit Antenne. Sie wurde seit 1999 in unzähligen Sets im gesamten LEGO-Star-Wars-Thema veröffentlicht, was sie zu einer der am meisten produzierten Star Wars-Minifiguren aller Zeiten macht. Kampfdroiden sind unverzichtbar für den Armeeaufbau von Separatisten-Streitkräften und die Nachstellung von Klonkriegs-Schlachten über alle Epochen hinweg. Obwohl sie in der Star Wars-Geschichte einzeln schwach sind, liegt ihre Stärke in der Masse, was sie perfekt für massenhaften Armeeaufbau macht. Sammler erwerben oft Dutzende oder Hunderte von Kampfdroiden, um authentischen Schlachtmaßstab zu erreichen. Das einfache aber ikonische Design und die weitverbreitete Verfügbarkeit machen Kampfdroiden zu einem grundlegenden Element jeder Clone Wars- oder Prequel-Trilogie-Sammlung und repräsentieren die gesichtslosen mechanischen Antagonisten, die der Klon-Armee gegenüberstanden.',
    fr: 'Le Droïde de Combat est l\'unité d\'infanterie standard de l\'Armée Droïde Séparatiste, produit en masse pour servir de force de combat principale pendant la Guerre des Clones. Cette minifigurine présente une coloration beige représentant la variante désert/standard, un design de corps mécanique mince distinctif, des membres articulés, et la tête caractéristique avec antenne. Sortie dans d\'innombrables sets tout au long du thème LEGO Star Wars depuis 1999, en faisant l\'une des minifigurines Star Wars les plus produites de tous les temps. Les Droïdes de Combat sont essentiels pour construire des armées de forces Séparatistes et recréer des batailles des Clone Wars à travers toutes les époques. Bien qu\'individuellement faibles dans la tradition Star Wars, leur force réside dans le nombre, ce qui les rend parfaits pour la construction d\'armées de masse. Les collectionneurs acquièrent souvent des dizaines ou des centaines de Droïdes de Combat pour atteindre une échelle de bataille authentique. Le design simple mais emblématique et la large disponibilité font des Droïdes de Combat un élément fondamental de toute collection Clone Wars ou Trilogie Préquelle, représentant les antagonistes mécaniques sans visage qui s\'opposaient à l\'Armée Clone.',
    es: 'El Droide de Batalla es la unidad de infantería estándar del Ejército Droide Separatista, producido en masa para servir como la fuerza de combate principal durante las Guerras Clon. Esta minifigura presenta coloración beige que representa la variante desierto/estándar, distintivo diseño de cuerpo mecánico delgado, extremidades articuladas, y la característica cabeza con antena. Lanzado en innumerables sets a lo largo del tema de LEGO Star Wars desde 1999, convirtiéndolo en una de las minifiguras de Star Wars más producidas de todos los tiempos. Los Droides de Batalla son esenciales para construir ejércitos de fuerzas Separatistas y recrear batallas de las Guerras Clon a través de todas las eras. A pesar de ser individualmente débiles en la tradición de Star Wars, su fuerza reside en los números, haciéndolos perfectos para construcción de ejércitos en masa. Los coleccionistas a menudo adquieren docenas o cientos de Droides de Batalla para lograr escala de batalla auténtica. El diseño simple pero icónico y la amplia disponibilidad hacen que los Droides de Batalla sean un elemento fundamental de cualquier colección de Clone Wars o Trilogía Precuela, representando los antagonistas mecánicos sin rostro que se opusieron al Ejército Clon.'
  },
  {
    no: 'sw0487',
    name: 'Pit Droid',
    en: 'The Pit Droid is a small mechanical service droid commonly seen working on podracers in The Phantom Menace, particularly in the Mos Espa podracing sequences. This minifigure features the distinctive small orange or brown body design, large ears, retractable nose mechanism, and compact proportions that differentiate it from combat droids. Released in Episode I sets featuring podracing scenes, including Anakin\'s Podracer and various Tatooine-themed builds from 2005 onward. Pit Droids represent the civilian side of the Star Wars droid universe, serving as maintenance workers rather than soldiers. Collectors value these figures for building authentic podracing scenes and Tatooine environments. The unique small-scale design and specialized role make Pit Droids stand out in LEGO Star Wars collections. Their comedic appearance and quirky personality from The Phantom Menace add character to displays, making them essential for recreating the bustling atmosphere of podracing culture on Tatooine.',
    de: 'Der Pit-Droide ist ein kleiner mechanischer Servicedroide, der häufig bei der Arbeit an Podracern in Die dunkle Bedrohung zu sehen ist, insbesondere in den Mos Espa-Podrennen-Sequenzen. Diese Minifigur zeigt das charakteristische kleine orange oder braune Körperdesign, große Ohren, ausfahrbaren Nasenmechanismus und kompakte Proportionen, die sie von Kampfdroiden unterscheiden. Sie wurde in Episode-I-Sets mit Podrennen-Szenen veröffentlicht, darunter Anakins Podracer und verschiedene Tatooine-thematische Builds ab 2005. Pit-Droiden repräsentieren die zivile Seite des Star Wars-Droiden-Universums und dienen als Wartungsarbeiter statt als Soldaten. Sammler schätzen diese Figuren für den Bau authentischer Podrennen-Szenen und Tatooine-Umgebungen. Das einzigartige kleine Design und die spezialisierte Rolle lassen Pit-Droiden in LEGO-Star-Wars-Sammlungen hervorstechen. Ihr komisches Aussehen und ihre skurrile Persönlichkeit aus Die dunkle Bedrohung verleihen Displays Charakter und machen sie unverzichtbar für die Nachstellung der geschäftigen Atmosphäre der Podrennen-Kultur auf Tatooine.',
    fr: 'Le Droïde de Fosse est un petit droïde de service mécanique couramment vu travaillant sur les podracers dans La Menace Fantôme, en particulier dans les séquences de course de pods de Mos Espa. Cette minifigurine présente le design de corps orange ou brun petit distinctif, de grandes oreilles, un mécanisme de nez rétractable, et des proportions compactes qui le différencient des droïdes de combat. Sortie dans des sets de l\'Épisode I présentant des scènes de course de pods, y compris le Podracer d\'Anakin et diverses constructions à thème Tatooine à partir de 2005. Les Droïdes de Fosse représentent le côté civil de l\'univers des droïdes Star Wars, servant de travailleurs de maintenance plutôt que de soldats. Les collectionneurs apprécient ces figurines pour construire des scènes de course de pods authentiques et des environnements Tatooine. Le design unique à petite échelle et le rôle spécialisé font ressortir les Droïdes de Fosse dans les collections LEGO Star Wars. Leur apparence comique et leur personnalité originale de La Menace Fantôme ajoutent du caractère aux affichages, les rendant essentiels pour recréer l\'atmosphère animée de la culture de course de pods sur Tatooine.',
    es: 'El Droide de Foso es un pequeño droide de servicio mecánico comúnmente visto trabajando en carreras de vainas en La Amenaza Fantasma, particularmente en las secuencias de carreras de vainas de Mos Espa. Esta minifigura presenta el distintivo diseño de cuerpo pequeño naranja o marrón, orejas grandes, mecanismo de nariz retráctil, y proporciones compactas que lo diferencian de los droides de combate. Lanzado en sets del Episodio I que presentan escenas de carreras de vainas, incluyendo el Corredor de Vainas de Anakin y varias construcciones temáticas de Tatooine desde 2005 en adelante. Los Droides de Foso representan el lado civil del universo de droides de Star Wars, sirviendo como trabajadores de mantenimiento en lugar de soldados. Los coleccionistas valoran estas figuras para construir escenas auténticas de carreras de vainas y entornos de Tatooine. El diseño único a pequeña escala y el papel especializado hacen que los Droides de Foso se destaquen en las colecciones de LEGO Star Wars. Su apariencia cómica y personalidad peculiar de La Amenaza Fantasma añaden carácter a las exhibiciones, haciéndolos esenciales para recrear la atmósfera bulliciosa de la cultura de carreras de vainas en Tatooine.'
  },
  {
    no: 'sw0488',
    name: 'Anakin Skywalker (Boy)',
    en: 'This young Anakin Skywalker minifigure represents the boy slave from Tatooine who would eventually become Darth Vader, as seen in The Phantom Menace. The figure features Anakin\'s childhood appearance with short brown hair, slave outfit with tan and gray clothing, and a youthful facial expression. Released in Episode I sets from 2005 onward, particularly in sets featuring Anakin\'s Podracer and Tatooine locations. This version captures Anakin at the pivotal moment when Qui-Gon Jinn discovered his extraordinary Force potential. Essential for collectors building the complete Anakin Skywalker timeline from childhood through his transformation into Darth Vader. The boy Anakin figure represents innocence before his fall to the dark side, making it a poignant piece for fans of the complete Star Wars saga. Highly collectible for those recreating The Phantom Menace storyline, podracing scenes, and Anakin\'s departure from Tatooine that set him on the path to becoming the galaxy\'s most infamous Sith Lord.',
    de: 'Diese junge Anakin Skywalker-Minifigur repräsentiert den Jungen-Sklaven von Tatooine, der schließlich zu Darth Vader werden würde, wie in Die dunkle Bedrohung zu sehen. Die Figur zeigt Anakins Kindheitserscheinung mit kurzem braunem Haar, Sklaven-Outfit mit beiger und grauer Kleidung und einem jugendlichen Gesichtsausdruck. Sie wurde ab 2005 in Episode-I-Sets veröffentlicht, insbesondere in Sets mit Anakins Podracer und Tatooine-Schauplätzen. Diese Version fängt Anakin in dem entscheidenden Moment ein, als Qui-Gon Jinn sein außergewöhnliches Macht-Potenzial entdeckte. Unverzichtbar für Sammler, die die vollständige Anakin Skywalker-Zeitlinie von der Kindheit bis zu seiner Verwandlung in Darth Vader aufbauen. Die Jungen-Anakin-Figur repräsentiert Unschuld vor seinem Fall zur dunklen Seite und macht sie zu einem ergreifenden Stück für Fans der vollständigen Star Wars-Saga. Sehr sammelwürdig für diejenigen, die die Geschichte von Die dunkle Bedrohung nachstellen, Podrennen-Szenen und Anakins Abschied von Tatooine, der ihn auf den Weg zum berüchtigtsten Sith-Lord der Galaxis brachte.',
    fr: 'Cette jeune minifigurine d\'Anakin Skywalker représente le garçon esclave de Tatooine qui deviendrait finalement Dark Vador, tel qu\'il apparaît dans La Menace Fantôme. La figurine présente l\'apparence d\'enfance d\'Anakin avec des cheveux bruns courts, une tenue d\'esclave avec des vêtements beiges et gris, et une expression faciale juvénile. Sortie dans des sets de l\'Épisode I à partir de 2005, en particulier dans des sets présentant le Podracer d\'Anakin et les emplacements de Tatooine. Cette version capture Anakin au moment crucial où Qui-Gon Jinn a découvert son potentiel extraordinaire dans la Force. Essentielle pour les collectionneurs construisant la chronologie complète d\'Anakin Skywalker de l\'enfance à travers sa transformation en Dark Vador. La figurine du garçon Anakin représente l\'innocence avant sa chute vers le côté obscur, en faisant une pièce poignante pour les fans de la saga Star Wars complète. Hautement collectionnable pour ceux recréant l\'histoire de La Menace Fantôme, les scènes de course de pods, et le départ d\'Anakin de Tatooine qui l\'a mis sur le chemin pour devenir le Seigneur Sith le plus infâme de la galaxie.',
    es: 'Esta minifigura del joven Anakin Skywalker representa al niño esclavo de Tatooine que eventualmente se convertiría en Darth Vader, como se ve en La Amenaza Fantasma. La figura presenta la apariencia infantil de Anakin con cabello corto marrón, atuendo de esclavo con ropa beige y gris, y una expresión facial juvenil. Lanzado en sets del Episodio I desde 2005 en adelante, particularmente en sets que presentan el Corredor de Vainas de Anakin y ubicaciones de Tatooine. Esta versión captura a Anakin en el momento crucial cuando Qui-Gon Jinn descubrió su extraordinario potencial de la Fuerza. Esencial para coleccionistas que construyen la línea de tiempo completa de Anakin Skywalker desde la infancia a través de su transformación en Darth Vader. La figura del niño Anakin representa la inocencia antes de su caída al lado oscuro, haciéndola una pieza conmovedora para fanáticos de la saga completa de Star Wars. Altamente coleccionable para aquellos que recrean la historia de La Amenaza Fantasma, escenas de carreras de vainas, y la partida de Anakin de Tatooine que lo puso en el camino para convertirse en el Señor Sith más infame de la galaxia.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 371-380 (sw0479-sw0488) - 10 minifigs...\n');

  for (const m of batch) {
    await prisma.minifigCatalog.upsert({
      where: { minifigure_no: m.no },
      update: {
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      },
      create: {
        minifigure_no: m.no,
        name: m.name,
        category_id: 1,
        category_name: 'Star Wars',
        search_name: m.name.toLowerCase(),
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`  ✅ ${m.no}: ${m.name}`);
  }

  console.log('\n✨ Batch 371-380 complete: 10 minifigs (40 descriptions)');
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
