import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0061',
    name: 'Battle Droid - Sand Red (Geonosian)',
    en: 'Battle Droid Sand Red Geonosian represents the specialized battle droids deployed by the Separatists on the desert planet Geonosis during the opening battles of the Clone Wars. This LEGO minifigure features distinctive sand red coloring adapted for the Geonosian environment, angled arms, skeletal design, and the appearance of the specialized infantry units stationed at droid factories. Released in 2002 with Attack of the Clones sets, this version captures the color-coded battle droids that fought in the arena battle and defended Separatist installations. The sand red Geonosian coloring makes this minifigure valuable for collectors army-building planet-specific Separatist forces and creating varied battle droid unit designations.',
    de: 'Kampfdroide Sandrot Geonosianisch repräsentiert die spezialisierten Kampfdroiden, die von den Separatisten auf dem Wüstenplaneten Geonosis während der Eröffnungsschlachten der Klonkriege eingesetzt wurden. Diese LEGO Minifigur zeigt charakteristische sandrote Färbung, die für die geonosianische Umgebung angepasst ist, abgewinkelte Arme, skelettartiges Design und das Aussehen der spezialisierten Infanterie-Einheiten, die in Droiden-Fabriken stationiert waren. Veröffentlicht 2002 mit Angriff-der-Klonkrieger-Sets, fängt diese Version die farbcodierten Kampfdroiden ein, die in der Arena-Schlacht kämpften und Separatisten-Installationen verteidigten. Die sandrote geonosianische Färbung macht diese Minifigur wertvoll für Sammler, die planeten-spezifische Separatisten-Streitkräfte für Armeen zusammenstellen und verschiedene Kampfdroiden-Einheiten-Bezeichnungen erstellen.',
    fr: 'Droïde de Bataille Rouge Sable Géonosien représente les droïdes de bataille spécialisés déployés par les Séparatistes sur la planète désertique Geonosis pendant les batailles d\'ouverture des Guerres des Clones. Cette minifigurine LEGO présente une coloration rouge sable distinctive adaptée pour l\'environnement géonosien, bras inclinés, design squelettique et l\'apparence des unités d\'infanterie spécialisées stationnées dans les usines de droïdes. Sortie en 2002 avec les sets L\'Attaque des Clones, cette version capture les droïdes de bataille codés par couleur qui ont combattu dans la bataille de l\'arène et défendu les installations séparatistes. La coloration géonosienne rouge sable rend cette minifigurine précieuse pour les collectionneurs assemblant des forces séparatistes spécifiques à la planète et créant des désignations d\'unités de droïdes de bataille variées.',
    es: 'Droide de Batalla Rojo Arena Geonosiano representa a los droides de batalla especializados desplegados por los Separatistas en el planeta desértico Geonosis durante las batallas de apertura de las Guerras Clon. Esta minifigura LEGO presenta distintiva coloración rojo arena adaptada para el ambiente geonosiano, brazos angulados, diseño esquelético y la apariencia de las unidades de infantería especializadas estacionadas en fábricas de droides. Lanzada en 2002 con sets de El Ataque de los Clones, esta versión captura a los droides de batalla codificados por color que lucharon en la batalla de arena y defendieron instalaciones separatistas. La coloración geonosiana rojo arena hace de esta minifigura valiosa para coleccionistas ensamblando fuerzas separatistas específicas de planeta y creando designaciones de unidades de droides de batalla variadas.'
  },
  {
    no: 'sw0062',
    name: 'Geonosian - Dark Gray',
    en: 'Geonosian in Dark Gray represents the insectoid species native to Geonosis who allied with the Separatists and operated massive droid foundries during the Clone Wars. This LEGO minifigure features the distinctive dark gray coloring, insect-like head with compound eyes, wing pieces, and the appearance of the worker caste who built battle droids. Released in 2002 with Geonosis battle sets, this version captures the hive-dwelling aliens whose collaboration with Count Dooku sparked the Clone Wars. The dark gray color and unique alien anatomy make this minifigure valuable for collectors seeking exotic species and building complete Geonosis droid factory displays.',
    de: 'Geonosianer in Dunkelgrau repräsentiert die insektoide Spezies, die auf Geonosis heimisch ist und sich mit den Separatisten verbündete und während der Klonkriege massive Droiden-Gießereien betrieb. Diese LEGO Minifigur zeigt die charakteristische dunkelgraue Färbung, insektenartigen Kopf mit Facettenaugen, Flügelteile und das Aussehen der Arbeiter-Kaste, die Kampfdroiden baute. Veröffentlicht 2002 mit Geonosis-Schlacht-Sets, fängt diese Version die Stock-bewohnenden Außerirdischen ein, deren Zusammenarbeit mit Graf Dooku die Klonkriege auslöste. Die dunkelgraue Farbe und einzigartige außerirdische Anatomie machen diese Minifigur wertvoll für Sammler, die exotische Spezies suchen und vollständige Geonosis-Droiden-Fabrik-Displays aufbauen.',
    fr: 'Géonosien en Gris Foncé représente l\'espèce insectoïde native de Geonosis qui s\'est alliée aux Séparatistes et a exploité des fonderies de droïdes massives pendant les Guerres des Clones. Cette minifigurine LEGO présente la coloration gris foncé distinctive, tête insectoïde avec yeux composés, pièces d\'ailes et l\'apparence de la caste ouvrière qui a construit des droïdes de bataille. Sortie en 2002 avec les sets de bataille de Geonosis, cette version capture les extraterrestres vivant en ruche dont la collaboration avec le Comte Dooku a déclenché les Guerres des Clones. La couleur gris foncé et l\'anatomie extraterrestre unique rendent cette minifigurine précieuse pour les collectionneurs recherchant des espèces exotiques et construisant des affichages complets d\'usines de droïdes de Geonosis.',
    es: 'Geonosiano en Gris Oscuro representa a la especie insectoide nativa de Geonosis quien se alió con los Separatistas y operó fundiciones de droides masivas durante las Guerras Clon. Esta minifigura LEGO presenta la distintiva coloración gris oscuro, cabeza tipo insecto con ojos compuestos, piezas de alas y la apariencia de la casta trabajadora que construyó droides de batalla. Lanzada en 2002 con sets de batalla de Geonosis, esta versión captura a los alienígenas habitantes de colmena cuya colaboración con el Conde Dooku desencadenó las Guerras Clon. El color gris oscuro y anatomía alienígena única hacen de esta minifigura valiosa para coleccionistas buscando especies exóticas y construyendo exhibiciones completas de fábrica de droides de Geonosis.'
  },
  {
    no: 'sw0063',
    name: 'Droideka (Destroyer Droid) - Brown, Light Gray, and Dark Gray',
    en: 'Droideka Destroyer Droid in Brown, Light Gray, and Dark Gray represents the heavily shielded rolling combat droids deployed by the Trade Federation and Separatists as elite assault units. This LEGO minifigure features the distinctive tri-colored design, specialized curved build with multiple legs, built-in twin blasters, and the menacing appearance of the most dangerous standard battle droid variant. Released in 2002 with Attack of the Clones sets, this version captures the feared droidekas that could roll into ball form and deploy energy shields. The unique construction and powerful reputation make this minifigure extremely valuable for collectors seeking specialized droid variants and army-building elite Separatist forces.',
    de: 'Droideka Zerstörer-Droide in Braun, Hellgrau und Dunkelgrau repräsentiert die schwer abgeschirmten rollenden Kampfdroiden, die von der Handelsföderation und den Separatisten als Elite-Angriffs-Einheiten eingesetzt wurden. Diese LEGO Minifigur zeigt das charakteristische dreifarbige Design, spezialisierte gebogene Bauweise mit mehreren Beinen, eingebaute Zwillings-Blaster und das bedrohliche Aussehen der gefährlichsten Standard-Kampfdroiden-Variante. Veröffentlicht 2002 mit Angriff-der-Klonkrieger-Sets, fängt diese Version die gefürchteten Droidekas ein, die sich in Kugelform rollen und Energieschilde einsetzen konnten. Die einzigartige Konstruktion und mächtige Reputation machen diese Minifigur extrem wertvoll für Sammler, die spezialisierte Droiden-Varianten suchen und Elite-Separatisten-Streitkräfte für Armeen zusammenstellen.',
    fr: 'Droideka Droïde Destructeur en Brun, Gris Clair et Gris Foncé représente les droïdes de combat roulants lourdement blindés déployés par la Fédération du Commerce et les Séparatistes comme unités d\'assaut d\'élite. Cette minifigurine LEGO présente le design tricolore distinctif, construction courbée spécialisée avec plusieurs jambes, blasters jumeaux intégrés et l\'apparence menaçante de la variante de droïde de bataille standard la plus dangereuse. Sortie en 2002 avec les sets L\'Attaque des Clones, cette version capture les droidekas redoutés qui pouvaient rouler en forme de boule et déployer des boucliers énergétiques. La construction unique et la réputation puissante rendent cette minifigurine extrêmement précieuse pour les collectionneurs recherchant des variantes de droïdes spécialisées et assemblant des forces séparatistes d\'élite.',
    es: 'Droideka Droide Destructor en Marrón, Gris Claro y Gris Oscuro representa a los droides de combate rodantes fuertemente blindados desplegados por la Federación de Comercio y Separatistas como unidades de asalto de élite. Esta minifigura LEGO presenta el distintivo diseño tricolor, construcción curva especializada con múltiples piernas, blásters gemelos incorporados y la apariencia amenazante de la variante de droide de batalla estándar más peligrosa. Lanzada en 2002 con sets de El Ataque de los Clones, esta versión captura a los temidos droidekas que podían rodar en forma de bola y desplegar escudos de energía. La construcción única y reputación poderosa hacen de esta minifigura extremadamente valiosa para coleccionistas buscando variantes de droides especializadas y ensamblando fuerzas separatistas de élite.'
  },
  {
    no: 'sw0077',
    name: 'T-16 Skyhopper Pilot - Red Helmet',
    en: 'T-16 Skyhopper Pilot with Red Helmet represents the civilian pilots who flew the Incom T-16 skyhoppers on Tatooine for sport racing and womp rat hunting. This LEGO minifigure features the distinctive red helmet, flight suit torso print, and the appearance of recreational pilots like young Luke Skywalker before joining the Rebellion. Released in 2003 with the T-16 Skyhopper set 4477, this version captures the civilian aviation culture on Tatooine that prepared pilots for later military service. The red helmet design and connection to Luke\'s backstory make this minifigure valuable for collectors building complete Tatooine civilian life displays and understanding character origins.',
    de: 'T-16 Skyhopper-Pilot mit rotem Helm repräsentiert die zivilen Piloten, die die Incom T-16 Skyhoppers auf Tatooine für Sportrennen und Womp-Ratten-Jagd flogen. Diese LEGO Minifigur zeigt den charakteristischen roten Helm, Fluganzug-Torso-Druck und das Aussehen von Freizeit-Piloten wie dem jungen Luke Skywalker vor dem Beitritt zur Rebellion. Veröffentlicht 2003 mit dem T-16 Skyhopper-Set 4477, fängt diese Version die zivile Luftfahrt-Kultur auf Tatooine ein, die Piloten für späteren Militärdienst vorbereitete. Das rote Helm-Design und die Verbindung zu Lukes Hintergrundgeschichte machen diese Minifigur wertvoll für Sammler, die vollständige Tatooine-Zivilleben-Displays aufbauen und Charakter-Ursprünge verstehen.',
    fr: 'Pilote de T-16 Skyhopper avec Casque Rouge représente les pilotes civils qui ont piloté les skyhoppers Incom T-16 sur Tatooine pour les courses sportives et la chasse aux rats womp. Cette minifigurine LEGO présente le casque rouge distinctif, impression de torse de combinaison de vol et l\'apparence des pilotes récréatifs comme le jeune Luke Skywalker avant de rejoindre la Rébellion. Sortie en 2003 avec le set T-16 Skyhopper 4477, cette version capture la culture de l\'aviation civile sur Tatooine qui a préparé les pilotes pour le service militaire ultérieur. Le design de casque rouge et la connexion à l\'histoire de Luke rendent cette minifigurine précieuse pour les collectionneurs construisant des affichages complets de vie civile de Tatooine et comprenant les origines des personnages.',
    es: 'Piloto de T-16 Skyhopper con Casco Rojo representa a los pilotos civiles quienes volaron los skyhoppers Incom T-16 en Tatooine para carreras deportivas y caza de ratas womp. Esta minifigura LEGO presenta el distintivo casco rojo, impresión de torso de traje de vuelo y la apariencia de pilotos recreativos como el joven Luke Skywalker antes de unirse a la Rebelión. Lanzada en 2003 con el set T-16 Skyhopper 4477, esta versión captura la cultura de aviación civil en Tatooine que preparó pilotos para servicio militar posterior. El diseño de casco rojo y conexión con la historia de fondo de Luke hacen de esta minifigura valiosa para coleccionistas construyendo exhibiciones completas de vida civil de Tatooine y entendiendo orígenes de personajes.'
  },
  {
    no: 'sw0078',
    name: 'Geonosian - Dark Gray, with Wings',
    en: 'Geonosian Dark Gray with Wings represents the warrior caste of the insectoid Geonosian species who could fly and fought in aerial combat during the Clone Wars. This LEGO minifigure features dark gray coloring, transparent wings allowing flight capability, insect-like anatomy, and the appearance of the more aggressive flying Geonosians. Released in 2003 with Geonosis sets, this version captures the winged warriors who defended their hive and attacked clone troopers from the air. The functional wing pieces make this minifigure valuable for collectors creating dynamic battle scenes and distinguishing between Geonosian castes and capabilities.',
    de: 'Geonosianer Dunkelgrau mit Flügeln repräsentiert die Krieger-Kaste der insektoiden geonosianischen Spezies, die fliegen konnten und während der Klonkriege in Luftkämpfen kämpften. Diese LEGO Minifigur zeigt dunkelgraue Färbung, transparente Flügel, die Flugfähigkeit ermöglichen, insektenartige Anatomie und das Aussehen der aggressiveren fliegenden Geonosianer. Veröffentlicht 2003 mit Geonosis-Sets, fängt diese Version die geflügelten Krieger ein, die ihren Stock verteidigten und Klonkrieger aus der Luft angriffen. Die funktionalen Flügelteile machen diese Minifigur wertvoll für Sammler, die dynamische Kampfszenen erstellen und zwischen geonosianischen Kasten und Fähigkeiten unterscheiden.',
    fr: 'Géonosien Gris Foncé avec Ailes représente la caste guerrière de l\'espèce géonosienne insectoïde qui pouvait voler et a combattu en combat aérien pendant les Guerres des Clones. Cette minifigurine LEGO présente une coloration gris foncé, ailes transparentes permettant la capacité de vol, anatomie insectoïde et l\'apparence des Géonosiens volants plus agressifs. Sortie en 2003 avec les sets de Geonosis, cette version capture les guerriers ailés qui ont défendu leur ruche et attaqué les clone troopers depuis les airs. Les pièces d\'ailes fonctionnelles rendent cette minifigurine précieuse pour les collectionneurs créant des scènes de bataille dynamiques et distinguant entre les castes et capacités géonosiennes.',
    es: 'Geonosiano Gris Oscuro con Alas representa a la casta guerrera de la especie geonosiana insectoide quienes podían volar y lucharon en combate aéreo durante las Guerras Clon. Esta minifigura LEGO presenta coloración gris oscuro, alas transparentes permitiendo capacidad de vuelo, anatomía tipo insecto y la apariencia de los geonosianos voladores más agresivos. Lanzada en 2003 con sets de Geonosis, esta versión captura a los guerreros alados quienes defendieron su colmena y atacaron soldados clon desde el aire. Las piezas de alas funcionales hacen de esta minifigura valiosa para coleccionistas creando escenas de batalla dinámicas y distinguiendo entre castas y capacidades geonosianas.'
  },
  {
    no: 'sw0079',
    name: 'Luke Skywalker (Jabba\'s Palace)',
    en: 'Luke Skywalker in Jabba\'s Palace outfit represents the Jedi Knight during his infiltration of the crime lord\'s palace to rescue Han Solo in Return of the Jedi. This LEGO minifigure features Luke in his black robes with brown hooded cloak disguise, representing his appearance when entering Jabba\'s court. Released in 2003 with Jabba\'s Palace sets, this version captures Luke using stealth and diplomacy before revealing his Jedi powers. The hooded cloak disguise makes this minifigure essential for collectors recreating the palace infiltration sequence and building complete Luke Skywalker mission-specific costume collections.',
    de: 'Luke Skywalker im Jabba\'s Palace-Outfit repräsentiert den Jedi-Ritter während seiner Infiltration des Palastes des Verbrecherlords, um Han Solo in Die Rückkehr der Jedi-Ritter zu retten. Diese LEGO Minifigur zeigt Luke in seinen schwarzen Roben mit brauner Kapuzenumhang-Verkleidung und repräsentiert sein Aussehen beim Betreten von Jabbas Hof. Veröffentlicht 2003 mit Jabba\'s Palace-Sets, fängt diese Version Luke ein, der Heimlichkeit und Diplomatie nutzt, bevor er seine Jedi-Kräfte enthüllt. Die Kapuzenumhang-Verkleidung macht diese Minifigur wesentlich für Sammler, die die Palast-Infiltrations-Sequenz nachstellen und vollständige Luke Skywalker-Missions-spezifische Kostüm-Sammlungen aufbauen.',
    fr: 'Luke Skywalker en Tenue de Jabba\'s Palace représente le Chevalier Jedi pendant son infiltration du palais du seigneur du crime pour sauver Han Solo dans Le Retour du Jedi. Cette minifigurine LEGO présente Luke dans ses robes noires avec déguisement de cape à capuche brune, représentant son apparence en entrant dans la cour de Jabba. Sortie en 2003 avec les sets Jabba\'s Palace, cette version capture Luke utilisant la furtivité et la diplomatie avant de révéler ses pouvoirs Jedi. Le déguisement de cape à capuche rend cette minifigurine essentielle pour les collectionneurs recréant la séquence d\'infiltration du palais et construisant des collections complètes de costumes spécifiques aux missions de Luke Skywalker.',
    es: 'Luke Skywalker en Atuendo de Jabba\'s Palace representa al Caballero Jedi durante su infiltración del palacio del señor del crimen para rescatar a Han Solo en El Retorno del Jedi. Esta minifigura LEGO presenta a Luke en sus túnicas negras con disfraz de capa con capucha marrón, representando su apariencia al entrar a la corte de Jabba. Lanzada en 2003 con sets de Jabba\'s Palace, esta versión captura a Luke usando sigilo y diplomacia antes de revelar sus poderes Jedi. El disfraz de capa con capucha hace de esta minifigura esencial para coleccionistas recreando la secuencia de infiltración del palacio y construyendo colecciones completas de vestuario específico de misión de Luke Skywalker.'
  },
  {
    no: 'sw0055a',
    name: 'Obi-Wan Kenobi (Young with Dark Orange Hair, without Headset)',
    en: 'Obi-Wan Kenobi Young with Dark Orange Hair without Headset represents the Jedi Knight during various missions throughout Attack of the Clones and the Clone Wars. This LEGO minifigure features young Obi-Wan with dark orange hair, clean head piece without headset printing, tan Jedi robes, and the standard appearance of the warrior-diplomat. Released in 2003 as a variant of earlier releases, this version provides a cleaner minifigure design without mission-specific accessories. The headset-free variant makes this minifigure notable for collectors seeking different Obi-Wan versions and preferring generic appearances suitable for multiple scenes.',
    de: 'Obi-Wan Kenobi Jung mit dunkelorangem Haar ohne Headset repräsentiert den Jedi-Ritter während verschiedener Missionen während Angriff der Klonkrieger und der Klonkriege. Diese LEGO Minifigur zeigt den jungen Obi-Wan mit dunkelorangem Haar, sauberem Kopfteil ohne Headset-Druck, beigefarbenen Jedi-Roben und dem Standard-Aussehen des Krieger-Diplomaten. Veröffentlicht 2003 als Variante früherer Veröffentlichungen, bietet diese Version ein saubereres Minifigur-Design ohne missions-spezifisches Zubehör. Die Headset-freie Variante macht diese Minifigur bemerkenswert für Sammler, die verschiedene Obi-Wan-Versionen suchen und generische Erscheinungen bevorzugen, die für mehrere Szenen geeignet sind.',
    fr: 'Obi-Wan Kenobi Jeune avec Cheveux Orange Foncé sans Casque représente le Chevalier Jedi pendant diverses missions tout au long de L\'Attaque des Clones et des Guerres des Clones. Cette minifigurine LEGO présente le jeune Obi-Wan avec cheveux orange foncé, pièce de tête propre sans impression de casque, robes Jedi beiges et l\'apparence standard du guerrier-diplomate. Sortie en 2003 comme variante des sorties antérieures, cette version fournit un design de minifigurine plus propre sans accessoires spécifiques à la mission. La variante sans casque rend cette minifigurine notable pour les collectionneurs recherchant différentes versions d\'Obi-Wan et préférant des apparences génériques appropriées pour plusieurs scènes.',
    es: 'Obi-Wan Kenobi Joven con Cabello Naranja Oscuro sin Auriculares representa al Caballero Jedi durante varias misiones a lo largo de El Ataque de los Clones y las Guerras Clon. Esta minifigura LEGO presenta al joven Obi-Wan con cabello naranja oscuro, pieza de cabeza limpia sin impresión de auriculares, túnicas Jedi beige y la apariencia estándar del guerrero-diplomático. Lanzada en 2003 como variante de lanzamientos anteriores, esta versión proporciona un diseño de minifigura más limpio sin accesorios específicos de misión. La variante sin auriculares hace de esta minifigura notable para coleccionistas buscando diferentes versiones de Obi-Wan y prefiriendo apariencias genéricas adecuadas para múltiples escenas.'
  },
  {
    no: 'sw0100',
    name: 'Anakin Skywalker (Padawan) - Yellow Head',
    en: 'Anakin Skywalker Padawan with Yellow Head represents the young Jedi apprentice during his training under Obi-Wan Kenobi in Attack of the Clones. This LEGO minifigure features the classic yellow head with Padawan braid hairstyle, brown Jedi robes, and the appearance of the talented but impulsive youth before his fall to darkness. Released in 2003 with prequel sets, this version captures Anakin during his tumultuous journey from skilled Padawan to Jedi Knight. The yellow head and Padawan rank make this minifigure valuable for collectors documenting Anakin\'s character progression and building complete prequel trilogy Jedi collections.',
    de: 'Anakin Skywalker Padawan mit gelbem Kopf repräsentiert den jungen Jedi-Lehrling während seines Trainings unter Obi-Wan Kenobi in Angriff der Klonkrieger. Diese LEGO Minifigur zeigt den klassischen gelben Kopf mit Padawan-Zopf-Frisur, braune Jedi-Roben und das Aussehen des talentierten aber impulsiven Jugendlichen vor seinem Fall in die Dunkelheit. Veröffentlicht 2003 mit Prequel-Sets, fängt diese Version Anakin während seiner turbulenten Reise vom geschickten Padawan zum Jedi-Ritter ein. Der gelbe Kopf und Padawan-Rang machen diese Minifigur wertvoll für Sammler, die Anakins Charakterprogression dokumentieren und vollständige Prequel-Trilogie-Jedi-Sammlungen aufbauen.',
    fr: 'Anakin Skywalker Padawan avec Tête Jaune représente le jeune apprenti Jedi pendant son entraînement sous Obi-Wan Kenobi dans L\'Attaque des Clones. Cette minifigurine LEGO présente la tête jaune classique avec coiffure de tresse de Padawan, robes Jedi brunes et l\'apparence du jeune talentueux mais impulsif avant sa chute dans les ténèbres. Sortie en 2003 avec les sets préquels, cette version capture Anakin pendant son voyage tumultueux de Padawan qualifié à Chevalier Jedi. La tête jaune et le rang de Padawan rendent cette minifigurine précieuse pour les collectionneurs documentant la progression du personnage d\'Anakin et construisant des collections complètes de Jedi de la trilogie préquelle.',
    es: 'Anakin Skywalker Padawan con Cabeza Amarilla representa al joven aprendiz Jedi durante su entrenamiento bajo Obi-Wan Kenobi en El Ataque de los Clones. Esta minifigura LEGO presenta la clásica cabeza amarilla con peinado de trenza Padawan, túnicas Jedi marrones y la apariencia del joven talentoso pero impulsivo antes de su caída a la oscuridad. Lanzada en 2003 con sets de precuelas, esta versión captura a Anakin durante su tumultuoso viaje de Padawan hábil a Caballero Jedi. La cabeza amarilla y rango Padawan hacen de esta minifigura valiosa para coleccionistas documentando la progresión de personaje de Anakin y construyendo colecciones completas de Jedi de trilogía de precuelas.'
  },
  {
    no: 'sw0101',
    name: 'Snowtrooper, Light Gray Hips, White Hands',
    en: 'Snowtrooper with Light Gray Hips and White Hands represents the specialized Imperial cold weather assault troops who attacked Echo Base on Hoth in The Empire Strikes Back. This LEGO minifigure features white armor with distinctive fabric kama skirt piece, light gray hips, white hands, and the insulated appearance designed for frozen environments. Released in 2003 with Hoth battle sets, this version captures the elite Imperial forces trained for extreme climate operations. The light gray hips and white hands variant make this minifigure valuable for collectors army-building Imperial specialist units and recreating the Battle of Hoth assault sequences.',
    de: 'Snowtrooper mit hellgrauen Hüften und weißen Händen repräsentiert die spezialisierten imperialen Kältewetter-Angriffstruppen, die Echo Base auf Hoth in Das Imperium schlägt zurück angriffen. Diese LEGO Minifigur zeigt weiße Rüstung mit charakteristischem Stoff-Kama-Rock-Teil, hellgraue Hüften, weiße Hände und das isolierte Aussehen, das für gefrorene Umgebungen entworfen wurde. Veröffentlicht 2003 mit Hoth-Schlacht-Sets, fängt diese Version die Elite-Imperialen-Streitkräfte ein, die für Extremklima-Operationen trainiert wurden. Die hellgrauen Hüften und weißen Hände-Variante machen diese Minifigur wertvoll für Sammler, die imperiale Spezialisten-Einheiten für Armeen zusammenstellen und die Schlacht-von-Hoth-Angriffssequenzen nachstellen.',
    fr: 'Snowtrooper avec Hanches Gris Clair et Mains Blanches représente les troupes d\'assaut impériales spécialisées par temps froid qui ont attaqué la Base Echo sur Hoth dans L\'Empire contre-attaque. Cette minifigurine LEGO présente une armure blanche avec pièce de jupe kama en tissu distinctive, hanches gris clair, mains blanches et l\'apparence isolée conçue pour les environnements gelés. Sortie en 2003 avec les sets de bataille de Hoth, cette version capture les forces impériales d\'élite entraînées pour les opérations en climat extrême. La variante de hanches gris clair et mains blanches rend cette minifigurine précieuse pour les collectionneurs assemblant des unités spécialisées impériales et recréant les séquences d\'assaut de la Bataille de Hoth.',
    es: 'Snowtrooper con Caderas Gris Claro y Manos Blancas representa a las tropas de asalto imperiales especializadas en clima frío quienes atacaron Base Echo en Hoth en El Imperio Contraataca. Esta minifigura LEGO presenta armadura blanca con distintiva pieza de falda kama de tela, caderas gris claro, manos blancas y la apariencia aislada diseñada para ambientes congelados. Lanzada en 2003 con sets de batalla de Hoth, esta versión captura a las fuerzas imperiales de élite entrenadas para operaciones de clima extremo. La variante de caderas gris claro y manos blancas hacen de esta minifigura valiosa para coleccionistas ensamblando unidades especialistas imperiales y recreando secuencias de asalto de la Batalla de Hoth.'
  },
  {
    no: 'sw0102',
    name: 'AT-AT Driver - Red Imperial Logo, Yellow Head',
    en: 'AT-AT Driver with Red Imperial Logo and Yellow Head represents the specialized pilots who operated the massive All Terrain Armored Transport walkers during the Battle of Hoth in The Empire Strikes Back. This LEGO minifigure features the classic yellow head, gray uniform with red Imperial logo torso print, and distinctive helmet worn by walker crew. Released in 2003 with AT-AT sets, this version captures the elite Imperial vehicle operators who coordinated the devastating ground assault on Echo Base. The red Imperial logo variant makes this minifigure valuable for collectors building complete Imperial vehicle crew rosters and army-building specialized pilot units.',
    de: 'AT-AT-Fahrer mit rotem imperialen Logo und gelbem Kopf repräsentiert die spezialisierten Piloten, die die massiven All Terrain Armored Transport Walker während der Schlacht von Hoth in Das Imperium schlägt zurück bedienten. Diese LEGO Minifigur zeigt den klassischen gelben Kopf, graue Uniform mit rotem imperialen Logo-Torso-Druck und charakteristischen Helm, der von Walker-Besatzung getragen wird. Veröffentlicht 2003 mit AT-AT-Sets, fängt diese Version die Elite-Imperialen-Fahrzeugoperatoren ein, die den verheerenden Bodenangriff auf Echo Base koordinierten. Die rote imperiale Logo-Variante macht diese Minifigur wertvoll für Sammler, die vollständige imperiale Fahrzeugbesatzungs-Kader aufbauen und spezialisierte Piloten-Einheiten für Armeen zusammenstellen.',
    fr: 'Pilote AT-AT avec Logo Impérial Rouge et Tête Jaune représente les pilotes spécialisés qui ont opéré les massifs marcheurs All Terrain Armored Transport pendant la Bataille de Hoth dans L\'Empire contre-attaque. Cette minifigurine LEGO présente la tête jaune classique, uniforme gris avec impression de torse de logo impérial rouge et casque distinctif porté par l\'équipage de marcheur. Sortie en 2003 avec les sets AT-AT, cette version capture les opérateurs de véhicules impériaux d\'élite qui ont coordonné l\'assaut au sol dévastateur sur la Base Echo. La variante de logo impérial rouge rend cette minifigurine précieuse pour les collectionneurs construisant des listes complètes d\'équipage de véhicules impériaux et assemblant des unités de pilotes spécialisées.',
    es: 'Piloto AT-AT con Logo Imperial Rojo y Cabeza Amarilla representa a los pilotos especializados quienes operaron los masivos caminantes All Terrain Armored Transport durante la Batalla de Hoth en El Imperio Contraataca. Esta minifigura LEGO presenta la clásica cabeza amarilla, uniforme gris con impresión de torso de logo imperial rojo y casco distintivo usado por tripulación de caminante. Lanzada en 2003 con sets AT-AT, esta versión captura a los operadores de vehículos imperiales de élite quienes coordinaron el devastador asalto terrestre en Base Echo. La variante de logo imperial rojo hace de esta minifigura valiosa para coleccionistas construyendo listas completas de tripulación de vehículos imperiales y ensamblando unidades de pilotos especializadas.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 009 (sw0061-sw0102) - 10 minifigs...\n');

  for (const m of batch) {
    try {
      await prisma.minifigCatalog.update({
        where: { minifigure_no: m.no },
        data: {
          description_en: m.en,
          description_de: m.de,
          description_fr: m.fr,
          description_es: m.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        }
      });
      console.log(`  ✅ ${m.no}: ${m.name}`);
    } catch (error: any) {
      console.log(`  ⚠️  ${m.no}: NOT IN DATABASE (skipped)`);
    }
  }

  console.log('\n✨ Batch 009 complete: 10 minifigs (40 descriptions)');
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
