import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0429',
    name: 'Clone Trooper - Episode II',
    en: 'Clone Troopers are the genetically identical soldiers of the Grand Army of the Republic, cloned from Jango Fett and deployed to fight the Separatists in Attack of the Clones. This minifigure features the distinctive Phase I white armor with blue or red markings, helmet with T-visor, and blaster rifle. As the Republic\'s military force during the Clone Wars, these soldiers represent both the hope of the Republic and the tragic irony of their future role in Order 66. Released in countless battle packs and army builder sets, Clone Troopers are among the most produced minifigures and essential for building Clone Wars armies.',
    de: 'Klonkrieger sind die genetisch identischen Soldaten der Großen Armee der Republik, geklont von Jango Fett und eingesetzt, um die Separatisten in Angriff der Klonkrieger zu bekämpfen. Diese Minifigur zeigt die charakteristische Phase-I-weiße Rüstung mit blauen oder roten Markierungen, Helm mit T-Visier und Blastergewehr. Als militärische Streitmacht der Republik während der Klonkriege repräsentieren diese Soldaten sowohl die Hoffnung der Republik als auch die tragische Ironie ihrer zukünftigen Rolle in Order 66. Veröffentlicht in zahllosen Kampfpaketen und Armee-Bauer-Sets, gehören Klonkrieger zu den am häufigsten produzierten Minifiguren und sind unerlässlich für den Aufbau von Klonkriegs-Armeen.',
    fr: 'Les Clone Troopers sont les soldats génétiquement identiques de la Grande Armée de la République, clonés de Jango Fett et déployés pour combattre les Séparatistes dans L\'Attaque des Clones. Cette minifigurine présente l\'armure blanche distinctive de Phase I avec marques bleues ou rouges, casque avec visière en T, et fusil blaster. En tant que force militaire de la République pendant les Guerres des Clones, ces soldats représentent à la fois l\'espoir de la République et l\'ironie tragique de leur futur rôle dans l\'Ordre 66. Sortie dans d\'innombrables packs de bataille et sets de constructeurs d\'armée, les Clone Troopers sont parmi les minifigurines les plus produites et essentielles pour construire des armées des Guerres des Clones.',
    es: 'Los Clone Troopers son los soldados genéticamente idénticos del Gran Ejército de la República, clonados de Jango Fett y desplegados para luchar contra los Separatistas en El Ataque de los Clones. Esta minifigura presenta la distintiva armadura blanca de Fase I con marcas azules o rojas, casco con visor en T y rifle bláster. Como la fuerza militar de la República durante las Guerras Clon, estos soldados representan tanto la esperanza de la República como la trágica ironía de su futuro papel en la Orden 66. Lanzada en innumerables paquetes de batalla y sets de constructores de ejércitos, los Clone Troopers están entre las minifiguras más producidas y esenciales para construir ejércitos de las Guerras Clon.'
  },
  {
    no: 'sw0430',
    name: 'Super Battle Droid',
    en: 'Super Battle Droids are the heavily armored and more dangerous upgrade to standard battle droids deployed by the Separatists in Attack of the Clones. This minifigure features bulkier blue-gray metallic body plating, integrated wrist blasters, and more intimidating design. Unlike their weaker predecessors, Super Battle Droids are tougher, more aggressive, and provide sustained firepower. Released in numerous Clone Wars battle sets and army builder packs, these droids are essential for building Separatist forces and represent the escalating arms race of the Clone Wars.',
    de: 'Super-Kampfdroiden sind die schwer gepanzerten und gefährlicheren Upgrades zu Standard-Kampfdroiden, die von den Separatisten in Angriff der Klonkrieger eingesetzt werden. Diese Minifigur zeigt massivere blaugraue metallische Körperplatten, integrierte Handgelenk-Blaster und ein einschüchternderes Design. Im Gegensatz zu ihren schwächeren Vorgängern sind Super-Kampfdroiden härter, aggressiver und bieten anhaltende Feuerkraft. Veröffentlicht in zahlreichen Klonkriegs-Schlacht-Sets und Armee-Bauer-Paketen, sind diese Droiden unerlässlich für den Aufbau von Separatistenstreitkräften und repräsentieren das eskalierende Wettrüsten der Klonkriege.',
    fr: 'Les Super Droïdes de Combat sont la mise à niveau lourdement blindée et plus dangereuse des droïdes de combat standard déployés par les Séparatistes dans L\'Attaque des Clones. Cette minifigurine présente un plaquage de corps métallique gris-bleu plus volumineux, des blasters de poignet intégrés, et un design plus intimidant. Contrairement à leurs prédécesseurs plus faibles, les Super Droïdes de Combat sont plus résistants, plus agressifs, et fournissent une puissance de feu soutenue. Sortie dans de nombreux sets de bataille des Guerres des Clones et packs de constructeurs d\'armée, ces droïdes sont essentiels pour construire des forces Séparatistes et représentent la course aux armements croissante des Guerres des Clones.',
    es: 'Los Super Droides de Batalla son la mejora pesadamente blindada y más peligrosa de los droides de batalla estándar desplegados por los Separatistas en El Ataque de los Clones. Esta minifigura presenta placas de cuerpo metálicas gris-azuladas más voluminosas, blásteres de muñeca integrados y un diseño más intimidante. A diferencia de sus predecesores más débiles, los Super Droides de Batalla son más resistentes, más agresivos y proporcionan potencia de fuego sostenida. Lanzada en numerosos sets de batalla de las Guerras Clon y paquetes de constructores de ejércitos, estos droides son esenciales para construir fuerzas Separatistas y representan la carrera armamentística escalada de las Guerras Clon.'
  },
  {
    no: 'sw0431',
    name: 'Destroyer Droid',
    en: 'Destroyer Droids, also known as Droidekas, are the deadly rolling combat droids with personal shield generators used by the Trade Federation and Separatists. This minifigure captures the distinctive three-legged design with bronze coloring, twin blaster cannons, and ability to curl into a wheel form. Nearly unstoppable in combat due to their shields and firepower, Droidekas represent the most fearsome droid warriors. Released in various battle sets with specialized building techniques for transformation, these unique minifigures are highly valued by collectors for their complex design.',
    de: 'Zerstörerdroiden, auch bekannt als Droidekas, sind die tödlichen rollenden Kampfdroiden mit persönlichen Schildgeneratoren, die von der Handelsföderation und den Separatisten eingesetzt werden. Diese Minifigur erfasst das charakteristische dreibeinige Design mit bronzener Färbung, Doppel-Blaster-Kanonen und Fähigkeit, sich in eine Radform zu rollen. Nahezu unaufhaltsam im Kampf aufgrund ihrer Schilde und Feuerkraft, repräsentieren Droidekas die furchtbarsten Droiden-Krieger. Veröffentlicht in verschiedenen Schlacht-Sets mit spezialisierten Bautechniken für Transformation, werden diese einzigartigen Minifiguren von Sammlern wegen ihres komplexen Designs sehr geschätzt.',
    fr: 'Les Droïdes Destructeurs, également connus sous le nom de Droidekas, sont les droïdes de combat roulants mortels avec générateurs de bouclier personnel utilisés par la Fédération du Commerce et les Séparatistes. Cette minifigurine capture le design distinctif à trois pattes avec coloration bronze, canons blaster doubles, et capacité à se rouler en forme de roue. Presque imparables au combat grâce à leurs boucliers et leur puissance de feu, les Droidekas représentent les guerriers droïdes les plus redoutables. Sortie dans divers sets de bataille avec techniques de construction spécialisées pour la transformation, ces minifigurines uniques sont très appréciées par les collectionneurs pour leur design complexe.',
    es: 'Los Droides Destructores, también conocidos como Droidekas, son los droides de combate rodantes mortales con generadores de escudo personal utilizados por la Federación de Comercio y los Separatistas. Esta minifigura captura el distintivo diseño de tres patas con coloración bronce, cañones bláster gemelos y capacidad para enrollarse en forma de rueda. Casi imparables en combate debido a sus escudos y potencia de fuego, los Droidekas representan a los guerreros droides más temibles. Lanzada en varios sets de batalla con técnicas de construcción especializadas para transformación, estas minifiguras únicas son muy valoradas por coleccionistas por su diseño complejo.'
  },
  {
    no: 'sw0432',
    name: 'Geonosian Warrior',
    en: 'Geonosian Warriors are the insectoid inhabitants of Geonosis who serve the Separatist cause and operate the planet\'s droid foundries in Attack of the Clones. This minifigure depicts the flying alien species with distinctive wings, elongated head, exoskeleton details, and sonic blaster weapon. As the species that built the first Death Star plans, Geonosians represent the industrial backbone of the Separatist war machine. Released in Geonosis arena and factory battle sets, these unique alien minifigures add authenticity to the climactic Clone Wars battle sequences.',
    de: 'Geonosianische Krieger sind die insektoiden Bewohner von Geonosis, die der Separatistensache dienen und die Droidengießereien des Planeten in Angriff der Klonkrieger betreiben. Diese Minifigur zeigt die fliegende außerirdische Spezies mit charakteristischen Flügeln, verlängertem Kopf, Exoskelett-Details und Schall-Blaster-Waffe. Als die Spezies, die die ersten Todesstern-Pläne baute, repräsentieren Geonosianer das industrielle Rückgrat der Separatisten-Kriegsmaschine. Veröffentlicht in Geonosis-Arena- und Fabrik-Schlacht-Sets, fügen diese einzigartigen außerirdischen Minifiguren Authentizität zu den klimatischen Klonkriegs-Schlacht-Sequenzen hinzu.',
    fr: 'Les Guerriers Géonosiens sont les habitants insectoïdes de Geonosis qui servent la cause Séparatiste et opèrent les fonderies de droïdes de la planète dans L\'Attaque des Clones. Cette minifigurine dépeint l\'espèce extraterrestre volante avec ailes distinctives, tête allongée, détails d\'exosquelette, et arme blaster sonique. En tant qu\'espèce qui a construit les premiers plans de l\'Étoile de la Mort, les Géonosiens représentent la colonne vertébrale industrielle de la machine de guerre Séparatiste. Sortie dans les sets d\'arène et de bataille d\'usine de Geonosis, ces minifigurines extraterrestres uniques ajoutent de l\'authenticité aux séquences de bataille climatiques des Guerres des Clones.',
    es: 'Los Guerreros Geonosianos son los habitantes insectoides de Geonosis que sirven a la causa Separatista y operan las fundiciones de droides del planeta en El Ataque de los Clones. Esta minifigura representa a la especie alienígena voladora con alas distintivas, cabeza alargada, detalles de exoesqueleto y arma bláster sónica. Como la especie que construyó los primeros planos de la Estrella de la Muerte, los Geonosianos representan la columna vertebral industrial de la máquina de guerra Separatista. Lanzada en sets de arena y batalla de fábrica de Geonosis, estas minifiguras alienígenas únicas añaden autenticidad a las secuencias de batalla climáticas de las Guerras Clon.'
  },
  {
    no: 'sw0433',
    name: 'Poggle the Lesser',
    en: 'Poggle the Lesser is the Archduke of Geonosis who pledged his planet\'s droid factories to the Separatist cause in Attack of the Clones. This minifigure depicts the Geonosian leader with distinctive staff of office, elaborate robes over his insectoid body, and authority befitting his position. As the architect who designed the Death Star, Poggle represents the industrial leaders who enabled the Separatist war effort. Released in limited Geonosis war room sets, this minifigure is valued by collectors for completing Separatist leadership displays.',
    de: 'Poggle der Geringere ist der Erzherzog von Geonosis, der die Droidenfabriken seines Planeten der Separatistensache in Angriff der Klonkrieger verpfändete. Diese Minifigur zeigt den geonosianischen Anführer mit charakteristischem Amtsstab, aufwendigen Roben über seinem insektoiden Körper und Autorität, die seiner Position entspricht. Als Architekt, der den Todesstern entwarf, repräsentiert Poggle die Industrieführer, die die Separatisten-Kriegsanstrengung ermöglichten. Veröffentlicht in begrenzten Geonosis-Kriegsraum-Sets, wird diese Minifigur von Sammlern geschätzt, um Separatisten-Führungs-Displays zu vervollständigen.',
    fr: 'Poggle le Moindre est l\'Archiduc de Geonosis qui a engagé les usines de droïdes de sa planète à la cause Séparatiste dans L\'Attaque des Clones. Cette minifigurine dépeint le leader Géonosien avec bâton d\'office distinctif, robes élaborées sur son corps insectoïde, et autorité correspondant à sa position. En tant qu\'architecte qui a conçu l\'Étoile de la Mort, Poggle représente les leaders industriels qui ont permis l\'effort de guerre Séparatiste. Sortie dans des sets de salle de guerre Geonosis limités, cette minifigurine est appréciée par les collectionneurs pour compléter les displays de leadership Séparatiste.',
    es: 'Poggle el Menor es el Archiduque de Geonosis que comprometió las fábricas de droides de su planeta a la causa Separatista en El Ataque de los Clones. Esta minifigura representa al líder Geonosiano con distintivo bastón de oficio, elaboradas túnicas sobre su cuerpo insectoide y autoridad acorde a su posición. Como el arquitecto que diseñó la Estrella de la Muerte, Poggle representa a los líderes industriales que permitieron el esfuerzo de guerra Separatista. Lanzada en sets limitados de sala de guerra de Geonosis, esta minifigura es valorada por coleccionistas para completar exhibiciones de liderazgo Separatista.'
  },
  {
    no: 'sw0434',
    name: 'Ki-Adi-Mundi',
    en: 'Ki-Adi-Mundi is the Cerean Jedi Master and member of the Jedi Council known for his distinctive elongated head and binary brain in Attack of the Clones. This minifigure depicts the wise Jedi with his characteristic cone-shaped head, white beard, tan Jedi robes, and blue-bladed lightsaber. Fighting on Geonosis and throughout the Clone Wars, Ki-Adi-Mundi represents the Jedi Order\'s warrior-diplomats. Released in various Clone Wars battle sets, this unique alien Jedi is valued by collectors for his distinctive appearance and role as a Council member.',
    de: 'Ki-Adi-Mundi ist der Cereanische Jedi-Meister und Mitglied des Jedi-Rates, bekannt für seinen charakteristischen verlängerten Kopf und binäres Gehirn in Angriff der Klonkrieger. Diese Minifigur zeigt den weisen Jedi mit seinem charakteristischen kegelförmigen Kopf, weißem Bart, hellbraunen Jedi-Roben und blauklingigem Lichtschwert. Kämpfend auf Geonosis und während der gesamten Klonkriege, repräsentiert Ki-Adi-Mundi die Krieger-Diplomaten des Jedi-Ordens. Veröffentlicht in verschiedenen Klonkriegs-Schlacht-Sets, wird dieser einzigartige außerirdische Jedi von Sammlern wegen seines charakteristischen Aussehens und seiner Rolle als Ratsmitglied geschätzt.',
    fr: 'Ki-Adi-Mundi est le Maître Jedi Ceréen et membre du Conseil Jedi connu pour sa tête allongée distinctive et son cerveau binaire dans L\'Attaque des Clones. Cette minifigurine dépeint le Jedi sage avec sa tête en forme de cône caractéristique, barbe blanche, robes Jedi beiges, et sabre laser à lame bleue. Combattant sur Geonosis et tout au long des Guerres des Clones, Ki-Adi-Mundi représente les guerriers-diplomates de l\'Ordre Jedi. Sortie dans divers sets de bataille des Guerres des Clones, ce Jedi extraterrestre unique est apprécié par les collectionneurs pour son apparence distinctive et son rôle de membre du Conseil.',
    es: 'Ki-Adi-Mundi es el Maestro Jedi Cereano y miembro del Consejo Jedi conocido por su distintiva cabeza alargada y cerebro binario en El Ataque de los Clones. Esta minifigura representa al sabio Jedi con su característica cabeza en forma de cono, barba blanca, túnicas Jedi beige y sable de luz de hoja azul. Luchando en Geonosis y a lo largo de las Guerras Clon, Ki-Adi-Mundi representa a los guerreros-diplomáticos de la Orden Jedi. Lanzada en varios sets de batalla de las Guerras Clon, este Jedi alienígena único es valorado por coleccionistas por su apariencia distintiva y papel como miembro del Consejo.'
  },
  {
    no: 'sw0435',
    name: 'Kit Fisto',
    en: 'Kit Fisto is the Nautolan Jedi Master known for his distinctive head tentacles, cheerful demeanor, and exceptional underwater combat abilities in Attack of the Clones. This minifigure depicts the aquatic Jedi with his characteristic green skin, head-tails, wide smile, and green-bladed lightsaber. Fighting on Geonosis and later confronting Palpatine in Revenge of the Sith, Kit Fisto represents the diverse species within the Jedi Order. Released in various Clone Wars sets, this unique alien Jedi is highly popular with collectors for his distinctive and friendly appearance.',
    de: 'Kit Fisto ist der Nautolanische Jedi-Meister, bekannt für seine charakteristischen Kopftentakel, fröhliche Art und außergewöhnliche Unterwasser-Kampffähigkeiten in Angriff der Klonkrieger. Diese Minifigur zeigt den aquatischen Jedi mit seiner charakteristischen grünen Haut, Kopfschwänzen, breitem Lächeln und grünklingigem Lichtschwert. Kämpfend auf Geonosis und später Palpatine in Die Rache der Sith konfrontierend, repräsentiert Kit Fisto die vielfältigen Spezies innerhalb des Jedi-Ordens. Veröffentlicht in verschiedenen Klonkriegs-Sets, ist dieser einzigartige außerirdische Jedi bei Sammlern wegen seines charakteristischen und freundlichen Aussehens sehr beliebt.',
    fr: 'Kit Fisto est le Maître Jedi Nautolan connu pour ses tentacules de tête distinctifs, son comportement joyeux, et ses capacités de combat sous-marin exceptionnelles dans L\'Attaque des Clones. Cette minifigurine dépeint le Jedi aquatique avec sa peau verte caractéristique, queues de tête, large sourire, et sabre laser à lame verte. Combattant sur Geonosis et confrontant plus tard Palpatine dans La Revanche des Sith, Kit Fisto représente les espèces diverses au sein de l\'Ordre Jedi. Sortie dans divers sets des Guerres des Clones, ce Jedi extraterrestre unique est très populaire auprès des collectionneurs pour son apparence distinctive et amicale.',
    es: 'Kit Fisto es el Maestro Jedi Nautolano conocido por sus distintivos tentáculos de cabeza, comportamiento alegre y habilidades excepcionales de combate submarino en El Ataque de los Clones. Esta minifigura representa al Jedi acuático con su característica piel verde, colas de cabeza, amplia sonrisa y sable de luz de hoja verde. Luchando en Geonosis y más tarde confrontando a Palpatine en La Venganza de los Sith, Kit Fisto representa las diversas especies dentro de la Orden Jedi. Lanzada en varios sets de las Guerras Clon, este Jedi alienígena único es muy popular entre coleccionistas por su apariencia distintiva y amigable.'
  },
  {
    no: 'sw0436',
    name: 'Plo Koon',
    en: 'Plo Koon is the Kel Dor Jedi Master and skilled starfighter pilot who sits on the Jedi Council in Attack of the Clones. This minifigure depicts the alien Jedi with his distinctive breathing mask and goggles required for oxygen-rich atmospheres, orange skin tone, and traditional Jedi robes. Known for his compassion and tactical brilliance during the Clone Wars, Plo Koon represents the Jedi\'s military leadership. Released in various Clone Wars starfighter and battle sets, this unique masked Jedi is popular with collectors for his distinctive appearance and Clone Wars prominence.',
    de: 'Plo Koon ist der Kel Dor Jedi-Meister und geschickter Sternenjägerpilot, der im Jedi-Rat in Angriff der Klonkrieger sitzt. Diese Minifigur zeigt den außerirdischen Jedi mit seiner charakteristischen Atemmaske und Schutzbrille, die für sauerstoffreiche Atmosphären erforderlich sind, orangenem Hautton und traditionellen Jedi-Roben. Bekannt für sein Mitgefühl und taktische Brillanz während der Klonkriege, repräsentiert Plo Koon die militärische Führung der Jedi. Veröffentlicht in verschiedenen Klonkriegs-Sternenjäger- und Schlacht-Sets, ist dieser einzigartige maskierte Jedi bei Sammlern wegen seines charakteristischen Aussehens und seiner Prominenz in den Klonkriegen beliebt.',
    fr: 'Plo Koon est le Maître Jedi Kel Dor et pilote de chasseur stellaire qualifié qui siège au Conseil Jedi dans L\'Attaque des Clones. Cette minifigurine dépeint le Jedi extraterrestre avec son masque respiratoire distinctif et ses lunettes requis pour les atmosphères riches en oxygène, ton de peau orange, et robes Jedi traditionnelles. Connu pour sa compassion et sa brillance tactique pendant les Guerres des Clones, Plo Koon représente le leadership militaire des Jedi. Sortie dans divers sets de chasseur stellaire et bataille des Guerres des Clones, ce Jedi masqué unique est populaire auprès des collectionneurs pour son apparence distinctive et sa prééminence dans les Guerres des Clones.',
    es: 'Plo Koon es el Maestro Jedi Kel Dor y piloto de caza estelar hábil que se sienta en el Consejo Jedi en El Ataque de los Clones. Esta minifigura representa al Jedi alienígena con su distintiva máscara respiratoria y gafas requeridas para atmósferas ricas en oxígeno, tono de piel naranja y túnicas Jedi tradicionales. Conocido por su compasión y brillantez táctica durante las Guerras Clon, Plo Koon representa el liderazgo militar de los Jedi. Lanzada en varios sets de caza estelar y batalla de las Guerras Clon, este Jedi enmascarado único es popular entre coleccionistas por su apariencia distintiva y prominencia en las Guerras Clon.'
  },
  {
    no: 'sw0437',
    name: 'Aayla Secura',
    en: 'Aayla Secura is the Twi\'lek Jedi Knight known for her distinctive blue skin and exceptional combat skills in Attack of the Clones and Revenge of the Sith. This minifigure depicts the female Jedi with her characteristic blue skin tone, head-tails (lekku), brown leather outfit, and blue-bladed lightsaber. Fighting on Geonosis and later tragically killed during Order 66, Aayla represents the diverse and capable female Jedi of the Order. Released in various Clone Wars battle sets, this minifigure is highly sought after by collectors for being one of the few prominent female Jedi and her unique alien design.',
    de: 'Aayla Secura ist die Twi\'lek-Jedi-Ritterin, bekannt für ihre charakteristische blaue Haut und außergewöhnliche Kampffähigkeiten in Angriff der Klonkrieger und Die Rache der Sith. Diese Minifigur zeigt die weibliche Jedi mit ihrem charakteristischen blauen Hautton, Kopfschwänzen (Lekku), braunem Lederoutfit und blauklingigem Lichtschwert. Kämpfend auf Geonosis und später tragisch während Order 66 getötet, repräsentiert Aayla die vielfältigen und fähigen weiblichen Jedi des Ordens. Veröffentlicht in verschiedenen Klonkriegs-Schlacht-Sets, wird diese Minifigur von Sammlern sehr begehrt, da sie eine der wenigen prominenten weiblichen Jedi ist und ihr einzigartiges außerirdisches Design hat.',
    fr: 'Aayla Secura est la Chevalier Jedi Twi\'lek connue pour sa peau bleue distinctive et ses compétences de combat exceptionnelles dans L\'Attaque des Clones et La Revanche des Sith. Cette minifigurine dépeint la Jedi féminine avec son ton de peau bleu caractéristique, queues de tête (lekku), tenue en cuir brun, et sabre laser à lame bleue. Combattant sur Geonosis et plus tard tragiquement tuée pendant l\'Ordre 66, Aayla représente les Jedi féminins divers et capables de l\'Ordre. Sortie dans divers sets de bataille des Guerres des Clones, cette minifigurine est très recherchée par les collectionneurs pour être l\'une des rares Jedi féminins proéminents et son design extraterrestre unique.',
    es: 'Aayla Secura es la Caballero Jedi Twi\'lek conocida por su distintiva piel azul y habilidades de combate excepcionales en El Ataque de los Clones y La Venganza de los Sith. Esta minifigura representa a la Jedi femenina con su característico tono de piel azul, colas de cabeza (lekku), atuendo de cuero marrón y sable de luz de hoja azul. Luchando en Geonosis y más tarde trágicamente asesinada durante la Orden 66, Aayla representa a las Jedi femeninas diversas y capaces de la Orden. Lanzada en varios sets de batalla de las Guerras Clon, esta minifigura es muy buscada por coleccionistas por ser una de las pocas Jedi femeninas prominentes y su diseño alienígena único.'
  },
  {
    no: 'sw0438',
    name: 'Luminara Unduli',
    en: 'Luminara Unduli is the Mirialan Jedi Master known for her calm wisdom, distinctive facial tattoos, and traditional Jedi discipline in Attack of the Clones. This minifigure depicts the green-skinned Jedi with her characteristic geometric facial markings, head covering, dark robes, and green-bladed lightsaber. Fighting on Geonosis and mentoring her Padawan Barriss Offee, Luminara represents the Jedi\'s traditional values. Released in various Clone Wars sets, this elegant female Jedi is valued by collectors for her unique cultural design and role as a Jedi Master.',
    de: 'Luminara Unduli ist die Mirialanische Jedi-Meisterin, bekannt für ihre ruhige Weisheit, charakteristische Gesichtstätowierungen und traditionelle Jedi-Disziplin in Angriff der Klonkrieger. Diese Minifigur zeigt die grünhäutige Jedi mit ihren charakteristischen geometrischen Gesichtsmarkierungen, Kopfbedeckung, dunklen Roben und grünklingigem Lichtschwert. Kämpfend auf Geonosis und ihre Padawan Barriss Offee betreuend, repräsentiert Luminara die traditionellen Werte der Jedi. Veröffentlicht in verschiedenen Klonkriegs-Sets, wird diese elegante weibliche Jedi von Sammlern wegen ihres einzigartigen kulturellen Designs und ihrer Rolle als Jedi-Meisterin geschätzt.',
    fr: 'Luminara Unduli est la Maître Jedi Mirialan connue pour sa sagesse calme, ses tatouages faciaux distinctifs, et sa discipline Jedi traditionnelle dans L\'Attaque des Clones. Cette minifigurine dépeint la Jedi à peau verte avec ses marques faciales géométriques caractéristiques, couvre-chef, robes sombres, et sabre laser à lame verte. Combattant sur Geonosis et encadrant sa Padawan Barriss Offee, Luminara représente les valeurs traditionnelles des Jedi. Sortie dans divers sets des Guerres des Clones, cette Jedi féminine élégante est appréciée par les collectionneurs pour son design culturel unique et son rôle de Maître Jedi.',
    es: 'Luminara Unduli es la Maestra Jedi Mirialan conocida por su sabiduría calmada, distintivos tatuajes faciales y disciplina Jedi tradicional en El Ataque de los Clones. Esta minifigura representa a la Jedi de piel verde con sus características marcas faciales geométricas, cubierta de cabeza, túnicas oscuras y sable de luz de hoja verde. Luchando en Geonosis y siendo mentora de su Padawan Barriss Offee, Luminara representa los valores tradicionales de los Jedi. Lanzada en varios sets de las Guerras Clon, esta elegante Jedi femenina es valorada por coleccionistas por su diseño cultural único y papel como Maestra Jedi.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 321-330 (sw0429-sw0438) - 10 minifigs...\n');

  for (const m of batch) {
    try {
      await prisma.minifigCatalog.upsert({
        where: { minifigure_no: m.no },
        update: {
          description_en: m.en,
          description_de: m.de,
          description_fr: m.fr,
          description_es: m.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        },
        create: {
          minifigure_no: m.no,
          name: m.name,
          category_id: 1,
          category_name: 'Star Wars',
          search_name: m.name.toLowerCase(),
          description_en: m.en,
          description_de: m.de,
          description_fr: m.fr,
          description_es: m.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        }
      });
      console.log(`  ✅ ${m.no}: ${m.name}`);
    } catch (error: any) {
      console.error(`  ❌ ${m.no}: ${error.message}`);
    }
  }

  console.log('\n✨ Batch 321-330 complete: 10 minifigs (40 descriptions)');
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
