import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0639',
    name: 'Jyn Erso',
    en: 'Jyn Erso is the reluctant hero who leads the Rogue One mission to steal the Death Star plans in Rogue One: A Star Wars Story, becoming the catalyst for the Rebellion\'s greatest victory. This LEGO minifigure captures Jyn\'s appearance with dark hair in practical style, Rebel Alliance combat outfit in olive and tan colors, blaster pistol, and determined expression. Released in 2016-2017 across multiple sets including 75155 and 75171, Jyn represents the ordinary people who made extraordinary sacrifices for freedom. Her journey from criminal to hero and sacrifice on Scarif make this minifigure essential for collectors building Rogue One rosters and connecting prequel-era Rebellion to the original trilogy.',
    de: 'Jyn Erso ist die widerwillige Heldin, die in Rogue One: A Star Wars Story die Rogue One-Mission zum Stehlen der Todesstern-Pläne anführt und zum Katalysator für den größten Sieg der Rebellion wird. Diese LEGO Minifigur fängt Jyns Aussehen mit dunklem Haar in praktischem Stil, Rebellenallianz-Kampfoutfit in Oliv- und Beigetönen, Blaster-Pistole und entschlossenem Ausdruck ein. Veröffentlicht 2016-2017 in mehreren Sets einschließlich 75155 und 75171, repräsentiert Jyn die gewöhnlichen Menschen, die außergewöhnliche Opfer für die Freiheit brachten. Ihre Reise von Krimineller zu Heldin und Opfer auf Scarif machen diese Minifigur unverzichtbar für Sammler, die Rogue One-Rosters aufbauen und die Rebellion der Prequel-Ära mit der Original-Trilogie verbinden.',
    fr: 'Jyn Erso est l\'héroïne réticente qui dirige la mission Rogue One pour voler les plans de l\'Étoile de la Mort dans Rogue One: A Star Wars Story, devenant le catalyseur de la plus grande victoire de la Rébellion. Cette minifigurine LEGO capture l\'apparence de Jyn avec cheveux foncés dans un style pratique, tenue de combat de l\'Alliance Rebelle en couleurs olive et beige, pistolet blaster et expression déterminée. Sortie en 2016-2017 dans plusieurs sets dont 75155 et 75171, Jyn représente les gens ordinaires qui ont fait des sacrifices extraordinaires pour la liberté. Son voyage de criminelle à héroïne et son sacrifice sur Scarif rendent cette minifigurine essentielle pour les collectionneurs construisant des listes Rogue One et connectant la Rébellion de l\'ère préquelle à la trilogie originale.',
    es: 'Jyn Erso es la heroína reacia que lidera la misión Rogue One para robar los planos de la Estrella de la Muerte en Rogue One: Una Historia de Star Wars, convirtiéndose en el catalizador de la mayor victoria de la Rebelión. Esta minifigura LEGO captura la apariencia de Jyn con cabello oscuro en estilo práctico, atuendo de combate de la Alianza Rebelde en colores oliva y beige, pistola bláster y expresión determinada. Lanzada en 2016-2017 en múltiples sets incluyendo 75155 y 75171, Jyn representa a la gente ordinaria que hizo sacrificios extraordinarios por la libertad. Su viaje de criminal a heroína y sacrificio en Scarif hacen de esta minifigura esencial para coleccionistas construyendo listas de Rogue One y conectando la Rebelión de la era precuela con la trilogía original.'
  },
  {
    no: 'sw0640',
    name: 'Cassian Andor',
    en: 'Cassian Andor is the Rebel Alliance intelligence officer who partners with Jyn Erso on the Rogue One mission, having done morally questionable acts in service of the greater good. This LEGO minifigure captures Cassian\'s appearance with dark hair, brown Rebel jacket over black shirt, blaster pistol accessories, and resolute expression representing his dedication. Released in 2016-2017 in sets including 75155 and 75171, Cassian represents the spies and operatives who fought the Empire from the shadows. His complex morality and sacrifice on Scarif make this minifigure significant for collectors building Rogue One character rosters and exploring the grittier side of the Rebellion.',
    de: 'Cassian Andor ist der Geheimdienstoffizier der Rebellenallianz, der sich in der Rogue One-Mission mit Jyn Erso zusammentut, nachdem er moralisch fragwürdige Handlungen im Dienst des größeren Wohls begangen hat. Diese LEGO Minifigur fängt Cassians Aussehen mit dunklem Haar, brauner Rebellenjacke über schwarzem Hemd, Blaster-Pistolen-Accessoires und entschlossenem Ausdruck ein, der seine Hingabe repräsentiert. Veröffentlicht 2016-2017 in Sets einschließlich 75155 und 75171, repräsentiert Cassian die Spione und Agenten, die aus dem Schatten gegen das Imperium kämpften. Seine komplexe Moral und sein Opfer auf Scarif machen diese Minifigur bedeutsam für Sammler, die Rogue One-Charakter-Rosters aufbauen und die dunklere Seite der Rebellion erkunden.',
    fr: 'Cassian Andor est l\'officier du renseignement de l\'Alliance Rebelle qui s\'associe avec Jyn Erso pour la mission Rogue One, ayant accompli des actes moralement discutables au service du bien commun. Cette minifigurine LEGO capture l\'apparence de Cassian avec cheveux foncés, veste rebelle marron sur chemise noire, accessoires de pistolet blaster et expression résolue représentant son dévouement. Sortie en 2016-2017 dans des sets dont 75155 et 75171, Cassian représente les espions et opératifs qui ont combattu l\'Empire depuis les ombres. Sa moralité complexe et son sacrifice sur Scarif rendent cette minifigurine significative pour les collectionneurs construisant des listes de personnages Rogue One et explorant le côté plus sombre de la Rébellion.',
    es: 'Cassian Andor es el oficial de inteligencia de la Alianza Rebelde que se asocia con Jyn Erso en la misión Rogue One, habiendo hecho actos moralmente cuestionables al servicio del bien mayor. Esta minifigura LEGO captura la apariencia de Cassian con cabello oscuro, chaqueta Rebelde marrón sobre camisa negra, accesorios de pistola bláster y expresión resuelta representando su dedicación. Lanzada en 2016-2017 en sets incluyendo 75155 y 75171, Cassian representa a los espías y operativos que lucharon contra el Imperio desde las sombras. Su moralidad compleja y sacrificio en Scarif hacen de esta minifigura significativa para coleccionistas construyendo listas de personajes de Rogue One y explorando el lado más oscuro de la Rebelión.'
  },
  {
    no: 'sw0641',
    name: 'Chirrut Îmwe',
    en: 'Chirrut Îmwe is the blind warrior-monk from Jedha who believes in the Force despite not being a Jedi, wielding his staff and repeating "I am one with the Force and the Force is with me." This LEGO minifigure captures Chirrut\'s appearance with dark robes, distinctive headpiece, staff weapon accessory, and serene expression representing his spiritual connection. Released in 2016-2017 as part of sets including 75152 and 75171, Chirrut represents faith in the Force during the dark times when the Jedi were extinct. His martial arts prowess and heroic sacrifice on Scarif make this minifigure essential for collectors building Rogue One character collections and Force-believer rosters.',
    de: 'Chirrut Îmwe ist der blinde Krieger-Mönch von Jedha, der an die Macht glaubt, obwohl er kein Jedi ist, seinen Stab führt und "Ich bin eins mit der Macht und die Macht ist mit mir" wiederholt. Diese LEGO Minifigur fängt Chirruts Aussehen mit dunklen Roben, charakteristischem Kopfteil, Stab-Waffen-Zubehör und heiterer Ausdrucksweise ein, die seine spirituelle Verbindung repräsentiert. Veröffentlicht 2016-2017 als Teil von Sets einschließlich 75152 und 75171, repräsentiert Chirrut den Glauben an die Macht während der dunklen Zeiten, als die Jedi ausgestorben waren. Seine Kampfkunst-Fähigkeiten und heroisches Opfer auf Scarif machen diese Minifigur unverzichtbar für Sammler, die Rogue One-Charakter-Sammlungen und Macht-Gläubigen-Rosters aufbauen.',
    fr: 'Chirrut Îmwe est le moine-guerrier aveugle de Jedha qui croit en la Force bien qu\'il ne soit pas un Jedi, maniant son bâton et répétant "Je suis un avec la Force et la Force est avec moi". Cette minifigurine LEGO capture l\'apparence de Chirrut avec robes sombres, couvre-chef distinctif, accessoire d\'arme bâton et expression sereine représentant sa connexion spirituelle. Sortie en 2016-2017 dans le cadre de sets dont 75152 et 75171, Chirrut représente la foi en la Force pendant les temps sombres où les Jedi étaient éteints. Ses prouesses en arts martiaux et son sacrifice héroïque sur Scarif rendent cette minifigurine essentielle pour les collectionneurs construisant des collections de personnages Rogue One et des listes de croyants en la Force.',
    es: 'Chirrut Îmwe es el monje-guerrero ciego de Jedha que cree en la Fuerza a pesar de no ser un Jedi, empuñando su bastón y repitiendo "Soy uno con la Fuerza y la Fuerza está conmigo". Esta minifigura LEGO captura la apariencia de Chirrut con túnicas oscuras, distintivo tocado, accesorio de arma bastón y expresión serena representando su conexión espiritual. Lanzada en 2016-2017 como parte de sets incluyendo 75152 y 75171, Chirrut representa la fe en la Fuerza durante los tiempos oscuros cuando los Jedi estaban extintos. Su destreza en artes marciales y sacrificio heroico en Scarif hacen de esta minifigura esencial para coleccionistas construyendo colecciones de personajes de Rogue One y listas de creyentes en la Fuerza.'
  },
  {
    no: 'sw0642',
    name: 'Baze Malbus',
    en: 'Baze Malbus is the heavily armed warrior and Chirrut Îmwe\'s pragmatic companion who lost his faith in the Force but remains loyal to his friend. This LEGO minifigure captures Baze\'s appearance with armored vest over red shirt, heavy weapons loadout including large blaster rifle, and stern expression representing his guardian role. Released in 2016-2017 as part of sets including 75152 and 75171, Baze represents the protectors who fight for their friends even without spiritual belief. His friendship with Chirrut and sacrifice on Scarif make this minifigure significant for collectors building Rogue One character pairs and diverse Rebel warrior collections.',
    de: 'Baze Malbus ist der schwer bewaffnete Krieger und Chirrut Îmwes pragmatischer Begleiter, der seinen Glauben an die Macht verloren hat, aber seinem Freund treu bleibt. Diese LEGO Minifigur fängt Bazes Aussehen mit gepanzerter Weste über rotem Hemd, schwerer Waffenladung einschließlich großem Blastergewehr und strengem Ausdruck ein, der seine Wächterrolle repräsentiert. Veröffentlicht 2016-2017 als Teil von Sets einschließlich 75152 und 75171, repräsentiert Baze die Beschützer, die für ihre Freunde kämpfen, auch ohne spirituellen Glauben. Seine Freundschaft mit Chirrut und Opfer auf Scarif machen diese Minifigur bedeutsam für Sammler, die Rogue One-Charakter-Paare und vielfältige Rebellenkrieger-Sammlungen aufbauen.',
    fr: 'Baze Malbus est le guerrier lourdement armé et compagnon pragmatique de Chirrut Îmwe qui a perdu sa foi en la Force mais reste loyal à son ami. Cette minifigurine LEGO capture l\'apparence de Baze avec gilet blindé sur chemise rouge, chargement d\'armes lourdes incluant grand fusil blaster et expression sévère représentant son rôle de gardien. Sortie en 2016-2017 dans le cadre de sets dont 75152 et 75171, Baze représente les protecteurs qui combattent pour leurs amis même sans croyance spirituelle. Son amitié avec Chirrut et son sacrifice sur Scarif rendent cette minifigurine significative pour les collectionneurs construisant des paires de personnages Rogue One et des collections diverses de guerriers rebelles.',
    es: 'Baze Malbus es el guerrero fuertemente armado y compañero pragmático de Chirrut Îmwe que perdió su fe en la Fuerza pero permanece leal a su amigo. Esta minifigura LEGO captura la apariencia de Baze con chaleco blindado sobre camisa roja, carga de armas pesadas incluyendo gran rifle bláster y expresión severa representando su papel de guardián. Lanzada en 2016-2017 como parte de sets incluyendo 75152 y 75171, Baze representa a los protectores que luchan por sus amigos incluso sin creencia espiritual. Su amistad con Chirrut y sacrificio en Scarif hacen de esta minifigura significativa para coleccionistas construyendo parejas de personajes de Rogue One y colecciones diversas de guerreros Rebeldes.'
  },
  {
    no: 'sw0643',
    name: 'Bodhi Rook',
    en: 'Bodhi Rook is the Imperial cargo pilot who defects to the Rebellion after Galen Erso entrusts him with information about the Death Star\'s weakness. This LEGO minifigure captures Bodhi\'s appearance with Imperial flight suit modified with Rebel patches, pilot helmet accessories, and nervous expression representing his struggle with his defection. Released in 2016-2017 as part of sets including 75155 and 75171, Bodhi represents the Imperial personnel who chose conscience over duty. His crucial role piloting on Scarif and establishing communication make this minifigure essential for collectors building Rogue One complete crew rosters and Imperial defector collections.',
    de: 'Bodhi Rook ist der imperiale Frachtpilot, der zur Rebellion überläuft, nachdem Galen Erso ihm Informationen über die Schwäche des Todessterns anvertraut hat. Diese LEGO Minifigur fängt Bodhis Aussehen mit imperialem Fluganzug ein, der mit Rebellenaufnähern modifiziert ist, Pilotenhelm-Accessoires und nervösem Ausdruck, der seinen Kampf mit seinem Überlaufen repräsentiert. Veröffentlicht 2016-2017 als Teil von Sets einschließlich 75155 und 75171, repräsentiert Bodhi das imperiale Personal, das Gewissen über Pflicht wählte. Seine entscheidende Rolle beim Pilotieren auf Scarif und beim Herstellen der Kommunikation machen diese Minifigur unverzichtbar für Sammler, die vollständige Rogue One-Crew-Rosters und imperiale Überläufer-Sammlungen aufbauen.',
    fr: 'Bodhi Rook est le pilote de cargo impérial qui fait défection vers la Rébellion après que Galen Erso lui ait confié des informations sur la faiblesse de l\'Étoile de la Mort. Cette minifigurine LEGO capture l\'apparence de Bodhi avec combinaison de vol impériale modifiée avec patchs rebelles, accessoires de casque de pilote et expression nerveuse représentant sa lutte avec sa défection. Sortie en 2016-2017 dans le cadre de sets dont 75155 et 75171, Bodhi représente le personnel impérial qui a choisi la conscience plutôt que le devoir. Son rôle crucial pilotant sur Scarif et établissant la communication rendent cette minifigurine essentielle pour les collectionneurs construisant des listes d\'équipage complètes Rogue One et des collections de transfuges impériaux.',
    es: 'Bodhi Rook es el piloto de carga Imperial que deserta a la Rebelión después de que Galen Erso le confía información sobre la debilidad de la Estrella de la Muerte. Esta minifigura LEGO captura la apariencia de Bodhi con traje de vuelo Imperial modificado con parches Rebeldes, accesorios de casco de piloto y expresión nerviosa representando su lucha con su deserción. Lanzada en 2016-2017 como parte de sets incluyendo 75155 y 75171, Bodhi representa al personal Imperial que eligió conciencia sobre deber. Su papel crucial pilotando en Scarif y estableciendo comunicación hacen de esta minifigura esencial para coleccionistas construyendo listas completas de tripulación de Rogue One y colecciones de desertores imperiales.'
  },
  {
    no: 'sw0644',
    name: 'K-2SO',
    en: 'K-2SO is the reprogrammed Imperial security droid who serves the Rebellion with brutally honest commentary and remarkable combat capabilities. This LEGO minifigure captures K-2\'s distinctive tall black droid design with white Imperial markings, articulated limbs, and imposing stature representing his intimidating presence. Released in 2016-2017 across multiple Rogue One sets, K-2SO represents the rare droids with genuine personality and emotional depth. His dry humor, loyalty to Cassian, and heroic sacrifice protecting the Rogue One team make this minifigure beloved by collectors building Rogue One droid collections and memorable character rosters.',
    de: 'K-2SO ist der umprogrammierte imperiale Sicherheitsdroide, der der Rebellion mit brutal ehrlichen Kommentaren und bemerkenswerten Kampffähigkeiten dient. Diese LEGO Minifigur fängt K-2s charakteristisches großes schwarzes Droiden-Design mit weißen imperialen Markierungen, artikulierten Gliedmaßen und imposanter Statur ein, die seine einschüchternde Präsenz repräsentiert. Veröffentlicht 2016-2017 in mehreren Rogue One-Sets, repräsentiert K-2SO die seltenen Droiden mit echter Persönlichkeit und emotionaler Tiefe. Sein trockener Humor, Loyalität zu Cassian und heroisches Opfer beim Schutz des Rogue One-Teams machen diese Minifigur bei Sammlern beliebt, die Rogue One-Droiden-Sammlungen und denkwürdige Charakter-Rosters aufbauen.',
    fr: 'K-2SO est le droïde de sécurité impérial reprogrammé qui sert la Rébellion avec des commentaires brutalement honnêtes et des capacités de combat remarquables. Cette minifigurine LEGO capture le design distinctif de grand droïde noir de K-2 avec marquages impériaux blancs, membres articulés et stature imposante représentant sa présence intimidante. Sortie en 2016-2017 dans plusieurs sets Rogue One, K-2SO représente les rares droïdes avec une véritable personnalité et profondeur émotionnelle. Son humour sec, sa loyauté envers Cassian et son sacrifice héroïque protégeant l\'équipe Rogue One rendent cette minifigurine adorée par les collectionneurs construisant des collections de droïdes Rogue One et des listes de personnages mémorables.',
    es: 'K-2SO es el droide de seguridad Imperial reprogramado que sirve a la Rebelión con comentarios brutalmente honestos y notables capacidades de combate. Esta minifigura LEGO captura el distintivo diseño de droide negro alto de K-2 con marcas imperiales blancas, extremidades articuladas y estatura imponente representando su presencia intimidante. Lanzada en 2016-2017 en múltiples sets de Rogue One, K-2SO representa los raros droides con genuina personalidad y profundidad emocional. Su humor seco, lealtad a Cassian y sacrificio heroico protegiendo al equipo Rogue One hacen de esta minifigura amada por coleccionistas construyendo colecciones de droides de Rogue One y listas de personajes memorables.'
  },
  {
    no: 'sw0645',
    name: 'Director Krennic',
    en: 'Director Orson Krennic is the Imperial weapons developer who oversees the Death Star construction, wearing a distinctive white uniform and desperate to receive credit for his creation. This LEGO minifigure captures Krennic\'s appearance with white Imperial officer uniform with cape, rank insignia, blaster pistol, and ambitious expression. Released in 2016-2017 across multiple sets including 75156 and 75171, Krennic represents the Imperial bureaucrats whose ambition and hubris built superweapons. His rivalry with Grand Moff Tarkin and death on Scarif witnessing his creation\'s first firing make this minifigure essential for collectors building Rogue One Imperial leadership and Death Star construction storylines.',
    de: 'Direktor Orson Krennic ist der imperiale Waffenentwickler, der den Bau des Todessterns überwacht, eine charakteristische weiße Uniform trägt und verzweifelt Anerkennung für seine Schöpfung erhalten will. Diese LEGO Minifigur fängt Krennics Aussehen mit weißer imperialer Offiziersuniform mit Umhang, Rangabzeichen, Blaster-Pistole und ehrgeizigem Ausdruck ein. Veröffentlicht 2016-2017 in mehreren Sets einschließlich 75156 und 75171, repräsentiert Krennic die imperialen Bürokraten, deren Ehrgeiz und Hybris Superwaffen bauten. Seine Rivalität mit Großmoff Tarkin und Tod auf Scarif, als er den ersten Schuss seiner Schöpfung miterlebt, machen diese Minifigur unverzichtbar für Sammler, die Rogue One-Imperiale-Führung und Todesstern-Bau-Storylines aufbauen.',
    fr: 'Le Directeur Orson Krennic est le développeur d\'armes impérial qui supervise la construction de l\'Étoile de la Mort, portant un uniforme blanc distinctif et désespéré de recevoir le crédit pour sa création. Cette minifigurine LEGO capture l\'apparence de Krennic avec uniforme d\'officier impérial blanc avec cape, insignes de rang, pistolet blaster et expression ambitieuse. Sortie en 2016-2017 dans plusieurs sets dont 75156 et 75171, Krennic représente les bureaucrates impériaux dont l\'ambition et l\'orgueil ont construit des super-armes. Sa rivalité avec le Grand Moff Tarkin et sa mort sur Scarif assistant au premier tir de sa création rendent cette minifigurine essentielle pour les collectionneurs construisant le leadership impérial Rogue One et les histoires de construction de l\'Étoile de la Mort.',
    es: 'El Director Orson Krennic es el desarrollador de armas Imperial que supervisa la construcción de la Estrella de la Muerte, vistiendo un distintivo uniforme blanco y desesperado por recibir crédito por su creación. Esta minifigura LEGO captura la apariencia de Krennic con uniforme blanco de oficial Imperial con capa, insignias de rango, pistola bláster y expresión ambiciosa. Lanzada en 2016-2017 en múltiples sets incluyendo 75156 y 75171, Krennic representa a los burócratas imperiales cuya ambición y arrogancia construyeron superarmas. Su rivalidad con el Gran Moff Tarkin y muerte en Scarif presenciando el primer disparo de su creación hacen de esta minifigura esencial para coleccionistas construyendo liderazgo Imperial de Rogue One e historias de construcción de la Estrella de la Muerte.'
  },
  {
    no: 'sw0646',
    name: 'Shoretrooper',
    en: 'Shoretroopers are specialized Imperial stormtroopers stationed on tropical planets like Scarif, wearing distinctive tan armor adapted for coastal environments. This LEGO minifigure features tan and olive-colored armor with unique helmet design, specialist equipment, and blaster rifle representing their specialized training. Released in 2016-2018 across multiple Rogue One sets, Shoretroopers represent the Empire\'s diverse environmental specialist units. Their distinctive color scheme and role defending the Imperial security complex on Scarif make this minifigure highly desirable for army builders seeking trooper variety and collectors recreating the Battle of Scarif.',
    de: 'Shoretroopers sind spezialisierte imperiale Sturmtruppler, die auf tropischen Planeten wie Scarif stationiert sind und charakteristische beige Rüstung tragen, die an Küstenumgebungen angepasst ist. Diese LEGO Minifigur zeigt beige-olivfarbene Rüstung mit einzigartigem Helm-Design, Spezialausrüstung und Blastergewehr, die ihr spezialisiertes Training repräsentieren. Veröffentlicht 2016-2018 in mehreren Rogue One-Sets, repräsentieren Shoretroopers die vielfältigen Umweltspezialisten-Einheiten des Imperiums. Ihr charakteristisches Farbschema und Rolle bei der Verteidigung des imperialen Sicherheitskomplexes auf Scarif machen diese Minifigur sehr begehrenswert für Army Builder, die Soldatenvielfalt suchen, und Sammler, die die Schlacht von Scarif nachstellen.',
    fr: 'Les Shoretroopers sont des stormtroopers impériaux spécialisés stationnés sur des planètes tropicales comme Scarif, portant une armure beige distinctive adaptée aux environnements côtiers. Cette minifigurine LEGO présente une armure beige et olive avec design de casque unique, équipement spécialisé et fusil blaster représentant leur entraînement spécialisé. Sortie en 2016-2018 dans plusieurs sets Rogue One, les Shoretroopers représentent les diverses unités de spécialistes environnementaux de l\'Empire. Leur schéma de couleurs distinctif et leur rôle défendant le complexe de sécurité impérial sur Scarif rendent cette minifigurine hautement désirable pour les constructeurs d\'armées recherchant la variété de soldats et les collectionneurs recréant la Bataille de Scarif.',
    es: 'Los Shoretroopers son stormtroopers imperiales especializados estacionados en planetas tropicales como Scarif, vistiendo distintiva armadura beige adaptada para ambientes costeros. Esta minifigura LEGO presenta armadura beige y oliva con diseño único de casco, equipo especializado y rifle bláster representando su entrenamiento especializado. Lanzada en 2016-2018 en múltiples sets de Rogue One, los Shoretroopers representan las diversas unidades especialistas ambientales del Imperio. Su distintivo esquema de color y papel defendiendo el complejo de seguridad Imperial en Scarif hacen de esta minifigura altamente deseable para constructores de ejércitos buscando variedad de soldados y coleccionistas recreando la Batalla de Scarif.'
  },
  {
    no: 'sw0647',
    name: 'Shoretrooper Captain',
    en: 'Shoretrooper Captains command Scarif garrison forces with distinctive rank markings on their tan specialized armor, leading coastal defense operations. This LEGO minifigure features the Shoretrooper\'s tan armor with additional officer markings, unique helmet design, and enhanced equipment representing command authority. Released in 2016-2017 as part of sets including 75156, Shoretrooper Captains provide leadership to Imperial beach assault forces. The distinctive rank markings and role commanding Scarif defenses make this minifigure valuable for collectors building complete Shoretrooper units with proper military hierarchy.',
    de: 'Shoretrooper-Captains befehligen Scarif-Garnisonstruppen mit charakteristischen Rangmarkierungen auf ihrer beigen spezialisierten Rüstung und leiten Küstenverteidigungsoperationen. Diese LEGO Minifigur zeigt die beige Rüstung der Shoretroopers mit zusätzlichen Offiziersmarkierungen, einzigartigem Helm-Design und verbesserter Ausrüstung, die Befehlsautorität repräsentiert. Veröffentlicht 2016-2017 als Teil von Sets einschließlich 75156, bieten Shoretrooper-Captains Führung für imperiale Strand-Angriffstruppen. Die charakteristischen Rangmarkierungen und Rolle beim Kommandieren der Scarif-Verteidigung machen diese Minifigur wertvoll für Sammler, die vollständige Shoretrooper-Einheiten mit angemessener Militärhierarchie aufbauen.',
    fr: 'Les Capitaines Shoretroopers commandent les forces de garnison de Scarif avec des marquages de rang distinctifs sur leur armure spécialisée beige, dirigeant les opérations de défense côtière. Cette minifigurine LEGO présente l\'armure beige du Shoretrooper avec marquages d\'officier supplémentaires, design de casque unique et équipement amélioré représentant l\'autorité de commandement. Sortie en 2016-2017 dans le cadre de sets dont 75156, les Capitaines Shoretroopers fournissent le leadership aux forces d\'assaut de plage impériales. Les marquages de rang distinctifs et le rôle commandant les défenses de Scarif rendent cette minifigurine précieuse pour les collectionneurs construisant des unités complètes de Shoretroopers avec hiérarchie militaire appropriée.',
    es: 'Los Capitanes Shoretrooper comandan fuerzas de guarnición de Scarif con distintivas marcas de rango en su armadura especializada beige, liderando operaciones de defensa costera. Esta minifigura LEGO presenta la armadura beige del Shoretrooper con marcas adicionales de oficial, diseño único de casco y equipo mejorado representando autoridad de mando. Lanzada en 2016-2017 como parte de sets incluyendo 75156, los Capitanes Shoretrooper proporcionan liderazgo a las fuerzas de asalto de playa imperiales. Las distintivas marcas de rango y papel comandando las defensas de Scarif hacen de esta minifigura valiosa para coleccionistas construyendo unidades completas de Shoretroopers con jerarquía militar apropiada.'
  },
  {
    no: 'sw0648',
    name: 'Imperial Hovertank Pilot',
    en: 'Imperial Hovertank Pilots operate the TX-225 GAVw "Occupier" combat assault tanks deployed on occupied worlds like Jedha and Scarif. This LEGO minifigure features distinctive armored suit in gray with black accents, specialized enclosed helmet, and equipment representing vehicle operation expertise. Released in 2016 as part of set 75152, Hovertank Pilots represent Imperial armored divisions beyond standard AT-AT and AT-ST crews. Their role in urban pacification on Jedha and defending Scarif make this minifigure useful for collectors building diverse Imperial vehicle crews and Rogue One military displays.',
    de: 'Imperiale Hovertank-Piloten bedienen die TX-225 GAVw "Occupier" Kampfangriffstanks, die auf besetzten Welten wie Jedha und Scarif eingesetzt werden. Diese LEGO Minifigur zeigt charakteristischen gepanzerten Anzug in Grau mit schwarzen Akzenten, spezialisierten geschlossenen Helm und Ausrüstung, die Fahrzeugbedienungs-Expertise repräsentiert. Veröffentlicht 2016 als Teil des Sets 75152, repräsentieren Hovertank-Piloten imperiale Panzer-Divisionen jenseits von Standard-AT-AT- und AT-ST-Besatzungen. Ihre Rolle bei der urbanen Befriedung auf Jedha und Verteidigung von Scarif machen diese Minifigur nützlich für Sammler, die vielfältige imperiale Fahrzeugbesatzungen und Rogue One-Militär-Displays aufbauen.',
    fr: 'Les Pilotes de Hovertank Impériaux opèrent les chars d\'assaut de combat TX-225 GAVw "Occupier" déployés sur des mondes occupés comme Jedha et Scarif. Cette minifigurine LEGO présente une combinaison blindée distinctive en gris avec accents noirs, casque fermé spécialisé et équipement représentant l\'expertise d\'opération de véhicules. Sortie en 2016 dans le cadre du set 75152, les Pilotes de Hovertank représentent les divisions blindées impériales au-delà des équipages standards AT-AT et AT-ST. Leur rôle dans la pacification urbaine sur Jedha et la défense de Scarif rendent cette minifigurine utile pour les collectionneurs construisant des équipages de véhicules impériaux divers et des affichages militaires Rogue One.',
    es: 'Los Pilotos de Hovertank Imperiales operan los tanques de asalto de combate TX-225 GAVw "Ocupante" desplegados en mundos ocupados como Jedha y Scarif. Esta minifigura LEGO presenta distintivo traje blindado en gris con acentos negros, casco cerrado especializado y equipo representando experiencia en operación de vehículos. Lanzada en 2016 como parte del set 75152, los Pilotos de Hovertank representan divisiones blindadas imperiales más allá de tripulaciones estándar de AT-AT y AT-ST. Su papel en la pacificación urbana en Jedha y defensa de Scarif hacen de esta minifigura útil para coleccionistas construyendo tripulaciones diversas de vehículos imperiales y exhibiciones militares de Rogue One.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 531-540 (sw0639-sw0648) - 10 minifigs...\n');

  for (const m of batch) {
    await prisma.minifigCatalog.upsert({
      where: { minifigure_no: m.no },
      update: {
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      },
      create: {
        minifigure_no: m.no,
        name: m.name,
        category_id: 1,
        category_name: 'Star Wars',
        search_name: m.name.toLowerCase(),
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`  ✅ ${m.no}: ${m.name}`);
  }

  console.log('\n✨ Batch 531-540 complete: 10 minifigs (40 descriptions)');
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
