import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0214',
    name: 'Garindan (Long Snoot)',
    en: "Garindan is the Kubaz spy who reports the droids' location to Imperial forces in Mos Eisley, leading stormtroopers to the Millennium Falcon's hangar bay. This LEGO minifigure captures Garindan's distinctive elongated trunk-like snout and dark robes that help him blend into crowds. First released in 2018, Garindan represents the Imperial informant network that makes even rebel-friendly locations dangerous. The figure features unique head molding showing his species' characteristic proboscis and the inconspicuous clothing of a professional spy. Collectors value Garindan for his brief but crucial role tipping off the Empire and for representing the surveillance state that tracks rebels. His betrayal forces Han, Luke, and the others into a desperate escape, making this minifigure essential for recreating the Mos Eisley pursuit scenes from A New Hope.",
    de: "Garindan ist der Kubaz-Spion, der den Aufenthaltsort der Droiden an imperiale Streitkräfte in Mos Eisley meldet und Sturmtruppen zum Hangar des Millennium Falken führt. Diese LEGO-Minifigur fängt Garidans charakteristische verlängerte rüsselartige Schnauze und dunkle Roben ein, die ihm helfen, in Menschenmengen zu verschmelzen. Erstmals 2018 veröffentlicht, repräsentiert Garindan das imperiale Informantennetzwerk, das selbst rebellenfreundliche Orte gefährlich macht. Die Figur zeigt einzigartige Kopfformung mit dem charakteristischen Rüssel seiner Spezies und der unauffälligen Kleidung eines professionellen Spions. Sammler schätzen Garindan für seine kurze aber entscheidende Rolle beim Verpfeifen des Imperiums und für die Darstellung des Überwachungsstaates, der Rebellen verfolgt. Sein Verrat zwingt Han, Luke und die anderen zu einer verzweifelten Flucht und macht diese Minifigur unverzichtbar für die Nachbildung der Mos Eisley Verfolgungsszenen aus Eine neue Hoffnung.",
    fr: "Garindan est l'espion Kubaz qui signale l'emplacement des droïdes aux forces Impériales à Mos Eisley, conduisant les stormtroopers à la baie de hangar du Faucon Millenium. Cette minifigurine LEGO capture le museau allongé distinctif en forme de trompe de Garindan et les robes sombres qui l'aident à se fondre dans les foules. Sortie pour la première fois en 2018, Garindan représente le réseau d'informateurs Impérial qui rend même les endroits favorables aux rebelles dangereux. La figurine présente un moulage de tête unique montrant la trompe caractéristique de son espèce et les vêtements discrets d'un espion professionnel. Les collectionneurs apprécient Garindan pour son rôle bref mais crucial de dénonciation à l'Empire et pour représenter l'État de surveillance qui traque les rebelles. Sa trahison force Han, Luke et les autres à une évasion désespérée, faisant de cette minifigurine un élément essentiel pour recréer les scènes de poursuite de Mos Eisley d'Un Nouvel Espoir.",
    es: "Garindan es el espía Kubaz que reporta la ubicación de los droides a fuerzas Imperiales en Mos Eisley, guiando a soldados de asalto a la bahía de hangar del Halcón Milenario. Esta minifigura LEGO captura el distintivo hocico alargado tipo trompa de Garindan y túnicas oscuras que lo ayudan a mezclarse en multitudes. Lanzada por primera vez en 2018, Garindan representa la red de informantes Imperial que hace que incluso ubicaciones favorables a rebeldes sean peligrosas. La figura presenta moldeado de cabeza único mostrando la probóscide característica de su especie y la ropa discreta de un espía profesional. Los coleccionistas valoran a Garindan por su papel breve pero crucial informando al Imperio y por representar el estado de vigilancia que rastrea rebeldes. Su traición fuerza a Han, Luke y los demás a un escape desesperado, haciendo que esta minifigura sea esencial para recrear las escenas de persecución de Mos Eisley de Una Nueva Esperanza."
  },
  {
    no: 'sw0215',
    name: 'Cantina Band Member',
    en: "The Cantina Band, also known as Figrin D'an and the Modal Nodes, are Bith musicians performing the iconic \"Cantina Theme\" in the Mos Eisley watering hole. This LEGO minifigure captures the Bith's distinctive large cranium, black eyes, and musician attire with various instruments. First released in 2014, Cantina Band members represent one of the most memorable musical moments in Star Wars history. The figure features unique head molding showing the Bith species' enlarged brain case and the professional appearance of working musicians. Collectors value Cantina Band members for the unforgettable jizz-wailer music and for adding authentic atmosphere to Mos Eisley displays. Multiple band members with different instruments are essential for recreating the full ensemble that provided the soundtrack to one of A New Hope's most iconic locations.",
    de: "Die Cantina-Band, auch bekannt als Figrin D'an und die Modal Nodes, sind Bith-Musiker, die das ikonische \"Cantina-Thema\" in der Mos Eisley Wasserstelle aufführen. Diese LEGO-Minifigur fängt das charakteristische große Cranium, schwarze Augen und Musiker-Outfit der Bith mit verschiedenen Instrumenten ein. Erstmals 2014 veröffentlicht, repräsentieren Cantina-Band-Mitglieder einen der unvergesslichsten musikalischen Momente in der Star Wars Geschichte. Die Figur zeigt einzigartige Kopfformung mit dem vergrößerten Gehirnkasten der Bith-Spezies und dem professionellen Aussehen arbeitender Musiker. Sammler schätzen Cantina-Band-Mitglieder für die unvergessliche Jizz-Wailer-Musik und für das Hinzufügen authentischer Atmosphäre zu Mos Eisley Ausstellungen. Mehrere Bandmitglieder mit verschiedenen Instrumenten sind unverzichtbar für die Nachbildung des vollständigen Ensembles, das den Soundtrack zu einem der ikonischsten Orte von Eine neue Hoffnung lieferte.",
    fr: "Le Groupe de la Cantina, également connu sous le nom de Figrin D'an et les Modal Nodes, sont des musiciens Bith interprétant le \"Thème de la Cantina\" iconique dans le point d'eau de Mos Eisley. Cette minifigurine LEGO capture le crâne large distinctif des Bith, les yeux noirs et la tenue de musicien avec divers instruments. Sortie pour la première fois en 2014, les membres du Groupe de la Cantina représentent l'un des moments musicaux les plus mémorables de l'histoire de Star Wars. La figurine présente un moulage de tête unique montrant la boîte crânienne élargie de l'espèce Bith et l'apparence professionnelle de musiciens en activité. Les collectionneurs apprécient les membres du Groupe de la Cantina pour la musique jizz-wailer inoubliable et pour ajouter une atmosphère authentique aux expositions de Mos Eisley. Plusieurs membres du groupe avec différents instruments sont essentiels pour recréer l'ensemble complet qui a fourni la bande sonore à l'un des lieux les plus iconiques d'Un Nouvel Espoir.",
    es: "La Banda de Cantina, también conocida como Figrin D'an y los Modal Nodes, son músicos Bith interpretando el icónico \"Tema de Cantina\" en el abrevadero de Mos Eisley. Esta minifigura LEGO captura el distintivo cráneo grande de los Bith, ojos negros y vestimenta de músico con varios instrumentos. Lanzada por primera vez en 2014, los miembros de la Banda de Cantina representan uno de los momentos musicales más memorables en la historia de Star Wars. La figura presenta moldeado de cabeza único mostrando la caja craneal agrandada de la especie Bith y la apariencia profesional de músicos trabajadores. Los coleccionistas valoran a los miembros de la Banda de Cantina por la música jizz-wailer inolvidable y por agregar atmósfera auténtica a exhibiciones de Mos Eisley. Múltiples miembros de banda con diferentes instrumentos son esenciales para recrear el ensamble completo que proporcionó la banda sonora a una de las ubicaciones más icónicas de Una Nueva Esperanza."
  },
  {
    no: 'sw0216',
    name: 'Momaw Nadon (Hammerhead)',
    en: "Momaw Nadon, nicknamed Hammerhead, is an Ithorian exile in the Mos Eisley Cantina, recognizable by his distinctive hammer-shaped head and twin mouth openings. This LEGO minifigure captures the Ithorian's unique sideways-curved head and the peaceful demeanor that contrasts with the cantina's violence. First released in 2014, Momaw Nadon represents the diverse alien species that populate Tatooine's spaceports. The figure features specialized head construction showing the Ithorian's bizarre but memorable physiology. Collectors value Hammerhead for his iconic silhouette in the cantina scene and for representing the galaxy's incredible biodiversity. His gentle herbivore nature and tragic exile backstory add depth to what could be just another background alien, making this minifigure essential for building comprehensive Mos Eisley Cantina displays from A New Hope.",
    de: "Momaw Nadon, Spitzname Hammerhead, ist ein Ithorianer-Exilant in der Mos Eisley Cantina, erkennbar an seinem charakteristischen hammerförmigen Kopf und doppelten Mundöffnungen. Diese LEGO-Minifigur fängt den einzigartigen seitwärts gebogenen Kopf des Ithorianer und die friedliche Haltung ein, die mit der Gewalt der Cantina kontrastiert. Erstmals 2014 veröffentlicht, repräsentiert Momaw Nadon die vielfältigen außerirdischen Spezies, die Tatooines Raumhäfen bevölkern. Die Figur zeigt spezialisierte Kopfkonstruktion mit der bizarren aber unvergesslichen Physiologie des Ithorianer. Sammler schätzen Hammerhead für seine ikonische Silhouette in der Cantina-Szene und für die Darstellung der unglaublichen Biodiversität der Galaxie. Seine sanfte Pflanzenfresser-Natur und tragische Exil-Hintergrundgeschichte fügen Tiefe zu dem hinzu, was nur ein weiterer Hintergrund-Außerirdischer sein könnte, und machen diese Minifigur unverzichtbar für den Aufbau umfassender Mos Eisley Cantina Ausstellungen aus Eine neue Hoffnung.",
    fr: "Momaw Nadon, surnommé Hammerhead, est un Ithorien exilé dans la Cantina de Mos Eisley, reconnaissable à sa tête distinctive en forme de marteau et ses ouvertures buccales jumelles. Cette minifigurine LEGO capture la tête unique courbée latéralement de l'Ithorien et le comportement paisible qui contraste avec la violence de la cantina. Sortie pour la première fois en 2014, Momaw Nadon représente les diverses espèces extraterrestres qui peuplent les spatioports de Tatooine. La figurine présente une construction de tête spécialisée montrant la physiologie bizarre mais mémorable de l'Ithorien. Les collectionneurs apprécient Hammerhead pour sa silhouette iconique dans la scène de la cantina et pour représenter l'incroyable biodiversité de la galaxie. Sa nature herbivore douce et son histoire d'exil tragique ajoutent de la profondeur à ce qui pourrait n'être qu'un autre extraterrestre de fond, faisant de cette minifigurine un élément essentiel pour construire des expositions complètes de la Cantina de Mos Eisley d'Un Nouvel Espoir.",
    es: "Momaw Nadon, apodado Cabeza de Martillo, es un Ithoriano exiliado en la Cantina de Mos Eisley, reconocible por su distintiva cabeza en forma de martillo y aberturas bucales gemelas. Esta minifigura LEGO captura la única cabeza curvada lateralmente del Ithoriano y el comportamiento pacífico que contrasta con la violencia de la cantina. Lanzada por primera vez en 2014, Momaw Nadon representa las diversas especies alienígenas que pueblan los espaciopuertos de Tatooine. La figura presenta construcción de cabeza especializada mostrando la fisiología extraña pero memorable del Ithoriano. Los coleccionistas valoran a Cabeza de Martillo por su silueta icónica en la escena de cantina y por representar la increíble biodiversidad de la galaxia. Su naturaleza herbívora gentil e historia de fondo de exilio trágico añaden profundidad a lo que podría ser solo otro alienígena de fondo, haciendo que esta minifigura sea esencial para construir exhibiciones integrales de la Cantina de Mos Eisley de Una Nueva Esperanza."
  },
  {
    no: 'sw0217',
    name: 'Imperial Officer',
    en: "Imperial Officers command various military and administrative functions throughout the Empire's vast bureaucracy, wearing distinctive olive-gray uniforms with rank insignia. This LEGO minifigure features the standard officer tunic and cap worn by mid-level Imperial commanders across the galaxy. First released in 1999, the Imperial Officer has become essential for representing the Empire's professional military structure. The figure's detailed printing shows rank badges and the formal appearance that distinguishes officers from enlisted stormtroopers. Collectors value Imperial Officers for building command structures on Star Destroyers, Death Stars, and planetary garrisons. Multiple officers with varying rank insignia are crucial for recreating authentic Imperial military hierarchy and staffing control rooms, bridges, and administrative areas throughout the Original Trilogy.",
    de: "Imperiale Offiziere befehligen verschiedene militärische und administrative Funktionen in der riesigen Bürokratie des Imperiums und tragen charakteristische olivgraue Uniformen mit Rangabzeichen. Diese LEGO-Minifigur zeigt die Standard-Offiziers-Tunika und Mütze, die von mittleren imperialen Kommandeuren in der gesamten Galaxie getragen wird. Erstmals 1999 veröffentlicht, ist der Imperiale Offizier unverzichtbar geworden für die Darstellung der professionellen Militärstruktur des Imperiums. Die detaillierte Bedruckung der Figur zeigt Rangabzeichen und das formelle Aussehen, das Offiziere von eingezogenen Sturmtruppen unterscheidet. Sammler schätzen Imperiale Offiziere für den Aufbau von Kommandostrukturen auf Sternzerstörern, Todessternen und planetaren Garnisonen. Mehrere Offiziere mit variierenden Rangabzeichen sind entscheidend für die Nachbildung authentischer imperialer Militärhierarchie und die Besetzung von Kontrollräumen, Brücken und Verwaltungsbereichen während der gesamten Original-Trilogie.",
    fr: "Les Officiers Impériaux commandent diverses fonctions militaires et administratives à travers la vaste bureaucratie de l'Empire, portant des uniformes olive-gris distinctifs avec insignes de rang. Cette minifigurine LEGO présente la tunique et la casquette d'officier standard portées par les commandants Impériaux de niveau intermédiaire à travers la galaxie. Sortie pour la première fois en 1999, l'Officier Impérial est devenu essentiel pour représenter la structure militaire professionnelle de l'Empire. L'impression détaillée de la figurine montre des badges de rang et l'apparence formelle qui distingue les officiers des stormtroopers enrôlés. Les collectionneurs apprécient les Officiers Impériaux pour construire des structures de commandement sur les Destroyers Stellaires, les Étoiles de la Mort et les garnisons planétaires. Plusieurs officiers avec des insignes de rang variables sont cruciaux pour recréer une hiérarchie militaire Impériale authentique et doter en personnel les salles de contrôle, les ponts et les zones administratives tout au long de la trilogie originale.",
    es: "Los Oficiales Imperiales comandan varias funciones militares y administrativas a través de la vasta burocracia del Imperio, usando distintivos uniformes gris oliva con insignias de rango. Esta minifigura LEGO presenta la túnica y gorra de oficial estándar usadas por comandantes Imperiales de nivel medio a través de la galaxia. Lanzada por primera vez en 1999, el Oficial Imperial se ha vuelto esencial para representar la estructura militar profesional del Imperio. La impresión detallada de la figura muestra insignias de rango y la apariencia formal que distingue a oficiales de soldados de asalto enlistados. Los coleccionistas valoran a los Oficiales Imperiales por construir estructuras de comando en Destructores Estelares, Estrellas de la Muerte y guarniciones planetarias. Múltiples oficiales con insignias de rango variables son cruciales para recrear auténtica jerarquía militar Imperial y equipar salas de control, puentes y áreas administrativas a lo largo de la trilogía original."
  },
  {
    no: 'sw0218',
    name: 'Grand Moff Tarkin',
    en: "Grand Moff Tarkin commands the Death Star as governor of the Imperial Outland Regions, wielding absolute authority and demonstrating ruthless tactics like destroying Alderaan. This LEGO minifigure captures Tarkin's gaunt appearance with sharp features, gray-green uniform, and rank insignia showing his position above even Darth Vader. First released in 2006, Grand Moff Tarkin represents the Empire's cold bureaucratic evil and political power structure. The figure features detailed printing showing his distinctive facial features and high-ranking officer uniform. Collectors value Grand Moff Tarkin for his chilling command presence and for representing the destruction of Alderaan, one of Star Wars' most tragic moments. His authority over the Death Star and conflicts with Vader make this minifigure essential for recreating command deck and conference room scenes from A New Hope.",
    de: "Großmoff Tarkin befehligt den Todesstern als Gouverneur der imperialen Außenregionen, übt absolute Autorität aus und demonstriert rücksichtslose Taktiken wie die Zerstörung von Alderaan. Diese LEGO-Minifigur fängt Tarkins hageres Aussehen mit scharfen Zügen, grau-grüner Uniform und Rangabzeichen ein, die seine Position über sogar Darth Vader zeigen. Erstmals 2006 veröffentlicht, repräsentiert Großmoff Tarkin das kalte bürokratische Böse und die politische Machtstruktur des Imperiums. Die Figur zeigt detaillierte Bedruckung mit seinen charakteristischen Gesichtszügen und hochrangiger Offiziers-Uniform. Sammler schätzen Großmoff Tarkin für seine erschreckende Kommandopräsenz und für die Darstellung der Zerstörung von Alderaan, einem der tragischsten Momente von Star Wars. Seine Autorität über den Todesstern und Konflikte mit Vader machen diese Minifigur unverzichtbar für die Nachbildung von Kommandobrücken- und Konferenzraumszenen aus Eine neue Hoffnung.",
    fr: "Le Grand Moff Tarkin commande l'Étoile de la Mort en tant que gouverneur des Régions Extérieures Impériales, exerçant une autorité absolue et démontrant des tactiques impitoyables comme la destruction d'Alderaan. Cette minifigurine LEGO capture l'apparence émaciée de Tarkin avec des traits aigus, un uniforme gris-vert et des insignes de rang montrant sa position au-dessus même de Dark Vador. Sortie pour la première fois en 2006, le Grand Moff Tarkin représente le mal bureaucratique froid de l'Empire et la structure de pouvoir politique. La figurine présente une impression détaillée montrant ses traits faciaux distinctifs et son uniforme d'officier de haut rang. Les collectionneurs apprécient le Grand Moff Tarkin pour sa présence de commandement glaçante et pour représenter la destruction d'Alderaan, l'un des moments les plus tragiques de Star Wars. Son autorité sur l'Étoile de la Mort et ses conflits avec Vador font de cette minifigurine un élément essentiel pour recréer des scènes de pont de commandement et de salle de conférence d'Un Nouvel Espoir.",
    es: "El Gran Moff Tarkin comanda la Estrella de la Muerte como gobernador de las Regiones Exteriores Imperiales, ejerciendo autoridad absoluta y demostrando tácticas despiadadas como destruir Alderaan. Esta minifigura LEGO captura la apariencia demacrada de Tarkin con rasgos afilados, uniforme gris-verde e insignia de rango mostrando su posición por encima incluso de Darth Vader. Lanzada por primera vez en 2006, el Gran Moff Tarkin representa la maldad burocrática fría del Imperio y estructura de poder político. La figura presenta impresión detallada mostrando sus rasgos faciales distintivos y uniforme de oficial de alto rango. Los coleccionistas valoran al Gran Moff Tarkin por su presencia de comando escalofriante y por representar la destrucción de Alderaan, uno de los momentos más trágicos de Star Wars. Su autoridad sobre la Estrella de la Muerte y conflictos con Vader hacen que esta minifigura sea esencial para recrear escenas de cubierta de comando y sala de conferencias de Una Nueva Esperanza."
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 106-110 (sw0214-sw0218)...\n');

  for (const m of batch) {
    await prisma.minifigCatalog.upsert({
      where: { minifigure_no: m.no },
      update: {
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      },
      create: {
        minifigure_no: m.no,
        name: m.name,
        category_id: 1,
        category_name: 'Star Wars',
        search_name: m.name.toLowerCase(),
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`  ✅ ${m.no}: ${m.name}`);
  }

  console.log(`\n✨ Batch 106-110 complete: 5 minifigs (20 descriptions)`);
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
