import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0149',
    name: 'AT-ST Driver',
    en: "The AT-ST Driver pilots the Imperial All Terrain Scout Transport walker, providing mobile firepower and reconnaissance for ground operations across the galaxy. This LEGO minifigure features the distinctive gray and black armor with specialized helmet design that differs from standard stormtroopers. First released in 2001 in various AT-ST sets, the AT-ST Driver has become a recognizable Imperial specialist unit for collectors. The figure's unique helmet printing and armor markings identify the elite training required to operate these two-legged walkers. Collectors value AT-ST Drivers for completing Imperial ground forces displays and for their prominence in both The Empire Strikes Back and Return of the Jedi. Multiple versions have been released with updated printing detail showing the evolution of LEGO's minifigure design quality.",
    de: "Der AT-ST-Pilot steuert den imperialen All Terrain Scout Transport Walker und bietet mobile Feuerkraft und Aufklärung für Bodenoperationen in der gesamten Galaxie. Diese LEGO-Minifigur zeigt die charakteristische graue und schwarze Rüstung mit spezialisiertem Helmdesign, das sich von Standard-Sturmtruppen unterscheidet. Erstmals 2001 in verschiedenen AT-ST Sets veröffentlicht, ist der AT-ST-Pilot zu einer erkennbaren imperialen Spezialeinheit für Sammler geworden. Die einzigartige Helmbedruckung und Rüstungsmarkierungen der Figur kennzeichnen die Eliteausbildung, die erforderlich ist, um diese zweibeinigen Walker zu bedienen. Sammler schätzen AT-ST-Piloten für die Vervollständigung imperialer Bodentruppen-Ausstellungen und für ihre Prominenz sowohl in Das Imperium schlägt zurück als auch Die Rückkehr der Jedi-Ritter. Mehrere Versionen wurden mit aktualisierter Druckdetail veröffentlicht, die die Evolution der LEGO-Minifigur-Designqualität zeigen.",
    fr: "Le Pilote d'AT-ST pilote le marcheur de transport de reconnaissance tout-terrain Impérial, fournissant puissance de feu mobile et reconnaissance pour les opérations terrestres à travers la galaxie. Cette minifigurine LEGO présente l'armure grise et noire distinctive avec un design de casque spécialisé qui diffère des stormtroopers standard. Sortie pour la première fois en 2001 dans divers sets AT-ST, le Pilote d'AT-ST est devenu une unité spécialiste Impériale reconnaissable pour les collectionneurs. L'impression de casque unique et les marquages d'armure de la figurine identifient la formation d'élite requise pour opérer ces marcheurs à deux jambes. Les collectionneurs apprécient les Pilotes d'AT-ST pour compléter les expositions de forces terrestres Impériales et pour leur importance dans L'Empire contre-attaque et Le Retour du Jedi. Plusieurs versions ont été publiées avec des détails d'impression mis à jour montrant l'évolution de la qualité de conception des minifigurines LEGO.",
    es: "El Piloto de AT-ST pilotea el caminante de Transporte de Exploración Todo Terreno Imperial, proporcionando potencia de fuego móvil y reconocimiento para operaciones terrestres a través de la galaxia. Esta minifigura LEGO presenta la distintiva armadura gris y negra con diseño de casco especializado que difiere de los soldados de asalto estándar. Lanzada por primera vez en 2001 en varios sets AT-ST, el Piloto de AT-ST se ha convertido en una unidad especialista Imperial reconocible para coleccionistas. La impresión única de casco y marcas de armadura de la figura identifican el entrenamiento de élite requerido para operar estos caminantes de dos patas. Los coleccionistas valoran a los Pilotos de AT-ST por completar exhibiciones de fuerzas terrestres Imperiales y por su prominencia tanto en El Imperio Contraataca como en El Retorno del Jedi. Múltiples versiones han sido lanzadas con detalles de impresión actualizados mostrando la evolución de la calidad de diseño de minifiguras LEGO."
  },
  {
    no: 'sw0150',
    name: 'Imperial Officer (Battle of Endor)',
    en: "This Imperial Officer commanded ground forces during the critical Battle of Endor, coordinating the Empire's defense of the second Death Star's shield generator on the forest moon. The LEGO minifigure features the standard olive-gray Imperial officer uniform with rank insignia and command cap distinctive to the military hierarchy. Released in 2002 in the Imperial AT-ST set, this officer represents the field commanders who led troops against both Rebel commandos and native Ewok warriors. The figure's clean uniform design and authoritative appearance make it essential for recreating the Empire's final stand. Collectors value Imperial Officers for building command structures within their Imperial forces and for representing the bureaucratic military machine. Multiple officers are often desired to properly staff large Imperial base displays with appropriate leadership hierarchy.",
    de: "Dieser imperiale Offizier befehligte Bodentruppen während der kritischen Schlacht von Endor und koordinierte die Verteidigung des Schildgenerators des zweiten Todessterns durch das Imperium auf dem Waldmond. Die LEGO-Minifigur zeigt die Standard-olivgraue imperiale Offiziersuniform mit Rangabzeichen und Kommandomütze, die für die militärische Hierarchie charakteristisch ist. 2002 im Imperial AT-ST Set veröffentlicht, repräsentiert dieser Offizier die Feldkommandanten, die Truppen gegen sowohl Rebellenkommandos als auch einheimische Ewok-Krieger führten. Das saubere Uniformdesign und das autoritäre Aussehen der Figur machen sie unverzichtbar für die Nachbildung des letzten Gefechts des Imperiums. Sammler schätzen imperiale Offiziere für den Aufbau von Kommandostrukturen innerhalb ihrer imperialen Streitkräfte und für die Darstellung der bürokratischen Militärmaschine. Mehrere Offiziere werden oft gewünscht, um große imperiale Basis-Ausstellungen mit angemessener Führungshierarchie ordnungsgemäß zu besetzen.",
    fr: "Cet Officier Impérial commandait les forces terrestres pendant la Bataille cruciale d'Endor, coordonnant la défense de l'Empire du générateur de bouclier de la seconde Étoile de la Mort sur la lune forestière. La minifigurine LEGO présente l'uniforme d'officier Impérial olive-gris standard avec insigne de grade et casquette de commandement distinctifs de la hiérarchie militaire. Sortie en 2002 dans le set AT-ST Impérial, cet officier représente les commandants de terrain qui ont dirigé les troupes contre les commandos Rebelles et les guerriers Ewok natifs. Le design d'uniforme propre et l'apparence autoritaire de la figurine la rendent essentielle pour recréer le dernier combat de l'Empire. Les collectionneurs apprécient les Officiers Impériaux pour construire des structures de commandement au sein de leurs forces Impériales et pour représenter la machine militaire bureaucratique. Plusieurs officiers sont souvent désirés pour équiper correctement de grandes expositions de bases Impériales avec une hiérarchie de leadership appropriée.",
    es: "Este Oficial Imperial comandaba fuerzas terrestres durante la crítica Batalla de Endor, coordinando la defensa del Imperio del generador de escudo de la segunda Estrella de la Muerte en la luna boscosa. La minifigura LEGO presenta el uniforme de oficial Imperial gris oliva estándar con insignia de rango y gorra de comando distintivos de la jerarquía militar. Lanzada en 2002 en el set AT-ST Imperial, este oficial representa a los comandantes de campo que dirigieron tropas contra comandos Rebeldes y guerreros Ewok nativos. El diseño de uniforme limpio y apariencia autoritaria de la figura la hacen esencial para recrear la última batalla del Imperio. Los coleccionistas valoran a los Oficiales Imperiales por construir estructuras de comando dentro de sus fuerzas Imperiales y por representar la máquina militar burocrática. Múltiples oficiales son frecuentemente deseados para equipar apropiadamente grandes exhibiciones de bases Imperiales con jerarquía de liderazgo apropiada."
  },
  {
    no: 'sw0151',
    name: 'Rebel Commando (Battle of Endor)',
    en: "The Rebel Commando represents the elite strike force soldiers who infiltrated Endor to destroy the Death Star's shield generator in Return of the Jedi. This LEGO minifigure features camouflage uniform patterns, combat webbing, and specialized gear designed for guerrilla operations in forest environments. First released in 2002 in various Endor-themed sets, the Rebel Commando has become essential for recreating the Battle of Endor's ground assault. The figure typically includes a blaster rifle and sometimes a backpack, reflecting the light infantry tactics used against Imperial forces. Collectors value Rebel Commandos for building complete strike teams and for their crucial role in the Original Trilogy's climactic battle. Multiple commandos are needed to properly recreate the full assault force that worked alongside Ewok warriors to defeat the Empire.",
    de: "Der Rebellenkommando repräsentiert die Elite-Schlagkraftsoldaten, die Endor infiltrierten, um den Schildgenerator des Todessterns in Die Rückkehr der Jedi-Ritter zu zerstören. Diese LEGO-Minifigur zeigt Tarnuniformmuster, Kampfgurte und spezialisierte Ausrüstung, die für Guerillaoperationen in Waldumgebungen konzipiert ist. Erstmals 2002 in verschiedenen Endor-thematisierten Sets veröffentlicht, ist der Rebellenkommando unverzichtbar geworden für die Nachbildung des Bodenangriffs der Schlacht von Endor. Die Figur enthält typischerweise ein Blastergewehr und manchmal einen Rucksack, was die leichten Infanterietaktiken widerspiegelt, die gegen imperiale Streitkräfte eingesetzt wurden. Sammler schätzen Rebellenkommandos für den Aufbau vollständiger Schlagteams und für ihre entscheidende Rolle in der klimatischen Schlacht der Original-Trilogie. Mehrere Kommandos werden benötigt, um die vollständige Angriffstruppe ordnungsgemäß nachzubilden, die zusammen mit Ewok-Kriegern das Imperium besiegte.",
    fr: "Le Commando Rebelle représente les soldats de force de frappe d'élite qui ont infiltré Endor pour détruire le générateur de bouclier de l'Étoile de la Mort dans Le Retour du Jedi. Cette minifigurine LEGO présente des motifs d'uniforme de camouflage, des sangles de combat et un équipement spécialisé conçu pour les opérations de guérilla dans les environnements forestiers. Sortie pour la première fois en 2002 dans divers sets à thème Endor, le Commando Rebelle est devenu essentiel pour recréer l'assaut terrestre de la Bataille d'Endor. La figurine comprend généralement un fusil blaster et parfois un sac à dos, reflétant les tactiques d'infanterie légère utilisées contre les forces Impériales. Les collectionneurs apprécient les Commandos Rebelles pour construire des équipes de frappe complètes et pour leur rôle crucial dans la bataille culminante de la trilogie originale. Plusieurs commandos sont nécessaires pour recréer correctement la force d'assaut complète qui a travaillé aux côtés des guerriers Ewok pour vaincre l'Empire.",
    es: "El Comando Rebelde representa a los soldados de fuerza de ataque de élite que infiltraron Endor para destruir el generador de escudo de la Estrella de la Muerte en El Retorno del Jedi. Esta minifigura LEGO presenta patrones de uniforme de camuflaje, correas de combate y equipo especializado diseñado para operaciones de guerrilla en ambientes forestales. Lanzada por primera vez en 2002 en varios sets temáticos de Endor, el Comando Rebelde se ha vuelto esencial para recrear el asalto terrestre de la Batalla de Endor. La figura típicamente incluye un rifle bláster y a veces una mochila, reflejando las tácticas de infantería ligera usadas contra fuerzas Imperiales. Los coleccionistas valoran a los Comandos Rebeldes por construir equipos de ataque completos y por su papel crucial en la batalla culminante de la trilogía original. Múltiples comandos son necesarios para recrear apropiadamente la fuerza de asalto completa que trabajó junto a guerreros Ewok para derrotar al Imperio."
  },
  {
    no: 'sw0152',
    name: 'Luke Skywalker (Endor)',
    en: "Luke Skywalker appears in his black Jedi outfit during the Battle of Endor, having fully embraced his destiny as a Jedi Knight before confronting Darth Vader and the Emperor. This LEGO minifigure captures Luke's mature appearance from Return of the Jedi with his distinctive all-black clothing and Jedi belt. Released in 2002, this version represents one of the most significant character moments as Luke completes his hero's journey. The figure typically includes a green lightsaber and sometimes a removable cloak, reflecting his status as a fully trained Jedi. Collectors prize this Luke variant for representing the climax of the Original Trilogy and for completing Endor battle scenes. His confident, darker appearance marks the transformation from farm boy to Jedi Master, making this an essential version for any Star Wars collection.",
    de: "Luke Skywalker erscheint in seinem schwarzen Jedi-Outfit während der Schlacht von Endor, nachdem er sein Schicksal als Jedi-Ritter vollständig angenommen hat, bevor er Darth Vader und dem Imperator gegenübertritt. Diese LEGO-Minifigur fängt Lukes reifes Aussehen aus Die Rückkehr der Jedi-Ritter mit seiner charakteristischen ganz schwarzen Kleidung und dem Jedi-Gürtel ein. 2002 veröffentlicht, repräsentiert diese Version einen der bedeutendsten Charaktermomente, da Luke seine Heldenreise vollendet. Die Figur enthält typischerweise ein grünes Lichtschwert und manchmal einen abnehmbaren Umhang, was seinen Status als vollständig ausgebildeter Jedi widerspiegelt. Sammler schätzen diese Luke-Variante für die Darstellung des Höhepunkts der Original-Trilogie und für die Vervollständigung von Endor-Schlachtszenen. Sein selbstbewusstes, dunkleres Aussehen markiert die Verwandlung vom Farmjungen zum Jedi-Meister und macht dies zu einer unverzichtbaren Version für jede Star Wars Sammlung.",
    fr: "Luke Skywalker apparaît dans sa tenue Jedi noire pendant la Bataille d'Endor, ayant pleinement embrassé son destin de Chevalier Jedi avant d'affronter Dark Vador et l'Empereur. Cette minifigurine LEGO capture l'apparence mature de Luke du Retour du Jedi avec ses vêtements tout noirs distinctifs et sa ceinture Jedi. Sortie en 2002, cette version représente l'un des moments de personnage les plus significatifs alors que Luke complète son voyage de héros. La figurine comprend généralement un sabre laser vert et parfois une cape amovible, reflétant son statut de Jedi entièrement formé. Les collectionneurs apprécient cette variante de Luke pour représenter le point culminant de la trilogie originale et pour compléter les scènes de bataille d'Endor. Son apparence confiante et plus sombre marque la transformation de garçon de ferme à Maître Jedi, faisant de celle-ci une version essentielle pour toute collection Star Wars.",
    es: "Luke Skywalker aparece en su atuendo Jedi negro durante la Batalla de Endor, habiendo abrazado completamente su destino como Caballero Jedi antes de confrontar a Darth Vader y al Emperador. Esta minifigura LEGO captura la apariencia madura de Luke de El Retorno del Jedi con su distintiva ropa completamente negra y cinturón Jedi. Lanzada en 2002, esta versión representa uno de los momentos de personaje más significativos mientras Luke completa su viaje de héroe. La figura típicamente incluye un sable de luz verde y a veces una capa removible, reflejando su estatus como Jedi completamente entrenado. Los coleccionistas valoran esta variante de Luke por representar el clímax de la trilogía original y por completar escenas de batalla de Endor. Su apariencia confiada y más oscura marca la transformación de granjero a Maestro Jedi, haciendo de esta una versión esencial para cualquier colección de Star Wars."
  },
  {
    no: 'sw0153',
    name: 'Princess Leia (Endor)',
    en: "Princess Leia wears her distinctive camouflage poncho and combat gear during the Battle of Endor, leading Rebel forces alongside Han Solo in the ground assault. This LEGO minifigure captures her practical military outfit with detailed printing showing her field commander appearance from Return of the Jedi. First released in 2002, this version represents Leia at her most action-oriented, combining her diplomatic leadership with hands-on combat skills. The figure typically includes a blaster pistol and sometimes features the brown camouflage poncho that became iconic from the forest moon battle. Collectors value this Leia variant for showing her evolution from senator to general and for completing Endor strike team displays. Her partnership with Han and leadership of the commando mission make this an essential version for Original Trilogy battle recreations.",
    de: "Prinzessin Leia trägt ihren charakteristischen Tarnponcho und Kampfausrüstung während der Schlacht von Endor und führt Rebellentruppen zusammen mit Han Solo im Bodenangriff an. Diese LEGO-Minifigur fängt ihr praktisches Militäroutfit mit detaillierter Bedruckung ein, die ihr Feldkommandanten-Aussehen aus Die Rückkehr der Jedi-Ritter zeigt. Erstmals 2002 veröffentlicht, repräsentiert diese Version Leia in ihrer aktionsorientiertesten Form und kombiniert ihre diplomatische Führung mit praktischen Kampffähigkeiten. Die Figur enthält typischerweise eine Blasterpistole und zeigt manchmal den braunen Tarnponcho, der ikonisch aus der Waldmond-Schlacht wurde. Sammler schätzen diese Leia-Variante für die Darstellung ihrer Evolution von Senatorin zur Generalin und für die Vervollständigung von Endor-Schlagteam-Ausstellungen. Ihre Partnerschaft mit Han und Führung der Kommandomission machen dies zu einer unverzichtbaren Version für Original-Trilogie-Schlacht-Nachbildungen.",
    fr: "La Princesse Leia porte son poncho de camouflage distinctif et son équipement de combat pendant la Bataille d'Endor, dirigeant les forces Rebelles aux côtés de Han Solo dans l'assaut terrestre. Cette minifigurine LEGO capture sa tenue militaire pratique avec une impression détaillée montrant son apparence de commandant de terrain du Retour du Jedi. Sortie pour la première fois en 2002, cette version représente Leia à son plus orienté action, combinant son leadership diplomatique avec des compétences de combat pratiques. La figurine comprend généralement un pistolet blaster et présente parfois le poncho de camouflage brun qui est devenu iconique de la bataille de la lune forestière. Les collectionneurs apprécient cette variante de Leia pour montrer son évolution de sénatrice à général et pour compléter les expositions d'équipe de frappe d'Endor. Son partenariat avec Han et son leadership de la mission commando font de celle-ci une version essentielle pour les recréations de bataille de la trilogie originale.",
    es: "La Princesa Leia usa su distintivo poncho de camuflaje y equipo de combate durante la Batalla de Endor, liderando fuerzas Rebeldes junto a Han Solo en el asalto terrestre. Esta minifigura LEGO captura su atuendo militar práctico con impresión detallada mostrando su apariencia de comandante de campo de El Retorno del Jedi. Lanzada por primera vez en 2002, esta versión representa a Leia en su forma más orientada a la acción, combinando su liderazgo diplomático con habilidades de combate prácticas. La figura típicamente incluye una pistola bláster y a veces presenta el poncho de camuflaje marrón que se volvió icónico de la batalla de la luna boscosa. Los coleccionistas valoran esta variante de Leia por mostrar su evolución de senadora a general y por completar exhibiciones de equipo de ataque de Endor. Su asociación con Han y liderazgo de la misión comando hacen de esta una versión esencial para recreaciones de batalla de la trilogía original."
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 41-45 (sw0149-sw0153)...\n');

  for (const m of batch) {
    await prisma.minifigCatalog.upsert({
      where: { minifigure_no: m.no },
      update: {
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      },
      create: {
        minifigure_no: m.no,
        name: m.name,
        category_id: 1,
        category_name: 'Star Wars',
        search_name: m.name.toLowerCase(),
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`  ✅ ${m.no}: ${m.name}`);
  }

  console.log(`\n✨ Batch 41-45 complete: 5 minifigs (20 descriptions)`);
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
