import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0249',
    name: 'Shaak Ti',
    en: 'Shaak Ti\'s LEGO minifigure showcases the elegant Togruta Jedi Master with her distinctive red and white head-tails (montrals and lekku), facial markings, and the traditional brown Jedi robes that marked her as a senior member of the Jedi Order. This minifigure features detailed printing representing one of the few Jedi Council members to survive the initial outbreak of Order 66, known for her compassion and her crucial role overseeing clone trooper training on Kamino. As guardian of the cloning facilities and mentor to countless clone warriors, Shaak Ti developed deep connections with the Republic\'s army, making her survival beyond the initial Jedi purge particularly significant. Released in sets from 2011 onwards with Clone Wars variants, this minifigure appeals to collectors who appreciate Shaak Ti\'s unique Togruta design, her extensive role in The Clone Wars animated series, and her representation of the Jedi Order\'s connection to the clone army throughout the war.',
    de: 'Die LEGO-Minifigur von Shaak Ti zeigt die elegante Togruta-Jedi-Meisterin mit ihren markanten rot-weißen Kopfschwänzen (Montrals und Lekku), Gesichtsmarkierungen und den traditionellen braunen Jedi-Roben, die sie als hochrangiges Mitglied des Jedi-Ordens kennzeichneten. Diese Minifigur verfügt über detaillierte Bedruckung, die eines der wenigen Jedi-Ratsmitglieder repräsentiert, die den ersten Ausbruch von Order 66 überlebten, bekannt für ihr Mitgefühl und ihre entscheidende Rolle bei der Überwachung der Klonkrieger-Ausbildung auf Kamino. Als Wächterin der Klonierungsanlagen und Mentorin unzähliger Klonkrieger entwickelte Shaak Ti tiefe Verbindungen zur Armee der Republik, was ihr Überleben über die anfängliche Jedi-Säuberung hinaus besonders bedeutsam macht. In Sets ab 2011 veröffentlicht, wobei Clone Wars-Varianten erschienen, spricht diese Minifigur Sammler an, die Shaak Tis einzigartiges Togruta-Design, ihre umfassende Rolle in der Clone Wars-Animationsserie und ihre Darstellung der Verbindung des Jedi-Ordens zur Klon-Armee während des gesamten Krieges schätzen.',
    fr: 'La minifigurine LEGO de Shaak Ti présente l\'élégante Maître Jedi Togruta avec ses queues de tête rouge et blanc distinctives (montrals et lekku), ses marques faciales, et les robes Jedi marron traditionnelles qui la marquaient comme membre senior de l\'Ordre Jedi. Cette minifigurine présente une impression détaillée représentant l\'un des rares membres du Conseil Jedi à avoir survécu à l\'épidémie initiale de l\'Ordre 66, connue pour sa compassion et son rôle crucial supervisant l\'entraînement des soldats clones sur Kamino. En tant que gardienne des installations de clonage et mentor d\'innombrables guerriers clones, Shaak Ti a développé des liens profonds avec l\'armée de la République, rendant sa survie au-delà de la purge Jedi initiale particulièrement significative. Sortie dans des sets à partir de 2011 avec des variantes Clone Wars, cette minifigurine plaît aux collectionneurs qui apprécient le design Togruta unique de Shaak Ti, son rôle étendu dans la série animée The Clone Wars, et sa représentation de la connexion de l\'Ordre Jedi à l\'armée clone tout au long de la guerre.',
    es: 'La minifigura LEGO de Shaak Ti muestra a la elegante Maestra Jedi Togruta con sus distintivas colas de cabeza rojas y blancas (montrales y lekku), marcas faciales, y las tradicionales túnicas Jedi marrones que la marcaban como miembro senior de la Orden Jedi. Esta minifigura presenta impresión detallada representando a uno de los pocos miembros del Consejo Jedi en sobrevivir al brote inicial de la Orden 66, conocida por su compasión y su papel crucial supervisando el entrenamiento de soldados clon en Kamino. Como guardiana de las instalaciones de clonación y mentora de incontables guerreros clon, Shaak Ti desarrolló conexiones profundas con el ejército de la República, haciendo su supervivencia más allá de la purga Jedi inicial particularmente significativa. Lanzada en sets desde 2011 con variantes Clone Wars, esta minifigura atrae a coleccionistas que aprecian el diseño Togruta único de Shaak Ti, su extenso papel en la serie animada The Clone Wars, y su representación de la conexión de la Orden Jedi con el ejército clon durante toda la guerra.'
  },
  {
    no: 'sw0250',
    name: 'Saesee Tiin',
    en: 'Saesee Tiin\'s LEGO minifigure captures the Iktotchi Jedi Master with his distinctive horned head, gray-brown skin tone, and traditional Jedi robes, representing one of the Jedi Council\'s most skilled starfighter pilots and tacticians. This minifigure features detailed printing showing his contemplative expression and robes, embodying a Jedi known for his exceptional telepathic abilities and his mastery of high-speed combat both in the cockpit and in lightsaber duels. As one of the few Jedi to accompany Mace Windu in the attempted arrest of Chancellor Palpatine, Saesee Tiin demonstrated ultimate bravery despite falling quickly to the Sith Lord\'s overwhelming power. Released in sets from 2012 onwards, this minifigure appeals to dedicated collectors who appreciate the deeper Jedi Council membership representation, with Saesee Tiin\'s unique Iktotchi design and his heroic final stand making him a meaningful addition to complete Jedi Council collections and Revenge of the Sith displays.',
    de: 'Die LEGO-Minifigur von Saesee Tiin fängt den Iktotchi-Jedi-Meister mit seinem markanten gehörnten Kopf, graubraunem Hautton und traditionellen Jedi-Roben ein, der eines der geschicktesten Sternenjäger-Piloten und Taktiker des Jedi-Rats repräsentiert. Diese Minifigur verfügt über detaillierte Bedruckung, die seinen nachdenklichen Ausdruck und seine Roben zeigt, die einen Jedi verkörpern, der für seine außergewöhnlichen telepathischen Fähigkeiten und seine Beherrschung des Hochgeschwindigkeitskampfes sowohl im Cockpit als auch in Lichtschwert-Duellen bekannt ist. Als einer der wenigen Jedi, die Mace Windu beim versuchten Arrest von Kanzler Palpatine begleiteten, demonstrierte Saesee Tiin ultimative Tapferkeit, obwohl er schnell der überwältigenden Macht des Sith-Lords erlag. In Sets ab 2012 veröffentlicht, spricht diese Minifigur engagierte Sammler an, die die tiefere Darstellung der Jedi-Ratsmitgliedschaft schätzen, wobei Saesee Tiins einzigartiges Iktotchi-Design und sein heroisches letztes Gefecht ihn zu einer bedeutungsvollen Ergänzung machen, um Jedi-Rats-Sammlungen und Die Rache der Sith-Displays zu vervollständigen.',
    fr: 'La minifigurine LEGO de Saesee Tiin capture le Maître Jedi Iktotchi avec sa tête cornue distinctive, son teint de peau gris-brun, et ses robes Jedi traditionnelles, représentant l\'un des pilotes de chasseurs stellaires et tacticiens les plus habiles du Conseil Jedi. Cette minifigurine présente une impression détaillée montrant son expression contemplative et ses robes, incarnant un Jedi connu pour ses capacités télépathiques exceptionnelles et sa maîtrise du combat à grande vitesse à la fois dans le cockpit et dans les duels au sabre laser. En tant que l\'un des rares Jedi à accompagner Mace Windu dans la tentative d\'arrestation du Chancelier Palpatine, Saesee Tiin a démontré un courage ultime malgré sa chute rapide face au pouvoir écrasant du Seigneur Sith. Sortie dans des sets à partir de 2012, cette minifigurine plaît aux collectionneurs dédiés qui apprécient la représentation plus profonde des membres du Conseil Jedi, le design Iktotchi unique de Saesee Tiin et son dernier combat héroïque en faisant un ajout significatif pour compléter les collections du Conseil Jedi et les présentations de La Revanche des Sith.',
    es: 'La minifigura LEGO de Saesee Tiin captura al Maestro Jedi Iktotchi con su distintiva cabeza con cuernos, tono de piel gris-marrón, y túnicas Jedi tradicionales, representando a uno de los pilotos de cazas estelares y tácticos más hábiles del Consejo Jedi. Esta minifigura presenta impresión detallada mostrando su expresión contemplativa y túnicas, encarnando a un Jedi conocido por sus excepcionales habilidades telepáticas y su maestría del combate de alta velocidad tanto en la cabina como en duelos con sable de luz. Como uno de los pocos Jedi en acompañar a Mace Windu en el intento de arresto del Canciller Palpatine, Saesee Tiin demostró valentía suprema a pesar de caer rápidamente ante el poder abrumador del Señor Sith. Lanzada en sets desde 2012, esta minifigura atrae a coleccionistas dedicados que aprecian la representación más profunda de la membresía del Consejo Jedi, con el diseño Iktotchi único de Saesee Tiin y su heroica última resistencia haciéndolo una adición significativa para completar colecciones del Consejo Jedi y exhibiciones de La Venganza de los Sith.'
  },
  {
    no: 'sw0251',
    name: 'Barriss Offee',
    en: 'Barriss Offee\'s LEGO minifigure depicts the Mirialan Jedi Padawan with her distinctive blue facial tattoos, dark robes, and the traditional headdress that marked her as Luminara Unduli\'s apprentice. This minifigure features detailed printing showing her contemplative expression and modest attire, representing a character whose journey from dedicated healer to disillusioned bomber became one of The Clone Wars animated series\' most shocking storylines. Known initially for her medical expertise and compassionate nature during early Clone Wars battles, Barriss\'s eventual terrorist attack on the Jedi Temple and framing of Ahsoka Tano revealed her deep disillusionment with the Jedi Order\'s role in the war. Released in sets from 2013 onwards during The Clone Wars series run, this minifigure became particularly collectible due to Barriss\'s complex character arc, representing themes of war\'s corrupting influence and the Jedi Order\'s gradual loss of moral clarity that foreshadowed Order 66 and the Empire\'s rise.',
    de: 'Die LEGO-Minifigur von Barriss Offee zeigt die Mirialan-Jedi-Padawan mit ihren markanten blauen Gesichtstätowierungen, dunklen Roben und dem traditionellen Kopfschmuck, der sie als Schülerin von Luminara Unduli kennzeichnete. Diese Minifigur verfügt über detaillierte Bedruckung, die ihren nachdenklichen Ausdruck und ihre bescheidene Kleidung zeigt, die einen Charakter repräsentiert, dessen Reise von engagierter Heilerin zu desillusionierter Bomberin zu einer der schockierendsten Handlungsstränge der Clone Wars-Animationsserie wurde. Anfangs bekannt für ihre medizinische Expertise und mitfühlende Natur während früher Klonkriegs-Schlachten, enthüllte Barriss\' späterer Terrorangriff auf den Jedi-Tempel und ihre falsche Anschuldigung von Ahsoka Tano ihre tiefe Desillusionierung über die Rolle des Jedi-Ordens im Krieg. In Sets ab 2013 während des Laufs der Clone Wars-Serie veröffentlicht, wurde diese Minifigur besonders sammelwürdig aufgrund von Barriss\' komplexem Charakterbogen, der Themen des korrumpierenden Einflusses des Krieges und des allmählichen Verlusts moralischer Klarheit des Jedi-Ordens repräsentiert, der Order 66 und den Aufstieg des Imperiums vorwegnahm.',
    fr: 'La minifigurine LEGO de Barriss Offee dépeint la Padawan Jedi Mirialan avec ses tatouages faciaux bleus distinctifs, ses robes sombres, et la coiffe traditionnelle qui la marquait comme apprentie de Luminara Unduli. Cette minifigurine présente une impression détaillée montrant son expression contemplative et sa tenue modeste, représentant un personnage dont le voyage de guérisseuse dévouée à bombardière désabusée est devenu l\'une des intrigues les plus choquantes de la série animée The Clone Wars. Connue initialement pour son expertise médicale et sa nature compatissante pendant les premières batailles de Clone Wars, l\'attentat terroriste éventuel de Barriss sur le Temple Jedi et l\'accusation erronée d\'Ahsoka Tano ont révélé sa profonde désillusion avec le rôle de l\'Ordre Jedi dans la guerre. Sortie dans des sets à partir de 2013 pendant la diffusion de la série The Clone Wars, cette minifigurine est devenue particulièrement collectionnable en raison de l\'arc de personnage complexe de Barriss, représentant les thèmes de l\'influence corruptrice de la guerre et la perte graduelle de clarté morale de l\'Ordre Jedi qui préfigurait l\'Ordre 66 et la montée de l\'Empire.',
    es: 'La minifigura LEGO de Barriss Offee representa a la Padawan Jedi Mirialan con sus distintivos tatuajes faciales azules, túnicas oscuras, y el tocado tradicional que la marcaba como aprendiz de Luminara Unduli. Esta minifigura presenta impresión detallada mostrando su expresión contemplativa y atuendo modesto, representando a un personaje cuyo viaje desde sanadora dedicada hasta bombardera desilusionada se convirtió en una de las tramas más impactantes de la serie animada The Clone Wars. Conocida inicialmente por su experiencia médica y naturaleza compasiva durante las primeras batallas de las Guerras Clon, el eventual ataque terrorista de Barriss al Templo Jedi y su acusación falsa de Ahsoka Tano revelaron su profunda desilusión con el papel de la Orden Jedi en la guerra. Lanzada en sets desde 2013 durante la emisión de la serie The Clone Wars, esta minifigura se volvió particularmente coleccionable debido al complejo arco del personaje de Barriss, representando temas de la influencia corruptora de la guerra y la pérdida gradual de claridad moral de la Orden Jedi que presagió la Orden 66 y el ascenso del Imperio.'
  },
  {
    no: 'sw0252',
    name: 'Jar Jar Binks',
    en: 'Jar Jar Binks\'s LEGO minifigure captures the clumsy Gungan with his distinctive orange skin, long ear stalks, and the simple vest that defined his appearance throughout the prequel trilogy and Clone Wars. This minifigure features detailed printing showing his characteristic wide-eyed expression and awkward posture, representing one of Star Wars\' most controversial characters who inadvertently played crucial roles in galactic history. From his bumbling assistance during the Battle of Naboo to his tragic manipulation into granting emergency powers to Chancellor Palpatine, Jar Jar\'s journey from outcast to Senator embodied the unintended consequences that shaped the galaxy\'s fate. Released in numerous sets from 1999 onwards with Clone Wars variants appearing from 2011, this minifigure has become a fascinating collectible that divides fans, with some appreciating his comedic relief and others recognizing the tragic irony of his role in enabling the Empire\'s rise, making him both widely available and culturally significant in LEGO Star Wars history.',
    de: 'Die LEGO-Minifigur von Jar Jar Binks fängt den tollpatschigen Gungan mit seiner markanten orangefarbenen Haut, langen Ohrenstielen und der einfachen Weste ein, die sein Aussehen während der gesamten Prequel-Trilogie und Clone Wars definierten. Diese Minifigur verfügt über detaillierte Bedruckung, die seinen charakteristischen weitäugigen Ausdruck und seine unbeholfene Haltung zeigt, die einen der umstrittensten Star Wars-Charaktere repräsentiert, der versehentlich entscheidende Rollen in der galaktischen Geschichte spielte. Von seiner tollpatschigen Hilfe während der Schlacht von Naboo bis zu seiner tragischen Manipulation, Kanzler Palpatine Notstandsbefugnisse zu gewähren, verkörperte Jar Jars Reise vom Ausgestoßenen zum Senator die unbeabsichtigten Konsequenzen, die das Schicksal der Galaxie prägten. In zahlreichen Sets ab 1999 veröffentlicht, wobei Clone Wars-Varianten ab 2011 erschienen, ist diese Minifigur zu einem faszinierenden Sammlerstück geworden, das Fans spaltet, wobei einige seine komische Entlastung schätzen und andere die tragische Ironie seiner Rolle bei der Ermöglichung des Aufstiegs des Imperiums erkennen, was ihn sowohl weit verbreitet als auch kulturell bedeutsam in der LEGO Star Wars-Geschichte macht.',
    fr: 'La minifigurine LEGO de Jar Jar Binks capture le Gungan maladroit avec sa peau orange distinctive, ses longues tiges d\'oreilles, et le gilet simple qui définissait son apparence tout au long de la trilogie préquelle et Clone Wars. Cette minifigurine présente une impression détaillée montrant son expression caractéristique aux yeux écarquillés et sa posture maladroite, représentant l\'un des personnages les plus controversés de Star Wars qui a joué par inadvertance des rôles cruciaux dans l\'histoire galactique. De son assistance maladroite pendant la Bataille de Naboo à sa manipulation tragique pour accorder des pouvoirs d\'urgence au Chancelier Palpatine, le voyage de Jar Jar d\'exclu à Sénateur incarnait les conséquences involontaires qui ont façonné le destin de la galaxie. Sortie dans de nombreux sets à partir de 1999 avec des variantes Clone Wars apparaissant à partir de 2011, cette minifigurine est devenue un objet de collection fascinant qui divise les fans, certains appréciant son soulagement comique et d\'autres reconnaissant l\'ironie tragique de son rôle dans la montée de l\'Empire, la rendant à la fois largement disponible et culturellement significative dans l\'histoire LEGO Star Wars.',
    es: 'La minifigura LEGO de Jar Jar Binks captura al torpe Gungan con su distintiva piel naranja, largos tallos de orejas, y el chaleco simple que definió su apariencia a lo largo de la trilogía precuela y Clone Wars. Esta minifigura presenta impresión detallada mostrando su característica expresión de ojos muy abiertos y postura torpe, representando a uno de los personajes más controvertidos de Star Wars que inadvertidamente jugó roles cruciales en la historia galáctica. Desde su torpe asistencia durante la Batalla de Naboo hasta su trágica manipulación para otorgar poderes de emergencia al Canciller Palpatine, el viaje de Jar Jar desde marginado hasta Senador encarnó las consecuencias no intencionadas que moldearon el destino de la galaxia. Lanzada en numerosos sets desde 1999 con variantes Clone Wars apareciendo desde 2011, esta minifigura se ha convertido en un coleccionable fascinante que divide a los fans, con algunos apreciando su alivio cómico y otros reconociendo la trágica ironía de su papel en permitir el ascenso del Imperio, haciéndola tanto ampliamente disponible como culturalmente significativa en la historia LEGO Star Wars.'
  },
  {
    no: 'sw0253',
    name: 'Padmé Amidala (Geonosis Arena)',
    en: 'Padmé Amidala\'s Geonosis Arena LEGO minifigure captures the Senator during one of the prequel trilogy\'s most iconic action sequences, wearing her distinctive white outfit with midriff-revealing battle damage. This minifigure features detailed printing showing the torn costume that resulted from her encounter with the nexu beast in the Geonosian arena, representing Padmé\'s transformation from diplomat to warrior fighting alongside Jedi and clones. Armed with a blaster and demonstrating exceptional combat skills despite her political background, this version of Padmé showcased her bravery and resourcefulness during the battle that ignited the Clone Wars. Released in sets from 2002 onwards with updated versions appearing through the years, this minifigure became one of the most recognizable Padmé variants, highly collectible due to its connection to Attack of the Clones\' climactic battle scene and its representation of Padmé as both romantic lead and action hero in the Star Wars saga.',
    de: 'Die LEGO-Minifigur von Padmé Amidala in der Geonosis-Arena fängt die Senatorin während einer der ikonischsten Action-Sequenzen der Prequel-Trilogie ein, in ihrem markanten weißen Outfit mit bauchfreiem Kampfschaden. Diese Minifigur verfügt über detaillierte Bedruckung, die das zerrissene Kostüm zeigt, das aus ihrer Begegnung mit dem Nexu-Biest in der geonosianischen Arena resultierte, die Padmés Verwandlung von Diplomatin zu Kriegerin repräsentiert, die an der Seite von Jedi und Klonen kämpft. Bewaffnet mit einem Blaster und außergewöhnliche Kampffähigkeiten demonstrierend trotz ihres politischen Hintergrunds, zeigte diese Version von Padmé ihre Tapferkeit und Einfallsreichtum während der Schlacht, die die Klonkriege entfachte. In Sets ab 2002 veröffentlicht, wobei aktualisierte Versionen über die Jahre erschienen, wurde diese Minifigur zu einer der bekanntesten Padmé-Varianten, hochgradig sammelwürdig aufgrund ihrer Verbindung zur klimatischen Kampfszene von Angriff der Klonkrieger und ihrer Darstellung von Padmé als sowohl romantische Hauptrolle als auch Action-Heldin in der Star Wars-Saga.',
    fr: 'La minifigurine LEGO de Padmé Amidala dans l\'Arène de Geonosis capture la Sénatrice pendant l\'une des séquences d\'action les plus emblématiques de la trilogie préquelle, portant sa tenue blanche distinctive avec des dégâts de bataille révélant le ventre. Cette minifigurine présente une impression détaillée montrant le costume déchiré qui résultait de sa rencontre avec la bête nexu dans l\'arène géonosienne, représentant la transformation de Padmé de diplomate à guerrière combattant aux côtés des Jedi et des clones. Armée d\'un blaster et démontrant des compétences de combat exceptionnelles malgré son parcours politique, cette version de Padmé a mis en valeur son courage et son ingéniosité pendant la bataille qui a déclenché les Guerres des Clones. Sortie dans des sets à partir de 2002 avec des versions mises à jour apparaissant au fil des ans, cette minifigurine est devenue l\'une des variantes de Padmé les plus reconnaissables, hautement collectionnable en raison de sa connexion à la scène de bataille culminante de L\'Attaque des Clones et sa représentation de Padmé à la fois comme héroïne romantique et héroïne d\'action dans la saga Star Wars.',
    es: 'La minifigura LEGO de Padmé Amidala en la Arena de Geonosis captura a la Senadora durante una de las secuencias de acción más icónicas de la trilogía precuela, vistiendo su distintivo atuendo blanco con daño de batalla que revela el abdomen. Esta minifigura presenta impresión detallada mostrando el traje desgarrado que resultó de su encuentro con la bestia nexu en la arena geonosiana, representando la transformación de Padmé de diplomática a guerrera luchando junto a Jedi y clones. Armada con un bláster y demostrando habilidades de combate excepcionales a pesar de su trasfondo político, esta versión de Padmé mostró su valentía y ingenio durante la batalla que encendió las Guerras Clon. Lanzada en sets desde 2002 con versiones actualizadas apareciendo a través de los años, esta minifigura se convirtió en una de las variantes de Padmé más reconocibles, altamente coleccionable debido a su conexión con la escena de batalla climática de El Ataque de los Clones y su representación de Padmé como tanto protagonista romántica como heroína de acción en la saga Star Wars.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 141-145 (sw0249-sw0253)...\n');

  for (const m of batch) {
    await prisma.minifigCatalog.upsert({
      where: { minifigure_no: m.no },
      update: {
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      },
      create: {
        minifigure_no: m.no,
        name: m.name,
        category_id: 1,
        category_name: 'Star Wars',
        search_name: m.name.toLowerCase(),
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`  ✅ ${m.no}: ${m.name}`);
  }

  console.log('\n✨ Batch 141-145 complete: 5 minifigs (20 descriptions)');
  await prisma.$disconnect();
}

saveBatch().catch(console.error);