import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0509',
    name: 'IG-88',
    en: 'IG-88 is one of the most feared assassin droids in the galaxy, known for his ruthless efficiency and advanced combat programming, hired by Darth Vader to hunt the Millennium Falcon. This minifigure features the distinctive tall cylindrical head with sensor arrays, gray metallic body with detailed mechanical printing, multiple weapon attachments, and the menacing silhouette of a professional killer droid. Released in bounty hunter themed sets from 2005 onward, including the iconic bounty hunter collection from The Empire Strikes Back. IG-88 represents the pinnacle of assassination droid technology, a mechanical bounty hunter with no mercy or hesitation. Highly collectible as part of the legendary bounty hunters assembled by Vader, essential for completing the Empire Strikes Back bounty hunter lineup. Collectors value IG-88 for his unique droid design that stands out among humanoid bounty hunters and his role as one of the most dangerous non-organic beings in Star Wars. The tall, imposing build and distinctive head make IG-88 instantly recognizable in bounty hunter displays.',
    de: 'IG-88 ist einer der gefürchtetsten Attentäter-Droiden in der Galaxis, bekannt für seine rücksichtslose Effizienz und fortschrittliche Kampfprogrammierung, von Darth Vader angeheuert, um den Millennium Falcon zu jagen. Diese Minifigur zeigt den charakteristischen hohen zylindrischen Kopf mit Sensor-Arrays, grauen metallischen Körper mit detaillierter mechanischer Bedruckung, mehrere Waffenanbringungen und die bedrohliche Silhouette eines professionellen Killer-Droiden. Sie wurde ab 2005 in Kopfgeldjäger-thematischen Sets veröffentlicht, einschließlich der ikonischen Kopfgeldjäger-Sammlung aus Das Imperium schlägt zurück. IG-88 repräsentiert den Höhepunkt der Attentäter-Droiden-Technologie, ein mechanischer Kopfgeldjäger ohne Gnade oder Zögern. Sehr sammelwürdig als Teil der legendären Kopfgeldjäger, die von Vader versammelt wurden, unverzichtbar für die Vervollständigung der Das Imperium schlägt zurück Kopfgeldjäger-Aufstellung. Sammler schätzen IG-88 für sein einzigartiges Droiden-Design, das unter humanoiden Kopfgeldjägern hervorsticht, und seine Rolle als eines der gefährlichsten nicht-organischen Wesen in Star Wars. Der hohe, imposante Bau und der charakteristische Kopf machen IG-88 in Kopfgeldjäger-Displays sofort erkennbar.',
    fr: 'IG-88 est l\'un des droïdes assassins les plus redoutés de la galaxie, connu pour son efficacité impitoyable et sa programmation de combat avancée, engagé par Dark Vador pour chasser le Faucon Millenium. Cette minifigurine présente la tête cylindrique haute distinctive avec des réseaux de capteurs, un corps métallique gris avec une impression mécanique détaillée, plusieurs attaches d\'armes, et la silhouette menaçante d\'un droïde tueur professionnel. Sortie dans des sets à thème de chasseur de primes à partir de 2005, y compris la collection emblématique de chasseurs de primes de L\'Empire Contre-Attaque. IG-88 représente le summum de la technologie de droïdes d\'assassinat, un chasseur de primes mécanique sans pitié ni hésitation. Hautement collectionnable dans le cadre des chasseurs de primes légendaires assemblés par Vador, essentiel pour compléter la formation de chasseurs de primes de L\'Empire Contre-Attaque. Les collectionneurs apprécient IG-88 pour son design de droïde unique qui se démarque parmi les chasseurs de primes humanoïdes et son rôle comme l\'un des êtres non-organiques les plus dangereux de Star Wars. La construction haute et imposante et la tête distinctive rendent IG-88 instantanément reconnaissable dans les affichages de chasseurs de primes.',
    es: 'IG-88 es uno de los droides asesinos más temidos en la galaxia, conocido por su eficiencia despiadada y programación de combate avanzada, contratado por Darth Vader para cazar el Halcón Milenario. Esta minifigura presenta la distintiva cabeza cilíndrica alta con arreglos de sensores, cuerpo metálico gris con impresión mecánica detallada, múltiples accesorios de armas, y la silueta amenazante de un droide asesino profesional. Lanzado en sets temáticos de cazarrecompensas desde 2005 en adelante, incluyendo la icónica colección de cazarrecompensas de El Imperio Contraataca. IG-88 representa el pináculo de la tecnología de droides de asesinato, un cazarrecompensas mecánico sin piedad ni vacilación. Altamente coleccionable como parte de los legendarios cazarrecompensas reunidos por Vader, esencial para completar la formación de cazarrecompensas de El Imperio Contraataca. Los coleccionistas valoran a IG-88 por su diseño de droide único que se destaca entre los cazarrecompensas humanoides y su papel como uno de los seres no orgánicos más peligrosos en Star Wars. La construcción alta e imponente y la cabeza distintiva hacen que IG-88 sea instantáneamente reconocible en exhibiciones de cazarrecompensas.'
  },
  {
    no: 'sw0510',
    name: '4-LOM',
    en: '4-LOM is a protocol droid turned bounty hunter, partnering with Zuckuss as part of the team hired by Darth Vader to capture the Millennium Falcon in The Empire Strikes Back. This minifigure features the distinctive insectoid-like head design with large optical sensors, gray and black coloring showing the droid\'s modified appearance, detailed printing depicting sensor arrays and equipment, and the unusual silhouette of a protocol droid adapted for combat. Released in bounty hunter collection sets from 2005 onward, often paired with his partner Zuckuss. 4-LOM represents the dark side of droid reprogramming, a service droid transformed into a calculating hunter. Highly collectible as one of the six bounty hunters assembled by Vader, essential for completing the iconic Empire Strikes Back bounty hunter scene. Collectors value 4-LOM for his unique backstory as a reprogrammed protocol droid and distinctive insectoid appearance. The partnership with Zuckuss adds narrative depth, making both figures desirable for bounty hunter collections.',
    de: '4-LOM ist ein Protokoll-Droide, der zum Kopfgeldjäger wurde und mit Zuckuss als Teil des Teams zusammenarbeitet, das von Darth Vader angeheuert wurde, um den Millennium Falcon in Das Imperium schlägt zurück zu fangen. Diese Minifigur zeigt das charakteristische insektoide Kopfdesign mit großen optischen Sensoren, grau-schwarze Färbung, die das modifizierte Aussehen des Droiden zeigt, detaillierte Bedruckung, die Sensor-Arrays und Ausrüstung darstellt, und die ungewöhnliche Silhouette eines für den Kampf angepassten Protokoll-Droiden. Sie wurde ab 2005 in Kopfgeldjäger-Sammlungs-Sets veröffentlicht, oft gepaart mit seinem Partner Zuckuss. 4-LOM repräsentiert die dunkle Seite der Droiden-Neuprogrammierung, ein Service-Droide, der in einen berechnenden Jäger verwandelt wurde. Sehr sammelwürdig als einer der sechs Kopfgeldjäger, die von Vader versammelt wurden, unverzichtbar für die Vervollständigung der ikonischen Das Imperium schlägt zurück Kopfgeldjäger-Szene. Sammler schätzen 4-LOM für seine einzigartige Hintergrundgeschichte als neu programmierter Protokoll-Droide und charakteristisches insektoides Aussehen. Die Partnerschaft mit Zuckuss fügt narrative Tiefe hinzu und macht beide Figuren begehrenswert für Kopfgeldjäger-Sammlungen.',
    fr: '4-LOM est un droïde de protocole devenu chasseur de primes, s\'associant avec Zuckuss dans le cadre de l\'équipe engagée par Dark Vador pour capturer le Faucon Millenium dans L\'Empire Contre-Attaque. Cette minifigurine présente le design de tête distinctif ressemblant à un insectoïde avec de grands capteurs optiques, une coloration grise et noire montrant l\'apparence modifiée du droïde, une impression détaillée représentant des réseaux de capteurs et de l\'équipement, et la silhouette inhabituelle d\'un droïde de protocole adapté pour le combat. Sortie dans des sets de collection de chasseurs de primes à partir de 2005, souvent jumelée avec son partenaire Zuckuss. 4-LOM représente le côté obscur de la reprogrammation de droïdes, un droïde de service transformé en chasseur calculateur. Hautement collectionnable comme l\'un des six chasseurs de primes assemblés par Vador, essentiel pour compléter la scène emblématique de chasseurs de primes de L\'Empire Contre-Attaque. Les collectionneurs apprécient 4-LOM pour son histoire unique en tant que droïde de protocole reprogrammé et son apparence insectoïde distinctive. Le partenariat avec Zuckuss ajoute de la profondeur narrative, rendant les deux figurines désirables pour les collections de chasseurs de primes.',
    es: '4-LOM es un droide de protocolo convertido en cazarrecompensas, asociándose con Zuckuss como parte del equipo contratado por Darth Vader para capturar el Halcón Milenario en El Imperio Contraataca. Esta minifigura presenta el distintivo diseño de cabeza similar a insectoide con grandes sensores ópticos, coloración gris y negra mostrando la apariencia modificada del droide, impresión detallada representando arreglos de sensores y equipo, y la silueta inusual de un droide de protocolo adaptado para combate. Lanzado en sets de colección de cazarrecompensas desde 2005 en adelante, a menudo emparejado con su compañero Zuckuss. 4-LOM representa el lado oscuro de la reprogramación de droides, un droide de servicio transformado en un cazador calculador. Altamente coleccionable como uno de los seis cazarrecompensas reunidos por Vader, esencial para completar la icónica escena de cazarrecompensas de El Imperio Contraataca. Los coleccionistas valoran a 4-LOM por su historia de fondo única como droide de protocolo reprogramado y apariencia insectoide distintiva. La asociación con Zuckuss añade profundidad narrativa, haciendo que ambas figuras sean deseables para colecciones de cazarrecompensas.'
  },
  {
    no: 'sw0511',
    name: 'Dengar',
    en: 'Dengar is the heavily armored human bounty hunter and former swoop bike racer, one of the six hunters hired by Darth Vader to track the Millennium Falcon in The Empire Strikes Back. This minifigure features Dengar\'s distinctive wrapped head bandages covering battle scars, gray and brown armor plating with detailed equipment printing, weathered appearance showing years of combat, and the rugged look of a hardened mercenary. Released in bounty hunter themed sets from 2005 onward, essential for completing the iconic Executor bounty hunter lineup. Dengar represents human tenacity and survival in the dangerous bounty hunting profession, a scarred veteran with a personal vendetta against Han Solo. Highly collectible as part of the legendary six bounty hunters, valued for his unique appearance among the more exotic hunters. Collectors appreciate Dengar\'s backstory as a former Imperial assassin turned freelance hunter, and his distinctive bandaged head design makes him instantly recognizable in bounty hunter displays.',
    de: 'Dengar ist der schwer gepanzerte menschliche Kopfgeldjäger und ehemalige Swoop-Bike-Rennfahrer, einer der sechs Jäger, die von Darth Vader angeheuert wurden, um den Millennium Falcon in Das Imperium schlägt zurück zu verfolgen. Diese Minifigur zeigt Dengars charakteristische gewickelte Kopfbandagen, die Kampfnarben bedecken, grau-braune Rüstungsplattierung mit detaillierter Ausrüstungsbedruckung, verwittertes Aussehen, das Jahre des Kampfes zeigt, und den rauen Look eines abgehärteten Söldners. Sie wurde ab 2005 in Kopfgeldjäger-thematischen Sets veröffentlicht, unverzichtbar für die Vervollständigung der ikonischen Executor-Kopfgeldjäger-Aufstellung. Dengar repräsentiert menschliche Zähigkeit und Überleben im gefährlichen Kopfgeldjäger-Beruf, ein vernarbter Veteran mit persönlicher Vendetta gegen Han Solo. Sehr sammelwürdig als Teil der legendären sechs Kopfgeldjäger, geschätzt für sein einzigartiges Aussehen unter den exotischeren Jägern. Sammler schätzen Dengars Hintergrundgeschichte als ehemaliger imperialer Attentäter, der zum freiberuflichen Jäger wurde, und sein charakteristisches bandagiertes Kopfdesign macht ihn in Kopfgeldjäger-Displays sofort erkennbar.',
    fr: 'Dengar est le chasseur de primes humain lourdement blindé et ancien coureur de swoop bike, l\'un des six chasseurs engagés par Dark Vador pour traquer le Faucon Millenium dans L\'Empire Contre-Attaque. Cette minifigurine présente les bandages de tête enveloppés distinctifs de Dengar couvrant des cicatrices de bataille, un blindage gris et brun avec une impression d\'équipement détaillée, une apparence patinée montrant des années de combat, et l\'aspect robuste d\'un mercenaire endurci. Sortie dans des sets à thème de chasseur de primes à partir de 2005, essentielle pour compléter la formation emblématique de chasseurs de primes de l\'Executor. Dengar représente la ténacité humaine et la survie dans la profession dangereuse de chasseur de primes, un vétéran balafré avec une vendetta personnelle contre Han Solo. Hautement collectionnable dans le cadre des six chasseurs de primes légendaires, apprécié pour son apparence unique parmi les chasseurs plus exotiques. Les collectionneurs apprécient l\'histoire de Dengar en tant qu\'ancien assassin Impérial devenu chasseur indépendant, et son design de tête bandée distinctive le rend instantanément reconnaissable dans les affichages de chasseurs de primes.',
    es: 'Dengar es el cazarrecompensas humano fuertemente blindado y ex corredor de swoop bike, uno de los seis cazadores contratados por Darth Vader para rastrear el Halcón Milenario en El Imperio Contraataca. Esta minifigura presenta los distintivos vendajes de cabeza envueltos de Dengar cubriendo cicatrices de batalla, placas de armadura gris y marrón con impresión de equipo detallada, apariencia desgastada mostrando años de combate, y el aspecto rudo de un mercenario endurecido. Lanzado en sets temáticos de cazarrecompensas desde 2005 en adelante, esencial para completar la icónica formación de cazarrecompensas del Executor. Dengar representa la tenacidad humana y supervivencia en la peligrosa profesión de cazarrecompensas, un veterano con cicatrices con una venganza personal contra Han Solo. Altamente coleccionable como parte de los legendarios seis cazarrecompensas, valorado por su apariencia única entre los cazadores más exóticos. Los coleccionistas aprecian la historia de fondo de Dengar como ex asesino Imperial convertido en cazador independiente, y su distintivo diseño de cabeza vendada lo hace instantáneamente reconocible en exhibiciones de cazarrecompensas.'
  },
  {
    no: 'sw0512',
    name: 'Boba Fett',
    en: 'Boba Fett is the legendary Mandalorian bounty hunter and son of Jango Fett, widely considered the most dangerous and skilled hunter in the galaxy. This minifigure features the iconic green and gray Mandalorian armor with battle damage weathering, distinctive T-shaped visor helmet, jetpack with missile attachment, and cape piece representing his tactical equipment. Released in countless sets throughout LEGO Star Wars history since 1999, becoming one of the most popular and frequently reproduced characters. Boba Fett represents the pinnacle of bounty hunting expertise, successfully capturing Han Solo and delivering him to Jabba the Hutt. Extremely collectible with numerous variants across different eras, from his appearance in The Empire Strikes Back through his survival and return in The Mandalorian series. The distinctive Mandalorian armor design and mysterious character make Boba Fett one of the most iconic and valuable figures in LEGO Star Wars, essential for any serious collection.',
    de: 'Boba Fett ist der legendäre mandalorianische Kopfgeldjäger und Sohn von Jango Fett, weithin als der gefährlichste und geschickteste Jäger in der Galaxis angesehen. Diese Minifigur zeigt die ikonische grün-graue mandalorianische Rüstung mit Kampfschaden-Verwitterung, den charakteristischen T-förmigen Visier-Helm, Jetpack mit Raketenanbringung und Umhangteil, das seine taktische Ausrüstung repräsentiert. Sie wurde seit 1999 in unzähligen Sets durch die gesamte LEGO-Star-Wars-Geschichte veröffentlicht und wurde zu einem der beliebtesten und am häufigsten reproduzierten Charaktere. Boba Fett repräsentiert den Höhepunkt der Kopfgeldjäger-Expertise, fing erfolgreich Han Solo ein und lieferte ihn an Jabba the Hutt aus. Extrem sammelwürdig mit zahlreichen Varianten über verschiedene Epochen hinweg, von seinem Auftritt in Das Imperium schlägt zurück bis zu seinem Überleben und seiner Rückkehr in der Mandalorian-Serie. Das charakteristische mandalorianische Rüstungsdesign und der mysteriöse Charakter machen Boba Fett zu einer der ikonischsten und wertvollsten Figuren in LEGO Star Wars, unverzichtbar für jede ernsthafte Sammlung.',
    fr: 'Boba Fett est le chasseur de primes Mandalorien légendaire et fils de Jango Fett, largement considéré comme le chasseur le plus dangereux et le plus compétent de la galaxie. Cette minifigurine présente l\'armure Mandalorienne emblématique verte et grise avec patine de dommages de combat, un casque à visière en forme de T distinctif, un jetpack avec attache de missile, et une pièce de cape représentant son équipement tactique. Sortie dans d\'innombrables sets tout au long de l\'histoire LEGO Star Wars depuis 1999, devenant l\'un des personnages les plus populaires et fréquemment reproduits. Boba Fett représente le summum de l\'expertise en chasse de primes, capturant avec succès Han Solo et le livrant à Jabba le Hutt. Extrêmement collectionnable avec de nombreux variants à travers différentes époques, de son apparition dans L\'Empire Contre-Attaque à travers sa survie et son retour dans la série The Mandalorian. Le design d\'armure Mandalorienne distinctif et le personnage mystérieux font de Boba Fett l\'une des figurines les plus emblématiques et précieuses de LEGO Star Wars, essentielle pour toute collection sérieuse.',
    es: 'Boba Fett es el legendario cazarrecompensas Mandaloriano e hijo de Jango Fett, ampliamente considerado el cazador más peligroso y hábil en la galaxia. Esta minifigura presenta la icónica armadura Mandaloriana verde y gris con desgaste de daño de batalla, casco de visor en forma de T distintivo, mochila propulsora con accesorio de misil, y pieza de capa representando su equipo táctico. Lanzado en innumerables sets a lo largo de la historia de LEGO Star Wars desde 1999, convirtiéndose en uno de los personajes más populares y frecuentemente reproducidos. Boba Fett representa el pináculo de la experiencia en cazarrecompensas, capturando exitosamente a Han Solo y entregándolo a Jabba the Hutt. Extremadamente coleccionable con numerosas variantes a través de diferentes eras, desde su aparición en El Imperio Contraataca hasta su supervivencia y regreso en la serie The Mandalorian. El distintivo diseño de armadura Mandaloriana y el personaje misterioso hacen de Boba Fett una de las figuras más icónicas y valiosas en LEGO Star Wars, esencial para cualquier colección seria.'
  },
  {
    no: 'sw0513',
    name: 'Imperial Officer',
    en: 'The Imperial Officer represents the command structure of the Galactic Empire, serving aboard Star Destroyers and Imperial installations across the galaxy. This minifigure features the distinctive olive-gray or black uniform with rank insignia plaques, officer\'s cap, detailed printing showing Imperial insignia and code cylinders, and the authoritative appearance of Empire leadership. Released in numerous Imperial themed sets from 2005 onward, including Star Destroyers and Death Star command rooms. Imperial Officers represent the bureaucratic and military leadership that enforces the Emperor\'s will throughout the galaxy, overseeing stormtroopers and naval operations. Essential for completing Imperial command structures and adding authenticity to Empire military displays. Collectors value these officers for creating realistic Imperial hierarchies and command centers, with different uniform colors and rank insignia representing various positions within the Imperial military machine. The variety of officer types allows for detailed recreations of Empire organizational structure.',
    de: 'Der Imperiale Offizier repräsentiert die Kommandostruktur des Galaktischen Imperiums und dient an Bord von Sternenzerstörern und imperialen Anlagen in der gesamten Galaxis. Diese Minifigur zeigt die charakteristische olivgraue oder schwarze Uniform mit Rang-Abzeichen-Plaketten, Offizierskappe, detaillierte Bedruckung, die imperiale Insignien und Code-Zylinder zeigt, und das autoritäre Aussehen der Imperium-Führung. Sie wurde ab 2005 in zahlreichen Imperial-thematischen Sets veröffentlicht, darunter Sternenzerstörer und Todesstern-Kommandoräume. Imperiale Offiziere repräsentieren die bürokratische und militärische Führung, die den Willen des Imperators in der gesamten Galaxis durchsetzt und Stormtrooper und Marineoperationen überwacht. Unverzichtbar für die Vervollständigung imperialer Kommandostrukturen und das Hinzufügen von Authentizität zu Imperium-Militär-Displays. Sammler schätzen diese Offiziere für die Erstellung realistischer imperialer Hierarchien und Kommandozentren, wobei verschiedene Uniformfarben und Rangabzeichen verschiedene Positionen innerhalb der imperialen Militärmaschine repräsentieren. Die Vielfalt der Offizierstypen ermöglicht detaillierte Nachstellungen der Imperium-Organisationsstruktur.',
    fr: 'L\'Officier Impérial représente la structure de commandement de l\'Empire Galactique, servant à bord de Destroyer Stellaire et d\'installations Impériales à travers la galaxie. Cette minifigurine présente l\'uniforme distinctif gris olive ou noir avec des plaques d\'insignes de rang, une casquette d\'officier, une impression détaillée montrant des insignes Impériaux et des cylindres de code, et l\'apparence autoritaire du leadership de l\'Empire. Sortie dans de nombreux sets à thème Impérial à partir de 2005, y compris les Destroyer Stellaire et les salles de commandement de l\'Étoile de la Mort. Les Officiers Impériaux représentent le leadership bureaucratique et militaire qui impose la volonté de l\'Empereur à travers la galaxie, supervisant les stormtroopers et les opérations navales. Essentiels pour compléter les structures de commandement Impériales et ajouter de l\'authenticité aux affichages militaires de l\'Empire. Les collectionneurs apprécient ces officiers pour créer des hiérarchies Impériales réalistes et des centres de commandement, avec différentes couleurs d\'uniformes et insignes de rang représentant diverses positions au sein de la machine militaire Impériale. La variété des types d\'officiers permet des recréations détaillées de la structure organisationnelle de l\'Empire.',
    es: 'El Oficial Imperial representa la estructura de comando del Imperio Galáctico, sirviendo a bordo de Destructores Estelares e instalaciones Imperiales a través de la galaxia. Esta minifigura presenta el distintivo uniforme gris oliva o negro con placas de insignias de rango, gorra de oficial, impresión detallada mostrando insignias Imperiales y cilindros de código, y la apariencia autoritaria del liderazgo del Imperio. Lanzado en numerosos sets temáticos Imperiales desde 2005 en adelante, incluyendo Destructores Estelares y salas de comando de la Estrella de la Muerte. Los Oficiales Imperiales representan el liderazgo burocrático y militar que impone la voluntad del Emperador a través de la galaxia, supervisando stormtroopers y operaciones navales. Esencial para completar estructuras de comando Imperiales y agregar autenticidad a exhibiciones militares del Imperio. Los coleccionistas valoran estos oficiales para crear jerarquías Imperiales realistas y centros de comando, con diferentes colores de uniforme e insignias de rango representando varias posiciones dentro de la máquina militar Imperial. La variedad de tipos de oficiales permite recreaciones detalladas de la estructura organizacional del Imperio.'
  },
  {
    no: 'sw0514',
    name: 'TIE Fighter Pilot',
    en: 'The TIE Fighter Pilot operates the Empire\'s standard starfighters, serving as the frontline space combat force throughout the galaxy. This minifigure features the distinctive all-black flight suit with life support system chest box, specialized TIE pilot helmet with breathing apparatus, Imperial insignia, and equipment designed for the harsh vacuum of space. Released in countless TIE Fighter sets throughout LEGO Star Wars history since 1999. TIE Fighter Pilots represent the Empire\'s massive naval air superiority, countless pilots flying expendable fighters in overwhelming numbers. Essential for crewing TIE Fighters, TIE Interceptors, and other Imperial starfighter variants across all eras. Collectors often army-build these pilots to crew multiple TIE Fighter models, recreating the swarms of Imperial fighters that filled space battles. The iconic all-black uniform and distinctive helmet make TIE Pilots instantly recognizable, representing the faceless might of the Imperial Navy.',
    de: 'Der TIE-Jägerpilot bedient die Standard-Raumjäger des Imperiums und dient als Frontlinie-Weltraumkampftruppe in der gesamten Galaxis. Diese Minifigur zeigt den charakteristischen ganz schwarzen Fluganzug mit Lebenserhaltungssystem-Brustbox, spezialisierten TIE-Pilotenhelm mit Atemgerät, imperiale Insignien und Ausrüstung, die für das raue Vakuum des Weltraums konzipiert ist. Sie wurde seit 1999 in unzähligen TIE-Jäger-Sets durch die gesamte LEGO-Star-Wars-Geschichte veröffentlicht. TIE-Jägerpiloten repräsentieren die massive Marine-Luftüberlegenheit des Imperiums, unzählige Piloten fliegen entbehrliche Jäger in überwältigenden Zahlen. Unverzichtbar für die Bemannung von TIE-Jägern, TIE-Abfangjägern und anderen imperialen Raumjäger-Varianten über alle Epochen hinweg. Sammler bauen diese Piloten oft in Armeen auf, um mehrere TIE-Jäger-Modelle zu bemannen und die Schwärme imperialer Jäger nachzustellen, die Weltraumschlachten füllten. Die ikonische ganz schwarze Uniform und der charakteristische Helm machen TIE-Piloten sofort erkennbar und repräsentieren die gesichtslose Macht der imperialen Marine.',
    fr: 'Le Pilote de Chasseur TIE pilote les chasseurs stellaires standard de l\'Empire, servant de force de combat spatial de première ligne à travers la galaxie. Cette minifigurine présente la combinaison de vol entièrement noire distinctive avec boîtier de poitrine du système de survie, un casque de pilote TIE spécialisé avec appareil respiratoire, des insignes Impériaux, et un équipement conçu pour le vide spatial hostile. Sortie dans d\'innombrables sets de Chasseur TIE tout au long de l\'histoire LEGO Star Wars depuis 1999. Les Pilotes de Chasseurs TIE représentent la supériorité aérienne navale massive de l\'Empire, d\'innombrables pilotes pilotant des chasseurs sacrifiables en nombres écrasants. Essentiels pour équiper les Chasseurs TIE, les Intercepteurs TIE, et d\'autres variantes de chasseurs stellaires Impériaux à travers toutes les époques. Les collectionneurs construisent souvent des armées de ces pilotes pour équiper plusieurs modèles de Chasseurs TIE, recréant les essaims de chasseurs Impériaux qui remplissaient les batailles spatiales. L\'uniforme noir emblématique et le casque distinctif rendent les Pilotes TIE instantanément reconnaissables, représentant la puissance sans visage de la Marine Impériale.',
    es: 'El Piloto de Caza TIE opera los cazas estelares estándar del Imperio, sirviendo como fuerza de combate espacial de primera línea a través de la galaxia. Esta minifigura presenta el distintivo traje de vuelo completamente negro con caja de pecho de sistema de soporte vital, casco de piloto TIE especializado con aparato respiratorio, insignias Imperiales, y equipo diseñado para el duro vacío del espacio. Lanzado en innumerables sets de Caza TIE a lo largo de la historia de LEGO Star Wars desde 1999. Los Pilotos de Caza TIE representan la masiva superioridad aérea naval del Imperio, innumerables pilotos volando cazas prescindibles en números abrumadores. Esencial para tripular Cazas TIE, Interceptores TIE, y otras variantes de cazas estelares Imperiales a través de todas las eras. Los coleccionistas a menudo construyen ejércitos de estos pilotos para tripular múltiples modelos de Caza TIE, recreando los enjambres de cazas Imperiales que llenaban batallas espaciales. El icónico uniforme completamente negro y el casco distintivo hacen que los Pilotos TIE sean instantáneamente reconocibles, representando el poder sin rostro de la Marina Imperial.'
  },
  {
    no: 'sw0515',
    name: 'Stormtrooper',
    en: 'The Stormtrooper is the standard infantry soldier of the Galactic Empire, representing the faceless enforcement of Imperial rule across the galaxy. This minifigure features the iconic white armor with black undersuit, distinctive helmet design, detailed printing showing armor segments and equipment, and the anonymous appearance of Empire ground forces. Released in countless sets throughout LEGO Star Wars history since 1999, becoming one of the most frequently produced and army-built figures. Stormtroopers represent Imperial military might and control, deployed everywhere from Death Star corridors to remote outposts. Essential for army building Empire forces, with collectors often acquiring hundreds to recreate the overwhelming numbers seen in the films. The timeless white armor design and universal recognition make Stormtroopers foundational elements of any LEGO Star Wars collection. Their role throughout the Original Trilogy and beyond ensures perpetual demand, making them the Empire equivalent of Clone Troopers for army building.',
    de: 'Der Stormtrooper ist der Standard-Infanteriesoldat des Galaktischen Imperiums und repräsentiert die gesichtslose Durchsetzung imperialer Herrschaft in der gesamten Galaxis. Diese Minifigur zeigt die ikonische weiße Rüstung mit schwarzem Unteranzug, charakteristisches Helmdesign, detaillierte Bedruckung, die Rüstungssegmente und Ausrüstung zeigt, und das anonyme Aussehen der imperialen Bodentruppen. Sie wurde seit 1999 in unzähligen Sets durch die gesamte LEGO-Star-Wars-Geschichte veröffentlicht und wurde zu einer der am häufigsten produzierten und für Armeen gebauten Figuren. Stormtrooper repräsentieren imperiale Militärmacht und Kontrolle, eingesetzt überall von Todesstern-Korridoren bis zu abgelegenen Außenposten. Unverzichtbar für den Armeeaufbau von Imperium-Streitkräften, wobei Sammler oft Hunderte erwerben, um die überwältigenden Zahlen nachzustellen, die in den Filmen zu sehen sind. Das zeitlose weiße Rüstungsdesign und die universelle Wiedererkennung machen Stormtrooper zu grundlegenden Elementen jeder LEGO-Star-Wars-Sammlung. Ihre Rolle durch die Original-Trilogie und darüber hinaus sorgt für dauerhafte Nachfrage und macht sie zum Imperium-Äquivalent von Clone Troopers für Armeeaufbau.',
    fr: 'Le Stormtrooper est le soldat d\'infanterie standard de l\'Empire Galactique, représentant l\'application sans visage de la règle Impériale à travers la galaxie. Cette minifigurine présente l\'armure blanche emblématique avec combinaison noire, un design de casque distinctif, une impression détaillée montrant des segments d\'armure et de l\'équipement, et l\'apparence anonyme des forces terrestres de l\'Empire. Sortie dans d\'innombrables sets tout au long de l\'histoire LEGO Star Wars depuis 1999, devenant l\'une des figurines les plus fréquemment produites et construites en armée. Les Stormtroopers représentent la puissance militaire et le contrôle Impérial, déployés partout des couloirs de l\'Étoile de la Mort aux avant-postes éloignés. Essentiels pour construire des forces de l\'Empire, les collectionneurs en acquérant souvent des centaines pour recréer les nombres écrasants vus dans les films. Le design d\'armure blanche intemporel et la reconnaissance universelle font des Stormtroopers des éléments fondamentaux de toute collection LEGO Star Wars. Leur rôle tout au long de la Trilogie Originale et au-delà assure une demande perpétuelle, en faisant l\'équivalent de l\'Empire des Clone Troopers pour la construction d\'armées.',
    es: 'El Stormtrooper es el soldado de infantería estándar del Imperio Galáctico, representando la aplicación sin rostro del gobierno Imperial a través de la galaxia. Esta minifigura presenta la icónica armadura blanca con traje interior negro, diseño de casco distintivo, impresión detallada mostrando segmentos de armadura y equipo, y la apariencia anónima de las fuerzas terrestres del Imperio. Lanzado en innumerables sets a lo largo de la historia de LEGO Star Wars desde 1999, convirtiéndose en una de las figuras más frecuentemente producidas y construidas en ejército. Los Stormtroopers representan el poder militar y control Imperial, desplegados en todas partes desde corredores de la Estrella de la Muerte hasta puestos avanzados remotos. Esencial para construir ejércitos de fuerzas del Imperio, con coleccionistas a menudo adquiriendo cientos para recrear los números abrumadores vistos en las películas. El diseño de armadura blanca atemporal y el reconocimiento universal hacen que los Stormtroopers sean elementos fundamentales de cualquier colección de LEGO Star Wars. Su papel a lo largo de la Trilogía Original y más allá asegura demanda perpetua, convirtiéndolos en el equivalente del Imperio de los Soldados Clon para construcción de ejércitos.'
  },
  {
    no: 'sw0516',
    name: 'Death Star Trooper',
    en: 'The Death Star Trooper is a specialized Imperial soldier assigned to security and operations aboard the Death Star battle station. This minifigure features the distinctive black uniform with Imperial insignia, specialized helmet design for station duty, detailed printing showing rank badges and equipment, and the authoritative appearance of elite Death Star personnel. Released in Death Star themed sets from 2005 onward, particularly in detention block and control room scenarios. Death Star Troopers represent the specialized security forces that guard the Empire\'s ultimate weapon, responsible for internal security and prisoner control. Essential for populating Death Star interiors and creating authentic control room scenes. Collectors value these troopers for their unique black uniforms that distinguish them from standard Stormtroopers, adding variety to Imperial military displays. The association with the Death Star, Star Wars\' most iconic superweapon, makes these specialized troopers memorable elements of Empire collections.',
    de: 'Der Todesstern-Soldat ist ein spezialisierter imperialer Soldat, der der Sicherheit und dem Betrieb an Bord der Todesstern-Kampfstation zugewiesen ist. Diese Minifigur zeigt die charakteristische schwarze Uniform mit imperialen Insignien, spezialisiertes Helmdesign für Stationsdienst, detaillierte Bedruckung, die Rangabzeichen und Ausrüstung zeigt, und das autoritäre Aussehen des Elite-Todesstern-Personals. Sie wurde ab 2005 in Todesstern-thematischen Sets veröffentlicht, insbesondere in Haftblock- und Kontrollraum-Szenarien. Todesstern-Soldaten repräsentieren die spezialisierten Sicherheitskräfte, die die ultimative Waffe des Imperiums bewachen und für interne Sicherheit und Gefangenenkontrolle verantwortlich sind. Unverzichtbar für die Bevölkerung von Todesstern-Innenräumen und die Erstellung authentischer Kontrollraum-Szenen. Sammler schätzen diese Soldaten für ihre einzigartigen schwarzen Uniformen, die sie von Standard-Stormtroopern unterscheiden und Vielfalt zu imperialen Militär-Displays hinzufügen. Die Verbindung mit dem Todesstern, Star Wars\' ikonischster Superwaffe, macht diese spezialisierten Soldaten zu denkwürdigen Elementen von Imperium-Sammlungen.',
    fr: 'Le Soldat de l\'Étoile de la Mort est un soldat Impérial spécialisé assigné à la sécurité et aux opérations à bord de la station de combat de l\'Étoile de la Mort. Cette minifigurine présente l\'uniforme noir distinctif avec insignes Impériaux, un design de casque spécialisé pour le service de station, une impression détaillée montrant des badges de rang et de l\'équipement, et l\'apparence autoritaire du personnel d\'élite de l\'Étoile de la Mort. Sortie dans des sets à thème de l\'Étoile de la Mort à partir de 2005, en particulier dans des scénarios de bloc de détention et de salle de contrôle. Les Soldats de l\'Étoile de la Mort représentent les forces de sécurité spécialisées qui gardent l\'arme ultime de l\'Empire, responsables de la sécurité interne et du contrôle des prisonniers. Essentiels pour peupler les intérieurs de l\'Étoile de la Mort et créer des scènes de salle de contrôle authentiques. Les collectionneurs apprécient ces soldats pour leurs uniformes noirs uniques qui les distinguent des Stormtroopers standard, ajoutant de la variété aux affichages militaires Impériaux. L\'association avec l\'Étoile de la Mort, la super-arme la plus emblématique de Star Wars, fait de ces soldats spécialisés des éléments mémorables des collections de l\'Empire.',
    es: 'El Soldado de la Estrella de la Muerte es un soldado Imperial especializado asignado a seguridad y operaciones a bordo de la estación de batalla Estrella de la Muerte. Esta minifigura presenta el distintivo uniforme negro con insignias Imperiales, diseño de casco especializado para servicio de estación, impresión detallada mostrando insignias de rango y equipo, y la apariencia autoritaria del personal de élite de la Estrella de la Muerte. Lanzado en sets temáticos de la Estrella de la Muerte desde 2005 en adelante, particularmente en escenarios de bloque de detención y sala de control. Los Soldados de la Estrella de la Muerte representan las fuerzas de seguridad especializadas que custodian el arma definitiva del Imperio, responsables de la seguridad interna y control de prisioneros. Esencial para poblar interiores de la Estrella de la Muerte y crear escenas de sala de control auténticas. Los coleccionistas valoran estos soldados por sus uniformes negros únicos que los distinguen de los Stormtroopers estándar, agregando variedad a exhibiciones militares Imperiales. La asociación con la Estrella de la Muerte, la superarma más icónica de Star Wars, hace que estos soldados especializados sean elementos memorables de colecciones del Imperio.'
  },
  {
    no: 'sw0517',
    name: 'Grand Moff Tarkin',
    en: 'Grand Moff Tarkin is the ruthless Imperial governor and commander of the Death Star, one of the Emperor\'s most trusted and feared leaders. This minifigure features Tarkin\'s distinctive gaunt appearance with sharp facial features, olive-gray Imperial officer uniform with high rank insignia, detailed printing showing command codes and Imperial emblems, and the cold, calculating expression of a military mastermind. Released in Death Star sets from 2005 onward, essential for command deck scenarios. Tarkin represents the Empire\'s political and military elite, willing to destroy entire planets to maintain control. Highly collectible as one of the Original Trilogy\'s primary villains, essential for recreating the famous scene where he orders the destruction of Alderaan. Collectors value this figure for its unique character-specific head sculpt and role as the Death Star\'s commanding officer. Tarkin\'s presence elevates any Imperial display, representing the cold bureaucratic evil at the heart of the Empire.',
    de: 'Großmoff Tarkin ist der rücksichtslose imperiale Gouverneur und Kommandant des Todessterns, einer der vertrauenswürdigsten und gefürchtetsten Führer des Imperators. Diese Minifigur zeigt Tarkins charakteristisches hageres Aussehen mit scharfen Gesichtszügen, olivgraue imperiale Offiziersuniform mit hohem Rangabzeichen, detaillierte Bedruckung, die Kommandocodes und imperiale Embleme zeigt, und den kalten, berechnenden Ausdruck eines militärischen Genies. Sie wurde ab 2005 in Todesstern-Sets veröffentlicht, unverzichtbar für Kommandodeck-Szenarien. Tarkin repräsentiert die politische und militärische Elite des Imperiums, bereit, ganze Planeten zu zerstören, um die Kontrolle zu behalten. Sehr sammelwürdig als einer der Hauptbösewichte der Original-Trilogie, unverzichtbar für die Nachstellung der berühmten Szene, in der er die Zerstörung von Alderaan befiehlt. Sammler schätzen diese Figur für ihre einzigartige charakterspezifische Kopfskulptur und Rolle als kommandierender Offizier des Todessterns. Tarkins Präsenz wertet jedes imperiale Display auf und repräsentiert das kalte bürokratische Böse im Herzen des Imperiums.',
    fr: 'Le Grand Moff Tarkin est le gouverneur Impérial impitoyable et commandant de l\'Étoile de la Mort, l\'un des leaders les plus fiables et les plus redoutés de l\'Empereur. Cette minifigurine présente l\'apparence émaciée distinctive de Tarkin avec des traits faciaux pointus, un uniforme d\'officier Impérial gris olive avec insignes de rang élevé, une impression détaillée montrant des codes de commandement et des emblèmes Impériaux, et l\'expression froide et calculatrice d\'un génie militaire. Sortie dans des sets de l\'Étoile de la Mort à partir de 2005, essentielle pour les scénarios de pont de commandement. Tarkin représente l\'élite politique et militaire de l\'Empire, prêt à détruire des planètes entières pour maintenir le contrôle. Hautement collectionnable comme l\'un des principaux méchants de la Trilogie Originale, essentiel pour recréer la scène célèbre où il ordonne la destruction d\'Alderaan. Les collectionneurs apprécient cette figurine pour sa sculpture de tête unique spécifique au personnage et son rôle d\'officier commandant de l\'Étoile de la Mort. La présence de Tarkin élève tout affichage Impérial, représentant le mal bureaucratique froid au cœur de l\'Empire.',
    es: 'El Gran Moff Tarkin es el despiadado gobernador Imperial y comandante de la Estrella de la Muerte, uno de los líderes más confiables y temidos del Emperador. Esta minifigura presenta la distintiva apariencia demacrada de Tarkin con rasgos faciales afilados, uniforme de oficial Imperial gris oliva con insignias de alto rango, impresión detallada mostrando códigos de comando y emblemas Imperiales, y la expresión fría y calculadora de un genio militar. Lanzado en sets de la Estrella de la Muerte desde 2005 en adelante, esencial para escenarios de cubierta de mando. Tarkin representa la élite política y militar del Imperio, dispuesto a destruir planetas enteros para mantener el control. Altamente coleccionable como uno de los principales villanos de la Trilogía Original, esencial para recrear la famosa escena donde ordena la destrucción de Alderaan. Los coleccionistas valoran esta figura por su escultura de cabeza única específica del personaje y papel como oficial comandante de la Estrella de la Muerte. La presencia de Tarkin eleva cualquier exhibición Imperial, representando el frío mal burocrático en el corazón del Imperio.'
  },
  {
    no: 'sw0518',
    name: 'Darth Vader',
    en: 'Darth Vader is the Dark Lord of the Sith and the Emperor\'s enforcer, formerly Anakin Skywalker, representing the most iconic villain in Star Wars history. This minifigure features the legendary all-black armor and cape, distinctive helmet with face mask, detailed torso printing showing chest control panel and belt, and imposing presence. Released in countless sets throughout LEGO Star Wars history since 1999, becoming one of the most frequently produced and collected characters. Vader represents fallen heroism and tragic destiny, the ultimate symbol of the dark side\'s corruption. Extremely collectible with numerous variants showing subtle design improvements across decades of production. Essential for virtually any Star Wars collection, as Vader appears in pivotal scenes throughout the Original Trilogy and Prequel Trilogy. The iconic silhouette and universal recognition make Darth Vader the definitive Star Wars villain figure, with collectors often seeking every variant to track the evolution of this legendary character across LEGO history.',
    de: 'Darth Vader ist der Dunkle Lord der Sith und der Vollstrecker des Imperators, ehemals Anakin Skywalker, und repräsentiert den ikonischsten Bösewicht in der Star Wars-Geschichte. Diese Minifigur zeigt die legendäre ganz schwarze Rüstung und den Umhang, charakteristischen Helm mit Gesichtsmaske, detaillierte Torso-Bedruckung, die das Brust-Kontrollpanel und den Gürtel zeigt, und imposante Präsenz. Sie wurde seit 1999 in unzähligen Sets durch die gesamte LEGO-Star-Wars-Geschichte veröffentlicht und wurde zu einem der am häufigsten produzierten und gesammelten Charaktere. Vader repräsentiert gefallenes Heldentum und tragisches Schicksal, das ultimative Symbol der Korruption der dunklen Seite. Extrem sammelwürdig mit zahlreichen Varianten, die subtile Designverbesserungen über Jahrzehnte der Produktion zeigen. Unverzichtbar für praktisch jede Star Wars-Sammlung, da Vader in entscheidenden Szenen durch die Original-Trilogie und Prequel-Trilogie auftritt. Die ikonische Silhouette und universelle Wiedererkennung machen Darth Vader zur definitiven Star Wars-Bösewicht-Figur, wobei Sammler oft jede Variante suchen, um die Entwicklung dieses legendären Charakters durch die LEGO-Geschichte zu verfolgen.',
    fr: 'Dark Vador est le Seigneur Noir des Sith et l\'exécuteur de l\'Empereur, anciennement Anakin Skywalker, représentant le méchant le plus emblématique de l\'histoire de Star Wars. Cette minifigurine présente l\'armure et la cape légendaires entièrement noires, un casque distinctif avec masque facial, une impression de torse détaillée montrant le panneau de contrôle de poitrine et la ceinture, et une présence imposante. Sortie dans d\'innombrables sets tout au long de l\'histoire LEGO Star Wars depuis 1999, devenant l\'un des personnages les plus fréquemment produits et collectionnés. Vador représente l\'héroïsme déchu et le destin tragique, le symbole ultime de la corruption du côté obscur. Extrêmement collectionnable avec de nombreux variants montrant des améliorations de design subtiles à travers des décennies de production. Essentiel pour pratiquement toute collection Star Wars, car Vador apparaît dans des scènes cruciales tout au long de la Trilogie Originale et de la Trilogie Préquelle. La silhouette emblématique et la reconnaissance universelle font de Dark Vador la figurine de méchant Star Wars définitive, les collectionneurs recherchant souvent chaque variant pour suivre l\'évolution de ce personnage légendaire à travers l\'histoire LEGO.',
    es: 'Darth Vader es el Señor Oscuro de los Sith y el ejecutor del Emperador, anteriormente Anakin Skywalker, representando el villano más icónico en la historia de Star Wars. Esta minifigura presenta la legendaria armadura y capa completamente negras, casco distintivo con máscara facial, impresión de torso detallada mostrando panel de control de pecho y cinturón, y presencia imponente. Lanzado en innumerables sets a lo largo de la historia de LEGO Star Wars desde 1999, convirtiéndose en uno de los personajes más frecuentemente producidos y coleccionados. Vader representa el heroísmo caído y el destino trágico, el símbolo definitivo de la corrupción del lado oscuro. Extremadamente coleccionable con numerosas variantes mostrando mejoras de diseño sutiles a través de décadas de producción. Esencial para prácticamente cualquier colección de Star Wars, ya que Vader aparece en escenas cruciales a lo largo de la Trilogía Original y la Trilogía Precuela. La silueta icónica y el reconocimiento universal hacen de Darth Vader la figura de villano definitiva de Star Wars, con coleccionistas a menudo buscando cada variante para rastrear la evolución de este personaje legendario a través de la historia de LEGO.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 401-410 (sw0509-sw0518) - 10 minifigs...\n');

  for (const m of batch) {
    await prisma.minifigCatalog.upsert({
      where: { minifigure_no: m.no },
      update: {
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      },
      create: {
        minifigure_no: m.no,
        name: m.name,
        category_id: 1,
        category_name: 'Star Wars',
        search_name: m.name.toLowerCase(),
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`  ✅ ${m.no}: ${m.name}`);
  }

  console.log('\n✨ Batch 401-410 complete: 10 minifigs (40 descriptions)');
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
