import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0549',
    name: 'Ewok',
    en: 'Ewoks are the small furry inhabitants of Endor\'s forest moon who help the Rebel Alliance defeat the Empire in Return of the Jedi, proving that courage matters more than size. This minifigure features brown fur covering a small body, large curious eyes, simple primitive clothing and hood, and typically includes spear or bow weapons. Released in numerous Endor battle sets from 2005 onward, particularly in Ewok village and AT-ST battle scenarios. Ewoks represent the unlikely heroes who turned the tide at the Battle of Endor, using guerrilla tactics and local knowledge to defeat Imperial forces. Essential for recreating the forest moon battles and showing the Rebellion\'s ability to forge alliances. Collectors often army-build Ewoks to populate village displays and recreate the full scale of their contribution to the Empire\'s defeat. The cute appearance contrasts with their effective warrior capabilities, making Ewoks beloved characters.',
    de: 'Ewoks sind die kleinen pelzigen Bewohner des Waldmonds Endor, die der Rebellen-Allianz helfen, das Imperium in Die Rückkehr der Jedi-Ritter zu besiegen, und beweisen, dass Mut mehr zählt als Größe. Diese Minifigur zeigt braunes Fell, das einen kleinen Körper bedeckt, große neugierige Augen, einfache primitive Kleidung und Kapuze und enthält typischerweise Speer- oder Bogenwaffen. Sie wurde ab 2005 in zahlreichen Endor-Schlacht-Sets veröffentlicht, insbesondere in Ewok-Dorf- und AT-ST-Schlacht-Szenarien. Ewoks repräsentieren die unwahrscheinlichen Helden, die das Blatt in der Schlacht von Endor wendeten und Guerillataktiken und lokales Wissen nutzten, um imperiale Streitkräfte zu besiegen. Unverzichtbar für die Nachstellung der Waldmond-Schlachten und um die Fähigkeit der Rebellion zu zeigen, Allianzen zu schmieden. Sammler bauen Ewoks oft in Armeen auf, um Dorf-Displays zu bevölkern und den vollen Umfang ihres Beitrags zur Niederlage des Imperiums nachzustellen. Das niedliche Aussehen kontrastiert mit ihren effektiven Kriegerfähigkeiten und macht Ewoks zu beliebten Charakteren.',
    fr: 'Les Ewoks sont les petits habitants poilus de la lune forestière d\'Endor qui aident l\'Alliance Rebelle à vaincre l\'Empire dans Le Retour du Jedi, prouvant que le courage compte plus que la taille. Cette minifigurine présente de la fourrure brune couvrant un petit corps, de grands yeux curieux, des vêtements primitifs simples et une capuche, et inclut généralement des armes de lance ou d\'arc. Sortie dans de nombreux sets de bataille d\'Endor à partir de 2005, en particulier dans des scénarios de village Ewok et de bataille AT-ST. Les Ewoks représentent les héros improbables qui ont inversé la tendance à la Bataille d\'Endor, utilisant des tactiques de guérilla et des connaissances locales pour vaincre les forces Impériales. Essentiels pour recréer les batailles de la lune forestière et montrer la capacité de la Rébellion à forger des alliances. Les collectionneurs construisent souvent des armées d\'Ewoks pour peupler les affichages de village et recréer l\'ampleur totale de leur contribution à la défaite de l\'Empire. L\'apparence mignonne contraste avec leurs capacités de guerrier efficaces, faisant des Ewoks des personnages bien-aimés.',
    es: 'Los Ewoks son los pequeños habitantes peludos de la luna boscosa de Endor que ayudan a la Alianza Rebelde a derrotar al Imperio en El Retorno del Jedi, demostrando que el coraje importa más que el tamaño. Esta minifigura presenta pelaje marrón cubriendo un cuerpo pequeño, grandes ojos curiosos, ropa primitiva simple y capucha, y típicamente incluye armas de lanza o arco. Lanzado en numerosos sets de batalla de Endor desde 2005 en adelante, particularmente en escenarios de aldea Ewok y batalla AT-ST. Los Ewoks representan los héroes improbables que cambiaron el rumbo en la Batalla de Endor, usando tácticas de guerrilla y conocimiento local para derrotar fuerzas Imperiales. Esencial para recrear las batallas de la luna boscosa y mostrar la capacidad de la Rebelión para forjar alianzas. Los coleccionistas a menudo construyen ejércitos de Ewoks para poblar exhibiciones de aldea y recrear la escala completa de su contribución a la derrota del Imperio. La apariencia linda contrasta con sus capacidades efectivas de guerrero, haciendo que los Ewoks sean personajes queridos.'
  },
  {
    no: 'sw0550',
    name: 'Rebel Commando',
    en: 'Rebel Commandos are the elite special forces soldiers who formed the strike team to destroy the Death Star II shield generator on Endor. This minifigure features camouflage uniform with brown and green patterns, specialized combat helmet, tactical equipment and weaponry, and the rugged appearance of guerrilla fighters. Released in Endor battle sets from 2005 onward, particularly in shield generator bunker assault scenarios. Rebel Commandos represent the Rebellion\'s best trained soldiers, capable of operating behind enemy lines and executing high-risk missions. Essential for recreating the Battle of Endor ground assault led by Han Solo. Collectors value these figures for their distinctive camouflage patterns and role in the Rebellion\'s ultimate victory. The forest camouflage and military gear make Rebel Commandos visually distinct from standard Rebel troops, showing the specialized nature of the Endor mission.',
    de: 'Rebellen-Kommandos sind die Elite-Spezialeinheiten-Soldaten, die das Stoßteam bildeten, um den Todesstern-II-Schildgenerator auf Endor zu zerstören. Diese Minifigur zeigt Tarnuniform mit braun-grünen Mustern, spezialisierten Kampfhelm, taktische Ausrüstung und Bewaffnung und das raue Aussehen von Guerillakämpfern. Sie wurde ab 2005 in Endor-Schlacht-Sets veröffentlicht, insbesondere in Schildgenerator-Bunker-Angriffs-Szenarien. Rebellen-Kommandos repräsentieren die am besten ausgebildeten Soldaten der Rebellion, fähig, hinter feindlichen Linien zu operieren und Hochrisiko-Missionen auszuführen. Unverzichtbar für die Nachstellung des Bodenangriffs der Schlacht von Endor unter der Führung von Han Solo. Sammler schätzen diese Figuren für ihre charakteristischen Tarnmuster und ihre Rolle im ultimativen Sieg der Rebellion. Die Waldtarnung und militärische Ausrüstung machen Rebellen-Kommandos visuell anders als Standard-Rebellentruppen und zeigen die spezialisierte Natur der Endor-Mission.',
    fr: 'Les Commandos Rebelles sont les soldats des forces spéciales d\'élite qui ont formé l\'équipe de frappe pour détruire le générateur de bouclier de l\'Étoile de la Mort II sur Endor. Cette minifigurine présente un uniforme de camouflage avec des motifs bruns et verts, un casque de combat spécialisé, un équipement tactique et un armement, et l\'apparence robuste de combattants de guérilla. Sortie dans des sets de bataille d\'Endor à partir de 2005, en particulier dans des scénarios d\'assaut de bunker de générateur de bouclier. Les Commandos Rebelles représentent les soldats les mieux formés de la Rébellion, capables d\'opérer derrière les lignes ennemies et d\'exécuter des missions à haut risque. Essentiels pour recréer l\'assaut au sol de la Bataille d\'Endor dirigé par Han Solo. Les collectionneurs apprécient ces figurines pour leurs motifs de camouflage distinctifs et leur rôle dans la victoire ultime de la Rébellion. Le camouflage forestier et l\'équipement militaire rendent les Commandos Rebelles visuellement distincts des troupes Rebelles standard, montrant la nature spécialisée de la mission Endor.',
    es: 'Los Comandos Rebeldes son los soldados de fuerzas especiales de élite que formaron el equipo de asalto para destruir el generador de escudo de la Estrella de la Muerte II en Endor. Esta minifigura presenta uniforme de camuflaje con patrones marrones y verdes, casco de combate especializado, equipo táctico y armamento, y la apariencia ruda de luchadores guerrilleros. Lanzado en sets de batalla de Endor desde 2005 en adelante, particularmente en escenarios de asalto al búnker del generador de escudo. Los Comandos Rebeldes representan los soldados mejor entrenados de la Rebelión, capaces de operar tras las líneas enemigas y ejecutar misiones de alto riesgo. Esencial para recrear el asalto terrestre de la Batalla de Endor liderado por Han Solo. Los coleccionistas valoran estas figuras por sus patrones de camuflaje distintivos y papel en la victoria definitiva de la Rebelión. El camuflaje de bosque y el equipo militar hacen que los Comandos Rebeldes sean visualmente distintos de las tropas Rebeldes estándar, mostrando la naturaleza especializada de la misión de Endor.'
  },
  {
    no: 'sw0551',
    name: 'Scout Trooper',
    en: 'Scout Troopers are specialized Imperial soldiers trained for reconnaissance and patrol on speeder bikes, particularly deployed on Endor to guard the Death Star II shield generator. This minifigure features the distinctive white armor with black accents and flexible bodysuit, specialized helmet with enhanced optics, lighter equipment for mobility, and association with speeder bikes. Released in numerous Endor sets from 2005 onward, particularly in speeder bike chase scenarios. Scout Troopers represent Imperial adaptation for forest and reconnaissance operations, faster and more mobile than standard Stormtroopers. Essential for recreating the famous speeder bike chase through Endor\'s forests. Highly collectible for their unique armor design and iconic role in Return of the Jedi action sequences. The sleeker appearance and speeder bike association make Scout Troopers memorable Imperial variants.',
    de: 'Scout-Trooper sind spezialisierte imperiale Soldaten, die für Aufklärung und Patrouille auf Speeder-Bikes trainiert sind, insbesondere auf Endor eingesetzt, um den Todesstern-II-Schildgenerator zu bewachen. Diese Minifigur zeigt die charakteristische weiße Rüstung mit schwarzen Akzenten und flexiblem Bodysuit, spezialisierten Helm mit verbesserter Optik, leichtere Ausrüstung für Mobilität und Verbindung mit Speeder-Bikes. Sie wurde ab 2005 in zahlreichen Endor-Sets veröffentlicht, insbesondere in Speeder-Bike-Verfolgungsjagd-Szenarien. Scout-Trooper repräsentieren imperiale Anpassung für Wald- und Aufklärungsoperationen, schneller und mobiler als Standard-Stormtrooper. Unverzichtbar für die Nachstellung der berühmten Speeder-Bike-Verfolgungsjagd durch Endors Wälder. Sehr sammelwürdig für ihr einzigartiges Rüstungsdesign und ikonische Rolle in Die Rückkehr der Jedi-Ritter-Aktionssequenzen. Das schlankere Aussehen und die Speeder-Bike-Verbindung machen Scout-Trooper zu denkwürdigen imperialen Varianten.',
    fr: 'Les Scout Troopers sont des soldats Impériaux spécialisés formés pour la reconnaissance et la patrouille sur speeder bikes, en particulier déployés sur Endor pour garder le générateur de bouclier de l\'Étoile de la Mort II. Cette minifigurine présente l\'armure blanche distinctive avec des accents noirs et une combinaison flexible, un casque spécialisé avec optique améliorée, un équipement plus léger pour la mobilité, et une association avec les speeder bikes. Sortie dans de nombreux sets d\'Endor à partir de 2005, en particulier dans des scénarios de poursuite en speeder bike. Les Scout Troopers représentent l\'adaptation Impériale pour les opérations forestières et de reconnaissance, plus rapides et plus mobiles que les Stormtroopers standard. Essentiels pour recréer la célèbre poursuite en speeder bike à travers les forêts d\'Endor. Hautement collectionnables pour leur design d\'armure unique et leur rôle emblématique dans les séquences d\'action du Retour du Jedi. L\'apparence plus élancée et l\'association avec les speeder bikes font des Scout Troopers des variants Impériaux mémorables.',
    es: 'Los Scout Troopers son soldados Imperiales especializados entrenados para reconocimiento y patrulla en speeder bikes, particularmente desplegados en Endor para custodiar el generador de escudo de la Estrella de la Muerte II. Esta minifigura presenta la distintiva armadura blanca con acentos negros y traje flexible, casco especializado con óptica mejorada, equipo más ligero para movilidad, y asociación con speeder bikes. Lanzado en numerosos sets de Endor desde 2005 en adelante, particularmente en escenarios de persecución en speeder bike. Los Scout Troopers representan la adaptación Imperial para operaciones de bosque y reconocimiento, más rápidos y móviles que los Stormtroopers estándar. Esencial para recrear la famosa persecución en speeder bike a través de los bosques de Endor. Altamente coleccionable por su diseño de armadura único y papel icónico en secuencias de acción de El Retorno del Jedi. La apariencia más esbelta y la asociación con speeder bike hacen que los Scout Troopers sean variantes Imperiales memorables.'
  },
  {
    no: 'sw0552',
    name: 'AT-ST Driver',
    en: 'AT-ST Drivers pilot the two-legged All Terrain Scout Transport walkers used by the Empire for reconnaissance and ground support operations. This minifigure features distinctive light gray uniform, specialized helmet with enhanced targeting systems, Imperial insignia, and equipment for operating the compact walker. Released in AT-ST sets from 2005 onward, particularly in Endor battle scenarios. AT-ST Drivers represent specialized Imperial vehicle operators trained to navigate difficult terrain in the Empire\'s lighter assault walkers. Essential for crewing AT-ST models and recreating scenes where Ewoks capture and commandeer these vehicles. Collectors value these drivers for their unique uniform color and association with the memorable AT-ST that Chewbacca hijacks during the Battle of Endor. The light gray distinguishes them from other Imperial troops.',
    de: 'AT-ST-Fahrer pilotieren die zweibeinigen All Terrain Scout Transport-Läufer, die vom Imperium für Aufklärungs- und Bodenunterstützungsoperationen eingesetzt werden. Diese Minifigur zeigt charakteristische hellgraue Uniform, spezialisierten Helm mit verbesserten Zielsystemen, imperiale Insignien und Ausrüstung zum Bedienen des kompakten Läufers. Sie wurde ab 2005 in AT-ST-Sets veröffentlicht, insbesondere in Endor-Schlacht-Szenarien. AT-ST-Fahrer repräsentieren spezialisierte imperiale Fahrzeugoperatoren, die trainiert sind, schwieriges Gelände in den leichteren Angriffsläufern des Imperiums zu navigieren. Unverzichtbar für die Bemannung von AT-ST-Modellen und die Nachstellung von Szenen, in denen Ewoks diese Fahrzeuge erobern und kommandieren. Sammler schätzen diese Fahrer für ihre einzigartige Uniformfarbe und Verbindung mit dem denkwürdigen AT-ST, den Chewbacca während der Schlacht von Endor kapert. Das Hellgrau unterscheidet sie von anderen imperialen Truppen.',
    fr: 'Les Conducteurs d\'AT-ST pilotent les marcheurs All Terrain Scout Transport à deux jambes utilisés par l\'Empire pour les opérations de reconnaissance et de soutien au sol. Cette minifigurine présente un uniforme gris clair distinctif, un casque spécialisé avec systèmes de ciblage améliorés, des insignes Impériaux, et un équipement pour faire fonctionner le marcheur compact. Sortie dans des sets AT-ST à partir de 2005, en particulier dans des scénarios de bataille d\'Endor. Les Conducteurs d\'AT-ST représentent des opérateurs de véhicules Impériaux spécialisés formés pour naviguer sur terrain difficile dans les marcheurs d\'assaut plus légers de l\'Empire. Essentiels pour équiper les modèles AT-ST et recréer des scènes où les Ewoks capturent et commandent ces véhicules. Les collectionneurs apprécient ces conducteurs pour leur couleur d\'uniforme unique et leur association avec l\'AT-ST mémorable que Chewbacca détourne pendant la Bataille d\'Endor. Le gris clair les distingue des autres troupes Impériales.',
    es: 'Los Conductores de AT-ST pilotan los caminantes All Terrain Scout Transport de dos patas utilizados por el Imperio para operaciones de reconocimiento y apoyo terrestre. Esta minifigura presenta distintivo uniforme gris claro, casco especializado con sistemas de apuntado mejorados, insignias Imperiales, y equipo para operar el caminante compacto. Lanzado en sets de AT-ST desde 2005 en adelante, particularmente en escenarios de batalla de Endor. Los Conductores de AT-ST representan operadores de vehículos Imperiales especializados entrenados para navegar terreno difícil en los caminantes de asalto más ligeros del Imperio. Esencial para tripular modelos de AT-ST y recrear escenas donde los Ewoks capturan y comandean estos vehículos. Los coleccionistas valoran estos conductores por su color de uniforme único y asociación con el memorable AT-ST que Chewbacca secuestra durante la Batalla de Endor. El gris claro los distingue de otras tropas Imperiales.'
  },
  {
    no: 'sw0553',
    name: 'Admiral Ackbar',
    en: 'Admiral Ackbar is the Mon Calamari military leader who commands the Rebel fleet during the Battle of Endor, famous for warning "It\'s a trap!" when the Empire springs its ambush. This minifigure features Ackbar\'s distinctive salmon-colored fish-like head with large eyes, white Rebel admiral uniform with rank insignia, and the dignified appearance of fleet command. Released in Rebel fleet and command ship sets from 2005 onward. Admiral Ackbar represents alien leadership in the Rebellion, showing the diversity of species united against Imperial tyranny. Essential for recreating Rebel fleet command scenes and the Battle of Endor space combat. Highly collectible as one of the most memorable alien characters in Star Wars, with his tactical warning becoming an iconic meme. The unique Mon Calamari appearance makes Ackbar instantly recognizable and a fan-favorite character.',
    de: 'Admiral Ackbar ist der Mon Calamari-Militärführer, der die Rebellenflotte während der Schlacht von Endor kommandiert, berühmt für die Warnung "Es ist eine Falle!", als das Imperium seinen Hinterhalt auslöst. Diese Minifigur zeigt Ackbars charakteristischen lachsfarbenen fischähnlichen Kopf mit großen Augen, weiße Rebellen-Admiral-Uniform mit Rangabzeichen und das würdevolle Aussehen des Flottenkommandos. Sie wurde ab 2005 in Rebellenflotten- und Kommandoschiff-Sets veröffentlicht. Admiral Ackbar repräsentiert außerirdische Führung in der Rebellion und zeigt die Vielfalt der Spezies, die gegen imperiale Tyrannei vereint sind. Unverzichtbar für die Nachstellung von Rebellenflotten-Kommandoszenen und dem Weltraumkampf der Schlacht von Endor. Sehr sammelwürdig als einer der denkwürdigsten außerirdischen Charaktere in Star Wars, wobei seine taktische Warnung zu einem ikonischen Meme wurde. Das einzigartige Mon Calamari-Aussehen macht Ackbar sofort erkennbar und zu einem Fan-Favoriten-Charakter.',
    fr: 'L\'Amiral Ackbar est le leader militaire Mon Calamari qui commande la flotte Rebelle pendant la Bataille d\'Endor, célèbre pour avoir averti "C\'est un piège !" lorsque l\'Empire déclenche son embuscade. Cette minifigurine présente la tête distinctive couleur saumon ressemblant à un poisson d\'Ackbar avec de grands yeux, un uniforme blanc d\'amiral Rebelle avec insignes de rang, et l\'apparence digne du commandement de flotte. Sortie dans des sets de flotte Rebelle et de vaisseau de commandement à partir de 2005. L\'Amiral Ackbar représente le leadership alien dans la Rébellion, montrant la diversité des espèces unies contre la tyrannie Impériale. Essentiel pour recréer des scènes de commandement de flotte Rebelle et le combat spatial de la Bataille d\'Endor. Hautement collectionnable comme l\'un des personnages aliens les plus mémorables de Star Wars, son avertissement tactique étant devenu un mème emblématique. L\'apparence unique Mon Calamari rend Ackbar instantanément reconnaissable et un personnage favori des fans.',
    es: 'El Almirante Ackbar es el líder militar Mon Calamari que comanda la flota Rebelde durante la Batalla de Endor, famoso por advertir "¡Es una trampa!" cuando el Imperio lanza su emboscada. Esta minifigura presenta la distintiva cabeza de color salmón parecida a pez de Ackbar con ojos grandes, uniforme blanco de almirante Rebelde con insignias de rango, y la apariencia digna del comando de flota. Lanzado en sets de flota Rebelde y nave de comando desde 2005 en adelante. El Almirante Ackbar representa liderazgo alienígena en la Rebelión, mostrando la diversidad de especies unidas contra la tiranía Imperial. Esencial para recrear escenas de comando de flota Rebelde y el combate espacial de la Batalla de Endor. Altamente coleccionable como uno de los personajes alienígenas más memorables en Star Wars, con su advertencia táctica convirtiéndose en un meme icónico. La apariencia única Mon Calamari hace que Ackbar sea instantáneamente reconocible y un personaje favorito de los fanáticos.'
  },
  {
    no: 'sw0554',
    name: 'B-wing Pilot',
    en: 'B-wing Pilots operate the Rebellion\'s most powerful starfighter, designed specifically for assault missions against capital ships during the Battle of Endor. This minifigure features the distinctive flight suit with Rebel insignia, specialized helmet for B-wing operations, detailed equipment printing, and the appearance of elite strike fighter pilots. Released in B-wing starfighter sets from 2005 onward. B-wing Pilots represent the Rebellion\'s heavy assault capability, flying complex rotating-wing fighters that pack tremendous firepower. Essential for crewing B-wing models and recreating the multi-pronged Rebel attack on the second Death Star. Collectors value these pilots for representing one of the most unique Rebel starfighter designs. The B-wing\'s distinctive asymmetric design makes its pilots memorable elements of Rebel fleet displays.',
    de: 'B-Wing-Piloten bedienen den mächtigsten Raumjäger der Rebellion, speziell für Angriffsmissionen gegen Großkampfschiffe während der Schlacht von Endor entwickelt. Diese Minifigur zeigt den charakteristischen Fluganzug mit Rebellen-Insignien, spezialisierten Helm für B-Wing-Operationen, detaillierte Ausrüstungsbedruckung und das Aussehen von Elite-Angriffsjäger-Piloten. Sie wurde ab 2005 in B-Wing-Raumjäger-Sets veröffentlicht. B-Wing-Piloten repräsentieren die schwere Angriffsfähigkeit der Rebellion und fliegen komplexe rotierende Flügeljäger, die enorme Feuerkraft packen. Unverzichtbar für die Bemannung von B-Wing-Modellen und die Nachstellung des mehrzinkigen Rebellenangriffs auf den zweiten Todesstern. Sammler schätzen diese Piloten dafür, eines der einzigartigsten Rebellen-Raumjäger-Designs zu repräsentieren. Das charakteristische asymmetrische Design des B-Wings macht seine Piloten zu denkwürdigen Elementen von Rebellenflotten-Displays.',
    fr: 'Les Pilotes de B-wing pilotent le chasseur stellaire le plus puissant de la Rébellion, conçu spécifiquement pour les missions d\'assaut contre les vaisseaux capitaux pendant la Bataille d\'Endor. Cette minifigurine présente la combinaison de vol distinctive avec insignes Rebelles, un casque spécialisé pour les opérations B-wing, une impression d\'équipement détaillée, et l\'apparence de pilotes de chasseurs d\'assaut d\'élite. Sortie dans des sets de chasseur stellaire B-wing à partir de 2005. Les Pilotes de B-wing représentent la capacité d\'assaut lourd de la Rébellion, pilotant des chasseurs à ailes rotatives complexes qui emballent une puissance de feu formidable. Essentiels pour équiper les modèles B-wing et recréer l\'attaque Rebelle à plusieurs volets sur la deuxième Étoile de la Mort. Les collectionneurs apprécient ces pilotes pour représenter l\'un des designs de chasseurs stellaires Rebelles les plus uniques. Le design asymétrique distinctif du B-wing fait de ses pilotes des éléments mémorables des affichages de flotte Rebelle.',
    es: 'Los Pilotos de B-wing operan el caza estelar más poderoso de la Rebelión, diseñado específicamente para misiones de asalto contra naves capitales durante la Batalla de Endor. Esta minifigura presenta el distintivo traje de vuelo con insignias Rebeldes, casco especializado para operaciones de B-wing, impresión detallada de equipo, y la apariencia de pilotos de cazas de asalto de élite. Lanzado en sets de caza estelar B-wing desde 2005 en adelante. Los Pilotos de B-wing representan la capacidad de asalto pesado de la Rebelión, volando complejos cazas de ala rotatoria que empaquetan tremenda potencia de fuego. Esencial para tripular modelos de B-wing y recrear el ataque Rebelde de múltiples frentes a la segunda Estrella de la Muerte. Los coleccionistas valoran estos pilotos por representar uno de los diseños de caza estelar Rebelde más únicos. El distintivo diseño asimétrico del B-wing hace que sus pilotos sean elementos memorables de exhibiciones de flota Rebelde.'
  },
  {
    no: 'sw0555',
    name: 'A-wing Pilot',
    en: 'A-wing Pilots fly the Rebellion\'s fastest and most maneuverable starfighters, essential interceptors during the Battle of Endor. This minifigure features distinctive green flight suit with Rebel insignia, specialized helmet for high-speed operations, detailed equipment printing, and the appearance of elite fighter pilots. Released in A-wing starfighter sets from 2005 onward. A-wing Pilots represent speed and agility in the Rebel fleet, flying interceptors fast enough to engage TIE Interceptors and protect larger bombers. Essential for crewing A-wing models and recreating the diverse Rebel fighter squadrons at Endor. Collectors value these pilots for their unique green flight suit that distinguishes them from orange-suited X-wing pilots. The A-wing\'s reputation as the fastest Rebel fighter makes its pilots memorable elements representing the Rebellion\'s tactical diversity.',
    de: 'A-Wing-Piloten fliegen die schnellsten und wendigsten Raumjäger der Rebellion, unverzichtbare Abfangjäger während der Schlacht von Endor. Diese Minifigur zeigt charakteristischen grünen Fluganzug mit Rebellen-Insignien, spezialisierten Helm für Hochgeschwindigkeitsoperationen, detaillierte Ausrüstungsbedruckung und das Aussehen von Elite-Jägerpiloten. Sie wurde ab 2005 in A-Wing-Raumjäger-Sets veröffentlicht. A-Wing-Piloten repräsentieren Geschwindigkeit und Agilität in der Rebellenflotte und fliegen Abfangjäger, die schnell genug sind, um TIE-Abfangjäger anzugreifen und größere Bomber zu schützen. Unverzichtbar für die Bemannung von A-Wing-Modellen und die Nachstellung der vielfältigen Rebellen-Jäger-Geschwader bei Endor. Sammler schätzen diese Piloten für ihren einzigartigen grünen Fluganzug, der sie von orangefarbenen X-Wing-Piloten unterscheidet. Der Ruf des A-Wings als schnellster Rebellenjäger macht seine Piloten zu denkwürdigen Elementen, die die taktische Vielfalt der Rebellion repräsentieren.',
    fr: 'Les Pilotes d\'A-wing pilotent les chasseurs stellaires les plus rapides et les plus maniables de la Rébellion, des intercepteurs essentiels pendant la Bataille d\'Endor. Cette minifigurine présente une combinaison de vol verte distinctive avec insignes Rebelles, un casque spécialisé pour les opérations à haute vitesse, une impression d\'équipement détaillée, et l\'apparence de pilotes de chasse d\'élite. Sortie dans des sets de chasseur stellaire A-wing à partir de 2005. Les Pilotes d\'A-wing représentent la vitesse et l\'agilité dans la flotte Rebelle, pilotant des intercepteurs assez rapides pour engager les Intercepteurs TIE et protéger les bombardiers plus grands. Essentiels pour équiper les modèles A-wing et recréer les divers escadrons de chasseurs Rebelles à Endor. Les collectionneurs apprécient ces pilotes pour leur combinaison de vol verte unique qui les distingue des pilotes X-wing en orange. La réputation de l\'A-wing comme chasseur Rebelle le plus rapide fait de ses pilotes des éléments mémorables représentant la diversité tactique de la Rébellion.',
    es: 'Los Pilotos de A-wing vuelan los cazas estelares más rápidos y maniobrables de la Rebelión, interceptores esenciales durante la Batalla de Endor. Esta minifigura presenta distintivo traje de vuelo verde con insignias Rebeldes, casco especializado para operaciones de alta velocidad, impresión detallada de equipo, y la apariencia de pilotos de caza de élite. Lanzado en sets de caza estelar A-wing desde 2005 en adelante. Los Pilotos de A-wing representan velocidad y agilidad en la flota Rebelde, volando interceptores lo suficientemente rápidos para enfrentar Interceptores TIE y proteger bombarderos más grandes. Esencial para tripular modelos de A-wing y recrear los diversos escuadrones de cazas Rebeldes en Endor. Los coleccionistas valoran estos pilotos por su traje de vuelo verde único que los distingue de pilotos de X-wing vestidos de naranja. La reputación del A-wing como el caza Rebelde más rápido hace que sus pilotos sean elementos memorables representando la diversidad táctica de la Rebelión.'
  },
  {
    no: 'sw0556',
    name: 'Jabba the Hutt',
    en: 'Jabba the Hutt is the massive crime lord who controls the criminal underworld of Tatooine from his desert palace, holding Han Solo captive in carbonite. This minifigure features Jabba\'s distinctive slug-like body, large size taking multiple LEGO pieces, green-brown coloring with detailed texture, and the grotesque appearance of the galaxy\'s most powerful gangster. Released in Jabba\'s Palace sets from 2005 onward. Jabba represents organized crime and corruption in Star Wars, a villain whose power comes from wealth and connections rather than the Force. Essential for recreating the iconic palace scenes including Han\'s rescue and the Rancor pit. Highly collectible as one of Star Wars\' most memorable villains, with the unique large build making Jabba a centerpiece figure. The grotesque design and palace association make Jabba instantly recognizable and essential for Return of the Jedi collections.',
    de: 'Jabba the Hutt ist der massive Verbrecherlord, der die kriminelle Unterwelt von Tatooine von seinem Wüstenpalast aus kontrolliert und Han Solo in Karbonit gefangen hält. Diese Minifigur zeigt Jabbas charakteristischen schneckenähnlichen Körper, große Größe, die mehrere LEGO-Teile benötigt, grün-braune Färbung mit detaillierter Textur und das groteske Aussehen des mächtigsten Gangsters der Galaxis. Sie wurde ab 2005 in Jabbas Palast-Sets veröffentlicht. Jabba repräsentiert organisierte Kriminalität und Korruption in Star Wars, ein Bösewicht, dessen Macht aus Reichtum und Verbindungen statt aus der Macht kommt. Unverzichtbar für die Nachstellung der ikonischen Palastszenen einschließlich Hans Rettung und der Rancor-Grube. Sehr sammelwürdig als einer der denkwürdigsten Bösewichte von Star Wars, wobei der einzigartige große Bau Jabba zu einer Herzstück-Figur macht. Das groteske Design und die Palast-Verbindung machen Jabba sofort erkennbar und unverzichtbar für Die Rückkehr der Jedi-Ritter-Sammlungen.',
    fr: 'Jabba le Hutt est le seigneur du crime massif qui contrôle le monde souterrain criminel de Tatooine depuis son palais du désert, tenant Han Solo captif dans la carbonite. Cette minifigurine présente le corps distinctif ressemblant à une limace de Jabba, une grande taille nécessitant plusieurs pièces LEGO, une coloration vert-brun avec texture détaillée, et l\'apparence grotesque du gangster le plus puissant de la galaxie. Sortie dans des sets du Palais de Jabba à partir de 2005. Jabba représente le crime organisé et la corruption dans Star Wars, un méchant dont le pouvoir vient de la richesse et des connexions plutôt que de la Force. Essentiel pour recréer les scènes emblématiques du palais, y compris le sauvetage de Han et la fosse du Rancor. Hautement collectionnable comme l\'un des méchants les plus mémorables de Star Wars, la construction unique et grande faisant de Jabba une figurine pièce maîtresse. Le design grotesque et l\'association avec le palais rendent Jabba instantanément reconnaissable et essentiel pour les collections du Retour du Jedi.',
    es: 'Jabba the Hutt es el masivo señor del crimen que controla el submundo criminal de Tatooine desde su palacio en el desierto, manteniendo a Han Solo cautivo en carbonita. Esta minifigura presenta el distintivo cuerpo parecido a babosa de Jabba, gran tamaño que requiere múltiples piezas LEGO, coloración verde-marrón con textura detallada, y la apariencia grotesca del gángster más poderoso de la galaxia. Lanzado en sets del Palacio de Jabba desde 2005 en adelante. Jabba representa el crimen organizado y la corrupción en Star Wars, un villano cuyo poder proviene de la riqueza y las conexiones en lugar de la Fuerza. Esencial para recrear las icónicas escenas del palacio incluyendo el rescate de Han y el foso del Rancor. Altamente coleccionable como uno de los villanos más memorables de Star Wars, con la construcción grande única haciendo de Jabba una figura central. El diseño grotesco y la asociación con el palacio hacen que Jabba sea instantáneamente reconocible y esencial para colecciones de El Retorno del Jedi.'
  },
  {
    no: 'sw0557',
    name: 'Bib Fortuna',
    en: 'Bib Fortuna is Jabba the Hutt\'s Twi\'lek majordomo and chief of staff, managing the crime lord\'s palace operations and serving as his primary advisor. This minifigure features the distinctive pale skin of his species, long head-tails (lekku), ornate robes appropriate for a palace official, and calculating expression. Released in Jabba\'s Palace sets from 2005 onward. Bib Fortuna represents corrupt bureaucracy and self-serving loyalty, a character willing to betray even his master for the right price. Essential for populating Jabba\'s court and recreating palace intrigue scenes. Collectors value this figure for the unique Twi\'lek design and his role as Jabba\'s right-hand man. The distinctive head-tails and pale coloring make Bib Fortuna instantly recognizable, essential for authentic Jabba\'s Palace displays showing the crime lord\'s administrative hierarchy.',
    de: 'Bib Fortuna ist Jabba the Hutts Twi\'lek-Majordomus und Stabschef, verwaltet die Palastoperationen des Verbrecherlords und dient als sein primärer Berater. Diese Minifigur zeigt die charakteristische blasse Haut seiner Spezies, lange Kopf-Tentakel (Lekku), kunstvolle Roben, die für einen Palastbeamten angemessen sind, und berechnenden Ausdruck. Sie wurde ab 2005 in Jabbas Palast-Sets veröffentlicht. Bib Fortuna repräsentiert korrupte Bürokratie und eigennützige Loyalität, ein Charakter, der bereit ist, sogar seinen Meister für den richtigen Preis zu verraten. Unverzichtbar für die Bevölkerung von Jabbas Hof und die Nachstellung von Palast-Intrigen-Szenen. Sammler schätzen diese Figur für das einzigartige Twi\'lek-Design und seine Rolle als Jabbas rechte Hand. Die charakteristischen Kopf-Tentakel und blasse Färbung machen Bib Fortuna sofort erkennbar, unverzichtbar für authentische Jabbas Palast-Displays, die die administrative Hierarchie des Verbrecherlords zeigen.',
    fr: 'Bib Fortuna est le majordome Twi\'lek de Jabba le Hutt et chef de cabinet, gérant les opérations du palais du seigneur du crime et servant de conseiller principal. Cette minifigurine présente la peau pâle distinctive de son espèce, de longues queues de tête (lekku), des robes ornées appropriées pour un officiel de palais, et une expression calculatrice. Sortie dans des sets du Palais de Jabba à partir de 2005. Bib Fortuna représente la bureaucratie corrompue et la loyauté intéressée, un personnage prêt à trahir même son maître pour le bon prix. Essentiel pour peupler la cour de Jabba et recréer des scènes d\'intrigue de palais. Les collectionneurs apprécient cette figurine pour le design Twi\'lek unique et son rôle de bras droit de Jabba. Les queues de tête distinctives et la coloration pâle rendent Bib Fortuna instantanément reconnaissable, essentiel pour des affichages authentiques du Palais de Jabba montrant la hiérarchie administrative du seigneur du crime.',
    es: 'Bib Fortuna es el mayordomo Twi\'lek de Jabba the Hutt y jefe de personal, gestionando las operaciones del palacio del señor del crimen y sirviendo como su asesor principal. Esta minifigura presenta la distintiva piel pálida de su especie, largas colas de cabeza (lekku), túnicas ornamentadas apropiadas para un oficial de palacio, y expresión calculadora. Lanzado en sets del Palacio de Jabba desde 2005 en adelante. Bib Fortuna representa burocracia corrupta y lealtad interesada, un personaje dispuesto a traicionar incluso a su maestro por el precio correcto. Esencial para poblar la corte de Jabba y recrear escenas de intriga de palacio. Los coleccionistas valoran esta figura por el diseño Twi\'lek único y su papel como mano derecha de Jabba. Las distintivas colas de cabeza y coloración pálida hacen que Bib Fortuna sea instantáneamente reconocible, esencial para exhibiciones auténticas del Palacio de Jabba mostrando la jerarquía administrativa del señor del crimen.'
  },
  {
    no: 'sw0558',
    name: 'Gamorrean Guard',
    en: 'Gamorrean Guards are the brutish pig-like warriors who serve as Jabba the Hutt\'s palace enforcers and bodyguards. This minifigure features green skin, porcine facial features with tusks, primitive armor and weapons including axes or vibro-blades, and stocky muscular build. Released in Jabba\'s Palace sets from 2005 onward. Gamorrean Guards represent brute force security in Jabba\'s criminal organization, intimidating muscle hired for their strength and loyalty. Essential for populating Jabba\'s palace with appropriate security forces and recreating scenes of palace combat. Collectors often army-build these guards to show the scale of Jabba\'s security detail. The distinctive green pig-warrior design makes Gamorrean Guards memorable alien figures that add menace and atmosphere to palace displays, showing the diverse species employed by the Hutt crime syndicate.',
    de: 'Gamorreaner-Wachen sind die brutalen schweineähnlichen Krieger, die als Jabbas Palast-Vollstrecker und Leibwächter dienen. Diese Minifigur zeigt grüne Haut, schweineartige Gesichtszüge mit Stoßzähnen, primitive Rüstung und Waffen einschließlich Äxten oder Vibro-Klingen und stämmigen muskulösen Bau. Sie wurde ab 2005 in Jabbas Palast-Sets veröffentlicht. Gamorreaner-Wachen repräsentieren rohe Gewalt-Sicherheit in Jabbas krimineller Organisation, einschüchternde Muskelkraft, angeheuert für ihre Stärke und Loyalität. Unverzichtbar für die Bevölkerung von Jabbas Palast mit angemessenen Sicherheitskräften und die Nachstellung von Palast-Kampfszenen. Sammler bauen diese Wachen oft in Armeen auf, um den Umfang von Jabbas Sicherheitsdetail zu zeigen. Das charakteristische grüne Schwein-Krieger-Design macht Gamorreaner-Wachen zu denkwürdigen Alien-Figuren, die Bedrohung und Atmosphäre zu Palast-Displays hinzufügen und die vielfältigen Spezies zeigen, die vom Hutt-Verbrechersyndikat beschäftigt werden.',
    fr: 'Les Gardes Gamorréens sont les guerriers brutaux ressemblant à des cochons qui servent d\'exécuteurs et de gardes du corps du palais de Jabba le Hutt. Cette minifigurine présente une peau verte, des traits faciaux porcins avec des défenses, une armure et des armes primitives incluant des haches ou des vibro-lames, et une construction musculaire trapue. Sortie dans des sets du Palais de Jabba à partir de 2005. Les Gardes Gamorréens représentent la sécurité par force brute dans l\'organisation criminelle de Jabba, des muscles intimidants embauchés pour leur force et leur loyauté. Essentiels pour peupler le palais de Jabba avec des forces de sécurité appropriées et recréer des scènes de combat de palais. Les collectionneurs construisent souvent des armées de ces gardes pour montrer l\'échelle du détail de sécurité de Jabba. Le design distinctif de guerrier cochon vert fait des Gardes Gamorréens des figurines aliens mémorables qui ajoutent de la menace et de l\'atmosphère aux affichages de palais, montrant les espèces diverses employées par le syndicat du crime Hutt.',
    es: 'Los Guardias Gamorreanos son los brutales guerreros parecidos a cerdos que sirven como ejecutores de palacio y guardaespaldas de Jabba the Hutt. Esta minifigura presenta piel verde, rasgos faciales porcinos con colmillos, armadura y armas primitivas incluyendo hachas o vibro-espadas, y constitución musculosa robusta. Lanzado en sets del Palacio de Jabba desde 2005 en adelante. Los Guardias Gamorreanos representan seguridad de fuerza bruta en la organización criminal de Jabba, músculo intimidante contratado por su fuerza y lealtad. Esencial para poblar el palacio de Jabba con fuerzas de seguridad apropiadas y recrear escenas de combate de palacio. Los coleccionistas a menudo construyen ejércitos de estos guardias para mostrar la escala del detalle de seguridad de Jabba. El distintivo diseño de guerrero cerdo verde hace que los Guardias Gamorreanos sean figuras alienígenas memorables que añaden amenaza y atmósfera a exhibiciones de palacio, mostrando las diversas especies empleadas por el sindicato del crimen Hutt.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 441-450 (sw0549-sw0558) - 10 minifigs...\n');

  for (const m of batch) {
    await prisma.minifigCatalog.upsert({
      where: { minifigure_no: m.no },
      update: {
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      },
      create: {
        minifigure_no: m.no,
        name: m.name,
        category_id: 1,
        category_name: 'Star Wars',
        search_name: m.name.toLowerCase(),
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`  ✅ ${m.no}: ${m.name}`);
  }

  console.log('\n✨ Batch 441-450 complete: 10 minifigs (40 descriptions)');
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
