import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0279',
    name: 'Rebel Commando',
    en: 'The Rebel Commando LEGO minifigure captures the elite strike forces who led the assault on Endor\'s shield generator bunker, featuring distinctive camouflage patterns, tactical gear, and the rugged appearance of soldiers trained for high-risk special operations. This minifigure showcases detailed printing showing forest camouflage attire and combat equipment, representing the specialized troops who spearheaded dangerous missions behind enemy lines throughout the Galactic Civil War. Armed with blaster rifles and explosives, these commandos demonstrated exceptional courage and skill during the Battle of Endor, fighting alongside Ewoks to disable the Death Star\'s protective shield. Released in sets from 2009 onwards including Endor bunker assault scenarios and speeder bike chase builds, this minifigure appeals to collectors creating Rebel ground force displays, highly collectible due to its unique camouflage design distinguishing it from standard orange-suited Rebel pilots, its connection to Return of the Jedi\'s pivotal ground battle, and its representation of the Rebellion\'s diverse military capabilities beyond starfighter combat.',
    de: 'Die LEGO-Minifigur des Rebellenkommandos fängt die Elite-Stoßtruppen ein, die den Angriff auf den Endor-Schildgenerator-Bunker anführten, mit markanten Tarnmustern, taktischer Ausrüstung und dem robusten Aussehen von Soldaten, die für risikoreiche Spezialoperationen ausgebildet wurden. Diese Minifigur zeigt detaillierte Bedruckung, die Waldtarnungskleidung und Kampfausrüstung zeigt, die die spezialisierten Truppen repräsentiert, die gefährliche Missionen hinter feindlichen Linien während des gesamten Galaktischen Bürgerkriegs anführten. Bewaffnet mit Blastergewehren und Sprengstoff demonstrierten diese Kommandos außergewöhnlichen Mut und Geschick während der Schlacht von Endor und kämpften an der Seite von Ewoks, um den Schutzschild des Todessterns zu deaktivieren. In Sets ab 2009 veröffentlicht, einschließlich Endor-Bunker-Angriffs-Szenarien und Speeder-Bike-Verfolgungsjagd-Builds, spricht diese Minifigur Sammler an, die Rebellenbodentruppen-Displays erstellen, hochgradig sammelwürdig aufgrund ihres einzigartigen Tarnungsdesigns, das sie von Standard-orangefarbenen Rebellenpiloten unterscheidet, ihrer Verbindung zur entscheidenden Bodenschlacht von Die Rückkehr der Jedi-Ritter und ihrer Darstellung der vielfältigen militärischen Fähigkeiten der Rebellion jenseits des Sternenjäger-Kampfes.',
    fr: 'La minifigurine LEGO du Commando Rebelle capture les forces de frappe d\'élite qui ont mené l\'assaut sur le bunker du générateur de bouclier d\'Endor, avec des motifs de camouflage distinctifs, de l\'équipement tactique, et l\'apparence robuste de soldats entraînés pour des opérations spéciales à haut risque. Cette minifigurine présente une impression détaillée montrant une tenue de camouflage forestier et de l\'équipement de combat, représentant les troupes spécialisées qui ont mené des missions dangereuses derrière les lignes ennemies tout au long de la Guerre Civile Galactique. Armés de fusils blaster et d\'explosifs, ces commandos ont démontré un courage et des compétences exceptionnels pendant la Bataille d\'Endor, combattant aux côtés des Ewoks pour désactiver le bouclier protecteur de l\'Étoile de la Mort. Sortie dans des sets à partir de 2009 incluant des scénarios d\'assaut de bunker d\'Endor et des constructions de poursuite en speeder bike, cette minifigurine plaît aux collectionneurs créant des présentations de forces terrestres Rebelles, hautement collectionnable en raison de son design de camouflage unique la distinguant des pilotes Rebelles en combinaison orange standard, sa connexion à la bataille terrestre pivot du Retour du Jedi, et sa représentation des capacités militaires diverses de la Rébellion au-delà du combat de chasseurs stellaires.',
    es: 'La minifigura LEGO del Comando Rebelde captura a las fuerzas de ataque de élite que lideraron el asalto al búnker del generador de escudo de Endor, presentando distintivos patrones de camuflaje, equipo táctico, y la apariencia robusta de soldados entrenados para operaciones especiales de alto riesgo. Esta minifigura muestra impresión detallada mostrando atuendo de camuflaje forestal y equipo de combate, representando a las tropas especializadas que encabezaron misiones peligrosas detrás de líneas enemigas durante toda la Guerra Civil Galáctica. Armados con rifles bláster y explosivos, estos comandos demostraron excepcional coraje y habilidad durante la Batalla de Endor, luchando junto a Ewoks para desactivar el escudo protector de la Estrella de la Muerte. Lanzada en sets desde 2009 incluyendo escenarios de asalto al búnker de Endor y construcciones de persecución en speeder bike, esta minifigura atrae a coleccionistas creando exhibiciones de fuerzas terrestres Rebeldes, altamente coleccionable debido a su único diseño de camuflaje distinguiéndola de pilotos Rebeldes en traje naranja estándar, su conexión con la batalla terrestre fundamental de El Retorno del Jedi, y su representación de las diversas capacidades militares de la Rebelión más allá del combate de cazas estelares.'
  },
  {
    no: 'sw0280',
    name: 'Rebel Mechanic',
    en: 'The Rebel Mechanic LEGO minifigure depicts the essential technical personnel who kept the Alliance fleet operational with their distinctive orange jumpsuits, tool vests, and the grease-stained appearance of engineers working tirelessly to maintain starfighters and capital ships. This minifigure features detailed printing showing maintenance gear and utility equipment, representing the unsung heroes who performed repairs under constant pressure as the Rebellion fought with limited resources against the Empire\'s vast war machine. Working in hangars and repair bays across Rebel bases from Yavin to Hoth to D\'Qar, these mechanics transformed salvaged and donated ships into combat-worthy vessels through ingenuity and dedication. Released in sets from 2009 onwards appearing in hangar bay builds and maintenance scenarios, this minifigure appeals to collectors creating support crew displays, sought after due to its representation of the Rebellion\'s resourceful nature, its connection to iconic locations like the Yavin IV hangar where X-wings prepared for the Death Star assault, and its embodiment of the everyday heroes whose technical expertise proved as crucial as pilot skill in defeating the Empire.',
    de: 'Die LEGO-Minifigur des Rebellenmechanikers zeigt das essentielle technische Personal, das die Allianzflotte mit ihren markanten orangefarbenen Overalls, Werkzeugwesten und dem ölverschmierten Aussehen von Ingenieuren betriebsbereit hielt, die unermüdlich arbeiteten, um Sternenjäger und Hauptschiffe zu warten. Diese Minifigur verfügt über detaillierte Bedruckung, die Wartungsausrüstung und Werkzeug zeigt, die die unbesungenen Helden repräsentiert, die Reparaturen unter ständigem Druck durchführten, während die Rebellion mit begrenzten Ressourcen gegen die riesige Kriegsmaschinerie des Imperiums kämpfte. In Hangars und Reparaturbuchten über Rebellenbasen von Yavin bis Hoth bis D\'Qar arbeitend, verwandelten diese Mechaniker geborgene und gespendete Schiffe durch Einfallsreichtum und Hingabe in kampftaugliche Schiffe. In Sets ab 2009 veröffentlicht und in Hangar-Bucht-Builds und Wartungsszenarien erscheinend, spricht diese Minifigur Sammler an, die Support-Crew-Displays erstellen, begehrt aufgrund ihrer Darstellung der einfallsreichen Natur der Rebellion, ihrer Verbindung zu ikonischen Orten wie dem Yavin IV-Hangar, wo X-Flügler sich auf den Todesstern-Angriff vorbereiteten, und ihrer Verkörperung der alltäglichen Helden, deren technische Expertise sich als ebenso entscheidend erwies wie Pilotengeschick bei der Niederlage des Imperiums.',
    fr: 'La minifigurine LEGO du Mécanicien Rebelle dépeint le personnel technique essentiel qui maintenait la flotte de l\'Alliance opérationnelle avec leurs combinaisons orange distinctives, gilets à outils, et l\'apparence tachée de graisse d\'ingénieurs travaillant sans relâche pour maintenir les chasseurs stellaires et les vaisseaux capitaux. Cette minifigurine présente une impression détaillée montrant de l\'équipement de maintenance et du matériel utilitaire, représentant les héros méconnus qui effectuaient des réparations sous pression constante alors que la Rébellion combattait avec des ressources limitées contre la vaste machine de guerre de l\'Empire. Travaillant dans des hangars et des baies de réparation à travers les bases Rebelles de Yavin à Hoth à D\'Qar, ces mécaniciens transformaient des vaisseaux récupérés et donnés en navires dignes du combat grâce à l\'ingéniosité et au dévouement. Sortie dans des sets à partir de 2009 apparaissant dans les constructions de baie de hangar et les scénarios de maintenance, cette minifigurine plaît aux collectionneurs créant des présentations d\'équipages de soutien, recherchée en raison de sa représentation de la nature ingénieuse de la Rébellion, sa connexion à des lieux emblématiques comme le hangar de Yavin IV où les X-wings se préparaient pour l\'assaut de l\'Étoile de la Mort, et son incarnation des héros du quotidien dont l\'expertise technique s\'est avérée aussi cruciale que la compétence des pilotes pour vaincre l\'Empire.',
    es: 'La minifigura LEGO del Mecánico Rebelde representa al personal técnico esencial que mantuvo operativa la flota de la Alianza con sus distintivos monos naranjas, chalecos de herramientas, y la apariencia manchada de grasa de ingenieros trabajando incansablemente para mantener cazas estelares y naves capitales. Esta minifigura presenta impresión detallada mostrando equipo de mantenimiento y equipamiento utilitario, representando a los héroes no reconocidos que realizaron reparaciones bajo presión constante mientras la Rebelión luchaba con recursos limitados contra la vasta máquina de guerra del Imperio. Trabajando en hangares y bahías de reparación a través de bases Rebeldes desde Yavin hasta Hoth hasta D\'Qar, estos mecánicos transformaron naves rescatadas y donadas en vehículos dignos de combate mediante ingenio y dedicación. Lanzada en sets desde 2009 apareciendo en construcciones de bahía de hangar y escenarios de mantenimiento, esta minifigura atrae a coleccionistas creando exhibiciones de tripulación de apoyo, buscada debido a su representación de la naturaleza ingeniosa de la Rebelión, su conexión con ubicaciones icónicas como el hangar Yavin IV donde X-wings se prepararon para el asalto a la Estrella de la Muerte, y su encarnación de los héroes cotidianos cuya experiencia técnica resultó tan crucial como la habilidad del piloto en derrotar al Imperio.'
  },
  {
    no: 'sw0281',
    name: 'Hoth Rebel Trooper',
    en: 'The Hoth Rebel Trooper LEGO minifigure captures the cold-weather soldiers defending Echo Base with their distinctive white and tan insulated uniforms, cold-weather gear, and the determined appearance of troops fighting a desperate last stand against Imperial invasion. This minifigure features detailed printing showing thermal protection layers and combat equipment designed for Hoth\'s frozen environment, representing the brave defenders who bought precious evacuation time during the Empire\'s assault on the ice planet. Armed with blaster rifles and manning defensive positions across the trenches and corridors of Echo Base, these troopers demonstrated unwavering courage even as AT-ATs breached their shields. Released in sets from 2009 onwards including Hoth battle scenarios and Echo Base defense builds, this minifigure became essential for collectors recreating The Empire Strikes Back\'s opening battle, highly sought after due to its unique cold-weather design, its connection to one of Star Wars\' most iconic ground battles, and its representation of the Rebellion\'s sacrifice and resilience when facing overwhelming Imperial military superiority.',
    de: 'Die LEGO-Minifigur des Hoth-Rebellensoldaten fängt die Kältewetter-Soldaten ein, die Echo Base mit ihren markanten weißen und beigen isolierten Uniformen, Kältewetterausrüstung und dem entschlossenen Aussehen von Truppen verteidigen, die einen verzweifelten letzten Widerstand gegen die imperiale Invasion führen. Diese Minifigur verfügt über detaillierte Bedruckung, die thermische Schutzschichten und Kampfausrüstung zeigt, die für Hoths gefrorene Umgebung entwickelt wurde, die die tapferen Verteidiger repräsentiert, die wertvolle Evakuierungszeit während des Angriffs des Imperiums auf den Eisplaneten erkauften. Bewaffnet mit Blastergewehren und Verteidigungspositionen in den Gräben und Korridoren von Echo Base besetzend, demonstrierten diese Soldaten unerschütterlichen Mut, selbst als AT-ATs ihre Schilde durchbrachen. In Sets ab 2009 veröffentlicht, einschließlich Hoth-Kampfszenarien und Echo Base-Verteidigungs-Builds, wurde diese Minifigur für Sammler, die die Eröffnungsschlacht von Das Imperium schlägt zurück nachstellen, unverzichtbar, hochgradig begehrt aufgrund ihres einzigartigen Kältewetter-Designs, ihrer Verbindung zu einer von Star Wars\' ikonischsten Bodenschlachten und ihrer Darstellung des Opfers und der Widerstandsfähigkeit der Rebellion, wenn sie überwältigender imperialer militärischer Überlegenheit gegenüberstand.',
    fr: 'La minifigurine LEGO du Soldat Rebelle de Hoth capture les soldats par temps froid défendant la Base Echo avec leurs uniformes isolés blanc et beige distinctifs, équipement par temps froid, et l\'apparence déterminée de troupes menant un dernier combat désespéré contre l\'invasion Impériale. Cette minifigurine présente une impression détaillée montrant des couches de protection thermique et de l\'équipement de combat conçu pour l\'environnement gelé de Hoth, représentant les braves défenseurs qui ont gagné un temps d\'évacuation précieux pendant l\'assaut de l\'Empire sur la planète de glace. Armés de fusils blaster et occupant des positions défensives à travers les tranchées et couloirs de la Base Echo, ces soldats ont démontré un courage inébranlable même alors que les AT-AT perçaient leurs boucliers. Sortie dans des sets à partir de 2009 incluant des scénarios de bataille de Hoth et des constructions de défense de la Base Echo, cette minifigurine est devenue essentielle pour les collectionneurs recréant la bataille d\'ouverture de L\'Empire Contre-Attaque, très recherchée en raison de son design unique par temps froid, sa connexion à l\'une des batailles terrestres les plus emblématiques de Star Wars, et sa représentation du sacrifice et de la résilience de la Rébellion face à la supériorité militaire Impériale écrasante.',
    es: 'La minifigura LEGO del Soldado Rebelde de Hoth captura a los soldados de clima frío defendiendo la Base Echo con sus distintivos uniformes aislados blancos y beige, equipo de clima frío, y la apariencia determinada de tropas librando una última resistencia desesperada contra la invasión Imperial. Esta minifigura presenta impresión detallada mostrando capas de protección térmica y equipo de combate diseñado para el ambiente congelado de Hoth, representando a los valientes defensores que compraron precioso tiempo de evacuación durante el asalto del Imperio al planeta helado. Armados con rifles bláster y ocupando posiciones defensivas a través de las trincheras y corredores de la Base Echo, estos soldados demostraron coraje inquebrantable incluso cuando AT-ATs penetraron sus escudos. Lanzada en sets desde 2009 incluyendo escenarios de batalla de Hoth y construcciones de defensa de Base Echo, esta minifigura se volvió esencial para coleccionistas recreando la batalla de apertura de El Imperio Contraataca, muy buscada debido a su único diseño de clima frío, su conexión con una de las batallas terrestres más icónicas de Star Wars, y su representación del sacrificio y resistencia de la Rebelión al enfrentar abrumadora superioridad militar Imperial.'
  },
  {
    no: 'sw0282',
    name: 'Snowtrooper',
    en: 'The Snowtrooper LEGO minifigure depicts the Empire\'s elite cold-weather assault troops with their distinctive white armor, insulated fabric panels, and specialized helmets designed for combat in frozen environments like Hoth. This minifigure features detailed printing showing the unique armor configuration and thermal gear, representing the specialized Imperial forces trained to operate in extreme climates where standard Stormtroopers would fail. Armed with E-11 blasters and equipped with heating systems and terrain-adapted equipment, Snowtroopers spearheaded the ground assault on Echo Base during the Battle of Hoth. Released in numerous sets from 2003 onwards appearing in AT-AT crews and Hoth battle scenarios, this minifigure became one of the most collectible Imperial trooper variants, highly sought after by army builders due to its distinctive appearance combining white armor with gray fabric elements, its connection to The Empire Strikes Back\'s memorable opening battle, and its representation of the Empire\'s vast military resources that could field specialized units for every combat environment across the galaxy.',
    de: 'Die LEGO-Minifigur des Schneetruppers zeigt die Elite-Kältewetter-Angriffstruppen des Imperiums mit ihrer markanten weißen Rüstung, isolierten Stoffpaneelen und spezialisierten Helmen, die für den Kampf in gefrorenen Umgebungen wie Hoth entwickelt wurden. Diese Minifigur verfügt über detaillierte Bedruckung, die die einzigartige Rüstungskonfiguration und thermische Ausrüstung zeigt, die die spezialisierten imperialen Streitkräfte repräsentiert, die für den Einsatz in extremen Klimazonen ausgebildet wurden, wo Standard-Sturmtruppen versagen würden. Bewaffnet mit E-11-Blastern und ausgestattet mit Heizsystemen und geländeangepasster Ausrüstung führten Schneetrupper den Bodenangriff auf Echo Base während der Schlacht von Hoth an. In zahlreichen Sets ab 2003 veröffentlicht und in AT-AT-Besatzungen und Hoth-Kampfszenarien erscheinend, wurde diese Minifigur zu einer der sammelwürdigsten imperialen Truppen-Varianten, hochgradig begehrt bei Armee-Bauern aufgrund ihres markanten Aussehens, das weiße Rüstung mit grauen Stoffelementen kombiniert, ihrer Verbindung zur unvergesslichen Eröffnungsschlacht von Das Imperium schlägt zurück und ihrer Darstellung der riesigen militärischen Ressourcen des Imperiums, das spezialisierte Einheiten für jede Kampfumgebung in der gesamten Galaxie aufstellen konnte.',
    fr: 'La minifigurine LEGO du Snowtrooper dépeint les troupes d\'assaut d\'élite par temps froid de l\'Empire avec leur armure blanche distinctive, panneaux de tissu isolés, et casques spécialisés conçus pour le combat dans des environnements gelés comme Hoth. Cette minifigurine présente une impression détaillée montrant la configuration d\'armure unique et l\'équipement thermique, représentant les forces Impériales spécialisées formées pour opérer dans des climats extrêmes où les Stormtroopers standards échoueraient. Armés de blasters E-11 et équipés de systèmes de chauffage et d\'équipement adapté au terrain, les Snowtroopers ont mené l\'assaut terrestre sur la Base Echo pendant la Bataille de Hoth. Sortie dans de nombreux sets à partir de 2003 apparaissant dans les équipages d\'AT-AT et les scénarios de bataille de Hoth, cette minifigurine est devenue l\'une des variantes de soldats Impériaux les plus collectionnables, très recherchée par les constructeurs d\'armées en raison de son apparence distinctive combinant armure blanche avec éléments de tissu gris, sa connexion à la bataille d\'ouverture mémorable de L\'Empire Contre-Attaque, et sa représentation des vastes ressources militaires de l\'Empire qui pouvaient déployer des unités spécialisées pour chaque environnement de combat à travers la galaxie.',
    es: 'La minifigura LEGO del Snowtrooper representa a las tropas de asalto de élite de clima frío del Imperio con su distintiva armadura blanca, paneles de tela aislados, y cascos especializados diseñados para combate en ambientes congelados como Hoth. Esta minifigura presenta impresión detallada mostrando la única configuración de armadura y equipo térmico, representando a las fuerzas Imperiales especializadas entrenadas para operar en climas extremos donde Soldados de Asalto estándar fallarían. Armados con blásters E-11 y equipados con sistemas de calefacción y equipo adaptado al terreno, los Snowtroopers encabezaron el asalto terrestre a la Base Echo durante la Batalla de Hoth. Lanzada en numerosos sets desde 2003 apareciendo en tripulaciones AT-AT y escenarios de batalla de Hoth, esta minifigura se convirtió en una de las variantes de soldado Imperial más coleccionables, muy buscada por constructores de ejércitos debido a su apariencia distintiva combinando armadura blanca con elementos de tela gris, su conexión con la memorable batalla de apertura de El Imperio Contraataca, y su representación de los vastos recursos militares del Imperio que podía desplegar unidades especializadas para cada ambiente de combate a través de la galaxia.'
  },
  {
    no: 'sw0283',
    name: 'AT-AT Driver',
    en: 'The AT-AT Driver LEGO minifigure captures the specialized pilots who operated the Empire\'s massive All Terrain Armored Transport walkers with their distinctive light gray uniforms, reinforced helmets with blast shields, and the elite appearance marking them as master vehicle operators. This minifigure features detailed printing showing the unique armor configuration and life-support systems, representing the highly trained Imperial forces who controlled these walking fortresses during ground assaults like the Battle of Hoth. Operating from elevated cockpits requiring specialized training in walker locomotion and heavy weapons systems, AT-AT drivers became symbols of Imperial ground supremacy. Released in sets from 2007 onwards appearing in AT-AT cockpit builds and Hoth assault scenarios, this minifigure appeals to collectors completing Imperial walker crews, highly collectible due to its unique light gray coloring distinguishing it from other Imperial pilots, its association with one of Star Wars\' most iconic vehicles, and its representation of the Empire\'s technological dominance demonstrated through towering war machines that struck fear across Rebel forces throughout the galaxy.',
    de: 'Die LEGO-Minifigur des AT-AT-Piloten fängt die spezialisierten Piloten ein, die die massiven All Terrain Armored Transport-Läufer des Imperiums mit ihren markanten hellgrauen Uniformen, verstärkten Helmen mit Explosionsschutzschilden und dem Elite-Aussehen bedienten, das sie als Meister-Fahrzeugführer kennzeichnete. Diese Minifigur verfügt über detaillierte Bedruckung, die die einzigartige Rüstungskonfiguration und Lebenserhaltungssysteme zeigt, die die hochqualifizierten imperialen Streitkräfte repräsentiert, die diese gehenden Festungen während Bodenangriffen wie der Schlacht von Hoth kontrollierten. Von erhöhten Cockpits aus operierend, die spezialisiertes Training in Läuferfortbewegung und schweren Waffensystemen erforderten, wurden AT-AT-Piloten zu Symbolen imperialer Bodenüberlegenheit. In Sets ab 2007 veröffentlicht und in AT-AT-Cockpit-Builds und Hoth-Angriffs-Szenarien erscheinend, spricht diese Minifigur Sammler an, die imperiale Läufer-Besatzungen vervollständigen, hochgradig sammelwürdig aufgrund ihrer einzigartigen hellgrauen Färbung, die sie von anderen imperialen Piloten unterscheidet, ihrer Assoziation mit einem von Star Wars\' ikonischsten Fahrzeugen und ihrer Darstellung der technologischen Dominanz des Imperiums, die durch aufragende Kriegsmaschinen demonstriert wurde, die Angst über Rebellenstreitkräfte in der gesamten Galaxie verbreiteten.',
    fr: 'La minifigurine LEGO du Pilote d\'AT-AT capture les pilotes spécialisés qui opéraient les marcheurs massifs All Terrain Armored Transport de l\'Empire avec leurs uniformes gris clair distinctifs, casques renforcés avec boucliers anti-explosion, et l\'apparence d\'élite les marquant comme maîtres opérateurs de véhicules. Cette minifigurine présente une impression détaillée montrant la configuration d\'armure unique et les systèmes de survie, représentant les forces Impériales hautement formées qui contrôlaient ces forteresses ambulantes pendant les assauts terrestres comme la Bataille de Hoth. Opérant depuis des cockpits élevés nécessitant une formation spécialisée en locomotion de marcheur et systèmes d\'armes lourdes, les pilotes d\'AT-AT sont devenus des symboles de suprématie terrestre Impériale. Sortie dans des sets à partir de 2007 apparaissant dans les constructions de cockpit d\'AT-AT et les scénarios d\'assaut de Hoth, cette minifigurine plaît aux collectionneurs complétant les équipages de marcheurs Impériaux, hautement collectionnable en raison de sa coloration gris clair unique la distinguant des autres pilotes Impériaux, son association avec l\'un des véhicules les plus emblématiques de Star Wars, et sa représentation de la dominance technologique de l\'Empire démontrée à travers des machines de guerre imposantes qui inspiraient la peur à travers les forces Rebelles dans toute la galaxie.',
    es: 'La minifigura LEGO del Conductor de AT-AT captura a los pilotos especializados que operaban los masivos caminantes All Terrain Armored Transport del Imperio con sus distintivos uniformes gris claro, cascos reforzados con escudos anti-explosión, y la apariencia de élite marcándolos como maestros operadores de vehículos. Esta minifigura presenta impresión detallada mostrando la única configuración de armadura y sistemas de soporte vital, representando a las fuerzas Imperiales altamente entrenadas que controlaban estas fortalezas caminantes durante asaltos terrestres como la Batalla de Hoth. Operando desde cabinas elevadas requiriendo entrenamiento especializado en locomoción de caminante y sistemas de armas pesadas, los conductores AT-AT se convirtieron en símbolos de supremacía terrestre Imperial. Lanzada en sets desde 2007 apareciendo en construcciones de cabina AT-AT y escenarios de asalto de Hoth, esta minifigura atrae a coleccionistas completando tripulaciones de caminantes Imperiales, altamente coleccionable debido a su única coloración gris claro distinguiéndola de otros pilotos Imperiales, su asociación con uno de los vehículos más icónicos de Star Wars, y su representación del dominio tecnológico del Imperio demostrado mediante máquinas de guerra imponentes que infundieron miedo a través de fuerzas Rebeldes por toda la galaxia.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 171-175 (sw0279-sw0283)...\n');

  for (const m of batch) {
    await prisma.minifigCatalog.upsert({
      where: { minifigure_no: m.no },
      update: {
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      },
      create: {
        minifigure_no: m.no,
        name: m.name,
        category_id: 1,
        category_name: 'Star Wars',
        search_name: m.name.toLowerCase(),
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`  ✅ ${m.no}: ${m.name}`);
  }

  console.log('\n✨ Batch 171-175 complete: 5 minifigs (20 descriptions)');
  await prisma.$disconnect();
}

saveBatch().catch(console.error);