import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0309',
    name: 'Darth Vader (No Cape)',
    en: 'Darth Vader\'s No Cape LEGO minifigure depicts the Dark Lord in his damaged state after the throne room battle, revealing the life-support systems and vulnerable humanity beneath the intimidating armor. This variant captures the pivotal moment when Vader\'s redemption became visible, his protective outer layers stripped away both literally and metaphorically. As Luke removed his father\'s helmet in Return of the Jedi\'s most emotional scene, this capeless Vader represented the dying Anakin Skywalker reclaiming his identity. Released in sets from 2008 onwards, this minifigure appeals to collectors seeking complete Vader variants, valued for representing the character\'s most vulnerable and redemptive moment when he chose love over power and saved his son from the Emperor.',
    de: 'Die LEGO-Minifigur von Darth Vader ohne Umhang zeigt den Dunklen Lord in seinem beschädigten Zustand nach der Thronsaal-Schlacht und enthüllt die Lebenserhaltungssysteme und verletzliche Menschlichkeit unter der einschüchternden Rüstung. Diese Variante fängt den entscheidenden Moment ein, als Vaders Erlösung sichtbar wurde, seine schützenden äußeren Schichten sowohl buchstäblich als auch metaphorisch abgestreift. Als Luke den Helm seines Vaters in Die Rückkehr der Jedi-Ritters emotionalster Szene entfernte, repräsentierte dieser Vader ohne Umhang den sterbenden Anakin Skywalker, der seine Identität zurückgewann. In Sets ab 2008 veröffentlicht, spricht diese Minifigur Sammler an, die vollständige Vader-Varianten suchen, geschätzt für die Darstellung des verletzlichsten und erlösendsten Moments des Charakters, als er Liebe über Macht wählte und seinen Sohn vor dem Imperator rettete.',
    fr: 'La minifigurine LEGO de Dark Vador sans Cape dépeint le Seigneur Sombre dans son état endommagé après la bataille de la salle du trône, révélant les systèmes de survie et l\'humanité vulnérable sous l\'armure intimidante. Cette variante capture le moment pivot où la rédemption de Vador est devenue visible, ses couches protectrices extérieures dépouillées à la fois littéralement et métaphoriquement. Alors que Luke retirait le casque de son père dans la scène la plus émotionnelle du Retour du Jedi, ce Vador sans cape représentait l\'Anakin Skywalker mourant récupérant son identité. Sortie dans des sets à partir de 2008, cette minifigurine plaît aux collectionneurs cherchant des variantes complètes de Vador, valorisée pour représenter le moment le plus vulnérable et rédempteur du personnage lorsqu\'il a choisi l\'amour plutôt que le pouvoir et a sauvé son fils de l\'Empereur.',
    es: 'La minifigura LEGO de Darth Vader sin Capa representa al Señor Oscuro en su estado dañado después de la batalla de la sala del trono, revelando los sistemas de soporte vital y humanidad vulnerable bajo la intimidante armadura. Esta variante captura el momento fundamental cuando la redención de Vader se hizo visible, sus capas protectoras externas despojadas tanto literal como metafóricamente. Cuando Luke retiró el casco de su padre en la escena más emotiva de El Retorno del Jedi, este Vader sin capa representó al moribundo Anakin Skywalker recuperando su identidad. Lanzada en sets desde 2008, esta minifigura atrae a coleccionistas buscando variantes completas de Vader, valorada por representar el momento más vulnerable y redentor del personaje cuando eligió amor sobre poder y salvó a su hijo del Emperador.'
  },
  {
    no: 'sw0310',
    name: 'Anakin Skywalker (Spirit)',
    en: 'Anakin Skywalker\'s Spirit LEGO minifigure captures the redeemed Jedi appearing as a Force ghost alongside Obi-Wan and Yoda, representing the saga\'s ultimate triumph of redemption over darkness. This translucent blue minifigure depicts Anakin restored to his pre-Vader self, the chosen one finally bringing balance to the Force through his sacrifice. As one of Return of the Jedi\'s most powerful images showing the three Jedi Masters united in death, this spirit form symbolized hope and the enduring nature of the Force. Released in sets from 2009 onwards, this minifigure became highly collectible among fans, valued for its unique translucent design and its representation of Star Wars\' central theme that even those who fall to darkness can find redemption through love and selfless sacrifice.',
    de: 'Die LEGO-Minifigur von Anakin Skywalkers Geist fängt den erlösten Jedi ein, der als Machtgeist neben Obi-Wan und Yoda erscheint und den ultimativen Triumph der Erlösung über die Dunkelheit der Saga repräsentiert. Diese durchscheinende blaue Minifigur zeigt Anakin, der zu seinem Selbst vor Vader wiederhergestellt wurde, der Auserwählte, der durch sein Opfer endlich Gleichgewicht in die Macht bringt. Als eines von Die Rückkehr der Jedi-Ritters kraftvollsten Bildern, das die drei Jedi-Meister im Tod vereint zeigt, symbolisierte diese Geistform Hoffnung und die dauerhafte Natur der Macht. In Sets ab 2009 veröffentlicht, wurde diese Minifigur unter Fans hochgradig sammelwürdig, geschätzt für ihr einzigartiges durchscheinendes Design und ihre Darstellung von Star Wars\' zentralem Thema, dass selbst diejenigen, die zur Dunkelheit fallen, durch Liebe und selbstloses Opfer Erlösung finden können.',
    fr: 'La minifigurine LEGO de l\'Esprit d\'Anakin Skywalker capture le Jedi racheté apparaissant comme un fantôme de la Force aux côtés d\'Obi-Wan et Yoda, représentant le triomphe ultime de la rédemption sur les ténèbres de la saga. Cette minifigurine bleue translucide dépeint Anakin restauré à son soi pré-Vador, l\'élu apportant finalement l\'équilibre à la Force par son sacrifice. En tant que l\'une des images les plus puissantes du Retour du Jedi montrant les trois Maîtres Jedi unis dans la mort, cette forme spirituelle symbolisait l\'espoir et la nature durable de la Force. Sortie dans des sets à partir de 2009, cette minifigurine est devenue hautement collectionnable parmi les fans, valorisée pour son design translucide unique et sa représentation du thème central de Star Wars que même ceux qui tombent dans les ténèbres peuvent trouver la rédemption par l\'amour et le sacrifice désintéressé.',
    es: 'La minifigura LEGO del Espíritu de Anakin Skywalker captura al Jedi redimido apareciendo como fantasma de la Fuerza junto a Obi-Wan y Yoda, representando el triunfo definitivo de la redención sobre la oscuridad de la saga. Esta minifigura azul translúcida representa a Anakin restaurado a su yo pre-Vader, el elegido finalmente trayendo balance a la Fuerza mediante su sacrificio. Como una de las imágenes más poderosas de El Retorno del Jedi mostrando a los tres Maestros Jedi unidos en la muerte, esta forma espiritual simbolizó esperanza y la naturaleza perdurable de la Fuerza. Lanzada en sets desde 2009, esta minifigura se volvió altamente coleccionable entre fans, valorada por su único diseño translúcido y su representación del tema central de Star Wars de que incluso aquellos que caen a la oscuridad pueden encontrar redención mediante amor y sacrificio desinteresado.'
  },
  {
    no: 'sw0311',
    name: 'Nien Nunb',
    en: 'Nien Nunb\'s LEGO minifigure captures the Sullustan pilot with his distinctive jowled features, large eyes, and the flight suit marking him as Lando\'s trusted co-pilot during the Battle of Endor. This minifigure represents the brave navigator who helped destroy the second Death Star by flying the Millennium Falcon through its superstructure, demonstrating exceptional skill in the most dangerous flying conditions. As one of many alien species fighting for the Rebellion, Nien Nunb embodied the diverse coalition united against the Empire. Released in sets from 2011 onwards appearing in Millennium Falcon cockpit scenarios, this minifigure appeals to collectors seeking complete Rebel pilot rosters, valued for its unique alien design and its representation of the unsung heroes whose piloting expertise proved crucial to the Rebellion\'s ultimate victory.',
    de: 'Die LEGO-Minifigur von Nien Nunb fängt den Sullustanischen Piloten mit seinen markanten Backenzügen, großen Augen und dem Fluganzug ein, der ihn als Landos vertrauenswürdigen Co-Piloten während der Schlacht von Endor kennzeichnet. Diese Minifigur repräsentiert den tapferen Navigator, der half, den zweiten Todesstern zu zerstören, indem er den Millennium Falken durch seine Superstruktur flog und außergewöhnliche Fähigkeiten in den gefährlichsten Flugbedingungen demonstrierte. Als eine von vielen außerirdischen Spezies, die für die Rebellion kämpften, verkörperte Nien Nunb die vielfältige Koalition, die gegen das Imperium vereint war. In Sets ab 2011 in Millennium Falken-Cockpit-Szenarien veröffentlicht, spricht diese Minifigur Sammler an, die vollständige Rebellenpiloten-Listen suchen, geschätzt für ihr einzigartiges außerirdisches Design und ihre Darstellung der unbesungenen Helden, deren Piloten-Expertise sich als entscheidend für den ultimativen Sieg der Rebellion erwies.',
    fr: 'La minifigurine LEGO de Nien Nunb capture le pilote Sullustain avec ses traits de bajoues distinctifs, ses grands yeux, et la combinaison de vol le marquant comme copilote de confiance de Lando pendant la Bataille d\'Endor. Cette minifigurine représente le navigateur courageux qui a aidé à détruire la seconde Étoile de la Mort en pilotant le Faucon Millenium à travers sa superstructure, démontrant une compétence exceptionnelle dans les conditions de vol les plus dangereuses. En tant que l\'une des nombreuses espèces aliens combattant pour la Rébellion, Nien Nunb incarnait la coalition diverse unie contre l\'Empire. Sortie dans des sets à partir de 2011 apparaissant dans des scénarios de cockpit du Faucon Millenium, cette minifigurine plaît aux collectionneurs cherchant des listes complètes de pilotes Rebelles, valorisée pour son design alien unique et sa représentation des héros méconnus dont l\'expertise de pilotage s\'est avérée cruciale pour la victoire ultime de la Rébellion.',
    es: 'La minifigura LEGO de Nien Nunb captura al piloto Sullustano con sus distintivos rasgos de papada, grandes ojos, y el traje de vuelo marcándolo como copiloto de confianza de Lando durante la Batalla de Endor. Esta minifigura representa al valiente navegante que ayudó a destruir la segunda Estrella de la Muerte volando el Halcón Milenario a través de su superestructura, demostrando excepcional habilidad en las condiciones de vuelo más peligrosas. Como una de muchas especies alienígenas luchando por la Rebelión, Nien Nunb encarnó la diversa coalición unida contra el Imperio. Lanzada en sets desde 2011 apareciendo en escenarios de cabina del Halcón Milenario, esta minifigura atrae a coleccionistas buscando listas completas de pilotos Rebeldes, valorada por su único diseño alienígena y su representación de los héroes no reconocidos cuya experiencia de pilotaje resultó crucial para la victoria definitiva de la Rebelión.'
  },
  {
    no: 'sw0312',
    name: 'B-Wing Pilot',
    en: 'The B-Wing Pilot LEGO minifigure depicts the specialized aviators operating the Rebellion\'s most powerful starfighter with their distinctive helmet design, flight suit, and the expert appearance marking them as elite bomber pilots. This minifigure represents the brave crews who flew the asymmetrical B-Wing into combat during the Battle of Endor, delivering devastating firepower against Imperial capital ships. Known for the B-Wing\'s complex rotating cockpit and exceptional weapons payload, these pilots required advanced training to master one of the Alliance\'s most sophisticated combat craft. Released in sets from 2000 onwards appearing in B-Wing starfighter builds, this minifigure appeals to collectors seeking diverse Rebel pilot types, valued for its unique helmet design and its representation of the specialized strike forces that gave the Rebellion tactical advantages against the Empire\'s numerical superiority.',
    de: 'Die LEGO-Minifigur des B-Flügel-Piloten zeigt die spezialisierten Flieger, die den mächtigsten Sternenjäger der Rebellion mit ihrem markanten Helmdesign, Fluganzug und dem Experten-Aussehen bedienten, das sie als Elite-Bomberpiloten kennzeichnet. Diese Minifigur repräsentiert die tapferen Besatzungen, die den asymmetrischen B-Flügel während der Schlacht von Endor in den Kampf flogen und verheerende Feuerkraft gegen imperiale Hauptschiffe lieferten. Bekannt für das komplexe rotierende Cockpit des B-Flügels und außergewöhnliche Waffenlast benötigten diese Piloten fortgeschrittenes Training, um eines der ausgeklügeltsten Kampfflugzeuge der Allianz zu meistern. In Sets ab 2000 in B-Flügel-Sternenjäger-Builds veröffentlicht, spricht diese Minifigur Sammler an, die vielfältige Rebellenpiloten-Typen suchen, geschätzt für ihr einzigartiges Helmdesign und ihre Darstellung der spezialisierten Stoßtruppen, die der Rebellion taktische Vorteile gegenüber der zahlenmäßigen Überlegenheit des Imperiums gaben.',
    fr: 'La minifigurine LEGO du Pilote de B-Wing dépeint les aviateurs spécialisés opérant le chasseur stellaire le plus puissant de la Rébellion avec leur design de casque distinctif, combinaison de vol, et l\'apparence experte les marquant comme pilotes bombardiers d\'élite. Cette minifigurine représente les équipages courageux qui ont piloté le B-Wing asymétrique au combat pendant la Bataille d\'Endor, délivrant une puissance de feu dévastatrice contre les vaisseaux capitaux Impériaux. Connus pour le cockpit rotatif complexe du B-Wing et la charge d\'armes exceptionnelle, ces pilotes nécessitaient une formation avancée pour maîtriser l\'un des engins de combat les plus sophistiqués de l\'Alliance. Sortie dans des sets à partir de 2000 apparaissant dans des constructions de chasseur stellaire B-Wing, cette minifigurine plaît aux collectionneurs cherchant divers types de pilotes Rebelles, valorisée pour son design de casque unique et sa représentation des forces de frappe spécialisées qui ont donné à la Rébellion des avantages tactiques contre la supériorité numérique de l\'Empire.',
    es: 'La minifigura LEGO del Piloto B-Wing representa a los aviadores especializados operando el caza estelar más poderoso de la Rebelión con su distintivo diseño de casco, traje de vuelo, y la apariencia experta marcándolos como pilotos bombarderos de élite. Esta minifigura representa a las valientes tripulaciones que volaron el asimétrico B-Wing al combate durante la Batalla de Endor, entregando devastadora potencia de fuego contra naves capitales Imperiales. Conocidos por la compleja cabina giratoria del B-Wing y excepcional carga de armas, estos pilotos requerían entrenamiento avanzado para dominar una de las naves de combate más sofisticadas de la Alianza. Lanzada en sets desde 2000 apareciendo en construcciones de caza estelar B-Wing, esta minifigura atrae a coleccionistas buscando diversos tipos de pilotos Rebeldes, valorada por su único diseño de casco y su representación de las fuerzas de ataque especializadas que dieron a la Rebelión ventajas tácticas contra la superioridad numérica del Imperio.'
  },
  {
    no: 'sw0313',
    name: 'A-Wing Pilot',
    en: 'The A-Wing Pilot LEGO minifigure captures the daring aviators flying the Rebellion\'s fastest interceptor with their distinctive green-trimmed helmet, flight suit, and the elite appearance marking them as the Alliance\'s most skilled dogfighters. This minifigure represents pilots like Arvel Crynyd who demonstrated exceptional bravery during the Battle of Endor, with one famously crashing into the Executor\'s bridge and causing the Super Star Destroyer\'s destruction. Operating the most maneuverable but fragile starfighter in the Rebel fleet required nerves of steel and lightning reflexes. Released in sets from 2000 onwards appearing in A-Wing starfighter builds, this minifigure became essential for collectors creating Rebel pilot diversity, highly valued for its unique green helmet design and its representation of the fearless interceptor pilots whose speed and skill challenged Imperial fighter superiority.',
    de: 'Die LEGO-Minifigur des A-Flügel-Piloten fängt die wagemutigen Flieger ein, die den schnellsten Abfangjäger der Rebellion mit ihrem markanten grün-gerandeten Helm, Fluganzug und dem Elite-Aussehen flogen, das sie als die geschicktesten Luftkämpfer der Allianz kennzeichnet. Diese Minifigur repräsentiert Piloten wie Arvel Crynyd, die während der Schlacht von Endor außergewöhnliche Tapferkeit demonstrierten, wobei einer berühmt dafür wurde, in die Brücke der Executor zu krachen und die Zerstörung des Super-Sternenzerstörers zu verursachen. Das Bedienen des wendigsten, aber zerbrechlichsten Sternenjägers in der Rebellenflotte erforderte Nerven aus Stahl und blitzschnelle Reflexe. In Sets ab 2000 in A-Flügel-Sternenjäger-Builds veröffentlicht, wurde diese Minifigur für Sammler, die Rebellenpiloten-Vielfalt erstellen, unverzichtbar, hochgeschätzt für ihr einzigartiges grünes Helmdesign und ihre Darstellung der furchtlosen Abfangjäger-Piloten, deren Geschwindigkeit und Geschick die Jäger-Überlegenheit des Imperiums herausforderten.',
    fr: 'La minifigurine LEGO du Pilote d\'A-Wing capture les aviateurs audacieux pilotant l\'intercepteur le plus rapide de la Rébellion avec leur casque distinctif à bordure verte, combinaison de vol, et l\'apparence d\'élite les marquant comme les combattants aériens les plus habiles de l\'Alliance. Cette minifigurine représente des pilotes comme Arvel Crynyd qui ont démontré un courage exceptionnel pendant la Bataille d\'Endor, l\'un s\'étant célèbrement écrasé sur le pont de l\'Executor et causant la destruction du Super Star Destroyer. Opérer le chasseur stellaire le plus maniable mais fragile de la flotte Rebelle nécessitait des nerfs d\'acier et des réflexes fulgurants. Sortie dans des sets à partir de 2000 apparaissant dans des constructions de chasseur stellaire A-Wing, cette minifigurine est devenue essentielle pour les collectionneurs créant la diversité des pilotes Rebelles, hautement valorisée pour son design de casque vert unique et sa représentation des pilotes intercepteurs intrépides dont la vitesse et la compétence défiaient la supériorité des chasseurs Impériaux.',
    es: 'La minifigura LEGO del Piloto A-Wing captura a los audaces aviadores volando el interceptor más rápido de la Rebelión con su distintivo casco ribeteado en verde, traje de vuelo, y la apariencia de élite marcándolos como los combatientes aéreos más hábiles de la Alianza. Esta minifigura representa a pilotos como Arvel Crynyd que demostraron excepcional valentía durante la Batalla de Endor, con uno estrellándose famosamente en el puente del Executor y causando la destrucción del Super Destructor Estelar. Operar el caza estelar más maniobrable pero frágil en la flota Rebelde requería nervios de acero y reflejos relámpago. Lanzada en sets desde 2000 apareciendo en construcciones de caza estelar A-Wing, esta minifigura se volvió esencial para coleccionistas creando diversidad de pilotos Rebeldes, altamente valorada por su único diseño de casco verde y su representación de los intrépidos pilotos interceptores cuya velocidad y habilidad desafiaron la superioridad de cazas Imperial.'
  },
  {
    no: 'sw0314',
    name: 'TIE Interceptor Pilot',
    en: 'The TIE Interceptor Pilot LEGO minifigure depicts the Empire\'s elite fighter aces with their distinctive flight suit markings, specialized helmet, and the superior appearance marking them as the Imperial Navy\'s most skilled pilots. This minifigure represents the cream of TIE pilot training who flew the advanced Interceptor variant during the Battle of Endor, boasting superior speed and firepower over standard TIE Fighters. Selected from the best performing TIE pilots, Interceptor crews embodied Imperial military excellence and aggressive tactics. Released in sets from 2000 onwards appearing in TIE Interceptor builds, this minifigure became essential for collectors creating Imperial fighter squadrons, highly valued for its unique red markings distinguishing it from standard TIE pilots and its representation of the Empire\'s most dangerous starfighter threat that even skilled Rebel pilots feared encountering.',
    de: 'Die LEGO-Minifigur des TIE-Abfangjäger-Piloten zeigt die Elite-Jäger-Asse des Imperiums mit ihren markanten Fluganzug-Markierungen, spezialisiertem Helm und dem überlegenen Aussehen, das sie als die geschicktesten Piloten der imperialen Marine kennzeichnet. Diese Minifigur repräsentiert die Crème de la Crème der TIE-Pilotenausbildung, die während der Schlacht von Endor die fortgeschrittene Abfangjäger-Variante flogen und überlegene Geschwindigkeit und Feuerkraft gegenüber Standard-TIE-Jägern aufwiesen. Aus den leistungsstärksten TIE-Piloten ausgewählt, verkörperten Abfangjäger-Besatzungen imperiale militärische Exzellenz und aggressive Taktiken. In Sets ab 2000 in TIE-Abfangjäger-Builds veröffentlicht, wurde diese Minifigur für Sammler, die imperiale Jäger-Staffeln erstellen, unverzichtbar, hochgeschätzt für ihre einzigartigen roten Markierungen, die sie von Standard-TIE-Piloten unterscheiden, und ihre Darstellung der gefährlichsten Sternenjäger-Bedrohung des Imperiums, die selbst geschickte Rebellenpiloten fürchteten zu begegnen.',
    fr: 'La minifigurine LEGO du Pilote d\'Intercepteur TIE dépeint les as de chasseurs d\'élite de l\'Empire avec leurs marques de combinaison de vol distinctives, casque spécialisé, et l\'apparence supérieure les marquant comme les pilotes les plus habiles de la Marine Impériale. Cette minifigurine représente la crème de la formation des pilotes TIE qui ont piloté la variante Intercepteur avancée pendant la Bataille d\'Endor, vantant une vitesse et une puissance de feu supérieures aux TIE Fighters standards. Sélectionnés parmi les pilotes TIE les plus performants, les équipages d\'Intercepteurs incarnaient l\'excellence militaire Impériale et les tactiques agressives. Sortie dans des sets à partir de 2000 apparaissant dans des constructions d\'Intercepteur TIE, cette minifigurine est devenue essentielle pour les collectionneurs créant des escadrons de chasseurs Impériaux, hautement valorisée pour ses marques rouges uniques la distinguant des pilotes TIE standards et sa représentation de la menace de chasseur stellaire la plus dangereuse de l\'Empire que même les pilotes Rebelles habiles craignaient de rencontrer.',
    es: 'La minifigura LEGO del Piloto Interceptor TIE representa a los ases de cazas de élite del Imperio con sus distintivas marcas de traje de vuelo, casco especializado, y la apariencia superior marcándolos como los pilotos más hábiles de la Marina Imperial. Esta minifigura representa a la crema del entrenamiento de pilotos TIE que volaron la variante Interceptor avanzada durante la Batalla de Endor, presumiendo velocidad y potencia de fuego superiores sobre los TIE Fighters estándar. Seleccionados de los pilotos TIE de mejor desempeño, las tripulaciones de Interceptor encarnaron la excelencia militar Imperial y tácticas agresivas. Lanzada en sets desde 2000 apareciendo en construcciones de Interceptor TIE, esta minifigura se volvió esencial para coleccionistas creando escuadrones de cazas Imperiales, altamente valorada por sus únicas marcas rojas distinguiéndola de pilotos TIE estándar y su representación de la amenaza de caza estelar más peligrosa del Imperio que incluso pilotos Rebeldes hábiles temían encontrar.'
  },
  {
    no: 'sw0315',
    name: 'Rebel Trooper (Endor)',
    en: 'The Rebel Trooper Endor LEGO minifigure captures the infantry soldiers who fought alongside commandos during the ground assault on the shield generator bunker, wearing camouflage gear adapted for forest combat. This minifigure represents the regular troops who formed the backbone of the Rebel ground forces, less specialized than commandos but equally brave in facing Imperial forces and AT-ST walkers. Armed with standard infantry weapons and supported by Ewok allies, these troopers demonstrated that the Rebellion\'s strength came from ordinary beings choosing to fight tyranny. Released in sets from 2009 onwards, this minifigure appeals to collectors building complete Endor battle scenes, valued for representing the diverse ground forces that combined with local resistance to achieve the impossible victory that enabled the Death Star\'s destruction.',
    de: 'Die LEGO-Minifigur des Rebellensoldaten auf Endor fängt die Infanteriesoldaten ein, die während des Bodenangriffs auf den Schildgenerator-Bunker an der Seite von Kommandos kämpften und Tarnausrüstung trugen, die für Waldkampf angepasst war. Diese Minifigur repräsentiert die regulären Truppen, die das Rückgrat der Rebellenbodentruppen bildeten, weniger spezialisiert als Kommandos, aber ebenso tapfer im Kampf gegen imperiale Streitkräfte und AT-ST-Läufer. Bewaffnet mit Standard-Infanteriewaffen und unterstützt von Ewok-Verbündeten demonstrierten diese Soldaten, dass die Stärke der Rebellion von gewöhnlichen Wesen kam, die sich entschieden, gegen Tyrannei zu kämpfen. In Sets ab 2009 veröffentlicht, spricht diese Minifigur Sammler an, die vollständige Endor-Kampfszenen aufbauen, geschätzt für die Darstellung der vielfältigen Bodentruppen, die sich mit lokalem Widerstand verbanden, um den unmöglichen Sieg zu erreichen, der die Zerstörung des Todessterns ermöglichte.',
    fr: 'La minifigurine LEGO du Soldat Rebelle d\'Endor capture les soldats d\'infanterie qui ont combattu aux côtés des commandos pendant l\'assaut terrestre sur le bunker du générateur de bouclier, portant un équipement de camouflage adapté au combat forestier. Cette minifigurine représente les troupes régulières qui formaient l\'épine dorsale des forces terrestres Rebelles, moins spécialisées que les commandos mais tout aussi courageuses face aux forces Impériales et aux marcheurs AT-ST. Armés d\'armes d\'infanterie standard et soutenus par des alliés Ewoks, ces soldats ont démontré que la force de la Rébellion venait d\'êtres ordinaires choisissant de combattre la tyrannie. Sortie dans des sets à partir de 2009, cette minifigurine plaît aux collectionneurs construisant des scènes de bataille complètes d\'Endor, valorisée pour représenter les forces terrestres diverses qui se sont combinées avec la résistance locale pour atteindre la victoire impossible qui a permis la destruction de l\'Étoile de la Mort.',
    es: 'La minifigura LEGO del Soldado Rebelde de Endor captura a los soldados de infantería que lucharon junto a comandos durante el asalto terrestre al búnker del generador de escudo, vistiendo equipo de camuflaje adaptado para combate forestal. Esta minifigura representa a las tropas regulares que formaron la columna vertebral de las fuerzas terrestres Rebeldes, menos especializadas que los comandos pero igualmente valientes enfrentando fuerzas Imperiales y caminantes AT-ST. Armados con armas de infantería estándar y apoyados por aliados Ewok, estos soldados demostraron que la fuerza de la Rebelión provenía de seres ordinarios eligiendo luchar contra la tiranía. Lanzada en sets desde 2009, esta minifigura atrae a coleccionistas construyendo escenas completas de batalla de Endor, valorada por representar las diversas fuerzas terrestres que se combinaron con resistencia local para lograr la victoria imposible que permitió la destrucción de la Estrella de la Muerte.'
  },
  {
    no: 'sw0316',
    name: 'Scout Trooper (Endor)',
    en: 'The Scout Trooper LEGO minifigure depicts the Empire\'s specialized reconnaissance forces on Endor with their distinctive white armor with black accents, lightweight design, and the speeder bike pilot appearance. This minifigure captures the elite Imperial scouts who patrolled the forest moon\'s dense terrain, tasked with securing the Death Star\'s shield generator from Rebel infiltration. Known for their agility and piloting skills on 74-Z speeder bikes during high-speed pursuits through the forest, Scout Troopers represented the Empire\'s tactical adaptation to diverse combat environments. Released in numerous sets from 2000 onwards, this minifigure became one of the most iconic Imperial variants, highly collectible due to Return of the Jedi\'s memorable speeder bike chase sequence and its distinctive armor design that made Scout Troopers instantly recognizable among Imperial forces.',
    de: 'Die LEGO-Minifigur des Spähtruppers zeigt die spezialisierten Aufklärungskräfte des Imperiums auf Endor mit ihrer markanten weißen Rüstung mit schwarzen Akzenten, leichtem Design und dem Speeder-Bike-Piloten-Aussehen. Diese Minifigur fängt die Elite-imperialen Späher ein, die das dichte Gelände des Waldmondes patrouillierten und mit der Sicherung des Schildgenerators des Todessterns vor Rebelleninfiltration beauftragt waren. Bekannt für ihre Agilität und Pilotenfähigkeiten auf 74-Z-Speeder-Bikes während Hochgeschwindigkeitsverfolgungen durch den Wald repräsentierten Spähtruppen die taktische Anpassung des Imperiums an vielfältige Kampfumgebungen. In zahlreichen Sets ab 2000 veröffentlicht, wurde diese Minifigur zu einer der ikonischsten imperialen Varianten, hochgradig sammelwürdig aufgrund von Die Rückkehr der Jedi-Ritters unvergesslicher Speeder-Bike-Verfolgungsjagd-Sequenz und ihrem markanten Rüstungsdesign, das Spähtruppen unter den imperialen Streitkräften sofort erkennbar machte.',
    fr: 'La minifigurine LEGO du Scout Trooper dépeint les forces de reconnaissance spécialisées de l\'Empire sur Endor avec leur armure blanche distinctive avec des accents noirs, design léger, et l\'apparence de pilote de speeder bike. Cette minifigurine capture les scouts Impériaux d\'élite qui patrouillaient le terrain dense de la lune forestière, chargés de sécuriser le générateur de bouclier de l\'Étoile de la Mort contre l\'infiltration Rebelle. Connus pour leur agilité et leurs compétences de pilotage sur les speeder bikes 74-Z pendant les poursuites à haute vitesse à travers la forêt, les Scout Troopers représentaient l\'adaptation tactique de l\'Empire à divers environnements de combat. Sortie dans de nombreux sets à partir de 2000, cette minifigurine est devenue l\'une des variantes Impériales les plus emblématiques, hautement collectionnable en raison de la séquence de poursuite en speeder bike mémorable du Retour du Jedi et de son design d\'armure distinctif qui rendait les Scout Troopers instantanément reconnaissables parmi les forces Impériales.',
    es: 'La minifigura LEGO del Scout Trooper representa a las fuerzas de reconocimiento especializadas del Imperio en Endor con su distintiva armadura blanca con acentos negros, diseño ligero, y la apariencia de piloto de speeder bike. Esta minifigura captura a los exploradores Imperiales de élite que patrullaban el denso terreno de la luna forestal, encargados de asegurar el generador de escudo de la Estrella de la Muerte contra infiltración Rebelde. Conocidos por su agilidad y habilidades de pilotaje en speeder bikes 74-Z durante persecuciones de alta velocidad a través del bosque, los Scout Troopers representaron la adaptación táctica del Imperio a diversos ambientes de combate. Lanzada en numerosos sets desde 2000, esta minifigura se convirtió en una de las variantes Imperiales más icónicas, altamente coleccionable debido a la memorable secuencia de persecución en speeder bike de El Retorno del Jedi y su distintivo diseño de armadura que hizo a los Scout Troopers instantáneamente reconocibles entre las fuerzas Imperiales.'
  },
  {
    no: 'sw0317',
    name: 'AT-ST Driver',
    en: 'The AT-ST Driver LEGO minifigure depicts the specialized pilots operating the Empire\'s two-legged scout walker with their distinctive gray uniform, reinforced helmet, and the expert appearance marking them as trained vehicle operators. This minifigure represents the crews who piloted the All Terrain Scout Transport through Endor\'s forests, providing mobile firepower and reconnaissance for Imperial ground forces. Operating the nimble but vulnerable walker required skill in navigating rough terrain while coordinating weapons systems against Rebel and Ewok attacks. Released in sets from 2001 onwards appearing in AT-ST vehicle builds, this minifigure became essential for collectors creating Imperial ground forces, valued for its unique gray coloring and its representation of the Empire\'s mechanized advantage that ultimately proved insufficient against determined resistance and guerrilla tactics employed by the Rebellion and their Ewok allies.',
    de: 'Die LEGO-Minifigur des AT-ST-Piloten zeigt die spezialisierten Piloten, die den zweibeinigen Späher-Läufer des Imperiums mit ihrer markanten grauen Uniform, verstärktem Helm und dem Experten-Aussehen bedienten, das sie als ausgebildete Fahrzeugführer kennzeichnet. Diese Minifigur repräsentiert die Besatzungen, die den All Terrain Scout Transport durch Endors Wälder pilotierten und mobile Feuerkraft und Aufklärung für imperiale Bodentruppen bereitstellten. Das Bedienen des wendigen, aber verwundbaren Läufers erforderte Geschick beim Navigieren in rauem Gelände, während Waffensysteme gegen Rebellen- und Ewok-Angriffe koordiniert wurden. In Sets ab 2001 in AT-ST-Fahrzeug-Builds veröffentlicht, wurde diese Minifigur für Sammler, die imperiale Bodentruppen erstellen, unverzichtbar, geschätzt für ihre einzigartige graue Färbung und ihre Darstellung des mechanisierten Vorteils des Imperiums, der sich letztendlich als unzureichend gegen entschlossenen Widerstand und Guerilla-Taktiken erwies, die von der Rebellion und ihren Ewok-Verbündeten eingesetzt wurden.',
    fr: 'La minifigurine LEGO du Conducteur d\'AT-ST dépeint les pilotes spécialisés opérant le marcheur scout à deux pattes de l\'Empire avec leur uniforme gris distinctif, casque renforcé, et l\'apparence experte les marquant comme opérateurs de véhicules formés. Cette minifigurine représente les équipages qui ont piloté le All Terrain Scout Transport à travers les forêts d\'Endor, fournissant une puissance de feu mobile et une reconnaissance pour les forces terrestres Impériales. Opérer le marcheur agile mais vulnérable nécessitait une compétence pour naviguer sur un terrain accidenté tout en coordonnant les systèmes d\'armes contre les attaques Rebelles et Ewoks. Sortie dans des sets à partir de 2001 apparaissant dans des constructions de véhicules AT-ST, cette minifigurine est devenue essentielle pour les collectionneurs créant des forces terrestres Impériales, valorisée pour sa coloration grise unique et sa représentation de l\'avantage mécanisé de l\'Empire qui s\'est finalement avéré insuffisant contre la résistance déterminée et les tactiques de guérilla employées par la Rébellion et leurs alliés Ewoks.',
    es: 'La minifigura LEGO del Conductor AT-ST representa a los pilotos especializados operando el caminante explorador de dos patas del Imperio con su distintivo uniforme gris, casco reforzado, y la apariencia experta marcándolos como operadores de vehículos entrenados. Esta minifigura representa a las tripulaciones que pilotearon el All Terrain Scout Transport a través de los bosques de Endor, proporcionando potencia de fuego móvil y reconocimiento para fuerzas terrestres Imperiales. Operar el caminante ágil pero vulnerable requería habilidad navegando terreno accidentado mientras coordinaban sistemas de armas contra ataques Rebeldes y Ewok. Lanzada en sets desde 2001 apareciendo en construcciones de vehículo AT-ST, esta minifigura se volvió esencial para coleccionistas creando fuerzas terrestres Imperiales, valorada por su única coloración gris y su representación de la ventaja mecanizada del Imperio que finalmente resultó insuficiente contra resistencia determinada y tácticas de guerrilla empleadas por la Rebelión y sus aliados Ewok.'
  },
  {
    no: 'sw0318',
    name: 'General Lando Calrissian',
    en: 'General Lando Calrissian\'s LEGO minifigure captures the redeemed hero in his Rebel Alliance general\'s uniform, marking his transformation from self-serving smuggler to trusted military leader. This minifigure depicts Lando during the Battle of Endor commanding the starfighter assault on the second Death Star, representing his complete redemption arc after betraying Han on Bespin. Promoted to general and entrusted with the Millennium Falcon for the war\'s most critical mission, Lando proved his loyalty and tactical brilliance by destroying the Empire\'s ultimate weapon. Released in sets from 2015 onwards, this minifigure became a valued Lando variant, representing his heroic transformation and the Rebellion\'s acceptance of reformed scoundrels who chose to fight for freedom rather than profit.',
    de: 'Die LEGO-Minifigur von General Lando Calrissian fängt den erlösten Helden in seiner Rebellen-Allianz-Generalsuniform ein und markiert seine Verwandlung vom eigennützigen Schmuggler zum vertrauenswürdigen militärischen Anführer. Diese Minifigur zeigt Lando während der Schlacht von Endor, als er den Sternenjäger-Angriff auf den zweiten Todesstern befehligte, und repräsentiert seinen vollständigen Erlösungsbogen nach dem Verrat an Han auf Bespin. Zum General befördert und mit dem Millennium Falken für die kritischste Mission des Krieges betraut, bewies Lando seine Loyalität und taktische Brillanz, indem er die ultimative Waffe des Imperiums zerstörte. In Sets ab 2015 veröffentlicht, wurde diese Minifigur zu einer geschätzten Lando-Variante, die seine heroische Transformation und die Akzeptanz der Rebellion von reformierten Schurken repräsentiert, die sich entschieden, für Freiheit statt Profit zu kämpfen.',
    fr: 'La minifigurine LEGO du Général Lando Calrissian capture le héros racheté dans son uniforme de général de l\'Alliance Rebelle, marquant sa transformation de contrebandier égoïste en leader militaire de confiance. Cette minifigurine dépeint Lando pendant la Bataille d\'Endor commandant l\'assaut de chasseurs stellaires sur la seconde Étoile de la Mort, représentant son arc de rédemption complet après avoir trahi Han sur Bespin. Promu général et chargé du Faucon Millenium pour la mission la plus critique de la guerre, Lando a prouvé sa loyauté et sa brillance tactique en détruisant l\'arme ultime de l\'Empire. Sortie dans des sets à partir de 2015, cette minifigurine est devenue une variante de Lando valorisée, représentant sa transformation héroïque et l\'acceptation de la Rébellion des scélérats réformés qui ont choisi de se battre pour la liberté plutôt que le profit.',
    es: 'La minifigura LEGO del General Lando Calrissian captura al héroe redimido en su uniforme de general de la Alianza Rebelde, marcando su transformación desde contrabandista egoísta hasta líder militar de confianza. Esta minifigura representa a Lando durante la Batalla de Endor comandando el asalto de cazas estelares a la segunda Estrella de la Muerte, representando su completo arco de redención después de traicionar a Han en Bespin. Promovido a general y confiado con el Halcón Milenario para la misión más crítica de la guerra, Lando probó su lealtad y brillantez táctica destruyendo el arma definitiva del Imperio. Lanzada en sets desde 2015, esta minifigura se convirtió en una valorada variante de Lando, representando su transformación heroica y la aceptación de la Rebelión de pícaros reformados que eligieron luchar por libertad en lugar de beneficio.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 201-210 (sw0309-sw0318) - 10 minifigs...\n');

  for (const m of batch) {
    await prisma.minifigCatalog.upsert({
      where: { minifigure_no: m.no },
      update: {
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      },
      create: {
        minifigure_no: m.no,
        name: m.name,
        category_id: 1,
        category_name: 'Star Wars',
        search_name: m.name.toLowerCase(),
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`  ✅ ${m.no}: ${m.name}`);
  }

  console.log('\n✨ Batch 201-210 complete: 10 minifigs (40 descriptions)');
  await prisma.$disconnect();
}

saveBatch().catch(console.error);