import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0024',
    name: 'Obi-Wan Kenobi (Young with Hood and Cape)',
    en: 'Obi-Wan Kenobi Young with Hood and Cape represents the Jedi Padawan and later Knight during the prequel trilogy era, mentored by Qui-Gon Jinn in The Phantom Menace. This LEGO minifigure features young Obi-Wan in his Jedi robes with brown hood and cape accessories, capturing his appearance as a skilled warrior before his later years of exile. Released in 1999 with early prequel sets including the Jedi Defense I set 7203, this version shows Obi-Wan at the height of his combat abilities during the Clone Wars era. The hooded cape and young appearance make this minifigure essential for collectors building prequel-era displays and contrasting with the older Ben Kenobi variants from the original trilogy.',
    de: 'Obi-Wan Kenobi Jung mit Kapuze und Umhang repräsentiert den Jedi-Padawan und späteren Ritter während der Prequel-Trilogie-Ära, der von Qui-Gon Jinn in Die dunkle Bedrohung betreut wurde. Diese LEGO Minifigur zeigt den jungen Obi-Wan in seinen Jedi-Roben mit brauner Kapuze und Umhang-Zubehör und fängt sein Aussehen als geschickter Krieger vor seinen späteren Exiljahren ein. Veröffentlicht 1999 mit frühen Prequel-Sets einschließlich des Jedi Defense I-Sets 7203, zeigt diese Version Obi-Wan auf dem Höhepunkt seiner Kampffähigkeiten während der Klonkriegs-Ära. Die Kapuzen-Umhang und das junge Aussehen machen diese Minifigur wesentlich für Sammler, die Prequel-Ära-Displays bauen und mit den älteren Ben Kenobi-Varianten aus der ursprünglichen Trilogie kontrastieren.',
    fr: 'Obi-Wan Kenobi Jeune avec Capuche et Cape représente le Padawan Jedi et plus tard Chevalier pendant l\'ère de la trilogie préquelle, encadré par Qui-Gon Jinn dans La Menace Fantôme. Cette minifigurine LEGO présente le jeune Obi-Wan dans ses robes Jedi avec accessoires de capuche et cape brunes, capturant son apparence comme guerrier qualifié avant ses années d\'exil ultérieures. Sortie en 1999 avec les premiers sets préquels incluant le set Jedi Defense I 7203, cette version montre Obi-Wan au sommet de ses capacités de combat pendant l\'ère des Guerres des Clones. La cape à capuche et l\'apparence jeune rendent cette minifigurine essentielle pour les collectionneurs construisant des affichages de l\'ère préquelle et contrastant avec les variantes plus âgées de Ben Kenobi de la trilogie originale.',
    es: 'Obi-Wan Kenobi Joven con Capucha y Capa representa al Padawan Jedi y posteriormente Caballero durante la era de la trilogía de precuelas, bajo la mentoría de Qui-Gon Jinn en La Amenaza Fantasma. Esta minifigura LEGO presenta al joven Obi-Wan en sus túnicas Jedi con accesorios de capucha y capa marrones, capturando su apariencia como guerrero hábil antes de sus años posteriores de exilio. Lanzada en 1999 con los primeros sets de precuelas incluyendo el set Jedi Defense I 7203, esta versión muestra a Obi-Wan en el apogeo de sus habilidades de combate durante la era de las Guerras Clon. La capa con capucha y apariencia joven hacen de esta minifigura esencial para coleccionistas construyendo exhibiciones de era de precuelas y contrastando con las variantes de Ben Kenobi más viejas de la trilogía original.'
  },
  {
    no: 'sw0025',
    name: 'Padmé Naberrie (Amidala) - Yellow Head',
    en: 'Padmé Naberrie Amidala with Yellow Head represents the Senator and former Queen of Naboo who played a crucial role in the Clone Wars and the fall of the Republic in the prequel trilogy. This LEGO minifigure features the classic yellow head, elaborate outfit torso print, and leg design that captures one of Padmé\'s many iconic costumes from the films. Released in the early 2000s with prequel-era sets, this version shows the brave politician and secret wife of Anakin Skywalker in one of her distinguished appearances. The yellow head and early minifigure design make this valuable for collectors seeking vintage prequel trilogy characters and complete Padmé Amidala costume variations.',
    de: 'Padmé Naberrie Amidala mit gelbem Kopf repräsentiert die Senatorin und ehemalige Königin von Naboo, die eine entscheidende Rolle in den Klonkriegen und dem Fall der Republik in der Prequel-Trilogie spielte. Diese LEGO Minifigur zeigt den klassischen gelben Kopf, aufwendigen Outfit-Torso-Druck und Bein-Design, das eines von Padmés vielen ikonischen Kostümen aus den Filmen einfängt. Veröffentlicht in den frühen 2000er Jahren mit Prequel-Ära-Sets, zeigt diese Version die mutige Politikerin und geheime Ehefrau von Anakin Skywalker in einer ihrer vornehmen Erscheinungen. Der gelbe Kopf und das frühe Minifigur-Design machen diese wertvoll für Sammler, die Vintage-Prequel-Trilogie-Charaktere und vollständige Padmé Amidala-Kostüm-Variationen suchen.',
    fr: 'Padmé Naberrie Amidala avec Tête Jaune représente la Sénatrice et ancienne Reine de Naboo qui a joué un rôle crucial dans les Guerres des Clones et la chute de la République dans la trilogie préquelle. Cette minifigurine LEGO présente la tête jaune classique, l\'impression de torse de tenue élaborée et le design de jambes qui capture l\'un des nombreux costumes emblématiques de Padmé des films. Sortie au début des années 2000 avec les sets de l\'ère préquelle, cette version montre la politicienne courageuse et épouse secrète d\'Anakin Skywalker dans l\'une de ses apparences distinguées. La tête jaune et le design de minifigurine précoce rendent celle-ci précieuse pour les collectionneurs recherchant des personnages de trilogie préquelle vintage et des variations de costumes complètes de Padmé Amidala.',
    es: 'Padmé Naberrie Amidala con Cabeza Amarilla representa a la Senadora y ex Reina de Naboo quien jugó un papel crucial en las Guerras Clon y la caída de la República en la trilogía de precuelas. Esta minifigura LEGO presenta la clásica cabeza amarilla, impresión de torso de atuendo elaborado y diseño de piernas que captura uno de los muchos trajes icónicos de Padmé de las películas. Lanzada a principios de los años 2000 con sets de era de precuelas, esta versión muestra a la valiente política y esposa secreta de Anakin Skywalker en una de sus apariencias distinguidas. La cabeza amarilla y diseño de minifigura temprano hacen de esta valiosa para coleccionistas buscando personajes de trilogía de precuelas vintage y variaciones de vestuario completas de Padmé Amidala.'
  },
  {
    no: 'sw0026',
    name: 'Princess Leia - White Dress, Simple Belt, Yellow Head and Hands',
    en: 'Princess Leia with White Dress and Yellow Head represents the iconic rebel leader and princess of Alderaan in her classic white ceremonial gown from A New Hope. This LEGO minifigure features the classic yellow head with side bun hair piece, white dress torso with simple belt print, and the distinctive appearance from the opening scenes and medal ceremony. Released in 1999 with the original Millennium Falcon set 7190, this version captures one of the most recognizable costumes in Star Wars history. The yellow head, simple belt design, and status as one of the earliest Princess Leia variants make this minifigure highly valuable for collectors seeking vintage LEGO Star Wars releases and complete Princess Leia collection variations.',
    de: 'Prinzessin Leia mit weißem Kleid und gelbem Kopf repräsentiert die ikonische Rebellenführerin und Prinzessin von Alderaan in ihrem klassischen weißen Zeremonienkleid aus Eine neue Hoffnung. Diese LEGO Minifigur zeigt den klassischen gelben Kopf mit Seitenknoten-Haarteil, weißes Kleid-Torso mit einfachem Gürtel-Druck und das charakteristische Aussehen aus den Eröffnungsszenen und der Medaillenzeremonie. Veröffentlicht 1999 mit dem ursprünglichen Millennium Falcon-Set 7190, fängt diese Version eines der erkennbarsten Kostüme in der Star Wars-Geschichte ein. Der gelbe Kopf, das einfache Gürtel-Design und der Status als eine der frühesten Prinzessin Leia-Varianten machen diese Minifigur sehr wertvoll für Sammler, die Vintage-LEGO Star Wars-Veröffentlichungen und vollständige Prinzessin Leia-Sammlungs-Variationen suchen.',
    fr: 'Princesse Leia avec Robe Blanche et Tête Jaune représente la leader rebelle emblématique et princesse d\'Alderaan dans sa robe cérémonielle blanche classique d\'Un nouvel espoir. Cette minifigurine LEGO présente la tête jaune classique avec pièce de cheveux en chignon latéral, torse de robe blanche avec impression de ceinture simple et l\'apparence distinctive des scènes d\'ouverture et de la cérémonie de médailles. Sortie en 1999 avec le set Millennium Falcon original 7190, cette version capture l\'un des costumes les plus reconnaissables de l\'histoire de Star Wars. La tête jaune, le design de ceinture simple et le statut de l\'une des premières variantes de Princesse Leia rendent cette minifigurine très précieuse pour les collectionneurs recherchant des sorties LEGO Star Wars vintage et des variations de collection complètes de Princesse Leia.',
    es: 'Princesa Leia con Vestido Blanco y Cabeza Amarilla representa a la icónica líder rebelde y princesa de Alderaan en su clásico vestido ceremonial blanco de Una Nueva Esperanza. Esta minifigura LEGO presenta la clásica cabeza amarilla con pieza de cabello de moño lateral, torso de vestido blanco con impresión de cinturón simple y la apariencia distintiva de las escenas de apertura y ceremonia de medallas. Lanzada en 1999 con el set Millennium Falcon original 7190, esta versión captura uno de los trajes más reconocibles en la historia de Star Wars. La cabeza amarilla, diseño de cinturón simple y estatus como una de las variantes más tempranas de Princesa Leia hacen de esta minifigura muy valiosa para coleccionistas buscando lanzamientos LEGO Star Wars vintage y variaciones de colección completas de Princesa Leia.'
  },
  {
    no: 'sw0027',
    name: 'Qui-Gon Jinn (Yellow Head)',
    en: 'Qui-Gon Jinn with Yellow Head represents the wise Jedi Master who discovered Anakin Skywalker and trained Obi-Wan Kenobi in The Phantom Menace. This LEGO minifigure features the classic yellow head with long brown hair piece, tan Jedi robes torso print, and the distinguished appearance of the maverick Jedi who believed in following the Living Force. Released in 1999 with early prequel sets including the Jedi Defense I set 7203, this version captures the mentor figure whose death at the hands of Darth Maul set the course for the entire saga. The yellow head and status as one of the earliest Qui-Gon Jinn releases make this minifigure highly valuable for collectors seeking vintage prequel trilogy characters and complete Jedi Master collections.',
    de: 'Qui-Gon Jinn mit gelbem Kopf repräsentiert den weisen Jedi-Meister, der Anakin Skywalker entdeckte und Obi-Wan Kenobi in Die dunkle Bedrohung trainierte. Diese LEGO Minifigur zeigt den klassischen gelben Kopf mit langem braunem Haarteil, beigefarbenen Jedi-Roben-Torso-Druck und das vornehme Aussehen des eigenwilligen Jedi, der daran glaubte, der Lebendigen Macht zu folgen. Veröffentlicht 1999 mit frühen Prequel-Sets einschließlich des Jedi Defense I-Sets 7203, fängt diese Version die Mentor-Figur ein, deren Tod durch die Hände von Darth Maul den Kurs für die gesamte Saga festlegte. Der gelbe Kopf und Status als eine der frühesten Qui-Gon Jinn-Veröffentlichungen machen diese Minifigur sehr wertvoll für Sammler, die Vintage-Prequel-Trilogie-Charaktere und vollständige Jedi-Meister-Sammlungen suchen.',
    fr: 'Qui-Gon Jinn avec Tête Jaune représente le sage Maître Jedi qui a découvert Anakin Skywalker et formé Obi-Wan Kenobi dans La Menace Fantôme. Cette minifigurine LEGO présente la tête jaune classique avec pièce de cheveux bruns longs, l\'impression de torse de robes Jedi beiges et l\'apparence distinguée du Jedi indépendant qui croyait en suivre la Force Vivante. Sortie en 1999 avec les premiers sets préquels incluant le set Jedi Defense I 7203, cette version capture la figure de mentor dont la mort aux mains de Dark Maul a fixé le cours de toute la saga. La tête jaune et le statut de l\'une des premières sorties de Qui-Gon Jinn rendent cette minifigurine très précieuse pour les collectionneurs recherchant des personnages de trilogie préquelle vintage et des collections complètes de Maîtres Jedi.',
    es: 'Qui-Gon Jinn con Cabeza Amarilla representa al sabio Maestro Jedi quien descubrió a Anakin Skywalker y entrenó a Obi-Wan Kenobi en La Amenaza Fantasma. Esta minifigura LEGO presenta la clásica cabeza amarilla con pieza de cabello largo marrón, impresión de torso de túnicas Jedi beige y la apariencia distinguida del Jedi inconformista que creía en seguir la Fuerza Viviente. Lanzada en 1999 con los primeros sets de precuelas incluyendo el set Jedi Defense I 7203, esta versión captura la figura de mentor cuya muerte a manos de Darth Maul estableció el curso para toda la saga. La cabeza amarilla y estatus como uno de los lanzamientos más tempranos de Qui-Gon Jinn hacen de esta minifigura muy valiosa para coleccionistas buscando personajes de trilogía de precuelas vintage y colecciones completas de Maestros Jedi.'
  },
  {
    no: 'sw0028',
    name: 'Astromech Droid, R2-D2',
    en: 'R2-D2 Astromech Droid represents the beloved and resourceful droid companion who appears throughout all nine episodes of the Skywalker saga. This LEGO minifigure features R2-D2\'s iconic white and blue cylindrical body with detailed printing, dome head, and the distinctive design of the most famous astromech droid in the galaxy. Released in 1999 with the very first LEGO Star Wars wave including X-Wing Fighter set 7140, this version captures the loyal droid who saved the heroes countless times with his technical skills and brave actions. The status as one of the earliest LEGO Star Wars droids and R2-D2\'s universal popularity make this minifigure essential for every Star Wars LEGO collector.',
    de: 'R2-D2 Astromech-Droide repräsentiert den geliebten und einfallsreichen Droiden-Begleiter, der in allen neun Episoden der Skywalker-Saga erscheint. Diese LEGO Minifigur zeigt R2-D2s ikonischen weiß-blauen zylindrischen Körper mit detailliertem Druck, Kuppelkopf und das charakteristische Design des berühmtesten Astromech-Droiden in der Galaxie. Veröffentlicht 1999 mit der allerersten LEGO Star Wars-Welle einschließlich X-Wing Fighter-Set 7140, fängt diese Version den treuen Droiden ein, der die Helden unzählige Male mit seinen technischen Fähigkeiten und mutigen Aktionen rettete. Der Status als einer der frühesten LEGO Star Wars-Droiden und R2-D2s universelle Beliebtheit machen diese Minifigur wesentlich für jeden Star Wars LEGO-Sammler.',
    fr: 'Droïde Astromécano R2-D2 représente le compagnon droïde bien-aimé et ingénieux qui apparaît tout au long des neuf épisodes de la saga Skywalker. Cette minifigurine LEGO présente le corps cylindrique blanc et bleu emblématique de R2-D2 avec impression détaillée, tête en dôme et le design distinctif du droïde astromécano le plus célèbre de la galaxie. Sortie en 1999 avec la toute première vague LEGO Star Wars incluant le set X-Wing Fighter 7140, cette version capture le droïde loyal qui a sauvé les héros d\'innombrables fois avec ses compétences techniques et actions courageuses. Le statut de l\'un des premiers droïdes LEGO Star Wars et la popularité universelle de R2-D2 rendent cette minifigurine essentielle pour chaque collectionneur LEGO Star Wars.',
    es: 'Droide Astromecánico R2-D2 representa al querido e ingenioso droide compañero que aparece a lo largo de los nueve episodios de la saga Skywalker. Esta minifigura LEGO presenta el icónico cuerpo cilíndrico blanco y azul de R2-D2 con impresión detallada, cabeza de cúpula y el diseño distintivo del droide astromecánico más famoso de la galaxia. Lanzada en 1999 con la primera ola de LEGO Star Wars incluyendo el set X-Wing Fighter 7140, esta versión captura al droide leal que salvó a los héroes innumerables veces con sus habilidades técnicas y acciones valientes. El estatus como uno de los droides LEGO Star Wars más tempranos y la popularidad universal de R2-D2 hacen de esta minifigura esencial para cada coleccionista LEGO Star Wars.'
  },
  {
    no: 'sw0029',
    name: 'Astromech Droid, R5-D4 - Dome Head with Short Red Stripes',
    en: 'R5-D4 Astromech Droid with Short Red Stripes represents the malfunctioning droid with a bad motivator that Luke\'s uncle almost purchased instead of R2-D2 in A New Hope. This LEGO minifigure features R5-D4\'s distinctive white and red cylindrical body with short red stripe printing, dome head, and the design of the droid whose breakdown changed galactic history. Released in the early 2000s with LEGO Star Wars Tatooine sets, this version captures the brief but memorable appearance of the unlucky astromech whose malfunction ensured R2-D2 would deliver Princess Leia\'s message to Obi-Wan Kenobi. The specific short red stripe variant and connection to a pivotal Star Wars moment make this minifigure valuable for collectors seeking complete astromech droid collections.',
    de: 'R5-D4 Astromech-Droide mit kurzen roten Streifen repräsentiert den defekten Droiden mit schlechtem Motivator, den Lukes Onkel fast anstelle von R2-D2 in Eine neue Hoffnung kaufte. Diese LEGO Minifigur zeigt R5-D4s charakteristischen weiß-roten zylindrischen Körper mit kurzem roten Streifen-Druck, Kuppelkopf und das Design des Droiden, dessen Zusammenbruch die galaktische Geschichte veränderte. Veröffentlicht in den frühen 2000er Jahren mit LEGO Star Wars Tatooine-Sets, fängt diese Version den kurzen aber einprägsamen Auftritt des unglücklichen Astromech-Droiden ein, dessen Fehlfunktion sicherstellte, dass R2-D2 Prinzessin Leias Nachricht an Obi-Wan Kenobi überbringen würde. Die spezifische kurze rote Streifen-Variante und Verbindung zu einem entscheidenden Star Wars-Moment machen diese Minifigur wertvoll für Sammler, die vollständige Astromech-Droiden-Sammlungen suchen.',
    fr: 'Droïde Astromécano R5-D4 avec Courtes Rayures Rouges représente le droïde défectueux avec un mauvais motivateur que l\'oncle de Luke a presque acheté à la place de R2-D2 dans Un nouvel espoir. Cette minifigurine LEGO présente le corps cylindrique blanc et rouge distinctif de R5-D4 avec impression de rayures rouges courtes, tête en dôme et le design du droïde dont la panne a changé l\'histoire galactique. Sortie au début des années 2000 avec les sets LEGO Star Wars Tatooine, cette version capture l\'apparition brève mais mémorable de l\'astromécano malchanceux dont le dysfonctionnement a assuré que R2-D2 livrerait le message de Princesse Leia à Obi-Wan Kenobi. La variante de rayures rouges courtes spécifique et la connexion à un moment Star Wars pivot rendent cette minifigurine précieuse pour les collectionneurs recherchant des collections complètes de droïdes astromécaniques.',
    es: 'Droide Astromecánico R5-D4 con Rayas Rojas Cortas representa al droide defectuoso con un mal motivador que el tío de Luke casi compró en lugar de R2-D2 en Una Nueva Esperanza. Esta minifigura LEGO presenta el distintivo cuerpo cilíndrico blanco y rojo de R5-D4 con impresión de rayas rojas cortas, cabeza de cúpula y el diseño del droide cuya avería cambió la historia galáctica. Lanzada a principios de los años 2000 con sets LEGO Star Wars Tatooine, esta versión captura la aparición breve pero memorable del astromecánico desafortunado cuya falla aseguró que R2-D2 entregaría el mensaje de la Princesa Leia a Obi-Wan Kenobi. La variante específica de rayas rojas cortas y conexión con un momento pivotal de Star Wars hacen de esta minifigura valiosa para coleccionistas buscando colecciones completas de droides astromecánicos.'
  },
  {
    no: 'sw0030',
    name: 'Rebel Engineer',
    en: 'Rebel Engineer represents the dedicated technical specialists who maintained starfighters and equipment for the Rebel Alliance throughout the Galactic Civil War. This LEGO minifigure features the distinctive orange jumpsuit with utility vest torso print, white helmet accessory, and practical outfit worn by the ground crew at Echo Base and Yavin Base. Released in the early 2000s with LEGO Star Wars hangar and base sets, this version captures the essential support personnel who kept X-Wings and other rebel craft operational. The orange engineer uniform makes this minifigure valuable for collectors building realistic rebel base displays and army-building ground crew units to accompany pilot collections.',
    de: 'Rebellen-Ingenieur repräsentiert die engagierten technischen Spezialisten, die Sternenjäger und Ausrüstung für die Rebellenallianz während des Galaktischen Bürgerkriegs warteten. Diese LEGO Minifigur zeigt den charakteristischen orangen Overall mit Werkzeugwesten-Torso-Druck, weißes Helm-Zubehör und praktisches Outfit, das von der Bodencrew auf Echo Base und Yavin Base getragen wurde. Veröffentlicht in den frühen 2000er Jahren mit LEGO Star Wars Hangar- und Basis-Sets, fängt diese Version das wesentliche Unterstützungspersonal ein, das X-Wings und andere Rebellenraumschiffe betriebsbereit hielt. Die orange Ingenieur-Uniform macht diese Minifigur wertvoll für Sammler, die realistische Rebellenbasis-Displays bauen und Bodencrew-Einheiten für Armeen zusammenstellen, um Piloten-Sammlungen zu begleiten.',
    fr: 'Ingénieur Rebelle représente les spécialistes techniques dévoués qui ont entretenu les chasseurs stellaires et l\'équipement pour l\'Alliance Rebelle tout au long de la Guerre Civile Galactique. Cette minifigurine LEGO présente la combinaison orange distinctive avec impression de torse de gilet utilitaire, accessoire de casque blanc et tenue pratique portée par l\'équipe au sol à la Base Echo et la Base Yavin. Sortie au début des années 2000 avec les sets de hangar et de base LEGO Star Wars, cette version capture le personnel de soutien essentiel qui a maintenu les X-Wings et autres vaisseaux rebelles opérationnels. L\'uniforme d\'ingénieur orange rend cette minifigurine précieuse pour les collectionneurs construisant des affichages de base rebelle réalistes et assemblant des unités d\'équipe au sol pour accompagner les collections de pilotes.',
    es: 'Ingeniero Rebelde representa a los especialistas técnicos dedicados que mantuvieron cazas estelares y equipo para la Alianza Rebelde durante la Guerra Civil Galáctica. Esta minifigura LEGO presenta el distintivo mono naranja con impresión de torso de chaleco de utilidad, accesorio de casco blanco y atuendo práctico usado por el personal de tierra en Base Echo y Base Yavin. Lanzada a principios de los años 2000 con sets de hangar y base LEGO Star Wars, esta versión captura al personal de apoyo esencial que mantuvo operativos los X-Wings y otras naves rebeldes. El uniforme de ingeniero naranja hace de esta minifigura valiosa para coleccionistas construyendo exhibiciones de base rebelde realistas y ensamblando unidades de personal de tierra para acompañar colecciones de pilotos.'
  },
  {
    no: 'sw0031',
    name: 'Rebel Pilot A-wing - Yellow Head, Trans-Yellow Visor, Green Jumpsuit',
    en: 'Rebel Pilot A-wing with Green Jumpsuit represents the elite fast-attack starfighter pilots who flew the RZ-1 A-wing interceptor for the Rebel Alliance during the Battle of Endor. This LEGO minifigure features the classic yellow head, green flight suit torso print, white helmet with transparent yellow visor, and the distinctive uniform worn by the fastest pilots in the rebel fleet. Released in 2000 with the A-Wing Fighter set 7134, this version captures the skilled pilots who provided crucial air support during the climactic space battle above the forest moon. The green jumpsuit and A-wing-specific design make this minifigure essential for collectors building Endor battle displays and complete rebel pilot squadron collections.',
    de: 'Rebellen-Pilot A-wing mit grünem Overall repräsentiert die Elite-Schnellangriffs-Sternenjäger-Piloten, die den RZ-1 A-wing-Abfangjäger für die Rebellenallianz während der Schlacht von Endor flogen. Diese LEGO Minifigur zeigt den klassischen gelben Kopf, grünen Fluganzug-Torso-Druck, weißen Helm mit transparentem gelbem Visier und die charakteristische Uniform, die von den schnellsten Piloten in der Rebellenflotte getragen wurde. Veröffentlicht 2000 mit dem A-Wing Fighter-Set 7134, fängt diese Version die geschickten Piloten ein, die entscheidende Luftunterstützung während der klimatischen Weltraumschlacht über dem Waldmond leisteten. Der grüne Overall und das A-wing-spezifische Design machen diese Minifigur wesentlich für Sammler, die Endor-Schlacht-Displays bauen und vollständige Rebellen-Piloten-Geschwader-Sammlungen zusammenstellen.',
    fr: 'Pilote Rebelle A-wing avec Combinaison Verte représente les pilotes d\'élite de chasseurs d\'attaque rapide qui ont piloté l\'intercepteur RZ-1 A-wing pour l\'Alliance Rebelle pendant la Bataille d\'Endor. Cette minifigurine LEGO présente la tête jaune classique, l\'impression de torse de combinaison de vol verte, le casque blanc avec visière jaune transparente et l\'uniforme distinctif porté par les pilotes les plus rapides de la flotte rebelle. Sortie en 2000 avec le set A-Wing Fighter 7134, cette version capture les pilotes qualifiés qui ont fourni un soutien aérien crucial pendant la bataille spatiale culminante au-dessus de la lune forestière. La combinaison verte et le design spécifique A-wing rendent cette minifigurine essentielle pour les collectionneurs construisant des affichages de bataille d\'Endor et des collections complètes d\'escadrons de pilotes rebelles.',
    es: 'Piloto Rebelde A-wing con Mono Verde representa a los pilotos de élite de cazas de ataque rápido que volaron el interceptor RZ-1 A-wing para la Alianza Rebelde durante la Batalla de Endor. Esta minifigura LEGO presenta la clásica cabeza amarilla, impresión de torso de traje de vuelo verde, casco blanco con visera amarilla transparente y el uniforme distintivo usado por los pilotos más rápidos de la flota rebelde. Lanzada en 2000 con el set A-Wing Fighter 7134, esta versión captura a los pilotos hábiles que proporcionaron apoyo aéreo crucial durante la batalla espacial culminante sobre la luna boscosa. El mono verde y diseño específico de A-wing hacen de esta minifigura esencial para coleccionistas construyendo exhibiciones de batalla de Endor y colecciones completas de escuadrones de pilotos rebeldes.'
  },
  {
    no: 'sw0032',
    name: 'Rebel Pilot B-wing (Yellow Head, Light Gray Helmet, Trans-Yellow Visor)',
    en: 'Rebel Pilot B-wing with Light Gray Helmet represents the specialized pilots who flew the unique B-wing starfighter bomber for the Rebel Alliance during major fleet engagements. This LEGO minifigure features the classic yellow head, orange flight suit torso print, light gray helmet with transparent yellow visor, and the distinctive uniform worn by heavy assault starfighter pilots. Released in 2000 with the B-Wing Fighter set 7180, this version captures the skilled pilots who operated the most powerful and unusual starfighter design in the rebel arsenal. The light gray helmet and B-wing-specific appearance make this minifigure valuable for collectors building complete rebel pilot collections and showcasing the diverse starfighter types of the Galactic Civil War.',
    de: 'Rebellen-Pilot B-wing mit hellgrauem Helm repräsentiert die spezialisierten Piloten, die den einzigartigen B-wing-Sternenjäger-Bomber für die Rebellenallianz während großer Flottenauseinandersetzungen flogen. Diese LEGO Minifigur zeigt den klassischen gelben Kopf, orangen Fluganzug-Torso-Druck, hellgrauen Helm mit transparentem gelbem Visier und die charakteristische Uniform, die von Schwer-Angriffs-Sternenjäger-Piloten getragen wurde. Veröffentlicht 2000 mit dem B-Wing Fighter-Set 7180, fängt diese Version die geschickten Piloten ein, die das mächtigste und ungewöhnlichste Sternenjäger-Design im Rebellenarsenal bedienten. Der hellgraue Helm und das B-wing-spezifische Aussehen machen diese Minifigur wertvoll für Sammler, die vollständige Rebellen-Piloten-Sammlungen aufbauen und die vielfältigen Sternenjäger-Typen des Galaktischen Bürgerkriegs präsentieren.',
    fr: 'Pilote Rebelle B-wing avec Casque Gris Clair représente les pilotes spécialisés qui ont piloté le bombardier chasseur stellaire B-wing unique pour l\'Alliance Rebelle pendant les grands engagements de flotte. Cette minifigurine LEGO présente la tête jaune classique, l\'impression de torse de combinaison de vol orange, le casque gris clair avec visière jaune transparente et l\'uniforme distinctif porté par les pilotes de chasseurs stellaires d\'assaut lourd. Sortie en 2000 avec le set B-Wing Fighter 7180, cette version capture les pilotes qualifiés qui ont opéré le design de chasseur stellaire le plus puissant et inhabituel de l\'arsenal rebelle. Le casque gris clair et l\'apparence spécifique B-wing rendent cette minifigurine précieuse pour les collectionneurs construisant des collections complètes de pilotes rebelles et présentant les types de chasseurs stellaires divers de la Guerre Civile Galactique.',
    es: 'Piloto Rebelde B-wing con Casco Gris Claro representa a los pilotos especializados que volaron el bombardero caza estelar B-wing único para la Alianza Rebelde durante grandes enfrentamientos de flota. Esta minifigura LEGO presenta la clásica cabeza amarilla, impresión de torso de traje de vuelo naranja, casco gris claro con visera amarilla transparente y el uniforme distintivo usado por pilotos de cazas estelares de asalto pesado. Lanzada en 2000 con el set B-Wing Fighter 7180, esta versión captura a los pilotos hábiles que operaron el diseño de caza estelar más poderoso e inusual del arsenal rebelde. El casco gris claro y apariencia específica de B-wing hacen de esta minifigura valiosa para coleccionistas construyendo colecciones completas de pilotos rebeldes y mostrando los diversos tipos de cazas estelares de la Guerra Civil Galáctica.'
  },
  {
    no: 'sw0033',
    name: 'Rebel Pilot Y-wing (Jon \'Dutch\' Vander, Gold Leader) - Yellow Head, Dark Gray Hips',
    en: 'Rebel Pilot Y-wing Jon Dutch Vander Gold Leader represents the commander of Gold Squadron who led the initial attack run on the first Death Star during the Battle of Yavin in A New Hope. This LEGO minifigure features the classic yellow head, orange and white flight suit torso print, white helmet accessory, and dark gray hips representing the Y-wing bomber pilot uniform. Released in 1999 with the original Y-Wing Fighter set 7150, this version captures Gold Leader who made the famous trench run attempt before Luke Skywalker\'s successful attack. The Gold Leader designation and status as an early Y-wing pilot make this minifigure valuable for collectors recreating the Death Star assault and building complete rebel squadron command structures.',
    de: 'Rebellen-Pilot Y-wing Jon Dutch Vander Gold Leader repräsentiert den Kommandanten des Gold-Geschwaders, der den anfänglichen Angriffsflug auf den ersten Todesstern während der Schlacht von Yavin in Eine neue Hoffnung führte. Diese LEGO Minifigur zeigt den klassischen gelben Kopf, orange-weißen Fluganzug-Torso-Druck, weißes Helm-Zubehör und dunkelgraue Hüften, die die Y-wing-Bomber-Piloten-Uniform repräsentieren. Veröffentlicht 1999 mit dem ursprünglichen Y-Wing Fighter-Set 7150, fängt diese Version Gold Leader ein, der den berühmten Graben-Angriff-Versuch vor Luke Skywalkers erfolgreichem Angriff unternahm. Die Gold Leader-Bezeichnung und der Status als früher Y-wing-Pilot machen diese Minifigur wertvoll für Sammler, die den Todesstern-Angriff nachstellen und vollständige Rebellen-Geschwader-Kommandostrukturen aufbauen.',
    fr: 'Pilote Rebelle Y-wing Jon Dutch Vander Gold Leader représente le commandant de l\'Escadron Or qui a mené l\'attaque initiale sur la première Étoile de la Mort pendant la Bataille de Yavin dans Un nouvel espoir. Cette minifigurine LEGO présente la tête jaune classique, l\'impression de torse de combinaison de vol orange et blanche, l\'accessoire de casque blanc et les hanches grises foncées représentant l\'uniforme de pilote de bombardier Y-wing. Sortie en 1999 avec le set Y-Wing Fighter original 7150, cette version capture Gold Leader qui a fait la fameuse tentative de course dans la tranchée avant l\'attaque réussie de Luke Skywalker. La désignation Gold Leader et le statut de pilote Y-wing précoce rendent cette minifigurine précieuse pour les collectionneurs recréant l\'assaut de l\'Étoile de la Mort et construisant des structures de commandement d\'escadron rebelle complètes.',
    es: 'Piloto Rebelde Y-wing Jon Dutch Vander Gold Leader representa al comandante del Escuadrón Oro quien lideró el ataque inicial en la primera Estrella de la Muerte durante la Batalla de Yavin en Una Nueva Esperanza. Esta minifigura LEGO presenta la clásica cabeza amarilla, impresión de torso de traje de vuelo naranja y blanco, accesorio de casco blanco y caderas gris oscuro representando el uniforme de piloto de bombardero Y-wing. Lanzada en 1999 con el set Y-Wing Fighter original 7150, esta versión captura a Gold Leader quien hizo el famoso intento de carrera en la trinchera antes del ataque exitoso de Luke Skywalker. La designación de Gold Leader y estatus como piloto Y-wing temprano hacen de esta minifigura valiosa para coleccionistas recreando el asalto a la Estrella de la Muerte y construyendo estructuras de comando de escuadrón rebelde completas.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 004 (sw0024-sw0033) - 10 minifigs...\n');

  for (const m of batch) {
    await prisma.minifigCatalog.update({
      where: { minifigure_no: m.no },
      data: {
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`  ✅ ${m.no}: ${m.name}`);
  }

  console.log('\n✨ Batch 004 complete: 10 minifigs (40 descriptions)');
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
