import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0060',
    name: 'Count Dooku - Light Gray Smooth Hair, Brown Cape',
    en: 'Count Dooku with Light Gray Smooth Hair and Brown Cape represents the former Jedi Master turned Sith Lord who became the public face of the Separatist movement during the Clone Wars. This LEGO minifigure features Count Dooku with light gray smooth hair piece, brown cape, dark robes, and the distinguished appearance of the elegant Sith apprentice to Darth Sidious. Released in 2002 with the Jedi Duel set 7103, this version captures the aristocratic villain who wielded a curved lightsaber and orchestrated major battles throughout Attack of the Clones. The smooth hair design and early Count Dooku release make this minifigure highly valuable for collectors seeking complete Sith Lord collections and prequel trilogy villains.',
    de: 'Graf Dooku mit hellgrauem glattem Haar und braunem Umhang repräsentiert den ehemaligen Jedi-Meister, der zum Sith-Lord wurde und das öffentliche Gesicht der Separatisten-Bewegung während der Klonkriege wurde. Diese LEGO Minifigur zeigt Graf Dooku mit hellgrauem glattem Haarteil, braunem Umhang, dunklen Roben und dem vornehmen Aussehen des eleganten Sith-Schülers von Darth Sidious. Veröffentlicht 2002 mit dem Jedi Duel-Set 7103, fängt diese Version den aristokratischen Bösewicht ein, der ein gebogenes Lichtschwert führte und große Schlachten während Angriff der Klonkrieger orchestrierte. Das glatte Haar-Design und die frühe Graf Dooku-Veröffentlichung machen diese Minifigur sehr wertvoll für Sammler, die vollständige Sith-Lord-Sammlungen und Prequel-Trilogie-Bösewichte suchen.',
    fr: 'Comte Dooku avec Cheveux Lisses Gris Clair et Cape Brune représente l\'ancien Maître Jedi devenu Seigneur Sith qui est devenu le visage public du mouvement séparatiste pendant les Guerres des Clones. Cette minifigurine LEGO présente le Comte Dooku avec pièce de cheveux lisses gris clair, cape brune, robes sombres et l\'apparence distinguée de l\'apprenti Sith élégant de Dark Sidious. Sortie en 2002 avec le set Jedi Duel 7103, cette version capture le méchant aristocratique qui maniait un sabre laser courbé et a orchestré des batailles majeures tout au long de L\'Attaque des Clones. Le design de cheveux lisses et la sortie précoce du Comte Dooku rendent cette minifigurine très précieuse pour les collectionneurs recherchant des collections complètes de Seigneurs Sith et des méchants de la trilogie préquelle.',
    es: 'Conde Dooku con Cabello Liso Gris Claro y Capa Marrón representa al ex Maestro Jedi convertido en Señor Sith quien se convirtió en el rostro público del movimiento separatista durante las Guerras Clon. Esta minifigura LEGO presenta al Conde Dooku con pieza de cabello liso gris claro, capa marrón, túnicas oscuras y la apariencia distinguida del elegante aprendiz Sith de Darth Sidious. Lanzada en 2002 con el set Jedi Duel 7103, esta versión captura al villano aristocrático quien empuñó un sable de luz curvo y orquestó batallas importantes a lo largo de El Ataque de los Clones. El diseño de cabello liso y lanzamiento temprano del Conde Dooku hacen de esta minifigura muy valiosa para coleccionistas buscando colecciones completas de Señores Sith y villanos de trilogía de precuelas.'
  },
  {
    no: 'sw0099',
    name: 'Anakin Skywalker (Padawan) - Yellow Head, Cape',
    en: 'Anakin Skywalker Padawan with Yellow Head and Cape represents the young Jedi apprentice to Obi-Wan Kenobi during Attack of the Clones before his fall to the dark side. This LEGO minifigure features the classic yellow head, Padawan braid hairstyle, brown Jedi robes with cape, and the appearance of the talented but troubled youth who would become Darth Vader. Released in 2002 with prequel sets, this version captures Anakin during his formative years as a Jedi learning the ways of the Force while struggling with forbidden attachment to Padmé. The Padawan rank and cape design make this minifigure valuable for collectors documenting Anakin\'s tragic transformation and building complete character progression displays.',
    de: 'Anakin Skywalker Padawan mit gelbem Kopf und Umhang repräsentiert den jungen Jedi-Lehrling von Obi-Wan Kenobi während Angriff der Klonkrieger vor seinem Fall zur dunklen Seite. Diese LEGO Minifigur zeigt den klassischen gelben Kopf, Padawan-Zopf-Frisur, braune Jedi-Roben mit Umhang und das Aussehen des talentierten aber geplagten Jugendlichen, der Darth Vader werden würde. Veröffentlicht 2002 mit Prequel-Sets, fängt diese Version Anakin während seiner prägenden Jahre als Jedi ein, der die Wege der Macht lernt während er mit verbotener Bindung zu Padmé kämpft. Der Padawan-Rang und das Umhang-Design machen diese Minifigur wertvoll für Sammler, die Anakins tragische Transformation dokumentieren und vollständige Charakterprogression-Displays aufbauen.',
    fr: 'Anakin Skywalker Padawan avec Tête Jaune et Cape représente le jeune apprenti Jedi d\'Obi-Wan Kenobi pendant L\'Attaque des Clones avant sa chute vers le côté obscur. Cette minifigurine LEGO présente la tête jaune classique, coiffure de tresse de Padawan, robes Jedi brunes avec cape et l\'apparence du jeune talentueux mais troublé qui deviendrait Dark Vador. Sortie en 2002 avec les sets préquels, cette version capture Anakin pendant ses années formatrices comme Jedi apprenant les voies de la Force tout en luttant avec l\'attachement interdit à Padmé. Le rang de Padawan et le design de cape rendent cette minifigurine précieuse pour les collectionneurs documentant la transformation tragique d\'Anakin et construisant des affichages complets de progression de personnage.',
    es: 'Anakin Skywalker Padawan con Cabeza Amarilla y Capa representa al joven aprendiz Jedi de Obi-Wan Kenobi durante El Ataque de los Clones antes de su caída al lado oscuro. Esta minifigura LEGO presenta la clásica cabeza amarilla, peinado de trenza Padawan, túnicas Jedi marrones con capa y la apariencia del joven talentoso pero atormentado quien se convertiría en Darth Vader. Lanzada en 2002 con sets de precuelas, esta versión captura a Anakin durante sus años formativos como Jedi aprendiendo los caminos de la Fuerza mientras lucha con el apego prohibido a Padmé. El rango Padawan y diseño de capa hacen de esta minifigura valiosa para coleccionistas documentando la transformación trágica de Anakin y construyendo exhibiciones completas de progresión de personaje.'
  },
  {
    no: 'sw0068',
    name: 'Luke Skywalker with Black Right Hand (Final Duel II)',
    en: 'Luke Skywalker with Black Right Hand represents the crucial moment during the final duel with Darth Vader in Return of the Jedi when Luke\'s cybernetic hand is revealed. This LEGO minifigure features Luke in his black Jedi robes with distinctive black right hand piece showing the mechanical prosthetic exposed during battle. Released in 2003 with Cloud City set 10123, this version captures the pivotal scene where Luke realizes his similarity to his father and chooses mercy over revenge. The black right hand detail makes this minifigure essential for collectors recreating the throne room duel and understanding Luke\'s character development during the original trilogy\'s climax.',
    de: 'Luke Skywalker mit schwarzer rechter Hand repräsentiert den entscheidenden Moment während des finalen Duells mit Darth Vader in Die Rückkehr der Jedi-Ritter, als Lukes kybernetische Hand enthüllt wird. Diese LEGO Minifigur zeigt Luke in seinen schwarzen Jedi-Roben mit charakteristischem schwarzem rechten Hand-Teil, das die mechanische Prothese zeigt, die während der Schlacht freigelegt wurde. Veröffentlicht 2003 mit Cloud City-Set 10123, fängt diese Version die entscheidende Szene ein, wo Luke seine Ähnlichkeit zu seinem Vater erkennt und Gnade über Rache wählt. Das schwarze rechte Hand-Detail macht diese Minifigur wesentlich für Sammler, die das Thronsaal-Duell nachstellen und Lukes Charakterentwicklung während des Höhepunkts der ursprünglichen Trilogie verstehen.',
    fr: 'Luke Skywalker avec Main Droite Noire représente le moment crucial pendant le duel final avec Dark Vador dans Le Retour du Jedi lorsque la main cybernétique de Luke est révélée. Cette minifigurine LEGO présente Luke dans ses robes Jedi noires avec pièce de main droite noire distinctive montrant la prothèse mécanique exposée pendant la bataille. Sortie en 2003 avec le set Cloud City 10123, cette version capture la scène pivot où Luke réalise sa similitude avec son père et choisit la miséricorde plutôt que la vengeance. Le détail de main droite noire rend cette minifigurine essentielle pour les collectionneurs recréant le duel de la salle du trône et comprenant le développement du personnage de Luke pendant le point culminant de la trilogie originale.',
    es: 'Luke Skywalker con Mano Derecha Negra representa el momento crucial durante el duelo final con Darth Vader en El Retorno del Jedi cuando se revela la mano cibernética de Luke. Esta minifigura LEGO presenta a Luke en sus túnicas Jedi negras con distintiva pieza de mano derecha negra mostrando la prótesis mecánica expuesta durante la batalla. Lanzada en 2003 con el set Cloud City 10123, esta versión captura la escena pivotal donde Luke se da cuenta de su similitud con su padre y elige misericordia sobre venganza. El detalle de mano derecha negra hace de esta minifigura esencial para coleccionistas recreando el duelo de la sala del trono y entendiendo el desarrollo del personaje de Luke durante el clímax de la trilogía original.'
  },
  {
    no: 'sw0070',
    name: 'Princess Leia - Jabba Slave Outfit, Yellow Skin, Neck Bracket',
    en: 'Princess Leia in Jabba Slave Outfit with Yellow Skin and Neck Bracket represents the rebel leader during her captivity at Jabba the Hutt\'s palace in Return of the Jedi. This LEGO minifigure features the classic yellow skin, distinctive slave outfit torso print, and neck bracket accessory representing the chain. Released in 2003 with Jabba\'s Palace sets, this version captures one of Leia\'s most iconic and memorable costume appearances from the original trilogy. The slave outfit design with neck bracket makes this minifigure notable for collectors building complete Jabba\'s Palace displays and seeking all Princess Leia costume variations throughout the saga.',
    de: 'Prinzessin Leia im Jabba-Sklaven-Outfit mit gelber Haut und Hals-Klammer repräsentiert die Rebellenführerin während ihrer Gefangenschaft in Jabba des Hutts Palast in Die Rückkehr der Jedi-Ritter. Diese LEGO Minifigur zeigt die klassische gelbe Haut, charakteristischen Sklaven-Outfit-Torso-Druck und Hals-Klammer-Zubehör, das die Kette repräsentiert. Veröffentlicht 2003 mit Jabba\'s Palace-Sets, fängt diese Version eines von Leias ikonischsten und einprägsamsten Kostüm-Erscheinungen aus der ursprünglichen Trilogie ein. Das Sklaven-Outfit-Design mit Hals-Klammer macht diese Minifigur bemerkenswert für Sammler, die vollständige Jabba\'s Palace-Displays bauen und alle Prinzessin Leia-Kostüm-Variationen während der Saga suchen.',
    fr: 'Princesse Leia en Tenue d\'Esclave de Jabba avec Peau Jaune et Bracelet de Cou représente la leader rebelle pendant sa captivité au palais de Jabba le Hutt dans Le Retour du Jedi. Cette minifigurine LEGO présente la peau jaune classique, impression de torse de tenue d\'esclave distinctive et accessoire de bracelet de cou représentant la chaîne. Sortie en 2003 avec les sets Jabba\'s Palace, cette version capture l\'une des apparences de costume les plus emblématiques et mémorables de Leia de la trilogie originale. Le design de tenue d\'esclave avec bracelet de cou rend cette minifigurine notable pour les collectionneurs construisant des affichages complets de Jabba\'s Palace et recherchant toutes les variations de costumes de Princesse Leia tout au long de la saga.',
    es: 'Princesa Leia en Atuendo de Esclava de Jabba con Piel Amarilla y Brazalete de Cuello representa a la líder rebelde durante su cautiverio en el palacio de Jabba el Hutt en El Retorno del Jedi. Esta minifigura LEGO presenta la clásica piel amarilla, distintiva impresión de torso de atuendo de esclava y accesorio de brazalete de cuello representando la cadena. Lanzada en 2003 con sets de Jabba\'s Palace, esta versión captura una de las apariencias de vestuario más icónicas y memorables de Leia de la trilogía original. El diseño de atuendo de esclava con brazalete de cuello hace de esta minifigura notable para coleccionistas construyendo exhibiciones completas de Jabba\'s Palace y buscando todas las variaciones de vestuario de Princesa Leia a lo largo de la saga.'
  },
  {
    no: 'sw0071',
    name: 'Jabba the Hutt - Sand Green',
    en: 'Jabba the Hutt in Sand Green represents the notorious crime lord who controlled the criminal underworld on Tatooine and enslaved Princess Leia in Return of the Jedi. This LEGO minifigure features Jabba\'s massive sand green slug-like body design, distinctive face with yellow eyes, and the imposing appearance of the most powerful gangster in the galaxy. Released in 2003 with the Jabba\'s Prize set 4476, this version captures the vile Hutt who met his end at Leia\'s hands aboard his sail barge. The large specialized build and iconic villain status make this minifigure extremely valuable for collectors recreating Jabba\'s Palace scenes and building complete Return of the Jedi displays.',
    de: 'Jabba der Hutt in Sandgrün repräsentiert den berüchtigten Verbrecherlord, der die kriminelle Unterwelt auf Tatooine kontrollierte und Prinzessin Leia in Die Rückkehr der Jedi-Ritter versklavte. Diese LEGO Minifigur zeigt Jabbas massiven sandgrünen schneckenartigen Körper-Design, charakteristisches Gesicht mit gelben Augen und das imposante Aussehen des mächtigsten Gangsters in der Galaxie. Veröffentlicht 2003 mit dem Jabba\'s Prize-Set 4476, fängt diese Version den niederträchtigen Hutt ein, der sein Ende durch Leias Hände an Bord seiner Segelbarke fand. Die große spezialisierte Bauweise und der ikonische Bösewicht-Status machen diese Minifigur extrem wertvoll für Sammler, die Jabba\'s Palace-Szenen nachstellen und vollständige Die-Rückkehr-der-Jedi-Ritter-Displays aufbauen.',
    fr: 'Jabba le Hutt en Vert Sable représente le seigneur du crime notoire qui contrôlait le monde criminel sur Tatooine et a asservi la Princesse Leia dans Le Retour du Jedi. Cette minifigurine LEGO présente le design de corps massif en forme de limace vert sable de Jabba, visage distinctif avec yeux jaunes et l\'apparence imposante du gangster le plus puissant de la galaxie. Sortie en 2003 avec le set Jabba\'s Prize 4476, cette version capture le Hutt vil qui a trouvé sa fin aux mains de Leia à bord de sa barge à voile. La grande construction spécialisée et le statut de méchant emblématique rendent cette minifigurine extrêmement précieuse pour les collectionneurs recréant des scènes de Jabba\'s Palace et construisant des affichages complets du Retour du Jedi.',
    es: 'Jabba el Hutt en Verde Arena representa al notorio señor del crimen quien controló el submundo criminal en Tatooine y esclavizó a la Princesa Leia en El Retorno del Jedi. Esta minifigura LEGO presenta el masivo diseño de cuerpo tipo babosa verde arena de Jabba, rostro distintivo con ojos amarillos y la apariencia imponente del gánster más poderoso de la galaxia. Lanzada en 2003 con el set Jabba\'s Prize 4476, esta versión captura al vil Hutt quien encontró su final a manos de Leia a bordo de su barcaza de vela. La gran construcción especializada y estatus de villano icónico hacen de esta minifigura extremadamente valiosa para coleccionistas recreando escenas de Jabba\'s Palace y construyendo exhibiciones completas de El Retorno del Jedi.'
  },
  {
    no: 'sw0072',
    name: 'EV-9D9',
    en: 'EV-9D9 represents the sadistic supervisor droid who tortured other droids in Jabba the Hutt\'s palace in Return of the Jedi. This LEGO minifigure features EV-9D9\'s distinctive dark torso design, red optical sensors, and the menacing appearance of the droid overseer who assigned C-3PO and R2-D2 to their duties. Released in 2003 with Jabba\'s Palace sets, this version captures the cruel droid known for taking pleasure in the suffering of other mechanical beings. The unique character design and connection to Jabba\'s Palace scenes make this minifigure valuable for collectors seeking complete droid collections and building authentic palace interior displays.',
    de: 'EV-9D9 repräsentiert den sadistischen Aufseher-Droiden, der andere Droiden in Jabba des Hutts Palast in Die Rückkehr der Jedi-Ritter folterte. Diese LEGO Minifigur zeigt EV-9D9s charakteristisches dunkles Torso-Design, rote optische Sensoren und das bedrohliche Aussehen des Droiden-Aufsehers, der C-3PO und R2-D2 ihre Pflichten zuwies. Veröffentlicht 2003 mit Jabba\'s Palace-Sets, fängt diese Version den grausamen Droiden ein, der dafür bekannt ist, Vergnügen am Leiden anderer mechanischer Wesen zu finden. Das einzigartige Charakter-Design und die Verbindung zu Jabba\'s Palace-Szenen machen diese Minifigur wertvoll für Sammler, die vollständige Droiden-Sammlungen suchen und authentische Palast-Innenraum-Displays aufbauen.',
    fr: 'EV-9D9 représente le droïde superviseur sadique qui torturait d\'autres droïdes dans le palais de Jabba le Hutt dans Le Retour du Jedi. Cette minifigurine LEGO présente le design de torse sombre distinctif d\'EV-9D9, capteurs optiques rouges et l\'apparence menaçante du droïde surveillant qui a assigné C-3PO et R2-D2 à leurs tâches. Sortie en 2003 avec les sets Jabba\'s Palace, cette version capture le droïde cruel connu pour prendre plaisir à la souffrance d\'autres êtres mécaniques. Le design de personnage unique et la connexion aux scènes de Jabba\'s Palace rendent cette minifigurine précieuse pour les collectionneurs recherchant des collections complètes de droïdes et construisant des affichages intérieurs de palais authentiques.',
    es: 'EV-9D9 representa al droide supervisor sádico quien torturó a otros droides en el palacio de Jabba el Hutt en El Retorno del Jedi. Esta minifigura LEGO presenta el distintivo diseño de torso oscuro de EV-9D9, sensores ópticos rojos y la apariencia amenazante del droide supervisor quien asignó a C-3PO y R2-D2 a sus deberes. Lanzada en 2003 con sets de Jabba\'s Palace, esta versión captura al droide cruel conocido por tomar placer en el sufrimiento de otros seres mecánicos. El diseño de personaje único y conexión con escenas de Jabba\'s Palace hacen de esta minifigura valiosa para coleccionistas buscando colecciones completas de droides y construyendo exhibiciones auténticas de interiores de palacio.'
  },
  {
    no: 'sw0073',
    name: 'Gonk Droid (GNK Power Droid), Light and Dark Gray',
    en: 'Gonk Droid GNK Power Droid in Light and Dark Gray represents the walking battery units used throughout the galaxy to provide mobile power for equipment and vehicles. This LEGO minifigure features the distinctive rectangular box-shaped body in light and dark gray colors, simple legs, and the iconic appearance of the beloved utilitarian droid. Released in 2003 with Sandcrawler and other sets, this version captures the simple but memorable power droids seen waddling through Tatooine and other locations. The box-shaped design and cult favorite status among fans make this minifigure valuable for collectors building complete droid rosters and adding background details to Star Wars displays.',
    de: 'Gonk-Droide GNK Power-Droide in Hell- und Dunkelgrau repräsentiert die gehenden Batterie-Einheiten, die in der gesamten Galaxie verwendet werden, um mobile Energie für Ausrüstung und Fahrzeuge bereitzustellen. Diese LEGO Minifigur zeigt den charakteristischen rechteckigen kastenförmigen Körper in hell- und dunkelgrauen Farben, einfache Beine und das ikonische Aussehen des geliebten Nutz-Droiden. Veröffentlicht 2003 mit Sandcrawler und anderen Sets, fängt diese Version die einfachen aber einprägsamen Power-Droiden ein, die durch Tatooine und andere Orte watscheln. Das kastenförmige Design und der Kultfavoriten-Status unter Fans machen diese Minifigur wertvoll für Sammler, die vollständige Droiden-Kader aufbauen und Hintergrund-Details zu Star Wars-Displays hinzufügen.',
    fr: 'Droïde Gonk Droïde d\'Alimentation GNK en Gris Clair et Foncé représente les unités de batterie marchantes utilisées dans toute la galaxie pour fournir de l\'énergie mobile pour l\'équipement et les véhicules. Cette minifigurine LEGO présente le corps en forme de boîte rectangulaire distinctif en couleurs gris clair et foncé, jambes simples et l\'apparence emblématique du droïde utilitaire bien-aimé. Sortie en 2003 avec Sandcrawler et d\'autres sets, cette version capture les droïdes d\'alimentation simples mais mémorables vus se dandinant à travers Tatooine et d\'autres emplacements. Le design en forme de boîte et le statut de favori culte parmi les fans rendent cette minifigurine précieuse pour les collectionneurs construisant des listes complètes de droïdes et ajoutant des détails d\'arrière-plan aux affichages Star Wars.',
    es: 'Droide Gonk Droide de Energía GNK en Gris Claro y Oscuro representa a las unidades de batería ambulantes usadas a través de la galaxia para proporcionar energía móvil para equipo y vehículos. Esta minifigura LEGO presenta el distintivo cuerpo en forma de caja rectangular en colores gris claro y oscuro, piernas simples y la apariencia icónica del querido droide utilitario. Lanzada en 2003 con Sandcrawler y otros sets, esta versión captura a los droides de energía simples pero memorables vistos bamboleándose a través de Tatooine y otras ubicaciones. El diseño en forma de caja y estatus de favorito de culto entre fanáticos hacen de esta minifigura valiosa para coleccionistas construyendo listas completas de droides y agregando detalles de fondo a exhibiciones Star Wars.'
  },
  {
    no: 'sw0074',
    name: 'B\'Omarr Monk - Trans-Neon Orange Plate',
    en: 'B\'Omarr Monk with Trans-Neon Orange Plate represents the mysterious brain-in-jar monks who inhabited Jabba\'s Palace before the Hutt crime lord took over the monastery in Return of the Jedi. This LEGO minifigure features the distinctive transparent neon orange plate showing the monk\'s brain, spider-like droid walker body, and the eerie appearance of the ascetic order who removed their bodies. Released in 2003 with Jabba\'s Palace sets, this version captures one of the most unusual and unsettling creatures from the Star Wars universe. The transparent brain jar design makes this minifigure extremely valuable for collectors seeking exotic alien species and complete Jabba\'s Palace inhabitant collections.',
    de: 'B\'Omarr-Mönch mit Trans-Neon-Orange-Platte repräsentiert die geheimnisvollen Gehirn-im-Glas-Mönche, die Jabba\'s Palace bewohnten, bevor der Hutt-Verbrecherlord das Kloster in Die Rückkehr der Jedi-Ritter übernahm. Diese LEGO Minifigur zeigt die charakteristische transparente neon-orange Platte, die das Gehirn des Mönchs zeigt, spinnenartigen Droiden-Walker-Körper und das unheimliche Aussehen des asketischen Ordens, der ihre Körper entfernte. Veröffentlicht 2003 mit Jabba\'s Palace-Sets, fängt diese Version eine der ungewöhnlichsten und beunruhigendsten Kreaturen aus dem Star Wars-Universum ein. Das transparente Gehirnglas-Design macht diese Minifigur extrem wertvoll für Sammler, die exotische außerirdische Spezies und vollständige Jabba\'s Palace-Bewohner-Sammlungen suchen.',
    fr: 'Moine B\'Omarr avec Plaque Trans-Néon Orange représente les moines mystérieux cerveau-dans-bocal qui habitaient Jabba\'s Palace avant que le seigneur du crime Hutt ne prenne le monastère dans Le Retour du Jedi. Cette minifigurine LEGO présente la plaque transparente néon orange distinctive montrant le cerveau du moine, corps de marcheur droïde en forme d\'araignée et l\'apparence sinistre de l\'ordre ascétique qui a retiré leurs corps. Sortie en 2003 avec les sets Jabba\'s Palace, cette version capture l\'une des créatures les plus inhabituelles et troublantes de l\'univers Star Wars. Le design de bocal à cerveau transparent rend cette minifigurine extrêmement précieuse pour les collectionneurs recherchant des espèces extraterrestres exotiques et des collections complètes d\'habitants de Jabba\'s Palace.',
    es: 'Monje B\'Omarr con Placa Trans-Neón Naranja representa a los misteriosos monjes cerebro-en-frasco quienes habitaron Jabba\'s Palace antes de que el señor del crimen Hutt tomara el monasterio en El Retorno del Jedi. Esta minifigura LEGO presenta la distintiva placa transparente neón naranja mostrando el cerebro del monje, cuerpo de caminante droide tipo araña y la apariencia espeluznante de la orden ascética que removió sus cuerpos. Lanzada en 2003 con sets de Jabba\'s Palace, esta versión captura a una de las criaturas más inusuales e inquietantes del universo Star Wars. El diseño de frasco de cerebro transparente hace de esta minifigura extremadamente valiosa para coleccionistas buscando especies alienígenas exóticas y colecciones completas de habitantes de Jabba\'s Palace.'
  },
  {
    no: 'sw0075',
    name: 'Gamorrean Guard - Sand Green, Dark Gray Arms',
    en: 'Gamorrean Guard with Sand Green body and Dark Gray Arms represents the brutish porcine guards who served as enforcers and soldiers for Jabba the Hutt in Return of the Jedi. This LEGO minifigure features the sand green torso and head with pig-like facial features, dark gray arms, brown skirt piece, and battle axe accessory representing the fierce palace guards. Released in 2003 with Jabba\'s Palace sets, this version captures the intimidating warriors who battled Luke Skywalker above the Sarlacc pit. The sand green and dark gray color combination makes this minifigure valuable for collectors army-building Jabba\'s guard forces and recreating authentic palace security details.',
    de: 'Gamorreaner-Wache mit sandgrünem Körper und dunkelgrauen Armen repräsentiert die brutalen schweineartigen Wachen, die als Vollstrecker und Soldaten für Jabba den Hutt in Die Rückkehr der Jedi-Ritter dienten. Diese LEGO Minifigur zeigt den sandgrünen Torso und Kopf mit schweineartigen Gesichtszügen, dunkelgraue Arme, braunes Rock-Teil und Streitaxt-Zubehör, das die wilden Palastwachen repräsentiert. Veröffentlicht 2003 mit Jabba\'s Palace-Sets, fängt diese Version die einschüchternden Krieger ein, die gegen Luke Skywalker über der Sarlacc-Grube kämpften. Die sandgrün-dunkelgraue Farbkombination macht diese Minifigur wertvoll für Sammler, die Jabbas Wach-Streitkräfte für Armeen zusammenstellen und authentische Palast-Sicherheitsdetails nachstellen.',
    fr: 'Garde Gamorréen avec Corps Vert Sable et Bras Gris Foncé représente les gardes porcins brutaux qui ont servi comme exécuteurs et soldats pour Jabba le Hutt dans Le Retour du Jedi. Cette minifigurine LEGO présente le torse et la tête vert sable avec traits faciaux porcins, bras gris foncé, pièce de jupe brune et accessoire de hache de bataille représentant les gardes de palais féroces. Sortie en 2003 avec les sets Jabba\'s Palace, cette version capture les guerriers intimidants qui ont combattu Luke Skywalker au-dessus de la fosse de Sarlacc. La combinaison de couleurs vert sable et gris foncé rend cette minifigurine précieuse pour les collectionneurs assemblant les forces de garde de Jabba et recréant des détails de sécurité de palais authentiques.',
    es: 'Guardia Gamorreano con Cuerpo Verde Arena y Brazos Gris Oscuro representa a los guardias porcinos brutales quienes sirvieron como ejecutores y soldados para Jabba el Hutt en El Retorno del Jedi. Esta minifigura LEGO presenta el torso y cabeza verde arena con rasgos faciales tipo cerdo, brazos gris oscuro, pieza de falda marrón y accesorio de hacha de batalla representando a los feroces guardias de palacio. Lanzada en 2003 con sets de Jabba\'s Palace, esta versión captura a los guerreros intimidantes quienes batallaron contra Luke Skywalker sobre el pozo Sarlacc. La combinación de colores verde arena y gris oscuro hace de esta minifigura valiosa para coleccionistas ensamblando fuerzas de guardia de Jabba y recreando detalles auténticos de seguridad de palacio.'
  },
  {
    no: 'sw0076',
    name: 'Bib Fortuna - Dark Blue Robe, Tan Skin',
    en: 'Bib Fortuna with Dark Blue Robe and Tan Skin represents Jabba the Hutt\'s Twi\'lek majordomo and chief aide who managed the crime lord\'s palace and operations in Return of the Jedi. This LEGO minifigure features Bib Fortuna\'s distinctive tan skin color, long lekku head-tails, dark blue robe torso print, and the sinister appearance of Jabba\'s most trusted servant. Released in 2003 with Jabba\'s Palace sets, this version captures the scheming administrator who later took over Jabba\'s criminal empire after the Hutt\'s death. The dark blue robe variant and important character status make this minifigure valuable for collectors building complete Jabba\'s Palace court hierarchies and Twi\'lek character collections.',
    de: 'Bib Fortuna mit dunkelblauer Robe und beigefarbener Haut repräsentiert Jabba des Hutts Twi\'lek-Majordomus und Hauptberater, der den Palast und die Operationen des Verbrecherlords in Die Rückkehr der Jedi-Ritter verwaltete. Diese LEGO Minifigur zeigt BibFortunas charakteristische beigefarbene Hautfarbe, lange Lekku-Kopfschwänze, dunkelblauen Roben-Torso-Druck und das finstere Aussehen von Jabbas vertrauenswerdigstem Diener. Veröffentlicht 2003 mit Jabba\'s Palace-Sets, fängt diese Version den intriganten Administrator ein, der später Jabbas kriminelles Imperium nach dem Tod des Hutts übernahm. Die dunkelblaue Roben-Variante und der wichtige Charakter-Status machen diese Minifigur wertvoll für Sammler, die vollständige Jabba\'s Palace-Hof-Hierarchien und Twi\'lek-Charakter-Sammlungen aufbauen.',
    fr: 'Bib Fortuna avec Robe Bleue Foncée et Peau Beige représente le majordome Twi\'lek de Jabba le Hutt et assistant en chef qui gérait le palais et les opérations du seigneur du crime dans Le Retour du Jedi. Cette minifigurine LEGO présente la couleur de peau beige distinctive de Bib Fortuna, longs lekku queues de tête, impression de torse de robe bleue foncée et l\'apparence sinistre du serviteur le plus fiable de Jabba. Sortie en 2003 avec les sets Jabba\'s Palace, cette version capture l\'administrateur intrigant qui a plus tard pris le contrôle de l\'empire criminel de Jabba après la mort du Hutt. La variante de robe bleue foncée et le statut de personnage important rendent cette minifigurine précieuse pour les collectionneurs construisant des hiérarchies de cour complètes de Jabba\'s Palace et des collections de personnages Twi\'lek.',
    es: 'Bib Fortuna con Túnica Azul Oscuro y Piel Beige representa al mayordomo Twi\'lek de Jabba el Hutt y asistente principal quien manejó el palacio y operaciones del señor del crimen en El Retorno del Jedi. Esta minifigura LEGO presenta el distintivo color de piel beige de Bib Fortuna, largos lekku colas de cabeza, impresión de torso de túnica azul oscuro y la apariencia siniestra del sirviente más confiable de Jabba. Lanzada en 2003 con sets de Jabba\'s Palace, esta versión captura al administrador intrigante quien más tarde tomó el imperio criminal de Jabba después de la muerte del Hutt. La variante de túnica azul oscuro y estatus de personaje importante hacen de esta minifigura valiosa para coleccionistas construyendo jerarquías completas de corte de Jabba\'s Palace y colecciones de personajes Twi\'lek.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 008 (sw0060-sw0076) - 10 minifigs...\n');

  for (const m of batch) {
    try {
      await prisma.minifigCatalog.update({
        where: { minifigure_no: m.no },
        data: {
          description_en: m.en,
          description_de: m.de,
          description_fr: m.fr,
          description_es: m.es,
          description_generated_at: new Date(),
          description_status: 'generated'
        }
      });
      console.log(`  ✅ ${m.no}: ${m.name}`);
    } catch (error: any) {
      console.log(`  ⚠️  ${m.no}: NOT IN DATABASE (skipped)`);
    }
  }

  console.log('\n✨ Batch 008 complete: 10 minifigs (40 descriptions)');
  await prisma.$disconnect();
}

saveBatch().catch(console.error);
