import { PrismaClient } from '@prisma/client-hostinger';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL || 'mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker'
});

const batch = [
  {
    no: 'sw0244',
    name: 'Mace Windu',
    en: 'Mace Windu\'s LEGO minifigure captures the powerful Jedi Master with his distinctive bald head, stern expression, and the iconic purple lightsaber that makes him instantly recognizable among Jedi warriors. This minifigure features detailed printing showing his traditional brown Jedi robes with tabards, representing the head of the Jedi Council and one of the Order\'s most formidable combatants. As the master of Form VII lightsaber combat and a key military leader during the Clone Wars, Windu\'s tactical brilliance and unwavering dedication to the Jedi Code defined his character throughout the prequel trilogy. Released in numerous sets from 2005 onwards with Clone Wars variants appearing from 2008, this minifigure remains highly collectible due to Mace Windu\'s pivotal role in attempting to stop Palpatine\'s rise to power and Samuel L. Jackson\'s commanding portrayal that made the character unforgettable.',
    de: 'Die LEGO-Minifigur von Mace Windu fängt den mächtigen Jedi-Meister mit seinem markanten kahlen Kopf, strengen Ausdruck und dem ikonischen violetten Lichtschwert ein, das ihn unter Jedi-Kriegern sofort erkennbar macht. Diese Minifigur verfügt über detaillierte Bedruckung, die seine traditionellen braunen Jedi-Roben mit Wappenröcken zeigt, die das Oberhaupt des Jedi-Rats und einen der gewaltigsten Kämpfer des Ordens repräsentiert. Als Meister der Form VII-Lichtschwert-Kampfkunst und ein wichtiger militärischer Anführer während der Klonkriege definierten Windus taktische Brillanz und unerschütterliche Hingabe an den Jedi-Kodex seinen Charakter während der gesamten Prequel-Trilogie. In zahlreichen Sets ab 2005 veröffentlicht, wobei Clone Wars-Varianten ab 2008 erschienen, bleibt diese Minifigur hochgradig sammelwürdig aufgrund von Mace Windus entscheidender Rolle beim Versuch, Palpatines Machtübernahme zu stoppen, und Samuel L. Jacksons befehlender Darstellung, die den Charakter unvergesslich machte.',
    fr: 'La minifigurine LEGO de Mace Windu capture le puissant Maître Jedi avec sa tête chauve distinctive, son expression sévère, et le sabre laser violet emblématique qui le rend instantanément reconnaissable parmi les guerriers Jedi. Cette minifigurine présente une impression détaillée montrant ses robes Jedi marron traditionnelles avec tabards, représentant le chef du Conseil Jedi et l\'un des combattants les plus redoutables de l\'Ordre. En tant que maître du combat au sabre laser de Forme VII et un leader militaire clé pendant les Guerres des Clones, la brillance tactique de Windu et son dévouement inébranlable au Code Jedi ont défini son personnage tout au long de la trilogie préquelle. Sortie dans de nombreux sets à partir de 2005 avec des variantes Clone Wars apparaissant à partir de 2008, cette minifigurine reste hautement collectionnable en raison du rôle pivot de Mace Windu dans la tentative d\'arrêter l\'ascension au pouvoir de Palpatine et la représentation commandante de Samuel L. Jackson qui a rendu le personnage inoubliable.',
    es: 'La minifigura LEGO de Mace Windu captura al poderoso Maestro Jedi con su distintiva cabeza calva, expresión severa, y el icónico sable de luz morado que lo hace instantáneamente reconocible entre los guerreros Jedi. Esta minifigura presenta impresión detallada mostrando sus tradicionales túnicas Jedi marrones con tabardos, representando al líder del Consejo Jedi y uno de los combatientes más formidables de la Orden. Como maestro del combate con sable de luz Forma VII y un líder militar clave durante las Guerras Clon, la brillantez táctica de Windu y su dedicación inquebrantable al Código Jedi definieron su personaje a lo largo de la trilogía precuela. Lanzada en numerosos sets desde 2005 con variantes Clone Wars apareciendo desde 2008, esta minifigura permanece altamente coleccionable debido al papel fundamental de Mace Windu en intentar detener el ascenso al poder de Palpatine y la interpretación dominante de Samuel L. Jackson que hizo al personaje inolvidable.'
  },
  {
    no: 'sw0245',
    name: 'Kit Fisto',
    en: 'Kit Fisto\'s LEGO minifigure brings the aquatic Nautolan Jedi Master to life with his distinctive green skin tone, large black eyes, and signature head tentacles that replaced traditional hair. This minifigure features detailed printing showing his traditional Jedi robes, representing one of the Jedi Council\'s most skilled lightsaber duelists and underwater combat specialists. Known for his perpetual smile and mastery of Form I lightsaber combat, Kit Fisto served with distinction during the Clone Wars, leading amphibious assault missions and earning respect for his adaptability in diverse combat environments. Released in sets from 2007 onwards with Clone Wars variants appearing from 2008, this minifigure appeals to collectors who appreciate the diverse alien Jedi representation, with Kit Fisto\'s unique appearance and heroic participation in the attempted arrest of Chancellor Palpatine making him a memorable presence in prequel trilogy lore.',
    de: 'Die LEGO-Minifigur von Kit Fisto erweckt den aquatischen Nautolan-Jedi-Meister mit seinem markanten grünen Hautton, großen schwarzen Augen und charakteristischen Kopftentakeln, die traditionelles Haar ersetzten, zum Leben. Diese Minifigur verfügt über detaillierte Bedruckung, die seine traditionellen Jedi-Roben zeigt, die einen der geschicktesten Lichtschwert-Duellanten und Unterwasser-Kampfspezialisten des Jedi-Rats repräsentiert. Bekannt für sein immerwährendes Lächeln und seine Beherrschung der Form I-Lichtschwert-Kampfkunst, diente Kit Fisto mit Auszeichnung während der Klonkriege, führte amphibische Angriffsmissionen an und erwarb Respekt für seine Anpassungsfähigkeit in diversen Kampfumgebungen. In Sets ab 2007 veröffentlicht, wobei Clone Wars-Varianten ab 2008 erschienen, spricht diese Minifigur Sammler an, die die vielfältige außerirdische Jedi-Darstellung schätzen, wobei Kit Fistos einzigartiges Aussehen und heroische Teilnahme am versuchten Arrest von Kanzler Palpatine ihn zu einer unvergesslichen Präsenz in der Prequel-Trilogie-Überlieferung machen.',
    fr: 'La minifigurine LEGO de Kit Fisto donne vie au Maître Jedi Nautolan aquatique avec son teint de peau vert distinctif, ses grands yeux noirs, et ses tentacules de tête emblématiques qui remplaçaient les cheveux traditionnels. Cette minifigurine présente une impression détaillée montrant ses robes Jedi traditionnelles, représentant l\'un des duellistes au sabre laser les plus habiles du Conseil Jedi et spécialistes de combat sous-marin. Connu pour son sourire perpétuel et sa maîtrise du combat au sabre laser de Forme I, Kit Fisto a servi avec distinction pendant les Guerres des Clones, menant des missions d\'assaut amphibies et gagnant le respect pour son adaptabilité dans divers environnements de combat. Sortie dans des sets à partir de 2007 avec des variantes Clone Wars apparaissant à partir de 2008, cette minifigurine plaît aux collectionneurs qui apprécient la représentation diversifiée des Jedi aliens, l\'apparence unique de Kit Fisto et sa participation héroïque dans la tentative d\'arrestation du Chancelier Palpatine en faisant une présence mémorable dans la tradition de la trilogie préquelle.',
    es: 'La minifigura LEGO de Kit Fisto da vida al Maestro Jedi Nautolano acuático con su distintivo tono de piel verde, grandes ojos negros, y tentáculos de cabeza característicos que reemplazaron el cabello tradicional. Esta minifigura presenta impresión detallada mostrando sus túnicas Jedi tradicionales, representando a uno de los duelistas con sable de luz más hábiles del Consejo Jedi y especialistas en combate submarino. Conocido por su sonrisa perpetua y maestría del combate con sable de luz Forma I, Kit Fisto sirvió con distinción durante las Guerras Clon, liderando misiones de asalto anfibio y ganándose respeto por su adaptabilidad en diversos entornos de combate. Lanzada en sets desde 2007 con variantes Clone Wars apareciendo desde 2008, esta minifigura atrae a coleccionistas que aprecian la diversa representación de Jedi alienígenas, con la apariencia única de Kit Fisto y su heroica participación en el intento de arresto del Canciller Palpatine haciéndolo una presencia memorable en la tradición de la trilogía precuela.'
  },
  {
    no: 'sw0246',
    name: 'Plo Koon',
    en: 'Plo Koon\'s LEGO minifigure distinctively portrays the Kel Dor Jedi Master with his unique antiox breath mask and protective goggles that allowed him to survive in oxygen-rich environments. This minifigure features detailed printing showing his traditional brown Jedi robes and the technological apparatus that defined his alien physiology, representing one of the Jedi Council\'s most compassionate and tactically brilliant members. Known for discovering Ahsoka Tano and bringing her to the Jedi Order, Plo Koon served with distinction as a starfighter pilot and fleet commander during the Clone Wars, earning deep loyalty from the clone troopers under his command. Released in sets from 2008 onwards with Clone Wars variants, this minifigure appeals to collectors who appreciate Plo Koon\'s unique design aesthetic and his tragic fate during Order 66, where his bond with clone troopers made his betrayal particularly poignant in Star Wars lore.',
    de: 'Die LEGO-Minifigur von Plo Koon porträtiert markant den Kel Dor-Jedi-Meister mit seiner einzigartigen Antiox-Atemmaske und Schutzbrillen, die es ihm ermöglichten, in sauerstoffreichen Umgebungen zu überleben. Diese Minifigur verfügt über detaillierte Bedruckung, die seine traditionellen braunen Jedi-Roben und den technologischen Apparat zeigt, der seine außerirdische Physiologie definierte, die eines der mitfühlendsten und taktisch brillantesten Mitglieder des Jedi-Rats repräsentiert. Bekannt dafür, Ahsoka Tano entdeckt und sie zum Jedi-Orden gebracht zu haben, diente Plo Koon mit Auszeichnung als Sternenjäger-Pilot und Flottenkommandant während der Klonkriege und erwarb tiefe Loyalität von den Klontruppen unter seinem Kommando. In Sets ab 2008 veröffentlicht, wobei Clone Wars-Varianten erschienen, spricht diese Minifigur Sammler an, die Plo Koons einzigartige Design-Ästhetik und sein tragisches Schicksal während Order 66 schätzen, wo seine Bindung zu Klontruppen seinen Verrat besonders ergreifend in der Star Wars-Überlieferung machte.',
    fr: 'La minifigurine LEGO de Plo Koon dépeint distinctivement le Maître Jedi Kel Dor avec son masque respiratoire antiox unique et ses lunettes de protection qui lui permettaient de survivre dans des environnements riches en oxygène. Cette minifigurine présente une impression détaillée montrant ses robes Jedi marron traditionnelles et l\'appareil technologique qui définissait sa physiologie alien, représentant l\'un des membres les plus compatissants et tactiquement brillants du Conseil Jedi. Connu pour avoir découvert Ahsoka Tano et l\'avoir amenée à l\'Ordre Jedi, Plo Koon a servi avec distinction en tant que pilote de chasseur stellaire et commandant de flotte pendant les Guerres des Clones, gagnant une loyauté profonde des soldats clones sous son commandement. Sortie dans des sets à partir de 2008 avec des variantes Clone Wars, cette minifigurine plaît aux collectionneurs qui apprécient l\'esthétique de design unique de Plo Koon et son destin tragique pendant l\'Ordre 66, où son lien avec les soldats clones a rendu sa trahison particulièrement poignante dans la tradition Star Wars.',
    es: 'La minifigura LEGO de Plo Koon retrata distintivamente al Maestro Jedi Kel Dor con su única máscara respiratoria antiox y gafas protectoras que le permitían sobrevivir en entornos ricos en oxígeno. Esta minifigura presenta impresión detallada mostrando sus túnicas Jedi marrones tradicionales y el aparato tecnológico que definía su fisiología alienígena, representando a uno de los miembros más compasivos y tácticamente brillantes del Consejo Jedi. Conocido por descubrir a Ahsoka Tano y traerla a la Orden Jedi, Plo Koon sirvió con distinción como piloto de caza estelar y comandante de flota durante las Guerras Clon, ganándose profunda lealtad de los soldados clon bajo su mando. Lanzada en sets desde 2008 con variantes Clone Wars, esta minifigura atrae a coleccionistas que aprecian la estética de diseño única de Plo Koon y su trágico destino durante la Orden 66, donde su vínculo con los soldados clon hizo su traición particularmente conmovedora en la tradición Star Wars.'
  },
  {
    no: 'sw0247',
    name: 'Aayla Secura',
    en: 'Aayla Secura\'s LEGO minifigure captures the striking Twi\'lek Jedi Knight with her distinctive blue skin tone, head-tails (lekku), and the brown leather outfit that defined her appearance in the Clone Wars. This minifigure features detailed printing showing her unique costume design with armored elements and utility belt, representing one of the few female Jedi prominently featured in the prequel trilogy battles. Known for her exceptional combat skills and leadership of the 327th Star Corps alongside Commander Bly, Aayla Secura became a tragic figure in Star Wars lore through her death during Order 66 on Felucia. Released in sets from 2005 onwards with Clone Wars variants appearing from 2008, this minifigure remains highly collectible due to Aayla\'s distinctive visual design, her memorable presence in Revenge of the Sith, and the tragic irony of her betrayal by the clone troopers she trusted and fought alongside throughout the war.',
    de: 'Die LEGO-Minifigur von Aayla Secura fängt die auffällige Twi\'lek-Jedi-Ritterin mit ihrem markanten blauen Hautton, Kopfschwänzen (Lekku) und dem braunen Lederoutfit ein, das ihr Aussehen in den Klonkriegen definierte. Diese Minifigur verfügt über detaillierte Bedruckung, die ihr einzigartiges Kostümdesign mit gepanzerten Elementen und Gürtel zeigt, die eine der wenigen weiblichen Jedi repräsentiert, die prominent in den Prequel-Trilogie-Schlachten vorkommen. Bekannt für ihre außergewöhnlichen Kampffähigkeiten und Führung des 327. Sternencorps an der Seite von Commander Bly, wurde Aayla Secura zu einer tragischen Figur in der Star Wars-Überlieferung durch ihren Tod während Order 66 auf Felucia. In Sets ab 2005 veröffentlicht, wobei Clone Wars-Varianten ab 2008 erschienen, bleibt diese Minifigur hochgradig sammelwürdig aufgrund von Aaylas markanten visuellen Designs, ihrer unvergesslichen Präsenz in Die Rache der Sith und der tragischen Ironie ihres Verrats durch die Klontruppen, denen sie vertraute und an deren Seite sie während des gesamten Krieges kämpfte.',
    fr: 'La minifigurine LEGO d\'Aayla Secura capture la frappante Chevalier Jedi Twi\'lek avec son teint de peau bleu distinctif, ses queues de tête (lekku), et la tenue de cuir marron qui définissait son apparence dans Clone Wars. Cette minifigurine présente une impression détaillée montrant son design de costume unique avec des éléments blindés et une ceinture utilitaire, représentant l\'une des rares Jedi féminines présentées de manière proéminente dans les batailles de la trilogie préquelle. Connue pour ses compétences de combat exceptionnelles et son leadership du 327e Corps d\'Étoiles aux côtés du Commandant Bly, Aayla Secura est devenue une figure tragique dans la tradition Star Wars à travers sa mort pendant l\'Ordre 66 sur Felucia. Sortie dans des sets à partir de 2005 avec des variantes Clone Wars apparaissant à partir de 2008, cette minifigurine reste hautement collectionnable en raison du design visuel distinctif d\'Aayla, sa présence mémorable dans La Revanche des Sith, et l\'ironie tragique de sa trahison par les soldats clones en qui elle avait confiance et aux côtés desquels elle a combattu pendant toute la guerre.',
    es: 'La minifigura LEGO de Aayla Secura captura a la llamativa Caballero Jedi Twi\'lek con su distintivo tono de piel azul, colas de cabeza (lekku), y el atuendo de cuero marrón que definió su apariencia en las Guerras Clon. Esta minifigura presenta impresión detallada mostrando su diseño de vestuario único con elementos blindados y cinturón de utilidad, representando a una de las pocas Jedi femeninas destacadas prominentemente en las batallas de la trilogía precuela. Conocida por sus excepcionales habilidades de combate y liderazgo del 327° Cuerpo Estelar junto al Comandante Bly, Aayla Secura se convirtió en una figura trágica en la tradición Star Wars a través de su muerte durante la Orden 66 en Felucia. Lanzada en sets desde 2005 con variantes Clone Wars apareciendo desde 2008, esta minifigura permanece altamente coleccionable debido al distintivo diseño visual de Aayla, su memorable presencia en La Venganza de los Sith, y la trágica ironía de su traición por los soldados clon en quienes confiaba y junto a quienes luchó durante toda la guerra.'
  },
  {
    no: 'sw0248',
    name: 'Luminara Unduli',
    en: 'Luminara Unduli\'s LEGO minifigure depicts the serene Mirialan Jedi Master with her distinctive green skin tone, geometric facial tattoos, and the elaborate black headdress that covered her traditional ceremonial attire. This minifigure features detailed printing showing her dark robes with intricate patterns, representing one of the Jedi Order\'s most orthodox and disciplined members who served with distinction on the Jedi Council. Known for her strict adherence to Jedi philosophy and her role as master to Barriss Offee, Luminara demonstrated exceptional combat prowess and tactical wisdom throughout the Clone Wars, particularly during campaigns on Geonosis and Kashyyyk. Released in sets from 2005 onwards with Clone Wars variants appearing from 2008, this minifigure appeals to collectors who appreciate Luminara\'s unique cultural design elements and her representation of Jedi traditional values, with her tragic capture and imprisonment by the Empire adding layers of depth to her character in the expanded Star Wars timeline.',
    de: 'Die LEGO-Minifigur von Luminara Unduli zeigt die gelassene Mirialan-Jedi-Meisterin mit ihrem markanten grünen Hautton, geometrischen Gesichtstätowierungen und dem aufwendigen schwarzen Kopfschmuck, der ihre traditionelle zeremonielle Kleidung bedeckte. Diese Minifigur verfügt über detaillierte Bedruckung, die ihre dunklen Roben mit komplizierten Mustern zeigt, die eines der orthodoxesten und diszipliniertesten Mitglieder des Jedi-Ordens repräsentiert, das mit Auszeichnung im Jedi-Rat diente. Bekannt für ihre strikte Einhaltung der Jedi-Philosophie und ihre Rolle als Meisterin von Barriss Offee, demonstrierte Luminara außergewöhnliche Kampffähigkeiten und taktische Weisheit während der gesamten Klonkriege, besonders während Kampagnen auf Geonosis und Kashyyyk. In Sets ab 2005 veröffentlicht, wobei Clone Wars-Varianten ab 2008 erschienen, spricht diese Minifigur Sammler an, die Luminaras einzigartige kulturelle Designelemente und ihre Darstellung traditioneller Jedi-Werte schätzen, wobei ihre tragische Gefangennahme und Inhaftierung durch das Imperium ihrem Charakter in der erweiterten Star Wars-Zeitlinie Tiefenschichten hinzufügt.',
    fr: 'La minifigurine LEGO de Luminara Unduli dépeint la Maître Jedi Mirialan sereine avec son teint de peau vert distinctif, ses tatouages faciaux géométriques, et la coiffe noire élaborée qui couvrait sa tenue cérémonielle traditionnelle. Cette minifigurine présente une impression détaillée montrant ses robes sombres avec des motifs complexes, représentant l\'un des membres les plus orthodoxes et disciplinés de l\'Ordre Jedi qui a servi avec distinction au Conseil Jedi. Connue pour son adhésion stricte à la philosophie Jedi et son rôle de maître de Barriss Offee, Luminara a démontré une prouesse de combat exceptionnelle et une sagesse tactique tout au long des Guerres des Clones, particulièrement pendant les campagnes sur Geonosis et Kashyyyk. Sortie dans des sets à partir de 2005 avec des variantes Clone Wars apparaissant à partir de 2008, cette minifigurine plaît aux collectionneurs qui apprécient les éléments de design culturel uniques de Luminara et sa représentation des valeurs traditionnelles Jedi, sa capture tragique et son emprisonnement par l\'Empire ajoutant des couches de profondeur à son personnage dans la chronologie élargie de Star Wars.',
    es: 'La minifigura LEGO de Luminara Unduli representa a la serena Maestra Jedi Mirialan con su distintivo tono de piel verde, tatuajes faciales geométricos, y el elaborado tocado negro que cubría su atuendo ceremonial tradicional. Esta minifigura presenta impresión detallada mostrando sus túnicas oscuras con patrones intrincados, representando a uno de los miembros más ortodoxos y disciplinados de la Orden Jedi que sirvió con distinción en el Consejo Jedi. Conocida por su estricta adherencia a la filosofía Jedi y su papel como maestra de Barriss Offee, Luminara demostró excepcional destreza en combate y sabiduría táctica durante todas las Guerras Clon, particularmente durante campañas en Geonosis y Kashyyyk. Lanzada en sets desde 2005 con variantes Clone Wars apareciendo desde 2008, esta minifigura atrae a coleccionistas que aprecian los elementos de diseño cultural únicos de Luminara y su representación de valores tradicionales Jedi, con su trágica captura y encarcelamiento por el Imperio añadiendo capas de profundidad a su personaje en la línea temporal expandida de Star Wars.'
  }
];

async function saveBatch() {
  console.log('💾 Saving batch 136-140 (sw0244-sw0248)...\n');

  for (const m of batch) {
    await prisma.minifigCatalog.upsert({
      where: { minifigure_no: m.no },
      update: {
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      },
      create: {
        minifigure_no: m.no,
        name: m.name,
        category_id: 1,
        category_name: 'Star Wars',
        search_name: m.name.toLowerCase(),
        description_en: m.en,
        description_de: m.de,
        description_fr: m.fr,
        description_es: m.es,
        description_generated_at: new Date(),
        description_status: 'generated'
      }
    });
    console.log(`  ✅ ${m.no}: ${m.name}`);
  }

  console.log('\n✨ Batch 136-140 complete: 5 minifigs (20 descriptions)');
  await prisma.$disconnect();
}

saveBatch().catch(console.error);