import { PrismaClient as PrismaClientHostinger } from '@prisma/client';

const prisma = new PrismaClientHostinger({
  datasources: {
    db: {
      url: "mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker"
    }
  }
});

const descriptions = [
  {
    minifigure_no: 'sh0452',
    description_en: "Batman, Space Batsuit launches the Dark Knight into cosmic adventures from THE LEGO BATMAN MOVIE. This figure features Batman in specialized space-ready armor with helmet and equipment for extraterrestrial missions. The design showcases Batman's preparedness for literally any scenario, even beyond Earth's atmosphere. A distinctive variant for Batman collectors who appreciate his obsessive contingency planning extending to space exploration.",
    description_de: "Batman, Space Batsuit startet den Dark Knight in kosmische Abenteuer aus THE LEGO BATMAN MOVIE. Diese Figur zeigt Batman in spezialisierter weltraumtauglicher Rüstung mit Helm und Ausrüstung für außerirdische Missionen. Das Design präsentiert Batmans Bereitschaft für buchstäblich jedes Szenario, sogar jenseits der Erdatmosphäre. Eine markante Variante für Batman-Sammler, die seine obsessive Notfallplanung bis zur Weltraumforschung schätzen.",
    description_fr: "Batman, Space Batsuit lance le Dark Knight dans des aventures cosmiques de THE LEGO BATMAN MOVIE. Cette figurine présente Batman en armure spécialisée prête pour l'espace avec casque et équipement pour missions extraterrestres. Le design présente la préparation de Batman pour littéralement tout scénario, même au-delà de l'atmosphère terrestre. Une variante distinctive pour les collectionneurs Batman qui apprécient sa planification de contingence obsessionnelle s'étendant à l'exploration spatiale.",
    description_es: "Batman, Space Batsuit lanza al Caballero Oscuro a aventuras cósmicas de THE LEGO BATMAN MOVIE. Esta figura presenta a Batman en armadura especializada lista para el espacio con casco y equipo para misiones extraterrestres. El diseño muestra la preparación de Batman para literalmente cualquier escenario, incluso más allá de la atmósfera terrestre. Una variante distintiva para coleccionistas de Batman que aprecian su planificación de contingencia obsesiva extendiéndose a exploración espacial."
  },
  {
    minifigure_no: 'sh0453',
    description_en: "Harley Quinn - Cannon Ball Suit brings Dr. Quinzel to LEGO form in explosive action attire from THE LEGO BATMAN MOVIE. This figure showcases Harley in a distinctive cannon ball-themed costume, combining her acrobatic circus background with destructive weaponry. The design emphasizes Harley's creative chaos and theatrical criminal style. A fun variant for Batman collectors who appreciate Harley Quinn's unpredictable and colorful villain personas.",
    description_de: "Harley Quinn - Cannon Ball Suit bringt Dr. Quinzel in LEGO-Form in explosiver Action-Kleidung aus THE LEGO BATMAN MOVIE. Diese Figur präsentiert Harley in einem markanten Kanonenkugel-thematisierten Kostüm, kombiniert ihren akrobatischen Zirkus-Hintergrund mit zerstörerischer Bewaffnung. Das Design betont Harleys kreatives Chaos und theatralischen Kriminellen-Stil. Eine lustige Variante für Batman-Sammler, die Harley Quinns unvorhersehbare und farbenfrohe Schurken-Personas schätzen.",
    description_fr: "Harley Quinn - Cannon Ball Suit apporte Dr. Quinzel en forme LEGO en tenue d'action explosive de THE LEGO BATMAN MOVIE. Cette figurine présente Harley dans un costume distinctif à thème de boulet de canon, combinant son parcours de cirque acrobatique avec des armes destructrices. Le design souligne le chaos créatif de Harley et le style criminel théâtral. Une variante amusante pour les collectionneurs Batman qui apprécient les personas de méchant imprévisibles et colorées de Harley Quinn.",
    description_es: "Harley Quinn - Cannon Ball Suit trae a la Dra. Quinzel en forma LEGO en atuendo de acción explosivo de THE LEGO BATMAN MOVIE. Esta figura muestra a Harley en un distintivo traje temático de bala de cañón, combinando su trasfondo de circo acrobático con armamento destructivo. El diseño enfatiza el caos creativo de Harley y estilo criminal teatral. Una variante divertida para coleccionistas de Batman que aprecian las personas villanas impredecibles y coloridas de Harley Quinn."
  },
  {
    minifigure_no: 'sh0454',
    description_en: "Crazy Quilt debuts in LEGO form as one of Batman's more visually striking villains. This figure captures the color-obsessed artist criminal in his distinctive patchwork costume, representing his unique visual-themed crimes. The design emphasizes Crazy Quilt's flamboyant appearance and artistic criminal methods. A rare character minifigure for Batman collectors seeking to complete their rogues' gallery with lesser-known but visually memorable villains.",
    description_de: "Crazy Quilt debütiert in LEGO-Form als einer von Batmans visuell auffälligeren Schurken. Diese Figur erfasst den farb-besessenen Künstler-Kriminellen in seinem markanten Flickwerk-Kostüm, repräsentiert seine einzigartigen visuell-thematisierten Verbrechen. Das Design betont Crazy Quilts extravagante Erscheinung und künstlerische kriminelle Methoden. Eine seltene Charakter-Minifigur für Batman-Sammler, die ihre Schurkengalerie mit weniger bekannten, aber visuell einprägsamen Schurken vervollständigen möchten.",
    description_fr: "Crazy Quilt fait ses débuts en forme LEGO en tant que l'un des méchants visuellement les plus frappants de Batman. Cette figurine capture l'artiste criminel obsédé par les couleurs dans son costume de patchwork distinctif, représentant ses crimes à thème visuel uniques. Le design souligne l'apparence flamboyante de Crazy Quilt et les méthodes criminelles artistiques. Une figurine de personnage rare pour les collectionneurs Batman cherchant à compléter leur galerie de méchants avec des méchants moins connus mais visuellement mémorables.",
    description_es: "Crazy Quilt debuta en forma LEGO como uno de los villanos visualmente más llamativos de Batman. Esta figura captura al criminal artista obsesionado con colores en su distintivo traje de retazos, representando sus crímenes únicos con temática visual. El diseño enfatiza la apariencia extravagante de Crazy Quilt y métodos criminales artísticos. Una minifigura de personaje rara para coleccionistas de Batman buscando completar su galería de villanos con villanos menos conocidos pero visualmente memorables."
  },
  {
    minifigure_no: 'sh0455',
    description_en: "Gentleman Ghost brings supernatural crime to LEGO form as one of DC's classic spectral villains. This figure captures the ghostly thief in his distinctive Victorian-era formal attire, representing his centuries-old criminal career. The design emphasizes Gentleman Ghost's elegant yet ethereal appearance. A unique villain minifigure for DC collectors building supernatural threat galleries and heroes facing paranormal adversaries.",
    description_de: "Gentleman Ghost bringt übernatürliches Verbrechen in LEGO-Form als einer von DCs klassischen Geister-Schurken. Diese Figur erfasst den geisterhaften Dieb in seiner markanten viktorianischen formellen Kleidung, repräsentiert seine jahrhundertealte kriminelle Karriere. Das Design betont Gentleman Ghosts elegante, aber ätherische Erscheinung. Eine einzigartige Schurken-Minifigur für DC-Sammler, die übernatürliche Bedrohungsgalerien und Helden aufbauen, die paranormalen Gegnern gegenüberstehen.",
    description_fr: "Gentleman Ghost apporte le crime surnaturel en forme LEGO en tant que l'un des méchants spectraux classiques de DC. Cette figurine capture le voleur fantomatique dans sa tenue formelle distinctive de l'ère victorienne, représentant sa carrière criminelle vieille de plusieurs siècles. Le design souligne l'apparence élégante mais éthérée de Gentleman Ghost. Une figurine méchante unique pour les collectionneurs DC construisant des galeries de menaces surnaturelles et des héros affrontant des adversaires paranormaux.",
    description_es: "Gentleman Ghost trae crimen sobrenatural en forma LEGO como uno de los villanos espectrales clásicos de DC. Esta figura captura al ladrón fantasmal en su distintiva vestimenta formal de era victoriana, representando su carrera criminal de siglos. El diseño enfatiza la apariencia elegante pero etérea de Gentleman Ghost. Una minifigura villana única para coleccionistas DC construyendo galerías de amenazas sobrenaturales y héroes enfrentando adversarios paranormales."
  },
  {
    minifigure_no: 'sh0456',
    description_en: "Wonder Woman - Gold Tiara, Blue Skirt brings Diana Prince to LEGO form in classic comic styling. This figure showcases the Amazonian warrior with her iconic gold tiara and blue skirt, capturing her traditional comic book appearance. The design emphasizes Wonder Woman's timeless heroic aesthetic and royal Themysciran heritage. A popular character minifigure for DC collectors building Justice League teams and Wonder Woman's heroic adventures.",
    description_de: "Wonder Woman - Gold Tiara, Blue Skirt bringt Diana Prince in LEGO-Form im klassischen Comic-Styling. Diese Figur präsentiert die amazonische Kriegerin mit ihrer ikonischen goldenen Tiara und blauem Rock, erfasst ihr traditionelles Comicbuch-Erscheinungsbild. Das Design betont Wonder Womans zeitloses heroisches Erscheinungsbild und königliches themyskirisches Erbe. Eine beliebte Charakter-Minifigur für DC-Sammler, die Justice League Teams und Wonder Womans heroische Abenteuer aufbauen.",
    description_fr: "Wonder Woman - Gold Tiara, Blue Skirt apporte Diana Prince en forme LEGO dans un style comic classique. Cette figurine présente la guerrière amazonienne avec sa tiare dorée iconique et sa jupe bleue, capturant son apparence traditionnelle de bande dessinée. Le design souligne l'esthétique héroïque intemporelle de Wonder Woman et l'héritage royal themyscirien. Une figurine de personnage populaire pour les collectionneurs DC construisant des équipes Justice League et les aventures héroïques de Wonder Woman.",
    description_es: "Wonder Woman - Gold Tiara, Blue Skirt trae a Diana Prince en forma LEGO con estilo cómico clásico. Esta figura muestra a la guerrera amazona con su icónica tiara dorada y falda azul, capturando su apariencia tradicional de cómic. El diseño enfatiza la estética heroica atemporal de Wonder Woman y herencia real themysciriana. Una minifigura de personaje popular para coleccionistas DC construyendo equipos Justice League y aventuras heroicas de Wonder Woman."
  },
  {
    minifigure_no: 'sh0457',
    description_en: "Firestorm debuts in LEGO form as DC's nuclear-powered fusion hero. This figure captures the merged consciousness of Ronnie Raymond and Professor Stein in Firestorm's distinctive flame-headed costume, representing their unique atomic transmutation powers. The design emphasizes Firestorm's fiery appearance and scientific superhero aesthetic. A significant character minifigure for DC collectors building Justice League teams and assembling DC's science-based heroes.",
    description_de: "Firestorm debütiert in LEGO-Form als DCs atomgetriebener Fusions-Held. Diese Figur erfasst das fusionierte Bewusstsein von Ronnie Raymond und Professor Stein in Firestorms markanten flammenköpfigen Kostüm, repräsentiert ihre einzigartigen atomaren Transmutationskräfte. Das Design betont Firestorms feuriges Erscheinungsbild und wissenschaftliche Superhelden-Ästhetik. Eine bedeutende Charakter-Minifigur für DC-Sammler, die Justice League Teams aufbauen und DCs wissenschaftsbasierte Helden versammeln.",
    description_fr: "Firestorm fait ses débuts en forme LEGO en tant que héros de fusion à énergie nucléaire de DC. Cette figurine capture la conscience fusionnée de Ronnie Raymond et du Professeur Stein dans le costume distinctif à tête de flamme de Firestorm, représentant leurs pouvoirs uniques de transmutation atomique. Le design souligne l'apparence enflammée de Firestorm et l'esthétique de super-héros scientifique. Une figurine de personnage significative pour les collectionneurs DC construisant des équipes Justice League et assemblant les héros basés sur la science de DC.",
    description_es: "Firestorm debuta en forma LEGO como el héroe de fusión con energía nuclear de DC. Esta figura captura la conciencia fusionada de Ronnie Raymond y el Profesor Stein en el distintivo traje con cabeza de llama de Firestorm, representando sus poderes únicos de transmutación atómica. El diseño enfatiza la apariencia ardiente de Firestorm y estética de superhéroe científico. Una minifigura de personaje significativa para coleccionistas DC construyendo equipos Justice League y reuniendo héroes basados en ciencia de DC."
  },
  {
    minifigure_no: 'sh0458',
    description_en: "Batman, Neck Bracket, No Cape showcases a specialized technical variant of the Dark Knight. This figure features Batman with neck bracket attachment point but no cape, representing either a building configuration or specialized mission loadout. The design provides flexibility for collectors creating custom Batman builds and cape variations. A practical variant for Batman collectors who want modular costume options and specialized gear configurations.",
    description_de: "Batman, Neck Bracket, No Cape präsentiert eine spezialisierte technische Variante des Dark Knight. Diese Figur zeigt Batman mit Halshalterung-Befestigungspunkt, aber ohne Umhang, repräsentiert entweder eine Baukonfiguration oder spezialisierte Missions-Ausrüstung. Das Design bietet Flexibilität für Sammler, die benutzerdefinierte Batman-Bauten und Umhang-Variationen erstellen. Eine praktische Variante für Batman-Sammler, die modulare Kostümoptionen und spezialisierte Ausrüstungskonfigurationen wünschen.",
    description_fr: "Batman, Neck Bracket, No Cape présente une variante technique spécialisée du Dark Knight. Cette figurine présente Batman avec point de fixation de support de cou mais sans cape, représentant soit une configuration de construction soit un équipement de mission spécialisé. Le design offre de la flexibilité pour les collectionneurs créant des constructions Batman personnalisées et des variations de cape. Une variante pratique pour les collectionneurs Batman voulant des options de costume modulaires et des configurations d'équipement spécialisées.",
    description_es: "Batman, Neck Bracket, No Cape muestra una variante técnica especializada del Caballero Oscuro. Esta figura presenta a Batman con punto de conexión de soporte de cuello pero sin capa, representando ya sea una configuración de construcción o carga de misión especializada. El diseño proporciona flexibilidad para coleccionistas creando construcciones Batman personalizadas y variaciones de capa. Una variante práctica para coleccionistas de Batman que desean opciones de vestuario modulares y configuraciones de equipo especializadas."
  },
  {
    minifigure_no: 'sh0459',
    description_en: "Lex Luthor - Green and Dark Purple Light Armor brings Superman's greatest nemesis to LEGO form in battle-ready configuration. This figure showcases Luthor in distinctive green and dark purple armor, representing his technological warfare against the Man of Steel. The design emphasizes Lex's genius inventor status and his determination to defeat Superman through science. A key villain minifigure for Superman collectors building Metropolis conflicts and Justice League rogues' galleries.",
    description_de: "Lex Luthor - Green and Dark Purple Light Armor bringt Supermans größten Nemesis in LEGO-Form in kampfbereiter Konfiguration. Diese Figur präsentiert Luthor in markanter grüner und dunkellila Rüstung, repräsentiert seine technologische Kriegsführung gegen den Man of Steel. Das Design betont Lex' Genie-Erfinder-Status und seine Entschlossenheit, Superman durch Wissenschaft zu besiegen. Eine wichtige Schurken-Minifigur für Superman-Sammler, die Metropolis-Konflikte und Justice League Schurkengalerien aufbauen.",
    description_fr: "Lex Luthor - Green and Dark Purple Light Armor apporte le plus grand ennemi de Superman en forme LEGO en configuration prête au combat. Cette figurine présente Luthor en armure distinctive verte et violet foncé, représentant sa guerre technologique contre l'Homme d'Acier. Le design souligne le statut d'inventeur génial de Lex et sa détermination à vaincre Superman par la science. Une figurine méchante clé pour les collectionneurs Superman construisant des conflits de Metropolis et des galeries de méchants Justice League.",
    description_es: "Lex Luthor - Green and Dark Purple Light Armor trae al mayor némesis de Superman en forma LEGO en configuración lista para batalla. Esta figura muestra a Luthor en distintiva armadura verde y púrpura oscuro, representando su guerra tecnológica contra el Hombre de Acero. El diseño enfatiza el estatus de inventor genio de Lex y su determinación de derrotar a Superman mediante ciencia. Una minifigura villana clave para coleccionistas de Superman construyendo conflictos de Metropolis y galerías de villanos de Justice League."
  },
  {
    minifigure_no: 'sh0460',
    description_en: "Cheetah arrives in LEGO form as Wonder Woman's most iconic animal-powered adversary. This figure captures Barbara Ann Minerva's transformation into the feline speedster with distinctive spotted pattern and claws. The design emphasizes Cheetah's feral ferocity and supernatural hunting abilities. A significant villain minifigure for Wonder Woman collectors building Themysciran conflicts and DC's mystically-powered rogues' galleries.",
    description_de: "Cheetah kommt in LEGO-Form als Wonder Womans ikonischster tiergetriebener Gegner an. Diese Figur erfasst Barbara Ann Minervas Verwandlung in den Katzen-Speedster mit markanten gefleckten Muster und Krallen. Das Design betont Cheetahs wilde Wildheit und übernatürliche Jagdfähigkeiten. Eine bedeutende Schurken-Minifigur für Wonder Woman Sammler, die themyskirische Konflikte und DCs mystisch angetriebene Schurkengalerien aufbauen.",
    description_fr: "Cheetah arrive en forme LEGO en tant qu'adversaire à pouvoirs animaux le plus iconique de Wonder Woman. Cette figurine capture la transformation de Barbara Ann Minerva en speedster félin avec motif tacheté distinctif et griffes. Le design souligne la férocité férale de Cheetah et les capacités de chasse surnaturelles. Une figurine méchante significative pour les collectionneurs Wonder Woman construisant des conflits themysciriens et des galeries de méchants aux pouvoirs mystiques de DC.",
    description_es: "Cheetah llega en forma LEGO como la adversaria con poderes animales más icónica de Wonder Woman. Esta figura captura la transformación de Barbara Ann Minerva en la velocista felina con patrón manchado distintivo y garras. El diseño enfatiza la ferocidad salvaje de Cheetah y habilidades de caza sobrenaturales. Una minifigura villana significativa para coleccionistas de Wonder Woman construyendo conflictos themyscirios y galerías de villanos místicamente potenciados de DC."
  },
  {
    minifigure_no: 'sh0461',
    description_en: "Hawkgirl brings the winged warrior Shayera Hol to LEGO form with her distinctive Thanagarian equipment. This figure showcases Hawkgirl in her classic costume with wings and mace, representing her fierce combat prowess and aerial superiority. The design emphasizes Hawkgirl's warrior heritage and role in the Justice League. A popular character minifigure for DC collectors building diverse Justice League rosters and cosmic hero teams.",
    description_de: "Hawkgirl bringt die geflügelte Kriegerin Shayera Hol in LEGO-Form mit ihrer markanten thanagarischen Ausrüstung. Diese Figur präsentiert Hawkgirl in ihrem klassischen Kostüm mit Flügeln und Streitkolben, repräsentiert ihre wilde Kampfkraft und Luftüberlegenheit. Das Design betont Hawkgirls Krieger-Erbe und Rolle in der Justice League. Eine beliebte Charakter-Minifigur für DC-Sammler, die vielfältige Justice League Aufstellungen und kosmische Helden-Teams aufbauen.",
    description_fr: "Hawkgirl apporte la guerrière ailée Shayera Hol en forme LEGO avec son équipement thanagarian distinctif. Cette figurine présente Hawkgirl dans son costume classique avec ailes et masse, représentant sa prouesse au combat féroce et sa supériorité aérienne. Le design souligne l'héritage guerrier de Hawkgirl et son rôle dans la Justice League. Une figurine de personnage populaire pour les collectionneurs DC construisant des listes Justice League diversifiées et des équipes de héros cosmiques.",
    description_es: "Hawkgirl trae a la guerrera alada Shayera Hol en forma LEGO con su distintivo equipo thanagario. Esta figura muestra a Hawkgirl en su traje clásico con alas y maza, representando su feroz destreza en combate y superioridad aérea. El diseño enfatiza la herencia guerrera de Hawkgirl y papel en la Justice League. Una minifigura de personaje popular para coleccionistas DC construyendo rosters diversificados de Justice League y equipos de héroes cósmicos."
  },
  {
    minifigure_no: 'sh0462',
    description_en: "El Dorado debuts in LEGO form as one of DC's lesser-known but culturally significant heroes. This figure captures the gold-powered hero with distinctive costume and abilities, representing Latino superhero representation in the DC universe. The design emphasizes El Dorado's unique golden powers and mystical heritage. A valuable character minifigure for DC collectors seeking diverse hero rosters and completing Super Friends lineups.",
    description_de: "El Dorado debütiert in LEGO-Form als einer von DCs weniger bekannten, aber kulturell bedeutenden Helden. Diese Figur erfasst den gold-getriebenen Helden mit markanten Kostüm und Fähigkeiten, repräsentiert Latino-Superhelden-Darstellung im DC-Universum. Das Design betont El Dorados einzigartige goldene Kräfte und mystisches Erbe. Eine wertvolle Charakter-Minifigur für DC-Sammler, die vielfältige Helden-Aufstellungen suchen und Super Friends Besetzungen vervollständigen.",
    description_fr: "El Dorado fait ses débuts en forme LEGO en tant que l'un des héros moins connus mais culturellement significatifs de DC. Cette figurine capture le héros aux pouvoirs d'or avec costume et capacités distinctifs, représentant la représentation de super-héros latino dans l'univers DC. Le design souligne les pouvoirs dorés uniques d'El Dorado et l'héritage mystique. Une figurine de personnage précieuse pour les collectionneurs DC recherchant des listes de héros diversifiées et complétant les alignements Super Friends.",
    description_es: "El Dorado debuta en forma LEGO como uno de los héroes menos conocidos pero culturalmente significativos de DC. Esta figura captura al héroe con poderes dorados con traje distintivo y habilidades, representando representación de superhéroe latino en el universo DC. El diseño enfatiza los poderes dorados únicos de El Dorado y herencia mística. Una minifigura de personaje valiosa para coleccionistas DC buscando rosters de héroes diversos y completando alineaciones de Super Friends."
  },
  {
    minifigure_no: 'sh0463',
    description_en: "Superman - Blue Suit, Spongy Cape, Hair with Front Curl, Open Mouth Smile / Sheepish Grin brings the Man of Steel to LEGO form with characteristic dual expressions. This figure showcases Clark Kent's Superman in classic blue suit with distinctive hair curl, featuring both confident smile and sheepish grin faces. The design captures Superman's humble heroism and dual nature as powerful protector and mild-mannered reporter. A versatile Superman variant for DC collectors wanting expressive display options.",
    description_de: "Superman - Blue Suit, Spongy Cape, Hair with Front Curl, Open Mouth Smile / Sheepish Grin bringt den Man of Steel in LEGO-Form mit charakteristischen doppelten Ausdrücken. Diese Figur präsentiert Clark Kents Superman im klassischen blauen Anzug mit markanter Haarlocke, zeigt sowohl selbstbewusstes Lächeln als auch verschämtes Grinsen. Das Design erfasst Supermans bescheidenes Heldentum und duale Natur als mächtiger Beschützer und sanftmütiger Reporter. Eine vielseitige Superman-Variante für DC-Sammler, die ausdrucksvolle Darstellungsoptionen wünschen.",
    description_fr: "Superman - Blue Suit, Spongy Cape, Hair with Front Curl, Open Mouth Smile / Sheepish Grin apporte l'Homme d'Acier en forme LEGO avec des expressions doubles caractéristiques. Cette figurine présente le Superman de Clark Kent en costume bleu classique avec boucle de cheveux distinctive, présentant à la fois un sourire confiant et un sourire timide. Le design capture l'héroïsme humble de Superman et sa double nature de protecteur puissant et reporter doux. Une variante Superman polyvalente pour les collectionneurs DC voulant des options d'affichage expressives.",
    description_es: "Superman - Blue Suit, Spongy Cape, Hair with Front Curl, Open Mouth Smile / Sheepish Grin trae al Hombre de Acero en forma LEGO con expresiones duales características. Esta figura muestra al Superman de Clark Kent en traje azul clásico con rizo de cabello distintivo, presentando tanto sonrisa confiada como sonrisa tímida. El diseño captura el heroísmo humilde de Superman y naturaleza dual como protector poderoso y reportero afable. Una variante Superman versátil para coleccionistas DC que desean opciones de exhibición expresivas."
  },
  {
    minifigure_no: 'sh0464',
    description_en: "Dick Grayson, Red Sweater with Dark Red Robins showcases Bruce Wayne's ward in civilian attire. This figure captures Dick in casual clothing with bird-themed sweater, representing his off-duty moments and connection to his Robin identity. The design provides essential civilian representation for storytelling beyond superhero action. A necessary companion piece for Batman collectors creating complete Wayne Manor scenes and Dick Grayson's dual-life narratives.",
    description_de: "Dick Grayson, Red Sweater with Dark Red Robins präsentiert Bruce Waynes Mündel in Zivilkleidung. Diese Figur erfasst Dick in Freizeitkleidung mit vogel-thematisiertem Pullover, repräsentiert seine Nicht-Dienst-Momente und Verbindung zu seiner Robin-Identität. Das Design bietet wesentliche zivile Darstellung für Geschichtenerzählung jenseits von Superhelden-Action. Ein notwendiges Begleitstück für Batman-Sammler, die vollständige Wayne Manor Szenen und Dick Graysons Doppelleben-Erzählungen erstellen.",
    description_fr: "Dick Grayson, Red Sweater with Dark Red Robins présente le pupille de Bruce Wayne en tenue civile. Cette figurine capture Dick en vêtements décontractés avec pull à thème d'oiseau, représentant ses moments hors service et sa connexion à son identité Robin. Le design fournit une représentation civile essentielle pour la narration au-delà de l'action de super-héros. Une pièce d'accompagnement nécessaire pour les collectionneurs Batman créant des scènes complètes de Wayne Manor et des récits de double vie de Dick Grayson.",
    description_es: "Dick Grayson, Red Sweater with Dark Red Robins muestra al pupilo de Bruce Wayne en vestimenta civil. Esta figura captura a Dick en ropa casual con suéter temático de pájaros, representando sus momentos fuera de servicio y conexión con su identidad Robin. El diseño proporciona representación civil esencial para narrativa más allá de acción de superhéroes. Una pieza complementaria necesaria para coleccionistas de Batman creando escenas completas de Wayne Manor y narrativas de doble vida de Dick Grayson."
  },
  {
    minifigure_no: 'sh0465',
    description_en: "Green Arrow - Hat with Feather brings Oliver Queen to LEGO form with classic archer styling. This figure showcases the Emerald Archer in distinctive costume with feathered hat, capturing his Robin Hood-inspired vigilante aesthetic. The design emphasizes Green Arrow's street-level heroism and expert marksmanship. A popular character minifigure for DC collectors building Justice League teams and assembling DC's skilled non-powered heroes.",
    description_de: "Green Arrow - Hat with Feather bringt Oliver Queen in LEGO-Form mit klassischem Bogenschützen-Styling. Diese Figur präsentiert den Smaragd-Bogenschützen im markanten Kostüm mit gefiedertem Hut, erfasst seine Robin Hood-inspirierte Vigilanten-Ästhetik. Das Design betont Green Arrows Straßen-Heldentum und Experten-Treffsicherheit. Eine beliebte Charakter-Minifigur für DC-Sammler, die Justice League Teams aufbauen und DCs geschickte Helden ohne Superkräfte versammeln.",
    description_fr: "Green Arrow - Hat with Feather apporte Oliver Queen en forme LEGO avec un style d'archer classique. Cette figurine présente l'Archer Émeraude en costume distinctif avec chapeau à plume, capturant son esthétique de justicier inspirée de Robin Hood. Le design souligne l'héroïsme de niveau rue de Green Arrow et l'expertise en tir. Une figurine de personnage populaire pour les collectionneurs DC construisant des équipes Justice League et assemblant les héros sans pouvoirs qualifiés de DC.",
    description_es: "Green Arrow - Hat with Feather trae a Oliver Queen en forma LEGO con estilo clásico de arquero. Esta figura muestra al Arquero Esmeralda en traje distintivo con sombrero con pluma, capturando su estética de vigilante inspirada en Robin Hood. El diseño enfatiza el heroísmo de nivel callejero de Green Arrow y puntería experta. Una minifigura de personaje popular para coleccionistas DC construyendo equipos Justice League y reuniendo héroes hábiles sin poderes de DC."
  },
  {
    minifigure_no: 'sh0466',
    description_en: "Black Panther - Reddish Brown Eyes brings T'Challa to LEGO form from the blockbuster Black Panther film. This figure showcases the King of Wakanda in his distinctive black suit with reddish brown eyes variant, capturing his role as warrior king and technological genius. The design emphasizes Black Panther's sleek vibranium suit and regal presence. A highly popular character minifigure for MCU collectors building Wakanda scenes and diverse Avengers rosters.",
    description_de: "Black Panther - Reddish Brown Eyes bringt T'Challa in LEGO-Form aus dem Blockbuster Black Panther Film. Diese Figur präsentiert den König von Wakanda in seinem markanten schwarzen Anzug mit rötlich-braunen Augen-Variante, erfasst seine Rolle als Krieger-König und Technologie-Genie. Das Design betont Black Panthers schlanken Vibranium-Anzug und königliche Präsenz. Eine sehr beliebte Charakter-Minifigur für MCU-Sammler, die Wakanda-Szenen und vielfältige Avengers-Aufstellungen aufbauen.",
    description_fr: "Black Panther - Reddish Brown Eyes apporte T'Challa en forme LEGO du film à succès Black Panther. Cette figurine présente le Roi du Wakanda dans sa combinaison noire distinctive avec variante aux yeux brun rougeâtre, capturant son rôle de roi guerrier et génie technologique. Le design souligne la combinaison en vibranium élégante de Black Panther et sa présence royale. Une figurine de personnage très populaire pour les collectionneurs MCU construisant des scènes du Wakanda et des listes d'Avengers diversifiées.",
    description_es: "Black Panther - Reddish Brown Eyes trae a T'Challa en forma LEGO de la exitosa película Black Panther. Esta figura muestra al Rey de Wakanda en su distintivo traje negro con variante de ojos marrón rojizo, capturando su papel como rey guerrero y genio tecnológico. El diseño enfatiza el elegante traje de vibranium de Black Panther y presencia regia. Una minifigura de personaje muy popular para coleccionistas MCU construyendo escenas de Wakanda y rosters de Avengers diversos."
  },
  {
    minifigure_no: 'sh0467',
    description_en: "Nakia - Red Top brings Lupita Nyong'o's character to LEGO form from Black Panther. This figure showcases T'Challa's love interest and War Dog spy in distinctive red attire, representing her role as both warrior and humanitarian. The design emphasizes Nakia's strength and independence within Wakanda's story. A significant character minifigure for Black Panther collectors building Wakanda's diverse cast and romantic storylines.",
    description_de: "Nakia - Red Top bringt Lupita Nyong'os Charakter in LEGO-Form aus Black Panther. Diese Figur präsentiert T'Challas Liebesinteresse und War Dog Spionin in markanter roter Kleidung, repräsentiert ihre Rolle als sowohl Kriegerin als auch Humanitärin. Das Design betont Nakias Stärke und Unabhängigkeit innerhalb von Wakandas Geschichte. Eine bedeutende Charakter-Minifigur für Black Panther Sammler, die Wakandas vielfältige Besetzung und romantische Handlungsstränge aufbauen.",
    description_fr: "Nakia - Red Top apporte le personnage de Lupita Nyong'o en forme LEGO de Black Panther. Cette figurine présente l'intérêt amoureux de T'Challa et l'espionne War Dog en tenue rouge distinctive, représentant son rôle à la fois de guerrière et d'humanitaire. Le design souligne la force et l'indépendance de Nakia dans l'histoire du Wakanda. Une figurine de personnage significative pour les collectionneurs Black Panther construisant le casting diversifié du Wakanda et les intrigues romantiques.",
    description_es: "Nakia - Red Top trae al personaje de Lupita Nyong'o en forma LEGO de Black Panther. Esta figura muestra al interés amoroso de T'Challa y espía War Dog en atuendo rojo distintivo, representando su papel como tanto guerrera como humanitaria. El diseño enfatiza la fuerza e independencia de Nakia dentro de la historia de Wakanda. Una minifigura de personaje significativa para coleccionistas de Black Panther construyendo el elenco diverso de Wakanda y líneas argumentales románticas."
  },
  {
    minifigure_no: 'sh0468',
    description_en: "Ulysses Klaue arrives in LEGO form as Black Panther's sound-powered adversary. This figure captures Andy Serkis's character with distinctive appearance and vibranium-stealing criminal background, representing the outside threats to Wakanda. The design emphasizes Klaue's mercenary nature and his sonic weapon technology. A key antagonist minifigure for Black Panther collectors building Wakanda conflicts and criminal underworld scenes.",
    description_de: "Ulysses Klaue kommt in LEGO-Form als Black Panthers schall-getriebener Gegner an. Diese Figur erfasst Andy Serkis' Charakter mit markanter Erscheinung und Vibranium-stehlenden kriminellen Hintergrund, repräsentiert die äußeren Bedrohungen für Wakanda. Das Design betont Klaues Söldner-Natur und seine Schallwaffen-Technologie. Eine wichtige Antagonisten-Minifigur für Black Panther Sammler, die Wakanda-Konflikte und kriminelle Unterwelt-Szenen aufbauen.",
    description_fr: "Ulysses Klaue arrive en forme LEGO en tant qu'adversaire aux pouvoirs sonores de Black Panther. Cette figurine capture le personnage d'Andy Serkis avec apparence distinctive et parcours criminel de vol de vibranium, représentant les menaces extérieures au Wakanda. Le design souligne la nature mercenaire de Klaue et sa technologie d'arme sonique. Une figurine antagoniste clé pour les collectionneurs Black Panther construisant des conflits du Wakanda et des scènes du monde criminel.",
    description_es: "Ulysses Klaue llega en forma LEGO como el adversario con poderes de sonido de Black Panther. Esta figura captura al personaje de Andy Serkis con apariencia distintiva y trasfondo criminal de robo de vibranium, representando las amenazas externas a Wakanda. El diseño enfatiza la naturaleza mercenaria de Klaue y su tecnología de arma sónica. Una minifigura antagonista clave para coleccionistas de Black Panther construyendo conflictos de Wakanda y escenas del submundo criminal."
  },
  {
    minifigure_no: 'sh0469',
    description_en: "Erik Killmonger brings Michael B. Jordan's complex villain to LEGO form from Black Panther. This figure showcases T'Challa's cousin and challenger with distinctive appearance, representing his role as ideological opponent and rightful claim to Wakanda's throne. The design captures Killmonger's warrior training and revolutionary perspective. An essential antagonist minifigure for Black Panther collectors building the film's central conflict and throne room battle scenes.",
    description_de: "Erik Killmonger bringt Michael B. Jordans komplexen Schurken in LEGO-Form aus Black Panther. Diese Figur präsentiert T'Challas Cousin und Herausforderer mit markanter Erscheinung, repräsentiert seine Rolle als ideologischer Gegner und rechtmäßigen Anspruch auf Wakandas Thron. Das Design erfasst Killmongers Krieger-Training und revolutionäre Perspektive. Eine wesentliche Antagonisten-Minifigur für Black Panther Sammler, die den zentralen Konflikt des Films und Thronsaal-Kampfszenen aufbauen.",
    description_fr: "Erik Killmonger apporte le méchant complexe de Michael B. Jordan en forme LEGO de Black Panther. Cette figurine présente le cousin et challenger de T'Challa avec apparence distinctive, représentant son rôle d'opposant idéologique et revendication légitime du trône du Wakanda. Le design capture l'entraînement de guerrier de Killmonger et sa perspective révolutionnaire. Une figurine antagoniste essentielle pour les collectionneurs Black Panther construisant le conflit central du film et les scènes de bataille de salle du trône.",
    description_es: "Erik Killmonger trae al villano complejo de Michael B. Jordan en forma LEGO de Black Panther. Esta figura muestra al primo y retador de T'Challa con apariencia distintiva, representando su papel como oponente ideológico y reclamo legítimo al trono de Wakanda. El diseño captura el entrenamiento guerrero de Killmonger y perspectiva revolucionaria. Una minifigura antagonista esencial para coleccionistas de Black Panther construyendo el conflicto central de la película y escenas de batalla de sala del trono."
  },
  {
    minifigure_no: 'sh0470',
    description_en: "Cyborg brings Victor Stone to LEGO form with classic comic styling. This figure showcases the half-human, half-machine hero in traditional red and silver design, representing his technological abilities and Teen Titans leadership. The design emphasizes Cyborg's cybernetic enhancements and dual nature between humanity and machine. A popular character minifigure for DC collectors building Teen Titans teams and Justice League rosters.",
    description_de: "Cyborg bringt Victor Stone in LEGO-Form mit klassischem Comic-Styling. Diese Figur präsentiert den halb-menschlichen, halb-maschinellen Helden im traditionellen rot-silbernen Design, repräsentiert seine technologischen Fähigkeiten und Teen Titans Führung. Das Design betont Cyborgs kybernetische Verbesserungen und duale Natur zwischen Menschlichkeit und Maschine. Eine beliebte Charakter-Minifigur für DC-Sammler, die Teen Titans Teams und Justice League Aufstellungen aufbauen.",
    description_fr: "Cyborg apporte Victor Stone en forme LEGO avec un style comic classique. Cette figurine présente le héros mi-humain, mi-machine en design rouge et argent traditionnel, représentant ses capacités technologiques et son leadership des Teen Titans. Le design souligne les améliorations cybernétiques de Cyborg et sa double nature entre humanité et machine. Une figurine de personnage populaire pour les collectionneurs DC construisant des équipes Teen Titans et des listes Justice League.",
    description_es: "Cyborg trae a Victor Stone en forma LEGO con estilo cómico clásico. Esta figura muestra al héroe mitad humano, mitad máquina en diseño tradicional rojo y plateado, representando sus habilidades tecnológicas y liderazgo de Teen Titans. El diseño enfatiza las mejoras cibernéticas de Cyborg y naturaleza dual entre humanidad y máquina. Una minifigura de personaje popular para coleccionistas DC construyendo equipos Teen Titans y rosters de Justice League."
  },
  {
    minifigure_no: 'sh0471',
    description_en: "Reverse Flash (Zoom) brings Barry Allen's greatest adversary to LEGO form. This figure showcases the evil speedster in reversed yellow and black costume, representing Eobard Thawne's time-traveling villainy and obsession with destroying the Flash. The design emphasizes the dark mirror image of Flash's heroism. A crucial villain minifigure for Flash collectors building Speed Force battles and Flash's most personal conflicts.",
    description_de: "Reverse Flash (Zoom) bringt Barry Allens größten Gegner in LEGO-Form. Diese Figur präsentiert den bösen Speedster im umgekehrten gelb-schwarzen Kostüm, repräsentiert Eobard Thawnes zeitreisende Schurkenei und Besessenheit, den Flash zu zerstören. Das Design betont das dunkle Spiegelbild von Flashs Heldentum. Eine entscheidende Schurken-Minifigur für Flash-Sammler, die Speed Force Kämpfe und Flashs persönlichste Konflikte aufbauen.",
    description_fr: "Reverse Flash (Zoom) apporte le plus grand adversaire de Barry Allen en forme LEGO. Cette figurine présente le speedster maléfique en costume jaune et noir inversé, représentant la vilenie voyageuse dans le temps d'Eobard Thawne et son obsession de détruire le Flash. Le design souligne l'image miroir sombre de l'héroïsme de Flash. Une figurine méchante cruciale pour les collectionneurs Flash construisant des batailles de Speed Force et les conflits les plus personnels de Flash.",
    description_es: "Reverse Flash (Zoom) trae al mayor adversario de Barry Allen en forma LEGO. Esta figura muestra al velocista malvado en traje amarillo y negro invertido, representando la villanía viajera del tiempo de Eobard Thawne y obsesión con destruir a Flash. El diseño enfatiza la imagen espejo oscura del heroísmo de Flash. Una minifigura villana crucial para coleccionistas de Flash construyendo batallas de Speed Force y conflictos más personales de Flash."
  },
  {
    minifigure_no: 'sh0472',
    description_en: "Killer Frost arrives in LEGO form as one of DC's cold-powered villains. This figure captures Caitlin Snow's transformation into the ice-wielding metahuman with distinctive blue and white costume. The design emphasizes Killer Frost's cryokinetic abilities and tragic origin story. A significant villain minifigure for Flash and DC collectors building rogues' galleries and ice-themed battle scenarios.",
    description_de: "Killer Frost kommt in LEGO-Form als einer von DCs kälte-getriebenen Schurken an. Diese Figur erfasst Caitlin Snows Verwandlung in den eis-schwingenden Metamenschen mit markanten blau-weißen Kostüm. Das Design betont Killer Frosts kryokinetische Fähigkeiten und tragische Ursprungsgeschichte. Eine bedeutende Schurken-Minifigur für Flash- und DC-Sammler, die Schurkengalerien und eis-thematisierte Kampfszenarien aufbauen.",
    description_fr: "Killer Frost arrive en forme LEGO en tant que l'un des méchants aux pouvoirs de froid de DC. Cette figurine capture la transformation de Caitlin Snow en métahumaine maniant la glace avec costume bleu et blanc distinctif. Le design souligne les capacités cryokinétiques de Killer Frost et son histoire d'origine tragique. Une figurine méchante significative pour les collectionneurs Flash et DC construisant des galeries de méchants et des scénarios de bataille à thème de glace.",
    description_es: "Killer Frost llega en forma LEGO como uno de los villanos con poderes de frío de DC. Esta figura captura la transformación de Caitlin Snow en la metahumana que maneja hielo con traje distintivo azul y blanco. El diseño enfatiza las habilidades criocinéticas de Killer Frost e historia de origen trágica. Una minifigura villana significativa para coleccionistas de Flash y DC construyendo galerías de villanos y escenarios de batalla temáticos de hielo."
  },
  {
    minifigure_no: 'sh0473',
    description_en: "The Flash - Gold Outlines on Chest showcases Barry Allen with enhanced costume detailing. This figure features the Scarlet Speedster with distinctive gold chest emblem outlines, representing a refined version of his classic costume. The design emphasizes Flash's iconic lightning bolt symbol and speed-inspired aesthetics. A popular Flash variant for DC collectors seeking detailed costume versions and building diverse Flash display options.",
    description_de: "The Flash - Gold Outlines on Chest präsentiert Barry Allen mit verbesserter Kostümdetaillierung. Diese Figur zeigt den Scharlachroten Speedster mit markanten goldenen Brust-Emblem-Umrissen, repräsentiert eine verfeinerte Version seines klassischen Kostüms. Das Design betont Flashs ikonisches Blitz-Symbol und geschwindigkeitsinspirierte Ästhetik. Eine beliebte Flash-Variante für DC-Sammler, die detaillierte Kostümversionen suchen und vielfältige Flash-Darstellungsoptionen aufbauen.",
    description_fr: "The Flash - Gold Outlines on Chest présente Barry Allen avec des détails de costume améliorés. Cette figurine présente le Scarlet Speedster avec des contours d'emblème de poitrine dorés distinctifs, représentant une version raffinée de son costume classique. Le design souligne le symbole d'éclair iconique de Flash et l'esthétique inspirée de la vitesse. Une variante Flash populaire pour les collectionneurs DC recherchant des versions de costume détaillées et construisant des options d'affichage Flash diversifiées.",
    description_es: "The Flash - Gold Outlines on Chest muestra a Barry Allen con detalles de traje mejorados. Esta figura presenta al Scarlet Speedster con distintivos contornos dorados de emblema de pecho, representando una versión refinada de su traje clásico. El diseño enfatiza el símbolo de rayo icónico de Flash y estética inspirada en velocidad. Una variante Flash popular para coleccionistas DC buscando versiones de traje detalladas y construyendo opciones de exhibición de Flash diversas."
  },
  {
    minifigure_no: 'sh0474',
    description_en: "Star-Lord - Short Legs brings Peter Quill to LEGO form in junior format. This figure showcases the Guardians of the Galaxy leader with short legs for younger builds, maintaining his distinctive red jacket and mask design. The design makes Star-Lord accessible for younger builders while retaining character authenticity. A practical variant for Marvel collectors building junior-scale Guardians teams and introducing young fans to the cosmic heroes.",
    description_de: "Star-Lord - Short Legs bringt Peter Quill in LEGO-Form im Junior-Format. Diese Figur präsentiert den Guardians of the Galaxy Anführer mit kurzen Beinen für jüngere Bauten, behält sein markantes rotes Jacken- und Masken-Design. Das Design macht Star-Lord für jüngere Baumeister zugänglich, während es Charakter-Authentizität behält. Eine praktische Variante für Marvel-Sammler, die Junior-Maßstab Guardians-Teams aufbauen und junge Fans in die kosmischen Helden einführen.",
    description_fr: "Star-Lord - Short Legs apporte Peter Quill en forme LEGO en format junior. Cette figurine présente le leader des Gardiens de la Galaxie avec des jambes courtes pour des constructions plus jeunes, maintenant son design distinctif de veste rouge et de masque. Le design rend Star-Lord accessible aux jeunes constructeurs tout en conservant l'authenticité du personnage. Une variante pratique pour les collectionneurs Marvel construisant des équipes de Gardiens à échelle junior et introduisant les jeunes fans aux héros cosmiques.",
    description_es: "Star-Lord - Short Legs trae a Peter Quill en forma LEGO en formato junior. Esta figura muestra al líder de Guardianes de la Galaxia con piernas cortas para construcciones más jóvenes, manteniendo su distintivo diseño de chaqueta roja y máscara. El diseño hace a Star-Lord accesible para constructores más jóvenes mientras mantiene autenticidad del personaje. Una variante práctica para coleccionistas Marvel construyendo equipos Guardianes a escala junior e introduciendo fans jóvenes a los héroes cósmicos."
  },
  {
    minifigure_no: 'sh0475',
    description_en: "Nebula - Short Legs brings Gamora's cyborg sister to LEGO form in junior format. This figure showcases the assassin-turned-Guardian with short legs for younger builds, capturing her distinctive blue and purple cybernetic appearance. The design maintains Nebula's fierce character while making her accessible to younger fans. A valuable junior-scale variant for Marvel collectors building complete junior Guardians rosters and introducing young fans to MCU characters.",
    description_de: "Nebula - Short Legs bringt Gamoras Cyborg-Schwester in LEGO-Form im Junior-Format. Diese Figur präsentiert die zur Guardianin gewordene Attentäterin mit kurzen Beinen für jüngere Bauten, erfasst ihr markantes blau-lila kybernetisches Erscheinungsbild. Das Design bewahrt Nebulas wilden Charakter, während es sie jüngeren Fans zugänglich macht. Eine wertvolle Junior-Maßstab-Variante für Marvel-Sammler, die vollständige Junior-Guardians-Aufstellungen aufbauen und junge Fans in MCU-Charaktere einführen.",
    description_fr: "Nebula - Short Legs apporte la sœur cyborg de Gamora en forme LEGO en format junior. Cette figurine présente l'assassin devenue Gardienne avec des jambes courtes pour des constructions plus jeunes, capturant son apparence cybernétique bleue et violette distinctive. Le design maintient le caractère féroce de Nebula tout en la rendant accessible aux jeunes fans. Une variante à échelle junior précieuse pour les collectionneurs Marvel construisant des listes de Gardiens junior complètes et introduisant les jeunes fans aux personnages MCU.",
    description_es: "Nebula - Short Legs trae a la hermana ciborg de Gamora en forma LEGO en formato junior. Esta figura muestra a la asesina convertida en Guardiana con piernas cortas para construcciones más jóvenes, capturando su distintiva apariencia cibernética azul y púrpura. El diseño mantiene el carácter feroz de Nebula mientras la hace accesible a fans más jóvenes. Una variante a escala junior valiosa para coleccionistas Marvel construyendo rosters completos de Guardianes junior e introduciendo fans jóvenes a personajes MCU."
  }
];

async function main() {
  console.log(`🦸 Starting Super Heroes batch sh0451-sh0475 (${descriptions.length} minifigs)...\n`);

  for (let i = 0; i < descriptions.length; i++) {
    const desc = descriptions[i];

    await prisma.minifigCatalog.update({
      where: { minifigure_no: desc.minifigure_no },
      data: {
        description_en: desc.description_en,
        description_de: desc.description_de,
        description_fr: desc.description_fr,
        description_es: desc.description_es,
        description_generated_at: new Date(),
        description_status: 'completed'
      }
    });

    console.log(`✓ Saved ${desc.minifigure_no} (${i + 1}/${descriptions.length})`);
  }

  console.log(`\n✅ Batch complete! ${descriptions.length} minifigs saved. Total: 475 done.`);
  await prisma.$disconnect();
}

main().catch(async (e) => {
  console.error('Error:', e);
  await prisma.$disconnect();
  process.exit(1);
});
