import { PrismaClient as PrismaClientHostinger } from '@prisma/client-hostinger';

const prisma = new PrismaClientHostinger({
  datasources: {
    db: {
      url: "mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker"
    }
  }
});

const descriptions = [
  {
    minifigure_no: 'sh0726',
    description_en: "Betty Brant works at the Daily Bugle as J. Jonah Jameson's secretary navigating the chaos of newspaper office life. Her relationship with Peter Parker adds romantic complications to his already complex world. This supporting character represents the personal connections that ground superhero stories. Important for Daily Bugle office displays and Spider-Man supporting cast collections.",
    description_de: "Betty Brant arbeitet beim Daily Bugle als Sekretärin von J. Jonah Jameson und navigiert das Chaos des Zeitungsbüro-Lebens. Ihre Beziehung zu Peter Parker fügt romantische Komplikationen zu seiner bereits komplexen Welt hinzu. Diese Nebenfigur repräsentiert die persönlichen Verbindungen, die Superhelden-Geschichten erden. Wichtig für Daily Bugle-Büro-Displays und Spider-Man-Nebendarsteller-Sammlungen.",
    description_fr: "Betty Brant travaille au Daily Bugle en tant que secrétaire de J. Jonah Jameson naviguant dans le chaos de la vie de bureau d'un journal. Sa relation avec Peter Parker ajoute des complications romantiques à son monde déjà complexe. Ce personnage de soutien représente les connexions personnelles qui ancrent les histoires de super-héros. Important pour les présentations de bureau du Daily Bugle et les collections de distribution de soutien de Spider-Man.",
    description_es: "Betty Brant trabaja en el Daily Bugle como secretaria de J. Jonah Jameson navegando el caos de la vida de oficina del periódico. Su relación con Peter Parker agrega complicaciones románticas a su mundo ya complejo. Este personaje de apoyo representa las conexiones personales que fundamentan historias de superhéroes. Importante para exhibiciones de oficina del Daily Bugle y colecciones de reparto de apoyo de Spider-Man."
  },
  {
    minifigure_no: 'sh0727',
    description_en: "Doctor Octopus menaces with his dark green suit and mechanical arms featuring bar attachments for enhanced grip and versatility. Otto Octavius' tentacles with bar connections create unique posing possibilities for dynamic displays. The distinctive arm design showcases different mechanical configurations. Essential Doc Ock variant for comprehensive Spider-Man villain collections.",
    description_de: "Doctor Octopus bedroht in seinem dunkelgrünen Anzug und mechanischen Armen mit Stangen-Befestigungen für verbesserten Griff und Vielseitigkeit. Otto Octavius' Tentakel mit Stangen-Verbindungen schaffen einzigartige Posing-Möglichkeiten für dynamische Displays. Das charakteristische Arm-Design zeigt verschiedene mechanische Konfigurationen. Unverzichtbare Doc Ock-Variante für umfassende Spider-Man-Schurken-Sammlungen.",
    description_fr: "Doctor Octopus menace avec son costume vert foncé et ses bras mécaniques comportant des attaches de barres pour une prise et une polyvalence améliorées. Les tentacules d'Otto Octavius avec connexions de barres créent des possibilités de pose uniques pour des présentations dynamiques. Le design de bras distinctif met en valeur différentes configurations mécaniques. Variante Doc Ock essentielle pour des collections complètes de méchants Spider-Man.",
    description_es: "Doctor Octopus amenaza con su traje verde oscuro y brazos mecánicos con accesorios de barras para agarre y versatilidad mejorados. Los tentáculos de Otto Octavius con conexiones de barras crean posibilidades únicas de poses para exhibiciones dinámicas. El distintivo diseño de brazos muestra diferentes configuraciones mecánicas. Variante esencial de Doc Ock para colecciones completas de villanos de Spider-Man."
  },
  {
    minifigure_no: 'sh0728',
    description_en: "Black Panther prowls in a distinctive costume featuring dark purple and lavender highlights creating a unique color variant. T'Challa's regal bearing and Wakandan technology make him one of Marvel's most powerful heroes. This color scheme variation offers fresh display options while maintaining the iconic panther design. Important variant for comprehensive Black Panther costume collections.",
    description_de: "Black Panther schleicht in einem charakteristischen Kostüm mit dunkellila und Lavendel-Highlights, die eine einzigartige Farbvariante schaffen. T'Challas königliche Haltung und Wakanda-Technologie machen ihn zu einem der mächtigsten Helden von Marvel. Diese Farbschema-Variation bietet frische Display-Optionen, während das ikonische Panther-Design beibehalten wird. Wichtige Variante für umfassende Black Panther-Kostüm-Sammlungen.",
    description_fr: "Black Panther rôde dans un costume distinctif présentant des reflets violet foncé et lavande créant une variante de couleur unique. Le port royal de T'Challa et la technologie du Wakanda en font l'un des héros les plus puissants de Marvel. Cette variation de schéma de couleurs offre des options d'affichage fraîches tout en conservant le design de panthère iconique. Variante importante pour des collections complètes de costumes Black Panther.",
    description_es: "Black Panther merodea con un traje distintivo con destellos púrpura oscuro y lavanda creando una variante única de color. El porte real de T'Challa y la tecnología de Wakanda lo convierten en uno de los héroes más poderosos de Marvel. Esta variación de esquema de colores ofrece opciones de exhibición frescas mientras mantiene el icónico diseño de pantera. Variante importante para colecciones completas de trajes de Black Panther."
  },
  {
    minifigure_no: 'sh0729',
    description_en: "Captain America stands ready in dark blue suit with reddish brown belt and harness, featuring reddish brown hands, hair, dark brown eyebrows, and chin strap details. Steve Rogers' tactical appearance showcases mission-ready gear with comprehensive printing. The detailed facial features and equipment harness create a fully realized combat-ready Cap. Essential for tactical Captain America displays and detailed character collections.",
    description_de: "Captain America steht bereit in dunkelblauen Anzug mit rotbraunem Gürtel und Geschirr, mit rotbraunen Händen, Haaren, dunkelbraunen Augenbrauen und Kinnriemen-Details. Steve Rogers' taktisches Erscheinungsbild zeigt missionsbereite Ausrüstung mit umfassendem Druck. Die detaillierten Gesichtszüge und Ausrüstungsgeschirr schaffen einen vollständig realisierten kampfbereiten Cap. Unverzichtbar für taktische Captain America-Displays und detaillierte Charakter-Sammlungen.",
    description_fr: "Captain America se tient prêt dans une combinaison bleu foncé avec ceinture et harnais brun rougeâtre, présentant mains brun rougeâtre, cheveux, sourcils brun foncé et détails de mentonnière. L'apparence tactique de Steve Rogers présente un équipement prêt pour la mission avec impression complète. Les traits du visage détaillés et le harnais d'équipement créent un Cap prêt au combat entièrement réalisé. Essentiel pour les présentations tactiques de Captain America et les collections de personnages détaillées.",
    description_es: "Captain America está listo con traje azul oscuro con cinturón y arnés marrón rojizo, con manos marrón rojizo, cabello, cejas marrón oscuro y detalles de correa de barbilla. La apariencia táctica de Steve Rogers muestra equipo listo para misión con impresión completa. Los rasgos faciales detallados y arnés de equipo crean un Cap listo para combate completamente realizado. Esencial para exhibiciones tácticas del Capitán América y colecciones de personajes detallados."
  },
  {
    minifigure_no: 'sh0730',
    description_en: "The Chitauri warrior invades Earth in dark bluish gray armor as part of the alien army from The Avengers. These expendable soldiers serve Thanos in his quest for universal domination. The distinctive alien design and dark coloring create perfect army-building fodder for battle displays. Essential for Avengers movie battle scenes and alien invasion collections.",
    description_de: "Der Chitauri-Krieger fällt in die Erde ein in dunkelblauen grauer Rüstung als Teil der außerirdischen Armee aus The Avengers. Diese entbehrlichen Soldaten dienen Thanos in seinem Streben nach universeller Herrschaft. Das charakteristische Alien-Design und dunkle Färbung schaffen perfektes Armee-Bau-Material für Kampf-Displays. Unverzichtbar für Avengers-Film-Kampfszenen und Alien-Invasions-Sammlungen.",
    description_fr: "Le guerrier Chitauri envahit la Terre dans une armure gris bleuté foncé dans le cadre de l'armée extraterrestre de The Avengers. Ces soldats jetables servent Thanos dans sa quête de domination universelle. Le design extraterrestre distinctif et la coloration sombre créent un matériel parfait pour la construction d'armée pour les présentations de bataille. Essentiel pour les scènes de bataille de film Avengers et les collections d'invasion extraterrestre.",
    description_es: "El guerrero Chitauri invade la Tierra con armadura gris azulado oscuro como parte del ejército alienígena de The Avengers. Estos soldados prescindibles sirven a Thanos en su búsqueda de dominación universal. El distintivo diseño alienígena y coloración oscura crean material perfecto para construcción de ejércitos para exhibiciones de batalla. Esencial para escenas de batalla de película de Avengers y colecciones de invasión alienígena."
  },
  {
    minifigure_no: 'sh0731',
    description_en: "Iron Man appears in the Mark 85 armor with visible hair showing Tony Stark beneath the helmet. This final armor from Avengers: Endgame represents the culmination of Tony's technological achievements. The exposed hair detail emphasizes the human element behind the advanced technology. Essential for Endgame displays and Tony Stark character-focused collections.",
    description_de: "Iron Man erscheint in der Mark 85-Rüstung mit sichtbaren Haaren, die Tony Stark unter dem Helm zeigen. Diese finale Rüstung aus Avengers: Endgame repräsentiert den Höhepunkt von Tonys technologischen Errungenschaften. Das exponierte Haar-Detail betont das menschliche Element hinter der fortgeschrittenen Technologie. Unverzichtbar für Endgame-Displays und Tony Stark-charakterfokussierte Sammlungen.",
    description_fr: "Iron Man apparaît dans l'armure Mark 85 avec des cheveux visibles montrant Tony Stark sous le casque. Cette armure finale d'Avengers: Endgame représente l'aboutissement des réalisations technologiques de Tony. Le détail de cheveux exposés souligne l'élément humain derrière la technologie avancée. Essentiel pour les présentations Endgame et les collections axées sur le personnage de Tony Stark.",
    description_es: "Iron Man aparece con la armadura Mark 85 con cabello visible mostrando a Tony Stark debajo del casco. Esta armadura final de Avengers: Endgame representa la culminación de los logros tecnológicos de Tony. El detalle de cabello expuesto enfatiza el elemento humano detrás de la tecnología avanzada. Esencial para exhibiciones de Endgame y colecciones enfocadas en el personaje de Tony Stark."
  },
  {
    minifigure_no: 'sh0732',
    description_en: "The Scarlet Witch channels chaos magic with plain legs and reddish brown hair representing Wanda Maximoff's powerful presence. Her reality-warping abilities make her one of the MCU's most formidable heroes. This appearance captures Wanda during key story moments with simplified costume design. Essential for Avengers team displays and Scarlet Witch character collections.",
    description_de: "Die Scarlet Witch kanalisiert Chaos-Magie mit einfachen Beinen und rotbraunen Haaren, die Wanda Maximoffs mächtige Präsenz repräsentieren. Ihre realitätsverzerrenden Fähigkeiten machen sie zu einer der gewaltigsten Heldinnen des MCU. Dieses Erscheinungsbild fängt Wanda während wichtiger Story-Momente mit vereinfachtem Kostümdesign ein. Unverzichtbar für Avengers-Team-Displays und Scarlet Witch-Charakter-Sammlungen.",
    description_fr: "La Sorcière Rouge canalise la magie du chaos avec des jambes unies et des cheveux brun rougeâtre représentant la présence puissante de Wanda Maximoff. Ses capacités de distorsion de la réalité en font l'une des héroïnes les plus formidables du MCU. Cette apparence capture Wanda lors de moments clés de l'histoire avec un design de costume simplifié. Essentielle pour les présentations d'équipe Avengers et les collections de personnages Sorcière Rouge.",
    description_es: "La Bruja Escarlata canaliza magia del caos con piernas lisas y cabello marrón rojizo representando la poderosa presencia de Wanda Maximoff. Sus habilidades de deformar la realidad la convierten en una de las heroínas más formidables del MCU. Esta apariencia captura a Wanda durante momentos clave de la historia con diseño de traje simplificado. Esencial para exhibiciones del equipo Avengers y colecciones de personajes de Bruja Escarlata."
  },
  {
    minifigure_no: 'sh0733',
    description_en: "Thanos towers in giant form wearing dark bluish gray outfit with gold armor and printed legs, featuring an unusual smile. This large-scale Mad Titan showcases his imposing physical presence with detailed costume printing. The unexpected smile expression adds unique character to this villain display. Essential giant figure for Infinity War and Endgame battle scenes.",
    description_de: "Thanos ragt in Riesenform auf mit dunkelblauen grauem Outfit mit goldener Rüstung und bedruckten Beinen, mit einem ungewöhnlichen Lächeln. Dieser großmaßstäbliche Mad Titan zeigt seine imposante physische Präsenz mit detailliertem Kostüm-Druck. Der unerwartete Lächeln-Ausdruck fügt einzigartigen Charakter zu diesem Schurken-Display hinzu. Unverzichtbare Riesenfigur für Infinity War- und Endgame-Kampfszenen.",
    description_fr: "Thanos se dresse sous forme géante portant une tenue gris bleuté foncé avec armure dorée et jambes imprimées, présentant un sourire inhabituel. Ce Mad Titan à grande échelle met en valeur sa présence physique imposante avec impression de costume détaillée. L'expression de sourire inattendue ajoute un caractère unique à cette présentation de méchant. Figurine géante essentielle pour les scènes de bataille Infinity War et Endgame.",
    description_es: "Thanos se eleva en forma gigante vistiendo atuendo gris azulado oscuro con armadura dorada y piernas impresas, con una sonrisa inusual. Este Titán Loco a gran escala muestra su imponente presencia física con impresión de traje detallada. La expresión de sonrisa inesperada agrega carácter único a esta exhibición de villano. Figura gigante esencial para escenas de batalla de Infinity War y Endgame."
  },
  {
    minifigure_no: 'sh0734',
    description_en: "Thor channels divine power with distinctive long dark tan hair representing the God of Thunder during specific story appearances. This hair color variant distinguishes this version from other Thor figures while maintaining his heroic presence. The unique hair styling adds variety to Thor displays. Important for collectors building comprehensive Thor costume variation collections.",
    description_de: "Thor kanalisiert göttliche Kraft mit charakteristischen langen dunkeltanfarbenen Haaren, die den Donnergott während spezifischer Story-Auftritte repräsentieren. Diese Haarfarben-Variante unterscheidet diese Version von anderen Thor-Figuren, während seine heroische Präsenz beibehalten wird. Das einzigartige Haar-Styling fügt Vielfalt zu Thor-Displays hinzu. Wichtig für Sammler, die umfassende Thor-Kostüm-Variationen-Sammlungen aufbauen.",
    description_fr: "Thor canalise un pouvoir divin avec des cheveux longs tan foncé distinctifs représentant le Dieu du Tonnerre lors d'apparitions d'histoire spécifiques. Cette variante de couleur de cheveux distingue cette version des autres figurines Thor tout en conservant sa présence héroïque. Le coiffage de cheveux unique ajoute de la variété aux présentations Thor. Important pour les collectionneurs construisant des collections complètes de variations de costume Thor.",
    description_es: "Thor canaliza poder divino con distintivo cabello largo color canela oscuro representando al Dios del Trueno durante apariciones específicas de historia. Esta variante de color de cabello distingue esta versión de otras figuras de Thor mientras mantiene su presencia heroica. El estilo único de cabello agrega variedad a las exhibiciones de Thor. Importante para coleccionistas que construyen colecciones completas de variaciones de traje de Thor."
  },
  {
    minifigure_no: 'sh0735',
    description_en: "Shuri appears in dark blue top as Wakanda's brilliant princess and technological genius. Her innovations push Wakandan science even beyond what previous generations achieved. This civilian appearance captures Shuri in her laboratory element creating breakthrough inventions. Essential for Black Panther supporting cast and Wakandan technology displays.",
    description_de: "Shuri erscheint in dunkelblauen Top als Wakandas brillante Prinzessin und technologisches Genie. Ihre Innovationen treiben die Wakanda-Wissenschaft über das hinaus, was frühere Generationen erreichten. Dieses zivile Erscheinungsbild fängt Shuri in ihrem Labor-Element ein, das bahnbrechende Erfindungen schafft. Unverzichtbar für Black Panther-Nebendarsteller und Wakanda-Technologie-Displays.",
    description_fr: "Shuri apparaît dans un haut bleu foncé en tant que princesse brillante et génie technologique du Wakanda. Ses innovations poussent la science du Wakanda encore au-delà de ce que les générations précédentes ont réalisé. Cette apparence civile capture Shuri dans son élément de laboratoire créant des inventions révolutionnaires. Essentiel pour la distribution de soutien de Black Panther et les présentations de technologie du Wakanda.",
    description_es: "Shuri aparece con top azul oscuro como la brillante princesa y genio tecnológico de Wakanda. Sus innovaciones impulsan la ciencia de Wakanda incluso más allá de lo que generaciones anteriores lograron. Esta apariencia civil captura a Shuri en su elemento de laboratorio creando invenciones revolucionarias. Esencial para reparto de apoyo de Black Panther y exhibiciones de tecnología de Wakanda."
  },
  {
    minifigure_no: 'sh0736',
    description_en: "Captain America charges into battle in dark blue suit with reddish brown belt and harness, featuring reddish brown hands and iconic helmet. Steve Rogers' combat-ready appearance emphasizes tactical functionality with comprehensive equipment details. The helmet-wearing version captures Cap during intense battle sequences. Essential for Captain America combat displays and Avengers action scenes.",
    description_de: "Captain America stürmt in die Schlacht in dunkelblauen Anzug mit rotbraunem Gürtel und Geschirr, mit rotbraunen Händen und ikonischem Helm. Steve Rogers' kampfbereites Erscheinungsbild betont taktische Funktionalität mit umfassenden Ausrüstungs-Details. Die helm-tragende Version fängt Cap während intensiver Kampfsequenzen ein. Unverzichtbar für Captain America-Kampf-Displays und Avengers-Action-Szenen.",
    description_fr: "Captain America charge au combat dans une combinaison bleu foncé avec ceinture et harnais brun rougeâtre, présentant des mains brun rougeâtre et un casque iconique. L'apparence prête au combat de Steve Rogers met l'accent sur la fonctionnalité tactique avec des détails d'équipement complets. La version portant un casque capture Cap lors de séquences de bataille intenses. Essentiel pour les présentations de combat de Captain America et les scènes d'action Avengers.",
    description_es: "Captain America carga a la batalla con traje azul oscuro con cinturón y arnés marrón rojizo, con manos marrón rojizo y casco icónico. La apariencia lista para combate de Steve Rogers enfatiza funcionalidad táctica con detalles de equipo completos. La versión con casco captura a Cap durante secuencias de batalla intensas. Esencial para exhibiciones de combate del Capitán América y escenas de acción de Avengers."
  },
  {
    minifigure_no: 'sh0737',
    description_en: "The Hydra Agent serves the terrorist organization dedicated to world domination through superior weaponry and infiltration. These faceless soldiers represent the countless operatives working to undermine freedom. The distinctive Hydra uniform makes these henchmen perfect for army building. Essential for Captain America villain displays and HYDRA organization collections.",
    description_de: "Der Hydra-Agent dient der terroristischen Organisation, die sich der Weltherrschaft durch überlegene Bewaffnung und Infiltration verschrieben hat. Diese gesichtslosen Soldaten repräsentieren die zahllosen Operativen, die daran arbeiten, Freiheit zu untergraben. Die charakteristische Hydra-Uniform macht diese Handlanger perfekt für Armeeaufbau. Unverzichtbar für Captain America-Schurken-Displays und HYDRA-Organisations-Sammlungen.",
    description_fr: "L'agent Hydra sert l'organisation terroriste dédiée à la domination mondiale par armement supérieur et infiltration. Ces soldats sans visage représentent les innombrables opérateurs travaillant à saper la liberté. L'uniforme Hydra distinctif rend ces hommes de main parfaits pour la construction d'armée. Essentiel pour les présentations de méchants Captain America et les collections d'organisation HYDRA.",
    description_es: "El agente Hydra sirve a la organización terrorista dedicada a la dominación mundial a través de armamento superior e infiltración. Estos soldados sin rostro representan a los innumerables operativos trabajando para socavar la libertad. El distintivo uniforme de Hydra hace que estos secuaces sean perfectos para construcción de ejércitos. Esencial para exhibiciones de villanos del Capitán América y colecciones de organización HYDRA."
  },
  {
    minifigure_no: 'sh0738',
    description_en: "Obadiah Stane appears as Tony Stark's treacherous mentor who became the Iron Monger. This corrupt businessman represents betrayal from within as he weaponizes Stark technology for profit. His civilian appearance captures the villain before donning massive armor. Essential antagonist for Iron Man origin story displays and corporate villain collections.",
    description_de: "Obadiah Stane erscheint als Tony Starks verräterischer Mentor, der zum Iron Monger wurde. Dieser korrupte Geschäftsmann repräsentiert Verrat von innen, während er Stark-Technologie für Profit bewaffnet. Sein ziviles Erscheinungsbild fängt den Schurken ein, bevor er massive Rüstung anlegt. Unverzichtbarer Antagonist für Iron Man-Ursprungsgeschichte-Displays und Unternehmens-Schurken-Sammlungen.",
    description_fr: "Obadiah Stane apparaît comme le mentor traître de Tony Stark qui est devenu l'Iron Monger. Cet homme d'affaires corrompu représente la trahison de l'intérieur alors qu'il militarise la technologie Stark pour le profit. Son apparence civile capture le méchant avant de revêtir une armure massive. Antagoniste essentiel pour les présentations de l'histoire d'origine d'Iron Man et les collections de méchants d'entreprise.",
    description_es: "Obadiah Stane aparece como el traidor mentor de Tony Stark que se convirtió en Iron Monger. Este empresario corrupto representa traición desde dentro mientras militariza la tecnología Stark para beneficio. Su apariencia civil captura al villano antes de ponerse armadura masiva. Antagonista esencial para exhibiciones de historia de origen de Iron Man y colecciones de villanos corporativos."
  },
  {
    minifigure_no: 'sh0739',
    description_en: "Iron Man soars in Mark 3 armor with visible hair showing Tony Stark's presence beneath the helmet. This early suit represents a crucial development stage in Iron Man's technological evolution. The exposed hair detail humanizes the advanced armor technology. Important for Iron Man origin story collections and armor progression displays.",
    description_de: "Iron Man schwebt in Mark 3-Rüstung mit sichtbaren Haaren, die Tony Starks Präsenz unter dem Helm zeigen. Dieser frühe Anzug repräsentiert eine entscheidende Entwicklungsstufe in Iron Mans technologischer Evolution. Das exponierte Haar-Detail vermenschlicht die fortgeschrittene Rüstungs-Technologie. Wichtig für Iron Man-Ursprungsgeschichte-Sammlungen und Rüstungs-Progressions-Displays.",
    description_fr: "Iron Man plane dans l'armure Mark 3 avec des cheveux visibles montrant la présence de Tony Stark sous le casque. Cette combinaison précoce représente une étape de développement cruciale dans l'évolution technologique d'Iron Man. Le détail de cheveux exposés humanise la technologie d'armure avancée. Important pour les collections d'histoire d'origine d'Iron Man et les présentations de progression d'armure.",
    description_es: "Iron Man vuela con armadura Mark 3 con cabello visible mostrando la presencia de Tony Stark debajo del casco. Este traje temprano representa una etapa de desarrollo crucial en la evolución tecnológica de Iron Man. El detalle de cabello expuesto humaniza la tecnología de armadura avanzada. Importante para colecciones de historia de origen de Iron Man y exhibiciones de progresión de armadura."
  },
  {
    minifigure_no: 'sh0740',
    description_en: "Pepper Potts appears in professional black suit with dark orange ponytail representing Tony Stark's trusted assistant and later CEO of Stark Industries. Her evolution from secretary to executive to superhero showcases character growth throughout the MCU. This business attire captures Pepper's professional competence. Essential for Stark Industries office displays and Pepper character evolution collections.",
    description_de: "Pepper Potts erscheint in professionellem schwarzen Anzug mit dunkelorangen Pferdeschwanz und repräsentiert Tony Starks vertrauenswürdige Assistentin und spätere CEO von Stark Industries. Ihre Entwicklung von Sekretärin zu Führungskraft zu Superheldin zeigt Charakter-Wachstum im gesamten MCU. Diese Geschäftskleidung fängt Peppers professionelle Kompetenz ein. Unverzichtbar für Stark Industries-Büro-Displays und Pepper-Charakter-Evolutions-Sammlungen.",
    description_fr: "Pepper Potts apparaît en costume noir professionnel avec queue de cheval orange foncé représentant l'assistante de confiance de Tony Stark et plus tard PDG de Stark Industries. Son évolution de secrétaire à cadre à super-héroïne met en valeur la croissance du personnage tout au long du MCU. Cette tenue d'affaires capture la compétence professionnelle de Pepper. Essentiel pour les présentations de bureau de Stark Industries et les collections d'évolution du personnage Pepper.",
    description_es: "Pepper Potts aparece con traje negro profesional con cola de caballo naranja oscuro representando a la asistente de confianza de Tony Stark y posterior CEO de Stark Industries. Su evolución de secretaria a ejecutiva a superheroína muestra crecimiento del personaje a lo largo del MCU. Este atuendo de negocios captura la competencia profesional de Pepper. Esencial para exhibiciones de oficina de Stark Industries y colecciones de evolución del personaje Pepper."
  },
  {
    minifigure_no: 'sh0741',
    description_en: "Captain America stands ready in dark blue suit with reddish brown belt, red hands, and visible hair. Steve Rogers' appearance with exposed hair emphasizes the man behind the shield. This costume variant offers different display options while maintaining Cap's heroic presence. Essential for Captain America character collections and civilian-adjacent displays.",
    description_de: "Captain America steht bereit in dunkelblauen Anzug mit rotbraunem Gürtel, roten Händen und sichtbaren Haaren. Steve Rogers' Erscheinungsbild mit exponiertem Haar betont den Mann hinter dem Schild. Diese Kostümvariante bietet verschiedene Display-Optionen, während Caps heroische Präsenz beibehalten wird. Unverzichtbar für Captain America-Charakter-Sammlungen und zivil-angrenzende Displays.",
    description_fr: "Captain America se tient prêt dans une combinaison bleu foncé avec ceinture brun rougeâtre, mains rouges et cheveux visibles. L'apparence de Steve Rogers avec cheveux exposés souligne l'homme derrière le bouclier. Cette variante de costume offre différentes options d'affichage tout en conservant la présence héroïque de Cap. Essentiel pour les collections de personnages Captain America et les présentations adjacentes civiles.",
    description_es: "Captain America está listo con traje azul oscuro con cinturón marrón rojizo, manos rojas y cabello visible. La apariencia de Steve Rogers con cabello expuesto enfatiza al hombre detrás del escudo. Esta variante de traje ofrece diferentes opciones de exhibición mientras mantiene la presencia heroica de Cap. Esencial para colecciones de personajes del Capitán América y exhibiciones adyacentes a civiles."
  },
  {
    minifigure_no: 'sh0742',
    description_en: "Rocket Raccoon brings weapons expertise and sarcastic attitude in his dark bluish gray outfit with reddish brown head. This genetically enhanced raccoon serves as the Guardians of the Galaxy's tactical genius and heavy weapons specialist. The distinctive coloring captures Rocket's unique appearance. Essential for Guardians team displays and cosmic Marvel collections.",
    description_de: "Rocket Raccoon bringt Waffen-Expertise und sarkastische Haltung in seinem dunkelblauen grauen Outfit mit rotbraunem Kopf. Dieser genetisch verbesserte Waschbär dient als taktisches Genie und Schwerer-Waffen-Spezialist der Guardians of the Galaxy. Die charakteristische Färbung fängt Rockets einzigartiges Erscheinungsbild ein. Unverzichtbar für Guardians-Team-Displays und kosmische Marvel-Sammlungen.",
    description_fr: "Rocket Raccoon apporte une expertise en armes et une attitude sarcastique dans sa tenue gris bleuté foncé avec tête brun rougeâtre. Ce raton laveur génétiquement amélioré sert de génie tactique et spécialiste des armes lourdes des Guardians of the Galaxy. La coloration distinctive capture l'apparence unique de Rocket. Essentiel pour les présentations d'équipe Guardians et les collections Marvel cosmiques.",
    description_es: "Rocket Raccoon trae experiencia en armas y actitud sarcástica con su atuendo gris azulado oscuro con cabeza marrón rojizo. Este mapache genéticamente mejorado sirve como genio táctico y especialista en armas pesadas de los Guardianes de la Galaxia. La coloración distintiva captura la apariencia única de Rocket. Esencial para exhibiciones del equipo Guardianes y colecciones cósmicas de Marvel."
  },
  {
    minifigure_no: 'sh0743',
    description_en: "Teen Groot stands as the adolescent version of the beloved tree hero in dark tan coloring. After sacrificing himself, Groot regrew into this rebellious teenager with all the attitude you'd expect. The smaller scale and distinct coloring separate Teen Groot from adult versions. Essential for Guardians of the Galaxy Vol. 2 displays and Groot evolution collections.",
    description_de: "Teen Groot steht als jugendliche Version des geliebten Baum-Helden in dunkeltanfarbener Färbung. Nachdem er sich selbst geopfert hatte, wuchs Groot zu diesem rebellischen Teenager mit all der Haltung nach, die man erwarten würde. Der kleinere Maßstab und die charakteristische Färbung trennen Teen Groot von erwachsenen Versionen. Unverzichtbar für Guardians of the Galaxy Vol. 2-Displays und Groot-Evolutions-Sammlungen.",
    description_fr: "Teen Groot se tient comme la version adolescente du héros arbre bien-aimé en coloration tan foncé. Après s'être sacrifié, Groot a repoussé en cet adolescent rebelle avec toute l'attitude que l'on attendrait. L'échelle plus petite et la coloration distincte séparent Teen Groot des versions adultes. Essentiel pour les présentations Guardians of the Galaxy Vol. 2 et les collections d'évolution Groot.",
    description_es: "Teen Groot se para como la versión adolescente del querido héroe árbol en coloración canela oscuro. Después de sacrificarse, Groot volvió a crecer como este adolescente rebelde con toda la actitud que esperarías. La escala más pequeña y coloración distinta separan a Teen Groot de versiones adultas. Esencial para exhibiciones de Guardianes de la Galaxia Vol. 2 y colecciones de evolución de Groot."
  },
  {
    minifigure_no: 'sh0744',
    description_en: "Star-Lord leads the Guardians of the Galaxy with black boots completing his iconic spacefaring outlaw look. Peter Quill combines Earth pop culture knowledge with cosmic adventure in the perfect roguish hero package. The black boot detail adds visual accuracy to his characteristic costume. Essential for Guardians team displays and cosmic Marvel hero collections.",
    description_de: "Star-Lord führt die Guardians of the Galaxy mit schwarzen Stiefeln, die seinen ikonischen weltraumfahrenden Gesetzlosen-Look vervollständigen. Peter Quill kombiniert Erd-Popkultur-Wissen mit kosmischem Abenteuer im perfekten schelmischen Helden-Paket. Das schwarze Stiefel-Detail fügt visuelle Genauigkeit zu seinem charakteristischen Kostüm hinzu. Unverzichtbar für Guardians-Team-Displays und kosmische Marvel-Helden-Sammlungen.",
    description_fr: "Star-Lord dirige les Guardians of the Galaxy avec des bottes noires complétant son look de hors-la-loi spatial iconique. Peter Quill combine les connaissances de la culture pop terrestre avec l'aventure cosmique dans le package de héros roguish parfait. Le détail de bottes noires ajoute une précision visuelle à son costume caractéristique. Essentiel pour les présentations d'équipe Guardians et les collections de héros Marvel cosmiques.",
    description_es: "Star-Lord lidera a los Guardianes de la Galaxia con botas negras completando su icónico aspecto de forajido espacial. Peter Quill combina conocimiento de cultura pop terrestre con aventura cósmica en el paquete perfecto de héroe pícaro. El detalle de botas negras agrega precisión visual a su traje característico. Esencial para exhibiciones del equipo Guardianes y colecciones de héroes cósmicos de Marvel."
  },
  {
    minifigure_no: 'sh0745',
    description_en: "Mantis joins the Guardians with her empathic abilities and black belt with clasps adorning her distinctive costume. This innocent alien can sense and manipulate emotions making her invaluable for both combat and diplomacy. The detailed belt showcases her unique alien fashion sense. Essential for Guardians team displays and cosmic supporting character collections.",
    description_de: "Mantis schließt sich den Guardians mit ihren empathischen Fähigkeiten und schwarzem Gürtel mit Schnallen an, die ihr charakteristisches Kostüm schmücken. Diese unschuldige Außerirdische kann Emotionen spüren und manipulieren, was sie sowohl für Kampf als auch Diplomatie unschätzbar macht. Der detaillierte Gürtel zeigt ihren einzigartigen Alien-Mode-Sinn. Unverzichtbar für Guardians-Team-Displays und kosmische Nebendarsteller-Sammlungen.",
    description_fr: "Mantis rejoint les Guardians avec ses capacités empathiques et sa ceinture noire avec fermoirs ornant son costume distinctif. Cette extraterrestre innocente peut sentir et manipuler les émotions, la rendant inestimable pour le combat et la diplomatie. La ceinture détaillée met en valeur son sens de la mode extraterrestre unique. Essentiel pour les présentations d'équipe Guardians et les collections de personnages de soutien cosmiques.",
    description_es: "Mantis se une a los Guardianes con sus habilidades empáticas y cinturón negro con broches adornando su distintivo traje. Esta inocente alienígena puede sentir y manipular emociones haciéndola invaluable tanto para combate como diplomacia. El cinturón detallado muestra su único sentido de moda alienígena. Esencial para exhibiciones del equipo Guardianes y colecciones de personajes de apoyo cósmicos."
  },
  {
    minifigure_no: 'sh0746',
    description_en: "The Watcher observes as the cosmic being who witnesses all events across the multiverse without interference. Uatu's oath of non-intervention creates dramatic tension when he must decide whether to act. This powerful entity represents the ultimate impartial observer of Marvel's infinite realities. Essential for What If...? displays and cosmic entity collections.",
    description_de: "Der Watcher beobachtet als kosmisches Wesen, das alle Ereignisse im Multiversum ohne Einmischung bezeugt. Uatus Eid der Nicht-Intervention schafft dramatische Spannung, wenn er entscheiden muss, ob er handeln soll. Diese mächtige Entität repräsentiert den ultimativen unparteiischen Beobachter von Marvels unendlichen Realitäten. Unverzichtbar für What If...?-Displays und kosmische Entitäts-Sammlungen.",
    description_fr: "Le Watcher observe en tant qu'être cosmique qui est témoin de tous les événements à travers le multivers sans interférence. Le serment de non-intervention d'Uatu crée une tension dramatique lorsqu'il doit décider d'agir ou non. Cette entité puissante représente l'observateur impartial ultime des réalités infinies de Marvel. Essentiel pour les présentations What If...? et les collections d'entités cosmiques.",
    description_es: "The Watcher observa como el ser cósmico que presencia todos los eventos a través del multiverso sin interferencia. El juramento de no intervención de Uatu crea tensión dramática cuando debe decidir si actuar. Esta poderosa entidad representa al observador imparcial definitivo de las infinitas realidades de Marvel. Esencial para exhibiciones de What If...? y colecciones de entidades cósmicas."
  },
  {
    minifigure_no: 'sh0747',
    description_en: "Tony Stark appears in black shirt with gold helmet showing the transition between civilian and Iron Man identities. This hybrid appearance captures moments of suiting up or revealing his identity. The combination of casual clothing with armor piece creates unique character display options. Important for Tony Stark character-focused collections showing the man behind Iron Man.",
    description_de: "Tony Stark erscheint in schwarzem Hemd mit goldenem Helm und zeigt den Übergang zwischen ziviler und Iron Man-Identität. Dieses hybride Erscheinungsbild fängt Momente des Anzuganlegens oder Enthüllens seiner Identität ein. Die Kombination von lässiger Kleidung mit Rüstungsstück schafft einzigartige Charakter-Display-Optionen. Wichtig für Tony Stark-charakterfokussierte Sammlungen, die den Mann hinter Iron Man zeigen.",
    description_fr: "Tony Stark apparaît en chemise noire avec casque doré montrant la transition entre identités civiles et Iron Man. Cette apparence hybride capture les moments d'enfilage de costume ou de révélation de son identité. La combinaison de vêtements décontractés avec pièce d'armure crée des options d'affichage de personnage uniques. Important pour les collections axées sur le personnage de Tony Stark montrant l'homme derrière Iron Man.",
    description_es: "Tony Stark aparece con camisa negra con casco dorado mostrando la transición entre identidades civil e Iron Man. Esta apariencia híbrida captura momentos de ponerse el traje o revelar su identidad. La combinación de ropa casual con pieza de armadura crea opciones únicas de exhibición de personaje. Importante para colecciones enfocadas en el personaje de Tony Stark mostrando al hombre detrás de Iron Man."
  },
  {
    minifigure_no: 'sh0748',
    description_en: "Valkyrie charges into battle in pearl dark gray suit as Asgard's legendary warrior and eventual king. Her fierce combat skills and tragic past make her one of Thor's most compelling allies. The distinctive suit coloring sets this version apart from other Valkyrie appearances. Essential for Thor: Ragnarok displays and Asgardian warrior collections.",
    description_de: "Valkyrie stürmt in die Schlacht in perldunkelgrauem Anzug als Asgards legendäre Kriegerin und eventuelle Königin. Ihre heftigen Kampffähigkeiten und tragische Vergangenheit machen sie zu einer der fesselndsten Verbündeten Thors. Die charakteristische Anzug-Färbung hebt diese Version von anderen Valkyrie-Auftritten ab. Unverzichtbar für Thor: Ragnarok-Displays und asgardische Krieger-Sammlungen.",
    description_fr: "Valkyrie charge au combat dans une combinaison gris foncé perlé en tant que guerrière légendaire d'Asgard et futur roi. Ses compétences de combat féroces et son passé tragique en font l'une des alliées les plus convaincantes de Thor. La coloration de combinaison distinctive distingue cette version des autres apparitions de Valkyrie. Essentiel pour les présentations Thor: Ragnarok et les collections de guerriers asgardiens.",
    description_es: "Valkyrie carga a la batalla con traje gris oscuro perlado como la legendaria guerrera de Asgard y eventual rey. Sus feroces habilidades de combate y pasado trágico la convierten en una de las aliadas más convincentes de Thor. La coloración distintiva del traje distingue esta versión de otras apariciones de Valkyrie. Esencial para exhibiciones de Thor: Ragnarok y colecciones de guerreros asgardianos."
  },
  {
    minifigure_no: 'sh0749',
    description_en: "Captain Peggy Carter proves herself as Britain's first super-soldier in her stealth suit from the What If...? multiverse. This alternate reality shows what happens when Peggy received the super-soldier serum instead of Steve Rogers. The tactical stealth design showcases her espionage expertise. Essential for What If...? displays and alternate universe hero collections.",
    description_de: "Captain Peggy Carter beweist sich als Britanniens erste Super-Soldatin in ihrem Stealth-Anzug aus dem What If...?-Multiversum. Diese alternative Realität zeigt, was passiert, wenn Peggy das Super-Soldaten-Serum statt Steve Rogers erhielt. Das taktische Stealth-Design zeigt ihre Spionage-Expertise. Unverzichtbar für What If...?-Displays und alternative Universum-Helden-Sammlungen.",
    description_fr: "Captain Peggy Carter se prouve en tant que premier super-soldat de Grande-Bretagne dans sa combinaison furtive du multivers What If...?. Cette réalité alternative montre ce qui se passe lorsque Peggy a reçu le sérum de super-soldat au lieu de Steve Rogers. Le design furtif tactique met en valeur son expertise en espionnage. Essentiel pour les présentations What If...? et les collections de héros d'univers alternatif.",
    description_es: "Captain Peggy Carter se prueba como la primera supersoldado de Gran Bretaña con su traje de sigilo del multiverso What If...?. Esta realidad alternativa muestra qué sucede cuando Peggy recibió el suero de supersoldado en lugar de Steve Rogers. El diseño táctico de sigilo muestra su experiencia en espionaje. Esencial para exhibiciones de What If...? y colecciones de héroes de universo alternativo."
  },
  {
    minifigure_no: 'sh0750',
    description_en: "Red Skull menaces with detailed printed legs enhancing his Nazi villain appearance. Johann Schmidt's transformation into the Red Skull created Captain America's ultimate nemesis. The comprehensive leg printing adds visual detail to this iconic villain. Essential for Captain America displays and HYDRA villain collections with maximum character detail.",
    description_de: "Red Skull bedroht mit detailliert bedruckten Beinen, die sein Nazi-Schurken-Erscheinungsbild verbessern. Johann Schmidts Transformation in den Red Skull schuf Captain Americas ultimativen Nemesis. Der umfassende Bein-Druck fügt visuelle Details zu diesem ikonischen Schurken hinzu. Unverzichtbar für Captain America-Displays und HYDRA-Schurken-Sammlungen mit maximalen Charakter-Details.",
    description_fr: "Red Skull menace avec des jambes imprimées détaillées améliorant son apparence de méchant nazi. La transformation de Johann Schmidt en Red Skull a créé le némésis ultime de Captain America. L'impression complète des jambes ajoute des détails visuels à ce méchant iconique. Essentiel pour les présentations Captain America et les collections de méchants HYDRA avec un maximum de détails de personnage.",
    description_es: "Red Skull amenaza con piernas impresas detalladas mejorando su apariencia de villano nazi. La transformación de Johann Schmidt en Red Skull creó el némesis definitivo del Capitán América. La impresión completa de piernas agrega detalle visual a este villano icónico. Esencial para exhibiciones del Capitán América y colecciones de villanos HYDRA con máximo detalle de personaje."
  }
];

async function main() {
  console.log(`🦸 Starting Super Heroes batch sh0726-sh0750 (${descriptions.length} minifigs)...\n`);

  for (let i = 0; i < descriptions.length; i++) {
    const desc = descriptions[i];

    await prisma.minifigCatalog.update({
      where: { minifigure_no: desc.minifigure_no },
      data: {
        description_en: desc.description_en,
        description_de: desc.description_de,
        description_fr: desc.description_fr,
        description_es: desc.description_es,
        description_generated_at: new Date(),
        description_status: 'completed'
      }
    });

    console.log(`✓ Saved ${desc.minifigure_no} (${i + 1}/${descriptions.length})`);
  }

  console.log(`\n✅ Batch complete! ${descriptions.length} minifigs saved. Total: 750 done.`);
  await prisma.$disconnect();
}

main().catch(async (e) => {
  console.error('Error:', e);
  await prisma.$disconnect();
  process.exit(1);
});
