import { PrismaClient as PrismaClientHostinger } from '@prisma/client-hostinger';

const prisma = new PrismaClientHostinger({
  datasources: {
    db: {
      url: "mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker"
    }
  }
});

const descriptions = [
  {
    minifigure_no: 'sh0021',
    description_en: "This Two-Face's Henchman minifigure from 2012 features a criminal wearing orange and purple colors matching his boss's twisted duality, distinguished by a beard. The figure represents one of Harvey Dent's loyal thugs who carry out the coin-flipping villain's crimes across Gotham City. As part of Two-Face's gang, this minifigure adds authenticity to Batman crime scene builds with appropriate color-coded costume details. Collectors value this army-building figure for creating realistic Gotham underworld scenarios and expanding their rogues gallery displays with supporting villains.",
    description_de: "Diese Two-Face's Henchman-Minifigur von 2012 zeigt einen Kriminellen in orange-violetten Farben, die zur verdrehten Dualität seines Bosses passen, mit charakteristischem Bart. Die Figur repräsentiert einen von Harvey Dents treuen Schlägern, die die Verbrechen des münzwerfenden Schurken in Gotham City ausführen. Als Teil von Two-Faces Gang verleiht diese Minifigur Batman-Verbrechensszenen Authentizität mit angemessenen farbkodierten Kostümdetails. Sammler schätzen diese Armee-Aufbau-Figur für die Erstellung realistischer Gotham-Unterwelt-Szenarien und die Erweiterung ihrer Schurkengalerie-Displays mit unterstützenden Schurken.",
    description_fr: "Cette minifigurine de l'Homme de Main de Two-Face de 2012 présente un criminel portant des couleurs orange et violet correspondant à la dualité tordue de son patron, distingué par une barbe. La figurine représente l'un des voyous loyaux de Harvey Dent qui exécutent les crimes du méchant lanceur de pièces à travers Gotham City. En tant que partie du gang de Two-Face, cette minifigurine ajoute de l'authenticité aux constructions de scènes de crime de Batman avec des détails de costume codés par couleur appropriés. Les collectionneurs apprécient cette figurine de construction d'armée pour créer des scénarios réalistes du monde souterrain de Gotham et agrandir leurs présentations de galerie des ennemis avec des méchants de soutien.",
    description_es: "Esta minifigura de Secuaz de Dos Caras de 2012 presenta a un criminal vistiendo colores naranja y púrpura que coinciden con la dualidad retorcida de su jefe, distinguido por una barba. La figura representa uno de los matones leales de Harvey Dent que llevan a cabo los crímenes del villano lanzador de monedas en Ciudad Gótica. Como parte de la pandilla de Dos Caras, esta minifigura añade autenticidad a las construcciones de escenas de crimen de Batman con detalles de vestuario codificados por color apropiados. Los coleccionistas valoran esta figura de construcción de ejército para crear escenarios realistas del submundo de Gotham y expandir sus exhibiciones de galería de villanos con villanos de apoyo."
  },
  {
    minifigure_no: 'sh0022',
    description_en: "This Two-Face's Henchman minifigure from 2012 wears the distinctive orange and purple gang colors with sunglasses, representing another member of Harvey Dent's criminal organization. The figure showcases a different henchman variant with eyewear, allowing collectors to build diverse criminal crews for their Gotham displays. As one of Two-Face's enforcers who execute the duality-obsessed villain's schemes, this minifigure adds variety to Batman rogues gallery scenes. Collectors appreciate having multiple henchman variants for army building and creating authentic Two-Face criminal operations.",
    description_de: "Diese Two-Face's Henchman-Minifigur von 2012 trägt die markanten orange-violetten Gangfarben mit Sonnenbrille und repräsentiert ein weiteres Mitglied von Harvey Dents krimineller Organisation. Die Figur zeigt eine andere Handlanger-Variante mit Augenausstattung, die es Sammlern ermöglicht, vielfältige kriminelle Crews für ihre Gotham-Displays aufzubauen. Als einer von Two-Faces Vollstreckern, die die Pläne des dualitätsbesessenen Schurken ausführen, fügt diese Minifigur Vielfalt zu Batman-Schurkengalerie-Szenen hinzu. Sammler schätzen mehrere Handlanger-Varianten für den Armee-Aufbau und die Erstellung authentischer Two-Face-Kriminaloperationen.",
    description_fr: "Cette minifigurine de l'Homme de Main de Two-Face de 2012 porte les couleurs de gang orange et violet distinctives avec des lunettes de soleil, représentant un autre membre de l'organisation criminelle de Harvey Dent. La figurine présente une variante différente d'homme de main avec des lunettes, permettant aux collectionneurs de construire des équipes criminelles diverses pour leurs présentations Gotham. En tant que l'un des exécuteurs de Two-Face qui exécutent les plans du méchant obsédé par la dualité, cette minifigurine ajoute de la variété aux scènes de galerie des ennemis de Batman. Les collectionneurs apprécient d'avoir plusieurs variantes d'hommes de main pour la construction d'armée et la création d'opérations criminelles authentiques de Two-Face.",
    description_es: "Esta minifigura de Secuaz de Dos Caras de 2012 viste los distintivos colores de pandilla naranja y púrpura con gafas de sol, representando otro miembro de la organización criminal de Harvey Dent. La figura muestra una variante diferente de secuaz con gafas, permitiendo a los coleccionistas construir equipos criminales diversos para sus exhibiciones de Gotham. Como uno de los ejecutores de Dos Caras que ejecutan los esquemas del villano obsesionado con la dualidad, esta minifigura añade variedad a las escenas de galería de villanos de Batman. Los coleccionistas aprecian tener múltiples variantes de secuaces para construcción de ejército y crear operaciones criminales auténticas de Dos Caras."
  },
  {
    minifigure_no: 'sh0023',
    description_en: "This Guard minifigure from 2012 represents a generic security personnel from the Batman II theme, useful for creating various Gotham City scenarios. The figure serves as a versatile civilian character that can be used in multiple contexts including bank heists, museum robberies, or facility security scenes. As a supporting character in Batman's world, this guard adds realism to crime scene builds where villains clash with regular security before Batman arrives. Collectors value this generic figure type for its flexibility in building diverse Gotham City stories and locations.",
    description_de: "Diese Guard-Minifigur von 2012 repräsentiert generisches Sicherheitspersonal aus dem Batman II Thema, nützlich für die Erstellung verschiedener Gotham City Szenarien. Die Figur dient als vielseitiger Zivilcharakter, der in mehreren Kontexten verwendet werden kann, einschließlich Banküberfällen, Museumseinbrüchen oder Anlagesicherheitsszenen. Als unterstützender Charakter in Batmans Welt fügt dieser Wächter Realismus zu Verbrechensszenen-Builds hinzu, wo Schurken mit regulärer Sicherheit zusammenstoßen, bevor Batman ankommt. Sammler schätzen diesen generischen Figurentyp für seine Flexibilität beim Aufbau vielfältiger Gotham City Geschichten und Orte.",
    description_fr: "Cette minifigurine de Garde de 2012 représente un personnel de sécurité générique du thème Batman II, utile pour créer divers scénarios de Gotham City. La figurine sert de personnage civil polyvalent qui peut être utilisé dans plusieurs contextes, y compris les cambriolages de banque, les vols de musée ou les scènes de sécurité des installations. En tant que personnage de soutien dans le monde de Batman, ce garde ajoute du réalisme aux constructions de scènes de crime où les méchants s'affrontent avec la sécurité régulière avant l'arrivée de Batman. Les collectionneurs apprécient ce type de figurine générique pour sa flexibilité dans la construction d'histoires et de lieux diversifiés de Gotham City.",
    description_es: "Esta minifigura de Guardia de 2012 representa personal de seguridad genérico del tema Batman II, útil para crear varios escenarios de Ciudad Gótica. La figura sirve como personaje civil versátil que puede usarse en múltiples contextos incluyendo atracos bancarios, robos de museos o escenas de seguridad de instalaciones. Como personaje de apoyo en el mundo de Batman, este guardia añade realismo a las construcciones de escenas de crimen donde los villanos chocan con seguridad regular antes de que Batman llegue. Los coleccionistas valoran este tipo de figura genérica por su flexibilidad en construir diversas historias y ubicaciones de Ciudad Gótica."
  },
  {
    minifigure_no: 'sh0024',
    description_en: "This Harley Quinn minifigure from 2012 captures the Joker's loyal girlfriend and accomplice with black and red hands matching her iconic jester costume. The figure features Harley's classic red and black diamond pattern outfit, white face makeup, and blonde pigtails, representing the chaotic anti-heroine from Batman's rogues gallery. As the Joker's partner in crime who brings her own brand of mayhem to Gotham, this minifigure embodies the unpredictable and dangerous nature of Batman's most colorful villains. Collectors value this early Harley Quinn release for its faithful comic book design and popularity as one of DC's most beloved characters.",
    description_de: "Diese Harley Quinn-Minifigur von 2012 fängt die treue Freundin und Komplizin des Jokers mit schwarz-roten Händen ein, die zu ihrem ikonischen Narrenkostüm passen. Die Figur zeigt Harleys klassisches rot-schwarzes Rautenmuster-Outfit, weißes Gesichts-Make-up und blonde Zöpfe und repräsentiert die chaotische Anti-Heldin aus Batmans Schurkengalerie. Als Jokers Partnerin im Verbrechen, die ihre eigene Art von Chaos nach Gotham bringt, verkörpert diese Minifigur die unberechenbare und gefährliche Natur von Batmans farbenfrohsten Schurken. Sammler schätzen diese frühe Harley Quinn Veröffentlichung für ihr treues Comic-Design und Beliebtheit als einer von DCs beliebtesten Charakteren.",
    description_fr: "Cette minifigurine Harley Quinn de 2012 capture la petite amie loyale et complice du Joker avec des mains noires et rouges correspondant à son costume de bouffon emblématique. La figurine présente la tenue classique à motif de diamant rouge et noir de Harley, le maquillage facial blanc et les couettes blondes, représentant l'anti-héroïne chaotique de la galerie des ennemis de Batman. En tant que partenaire dans le crime du Joker qui apporte sa propre marque de chaos à Gotham, cette minifigurine incarne la nature imprévisible et dangereuse des méchants les plus colorés de Batman. Les collectionneurs apprécient cette sortie précoce de Harley Quinn pour sa conception fidèle aux bandes dessinées et sa popularité en tant que l'un des personnages les plus aimés de DC.",
    description_es: "Esta minifigura de Harley Quinn de 2012 captura a la novia leal y cómplice del Joker con manos negras y rojas que coinciden con su icónico traje de bufón. La figura presenta el clásico atuendo de patrón de diamante rojo y negro de Harley, maquillaje facial blanco y coletas rubias, representando a la antiheroína caótica de la galería de villanos de Batman. Como socia en el crimen del Joker que trae su propia marca de caos a Gotham, esta minifigura encarna la naturaleza impredecible y peligrosa de los villanos más coloridos de Batman. Los coleccionistas valoran este lanzamiento temprano de Harley Quinn por su diseño fiel al cómic y popularidad como uno de los personajes más queridos de DC."
  },
  {
    minifigure_no: 'sh0025',
    description_en: "This Batman minifigure from 2012 features an alternate light bluish gray suit with yellow utility belt and bat crest, dark blue mask and cape with Type 1 cowl design. The figure represents a unique color variant of the Dark Knight that stands out from the traditional black costume, possibly representing different lighting conditions or a specialized mission suit. As one of multiple Batman variants in the Super Heroes line, this figure showcases LEGO's commitment to offering diverse versions of the character. Collectors appreciate this lighter-colored Batman for its distinctive appearance and variety in their Gotham City displays.",
    description_de: "Diese Batman-Minifigur von 2012 zeigt einen alternativen hellblaugrauen Anzug mit gelbem Utility-Gürtel und Fledermaus-Wappen, dunkelblauer Maske und Cape mit Type 1 Kapuzendesign. Die Figur repräsentiert eine einzigartige Farbvariante des Dunklen Ritters, die sich vom traditionellen schwarzen Kostüm abhebt und möglicherweise unterschiedliche Lichtverhältnisse oder einen spezialisierten Missionsanzug darstellt. Als eine von mehreren Batman-Varianten in der Super Heroes Linie zeigt diese Figur LEGOs Engagement, vielfältige Versionen des Charakters anzubieten. Sammler schätzen diesen heller gefärbten Batman für sein markantes Erscheinungsbild und Vielfalt in ihren Gotham City Displays.",
    description_fr: "Cette minifigurine Batman de 2012 présente un costume gris bleuté clair alternatif avec ceinture utilitaire jaune et écusson de chauve-souris, masque et cape bleu foncé avec design de cagoule Type 1. La figurine représente une variante de couleur unique du Chevalier Noir qui se démarque du costume noir traditionnel, représentant peut-être différentes conditions d'éclairage ou un costume de mission spécialisé. En tant que l'une des multiples variantes de Batman dans la gamme Super Heroes, cette figurine présente l'engagement de LEGO à offrir diverses versions du personnage. Les collectionneurs apprécient ce Batman de couleur plus claire pour son apparence distinctive et sa variété dans leurs présentations de Gotham City.",
    description_es: "Esta minifigura de Batman de 2012 presenta un traje gris azulado claro alternativo con cinturón utilitario amarillo y emblema de murciélago, máscara y capa azul oscuro con diseño de capucha Tipo 1. La figura representa una variante de color única del Caballero Oscuro que se destaca del traje negro tradicional, posiblemente representando diferentes condiciones de iluminación o un traje de misión especializado. Como una de las múltiples variantes de Batman en la línea Super Heroes, esta figura muestra el compromiso de LEGO de ofrecer versiones diversas del personaje. Los coleccionistas aprecian este Batman de color más claro por su apariencia distintiva y variedad en sus exhibiciones de Ciudad Gótica."
  },
  {
    minifigure_no: 'sh0026',
    description_en: "This Bruce Wayne minifigure from 2012 reveals Batman's civilian identity wearing a sand blue business suit, representing the billionaire playboy philanthropist persona. The figure allows collectors to display the man behind the mask, showcasing Bruce Wayne's public face as Gotham's wealthiest citizen and owner of Wayne Enterprises. As the rare non-costumed version of Batman, this minifigure is essential for creating Wayne Manor scenes, charity galas, or moments before Bruce suits up to fight crime. Collectors value this figure for adding depth to Batman displays by showing his dual identity beyond just the Dark Knight persona.",
    description_de: "Diese Bruce Wayne-Minifigur von 2012 enthüllt Batmans zivile Identität in einem sandblauem Geschäftsanzug und repräsentiert die Milliardär-Playboy-Philanthropen-Persona. Die Figur ermöglicht es Sammlern, den Mann hinter der Maske zu zeigen und Bruce Waynes öffentliches Gesicht als Gothams reichster Bürger und Besitzer von Wayne Enterprises zu präsentieren. Als seltene nicht-kostümierte Version von Batman ist diese Minifigur wesentlich für die Erstellung von Wayne Manor Szenen, Wohltätigkeitsgalas oder Momenten, bevor Bruce sich anzieht, um Verbrechen zu bekämpfen. Sammler schätzen diese Figur dafür, Batman-Displays Tiefe zu verleihen, indem sie seine duale Identität jenseits der Dunklen Ritter Persona zeigt.",
    description_fr: "Cette minifigurine Bruce Wayne de 2012 révèle l'identité civile de Batman portant un costume d'affaires bleu sable, représentant la personnalité de playboy philanthrope milliardaire. La figurine permet aux collectionneurs d'afficher l'homme derrière le masque, présentant le visage public de Bruce Wayne en tant que citoyen le plus riche de Gotham et propriétaire de Wayne Enterprises. En tant que version rare non costumée de Batman, cette minifigurine est essentielle pour créer des scènes de Wayne Manor, des galas de charité ou des moments avant que Bruce ne s'habille pour combattre le crime. Les collectionneurs apprécient cette figurine pour ajouter de la profondeur aux présentations Batman en montrant sa double identité au-delà de la simple personnalité du Chevalier Noir.",
    description_es: "Esta minifigura de Bruce Wayne de 2012 revela la identidad civil de Batman vistiendo un traje de negocios azul arena, representando la personalidad de multimillonario playboy filántropo. La figura permite a los coleccionistas mostrar al hombre detrás de la máscara, mostrando la cara pública de Bruce Wayne como el ciudadano más rico de Gotham y propietario de Wayne Enterprises. Como la rara versión sin disfraz de Batman, esta minifigura es esencial para crear escenas de Wayne Manor, galas benéficas o momentos antes de que Bruce se vista para luchar contra el crimen. Los coleccionistas valoran esta figura por añadir profundidad a las exhibiciones de Batman mostrando su identidad dual más allá de la personalidad del Caballero Oscuro."
  },
  {
    minifigure_no: 'sh0027',
    description_en: "This Iron Man Model 37 Armor minifigure from 2012 was an exclusive Toy Fair release, representing one of Tony Stark's many specialized suit designs. The figure features unique armor detailing that distinguishes it from standard Iron Man variants, making it a highly sought-after exclusive for Marvel collectors. As a limited promotional release from the 2012 Toy Fair, this minifigure showcases LEGO's tradition of creating special event exclusives. Collectors prize this rare variant for its limited availability and representation of Iron Man's ever-evolving armor technology in the Marvel Universe.",
    description_de: "Diese Iron Man Model 37 Rüstungs-Minifigur von 2012 war eine exklusive Toy Fair Veröffentlichung und repräsentiert eines von Tony Starks vielen spezialisierten Anzugdesigns. Die Figur zeigt einzigartige Rüstungsdetails, die sie von Standard-Iron Man-Varianten unterscheiden und sie zu einer sehr begehrten Exklusivität für Marvel-Sammler machen. Als limitierte Werbe-Veröffentlichung von der Toy Fair 2012 zeigt diese Minifigur LEGOs Tradition, spezielle Event-Exklusivitäten zu schaffen. Sammler schätzen diese seltene Variante für ihre begrenzte Verfügbarkeit und Darstellung von Iron Mans sich ständig weiterentwickelnder Rüstungstechnologie im Marvel-Universum.",
    description_fr: "Cette minifigurine d'Armure Iron Man Model 37 de 2012 était une sortie exclusive du Toy Fair, représentant l'un des nombreux designs de costume spécialisés de Tony Stark. La figurine présente des détails d'armure uniques qui la distinguent des variantes Iron Man standard, ce qui en fait une exclusive très recherchée pour les collectionneurs Marvel. En tant que sortie promotionnelle limitée du Toy Fair 2012, cette minifigurine présente la tradition de LEGO de créer des exclusivités d'événements spéciaux. Les collectionneurs apprécient cette variante rare pour sa disponibilité limitée et sa représentation de la technologie d'armure en constante évolution d'Iron Man dans l'univers Marvel.",
    description_es: "Esta minifigura de Armadura Modelo 37 de Iron Man de 2012 fue un lanzamiento exclusivo de Toy Fair, representando uno de los muchos diseños de traje especializado de Tony Stark. La figura presenta detalles de armadura únicos que la distinguen de las variantes estándar de Iron Man, convirtiéndola en una exclusiva muy codiciada para los coleccionistas de Marvel. Como lanzamiento promocional limitado del Toy Fair 2012, esta minifigura muestra la tradición de LEGO de crear exclusivas de eventos especiales. Los coleccionistas valoran esta variante rara por su disponibilidad limitada y representación de la tecnología de armadura en constante evolución de Iron Man en el Universo Marvel."
  },
  {
    minifigure_no: 'sh0028',
    description_en: "This Captain America minifigure from 2012 was a Toy Fair exclusive release, representing Steve Rogers in his iconic star-spangled uniform at a special promotional event. The figure showcases Cap's patriotic red, white, and blue color scheme with his signature shield, celebrating America's First Avenger. As a limited Toy Fair 2012 promotional release, this exclusive variant holds special value for Marvel Super Heroes collectors. The rarity and event-specific nature of this minifigure make it a prized addition to any Captain America or Avengers collection.",
    description_de: "Diese Captain America-Minifigur von 2012 war eine exklusive Toy Fair Veröffentlichung und repräsentiert Steve Rogers in seiner ikonischen sternenbedeckten Uniform bei einem speziellen Werbeevent. Die Figur zeigt Caps patriotisches rot-weiß-blaues Farbschema mit seinem charakteristischen Schild und feiert Amerikas Ersten Avenger. Als limitierte Toy Fair 2012 Werbe-Veröffentlichung hat diese exklusive Variante besonderen Wert für Marvel Super Heroes Sammler. Die Seltenheit und event-spezifische Natur dieser Minifigur machen sie zu einer geschätzten Ergänzung für jede Captain America oder Avengers Sammlung.",
    description_fr: "Cette minifigurine Captain America de 2012 était une sortie exclusive du Toy Fair, représentant Steve Rogers dans son uniforme étoilé emblématique lors d'un événement promotionnel spécial. La figurine présente le schéma de couleurs patriotique rouge, blanc et bleu de Cap avec son bouclier signature, célébrant le Premier Avenger d'Amérique. En tant que sortie promotionnelle limitée du Toy Fair 2012, cette variante exclusive a une valeur particulière pour les collectionneurs Marvel Super Heroes. La rareté et la nature spécifique à l'événement de cette minifigurine en font un ajout précieux à toute collection Captain America ou Avengers.",
    description_es: "Esta minifigura de Capitán América de 2012 fue un lanzamiento exclusivo de Toy Fair, representando a Steve Rogers en su icónico uniforme estrellado en un evento promocional especial. La figura muestra el esquema de colores patriótico rojo, blanco y azul de Cap con su escudo característico, celebrando al Primer Vengador de América. Como lanzamiento promocional limitado del Toy Fair 2012, esta variante exclusiva tiene un valor especial para los coleccionistas de Marvel Super Heroes. La rareza y naturaleza específica del evento de esta minifigura la convierten en una adición preciada a cualquier colección de Capitán América o Vengadores."
  },
  {
    minifigure_no: 'sh0029',
    description_en: "This Chitauri General minifigure from 2012 represents the alien military commander leading the invasion force in The Avengers film. The figure features distinctive alien armor and weaponry, showcasing the extraterrestrial threat that brings Earth's Mightiest Heroes together. As the commanding officer of the Chitauri army sent by Loki and Thanos, this minifigure embodies the cosmic-level danger facing the Avengers. Collectors value this figure for completing Avengers battle scenes and representing the pivotal Battle of New York from the MCU.",
    description_de: "Diese Chitauri General-Minifigur von 2012 repräsentiert den außerirdischen Militärkommandanten, der die Invasionstruppe im The Avengers Film anführt. Die Figur zeigt markante außerirdische Rüstung und Bewaffnung und präsentiert die außerirdische Bedrohung, die die mächtigsten Helden der Erde zusammenbringt. Als kommandierender Offizier der Chitauri-Armee, die von Loki und Thanos geschickt wurde, verkörpert diese Minifigur die kosmische Gefahr, der die Avengers gegenüberstehen. Sammler schätzen diese Figur für die Vervollständigung von Avengers-Kampfszenen und die Darstellung der entscheidenden Schlacht von New York aus dem MCU.",
    description_fr: "Cette minifigurine de Général Chitauri de 2012 représente le commandant militaire extraterrestre dirigeant la force d'invasion dans le film The Avengers. La figurine présente une armure et un armement extraterrestres distinctifs, présentant la menace extraterrestre qui rassemble les Héros les Plus Puissants de la Terre. En tant qu'officier commandant de l'armée Chitauri envoyée par Loki et Thanos, cette minifigurine incarne le danger au niveau cosmique auquel sont confrontés les Avengers. Les collectionneurs apprécient cette figurine pour compléter les scènes de bataille des Avengers et représenter la Bataille de New York pivotale du MCU.",
    description_es: "Esta minifigura de General Chitauri de 2012 representa al comandante militar alienígena que lidera la fuerza de invasión en la película The Avengers. La figura presenta armadura y armamento alienígena distintivos, mostrando la amenaza extraterrestre que reúne a los Héroes Más Poderosos de la Tierra. Como oficial al mando del ejército Chitauri enviado por Loki y Thanos, esta minifigura encarna el peligro a nivel cósmico que enfrentan los Vengadores. Los coleccionistas valoran esta figura para completar escenas de batalla de los Vengadores y representar la Batalla de Nueva York fundamental del MCU."
  },
  {
    minifigure_no: 'sh0030',
    description_en: "This Chitauri Foot Soldier minifigure from 2012 represents the alien infantry troops invading Earth in The Avengers. The figure features generic alien warrior design for army building massive invasion forces in the Battle of New York scenes. As expendable shock troops serving Loki's conquest, these soldiers embody the overwhelming numbers that challenge the Avengers. Collectors value this army-builder figure for creating epic MCU battle displays with multiple Chitauri warriors facing off against Earth's heroes.",
    description_de: "Diese Chitauri Foot Soldier-Minifigur von 2012 repräsentiert die außerirdischen Infanterietruppen, die in The Avengers die Erde überfallen. Die Figur zeigt generisches außerirdisches Kriegerdesign für den Armee-Aufbau massiver Invasionstruppen in Schlacht von New York Szenen. Als entbehrliche Stoßtruppen, die Lokis Eroberung dienen, verkörpern diese Soldaten die überwältigenden Zahlen, die die Avengers herausfordern. Sammler schätzen diese Armee-Aufbau-Figur für die Erstellung epischer MCU-Kampf-Displays mit mehreren Chitauri-Kriegern, die gegen die Helden der Erde antreten.",
    description_fr: "Cette minifigurine de Soldat Chitauri de 2012 représente les troupes d'infanterie extraterrestres envahissant la Terre dans The Avengers. La figurine présente un design de guerrier extraterrestre générique pour la construction d'armées de forces d'invasion massives dans les scènes de la Bataille de New York. En tant que troupes de choc jetables servant la conquête de Loki, ces soldats incarnent les nombres écrasants qui défient les Avengers. Les collectionneurs apprécient cette figurine de construction d'armée pour créer des présentations de bataille MCU épiques avec plusieurs guerriers Chitauri affrontant les héros de la Terre.",
    description_es: "Esta minifigura de Soldado de Infantería Chitauri de 2012 representa las tropas de infantería alienígena invadiendo la Tierra en The Avengers. La figura presenta diseño genérico de guerrero alienígena para construcción de ejército de fuerzas de invasión masivas en escenas de la Batalla de Nueva York. Como tropas de choque prescindibles sirviendo a la conquista de Loki, estos soldados encarnan los números abrumadores que desafían a los Vengadores. Los coleccionistas valoran esta figura de construcción de ejército para crear exhibiciones de batalla épicas del MCU con múltiples guerreros Chitauri enfrentándose a los héroes de la Tierra."
  },
  {
    minifigure_no: 'sh0031',
    description_en: "This Magneto minifigure from 2012 features the Master of Magnetism in his classic red outfit with cloth cape, representing one of the X-Men's most powerful adversaries. The figure showcases Magneto's iconic helmet that protects against telepathy and his distinctive costume from the comics. As the mutant who controls magnetic fields and fights for mutant supremacy, this minifigure embodies the complex anti-hero who believes he's protecting mutantkind. Collectors value this release for its comic-accurate design and representation of Marvel's most iconic mutant villain turned occasional ally.",
    description_de: "Diese Magneto-Minifigur von 2012 zeigt den Meister des Magnetismus in seinem klassischen roten Outfit mit Stoffumhang und repräsentiert einen der mächtigsten Gegner der X-Men. Die Figur zeigt Magnetos ikonischen Helm, der vor Telepathie schützt, und sein markantes Kostüm aus den Comics. Als Mutant, der Magnetfelder kontrolliert und für Mutanten-Vormacht kämpft, verkörpert diese Minifigur den komplexen Anti-Helden, der glaubt, die Mutanten zu schützen. Sammler schätzen diese Veröffentlichung für ihr comic-genaues Design und Darstellung von Marvels ikonischstem Mutanten-Schurken, der zum gelegentlichen Verbündeten wurde.",
    description_fr: "Cette minifigurine Magneto de 2012 présente le Maître du Magnétisme dans sa tenue rouge classique avec cape en tissu, représentant l'un des adversaires les plus puissants des X-Men. La figurine présente le casque emblématique de Magneto qui protège contre la télépathie et son costume distinctif des bandes dessinées. En tant que mutant qui contrôle les champs magnétiques et se bat pour la suprématie mutante, cette minifigurine incarne l'anti-héros complexe qui croit protéger les mutants. Les collectionneurs apprécient cette sortie pour sa conception fidèle aux bandes dessinées et sa représentation du méchant mutant le plus emblématique de Marvel devenu allié occasionnel.",
    description_es: "Esta minifigura de Magneto de 2012 presenta al Maestro del Magnetismo en su atuendo rojo clásico con capa de tela, representando uno de los adversarios más poderosos de los X-Men. La figura muestra el icónico casco de Magneto que protege contra la telepatía y su distintivo traje de los cómics. Como el mutante que controla campos magnéticos y lucha por la supremacía mutante, esta minifigura encarna al complejo antihéroe que cree que está protegiendo a los mutantes. Los coleccionistas valoran este lanzamiento por su diseño fiel al cómic y representación del villano mutante más icónico de Marvel convertido en aliado ocasional."
  },
  {
    minifigure_no: 'sh0032',
    description_en: "This Deadpool minifigure from 2012 brings the Merc with a Mouth to LEGO form with his iconic red and black costume. The figure features Deadpool's signature mask, dual katanas, and mercenary outfit, capturing the anti-hero known for breaking the fourth wall. As Marvel's most irreverent character who combines comedy with deadly combat skills, this minifigure represents Wade Wilson's unique place in the X-Men universe. Collectors highly value this early Deadpool release for the character's massive popularity and limited LEGO appearances in the Super Heroes theme.",
    description_de: "Diese Deadpool-Minifigur von 2012 bringt den Söldner mit dem großen Mund in LEGO-Form mit seinem ikonischen rot-schwarzen Kostüm. Die Figur zeigt Deadpools charakteristische Maske, doppelte Katanas und Söldner-Outfit und fängt den Anti-Helden ein, der dafür bekannt ist, die vierte Wand zu durchbrechen. Als Marvels respektlosester Charakter, der Komödie mit tödlichen Kampffähigkeiten kombiniert, repräsentiert diese Minifigur Wade Wilsons einzigartigen Platz im X-Men-Universum. Sammler schätzen diese frühe Deadpool-Veröffentlichung sehr hoch für die massive Popularität des Charakters und begrenzte LEGO-Auftritte im Super Heroes Thema.",
    description_fr: "Cette minifigurine Deadpool de 2012 apporte le Mercenaire à la Grande Bouche sous forme LEGO avec son costume rouge et noir emblématique. La figurine présente le masque signature de Deadpool, les doubles katanas et la tenue de mercenaire, capturant l'anti-héros connu pour briser le quatrième mur. En tant que personnage le plus irrévérencieux de Marvel qui combine comédie et compétences de combat mortelles, cette minifigurine représente la place unique de Wade Wilson dans l'univers X-Men. Les collectionneurs apprécient hautement cette sortie précoce de Deadpool pour la popularité massive du personnage et les apparitions LEGO limitées dans le thème Super Heroes.",
    description_es: "Esta minifigura de Deadpool de 2012 trae al Mercenario Bocazas a forma LEGO con su icónico traje rojo y negro. La figura presenta la máscara característica de Deadpool, katanas duales y atuendo de mercenario, capturando al antihéroe conocido por romper la cuarta pared. Como el personaje más irreverente de Marvel que combina comedia con habilidades de combate mortales, esta minifigura representa el lugar único de Wade Wilson en el universo X-Men. Los coleccionistas valoran altamente este lanzamiento temprano de Deadpool por la popularidad masiva del personaje y apariciones limitadas de LEGO en el tema Super Heroes."
  },
  {
    minifigure_no: 'sh0033',
    description_en: "This Loki minifigure from 2012 features Thor's adopted brother and trickster god with his 4.0cm height starched fabric cape from The Avengers. The figure showcases Loki's horned helmet, golden armor details, and scepter with Mind Stone, capturing the God of Mischief's role as the film's main antagonist. As the Asgardian prince who brings the Chitauri invasion to Earth, this minifigure represents one of the MCU's most compelling villains. Collectors value this release for its movie-accurate design and Loki's status as a fan-favorite Marvel character.",
    description_de: "Diese Loki-Minifigur von 2012 zeigt Thors Adoptivbruder und Trickster-Gott mit seinem 4,0 cm hohen gestärkten Stoffumhang aus The Avengers. Die Figur zeigt Lokis gehörnten Helm, goldene Rüstungsdetails und Zepter mit Gedankenstein und fängt die Rolle des Gottes des Schabernacks als Hauptantagonist des Films ein. Als Asgardischer Prinz, der die Chitauri-Invasion zur Erde bringt, repräsentiert diese Minifigur einen von MCUs fesselndsten Schurken. Sammler schätzen diese Veröffentlichung für ihr filmgenaues Design und Lokis Status als Fan-Liebling Marvel-Charakter.",
    description_fr: "Cette minifigurine Loki de 2012 présente le frère adoptif de Thor et dieu farceur avec sa cape en tissu amidonné de 4,0 cm de hauteur de The Avengers. La figurine présente le casque cornu de Loki, les détails d'armure dorée et le sceptre avec Pierre d'Esprit, capturant le rôle du Dieu de la Malice en tant qu'antagoniste principal du film. En tant que prince Asgardien qui amène l'invasion Chitauri sur Terre, cette minifigurine représente l'un des méchants les plus convaincants du MCU. Les collectionneurs apprécient cette sortie pour sa conception fidèle au film et le statut de Loki en tant que personnage Marvel favori des fans.",
    description_es: "Esta minifigura de Loki de 2012 presenta al hermano adoptivo de Thor y dios embaucador con su capa de tela almidonada de 4.0cm de altura de The Avengers. La figura muestra el casco con cuernos de Loki, detalles de armadura dorada y cetro con Gema Mental, capturando el papel del Dios del Engaño como antagonista principal de la película. Como príncipe Asgardiano que trae la invasión Chitauri a la Tierra, esta minifigura representa uno de los villanos más convincentes del MCU. Los coleccionistas valoran este lanzamiento por su diseño fiel a la película y el estatus de Loki como personaje favorito de los fans de Marvel."
  }
];

async function main() {
  console.log('🦸 Starting Super Heroes batch sh0021-sh0050...\n');

  for (const desc of descriptions) {
    await prisma.minifigCatalog.update({
      where: { minifigure_no: desc.minifigure_no },
      data: {
        description_en: desc.description_en,
        description_de: desc.description_de,
        description_fr: desc.description_fr,
        description_es: desc.description_es,
        description_generated_at: new Date(),
        description_status: 'completed'
      }
    });
    console.log(`✓ Saved ${desc.minifigure_no}`);
  }

  console.log(`\n✅ Batch sh0021-sh0023 complete! 23 total done.\n`);
  await prisma.$disconnect();
}

main();
