import { PrismaClient as PrismaClientHostinger } from '@prisma/client-hostinger';

const prisma = new PrismaClientHostinger({
  datasources: {
    db: {
      url: "mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker"
    }
  }
});

const descriptions = [
  {
    minifigure_no: 'sh0676',
    description_en: "Red Guardian stands as Russia's answer to Captain America, representing Alexei Shostakov's patriotic super-soldier legacy. This Soviet hero's red and blue costume with star emblem mirrors American iconography while establishing Russian national pride. As Natasha's surrogate father figure, Red Guardian adds family depth to Black Widow's origin story. Essential for Black Widow movie displays and international superhero collections.",
    description_de: "Red Guardian steht als Russlands Antwort auf Captain America und repräsentiert Alexei Shostakovs patriotisches Super-Soldaten-Erbe. Das rot-blaue Kostüm dieses sowjetischen Helden mit Stern-Emblem spiegelt amerikanische Ikonographie wider, während es russischen Nationalstolz etabliert. Als Natashas Ersatzvater-Figur fügt Red Guardian familiäre Tiefe zu Black Widows Ursprungsgeschichte hinzu. Unverzichtbar für Black Widow-Film-Displays und internationale Superhelden-Sammlungen.",
    description_fr: "Red Guardian se tient comme la réponse de la Russie à Captain America, représentant l'héritage de super-soldat patriotique d'Alexei Shostakov. Le costume rouge et bleu de ce héros soviétique avec emblème d'étoile reflète l'iconographie américaine tout en établissant la fierté nationale russe. En tant que figure de père de substitution de Natasha, Red Guardian ajoute une profondeur familiale à l'histoire d'origine de Black Widow. Essentiel pour les présentations de film Black Widow et les collections de super-héros internationaux.",
    description_es: "Red Guardian se erige como la respuesta de Rusia al Capitán América, representando el legado de supersoldado patriótico de Alexei Shostakov. El traje rojo y azul de este héroe soviético con emblema de estrella refleja la iconografía americana mientras establece el orgullo nacional ruso. Como figura paterna sustituta de Natasha, Red Guardian agrega profundidad familiar a la historia de origen de Black Widow. Esencial para exhibiciones de la película Black Widow y colecciones de superhéroes internacionales."
  },
  {
    minifigure_no: 'sh0677',
    description_en: "Etta Candy appears as Wonder Woman's loyal friend and comic relief companion who brings humor and humanity to Diana's adventures. This brave civilian character proves that heroism doesn't require superpowers through her courage and unwavering support. Her cheerful presence balances the epic stakes of Wonder Woman's battles. Important supporting character for Wonder Woman displays and civilian ally collections.",
    description_de: "Etta Candy erscheint als Wonder Womans treue Freundin und komische Begleiterin, die Humor und Menschlichkeit zu Dianas Abenteuern bringt. Diese mutige zivile Figur beweist, dass Heldentum keine Superkräfte durch ihren Mut und unerschütterliche Unterstützung erfordert. Ihre fröhliche Präsenz balanciert die epischen Einsätze von Wonder Womans Kämpfen. Wichtige Nebenfigur für Wonder Woman-Displays und zivile Verbündeten-Sammlungen.",
    description_fr: "Etta Candy apparaît comme l'amie fidèle et compagne de soulagement comique de Wonder Woman qui apporte humour et humanité aux aventures de Diana. Ce personnage civil courageux prouve que l'héroïsme ne nécessite pas de super-pouvoirs grâce à son courage et son soutien indéfectible. Sa présence joyeuse équilibre les enjeux épiques des batailles de Wonder Woman. Personnage de soutien important pour les présentations Wonder Woman et les collections d'alliés civils.",
    description_es: "Etta Candy aparece como la leal amiga y compañera de alivio cómico de Wonder Woman que trae humor y humanidad a las aventuras de Diana. Este valiente personaje civil prueba que el heroísmo no requiere superpoderes a través de su coraje y apoyo inquebrantable. Su presencia alegre equilibra las apuestas épicas de las batallas de Wonder Woman. Personaje de apoyo importante para exhibiciones de Wonder Woman y colecciones de aliados civiles."
  },
  {
    minifigure_no: 'sh0678',
    description_en: "Ghost Rider roars as Roberto Robbie Reyes with his distinctive flat silver head representing the spirit of vengeance's flaming skull. This modern incarnation of Ghost Rider brings street racing culture to the supernatural hero legacy. The metallic skull design captures the otherworldly nature of the character's demonic transformation. Essential for Ghost Rider collections and supernatural Marvel hero displays.",
    description_de: "Ghost Rider brüllt als Roberto Robbie Reyes mit seinem charakteristischen flachen silbernen Kopf, der den flammenden Schädel des Geistes der Rache repräsentiert. Diese moderne Inkarnation von Ghost Rider bringt Straßenrennkultur zum übernatürlichen Helden-Erbe. Das metallische Schädel-Design fängt die jenseitige Natur der dämonischen Transformation der Figur ein. Unverzichtbar für Ghost Rider-Sammlungen und übernatürliche Marvel-Helden-Displays.",
    description_fr: "Ghost Rider rugit en tant que Roberto Robbie Reyes avec sa tête argentée plate distinctive représentant le crâne enflammé de l'esprit de vengeance. Cette incarnation moderne de Ghost Rider apporte la culture des courses de rue à l'héritage de héros surnaturel. Le design de crâne métallique capture la nature surnaturelle de la transformation démoniaque du personnage. Essentiel pour les collections Ghost Rider et les présentations de héros Marvel surnaturels.",
    description_es: "Ghost Rider ruge como Roberto Robbie Reyes con su distintiva cabeza plateada plana que representa el cráneo en llamas del espíritu de venganza. Esta encarnación moderna de Ghost Rider trae cultura de carreras callejeras al legado de héroe sobrenatural. El diseño de cráneo metálico captura la naturaleza sobrenatural de la transformación demoníaca del personaje. Esencial para colecciones de Ghost Rider y exhibiciones de héroes sobrenaturales de Marvel."
  },
  {
    minifigure_no: 'sh0679',
    description_en: "Spider-Man swings as Miles Morales in his distinctive costume with dark red hood and black lower legs. This Brooklyn teenager brings fresh energy to the Spider-Man legacy with unique bio-electric venom blast powers. The distinctive color scheme and design separate Miles from Peter Parker while honoring the spider-hero tradition. Essential figure for Spider-Verse collections and Miles Morales character displays.",
    description_de: "Spider-Man schwingt sich als Miles Morales in seinem charakteristischen Kostüm mit dunkelroter Kapuze und schwarzen unteren Beinen. Dieser Teenager aus Brooklyn bringt frische Energie zum Spider-Man-Erbe mit einzigartigen bio-elektrischen Venom-Blast-Kräften. Das charakteristische Farbschema und Design trennen Miles von Peter Parker, während die Spider-Hero-Tradition geehrt wird. Unverzichtbare Figur für Spider-Verse-Sammlungen und Miles Morales-Charakter-Displays.",
    description_fr: "Spider-Man se balance en tant que Miles Morales dans son costume distinctif avec capuche rouge foncé et jambes inférieures noires. Cet adolescent de Brooklyn apporte une énergie fraîche à l'héritage de Spider-Man avec des pouvoirs de décharge de venin bio-électrique uniques. Le schéma de couleurs et le design distinctifs séparent Miles de Peter Parker tout en honorant la tradition du héros araignée. Figurine essentielle pour les collections Spider-Verse et les présentations de personnage Miles Morales.",
    description_es: "Spider-Man se balancea como Miles Morales con su distintivo traje con capucha rojo oscuro y piernas inferiores negras. Este adolescente de Brooklyn trae energía fresca al legado de Spider-Man con poderes únicos de explosión de veneno bio-eléctrico. El distintivo esquema de colores y diseño separan a Miles de Peter Parker mientras honran la tradición del héroe araña. Figura esencial para colecciones de Spider-Verse y exhibiciones del personaje Miles Morales."
  },
  {
    minifigure_no: 'sh0680',
    description_en: "Thor stands ready in his distinctive helmet without cape, representing the God of Thunder in ceremonial or pre-battle preparation. This variant showcases Thor's iconic winged helmet while offering different display options from caped versions. The helmet-focused appearance emphasizes his Asgardian royal heritage and warrior status. Important variant for comprehensive Thor collections and alternate display configurations.",
    description_de: "Thor steht bereit in seinem charakteristischen Helm ohne Cape und repräsentiert den Donnergott in zeremonieller oder Vor-Schlacht-Vorbereitung. Diese Variante zeigt Thors ikonischen geflügelten Helm, während verschiedene Display-Optionen von Cape-Versionen geboten werden. Das helm-fokussierte Erscheinungsbild betont sein asgardisches königliches Erbe und Krieger-Status. Wichtige Variante für umfassende Thor-Sammlungen und alternative Display-Konfigurationen.",
    description_fr: "Thor se tient prêt dans son casque distinctif sans cape, représentant le Dieu du Tonnerre en préparation cérémonielle ou pré-bataille. Cette variante présente le casque ailé iconique de Thor tout en offrant différentes options d'affichage par rapport aux versions avec cape. L'apparence axée sur le casque souligne son héritage royal asgardien et son statut de guerrier. Variante importante pour les collections complètes de Thor et les configurations d'affichage alternatives.",
    description_es: "Thor está listo con su distintivo casco sin capa, representando al Dios del Trueno en preparación ceremonial o prebatalla. Esta variante muestra el icónico casco alado de Thor mientras ofrece diferentes opciones de exhibición de versiones con capa. La apariencia enfocada en el casco enfatiza su herencia real asgardiana y estatus de guerrero. Variante importante para colecciones completas de Thor y configuraciones de exhibición alternativas."
  },
  {
    minifigure_no: 'sh0681',
    description_en: "Mysterio materializes with light bluish gray head visible through his satin transparent light blue fishbowl helmet and flowing cape. Quentin Beck's master illusionist persona combines theatrical showmanship with dangerous deception. The distinctive dome helmet and cape create one of Spider-Man's most visually unique villains. Essential for Spider-Man: Far From Home displays and spectacular villain collections.",
    description_de: "Mysterio materialisiert sich mit hellblaugrauem Kopf sichtbar durch seinen satinierten transparenten hellblauen Fischglas-Helm und fließenden Cape. Quentin Becks Meister-Illusionist-Persona kombiniert theatralisches Showmanship mit gefährlicher Täuschung. Der charakteristische Kuppelhelm und Cape schaffen einen der visuell einzigartigsten Schurken von Spider-Man. Unverzichtbar für Spider-Man: Far From Home-Displays und spektakuläre Schurken-Sammlungen.",
    description_fr: "Mysterio se matérialise avec tête gris bleuté clair visible à travers son casque bocal à poissons bleu clair transparent satiné et sa cape flottante. Le personnage de maître illusionniste de Quentin Beck combine le sens du spectacle théâtral avec une tromperie dangereuse. Le casque dôme distinctif et la cape créent l'un des méchants les plus visuellement uniques de Spider-Man. Essentiel pour les présentations Spider-Man: Far From Home et les collections de méchants spectaculaires.",
    description_es: "Mysterio se materializa con cabeza gris azulado claro visible a través de su casco de pecera azul claro transparente satinado y capa flotante. La persona de maestro ilusionista de Quentin Beck combina espectáculo teatral con engaño peligroso. El distintivo casco de cúpula y capa crean uno de los villanos más visualmente únicos de Spider-Man. Esencial para exhibiciones de Spider-Man: Far From Home y colecciones de villanos espectaculares."
  },
  {
    minifigure_no: 'sh0682',
    description_en: "Ghost-Spider leaps into action as Gwen Stacy with her iconic white hood and black legs creating the beloved Spider-Gwen look. This alternate universe hero brings punk rock attitude and spider-powers together in one of the Spider-Verse's most popular characters. The striking white and black design makes Ghost-Spider instantly recognizable. Highly sought after for Spider-Verse collections and alternate spider-hero displays.",
    description_de: "Ghost-Spider springt in Action als Gwen Stacy mit ihrer ikonischen weißen Kapuze und schwarzen Beinen, die den beliebten Spider-Gwen-Look schaffen. Diese alternative Universum-Heldin bringt Punk-Rock-Attitüde und Spinnenkräfte in einer der beliebtesten Figuren des Spider-Verse zusammen. Das auffällige weiß-schwarze Design macht Ghost-Spider sofort erkennbar. Sehr begehrt für Spider-Verse-Sammlungen und alternative Spider-Hero-Displays.",
    description_fr: "Ghost-Spider bondit dans l'action en tant que Gwen Stacy avec sa capuche blanche iconique et ses jambes noires créant le look Spider-Gwen bien-aimé. Ce héros d'univers alternatif rassemble attitude punk rock et pouvoirs d'araignée dans l'un des personnages les plus populaires du Spider-Verse. Le design blanc et noir saisissant rend Ghost-Spider instantanément reconnaissable. Très recherché pour les collections Spider-Verse et les présentations de héros araignées alternatifs.",
    description_es: "Ghost-Spider salta a la acción como Gwen Stacy con su icónica capucha blanca y piernas negras creando el querido aspecto de Spider-Gwen. Esta heroína de universo alternativo reúne actitud punk rock y poderes de araña en uno de los personajes más populares del Spider-Verse. El llamativo diseño blanco y negro hace a Ghost-Spider instantáneamente reconocible. Muy buscado para colecciones de Spider-Verse y exhibiciones de héroes araña alternativos."
  },
  {
    minifigure_no: 'sh0683',
    description_en: "Carnage rampages with medium-sized appendages extending from the red symbiote's deadly form. This version of Cletus Kasady's monstrous alter ego showcases moderate tentacle length for dynamic posing options. The red and black alien design captures Carnage's violent nature and chaotic energy. Important variant for Spider-Man villain displays and symbiote character collections.",
    description_de: "Carnage tobt mit mittelgroßen Anhängen, die sich von der tödlichen Form des roten Symbionts erstrecken. Diese Version von Cletus Kasadys monströsem Alter Ego zeigt moderate Tentakellänge für dynamische Posing-Optionen. Das rot-schwarze Alien-Design fängt Carnages gewalttätige Natur und chaotische Energie ein. Wichtige Variante für Spider-Man-Schurken-Displays und Symbiont-Charakter-Sammlungen.",
    description_fr: "Carnage fait rage avec des appendices de taille moyenne s'étendant de la forme mortelle du symbiote rouge. Cette version de l'alter ego monstrueux de Cletus Kasady présente une longueur de tentacule modérée pour des options de pose dynamiques. Le design extraterrestre rouge et noir capture la nature violente et l'énergie chaotique de Carnage. Variante importante pour les présentations de méchants Spider-Man et les collections de personnages symbiotes.",
    description_es: "Carnage arrasa con apéndices de tamaño mediano que se extienden desde la forma mortal del simbionte rojo. Esta versión del alter ego monstruoso de Cletus Kasady muestra longitud moderada de tentáculos para opciones de poses dinámicas. El diseño alienígena rojo y negro captura la naturaleza violenta y energía caótica de Carnage. Variante importante para exhibiciones de villanos de Spider-Man y colecciones de personajes simbiontes."
  },
  {
    minifigure_no: 'sh0684',
    description_en: "Spider-Man swings in classic form with detailed printed blue arms and plain legs representing an early or simplified costume version. This streamlined appearance focuses on the iconic red and blue color scheme with enhanced arm printing. The cleaner leg design offers collectors a different aesthetic from heavily detailed variants. Perfect for displays emphasizing classic Spider-Man design elements.",
    description_de: "Spider-Man schwingt sich in klassischer Form mit detailliert bedruckten blauen Armen und einfachen Beinen, die eine frühe oder vereinfachte Kostümversion repräsentieren. Dieses stromlinienförmige Erscheinungsbild konzentriert sich auf das ikonische rot-blaue Farbschema mit verbessertem Arm-Druck. Das sauberere Bein-Design bietet Sammlern eine andere Ästhetik als stark detaillierte Varianten. Perfekt für Displays, die klassische Spider-Man-Designelemente betonen.",
    description_fr: "Spider-Man se balance sous forme classique avec bras bleus imprimés détaillés et jambes unies représentant une version de costume précoce ou simplifiée. Cette apparence rationalisée se concentre sur le schéma de couleurs rouge et bleu iconique avec impression de bras améliorée. Le design de jambes plus propre offre aux collectionneurs une esthétique différente des variantes fortement détaillées. Parfait pour les présentations mettant l'accent sur les éléments de design classiques de Spider-Man.",
    description_es: "Spider-Man se balancea en forma clásica con brazos azules impresos detallados y piernas lisas que representan una versión de traje temprana o simplificada. Esta apariencia simplificada se enfoca en el icónico esquema de colores rojo y azul con impresión de brazos mejorada. El diseño de piernas más limpio ofrece a los coleccionistas una estética diferente de variantes muy detalladas. Perfecto para exhibiciones que enfatizan elementos de diseño clásicos de Spider-Man."
  },
  {
    minifigure_no: 'sh0685',
    description_en: "Sandman rises on his swirling base in green outfit, representing Flint Marko's ability to transform into and control sand. This classic Spider-Man villain gained incredible shapeshifting powers after a freak accident merged him with radioactive sand. The swirling base captures his constant transformation between solid and granular forms. Essential villain for Spider-Man rogues gallery and elemental-powered character displays.",
    description_de: "Sandman erhebt sich auf seiner wirbelnden Basis in grünem Outfit und repräsentiert Flint Markos Fähigkeit, sich in Sand zu verwandeln und ihn zu kontrollieren. Dieser klassische Spider-Man-Schurke erhielt unglaubliche Gestaltwandlungs-Kräfte, nachdem ein bizarrer Unfall ihn mit radioaktivem Sand verschmolz. Die wirbelnde Basis fängt seine ständige Transformation zwischen festen und körnigen Formen ein. Unverzichtbarer Schurke für Spider-Mans Schurkengalerie und elementar-betriebene Charakter-Displays.",
    description_fr: "Sandman s'élève sur sa base tourbillonnante en tenue verte, représentant la capacité de Flint Marko à se transformer en sable et à le contrôler. Ce méchant classique de Spider-Man a acquis des pouvoirs de métamorphose incroyables après qu'un accident bizarre l'ait fusionné avec du sable radioactif. La base tourbillonnante capture sa transformation constante entre formes solides et granulaires. Méchant essentiel pour la galerie de méchants de Spider-Man et les présentations de personnages dotés de pouvoirs élémentaires.",
    description_es: "Sandman se eleva sobre su base giratoria con atuendo verde, representando la habilidad de Flint Marko de transformarse en arena y controlarla. Este villano clásico de Spider-Man obtuvo increíbles poderes de cambio de forma después de que un extraño accidente lo fusionara con arena radiactiva. La base giratoria captura su constante transformación entre formas sólidas y granulares. Villano esencial para la galería de villanos de Spider-Man y exhibiciones de personajes con poderes elementales."
  },
  {
    minifigure_no: 'sh0686',
    description_en: "Captain America charges into battle wearing his dark blue suit with reddish brown belt, red hands, and iconic helmet. Steve Rogers' leadership and unwavering moral compass make him the heart of the Avengers. This costume variant showcases different color combinations while maintaining the star-spangled hero's essential design. Essential for Avengers team displays and Captain America costume evolution collections.",
    description_de: "Captain America stürmt in die Schlacht in seinem dunkelblauen Anzug mit rotbraunem Gürtel, roten Händen und ikonischem Helm. Steve Rogers' Führung und unerschütterlicher moralischer Kompass machen ihn zum Herzen der Avengers. Diese Kostümvariante zeigt verschiedene Farbkombinationen, während das wesentliche Design des sternengeschmückten Helden beibehalten wird. Unverzichtbar für Avengers-Team-Displays und Captain America-Kostüm-Evolutions-Sammlungen.",
    description_fr: "Captain America charge au combat portant sa combinaison bleu foncé avec ceinture brun rougeâtre, mains rouges et casque iconique. Le leadership de Steve Rogers et sa boussole morale inébranlable font de lui le cœur des Avengers. Cette variante de costume présente différentes combinaisons de couleurs tout en conservant le design essentiel du héros étoilé. Essentiel pour les présentations d'équipe Avengers et les collections d'évolution de costume de Captain America.",
    description_es: "Captain America carga a la batalla vistiendo su traje azul oscuro con cinturón marrón rojizo, manos rojas y casco icónico. El liderazgo de Steve Rogers y su brújula moral inquebrantable lo convierten en el corazón de los Avengers. Esta variante de traje muestra diferentes combinaciones de colores mientras mantiene el diseño esencial del héroe adornado con estrellas. Esencial para exhibiciones del equipo Avengers y colecciones de evolución de traje del Capitán América."
  },
  {
    minifigure_no: 'sh0687',
    description_en: "Doctor Octopus menaces in his dark green suit with neck bracket attachment for mounting his infamous mechanical arms. Otto Octavius remains one of Spider-Man's most dangerous foes with genius-level intellect and four powerful tentacles. The neck bracket design allows for versatile arm configurations and dynamic posing. Essential villain for Spider-Man collections and mad scientist character displays.",
    description_de: "Doctor Octopus bedroht in seinem dunkelgrünen Anzug mit Halsstück-Befestigung zum Montieren seiner berüchtigten mechanischen Arme. Otto Octavius bleibt einer der gefährlichsten Feinde von Spider-Man mit Intelligenz auf Genie-Niveau und vier mächtigen Tentakeln. Das Halsstück-Design ermöglicht vielseitige Arm-Konfigurationen und dynamisches Posing. Unverzichtbarer Schurke für Spider-Man-Sammlungen und verrückter Wissenschaftler-Charakter-Displays.",
    description_fr: "Doctor Octopus menace dans son costume vert foncé avec support de cou pour monter ses bras mécaniques infâmes. Otto Octavius reste l'un des ennemis les plus dangereux de Spider-Man avec un intellect de niveau génie et quatre tentacules puissants. Le design du support de cou permet des configurations de bras polyvalentes et des poses dynamiques. Méchant essentiel pour les collections Spider-Man et les présentations de personnages de scientifiques fous.",
    description_es: "Doctor Octopus amenaza con su traje verde oscuro con soporte de cuello para montar sus infames brazos mecánicos. Otto Octavius sigue siendo uno de los enemigos más peligrosos de Spider-Man con intelecto de nivel genio y cuatro tentáculos poderosos. El diseño del soporte de cuello permite configuraciones versátiles de brazos y poses dinámicas. Villano esencial para colecciones de Spider-Man y exhibiciones de personajes de científicos locos."
  },
  {
    minifigure_no: 'sh0688',
    description_en: "Batman soars with specialized rocket pack adding jet-powered flight to the Dark Knight's arsenal. This enhanced mobility allows Batman to engage aerial threats and reach rooftop vantage points instantly. The rocket pack represents Wayne Tech innovation applied to crime-fighting equipment. Perfect for aerial combat scenarios and showcasing Batman's technological versatility.",
    description_de: "Batman schwebt mit spezialisiertem Raketenpack, der strahlgetriebenen Flug zum Arsenal des Dunklen Ritters hinzufügt. Diese verbesserte Mobilität ermöglicht es Batman, Luftbedrohungen anzugreifen und sofort Dach-Aussichtspunkte zu erreichen. Das Raketenpack repräsentiert Wayne Tech-Innovation angewendet auf Verbrechensbekämpfungs-Ausrüstung. Perfekt für Luftkampf-Szenarien und zur Präsentation von Batmans technologischer Vielseitigkeit.",
    description_fr: "Batman plane avec un pack de fusée spécialisé ajoutant un vol à réaction à l'arsenal du Chevalier Noir. Cette mobilité améliorée permet à Batman d'engager des menaces aériennes et d'atteindre instantanément des points de vue sur les toits. Le pack de fusée représente l'innovation Wayne Tech appliquée à l'équipement de lutte contre le crime. Parfait pour les scénarios de combat aérien et pour mettre en valeur la polyvalence technologique de Batman.",
    description_es: "Batman vuela con paquete de cohetes especializado que agrega vuelo impulsado por chorro al arsenal del Caballero Oscuro. Esta movilidad mejorada permite a Batman enfrentar amenazas aéreas y alcanzar puntos de observación en azoteas instantáneamente. El paquete de cohetes representa innovación de Wayne Tech aplicada a equipo de lucha contra el crimen. Perfecto para escenarios de combate aéreo y mostrar la versatilidad tecnológica de Batman."
  },
  {
    minifigure_no: 'sh0689',
    description_en: "Batman prowls in light bluish gray suit with yellow belt and black crest, featuring the Type 3 cowl design and flowing cape. This color variant offers unique display options while maintaining Batman's iconic silhouette. The lighter suit color creates striking visual contrast perfect for specific storyline representations. Important variant for collectors seeking comprehensive Batman costume variations.",
    description_de: "Batman schleicht in hellblaugrauem Anzug mit gelbem Gürtel und schwarzem Wappen, mit Type 3-Kapuzen-Design und fließendem Cape. Diese Farbvariante bietet einzigartige Display-Optionen, während Batmans ikonische Silhouette beibehalten wird. Die hellere Anzugfarbe schafft auffälligen visuellen Kontrast perfekt für spezifische Storyline-Darstellungen. Wichtige Variante für Sammler, die umfassende Batman-Kostüm-Variationen suchen.",
    description_fr: "Batman rôde dans une combinaison gris bleuté clair avec ceinture jaune et écusson noir, présentant le design de cagoule Type 3 et une cape flottante. Cette variante de couleur offre des options d'affichage uniques tout en conservant la silhouette iconique de Batman. La couleur de combinaison plus claire crée un contraste visuel saisissant parfait pour des représentations de scénarios spécifiques. Variante importante pour les collectionneurs recherchant des variations complètes de costume Batman.",
    description_es: "Batman merodea con traje gris azulado claro con cinturón amarillo y emblema negro, con diseño de capucha Tipo 3 y capa flotante. Esta variante de color ofrece opciones de exhibición únicas mientras mantiene la silueta icónica de Batman. El color más claro del traje crea contraste visual llamativo perfecto para representaciones específicas de historias. Variante importante para coleccionistas que buscan variaciones completas de trajes de Batman."
  },
  {
    minifigure_no: 'sh0690',
    description_en: "Venom towers menacingly with distinctive white parted teeth and two asymmetrical back appendages creating a unique symbiote appearance. This variant showcases Eddie Brock's alien costume with moderate tentacle configuration. The asymmetrical design adds organic unpredictability to Venom's threatening form. Important for Spider-Man villain displays and symbiote variant collections.",
    description_de: "Venom ragt bedrohlich auf mit charakteristischen weißen getrennten Zähnen und zwei asymmetrischen Rückenanhängen, die ein einzigartiges Symbiont-Erscheinungsbild schaffen. Diese Variante zeigt Eddie Brocks Alien-Kostüm mit moderater Tentakel-Konfiguration. Das asymmetrische Design fügt organische Unberechenbarkeit zu Venoms bedrohlicher Form hinzu. Wichtig für Spider-Man-Schurken-Displays und Symbiont-Varianten-Sammlungen.",
    description_fr: "Venom se dresse de manière menaçante avec des dents blanches séparées distinctives et deux appendices arrière asymétriques créant une apparence de symbiote unique. Cette variante présente le costume extraterrestre d'Eddie Brock avec une configuration de tentacules modérée. Le design asymétrique ajoute une imprévisibilité organique à la forme menaçante de Venom. Important pour les présentations de méchants Spider-Man et les collections de variantes de symbiotes.",
    description_es: "Venom se eleva amenazadoramente con distintivos dientes blancos separados y dos apéndices traseros asimétricos creando una apariencia única de simbionte. Esta variante muestra el traje alienígena de Eddie Brock con configuración moderada de tentáculos. El diseño asimétrico agrega imprevisibilidad orgánica a la forma amenazante de Venom. Importante para exhibiciones de villanos de Spider-Man y colecciones de variantes de simbiontes."
  },
  {
    minifigure_no: 'sh0691',
    description_en: "Spider-Man infiltrates in his Stealth Big Time Suit featuring sleek black design optimized for covert operations. This tactical costume represents Peter Parker's espionage-focused suit designed for stealth missions requiring invisibility and silence. The all-black aesthetic creates striking contrast to classic red and blue Spider-Man designs. Highly collectible variant showcasing Spider-Man's tactical versatility.",
    description_de: "Spider-Man infiltriert in seinem Stealth Big Time Suit mit schlankem schwarzem Design optimiert für verdeckte Operationen. Dieses taktische Kostüm repräsentiert Peter Parkers spionagefokussierten Anzug, der für Stealth-Missionen entwickelt wurde, die Unsichtbarkeit und Stille erfordern. Die ganz schwarze Ästhetik schafft auffälligen Kontrast zu klassischen rot-blauen Spider-Man-Designs. Sehr begehrte Variante, die Spider-Mans taktische Vielseitigkeit zeigt.",
    description_fr: "Spider-Man s'infiltre dans sa combinaison Stealth Big Time présentant un design noir élégant optimisé pour les opérations secrètes. Ce costume tactique représente la combinaison axée sur l'espionnage de Peter Parker conçue pour les missions furtives nécessitant invisibilité et silence. L'esthétique entièrement noire crée un contraste saisissant avec les designs classiques rouge et bleu de Spider-Man. Variante hautement collectionnable mettant en valeur la polyvalence tactique de Spider-Man.",
    description_es: "Spider-Man se infiltra con su traje Stealth Big Time que presenta diseño negro elegante optimizado para operaciones encubiertas. Este traje táctico representa el traje enfocado en espionaje de Peter Parker diseñado para misiones sigilosas que requieren invisibilidad y silencio. La estética completamente negra crea contraste llamativo con diseños clásicos rojo y azul de Spider-Man. Variante altamente coleccionable que muestra la versatilidad táctica de Spider-Man."
  },
  {
    minifigure_no: 'sh0692',
    description_en: "Iron Spider deploys advanced mechanical arms with barbed tips for enhanced combat and climbing capabilities. Tony Stark's upgraded spider-suit combines cutting-edge technology with Peter's natural abilities creating an incredibly versatile fighting platform. The barbed mechanical limbs add offensive capability beyond standard Iron Spider versions. Essential for Infinity War displays and advanced Spider-Man technology collections.",
    description_de: "Iron Spider setzt fortgeschrittene mechanische Arme mit Widerhaken-Spitzen für verbesserte Kampf- und Kletterfähigkeiten ein. Tony Starks aufgewerteter Spider-Anzug kombiniert modernste Technologie mit Peters natürlichen Fähigkeiten und schafft eine unglaublich vielseitige Kampfplattform. Die mechanischen Gliedmaßen mit Widerhaken fügen Angriffsfähigkeit jenseits standard Iron Spider-Versionen hinzu. Unverzichtbar für Infinity War-Displays und fortgeschrittene Spider-Man-Technologie-Sammlungen.",
    description_fr: "Iron Spider déploie des bras mécaniques avancés avec pointes barbelées pour des capacités de combat et d'escalade améliorées. La combinaison d'araignée améliorée de Tony Stark combine technologie de pointe avec les capacités naturelles de Peter créant une plateforme de combat incroyablement polyvalente. Les membres mécaniques barbelés ajoutent une capacité offensive au-delà des versions standard d'Iron Spider. Essentiel pour les présentations Infinity War et les collections de technologie avancée Spider-Man.",
    description_es: "Iron Spider despliega brazos mecánicos avanzados con puntas con púas para capacidades mejoradas de combate y escalada. El traje de araña mejorado de Tony Stark combina tecnología de vanguardia con las habilidades naturales de Peter creando una plataforma de lucha increíblemente versátil. Las extremidades mecánicas con púas agregan capacidad ofensiva más allá de versiones estándar de Iron Spider. Esencial para exhibiciones de Infinity War y colecciones de tecnología avanzada de Spider-Man."
  },
  {
    minifigure_no: 'sh0693',
    description_en: "Spider-Man appears as Peter Parker in civilian identity representing the brilliant but struggling teenager behind the mask. This unmasked version captures Peter during moments between superhero duties - attending school, working at the Daily Bugle, or spending time with friends. The civilian appearance reminds collectors that Peter's humanity drives his heroism. Essential for character-focused displays showing Spider-Man's dual life.",
    description_de: "Spider-Man erscheint als Peter Parker in ziviler Identität und repräsentiert den brillanten, aber kämpfenden Teenager hinter der Maske. Diese unmaskierte Version fängt Peter während Momenten zwischen Superhelden-Pflichten ein - Schulbesuch, Arbeit beim Daily Bugle oder Zeit mit Freunden verbringen. Das zivile Erscheinungsbild erinnert Sammler daran, dass Peters Menschlichkeit sein Heldentum antreibt. Unverzichtbar für charakterfokussierte Displays, die Spider-Mans Doppelleben zeigen.",
    description_fr: "Spider-Man apparaît en tant que Peter Parker dans son identité civile représentant l'adolescent brillant mais en difficulté derrière le masque. Cette version démasquée capture Peter lors de moments entre les devoirs de super-héros - fréquenter l'école, travailler au Daily Bugle ou passer du temps avec des amis. L'apparence civile rappelle aux collectionneurs que l'humanité de Peter anime son héroïsme. Essentiel pour les présentations axées sur les personnages montrant la double vie de Spider-Man.",
    description_es: "Spider-Man aparece como Peter Parker en identidad civil representando al adolescente brillante pero luchador detrás de la máscara. Esta versión desenmascarada captura a Peter durante momentos entre deberes de superhéroe - asistiendo a la escuela, trabajando en el Daily Bugle o pasando tiempo con amigos. La apariencia civil recuerda a los coleccionistas que la humanidad de Peter impulsa su heroísmo. Esencial para exhibiciones enfocadas en personajes que muestran la doble vida de Spider-Man."
  },
  {
    minifigure_no: 'sh0694',
    description_en: "Spider-Man swings as Miles Morales in his classic suit as the exclusive Sony PlayStation 2020 collectible. This special edition celebrates the acclaimed video game that introduced many fans to Miles' hero journey. The game-accurate appearance captures the beloved suit design from Marvel's Spider-Man: Miles Morales. Highly sought after limited edition essential for gaming collectors and Miles Morales fans.",
    description_de: "Spider-Man schwingt sich als Miles Morales in seinem klassischen Anzug als exklusives Sony PlayStation 2020-Sammlerstück. Diese Sonderedition feiert das gefeierte Videospiel, das vielen Fans Miles' Helden-Reise vorstellte. Das spielgenaue Erscheinungsbild fängt das beliebte Anzug-Design aus Marvels Spider-Man: Miles Morales ein. Sehr begehrte limitierte Edition unverzichtbar für Gaming-Sammler und Miles Morales-Fans.",
    description_fr: "Spider-Man se balance en tant que Miles Morales dans sa combinaison classique en tant qu'objet de collection exclusif Sony PlayStation 2020. Cette édition spéciale célèbre le jeu vidéo acclamé qui a présenté le parcours de héros de Miles à de nombreux fans. L'apparence fidèle au jeu capture le design de combinaison bien-aimé de Marvel's Spider-Man: Miles Morales. Édition limitée très recherchée essentielle pour les collectionneurs de jeux et les fans de Miles Morales.",
    description_es: "Spider-Man se balancea como Miles Morales con su traje clásico como el coleccionable exclusivo de Sony PlayStation 2020. Esta edición especial celebra el aclamado videojuego que presentó a muchos fanáticos el viaje heroico de Miles. La apariencia fiel al juego captura el querido diseño de traje de Marvel's Spider-Man: Miles Morales. Edición limitada muy buscada esencial para coleccionistas de videojuegos y fanáticos de Miles Morales."
  },
  {
    minifigure_no: 'sh0695',
    description_en: "Green Goblin cackles maniacally with bright green skin, dark purple outfit, small yellow eyes, and detailed printed legs. Norman Osborn's transformation into the Goblin created Spider-Man's most personal and dangerous enemy. The distinctive goblin features and purple costume make this villain instantly recognizable. Essential antagonist for Spider-Man collections representing the hero's greatest nemesis.",
    description_de: "Green Goblin kichert wahnsinnig mit hellgrüner Haut, dunkellila Outfit, kleinen gelben Augen und detailliert bedruckten Beinen. Norman Osborns Transformation in den Goblin schuf Spider-Mans persönlichsten und gefährlichsten Feind. Die charakteristischen Goblin-Merkmale und das lila Kostüm machen diesen Schurken sofort erkennbar. Unverzichtbarer Antagonist für Spider-Man-Sammlungen, der den größten Nemesis des Helden repräsentiert.",
    description_fr: "Green Goblin ricane de manière maniaque avec peau vert vif, tenue violet foncé, petits yeux jaunes et jambes imprimées détaillées. La transformation de Norman Osborn en Goblin a créé l'ennemi le plus personnel et dangereux de Spider-Man. Les caractéristiques distinctives de gobelin et le costume violet rendent ce méchant instantanément reconnaissable. Antagoniste essentiel pour les collections Spider-Man représentant le plus grand némésis du héros.",
    description_es: "Green Goblin se ríe maníacamente con piel verde brillante, atuendo púrpura oscuro, pequeños ojos amarillos y piernas impresas detalladas. La transformación de Norman Osborn en el Duende creó el enemigo más personal y peligroso de Spider-Man. Las distintivas características de duende y el traje púrpura hacen que este villano sea instantáneamente reconocible. Antagonista esencial para colecciones de Spider-Man que representa el mayor némesis del héroe."
  },
  {
    minifigure_no: 'sh0696',
    description_en: "Thanos schemes in standard minifigure scale wearing his dark blue and gold outfit with pearl gold hands, plain legs, and distinctive helmet. This more accessible scale Mad Titan allows for integration with regular LEGO displays while maintaining his threatening presence. The helmet adds regal authority to his already imposing appearance. Important variant for collectors preferring standard scale villain displays.",
    description_de: "Thanos intrigiert im Standard-Minifiguren-Maßstab mit seinem dunkelblauen und goldenen Outfit mit perlgoldenen Händen, einfachen Beinen und charakteristischem Helm. Dieser zugänglichere Maßstab Mad Titan ermöglicht Integration mit regulären LEGO-Displays, während seine bedrohliche Präsenz beibehalten wird. Der Helm fügt königliche Autorität zu seinem bereits imposanten Erscheinungsbild hinzu. Wichtige Variante für Sammler, die Standard-Maßstab-Schurken-Displays bevorzugen.",
    description_fr: "Thanos complote à l'échelle standard de minifigurine portant sa tenue bleu foncé et or avec mains or perlé, jambes unies et casque distinctif. Ce Mad Titan à échelle plus accessible permet l'intégration avec les présentations LEGO régulières tout en conservant sa présence menaçante. Le casque ajoute une autorité royale à son apparence déjà imposante. Variante importante pour les collectionneurs préférant les présentations de méchants à échelle standard.",
    description_es: "Thanos conspira en escala de minifigura estándar vistiendo su atuendo azul oscuro y dorado con manos doradas perladas, piernas lisas y casco distintivo. Este Titán Loco a escala más accesible permite integración con exhibiciones LEGO regulares mientras mantiene su presencia amenazante. El casco agrega autoridad real a su apariencia ya imponente. Variante importante para coleccionistas que prefieren exhibiciones de villanos a escala estándar."
  },
  {
    minifigure_no: 'sh0697',
    description_en: "Iron Venom displays the horrifying mid-transformation with headgear partially transformed between Iron Man armor and Venom symbiote. This unique variant captures the moment when technology and alien biology merge into something terrifying. The partial transformation showcases the struggle between machine and organism. Highly collectible variant exploring the dangerous combination of Stark tech and symbiote power.",
    description_de: "Iron Venom zeigt die schreckliche Zwischen-Transformation mit teilweise verwandeltem Kopfschmuck zwischen Iron Man-Rüstung und Venom-Symbiont. Diese einzigartige Variante fängt den Moment ein, in dem Technologie und außerirdische Biologie zu etwas Erschreckendem verschmelzen. Die teilweise Transformation zeigt den Kampf zwischen Maschine und Organismus. Sehr begehrte Variante, die die gefährliche Kombination von Stark-Tech und Symbiont-Kraft erforscht.",
    description_fr: "Iron Venom affiche la transformation intermédiaire horrifiante avec un couvre-chef partiellement transformé entre l'armure Iron Man et le symbiote Venom. Cette variante unique capture le moment où la technologie et la biologie extraterrestre fusionnent en quelque chose de terrifiant. La transformation partielle met en valeur la lutte entre machine et organisme. Variante hautement collectionnable explorant la combinaison dangereuse de la technologie Stark et du pouvoir du symbiote.",
    description_es: "Iron Venom muestra la horrible transformación intermedia con tocado parcialmente transformado entre armadura de Iron Man y simbionte Venom. Esta variante única captura el momento cuando tecnología y biología alienígena se fusionan en algo aterrador. La transformación parcial muestra la lucha entre máquina y organismo. Variante altamente coleccionable que explora la peligrosa combinación de tecnología Stark y poder del simbionte."
  },
  {
    minifigure_no: 'sh0698',
    description_en: "Pork Grind brings Spider-Ham's villainous counterpart to life as the pork-themed version of classic Marvel villains. This comedic antagonist from the Spider-Verse adds humor and chaos to Peter Porker's cartoon universe adventures. The anthropomorphic villain design creates memorable contrast to heroic Spider-Ham. Fun addition for Spider-Verse collections and cartoon-themed displays.",
    description_de: "Pork Grind bringt Spider-Hams schurkenhafte Entsprechung zum Leben als schweine-thematische Version klassischer Marvel-Schurken. Dieser komödiantische Antagonist aus dem Spider-Verse fügt Humor und Chaos zu Peter Porkers Cartoon-Universum-Abenteuern hinzu. Das anthropomorphe Schurken-Design schafft einprägsamen Kontrast zum heroischen Spider-Ham. Lustige Ergänzung für Spider-Verse-Sammlungen und Cartoon-thematische Displays.",
    description_fr: "Pork Grind donne vie à la contrepartie méchante de Spider-Ham en tant que version à thème porcin de méchants Marvel classiques. Cet antagoniste comique du Spider-Verse ajoute humour et chaos aux aventures de l'univers cartoon de Peter Porker. Le design de méchant anthropomorphe crée un contraste mémorable avec le héroïque Spider-Ham. Ajout amusant pour les collections Spider-Verse et les présentations à thème cartoon.",
    description_es: "Pork Grind trae a la vida la contraparte villana de Spider-Ham como la versión temática de cerdo de villanos clásicos de Marvel. Este antagonista cómico del Spider-Verse agrega humor y caos a las aventuras del universo de dibujos animados de Peter Porker. El diseño de villano antropomórfico crea contraste memorable con el heroico Spider-Ham. Adición divertida para colecciones de Spider-Verse y exhibiciones temáticas de dibujos animados."
  },
  {
    minifigure_no: 'sh0699',
    description_en: "Katy stands as Shang-Chi's loyal best friend bringing humor and heart to his hero journey. Despite lacking martial arts training, her courage and quick thinking prove invaluable during dangerous adventures. This civilian companion character represents the importance of friendship and ordinary heroism. Essential supporting character for Shang-Chi displays and civilian ally collections.",
    description_de: "Katy steht als Shang-Chis treue beste Freundin und bringt Humor und Herz zu seiner Helden-Reise. Trotz fehlenden Kampfkunst-Trainings erweisen sich ihr Mut und schnelles Denken als unschätzbar während gefährlicher Abenteuer. Diese zivile Begleitfigur repräsentiert die Wichtigkeit von Freundschaft und gewöhnlichem Heldentum. Unverzichtbare Nebenfigur für Shang-Chi-Displays und zivile Verbündeten-Sammlungen.",
    description_fr: "Katy se tient comme la meilleure amie fidèle de Shang-Chi apportant humour et cœur à son parcours de héros. Malgré le manque de formation en arts martiaux, son courage et sa pensée rapide se révèlent inestimables lors d'aventures dangereuses. Ce personnage compagnon civil représente l'importance de l'amitié et de l'héroïsme ordinaire. Personnage de soutien essentiel pour les présentations Shang-Chi et les collections d'alliés civils.",
    description_es: "Katy se para como la leal mejor amiga de Shang-Chi trayendo humor y corazón a su viaje heroico. A pesar de carecer de entrenamiento en artes marciales, su coraje y pensamiento rápido resultan invaluables durante aventuras peligrosas. Este personaje compañero civil representa la importancia de la amistad y el heroísmo ordinario. Personaje de apoyo esencial para exhibiciones de Shang-Chi y colecciones de aliados civiles."
  },
  {
    minifigure_no: 'sh0700',
    description_en: "Shang-Chi masters martial arts as the son of the legendary Mandarin bringing kung fu expertise to the MCU. Trained since childhood as an assassin, Shang-Chi chose heroism over his father's criminal empire. His incredible fighting skills and moral courage make him one of Marvel's most skilled hand-to-hand combatants. Essential hero for martial arts focused collections and Shang-Chi movie displays.",
    description_de: "Shang-Chi meistert Kampfkünste als Sohn des legendären Mandarin und bringt Kung-Fu-Expertise ins MCU. Seit Kindheit als Attentäter trainiert, wählte Shang-Chi Heldentum über das kriminelle Imperium seines Vaters. Seine unglaublichen Kampffähigkeiten und moralischer Mut machen ihn zu einem der geschicktesten Nahkampf-Kämpfer von Marvel. Unverzichtbarer Held für Kampfkunst-fokussierte Sammlungen und Shang-Chi-Film-Displays.",
    description_fr: "Shang-Chi maîtrise les arts martiaux en tant que fils du légendaire Mandarin apportant une expertise en kung-fu au MCU. Formé depuis l'enfance comme assassin, Shang-Chi a choisi l'héroïsme plutôt que l'empire criminel de son père. Ses incroyables compétences de combat et son courage moral font de lui l'un des combattants au corps à corps les plus compétents de Marvel. Héros essentiel pour les collections axées sur les arts martiaux et les présentations de film Shang-Chi.",
    description_es: "Shang-Chi domina las artes marciales como hijo del legendario Mandarín trayendo experiencia en kung-fu al MCU. Entrenado desde la infancia como asesino, Shang-Chi eligió el heroísmo sobre el imperio criminal de su padre. Sus increíbles habilidades de lucha y coraje moral lo convierten en uno de los combatientes cuerpo a cuerpo más hábiles de Marvel. Héroe esencial para colecciones enfocadas en artes marciales y exhibiciones de la película Shang-Chi."
  }
];

async function main() {
  console.log(`🦸 Starting Super Heroes batch sh0676-sh0700 (${descriptions.length} minifigs)...\n`);

  for (let i = 0; i < descriptions.length; i++) {
    const desc = descriptions[i];

    await prisma.minifigCatalog.update({
      where: { minifigure_no: desc.minifigure_no },
      data: {
        description_en: desc.description_en,
        description_de: desc.description_de,
        description_fr: desc.description_fr,
        description_es: desc.description_es,
        description_generated_at: new Date(),
        description_status: 'completed'
      }
    });

    console.log(`✓ Saved ${desc.minifigure_no} (${i + 1}/${descriptions.length})`);
  }

  console.log(`\n✅ Batch complete! ${descriptions.length} minifigs saved. Total: 700 done.`);
  await prisma.$disconnect();
}

main().catch(async (e) => {
  console.error('Error:', e);
  await prisma.$disconnect();
  process.exit(1);
});
