import { PrismaClient as PrismaClientHostinger } from '@prisma/client';

const prisma = new PrismaClientHostinger({
  datasources: {
    db: {
      url: "mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker"
    }
  }
});

const descriptions = [
  {
    minifigure_no: 'sh0576',
    description_en: "Thanos - Large Figure, Dark Bluish Gray Outfit with Gold Armor, Pearl Gold Helmet brings the Mad Titan to LEGO form in armored configuration. This large figure showcases Thanos in dark bluish gray with distinctive gold armor plating and pearl gold helmet, representing his fully-armored warrior appearance. The design emphasizes Thanos's imposing presence with enhanced protection. A premium villain centerpiece for MCU collectors building Thanos in battle-ready configuration.",
    description_de: "Thanos - Large Figure, Dark Bluish Gray Outfit with Gold Armor, Pearl Gold Helmet bringt den Mad Titan in LEGO-Form in gepanzerter Konfiguration. Diese große Figur präsentiert Thanos in dunkel bläulich-grau mit markanter goldener Rüstungsplattierung und perlgoldenem Helm, repräsentiert sein vollgepanzertes Krieger-Erscheinungsbild. Das Design betont Thanos' imposante Präsenz mit verbessertem Schutz. Ein Premium-Schurken-Herzstück für MCU-Sammler, die Thanos in kampfbereiter Konfiguration aufbauen.",
    description_fr: "Thanos - Large Figure, Dark Bluish Gray Outfit with Gold Armor, Pearl Gold Helmet apporte le Titan Fou en forme LEGO en configuration blindée. Cette grande figurine présente Thanos en gris bleuté foncé avec blindage doré distinctif et casque or perlé, représentant son apparence de guerrier entièrement blindé. Le design souligne la présence imposante de Thanos avec protection améliorée. Une pièce maîtresse de méchant premium pour les collectionneurs MCU construisant Thanos en configuration prête au combat.",
    description_es: "Thanos - Large Figure, Dark Bluish Gray Outfit with Gold Armor, Pearl Gold Helmet trae al Titán Loco en forma LEGO en configuración blindada. Esta figura grande muestra a Thanos en gris azulado oscuro con distintivo blindaje dorado y casco oro perla, representando su apariencia de guerrero totalmente blindado. El diseño enfatiza la presencia imponente de Thanos con protección mejorada. Una pieza central villana premium para coleccionistas MCU construyendo a Thanos en configuración lista para batalla."
  },
  {
    minifigure_no: 'sh0577',
    description_en: "Hulk - Giant, Dark Blue Pants brings the Green Goliath to LEGO form in large scale with alternate pants coloring. This giant figure showcases Hulk with dark blue pants instead of purple, providing color variation for the strongest Avenger. The design maintains Hulk's massive size while offering display diversity. A variant for MCU collectors seeking different Hulk pant color options in large-format figures.",
    description_de: "Hulk - Giant, Dark Blue Pants bringt den Grünen Goliath in LEGO-Form in großem Maßstab mit alternativer Hosenfärbung. Diese riesige Figur präsentiert Hulk mit dunkelblauen Hosen statt lila, bietet Farbvariation für den stärksten Avenger. Das Design bewahrt Hulks massive Größe, während es Darstellungsvielfalt bietet. Eine Variante für MCU-Sammler, die verschiedene Hulk-Hosen-Farboptionen in großformatigen Figuren suchen.",
    description_fr: "Hulk - Giant, Dark Blue Pants apporte le Goliath Vert en forme LEGO à grande échelle avec coloration de pantalon alternative. Cette figurine géante présente Hulk avec pantalon bleu foncé au lieu de violet, fournissant une variation de couleur pour l'Avenger le plus fort. Le design maintient la taille massive de Hulk tout en offrant une diversité d'affichage. Une variante pour les collectionneurs MCU recherchant différentes options de couleur de pantalon Hulk dans des figurines grand format.",
    description_es: "Hulk - Giant, Dark Blue Pants trae al Goliat Verde en forma LEGO a gran escala con coloración de pantalones alternativa. Esta figura gigante muestra a Hulk con pantalones azul oscuro en lugar de púrpura, proporcionando variación de color para el Avenger más fuerte. El diseño mantiene el tamaño masivo de Hulk mientras ofrece diversidad de exhibición. Una variante para coleccionistas MCU buscando diferentes opciones de color de pantalones de Hulk en figuras de gran formato."
  },
  {
    minifigure_no: 'sh0578',
    description_en: "Spider-Man - Black and Gray Suit (Stealth Suit) brings Peter Parker to LEGO form in tactical gear from Spider-Man: Far From Home. This figure showcases Spidey in black and gray stealth suit without traditional colors, representing his covert European mission outfit. The design emphasizes the tactical, non-superhero appearance. A popular variant for Spider-Man collectors building Far From Home adventures and stealth mission scenarios.",
    description_de: "Spider-Man - Black and Gray Suit (Stealth Suit) bringt Peter Parker in LEGO-Form in taktischer Ausrüstung aus Spider-Man: Far From Home. Diese Figur präsentiert Spidey in schwarz-grauem Tarnanzug ohne traditionelle Farben, repräsentiert sein verdecktes Europa-Missions-Outfit. Das Design betont das taktische Nicht-Superhelden-Erscheinungsbild. Eine beliebte Variante für Spider-Man-Sammler, die Far From Home Abenteuer und Tarnmissions-Szenarien aufbauen.",
    description_fr: "Spider-Man - Black and Gray Suit (Stealth Suit) apporte Peter Parker en forme LEGO en équipement tactique de Spider-Man: Far From Home. Cette figurine présente Spidey en combinaison furtive noire et grise sans couleurs traditionnelles, représentant sa tenue de mission européenne secrète. Le design souligne l'apparence tactique non super-héroïque. Une variante populaire pour les collectionneurs Spider-Man construisant des aventures Far From Home et des scénarios de mission furtive.",
    description_es: "Spider-Man - Black and Gray Suit (Stealth Suit) trae a Peter Parker en forma LEGO en equipo táctico de Spider-Man: Far From Home. Esta figura muestra a Spidey en traje sigiloso negro y gris sin colores tradicionales, representando su atuendo de misión europea encubierta. El diseño enfatiza la apariencia táctica no-superhéroe. Una variante popular para coleccionistas de Spider-Man construyendo aventuras de Far From Home y escenarios de misión sigilosa."
  },
  {
    minifigure_no: 'sh0579',
    description_en: "Firefighter - Dark Red Fire Helmet, Reddish Brown Head, Reflective Stripes provides essential civilian presence for Spider-Man sets. This figure represents New York City's brave firefighters with authentic gear including reflective safety stripes, adding realism to emergency response scenes. The design emphasizes professional first responder appearance. A practical civilian for Spider-Man collectors building realistic NYC emergency scenarios.",
    description_de: "Firefighter - Dark Red Fire Helmet, Reddish Brown Head, Reflective Stripes bietet wesentliche Zivilpräsenz für Spider-Man Sets. Diese Figur repräsentiert New York Citys tapfere Feuerwehrleute mit authentischer Ausrüstung einschließlich reflektierender Sicherheitsstreifen, fügt Realismus zu Notfall-Reaktions-Szenen hinzu. Das Design betont professionelles Ersthelfer-Erscheinungsbild. Ein praktischer Zivilist für Spider-Man-Sammler, die realistische NYC-Notfall-Szenarien aufbauen.",
    description_fr: "Firefighter - Dark Red Fire Helmet, Reddish Brown Head, Reflective Stripes fournit une présence civile essentielle pour les ensembles Spider-Man. Cette figurine représente les courageux pompiers de New York City avec équipement authentique incluant des bandes de sécurité réfléchissantes, ajoutant du réalisme aux scènes de réponse d'urgence. Le design souligne l'apparence professionnelle de premier intervenant. Un civil pratique pour les collectionneurs Spider-Man construisant des scénarios d'urgence NYC réalistes.",
    description_es: "Firefighter - Dark Red Fire Helmet, Reddish Brown Head, Reflective Stripes proporciona presencia civil esencial para sets de Spider-Man. Esta figura representa a los valientes bomberos de la Ciudad de Nueva York con equipo auténtico incluyendo rayas de seguridad reflectantes, agregando realismo a escenas de respuesta de emergencia. El diseño enfatiza apariencia profesional de primer respondedor. Un civil práctico para coleccionistas de Spider-Man construyendo escenarios de emergencia NYC realistas."
  },
  {
    minifigure_no: 'sh0580',
    description_en: "Mysterio - Magenta Trim, Flat Silver Head, Trans-Clear Helmet brings the master of illusion to LEGO form from Spider-Man: Far From Home. This figure showcases Quentin Beck in distinctive costume with magenta trim, silver head, and transparent helmet, representing his false hero persona. The design emphasizes Mysterio's theatrical appearance and deceptive nature. A crucial villain for Spider-Man collectors building Far From Home battles and illusion-based conflicts.",
    description_de: "Mysterio - Magenta Trim, Flat Silver Head, Trans-Clear Helmet bringt den Meister der Illusion in LEGO-Form aus Spider-Man: Far From Home. Diese Figur präsentiert Quentin Beck im markanten Kostüm mit Magenta-Besatz, silbernem Kopf und transparentem Helm, repräsentiert seine falsche Helden-Persona. Das Design betont Mysterios theatralisches Erscheinungsbild und täuschende Natur. Ein entscheidender Schurke für Spider-Man-Sammler, die Far From Home Kämpfe und illusionsbasierte Konflikte aufbauen.",
    description_fr: "Mysterio - Magenta Trim, Flat Silver Head, Trans-Clear Helmet apporte le maître de l'illusion en forme LEGO de Spider-Man: Far From Home. Cette figurine présente Quentin Beck en costume distinctif avec garniture magenta, tête argentée et casque transparent, représentant son faux personnage de héros. Le design souligne l'apparence théâtrale de Mysterio et sa nature trompeuse. Un méchant crucial pour les collectionneurs Spider-Man construisant des batailles Far From Home et des conflits basés sur l'illusion.",
    description_es: "Mysterio - Magenta Trim, Flat Silver Head, Trans-Clear Helmet trae al maestro de la ilusión en forma LEGO de Spider-Man: Far From Home. Esta figura muestra a Quentin Beck en traje distintivo con ribete magenta, cabeza plateada y casco transparente, representando su falsa persona de héroe. El diseño enfatiza la apariencia teatral de Mysterio y naturaleza engañosa. Un villano crucial para coleccionistas de Spider-Man construyendo batallas de Far From Home y conflictos basados en ilusión."
  },
  {
    minifigure_no: 'sh0581',
    description_en: "Hydro-Man brings the water-powered villain to LEGO form from Spider-Man: Far From Home. This figure captures Morris Bench with distinctive water-based appearance, representing one of Mysterio's elemental illusions. The design emphasizes Hydro-Man's liquid form and aquatic threat. A memorable villain minifigure for Spider-Man collectors building Far From Home's elemental battles and Mysterio's elaborate deceptions.",
    description_de: "Hydro-Man bringt den wasser-getriebenen Schurken in LEGO-Form aus Spider-Man: Far From Home. Diese Figur erfasst Morris Bench mit markanter wasser-basierter Erscheinung, repräsentiert eine von Mysterios elementaren Illusionen. Das Design betont Hydro-Mans flüssige Form und aquatische Bedrohung. Eine einprägsame Schurken-Minifigur für Spider-Man-Sammler, die Far From Homes elementare Kämpfe und Mysterios aufwendige Täuschungen aufbauen.",
    description_fr: "Hydro-Man apporte le méchant aux pouvoirs d'eau en forme LEGO de Spider-Man: Far From Home. Cette figurine capture Morris Bench avec apparence basée sur l'eau distinctive, représentant l'une des illusions élémentaires de Mysterio. Le design souligne la forme liquide d'Hydro-Man et la menace aquatique. Une figurine méchante mémorable pour les collectionneurs Spider-Man construisant les batailles élémentaires de Far From Home et les tromperies élaborées de Mysterio.",
    description_es: "Hydro-Man trae al villano con poderes de agua en forma LEGO de Spider-Man: Far From Home. Esta figura captura a Morris Bench con apariencia distintiva basada en agua, representando una de las ilusiones elementales de Mysterio. El diseño enfatiza la forma líquida de Hydro-Man y amenaza acuática. Una minifigura villana memorable para coleccionistas de Spider-Man construyendo batallas elementales de Far From Home y engaños elaborados de Mysterio."
  },
  {
    minifigure_no: 'sh0582',
    description_en: "Peter Parker - Spider-Man Cap brings Spider-Man's alter ego to LEGO form in casual attire. This figure showcases Peter in civilian clothes with Spider-Man baseball cap, representing his off-duty moments and teenage life. The design provides essential character representation beyond the costume. A necessary minifigure for Spider-Man collectors building complete Peter Parker storylines and civilian life scenes.",
    description_de: "Peter Parker - Spider-Man Cap bringt Spider-Mans Alter Ego in LEGO-Form in Freizeitkleidung. Diese Figur präsentiert Peter in Zivilkleidung mit Spider-Man Baseballkappe, repräsentiert seine Nicht-Dienst-Momente und Teenager-Leben. Das Design bietet wesentliche Charakterdarstellung jenseits des Kostüms. Eine notwendige Minifigur für Spider-Man-Sammler, die vollständige Peter Parker Handlungsstränge und Zivilleben-Szenen aufbauen.",
    description_fr: "Peter Parker - Spider-Man Cap apporte l'alter ego de Spider-Man en forme LEGO en tenue décontractée. Cette figurine présente Peter en vêtements civils avec casquette de baseball Spider-Man, représentant ses moments hors service et sa vie d'adolescent. Le design fournit une représentation de personnage essentielle au-delà du costume. Une figurine nécessaire pour les collectionneurs Spider-Man construisant des storylines complètes de Peter Parker et des scènes de vie civile.",
    description_es: "Peter Parker - Spider-Man Cap trae al alter ego de Spider-Man en forma LEGO en vestimenta casual. Esta figura muestra a Peter en ropa civil con gorra de béisbol de Spider-Man, representando sus momentos fuera de servicio y vida adolescente. El diseño proporciona representación de personaje esencial más allá del traje. Una minifigura necesaria para coleccionistas de Spider-Man construyendo líneas argumentales completas de Peter Parker y escenas de vida civil."
  },
  {
    minifigure_no: 'sh0583',
    description_en: "MJ (Michelle Jones) - Light Bluish Gray Hoodie, Black Ponytail brings Zendaya's character to LEGO form from Spider-Man: Far From Home. This figure showcases MJ in casual attire with distinctive ponytail, representing Peter's love interest and her important role in his life. The design captures MJ's modern, relatable appearance. A significant character minifigure for Spider-Man collectors building complete Far From Home cast and Peter's personal relationships.",
    description_de: "MJ (Michelle Jones) - Light Bluish Gray Hoodie, Black Ponytail bringt Zendayas Charakter in LEGO-Form aus Spider-Man: Far From Home. Diese Figur präsentiert MJ in Freizeitkleidung mit markanten Pferdeschwanz, repräsentiert Peters Liebesinteresse und ihre wichtige Rolle in seinem Leben. Das Design erfasst MJs modernes, nahbares Erscheinungsbild. Eine bedeutende Charakter-Minifigur für Spider-Man-Sammler, die vollständige Far From Home Besetzung und Peters persönliche Beziehungen aufbauen.",
    description_fr: "MJ (Michelle Jones) - Light Bluish Gray Hoodie, Black Ponytail apporte le personnage de Zendaya en forme LEGO de Spider-Man: Far From Home. Cette figurine présente MJ en tenue décontractée avec queue de cheval distinctive, représentant l'intérêt amoureux de Peter et son rôle important dans sa vie. Le design capture l'apparence moderne et accessible de MJ. Une figurine de personnage significative pour les collectionneurs Spider-Man construisant le casting complet de Far From Home et les relations personnelles de Peter.",
    description_es: "MJ (Michelle Jones) - Light Bluish Gray Hoodie, Black Ponytail trae al personaje de Zendaya en forma LEGO de Spider-Man: Far From Home. Esta figura muestra a MJ en vestimenta casual con distintiva cola de caballo, representando el interés amoroso de Peter y su papel importante en su vida. El diseño captura la apariencia moderna y relatable de MJ. Una minifigura de personaje significativa para coleccionistas de Spider-Man construyendo elenco completo de Far From Home y relaciones personales de Peter."
  },
  {
    minifigure_no: 'sh0584',
    description_en: "Tony Stark - Black Iron Man Suit with Dark Red Right Arm brings the damaged Mark 85 to LEGO form. This figure showcases Tony in black suit with distinctive dark red damaged right arm, representing the armor's battle damage during Endgame's final conflict. The design captures the toll of wielding the Infinity Stones. A poignant variant for MCU collectors honoring Tony Stark's ultimate sacrifice.",
    description_de: "Tony Stark - Black Iron Man Suit with Dark Red Right Arm bringt den beschädigten Mark 85 in LEGO-Form. Diese Figur präsentiert Tony in schwarzem Anzug mit markanten dunkelroten beschädigten rechten Arm, repräsentiert die Kampfbeschädigung der Rüstung während Endgames finalem Konflikt. Das Design erfasst die Belastung durch das Führen der Infinity Stones. Eine ergreifende Variante für MCU-Sammler, die Tony Starks ultimatives Opfer ehren.",
    description_fr: "Tony Stark - Black Iron Man Suit with Dark Red Right Arm apporte le Mark 85 endommagé en forme LEGO. Cette figurine présente Tony en costume noir avec bras droit endommagé rouge foncé distinctif, représentant les dommages de combat de l'armure pendant le conflit final d'Endgame. Le design capture le tribut de manier les Pierres d'Infinité. Une variante poignante pour les collectionneurs MCU honorant le sacrifice ultime de Tony Stark.",
    description_es: "Tony Stark - Black Iron Man Suit with Dark Red Right Arm trae el Mark 85 dañado en forma LEGO. Esta figura muestra a Tony en traje negro con distintivo brazo derecho dañado rojo oscuro, representando el daño de batalla de la armadura durante el conflicto final de Endgame. El diseño captura el costo de empuñar las Gemas del Infinito. Una variante conmovedora para coleccionistas MCU honrando el sacrificio último de Tony Stark."
  },
  {
    minifigure_no: 'sh0585',
    description_en: "Nick Fury - Gray Sweater and Black Trench Coat (Undetermined Legs) brings the S.H.I.E.L.D. director to LEGO form in casual mission attire. This figure showcases Fury in gray sweater with iconic black trench coat, representing his appearance in Spider-Man: Far From Home. The design captures Fury's commanding yet undercover presence. A valuable character minifigure for MCU collectors building Far From Home storylines and Nick Fury's mentorship role.",
    description_de: "Nick Fury - Gray Sweater and Black Trench Coat (Undetermined Legs) bringt den S.H.I.E.L.D.-Direktor in LEGO-Form in legerer Missions-Kleidung. Diese Figur präsentiert Fury in grauem Pullover mit ikonischem schwarzen Trenchcoat, repräsentiert sein Erscheinungsbild in Spider-Man: Far From Home. Das Design erfasst Furys kommandierendeaber undercover Präsenz. Eine wertvolle Charakter-Minifigur für MCU-Sammler, die Far From Home Handlungsstränge und Nick Furys Mentoren-Rolle aufbauen.",
    description_fr: "Nick Fury - Gray Sweater and Black Trench Coat (Undetermined Legs) apporte le directeur du S.H.I.E.L.D. en forme LEGO en tenue de mission décontractée. Cette figurine présente Fury en pull gris avec trench-coat noir iconique, représentant son apparence dans Spider-Man: Far From Home. Le design capture la présence commandante mais sous couverture de Fury. Une figurine de personnage précieuse pour les collectionneurs MCU construisant des storylines Far From Home et le rôle de mentor de Nick Fury.",
    description_es: "Nick Fury - Gray Sweater and Black Trench Coat (Undetermined Legs) trae al director de S.H.I.E.L.D. en forma LEGO en vestimenta de misión casual. Esta figura muestra a Fury en suéter gris con icónico abrigo largo negro, representando su apariencia en Spider-Man: Far From Home. El diseño captura la presencia dominante pero encubierta de Fury. Una minifigura de personaje valiosa para coleccionistas MCU construyendo líneas argumentales de Far From Home y papel de mentor de Nick Fury."
  },
  {
    minifigure_no: 'sh0586',
    description_en: "Shazam brings the lightning-powered hero to LEGO form from the DCEU. This figure showcases Billy Batson's superhero form in distinctive red suit with gold lightning bolt and white cape, representing the magical champion. The design emphasizes Shazam's youthful heroism and magical powers. A popular character minifigure for DC collectors building DCEU teams and Shazam's magical adventures.",
    description_de: "Shazam bringt den blitz-getriebenen Helden in LEGO-Form aus dem DCEU. Diese Figur präsentiert Billy Batsons Superhelden-Form im markanten roten Anzug mit goldenem Blitz und weißem Umhang, repräsentiert den magischen Champion. Das Design betont Shazams jugendliches Heldentum und magische Kräfte. Eine beliebte Charakter-Minifigur für DC-Sammler, die DCEU-Teams und Shazams magische Abenteuer aufbauen.",
    description_fr: "Shazam apporte le héros aux pouvoirs de foudre en forme LEGO du DCEU. Cette figurine présente la forme de super-héros de Billy Batson en costume rouge distinctif avec éclair doré et cape blanche, représentant le champion magique. Le design souligne l'héroïsme juvénile de Shazam et ses pouvoirs magiques. Une figurine de personnage populaire pour les collectionneurs DC construisant des équipes DCEU et des aventures magiques de Shazam.",
    description_es: "Shazam trae al héroe con poderes de rayo en forma LEGO del DCEU. Esta figura muestra la forma de superhéroe de Billy Batson en distintivo traje rojo con rayo dorado y capa blanca, representando al campeón mágico. El diseño enfatiza el heroísmo juvenil de Shazam y poderes mágicos. Una minifigura de personaje popular para coleccionistas DC construyendo equipos DCEU y aventuras mágicas de Shazam."
  },
  {
    minifigure_no: 'sh0587',
    description_en: "Mr. Freeze, Pearl Dark Gray, Neck Bracket provides a building variant of Batman's cryogenic villain. This figure features Mr. Freeze in pearl dark gray with neck bracket for helmet attachment, offering modular display options. The design allows customization of Freeze's distinctive appearance. A practical variant for Batman collectors creating custom Mr. Freeze poses and cryogenic laboratory scenes.",
    description_de: "Mr. Freeze, Pearl Dark Gray, Neck Bracket bietet eine Bau-Variante von Batmans kryogenischen Schurken. Diese Figur zeigt Mr. Freeze in perldunkelgrau mit Halshalterung für Helmbefestigung, bietet modulare Darstellungsoptionen. Das Design ermöglicht Anpassung von Freezes markanter Erscheinung. Eine praktische Variante für Batman-Sammler, die benutzerdefinierte Mr. Freeze Posen und kryogene Labor-Szenen erstellen.",
    description_fr: "Mr. Freeze, Pearl Dark Gray, Neck Bracket fournit une variante de construction du méchant cryogénique de Batman. Cette figurine présente Mr. Freeze en gris foncé perlé avec support de cou pour fixation de casque, offrant des options d'affichage modulaires. Le design permet la personnalisation de l'apparence distinctive de Freeze. Une variante pratique pour les collectionneurs Batman créant des poses Mr. Freeze personnalisées et des scènes de laboratoire cryogénique.",
    description_es: "Mr. Freeze, Pearl Dark Gray, Neck Bracket proporciona una variante de construcción del villano criogénico de Batman. Esta figura presenta a Mr. Freeze en gris oscuro perla con soporte de cuello para conexión de casco, ofreciendo opciones de exhibición modulares. El diseño permite personalización de la apariencia distintiva de Freeze. Una variante práctica para coleccionistas de Batman creando poses personalizadas de Mr. Freeze y escenas de laboratorio criogénico."
  },
  {
    minifigure_no: 'sh0588',
    description_en: "Robin - Green Mask and Hands, Black Short Legs, Yellow Scalloped Cape brings the Boy Wonder to LEGO form in junior format. This figure showcases Dick Grayson with distinctive green mask, short legs, and classic yellow scalloped cape for younger builds. The design maintains Robin's iconic appearance in age-appropriate configuration. A valuable junior hero for Batman collectors building junior Dynamic Duo sets.",
    description_de: "Robin - Green Mask and Hands, Black Short Legs, Yellow Scalloped Cape bringt den Boy Wonder in LEGO-Form im Junior-Format. Diese Figur präsentiert Dick Grayson mit markanter grüner Maske, kurzen Beinen und klassischem gelben gezackten Umhang für jüngere Bauten. Das Design bewahrt Robins ikonisches Erscheinungsbild in altersgerechter Konfiguration. Ein wertvoller Junior-Held für Batman-Sammler, die Junior Dynamic Duo Sets aufbauen.",
    description_fr: "Robin - Green Mask and Hands, Black Short Legs, Yellow Scalloped Cape apporte le Boy Wonder en forme LEGO en format junior. Cette figurine présente Dick Grayson avec masque vert distinctif, jambes courtes et cape festonnée jaune classique pour des constructions plus jeunes. Le design maintient l'apparence iconique de Robin en configuration adaptée à l'âge. Un héros junior précieux pour les collectionneurs Batman construisant des ensembles Dynamic Duo junior.",
    description_es: "Robin - Green Mask and Hands, Black Short Legs, Yellow Scalloped Cape trae al Boy Wonder en forma LEGO en formato junior. Esta figura muestra a Dick Grayson con distintiva máscara verde, piernas cortas y capa festoneada amarilla clásica para construcciones más jóvenes. El diseño mantiene la apariencia icónica de Robin en configuración apropiada para la edad. Un héroe junior valioso para coleccionistas de Batman construyendo sets de Dúo Dinámico junior."
  },
  {
    minifigure_no: 'sh0589',
    description_en: "Batman - Dark Bluish Gray Suit with Gold Outline Belt and Crest, Mask and Cape (Type 3 Cowl, Teardrop Neck Cut Spongy Cape) showcases specific technical specifications. This figure features Batman with Type 3 cowl and teardrop neck cut cape design, offering precise variant identification for collectors. The design provides detailed costume documentation. A technical variant for Batman collectors cataloging specific cowl types and cape configurations.",
    description_de: "Batman - Dark Bluish Gray Suit with Gold Outline Belt and Crest, Mask and Cape (Type 3 Cowl, Teardrop Neck Cut Spongy Cape) präsentiert spezifische technische Spezifikationen. Diese Figur zeigt Batman mit Typ-3-Kapuze und Tropfen-Halsschnitt-Umhang-Design, bietet präzise Variantenidentifikation für Sammler. Das Design bietet detaillierte Kostümdokumentation. Eine technische Variante für Batman-Sammler, die spezifische Kapuzen-Typen und Umhang-Konfigurationen katalogisieren.",
    description_fr: "Batman - Dark Bluish Gray Suit with Gold Outline Belt and Crest, Mask and Cape (Type 3 Cowl, Teardrop Neck Cut Spongy Cape) présente des spécifications techniques spécifiques. Cette figurine présente Batman avec cagoule Type 3 et design de cape à coupe de cou en larme, offrant une identification de variante précise pour les collectionneurs. Le design fournit une documentation de costume détaillée. Une variante technique pour les collectionneurs Batman cataloguant des types de cagoule spécifiques et des configurations de cape.",
    description_es: "Batman - Dark Bluish Gray Suit with Gold Outline Belt and Crest, Mask and Cape (Type 3 Cowl, Teardrop Neck Cut Spongy Cape) muestra especificaciones técnicas específicas. Esta figura presenta a Batman con capucha Tipo 3 y diseño de capa con corte de cuello de lágrima, ofreciendo identificación de variante precisa para coleccionistas. El diseño proporciona documentación de vestuario detallada. Una variante técnica para coleccionistas de Batman catalogando tipos específicos de capucha y configuraciones de capa."
  },
  {
    minifigure_no: 'sh0590',
    description_en: "The Joker - Orange Bow Tie, Green Arms brings the Clown Prince to LEGO form with colorful styling. This figure showcases the Joker in distinctive orange bow tie with green arms, emphasizing his flamboyant wardrobe choices. The design captures Joker's theatrical personality through bold color combinations. A vibrant villain variant for Batman collectors who appreciate Joker's diverse costume interpretations.",
    description_de: "The Joker - Orange Bow Tie, Green Arms bringt den Clown Prince in LEGO-Form mit farbenfrohem Styling. Diese Figur präsentiert den Joker in markanter oranger Fliege mit grünen Armen, betont seine extravaganten Garderoben-Entscheidungen. Das Design erfasst Jokers theatralische Persönlichkeit durch kühne Farbkombinationen. Eine lebendige Schurken-Variante für Batman-Sammler, die Jokers vielfältige Kostüminterpretationen schätzen.",
    description_fr: "The Joker - Orange Bow Tie, Green Arms apporte le Clown Prince en forme LEGO avec un style coloré. Cette figurine présente le Joker en nœud papillon orange distinctif avec bras verts, soulignant ses choix de garde-robe flamboyants. Le design capture la personnalité théâtrale du Joker à travers des combinaisons de couleurs audacieuses. Une variante de méchant vibrante pour les collectionneurs Batman qui apprécient les interprétations de costume diverses du Joker.",
    description_es: "The Joker - Orange Bow Tie, Green Arms trae al Príncipe Payaso en forma LEGO con estilo colorido. Esta figura muestra al Joker en distintivo corbatín naranja con brazos verdes, enfatizando sus elecciones extravagantes de vestuario. El diseño captura la personalidad teatral del Joker mediante combinaciones de colores audaces. Una variante villana vibrante para coleccionistas de Batman que aprecian las diversas interpretaciones de vestuario del Joker."
  },
  {
    minifigure_no: 'sh0591',
    description_en: "Commissioner Gordon - Reddish Brown Hair and Coat brings Batman's police ally to LEGO form. This figure showcases James Gordon in civilian attire with distinctive coat, representing Gotham's honest police commissioner and Batman's essential GCPD connection. The design captures Gordon's determined law enforcement presence. A necessary supporting character for Batman collectors building complete Gotham City cast and police headquarters scenes.",
    description_de: "Commissioner Gordon - Reddish Brown Hair and Coat bringt Batmans Polizei-Verbündeten in LEGO-Form. Diese Figur präsentiert James Gordon in Zivilkleidung mit markanten Mantel, repräsentiert Gothams ehrlichen Polizeikommissar und Batmans wesentliche GCPD-Verbindung. Das Design erfasst Gordons entschlossene Strafverfolgungs-Präsenz. Ein notwendiger Nebencharakter für Batman-Sammler, die vollständige Gotham City Besetzung und Polizeihauptquartier-Szenen aufbauen.",
    description_fr: "Commissioner Gordon - Reddish Brown Hair and Coat apporte l'allié policier de Batman en forme LEGO. Cette figurine présente James Gordon en tenue civile avec manteau distinctif, représentant le commissaire de police honnête de Gotham et la connexion essentielle de Batman au GCPD. Le design capture la présence déterminée d'application de la loi de Gordon. Un personnage secondaire nécessaire pour les collectionneurs Batman construisant le casting complet de Gotham City et des scènes de quartier général de police.",
    description_es: "Commissioner Gordon - Reddish Brown Hair and Coat trae al aliado policial de Batman en forma LEGO. Esta figura muestra a James Gordon en vestimenta civil con distintivo abrigo, representando al honesto comisionado de policía de Gotham y conexión esencial de Batman con GCPD. El diseño captura la presencia determinada de aplicación de la ley de Gordon. Un personaje de apoyo necesario para coleccionistas de Batman construyendo elenco completo de Gotham City y escenas de cuartel general de policía."
  },
  {
    minifigure_no: 'sh0592',
    description_en: "Shazam - White Hood, Spongy Cape brings the champion of magic to LEGO form with enhanced cape configuration. This figure showcases Shazam with distinctive white hood and spongy cape design, representing his magical hero appearance with additional styling. The design adds visual drama to Shazam's costume. A variant for DC collectors seeking different Shazam cape and hood configurations.",
    description_de: "Shazam - White Hood, Spongy Cape bringt den Champion der Magie in LEGO-Form mit verbesserter Umhang-Konfiguration. Diese Figur präsentiert Shazam mit markanter weißer Kapuze und schwammigem Umhang-Design, repräsentiert sein magisches Helden-Erscheinungsbild mit zusätzlichem Styling. Das Design fügt visuelles Drama zu Shazams Kostüm hinzu. Eine Variante für DC-Sammler, die verschiedene Shazam-Umhang- und Kapuzen-Konfigurationen suchen.",
    description_fr: "Shazam - White Hood, Spongy Cape apporte le champion de la magie en forme LEGO avec configuration de cape améliorée. Cette figurine présente Shazam avec capuche blanche distinctive et design de cape spongieuse, représentant son apparence de héros magique avec style supplémentaire. Le design ajoute du drame visuel au costume de Shazam. Une variante pour les collectionneurs DC recherchant différentes configurations de cape et capuche Shazam.",
    description_es: "Shazam - White Hood, Spongy Cape trae al campeón de la magia en forma LEGO con configuración de capa mejorada. Esta figura muestra a Shazam con distintiva capucha blanca y diseño de capa esponjosa, representando su apariencia de héroe mágico con estilo adicional. El diseño agrega drama visual al traje de Shazam. Una variante para coleccionistas DC buscando diferentes configuraciones de capa y capucha de Shazam."
  },
  {
    minifigure_no: 'sh0593',
    description_en: "The Riddler - Lime Outfit brings Edward Nygma to LEGO form in vibrant question-mark themed attire. This figure showcases the Riddler in distinctive lime green outfit, representing his obsession with puzzles and riddles. The design emphasizes Riddler's colorful criminal aesthetic and intellectual villainy. A classic villain minifigure for Batman collectors building Gotham rogues' gallery and puzzle-based crimes.",
    description_de: "The Riddler - Lime Outfit bringt Edward Nygma in LEGO-Form in lebendiger fragezeichen-thematisierter Kleidung. Diese Figur präsentiert den Riddler in markanter limonengrüner Kleidung, repräsentiert seine Besessenheit von Puzzles und Rätseln. Das Design betont Riddlers farbenfrohe kriminelle Ästhetik und intellektuelle Schurkenei. Eine klassische Schurken-Minifigur für Batman-Sammler, die Gothams Schurkengalerie und puzzle-basierte Verbrechen aufbauen.",
    description_fr: "The Riddler - Lime Outfit apporte Edward Nygma en forme LEGO en tenue vibrante à thème de point d'interrogation. Cette figurine présente le Riddler en tenue vert citron distinctive, représentant son obsession pour les puzzles et les énigmes. Le design souligne l'esthétique criminelle colorée du Riddler et la vilenie intellectuelle. Une figurine méchante classique pour les collectionneurs Batman construisant la galerie de méchants de Gotham et les crimes basés sur les puzzles.",
    description_es: "The Riddler - Lime Outfit trae a Edward Nygma en forma LEGO en atuendo vibrante con temática de signo de interrogación. Esta figura muestra al Riddler en distintivo atuendo verde lima, representando su obsesión con rompecabezas y acertijos. El diseño enfatiza la estética criminal colorida de Riddler y villanía intelectual. Una minifigura villana clásica para coleccionistas de Batman construyendo galería de villanos de Gotham y crímenes basados en acertijos."
  },
  {
    minifigure_no: 'sh0594',
    description_en: "Two-Face - Black Shirt, Red Tie and Jacket brings Harvey Dent's villainous form to LEGO form. This figure showcases Two-Face in distinctive half-scarred appearance with stylish attire, representing the duality-obsessed criminal mastermind. The design captures Two-Face's split personality through his characteristic appearance. A significant villain for Batman collectors building Gotham rogues' gallery and courtroom-to-crime storylines.",
    description_de: "Two-Face - Black Shirt, Red Tie and Jacket bringt Harvey Dents schurkenhafte Form in LEGO-Form. Diese Figur präsentiert Two-Face in markanter halb-vernarbter Erscheinung mit stilvoller Kleidung, repräsentiert den dualitäts-besessenen kriminellen Mastermind. Das Design erfasst Two-Faces gespaltene Persönlichkeit durch sein charakteristisches Erscheinungsbild. Ein bedeutender Schurke für Batman-Sammler, die Gothams Schurkengalerie und Gerichtssaal-zu-Verbrechen-Handlungsstränge aufbauen.",
    description_fr: "Two-Face - Black Shirt, Red Tie and Jacket apporte la forme de méchant de Harvey Dent en forme LEGO. Cette figurine présente Two-Face en apparence distinctive à moitié cicatrisée avec tenue élégante, représentant le cerveau criminel obsédé par la dualité. Le design capture la personnalité divisée de Two-Face à travers son apparence caractéristique. Un méchant significatif pour les collectionneurs Batman construisant la galerie de méchants de Gotham et des storylines de salle d'audience au crime.",
    description_es: "Two-Face - Black Shirt, Red Tie and Jacket trae la forma villana de Harvey Dent en forma LEGO. Esta figura muestra a Two-Face en distintiva apariencia medio-cicatrizada con atuendo elegante, representando a la mente maestra criminal obsesionada con dualidad. El diseño captura la personalidad dividida de Two-Face mediante su apariencia característica. Un villano significativo para coleccionistas de Batman construyendo galería de villanos de Gotham y líneas argumentales de sala de corte a crimen."
  },
  {
    minifigure_no: 'sh0595',
    description_en: "Catwoman - Black Suit and Mask, Silver Goggles brings Selina Kyle to LEGO form in classic cat burglar attire. This figure showcases Catwoman in sleek black suit with distinctive silver goggles, representing her morally ambiguous antihero persona. The design emphasizes Catwoman's feline grace and thief aesthetic. A popular character for Batman collectors building complex relationships and Gotham's gray-area characters.",
    description_de: "Catwoman - Black Suit and Mask, Silver Goggles bringt Selina Kyle in LEGO-Form in klassischer Katzendieb-Kleidung. Diese Figur präsentiert Catwoman in schlankem schwarzen Anzug mit markanten silbernen Schutzbrillen, repräsentiert ihre moralisch zweideutige Antihelden-Persona. Das Design betont Catwomans katzenartige Anmut und Dieb-Ästhetik. Ein beliebter Charakter für Batman-Sammler, die komplexe Beziehungen und Gothams Grauzone-Charaktere aufbauen.",
    description_fr: "Catwoman - Black Suit and Mask, Silver Goggles apporte Selina Kyle en forme LEGO en tenue classique de cambrioleuse féline. Cette figurine présente Catwoman en combinaison noire élégante avec lunettes argentées distinctives, représentant son personnage d'anti-héroïne moralement ambiguë. Le design souligne la grâce féline de Catwoman et l'esthétique de voleuse. Un personnage populaire pour les collectionneurs Batman construisant des relations complexes et des personnages de zone grise de Gotham.",
    description_es: "Catwoman - Black Suit and Mask, Silver Goggles trae a Selina Kyle en forma LEGO en atuendo clásico de ladrona felina. Esta figura muestra a Catwoman en elegante traje negro con distintivas gafas plateadas, representando su persona de anti-heroína moralmente ambigua. El diseño enfatiza la gracia felina de Catwoman y estética de ladrona. Un personaje popular para coleccionistas de Batman construyendo relaciones complejas y personajes de área gris de Gotham."
  },
  {
    minifigure_no: 'sh0596',
    description_en: "Bruce Wayne - Black Suit with Dark Red Tie brings Batman's civilian identity to LEGO form. This figure showcases Bruce in formal business attire, representing his billionaire playboy public persona and Wayne Enterprises leadership. The design provides essential civilian representation for storytelling beyond the cowl. A necessary character for Batman collectors building complete Wayne Manor scenes and Bruce's dual identity narratives.",
    description_de: "Bruce Wayne - Black Suit with Dark Red Tie bringt Batmans Zivilidentität in LEGO-Form. Diese Figur präsentiert Bruce in formeller Geschäftskleidung, repräsentiert seine Milliardär-Playboy öffentliche Persona und Wayne Enterprises Führung. Das Design bietet wesentliche zivile Darstellung für Geschichtenerzählung jenseits der Kapuze. Ein notwendiger Charakter für Batman-Sammler, die vollständige Wayne Manor Szenen und Bruces duale Identitäts-Erzählungen aufbauen.",
    description_fr: "Bruce Wayne - Black Suit with Dark Red Tie apporte l'identité civile de Batman en forme LEGO. Cette figurine présente Bruce en tenue d'affaires formelle, représentant son personnage public de milliardaire playboy et le leadership de Wayne Enterprises. Le design fournit une représentation civile essentielle pour la narration au-delà de la cagoule. Un personnage nécessaire pour les collectionneurs Batman construisant des scènes complètes de Wayne Manor et des récits d'identité duale de Bruce.",
    description_es: "Bruce Wayne - Black Suit with Dark Red Tie trae la identidad civil de Batman en forma LEGO. Esta figura muestra a Bruce en vestimenta formal de negocios, representando su persona pública de playboy millonario y liderazgo de Wayne Enterprises. El diseño proporciona representación civil esencial para narrativa más allá de la capucha. Un personaje necesario para coleccionistas de Batman construyendo escenas completas de Wayne Manor y narrativas de identidad dual de Bruce."
  },
  {
    minifigure_no: 'sh0597a',
    description_en: "Maria Rambeau - Black Helmet and Oxygen Mask brings Carol Danvers' best friend to LEGO form from Captain Marvel. This figure showcases the talented pilot in flight gear with helmet and oxygen mask, representing her role as Carol's fellow Air Force pilot. The design emphasizes Maria's military aviation expertise. A significant supporting character for MCU collectors building Captain Marvel cast and Air Force pilot scenes.",
    description_de: "Maria Rambeau - Black Helmet and Oxygen Mask bringt Carol Danvers' beste Freundin in LEGO-Form aus Captain Marvel. Diese Figur präsentiert die talentierte Pilotin in Flugausrüstung mit Helm und Sauerstoffmaske, repräsentiert ihre Rolle als Carols Mitpilotin der Air Force. Das Design betont Marias militärische Luftfahrt-Expertise. Ein bedeutender Nebencharakter für MCU-Sammler, die Captain Marvel Besetzung und Air Force Piloten-Szenen aufbauen.",
    description_fr: "Maria Rambeau - Black Helmet and Oxygen Mask apporte la meilleure amie de Carol Danvers en forme LEGO de Captain Marvel. Cette figurine présente la pilote talentueuse en équipement de vol avec casque et masque à oxygène, représentant son rôle de collègue pilote de l'Air Force de Carol. Le design souligne l'expertise en aviation militaire de Maria. Un personnage secondaire significatif pour les collectionneurs MCU construisant le casting Captain Marvel et des scènes de pilotes de l'Air Force.",
    description_es: "Maria Rambeau - Black Helmet and Oxygen Mask trae a la mejor amiga de Carol Danvers en forma LEGO de Captain Marvel. Esta figura muestra a la talentosa piloto en equipo de vuelo con casco y máscara de oxígeno, representando su papel como compañera piloto de Fuerza Aérea de Carol. El diseño enfatiza la experiencia en aviación militar de Maria. Un personaje de apoyo significativo para coleccionistas MCU construyendo elenco de Captain Marvel y escenas de pilotos de Fuerza Aérea."
  },
  {
    minifigure_no: 'sh0598',
    description_en: "The Joker - Prison Jumpsuit brings the Clown Prince to LEGO form in incarcerated state. This figure showcases the Joker in orange prison jumpsuit, representing his frequent stints in Arkham Asylum and Gotham prisons. The design captures Joker's inability to stay contained. A practical variant for Batman collectors building prison break scenarios and Arkham Asylum scenes.",
    description_de: "The Joker - Prison Jumpsuit bringt den Clown Prince in LEGO-Form im inhaftierten Zustand. Diese Figur präsentiert den Joker in orangenem Gefängnisoverall, repräsentiert seine häufigen Aufenthalte in Arkham Asylum und Gotham-Gefängnissen. Das Design erfasst Jokers Unfähigkeit, eingesperrt zu bleiben. Eine praktische Variante für Batman-Sammler, die Gefängnisausbruchs-Szenarien und Arkham Asylum Szenen aufbauen.",
    description_fr: "The Joker - Prison Jumpsuit apporte le Clown Prince en forme LEGO en état d'incarcération. Cette figurine présente le Joker en combinaison de prison orange, représentant ses séjours fréquents à Arkham Asylum et dans les prisons de Gotham. Le design capture l'incapacité du Joker à rester contenu. Une variante pratique pour les collectionneurs Batman construisant des scénarios d'évasion de prison et des scènes d'Arkham Asylum.",
    description_es: "The Joker - Prison Jumpsuit trae al Príncipe Payaso en forma LEGO en estado encarcelado. Esta figura muestra al Joker en mono de prisión naranja, representando sus frecuentes estadías en Arkham Asylum y prisiones de Gotham. El diseño captura la incapacidad del Joker para permanecer contenido. Una variante práctica para coleccionistas de Batman construyendo escenarios de fuga de prisión y escenas de Arkham Asylum."
  },
  {
    minifigure_no: 'sh0599',
    description_en: "Harley Quinn - Prison Jumpsuit brings the Clown Princess to LEGO form in incarcerated state. This figure showcases Harley in orange prison jumpsuit, representing her time behind bars between criminal escapades with the Joker. The design captures Harley's rebellious spirit even in captivity. A practical variant for Batman collectors building prison scenarios and Harley's criminal history.",
    description_de: "Harley Quinn - Prison Jumpsuit bringt die Clown Princess in LEGO-Form im inhaftierten Zustand. Diese Figur präsentiert Harley in orangenem Gefängnisoverall, repräsentiert ihre Zeit hinter Gittern zwischen kriminellen Eskapaden mit dem Joker. Das Design erfasst Harleys rebellischen Geist sogar in Gefangenschaft. Eine praktische Variante für Batman-Sammler, die Gefängnisszenarien und Harleys kriminelle Geschichte aufbauen.",
    description_fr: "Harley Quinn - Prison Jumpsuit apporte la Clown Princess en forme LEGO en état d'incarcération. Cette figurine présente Harley en combinaison de prison orange, représentant son temps derrière les barreaux entre les escapades criminelles avec le Joker. Le design capture l'esprit rebelle de Harley même en captivité. Une variante pratique pour les collectionneurs Batman construisant des scénarios de prison et l'histoire criminelle de Harley.",
    description_es: "Harley Quinn - Prison Jumpsuit trae a la Princesa Payaso en forma LEGO en estado encarcelado. Esta figura muestra a Harley en mono de prisión naranja, representando su tiempo tras las rejas entre escapadas criminales con el Joker. El diseño captura el espíritu rebelde de Harley incluso en cautiverio. Una variante práctica para coleccionistas de Batman construyendo escenarios de prisión e historia criminal de Harley."
  },
  {
    minifigure_no: 'sh0600',
    description_en: "Prison Guard provides essential security personnel for Gotham correctional facility scenes. This figure represents the brave guards attempting to contain Gotham's most dangerous criminals in prisons and Arkham Asylum. The design emphasizes professional correctional officer appearance. A practical civilian for Batman collectors building complete prison environments and breakout scenarios.",
    description_de: "Prison Guard bietet wesentliches Sicherheitspersonal für Gotham-Justizvollzugsanstalts-Szenen. Diese Figur repräsentiert die tapferen Wachen, die versuchen, Gothams gefährlichste Kriminelle in Gefängnissen und Arkham Asylum einzusperren. Das Design betont professionelles Justizvollzugsbeamten-Erscheinungsbild. Ein praktischer Zivilist für Batman-Sammler, die vollständige Gefängnisumgebungen und Ausbruchs-Szenarien aufbauen.",
    description_fr: "Prison Guard fournit le personnel de sécurité essentiel pour les scènes de l'établissement correctionnel de Gotham. Cette figurine représente les gardes courageux tentant de contenir les criminels les plus dangereux de Gotham dans les prisons et Arkham Asylum. Le design souligne l'apparence professionnelle d'agent correctionnel. Un civil pratique pour les collectionneurs Batman construisant des environnements de prison complets et des scénarios d'évasion.",
    description_es: "Prison Guard proporciona personal de seguridad esencial para escenas de instalación correccional de Gotham. Esta figura representa a los valientes guardias intentando contener a los criminales más peligrosos de Gotham en prisiones y Arkham Asylum. El diseño enfatiza apariencia profesional de oficial correccional. Un civil práctico para coleccionistas de Batman construyendo ambientes de prisión completos y escenarios de fuga."
  }
];

async function main() {
  console.log(`🦸 Starting Super Heroes batch sh0576-sh0600 (${descriptions.length} minifigs)...\n`);

  for (let i = 0; i < descriptions.length; i++) {
    const desc = descriptions[i];

    await prisma.minifigCatalog.update({
      where: { minifigure_no: desc.minifigure_no },
      data: {
        description_en: desc.description_en,
        description_de: desc.description_de,
        description_fr: desc.description_fr,
        description_es: desc.description_es,
        description_generated_at: new Date(),
        description_status: 'completed'
      }
    });

    console.log(`✓ Saved ${desc.minifigure_no} (${i + 1}/${descriptions.length})`);
  }

  console.log(`\n✅ Batch complete! ${descriptions.length} minifigs saved. Total: 600 done.`);
  await prisma.$disconnect();
}

main().catch(async (e) => {
  console.error('Error:', e);
  await prisma.$disconnect();
  process.exit(1);
});
