import { PrismaClient as PrismaClientHostinger } from '@prisma/client';

const prisma = new PrismaClientHostinger({
  datasources: {
    db: {
      url: "mysql://u493602047_figtracker_use:Legocatelogstuff12345!@srv1777.hstgr.io:3306/u493602047_figtracker"
    }
  }
});

const descriptions = [
  {
    minifigure_no: 'sh0601',
    description_en: "Maria Hill appears in her tactical S.H.I.E.L.D. operations outfit with black jacket over light gray shirt and dark blue pants. As Nick Fury's trusted deputy director, she coordinated critical missions throughout the Avengers' operations. This professional civilian appearance captures her role during field assignments rather than in uniform. Essential for S.H.I.E.L.D. headquarters displays and Avengers team collections.",
    description_de: "Maria Hill erscheint in ihrem taktischen S.H.I.E.L.D.-Einsatzoutfit mit schwarzer Jacke über hellgrauem Hemd und dunkelblauen Hosen. Als vertraute stellvertretende Direktorin von Nick Fury koordinierte sie kritische Missionen während der Operationen der Avengers. Dieses professionelle zivile Erscheinungsbild fängt ihre Rolle während Feldeinsätzen statt in Uniform ein. Unverzichtbar für S.H.I.E.L.D.-Hauptquartier-Displays und Avengers-Team-Sammlungen.",
    description_fr: "Maria Hill apparaît dans sa tenue tactique d'opérations S.H.I.E.L.D. avec veste noire sur chemise gris clair et pantalon bleu foncé. En tant que directrice adjointe de confiance de Nick Fury, elle a coordonné des missions critiques tout au long des opérations des Avengers. Cette apparence civile professionnelle capture son rôle lors de missions sur le terrain plutôt qu'en uniforme. Essentielle pour les présentations du quartier général du S.H.I.E.L.D. et les collections d'équipes Avengers.",
    description_es: "Maria Hill aparece con su atuendo táctico de operaciones de S.H.I.E.L.D. con chaqueta negra sobre camisa gris claro y pantalones azul oscuro. Como subdirectora de confianza de Nick Fury, coordinó misiones críticas durante las operaciones de los Avengers. Esta apariencia civil profesional captura su papel durante asignaciones de campo en lugar de uniforme. Esencial para exhibiciones del cuartel general de S.H.I.E.L.D. y colecciones del equipo Avengers."
  },
  {
    minifigure_no: 'sh0602',
    description_en: "Ned Leeds appears as Peter Parker's loyal best friend in his casual dark red plaid shirt and dark blue pants. As the Guy in the Chair who provided crucial computer assistance to Spider-Man, Ned became an invaluable part of the hero's support team. This civilian appearance represents his role before discovering Peter's secret identity. Perfect for recreating high school and tech support scenes from Spider-Man: Homecoming.",
    description_de: "Ned Leeds erscheint als Peter Parkers treuer bester Freund in seinem lässigen dunkelroten karierten Hemd und dunkelblauen Hosen. Als der Mann im Stuhl, der Spider-Man entscheidende Computer-Unterstützung lieferte, wurde Ned ein unverzichtbarer Teil des Support-Teams des Helden. Dieses zivile Erscheinungsbild repräsentiert seine Rolle, bevor er Peters geheime Identität entdeckte. Perfekt zum Nachstellen von Highschool- und Tech-Support-Szenen aus Spider-Man: Homecoming.",
    description_fr: "Ned Leeds apparaît comme le meilleur ami fidèle de Peter Parker dans sa chemise à carreaux rouge foncé décontractée et son pantalon bleu foncé. En tant que Gars dans la Chaise qui fournissait une assistance informatique cruciale à Spider-Man, Ned est devenu une partie inestimable de l'équipe de soutien du héros. Cette apparence civile représente son rôle avant de découvrir l'identité secrète de Peter. Parfait pour recréer les scènes de lycée et de support technique de Spider-Man: Homecoming.",
    description_es: "Ned Leeds aparece como el leal mejor amigo de Peter Parker con su camisa a cuadros rojo oscuro casual y pantalones azul oscuro. Como el Chico en la Silla que proporcionó asistencia informática crucial a Spider-Man, Ned se convirtió en una parte invaluable del equipo de apoyo del héroe. Esta apariencia civil representa su papel antes de descubrir la identidad secreta de Peter. Perfecto para recrear escenas de la escuela secundaria y soporte técnico de Spider-Man: Homecoming."
  },
  {
    minifigure_no: 'sh0603',
    description_en: "PS4 Spider-Man swings into action wearing the iconic white spider suit from Marvel's Spider-Man video game. This Comic-Con 2019 exclusive celebrates one of gaming's most beloved superhero experiences with its distinctive white spider emblem and sleek design. The game-accurate appearance captures the Advanced Suit's modern aesthetic that redefined Spider-Man's look for a new generation. Highly collectible convention exclusive sought after by both LEGO and gaming fans.",
    description_de: "PS4 Spider-Man schwingt sich in seinem ikonischen weißen Spider-Anzug aus Marvels Spider-Man-Videospiel in Action. Dieses Comic-Con 2019-Exklusivstück feiert eines der beliebtesten Superhelden-Spielerlebnisse mit seinem charakteristischen weißen Spider-Emblem und schlanken Design. Das spielgenaue Erscheinungsbild fängt die moderne Ästhetik des Advanced Suit ein, der Spider-Mans Look für eine neue Generation neu definierte. Sehr begehrtes Convention-Exklusivstück, das sowohl von LEGO- als auch von Gaming-Fans gesucht wird.",
    description_fr: "PS4 Spider-Man se lance dans l'action portant le costume d'araignée blanc iconique du jeu vidéo Marvel's Spider-Man. Cette exclusivité Comic-Con 2019 célèbre l'une des expériences de super-héros les plus appréciées du jeu vidéo avec son emblème d'araignée blanc distinctif et son design élégant. L'apparence fidèle au jeu capture l'esthétique moderne du Advanced Suit qui a redéfini le look de Spider-Man pour une nouvelle génération. Exclusivité de convention hautement collectionnable recherchée par les fans de LEGO et de jeux vidéo.",
    description_es: "PS4 Spider-Man entra en acción vistiendo el icónico traje de araña blanco del videojuego Marvel's Spider-Man. Este exclusivo de Comic-Con 2019 celebra una de las experiencias de superhéroes más queridas de los videojuegos con su distintivo emblema de araña blanco y diseño elegante. La apariencia fiel al juego captura la estética moderna del Advanced Suit que redefinió el aspecto de Spider-Man para una nueva generación. Exclusivo de convención altamente coleccionable buscado por fanáticos de LEGO y videojuegos."
  },
  {
    minifigure_no: 'sh0604',
    description_en: "Zebra Batman brings bold black and white stripes to the Dark Knight's arsenal in this eye-catching Comic-Con 2019 exclusive variant. This wild tribute to Batman's 80th anniversary combines crime-fighting functionality with impossible-to-miss zebra pattern camouflage. The striking design references various alternate costumes from comic book history while creating something entirely unique. Convention exclusive that stands out in any Batman collection with its unforgettable pattern.",
    description_de: "Zebra Batman bringt kühne schwarz-weiße Streifen in das Arsenal des Dunklen Ritters in dieser auffälligen Comic-Con 2019-Exklusivvariante. Diese wilde Hommage an Batmans 80. Jubiläum kombiniert Verbrechensbekämpfungsfunktionalität mit unmöglich zu übersehendem Zebramuster-Camouflage. Das markante Design verweist auf verschiedene alternative Kostüme aus der Comic-Geschichte, während es etwas völlig Einzigartiges schafft. Convention-Exklusivstück, das in jeder Batman-Sammlung mit seinem unvergesslichen Muster hervorsticht.",
    description_fr: "Zebra Batman apporte des rayures noires et blanches audacieuses à l'arsenal du Chevalier Noir dans cette variante exclusive Comic-Con 2019 accrocheuse. Cet hommage sauvage au 80e anniversaire de Batman combine fonctionnalité de lutte contre le crime avec camouflage à motif zèbre impossible à manquer. Le design saisissant fait référence à divers costumes alternatifs de l'histoire de la bande dessinée tout en créant quelque chose d'entièrement unique. Exclusivité de convention qui se démarque dans toute collection Batman avec son motif inoubliable.",
    description_es: "Zebra Batman trae audaces rayas blancas y negras al arsenal del Caballero Oscuro en esta llamativa variante exclusiva de Comic-Con 2019. Este salvaje tributo al 80 aniversario de Batman combina funcionalidad de lucha contra el crimen con camuflaje de patrón de cebra imposible de pasar por alto. El diseño llamativo hace referencia a varios trajes alternativos de la historia del cómic mientras crea algo completamente único. Exclusivo de convención que destaca en cualquier colección de Batman con su patrón inolvidable."
  },
  {
    minifigure_no: 'sh0605',
    description_en: "Captain Marvel appears as Vers in her distinctive Kree Starforce uniform before recovering her full memories as Carol Danvers. This teal and silver outfit represents her time serving with the elite alien military unit, complete with Starforce insignia. The design captures her journey from Kree warrior to Earth's mightiest hero in Captain Marvel. Key figure for displaying Carol's origin story and Starforce team lineup.",
    description_de: "Captain Marvel erscheint als Vers in ihrer charakteristischen Kree-Starforce-Uniform, bevor sie ihre vollständigen Erinnerungen als Carol Danvers wiedererlangte. Dieses türkisfarbene und silberne Outfit repräsentiert ihre Zeit im Dienst der Elite-Alien-Militäreinheit, komplett mit Starforce-Insignien. Das Design fängt ihre Reise von der Kree-Kriegerin zu Earths mächtigster Heldin in Captain Marvel ein. Schlüsselfigur für die Darstellung von Carols Ursprungsgeschichte und Starforce-Team-Aufstellung.",
    description_fr: "Captain Marvel apparaît comme Vers dans son uniforme distinctif de Kree Starforce avant de récupérer ses souvenirs complets en tant que Carol Danvers. Cette tenue turquoise et argent représente son temps au service de l'unité militaire extraterrestre d'élite, avec insignes Starforce. Le design capture son parcours de guerrière Kree au héros le plus puissant de la Terre dans Captain Marvel. Figure clé pour afficher l'histoire d'origine de Carol et l'alignement de l'équipe Starforce.",
    description_es: "Captain Marvel aparece como Vers en su distintivo uniforme de Kree Starforce antes de recuperar sus recuerdos completos como Carol Danvers. Este atuendo turquesa y plateado representa su tiempo sirviendo con la unidad militar alienígena de élite, completo con insignias de Starforce. El diseño captura su viaje de guerrera Kree a la heroína más poderosa de la Tierra en Captain Marvel. Figura clave para exhibir la historia de origen de Carol y la alineación del equipo Starforce."
  },
  {
    minifigure_no: 'sh0606',
    description_en: "Happy Hogan appears as Tony Stark's loyal head of security and trusted friend in his professional business attire. From bodyguard to executive, Happy's journey through the MCU showcased his unwavering dedication to protecting Tony and later Peter Parker. This civilian appearance represents his role managing Stark Industries security operations. Essential for Iron Man workshop scenes and Spider-Man mentorship displays.",
    description_de: "Happy Hogan erscheint als Tony Starks treuer Sicherheitschef und vertrauenswürdiger Freund in seiner professionellen Geschäftskleidung. Vom Bodyguard zum Führungskraft zeigte Happys Reise durch das MCU seine unerschütterliche Hingabe, Tony und später Peter Parker zu beschützen. Dieses zivile Erscheinungsbild repräsentiert seine Rolle beim Management der Sicherheitsoperationen von Stark Industries. Unverzichtbar für Iron Man-Werkstattszenen und Spider-Man-Mentorship-Displays.",
    description_fr: "Happy Hogan apparaît comme le chef de sécurité loyal et ami de confiance de Tony Stark dans sa tenue professionnelle d'affaires. De garde du corps à cadre, le parcours de Happy à travers le MCU a mis en valeur son dévouement indéfectible à protéger Tony et plus tard Peter Parker. Cette apparence civile représente son rôle dans la gestion des opérations de sécurité de Stark Industries. Essentiel pour les scènes d'atelier d'Iron Man et les présentations de mentorat de Spider-Man.",
    description_es: "Happy Hogan aparece como el leal jefe de seguridad y amigo de confianza de Tony Stark en su atuendo profesional de negocios. De guardaespaldas a ejecutivo, el viaje de Happy a través del MCU mostró su dedicación inquebrantable para proteger a Tony y más tarde a Peter Parker. Esta apariencia civil representa su papel gestionando las operaciones de seguridad de Stark Industries. Esencial para escenas del taller de Iron Man y exhibiciones de mentoría de Spider-Man."
  },
  {
    minifigure_no: 'sh0607',
    description_en: "Batman makes his triumphant return in the iconic 1989 Tim Burton film costume with integrated cowl and cape featuring the complex bat logo. This groundbreaking design revolutionized superhero movies with its dark, gothic aesthetic and serious tone. The detailed torso printing captures Michael Keaton's unforgettable portrayal that defined Batman for an entire generation. Highly sought after by collectors celebrating the film's cultural impact and timeless style.",
    description_de: "Batman kehrt triumphierend im ikonischen Kostüm des Tim Burton-Films von 1989 mit integrierter Kapuze und Cape mit komplexem Bat-Logo zurück. Dieses bahnbrechende Design revolutionierte Superheldenfilme mit seiner dunklen, gotischen Ästhetik und ernsten Ton. Der detaillierte Torso-Druck fängt Michael Keatons unvergessliche Darstellung ein, die Batman für eine ganze Generation definierte. Sehr begehrt von Sammlern, die den kulturellen Einfluss und zeitlosen Stil des Films feiern.",
    description_fr: "Batman fait son retour triomphal dans le costume iconique du film de Tim Burton de 1989 avec cagoule et cape intégrées présentant le logo complexe de chauve-souris. Ce design révolutionnaire a révolutionné les films de super-héros avec son esthétique sombre et gothique et son ton sérieux. L'impression détaillée du torse capture l'interprétation inoubliable de Michael Keaton qui a défini Batman pour toute une génération. Très recherché par les collectionneurs célébrant l'impact culturel et le style intemporel du film.",
    description_es: "Batman hace su regreso triunfal en el icónico traje de la película de Tim Burton de 1989 con capucha y capa integradas con el complejo logo del murciélago. Este diseño innovador revolucionó las películas de superhéroes con su estética oscura y gótica y tono serio. La impresión detallada del torso captura la interpretación inolvidable de Michael Keaton que definió a Batman para toda una generación. Muy buscado por coleccionistas que celebran el impacto cultural y el estilo atemporal de la película."
  },
  {
    minifigure_no: 'sh0608',
    description_en: "The Joker brings chaos and mayhem in his theatrical 1989 appearance with distinctive dark turquoise bow tie and detailed printed legs. Jack Nicholson's legendary performance created an unforgettable villain whose flamboyant style matched his dangerous unpredictability. The vibrant purple suit and printed leg details capture the Joker's transformation from mobster Jack Napier to Gotham's Clown Prince of Crime. Essential villain for completing classic Batman movie displays.",
    description_de: "Der Joker bringt Chaos und Verwüstung in seinem theatralischen 1989-Auftritt mit charakteristischer dunkeltürkiser Fliege und detailliert bedruckten Beinen. Jack Nicholsons legendäre Performance schuf einen unvergesslichen Schurken, dessen extravaganter Stil seiner gefährlichen Unberechenbarkeit entsprach. Der lebendige lila Anzug und bedruckte Beindetails fangen Jokers Transformation vom Gangster Jack Napier zu Gothams Clown Prince of Crime ein. Unverzichtbarer Schurke für klassische Batman-Film-Displays.",
    description_fr: "Le Joker apporte chaos et pagaille dans son apparence théâtrale de 1989 avec nœud papillon turquoise foncé distinctif et jambes imprimées détaillées. La performance légendaire de Jack Nicholson a créé un méchant inoubliable dont le style flamboyant correspondait à son imprévisibilité dangereuse. Le costume violet vibrant et les détails des jambes imprimées capturent la transformation du Joker du gangster Jack Napier au Prince Clown du Crime de Gotham. Méchant essentiel pour compléter les présentations classiques de films Batman.",
    description_es: "El Joker trae caos y destrucción en su apariencia teatral de 1989 con distintiva corbata de moño turquesa oscuro y piernas impresas detalladas. La legendaria actuación de Jack Nicholson creó un villano inolvidable cuyo estilo extravagante coincidía con su peligrosa impredecibilidad. El vibrante traje púrpura y los detalles de piernas impresas capturan la transformación del Joker del mafioso Jack Napier al Príncipe Payaso del Crimen de Gotham. Villano esencial para completar exhibiciones clásicas de películas de Batman."
  },
  {
    minifigure_no: 'sh0609',
    description_en: "Vicki Vale appears as the intrepid photojournalist whose investigation into Batman's identity drove the plot of the 1989 film. Kim Basinger's portrayal brought intelligence and determination to the role beyond typical damsel-in-distress expectations. This minifigure captures her professional appearance while documenting Gotham's mysterious vigilante and dangerous criminal underworld. Essential civilian character for recreating classic Batman movie moments and photo shoot scenes.",
    description_de: "Vicki Vale erscheint als unerschrockene Fotojournalistin, deren Untersuchung von Batmans Identität die Handlung des Films von 1989 vorantrieb. Kim Basingers Darstellung brachte Intelligenz und Entschlossenheit in die Rolle jenseits typischer Jungfrau-in-Not-Erwartungen. Diese Minifigur fängt ihr professionelles Erscheinungsbild ein, während sie Gothams mysteriösen Vigilanten und gefährliche kriminelle Unterwelt dokumentiert. Unverzichtbare zivile Figur zum Nachstellen klassischer Batman-Film-Momente und Fotoshooting-Szenen.",
    description_fr: "Vicki Vale apparaît comme la photojournaliste intrépide dont l'enquête sur l'identité de Batman a conduit l'intrigue du film de 1989. L'interprétation de Kim Basinger a apporté intelligence et détermination au rôle au-delà des attentes typiques de demoiselle en détresse. Cette minifigurine capture son apparence professionnelle tout en documentant le justicier mystérieux de Gotham et le monde criminel dangereux. Personnage civil essentiel pour recréer les moments classiques du film Batman et les scènes de séances photo.",
    description_es: "Vicki Vale aparece como la intrépida fotoperiodista cuya investigación sobre la identidad de Batman impulsó la trama de la película de 1989. La interpretación de Kim Basinger aportó inteligencia y determinación al papel más allá de las expectativas típicas de damisela en apuros. Esta minifigura captura su apariencia profesional mientras documenta al misterioso vigilante de Gotham y el peligroso submundo criminal. Personaje civil esencial para recrear momentos clásicos de películas de Batman y escenas de sesiones fotográficas."
  },
  {
    minifigure_no: 'sh0610',
    description_en: "Rescue emerges as Pepper Potts' superhero identity wearing the distinctive dark purple armor designed by Tony Stark. This powerful suit allows Pepper to fight alongside the Avengers during the final battle against Thanos in Endgame. The sleek design combines elegance with formidable weaponry, representing Pepper's evolution from CEO to armored hero. Essential for completing Avengers Endgame battle displays and Stark family collection.",
    description_de: "Rescue taucht als Pepper Potts' Superhelden-Identität in der charakteristischen dunkellila Rüstung auf, die von Tony Stark entworfen wurde. Dieser mächtige Anzug ermöglicht es Pepper, während der finalen Schlacht gegen Thanos in Endgame an der Seite der Avengers zu kämpfen. Das schlanke Design kombiniert Eleganz mit gewaltigen Waffen und repräsentiert Peppers Entwicklung von der CEO zur gepanzerten Heldin. Unverzichtbar für Avengers Endgame-Kampf-Displays und Stark-Familien-Sammlungen.",
    description_fr: "Rescue émerge comme l'identité de super-héros de Pepper Potts portant l'armure violet foncé distinctive conçue par Tony Stark. Cette armure puissante permet à Pepper de combattre aux côtés des Avengers lors de la bataille finale contre Thanos dans Endgame. Le design élégant combine élégance et armement formidable, représentant l'évolution de Pepper de PDG à héroïne blindée. Essentiel pour compléter les présentations de bataille Avengers Endgame et la collection de la famille Stark.",
    description_es: "Rescue emerge como la identidad de superhéroe de Pepper Potts vistiendo la distintiva armadura púrpura oscuro diseñada por Tony Stark. Este poderoso traje permite a Pepper luchar junto a los Avengers durante la batalla final contra Thanos en Endgame. El diseño elegante combina elegancia con armamento formidable, representando la evolución de Pepper de CEO a heroína blindada. Esencial para completar exhibiciones de batalla de Avengers Endgame y colección de la familia Stark."
  },
  {
    minifigure_no: 'sh0611',
    description_en: "Hulk appears in his giant form wearing the distinctive white quantum realm jumpsuit from Avengers: Endgame's time heist mission. This Professor Hulk version combines Bruce Banner's intelligence with Hulk's strength, representing the perfect fusion achieved between hero and alter ego. The white suit with red accents marks one of the Avengers' most desperate and important missions to reverse the snap. Essential giant figure for time heist displays and Endgame team collections.",
    description_de: "Hulk erscheint in seiner riesigen Form und trägt den charakteristischen weißen Quantenreich-Jumpsuit aus der Zeitraub-Mission von Avengers: Endgame. Diese Professor Hulk-Version kombiniert Bruce Banners Intelligenz mit Hulks Stärke und repräsentiert die perfekte Fusion zwischen Held und Alter Ego. Der weiße Anzug mit roten Akzenten markiert eine der verzweifeltsten und wichtigsten Missionen der Avengers, um den Snap umzukehren. Unverzichtbare Riesenfigur für Zeitraub-Displays und Endgame-Team-Sammlungen.",
    description_fr: "Hulk apparaît dans sa forme géante portant la combinaison distinctive du royaume quantique blanc de la mission de casse temporel d'Avengers: Endgame. Cette version Professor Hulk combine l'intelligence de Bruce Banner avec la force de Hulk, représentant la fusion parfaite réalisée entre héros et alter ego. Le costume blanc avec accents rouges marque l'une des missions les plus désespérées et importantes des Avengers pour inverser le claquement. Figure géante essentielle pour les présentations de casse temporel et les collections d'équipe Endgame.",
    description_es: "Hulk aparece en su forma gigante vistiendo el distintivo traje blanco del reino cuántico de la misión del robo temporal de Avengers: Endgame. Esta versión de Professor Hulk combina la inteligencia de Bruce Banner con la fuerza de Hulk, representando la fusión perfecta lograda entre héroe y alter ego. El traje blanco con acentos rojos marca una de las misiones más desesperadas e importantes de los Avengers para revertir el chasquido. Figura gigante esencial para exhibiciones del robo temporal y colecciones del equipo Endgame."
  },
  {
    minifigure_no: 'sh0612',
    description_en: "Iron Man soars in another Mark armor variant distinguished by the silver hexagon arc reactor on his chest. This sleek red and gold armor represents Tony Stark's continuous innovation in creating more powerful and efficient suits. The distinctive hexagonal chest piece marks this as one of the later advanced models in his extensive armor collection. Important for displaying the evolution of Iron Man's technology and suit development.",
    description_de: "Iron Man schwebt in einer weiteren Mark-Rüstungsvariante, die sich durch den silbernen Sechseck-Arc-Reaktor auf seiner Brust auszeichnet. Diese schlanke rot-goldene Rüstung repräsentiert Tony Starks kontinuierliche Innovation bei der Entwicklung leistungsfähigerer und effizienterer Anzüge. Das charakteristische sechseckige Bruststück kennzeichnet dies als eines der späteren fortgeschrittenen Modelle in seiner umfangreichen Rüstungssammlung. Wichtig für die Darstellung der Evolution von Iron Mans Technologie und Anzugentwicklung.",
    description_fr: "Iron Man plane dans une autre variante d'armure Mark distinguée par le réacteur arc hexagonal argenté sur sa poitrine. Cette armure rouge et or élégante représente l'innovation continue de Tony Stark dans la création de combinaisons plus puissantes et efficaces. La pièce de poitrine hexagonale distinctive marque celle-ci comme l'un des modèles avancés ultérieurs de sa vaste collection d'armures. Important pour afficher l'évolution de la technologie et du développement de combinaison d'Iron Man.",
    description_es: "Iron Man vuela en otra variante de armadura Mark distinguida por el reactor arc hexagonal plateado en su pecho. Esta elegante armadura roja y dorada representa la innovación continua de Tony Stark en crear trajes más poderosos y eficientes. La distintiva pieza hexagonal del pecho marca esto como uno de los modelos avanzados posteriores en su extensa colección de armaduras. Importante para exhibir la evolución de la tecnología y desarrollo de trajes de Iron Man."
  },
  {
    minifigure_no: 'sh0613',
    description_en: "Thanos appears in his standard minifigure scale wearing the dark blue and gold outfit with pearl gold hands and detailed printed legs. This more accessible scale version of the Mad Titan allows for easier integration with standard LEGO minifigure displays. The distinctive blue armor and gold accents capture his imposing presence while maintaining compatibility with regular building sets. Essential villain for collectors who prefer standard scale Avengers team confrontations.",
    description_de: "Thanos erscheint im Standard-Minifiguren-Maßstab mit dem dunkelblauen und goldenen Outfit mit perlgoldenen Händen und detailliert bedruckten Beinen. Diese zugänglichere Maßstabsversion des Mad Titan ermöglicht eine einfachere Integration in Standard-LEGO-Minifiguren-Displays. Die charakteristische blaue Rüstung und goldenen Akzente fangen seine imposante Präsenz ein, während die Kompatibilität mit regulären Bausets erhalten bleibt. Unverzichtbarer Schurke für Sammler, die Standard-Maßstab-Konfrontationen des Avengers-Teams bevorzugen.",
    description_fr: "Thanos apparaît à l'échelle standard de minifigurine portant la tenue bleu foncé et or avec mains or perlé et jambes imprimées détaillées. Cette version à échelle plus accessible du Mad Titan permet une intégration plus facile avec les présentations standard de minifigurines LEGO. L'armure bleue distinctive et les accents dorés capturent sa présence imposante tout en maintenant la compatibilité avec les ensembles de construction réguliers. Méchant essentiel pour les collectionneurs qui préfèrent les confrontations d'équipe Avengers à échelle standard.",
    description_es: "Thanos aparece en escala de minifigura estándar vistiendo el atuendo azul oscuro y dorado con manos doradas perladas y piernas impresas detalladas. Esta versión a escala más accesible del Titán Loco permite una integración más fácil con exhibiciones estándar de minifiguras LEGO. La distintiva armadura azul y acentos dorados capturan su presencia imponente mientras mantiene compatibilidad con sets de construcción regulares. Villano esencial para coleccionistas que prefieren confrontaciones del equipo Avengers a escala estándar."
  },
  {
    minifigure_no: 'sh0614',
    description_en: "Spider-Man Noir swings from the shadows in his distinctive black and white costume from the noir universe. This darker, grittier version of Spider-Man operates in a 1930s Great Depression setting where Peter Parker fights organized crime with detective skills and web-slinging action. The monochrome design and vintage aesthetic made this character a standout in Into the Spider-Verse. Highly sought after for Spider-Verse displays and alternate universe Spider-Man collections.",
    description_de: "Spider-Man Noir schwingt sich aus den Schatten in seinem charakteristischen schwarz-weißen Kostüm aus dem Noir-Universum. Diese dunklere, härtere Version von Spider-Man operiert in einem Setting der Großen Depression der 1930er Jahre, in dem Peter Parker mit Detektivfähigkeiten und Spinnennetz-Action das organisierte Verbrechen bekämpft. Das monochrome Design und die Vintage-Ästhetik machten diese Figur zu einem Highlight in Into the Spider-Verse. Sehr begehrt für Spider-Verse-Displays und alternative Universum-Spider-Man-Sammlungen.",
    description_fr: "Spider-Man Noir se balance depuis les ombres dans son costume noir et blanc distinctif de l'univers noir. Cette version plus sombre et plus rugueuse de Spider-Man opère dans un cadre de la Grande Dépression des années 1930 où Peter Parker combat le crime organisé avec des compétences de détective et de l'action de lancement de toile. Le design monochrome et l'esthétique vintage ont fait de ce personnage un point culminant dans Into the Spider-Verse. Très recherché pour les présentations Spider-Verse et les collections de Spider-Man d'univers alternatif.",
    description_es: "Spider-Man Noir se balancea desde las sombras en su distintivo traje blanco y negro del universo noir. Esta versión más oscura y más dura de Spider-Man opera en un escenario de la Gran Depresión de los años 1930 donde Peter Parker lucha contra el crimen organizado con habilidades de detective y acción de lanzamiento de telarañas. El diseño monocromo y la estética vintage hicieron de este personaje un punto destacado en Into the Spider-Verse. Muy buscado para exhibiciones de Spider-Verse y colecciones de Spider-Man de universo alternativo."
  },
  {
    minifigure_no: 'sh0615',
    description_en: "Spider-Girl leaps into action in her striking black and white costume representing one of the many spider-powered heroes across the multiverse. This variant brings fresh energy to the spider-hero legacy with distinctive costume design and youthful enthusiasm. The bold black and white color scheme creates strong visual contrast perfect for dynamic action displays. Great addition for collectors building comprehensive Spider-Verse and alternate spider-hero collections.",
    description_de: "Spider-Girl springt in ihrem auffälligen schwarz-weißen Kostüm in Action, das eine der vielen spinnengetriebenen Heldinnen im Multiversum repräsentiert. Diese Variante bringt frische Energie in das Spider-Hero-Erbe mit charakteristischem Kostümdesign und jugendlichem Enthusiasmus. Das kühne schwarz-weiße Farbschema schafft starken visuellen Kontrast, perfekt für dynamische Action-Displays. Tolle Ergänzung für Sammler, die umfassende Spider-Verse- und alternative Spider-Hero-Sammlungen aufbauen.",
    description_fr: "Spider-Girl bondit dans l'action dans son costume noir et blanc saisissant représentant l'une des nombreuses héroïnes dotées de pouvoirs d'araignée à travers le multivers. Cette variante apporte une énergie fraîche à l'héritage des héros araignées avec un design de costume distinctif et un enthousiasme juvénile. Le schéma de couleurs noir et blanc audacieux crée un contraste visuel fort parfait pour les présentations d'action dynamiques. Excellent ajout pour les collectionneurs construisant des collections complètes Spider-Verse et de héros araignées alternatifs.",
    description_es: "Spider-Girl salta a la acción en su llamativo traje blanco y negro que representa a una de las muchas heroínas con poderes de araña a través del multiverso. Esta variante aporta energía fresca al legado de héroes araña con diseño de traje distintivo y entusiasmo juvenil. El audaz esquema de colores blanco y negro crea un fuerte contraste visual perfecto para exhibiciones de acción dinámica. Gran adición para coleccionistas que construyen colecciones completas de Spider-Verse y héroes araña alternativos."
  },
  {
    minifigure_no: 'sh0616',
    description_en: "Doctor Octopus emerges as one of Spider-Man's most dangerous foes with his green outfit and four long mechanical arms ready for battle. Otto Octavius transformed from brilliant scientist to super-villain after his fusion-reactor accident permanently bonded the tentacles to his body. The mechanical arms with detailed printing showcase Doc Ock's genius-level intellect turned to criminal schemes. Essential villain for Spider-Man rogues gallery and laboratory confrontation displays.",
    description_de: "Doctor Octopus taucht als einer der gefährlichsten Feinde von Spider-Man mit seinem grünen Outfit und vier langen mechanischen Armen kampfbereit auf. Otto Octavius verwandelte sich von brillantem Wissenschaftler zum Superschurken, nachdem sein Fusionsreaktor-Unfall die Tentakel dauerhaft mit seinem Körper verband. Die mechanischen Arme mit detailliertem Druck zeigen Doc Ocks Intelligenz auf Genie-Niveau, die sich kriminellen Machenschaften zugewandt hat. Unverzichtbarer Schurke für Spider-Mans Schurkengalerie und Labor-Konfrontations-Displays.",
    description_fr: "Doctor Octopus émerge comme l'un des ennemis les plus dangereux de Spider-Man avec sa tenue verte et quatre longs bras mécaniques prêts au combat. Otto Octavius s'est transformé de brillant scientifique en super-vilain après que son accident de réacteur à fusion a lié en permanence les tentacules à son corps. Les bras mécaniques avec impression détaillée mettent en valeur l'intellect de niveau génie de Doc Ock tourné vers des plans criminels. Méchant essentiel pour la galerie de méchants de Spider-Man et les présentations de confrontation de laboratoire.",
    description_es: "Doctor Octopus emerge como uno de los enemigos más peligrosos de Spider-Man con su atuendo verde y cuatro largos brazos mecánicos listos para la batalla. Otto Octavius se transformó de brillante científico a supervillano después de que su accidente de reactor de fusión unió permanentemente los tentáculos a su cuerpo. Los brazos mecánicos con impresión detallada muestran el intelecto de nivel genio de Doc Ock volcado a esquemas criminales. Villano esencial para la galería de villanos de Spider-Man y exhibiciones de confrontación de laboratorio."
  },
  {
    minifigure_no: 'sh0617',
    description_en: "The Armored Truck Driver appears in full security gear with protective helmet, ready to defend valuable cargo from super-powered threats. This civilian security professional represents the everyday workers caught in the crossfire between heroes and villains in Marvel's urban battles. The detailed uniform and helmet showcase the practical protective equipment needed in a world with super-criminals. Perfect for heist scenes, bank robbery displays, and street-level action scenarios.",
    description_de: "Der gepanzerte Truck-Fahrer erscheint in voller Sicherheitsausrüstung mit Schutzhelm, bereit, wertvolle Fracht vor superbewaffneten Bedrohungen zu verteidigen. Dieser zivile Sicherheitsprofi repräsentiert die alltäglichen Arbeiter, die im Kreuzfeuer zwischen Helden und Schurken in Marvels urbanen Kämpfen gefangen sind. Die detaillierte Uniform und der Helm zeigen die praktische Schutzausrüstung, die in einer Welt mit Superkriminellen benötigt wird. Perfekt für Raubszenen, Bankraub-Displays und Action-Szenarien auf Straßenniveau.",
    description_fr: "Le conducteur de camion blindé apparaît en équipement de sécurité complet avec casque de protection, prêt à défendre une cargaison précieuse contre des menaces dotées de super-pouvoirs. Ce professionnel de la sécurité civile représente les travailleurs quotidiens pris entre deux feux entre héros et méchants dans les batailles urbaines de Marvel. L'uniforme détaillé et le casque mettent en valeur l'équipement de protection pratique nécessaire dans un monde avec des super-criminels. Parfait pour les scènes de braquage, les présentations de vol de banque et les scénarios d'action au niveau de la rue.",
    description_es: "El conductor de camión blindado aparece con equipo de seguridad completo con casco protector, listo para defender carga valiosa de amenazas con superpoderes. Este profesional de seguridad civil representa a los trabajadores cotidianos atrapados en el fuego cruzado entre héroes y villanos en las batallas urbanas de Marvel. El uniforme detallado y el casco muestran el equipo de protección práctica necesario en un mundo con supercriminales. Perfecto para escenas de atraco, exhibiciones de robo de bancos y escenarios de acción a nivel de calle."
  },
  {
    minifigure_no: 'sh0618',
    description_en: "The Vulture soars as one of Spider-Man's oldest and most persistent adversaries with his distinctive winged flight suit and predatory design. Adrian Toomes used his brilliant engineering skills to create the electromagnetic harness that allows him to fly and grants enhanced strength. The angular wing design and menacing appearance capture the aerial threat this villain poses to the wall-crawler. Essential for Spider-Man Homecoming displays and classic rogues gallery collections.",
    description_de: "Der Vulture schwebt als einer der ältesten und hartnäckigsten Gegner von Spider-Man mit seinem charakteristischen geflügelten Fluganzug und räuberischem Design. Adrian Toomes nutzte seine brillanten Ingenieursfähigkeiten, um das elektromagnetische Geschirr zu schaffen, das ihm das Fliegen ermöglicht und verstärkte Stärke verleiht. Das kantige Flügeldesign und bedrohliche Erscheinungsbild fangen die Luftbedrohung ein, die dieser Schurke für den Wall-Crawler darstellt. Unverzichtbar für Spider-Man Homecoming-Displays und klassische Schurkengalerie-Sammlungen.",
    description_fr: "Le Vautour plane comme l'un des adversaires les plus anciens et les plus persistants de Spider-Man avec sa combinaison de vol ailée distinctive et son design prédateur. Adrian Toomes a utilisé ses brillantes compétences d'ingénierie pour créer le harnais électromagnétique qui lui permet de voler et lui confère une force améliorée. Le design d'aile angulaire et l'apparence menaçante capturent la menace aérienne que ce méchant pose au grimpeur de murs. Essentiel pour les présentations Spider-Man Homecoming et les collections de galerie de méchants classiques.",
    description_es: "The Vulture vuela como uno de los adversarios más antiguos y persistentes de Spider-Man con su distintivo traje de vuelo alado y diseño depredador. Adrian Toomes usó sus brillantes habilidades de ingeniería para crear el arnés electromagnético que le permite volar y le otorga fuerza mejorada. El diseño angular de las alas y la apariencia amenazante capturan la amenaza aérea que este villano representa para el trepador de paredes. Esencial para exhibiciones de Spider-Man Homecoming y colecciones de galería de villanos clásicos."
  },
  {
    minifigure_no: 'sh0620',
    description_en: "Mysterio materializes with his iconic light aqua head visible through the transparent dome helmet, master of illusions and special effects. Quentin Beck used his talents as a Hollywood stuntman and effects expert to create elaborate holographic deceptions that made him one of Spider-Man's most visually spectacular villains. The distinctive fishbowl helmet and dramatic cape capture his theatrical approach to super-villainy. Highly collectible figure from Spider-Man: Far From Home.",
    description_de: "Mysterio materialisiert sich mit seinem ikonischen hellblauen Kopf, der durch den transparenten Kuppelhelm sichtbar ist, Meister der Illusionen und Spezialeffekte. Quentin Beck nutzte seine Talente als Hollywood-Stuntman und Effekt-Experte, um aufwendige holografische Täuschungen zu schaffen, die ihn zu einem der visuell spektakulärsten Schurken von Spider-Man machten. Der charakteristische Fischglas-Helm und dramatische Cape fangen seinen theatralischen Ansatz zur Superschurkenrolle ein. Sehr begehrte Figur aus Spider-Man: Far From Home.",
    description_fr: "Mysterio se matérialise avec sa tête bleu clair aqua iconique visible à travers le casque dôme transparent, maître des illusions et effets spéciaux. Quentin Beck a utilisé ses talents de cascadeur hollywoodien et expert en effets pour créer des tromperies holographiques élaborées qui ont fait de lui l'un des méchants les plus spectaculaires visuellement de Spider-Man. Le casque bocal à poissons distinctif et la cape dramatique capturent son approche théâtrale de la super-vilenie. Figurine hautement collectionnable de Spider-Man: Far From Home.",
    description_es: "Mysterio se materializa con su icónica cabeza azul claro aqua visible a través del casco de cúpula transparente, maestro de ilusiones y efectos especiales. Quentin Beck usó sus talentos como doble de acción de Hollywood y experto en efectos para crear elaborados engaños holográficos que lo convirtieron en uno de los villanos más espectaculares visualmente de Spider-Man. El distintivo casco de pecera y capa dramática capturan su enfoque teatral de la supervillanía. Figura altamente coleccionable de Spider-Man: Far From Home."
  },
  {
    minifigure_no: 'sh0621',
    description_en: "Mr. Freeze emerges in his pearl dark gray cryogenic suit with distinctive neck bracket featuring four angled handles for his freeze technology. Victor Fries became one of Batman's most tragic villains, driven to crime to fund research that might save his terminally ill wife Nora. The specialized containment suit and technical details represent his brilliant cryogenics expertise turned to cold-themed crimes. Essential Batman villain combining sympathetic motivation with formidable ice-based powers.",
    description_de: "Mr. Freeze taucht in seinem perldunkelgrauen kryogenen Anzug mit charakteristischem Halsstück mit vier abgewinkelten Griffen für seine Gefrier-Technologie auf. Victor Fries wurde zu einem der tragischsten Schurken Batmans, getrieben vom Verbrechen, um Forschung zu finanzieren, die seine todkranke Frau Nora retten könnte. Der spezialisierte Eindämmungsanzug und technische Details repräsentieren seine brillante Kryogenik-Expertise, die sich kältethematischen Verbrechen zugewandt hat. Unverzichtbarer Batman-Schurke, der sympathische Motivation mit gewaltigen eisbasierten Kräften kombiniert.",
    description_fr: "Mr. Freeze émerge dans sa combinaison cryogénique gris foncé perlé avec support de cou distinctif comportant quatre poignées angulaires pour sa technologie de congélation. Victor Fries est devenu l'un des méchants les plus tragiques de Batman, poussé au crime pour financer des recherches qui pourraient sauver sa femme en phase terminale Nora. La combinaison de confinement spécialisée et les détails techniques représentent son expertise brillante en cryogénie tournée vers des crimes à thème froid. Méchant Batman essentiel combinant motivation sympathique avec des pouvoirs formidables basés sur la glace.",
    description_es: "Mr. Freeze emerge en su traje criogénico gris oscuro perlado con soporte de cuello distintivo con cuatro manijas angulares para su tecnología de congelación. Victor Fries se convirtió en uno de los villanos más trágicos de Batman, impulsado al crimen para financiar investigación que podría salvar a su esposa en fase terminal Nora. El traje de contención especializado y los detalles técnicos representan su brillante experiencia en criogenia volcada a crímenes de tema frío. Villano esencial de Batman que combina motivación simpática con formidables poderes basados en hielo."
  },
  {
    minifigure_no: 'sh0622',
    description_en: "Black Panther stands ready in his distinctive suit with detailed collar piece, representing T'Challa as both king of Wakanda and Avenger. The vibranium-weave suit provides incredible protection while the panther-themed design honors the sacred tradition of Wakanda's protector. This version features the characteristic collar detail that distinguishes certain appearances of the suit. Essential for MCU displays combining royal authority with superhero action.",
    description_de: "Black Panther steht bereit in seinem charakteristischen Anzug mit detailliertem Kragenstück, das T'Challa sowohl als König von Wakanda als auch als Avenger repräsentiert. Der Vibranium-Gewebe-Anzug bietet unglaublichen Schutz, während das Panther-thematische Design die heilige Tradition von Wakandas Beschützer ehrt. Diese Version weist das charakteristische Kragendetail auf, das bestimmte Erscheinungen des Anzugs auszeichnet. Unverzichtbar für MCU-Displays, die königliche Autorität mit Superhelden-Action kombinieren.",
    description_fr: "Black Panther se tient prêt dans sa combinaison distinctive avec pièce de col détaillée, représentant T'Challa à la fois comme roi du Wakanda et Avenger. La combinaison tissée en vibranium offre une protection incroyable tandis que le design à thème panthère honore la tradition sacrée du protecteur du Wakanda. Cette version présente le détail de col caractéristique qui distingue certaines apparences de la combinaison. Essentiel pour les présentations MCU combinant autorité royale avec action de super-héros.",
    description_es: "Black Panther está listo en su distintivo traje con pieza de cuello detallada, representando a T'Challa como rey de Wakanda y Avenger. El traje tejido de vibranium proporciona protección increíble mientras que el diseño con tema de pantera honra la tradición sagrada del protector de Wakanda. Esta versión presenta el detalle de cuello característico que distingue ciertas apariciones del traje. Esencial para exhibiciones MCU que combinan autoridad real con acción de superhéroe."
  },
  {
    minifigure_no: 'sh0623',
    description_en: "Thor wields his mighty hammer wearing the distinctive spongy-textured cape and pearl dark gray pants from one of his MCU appearances. The God of Thunder's regal bearing and powerful presence make him essential for Avengers team displays. This version's unique cape texture and color scheme distinguish it from other Thor variants. Important for collectors completing comprehensive Asgardian and Avengers collections.",
    description_de: "Thor schwingt seinen mächtigen Hammer und trägt den charakteristischen schwammigen Cape und perldunkelgraue Hosen aus einem seiner MCU-Auftritte. Die königliche Haltung und mächtige Präsenz des Donnergotts machen ihn unverzichtbar für Avengers-Team-Displays. Die einzigartige Cape-Textur und Farbschema dieser Version unterscheiden sie von anderen Thor-Varianten. Wichtig für Sammler, die umfassende asgardische und Avengers-Sammlungen vervollständigen.",
    description_fr: "Thor brandit son puissant marteau portant la cape à texture spongieuse distinctive et le pantalon gris foncé perlé de l'une de ses apparitions MCU. Le port royal et la présence puissante du Dieu du Tonnerre le rendent essentiel pour les présentations d'équipe Avengers. La texture unique de cape et le schéma de couleurs de cette version la distinguent des autres variantes de Thor. Important pour les collectionneurs complétant des collections complètes asgardiennes et Avengers.",
    description_es: "Thor empuña su poderoso martillo vistiendo la distintiva capa de textura esponjosa y pantalones gris oscuro perlado de una de sus apariciones en MCU. El porte real y la poderosa presencia del Dios del Trueno lo hacen esencial para exhibiciones del equipo Avengers. La textura única de capa y el esquema de colores de esta versión la distinguen de otras variantes de Thor. Importante para coleccionistas que completan colecciones completas asgardianas y Avengers."
  },
  {
    minifigure_no: 'sh0624',
    description_en: "The AIM Agent appears in the distinctive yellow hazmat suit uniform of Advanced Idea Mechanics, the terrorist science organization opposing the Avengers. These faceless soldiers of HYDRA's scientific division represent the countless nameless threats heroes face. The bright yellow protective suit with AIM insignia makes these henchmen instantly recognizable. Perfect for army building and recreating scenes where heroes storm AIM facilities and laboratories.",
    description_de: "Der AIM-Agent erscheint in der charakteristischen gelben Hazmat-Anzug-Uniform von Advanced Idea Mechanics, der terroristischen Wissenschaftsorganisation, die sich den Avengers widersetzt. Diese gesichtslosen Soldaten der wissenschaftlichen Abteilung von HYDRA repräsentieren die zahllosen namenlosen Bedrohungen, denen Helden gegenüberstehen. Der leuchtend gelbe Schutzanzug mit AIM-Insignien macht diese Handlanger sofort erkennbar. Perfekt zum Armeeaufbau und Nachstellen von Szenen, in denen Helden AIM-Einrichtungen und Labore stürmen.",
    description_fr: "L'agent AIM apparaît dans l'uniforme distinctif de combinaison hazmat jaune d'Advanced Idea Mechanics, l'organisation scientifique terroriste s'opposant aux Avengers. Ces soldats sans visage de la division scientifique d'HYDRA représentent les innombrables menaces sans nom auxquelles les héros font face. La combinaison de protection jaune vif avec insignes AIM rend ces hommes de main instantanément reconnaissables. Parfait pour la construction d'armée et la recréation de scènes où les héros prennent d'assaut les installations et laboratoires AIM.",
    description_es: "El agente AIM aparece con el distintivo uniforme de traje hazmat amarillo de Advanced Idea Mechanics, la organización científica terrorista que se opone a los Avengers. Estos soldados sin rostro de la división científica de HYDRA representan las innumerables amenazas sin nombre que enfrentan los héroes. El brillante traje de protección amarillo con insignias de AIM hace que estos secuaces sean instantáneamente reconocibles. Perfecto para construcción de ejércitos y recrear escenas donde los héroes asaltan instalaciones y laboratorios de AIM."
  },
  {
    minifigure_no: 'sh0625',
    description_en: "Captain America stands ready in his dark blue stealth suit with black and gray belt, representing Steve Rogers during covert operations. This tactical outfit trades the iconic red, white, and blue for subdued colors better suited for undercover missions. The black hands and detailed belt system showcase the practical, mission-focused design. Essential for displaying Cap's versatility beyond his traditional heroic costume and for stealth mission scenarios.",
    description_de: "Captain America steht bereit in seinem dunkelblauen Stealth-Anzug mit schwarz-grauem Gürtel, der Steve Rogers während verdeckter Operationen repräsentiert. Dieses taktische Outfit tauscht das ikonische Rot, Weiß und Blau gegen gedämpfte Farben, die besser für Undercover-Missionen geeignet sind. Die schwarzen Hände und das detaillierte Gürtelsystem zeigen das praktische, missionsfokussierte Design. Unverzichtbar für die Darstellung von Caps Vielseitigkeit jenseits seines traditionellen Heldenkostüms und für Stealth-Mission-Szenarien.",
    description_fr: "Captain America se tient prêt dans sa combinaison de furtivité bleu foncé avec ceinture noire et grise, représentant Steve Rogers lors d'opérations secrètes. Cette tenue tactique échange le rouge, blanc et bleu iconiques contre des couleurs sobres mieux adaptées aux missions d'infiltration. Les mains noires et le système de ceinture détaillé mettent en valeur le design pratique et axé sur la mission. Essentiel pour afficher la polyvalence de Cap au-delà de son costume héroïque traditionnel et pour les scénarios de mission furtive.",
    description_es: "Captain America está listo en su traje de sigilo azul oscuro con cinturón negro y gris, representando a Steve Rogers durante operaciones encubiertas. Este atuendo táctico cambia el icónico rojo, blanco y azul por colores tenues más adecuados para misiones encubiertas. Las manos negras y el sistema de cinturón detallado muestran el diseño práctico enfocado en la misión. Esencial para exhibir la versatilidad de Cap más allá de su traje heroico tradicional y para escenarios de misión sigilosa."
  }
];

async function main() {
  console.log(`🦸 Starting Super Heroes batch sh0601-sh0625 (${descriptions.length} minifigs)...\n`);

  for (let i = 0; i < descriptions.length; i++) {
    const desc = descriptions[i];

    await prisma.minifigCatalog.update({
      where: { minifigure_no: desc.minifigure_no },
      data: {
        description_en: desc.description_en,
        description_de: desc.description_de,
        description_fr: desc.description_fr,
        description_es: desc.description_es,
        description_generated_at: new Date(),
        description_status: 'completed'
      }
    });

    console.log(`✓ Saved ${desc.minifigure_no} (${i + 1}/${descriptions.length})`);
  }

  console.log(`\n✅ Batch complete! ${descriptions.length} minifigs saved. Total: 625 done.`);
  await prisma.$disconnect();
}

main().catch(async (e) => {
  console.error('Error:', e);
  await prisma.$disconnect();
  process.exit(1);
});
